### ISSUE TITLE
wrong assertion test for wsi->sock

### ISSUE THREAD

**Issue by mhaberler** [warmcat/libwebsockets#10]
the test in https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.c#L116 doesnt make sense

file descriptor 0 is legit after an accept - in particular you will get this if you have a demon-type setup where stdin, stdout stderr are typically closed. The way fd's are recycled you will get fd 0 on first accept after closing stdin.

suggestion: remove or mark an invalid fd as < 0.

**Comment by warmcat** [comment]
You were right.  This got refactored into check against == LWS_INVALID_FILE a while ago.
