### ISSUE TITLE
How to don't send "Sec-WebSocket-Protocol" header

### ISSUE THREAD

**Issue by howardguo** [warmcat/libwebsockets#1001]
Hi, master.
Could you tell me how to disable send "Sec-WebSocket-Protocol" header ? Our server don't want our client to send this header.:).

**Comment by lws-team** [comment]
"master" lol... you can just set `info->protocol` to `NULL` or `""`.

**Comment by howardguo** [comment]
LOL. Other question，the speed of sending and receiving data is too slow. How to speed up the time of sending data?

**Comment by lws-team** [comment]
You need to reformulate that into a question that can be answered, eg, by giving information on exactly what 'too slow' means to you.  Lws doesn't sit on your data, and it will let you send it as fast as the other side can receive it (but no faster).  How big are the packets the client is sending on the wire (by tcpdump / wireshark)?  This and other aspects are under the control of your user code / struct lws_protocols definition... did you look at this before asking me?

**Comment by howardguo** [comment]
Yes. Thank you very much. 👍
