### ISSUE TITLE
Same response for multiple different requests

### ISSUE THREAD

**Issue by pparadzik** [warmcat/libwebsockets#1006]
Hi,

I'm having issues with http file serving because, in certain cases, function `lws_header_table_reset` is not being called, and, as a consequence, multiple different requests would get the same response (http parser flags would not be set to default values, so it would skip the parser part). This happens because, when calling `lws_serve_http_file_fragment` from `lws_server_socket_service`, function `lws_http_transaction_completed` (which, among other things, resets the headers) is not being called if file is completely served.

I "solved" this in the client part by calling `lws_http_transaction_completed` from the `LWS_CALLBACK_HTTP_FILE_COMPLETION` callback. Is this how it's supposed to work or lws is missing some call to reset the headers?

**Comment by lws-team** [comment]
Yes, if you are dealing with it using the old "by hand" http callback stuff, that's something you need to take care of as shown in test-server-http.c

```
	case LWS_CALLBACK_HTTP_FILE_COMPLETION:
		goto try_to_reuse;

...
try_to_reuse:
	if (lws_http_transaction_completed(wsi))
		return -1;

	return 0;
}
```

If all you're really doing is "serving files", you don't have to get involved with the http callback detail.  If you have a look at test-server-v2.0.c, lws handles the file serving by "mounting" a part of your server directory structure somewhere in the server URL space, and handles everything for you.

You can even avoid the code setting up the mounts etc by using lwsws, which is a generic server configured from JSON and your ws protocol provided by runtime-loaded plugins.

**Comment by pparadzik** [comment]
OK, thanks.
