### ISSUE TITLE
missing lws_vhost_user

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#1008]
Hi,
when creating context, it is possible to set the void *user. While when creating vhost, the same structure is used (the lws_context_creation_info) but void *user is ignored and there is no way how to obtain in later. Is there a reason? 

I'm creating some C++ wrapper around the libwebsockets for our own purposes and I'm using those void* to point to our wrapper objects, for lws*, lws_protocols*, lws_context* it is possible, but for lws_vhost* it is not.

Thanks for clarification.

Ondrej

**Comment by lws-team** [comment]
I pushed a patch on master that allows that (via the same info.user used at context creation time) for vhost creation time, along with a matching `void *lws_vhost_user(struct lws_vhost *vhost)`.

A lot if the plugins rely on per-vhost data but they allocate it at plugin init and refer to it in the callback... this is such a common pattern there's even a helper api `lws_protocol_vh_priv_zalloc()` and the allocation is automatically freed by lws when the vhost is destroyed.  But I understand if you want to attach an external object for similar reasons... it's just so far all the user vhost related stuff has been inside vhost protocols.

**Comment by sejvlond** [comment]
Awesome, thanks a lot

**Comment by Sleepingbug** [comment]
lws_protocol_vh_priv_zalloc will alloc new memory , right ? when  will the memory   be free ?
