### ISSUE TITLE
lws_write - how long must the buf survive

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#1009]
In the documentation of `lws_write` there is:

> be sure to allocate valid storage before and after buf as explained above

But then only in some cases the BEFORE space is demanded, I guess the AFTER space is some legacy relic?

And in the case when OS will not accept everything I asked to write on the connection, doc states

> LWS will buffer the remainder automatically, and send it out autonomously.

Does this mean `lws_write` returns some value (which is not the same as requested length) and the `unsigned char *buf` must remain valid? And when I'll be notified about successful/failed sending?

Is it save to have?
```
int WebSocketContext::protocol_callback_function(
    lws *wsi, lws_callback_reasons reason, void *user, void *in, size_t len)
{
    switch (reason) {
    case LWS_CALLBACK_SERVER_WRITEABLE:
        std::string buff(LWS_PRE, ' ');
        buff += "my message to be sent";
        const int len = lws_write(wsi,
                  buff.data() + LWS_PRE,
                  buff.size() - LWS_PRE,
                  LWS_WRITE_BINARY);
        assert(len == buff.size() - LWS_PRE);
        break;
    }    
}
```

**Comment by lws-team** [comment]
Yes, after space was needed for old versions of ws protocol before it was finalized.  Support for those was removed long ago.

You can always destroy / lose the lws_write() buffer immediately on return from there, ie, it can always be on the stack.  You only have to take care about the return being <0, indicating a fatal network situation that you should pass on by asking to close.  Your code needs to deal with that, since the peer can close his end of the connection at any time, not assert on it.  Otherwise for ws lws will always tell it was all sent even if it was partially buffered.  You won't get any more WRITABLE callbacks to user code until is was all sent.

**Comment by sejvlond** [comment]
> Otherwise for ws lws will always tell it was all sent even if it was partially buffered

That means, `lws_write` returns either <0 for errors or exactly `size_t len` which indicates - all have been sent - even if it is internally buffered etc. Never something between 0, len.

**Comment by lws-team** [comment]
All you need to check is the < 0 case.  If it wasn't <0, it's either sent or in the process of being sent, and you won't receive any WRITABLE callback until it's flushed.

**Comment by sejvlond** [comment]
<0 - understood - it is an immediate error

but what about >0 - if it means  "either sent or in the process of being sent" then how should I known if the sending was successful?

I have some queue of messages. When `lws_write` returns >0, I remove the message from queue. If the sending fails silently somewhere in the lws while it buffers, then I loose a message.
Isn't there some callback with successfully sent reason?

**Comment by lws-team** [comment]
No... you have a queue of messages, and you ask for a callback when the wsi is writeable.  When you get the callback, you do the lws_write().  If you have more messages in the queue, you ask for another callback when writeable.

If there are a lot of messages, you can use a pattern like

```
do {
    lws_write(...);
} while (!lws_send_pipe_choked(wsi) && more_messages());
```

in the WRITABLE callback, `lws_send_pipe_choked()` will be true if there was a partial send or POLLOUT is not set on the wsi socket.

While there is a partial send being flushed __you won't get any WRITABLE callbacks__.  So ordering is always enforced.

**Comment by sejvlond** [comment]
> you have a queue of messages, and you ask for a callback when the wsi is writeable. 

Yes

>  If you have more messages in the queue, you ask for another callback when writeable.

Yes, but if I call `lws_write` and it returns something >0, I may think "ok, message was sent" and I remove the message from queue and ask for another callback.
But what if the partial sending fails (it returns >0 and lws starts buffering and sending chunks, and it fails)? Will I be notified?

**Comment by lws-team** [comment]
It can only fail because the connection is dead, actually, we are talking about write() or send() returning a fatal error.  So there will be a logical close done on the wsi and you will get the usual CLOSE callback.

**Comment by sejvlond** [comment]
Yeah, but I won't know if the last message was or wasn't sent. I need to know that, because my (non standard situation, I guess) is:

My server accepts only one client. Messages are queued and sent on WRITABLE callback. If client disconnects, CLOSE callback is received, but the queue preserves. When new client connects, messages from the queue continues to be sent.

This way, I may loose a message, because `lws_write` returns OK and then it fails and returns only CLOSE callback.

**Comment by lws-team** [comment]
Hm... write() or send() accepting your data does not mean it reached the peer.  It's buffered in kernel space and sent according to constraints out of the control of userland.  The kernel may accept it but the peer has already closed, and news did not reach the kernel on your side yet.

Or the peer was dropped into a volcano and will never send or receive anything again, yet your kernel accepted to buffer the send() data and said it was OK.

Successful return from write() or send() does __not__ mean it was sent-and-received.  You need to improve your protocol so when the peer reconnects, he tells the index of the last message he really received and handled.

**Comment by sejvlond** [comment]
Oh... you're right, and now we have a bigger problem :-)

Well, thank you and I guess the lws_write functionality is ok as is.
