### ISSUE TITLE
Stack corruption in calls to socks_generate_msg()

### ISSUE THREAD

**Issue by pierre-emutex** [warmcat/libwebsockets#1010]
in multiple places in lib/client.c and lib/client_handshake.c,

len is declared as a int
socks_generate_msg() expects a " size_t  *  " as third parameter 

			socks_generate_msg(wsi, SOCKS_MSG_CONNECT, (size_t *)&len);

This code creates a stack corruption and depending on compiler, and optimization options, triggers a crash.

**Comment by pierre-emutex** [comment]
When running under gdb, the right place of code ../lib/client.c:544 is shown  (libwebsockets 2.3.0)

```
*** stack smashing detected ***: ?? terminated

Thread 1 "??" received signal SIGABRT, Aborted.
0x00007ffff71d7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007ffff71d7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff71d902a in __GI_abort () at abort.c:89
#2  0x00007ffff72197ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff733145f "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff72bb11c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7ffff7331441 "stack smashing detected")
    at fortify_fail.c:37
#4  0x00007ffff72bb0c0 in __stack_chk_fail () at stack_chk_fail.c:28
#5  0x00007ffff6f91ac9 in lws_client_socket_service (context=context@entry=0x7a4de0, wsi=wsi@entry=0x7d7330,
    pollfd=pollfd@entry=0x7a6508) at ../lib/client.c:544
#6  0x00007ffff6f895ba in lws_service_fd_tsi (context=context@entry=0x7a4de0, pollfd=0x7a6508, tsi=tsi@entry=0)
    at ../lib/service.c:1373
#7  0x00007ffff6f965cb in _lws_plat_service_tsi (context=0x7a4de0, timeout_ms=<optimized out>, tsi=0)
    at ../lib/lws-plat-unix.c:187
#8  0x0000000000444673 in ?? ()
#10 0x000000000041d124 in main ()
(gdb) q
```

And to help understand my settings (linux 64 bits), this example of code shows clearly that "size_t" and "int" do have different sizes. writing *msg_len in socks_generate_msg() writes 8 bytes in the 4 bytes of the len parameters.

```
$ cat tt.c
#include <stdio.h>
int main (int argc, char **argv)
{
  printf("%u %u\n", (unsigned)sizeof(int), (unsigned)sizeof(size_t));
}

$ gcc tt.c
$ ./a.out
4 8
$ 
```

**Comment by lws-team** [comment]
Hmm nasty... it was contributed in ed92b6dfe75ad65a78dadfa4dc96da4568d95d69 but I didn't spot the dodgy casts behind this.  I'll clean it up shortly.

**Comment by pierre-emutex** [comment]
I admit I had fun to find it and locate the right part of code and compiler options. Thanks for your quick response.

**Comment by lws-team** [comment]
Please try the patch on master mentioned above.

**Comment by lws-team** [comment]
Can you also try the next patch on master 32eaf83f24ec4b355add6fa8ffbcc0ef5884f7d1 as well?  I went to clean the related code up and found some error paths that did not give CONNECTION_ERROR callback.  Thanks.

**Comment by pierre-emutex** [comment]
Verified master 32eaf83  "works" for me. Note that you can remove the unnecessary casts, that look to have been the wrong fix when the compiler rightfully complained against mismatched types being used.
