### ISSUE TITLE
MbedTLS Server Certificate Verification

### ISSUE THREAD

**Issue by asherkin** [warmcat/libwebsockets#1011]
Been trying out the new mbedTLS support (on Linux and Windows) for a libwebsockets client and it is all working pretty well, but I've noticed that certificate verification appears to be completely ignored at the moment - pretty much just filing something to keep track of this.

1. `SSL_VERIFY_NONE` is passed to `SSL_set_verify`.
2. `LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION` doesn't get called.

I'm not seeing the `lwsl_notice` in `OpenSSL_client_verify_callback`, which pretty much precludes 2. (and thus doing verification completely in user-code). Tried to trace through the wrapper, but it was not obvious how `verify_mode` and `verify_callback` translates through to mbedTLS.

EDIT: Just a note I forgot, I had to add the following to `ssl_x509.h` to compile with mbedTLS on Windows:
```
#ifdef X509_NAME
#undef X509_NAME
#endif
```
as `X509_NAME` is being pulled in from a random Windows header.

**Comment by lws-team** [comment]
Yeah... the mbedtls shim does not 100% reproduce every api from openssl.  It has some selected ones, so some specific things like server cipher selection that work with real OpenSSL are not wired up to the shim.

For client it can complete the TLS handhake and use the TLS connection seemingly perfectly already, the problem is specifically we don't get a working verify callback as we do with real OpenSSL, so it always just accepts the server cert with mbedtls atm.

Actually this was my comment from March when I implemented the ESP32 support that uses mbedtls

```
#if defined(LWS_USE_MBEDTLS)
// esp-idf openssl shim does not seem ready for this
//	SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, OpenSSL_client_verify_callback);
	SSL_set_verify(wsi->ssl, SSL_VERIFY_NONE, OpenSSL_client_verify_callback);
```

it might be worth reversing which line is commented and see if you get the cb now esp-idf the wrapper comes from is 6 months older.  If not we can maybe try to discuss with the wrapper author.

**Comment by asherkin** [comment]
Sadly I have already tried with `SSL_VERIFY_PEER` there, the behaviour was the same.

**Comment by lws-team** [comment]
"The same" means what, we never got the callback?

**Comment by asherkin** [comment]
Indeed, the only SSL-specific callback I get in user code is `LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS` - which is the same regardless of `SSL_VERIFY_NONE` or `SSL_VERIFY_PEER`.

**Comment by asherkin** [comment]
Aha, the verify callback at least is never passed into mbedTLS, it is never hooked up with `mbedtls_ssl_conf_verify` in `ssl_pm_reload_crt`.

It is going to be a bit of a shim job because they're not directly compatible and the overriding methods are rather different, the implementation here could end up being quite fun...

**Comment by lws-team** [comment]
It's open to you to `#if defined(LWS_USE_MBEDTLS)` the lws OpenSSL_client_verify_callback() callback args and content to something more convenient if it helps; it doesn't have to exactly match what's needed for real openssl (although it needs to still be like that is not built with LWS_USE_MBEDTLS).  It's 22:00 here and the wrapper author is also in UTC+8, I'll try to help tomorrow if anything moved on.

**Comment by asherkin** [comment]
Ignoring the callback for now and just looking at native validation, it looks like `mbedtls_ssl_conf_ca_chain` (the function set the trusted CA roots, see end of https://tls.mbed.org/kb/how-to/mbedtls-tutorial) is hooked up to `SSL_add_client_CA` by the wrapper, which doesn't appear to be correct behaviour.

I'm going to slowly continue poking around in this (time permitting), but if anyone more familiar with mbedTLS or OpenSSL wants to dive in alongside please be my guest -- if I get anywhere worth mentioning I'll continue updating here to avoid duplication of effort.

Rough plan of attack seems to be:
1. Hook up `X509_STORE_CTX_get_error`, `X509_STORE_CTX_get_error_depth`, and `X509_verify_cert_error_string` in the wrapper.
2. Try and understand the correct path towards setting the CA certificates, see if native validation starts working correctly with them set.
3. Take another look at the callback situation for custom logic.

**Comment by lws-team** [comment]
I pushed a patch which stitches in providing the CA cert using the existing info arrangements, and without needing to patch the wrapper.  If you don't pass it a CA cert using the client info, it operates as before (without any server cert validation).

Testing it like this

```
$ libwebsockets-test-client https://warmcat.com -A ~/Downloads/comodorsaaddtrustca.crt
```

it fails

```
[2017/09/02 10:50:28:0451] NOTICE: created client ssl context for default
[2017/09/02 10:50:28:0455] NOTICE: client loaded CA for verification /home/agreen/Downloads/comodorsaaddtrustca.crt
[2017/09/02 10:50:28:0455] NOTICE:  mem: per-conn:          584 bytes + protocol rx buf
[2017/09/02 10:50:28:0456] NOTICE:  canonical_hostname = build
[2017/09/02 10:50:28:0456] NOTICE: using https mode (non-ws)
[2017/09/02 10:50:28:0456] NOTICE: http: connecting
[2017/09/02 10:50:28:0457] NOTICE: lws_client_connect_2: 0x12b1d60: address warmcat.com
[2017/09/02 10:50:28:3387] NOTICE: lws_client_connect_2: 0x12b1d60: address warmcat.com
[2017/09/02 10:50:28:6448] NOTICE: peer provided cert
[2017/09/02 10:50:28:6448] ERR: server's cert didn't look good, X509_V_ERR = 1: unknown
[2017/09/02 10:50:28:6448] ERR: CLIENT_CONNECTION_ERROR: dumb: lws_ssl_client_connect2 failed
```

but unlike before the client CA is supposed to be there and be used via `ssl_pm_reload_crt()` in the wrapper.  So I push it since this should move your debugging on.

**Comment by lws-team** [comment]
I updated the patch, this seems to work for CA validation now, although I don't know about verify_depth.

 - Forcing `SSL_VERIFY_PEER` with no CA cert given -> fail
 - Giving the related CA cert for https://warmcat.com (with `SSL_VERIFY_PEER` implied)-> succeed
 - Giving a selfsigned CA cert for https://warmcat.com (with `SSL_VERIFY_PEER` implied) -> fail

It doesn't have a generic "accept selfsigned"... I think it will need meddling with verify depth.

But at least this is a lot further along :-)

**Comment by asherkin** [comment]
This looks to be in pretty good shape, thanks!

The one remaining bit I think this really needs to be sane in production is hostname verification. I hacked up the wrapper to call `mbedtls_ssl_set_hostname` and it seems to do the correct thing, but I cannot get to grips with the wrapper internals to hook it up correctly to `X509_VERIFY_PARAM_set1_host`.

It seems like it should be relatively simple, have `SSL_get0_param` return the input param without modification, stub `X509_VERIFY_PARAM_set_hostflags`, and hookup `X509_VERIFY_PARAM_set1_host` to call `mbedtls_ssl_set_hostname`.

Can you think of any way to do it without modifying the wrapper? (or implementing CN/SAN matching in LWS...)

**Comment by lws-team** [comment]
I don't think LWS can do the CN / hostname check without a verify callback, we don't have that either.

At the moment for "real OpenSSL" we tell it the hostname and ask it to confirm it if the version of OpenSSL supports it.

According to these

https://github.com/ARMmbed/mbedtls/issues/466
https://curl.haxx.se/docs/adv_20160518.html

```
The documentation for mbedTLS and PolarSSL (wrongly) says that the API function ssl_set_hostname() is used only for setting the name for the TLS extension SNI. The set string is however even more importantly used by the libraries to verify the server certificate, and if no "hostname" is set it will just skip the check and successfully continue with the handshake.
```

So according to that, you only need to wire up the existing `hostname` in `lws_ssl_client_bio_create()` via `mbedtls_ssl_set_hostname()`, and mbedtls will validate the CN against it.  You should be able to check it by setting garbage there instead of `hostname`.

**Comment by asherkin** [comment]
I did some horrible hacky stuff to test it from LWS, and yes, that does work great setting it there.

However, the wrapper doesn't expose the internal libmbedtls context afaict, the struct required isn't even in one of the internal headers.

It isn't remotely shippable for obvious reasons, but here is what I ended up doing for testing:
```
diff --git a/lib/ssl-client.c b/lib/ssl-client.c
index 6ef1bb5..258fb42 100644
--- a/lib/ssl-client.c
+++ b/lib/ssl-client.c
@@ -180,6 +180,10 @@ lws_ssl_client_bio_create(struct lws *wsi)
        else
                SSL_set_verify(wsi->ssl, SSL_VERIFY_NONE, OpenSSL_client_verify_callback);
 
+       struct ssl_pm *ssl_pm = (struct ssl_pm *)wsi->ssl->ssl_pm;
+       struct mbedtls_ssl_context *ssl_context = (struct mbedtls_ssl_context *)((unsigned char *)ssl_pm + 536);
+       int ret = mbedtls_ssl_set_hostname(ssl_context, hostname);
+       lwsl_notice("%s: mbedtls_ssl_set_hostname(%p, \"%s\") = %d\n", __func__, ssl_context, hostname, ret);
 #else
 #ifdef SSL_CTRL_SET_TLSEXT_HOSTNAME
        SSL_set_tlsext_host_name(wsi->ssl, hostname);
```

Looks like any route to correct verification will require additions to the wrapper, either exposing the internal context, or hooking up the OpenSSL equivs.

**Comment by lws-team** [comment]
Well that's encouraging that we know it'll work, thanks.

I'll try to wrap my head around it tomorrow.  This reflects the limit of the wrapper capability not just for lws use but also for ESP32 use, its original purpose.  So the author may also have reason to accept a reasonable patch on the upstream wrapper.

**Comment by lws-team** [comment]
I added the necessary OpenSSL apis to the wrapper to have the existing lws implementation work.

This seems to do everything as designed (the patch series is on master) and continues to do the test client OK to https://warmcat.com.  However if I force `hostname` to "xxx" it's still completely happy.

Did you check that giving a garbage hostname to `mbedtls_ssl_set_hostname()` actually breaks the ssl verification?

**Comment by lws-team** [comment]
Hmmm no scratch that... it works perfectly.

The problem that is with mbedtls, it defaults to just accepting the cert atm if we don't give it a CA explicitly.

If I test it with -A and the peer CA cert, then it works, and trashing `hostname` by hand stops it accepting the certificate.
