### ISSUE TITLE
windows.h and winsock2.h multiple symbol redefinition

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#1014]
Hi, (me again),

I found out, that if I do
```
#include <Windows.h>
#include <libwebsockets/libwebsockets.h>
int main() { return 0; }
```
I end up with 121 compiler errors like `Error	C2011	'hostent': 'struct' type redefinition`

I found out, that libwebsockets.h defines 
```
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
```
Which should prevent Windows.h from loading some websocket api together with some other apis. But then the libwebsockets.h includes
```
#include <winsock2.h>
```

So, if I try to use the 'full' windows.h I get errors. Maybe this is a problem of microsoft libs (I guess so) or maybe I'm doing something wrong, I'm not quite familiar with the windows libs, but woudn't the solution be, if libwebsockets.h doesn't expose (include) 3th part libraries? Couldn't be possible to move those includes to the private-libwebsockets.h?

Just asking about your opinion.. Thank you.

**Comment by lws-team** [comment]
Lws + test apps has built for a long while on appveyor, this is the current HEAD

https://ci.appveyor.com/project/lws-team/libwebsockets

So whatever it is, it doesn't have to blow up.

Types from platform includes are used in apis on that platform... that's why it's in the public header.

**Comment by lws-team** [comment]
If there's something we should do to make this better, let us know.
