### ISSUE TITLE
Reading HTTP POST response headers

### ISSUE THREAD

**Issue by 9too** [warmcat/libwebsockets#1019]
## Context
I have a client that needs a 2-step authentication protocol.

1. Open a websocket connection and receive an identifier.
2. HTTP POST credentials along with the received identifier

The POST response will contain a Set-Cookie header to use to communicate on the websocket.

## Issue
Everything works only using lws. Except that I can't find how to read the POST response headers. I took a look at the HTTP header releated functions but it doesn't look like I can do what I want. I can see the cookie header being parsed when I enable debug on the library. I just can't find how to extract it...

### Side note
I'd like to add that cookie on the opened websocket connection but it seems like it's only possible during the handshake. So is there a way to make a connection restart the LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER ?
Currently I just recreate the context and open a new connection.

**Comment by lws-team** [comment]
1) You can use the lws_hdr apis in `LWS_CALLBACK_HTTP_BODY`with POST, eg

```
	case LWS_CALLBACK_HTTP_BODY:
		{
			char ctype[128];
			int ctlen;
			ctlen = lws_hdr_copy(wsi, ctype, sizeof(ctype), WSI_TOKEN_HTTP_CONTENT_TYPE);
			if (ctlen > 0)
				lwsl_notice("HTTP_BODY: content type: %s\n", ctype);
			lwsl_notice("HTTP_BODY: len %d\n", ctlen);
		}
		...
```

2) The ws upgrade is a one-way street, once it completes the connection is no longer "talking http".  So there is no way to use http features like cookies, and no way to undo the upgrade.  These rules are part of the ws definition, even if lws tried to bend them your browser or whatever will not understand and stick with the ws standard that disallows it.

3) You shouldn't create a context for every connection if that's what you are doing.  The context can be created once and any amount of client connections can use it, or if there are no active client connections that's also fine.  Creating the context is relatively expensive.

**Comment by 9too** [comment]
Thank you for your fast reply, it enlightened me on something I was doing wrong...
And another thanks for this library !

**Comment by zalmoxis2019** [comment]
Hello,

   I used your sample code above, to receive the WSI_TOKEN_HTTP_CONTENT_ENCODING and i expected to receive "gzip" in the ctype but ctlen returned is 0. The http response i get has both http header fields like this: 

content-encoding: gzip
content-type: application/json; charset=utf-8

content-type is returned correctly but content-engoding not. This is very weird, any idea why that happens?

thank you

	case LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP:
	{
		char ctype[128];
		int ctlen;
		ctlen = lws_hdr_copy(wsi, ctype, sizeof(ctype) - 1, WSI_TOKEN_HTTP_CONTENT_TYPE);
		//ctlen = lws_hdr_copy(wsi, ctype, sizeof(ctype) - 1, WSI_TOKEN_HTTP_CONTENT_ENCODING);
		if (ctlen > 0)
		    lwsl_notice("HTTP_BODY: content type: %s\n", ctype);
		lwsl_notice("HTTP_BODY: len %d\n", ctlen);
	}
