### ISSUE TITLE
Missing xxd fails silently

### ISSUE THREAD

**Issue by johanvdp** [warmcat/libwebsockets#1021]
As novice I tried to install lws-esp32-factory image, but ended with a non-starter.
It took quite some work to find a simple reason.
I found that make silently fails (actually it continues) even when missing a dependency.
I needed to install 'xxd' (from fedora vim-common). This file is used (in my case) by scripts/esp32.mk.

**Comment by lws-team** [comment]
I pushed a patch on lws that has the cmake part check for genromfs and xxd availability when building for ESP32.
