### ISSUE TITLE
CMake: RPM package target does not obey LWS_* options

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#1023]
When `cmake` is called like:

```
cmake .. -DLWS_WITH_SERVER_STATUS=1
```

and then a RPM package is build:

```
make libwebsockets_rpm
```

The resulting RPM package is build without the compile time options provided to cmake.

**Comment by lws-team** [comment]
RPM spec files enforce their own config and build from scratch in a repeatable way, not "tar up" whatever you have in ./build.
