### ISSUE TITLE
Set-Cookie in WebSocket Handshake

### ISSUE THREAD

**Issue by apirila** [warmcat/libwebsockets#1028]
According to RFC, the specification allows sending of additional headers in the WebSocket handshake. It seems that it is not possible to do this with libwebsocket. I would like to set a cookie on WebSocket handshake. Is it be possible to add, e.g. a callback which would allow me to add all headers that I want to in the handshake (called e.g. from handshake_0405 function).

**Comment by lws-team** [comment]
Lws already has a callback for this job, `LWS_CALLBACK_ADD_HEADERS`... it just isn't called on the upgrade header.  Usually the client has visited another page, to get the script that is directing him to open the ws connection, and you can set the cookie there.  But you're right there's no reason to disallow it on upgrade headers.

How about the patch linked above, on master?

**Comment by apirila** [comment]
Hi, 

Thanks for quite reply. If I understand correctly, than looks what I was looking for.

**Comment by vinifr** [comment]
Hello. How could I add a cookie like this in websocket client handshake?

Cookie: authtoken=8af61fdd-bcb0-4e7e-a686-836d9e386d20; device_type=web; device_id=a9abdfb9b19a10bb3bd26bd77e4263ed; l=; ref.929a9991f7ee.group=3

**Comment by lws-team** [comment]
You use either `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h?h=main#n537-554

or `LWS_CALLBACK_ADD_HEADERS`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h?h=main#n270-295

to insert headers, for client and server respectively.

The ws handshake is still http, so it follows normal http callback flow.

**Comment by vinifr** [comment]
Thanks, it is working good. But now I need to add some custom headers like these:

Header: sec-ch-ua-platform: "Linux"
Header: origin: https://broker.com
Header: sec-fetch-site: same-site
Header: sec-fetch-mode: cors
Header: sec-fetch-dest: empty

Are there no static_token option for this?
