### ISSUE TITLE
When will wsi be freed?

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1030]
Hi, Andy
I met another problems, when will wsi be freed?  I did a test , when wsi be established, it`s memory is 1000B(for example),but after I killed the client (ctrl+c),  it`s also 1000B.
Then I checked LWS_CALLBACK_CLOSED implementation in libwebsockets, found that free function is empty as below,and I did not have TEE_Free in my codes. so ,how did I free it?
_void __attribute__((weak))
	TEE_Free(void *buffer)
{
}_

**Comment by lws-team** [comment]
Are you using lws on OP-TEE?

Notice the "attribute weak", this is a placeholder function if you do not link against the OP-TEE TA library that actually provides TEE_Free().

The wsi will be freed when lws finds the socket closed, or it decides to close the socket.

You will get the CLOSED callback, and then depending on the kind of connection it will be freed right away, or after allowing some time for protocol close messages to be exchanged.

If it's a ws connection, it may attempt to close according to ws protocol, which involves sending a message.  That means the actual close relies on timeout working in lws... in turn that relies on a working gettimeofday() (which OP-TEE has) and you calling lws for service regularly.

**Comment by xmanmax** [comment]
Hi, thx for your reply,
1) not using lws on OP-TEE. Just a ubuntu env which be used for my ws server.
2) yes ,I got a LWS_CALLBACK_CLOSED callback after I killed ws cient,  maybe i did not say clearly, sorry, I mean when **_ws-server_**  wsi be freed after  I killed **_ws-client_**. 
2) yes, it`s a ws connection, but I did not use gettimeofday() in my code .
4) 

> That means the actual close relies on timeout working in lws
what mean of timeout? 
In my code,  I got LWS_CALLBACK_CLOSED callback ,and just print some log, do nothing else.

**Comment by lws-team** [comment]
TEE_Free() is only related to OP-TEE.  So you are looking in the wrong place.

When your client socket closes, the client side sends a FIN to the server.  We notice it shortly after that arrives and close and free the wsi.

You can play with the test server and test client, or test server and a browser and see the log messages about CLOSE on server side.

On both client and server sides, wsis are ultimately freed here

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.c#L119

put a log there if you are still worried it's leaking.
