### ISSUE TITLE
Library ordering issue in CMakeLists

### ISSUE THREAD

**Issue by kallisti5** [warmcat/libwebsockets#1032]
In CmakeLists, the CHECK_FUNCTION_EXISTS calls are made, then much later in the CMakeLists, the platform specific libraries are appended to LIB_LIST and CMAKE_REQUIRED_LIBRARIES is set.

The CHECK_FUNCTION_EXISTS calls actually depend on CMAKE_REQUIRED_LIBRARIES, so it isn't possible to append platform libraries for the function searches unless you hack them in before the CHECK_FUNCTION_EXISTS calls.

To make all of this stuff simpler, the CHECK_FUNCTION_EXISTS calls need to occur after CMAKE_REQUIRED_LIBRARIES.

Example hack
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ce2bce6..0d1e96d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -497,6 +497,10 @@ if (LWS_WITHOUT_BUILTIN_SHA1)
        set(LWS_SHA1_USE_OPENSSL_NAME 1)
 endif()

+if (HAIKU)
+    set(CMAKE_REQUIRED_LIBRARIES network)
+endif()
+
CHECK_FUNCTION_EXISTS(bzero, LWS_HAVE_BZERO)
CHECK_FUNCTION_EXISTS(fork, LWS_HAVE_FORK)
CHECK_FUNCTION_EXISTS(getenv, LWS_HAVE_GETENV)
```

**Comment by lws-team** [comment]
I moved the existing ones (which are generic toolchain / libc functions) to after the stuff that sets CMAKE_REQUIRED_LIBRARIES as you suggested.

**Comment by kallisti5** [comment]
Looks good!   I was reluctant to make that change myself since it had a strong potential of breaking "all the things" if done wrong :-)

**Comment by lws-team** [comment]
It did break everything :-)  CMakeCache hid it from me.... I am just editing my patch to unbreak it.

**Comment by lws-team** [comment]
I yanked this patch, see discussion in #1033

**Comment by kallisti5** [comment]
I can confirm the sources as they exist right now compile and run fine on Haiku.

Thanks!
