### ISSUE TITLE
Broken Link in Notes About Building Lws

### ISSUE THREAD

**Issue by Yang09701194** [warmcat/libwebsockets#1034]
In **Building on Windows (Visual Studio)**  section in **Notes About Building Lws** page:
https://libwebsockets.org/lws-api-doc-master/html/md_README_8build.html

In Step2: `Install OpenSSL binaries. http://www.openssl.org/related/binaries.html` ,

The link ' http://www.openssl.org/related/binaries.html ' was a not found page,
Does it need to updated?

**Comment by lws-team** [comment]
Thanks... it seems to have become https://wiki.openssl.org/index.php/Binaries

I'll update the README in the morning.

**Comment by lws-team** [comment]
I updated it on v2.3-stable and master.

**Comment by Yang09701194** [comment]
Thanks, I find Step 4 of `@section cmwmgw Building on Windows (MinGW)` is updated.

But Step2 of `@section cmw Building on Windows (Visual Studio)` is not yet updated,
hope it can be updated, thanks!

**Comment by lws-team** [comment]
Thanks I fixed the other one too.
