### ISSUE TITLE
Http2 support on esp32?

### ISSUE THREAD

**Issue by negativekelvin** [warmcat/libwebsockets#1035]
Do you think this would be a nice feature for esp32 platform? I think that mbedtls wrapper does not include alpn functions required for http2 but mbedtls does support it. So if wrapper was extended to cover these then lws could be built with http2 option, right? Thanks

**Comment by lws-team** [comment]
The Powers That Be decided they won't support ws on http2.  I did the existing support for http2 in lws a few years ago on the expectation The Powers That Be weren't that retarded, but they are.  (ws is the only http/1 mainstream feature not supported in http/2).

So unless that changes I don't plan to support http/2 ongoing.

If you look at the lws test apps example for ESP32, actually he does mux on http/1 using `lws-meta` protocol... he has three ws connections running over one https / wss connection.  Connection and function is very fast.

**Comment by negativekelvin** [comment]
Thanks for info. So you don't think it is worth it to load initial static page assets over single tcp with http2 even if you can't use it for wss?

**Comment by lws-team** [comment]
I took a look thismorning at the state of the existing http/2 stuff on master, it is in better shape than I thought, although there is still a lot to do on it to make it compliant.

After some upgrading the code to match the rest of lws it's able to build against Fedora's default distro openssl and give ALPN / h2 upgrades, to the point it can actually run the test server in firefox.  (although it has problems losing sync with the http/2 stream after transferring a file, it's enough and it stays up).  It remains valgrind-clean except one leak that can happen depending on the lost sync before it closes the stream.

I was really surprised to see the ws connections working as well, but after seeing it, I realized naturally they don't try to do an h2 upgrade, because the client will always send a ws upgrade.  So the integration problem for ws is way less than I was expecting; everything can coexist in a single vhost as normal and the client will drive the correct path.

That's on a PC, looking at ESP32 as you say the problem is the extra apis are missing from the wrapper.  Espressif seem to have given up taking patches, my patch on the wrapper giving it the power to check the cert CN against the hostname used to reach the server is stuck for 18 days

**Comment by lws-team** [comment]
After removing the deprecated NPN stuff in lws it only required two new OpenSSL apis adding to the wrapper.  So as far as lws http/2 support works (as far as Firefox + the test server) that now works the same on both OpenSSL and mbedTLS builds of lws, on current master.

So the last step is try to integrate the wrapper changes to the lws test server app on ESP32 somehow and see if it acts the same there with http/2 enabled.

**Comment by negativekelvin** [comment]
Thanks for digging into it. Yes, exactly client can use h2 but not conflict ws path.  

I have noticed Espressif is slow to process contributions, but usually get around to it.  Yes nghttp is just sort of thrown in there not very useful out of the box especially since its examples are for openssl too ... wrappers.

Sounds promising so far.  Staying tuned.

**Comment by lws-team** [comment]
I patched esp-idf with the wrapper changes for now... it can start up OK but has a problem with hpack when connecting to it.

I also checked the PC version with Chrome, it provokes the same hpack problem on PC platform (which makes it easier to study); Firefox continues to work as before.  So there is still stuff to fix in the http/2 code, probably around hpack dynamic symbol table.  But it looks like ESP32 or not isn't going to matter now, although the wrapper patch needs integrating somewhere.  I'll resume looking at it later.

**Comment by negativekelvin** [comment]
For wrapper you could do like bootloader and have patched openssl component in project

**Comment by lws-team** [comment]
I updated https://github.com/warmcat/lws-esp32-test-server-demos so

 - it builds using the internal lws openssl wrapper with the necessary extra APIs + fixes

 - HTTP/2 is enabled by default and works for the test server on Firefox 55 / Chrome 63 for me anyway

 - The test server HTML reports if it arrived over h2 with an HTTP/2 icon on the top right if so

Apart from the wrapper provision coming from lws, everything else is aligned with current HTTP/2 support in normal lws, which is valgrind-clean.  In other words ESP32 platform is able to follow lws HTTP/2 development without any special problem now, and you can also run the test server on a PC build of lws using HTTP/2.

If you want to enable or disable HTTP2 eg for comparison, edit `./components/libwebsockets/component.mk` and change

```
                -DLWS_WITH_HTTP2=1 \
```

With the way HTTP/2 is integrated in lws, HTTP/1.x is still available along with ws on the same vhost, so it will all work exactly the same whether you have HTTP/2 enabled or not.

The next thing is fix the various noncompliances and problems that will be hiding, I found a test suite  https://github.com/http2/http2-test but it's kind of abandoned.  If anyone has a better idea please let me know.

**Comment by negativekelvin** [comment]
Excellent, will try it.  So if we are also using native esp-idf wrapper in other components is there any linker conflict or code duplication?

**Comment by lws-team** [comment]
No... the internal lws version doesn't have symbols that are visible outside of the lws build.  Since that satisfies all the internal lws users, there is nothing left wanting any symbols the esp-idf version globally exports, the function-level linking eliminates the whole of the esp-idf version.  You don't have to patch, disable or do anything about the esp-idf wrapper it's just ignored.

**Comment by negativekelvin** [comment]
Ok so assuming we are using the idf wrapper in other places we'll just end up with a slightly larger binary than if we had a shared wrapper.

**Comment by lws-team** [comment]
Yeah.  If espressif deign to look at my patches, or provide the same apis + fixes themselves (I guess this is why the just ignore my patch), we can go back to using the idf version as we did until now.  But while the idf one is broken / inadequate this is the best compromise.

**Comment by negativekelvin** [comment]
Looks pretty good. How much can we reduce window and frame size on esp32 to conserve ram?

**Comment by lws-team** [comment]
All the h2spec tests pass now.

For adapting http/2 SETTINGS, the context holds a copy which can be modified by the lws platform code to whatever makes most sense to that... for esp32 it modifies it to

```
	/* H2SET_HEADER_TABLE_SIZE */			  32,
	/* H2SET_ENABLE_PUSH */				   0,
	/* H2SET_MAX_CONCURRENT_STREAMS */		   8,
	/* H2SET_INITIAL_WINDOW_SIZE */		       65535,
	/* H2SET_MAX_FRAME_SIZE */		         900,
	/* H2SET_MAX_HEADER_LIST_SIZE */	 	 512,
```

those numbers are returned into a new context creation info member

```
	uint32_t	http2_settings[7];
	/**< CONTEXT: after context creation http2_settings[1] thru [6] have
	 *	      been set to the lws platform default values.
	 *   VHOST:   if http2_settings[0] is nonzero, the values given in
	 *	      http2_settings[1]..[6] are used instead of the lws
	 *	      platform default values.
	 *	      Just leave all at 0 if you don't care.
	 */
```

and as it says, you can choose to modify them further before creating the vhost(s)... so you can control SETTINGS by vhost with the defaults sane for your platform.

I instrumented the heap allocation inside lws (it doesn't cover allocations in the protocols, but only mirror does this on the test server, and only while you are drawing).  The bulk of the heap allocations occur outside lws now, in mbedtls and the tcp/ip stack I guess.  Every allocation from is printed at the moment, but not the frees, along with the allocation reason.  I updated the lws-esp32-test-server-demos project with this.

Opening 2 x test server sessions that stay up in two browsers looks like this (_realloc: ... are the lws allocations)

```
4: gapss from LWS_GAPSS_INITIAL to LWS_GAPSS_SCAN
I (1492) wifi: wifi firmware version: 731ced4
I (1492) wifi: config NVS flash: disabled
I (1492) wifi: config nano formating: disabled
I (1502) wifi: Init dynamic tx buffer num: 32
I (1502) wifi: Init data frame dynamic rx buffer num: 20
I (1512) wifi: Init management frame dynamic rx buffer num: 20
I (1512) wifi: wifi driver task: 3ffc79a0, prio:23, stack:4096
I (1522) wifi: Init static rx buffer num: 20
I (1522) wifi: Init dynamic rx buffer num: 20
I (1532) wifi: Init rx ampdu len mblock:7
I (1532) wifi: Init lldesc rx ampdu entry mblock:4
I (1542) wifi: wifi power manager task: 0x3ffd0cdc prio: 21 stack: 2560
W (1542) wifi: ap start fail

I (1602) wifi: mode : sta (24:0a:c4:05:d7:68)
4: SYSTEM_EVENT_STA_DISCONNECTED
4: gapss from LWS_GAPSS_SCAN to LWS_GAPSS_SCAN
4: lws_esp32_scan_timer_cb
4: _realloc: size 504: context
4: _realloc: size 900: pt_serv_buf
4: _realloc: size 1536: context ah hdr data
4: _realloc: size 10968: context ah hdr pool
4: _realloc: size 240: fds table
4: _realloc: size 120: esp32 lws_lookup
4:  mem: platform fd map:   120 bytes
4: ROMFS length 1517KiB
{
 "schema": "lws1",
 "model": "lws",
 "builder": "build",
 "app": "lws-esp32-test-server-demos",
 "user": "agreen",
 "git": "03c0807-dirty",
 "date": "Wed Oct  4 09:25:48 CST 2017",
 "unixtime": "1507080348",
 "file": "lws-esp32-test-server-demos-1507080348.bin",
 "factory": "0"
}
4: _realloc: size 440: create vhost
4: _realloc: size 224: vhost-specific plugin table
4: _realloc: size 28: same vh list
4: Creating Vhost 'station' port 443, 7 protocols, IPv6 off
4:    mounting file:///station to /
4:    mounting callback://protocol-post-demo to /formtest
4:    mounting callback://esplws-rtf to /esp32-rtf
4:  Using SSL mode
4:  HTTP2 / ALPN enabled
4: created client ssl context for station
4: _realloc: size 528: listen wsi
4: _realloc: size 28: protocol_vh_privs
4: _realloc: size 16: vh priv
4: _realloc: size 4100: vh priv
4: _realloc: size 20: vh priv
4:  heap :166344 (-24728)
4: SYSTEM_EVENT_SCAN_DONE
4: checking 4 scan records
4: looking for foamy
4: Attempting connection with slot 0: foamy:
4: gapss from LWS_GAPSS_SCAN to LWS_GAPSS_STAT
4:  heap :166468 (+124)
I (4632) wifi: n:11 0, o:1 0, ap:255 255, sta:11 0, prof:1
I (5192) wifi: state: init -> auth (b0)
I (5202) wifi: state: auth -> assoc (0)
I (5212) wifi: state: assoc -> run (10)
I (5232) wifi: connected with foamy, channel 11
4: SYSTEM_EVENT_STA_GOT_IP
4: gapss from LWS_GAPSS_STAT to LWS_GAPSS_STAT_HAPPY
4:  --- Got IP 192.168.2.200
4:  heap :159708 (-6760)
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
I (8212) wifi: pm start, type:0

4: _realloc: size 180: h2n
4: _realloc: size 256: dynamic table entries
4:  heap :144864 (-14844)
4: _realloc: size 514: h2 rx scratch
4: _realloc: size 48: pps
4: _realloc: size 124: rxflow buf
4: _realloc: size 48: pps
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffd951c for sid 15
4: _realloc: size 14: hpack dyn
4: _realloc: size 77: hpack dyn
4: _realloc: size 64: hpack dyn
4: _realloc: size 15: hpack dyn
4: _realloc: size 18: hpack dyn
4: _realloc: size 10: hpack dyn
4: esp32_lws_fops_open: /station/test.html
4:  heap :135664 (-9200)
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffdc51c for sid 17
4: _realloc: size 23: hpack dyn
4: esp32_lws_fops_open: /station/lws-common.js
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffdcc68 for sid 19
4: esp32_lws_fops_open: /station/libwebsockets.org-logo.png
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
4:  heap :128848 (-6816)
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffde32c for sid 21
4: esp32_lws_fops_open: /station/http2.png
4: _realloc: size 288: user space
4: _realloc: size 1044: rx_ubuf
8: callback_lws_meta: LWS_CALLBACK_ESTABLISHED
16: callback_lws_meta: dumb-increment-protocol /  / C1
4: _realloc: size 528: new server wsi
4: _realloc: size 4: user space
4: _realloc: size 4: user space
4: _realloc: size 30: rx_ubuf
16: cwsi 0x3ffdc258 on parent 0x3ffde118 open OK dumb-increment-protocol
16: callback_lws_meta: lws-status / wss://192.168.2.200/ / C2
4: _realloc: size 528: new server wsi
4: _realloc: size 152: user space
4: _realloc: size 152: user space
4: _realloc: size 532: rx_ubuf
16: cwsi 0x3ffde780 on parent 0x3ffde118 open OK lws-status
16: callback_lws_meta: lws-mirror-protocol / wss://192.168.2.200/?mirror= / C3
4: _realloc: size 528: new server wsi
4: _realloc: size 8: user space
4: _realloc: size 8: user space
4: _realloc: size 148: rx_ubuf
8: callback_lws_mirror: LWS_CALLBACK_ESTABLISHED
16: cwsi 0x3ffdebac on parent 0x3ffde118 open OK lws-mirror-protocol
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffdb250 for sid 23
4: esp32_lws_fops_open: /station/favicon.ico
16: open result C3 lws-mirror-protocol
16: open result C2 lws-status
16: open result C1 dumb-increment-protocol
4: lws_esp32_scan_timer_cb
4:  heap :130748 (+1900)
4:  heap :117980 (-12768)
4: SYSTEM_EVENT_SCAN_DONE
4: ignoring scan as gapss LWS_GAPSS_STAT_HAPPY
4:  heap :130748 (+12768)
4:  heap :132344 (+1596)
4:  heap :133408 (+1064)
4:  heap :144416 (+11008)
4:  heap :144412 (-4)
4:  heap :144416 (+4)
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
4: _realloc: size 180: h2n
4: _realloc: size 256: dynamic table entries
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
4: _realloc: size 180: h2n
4: _realloc: size 256: dynamic table entries
4:  heap :117088 (-27328)
4: _realloc: size 514: h2 rx scratch
4: _realloc: size 514: h2 rx scratch
4: _realloc: size 48: pps
4: _realloc: size 46: rxflow buf
4: _realloc: size 48: pps
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffdbd10 for sid 1
4: _realloc: size 14: hpack dyn
4: _realloc: size 10: hpack dyn
4: _realloc: size 112: hpack dyn
4: _realloc: size 86: hpack dyn
4: _realloc: size 18: hpack dyn
4: _realloc: size 15: hpack dyn
4: esp32_lws_fops_open: /station/test.html
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffe3a98 for sid 3
4: _realloc: size 4: hpack dyn
4: _realloc: size 23: hpack dyn
4: esp32_lws_fops_open: /station/lws-common.js
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffd9a50 for sid 5
4: _realloc: size 40: hpack dyn
4: esp32_lws_fops_open: /station/libwebsockets.org-logo.png
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
4:  heap :118100 (+1012)
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffd9f98 for sid 7
4: esp32_lws_fops_open: /station/http2.png
4: _realloc: size 528: new server wsi
ssl->ctx->read_buffer_len = 2048 ++++++++++++++++++++
4:  heap :114652 (-3448)
4: _realloc: size 288: user space
4: _realloc: size 1044: rx_ubuf
8: callback_lws_meta: LWS_CALLBACK_ESTABLISHED
16: callback_lws_meta: dumb-increment-protocol /  / C1
4: _realloc: size 528: new server wsi
4: _realloc: size 4: user space
4: _realloc: size 4: user space
4: _realloc: size 30: rx_ubuf
16: cwsi 0x3ffdb330 on parent 0x3ffd9c64 open OK dumb-increment-protocol
16: callback_lws_meta: lws-status / wss://192.168.2.200/ / C2
4: _realloc: size 528: new server wsi
4: _realloc: size 152: user space
4: _realloc: size 152: user space
4: _realloc: size 532: rx_ubuf
16: cwsi 0x3ffe1ad4 on parent 0x3ffd9c64 open OK lws-status
16: callback_lws_meta: lws-mirror-protocol / wss://192.168.2.200/?mirror= / C3
4: _realloc: size 528: new server wsi
4: _realloc: size 8: user space
4: _realloc: size 8: user space
4: _realloc: size 148: rx_ubuf
8: callback_lws_mirror: LWS_CALLBACK_ESTABLISHED
16: cwsi 0x3ffe4784 on parent 0x3ffd9c64 open OK lws-mirror-protocol
4: _realloc: size 528: new server wsi
4: created wsi 0x3ffd9f98 for sid 9
4: _realloc: size 9: hpack dyn
4: _realloc: size 9: hpack dyn
4: esp32_lws_fops_open: /station/favicon.ico
16: open result C3 lws-mirror-protocol
16: open result C2 lws-status
16: open result C1 dumb-increment-protocol
4:  heap :117640 (+2988)
4:  heap :119232 (+1592)
4:  heap :130188 (+10956)
4:  heap :128312 (-1876)
4:  heap :128308 (-4)
4:  heap :124196 (-4112)
4:  heap :126080 (+1884)
4:  heap :124300 (-1780)
4:  heap :126080 (+1780)
4:  heap :115364 (-10716)
4:  heap :113532 (-1832)
4:  heap :108192 (-5340)
4:  heap :126080 (+17888)
4:  heap :124516 (-1564)
4:  heap :126080 (+1564)
4:  heap :124296 (-1784)
4:  heap :126080 (+1784)
4:  heap :122784 (-3296)
4:  heap :126080 (+3296)
4:  heap :122520 (-3560)
4:  heap :126080 (+3560)
4:  heap :112236 (-13844)
4:  heap :122708 (+10472)
4:  heap :126080 (+3372)
4:  heap :126288 (+208)
4:  heap :124724 (-1564)
4:  heap :126288 (+1564)
4:  heap :124724 (-1564)
4:  heap :126288 (+1564)
...
```

You can see lws allocations are relatively modest compared to changes in global heap, and at the end lws is idle except sending dumb-increment to the browsers, yet there is considerable churn on the heap, not from us, up to +/- 17KB.  So while I would welcome ideas to meaningfully improve it, I think lws is doing OK AFAICT.
