### ISSUE TITLE
poll

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#1036]
I read that lws library use poll, is this right ? If yes why my server can accept only 1024 connection ? Must I set any variable ?

Thank you for help

Mario

**Comment by lws-team** [comment]
Assuming you're on Linux, from README.coding.md:

```
@section conns Maximum number of connections

The maximum number of connections the library can deal with is decided when it starts by querying the OS to find out how many file descriptors it is allowed to open (1024 on Fedora for example). It then allocates arrays that allow up to that many connections, minus whatever other file descriptors are in use by the user code.

If you want to restrict that allocation, or increase it, you can use ulimit or similar to change the available number of file descriptors, and when restarted libwebsockets will adapt accordingly.
```

**Comment by rollen1960** [comment]
Can you say me the exactly function that you call for "querying the OS to find out how many file descriptors" ?
Thank

**Comment by lws-team** [comment]
For Linux, it's

```
$ ulimit -n
```

For other OS, no idea.

**Comment by rollen1960** [comment]
I think in lws library what function call you ?

**Comment by rollen1960** [comment]
because my ulimit is 

[mercury@dev-msp temp]$ ulimit -n
32678

**Comment by lws-team** [comment]
lws finds out how any fds its process is allowed and it configures itself at runtime to use that many. See

https://github.com/warmcat/libwebsockets/blob/master/lib/context.c#L871

See `man getdtablesize`.

If you want more fds for your process, you need to agree that with your OS.

You can restrict lws to a smaller number of fds, are you seeing `info->fd_limit_per_thread` at context creation time?  If not, is your server running under the same user as the ulimit you checked?

**Comment by rollen1960** [comment]
I have write some check before lws_create_context:

getdtablesize() return 32678
getrlimit(RLIMIT_NOFILE, &rlim) return 32678 32678
info_.fd_limit_per_thread is 0

but I open only 1024 connection

I probe with set info_.fd_limit_per_thread=32678 before lws_create_context, but the result is the same:

only 1024 connection are opened

and I receive

WpsServer_log_emit_function : lws_header_table_attach: adding 0x7f7478316490 to ah waiting list
WpsServer_log_emit_function : error on reading from skt : 104
WpsServer_log_emit_function : lws_server_socket_service: wsi 0x7f74782f8190 read -1
WpsServer_log_emit_function : lws_server_socket_service: wsi 0x7f74782f8190 read 0

**Comment by lws-team** [comment]
So how are you opening "1024 connections"?

104 is "Connection Reset by Peer"... are you sure that whatever opens the "1024 connections" on the client side can open > 1024 connections?

**Comment by rollen1960** [comment]
oops found the mistake I have info_.max_http_header_pool = 1024
Thank you for your patient.

Mario

**Comment by lws-team** [comment]
Hm... that shouldn't really kill it.  It should accept connections past 1024 but add them to a waiting list to get a free ah when the other connections are finished with it.

I guess from your log snippit what happens is the client times out waiting for the connection to be serviced, bexause these other guys hold on to it endlessly.

If your connections are HTTP but then sit there not sending headers, or sit there taking endless data they will hog an ah.  There should be a serverside timeout on idle connections to free up the ah.  For ws connections, the ah from the pool is freed up as soon as the connection upgrades to ws.

**Comment by rollen1960** [comment]
Hm... that shouldn't really kill it. It should accept connections past 1024 but add them to a waiting list to get a free ah when the other connections are finished with it.

Tha's right but my server don't close the connection and so after 1024 I can not receive a new client. I have now 2048 for info_.max_http_header_pool and the server accept 2048 client ...

Thank for all

Mario
