### ISSUE TITLE
HTTP 100 Continue

### ISSUE THREAD

**Issue by arielvsp** [warmcat/libwebsockets#1041]
Hello and thanks for the great piece of software.
What would be the best way to return HTTP 100 Continue?
I understand that this status is not currently supported (not in enum http_status) and trying to return it with lws_return_http_status() adds content length and html. Any suggestions? Will be happy to help adding support for this if you can point me to the right direction. 
For the background, I'd like to implement http progressive upload/streaming. I could not find any support for it in LWS. If I miss anything please let me know.

**Comment by lws-team** [comment]
`lws_add_http_header_status()` is just a helper, it only uses public apis.  If you had to mess with it, there's nothing stopping you pasting it into your code.

FWIW I added a patch on master that provides definitions for 100 return code and makes `lws_add_http_header_status()` understand it should add "Continue".

"Progressive..." is an overused word, to you it means RFC 7233 http ranges (lws supports it) or something else?

**Comment by arielvsp** [comment]
Thanks for a prompt response and for the info on patch!
I intended to HTTP 1.1. chunked transfer encoding.  Is there any support for it in LWS?

**Comment by lws-team** [comment]
Lws supports it for cgi, since cgi commonly produce it.  Otherwise no.
