### ISSUE TITLE
Cross Compiler not recognized?

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1042]
I have been working with libwebsockets for about a week now, with the end goal of creating a web server using cross-compilation to an ARM processor on an embedded systems board. I am new to Linux, LWS, and cross compiling. I am working in Ubuntu 16.04.

I have gotten the test-server and lwsws to compile and run using gcc. So, the compiler, libraries, and build of cmake is fine on that side. For the cross-compiler (arm-linux-gcc for the TS-7800 board), I have installed the compiler (executable arm-linux-gcc is in the /bin dir), created a toolchain file and compiled using the directions in the LWS read me files. However, the executable for lwsws or test-server is still compiled for gcc rather than my arm board.

**_What am I missing in my set-up to get the cross compilation to work?_**

Here is my toolchain file:

    # Target operating system name
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR arm)

    # Name of C compiler
    set(CMAKE_C_COMPILER usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2/bin/arm-linux-gcc)
    set(CMAKE_CXX_COMPILER usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2/bin/arm-linux-g++)

    # Where to look for the target environment. (More paths can be added here)
    set(CMAKE_FIND_ROOT_PATH usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2)
    set(ZLIB_INCLUDE_DIR usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2/src/libwebsockets/win32port/zlib)
    set(OPENSSL_INCLUDE_DIR usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2/src/libwebsockets/lib/mbedtls_wrapper/include/openssl)

    # Adjust the default behavior of the FIND_XXX() commands:
    # search programs in the host environment only.
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

    # Search headers and libraries in the target environment only.
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

The paths of OpenSSL and libz seem to be unaffected by my path settings in the toolchain file, as seen below.

Here is some of the terminal readout when running cmake:

    -- CMAKE_TOOLCHAIN_FILE='../arm-linux-gcc.cmake'
    Git commit hash: root@gordon-MS-7A39-v2.0.0-570-gc2a31fa
    -- LWS_WITH_LWSWS --> Enabling LWS_WITH_PLUGINS and LWS_WITH_LIBUV
    zlib include dirs: /usr/include
    zlib libraries: /usr/lib/x86_64-linux-gnu/libz.so
    Compiling with SSL support
    OpenSSL include dir: /usr/include
    OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
    libuv include dir: /usr/local/include
    libuv libraries: /usr/local/lib/libuv.so
    Searching for OpenSSL executable and dlls
    OpenSSL executable: /usr/bin/openssl
     GENCERTS = 1
    Generating SSL Certificates for the test-server...

I notice that the toolchain file is recognized, but the compiler is not identified by name like I have seen in other posts and in my own compilation in gcc.

Is my toolchain file incorrect or missing references to libraries?
I have seen "openssl.h" and "libz.h" in the LWS build files for the cross compiler, but I do not see the shared library (.so files) or archive files. Do I need to rebuild the cross-compiler LWS files to create these somehow? I don't have enough experience to know what I am missing.

I have asked questions pertaining to this project on StackOverflow, but thought I could get a more succinct and accurate answer if I took it to the source.

Thank for any help you can give.

**Comment by lws-team** [comment]
Although lws is involved in how to do the correct incantations for libs, mainly how to do this is decided by cmake and your toolchain, not me.  Generally if you find yourself wandering around in the fog for a week it's a sign you need to cut your problem into pieces.

These options will eliminate non-toolchain lib dependencies, so you can remove worrying about library paths

```
-DLWS_WITH_SSL=0 -DLWS_WITH_ZIP_FOPS=0 -DLWS_WITH_ZLIB=0 -DLWS_WITHOUT_EXTENSIONS=1 
```

I did the following steps:

1) cd /tmp
2) git clone ssh://git@github.com/warmcat/libwebsockets
3) cd libwebsockets
4) mkdir build ; cd build
5) cp ../contrib/cross-arm-linux-gnueabihf.cmake ../mytoolchainfile
6) Edit CROSS_PATH, in my case `set(CROSS_PATH /projects/aist-tb/arm-tc/)` and my compiler is already named "${CROSS_PATH}/bin/arm-linux-gnueabihf-gcc" as in the example cross file.
7) 
(Note you should delete `build/CMakeCache.txt` beforehand if you are trying different options, it remembers previous options and makes a difference between what you think you are testing and what you are actually testing.)

```
$ cmake .. -DLWS_WITH_SSL=0 -DLWS_WITH_ZIP_FOPS=0 -DLWS_WITH_ZLIB=0 -DLWS_WITHOUT_EXTENSIONS=1 -DCMAKE_TOOLCHAIN_FILE=../mytoolchainfile
-- The C compiler identification is GNU 6.2.1
-- Check for working C compiler: /projects/aist-tb/arm-tc//bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /projects/aist-tb/arm-tc//bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE='/tmp/libwebsockets/mytoolchainfile'
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/libwebsockets/build
$make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  3%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
...
Scanning dependencies of target test-ping
[ 98%] Building C object CMakeFiles/test-ping.dir/test-apps/test-ping.c.o
[100%] Linking C executable bin/libwebsockets-test-ping
[100%] Built target test-ping
$ file lib/libwebsockets.so.11
lib/libwebsockets.so.11: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=009c8a086ae5c95e1470a580d94982e647fef331, with debug_info, not stripped
```

That's not so hard, is it?

For adding in the libs, I don't have toolchain-built libs to hand so I can't do an example for you.  Don't forget to delete `build/CMakeCache.txt` between trials or some of what you tried last time will be applied again, badly confusing matters.  For mbedtls, you will need `-DLWS_WITH_MBEDTLS=1`, something like this

```
cmake .. -DLWS_WITH_MBEDTLS=1 -DLWS_MBEDTLS_LIBRARIES=xxxx -DLWS_MBEDTLS_INCLUDE_DIRS=xxxx -DCMAKE_TOOLCHAIN_FILE=../mytoolchainfile
```

If you add things like lwsws you will also need libuv, like  `-DLWS_LIBUV_LIBRARIES=xxx -DLWS_LIBUV_INCLUDE_DIRS=xxx`

**Comment by GordonMadden** [comment]
Yes, not too hard! Once you know what is happening for sure.
I did get it to compile and run for the target platform, but once I diverted from your set-up, e.g., adding in lwsws, I could build the LWS files but not compile. I resorted to deleting the /build file between builds, just to make sure I started with a clean slate.
When it did compile, LIBUV was not compiled in, so usability was hampered.
Adding lswsw (-DLWS_WITH_LWSWS=1) to cmake causes a parsing error (at 1%) when running "make && sudo make install"
Adding in extensions and zlib, caused the following error:
/usr/lib/x86_64-linux-gnu/libz.a: could not read symbols: File format not recognized

Where would I look for additional guidance on how to get lwsws compiled? Does the zlib library need to be built for the cross-compiler, or can the existing library be used?

Thanks again for the tutorial!

**Comment by lws-team** [comment]
> causes a parsing error

Okay, so what is the error?  What does your cmake commandline and results look like?

> Adding in extensions and zlib, caused the following error:
> /usr/lib/x86_64-linux-gnu/libz.a: could not read symbols: File format not recognized

Clearly cmake found your build host's zlib, not your cross zlib.  So again you need to copy and paste your cmake commandline and results.

Your problem isn't really 'getting lwsws compiled', cmake will do that for you just fine... it's only pointing cmake to your cross libuv /zlib build... it sounds like you are okay for mbedtls.

**Comment by GordonMadden** [comment]
Just deleted and cloned project again. Cmake was no longer building. New copy is building and compiling per your instructions.

Here is my toolchain file. I trust (rather than know) that it's working. When I run cmake with -LH, the paths that it shows are not filled in like they are when paths are entered in the command line.
```
set(CROSS_PATH /usr/local/opt/crosstool/arm-linux/gcc-3.3.4-glibc-2.3.2)

# Target operating system name
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Name of C compiler
set(CMAKE_C_COMPILER "${CROSS_PATH}/bin/arm-linux-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_PATH}/bin/arm-linux-g++")

link_directories("/usr/include/")

# Where to look for the target environment. (More paths can be added here)
set(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")

set(ZLIB_INCLUDE_DIR "${CROSS_PATH}/src/libwebsockets/win32port/")
set(ZLIB_LIBRARY "/usr/lib/x86_64-linux-gnu/libz.a")

set(LIBUV_INCLUDE_DIRS "/usr/local/lib")
set(LIBUV_LIBRARIES "/usr/local/lib/libz.a")

set(OPENSSL_ROOT_DIR "/usr/lib/ssl/")
set(OPENSSL_LIBRARIES "/usr/include/openssl/")
set(OPENSSL_INCLUDE_DIR "/usr/include/openssl/")

set(MBEDTLS_INCLUDE_DIRS "/cc/libwebsockets/lib/mbedtls_wrapper/include/")
set(MBEDTLS_LIBRARIES "/cc/libwebsockets/lib/library/")

# Adjust the default behavior of the FIND_XXX() commands:
# search programs in the host environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search headers and libraries in the target environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
Maybe the target environment is LWS and not the cross compiler?

I'm still a little unsure sometimes about what path things need to see, and there seem to be a lot of (seemingly) random bin, include, and lib directories. So, I hope I'm not too far off the mark on those.

Running make gives this:
```
root@gordon-MS-7A39:/cc/libwebsockets/build# make
Scanning dependencies of target websockets
[ 29%] Built target websockets
Scanning dependencies of target test-fuzxy
[ 31%] Linking C executable bin/libwebsockets-test-fuzxy
[ 34%] Built target test-fuzxy
Scanning dependencies of target test-server
[ 35%] Linking C executable bin/libwebsockets-test-server
[ 42%] Built target test-server
Scanning dependencies of target websockets_shared
[ 43%] Linking C shared library lib/libwebsockets.so
[ 73%] Built target websockets_shared
Scanning dependencies of target test-fraggle
[ 75%] Linking C executable bin/libwebsockets-test-fraggle
[ 78%] Built target test-fraggle
Scanning dependencies of target test-ping
[ 79%] Linking C executable bin/libwebsockets-test-ping
[ 82%] Built target test-ping
Scanning dependencies of target test-server-extpoll
[ 84%] Linking C executable bin/libwebsockets-test-server-extpoll
[ 90%] Built target test-server-extpoll
Scanning dependencies of target test-echo
[ 92%] Linking C executable bin/libwebsockets-test-echo
[ 95%] Built target test-echo
Scanning dependencies of target test-client
[ 96%] Linking C executable bin/libwebsockets-test-client
[100%] Built target test-client
```
Running cmake with LWSWS, says:
```
root@gordon-MS-7A39:/cc/libwebsockets/build# cmake .. -DLWS_WITH_SSL=0  -DCMAKE_TOOLCHAIN_FILE=../tcf.cmake -DLWS_WITH_LWSWS=1
-- CMAKE_TOOLCHAIN_FILE='../tcf.cmake'
Git commit hash: root@gordon-MS-7A39-v2.0.0-573-g54faedf
-- LWS_WITH_LWSWS --> Enabling LWS_WITH_PLUGINS and LWS_WITH_LIBUV
-- Looking for uv-version.h
-- Looking for uv-version.h - not found
libuv include dir: /usr/local/lib
libuv libraries: /usr/local/lib/libz.a
 GENCERTS = 0
-- Looking for RPMTools... - rpmbuild NOT FOUND
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = 0 (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_WITH_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_WITH_MBEDTLS = OFF (mbedTLS replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = 1
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_WITH_LIBEV = OFF
 LWS_WITH_LIBUV = 1
 LWS_WITH_LIBEVENT = OFF
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 
 LWS_HAVE_SSL_CTX_set1_param = 
 LWS_HAVE_RSA_SET0_KEY = 
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES = 
 PLUGINS = protocol_lws_meta;protocol_dumb_increment;protocol_lws_mirror;protocol_lws_status;protocol_post_demo;protocol_lws_table_dirlisting;protocol_lws_sshd_base;protocol_lws_raw_test;protocol_lws_server_status;protocol_client_loopback_test
 LWS_WITH_ACCESS_LOG = 1
 LWS_WITH_SERVER_STATUS = 1
 LWS_WITH_LEJP = 1
 LWS_WITH_LEJP_CONF = 1
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
 LWS_WITH_RANGES = ON
 LWS_PLAT_OPTEE = OFF
 LWS_WITH_ESP32 = OFF
 LWS_WITH_ZIP_FOPS = 0
 LWS_AVOID_SIGPIPE_IGN = OFF
 LWS_WITH_STATS = OFF
 LWS_WITH_SOCKS5 = OFF
 LWS_HAVE_SYS_CAPABILITY_H = 
 LWS_HAVE_LIBCAP = 
 LWS_WITH_PEER_LIMITS = 1
 LWS_HAVE_ATOLL = 1
 LWS_HAVE__ATOI64 = 
 LWS_HAVE_STAT32I64 = 
 LWS_HAS_INTPTR_T = 1
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /cc/libwebsockets/build
```
And then make:
```
root@gordon-MS-7A39:/cc/libwebsockets/build# make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
In file included from /cc/libwebsockets/lib/base64-decode.c:41:
/cc/libwebsockets/lib/stdio.h:195: error: parse error before "__wur"
/cc/libwebsockets/lib/stdio.h:195: warning: type defaults to `int' in declaration of `__wur'
/cc/libwebsockets/lib/stdio.h:195: warning: data definition has no type or storage class
/cc/libwebsockets/lib/stdio.h:209: error: parse error before "__wur"
/cc/libwebsockets/lib/stdio.h:209: warning: type defaults to `int' in declaration of `__wur'
/cc/libwebsockets/lib/stdio.h:209: warning: data definition has no type or storage class
/cc/libwebsockets/lib/stdio.h:215: error: parse error before "__wur"
/cc/libwebsockets/lib/stdio.h:215: warning: type defaults to `int' in declaration of `__wur'
/cc/libwebsockets/lib/stdio.h:215: warning: data definition has no type or storage class
/cc/libwebsockets/lib/stdio.h:228: error: parse error before "__wur"
/cc/libwebsockets/lib/stdio.h:273: error: parse error before "__wur"
/cc/libwebsockets/lib/stdio.h:273: warning: type defaults to `int' in declaration of `__wur'
/cc/libwebsockets/lib/stdio.h:273: warning: data definition has no type or storage class
```
There is many pages of that.

Last time on some of the builds I got this: (could not reproduce this time because of changes?)
```
/usr/lib/x86_64-linux-gnu/libz.a: could not read symbols: File format not recognized
```
I may not have the right paths to libraries for libuv, zlib, openssl, and mbedtls. How do I know whether a path should point inside LWS or outside? Libuv and SSL seems to be outside, while others (mbed, zlib) are inside. A search for a named file brings up multiple versions in different locations with different sizes and contents. How to choose the right one?
This project is a single computer board connected to a laptop for motor control. Is openssl or mbedtls the best choice?

Thanks for your insight into my myriad problems.

**Comment by lws-team** [comment]
Ehhh 

 - none of the paths should point inside lws

 - don't edit the toolchain file except to point it to the *toolchain*, that should be `CROSS_PATH` and `CMAKE_C[XX]_COMPILER`.  Give the lib and include paths on the cmake command line.

 - don't give paths for openssl if you will use mbed.  Both work, mbedtls should be smaller footprint, openssl is the more conservative choice.

 - `libuv include dir: /usr/local/lib` no... the include dir would be something like `/usr/local/include` if your cross-build of libuv was installed to `/usr/local`.

 - I wrote the first time:

>  For mbedtls, you will need -DLWS_WITH_MBEDTLS=1, something like this

> cmake .. -DLWS_WITH_MBEDTLS=1 -DLWS_MBEDTLS_LIBRARIES=xxxx -DLWS_MBEDTLS_INCLUDE_DIRS=xxxx -DCMAKE_TOOLCHAIN_FILE=../mytoolchainfile

> If you add things like lwsws you will also need libuv, like -DLWS_LIBUV_LIBRARIES=xxx -DLWS_LIBUV_INCLUDE_DIRS=xxx

This was good advice...

**Comment by lws-team** [comment]
# Building lws cross with mbedtls and lwsws example

Here are step by step instructions for cross-building the external projects you want to use and making lws use them.  I did all these steps and got a successful build, so they are known to work.

My toolchain lives in `/projects/aist-tb/arm-tc` and is named `arm-linux-gnueabihf`.  So you will need to adapt those to where your toolchain lives and its name where you see them here.

Likewise I do all this in /tmp but it has no special meaning, you can adapt that to somewhere else.

All "foreign" cross-built binaries are sent into `/tmp/cross` so they cannot be confused for 'native' x86_64 stuff on your host machine in /usr/[local/]....

## Prepare the cmake toolchain file

1) `cd /tmp`

2) `wget -O mytoolchainfile https://raw.githubusercontent.com/warmcat/libwebsockets/master/contrib/cross-arm-linux-gnueabihf.cmake` 

3) Edit `/tmp/mytoolchainfile` adapting `CROSS_PATH`, `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` to reflect your toolchain install dir and path to your toolchain C and C++ compilers respectively

## 1/4: Building libuv cross:

1) `export PATH=/projects/aist-tb/arm-tc/bin:$PATH`  Notice there is a **/bin** on the end of the toolchain path

2) `cd /tmp ; mkdir cross` we will put the cross-built libs in /tmp/cross

3) `git clone https://github.com/libuv/libuv.git` get libuv

4) `cd libuv`

5) `./autogen.sh`

```
+ libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
configure.ac:38: installing './ar-lib'
configure.ac:25: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
```
If it has problems, you will need to install `automake`, `libtool` etc.

6) `./configure  --host=arm-linux-gnueabihf --prefix=/tmp/cross`

7) `make && make install` this will install to `/tmp/cross/...`

8) `file /tmp/cross/lib/libuv.so.1.0.0`  Check it's really built for ARM
```
/tmp/cross/lib/libuv.so.1.0.0: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=cdde0bc945e51db6001a9485349c035baaec2b46, with debug_info, not stripped
```

## 2/4: Building zlib cross

1) `cd /tmp`

2) `git clone https://github.com/madler/zlib.git`

3) `CC=arm-linux-gnueabihf-gcc ./configure --prefix=/tmp/cross`
```
Checking for shared library support...
Building shared library libz.so.1.2.11 with arm-linux-gnueabihf-gcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
```

4)  `make && make install`
```
arm-linux-gnueabihf-gcc -O3 -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
...
rm -f /tmp/cross/include/zlib.h /tmp/cross/include/zconf.h
cp zlib.h zconf.h /tmp/cross/include
chmod 644 /tmp/cross/include/zlib.h /tmp/cross/include/zconf.h
```

5) `file /tmp/cross/lib/libz.so.1.2.11`  This is just to confirm we built an ARM lib as expected
```
/tmp/cross/lib/libz.so.1.2.11: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=6f8ffef84389b1417d2fd1da1bd0c90f748f300d, with debug_info, not stripped
```

## 3/4: Building mbedtls cross

1) `cd /tmp`

2) `git clone https://github.com/ARMmbed/mbedtls.git`

3) `cd mbedtls ; mkdir build ; cd build`

3) `cmake .. -DCMAKE_TOOLCHAIN_FILE=/tmp/mytoolchainfile -DCMAKE_INSTALL_PREFIX:PATH=/tmp/cross -DUSE_SHARED_MBEDTLS_LIBRARY=1`  mbedtls also uses cmake, so you can simply reuse the toolchain file you used for libwebsockets.  That is why you shouldn't put project-specific options in the toolchain file, it should just describe the toolchain.

4) `make && make install`

5) `file /tmp/cross/lib/libmbedcrypto.so.2.6.0`
```
/tmp/cross/lib/libmbedcrypto.so.2.6.0: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=bcca195e78bd4fd2fb37f36ab7d72d477d609d87, with debug_info, not stripped
```

## 4/4: Building libwebsockets with everything

1) `cd /tmp`

2) `git clone ssh://git@github.com/warmcat/libwebsockets`

3) `cd libwebsockets ; mkdir build ; cd build`

4)  (this is all one line on the commandline)
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=/tmp/mytoolchainfile \
-DCMAKE_INSTALL_PREFIX:PATH=/tmp/cross \
-DLWS_WITH_LWSWS=1 \
-DLWS_WITH_MBEDTLS=1 \
-DLWS_MBEDTLS_LIBRARIES="/tmp/cross/lib/libmbedcrypto.so;/tmp/cross/lib/libmbedtls.so;/tmp/cross/lib/libmbedx509.so" \
-DLWS_MBEDTLS_INCLUDE_DIRS=/tmp/cross/include \
-DLWS_LIBUV_LIBRARIES=/tmp/cross/lib/libuv.so \
-DLWS_LIBUV_INCLUDE_DIRS=/tmp/cross/include \
-DLWS_ZLIB_LIBRARIES=/tmp/cross/lib/libz.so \
-DLWS_ZLIB_INCLUDE_DIRS=/tmp/cross/include
```

3) `make && make install`

4) `file /tmp/cross/lib/libwebsockets.so.11`
```
/tmp/cross/lib/libwebsockets.so.11: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=81e59c6534f8e9629a9fc9065c6e955ce96ca690, with debug_info, not stripped
```

5) `arm-linux-gnueabihf-objdump -p /tmp/cross/lib/libwebsockets.so.11 | grep NEEDED`  Confirm that the lws library was linked against everything we expect (libm / libc are provided by your toolchain)
```
  NEEDED               libz.so.1
  NEEDED               libmbedcrypto.so.0
  NEEDED               libmbedtls.so.10
  NEEDED               libmbedx509.so.0
  NEEDED               libuv.so.1
  NEEDED               libm.so.6
  NEEDED               libc.so.6
```

You will also find the lws test apps in `/tmp/cross/bin`... to run lws on the target you will need to copy the related things from /tmp/cross... all the .so from /tmp/cross/lib and anything from /tmp/cross/bin you want.

**Comment by GordonMadden** [comment]
Wow, thanks for the detailed instructions. It really helps me understand cross-compilation. I kind of jumped into the middle of this project with little practical Linux experience.

I was able to compile the ZLIB libraries okay.

LIBUV had a problem:
```
root@gordon-MS-7A39:/cc/libuv# make && make install
  CC       src/unix/libuv_la-thread.lo
src/unix/thread.c:161:23: warning: use of C99 long long integer constant
src/unix/thread.c: In function `uv_cond_init':
src/unix/thread.c:572: warning: implicit declaration of function `pthread_condattr_setclock'
src/unix/thread.c:572: error: `CLOCK_MONOTONIC' undeclared (first use in this function)
src/unix/thread.c:572: error: (Each undeclared identifier is reported only once
src/unix/thread.c:572: error: for each function it appears in.)
Makefile:2197: recipe for target 'src/unix/libuv_la-thread.lo' failed
make: *** [src/unix/libuv_la-thread.lo] Error 1
```
and also MBEDTLS:
```
root@gordon-MS-7A39:/cc/mbedtls/build# make && make install
Scanning dependencies of target mbedcrypto_static
[  0%] Building C object library/CMakeFiles/mbedcrypto_static.dir/aes.c.o
cc1: error: unrecognized option `-Wextra'
cc1: error: unrecognized option `-Wdeclaration-after-statement'
library/CMakeFiles/mbedcrypto_static.dir/build.make:62: recipe for target 'library/CMakeFiles/mbedcrypto_static.dir/aes.c.o' failed
make[2]: *** [library/CMakeFiles/mbedcrypto_static.dir/aes.c.o] Error 1
CMakeFiles/Makefile2:374: recipe for target 'library/CMakeFiles/mbedcrypto_static.dir/all' failed
make[1]: *** [library/CMakeFiles/mbedcrypto_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
I am loathe to start tinkering with these libraries when they don't install properly. The errors appear to be problems with code inside .h, .c or object files. What is the proper way to investigate these types of errors? Is it usually a problem with the library itself or more likely something else?

I completely started this project over and built directories similar to your own. I was very careful to get all the command lines entered correctly for my set-up. If you could share any tips for troubleshooting these errors, I would appreciate it. I will try to figure it out in the meantime. Thanks!

**Comment by lws-team** [comment]
These are problems with your toolchain, probably the age of it, gcc 3.3 from your first post... that came out 12 years ago.

My tests were on gcc 6.2.  Update your toolchain to a modern gcc, delete ./build or do a `make clean` in each project and retry the broken builds.
