### ISSUE TITLE
null pointer dereference on connection with no network.

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#1044]
I'm testing a failure case where I've disconnected the network cable on my vm. windows 10. It gets a failure "getaddrinfo failed" calls the callback and then blows up here:

https://github.com/warmcat/libwebsockets/blob/10e2ef50380c1aeaf7a2d4ae934f0fb140279662/lib/libwebsockets.c#L518

the reason is vhost is null.

Not sure when that gets set, but I don't set it in my ccinfo call, and I can't find any docs that say I should.
This is my connect call:

  lws_client_connect_info ccinfo;
    memset(&ccinfo, 0, sizeof ccinfo);
    ccinfo.address = host.c_str();
    ccinfo.context = context;
    ccinfo.host = host.c_str(); // content of host header
    ccinfo.path = "/index.html"; // what url to hit
    ccinfo.port = port;
    ccinfo.protocol = protocol[0].name; 
    ccinfo.ssl_connection = 0; 

   connid = lws_client_connect_via_info(&ccinfo);

and it blows up. What am I doing wrong? 

The docs say "If you don't care about multiple "site" support, you can ignore it and lws will create a single default vhost at context creation time."

But I'm guessing it hasn't been created by the time this connection failure happens.

**Comment by nixomose** [comment]
I fixed the library to check for vhost==NULL and skip the callback() call if it is, and now it's blowing up somewhere else.
I have to think I'm doing something wrong. 
Do I maybe need to make an http protocol like I do in the server?

**Comment by lws-team** [comment]
You need at least a protocols[0] to take callbacks related to async client connection state and payload.  `lws_client_connect_via_info()` is nonblocking, if there's nothing immediately wrong it returns a wsi and the actual connection completes in the background.  Inside there --->

```
	wsi->vhost = i->vhost;
	if (!wsi->vhost)
		wsi->vhost = i->context->vhost_list;
```

So it will default to the first (default) vhost in the context for you if the i.vhost is NULL.

The problem is lws client connection is meaningless without a callback and you have no protocol / callback.

**Comment by nixomose** [comment]
sorry I didn't include all th pieces. I do have a protocol section:
```

  memset(&info, 0, sizeof info);
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.iface = NULL;
    info.protocols = protocol;
    info.ssl_cert_filepath = NULL; 
    info.ssl_private_key_filepath = NULL;
    info.extensions = NULL; // lws_get_internal_extensions();
    info.gid = -1;
    info.uid = -1;
    info.options = 0;

    protocol[0].name = TXT_SIRISD_PROTOCOL;
    protocol[0].callback = &ws_service_callback;
    protocol[0].per_session_data_size = sizeof(struct lwsc_connection_state *); // it's an object so we only store the pointer
    protocol[0].rx_buffer_size = 0;
    protocol[0].id = 0;
    protocol[0].user = NULL;
    // end of protocols list
    protocol[1].name = NULL;
    protocol[1].callback = NULL;

    context = lws_create_context(&info);
    if (context == NULL)
return Ret(-1, "Unable to create lws context.");

```

So I recall when creating a server, you have to have  an HTTP protocol as well as your websockets protocol. Is that true here too?

And everything works okay when the network is up, but when I remove the network cable from the vm, everything goes south.

**Comment by lws-team** [comment]
Hm you can't have a NULL vhost.  If you don't provide a vhost when you make the client connection, as I showed it will choose the default vhost created at context creation time.  So what you pasted

```
wsi->vhost->protocols->callback(wsi, LWS_CALLBACK_CLOSED_HTTP, 
```

shouldn't blow up at all.  You need to debug deeper into that and tell me what actually "blows up"... what is NULL or whatever.  Run it under gdb and let me know what the actual cause is.

**Comment by nixomose** [comment]
I'm out of the office today, I'll try and reproduce it tomorrow, but it must have something to do with this failure case of the network not being there, because that's the only time it happens (that I've found so far) when there's a network connection, it all works fine.

**Comment by nixomose** [comment]
sorry, I'm not going to be able to get to this for a few days. for right now I've if'd out the dereference if vhost is null, but I'll try to get to this as soon as I can. I want to make sure we all agree what's going on if I'm doing something wrong or not.

**Comment by nixomose** [comment]
yeah a few days turned into  a lot more days than I thought.
We added ssl support to our connections, and haven't seen the problem since, so I'm going to deal with other bigger problems, and reopen this if it comes up again.

**Comment by lws-team** [comment]
If you see that again or any other kind of segfault type exception, a backtrace is really valuable to try to understand where it's coming from.  Especially as in that case, it doesn't seem to have a legit way to occur, doesn't occur on the test apps and isn't reproducible...
