### ISSUE TITLE
localhost does not work without internet connection

### ISSUE THREAD

**Issue by Globik** [warmcat/libwebsockets#1046]
I am testing lws websocket server. With client side on browser google chrome. So always websocket is in 'CONNECTING' state. Node.js server works OK without internet connection on localhost but is not the case with lws websocket server. Is it special for lws? Or in opts I should explicitly to allow loopback interface?
 With internet connectivity lws works like a charm on localhost though.

**Comment by lws-team** [comment]
If what it means is your default route is there, but doesn't work, you can force lws to use a different nework interface at vhost creation time.  There are two levels of that info.iface binds the listen socket and optionally info.bind_iface does the accepted sockets too

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L2301
