### ISSUE TITLE
Listening port is busy

### ISSUE THREAD

**Issue by Globik** [warmcat/libwebsockets#1047]
When I'm starting node.js server on port 5000(on localhost), then lws server starting fails on the same port 5000 to listen.
Is it possible make friendship among third party http-server and lws websocket server?
Let's say can I use the same port with libmicrohttpd and libwebsockets at same time?

**Comment by lws-team** [comment]
It should fail.  How should it have magically worked?

You can integrate lws to another app's listen socket by "adopting" sockets it accepted into lws, using the lws_adopt_...() apis.  But that means integrating lws into the other app somehow.
