### ISSUE TITLE
What kind of http-server is libwebsockets???

### ISSUE THREAD

**Issue by Globik** [warmcat/libwebsockets#1048]
Can lws as a web http server handle post, get requests??? Give a static files ?  Is there template engine? A router mechanism?

**Comment by lws-team** [comment]
GET / POST / Static files... of course.  Try libsockets-teset-server it demos all those plus ws protocols.  Here in the protocol plugin behind thebPOST demo

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c

Template engine... lws supports cgi (eg to php or whatever) and proxying with limited rewrite.  You can write a protocol plugin and bind it to somewhere in the url space to do produce whatever you want dynamically.

"router mechanism" not sure what that would be, so no.
