### ISSUE TITLE
SegFaults with libwebsockets v2.3-stable when closing (return -1 in callback) a websocket connection

### ISSUE THREAD

**Issue by rtcote** [warmcat/libwebsockets#1053]
Observed these occurrences of segmentation faults in libwebsockets v2.3-stable when closing (return -1 in callback) a websocket connection.  It's not a consistent behavior and it seems to happen when the connection can not be made to an end point for a lengthy period of time (5+ minutes).  Any ideas as to what is causing this behavior?  Any help would be greatly appreciated.  Thank you! Russell

[New LWP 26304]
[New LWP 26301]
[New LWP 26303]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Program terminated with signal 11, Segmentation fault.
#0  0x00007fcbed457238 in lws_header_table_force_to_detachable_state () from /usr/local/lib/libwebsockets.so.11
(gdb) bt
#0  0x00007fcbed457238 in lws_header_table_force_to_detachable_state () from /usr/local/lib/libwebsockets.so.11
#1  0x00007fcbed451ba1 in lws_close_free_wsi () from /usr/local/lib/libwebsockets.so.11
#2  0x00007fcbed463c87 in lws_server_socket_service () from /usr/local/lib/libwebsockets.so.11
#3  0x00007fcbed454ade in lws_service_fd_tsi () from /usr/local/lib/libwebsockets.so.11
#4  0x00007fcbed461b6b in _lws_plat_service_tsi () from /usr/local/lib/libwebsockets.so.11
#5  0x0000000000406889 in ws_if_thread (arg=<optimized out>) at src/websocketIf.c:1120  <-- lws_service(lws_ctx, 400)
#6  0x00007fcbecfcbdc5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fcbeccfa73d in clone () from /lib64/libc.so.6

[New LWP 30698]
[New LWP 30695]
[New LWP 30697]
warning: Corrupted shared library list: 0x26902030 != 0x0
warning: Corrupted shared library list: 0x26902030 != 0x0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Program terminated with signal 11, Segmentation fault.
#0  0x00007fe84d3e491a in lws_hdr_simple_create () from /usr/local/lib/libwebsockets.so.11
(gdb) bt
#0  0x00007fe84d3e491a in lws_hdr_simple_create () from /usr/local/lib/libwebsockets.so.11
#1  0x00007fe84d3eae7f in lws_client_connect_via_info2 () from /usr/local/lib/libwebsockets.so.11
#2  0x00007fe84d3e4531 in lws_header_table_detach () from /usr/local/lib/libwebsockets.so.11
#3  0x00007fe84d3de3d4 in lws_free_wsi () from /usr/local/lib/libwebsockets.so.11
#4  0x00007fe84d3df016 in lws_close_free_wsi () from /usr/local/lib/libwebsockets.so.11
#5  0x00007fe84d3e19ab in lws_service_fd_tsi () from /usr/local/lib/libwebsockets.so.11
#6  0x00007fe84d3eeb6b in _lws_plat_service_tsi () from /usr/local/lib/libwebsockets.so.11
#7  0x0000000000406889 in ws_if_thread (arg=<optimized out>) at src/websocketIf.c:1120
#8  0x00007fe84cf58dc5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fe84cc8773d in clone () from /lib64/libc.so.6

**Comment by lws-team** [comment]
Please rebuild libwebsockets with debug info

```
 $ cmake .. -DCMAKE_BUILD_TYPE=DEBUG
```

so the backtrace will be useful.

Lws is being called from a single thread only?

**Comment by lws-team** [comment]
... also try running your app under valgrind.

**Comment by rtcote** [comment]
Will do on building libwebsockets with debug info.

Yes, lws API is being called only in a single thread (learned that lesson awhile back)

I'll see if I can reproduce under valgrind as well. I normally test  with both memcheck & helgrind prior to App release and have not notice anything in the previous outputs.

Thanks!
Russell

**Comment by lws-team** [comment]
Anything happening with this?  Going by the

```
warning: Corrupted shared library list: 0x26902030 != 0x0
warning: Corrupted shared library list: 0x26902030 != 0x0
```

it might be something trashing the heap is the underlying problem.  Valgrind should shine some light if so.

**Comment by lws-team** [comment]
Welp there's nothing I can do unless you send more info, so closing.
