### ISSUE TITLE
How to compile for Win64 with Visual Studio?

### ISSUE THREAD

**Issue by iUltimateLP** [warmcat/libwebsockets#1058]
Hey again, before I can come back to my initial issue (https://github.com/warmcat/libwebsockets/issues/1052) I wonder how can I compile it for x64 with VS? I created the project using cmake, but Visual Studio only shows the "Win32" platform there. I created a x64 one, but that results in a lot of errors, saying "adler32.obj" and "base64-decode.obj" are in conflict ("module-computer type "x64" is in confligt with the target computer type "x86"")

Thanks!

**Comment by iUltimateLP** [comment]
Looks like CMake put a stray /machine:x86 in there where none should belong. Allthough it compiles, there are a lot of warnings, but I guess thats normal?

**Comment by lws-team** [comment]
1) CMake wants you to tell it which "generator" to use with -G

```
Generates Visual Studio 12 (VS 2013) project files.

It is possible to append a space followed by the platform name to create project files for a specific target platform. E.g. “Visual Studio 12 2013 Win64” will create project files for the x64 processor; “Visual Studio 12 2013 ARM” for ARM.

For compatibility with CMake versions prior to 3.0, one may specify this generator using the name “Visual Studio 12” without the year component.
```

https://cmake.org/cmake/help/v3.0/generator/Visual%20Studio%2012%202013.html

2) The warnings about zlib repeated symbols are "normal", they also appear on Appveyor, eg

https://ci.appveyor.com/project/lws-team/libwebsockets/build/1.0.2068/job/g8kx0dvuyb5yn3wo

I would like to get rid of them, but the zlib integration was contributed, and I don't know what was repeated.  Likewise of the remaining warnings I see there, complaining that `open()` etc is undefined, the correct includes are used and that doesn't occur on any other platform.  At least on appveryor / 32-bit, there's only one "real" warning about a single signed / unsigned comparison atm.

If you see more warnings on 64-bit than appear on Appveyor, please paste them here I will look at them.

**Comment by lws-team** [comment]
About the warnings on windows builds, on master

 - I fixed the zlib and other one-line warnings on the 32-bit Appveyor builds

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:01:00.58
```

 - I added a 64-bit build to Appveyor, including HTTP2, OpenSSL and the plugins
 - 0 warnings or errors on the 64-bit Appveyor builds

```
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:58.95
```
