### ISSUE TITLE
use libwebsockets dll on windows, link error

### ISSUE THREAD

**Issue by zhoualbeart** [warmcat/libwebsockets#1060]
my environment is 
system: windows 10 Enterprise
vs version: 2010

I compile the websockets.dll follow the README.build.md with VS2010 , and generate websockets.dll and websockets.lib file successful.
But ,when I use the lib file to call the libwebsockets library function , it prompt "error 2019 unresolved external symbol _lws_client_connect_via_info" errors.

It seems can not find my lib file ,but I had put the websockets.lib into my project folder, and set the websockets.lib in my project property

Please help me with solution.

**Comment by lws-team** [comment]
It is just `lws_client_connect_via_info` you get errors about, or loads of things?  If loads of things, it sounds like you have not successfuly linked againts the libwebsockets dll.

What were your cmake options?  Althight the client stuff is enabled by default, t's possible to disable the build of client functionality in lws, with, eg, `LWS_WITHOUT_CLIENT` and make this problem.

**Comment by zhoualbeart** [comment]
All the dll function get errors.

I use the default cmake options. And the LWS_WITHOUT_CLIENT option is disable.

**Comment by lws-team** [comment]
I think this is to do with you importing the library into your app, not with lws.

Does the lib contain the symbols?

https://stackoverflow.com/questions/15805738/msvc-list-symbols-inside-a-static-lib-file

Does the DLL contain them?

https://www.nirsoft.net/utils/dll_export_viewer.html

Then the problem is how you are (or aren't) binding your app to the lib / dll...

**Comment by zhoualbeart** [comment]
I use dumpbin -exports lib (or dll) to see the exports section.
It seems the dll and the lib file do contain the function I called.

Here is the section of  output when I use dumpbin -exports websockets.dll (websockets.lib)

C:\Users\clouder\Documents\Visual Studio 2010\Projects\testnewlib\testnewlib>dumpbin -exports websockets.dll
Microsoft (R) COFF/PE Dumper Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file websockets.dll

File Type: DLL

  Section contains the following exports for websockets.dll

    00000000 characteristics
    59E6C7CB time date stamp Wed Oct 18 11:17:31 2017
        0.00 version
           1 ordinal base
         236 number of functions
         236 number of names

    ordinal hint RVA      name

          1    0 00004E40 _lws_change_pollfd
          2    1 00001F10 _lws_log
          3    2 00001E90 _lws_logv
          4    3 00011550 _lws_plat_file_close
          5    4 00011410 _lws_plat_file_open
          6    5 000115B0 _lws_plat_file_read
          7    6 00011590 _lws_plat_file_seek_cur
          8    7 00011620 _lws_plat_file_write
          9    8 00010940 _lws_plat_service_tsi
         10    9 00002190 _lws_rx_flow_control
         11    A 00002850 _snprintf
         12    B 00010700 delete_from_fd
         13    C 00015FE0 handshake_0405
         14    D 00010680 insert_wsi
         15    E 00004FA0 insert_wsi_socket_into_fds
         16    F 00001740 interface_to_sa
         17   10 0002D000 log_level
         18   11 00010480 lws_SHA1
         19   12 00009C80 lws_add_http_header_by_name
         20   13 00009D60 lws_add_http_header_by_token
         21   14 00009DB0 lws_add_http_header_content_length
         22   15 00009E90 lws_add_http_header_status
         23   16 00007970 lws_add_wsi_to_draining_ext_list
         24   17 00012480 lws_adopt_descriptor_vhost
         25   18 000128E0 lws_adopt_socket
         26   19 00012AC0 lws_adopt_socket_readbuf
         27   1A 00012790 lws_adopt_socket_vhost
         28   1B 00012B00 lws_adopt_socket_vhost_readbuf
         29   1C 0000D750 lws_alloc_vfs_file
         30   1D 000168D0 lws_any_extension_handled
         31   1E 00001130 lws_b64_decode_string
         32   1F 00001000 lws_b64_encode_string
         33   20 00001940 lws_callback_all_protocol
         34   21 00001A00 lws_callback_all_protocol_vhost
         35   22 00008760 lws_callback_http_dummy
         36   23 00005270 lws_callback_on_writable
         37   24 000054D0 lws_callback_on_writable_all_protocol
         38   25 00005380 lws_callback_on_writable_all_protocol_vhost
         39   26 00001AD0 lws_callback_vhost_protocols
         40   27 000108C0 lws_cancel_service
         41   28 00010900 lws_cancel_service_pt
         42   29 00001E40 lws_canonical_hostname
         43   2A 00005160 lws_change_pollfd
         44   2B 00002230 lws_check_utf8
         45   2C 00014360 lws_chunked_html_process
         46   2D 00002100 lws_clear_child_pending_on_writable
         47   2E 0000CDC0 lws_client_connect
         48   2F 0000BEC0 lws_client_connect_2
         49   30 0000CD00 lws_client_connect_extended
         50   31 0000C830 lws_client_connect_via_info
         51   32 0000CB90 lws_client_connect_via_info2
         52   33 0000A4F0 lws_client_http_body_pending
         53   34 0000A540 lws_client_interpret_server_handshake
         54   35 0000CE80 lws_client_rx_sm
         55   36 0000BAE0 lws_client_socket_service
         56   37 00003280 lws_close_free_wsi
         57   38 00002AF0 lws_close_free_wsi_final
         58   39 00002130 lws_close_reason
         59   3A 00008C40 lws_context_deprecate
         60   3B 000094C0 lws_context_destroy


=============================================================

C:\Users\clouder\Documents\Visual Studio 2010\Projects\testnewlib\testnewlib>dumpbin -exports websockets.lib
Microsoft (R) COFF/PE Dumper Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file websockets.lib

File Type: LIBRARY

     Exports

       ordinal    name

                  _lws_change_pollfd
                  _lws_log
                  _lws_logv
                  _lws_plat_file_close
                  _lws_plat_file_open
                  _lws_plat_file_read
                  _lws_plat_file_seek_cur
                  _lws_plat_file_write
                  _lws_plat_service_tsi
                  _lws_rx_flow_control
                  _snprintf
                  delete_from_fd
                  handshake_0405
                  insert_wsi
                  insert_wsi_socket_into_fds
                  interface_to_sa
                  log_level
                  lws_SHA1
                  lws_add_http_header_by_name
                  lws_add_http_header_by_token
                  lws_add_http_header_content_length
                  lws_add_http_header_status
                  lws_add_wsi_to_draining_ext_list
                  lws_adopt_descriptor_vhost
                  lws_adopt_socket
                  lws_adopt_socket_readbuf
                  lws_adopt_socket_vhost
                  lws_adopt_socket_vhost_readbuf
                  lws_alloc_vfs_file
                  lws_any_extension_handled
                  lws_b64_decode_string
                  lws_b64_encode_string
                  lws_callback_all_protocol
                  lws_callback_all_protocol_vhost
                  lws_callback_http_dummy
                  lws_callback_on_writable
                  lws_callback_on_writable_all_protocol
                  lws_callback_on_writable_all_protocol_vhost
                  lws_callback_vhost_protocols
                  lws_cancel_service
                  lws_cancel_service_pt
                  lws_canonical_hostname
                  lws_change_pollfd
                  lws_check_utf8
                  lws_chunked_html_process
                  lws_clear_child_pending_on_writable
                  lws_client_connect
                  lws_client_connect_2
                  lws_client_connect_extended
                  lws_client_connect_via_info
                  lws_client_connect_via_info2
                  lws_client_http_body_pending
                  lws_client_interpret_server_handshake
                  lws_client_rx_sm
                  lws_client_socket_service
                  lws_close_free_wsi
                  lws_close_free_wsi_final
                  lws_close_reason
                  lws_context_deprecate
                  lws_context_destroy

**Comment by lws-team** [comment]
Then I don't think there is any problem with lws... the symbol your app has linking problems with is there

```
     50   31 0000C830 lws_client_connect_via_info
```

> It seems can not find my lib file ,but I had put the websockets.lib into my project folder, and set the websockets.lib in my project property

I don't think that's enough.  You will have to put the .lib somewhere else in your project properties.  Googling gets this

https://msdn.microsoft.com/en-us/library/ba1z7822.aspx

is that what you are doing?

**Comment by zhoualbeart** [comment]
I am doing the same as https://msdn.microsoft.com/en-us/library/ba1z7822.aspx tell us to do

To add .lib files as linker input in the development environment
Open the project's Property Pages dialog box. For details, see Setting Visual C++ Project Properties.
Click the Linker folder.
Click the Input property page.
Modify the Additional Dependencies property.(I add websockets.lib to Additional Dependencies property )

I just set this property. Does any other properties need to set?

**Comment by lws-team** [comment]
I have no idea, I don't use windows.  I think you need to ask somewhere where they support VS questions,

**Comment by zhoualbeart** [comment]
OK.. Thanks you!
