### ISSUE TITLE
Loop Problem when SSL connect error on lws 1.2 

### ISSUE THREAD

**Issue by jjiego** [warmcat/libwebsockets#1063]
Hello, all.
I used libwebsockets v 1.2 with Client Side.
Below Loop is polling for ACRWebSocket callback and response.

`    // Do Service Loop
    while (m_bStopThread == false)
    {
        if(m_bIsPaused == false)
        {
            if (g_wsi == NULL && GetConnectAvailable())
            {
                g_wsi = this->get_connection();
                SetConnectAvailable(false);
            }

            if (m_context && g_wsi)
            {
                libwebsocket_service(m_context, m_nTimeout);    // service with timeout - will call receive callback
            }
            else
            {
                usleep(SLEEP_FOR_CONN_MS * MSEC_TO_USEC);
            }
        }
        else
        {
            usleep(SLEEP_FOR_CONN_MS * MSEC_TO_USEC);
            
            // Re-initialize m_context instance
            if (g_wsi != NULL) 
            {
                mutexWsi.lock();    // lock between send and t_main threads
                libwebsocket_context_destroy(m_context);
                m_context = NULL;    
                g_wsi = NULL;
                mutexWsi.unlock();
            }
        }
    }`

In normal situation, It works properly.
But, I got critical ERROR when I modified Server status.
You can check below error with "SSL Connect Error"

lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0]
WsServiceCallback(564) > reason = [26]
lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0]
lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0]
WsServiceCallback(564) > reason = [26]
lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0]
WsServiceCallback(564) > reason = [26]
lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0]
WsServiceCallback(564) > reason = [26]
lws_print(660) > lws[lv:1]:SSL connect error 336031996: error:00000000:lib(0):func(0):reason(0)
t_Main(493) > nRetLWSService = [0] 

Because, "SSL Connect error" of lws v1.2 never gives error callback.

* lws_client_socket_service () : client.c of lws v1.2
`   if (n <= 0) {
    /*
     * retry if new data comes until we
     * run into the connection timeout or win
     */
    lwsl_err("SSL connect error %lu: %s\n", 
     ERR_get_error(),
     ERR_error_string(ERR_get_error(),
           (char *)context->service_buffer));
    return 0;
   } 
`

* lws_client_socket_service () : client.c of lws v1.7
` if (n <= 0) {
     /*
      * retry if new data comes until we
      * run into the connection timeout or win
      */
     n = ERR_get_error();
     if (n != SSL_ERROR_NONE) {
      lwsl_err("SSL connect error %lu: %s\n",
        n, ERR_error_string(n, sb));
      goto bail3;
     }
    }
 
....
bail3:
  lwsl_info("closing conn at LWS_CONNMODE...SERVER_REPLY\n");
  wsi->context->protocols[0].callback(wsi,
    LWS_CALLBACK_CLIENT_CONNECTION_ERROR,
    wsi->user_space, NULL, 0);
  lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS);
  return -1;
`

SSL Error of lws v1.7 is handled with "bail3".
Is it bug ? or any handling way for SSL Error ?
Please give me some advice.
Thanks :)

**Comment by lws-team** [comment]
> Please give me some advice.

Update to a newer lws... v1.2 was 4.5 years ago...  if you still have problems I'll try to help.
