### ISSUE TITLE
Compilation issue in getifaddrs.c: LWS_HAVE_GETIFADDRS is undefined

### ISSUE THREAD

**Issue by aSebastianMueller** [warmcat/libwebsockets#1065]
I cross compiled with crosstools-mips-gcc-4.6-linux-3.4-uclibc-0.9.32-binutils-2.21
and got following error.

**[ 50%] Building C object CMakeFiles/websockets.dir/lib/misc/getifaddrs.c.o
/projects/dlna/nflc/src/ext/libwebsockets/lib/misc/getifaddrs.c:46:6: error: "LWS_HAVE_GETIFADDRS" is not defined [-Werror=undef]
cc1: all warnings being treated as errors**

Default setting is -Werror=undef. I can change this but LWS_HAVE_GETIFADDRS will be always undefined.

Moving #if !LWS_HAVE_GETIFADDRS below line 47 fixed this issue for me.

...
#include "private-libwebsockets.h"

#if !LWS_HAVE_GETIFADDRS
...

**Comment by lws-team** [comment]
Thanks... I think that check itself if not needed any more, CMakeLists.txt will just not include the file for build if LWS_HAVE_GETIFADDRS is set, and the check covers the whole file.  -Wundef is right to complain about it as well, it's checking it as a bool when it's either defined or not... gcc pretends it's 0 if not defined normally.

I pushed a patch removing the check on master and v2.4-stable.
