### ISSUE TITLE
Cant install libwebsockets

### ISSUE THREAD

**Issue by ugljanin** [warmcat/libwebsockets#1067]
Hi,

I am installing libwesocket on centos7 using this

```
yum install wget mercurial cmake openssl-devel c-ares-devel libuuid-devel
yum install git gcc gcc-c++

git clone https://github.com/warmcat/libwebsockets.git

cd libwebsockets
mkdir build
cd build
cmake .. -DLIB_SUFFIX=64
make
make install
```

but, when I type make I get error

```
root@server [/libwebsockets/build]# make
[  1%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
cc1: warnings being treated as errors
/libwebsockets/lib/libwebsockets.c: In function ‘lws_socket_bind’:
/libwebsockets/lib/libwebsockets.c:2268: error: dereferencing pointer ‘sin.84’ does break strict-aliasing rules
/libwebsockets/lib/libwebsockets.c:2268: note: initialized from here
make[2]: *** [CMakeFiles/websockets.dir/lib/libwebsockets.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
```

How can I fix it?

**Comment by lws-team** [comment]
libwebsockets.c:2268 says this at the minute

```
port = ntohs(((struct sockaddr_in *) &sin)->sin_port);
```

with gcc7.2 from Fedora 27 beta, if I give it `-fno-strict-aliasing` or `-fstrict-aliasing` it doesn't make any error either way.  When I met this kind of problem before some years ago, the (over-fragile) compiler was satisfied if I broke out the cast into a temp var, eg,

```
diff --git a/lib/libwebsockets.c b/lib/libwebsockets.c
index 64f695b3..d84e6e7c 100644
--- a/lib/libwebsockets.c
+++ b/lib/libwebsockets.c
@@ -2265,7 +2265,10 @@ lws_socket_bind(struct lws_vhost *vhost, lws_sockfd_type sockfd, int port,
                                  ntohs(((struct sockaddr_in6 *) &sin)->sin6_port) :
                                  ntohs(((struct sockaddr_in *) &sin)->sin_port);
 #else
-               port = ntohs(((struct sockaddr_in *) &sin)->sin_port);
+               {
+                       struct sockaddr_in *sain = (struct sockaddr_in *)&sin;
+                       port = ntohs(sain->sin_port);
+               }
 #endif
 #endif
 
```

does that help?

**Comment by lws-team** [comment]
Well I pushed that change on master + v2.4-stable, installed CentOS 7 in a VM, and confirmed I can build it fine.

**Comment by ugljanin** [comment]
I made mistake, it is not working on Centos6, I have tested it on centos7 and there it works.
After this change you made, I am able to go further but I still have error but on different percentage

`-- Configuring done
-- Generating done
-- Build files have been written to: /libwebsockets/build
root@server [/libwebsockets/build]# make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o
[  2%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  4%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
cc1: warnings being treated as errors
/libwebsockets/lib/libwebsockets.c: In function ‘lws_socket_bind’:
/libwebsockets/lib/libwebsockets.c:2270: error: dereferencing pointer ‘sain’ does break strict-aliasing rules
/libwebsockets/lib/libwebsockets.c:2269: note: initialized from here
make[2]: *** [CMakeFiles/websockets.dir/lib/libwebsockets.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by lws-team** [comment]
Hmmm I installed Centos **6** in a VM and adapted the fix, after that it builds.  Please try latest master or v2.4-stable.

**Comment by ugljanin** [comment]
It is now working, thanks for help
