### ISSUE TITLE
Problems building and running LWS on ARM board

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1069]
I am developing a project for the TS-7800-V2 board which runs Linux Debian. I have LWSWS (web server) running in Ubuntu with plugins, but I am having trouble getting it to run on the  board, both as a cross-compiled .exe and as a project built entirely on the board. The dev board is an upgrade of a board (7800 original) I was using earlier. 

**CROSS COMPILING**
I built the cross set-up in Ubuntu and built the test apps. I compressed the directory that contains lwsws, the test.html file, shared libraries, etc. and then copied the JSON conf files (conf and test-server) to the board's /etc/lwsws directory. But trying to run any of the test apps (even "hello") gives the following:
```
root@ts7800-v2:/cc/cross/bin# ./lwsws 
-bash: ./lwsws: No such file or directory
```
I transferred the entire "cc" directory (see terminal entry above) over to the board. By transferring it in a compressed state, I was able to keep the sym links for the the libraries. Nothing in the build looked out of place and was similar to the build on Ubuntu. The lwsws exe auto completes when I type it in the terminal, so it is there. **_What else should I look at to fix this problem?_**

**COMPILATION ON DEV BOARD**
This board has a lot of space on it, so I built LWS on the board in a different directory away from the cross build. I also built it after the cross build, so I'm sure this build did not interfere with the cross.
I built all the libraries (zlib, libuv, mbedtls) on the board and then LWS itself. Everything was fine until "make && make install' on LWS.
```
-- Build files have been written to: make && make install
[  1%] Building C object CMakeFiles/websockets_shared.dir/lib/misc/lejp.c.o
/libwebsockets/lib/misc/lejp.c: In function ��‘lejp_parse��’:
/libwebsockets/lib/misc/lejp.c:248:33: error: comparison is always false due to]
             LEJPCB_VAL_STR_END) < 0) {
                                 ^
cc1: all warnings being treated as errors
CMakeFiles/websockets_shared.dir/build.make:1022: recipe for target 'CMakeFilesd
make[2]: *** [CMakeFiles/websockets_shared.dir/lib/misc/lejp.c.o] Error 1
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/websockets_shared.dir/ad
make[1]: *** [CMakeFiles/websockets_shared.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
It says 1% now, but originally it was about 32% of the way through the make and install. Should I run cmake to turn off the JSON libraries. I thought it might affect lwsws's ability to read its own configuration files. It looks like the problem is internal to the library file? **_Please let me know what to look for to fix this type of problem._**

Going forward, I would prefer to continue to build the project on the board, since there is room. If this is not advisable for some reason, I would appreciate input on that as well. Thank you!

**Comment by lws-team** [comment]
Hm your first problem is just a general build problem on your side I think.

Use `file` and `ldd` to check the file you built is what you think it is, and that it can find its dependent libs.  Did you run `ldconfig` / are the libs installed in a place `/etc/ld.so.conf` knows about?  File has +x perms?

The second problem is caused because on your native toolchain on that board, it decided that char will not be signed by default.  On your cross toolchain, like pretty much every C compiler everywhere else, the compiler defaults to chars being signed so no problems.

I pushed a patch on master + v2.4-stable explicitly changing the return type involved there from `char` to `signed char`... it won't make any difference unless your compiler defaults to unsigned as in your case.

Building native has its advantages and disadvantages like building cross.  Although native may seem "easier", unless you are building against a normal distro with packages you will find it difficult to capture and repeat what you are doing... the native rootfs built by hand or crosstool etc is a mismash of unregulated bits from different places, some cross some native some "by hand" direct on the rootfs.  This is a recipe for unrepeatable results.

Enforcing the build process to be entirely captured somehow on another machine may not seem like your biggest problem right now, but this is critical for a manageable and updateable result and avoiding something that "works but you dare not touch and cannot repeat".  Whether you do that cross or native doesn't really matter but cross more naturally lends itself to forcing you to have the build assets on the build machine.

**Comment by GordonMadden** [comment]
![image](https://user-images.githubusercontent.com/25450928/31966595-0486f77a-b8c0-11e7-8e8c-f6f3388b1232.png)

**Comment by GordonMadden** [comment]
Thanks! This is great stuff. I wish I knew now what I'm going to know when this project is finished.

**Comment by GordonMadden** [comment]
Is this an issue resulting from the patch? It's a signed-unsigned thing is why I ask.
```
[ 90%] Built target protocol_client_loopback_test
[ 91%] Built target protocol_lws_meta
[ 92%] Building C object CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/o
/libwebsockets/plugins/ssh-base/sshd.c: In function ��‘lws_callback_raw_sshd��’:
/libwebsockets/plugins/ssh-base/sshd.c:2190:10: error: comparison between signe]
    if (n > (int)sizeof(buf) - LWS_PRE) {
          ^
cc1: all warnings being treated as errors
CMakeFiles/protocol_lws_ssh_base.dir/build.make:62: recipe for target 'CMakeFild
make[2]: *** [CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/sshd.c.o] E1
CMakeFiles/Makefile2:876: recipe for target 'CMakeFiles/protocol_lws_ssh_base.dd
make[1]: *** [CMakeFiles/protocol_lws_ssh_base.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
**Here is where the error is:** line 2190 is "if (n > (int)sizeof(buf) - LWS_PRE) {"
```
case SSH_WT_UA_PK_OK:
			/*
			 *  The server MUST respond to this message with
			 *  either SSH_MSG_USERAUTH_FAILURE or with the
			 *  following:
			 *
			 *    byte      SSH_MSG_USERAUTH_PK_OK
			 *    string    public key alg name from the request
			 *    string    public key blob from the request
      			 */
			n = 74 + pss->ua->pubkey_len;
			if (n > (int)sizeof(buf) - LWS_PRE) {
				lwsl_notice("pubkey too large\n");
				goto bail;
			}
			ps = sshd_zalloc(n);
			if (!ps)
				goto bail;
			pp = ps + 5;
			*pp++ = SSH_MSG_USERAUTH_PK_OK;
			if (lws_cstr(&pp, pss->ua->alg, 64)) {
				free(ps);
				goto bail;
			}
			lws_p32(pp, pss->ua->pubkey_len);
			pp += 4;
			memcpy(pp, pss->ua->pubkey, pss->ua->pubkey_len);
			pp += pss->ua->pubkey_len;

			/* we no longer need the UA now we judged it */
			lws_ua_destroy(pss);

			goto pac;
```

**Comment by lws-team** [comment]
I pushed a fix on master making LWS_PRE a signed int.

**Comment by GordonMadden** [comment]
Native and cross-compile choked on this one. It's getting better though!
```
[ 93%] Building C object CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/o
/libwebsockets/plugins/ssh-base/kex-25519.c: In function ��‘ed25519_key_parse��:
/libwebsockets/plugins/ssh-base/kex-25519.c:149:22: error: comparison between s]
  if ((p - op) + publ >= (int)len)
                      ^~
/libwebsockets/plugins/ssh-base/kex-25519.c:169:22: error: comparison between s]
  if ((p - op) + publ != (int)len)
                      ^~
```

```
Scanning dependencies of target protocol_lws_ssh_base
[ 85%] Building C object CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/sshd.c.o
[ 85%] Building C object CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/telnet.c.o
[ 86%] Building C object CMakeFiles/protocol_lws_ssh_base.dir/plugins/ssh-base/kex-25519.c.o
/cc/libwebsockets/plugins/ssh-base/kex-25519.c: In function 'ed25519_key_parse':
/cc/libwebsockets/plugins/ssh-base/kex-25519.c:149:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
/cc/libwebsockets/plugins/ssh-base/kex-25519.c:169:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

**Comment by lws-team** [comment]
These errors don't appear on my Fedora gcc, or Appveyor or Travis... but they don't seem to be wrong.  I adapted the code around this and updated master again.

**Comment by GordonMadden** [comment]
You, sir, have triumphed! Thank you!
![image](https://user-images.githubusercontent.com/25450928/32008330-cd791046-b960-11e7-9421-564345716b38.png)
