### ISSUE TITLE
2.4 release: lib/server/cgi.c:242:10:  'm' may be used uninitialized in this function

### ISSUE THREAD

**Issue by karlp** [warmcat/libwebsockets#1071]
Build failure on some targets for the 2.4 release.  (not all!)

Compile log here: http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a9_neon/packages/libwebsockets/full/compile.txt
also on http://downloads.lede-project.org/snapshots/faillogs/aarch64_cortex-a53/packages/libwebsockets/full/compile.txt for instance

mips and x86 targets seem to build it ok...

**Comment by lws-team** [comment]
I pushed a workaround on master / v2.4-stable... it's probably better to follow the most recent -stable branch than use a point release.  Unfortunately it has always been we get most bug reports only after we make a release, not before, even though I do ask :-(

**Comment by karlp** [comment]
I feel your pain, but unfortunately, we're simply downstream users, we don't even _look_ for things until there's a new release I'm sorry.

**Comment by lws-team** [comment]
No worries... it wasn't directed at you, I was generally explaining why we are constantly in the embarrassing situation of patched releases like that, and why following -stable will work around it.
