### ISSUE TITLE
Atribute certificate

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1072]
Hi, libwebsocket is running fine for me, and thanks to all.

I have one query regarding Attribute certificate. 
Is there any support of attribute certificate to transfer from websocket client to server ?

**Comment by lws-team** [comment]
I think what you are asking would be more commonly said as, "are client certs supported".

Yes, they are supported.  In the test server, you can configure for them like this

```
 $ libwebsockets-test-server -s -A ca.crt -K server.key -C server.crt -v
```

the `-v` means that lws must receive from the client a client cert signed by the same CA given in -A, or the connection will be terminated.
