### ISSUE TITLE
LWS_CALLBACK_CLOSED problem

### ISSUE THREAD

**Issue by 445615105** [warmcat/libwebsockets#1078]
hi,I use libwebsocket v1.7 on ios, when I shut down my wifi, after about 30 seconds I get LWS_CALLBACK_CLOSED.On the windows or android, the time may only 3-4 seconds.Is it a problem?Can I fix it? THX

**Comment by lws-team** [comment]
... what would "fix" look like for that?  Fix IOS so it informs us earlier?
