### ISSUE TITLE
Getting error C2059: syntax error: '<parameter-list>'

### ISSUE THREAD

**Issue by raaaar** [warmcat/libwebsockets#1080]
When compiling on windows with mbedtls (-DLWS_WITH_MBEDTLS=ON) getting the error above in ssl_x509.h(25):

`DEFINE_STACK_OF(X509_NAME)` -- VS tooltip says "expected a ')'". Looks like `X509_NAME` collides with a macro from wincrypt.h:
`#define X509_NAME                           ((LPCSTR) 7)`

What am I doing wrong?

**Comment by PSyton** [comment]
Looks like need to define WIN32_LEAN_AND_MEAN for windows builds in private-libwebsockets.h.

**Comment by lws-team** [comment]
Thanks for the clue @PSyton ... we do define it in libwebsockets.h but we include the mbedtls bits before we include libwebsockets.h.  I added a definition of it before on both master + v2.4-stable.
