### ISSUE TITLE
v2.3 and v2.4 libwebsockets-test-server hangs using libwebsockets-test-client

### ISSUE THREAD

**Issue by nospamcalfee** [warmcat/libwebsockets#1085]
By the way 2.2.2 does not hang the server. I just changed tags in git and rebuilt/installed to change versions.

in v2.4 I was able to connect 2 browser windows and the demo worked as I expected. Whenever I started libwebsockets-test-client localhost the server would peg one processor (I am on a i7). But it seemed to hang - I couldn't even ctl C out of the server - but I could kill it.

In v2.3 and v2.4 I could run the test-server localhost and test-client localhost and the server did not hang until I tried starting a browser window.

In v2.2.2 the system got really busy, the server at 25% the client at 25% and firefox using another 25% to keep up with the circle drawing. But it did seem to work properly.

As a demo, maybe test-client should pause a little between mirror sends? It would make interacting from a browser more interesting.

**Comment by lws-team** [comment]
Are you using v2.4-stable?  There are many fixes on there compared to v2.4.0 tag.

**Comment by nospamcalfee** [comment]
I did a git tag and it said:
v2.1.1
v2.2.0
v2.2.1
v2.2.2
v2.3.0
v2.4.0

so those are the ones I tried.

**Comment by nospamcalfee** [comment]
Should I be using one of these? And how do they map to v2.2.2 etc version numbers?
release-0.1
release-0.2
release-0.3
release-0.4
release-0.5
release-0.6

**Comment by lws-team** [comment]
Basically most users just want 'stable' versions, so they do what you did and just use tags.

But these things only become stable when people bang on them.  Although there are hardy souls that follow master and help with that, the bulk of users just expect everything to be magically stable already.  So especially for vx.y.0, you should use the branch vx.y-stable instead.  Fixes get piled on there and at intervals produce the .1, .2 etc tags.

**Comment by nospamcalfee** [comment]
Ah, ok.

git branch -a shows (among others):
remotes/origin/v1.6-stable
  remotes/origin/v1.7-stable
  remotes/origin/v2.0-stable
  remotes/origin/v2.1-stable
  remotes/origin/v2.2-stable
  remotes/origin/v2.3-stable
  remotes/origin/v2.4-stable

So I think you are saying I should use branch v2.4-stable rather than the tagged v2.4.0?

OK I'll try and see what happens, thanks for the help.
Steve

**Comment by lws-team** [comment]
Yeah, it's 17 patches ahead of v2.4.0 atm.

**Comment by nospamcalfee** [comment]
OK, changed to v2.4-stable. It no longer hangs, good. 

However the test-client localhost is busy doing something, but my two browser windows (which are mirroring my drawings) are not seeing the circles from my 2.2.2 experiment.

**Comment by lws-team** [comment]
OK hold on a tick I can reproduce it

**Comment by lws-team** [comment]
There are a couple more patches on v2.4-stable fixing those.

Basically you can have multiple mirror "instances" now, setting the name using `?mirror=name`  The client traffic was going to a different instance.  There was also a bug on deleting the instance on close fixed.

About the browser getting overwhelmed... yes... but it's a feature of the browser it doesn't perform rx flow control properly to make the server wait.  You can add a usleep or so on the test client to "work around it".

**Comment by nospamcalfee** [comment]
OK I got a couple of merge errors on git pull, I just mergetool accepted the upstream changes. (I had not made any local changes, so I don't know what caused the problem). 

So now I build and my Firefox browser tabs seem to work fine the test-client still totally swamps the system with all its circles - but if that is intended as a load test, fine it works.

I appreciate the quick help. I have not used libwebsockets in a few years and I am thinking about replacing a small python app with a C one for an embedded system.

Steve
