### ISSUE TITLE
CMake Error: install(EXPORT "LibwebsocketsTargets" ...) includes target "websockets" which requires target "mbedtls" that is not in the export set.

### ISSUE THREAD

**Issue by raaaar** [warmcat/libwebsockets#1087]
Added libwebsockets and mbedtls as git submodules to a project, in the top-level CMakeList.txt included both via `add_subdirectory`:
```
    set(MBEDTLS_ROOT "${PROJECT_SOURCE_DIR}/external/lib/mbedtls")
    add_subdirectory("${MBEDTLS_ROOT}")
    option(LWS_WITH_MBEDTLS "" ON)
    set(LWS_MBEDTLS_INCLUDE_DIRS "${MBEDTLS_ROOT}/include")
    include_directories(${LWS_MBEDTLS_INCLUDE_DIRS})
    set(LWS_MBEDTLS_LIBRARIES)
    list(APPEND LWS_MBEDTLS_LIBRARIES mbedtls)
    list(APPEND LWS_MBEDTLS_LIBRARIES mbedx509)
    list(APPEND LWS_MBEDTLS_LIBRARIES mbedcrypto)
....
    option(LWS_WITH_SHARED OFF)
    add_subdirectory ("${PROJECT_SOURCE_DIR}/external/lib/libwebsockets")
```
Getting the error above when running `cmake`:
```
-- Configuring done
CMake Error: install(EXPORT "LibwebsocketsTargets" ...) includes target "websockets" which requires target "mbedtls" that is not in the export set.
CMake Error: install(EXPORT "LibwebsocketsTargets" ...) includes target "websockets" which requires target "mbedx509" that is not in the export set.
CMake Error: install(EXPORT "LibwebsocketsTargets" ...) includes target "websockets" which requires target "mbedcrypto" that is not in the export set.
-- Generating done
```
However, running `make` afterwards works just fine. 

Is there any quick fix that would address the issue (just started poking around cmake, could be missing something totally trivial)? Alternatively, would it make sense to add an option that would disable the install directives?

**Comment by lws-team** [comment]
I'm sorry I personally never tried this cmake include technique, I have included lws in other projects but by building it the normal way by running cmake on it directly... no such errors are ciming then.

Have a look at the second suggestion in the answer here though, it sounds like avway to resolve it in your cmake file.

**Comment by lws-team** [comment]
Any news?

**Comment by lws-team** [comment]
I am willing to modify stuff in lws if it makes general sense.  Do you have a patch you want to propose?

**Comment by raaaar** [comment]
Submitted PR #1102. Not sure if this is an optimal solution, but it did resolve export issues for my setup.
