### ISSUE TITLE
Compiling with the latest version of openssl failed

### ISSUE THREAD

**Issue by honghailiu** [warmcat/libwebsockets#1088]
First of all, thank the author for nothing more than sharing:
I downloaded the latest source code from github, in accordance with the build.md steps compiled in the windows environment and found that the structure is not correct, from google to find the reason, the new version of openssl and the old version of openssl at rsa.h In struct rsa_t defined in different positions, resulting in compilation, however, due to the limited level, the problem can only be described clearly, thank the author again!

**Comment by lws-team** [comment]
沒關系...

Can you let me know the exact version of openssl?  Here I build it on Fedora against  `openssl-1.1.0f` which is pretty recent.

There are many variations of openssl over the years, cmake tries to discover what is available in your openssl library version and there are #if in the code to try to adapt.  Versions from 0.98 ... 1.1.0f at least should compile and build OK.

Can you paste the errors as well?

**Comment by honghailiu** [comment]
Thank you so much for my reply！
I downloaded from this site https://slproweb.com/products/Win32OpenSSL.html, version number is Win32OpenSSL-1_1_0g.exe, the use of cmake tools to generate project files compiled under Microsoft vs2013 error message is:
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (75): error C2037: The left part of "e" specifies an undefined structure / union "rsa_st"
2: D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (76): error C2037: The left part of "n" specifies an undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (77): error C2037: The left part of "d" specifies undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (78): error C2037: The left part of "p" specifies an undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (79): error C2037: The left part of "q" specifies undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (137): error C2037: The left part of "n" specifies undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (137): error C2037: The left part of "e" specifies an undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (137): error C2037: The left part of "d" specifies undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (138): error C2037: The left part of "p" specifies undefined structure / union "rsa_st"
2> D: \ libwebsocekt \ libwebsockets-master \ libwebsockets-master \ lib \ tls \ openssl \ lws-genrsa.c (138): error C2037: The left part of "q" specifies undefined structure / union "rsa_st"
struct rsa_st This structure is defined in the old version of openssl rsa.h, I did not find a new version, I am currently using openssl1.0.d and libwebsocket2.2.0 debugging

**Comment by lws-team** [comment]
Hmm the code there looks like this

```
#if defined(LWS_HAVE_RSA_SET0_KEY)
	if (RSA_set0_key(ctx->rsa, ctx->bn[JWK_KEY_N], ctx->bn[JWK_KEY_E],
			 ctx->bn[JWK_KEY_D]) != 1) {
		lwsl_notice("RSA_set0_key failed\n");
		goto bail;
	}
	RSA_set0_factors(ctx->rsa, ctx->bn[JWK_KEY_P], ctx->bn[JWK_KEY_Q]);
#else
	ctx->rsa->e = ctx->bn[JWK_KEY_E];
	ctx->rsa->n = ctx->bn[JWK_KEY_N];
	ctx->rsa->d = ctx->bn[JWK_KEY_D];
	ctx->rsa->p = ctx->bn[JWK_KEY_P];
	ctx->rsa->q = ctx->bn[JWK_KEY_Q];
#endif
```

Basically OpenSSL after 1.1.0 don't allow access to the members of the context, but provide `RSA_set0_key()` to access instead.  lws understands both ways; OpenSSL before 1.1.0 doesn't have `RSA_set0_key()`, so you have to use the direct way.

CMake should be looking for `RSA_set0_key()`, and it it exists it will define `LWS_HAVE_RSA_SET0_KEY`.  Then we know we should use the new way.

So what is the output of CMake for you?  Is there any problem about it?

**Comment by honghailiu** [comment]
Thank you for your analysis of the problem, the error is where you say, I follow your prompts in the CMakeLists.txt joined the following macro switch, compiled through,
```
option (LWS_WITH_ACME "Enable support for ACME automatic cert acquisition + maintenance (letsencrypt etc)" OFF)
option (LWS_HAVE_RSA_SET0_KEY "Use this macro definition after openssl version 1.1.0" ON)
```
As the first time using libwebsockets openssl a lot of things do not understand, not indiscriminately add, thank you again for your selfless sharing! I wish you good health, happy family!

**Comment by honghailiu** [comment]
Cmake gui tool tips LWS_HAVE_RSA_SET0_KEY not defined, but not set on the GUI, I will directly refer to your other definitions added in CMakeLists.txt

**Comment by lws-team** [comment]
Well... I understand what you did for a workaround, but actually cmake is supposed to discover by itself if `RSA_set0_key()` is available... that is what

```
CHECK_FUNCTION_EXISTS(RSA_set0_key LWS_HAVE_RSA_SET0_KEY)
```

in CMakeLists.txt is supposed to do.

cmake tries to build little test programs for these guys, and if they can link, he understands the function must exist, and he defines LWS_HAVE_RSA_SET0_KEY.  If they can't link, he knows the function doesn't exist, and he doesn't define anything.  This works OK on Linux, because I have LWS_HAVE_RSA_SET0_KEY defined in my build as it should be.

Please have a look in your build directory, for `CMakeFiles/CMakeOutput.log`, and search it for `RSA_set0_key`.

Mine says this for the result of the test

```
Determining if the function RSA_set0_key exists passed with the following output:
Change Dir: /projects/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_75660/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_75660.dir/build.make CMakeFiles/cmTC_75660.dir/build
gmake[1]: Entering directory '/projects/libwebsockets/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_75660.dir/CheckFunctionExists.c.o
/usr/lib64/ccache/cc -DKEYWORD=__inline  -Wall -Wsign-compare -Wignored-qualifiers -Wtype-limits -Wuninitialized -Werror -fvisibility=hidden -Wundef  -DCHECK_FUNCTION_EXISTS=RSA_set0_key   -o CMakeFiles/cmTC_75660.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_75660
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_75660.dir/link.txt --verbose=1
/usr/lib64/ccache/cc -Wall -Wsign-compare -Wignored-qualifiers -Wtype-limits -Wuninitialized -Werror -fvisibility=hidden -Wundef  -DCHECK_FUNCTION_EXISTS=RSA_set0_key    -rdynamic CMakeFiles/cmTC_75660.dir/CheckFunctionExists.c.o  -o cmTC_75660 /usr/lib64/libz.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libuv.so /usr/lib64/libsqlite3.so -lm -lcap
gmake[1]: Leaving directory '/projects/libwebsockets/build/CMakeFiles/CMakeTmp'
```

I think yours will be different anyway, but can you paste what it says here?

**Comment by honghailiu** [comment]
Sorry, so long ago to reply to you, I would like to put my programming environment all replaced by English version, before the Chinese version of the log some garbled. I follow your search for CMakeOutput.log, did not search RSA_set0_key, but see CMakeError .log in the following tips
`
Determining if the function RSA_set0_key exists failed with the following output:
Change Dir: C:/libwebsockets/build/CMakeFiles/CMakeTmp
Run Build Command:"C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe" "cmTC_8669d.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=12.0"
Microsoft (R) Build Engine version 12.0.21005.1
[Microsoft .NET Framework, version 4.0.30319.18444]
Copyright (C) Microsoft Corporation. All rights reserved.
`
The final build failed
When I use cmake tool configure, it prompts LWS_HAVE_RSA_SET0_KEY undefined.
Maybe I use the tool is not correct, I will try again, thank you for your help

**Comment by lws-team** [comment]
Is there a bit more output in the log after this?

```
Determining if the function RSA_set0_key exists failed with the following output: Change Dir: C:/libwebsockets/build/CMakeFiles/CMakeTmp Run Build Command:"C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe" "cmTC_8669d.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=12.0" Microsoft (R) Build Engine version 12.0.21005.1 [Microsoft .NET Framework, version 4.0.30319.18444] Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by honghailiu** [comment]
Um, can you give me an email, there's encryption software on the company's computer, inconvenient communication on git.

**Comment by lws-team** [comment]
andy@warmcat.com

**Comment by lws-team** [comment]
```
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\libwebsockets\build\CMakeFiles\CMakeTmp\Debug\cmTC_f5882.exe" /INCREMENTAL /NOLOGO C:\libwebsockets\build\lib\Debug\zlib_internal.lib "C:\OpenSSL-Win32\lib\VC\libssl32MDd.lib" "C:\OpenSSL-Win32\lib\VC\libcrypto32MDd.lib" ws2_32.lib userenv.lib psapi.lib iphlpapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/libwebsockets/build/CMakeFiles/CMakeTmp/Debug/cmTC_f5882.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/libwebsockets/build/CMakeFiles/CMakeTmp/Debug/cmTC_f5882.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_f5882.dir\Debug\CheckFunctionExists.obj


LINK : fatal error LNK1104: 无法打开文件“C:\libwebsockets\build\lib\Debug\zlib_internal.lib” [C:\libwebsockets\build\CMakeFiles\CMakeTmp\cmTC_f5882.vcxproj]


Done Building Project "C:\libwebsockets\build\CMakeFiles\CMakeTmp\cmTC_f5882.vcxproj" (default targets) -- FAILED.
```

Basically on Windows, it gets the idea it needs zlib_internal.lib to run the tests... it's not true and it  doesn't exist.  zlib_internal is for lws itself on windows, it's built statically.

I pushed a patch on master, please try it and see if it helps.

**Comment by honghailiu** [comment]
Ah, but also trouble you look once, now the macro definition is normal, but cmake configure is a direct error, can not be generated under windows VS2013 project files, thank you! I still sent the relevant documents to your mailbox, forgive me for the first time using cmake.

**Comment by honghailiu** [comment]
According to your tips, I use your patch before pushing a version of the test, the first use cmake generated windows visual studio project, then generate zlib_internal.lib, and then configure the cmake tools on it. Now you push the patch, there is a direct error, can not generate visual studio project.

**Comment by lws-team** [comment]
Yes... I had to go out for 1hr.  But when I got back, found the Appveyor Ci also broke.  So before replying again, I try things to make the tests work on appveyor and not break it's build.  So please hold on a little while.

**Comment by honghailiu** [comment]
Well, it does not matter, the first time to communicate with the god, a little nervous and excited. . .

**Comment by lws-team** [comment]
I think a god wouldn't make so many bugs.

Please retry current master, it works on Appveyor, it can find things like it should now

```
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - found
-- Looking for SSL_CTX_get_extra_chain_certs_only
-- Looking for SSL_CTX_get_extra_chain_certs_only - found
-- Looking for TLS_client_method
-- Looking for TLS_client_method - not found
-- Looking for TLSv1_2_client_method
-- Looking for TLSv1_2_client_method - found
```

and the build completed OK.
