### ISSUE TITLE
libWebsocket v1.3 lws_client_interpret_server_handshake error

### ISSUE THREAD

**Issue by jusforfun** [warmcat/libwebsockets#1090]
Hi,
I know i am using a pretty old version of libWebsocket but would like to ask for confirmation or help for the issue faced.

Client Connects with the defaults lws_extensions code for permessage-deflate;
Server(websocketSharp) returns the default extensions permessage-deflate; client_no_context_takeover; server_no_context_takeover;
Client afterwards will returns an error:  lws_client_interpret_server_handshake error, {followed by the extensions}

Just would want to check is the issue lies with this version of libwebSockets, or perhaps in other areas;

Many thanks for help.

**Comment by lws-team** [comment]
It's a problem on older versions of lws... it was addressed with this in March 2017 I think 4578036b53f53d9e4434444d698903902318ae18  ... you should look at v2.4-stable or master.
