### ISSUE TITLE
Issue with debug build make v2.1.1

### ISSUE THREAD

**Issue by dogunyoye** [warmcat/libwebsockets#1096]
Hi Andy,

I'm experiencing a compilation failure during the make phase of a v2.1.1 debug build - this is the output I receive:

```
➜  build-osx-debug make
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  2%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  3%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  5%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[  6%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[  7%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
/Users/dimeji/libwebsockets/libwebsockets-2.1.1/lib/output.c:495:8: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
                                          wsi->u.http.content_remain);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dimeji/libwebsockets/libwebsockets-2.1.1/lib/libwebsockets.h:325:43: note: expanded from macro 'lwsl_info'
#define lwsl_info(...) _lws_log(LLL_INFO, __VA_ARGS__)
                                          ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/websockets.dir/lib/output.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
```

I'm aware that this version is more than a few releases old, though I wanted to confirm if this was perhaps an issue of my own doing/something that has been resolved in a future release or otherwise.

Many thanks,
Dimeji

**Comment by lws-team** [comment]
It's fixed in later versions, on master it became

https://github.com/warmcat/libwebsockets/blob/10dc3e62aa9250bb01a992a0975c9778581a1e5a/lib/output.c#L508

Although on the face of it, it's simply a casting problem, actually it reflects a bug in the portability of the type used at that time for >32-bit file length support.  So you should better move to v2.4-stable branch or master.
