### ISSUE TITLE
Using deprecated OpenSSL method

### ISSUE THREAD

**Issue by beniloew** [warmcat/libwebsockets#1098]
Trying to build on windows with mingw.
Installed OpenSSL 1.1.0
I get the following error:
libwebsockets/lib/tls/openssl/openssl-client.c: In function 'lws_tls_client_create_vhost_context':
libwebsockets/lib/tls/openssl/openssl-client.c:285:2: error: 'TLSv1_2_client_method' is deprecated [-Werror=deprecated-declarations]
  method = (SSL_METHOD *)TLSv1_2_client_method();
  ^~~~~~
In file included from C:/OpenSSL-Win64/include/openssl/ct.h:13:0,
                 from C:/OpenSSL-Win64/include/openssl/ssl.h:61,
                 from .../libwebsockets/lib/private-libwebsockets.h:303,
                 from .../libwebsockets/lib/tls/openssl/openssl-client.c:22:
C:/OpenSSL-Win64/include/openssl/ssl.h:1638:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void)) /* TLSv1.2 */
                                             ^
C:/OpenSSL-Win64/include/openssl/opensslconf.h:105:35: note: in definition of macro 'DECLARE_DEPRECATED'
 # define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                   ^
C:/OpenSSL-Win64/include/openssl/ssl.h:1638:1: note: in expansion of macro 'DEPRECATEDIN_1_1_0'
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void)) /* TLSv1.2 */
 ^~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.obj] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2

**Comment by lws-team** [comment]
This is actually a bug in the windows support for cmake to detect what it should be using.

It's fixed in v2.4-stable and master, so please try one of those instead.

**Comment by beniloew** [comment]
This one was build from master...
HEAD is at:
gcov: add in cmake and adapt defaults

**Comment by lws-team** [comment]
What does cmake say for discovering what functions are available?  For example the 64-bit build on appveyor says for the version of openssl it has (1.0.2l)

```
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - found
-- Looking for SSL_CTX_get_extra_chain_certs_only
-- Looking for SSL_CTX_get_extra_chain_certs_only - found
-- Looking for TLS_client_method
-- Looking for TLS_client_method - not found
-- Looking for TLSv1_2_client_method
-- Looking for TLSv1_2_client_method - found
```

The code looks like this

```
#if defined(LWS_HAVE_TLS_CLIENT_METHOD)
	method = (SSL_METHOD *)TLS_client_method();
#elif defined(LWS_HAVE_TLSV1_2_CLIENT_METHOD)
	method = (SSL_METHOD *)TLSv1_2_client_method();
#else
	method = (SSL_METHOD *)SSLv23_client_method();
#endif
```

Ie, if you have `TLS_client_method()` on your version of openssl, it should use it.

**Comment by beniloew** [comment]
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - found
-- Looking for SSL_CTX_get_extra_chain_certs_only
-- Looking for SSL_CTX_get_extra_chain_certs_only - found
-- Looking for TLS_client_method
-- Looking for TLS_client_method - not found
-- Looking for TLSv1_2_client_method
-- Looking for TLSv1_2_client_method - found

**Comment by lws-team** [comment]
Hum... on Linux, with 1.1.0f, it's like this

```
-- Looking for TLS_client_method
-- Looking for TLS_client_method - found
```

Inside the `openssl/ssl.h`, there is this

```
__owur const SSL_METHOD *TLS_client_method(void);
```

The result of the cmake test it did to find out if it exists (from build/CMakeFiles/CMakeOutput.log) is this

```
Determining if the function TLS_client_method exists passed with the following output:
Change Dir: /projects/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_3d6b2/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_3d6b2.dir/build.make CMakeFiles/cmTC_3d6b2.dir/build
gmake[1]: Entering directory '/projects/libwebsockets/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3d6b2.dir/CheckFunctionExists.c.o
/usr/lib64/ccache/cc -DKEYWORD=__inline  -Wall -Wsign-compare -Wignored-qualifiers -Wtype-limits -Wuninitialized -Werror -fvisibility=hidden -Wundef   -DCHECK_FUNCTION_EXISTS=TLS_client_method   -o CMakeFiles/cmTC_3d6b2.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_3d6b2
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3d6b2.dir/link.txt --verbose=1
/usr/lib64/ccache/cc -Wall -Wsign-compare -Wignored-qualifiers -Wtype-limits -Wuninitialized -Werror -fvisibility=hidden -Wundef   -DCHECK_FUNCTION_EXISTS=TLS_client_method    -rdynamic CMakeFiles/cmTC_3d6b2.dir/CheckFunctionExists.c.o  -o cmTC_3d6b2 /usr/lib64/libssl.so /usr/lib64/libcrypto.so -lm -lcap
gmake[1]: Leaving directory '/projects/libwebsockets/build/CMakeFiles/CMakeTmp'
```

Can you have a look in `build/CMakeFiles/CMakeError.log` and search for `TLS_client_method` and paste what your test section says?  And maybe have a look in openssl/include/ssl.h and check it is there?

**Comment by lws-team** [comment]
It would be great if you could help with this info... I don't use windows and Appveyor's OpenSSL version predates this api introduction.

**Comment by lws-team** [comment]
Well, if you want to help, I'll be happy to continue.

**Comment by beniloew** [comment]
Hi - i will apply as soon as i will have the time to get back to it
Sorry for the inconvenience

**Comment by trankkilou** [comment]
Hi Larry,
I have exactly the same issue but I m under linux.. 
SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

Make seems to find openssl
_### Compiling with SSL support
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "**1.1.0f**") 
OpenSSL include dir: /usr/include
OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - found
-- Looking for SSL_CTX_get_extra_chain_certs_only
-- Looking for SSL_CTX_get_extra_chain_certs_only - found
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl_

here the build/CMakeFiles/CMakeOutput.log
_Determining if the function TLSv1_2_client_method exists passed with the following output:
Change Dir: /opt/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec1040205342/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1040205342.dir/build.make CMakeFiles/cmTryCompileExec1040205342.dir/build
make[1]: Entering directory '/opt/libwebsockets/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /opt/libwebsockets/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1040205342.dir/CheckFunctionExists.c.o
/usr/bin/cc  -DKEYWORD=__inline -Wall -Werror -fvisibility=hidden -fpic -pthread -DCHECK_FUNCTION_EXISTS=TLSv1_2_client_method   -o CMakeFiles/cmTryCompileExec1040205342.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.0/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec1040205342
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1040205342.dir/link.txt --verbose=1
/usr/bin/cc  -Wall -Werror -fvisibility=hidden -fpic -pthread -DCHECK_FUNCTION_EXISTS=TLSv1_2_client_method    CMakeFiles/cmTryCompileExec1040205342.dir/CheckFunctionExists.c.o  -o cmTryCompileExec1040205342 -rdynamic -lz -lssl -lcrypto -lm 
make[1]: Leaving directory '/opt/libwebsockets/build/CMakeFiles/CMakeTmp'


The system is: Linux - 4.9.0-4-amd64 - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: -fpic
Id flags: 

The output was: 
0_

**Comment by trankkilou** [comment]
regarding my /usr/include/openssl/ssl.h

/* Negotiate highest available SSL/TLS version */
__owur const SSL_METHOD *TLS_method(void);
__owur const SSL_METHOD *TLS_server_method(void);
__owur const SSL_METHOD *TLS_client_method(void);

**Comment by trankkilou** [comment]
update 2 
As I cannot wait, I remove my libwebsocket folder and redo compilation from scratch -> now it works
my issue was after a "git pull"

root@OMS-WEBRTC0:/opt/libwebsockets# git pull
remote: Counting objects: 2827, done.
remote: Compressing objects: 100% (1137/1137), done.
remote: Total 2827 (delta 2152), reused 2209 (delta 1679)
Receiving objects: 100% (2827/2827), 1.03 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2152/2152), completed with 64 local objects.
From git://git.libwebsockets.org/libwebsockets
   af718ff5..93f904f6  master      -> origin/master
 * [new branch]        esp32       -> origin/esp32
   31b10292..fff2bb5b  v2.2-stable -> origin/v2.2-stable
 * [new branch]        v2.3-stable -> origin/v2.3-stable
 * [new branch]        v2.4-stable -> origin/v2.4-stable
 * [new tag]           v2.2.2      -> v2.2.2
 * [new tag]           v2.3.0      -> v2.3.0
 * [new tag]           v2.4.0      -> v2.4.0
 * [new tag]           v2.4.1      -> v2.4.1
Updating af718ff5..93f904f6
Fast-forward

if it could help others...

**Comment by jimon** [comment]
There is no `TLS_client_method` on macOS `openssl 1.0.2o_2` if that helps.
