### ISSUE TITLE
Secure Websocket client: MSG_DONTWAIT or non-blocking socket

### ISSUE THREAD

**Issue by mstanichenko** [warmcat/libwebsockets#1101]
Dear `libwebsockets` developers,

Would you be so kind as to advise whether the library supports non-blocking sockets with secure websocket clients?

I am developing a component in a single-threaded program which is called externally and supposed to receive some data via a secure websocket. It is supposed to check data availability and if no messages received, it is supposed to return immediately i.e. it cannot block the whole application respectively.

I usually use `MSG_DONTWAIT` (see [man recv](http://man7.org/linux/man-pages/man2/recv.2.html)) for normal berkeley sockets. Alternatively, the socket can be set in non-blocking mode (`O_NONBLOCK`).

Is there a way to emulate such a behavior within `libwebsockets`?

Thanks in advance

**Comment by lws-team** [comment]
It's all nonblocking / singlethreaded / event loop, as you would know if you took even a casual look at it or any of the examples.

**Comment by mstanichenko** [comment]
Thank you very much for such a prompt response. Much appreciated.

>  as you would know if you took even a casual look at it or any of the examples

I did as I did for a few other libraries out there.

Anyway, thanks again for you assistance.
