### ISSUE TITLE
libwebsocket :remaining packet payload

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1103]
lws_remaining_packet_payload(wsi) is the remaining packet in the kernel buffer ?
 

what all the possible values that the libwebsocket library can provide for these two APIs ?

**lws_remaining_packet_payload
lws_is_final_fragment**

that is, Should i need to use these two apis to combine the websocket fragments ?

case 1 lws_remaining_packet_payload > 0 && lws_is_final_fragment =0 (Not final fragment and still pending in kernel rx buffer)
case 2 lws_remaining_packet_payload > 0 && lws_is_final_fragment >0 (Last fragment and still pending in kernel rx buffer)

case 3 lws_remaining_packet_payload > 0 && lws_is_final_fragment >0 (Last fragment and not pending in the kernel rx buffer )
case 4 lws_remaining_packet_payload > 0 && lws_is_final_fragment =0(Not final fragment and not pending in the kernel rx buffer )

**Comment by lws-team** [comment]
The naming on these apis is a bit confusing.

What `lws_remaining_packet_payload()` is measuring is the amount of data left in the current websocket fragment.  When a ws fragment is sent, in the header there is a payload length.  The number returned by `lws_remaining_packet_payload()` is the difference between the amount of data that has been passed to the RX callback, and was told in the fragment header.

If that data "in the kernel", "in the TLS library", "in the compression extension", "in transit", "not sent yet", nobody knows.  A single fragment can have a length up to 2^63 -1, so you cannot think of it as simply "in the kernel".  It means that for whatever reason, it wasn't passed to your callback yet as RX.

`lws_is_final_fragment()` is telling you if when the sender started sending this fragment, he marked it as being the last fragment in the ws message, ie, that when you receive the last chunk of this fragment, you will have received a "whole ws message".

There is one other quirk, if you are using `permessage-deflate`, which in lws provides you with chunks at a time (default is 1KB), even if lws has received the last part of the compressed data, it will conceal (lie about) the result of `lws_is_final_fragment()` until `permessage-deflate` is passing you the last uncompressed data from it.

So you normally only care about the combination `lws_is_final_fragment() && !lws_remaining_packet_payload()` in the RX callback.  If it's true, it means you were just passed the last piece of a ws message.  If it's not true, you are partway through the message: more data is coming for that message in one or more following RX callbacks.

**Comment by arunkvnss** [comment]
sir,Basically i confused with the amount of memory i can use for the buffer,When the fragmented messages are coming the (lws_remaining packet payload return value + current recvd length) will be ensuring the total size of the buffer to recv ?
