### ISSUE TITLE
ERR: WSAEnumNetworkEvents() failed with error 10038

### ISSUE THREAD

**Issue by geniuz** [warmcat/libwebsockets#1105]
Hi
This error occurs when client connects to server running on windows:
ERR: WSAEnumNetworkEvents() failed with error 10038
How to solve this problem?
Thanks

**Comment by lws-team** [comment]
Okay... so where does that error happen?  What version of lws is it?

I do not use windows myself.  If you are willing to help debug it I'll try to help.
