### ISSUE TITLE
wrong source file link

### ISSUE THREAD

**Issue by bvs23bkv33** [warmcat/libwebsockets#1110]
please update README.test-apps.md paragraph "Notes about lws test apps" to point to correct test-server.c file, as it is done in paragraph "Overview of lws test apps" (test-server-v2.0.c)

**Comment by lws-team** [comment]
I went to look for this on master, but perhaps because I didn't have enough coffee yet, I didn't find the problem.  Can you let me know the line number in the file, or the lws version if not master?

**Comment by bvs23bkv33** [comment]
it does not show line numbers in README, it just shows github 404 page when clicking links in README.test-apps.md
btw i was assuming that test-server-v2.0.c link is ok, but i was wrong - it shows 404 too

**Comment by lws-team** [comment]
Hm I get it... I moved the READMEs into ./READMEs a few weeks ago since they were increasing in number at the top level of the project, that broke these kind of links.  I'll fix them up shortly.

**Comment by bvs23bkv33** [comment]
thanks

**Comment by lws-team** [comment]
They should be fixed now, thanks for reporting it.

**Comment by bvs23bkv33** [comment]
fix confirmed
