### ISSUE TITLE
Unable to build with lwsws and SSL disabled

### ISSUE THREAD

**Issue by Anzey** [warmcat/libwebsockets#1112]
Build configuration like
 cmake .. -DLWS_WITH_SSL=0 -DLWS_WITH_LWSWS=1
leads to make error in sshd.c
Seems there is no way to diable SSHD?

**Comment by lws-team** [comment]
Thanks for pointing it out... I pushed a patch only building the sshd bits when SSL is enabled on master and v2.4.
