### ISSUE TITLE
Invalid code

### ISSUE THREAD

**Issue by wzugang** [warmcat/libwebsockets#1113]
https://github.com/warmcat/libwebsockets/blob/c8a1beb811726916a02245b8757027aad90dd68b/lib/private-libwebsockets.h#L373
According to the context, _WIN32 was not defined here, therefore FD_HASHTABLE_MODULUS will not be defined as well.  the following code have the same question.

**Comment by lws-team** [comment]
... the idea there is that on windows platform, the compiler defines _WIN32.

The only uses of FD_HASHTABLE_MODULUS are on windows platform...

```
$ git grep FD_HASHTABLE_MODULUS
lib/plat/lws-plat-win.c:        for (n = 0; n < FD_HASHTABLE_MODULUS; n++) {
lib/plat/lws-plat-win.c:        for (i = 0; i < FD_HASHTABLE_MODULUS; i++) {
lib/private-libwebsockets.h:#ifndef FD_HASHTABLE_MODULUS
lib/private-libwebsockets.h:#define FD_HASHTABLE_MODULUS 32
lib/private-libwebsockets.h:#define LWS_FD_HASH(fd) ((fd ^ (fd >> 8) ^ (fd >> 16)) % FD_HASHTABLE_MODULUS)
lib/private-libwebsockets.h:    struct lws_fd_hashtable fd_hashtable[FD_HASHTABLE_MODULUS];
```

`lib/plat/lws-plat-win.c` is only built for windows platform, and all of the references in `private-libwebsockets.h` are also protected by `#ifdef _WIN32`.

So what problem are you seeing?  It seems to be OK if I understand it.

**Comment by wzugang** [comment]
here is an example. whether B is defined or not, line 12  will never works. the macro of B below is similar with _WIN32 in file private-libwebsockets.h. 

  1 #include<stdio.h> 
  2 #include<string.h>                                                             
  3                                                                                
  4 int main()                                                                     
  5 {                                                                              
  6 #define B                                                                      
  7 #if defined(A) || defined(B)                                                   
  8     printf("defined\n");                                                       
  9 #else                                                                          
 10     printf("not defined\n");                                                   
 11 #ifdef B                                                                       
 12     printf("test\n");                                                          
 13 #endif                                                                         
 14                                                                                
 15 #endif                                                                         
 16     return 0;                                                                  
 17 }

**Comment by lws-team** [comment]
I can understand what you're saying from your example, but I can't map it on to what I see in `private-libwebsockets.h`, maybe I am just too dumb to see it.  Although this stuff builds in Appveyor, if there was a problem with FD_HASHTABLE_MODULUS definition, that should fail to build, right?

https://ci.appveyor.com/project/lws-team/libwebsockets/build/1.0.2326/job/2k8a1i5nptrvduu9

As far as I can see at line 373, there is NO outer #if / #ifdef active in the file until the one at line 373.  So it does not look like your example.  Apologies if I miss your point.

**Comment by wzugang** [comment]
sorry, the editor notepad++ Misled me，the file private-libwebsockets.h has no problem.
