### ISSUE TITLE
Artifacts are not exposed on AppVeyor

### ISSUE THREAD

**Issue by FRSgit** [warmcat/libwebsockets#1114]
Hi,
I wanted to download binary build for Windows, but unfortunately there are artifact missing for jobs on AppVeyor.

I've looked in console output of one of jobs (screen below) and I see that something is borked with lws.zip archive (maybe incorrect path?).
![image](https://user-images.githubusercontent.com/10456649/33506642-17b658c8-d6f1-11e7-9c8b-a40479663185.png)

**Comment by lws-team** [comment]
That gave me a bad feeling :-) but actually it's OK... I struggled to get the artifacts to work for some months... the top build on appveyor at the moment happens to be v2.4-stable, which is from before I got them working.

If you dig a bit deeper the second build down atm is master, which has them working OK.

https://ci.appveyor.com/project/lws-team/libwebsockets/build/1.0.2326/job/2k8a1i5nptrvduu9/artifacts

**Comment by FRSgit** [comment]
Ah, sorry - yes, I figured out that second latest build works but I didn't see that it's linked to different branch, my bad!
Well, I saw your struggles as I try to use this library for my private project and I'm really thankful for your work - I know that configuring appveyor can be pain in the ass ;)

Sorry for confusion and thanks for great library you've created!
