### ISSUE TITLE
ESP32 branch has lots of console prints that can not be turned off

### ISSUE THREAD

**Issue by JimGaluska** [warmcat/libwebsockets#1115]
The LWS library sends lots of information to the console with no apparent way to turn it off.   I have created my own log emit function and have call the function:
   lws_set_log_level(LLL_ERR , log_emit_function);
Yet, I still get a lot of output to the console.  A trace of the output is attached.

[LWS-ESP32-Console.txt](https://github.com/warmcat/libwebsockets/files/1529876/LWS-ESP32-Console.txt)

**Comment by lws-team** [comment]
When do you set your log emit function?  Because `lws_esp32_set_creation_defaults()` also calls it to set lwsl_emit_syslog; if you set it before calling that it will get overridden.

There are a fair amount of debugging logs on at LLL_NOTICE, if you only allow LLL_ERR it should be pretty quiet.

**Comment by JimGaluska** [comment]
I was calling the function lws_set_log_level before calling lws_esp32_set_creation_defaults.  Moving this line does quiet everything down.  Thanks!
