### ISSUE TITLE
unable to use websocket extension

### ISSUE THREAD

**Issue by abs1001** [warmcat/libwebsockets#1116]
i am unable to use libwebsocket extension and verify it on the wireshark.
can you provide any document regarding usage of websocket extension on libwebsocket library.

Hypertext Transfer Protocol
    GET // HTTP/1.1\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    Host: a.b.c.d\r\n
    Origin: http://a.b.c.d\r\n
    Upgrade: websocket\r\n
    Connection: Upgrade\r\n
    Sec-WebSocket-Key: ampe0gLPhU4NQLlsoRoJpg==\r\n
    Sec-WebSocket-Protocol: lws-mirror-protocol\r\n
    Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover\r\n
    Sec-WebSocket-Version: 13\r\n
    \r\n
    [Full request URI: http://a.b.c.d//]
    [HTTP request 1/1]
    [Response in frame: 14]

Hypertext Transfer Protocol
    HTTP/1.1 101 Switching Protocols\r\n
    Upgrade: WebSocket\r\n
    Connection: Upgrade\r\n
    Sec-WebSocket-Accept: 6c/nUBDY9aTrjr16jN5gbBVWIb0=\r\n
    Sec-WebSocket-Protocol: lws-mirror-protocol\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.000224000 seconds]
    [Request in frame: 11]

This is request and response I captured on wireshark

**Comment by lws-team** [comment]
Mirror disables compression... try it again commenting this case

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_mirror.c#L310

**Comment by abs1001** [comment]
can your share your mail or contact ? 
i have many query regarding websocket extension as i am doing for the first time i need to know it from scratch , i have gone through the rfc

**Comment by abs1001** [comment]
Still Facing the same issue

**Comment by lws-team** [comment]
Maybe you should back up and explain what you first posted about a bit better.

What are the client and server in these cases, both lws?

If you go here and click on the Server Info tab, you should see it says "permessage deflate" in the green box, right?

https://libwebsockets.org/testserver/

That is the compression extension working with lws test server.

Are extensions enabled at cmake?
