### ISSUE TITLE
LWS Build always causes a new binary to be created, even if nothing has changed

### ISSUE THREAD

**Issue by JimGaluska** [warmcat/libwebsockets#1117]
I have installed Expressif ESP_IDF and then install LWS into the components directory of the ESP_IDF.  Now, every time anything is built, cmake is called and a new binary is created, even if no changes have been made to the LWS code.  A new binary is built even if the project does not use LWS.

**Comment by lws-team** [comment]
> I have installed Expressif ESP_IDF and then install LWS into the components directory of the ESP_IDF.

There's no reason to do that, use the same technique as -factory and the test demo and put lws in your project.

I don't understand what you mean by "new binary" either, the component should generate a .a.

If you really want to put it in esp-idf, well that's fine, but maybe you can debug the issue?
