### ISSUE TITLE
infine loop PENDING_TIMEOUT_SHUTDOWN_FLUSH

### ISSUE THREAD

**Issue by mdmivanov** [warmcat/libwebsockets#1124]
Hi, after client connection was successfully established, stop server application. After the server application was stopped the client library goes into an infinite loop.

OS: ios 9.3
DLWS_WITH_SSL=1 
DLWS_WITHOUT_SERVER=1 
DLWS_WITH_SHARED=0
DLWS_WITHOUT_TEST_SERVER=1 
DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1 
DLWS_WITHOUT_TEST_PING=1 
DLWS_WITHOUT_TEST_ECHO=1 
DLWS_WITHOUT_TEST_FRAGGLE=1 
DLWS_WITHOUT_TESTAPPS=1 
DLWS_WITHOUT_TEST_CLIENT=1	
DLWS_AVOID_SIGPIPE_IGN=1 
DLWS_IPV6=1

D/WebSocket.cpp (1395): protocol drop...
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7fc4f9a19c70 (sock 10, state 236)
D/WebSocket.cpp (167): DEBUG: closing: shutdown (state 236) ret 57
D/WebSocket.cpp (167): DEBUG: PENDING_TIMEOUT_SHUTDOWN_FLUSH
D/WebSocket.cpp (167): DEBUG: _lws_change_pollfd: wsi 0x7fc4f9a19c70: fd 10 events 1 -> 1
D/WebSocket.cpp (167): DEBUG: lws_set_timeout: 0x7fc4f9a19c70: 3 secs
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (167): DEBUG: 0x7fc4f9a19c70: Close and handled
D/WebSocket.cpp (167): DEBUG: lws_close_free_wsi: 0x7fc4f9a19c70
D/WebSocket.cpp (167): DEBUG: lws_close_free_wsi: 0x7fc4f9a19c70: DROP_PROTOCOL api

D/WebSocket.cpp (1395): protocol drop...
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7fc4f9a19c70 (sock 10, state 236)
D/WebSocket.cpp (167): DEBUG: closing: shutdown (state 236) ret 57
D/WebSocket.cpp (167): DEBUG: PENDING_TIMEOUT_SHUTDOWN_FLUSH
D/WebSocket.cpp (167): DEBUG: _lws_change_pollfd: wsi 0x7fc4f9a19c70: fd 10 events 1 -> 1
D/WebSocket.cpp (167): DEBUG: lws_set_timeout: 0x7fc4f9a19c70: 3 secs
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (167): DEBUG: 0x7fc4f9a19c70: Close and handled
D/WebSocket.cpp (167): DEBUG: lws_close_free_wsi: 0x7fc4f9a19c70
D/WebSocket.cpp (167): DEBUG: lws_close_free_wsi: 0x7fc4f9a19c70: DROP_PROTOCOL api

D/WebSocket.cpp (1395): protocol drop...
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7fc4f9a19c70 (sock 10, state 236)
D/WebSocket.cpp (167): DEBUG: closing: shutdown (state 236) ret 57
D/WebSocket.cpp (167): DEBUG: PENDING_TIMEOUT_SHUTDOWN_FLUSH
D/WebSocket.cpp (167): DEBUG: _lws_change_pollfd: wsi 0x7fc4f9a19c70: fd 10 events 1 -> 1
D/WebSocket.cpp (167): DEBUG: lws_set_timeout: 0x7fc4f9a19c70: 3 secs

**Comment by lws-team** [comment]
This was a ws or wss connection that the server closed, is it?

**Comment by mdmivanov** [comment]
I use ws connection directly to server application without nginx

**Comment by mdmivanov** [comment]
After investigate the code I found that loop started after was executed the code bellow

libwebsockets.c

#if !defined(_WIN32_WCE) && !defined(LWS_WITH_ESP32)
		/* libuv: no event available to guarantee completion */
		if (!wsi->socket_is_permanently_unusable &&
		    lws_sockfd_valid(wsi->desc.sockfd) &&
		    !LWS_LIBUV_ENABLED(context)) {
			lws_change_pollfd(wsi, LWS_POLLOUT, LWS_POLLIN);
			wsi->state = (wsi->state & ~0x1f) | LWSS_SHUTDOWN;
			lws_set_timeout(wsi, PENDING_TIMEOUT_SHUTDOWN_FLUSH,
					context->timeout_secs);

			return;
		}
#endif

**Comment by BHamrick1** [comment]
I think I am seeing the same thing when using this library with Janus. This only happens on the master branch of libwebsocket. If it helps here is the log it prints out:

`[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))
[Mon Dec 18 15:48:29 2017] [WSS-0x7f96c2524a30] 50 ((null))`

**Comment by BHamrick1** [comment]
I am linking the Janus issue here for reference https://github.com/meetecho/janus-gateway/issues/1105

**Comment by lws-team** [comment]
Sorry for taking a long time to look at this, I am travelling the last few days.

I think it's fixed by a patch on master today, please retry it.

**Comment by mdmivanov** [comment]
The issues was reproduced again  (master,b42de85)

OS: ios 9.3, ws connection

D/WebSocket.cpp (1146): -----------------------------------------------------------
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm:    This RX frame Final 1
D/WebSocket.cpp (167): INFO: client receied pong
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm: passing 1 to ext
D/WebSocket.cpp (167): EXTENSION: Ext RX returned 0
D/WebSocket.cpp (167): EXTENSION: post inflate eff_buf len 1
D/WebSocket.cpp (167): INFO: Client doing pong callback
D/WebSocket.cpp (167): INFO: lws_read: 0x799a0c40: read_ok, used 3 (len 3, state 229)
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm:    This RX frame Final 1
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm: passing 2 to ext
D/WebSocket.cpp (167): EXTENSION: Ext RX returned 0
D/WebSocket.cpp (167): EXTENSION: post inflate eff_buf len 2
D/WebSocket.cpp (1167): Receiving data:index:6, len=2
D/WebSocket.cpp (167): INFO: lws_is_final_fragment: final 1, rx pk length 0, draining 0
D/WebSocket.cpp (167): INFO: lws_read: 0x799a0c40: read_ok, used 4 (len 4, state 229)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 229)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x79632140) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x799a0c40 (sock 11, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read

**Comment by mdmivanov** [comment]
The issues was reproduced  master,d2bc2d1
IOS, ws connection

D/WebSocket.cpp (1122): Safely done, msg(15)!
D/WebSocket.cpp (1125): msg(15) append: 0 + 1 = 1
D/WebSocket.cpp (1126): msg(15) was totally sent!
D/WebSocket.cpp (1146): -----------------------------------------------------------
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm:    This RX frame Final 1
D/WebSocket.cpp (167): INFO: client receied pong
D/WebSocket.cpp (167): EXTENSION: lws_client_rx_sm: passing 1 to ext
D/WebSocket.cpp (167): EXTENSION: Ext RX returned 0
D/WebSocket.cpp (167): EXTENSION: post inflate eff_buf len 1
D/WebSocket.cpp (167): INFO: Client doing pong callback
D/WebSocket.cpp (167): INFO: lws_read: 0x7969cbe0: read_ok, used 3 (len 3, state 229)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 229)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read
D/WebSocket.cpp (1393): WebSocket (0x7968ca50) Unhandled websocket event: 50
D/WebSocket.cpp (167): INFO: lws_close_free_wsi: shutdown conn: 0x7969cbe0 (sock 13, state 236)
D/WebSocket.cpp (167): INFO: lws_service_fd_tsi: zero length read

**Comment by redbluetoken** [comment]
Hi,

I am having the same issue. I'm using a simple perl based websocket client for testing and when you ctrl-c the client, the server goes to 100% CPU with event 50 being repeatedly called. 

If you need any help reproducing this, I should be able to create a usecase.

Regards,

**Comment by lws-team** [comment]
If there's a way to reproduce it on Linux, using the test apps, I'll be happy to give it a go.

**Comment by redbluetoken** [comment]
Hi,

Using the code in #1135 you should be able to replicate the issue (I am using linux, and if you need more info, let me know). Also to add:

I noticed that if I have:

```
static struct lws_protocols protocols[] =
{
	/* The first protocol must always be the HTTP handler */
	{
		"http-only",   /* name */
		callback_http, /* callback */
		0,             /* No per session data. */
		0,             /* max frame size / rx buffer */
	},
	{
		"example-protocol", //"example-protocol"
		callback_websocket,
		8, // <<<<<<<<<<see here
		EXAMPLE_RX_BUFFER_BYTES,
	},
	{ NULL, NULL, 0, 0 } /* terminator */
};
```

Then I get the 50 messages, but if the above value is zero, I still get 100% cpu, but no 50 messages, just:

callback_http 36 
callback_http 35 
callback_http 34 
callback_http 36 
callback_http 35 
callback_http 34 
callback_http 36 
callback_http 35 
callback_http 34
....

**Comment by lws-team** [comment]
There are a couple of patches on v2.4-stable and master that should help with this.

**Comment by redbluetoken** [comment]
Ok, played with master and this issue seems to have gone away. I'll keep testing.

**Comment by mdmivanov** [comment]
Hi, I checked this issue with master (bd3d8d9) and it didn't reproduced now. 
Thanks.
