### ISSUE TITLE
SSL Certificate Pinning

### ISSUE THREAD

**Issue by sp-miguel-ibero** [warmcat/libwebsockets#1127]
Hi,

I would be really interested in libwebsockets having client certificate pinning support for the wss connections. Have you thought about this feature? Something similar to [CURLOPT_PINNEDPUBLICKEY](https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html) would be nice.

**Comment by lws-team** [comment]
When you say, 'interested', it's interested as in interested in sending a patch?  There are a lot of related pieces on master, which work on both openssl and mbedtls, after the ACME plugin work.  Including a backend-agnostic api for fetching things out of x509 (not the pubkey atm but it shouldn't be hard to add).  That's all you need really and confirm it during the verify callback or so; how to store it is application dependent.

**Comment by lws-team** [comment]
Patch welcome...
