### ISSUE TITLE
set LWS_WITH_LIBEVENT on,  compile error

### ISSUE THREAD

**Issue by u203** [warmcat/libwebsockets#1131]
libwebsockets/test-apps/test-server-libevent.c:260:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 for (n = 0; n < ARRAY_SIZE(sigs); n++) {
                ^
cc1: all warnings being treated as errors

**Comment by lws-team** [comment]
Sorry for the delay... it should be fixed in master now.
