### ISSUE TITLE
libwebsockets.org is down

### ISSUE THREAD

**Issue by pbn4** [warmcat/libwebsockets#1132]
Hello, 

is the site permamently down due to some hosting issue or is it being moved somewhere else?

**Comment by lws-team** [comment]
It runs master by way of eating my own dogfood... sometimes "somebody helps me find a bug".  It's back up now with a fix https://github.com/warmcat/libwebsockets/commit/4cee34c0d06a6f43baf22260ba906283fce5e3d4
