### ISSUE TITLE
100% CPU spike when client requests incorrect protocol 

### ISSUE THREAD

**Issue by redbluetoken** [warmcat/libwebsockets#1135]
Hi,

I've been playing around with libwebsockets and I've come across a few issues with protocols and a test client (perl). I've stripped everything down to the basics, but I'm not sure if the issue is with something I am doing (or an event I need to handle) or a bug.

The first issue I've come across is when the client requests an incorrect protocol. 

I'm currently using 2.4.0 v2.0.0-701-gd2bc2d1

```
static struct lws_protocols protocols[] =
{
	/* The first protocol must always be the HTTP handler */
	{
		"http-only",   /* name */
		callback_http, /* callback */
		0,             /* No per session data. */
		0,             /* max frame size / rx buffer */
	},
	{
		"example-protocol",
		callback_websocket,
		0, 
		EXAMPLE_RX_BUFFER_BYTES,
	},
	{ NULL, NULL, 0, 0 } /* terminator */
};

static int callback_http( struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len )
{
  printf("callback_http %i \n",reason);
  return 0;
}

static int callback_websocket(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len ) {
  printf("callback_websocket %i \n", reason);
  return 0;
}

```

My client then tries to connect to the protocol "example-protocol2", the client exits with the correct error message. I get the following output:

callback_http 27 
callback_websocket 27 
callback_http 17 
callback_http 29 
callback_http 35 
callback_http 32 
callback_http 36 
callback_http 19 
callback_http 34 
callback_http 35 
callback_http 34 
callback_http 36 
callback_http 35 
callback_http 33 
callback_http 36

Then the CPU spins for about 5 seconds at 100% CPU, then I get:

callback_http 4 
callback_http 30 

The CPU then drops to 0.

The perl client is simply:

```
use warnings;
use strict;
use feature qw(say);
use Mojolicious;
use Mojo::UserAgent;

my $ua  = Mojo::UserAgent->new;
# WebSocket connection sending and receiving JSON
my $ws;
$ua->websocket('ws://localhost:8061/' => { 'Sec-WebSocket-Protocol' => 'example-protocol2'}=> sub {
  my ($ua, $tx) = @_;
  say 'WebSocket handshake failed!' and return unless $tx->is_websocket;
  say 'Websocket connected';
  $tx->on(json => sub {
    my ($tx, $hash) = @_;
    say "WebSocket message via JSON: $hash";

  });
  $tx->send({json => {cmd => 'hello'}});
});

Mojo::IOLoop->start unless Mojo::IOLoop->is_running;

```

The second issue I am having is when no protocol is specified.  I think the below is the correct way to specify this:

```
static struct lws_protocols protocols[] =
{
	/* The first protocol must always be the HTTP handler */
	{
		"http-only",   /* name */
		callback_http, /* callback */
		0,             /* No per session data. */
		0,             /* max frame size / rx buffer */
	},
	{
		NULL, //"example-protocol"
		callback_websocket,
		0, 
		EXAMPLE_RX_BUFFER_BYTES,
	},
	{ NULL, NULL, 0, 0 } /* terminator */
};
```

Then the perl client would connect with:

$ua->websocket('ws://localhost:8061/' => sub {

In this example the client connects, but the socket connection on the server side doesn't seem to get elevated to a websocket connection:

callback_http 27 
callback_http 17 
callback_http 29 
callback_http 35 
callback_http 32 
callback_http 36 
callback_http 19 
callback_http 34 
callback_http 20 
callback_http 53 
callback_http 0 
callback_http 6

When both the client and server use the same protocol ("example-protocol") then things work as expected. 

Thoughts?

**Comment by lws-team** [comment]
The second part you need to do differently, there's example code in test-server-v2.0.c, and it's documented how to do it with lwsws, I couldn't find how to do it in code explained in the docs though so I added an explanation here: https://github.com/warmcat/libwebsockets/commit/15820da8ba44b2ca7636c03046cc1493bef83322

The spinning I will look at later (lws logging is a lot more helpful to see what is happening than dumping callbacks).  I assume it's the server side doing the spinning.

**Comment by lws-team** [comment]
There are a couple of patches on v2.4-stable and master that should help with this.

**Comment by redbluetoken** [comment]
yes, spinning on server side. Seems to be fixed in master. I'll keep testing.

**Comment by lws-team** [comment]
Well, there is nothing for me to do,so no point keeping it open.  Let me know if any trouble appears.
