### ISSUE TITLE
user data in callback

### ISSUE THREAD

**Issue by karelzak** [warmcat/libwebsockets#1140]
I trying to use user data in the callback, and it's really painful (something is already in #819).

Not sure, but I guess many library users don't need any extra management for user data as expected by per_session_data_size.  All we usually need is to have void pointer to address user data *before* connection and later access to the pointer from the callback.  (See for example pthread_create(), qsort_r(), ... libc does not allocate any data for you, just pass the pointer to callback....)

Another user with the same issue:
https://libwebsockets.org/pipermail/libwebsockets/2015-August/001885.html

The best solution would be to add "void * persistent_user_data" to the lws_client_connect_info and make it accessible by a new function lws_get_wsi_persistent_user(wsi). So so...

**Comment by lws-team** [comment]
```
	void *userdata;
/**< if non-NULL, use this as wsi user_data instead of malloc it */
```

**Comment by karelzak** [comment]
Ah, sorry. So obvious now ;-) Somehow miss it in docs and by google... Thanks.

**Comment by lws-team** [comment]
No... include/libwebsockets/lws-client.h line 134

**Comment by alien999999999** [comment]
ah, i see my mistake, i mixed up the user and userdata from protocols and context_info... there is a lot of different meaning user / userdata things at various places; it is a bit confusing...

**Comment by alien999999999** [comment]
i just accidentally found https://libwebsockets.org/libwebsockets-api-doc.html would it be possible to link this up top of https://libwebsockets.org/ , in the bullets below doxygen API and the demo server? as useful as the doxygen is (it is not searchable, so you kinda have to know the category; and you cannot start from the structures to find the helper functions "belonging" with that data structure, and amazingly "**struct lws**" (the wsi) seems missing), that single page has a lots of good info that kinda belongs in the getting started.
