### ISSUE TITLE
websocket client timedout after every 10 mins

### ISSUE THREAD

**Issue by dhananjayj29** [warmcat/libwebsockets#1143]
Hi
I have lws client written , which creates ws connection with server .. if there is no transaction for 10 mins then it drops the tcp connection with server and not responding any further ..that too without any callback notification.
I wan to have this connection up forever...and never drop.

Is someone encountered this issue earlier and is there a place to specify this timeout values in lws client code

**Comment by lws-team** [comment]
What makes you think that is anything to do with lws, and not, eg your server's policy or something inbetween you and your server's policy?

Did you try the same test where both the client and server are on the same machine?

**Comment by lws-team** [comment]
Lws itself removes any timeout when then ws connection is established.  And if lws does timeout a connection, it always calls the close callback, since it definitively knows it's closing the connection.

I think you find "something else" simply stops passing network traffic on the connection.
