### ISSUE TITLE
lws_service return immediately in a unexpected way.

### ISSUE THREAD

**Issue by freemine** [warmcat/libwebsockets#1144]
I guess this might be a bug. Hereafter are the steps to follow:
1.  modify ./test-apps/test-client.c as such: (near line 817)
     printf("enter\n");
     lws_service(context, 500); // as origin
     printf("leave\n");
    and build as usual
2. open another terminal, and run:
      nc -lk 9000
3. switch back, and run:
    ./build/bin/libwebsockets-test-client https://localhost:9000/d
4. switch to the terminal as step 2, you shall see some input that coming from test-client
    and then Ctrl-C to terminate nc
5. switch back again, and you'll see 'enter/leave' pairs are scrolling on the screen

As compared, if we run instead in step 3 as:
./build/bin/libwebsockets-test-client http://localhost:9000/d
all seems smooth and nice.
Thus, I guess this might be bug relating to SSL.

**Comment by lws-team** [comment]
What's the ssl backend, openssl or mbedtls?  This is current master lws or something else?

**Comment by freemine** [comment]
openssl version:
OpenSSL 1.0.1f 6 Jan 2014

I am running this on my Ubuntu 14.04

**Comment by freemine** [comment]
git log:
b94091130bc7a9a037bd85fc9fa1f22c53aabe9e

**Comment by lws-team** [comment]
Can you try current master HEAD?  There's a patch since Dec 27 that may help.  If it doesn't I'll try to reproduce in the morning.

**Comment by freemine** [comment]
Well, just tried. And it seems still the same.

**Comment by freemine** [comment]
[test-simple.c.txt](https://github.com/warmcat/libwebsockets/files/1609843/test-simple.c.txt)

Just a simple start to reproduce. test-client.c is still to complex for this issue. :)

**Comment by lws-team** [comment]
Thanks, I could reproduce it with your test app.

Basically at the ssl version of connect(), OpenSSL reports SSL_ERROR_SYSCALL with errno 0... it evidently means the connection isn't going to happen.  I pushed a patch on master that reacts accordingly and this should be solved.

**Comment by freemine** [comment]
Thanks. It's ok now.
