### ISSUE TITLE
Performance issue with lws_parse

### ISSUE THREAD

**Issue by redbluetoken** [warmcat/libwebsockets#1146]
I have a server where the work load is to parse a JSON object, then fetch the key from the DB, and return the value to the client as a JSON object. It can be called via websockets or HTTP, the JSON object is the same in both cases.

When using HTTP only, the server takes much longer to complete the same request workload. valgrind --tool=callgrind  says:

websockets, I refs: 105,544,729
HTTP: I refs: 416,631,850

For a test case of 5000 JSON objects. The above counts are inclusive of DB work and memory management for the application. Looking at the trace through kcachegrind (image attached) it looks like a some of the cost of this function is due to calls _lws_log even though no logging is outputted. 

![08-01-2018 14-14-56](https://user-images.githubusercontent.com/35028694/34675399-5d74c132-f43e-11e7-81da-c35a2b924c51.png)

**Comment by lws-team** [comment]
"DB work" may not be as impressive as it sounds.  But I take the point about "same workload".

> some of the cost of this function is due to calls _lws_log even though no logging is outputted.

LLL_PARSER stuff should not be compiled in with CMAKE_BUILD_TYPE=RELEASE, so you are comparing the debug build.  In fact you can use LWS_WITH_NO_LOGS at cmake so only LLL_ERR and LLL_USER (which is not used inside lws) are compiled in.  So you should retry with those.

**Comment by redbluetoken** [comment]
You were right, it was a debug build which skewed the numbers massively. Using a release build, this is what I get:

HTTP      :I   refs:      223,672,472
websockets:I   refs:      92,465,407

Yes, the DB work isn't impressive, simply fetching a key, but there is a lot of malloc's/free's going on for each JSON fetch which effect the workload (much of this can/will be optimized out). As you can see, when running in HTTP, lws uses a large number of cycles:

HTTP:

![http](https://user-images.githubusercontent.com/35028694/34713550-7d7074d4-f4db-11e7-9c7a-06dc83a6e851.png)

Websockets:

![websocket](https://user-images.githubusercontent.com/35028694/34713573-8d347172-f4db-11e7-9db1-fd2e4703e4df.png)

**Comment by lws-team** [comment]
> You were right, it was a debug build which skewed the numbers massively.

Okay... but...

> As you can see, when running in HTTP, lws uses a large number of cycles:

...we still don't seem to have moved on from your original feeling, which is trying to tell me lws is "slow" along with the implication I should put aside Real Paying Work to improve it.  Now it comes down to the assertion, "lws uses a large number of cycles".

You were better off trying to tell me, "lws uses **more** cycles to do the same job as xxx".  Then I can feel inferior about xxx; preferably I (even more preferably, you) can also have xxx do the same and see what the difference is and if we can align lws to whatever magic xxx is doing to the joy of ourselves and future users.

But if you ask anything to do a lot of work, it will "[use] a large number of cycles".  At least as far as this goes I am unrepentant...

**Comment by redbluetoken** [comment]
> ...we still don't seem to have moved on from your original feeling, which is trying to tell me lws is "slow" along with the implication I should put aside Real Paying Work to improve it. Now it comes down to the assertion, "lws uses a large number of cycles".

I apologies if I have caused upset, that was not my intent. I am clearly new to using lws, and was simply reporting something I had noticed as an attempt to get more involved. I admit my language wasn't the clearest and was not meant to be accusatory in tone. This isn't the ideal forum and with the Libwebsockets mail Archives link down I had assumed this was the forum for general comment. I certainly wasn't expecting you to "improve" things on a whim, but the report may have provided some insight, an 'Aha' moment so to speak. I was even expecting that I was using lws incorrectly. 

> You were better off trying to tell me, "lws uses more cycles to do the same job as xxx". Then I can feel inferior about xxx; preferably I (even more preferably, you) can also have xxx do the same and see what the difference is and if we can align lws to whatever magic xxx is doing to the joy of ourselves and future users.

Once I've got my app stable with lws, I am quite happy to do this comparison, and indeed dig around the code more, if that has value to you and the broader lws community.

**Comment by lws-team** [comment]
> Libwebsockets mail Archives link down 

https://libwebsockets.org/pipermail/libwebsockets/ is not down :-)

https://libwebsockets.org/server-status/

If you have some patches I'll be very happy to look at them.

Your other issue seems to relate to changes in master recently, I will try to look at it tomorrow.

**Comment by redbluetoken** [comment]
> https://libwebsockets.org/pipermail/libwebsockets/ is not down :-)

Arh, apologies. If you goto https://libwebsockets.org/mailman/listinfo/libwebsockets, then click on Libwebsockets Archives, then you get an "The connection was reset" error (link should be https?)

> Your` other issue seems to relate to changes in master recently, I will try to look at it tomorrow.

Thanks. If you need me to create more examples etc, just let me know.

**Comment by lws-team** [comment]
>  (link should be https?)

Thanks... you are right about that, it's fixed now.

My clients all have "https everywhere" installed; it auto-upgrades the URL to https at the client so that's a problem I can't actually detect any more.
