### ISSUE TITLE
Static Compiled Example

### ISSUE THREAD

**Issue by RoJo73** [warmcat/libwebsockets#1147]
Hi,

Awesome software, I'm just a bit confused.  Would you be able to provide a complete example of a totally static compiled basic echo server ?

Whilst I've read through the documentation I am still a bit confused.  Probably the lack of coffee.  

This example will make a docker deployment quite nice!

thanks,

Rob

**Comment by lws-team** [comment]
Instead of just dumping this on me, without even mentioning the platform or toolchain, why don't you explain what you tried and your results.
