### ISSUE TITLE
wsi specific timeout

### ISSUE THREAD

**Issue by freemine** [warmcat/libwebsockets#1148]
It seems that if lws_service does not timeout, no LWS_CALLBACK_TIMER would be dispatched even user call lws_set_timer previously.

Is this designed-behavior?

**Comment by lws-team** [comment]
If you are using the default poll() backend, you must set the lws_service timeout value to <1000ms for normal operation.  Once per second it needs to wake and check timeouts and other periodic things.  If you don't follow that, and stay asleep, lws operates in a single thread... it's asleep until some network traffic wakes it.
