### ISSUE TITLE
Reference per-session user data outside of the callback

### ISSUE THREAD

**Issue by tsl0922** [warmcat/libwebsockets#1149]
Hi,

I'm writing a websocket server with libwebsockets, it starts a process when the client connected(`LWS_CALLBACK_ESTABLISHED`), and terminate the process when client disconnected(`LWS_CALLBACK_CLOSED`). 

But the close event won't always be triggered, however, the wsi and per-session user data will be freed, so reference to the per-session user data outside the callback will be unsafe.

Is there a reliable way (event) that can handle this scenario?

Thanks.

**Comment by lws-team** [comment]
Lws should always call back CLOSED on a wsi that had called back ESTABLISHED.

This is happening on latest master or something else?  Can it be reproduced with the test server?

**Comment by tsl0922** [comment]
I'm using the latest tagged release (v2.4.1), trying to reproducing it with the test server now.

**Comment by tsl0922** [comment]
Can not reproduce with the test server, the bug should be on my side, thank you.
