### ISSUE TITLE
possible problem with logging info after timeout?

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#1152]
I was chasing this down, which apparently you already fixed
https://github.com/warmcat/libwebsockets/commit/5a6764f218993f27f5a557e88ae18db44c8e4021

but while doing so I noticed this, not sure if it's a problem.

https://github.com/warmcat/libwebsockets/blob/master/lib/service.c#L1174
If the token it's matching is an empty string as mine was, it matches nothing and gets to the end of the set[] list which is a blank string, position 84 (in version 2.4.0)

Then it calls this to get the header for that blank entry.... (m being the blank/end marker entry)
				len = lws_hdr_total_length(wsi, m);

it does a header copy of something at that point (not sure how anything gets in that fragment list yet) and I ended up with a log that looked like this:

```
2018-01-11 14:10:28.625 [2944] [INFO:]          lwsc::> ah excessive hold: wsi 00000210193A4B60
  peer address: 10.0.21.88
  ah rxpos 0, rxlen 0, pos 67

2018-01-11 14:38:40.301 [2944] [INFO:]          lwsc::>     = my-protocol
```
As in the left side of the = was the blank entry, and the right side it happened to pick up the protocol name, not sure why.

Not sure it's a problem but I thought I'd mention it in case that fragment lookup of a non-existent header could cause a bad memory read somewhere. That hasn't happened to me yet, but you'd know better if it was possible.

**Comment by lws-team** [comment]
Thanks... it doesn't make any way to get a problem other than the possibility of the extra line in the dump.

There are some extra tokens defined after the last non-sentinel one...

```
        WSI_TOKEN_TE                                            = 83,
        /****** add new things just above ---^ ******/

        /* use token storage to stash these internally, not for
         * user use */

        _WSI_TOKEN_CLIENT_SENT_PROTOCOLS,
        _WSI_TOKEN_CLIENT_PEER_ADDRESS,
        _WSI_TOKEN_CLIENT_URI,
        _WSI_TOKEN_CLIENT_HOST,
        _WSI_TOKEN_CLIENT_ORIGIN,
        _WSI_TOKEN_CLIENT_METHOD,
        _WSI_TOKEN_CLIENT_IFACE,

        /* always last real token index*/
        WSI_TOKEN_COUNT,
```
... these extra "internal" ones exist in the ah and are zeroed down / processed with strings the same as the ones with matchable parsing names.

```
struct allocated_headers {
...
        struct lws_fragments frags[WSI_TOKEN_COUNT];
```

So yes, it does go over the extent of the list of parsing names by one, but the next guy exists, making the problem cosmetic only.  The reason it gave your protocol name wasn't random, _WSI_TOKEN_CLIENT_SENT_PROTOCOLS is used by lws to stash what the client told for the list of protocols.

I pushed a patch on v2.4-stable + master to end dumping the headers when we get to the empty string sentinel to get rid of the extra line.

**Comment by lws-team** [comment]
Sorry there is another patch needed as well, it's on v2.4-stable + master.
