### ISSUE TITLE
Is it threading-safety libwebsockets with libuv on windows?

### ISSUE THREAD

**Issue by BambooAce** [warmcat/libwebsockets#1153]
Hi
Whether Lws_libuv_run is safe at Multithreading?   If I use libuv at foreign loop, and the lws_context need to be locked?

Thanks.

**Comment by lws-team** [comment]
...hm.... libuv itself is not threadsafe.

When you use lws with libuv backend, actually lws does absolutely nothing that isn't part of handling a libuv event.  Lws does not have a "thread of its own", it runs **entirely** under the thread context of the libuv event loop.  So when libuv isn't calling it, from its thread context, lws will do NOTHING.

So if I understand your question, although neither libuv nor lws are "threadsafe", lws becomes completely subordinate to libuv when it is the backend, so there is no opportunity for trouble.

**Comment by BambooAce** [comment]
Thanks, Get it

**Comment by BambooAce** [comment]
@lws-team, and another question.  Does LWS have any way to use mutilthread to run the callback? Currently, I just saw a way that use pthread/poll to run service on Linux.  Is it possible?

**Comment by lws-team** [comment]
lws and libuv are single-threaded.  So no.

However it depends on what you are trying to do, which you have not explained at all.  If you get everything working in one instance for some amount of connections, on say :444, if you eg, architechted it to distribute data from a common source, you can just bring up a second instance on :445, or more instances on other machines, and tell the clients where to go to balance the load.

However you can handle huge numbers of connections in one lws instance (hundreds of thousands) if the task is not latency-critical.  So I would not assume that's a problem until you can see why it would be a problem.
