### ISSUE TITLE
Large write performance issue v2.4.1 and up

### ISSUE THREAD

**Issue by mulander** [warmcat/libwebsockets#1157]
Hi,

For the past few days I have been trying to narrow down a performance issue with large message writes (`1024*100` bytes per write over TLS). The issue is not straightforward so it's best that I outline the situation first.

I have a server at head.koparo.com - this is a linode hosted development server, code samples attached to this  ticket will have values hardcoded to run against it. The server is running a rails stack with an ActionCable websocket endpoint to which I have lws connecting. I wanted to see how well rails will handle large messages on the ActionCable so I implemented a benchmarking mode in our existing codebase that uses lws and already talks to this endpoint. The ActionCable protocol is detailed [in this github repository](https://github.com/NullVoxPopuli/action_cable_client#the-action-cable-protocol) but understanding it is not required to reproduce or understand the issue I'm having.

In the implemented benchmarking mode, I picked an arbitrary value for the packet payload which is `1024*100` bytes plus a small overhead of the protocol required remaining json fields, I also picked an arbitrary rate at which I'm attempting to send the messages which is one write en-queued every 16666 usecs. I then measured server side how many valid payloads the server saw delivered per second. To my surprise the value was 1 per second, event though when testing against a localhost server yielded 55-60 fps.

I initially assumed I'm using the API wrong, so after reading [this issue](https://github.com/warmcat/libwebsockets/issues/994#thread-subscription-status) I rewrote the application code to maintain a ring buffer of outgoing messages, sending them out in lws_writes that don't exceed the TX buffer set for the protocol per write and returning to the event loop as soon as `lws_partial_buffered` returns 1. This had no effect on measured performance so I started suspecting my uplink hence started testing on various setups.

Testing environments:
1. my laptop at home (OpenBSD -current amd64, 20/2 up/down)
2. vultr server (OpenBSD 6.2 amd64 100/100)
3. linode - head.koparo.com (Debian amd64 100/100)
4. linode - failover machine (Debian amd64 100/100)
5. Fedora laptop at a co-workers location amd64

Here are the test results:
1. laptop -> head.koparo.com => 1 payload per second observed.
2. vultr -> head.koparo.com => 1 payload per second observed
3. head.koparo.com -> head.koparo.com => **50 payloads** per second
4. linode.failover -> head.koparo.com => **50 payloads** per second
5. Fedora -> head.koparo.com => 1 payload per second observed

By tweaking the TX size (to 1024 * 101) and max write size (4096 per write) I was able to squeeze out 15-17 fps on test 1 & 2 but only for a period of 3 seconds max, after which performance degraded back to a single payload per second. 

The machines at vultr and linode are virtual private servers. Linode claims that 3 & 4 are hosted on separate physical hardware - they do however share a data center.

I wanted to rule out that the server itself (rails) is having performance issues, so I wrote a simple golang client performing the same benchmarking test and sending a 1024*100 packet every 8 milliseconds. To  my surprise, in all scenarios the go client runs at full speed of 55-58 packets per second as observed server side.

Here are the test results of the golang client:
1. laptop -> head.koparo.com => **2-3 payloads** per second (my upstream limit hit with other traffic on my local network)
2. vultr -> head.koparo.com => **50 payloads** per second
3. head.koparo.com -> head.koparo.com => **50 payloads** per second
4. linode.failover -> head.koparo.com => **50 payloads** per second
5. Fedora -> head.koparo.com => not tested

I did try moving up to the unreleased lws 2.5, saw no change in performance except the library complaining on back-to-back writes which I eliminated when testing with that unreleased version.

I am running out of ideas so I'm reaching out for suggestions on where to look. I created 2 repositories with code that replicates the above tests both in C using LWS and in Go. I made them public and hardcoded to run against head.koparo.com - it's possible to reproduce and see the same behavior using that code.

Here are the repositories, their README's detail how to build and run the tests:

1. https://github.com/Koparo/lwsbench/ - C using libwebsockets v2.4.1
2. https://github.com/Koparo/wsbench - Go

It's quite possible that I'm just using the libwebsockets API in a very wrong way and would appreciate any pointers on that, however I find it very weird that test case 4 (2 machines in the same datacenter) runs at full expected performance.

**Comment by lws-team** [comment]
Sorry, it's Friday evening here I can't really absorb all of these details specific to your case.

You seem to be saying you can make something go wrong on Fedora

> Fedora -> head.koparo.com => 1 payload per second observed

instead of detailing everything about your situation, which in truth I have no reason to specifically care about, why not change tack and just explain how I - on Fedora - can see a problem on lws, which I do care about, preferably based around the test apps with whatever hacks are needed.

**Comment by mulander** [comment]
Hi, first of I am aware it's Friday - appreciate any help and don't expect it soon :)

Steps to reproduce:

1. `git clone git@github.com:Koparo/lwsbench.git`
2. `cd lwsbench`
3. `mkdir build; cd build; cmake ..; make`
4. `./camcell`

when it connects, `B` followed by hitting enter will send a single write, `b` followed by hitting enter will start a loop with writes every 16666 usecs.

The go client:
1. `go get github.com/koparo/wsbench`
2. `wsbench`

the wsbench starts sending immediately.

You will be able to observe the rate at which packets are sent.

**Comment by lws-team** [comment]
Thanks.... I am on f27...

1) it also need jansson-devel before cmake will complete.

2) On making it , I get:

```
$ make
Scanning dependencies of target camcell
[ 25%] Building C object CMakeFiles/camcell.dir/src/main.c.o
In file included from /usr/include/sys/stat.h:25:0,
                 from /tmp/lwsbench/src/main.c:4:
/usr/include/features.h:183:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
```

after changing the _BSD_SOURCE to _DEFAULT_SOURCE...

3) 
```
/tmp/lwsbench/src/tsunami/tsunami.c: In function ‘tsunami_event_cb’:
/tmp/lwsbench/src/tsunami/tsunami.c:405:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (type & EV_READ)
   ^~
/tmp/lwsbench/src/tsunami/tsunami.c:407:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    pollfd.revents |= LWS_POLLIN;
    ^~~~~~
/tmp/lwsbench/src/tsunami/tsunami.c:408:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (type & EV_WRITE)
   ^~
/tmp/lwsbench/src/tsunami/tsunami.c:410:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    pollfd.revents |= LWS_POLLOUT;
    ^~~~~~
```

It's true: the indendation is dangerously misleading, I guess you got infected by Python

```
                if (type & EV_READ)
                        pollfd.events |= LWS_POLLIN;
                        pollfd.revents |= LWS_POLLIN;
                if (type & EV_WRITE)
                        pollfd.events |= LWS_POLLOUT;
                        pollfd.revents |= LWS_POLLOUT;
```

with this, I can build it

```
diff --git a/src/main.c b/src/main.c
index 2740bcf..2aa4867 100644
--- a/src/main.c
+++ b/src/main.c
@@ -1,4 +1,4 @@
-#define _BSD_SOURCE 1
+#define _DEFAULT_SOURCE 1
 #define _POSIX_C_SOURCE 1
 
 #include <sys/stat.h>
diff --git a/src/tsunami/tsunami.c b/src/tsunami/tsunami.c
index 1582870..66089c8 100644
--- a/src/tsunami/tsunami.c
+++ b/src/tsunami/tsunami.c
@@ -1,4 +1,4 @@
-#define _BSD_SOURCE 1
+#define _DEFAULT_SOURCE 1
 
 #include <assert.h>
 #include <err.h>
@@ -402,12 +402,14 @@ tsunami_event_cb(int fd, short type, void *data)
                pollfd.fd = fd;
                pollfd.events = 0,
                pollfd.revents = 0;
-               if (type & EV_READ)
+               if (type & EV_READ) {
                        pollfd.events |= LWS_POLLIN;
                        pollfd.revents |= LWS_POLLIN;
-               if (type & EV_WRITE)
+               }
+               if (type & EV_WRITE) {
                        pollfd.events |= LWS_POLLOUT;
                        pollfd.revents |= LWS_POLLOUT;
+               }
                lws_service_fd(tsu->context, &pollfd);
        } else if (type & EV_TIMEOUT) {
                struct timeval tv = { 1, 0 };
```

It starts up after that and does some kind of PING every few secs

4)

$ go get github.com/koparo/wsbench
$ wsbench
bash: wsbench: command not found...

**Comment by mulander** [comment]
ouch on the dangling if, thanks for spotting that :man_facepalming: 

the moment you see pings you can enter the benchmarking loop by hitting `b` followed by the enter key.

for golang:
`$ export GOPATH=$HOME/go`
`$ export PATH=$PATH:$GOPATH/bin`
`$ go get github.com/koparo/wsbench`
`$ wsbench`

**Comment by lws-team** [comment]
> the moment you see pings you can enter the benchmarking loop by hitting b followed by the enter key.

I do that and it starts scrolling up like

```
...
Message queue full
Message queue full
Message queue full
Message queue full
37141856-d137-4f27-8c23-be4c2740d71b CAMERA: rx 36 '{"type":"ping","message":1516366727}'
(CABLE_PING)
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
Message queue full
...
```

Running the `wsbench` thing in another terminal, he emits this and then receives pings every few second

```
Hello World!
-> {"command":"subscribe", "identifier":"{\"channel\":\"BenchmarkChannel\", \"uuid\":\"71357086-787a-4fe4-afc9-72dd1f21a5fb\"}"}
-> {"command":"subscribe", "identifier":"{\"channel\":\"GroupChannel\", \"uuid\":\"71357086-787a-4fe4-afc9-72dd1f21a5fb\"}"}
-> {"command":"subscribe", "identifier":"{\"channel\":\"PresenceChannel\", \"uuid\":\"\"}"}
2018/01/19 21:00:01 recv: {"type":"welcome"}
2018/01/19 21:00:02 recv: {"identifier":"{\"channel\":\"BenchmarkChannel\", \"uuid\":\"71357086-787a-4fe4-afc9-72dd1f21a5fb\"}","type":"confirm_subscription"}
2018/01/19 21:00:02 recv: {"identifier":"{\"channel\":\"PresenceChannel\", \"uuid\":\"\"}","type":"confirm_subscription"}
2018/01/19 21:00:02 recv: {"identifier":"{\"channel\":\"GroupChannel\", \"uuid\":\"71357086-787a-4fe4-afc9-72dd1f21a5fb\"}","type":"confirm_subscription"}
2018/01/19 21:00:02 recv: {"identifier":"{\"channel\":\"PresenceChannel\", \"uuid\":\"\"}","message":{"group_id":39}}
2018/01/19 21:00:03 recv: {"type":"ping","message":1516366802}
2018/01/19 21:00:06 recv: {"type":"ping","message":1516366805}
2018/01/19 21:00:09 recv: {"type":"ping","message":1516366808}
```

**Comment by mulander** [comment]
yes, the rates can bee seen at: https://head.koparo.com/lwsbench.txt (I updated the previous comment).

From your test:
```
koparo:v1:37141856-d137-4f27-8c23-be4c2740d71b:1516366710  1 <- lwsbench
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366803  13 <- wsbench
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366804  16
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366805  17
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366806  19
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366807  18
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366808  19
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366809  19
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366810  20
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366811  20
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366812  20
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366813  19
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366814  21
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366815  23
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366816  25
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366817  27
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366818  26
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366819  39
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366820  25
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366821  21
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366822  22
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366823  24
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366824  25
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366825  25
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366826  25
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366827  24
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516366828  24
```

`Message queue full` shows up if the already en-queued  messages didn't leave on lws before the next tick.

**Comment by lws-team** [comment]
How about

```
diff --git a/src/tsunami/tsunami.c b/src/tsunami/tsunami.c
index 1582870..ed3ded3 100644
--- a/src/tsunami/tsunami.c
+++ b/src/tsunami/tsunami.c
@@ -20,7 +20,7 @@ typedef enum {
 #define UUID_LEN 37
 
 /* rx buffer size per websocket message */
-#define RX_BUFF_LEN 4096
+#define RX_BUFF_LEN 32768
 
 /* maximum length of the built request URI
  * including hostname and GET parameters */
@@ -328,7 +328,8 @@ tsunami_init(tsunami_type type, const char *uuid, const char *wshost,
        info->uid = -1;
        info->user = tsu;
        info->options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
- 
+       info->pt_serv_buf_size = 32768;
+
        tsu->context = lws_create_context(info);
        if (tsu->context == NULL)
          errx(1, "Creating libwebsocket context failed");
```

**Comment by mulander** [comment]
With the above change (`info->pt_serv_buf_size = 32768;` plus `RX_BUFF_LEN` upped to `32768`) while testing send from vultr to head.koparo.com the performance improves from one observed read to around 4-5 per second.

```
koparo:v1:519e4d3e-6442-41be-9301-f58f5b999b86:1516368319  2
koparo:v1:519e4d3e-6442-41be-9301-f58f5b999b86:1516368320  4
koparo:v1:519e4d3e-6442-41be-9301-f58f5b999b86:1516368321  5
koparo:v1:519e4d3e-6442-41be-9301-f58f5b999b86:1516368322  2
```
the golang test from the same server:

```
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368450  45
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368451  50
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368452  50
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368453  49
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368454  51
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368455  50
koparo:v1:71357086-787a-4fe4-afc9-72dd1f21a5fb:1516368456  50
```

**Comment by lws-team** [comment]
> vultr to head.koparo.com the performance improves from one observed read to around 4-5 per second.

Ultimately network programming isn't like programming to a schedule as it may be on a local box, where you can have meaningful 1kHz interrupts with relatively low jitter and DMA lots of data around.

Something may have a fervent hope that it is going to spam 100KiB at 16ms intervals (ie, 6MiB/s) to somewhere else over the internet, but the reality of that is in the hands of the network outside your control, especially on tcp rather than udp.

The design choice in lws to follow something becoming "writeable" is quite deep, it boils down to ACKs coming back making space in the tcp window,  There is nothing written anywhere that those ACKs are going to come sufficient to maintain 6MiB/s throughput from any random A to B.  For example if the guy is on a 4G phone, and he goes in a mountain tunnel, or a place where he only has lower bandwidth, he can't keep up.

That's your problem to architect the thing that sends so that it adapts (ie, skips frames) to network conditions.

**Comment by mulander** [comment]
Thank you for your time and the reply.

I assume then you didn't see anything apparently wrong in my usage of LWS that would cause degraded performance apart from the dangling if and the suggested buffer changes.

By making this ticket I wanted to make sure that I'm not making some stupid API usage error. I am aware that comparing Go and LWS here is an apple to oranges, I only did that to rule out the rails backend as the bottleneck.

You explanation actually explains why I'm reaching full asked rate with linode -> linode in the same data center.

Sorry for taking your time and sincere  thanks for helping me out with this on a Friday. I hope you have a great weekend.
