### ISSUE TITLE
cpu high when 'SSL_do_handshake'

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1162]
hi, lws team 
Thx for the library first.
I met a problem about cpu 100% whehn I received some wss messages .
Part of my lws-server  context info was be inited as below:

```
int init_context_info(struct lws_context_creation_info *info)
{
    int opts = 0;
    opts |= LWS_SERVER_OPTION_LIBEV;
    info->port = g_sinfo.listen_port;
    info->iface = g_sinfo.iface;
    info->protocols = protocols;
    info->gid = -1;
    info->uid = -1;
    info->options = opts;
    info->count_threads = 1;
    info->max_http_header_pool = 4;
    info->ka_time = 30;
    info->ka_probes = 2;
    info->ka_interval = 30;
    info->server_string = “ws-server”;
    info->extensions = NULL;
    info->ssl_cert_filepath = "/data/xxx";// 
    info->ssl_private_key_filepath = "/data/xxx";
    info->ssl_ca_filepath = "/data/xxx";
    info->ssl_cipher_list = "ECDHE-ECDSA-AES256-GCM-SHA384:"
                                "ECDHE-RSA-AES256-GCM-SHA384:"
                                "DHE-RSA-AES256-GCM-SHA384:"
                                "ECDHE-RSA-AES256-SHA384:"
                                "HIGH:!aNULL:!eNULL:!EXPORT:"
                                "!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:"
                                "!SHA1:!DHE-RSA-AES128-GCM-SHA256:"
                                "!DHE-RSA-AES128-SHA256:"
                                "!AES128-GCM-SHA256:"
                                "!AES128-SHA256:"
                                "!DHE-RSA-AES256-SHA256:"
                                "!AES256-GCM-SHA384:"
                                "!AES256-SHA256";
        /* redirect guys coming on http */
   info->options |= LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT;

    info->options = opts | LWS_SERVER_OPTION_VALIDATE_UTF8 | LWS_SERVER_OPTION_EXPLICIT_VHOSTS | LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
return 0;
}
```

I used callgrind to check what caused high cpu , found that back trace as below:

```
    [ 0]  read (19183676 x)
   [ 1]  sock_read (19183676 x)
   [ 2]  BIO_read (19183676 x)
   [ 3]  ssl3_read_n (18207676 x)
   [ 4]  ssl3_get_record (19279315 x)
   [ 5]  ssl3_read_bytes (19281776 x)
   [ 6]  tls_get_message_header (19281776 x)
   [ 7]  state_machine (19278681 x)
   [ 8]  ossl_statem_accept (19278681 x)
   [ 9]  SSL_do_handshake (19276533 x)
   [10]  SSL_accept (19278681 x)
   [11]  lws_server_socket_service_ssl (19277573 x)
   [12]  lws_server_socket_service (19280241 x)
   [13]  lws_service_fd_tsi (19303744 x)
   [14]  lws_service_fd (19291481 x)
   [15]  lws_accept_cb (11374416 x)
   [16]  ev_invoke_pending (11374562 x)
   [17]  ev_run (1 x)
   [18]  main (1 x)
   [19]  (below main) (1 x)
   [20]  0x00000000004077b7 (1 x)
   [21]  0x0000000000001260
```

is there something wrong? or how can I use async ssl connection instead of SSL_do_handshake what is sync function?

**Comment by lws-team** [comment]
1) What version of lws?

2) What version of OpenSSL?

3) What platform?

4) Lws uses nonblocking sockets, so this is all asynchronous.

It looks like lws misunderstands the situation at SSL_accept() return.  It should only get signalled to go back there after the accept() completes or fails.  There were problems with this a while back on master but I don't know of any problem now.

**Comment by xmanmax** [comment]
thanks for your reply!!!!
Sorry ... forgot env information
lws is v2.3-stable,, OpenSSL is 1.1.0f, and use ubuntu platform .
when i start my program, it has some ssl error as below, but only occurred while starting the program.

[2018/01/24 12:17:46:3750] ERR: lws_ssl_capable_read failed: error:00000001:lib(0):func(0):reason(1)
[2018/01/24 12:17:46:3751] ERR: *** error:1408F09C:SSL routines:ssl3_get_record:http request
[2018/01/24 12:17:47:0669] ERR: lws_ssl_capable_read failed: error:00000001:lib(0):func(0):reason(1)
[2018/01/24 12:17:47:0669] ERR: *** error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
[2018/01/24 12:17:48:1687] ERR: lws_ssl_capable_read failed: error:00000001:lib(0):func(0):reason(1)
[2018/01/24 12:17:48:1687] ERR: *** error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
[2018/01/24 12:17:48:1688] ERR: *** error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
[2018/01/24 12:17:48:1688] ERR: *** error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

cpu still 100% if has ws connection happened.using kcachegrind to check invoke relationship and cpu time usage,.

include invoked function, cpu usage as below:
the cycle:     99.99%
rand_add.par.1     45.95%
EVP_DigestFinal_ex     23.49%
final     21.54%
SHA1_Final     21.37%
sha1_block_data_order     18.48%
sha1_block_data_order_avx    18.2%
rsa_ossl_private_encrypt     10.31%
rsa_ossl_mod_exp     10.27%
BN_mod_exp_mont   10.25%
bn_power5    9.63%
...

not inclue invoked functions, cpu usage as below:
the cycle       22.92%
sha1_block_data_order_avx      18.2%
bn_sqr8x_internal         7.44%
OPPENSSL_cleanse      5.08%
rand_add.par.1     4.87%
ERR_clear_error     3.94%
lws_change_pollfd     3.85%
SHA1_Update     3.27%
...

part of my main function is


    struct ev_signal signals[ARRAY_SIZE(sigs)];
    loop = ev_default_loop(0);
    unsigned int n = 0;
    for (; n < ARRAY_SIZE(sigs); n++)
    {
        ev_init(&signals[n], signal_cb);
        ev_signal_set(&signals[n], sigs[n]);
        ev_signal_start(loop, &signals[n]);
    }
    lws_ev_initloop(g_context, loop, 0); //g_context is the context created above
    ev_run(loop, 0);

is there something wrong ?

**Comment by lws-team** [comment]
> lws is v2.3-stable

Can you try master for comparison?

Also is this happening with the lws test server on your platform?

> [2018/01/24 12:17:48:1687] ERR: *** error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

What does the client you are connecting with say at this time?

**Comment by lws-team** [comment]
...any news?

**Comment by xmanmax** [comment]
hi, I tryied v2.4-stable and master, it`s not happened yet . .
And btw, v2.3-stable always happening.
so, thank you very much ,but i still want to know the root cause ,...

**Comment by xmanmax** [comment]
Also I found that when I used v2.3, tcp connect finished by  "FIN,ACK --> ACK -->FIN,ACK -->ACK",
but for v2.4, it was "FIN,ACK --> FIN,ACK --> ACK" ，it looks strange..

**Comment by lws-team** [comment]
>  i still want to know the root cause

If you really want to know it, you can use git bisect between v2.3 and v2.4-stable HEAD; v2.3 release is also in v2.4-stable tree.  But I think no point... master is the real prize that should work best... all the releases are created from master.  So if master works well, future releases will work well.

> tcp connect finished by "FIN,ACK --> ACK -->FIN,ACK -->ACK"

If the connect was accepted... what is the problem?
