### ISSUE TITLE
Build with mbedTLS on OSX

### ISSUE THREAD

**Issue by bitomaxsp** [warmcat/libwebsockets#1163]
Unable to build with bmedTLS on OSX (BSD system) because of the following:
```C
/*
#include "esp_types.h"
#include "esp_log.h"
*/
#include "string.h"
#include "malloc.h".  <-------- NOT FOUND ON OSX
```

`malloc/free` declared in `stdlib.h` on osx

library is configure with the following flags:
`cmake -DCMAKE_BUILD_TYPE=Release -DLWS_WITH_ZLIB=OFF -DLWS_WITH_SHARED=OFF -DLWS_WITHOUT_SERVER=ON -DLWS_WITHOUT_TESTAPPS=ON -DLWS_WITHOUT_TEST_SERVER=ON -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON -DLWS_WITHOUT_TEST_PING=ON -DLWS_WITHOUT_TEST_ECHO=ON -DLWS_WITHOUT_TEST_CLIENT=ON -DLWS_WITHOUT_TEST_FRAGGLE=ON -DLWS_WITHOUT_EXTENSIONS=ON -DLWS_IPV6=ON -DLWS_STATIC_PIC=ON -DLWS_WITH_ZIP_FOPS=OFF -DLWS_WITH_MBEDTLS=ON -DLWS_MBEDTLS_INCLUDE_DIRS=../.build-tls/mbedTLS-2.6.1-Darwin/include -DMBEDTLS_LIBRARY=../.build-tls/mbedTLS-2.6.1-Darwin/lib -DMBEDX509_LIBRARY=../.build-tls/mbedTLS-2.6.1-Darwin/lib -DMBEDCRYPTO_LIBRARY=../.build-tls/mbedTLS-2.6.1-Darwin/lib ../libwebsockets`

If I replace `"malloc.h"` with `"stdlib.h"` i can successfully build it.

Would you mind sharing your concerns regarding the issue?
Would it make sense for me to open a PR?

**Comment by lws-team** [comment]
Does 1b43ed1cbaf189fd1a2a5da21a282bd03284bb22 solve it for you?  It doesn't affect my platform which has malloc.h.

**Comment by bitomaxsp** [comment]
It should. thank you.

**Comment by bitomaxsp** [comment]
Confirmed, it works

**Comment by lws-team** [comment]
Thanks :-)
