### ISSUE TITLE
Unable to get libwebsockets to work with SSL

### ISSUE THREAD

**Issue by mliras** [warmcat/libwebsockets#1164]
I'm finding an error when trying to connect a libwebsocket client with a server using SSL. This is the Error found:

[2018/01/26 15:05:18:9891] ERR: SSL_new failed: error:00000001:lib(0):func(0):reason(1)
[2018/01/26 15:05:18:9891] ERR: *** 336306371 error:140BA0C3:SSL routines:func(186):reason(195)

I followed the steps explained in https://github.com/warmcat/libwebsockets/issues/723 and the browser connects fine with libwebsockets-test-server. 

In my program both client & server  connect fine if unencrypted (0 in lws_client_connect) communication is requested, but when indicating value '2' (use selfsigned cert) in lws_client_connect, the previous error occurs.

I have found that the error is the same if I use 2 (self signed certificates) or 1 (= wss:// encrypted) in the lws_client_connect call.

The certificate and key were obtained with openssl:
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650

This is my code:

CLIENT
======
...
   info.port = CONTEXT_PORT_NO_LISTEN;
   info.iface = NULL;
   info.protocols = &protocol;
   info.ssl_cert_filepath = NULL;
   info.ssl_private_key_filepath = NULL; 
   info.extensions = lws_get_internal_extensions();
   info.gid = -1;
   info.uid = -1;
   info.options = 0;
   protocol.name="My_Protocol";
   protocol.callback = &service_callback;
   protocol.per_session_data_size = sizeof(struct session_data);
   protocol.rx_buffer_size = 0;
   protocol.id = 0;
   protocol.user = NULL;
   
   context = lws_create_context(&info);
   if (context == NULL) exit (-1);
	
wsi = lws_client_connect(context, "127.0.0.1", 5000, 2,"/webServices/myprot/CP3211", buf, NULL,protocol.name, -1);

SERVER
=======
   protocol.name = "My_Protocol";
    protocol.callback = service_callback;
    protocol.per_session_data_size=sizeof(struct per_session_data);
    protocol.rx_buffer_size = 0;
    memset(&info, 0, sizeof info);
    info.port = 5000; 
    info.iface = interface;
    info.protocols = &protocol;
    info.extensions = lws_get_internal_extensions();
    info.ssl_cert_filepath = "example-server/Debug/cert.pem";
    info.ssl_private_key_filepath = "example-server/Debug/key.pem";  
    info.gid = -1;
    info.uid = -1;
    info.options = 0;

    context = lws_create_context(&info);
    while ( !destroy_flag ) {
        lws_service(context, 300);
        lws_callback_on_writable_all_protocol(context,&protocols[0]);
    }

What could be happening?

Thank you for your help!

**Comment by lws-team** [comment]
```
$ openssl errstr 140BA0C3
error:140BA0C3:SSL routines:SSL_new:null ssl ctx
```

> info.options = 0;

Nope... look again at info.optionsbwhen using ssl in the test apps.

**Comment by mliras** [comment]
Thank you for your response. I added 
info.options=LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT

in the client side and left 
info.options=0 

in the server side.

It connects but... only the messages from the client to the server go encrypted, responses from the server side travel in clear...

I tried different options in the server side: LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT or LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT... but with any them the client do not connect with the server (The error that appears is:

 ERR: SSL_accept failed skt 15: error:00000001:lib(0):func(0):reason(1)
 ERR: *** error:1408F09C:SSL routines:ssl3_get_record:http request
 ERR: SSL_accept failed skt 15: error:00000005:lib(0):func(0):DH lib

Any idea?

**Comment by lws-team** [comment]
The test server and test client you are trying to base off of have no problem.  So just like your original issue, you failed to align your sources to what they do.  That's something for you to fix in your code by comparing your code to the working test server / client.
