### ISSUE TITLE
Headers and lws_config.h missing from Windows binaries built by AppVeyor

### ISSUE THREAD

**Issue by caskater4** [warmcat/libwebsockets#1165]
I have pulled the pre-built binaries from AppVeyor for Win64 and default but they are missing both the libwebsockets.h and lws_config.h headers needed to integrate the library into my code base.

I have pulled the libwebsockets.h directly from github but I am still missing the lws_config.h file. According to the docs it's supposed to be generated when the build is made.

**Comment by lws-team** [comment]
I pushed a patch on appveyor.yml that should have fixed it.

**Comment by lws-team** [comment]
After another patch copying the generic libwebsockets.h from another place, I confirmed it's fixed.
