### ISSUE TITLE
u_int64_t redefined

### ISSUE THREAD

**Issue by walkthetalk** [warmcat/libwebsockets#1167]
in lib/libwebsockets.h
we checking macro (u_int64_t), but in musl, it is a typedef, not macro, so libwebsockets redefined 'u_int64_t'.

another problem, I checked the header, it use 'uint64_t', not 'u_int64_t', why need it?

#if !defined(u_int64_t)
#define u_int64_t unsigned long long
#endif

**Comment by lws-team** [comment]
Don't need it... I pushed a patch on v2.4-stable and master removing it (and changing the one use to uint64_t )

**Comment by walkthetalk** [comment]
thanks!
