### ISSUE TITLE
LWS_NO_EXTENSIONS

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1169]
Hi sir,

What is this extensions used for ?

static const struct lws_extension exts[] = {
	{
		"permessage-deflate",
		lws_extension_callback_pm_deflate,
		"permessage-deflate; client_max_window_bits"
	},
	{
		"deflate-frame",
		lws_extension_callback_pm_deflate,
		"deflate_frame"
	},
	{ NULL, NULL, NULL /* terminator */ }
};

**Comment by lws-team** [comment]
https://tools.ietf.org/html/rfc7692

**Comment by arunkvnss** [comment]
hi , why i am coming into this, because of when my server sending data with 8192 bytes after some time the transaction got stopped. I did not know the reason behind it , And when i looked into the code and some documentation i understood that there is something called "client_max_window_bits" extension ehich i set in the context. when i remove the complete extensions the transaction is working properly.

**Comment by arunkvnss** [comment]
And is there any sample code which handles the windowing in libwesocket ?
