### ISSUE TITLE
Deploy binary packages to Conan Central

### ISSUE THREAD

**Issue by caskater4** [warmcat/libwebsockets#1170]
Please consider supporting Conan, the C/C++ package manager, and deploying pre-built binary packages of libwebsockets to the Conan Central repository.

[https://conan.io](https://conan.io)

**Comment by lws-team** [comment]
AFAICT this is done

https://bintray.com/lws-team/libwebsockets/windows#files

**Comment by jonasatturck** [comment]
Can we open this up again? Because there are some versions available, but by far not all of them. Latest 4.3.x available is 4.3.5.
