### ISSUE TITLE
unable to get issuer certificate on Windows.

### ISSUE THREAD

**Issue by BambooAce** [warmcat/libwebsockets#1171]
Hi
I tried my certificate signed by GeoTrust-CA  with LWS-SSL. It is no problem at Centos. The client works although not set **client_ssl_ca_filepath** option.  But when  at Win7, it always reported like this:
```
[2018/02/01 10:13:57:6645] ERR: SSL error: unable to get issuer certificate (pre
verify_ok=0;err=2;depth=1)
[2018/02/01 10:13:57:6645] ERR: SSL connect error 337047686: error:1416F086:SSL
routines:tls_process_server_certificate:certificate verify failed
```

My client code 
```
       use_ssl = 1;
	info.ssl_cert_filepath = NULL;
	info.ssl_private_key_filepath = NULL;
	info.gid = -1;
	info.uid = -1;
	info.extensions = exts;
	info.options = opts | LWS_SERVER_OPTION_VALIDATE_UTF8;
	info.client_ssl_ca_filepath = "./ca.pem";
	if (use_ssl)
	{
		info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
		//info.options |= LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS;
	}
	info.extensions = exts;
	context = lws_create_context(&info);
	if (context == NULL) {
		lwsl_err(">>>>>>>>>>>>>>>>>libwebsocket init failed\n");
		return -1;
	}
	signal(SIGINT, sighandler);
	i.context = context;
	i.address = address;
	i.port = port;
	if (use_ssl){
		i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;
		//i.ssl_connection = 0;
			
	}

```
No matter I set  LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS or not,  it always not work.  Is any else options I missed on Windows?  How to disable verify the CA ?

**Comment by BambooAce** [comment]
It‘s no problem use browser access server on Windows。

**Comment by lws-team** [comment]
> It is no problem at Centos.

I would guess there are differences between what is in the default trusted CA store in Centos and what is in Windows 7... the browser may be carrying around its own certificate store installed with the browser.

I would look at what CA and intermediate cert (s) if any are in your server's response, eg

https://www.sslshopper.com/ssl-checker.html

It should provide "your cert" at the top, along with any intermediate certs and the CA cert should be in your OS trust store.

**Comment by BambooAce** [comment]
Oh.....，I`m sorry.  There is something with my CA certificate on Windows, I copy it from Centos,  it works. Thanks a lot.
