### ISSUE TITLE
Compilation error when configuring the library for multithreading support

### ISSUE THREAD

**Issue by georgekjolly** [warmcat/libwebsockets#1172]
Compilation error when configuring the library for multithreading support with flag
 -DLWS_MAX_SMP

Branch(v2.4-stable)

Below code snippet in context.c giving a compilation error.

#if LWS_MAX_SMP > 1
	pthread_mutex_destroy(&context->lock, NULL);
#endif

Issue is resolved when I changed pthread_mutex_destroy(&context->lock, NULL) to pthread_mutex_destroy(&context->lock);

Thanks
George

**Comment by lws-team** [comment]
Thanks... it was already fixed on master.  I pushed a patch on v2.4-stable.
