### ISSUE TITLE
Reconnect on disconnection

### ISSUE THREAD

**Issue by mliras** [warmcat/libwebsockets#1174]
In a working Client-Server LibWebsocket communication, I need the client to be able to keep working through temporary connection interruptions. In other words: I need to reconnect interrupted connections.

When the connection between client & server is interrupted, in the client side I get a call to the service_callback function with the LWS_CALLBACK_CLOSED reason. My idea is, in that moment, to create a new thread that tries to reconnect periodically to the server. To do that, inside the infinite loop of the thread I follow the same steps that I do in the initial connection (prepare info struct, prepare the protocol struct, create the context and call lws_client_connect).

However, when the server comes up again (I'm simulating the interruption by stopping and restarting the server side), the connection does not initiates. I can see with wireshark that the three-way handshake is correctly done but the "GET /webservices/XXXX HTTP1.1" request which is performed in the initial connection is never sent now.

Why could this be happening?

**Comment by lws-team** [comment]
"Guess what I did wrong from a description of what I think I did" might make a good party game if the questioner shouts out "cold", "warm" to suggestions.  But it's not much fun in real life.

The test client shows how to do this (without throwing a thread on it), you can run the test client against the test server going up and down to confirm it.  Just align your code to how the test client does it.
