### ISSUE TITLE
Client Server chat application using websocket

### ISSUE THREAD

**Issue by ajupawar555** [warmcat/libwebsockets#1176]
Hello Andy Green,
I want to implement client-server chat application using web socket
I have tried with running libwebsockets-test-server as a server and libwebsockets-test-echo as a client

data (Client TX: hello from libwebsockets-test-echo client pid 23359 index 5)
is transmitted from the client to the server but not received at the receiver server side

can you please help me to know more about this issue?
Which files support this application?
How to run those files?

**Comment by ajupawar555** [comment]
One more question 
How should i set the protocol at the client side which is not supported by the client?

**Comment by lws-team** [comment]
> Which files support this application?

The mirror protocol in the test apps is the best match for it (the one used to share the drawings).  The drawing elements are just text.

> How should i set the protocol at the client side which is not supported by the client?

What?  You're asking how should it speak greek if it doesn't know how to speak greek?

**Comment by ajupawar555** [comment]
Sorry for the second question....my low understanding

**Comment by ajupawar555** [comment]
Thank u:)

**Comment by ajupawar555** [comment]
can i send HELLO message to the server using libwebsockets-test-client?
i am done this with java script using socket.send("HELLO") but i want to send HELLO message using C program can u please help

**Comment by lws-team** [comment]
Just look at the example code, eg, dumb-increment.  Have a look through READMEs/README.coding.txt
