### ISSUE TITLE
lws_send_pipe_choked

### ISSUE THREAD

**Issue by awais40** [warmcat/libwebsockets#1180]
Hi, i am using lws2.4. i have some webpages with communicate with the lws application. when a certain webpage is opened, lws application start to send data using
if(lws_send_pipe_choked(lws)==0)
lws_write(lws,(unsigned char*)(msgs +WS_SEND_BUFFER_PRE_PADDING),len ,LWS_WRITE_TEXT );

it work fine for some pages but for some pages lws_send_pipe_choked(lws) is !=0, it remain !=0 unless i restart lws applicaiton and when i restart lws application, it start working for that issue pages but stop working for someother pages and sometime it work fine for all pages.

**Comment by lws-team** [comment]
You may only use lws_write() from the WRITABLE callback.  Is that what you are doing?

In that case, you don't need to check lws_send_pipe_choked.  You only got the WRITABLE callback because it's not choked, in the middle of a partial send, etc.

Only the lws service thread can call lws_write().

**Comment by awais40** [comment]
Thanks for your response. I was calling the lws_write() outside the callback, so i rewrite the code but the issue remains the same for some of the webpages LWS_CALLBACK_SERVER_WRITEABLE event is coming that their right time but for some of the webpages LWS_CALLBACK_SERVER_WRITEABLE event is coming after a long time, around 40 to 60 seconds.
case LWS_CALLBACK_SERVER_WRITEABLE:
   std::cout<<"LWS_CALLBACK_SERVER_WRITEABLE"<<std::endl;
   lws_write(wsi,(unsigned char*)(msgs +WS_SEND_BUFFER_PRE_PADDING),len ,LWS_WRITE_TEXT );
    lws_callback_on_writable(wsi);
    break;

**Comment by lws-team** [comment]
> for some of the webpages LWS_CALLBACK_SERVER_WRITEABLE event is coming after a long time, around 40 to 60 seconds.

Lws is singlethreaded, so if you do something blocking in the event loop, it will just block all service.  Eg if you put a `sleep(30);` in a callback, lws will halt doing anything else for 30s; it can't start doing anything else until you returned from the callback.  All of lws use of sockets is nonblocking to avoid this, but your code may do something slow.

What event loop is it, eg, default poll() loop?  What value did you put for timeout on the lws_service() call if so?

Who asked for the writable callback?  Lws service thread or another thread?

**Comment by awais40** [comment]
Oh got it, i am doing something else in the other callback event which might making the LWS_CALLBACK_SERVER_WRITEABLE to delay. Thanks.
