### ISSUE TITLE
getaddrinfo_failed forever

### ISSUE THREAD

**Issue by eddiemilan** [warmcat/libwebsockets#1183]
Hello.
I am trying to understand how lws behaves in case of real world unreliable connections.
I have noticed a problem replicated when using the standard test client: 
./test-client "ws://echo.websocket.org" -d15
If upon start the network connection is down I get a loop of  
ERR: getaddrinfo failed
ERR: CLIENT_CONNECTION_ERROR
which is understandable.

Problem is that if connection returns, the callback keeps going forever through the same condition (getaddrinfo failed) and never gets notified of the new connectivity status.

Is it a bug? or am I missing something?

I am using v.2.3.0 on latest version of Fedora.

Thank you for helping

PS: it seems to me that if connection is established and only lost after being estabilished, then in this case the getaddrinfo failed is only a temporary condition lasting till net connectivity returns (which is right)

**Comment by eddiemilan** [comment]
Yes, for the time being I tested only the case of user having network disabled.  However I noticed that problem was and can be reproduced on machine with FC25 (with lws 2.3.0) and it is does not occur on  another having FC 27 lws 2.3.0.  So I assume it has something to do with differing Linux versions ... do you have knowledge of these problems on earlier Linuxes to better define the machine requirements?

Generally speaking, if I do encounter a problem with a connection and I want to reset it completely after being established (it can be also a semantic condition suggesting a reset, having nothing to do with the tcp link itself or the server being up and running), is it a correct strategy to:

- return -1 from the callback when the problem is detected (by some ad hoc built-in logic)
- wait that callback receives reason 4 LWS_CALLBACK_CLOSED and only at this point set connection wsi=NULL (I use the same code logic of your test client example)
- re-establish connection (and a new wsi) in the service loop via lws_client_connect_via_info()

I had some problems in a different set of tests with returning -1 and never getting reason 4 _CLOSED  or 1 _ERROR  and ending up having new connections reopened while the old ones remain forever in ESTABLISHED state (till the server decides to to something about it, of course).

Thank you very much in advance for helping us understand lws and for the time you dedicate to the project.

**Comment by lws-team** [comment]
Well, Fedora 25 is EOL'd https://fedoramagazine.org/fedora-25-end-life/  and isn't receiving security or any other updates any more.  The best plan is update that box to F27.  Fedora is great but it's a bit of an update treadmill, although dnf makes even remote updates pretty painless.

> is it a correct strategy to

The test client has "nailed up" connection retries with retry rate limiting for mirror protocol, I would just follow that approach.  Basically there is a wsi held per client connection, CLOSED or LWS_CALLBACK_CLIENT_CONNECTION_ERROR set the wsi to NULL indicating there is no longer any active connection.  In the poll() service loop, it confirms the rate limiting delay and then creates a new connection on the wsi, which all being well will be non-NULL until something decides to close it.

If you find trouble with the test client and F27, I have both and can check it directly.

**Comment by eddiemilan** [comment]
Thank you.
About that rate limiting (2 seconds) how do you see it in the context of reconnecting? could it be  that under certain network/socket conditions lws_client_connect_via_info() does lead to a valid wsi in the callback and you just want to limit the number of lws_client_(re)connects?
What problems would I hit (if any) with no rate limiting at all?

**Comment by eddiemilan** [comment]
sorry I meant *does NOT* lead to a valid (non NULL) wsi in the callback

**Comment by lws-team** [comment]
The rate limiting is there because without it, if the server name is wrong, or the server refused the connection, you will continuously attempt a new connection every time around the poll() service loop, draining your battery on a mobile device.  In the case the server is up but eg, overcapacity and sending 4xx, your device and any other clients out there will react by bombarding the server with a DDoS again by spamming it with new connections as fast as possible forever.

If it's too cautious for you to wait 2s, you can roll your own that lets it try say three times with no delay then enforces the rate-limiting, or does exponential backoff.  But in a real system, you will need the rate limiting.

**Comment by eddiemilan** [comment]
In case I want to close my connection which is up (no FIN has arrived) but seems to be inactive (for example I calculate an average data rate and its below my threshold) can I just return -1 in any of the callback calls? will this kill/close only the wsi+connection which is being processed (in the callback)? 

Normally in network problematic conditions I notice a sequence of 31 LWS_CALLBACK_GET_THREAD_ID which are not useful as they do not bring a valid wsi (it seems to me).
If I cyclically do lws_callback_on_writable_all_protocol(..) as in your example I get some other reasons 35-34-26-10 (10 is the final  _WRITABLE) although I would prefer to do lws_callback_on_writable() just once and only when it is needed (when data really needs to be transmitted). 
At least I could hook my data rate calculations (and wsi closing) to the processing of one of these reasons ... but am I able to return -1 and close?
Am I on the right track? What do you suggest?
I hope the whole idea is understandable ... 
thank you

**Comment by lws-team** [comment]
You can close a wsi by returning -1 from most callbacks **that were made with that wsi**.  But another way you can do from some other wsi's callback is to set the target wsi's timeout to -1, eg, `lws_set_timeout(wsi, PENDING_TIMEOUT_USER_REASON_BASE, -1);` it will close in a second or so.

**Comment by lws-team** [comment]
I think the original question disappeared and your other questions are answered, so closing.  If there's more please post here I will see it.

**Comment by eddiemilan** [comment]
Thank you very much for the hint.
I made one step ahead using async close   lws_set_timeout(... ... -1) rather than just returning -1 which does not seem to work from callbacks 35 or 36, not sure where is my mistake, maybe they are not in the "most callbacks" group :)
Finally I see my closed connections in TIME_WAIT status and it works well with simulated unreliable network conditions. Grazie.
