### ISSUE TITLE
How to append additional header when using lws_http_redirect

### ISSUE THREAD

**Issue by shenchsh** [warmcat/libwebsockets#1184]
Hi all,

It seems `lws_http_redirect` will only have `location`, `content-type` and `content-length` fields, I am wondering how can I add more header fields? I tried to call `lws_add_http_header_by_name` or `lws_add_http_header_by_token`, but it seems the client cannot receive the additional header. Any idea?

Thanks

**Comment by lws-team** [comment]
There isn't any way.

But, `lws_http_redirect()` is just a helper.  All the apis it uses are public.

```
LWS_VISIBLE int
lws_http_redirect(struct lws *wsi, int code, const unsigned char *loc, int len,
                  unsigned char **p, unsigned char *end)
{
        unsigned char *start = *p;

        if (lws_add_http_header_status(wsi, code, p, end))
                return -1;

        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_LOCATION, loc, len,
                                         p, end))
                return -1;
        /*
         * if we're going with http/1.1 and keepalive, we have to give fake
         * content metadata so the client knows we completed the transaction and
         * it can do the redirect...
         */
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_TYPE,
                                         (unsigned char *)"text/html", 9, p,
                                         end))
                return -1;
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_LENGTH,
                                         (unsigned char *)"0", 1, p, end))
                return -1;

        if (lws_finalize_http_header(wsi, p, end))
                return -1;

        return lws_write(wsi, start, *p - start, LWS_WRITE_HTTP_HEADERS |
                                                 LWS_WRITE_H2_STREAM_END);
}
```

You can just make your own helper that does whatever else you want before the `lws_finalize_http_header()` call.

**Comment by shenchsh** [comment]
Cool. thanks!

**Comment by jhgoebbert** [comment]
Would this also be the way to add a JSON answers to your example minimal-http-server-form-get?

How would you command to change the lws_http_redirect used here
https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/http-server/minimal-http-server-form-get/minimal-http-server-form-get.c#L63
or is there any other preferred way to send JSON back?
