### ISSUE TITLE
Remove counterpart of lws_adopt_descriptor_vhost?

### ISSUE THREAD

**Issue by izaid** [warmcat/libwebsockets#1189]
Hi -- thanks for the fantastic library!

Just a question about adoption of raw sockets. I've been using `lws_adopt_descriptor_vhost` to adopt a file descriptor that is nothing to do with HTTP or WebSockets. Is it possible to not just adopt, but also remove a file descriptor from the event loop at a later point?

**Comment by lws-team** [comment]
Glad the raw stuff is useful for you too.

At the moment, once it's adopted it belongs to lws "until death", the lifecycle of the socket or file descriptor is that it will close if the peer closes their end of the socket connection, or be closed when the lws context is destroyed, for both file and socket descriptors.

What you're talking about is some kind of "unadopt" where the descriptor is left unclosed, but just is no longer any business of lws?  Notice that for socket descriptors, while it belongs to lws it's always open to the peer to decide to close their end of it, and then we will close it and destroy the wsi.

**Comment by izaid** [comment]
Yeah, exactly that. Basically I have pieces of hardware that I want to poll, do stuff with, and then ignore for a while. Then repeat on and off.

It's not a massive deal, as I can work around this in other ways, but I think it would be a nice addition. The raw stuff is definitely useful, although maybe specialized.

**Comment by lws-team** [comment]
You probably don't need 'unadopt' IIUI... the existing Rx flow control api should work to control POLLIN type notification for raw socket + file.  POLLOUT is controlled by asking for a writable callback.

```
/**
 * lws_rx_flow_control() - Enable and disable socket servicing for
 *				received packets.
 *
 * If the output side of a server process becomes choked, this allows flow
 * control for the input side.
 *
 * \param wsi:	Websocket connection instance to get callback for
 * \param enable:	0 = disable read servicing for this connection, 1 = enable
 *
 * If you need more than one additive reason for rxflow control, you can give
 * iLWS_RXFLOW_REASON_APPLIES_ENABLE or _DISABLE together with one or more of
 * b5..b0 set to idicate which bits to enable or disable.  If any bits are
 * enabled, rx on the connection is suppressed.
 *
 * LWS_RXFLOW_REASON_FLAG_PROCESS_NOW  flag may also be given to force any change
 * in rxflowbstatus to benapplied immediately, this should be used when you are
 * changing a wsi flow control state from outside a callback on that wsi.
 */
LWS_VISIBLE LWS_EXTERN int
lws_rx_flow_control(struct lws *wsi, int enable);
```

**Comment by lws-team** [comment]
I take from this silence you were either so stunned by the brilliance of my suggestion you are undergoing therapy to recover, or you decided to use one of the other ways around it you mentioned.

**Comment by izaid** [comment]
Well, I'd prefer a remove API, but yes your suggestion works.

**Comment by lws-team** [comment]
> Well, I'd prefer a remove API

Patches are super welcome here.  In fact as I go around and try to get my patches in elsewhere, I realize they are SUPER welcome here.
