### ISSUE TITLE
using LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT cause a crash ...

### ISSUE THREAD

**Issue by 3DRSenior** [warmcat/libwebsockets#1191]
if you want to use LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT with the last version this make the lib crash. I fixed it with 2 little patch (version 2.4 (or 2.4.1 not sure) : 

**- in ssl.c** 
LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT make wsi->redirect_to_https but also wsi->ssl = NULL.  This last one is used (without test) with SSL_get_SSL_CTX a bit later (line 907). I only checked if wsi->ssl is NULL or not. 

```
vh = context->vhost_list;
while (vh) {
	if (!vh->being_destroyed && wsi->ssl && 
	    vh->ssl_ctx == SSL_get_SSL_CTX(wsi->ssl)) {
		lwsl_info("setting wsi to vh %s\n", vh->name);
		wsi->vhost = vh;
		break;
	}
	vh = vh->vhost_next;
}

```
**- in ssl-http2.c** 
same issue, SSL_get0_alpn_selected is call with wsi->ssl and it crash if it's NULL ! i checked just before this call and returned 0 .. 

```
if(!wsi->ssl)
	return 0;
SSL_get0_alpn_selected(wsi->ssl, &name, &len);
```

this maybe not perfect but it look to work well ...  for now ...

**Comment by lws-team** [comment]
Thanks a lot for the report.... I pushed patches on v2.4-stable and master with your changes.
