### ISSUE TITLE
Issue with sending large text message ( > 200k ) with permessage_deflate (v1.7)

### ISSUE THREAD

**Issue by pvub** [warmcat/libwebsockets#1192]
Hi Andy,

We have been using lws 1.7 for sometime now, with permessage_deflate extension enabled. Recently, we started seeing an issue with sending large text messages (json) over 200k. The clients are receiving a different message than what was passed into lws_write() on the server. 
Is there any known issue with pm_deflate extension with sending such large messages with the extension enabled? 
I don't have any test code right now for this, but wanted to check with you if you are aware of anything related to this, that was already addressed.
I was thinking of increasing the TX buffer size of PMD in order to reduce the number of times we have to go through the event loop to deflate and flush the entire message, but not sure of any drawbacks with that approach.

thank you,
Udai.

**Comment by lws-team** [comment]
1.7 is too old for me to do anything about.

permessage-deflate has been tested against Autobahn for a long time

https://libwebsockets.org/reports/clients/index.html

some of the tests there do permessage-deflate with multi-megabyte payloads with various flags... lws passes all of them.

You can increase the size of the buffers... the current choice of 1K is just a trade-off of performance vs memory, you can choose a different trade-off.
