### ISSUE TITLE
IPV6 not working.

### ISSUE THREAD

**Issue by dev23250240** [warmcat/libwebsockets#1193]
I have build code with -DLWS_IPV6=ON option using make command. Then I used build library and its showing IPV6 is on, still i am unable to make ipv6 connection. Please guide us.

**Comment by lws-team** [comment]
"not working"...

1) I built lws with LWS_IPV6=1

2) I start the test server and look at `netstat -pltn`

```
tcp6       0      0 :::7681                 :::*                    LISTEN      26517/libwebsockets 
```

3) I type "http://localhost:7681" in firefox and I see the test server

... can you specify a bit more clearly what "not working" means and how I should reproduce it?
