### ISSUE TITLE
user pointer in callback function

### ISSUE THREAD

**Issue by sackett** [warmcat/libwebsockets#1196]
Hello! I wonder how to assgn user pointer.

struct test_struct {
char buf[100];
};

test_struct ts;
sprintf_s(ts.buf, "test str");

lws_get_protocol(wsi)->user = &ts;
error C3892: 'lws_get_protocol': you cannot assign to a variable that is const

This way it works:
ctxCreationInfo.user = &ts;

but inside callback function the *user pointer not changed (still NULL).

How it works? Thanks in adavance.

**Comment by lws-team** [comment]
> This way it works:
> ctxCreationInfo.user = &ts;

For client you bind your pointer to it as you found.

> but inside callback function the *user pointer not changed (still NULL).

Which callback exactly?  Some callbacks are not really bound to a wsi.  For real callbacks on a client wsi it should be set.

**Comment by sackett** [comment]
Protocol callback.
By the logic this pointer must be the same for all cient wsi created with this context creation info.
(But now I have only 1 wsi).

**Comment by lws-team** [comment]
>> Which callback exactly?

> Protocol callback.

Yes, so which callback reason?

**Comment by sackett** [comment]
LWS_CALLBACK_CLIENT_RECEIVE for example
and for any other reason the same if I put my debug string above the "switch(reason)".

**Comment by lws-team** [comment]
I think you maybe are looking at the wrong member, you want this in the client info struct

```
	void *userdata;
/**< if non-NULL, use this as wsi user_data instead of malloc it */
```

**Comment by sackett** [comment]
For *userdata it works. Thank you!
I did not tryed it because there is a comment that it deprecated.
And if it deprecated then I suppose it is not safe to use it because of updates (and unexpected behavior in future)?

**Comment by lws-team** [comment]
Where is this comment?  I pasted the only comment on that member.  There's nothing deprecated about it.

**Comment by sackett** [comment]
Took a look and it is OK. I was misguided by MSVC:
http://prntscr.com/in31eq

**Comment by lws-team** [comment]
I see what you mean... MSVC should maybe learn doxygen comment convention if it's going to try to parse out the comments.
