### ISSUE TITLE
Compilation error for test applications in master

### ISSUE THREAD

**Issue by georgekjolly** [warmcat/libwebsockets#1198]
Getting below compilation errors for test applications in master. The issue got resolved when I added
#include <pthread.h> in lib/libwebsockets.h

-- Configuring done
-- Generating done
-- Build files have been written to: /ngs/app/callrecd/src_george/libwebsockets-master/build
-bash-4.2$ make
[ 32%] Built target websockets
[ 33%] Building C object CMakeFiles/test-fuzxy.dir/test-apps/fuzxy.c.o
In file included from /ngs/app/callrecd/src_george/libwebsockets-master/test-apps/fuzxy.c:53:0:
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h: In function ‘lws_pthread_mutex_init’:
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h:232:2: error: implicit declaration of function ‘pthread_mutex_init’ [-Werror=implicit-function-declaration]
  pthread_mutex_init(lock, NULL);
  ^
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h: In function ‘lws_pthread_mutex_destroy’:
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h:238:2: error: implicit declaration of function ‘pthread_mutex_destroy’ [-Werror=implicit-function-declaration]
  pthread_mutex_destroy(lock);
  ^
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h: In function ‘lws_pthread_mutex_lock’:
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h:244:2: error: implicit declaration of function ‘pthread_mutex_lock’ [-Werror=implicit-function-declaration]
  pthread_mutex_lock(lock);
  ^
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h: In function ‘lws_pthread_mutex_unlock’:
/ngs/app/callrecd/src_george/libwebsockets-master/test-apps/../lib/libwebsockets.h:250:2: error: implicit declaration of function ‘pthread_mutex_unlock’ [-Werror=implicit-function-declaration]
  pthread_mutex_unlock(lock);

Thanks
George

**Comment by lws-team** [comment]
Thanks... I don't get this on Fedora that I develop on, I guess the toolchain has it included from glibc headers or so.... but you're right, it should be including it explicitly when needed.  I pushed a patch on master adding the include if LWS_MAX_SMP > 1
