### ISSUE TITLE
Make response status available when WebSocket connection fails

### ISSUE THREAD

**Issue by joelittlejohn** [warmcat/libwebsockets#1200]
Hi. Firstly, thanks for providing this amazing library!

We're using libwebsockets to connect to an API that requires authorization, so to establish a WebSocket connection you have to provide a bearer token. If you don't provide a token (or the token is invalid/expired), the server will return a 401 response status and not upgrade the connection.

We're finding that when our authorization is invalid, we simply get `HS: ACCEPT missing` from libwebsockets rather than any information about _why_ the socket could not be established. This is a problem because if the reason for the failure is 401, then the client _must_ refresh their bearer token before retrying.

There seems to be two issues:

1. libwebsockets looks for `Sec-WebSocket-Accept` in the response first, before it checks the response status. This seems wrong, because you need to check whether the server has actually agreed to accept the connection (by checking for status code 101) before you check for the accept header.

    My suggestion here is to move this check:

https://github.com/warmcat/libwebsockets/blob/3dc71cf05998de2d47728c920e4744704552ae0c/lib/client/client.c#L766

so that it is above this check:

https://github.com/warmcat/libwebsockets/blob/3dc71cf05998de2d47728c920e4744704552ae0c/lib/client/client.c#L760

2. If the status code is not 101, it's important to provide some way for the caller find out what the status code is. If it's a 401, then the authorization is not correct, if it's  a 429, then the client should wait before retrying, if it's a 404 then the client should fix their endpoint address, etc. 

    Either some callback should be available to handle the status code, or this message should include the actual received status code:
https://github.com/warmcat/libwebsockets/blob/3dc71cf05998de2d47728c920e4744704552ae0c/lib/client/client.c#L769

What do you think?

The important case for us is 401, because the client must refresh their token when this happens. If we had an explicit failure `HS: ` message for this then that would be adequate. Obviously it's still important that the status code is validated before `Sec-WebSocket-Accept` is checked.

**Comment by lws-team** [comment]
It sounds pretty reasonable to me.  Can you provide a patch?

**Comment by xajdlg** [comment]
i'm creating connection to server by Authorization Bearer Token,but get error "E: CLIENT_CONNECTION_ERROR: read failed" when dealing callback case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER: lws_add_http_header_by_name(wsi, (const unsigned char*)"Authorization",  (const unsigned char*)"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMem91MzNjblY2a3JaR1R2ckhFckJ5TXRyaVVlc3lJaiIsImlhdCI6MTYxMDA4ODg1MiwiZXhwIjosssYdIdLsKSHWIHFhs.B6Gu_xroQkAfkmlGrgNnM-QkHc_YUZTZWIrOSJkE3Rw", 190, p, end)
