### ISSUE TITLE
Build a static ".a" linked library.

### ISSUE THREAD

**Issue by nospamcalfee** [warmcat/libwebsockets#1203]
How do I configure the cmake stuff to build a static library?

If I cannot how do I configure it so gdb can step into the libwebsockets code?

**Comment by lws-team** [comment]
For Linux anyway, just build it with defaults.  `./lib/libwebsockets.a` is produced in your build dir.

If you want to build with debug info, then `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` and remake it.
