### ISSUE TITLE
libwebsockets for sending server side events 

### ISSUE THREAD

**Issue by vaghelan** [warmcat/libwebsockets#1205]
Hi,
I need to integrate libwebsockets for my application where it detects some IoT event and then it needs to push that event to client. Client just makes connection with server for subscription of notifications once and server needs to push event when it occurs. Client does not poll for event. If it needs to then it defeats the purpose of websocket. Since libwebsocket lib is single threaded and it has its own event loop and callback mechanism,  I was wondering how do I push event from a separate application thread. May be I need to have event loop as part of my app thread.

Here are my thoughts : 

If there are events then call - lws_callback_on_writable(wsi) so that callback is called with
LWS_CALLBACK_SERVER_WRITEABLE reason code in callback. There I can push event. If more events left then I can keep interest ON - lws_callback_on_writable(wsi), otherwise no interest.

Would this work ?

----------MAIN EVENT LOOP CODE Integrated with app ----------
while (n >= 0 && !interrupted)
       // call app specific event generation code and get events in Q
      // if events need to push then  enable write interest - lws_callback_on_writable(wsi);
          n = lws_service(context, 1000);

----------EVENT LOOP CODE ----------

Thanks
Nilesh.

**Comment by vaghelan** [comment]
May be in main event loop - I can call my event generation code to get events and Q them.

If there are events then call - lws_callback_on_writable(wsi) so that callback is called with 
LWS_CALLBACK_SERVER_WRITEABLE reason code in callback. There I can push event. If more events left I can keep - lws_callback_on_writable(wsi) 

Would this work ?

----------EVENT LOOP CODE ----------
while (n >= 0 && !interrupted)
                 // call app specific event generation code and get events in Q
                //  if events need to push
                         lws_callback_on_writable(wsi);
		    n = lws_service(context, 1000);

-----------

**Comment by lws-team** [comment]
There's info about it in READMEs/README.coding.md .

However to make it easier to get started with it, I have added a minimal example on latest master

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/minimal-ws-server-threads

**Comment by vaghelan** [comment]
Hi,

Thanks for guidance. What if I want to post message also through Websocket. In other words,  I have three components. One is publisher, broker and subscribers. 

if my code needs to act as broker then from producer I can make Websocket connection and post message and then broker can stream to subscribers. Like Kafka but without storing events...

In LWS event loop how I can differentiate between publisher and susbcriber clients ?

Any hints ?

**Comment by lws-team** [comment]
> What if I want to post message also through Websocket.

That is exactly what the example app shows.

> how I can differentiate between publisher and susbcriber clients

In lws many different things can coexist by either using one protocol callback and set information at connection time by the URL part (ie, wss://myserver/arguments using one ws protocol), or connect to different protocols / callbacks in the first place depending on the role.

If all sides are using ws, that is simple to do using the ws subprotocol name to match to a particular protocol / callback, but it's also possible to bind either raw data or http connections to a specific protocol / callback.

If that isn't what you are talking about maybe you can explain more clearly what is needed that isn't in the existing example.

**Comment by vaghelan** [comment]
Yes I think I got it. We will have to have separate sub-protocol and
callbacks for each. I think that will make things easier.

I intend to use ws all sides.


My architecture has three separate processes :

1. Client posting event - should act like WS client
2. Broker or proxy - to receive event from client and dispatching to
multiple subscribers
3. Subscriber - Right now just using browser and Java script

Looking for example for (1) Pure WS client. Any example without Event loop
so that i can directly post event to Broker from client ?

Hope I am clear !!


Thanks

**Comment by lws-team** [comment]
Notice that client-related callbacks and server-related callback reasons do not overlap (the same is also true of RAW socket callbacks).  So it is possible to do it in one protocol callback, that handles client connections and server connections (and RAW connections) differently.

Lws supports mixing as many client and server connections how you like in the one event loop.  FWIW what you're describing does not need threads at all actually.  From the "proxy" perspective, if there is anything he needs to do, he can learn about it by lws callbacks and asking for callback on writable... he is entirely concerned with reacting to network events.  So he can be happy just in the lws event loop thread context.

https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/minimal-http-client/minimal-http-client.c shows how to make client https connections... ws connections are almost the same, there is a separate example now at https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/minimal-ws-client

I'll look at making an example integrating the serving and client stuff in one protocol as well.

**Comment by lws-team** [comment]
You can find a ws[s] proxying example here

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/minimal-ws-proxy

**Comment by vaghelan** [comment]
This is really great!! This will be useful.

I just realized that broker needs to act as server on publisher and subscriber side unlike proxy.

As Publisher connects to broker and posts event.
Subscriber subscribes so it also needs to connect to the broker and get event notification.

So I will need to implement publisher callback and subscriber callback with server call backs.

Nilesh.

**Comment by lws-team** [comment]
So you mean like

```
[publisher  ws client] <--> [ws server   broker   ws server] <---> [ ws client subscriber ]
```

it can be done even simpler with one server and one protocol... when ws client establishes a ws connection to the server, it passes an HTTP URL, like myserver.com/thisurl.  That's available at the ESTABLISHED callback in WSI_TOKEN_GET_URI.  You can then mark the pss as being a connection from a publisher or a subscriber based on the url the ws used to connect, and enforce different capabilities on that connection (ie, add events or only consume them).

You probably need to think about authentication.  But it can be done in the ws protocol if you control that.

**Comment by vaghelan** [comment]
Can you point me to some doc explaining concept of vhost ?

Is it necessary to have atleast one vhost ? Can we just not have "per
session user data"  and store them in Q ?

Nilesh.

**Comment by lws-team** [comment]
Eg, https://libwebsockets.org and http://warmcat.com are two vhosts (virtual hosts) running from one lws server.  What they serve and what protocols they support are different depending on which vhost you arrived by.  Lws uses SNI sent over tls to figure out which vhost to bind your connection to.  Or you can differentiate them by which port they listen on.

You can think of it that you might want to provide brokering services for other companies using your broker.  With vhosts, you can reuse the same lws protocol multiple times on the one server each in its own little world and accessible by its own https://vhostname

By default creating the context creates a single default vhost (named "default") at the same time.

You can do it with just the pss.  But you are much better off thinking of the vhd as being where you put "filescope variables".  Then you can painlessly extend the protocol to work on different vhosts simultaneously.

**Comment by lws-team** [comment]
There's an example here now

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/server/minimal-ws-broker

**Comment by vaghelan** [comment]
Thank Andy. This is really great with examples.

In Client example, what we have is receive client. If you can add client
which connects to server and act like publisher then we would complete
examples.

As normally one would have some iOT event created by C++module.

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/client

Good for subscriber. But one for publisher would make it complete.

But once again this is very good. Thanks for your support.

Thanks
Nilesh

**Comment by vaghelan** [comment]
Also in http client - POST example would be good. If publisher is http
client

This example is GET.
https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/client/minimal-http-client/minimal-http-client.c

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-client/minimal-ws-client-tx

shows how to have a rate-limited "nailed up" client connection to the broker sample, and as a "publisher" send it messages from other threads via a local ringbuffer.

**Comment by lws-team** [comment]
You can already see how to handle POST in this plugin

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c

There isn't just one "POST" though, there's multiple ways to encode the content.  The plugin above shows how to handle, eg, file transfer using multipart.  If you don't care about that you can just remove the code related to spa and get the raw POSTed data.

**Comment by vaghelan** [comment]
Hi,

I have integrated libwebsockets in my app. It worked great for while but
after running for some time lws_service () call returns with return code 1.

Do we know why lws_service() returns 1 ?

How should I handle that code ?

My app runs in one thread and it then posts message to ring Q. LWS event
lop thread reads it and sends to the client.

Thanks
Nilesh.

**Comment by lws-team** [comment]
Increase the logging... build lws with -DCMAKE_BUILD_TYPE=DEBUG, and edit the lws_set_log_level() to have more kinds of logging like `LLL_INFO | LLL_DEBUG`.  If the service call fails out rather than just a connection, it should be something major.

**Comment by vaghelan** [comment]
For some reason when I removed some opencv code it stabilized.

One more feature I need to add : Every time new client joins my App wants
to be notified that it needs to re-eval the events and send to all.

per_vhost_data__minimal has pss_list - I can count number of nodes but I
wanted do this without race condition. As my app is in a different thread
and if it is in the code where it is counting and if there are changes in
Q, it could lead to race condition.

So I want to raise event every time new client joins or existing client
leaves....

Any suggestions ?

**Comment by lws-team** [comment]
> For some reason when I removed some opencv code it stabilized.

Well... I can't help you with that.  If there are any problems that exist in the minimal examples themselves I would be anxious to fix them.

There are a couple of points mixed together about pss_list.

1) If you want to directly access pss_list from another thread, you must add a mutex and both your code and the callback so  _ESTABLISHED and _CLOSED must take the mutex before modifying the pss_list.  This serializes access so no thread changes the pss list while another was walking it.

Other places in the callback can access pss_list without mutex protection, because they also only read it, like your thread, and the lws service thread can only be doing one thing at a time.  But your thread must have the mutex protection.

2) IIUI you only want to "raise event" and "send to all" when the lws service thread is in the _ESTABLISHED (after adding the new pss) or _CLOSED (after removing the closing pss) callback.  It depends on what processing you are doing, but 

 - if it is short duration, you can take the approach to make the lws service thread wait for it and then do the callback_on_writable for everyone in the pss list from the lws service thread.  You put it that it must be done by inter-thread signalling, but probably all you need to do is acquire the locking that your thread would, and do it directly in the lws service thread in the callback.

 - If the processing takes a long time, then using a separate thread for it makes sense.  In that case you would trigger it in _ESTABLISHED and _CLOSED, and your thread would call lws_cancel_service(context); when it had finished.  That causes a LWS_CALLBACK_EVENT_WAIT_CANCELLED to happen in your callback in the lws service thread context where you can walk the pss list and ask for callback on writable.

**Comment by vaghelan** [comment]
Hi Andy,

One question. In case of ring style Q, if one of the clients does not suck
data or very slow...then it starve others and eventually no messages will
be sent.

If I all I care for is real-time message and not worry about sending old
messages on Q, I think I should point all tail to newest message and free
up old slots ?

In fact I think why should I even maintain Q if I care for sending fresh
message ?

Do you agree ?

**Comment by The-Robin-Hood** [comment]
Hi @lws-team, How can i gracefully close a server sent event connection. In your example its an infinty data. Could you clarify. ?

**Comment by lws-team** [comment]
You can generally hang up a connection (which will shutdown and close any related tls) by using `lws_wsi_close(wsi, LWS_TO_KILL_ASYNC)`.  It will close it shortly after you returned to the event loop, you will get CLOSE callback during that etc.

**Comment by lws-team** [comment]
What do you think "support[ing] CORS" would look like in this context?

**Comment by The-Robin-Hood** [comment]
Do we have  examples to handle CORS ?
