### ISSUE TITLE
libwebsockets and docker

### ISSUE THREAD

**Issue by fmalassagne** [warmcat/libwebsockets#1207]
Hello
I have a problem with big memory usage by binaries using libwebsockets in docker containers.
I don't success to reproduce this phenomena with any binaries without link to lws, and it's why I take my chance here...

How to reproduce :
- extract libwebsockets tarball, just do "cmake .." and "make"
- launch "./libwebsockets-test-server &"
- and watch memory consumption with "ps -p $(pidof libwebsockets-test-server) -o rss,vsz" (or "top")
```
  RSS    VSZ
 2720  22624
```
- now launch "docker run --rm -v $PWD:/lws -i -t ubuntu:16.04 /bin/bash"
- inside docker container now, launch "./libwebsockets-test-server &" (need "apt-get install libssl1.0.0" before)
- watch memory consumption in the same way (on host or on docker)
```
  RSS    VSZ
19156  37184
```

It's the same with all binaries linking lws (libwebsockets-test-* lwsws, and of course mine).
But when trying with any other binaries, I observe a quite same order value ...

I reproduce it in all cases : docker 1.7 and 1.11, libwebsockets 2.3 and 2.4.2, ubuntu or gentoo OS, Ubuntu or Alpine container ...

Due to this, I cannot put as many binaries/containers as I want on my servers, the memory is quickly full.

Thanks a lot

**Comment by lws-team** [comment]
Hmm nothing in lws is using this memory I think we find.  Because lws also works on small targets like ESP32, that only have 320KB RAM total.  Yet I can run lws test server on that with multiple clients.

Can you check master lws?  I will also try master later, but on Fedora not on docker.

**Comment by lws-team** [comment]
Hm right now Fedora's central update thing is down, I can't install docker to try it.

But what you're saying doesn't actually make sense... you can see there is no problem on lws outside docker.  The problem only occurs inside your Docker environment.  If lws is the same, I don't see how we can blame lws.  It has no idea you are in a docker environment itself.

While I wait for Fedora updates to work again, can you run ldd on the test server and the libwebsockets so on both your host and inside the docker env, and paste the results?  Also ls -l on those two things in the two environments.

**Comment by lws-team** [comment]
Mmm Fedora's update stuff is working again and I installed docker.  But it's 21:30 here so I won't look at it tonight.

What I would do is align your tests, presumably in the first case, where you build it yourself with default options, there's no issue with the memory consumption, right?

What happens if you do exactly the same inside the docker image, build it from git with default cmake options?

**Comment by fmalassagne** [comment]
I'll try to answer all your questions :

I check, and same problem on master branch

Here the result of "ldd libwebsockets-test-server" and "ls -l" :
- on host
```
	linux-vdso.so.1 (0x00007ffcce510000)
	libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007f6cb22d9000)
	libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007f6cb1e9a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6cb1b9f000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f6cb1999000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6cb177d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6cb13e2000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6cb11de000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f6cb0fc8000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f6cb0dc3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6cb254f000)

lrwxrwxrwx 1 root root      10 25 janv.  2016 /lib64/ld-linux-x86-64.so.2 -> ld-2.21.so
lrwxrwxrwx 1 root root      16 25 janv.  2016 /lib64/libattr.so.1 -> libattr.so.1.1.0
lrwxrwxrwx 1 root root      14 25 janv.  2016 /lib64/libcap.so.2 -> libcap.so.2.24
lrwxrwxrwx 1 root root      12 25 janv.  2016 /lib64/libc.so.6 -> libc-2.21.so
lrwxrwxrwx 1 root root      13 25 janv.  2016 /lib64/libdl.so.2 -> libdl-2.21.so
lrwxrwxrwx 1 root root      12 25 janv.  2016 /lib64/libm.so.6 -> libm-2.21.so
lrwxrwxrwx 1 root root      18 25 janv.  2016 /lib64/libpthread.so.0 -> libpthread-2.21.so
lrwxrwxrwx 1 root root      13  7 mars   2017 /lib64/libz.so.1 -> libz.so.1.2.8
-r-xr-xr-x 1 root root 2339272 18 mai    2017 /usr/lib64/libcrypto.so.1.0.0
-r-xr-xr-x 1 root root  483144 18 mai    2017 /usr/lib64/libssl.so.1.0.0
```
- on docker
```
	linux-vdso.so.1 =>  (0x00007ffc7f1cc000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f959fded000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f959f9a9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f959f6a0000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f959f499000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f959f27c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f959eeb2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f959ecad000)
	/lib64/ld-linux-x86-64.so.2 (0x000055dc02f4e000)

lrwxrwxrwx 1 root root      12 Jan 15 02:51 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.23.so
lrwxrwxrwx 1 root root      14 Oct 23  2015 /lib/x86_64-linux-gnu/libcap.so.2 -> libcap.so.2.24
-rw-r--r-- 1 root root 2361856 Dec  7 21:09 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
lrwxrwxrwx 1 root root      13 Jan 15 02:51 /lib/x86_64-linux-gnu/libdl.so.2 -> libdl-2.23.so
lrwxrwxrwx 1 root root      12 Jan 15 02:51 /lib/x86_64-linux-gnu/libm.so.6 -> libm-2.23.so
lrwxrwxrwx 1 root root      18 Jan 15 02:51 /lib/x86_64-linux-gnu/libpthread.so.0 -> libpthread-2.23.so
-rw-r--r-- 1 root root  428384 Dec  7 21:09 /lib/x86_64-linux-gnu/libssl.so.1.0.0
```

On host, 2.6MB of memory used by libwebsockets-test-server doesn't seem to me abnormal.

There is the same problem even if the binary is compiled on docker.

**Comment by lws-team** [comment]
Okay I sat down and reproduced it.

But the cause is simple and under your control... lws prepares fast maps between fd handles and logical structures for every possible fd the process may be using.  By default on Fedora and "stock ubuntu" this is 1024 per process... you can check it with `ulimit -n`.

But on this docker image, the default ulimit -n is 1024 times larger...

```
root@857877ff248e:/libwebsockets/build# ulimit -n
1048576
```

That's fine for lws, but it costs some memory for the maps.  If you reduce the ulimit before starting the server to the normal distro default of 1024, with `ulimit -n 1024`, the "problem" is gone.

You can also restrict the number of fds lws will set up for dynamically at runtime, using the context creation info struct

```
	unsigned int fd_limit_per_thread;
	/**< CONTEXT: nonzero means restrict each service thread to this
	 * many fds, 0 means the default which is divide the process fd
	 * limit by the number of threads. */
```

if this is set less than the ulimit -n, lws ignores the balance of fds it could open and operates as if the ulimit was the lower number.

**Comment by fmalassagne** [comment]
Arrrrgh, how I could miss it
Thanks
