### ISSUE TITLE
Send an int array  

### ISSUE THREAD

**Issue by newza-fullmetal** [warmcat/libwebsockets#1209]
Hello everyone and lws-team 

I am stuck with a problem (I think easy to solve ) and I am looking for any advice to understand more easily. 
here is my problem : 
I need to send data from an IOT object running a libwebsosckets server and get it back on a browser on the client side, so javascript.
This data is an array of int_16.
I know I can do it in two different ways, at least. 

- LWS_WRITE_TXT and turn my array of int in a JSON formated string. That I get back with JSON.parse in the client side
- LWS_WRITE_BINARY and transform my array of int in Byte. I get it back with arraybuffer on the client side.

I think the second option is better because I do care of the size of the data, (I will send a lot of data per second) 

here is an exemple : 
```
void send_message(struct lws *wsi){

	        int msg_t[10] = {1, 2, 3, 4, 5 ,6 ,7 ,8 ,9 , 10};

		unsigned char buf[LWS_PRE + 512];
		unsigned char *p = &buf[LWS_PRE];
		
		int n = 0;
		for (int i =0; i < 10 ; i++){
                        //what to do here to put in JSON or Byte ?
			n = n+sprintf((char *)&p[n], "%i", msg_t[i]);
		}
		
		
		int ret = lws_write(wsi, p, n, LWS_WRITE_BINARY ) ;

}
```
Thank you for your help

EDIT1 : 

I got it for the JSON version here is my exemple : 
```
void send_message(struct lws *wsi){
	
                int msg_t[10] = {1, 2, 3, 4, 5 ,6 ,7 ,8 ,9 , 10};
		unsigned char buf[LWS_PRE + 512];
		unsigned char *p = &buf[LWS_PRE];

		int n = 0;
		n = n+sprintf((char *)&p[n], "{"); //start the JSON
		n = n+sprintf((char *)&p[n], "\"data\":["); //name the data and start an array
		for (int i =0; i < 9 ; i++){

			n = n+sprintf((char *)&p[n], "%i,", msg_t[i]); //add value except the last
		}
		n = n+sprintf((char *)&p[n], "%i", msg_t[9]); //last value
		n = n+sprintf((char *)&p[n], "]}"); //close the array and the JSON

		int ret = lws_write(wsi, p, n, LWS_WRITE_TEXT ) ;

}
```

**Comment by lws-team** [comment]
If you care about efficiency, using binary ws mode is good.  But instead of iterate over the data, you can just memcpy it (the copy is necessary because ws write XORs the data with a mask in-place)

```
int send_message(struct lws *wsi, uint16_t *words, int count_words)
{
    unsigned char buf[LWS_PRE + 512], *p = &buf[LWS_PRE];
    int len = count_words * sizeof(*words);

    if (len >= sizeof(buf) - LWS_PRE)
        return 1;

    memcpy(p, words, len);
    return lws_write(wsi, p, len, LWS_WRITE_BINARY) != len;
} 
```

There are no alignment problems because LWS_PRE is currently 16.

You have to handle it in js via a 16-bit arraybuffer.

**Comment by newza-fullmetal** [comment]
Thank you, it is working perfectly, !

Have a nice day !
