### ISSUE TITLE
Stuck. Can't build examples

### ISSUE THREAD

**Issue by psdn** [warmcat/libwebsockets#1210]
I'm trying my best.

/libwebsockets/minimal-examples/http-server/minimal-http-server
$ cmake . && make
$ ./lws-minimal-http-client
./lws-minimal-http-server: error while loading shared libraries: libwebsockets.so.12: cannot open shared object file: No such file or directory

I was able to install and can run the examples in the bin directory.

Thank you.

**Comment by psdn** [comment]
Nevermind. ldconfig.

**Comment by lws-team** [comment]
Thanks, I added a mention of ldconfig in the README for the minimal-examples dir, I'll push it later,
