### ISSUE TITLE
vhost quick start

### ISSUE THREAD

**Issue by psdn** [warmcat/libwebsockets#1211]
I really loath asking this, because it's probably super simple thing I missed, but I have like 6 hours into trying to figure this out:

To get started quickly, an example config reproducing the old test server on port 7681, non-SSL is provided. To set it up

	# mkdir -p /etc/lwsws/conf.d /var/log/lwsws
	# cp ./lwsws/etc-lwsws-conf-EXAMPLE /etc/lwsws/conf
	# cp ./lwsws/etc-lwsws-conf.d-localhost-EXAMPLE /etc/lwsws/conf.d/test-server
	# sudo lwsws

So I do all of that, and get:

Root process is 28587
lwsws[28588]: lwsws libwebsockets web server - license CC0 + LGPL2.1
lwsws[28588]: (C) Copyright 2010-2016 Andy Green <andy@warmcat.com>
lwsws[28588]: Using config dir: "/etc/lwsws"
lwsws[28588]:   Plugins:
lwsws[28588]:   Scanning /usr/local/share/libwebsockets-test-server/plugins/
lwsws[28588]:    libprotocol_client_loopback_test.so
lwsws[28588]:    libprotocol_dumb_increment.so
lwsws[28588]:    libprotocol_lws_meta.so
lwsws[28588]:    libprotocol_lws_mirror.so
lwsws[28588]:    libprotocol_lws_raw_test.so
lwsws[28588]:    libprotocol_lws_server_status.so
lwsws[28588]:    libprotocol_lws_ssh_base.so
lwsws[28588]:    libprotocol_lws_sshd_demo.so
lwsws[28588]:    libprotocol_lws_status.so
lwsws[28588]:    libprotocol_lws_table_dirlisting.so
lwsws[28588]:    libprotocol_post_demo.so
lwsws[28588]:  Using foreign event loop...
lwsws[28588]: Creating Vhost 'localhost' port 7681, 7 protocols, IPv6 off
lwsws[28588]: getpwuid: unable to find uid 48

In the conf file, I comment out the uid 48 and sudo lwsws again. I get the same message, but no uid error. Either way, I browse to my IP:7681 and get connection refused. But if I run libwebsockets-test-server, browser connects just fine. When I run lwsws it shows the plugin directory scan, config directory, some good info, which leads me to believe it is picking up the /etc/lwsws/conf.d/test-server file.  libwebsockets-test-server doesn't really say anything when I run it, but it's obvious it's picking up the /etc/lwsws/conf.d/test-server file. 

My intention isn't to use libwebsockets to serve http necessarily, but I want to understand completely and it seems like setting out to make a plugin for the standard install would be a good first move.

Do I need to make vhost file? If so, how would I tell lwsws to use it, or how do I name it? Do I need to a FQDN to use a vhost file instead of just browsing to it by ip address? It just seems like the instructions above should work out of the box. I get nothing in the in the /var/log/lwsws/test-access-log. Just nothing.

**Comment by lws-team** [comment]
Any problem that can be reproduced with the lws samples and apps (at least on a platform I have) is my problem , so don't worry about asking.

I'm AFK for the next hour or two... but... browsing to http://127.0.0.1:7681 does what?  What does `sudo netstat -pltn` on the serving machine say?  When you say " my IP" that's an external IP?  If you are coming from a different machine, does the server have port 7681 open in its local firewall?

**Comment by psdn** [comment]
I have no ports blocked on the server or my desktop which I am browsing from. I'm running libwebsockerts from a digital ocean vps. Debian 9

netstat -pltn with sudo lwsws:
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      695/sshd
tcp        0      0 127.0.0.1:7681          0.0.0.0:*               LISTEN      29100/lwsws
tcp6       0      0 :::22                   :::*                    LISTEN      695/sshd

netstat -pltn with libwebsockets-test-server:
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      695/sshd
tcp        0      0 0.0.0.0:7681            0.0.0.0:*               LISTEN      29129/libwebsockets
tcp6       0      0 :::22                   :::*                    LISTEN      695/sshd

libwebsockets is running on a remote server, so:

curl -I  http://127.0.0.1:7681 running sudo lwsws:
HTTP/1.1 404 Not Found
server: lwsws
content-type: text/html
content-length: 38

curl -I  http://127.0.0.1:7681 running libwebsockets-test-server:
HTTP/1.1 200 OK
content-type: text/html
content-length: 66872
cache-control: no-store
connection: keep-alive
set-cookie: test=LWS_1521352698_292623_COOKIE;Max-Age=360000

If just do curl http://127.0.0.1:7681, it returns the test.html in both instances.

Since the curl response for lwsws was 404, I thought I'd be slick and do this in test-server:
replace:
"origin": "file://_lws_ddir_/libwebsockets-test-server",
with
"origin": "file://usr/local/share/libwebsockets-test-server",

But no difference.

**Comment by lws-team** [comment]
Clearly it's listening just fine, both from the netstat and 

> HTTP/1.1 404 Not Found

How about make sure lws is built with -DCMAKE_BUILD_TYPE=DEBUG and run lwsws with -d31 for more logging...does it say what happened on the 404?

**Comment by psdn** [comment]
If I hit it with the browser, there isn't even a blip. With curl -I http://127.0.0.1:7681 I get:

lwsws[30455]: accepted new conn port 34818 on fd=17
lwsws[30455]: lws_get_or_create_peer: creating new peer
lwsws[30455]: _realloc: size 88: peer
lwsws[30455]: _realloc: size 576: new server wsi
lwsws[30455]: new wsi 0x5567f561db80 joining vhost local, tsi 0
lwsws[30455]: lws_adopt_descriptor_vhost: new wsi 0x5567f561db80, sockfd 17
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 20 secs
lwsws[30455]: __insert_wsi_socket_into_fds: 0x5567f561db80: tsi=0, sock=17, pos-in-fds=2
lwsws[30455]: lws_header_table_attach: wsi 0x5567f561db80: ah (nil) (tsi 0, count = 0) in
lwsws[30455]: _realloc: size 3000: ah struct
lwsws[30455]: _realloc: size 4096: ah data
lwsws[30455]: _lws_create_ah: created ah 0x5567f561ddd0 (size 4096): pool length 1
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f561db80: fd 17 events 1 -> 1
lwsws[30455]: lws_header_table_attach: did attach wsi 0x5567f561db80: ah 0x5567f561ddd0: count 1 (on exit)
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 10 secs
lwsws[30455]: Attached ah immediately
lwsws[30455]: lws_plat_pipe_signal: fd 16 1
lwsws[30455]: LWS_CALLBACK_EVENT_WAIT_CANCELLED
lwsws[30455]: vhost match to local based on port 7681
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 0 secs
lwsws[30455]: No upgrade
lwsws[30455]: lws_union_transition: 0x5567f561db80: mode 1
lwsws[30455]: lws_handshake_server: wsi 0x5567f561db80: ah 0x5567f561ddd0
lwsws[30455]: Method: 'HEAD' (7), request for '/'
lwsws[30455]: lws_ensure_user_space: 0x5567f561db80 protocol pss 0, user_space=(nil)
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 20 secs
lwsws[30455]: _realloc: size 256: access log
lwsws[30455]: _realloc: size 13: access log
lwsws[30455]: no hit
lwsws[30455]: lws_same_vh_protocol_remove: removing same prot wsi 0x5567f561db80
lwsws[30455]: lws_ensure_user_space: 0x5567f561db80 protocol pss 0, user_space=(nil)
lwsws[30455]: lws_http_transaction_completed: wsi 0x5567f561db80
lwsws[30455]: ah attached, pos 0, len 79
lwsws[30455]: lws_same_vh_protocol_remove: removing same prot wsi 0x5567f561db80
lwsws[30455]: have prev 0x5567f56042e0, setting him to our next (nil)
lwsws[30455]: lws_ensure_user_space: 0x5567f561db80 protocol pss 0, user_space=(nil)
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 5 secs
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 10 secs
lwsws[30455]: __lws_set_timeout: 0x5567f561db80: 5 secs
lwsws[30455]: lws_http_transaction_completed: 0x5567f561db80: keep-alive await new transaction
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f561db80: fd 17 events 1 -> 5
lwsws[30455]: wsi->http.rx_content_length 0 0 0
lwsws[30455]: lws_server_socket_service: wsi 0x5567f561db80: ah read rxpos 79, rxlen 79
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f561db80: fd 17 events 5 -> 1
lwsws[30455]: lws_server_socket_service: LWSS_HTTP_DEFERRING_ACTION now writable
lwsws[30455]:      existing ah rxpos 79 / rxlen 79
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f561db80: fd 17 events 1 -> 1
lwsws[30455]: lws_server_socket_service: read 0 len a
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f561db80: fd 17 events 1 -> 0
lwsws[30455]: __lws_close_free_wsi: 0x5567f561db80: caller: server socket svc fail
lwsws[30455]: __lws_close_free_wsi: shutdown conn: 0x5567f561db80 (sock 17, state 64)
lwsws[30455]: __lws_close_free_wsi: real just_kill_connection: 0x5567f561db80 (sockfd 17)
lwsws[30455]: lws_same_vh_protocol_remove: removing same prot wsi 0x5567f561db80
lwsws[30455]: have prev 0x5567f56042e0, setting him to our next (nil)
lwsws[30455]: __remove_wsi_socket_from_fds: wsi=0x5567f561db80, sock=17, fds pos=2, end guy pos=3, endfd=0
lwsws[30455]: _lws_change_pollfd: wsi 0x5567f5614c80: fd 23 events 1 -> 1
lwsws[30455]: not calling back closed mode=0 state=64
lwsws[30455]: __lws_close_free_wsi: lws_libuv_closehandle: wsi 0x5567f561db80
lwsws[30455]: ah det due to close
lwsws[30455]: __lws_header_table_detach: wsi 0x5567f561db80: ah 0x5567f561ddd0 (tsi=0, count = 1)
lwsws[30455]: __lws_header_table_detach: nobody usable waiting
lwsws[30455]: _lws_destroy_ah: freed ah 0x5567f561ddd0 : pool length 0
lwsws[30455]: __lws_header_table_detach: wsi 0x5567f561db80: ah 0x5567f561ddd0 (tsi=0, count = 0)
lwsws[30455]: __lws_free_wsi: 0x5567f561db80, remaining wsi 2

**Comment by psdn** [comment]
I suppose you'd want the startup info as well:

Root process is 30587
lwsws[30588]: lwsws libwebsockets web server - license CC0 + LGPL2.1
lwsws[30588]: (C) Copyright 2010-2016 Andy Green <andy@warmcat.com>
lwsws[30588]: Using config dir: "/etc/lwsws"
lwsws[30588]: lwsws_get_config: /etc/lwsws/conf
lwsws[30588]: lwsws_get_config: /etc/lwsws/conf.d/test-server
lwsws[30588]: Initial logging level 31
lwsws[30588]: Libwebsockets version: 2.4.0 v2.0.0-805-g723546b0
lwsws[30588]: IPV6 not compiled in
lwsws[30588]: libev support not compiled in
lwsws[30588]: libuv support compiled in and enabled
lwsws[30588]:  LWS_DEF_HEADER_LEN    : 4096
lwsws[30588]:  LWS_MAX_PROTOCOLS     : 5
lwsws[30588]:  LWS_MAX_SMP           : 1
lwsws[30588]:  sizeof (*info)        : 456
lwsws[30588]:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
lwsws[30588]:  HTTP2 support         : not configured
lwsws[30588]: _realloc: size 3240: context
lwsws[30588]:  default timeout (secs): 20
lwsws[30588]: _realloc: size 4096: pt_serv_buf
lwsws[30588]:  Threads: 1 each 1024 fds
lwsws[30588]: _realloc: size 512: peer limits hash table
lwsws[30588]:  mem: context:          7336 B (3240 ctx + (1 thr x 4096))
lwsws[30588]:  mem: http hdr rsvd:   7266304 B (1 thr x (4096 + 3000) x 1024))
lwsws[30588]: _realloc: size 8192: fds table
lwsws[30588]:  mem: pollfd map:       8192
lwsws[30588]: _realloc: size 8192: lws_lookup
lwsws[30588]:  mem: platform fd map:  8192 bytes
lwsws[30588]:   Plugins:
lwsws[30588]:   Scanning /usr/local/share/libwebsockets-test-server/plugins/
lwsws[30588]:    libprotocol_client_loopback_test.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_dumb_increment.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_meta.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_mirror.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_raw_test.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_server_status.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_ssh_base.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_sshd_demo.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_status.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_lws_table_dirlisting.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:    libprotocol_post_demo.so
lwsws[30588]: _realloc: size 128: plugin
lwsws[30588]:  Compiled with OpenSSL support
lwsws[30588]:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
lwsws[30588]:  mem: per-conn:          576 bytes + protocol rx buf
lwsws[30588]:  canonical_hostname = debian-9
lwsws[30588]:  Using foreign event loop...
lwsws[30588]: _realloc: size 576: event pipe wsi
lwsws[30588]: event pipe fd 15
lwsws[30588]: __insert_wsi_socket_into_fds: 0x561443d315c0: tsi=0, sock=15, pos-in-fds=0
lwsws[30588]: _lws_change_pollfd: wsi 0x561443d315c0: fd 15 events 1 -> 1
lwsws[30588]: lwsws_get_config: /etc/lwsws/conf
lwsws[30588]: lwsws_get_config: /etc/lwsws/conf.d/test-server
lwsws[30588]: adding mount /
lwsws[30588]: ----file://usr/local/share/libwebsockets-test-server
lwsws[30588]: adding mount /server-status
lwsws[30588]: ----file:///usr/local/share/libwebsockets-test-server/server-status
lwsws[30588]: adding mount /testcgi
lwsws[30588]: ----cgi:///usr/local/share/libwebsockets-test-server/lws-cgi-test.sh
lwsws[30588]: adding mount /formtest
lwsws[30588]: ----callback://protocol-post-demo
lwsws[30588]:   adding protocol lws-meta
lwsws[30588]:   adding protocol dumb-increment-protocol
lwsws[30588]:   adding protocol lws-mirror-protocol
lwsws[30588]:   adding protocol lws-status
lwsws[30588]:   adding protocol protocol-post-demo
lwsws[30588]:   adding protocol lws-server-status
lwsws[30588]: _realloc: size 568: create vhost
lwsws[30588]: _realloc: size 784: vhost-specific plugin table
lwsws[30588]: _realloc: size 56: same vh list
lwsws[30588]: Creating Vhost 'local' port 7681, 7 protocols, IPv6 off
lwsws[30588]:    mounting file://usr/local/share/libwebsockets-test-server to /
lwsws[30588]:    mounting file:///usr/local/share/libwebsockets-test-server/server-status to /server-status
lwsws[30588]:    mounting cgi:///usr/local/share/libwebsockets-test-server/lws-cgi-test.sh to /testcgi
lwsws[30588]:    mounting callback://protocol-post-demo to /formtest
lwsws[30588]:  interface lo vs lo
lwsws[30588]:  interface eth0 vs lo
lwsws[30588]:  interface eth1 vs lo
lwsws[30588]:  interface lo vs lo
lwsws[30588]: _realloc: size 576: listen wsi
lwsws[30588]: __insert_wsi_socket_into_fds: 0x561443d31c80: tsi=0, sock=23, pos-in-fds=1
lwsws[30588]: lws_uv_timeout_cb
lwsws[30588]: lws_protocol_init
lwsws[30588]:     vhost "local", protocol "protocol-post-demo", option "status"
lwsws[30588]:     vhost "local", protocol "lws-status", option "status"
lwsws[30588]: _realloc: size 56: protocol_vh_privs
lwsws[30588]: _realloc: size 40: vh priv
lwsws[30588]:     vhost "local", protocol "lws-server-status", option "update-ms"
lwsws[30588]:     vhost "local", protocol "lws-server-status", option "status"
lwsws[30588]: _realloc: size 33984: vh priv
lwsws[30588]:     vhost "local", protocol "lws-mirror-protocol", option "status"
lwsws[30588]: _realloc: size 8: vh priv
lwsws[30588]:     vhost "local", protocol "lws-meta", option "status"
lwsws[30588]:     vhost "local", protocol "dumb-increment-protocol", option "status"
lwsws[30588]: _realloc: size 176: vh priv
lwsws[30588]: getpwuid: unable to find uid 48

**Comment by lws-team** [comment]
I'll be back in about 30m and can try to reproduce it.  But eg https://libwebsockets.org runs under master lws from a few days ago.  So whatever it is has to be something fairly narrow.

**Comment by lws-team** [comment]
So I tried it exactly as you wrote up... there is no problem here.  The test server is coming and working on http://localhost:7681

I have a UID48 ('apache' on Fedora), so I changed the conf to try to use 948 for uid and gid, also no problem, except the log is comeing

```
lwsws[77049]: getpwuid: unable to find uid 948
```

I notice on your log, it looks like you missed the leading '/' from the mount origin change

lwsws[30588]: ----file://usr/local/share/libwebsockets-test-server

Please check that.

**Comment by psdn** [comment]
I did fix the leading /. That was from my change I mentioned above.

Well shoot.  I could redo on a fresh vps, but I don't have anything else installed on this one except geth for etherum and a few supporting libraries.

**Comment by lws-team** [comment]
So fixing the leading , the problem coming is still a 404?  It you turn the logging (-d) up to 65535, I see this when I give it a bad url /xxx

```
lwsws[82172]: Method: 'GET' (0), request for '/xxx'
lwsws[82172]: lws_ensure_user_space: 0xddc950 protocol pss 0, user_space=(nil)
lwsws[82172]: __lws_set_timeout: 0xddc950: 20 secs
lwsws[82172]: _realloc: size 256: access log
lwsws[82172]: _realloc: size 78: access log
lwsws[82172]: client indicates GZIP is acceptable
lwsws[82172]: Unable to open '/usr/local/share/libwebsockets-test-server/xxx': errno 2
```

You don't get any logs like that?

**Comment by psdn** [comment]
sudo lwsws -d65535 Nothing from browser, the follwing from curl -I http://127.0.0.1:7681

lwsws[1241]: accepted new conn port 45678 on fd=17
lwsws[1241]: lws_get_or_create_peer: creating new peer
lwsws[1241]: _realloc: size 88: peer
lwsws[1241]: _realloc: size 576: new server wsi
lwsws[1241]: new wsi 0x55d05a914b80 joining vhost local, tsi 0
lwsws[1241]: lws_adopt_descriptor_vhost: new wsi 0x55d05a914b80, sockfd 17
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 20 secs
lwsws[1241]: __insert_wsi_socket_into_fds: 0x55d05a914b80: tsi=0, sock=17, pos-in-fds=2
lwsws[1241]: lws_header_table_attach: wsi 0x55d05a914b80: ah (nil) (tsi 0, count = 0) in
lwsws[1241]: _realloc: size 3000: ah struct
lwsws[1241]: _realloc: size 4096: ah data
lwsws[1241]: _lws_create_ah: created ah 0x55d05a914dd0 (size 4096): pool length 1
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a914b80: fd 17 events 1 -> 1
lwsws[1241]: lws_header_table_attach: did attach wsi 0x55d05a914b80: ah 0x55d05a914dd0: count 1 (on exit)
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 10 secs
lwsws[1241]: Attached ah immediately
lwsws[1241]: lws_plat_pipe_signal: fd 16 1
lwsws[1241]: LWS_CALLBACK_EVENT_WAIT_CANCELLED
lwsws[1241]: issuing 79 bytes to parser
lwsws[1241]: WSI_TOKEN_NAME_PART 'H' 0x48 (mode=0) wsi->lextable_pos=0
lwsws[1241]: WSI_TOKEN_NAME_PART 'E' 0x45 (mode=0) wsi->lextable_pos=102
lwsws[1241]: WSI_TOKEN_NAME_PART 'A' 0x41 (mode=0) wsi->lextable_pos=1136
lwsws[1241]: WSI_TOKEN_NAME_PART 'D' 0x44 (mode=0) wsi->lextable_pos=1137
lwsws[1241]: WSI_TOKEN_NAME_PART ' ' 0x20 (mode=0) wsi->lextable_pos=1138
lwsws[1241]: known hdr 82
lwsws[1241]: WSI_TOK_(82) '/'
lwsws[1241]: WSI_TOK_(82) ' '
lwsws[1241]: WSI_TOK_(15) 'H'
lwsws[1241]: WSI_TOK_(15) 'T'
lwsws[1241]: WSI_TOK_(15) 'T'
lwsws[1241]: WSI_TOK_(15) 'P'
lwsws[1241]: WSI_TOK_(15) '/'
lwsws[1241]: WSI_TOK_(15) '1'
lwsws[1241]: WSI_TOK_(15) '.'
lwsws[1241]: WSI_TOK_(15) '1'
'wsws[1241]: WSI_TOK_(15) '
lwsws[1241]: *
lwsws[1241]: WSI_TOKEN_SKIPPING_SAW_CR '
'
lwsws[1241]: WSI_TOKEN_NAME_PART 'H' 0x48 (mode=0) wsi->lextable_pos=0
lwsws[1241]: WSI_TOKEN_NAME_PART 'o' 0x6F (mode=0) wsi->lextable_pos=102
lwsws[1241]: WSI_TOKEN_NAME_PART 's' 0x73 (mode=0) wsi->lextable_pos=112
lwsws[1241]: WSI_TOKEN_NAME_PART 't' 0x74 (mode=0) wsi->lextable_pos=113
lwsws[1241]: WSI_TOKEN_NAME_PART ':' 0x3A (mode=0) wsi->lextable_pos=114
lwsws[1241]: known hdr 3
lwsws[1241]: WSI_TOK_(3) ' '
lwsws[1241]: WSI_TOK_(3) '1'
lwsws[1241]: WSI_TOK_(3) '2'
lwsws[1241]: WSI_TOK_(3) '7'
lwsws[1241]: WSI_TOK_(3) '.'
lwsws[1241]: WSI_TOK_(3) '0'
lwsws[1241]: WSI_TOK_(3) '.'
lwsws[1241]: WSI_TOK_(3) '0'
lwsws[1241]: WSI_TOK_(3) '.'
lwsws[1241]: WSI_TOK_(3) '1'
lwsws[1241]: WSI_TOK_(3) ':'
lwsws[1241]: WSI_TOK_(3) '7'
lwsws[1241]: WSI_TOK_(3) '6'
lwsws[1241]: WSI_TOK_(3) '8'
lwsws[1241]: WSI_TOK_(3) '1'
'wsws[1241]: WSI_TOK_(3) '
lwsws[1241]: *
lwsws[1241]: WSI_TOKEN_SKIPPING_SAW_CR '
'
lwsws[1241]: WSI_TOKEN_NAME_PART 'U' 0x55 (mode=0) wsi->lextable_pos=0
lwsws[1241]: WSI_TOKEN_NAME_PART 's' 0x73 (mode=0) wsi->lextable_pos=153
lwsws[1241]: WSI_TOKEN_NAME_PART 'e' 0x65 (mode=0) wsi->lextable_pos=1028
lwsws[1241]: WSI_TOKEN_NAME_PART 'r' 0x72 (mode=0) wsi->lextable_pos=1029
lwsws[1241]: WSI_TOKEN_NAME_PART '-' 0x2D (mode=0) wsi->lextable_pos=1030
lwsws[1241]: WSI_TOKEN_NAME_PART 'A' 0x41 (mode=0) wsi->lextable_pos=1031
lwsws[1241]: WSI_TOKEN_NAME_PART 'g' 0x67 (mode=0) wsi->lextable_pos=1032
lwsws[1241]: WSI_TOKEN_NAME_PART 'e' 0x65 (mode=0) wsi->lextable_pos=1033
lwsws[1241]: WSI_TOKEN_NAME_PART 'n' 0x6E (mode=0) wsi->lextable_pos=1034
lwsws[1241]: WSI_TOKEN_NAME_PART 't' 0x74 (mode=0) wsi->lextable_pos=1035
lwsws[1241]: WSI_TOKEN_NAME_PART ':' 0x3A (mode=0) wsi->lextable_pos=1036
lwsws[1241]: known hdr 69
lwsws[1241]: WSI_TOK_(69) ' '
lwsws[1241]: WSI_TOK_(69) 'c'
lwsws[1241]: WSI_TOK_(69) 'u'
lwsws[1241]: WSI_TOK_(69) 'r'
lwsws[1241]: WSI_TOK_(69) 'l'
lwsws[1241]: WSI_TOK_(69) '/'
lwsws[1241]: WSI_TOK_(69) '7'
lwsws[1241]: WSI_TOK_(69) '.'
lwsws[1241]: WSI_TOK_(69) '5'
lwsws[1241]: WSI_TOK_(69) '2'
lwsws[1241]: WSI_TOK_(69) '.'
lwsws[1241]: WSI_TOK_(69) '1'
'wsws[1241]: WSI_TOK_(69) '
lwsws[1241]: *
lwsws[1241]: WSI_TOKEN_SKIPPING_SAW_CR '
'
lwsws[1241]: WSI_TOKEN_NAME_PART 'A' 0x41 (mode=0) wsi->lextable_pos=0
lwsws[1241]: WSI_TOKEN_NAME_PART 'c' 0x63 (mode=0) wsi->lextable_pos=329
lwsws[1241]: WSI_TOKEN_NAME_PART 'c' 0x63 (mode=0) wsi->lextable_pos=342
lwsws[1241]: WSI_TOKEN_NAME_PART 'e' 0x65 (mode=0) wsi->lextable_pos=343
lwsws[1241]: WSI_TOKEN_NAME_PART 'p' 0x70 (mode=0) wsi->lextable_pos=344
lwsws[1241]: WSI_TOKEN_NAME_PART 't' 0x74 (mode=0) wsi->lextable_pos=351
lwsws[1241]: WSI_TOKEN_NAME_PART ':' 0x3A (mode=0) wsi->lextable_pos=352
lwsws[1241]: known hdr 17
lwsws[1241]: WSI_TOK_(17) ' '
lwsws[1241]: WSI_TOK_(17) '*'
lwsws[1241]: WSI_TOK_(17) '/'
lwsws[1241]: WSI_TOK_(17) '*'
'wsws[1241]: WSI_TOK_(17) '
lwsws[1241]: *
lwsws[1241]: WSI_TOKEN_SKIPPING_SAW_CR '
'
' 0x0D (mode=0) wsi->lextable_pos=0
lwsws[1241]: WSI_TOKEN_NAME_PART '
' 0x0A (mode=0) wsi->lextable_pos=238
lwsws[1241]: known hdr 8
lwsws[1241]: lws_handshake_server: lws_parse sees parsing complete
lwsws[1241]: vhost match to local based on port 7681
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 0 secs
lwsws[1241]: No upgrade
lwsws[1241]: lws_union_transition: 0x55d05a914b80: mode 1
lwsws[1241]: lws_handshake_server: wsi 0x55d05a914b80: ah 0x55d05a914dd0
lwsws[1241]: Method: 'HEAD' (7), request for '/'
lwsws[1241]: lws_ensure_user_space: 0x55d05a914b80 protocol pss 0, user_space=(nil)
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 20 secs
lwsws[1241]: _realloc: size 256: access log
lwsws[1241]: _realloc: size 13: access log
lwsws[1241]: no hit
lwsws[1241]: lws_same_vh_protocol_remove: removing same prot wsi 0x55d05a914b80
lwsws[1241]: lws_ensure_user_space: 0x55d05a914b80 protocol pss 0, user_space=(nil)
lwsws[1241]: lws_http_transaction_completed: wsi 0x55d05a914b80
lwsws[1241]: ah attached, pos 0, len 79
lwsws[1241]: lws_same_vh_protocol_remove: removing same prot wsi 0x55d05a914b80
lwsws[1241]: have prev 0x55d05a8fb2e0, setting him to our next (nil)
lwsws[1241]: lws_ensure_user_space: 0x55d05a914b80 protocol pss 0, user_space=(nil)
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 5 secs
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 10 secs
lwsws[1241]: __lws_set_timeout: 0x55d05a914b80: 5 secs
lwsws[1241]: lws_http_transaction_completed: 0x55d05a914b80: keep-alive await new transaction
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a914b80: fd 17 events 1 -> 5
lwsws[1241]: wsi->http.rx_content_length 0 0 0
lwsws[1241]: lws_server_socket_service: wsi 0x55d05a914b80: ah read rxpos 79, rxlen 79
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a914b80: fd 17 events 5 -> 1
lwsws[1241]: lws_server_socket_service: LWSS_HTTP_DEFERRING_ACTION now writable
lwsws[1241]:      existing ah rxpos 79 / rxlen 79
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a914b80: fd 17 events 1 -> 1
lwsws[1241]: lws_server_socket_service: read 0 len a
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a914b80: fd 17 events 1 -> 0
lwsws[1241]: __lws_close_free_wsi: 0x55d05a914b80: caller: server socket svc fail
lwsws[1241]: __lws_close_free_wsi: shutdown conn: 0x55d05a914b80 (sock 17, state 64)
lwsws[1241]: __lws_close_free_wsi: real just_kill_connection: 0x55d05a914b80 (sockfd 17)
lwsws[1241]: lws_same_vh_protocol_remove: removing same prot wsi 0x55d05a914b80
lwsws[1241]: have prev 0x55d05a8fb2e0, setting him to our next (nil)
lwsws[1241]: __remove_wsi_socket_from_fds: wsi=0x55d05a914b80, sock=17, fds pos=2, end guy pos=3, endfd=0
lwsws[1241]: _lws_change_pollfd: wsi 0x55d05a90bc80: fd 23 events 1 -> 1
lwsws[1241]: not calling back closed mode=0 state=64
lwsws[1241]: __lws_close_free_wsi: lws_libuv_closehandle: wsi 0x55d05a914b80
lwsws[1241]: ah det due to close
lwsws[1241]: __lws_header_table_detach: wsi 0x55d05a914b80: ah 0x55d05a914dd0 (tsi=0, count = 1)
lwsws[1241]: __lws_header_table_detach: nobody usable waiting
lwsws[1241]: _lws_destroy_ah: freed ah 0x55d05a914dd0 : pool length 0
lwsws[1241]: __lws_header_table_detach: wsi 0x55d05a914b80: ah 0x55d05a914dd0 (tsi=0, count = 0)
lwsws[1241]: __lws_free_wsi: 0x55d05a914b80, remaining wsi 2

**Comment by lws-team** [comment]
Eh..

```
lwsws[1241]: Method: 'HEAD' (7), request for '/'
```

What did you use to fetch the page?  I used firefox...

**Comment by psdn** [comment]
Firefox developer 59.0b13 (64-bit) and Chrome Version 64.0.3282.186. But from browser, the log just chunks along like below. I shutdown my virus program on my desktop as well.

lwsws[1443]: lws_uv_timeout_cb
lwsws[1443]: lws_uv_timeout_cb
lwsws[1443]: lws_uv_timeout_cb
lwsws[1443]: lws_uv_timeout_cb
lwsws[1443]: lws_uv_timeout_cb

**Comment by psdn** [comment]
Does the bold parts matter and can I change it?

netstat -pltn with sudo lwsws:
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 695/sshd
tcp 0 0 **127.0.0.1:7681** 0.0.0.0:* LISTEN 29100/lwsws
tcp6 0 0 :::22 :::* LISTEN 695/sshd

netstat -pltn with libwebsockets-test-server:
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 695/sshd
tcp 0 0 **0.0.0.0:7681** 0.0.0.0:* LISTEN 29129/libwebsockets
tcp6 0 0 :::22 :::* LISTEN 695/sshd

**Comment by lws-team** [comment]
Hmmm I also am on FF59, on Fedora.  But he doesn't send any HEAD, he sends a GET.

So what generated the HEAD?

**Comment by psdn** [comment]
curl. The browser doesn't affect the log in any way. curl  from localhost is the only way I get a response in the log.

**Comment by lws-team** [comment]
Oho... yes you can change it.

Edit /etc/lwsws/conf.d/test-server

```
     "interface": "lo",
```

means only bind to the loopback network device (127.0.0.1).

Just comment it, it will bind to all network interfaces.

**Comment by lws-team** [comment]
Curl was happening on the same box as the server, was it?

**Comment by psdn** [comment]
Winner winner, chicken dinner! Thank you Andy! See, I should've been able to catch that as I was loathing about from the beginning.

Yes, curl on the same box.

**Comment by lws-team** [comment]
I guess we undersood then... I'll turn that interface line into a commenton the next push.
