### ISSUE TITLE
Visual Studio support?

### ISSUE THREAD

**Issue by C-Treff** [warmcat/libwebsockets#1213]
I tried to follow the instructions in the docu to generate a solution, which can be built in VisualStudio, but the cmake generates a lot file not found entries. Most obvious error: inttypes.h not found and not part of the distribution. What additional step has to be performed to get these files? Any path missing somewhere?

I have downloaded and installed/unpacked cmake 3.10.3, libwebsockets-v2.4, Win64OpenSSL-1_1_0g. OPENSSL_CONF environment variable is correcly set.

I know, that many project focus Linux these days, but my target is Windows. Any hint, link wellcome. Thanks.
[log.txt](https://github.com/warmcat/libwebsockets/files/1832885/log.txt)

**Comment by lws-team** [comment]
I don't use windows, but lws is built in appveyor, eg

https://ci.appveyor.com/project/lws-team/libwebsockets/build/job/4cfm8k29mj78csjm

without problems; the 'missing files' are signs of it adapting not failing.  You can see the build log there.

Lws is able to adapt to the situation on your platform for build... it's looking for include files or symbols during cmake not because they are required, but so that the rest of lws adapts to whether they are on your platform or not.  In itself, it's not a problem if those things aren't found.

The only error in your log is this

```
OPENSSL_INPUT_WIN_PATH = C:\Users\chris\Documents\libwebsockets\build\openssl_input.txt cmd = "C:/OpenSSL-Win64/bin/openssl.exe" req -new -newkey rsa:1024 -days 10000 -nodes -x509 -keyout "C:/Users/chris/Documents/libwebsockets/build/libwebsockets-test-server.key.pem" -out "C:/Users/chris/Documents/libwebsockets/build/libwebsockets-test-server.pem" CMake Warning at CMakeLists.txt:1387 (message): !!! Failed to generate SSL certificate for Test Server using cmd.exe !!!: OpenSSL return code = 1 
```

Make sure openssl.exe exists at the expected path.

After that Appveyor just does this

```
cmake --build . --config Release
Microsoft (R) Build Engine version 14.0.25420.1
...
```

**Comment by C-Treff** [comment]
Thanks for the answer, I made one further step. I just executed the cmd manually and was asked to enter some additional information (country, name, email ...). After this, I was able to successfully run cmake -G ... once more without any error. But the problem is the same. The source private-libwebsockets.h has includes for inttypes.h which is not in standard include path.

**Comment by lws-team** [comment]
> But the problem is the same. The source private-libwebsockets.h has includes for inttypes.h which is not in standard include path.

I understand (although it would be easier to understand if you pasted the relevant error)... but as I pointed out, this stuff builds on windows on Appveyor.  Googling around, from VS2013 on, msvc evidently does have inttypes.h.  So how old is your VS?

**Comment by C-Treff** [comment]
Update. I just deleted the include in source file and now have to rewrite most of functions, which still have K&R definitions! Hope it will work.

**Comment by lws-team** [comment]
> I just deleted the include in source file and now have to rewrite most of functions, which still have K&R definitions! Hope it will work.

Sounds like you will waste a lot of time for no gain.

How old is your VS?  Pre 2013?

**Comment by C-Treff** [comment]
I have to use WolfSSL later on, which is delivered as a VS2012 library from external. So yes, I have VS2012 currently. Problem is Microsoft does not accept inline in C files and if you compile all as C++, the K&R is not any longer supported. But it shouldn't be to hard to convert. I will discuss with my external developer, if I can get VS2017 libs.

**Comment by lws-team** [comment]
Well, lws builds fine on Appveyor.  So using VC 2013+ should just work.

WolfSSL is FOSS, you can just build it using your newer VC too, if newer VC can't ear libs built on older VC.

Anyway, AFAIK nothing to fix on lws side.

**Comment by JoakimSoderberg** [comment]
> Thanks for the answer, I made one further step. I just executed the cmd manually and was asked to enter some additional information (country, name, email ...). After this, I was able to successfully run cmake -G ... once more without any error. But the problem is the same. The source private-libwebsockets.h has includes for inttypes.h which is not in standard include path.

This is simply an issue related to generating the dummy SSL cert used by some of the examples. Nothing required for the actual library.

The `logs.txt` you provided shows a successful run of `cmake`.
```
...
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/chris/Documents/libwebsockets/build
```

So now you will have a `.sln` file you can open in this directory. Just open it by running this command:
```
start *.sln
```

And try to build things inside of Visual Studio, which should work find out of the box.

Or you can build from the command line:
(Assuming you are still in C:/Users/chris/Documents/libwebsockets/build and using "git bash")
```
cmake --build .
```

> Update. I just deleted the include in source file and now have to rewrite most of functions, which still have K&R definitions! Hope it will work.

This should not be needed. @lws-team this seems to be a bug in LWS

https://github.com/warmcat/libwebsockets/blob/0bba228adbd6f504ee2a7b95843f73bb34bb0b0a/lib/private-libwebsockets.h#L45

Should be guarded by:
```
#ifdef LWS_HAVE_INTTYPES_H
```

**Comment by lws-team** [comment]
@JoakimSoderberg  thanks for weighing in.  However requiring inttypes.h is not a bug, quite the opposite.

It defines vsnprintf format string elements that match the stdint types like PRIu64 for uint64_t... without them if you have a stdint type vararg like uint64_t, you face the problem that the format elements are calibrated in natural types only like long int, long long int.  On different platforms, the correct format string then for uint64_t or whatever is different, according to what the libc headers typedef'd it to.

Using inttypes.h lets the same source of headers that defined the typedef for uint64_t also define the correct format string for use in vsnprintf and friends, so there is no longer any gap to fall into.

inttypes.h dates from C99... in 2018 the only bug using it in toolchains / libcs that don't have it.  Using it actually stops bugs.

**Comment by JoakimSoderberg** [comment]
No I meant having a check for `inttypes.h` is unecessary, if the include guard is never used for it.

So then the check if it exists can be removed from CMake. Or there could be an error there that it's required.

I did not mean the use of the header is a bug.

**Comment by lws-team** [comment]
Well fair enough... the cmake check is just cruft, since it is in fact required unconditionally.  I made a patch removing it from CMakeLists.txt and lws_config_private.h.in, I'll push it with other stuff later.
