### ISSUE TITLE
SSL verification skipped with mbedTLS and no CA provided

### ISSUE THREAD

**Issue by Faless** [warmcat/libwebsockets#1214]
As a follow-up from the discussion in #1128 .

**The problem**

When using the mbedTLS backend and no CA is provided any certificate is accepted by the client as specified here:
https://github.com/warmcat/libwebsockets/blob/d2bc2d17043ff373c8f2c54cd3eff473078aa16f/lib/tls/mbedtls/mbedtls-client.c#L75-L79

**Expected behaviour**

All SSL connections should fail when in strict mode (`LCCSCF_USE_SSL`).

**My suggestion**

Use `SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, OpenSSL_client_verify_callback);` in any case and fail when no CA is provided.

or

Always use `MBEDTLS_SSL_VERIFY_OPTIONAL` internally, and then implement the desired behaviour in the `ssl_pm_get_verify_result` function (this should also allow to implement the less strict options there like self signed certs, hostname verification, etc).
https://github.com/warmcat/libwebsockets/blob/d2bc2d17043ff373c8f2c54cd3eff473078aa16f/lib/tls/mbedtls/wrapper/platform/ssl_pm.c#L762

If can make a PR if you are interested.
**Thank you for your amazing work on this library.**
As I'm here, I'd like to let you know that we are integrating `libwebsockets` as a third party library in Godot Engine (see https://github.com/godotengine/godot and  https://github.com/godotengine/godot/blob/master/thirdparty/README.md#libwebsockets )

**Comment by lws-team** [comment]
Thanks... I guess ideally it should do the same as openssl and load the OS trust store in addition to VERIFY_OPTIONAL.  If you can provide a PR for the VERIFY_OPTIONAL bit at least it'd be a big help.  I think loading the OS trust store is going to be quite platform-dependent...

**Comment by lws-team** [comment]
Thanks a lot for the patch... it's applied and if you have any other integration problems or feature requests let me know.
