### ISSUE TITLE
Invalid memory access after lws_context_destroy() with foreign libuv loop

### ISSUE THREAD

**Issue by lukasgeyer** [warmcat/libwebsockets#1217]
When using a foreign libuv event loop with `v2.4.1-24-g36620a2`, an invalid memory access occurs after a call to `lws_context_destroy`. 

A modified `minimal-http-server.c` showing the behaviour can be found at https://pastebin.com/qtxNARyn, the corresponding Valgrind trace at https://pastebin.com/KRawuJLm.

I would have understood be9fb919d145d662d7a2ed4ae8e6912f75937449 that `lws_context_destroy2` should solve that problem, but the invalid access already occurs in `lws_context_destroy`.

**Comment by lws-team** [comment]
I'll study this in the morning, but...

```
[2018/03/28 17:03:45:2267] INFO: _lws_create_ah: created ah 0x83ca4c0 (size 4096): pool length 1
[2018/03/28 17:03:45:2268] INFO: lws_header_table_attach: did attach wsi 0x83c84f0: ah 0x83ca4c0: count 1 (on exit)
[2018/03/28 17:03:45:2268] DEBUG: lws_set_timeout: 0x83c84f0: 10 secs
[2018/03/28 17:03:45:2271] INFO: lws_server_socket_service: read 0 len a
[2018/03/28 17:03:45:2802] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:46:2818] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:47:2843] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:48:2882] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:49:2932] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:50:2957] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:51:3007] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:52:3058] DEBUG: lws_uv_timeout_cb
[2018/03/28 17:03:53:1782] INFO: lws_context_destroy: ctx 0x83c2090
```

...is there something necessary to do to reproduce it, in terms of making sure there is an attached ah when you destroy the context?

**Comment by lukasgeyer** [comment]
The example will destroy the context and terminate itself after 10 seconds. Just make sure that there is at least one HTTP request within that time, eg. `curl localhost:7681`.

Interestingly enough, when reducing `timeout_secs_ah_idle` so that the `ah` is destroyed before the context is destroyed the problem vanishes. So problem seems to be indeed related to an attached `ah`.

Speaking of that, is there any further documentation of `ah` and `timeout_secs_ah_idle`? I am still trying to grasp the purpose of that setting, or more specifically the need for that timeout in the first place (and why the `ah` is not released immediately when the connection is closed, there doesn't seem to be any re-use).

The example was compiled with `g++ -o main main.cpp -lwebsockets -luv` with `gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)`.

**Comment by lws-team** [comment]
Please take a look at

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-libuv-foreign

if you remove the optional line setting the 404 handler, this builds and works fine also on v2.4.

I pushed a very small patch on v2.4 and master

https://github.com/warmcat/libwebsockets/commit/4fcdc00924985ae8e95cadf2b8ea7faf1c4b6b10

which makes sure after lws closes his one-time libuv assets like hrtimer and idle, he spins a little bit in NOWAIT loop run himself to make sure the close callbacks are done before he moves on.

Please see if you get any problems using this new test app and the patch mentioned above, or 2.4 or master.

`timeout_secs_ah_idle` is kind of deprecated... it's still used to set a timeout on an established connection holding an ah.  In 2.4 I changed the code from having a fixed ah pool to dynamically creating ah up to a limit.  It's expensive to have the worst case amount of ah sitting around doing nothing most of the time on small targets.  With http/2, the peak number of ah you might want is larger than http/1.1 where the requests were pipelined, using one ah sequentially; with http/2 all your requests are fulfilled concurrently and then all are using an ah.

**Comment by lws-team** [comment]
I assume it's solved... if not, let me know how to reproduce on the stuff mentioned above.

**Comment by lukasgeyer** [comment]
I did some further testing and even though the actual problem does no longer occur, I am still dubious about the solution.

The `minimal-http-server-libuv-foreign.c` example assumes that the event loop has stopped when `lws_context_destroy` is called, which will likely not be the case when a foreign event loop is used, because the loop continues to serve the rest of the application. If `uv_run` is now called from within the library, additional callbacks apart from the desired close callbacks may be triggered while the context is being destructed in `lws_context_destroy` and thus is in an undefined state. These additional callbacks may have unwanted side-effects.

If the foreign event loop was stopped before a call to `lws_context_destroy` it will spin up the event loop uncontrollable.

This removes the basic guarantee of a controlled, in-order execution applications may want to or even need to rely on when using a single-threaded, asynchronous programming model based on an event loop.

The destruction of a context is split in two stages already, which require at least one loop iteration in between by defintion. Wouldn't it be possible to move the code which now requires a call to `uv_run` in `lws_context_destroy` to `lws_context_destroy2` so that there is no need for the library to spin the foreign event loop (this does not apply if the library uses its own event loop)?

So no, even though the problem does no longer occur, this issue is not resolved to me.

Thanks for the update on `timeout_secs_ah_idle`. So if I understood you correctly an `ah` is reserved for a specific connection because most likely there will be another request on that connection which can then reuse the reserved `ah` and does not need to acquire a new one. The timeout ensures that the reservation is cancelled when the connection is being idle for a certain period of time. This seems to be also true for a closed connection, which is where it stops making sense to me, because a closed connection will never be able to reuse the reserved `ah`.

Given that I simply want to serve some HTTP content. As there shall be an upper boundary for resource usage I set `max_http_header_pool` to 100 and I would assume that I now can serve 100 concurrent requests (`curl localhost:7681`) simultaneously (`max_http_header_pool`: _"The max number of connections with http headers that can be processed simultaneously"_). Actually, libwebsockets will serve 100 request and then block for 10 seconds or the configured `timeout_secs_ah_idle`, but at least one second (as `0` cannot be configured) even though there is no (simultaneous) connection.

**Comment by lws-team** [comment]
> The minimal-http-server-libuv-foreign.c example assumes that the event loop has stopped when lws_context_destroy is called, which will likely not be the case when a foreign event loop is used,

The process of lws_context_destroy stops the loop after it has seen all of its "dynamic assets" (ie, wsi) uv handles are closed.

https://github.com/warmcat/libwebsockets/blob/master/lib/event-libs/libuv.c#L471

>  Wouldn't it be possible to move the code which now requires a call to uv_run in lws_context_destroy to lws_context_destroy2 so that there is no need for the library to spin the foreign event loop (this does not apply if the library uses its own event loop)?

That won't change anything nor remove the need for more goes around the event loop.  Lws has closed its "static assets" (eg, uv_idle) at that time and somebody has to go around the event loop for libuv to complete that.

By running it in lws it lets me do it with NOWAIT and a budget for goes around that reflects what it has closed.

It sounds like what you think it needs is to ban running the event loop and extend the reference counting scheme for closes into the "static assets", and not allow lws to finish until those come "naturally" by something else running the event loop, is that it?

If so can you think of something simple to do in the minimal example that will show that this is enough to not get trouble from any fix (ie, something that will blow up as it is, if the scenario is realistic?)

**Comment by lukasgeyer** [comment]
> The process of lws_context_destroy stops the loop after it has seen all of its "dynamic assets" (ie, wsi) uv handles are closed.

But you cannot guarantee that not any other callback but those required to close the dynamic assets is called. 

> It sounds like what you think it needs is to ban running the event loop and extend the reference counting scheme for closes into the "static assets", and not allow lws to finish until those come "naturally" by something else running the event loop, is that it?

Exactly. As the foreign event loop is a shared resource a single participant must not modify the loop beyond it own handles like an unconditional `uv_walk` or `uv_run` and `uv_stop`, as this will affect all other participants as well. Spinning the event loop is the sole responsibility of the instance managing all participants, because just this instance has the required knowledge on when it is safe to start and stop the loop.

> That won't change anything nor remove the need for more goes around the event loop. Lws has closed its "static assets" (eg, uv_idle) at that time and somebody has to go around the event loop for libuv to complete that.

Yes, in order to properly destroy a context certain loop iterations are required and it is the responsibility of the mentioned instance that these are executed (which is in case of a foreign event loop, not the library). I thought that this is the purpose of `lws_context_destroy2()`. `lws_context_destroy()` frees "non-static" assets and closes all handles, then one must spin the event loop so that `libuv` invokes the close callbacks, then call `lws_context_destroy2()` to free those "static assets".

I am wondering why `lws_context_destroy2()` is even needed. Why can't `lws_context_destroy()` just free the "non-static assets" and close the handles, and the asynchronously invoked callbacks free the "static assets" as soon as the reference counts drops to zero (which must happen with the last close callback)?

> If so can you think of something simple to do in the minimal example that will show that this is enough to not get trouble from any fix (ie, something that will blow up as it is, if the scenario is realistic?)

What I did during testing is that I added a check handle and an assertion, that this handle must not be invoked until `lws_context_destroy` returned.

**Comment by lws-team** [comment]
>  I thought that this is the purpose of lws_context_destroy2()

Making it into two parts was facilitating running the loop outside lws before finalizing the destruction.  If lws owns the loop that was OK, and it's still OK with the last patch moving that into the destruction flow.

With non-foreign loop or foreign loop with no external handles, or handles that don't mind running as in the test-server-libuv, none of this makes any problem as it is.

It's only a truly foreign loop with handles that care about who is running the loop which require reference-counting even the static handles.

> What I did during testing is that I added a check handle and an assertion, that this handle must not be invoked until lws_context_destroy returned.

OK.

**Comment by lws-team** [comment]
Please have a look here

https://github.com/warmcat/libwebsockets/commit/d67eb91f13914cc66e8a605712b3e8a3862daa4b

This is working with no code left to do self-run of the event loop at all, on both the foreign and internal loops, with no valgrind problems.

**Comment by lukasgeyer** [comment]
I slightly modified `minimal-http-server-libuv-foreign.c` so that `lws_context_destroy()` is called once in the timer callback to cover the initial use case (port shall be closed while application keeps running). This again leads to an invalid memory access, see https://pastebin.com/PsBe9EpR.

The commit also contains a call to `uv_stop` (which is even worse than `uv_run`, as it will halt the application) - in which situation is it called actually? I can't seem to trigger this code path in the example, but it is not restricted to a foreign event loop either. 

The example also contains a call to `lws_context_destroy2`. Is it still needed?

**Comment by lws-team** [comment]
> The commit also contains a call to uv_stop (which is even worse than uv_run, as it will halt the application)

Correct me if I am wrong it will simply pause the application, so we can destroy the lws context.  You can just come back around and re-enter uv_run and everything as before.  If I said that was a constraint but everything else like the perfect cleanup okay, that is not "worse", is it?

Why don't you take a minute and explain from the perspective of your use case what you are looking for.

**Comment by lukasgeyer** [comment]
> Correct me if I am wrong it will simply pause the application, ...

It may pause the application, it may also halt the application - it depends on the implementation of the application. In our case it will halt the applications, because they roughly follow the same pattern as most event-driven applications do, where `uv_stop` logically equals to `std::exit()`:

```
int main(int, char *[])
{
   // Initialization
   
   uv_run(loop, UV_RUN_DEFAULT);

   // Finalization

   return ...;
}
```

> ... so we can destroy the lws context. 

There is no need to pause the application to destroy the context. If each related loop handle is closed in `lws_context_destroy` the reference count is asynchronously decreased on each close callback and the asset is finally destroyed somewhen in the future when the reference count drops to zero because of the last close callback being called. It is the responsibility of the owner of the event loop to make sure that it spins for the required amount of iterations.

> You can just come back around and re-enter uv_run and everything as before. 

I can't, the application has terminated because of `uv_stop`. This is the "worst case".

> Why don't you take a minute and explain from the perspective of your use case what you are looking for.

I want to integrate `libwebsockets` in our applications, which are already driven by an event loop. This event loop is used to drive the application flow and certain other libraries. For this, `libwebsockets` must be able to interact with the existing, shared event loop and it must not call `uv_run`, `uv_stop` or `uv_walk` unconditionally, because it will break the application flow (as seen above) and/or the other libraries.

**Comment by lws-team** [comment]
> it depends on the implementation of the application.

So it's your design decision but it's my problem.

Correct me if I am wrong but the effect on me if you use lws or not is exactly zero either way.  But somehow you are expecting me to run around to deliver exactly what you need.

> it must not call uv_run, uv_stop or uv_walk 

This is what is making me irritated with this "issue".  Eliminating uv_walk and uv_run was a lot of work, and it is done.  But you neither listed what you needed, nor acknowledged that most of the job is done (by me...), just tell me the result is "worse".  Where do you get off demanding your free work?  Now your only problem is uv_stop.

Why don't YOU do some work and propose a patch now the hard part is done?

**Comment by lukasgeyer** [comment]
> Correct me if I am wrong but the effect on me if you use lws or not is exactly zero either way. 

Surely.

> But somehow you are expecting me to run around to deliver exactly what you need.

Surely not. We found this issue during testing and we decided to report it upstream because it will affect everyone using a foreign event loop, regardless of the design decision made. Destroying a context driven by a foreign event loop will cause an invalid memory access. "[As a user] I want ..." is a common idiom to express a user story and no claim for anything other than what one is willingly to provide voluntarily was intended.

As asked, I tested and reviewed the patch and the added example and I have come to the conclusion that the patch will introduce another problem that must be fixed, because it will have a significant negative side effect. At the risk of sounding harsh or demanding again (please be assured that it is not meant that way), but the example does not reflect a real world use case for a foreign event loop, because "a truly foreign loop with handles that care about who is running the loop" with the loop outliving the context is the standard case. At the moment, there is an invalid memory access and an additional significant negative side effect - why I described it as being "worse" than before - and one cannot use the library in this scenario anymore. I made a proposal on how to fix that.

> Eliminating uv_walk and uv_run was a lot of work, and it is done. But you neither listed what you needed, nor acknowledged that most of the job is done (by me...).

This was not the intent, quite contrary to, the response time and the willingness to work on issues within that project is exceptional, yet I do not know what information to provide to "list what I need" other than what has already been provided.

> Why don't YOU do some work and propose a patch now the hard part is done?

Due to the lack of knowledge of the `libwebsockets` code base required to implement the change and the serious lack of spare time to improve it all I can contribute for now is providing information including a real world example, testing of patches and reviewing code changes based on the experience of resource management with `libuv` and event-driven applications (which is work too). 

I am not quite sure where this conversation took the wrong turn, but it is a pity it did and I hope that we can get back on track to fix this issue.
