### ISSUE TITLE
example requests.

### ISSUE THREAD

**Issue by nospamcalfee** [warmcat/libwebsockets#1218]
Hi,

First let me thank you for the excellent library. I used it a few years ago and was impressed. Lately I have been exploring replacing a Python Tornado web application with a much smaller embedded footprint using lws.

My embedded application is a multiple server system cooperating over wifi. So each system needs to be able to handle a human interface web interface gui via http, and communicate with others via client posts. I generally use json for client data interchange.

I recently ran into a problem with form posts in the lws "spa" support code. I needed to extend the internal "lws_urldecode_stateful" struct which has fixed length arrays for stuff like name lengths. It seems odd to have this buried in a library, rather than accepting user data structures.

Also with (server) POSTs the example uses const char * const param_names[] for form items to be decoded. I do not see how to have a different table for each possible post type. It seems like each URL might want its own decode table? For a complete app this one table would get very big.

I would like to request more minimal examples. I would really like to see a http server POST example and also a client example doing POSTs.

Thanks, Steve

**Comment by nospamcalfee** [comment]
While I am at it I would like an example showing how to do a POST/REDIR/GET process so a posted form can cause the browser to do a fetch from a new url, rather than getting the old form back or some plain ok type screen built by the post software.

**Comment by lws-team** [comment]
> It seems odd to have this buried in a library, rather than accepting user data structures.

I think there's maybe a misunderstanding there... the entire spa stuff is called (or not) from user code only, it's just a helper not part of the library internals.  If you find it doesn't do what you need, by all means let's discuss it, but you do not have to call it at all and can use your own implementation to interpret POST body content.

However it's not that easy to do it for both url parameter and multipart (file transfer), which is why spa exists as a helper.

> Also with (server) POSTs the example uses const char * const param_names[] ... For a complete app this one table would get very big.

If you have multiple forms being posted, you can select the list of parameter names you care about by looking at the WSI_TOKEN_POST_URI and choosing the appropriate one for the specific form.

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c exists which shows most of this.  But I guess a minimal example with a redirect won't hurt.

**Comment by lws-team** [comment]
Here we go:

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-form-get
https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-form-post
https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-form-post-file

**Comment by nospamcalfee** [comment]
These examples are very valuable. I am trying to implement a form post capability and I think I have found an example error.

in minimal-http-server-form-post.c:

		if (lws_http_redirect(wsi, HTTP_STATUS_MOVED_PERMANENTLY,
				      (unsigned char *)"after-form1.html",
				      16, &p, end))
			return -1;

		/* we could add more headers here */

		if (lws_finalize_http_header(wsi, &p, end))
			return -1;

		n = lws_write(wsi, start, lws_ptr_diff(p, start),
			      LWS_WRITE_HTTP_HEADERS |
			      LWS_WRITE_H2_STREAM_END);
		if (n < 0)
			return -1;

The error I am getting is the library complaining about back-to-back writes. OK, so then I look in header.c and I see:
	return lws_write(wsi, start, *p - start, LWS_WRITE_HTTP_HEADERS |
						 LWS_WRITE_H2_STREAM_END);

So I believe the write is handled in lws_http_redirect and does not have to be in my server. Correct?

Steve

**Comment by lws-team** [comment]
Yeah it's my mistake, thanks for pointing it out.  I fixed it and will push the patch later.

**Comment by nospamcalfee** [comment]
Also, don't forget that the return value from lws_http_redirect is now the number of bytes send if ok, or negative on error, because it is coming from lws_write - so the conditional in the example above needs to be 

if (lws_http_redirect(wsi, HTTP_STATUS_MOVED_PERMANENTLY,
			      (unsigned char *)"after-form1.html",
			      16, &p, end) < 0) ...

Regards, Steve

**Comment by lws-team** [comment]
Whoops... the docs are wrong on that... I amended the patch and the libwebsockets.h docs to reflect it's just returning the lws_write(), so <0 means failure.
