### ISSUE TITLE
Compile error with MinGW

### ISSUE THREAD

**Issue by Faless** [warmcat/libwebsockets#1219]
When compiling `v2.4.2` (or `v2.4-stable` in general) with MinGW `ENOTCONN` is not defined and the build fails.

```
lib/ssl.c:466:33: error: 'ENOTCONN' undeclared (first use in this function)
  if (!n || (n == -1 && errno == ENOTCONN)) {
```

I had to add an extra ifdef at the top (the same way as the `ECONNABORTED` one that is already there):
```
diff --git a/lib/ssl.c b/lib/ssl.c
index 755d06db..58e645d8 100644
--- a/lib/ssl.c
+++ b/lib/ssl.c
@@ -25,6 +25,9 @@
 #if !defined(ECONNABORTED)
 #define ECONNABORTED 103
 #endif
+#if !defined(ENOTCONN)
+#define ENOTCONN 126
+#endif
 
 int lws_alloc_vfs_file(struct lws_context *context, const char *filename, uint8_t **buf,
                lws_filepos_t *amount)
```

The problem is present in master branch too, but only for the OpenSSL version `lib/tls/openssl/ssl.c`, not the mbedTLS one `lib/tls/mbedtls/ssl.c` (not sure though if that could should be there too and was just not copy-pasted)

mingw-w64 version: `5.0.2`

**Comment by lws-team** [comment]
Thanks... mingw toolchain ought to provide these... anyway I pushed changes on both v2.4-stable and master for these.

mbedtls reports errors differently than openssl so no worries this is not needed there.

**Comment by Faless** [comment]
And it does actually: https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-headers/crt/errno.h#L150
You have to `#include "errno.h"`, not sure why it works with VS, probably just get included by some other windows header when building with VS.

**Comment by lws-team** [comment]
That's much better if it works... I adapted both the patches to do that instead (actually, <errno.h>)
