### ISSUE TITLE
hi! How to build android? arm64/armeabi/armeabi-v7a

### ISSUE THREAD

**Issue by saisaixv** [warmcat/libwebsockets#1220]

**Comment by lws-team** [comment]
I have never built it for android, but several users have done so.

There's a contributed makefile here

https://github.com/warmcat/libwebsockets/blob/master/contrib/Android.mk

But I'm guessing it's out of date.  If you'd like to contribute an updated version it's very welcome.

**Comment by lws-team** [comment]
... oh and another contribution here

https://github.com/warmcat/libwebsockets/blob/master/contrib/android-make-script.sh

**Comment by saisaixv** [comment]
Thank you. Let me see.
