### ISSUE TITLE
Unable to connect with an URL length > 1023. URL was truncated.

### ISSUE THREAD

**Issue by zhoujianboy** [warmcat/libwebsockets#1221]
Unable to connect with an URL length > 1023. URL was truncated.

/caihongmao_yn/eb925166-f24b-4902-bb02-2dc09cceb38e/?post_data=%7B%22channelid%22%3A%22yy%22%2C%22gameid%22%3A%22caihongmao_yn%22%2C%22roomid%22%3A%22eb925166-f24b-4902-bb02-2dc09cceb38e%22%2C%22player%22%3A%7B%22uid%22%3A%22990000027%22%2C%22name%22%3A%22hippop%22%2C%22avatarurl%22%3A%22http%3A%2F%2Fkaixindou.kaixindou.net%2Fuser_album%2F990000027_1522207978748.jpg%22%2C%22opt%22%3A%22%7B%5C%22ai%5C%22%3A1%2C%5C%22level%5C%22%3A4%2C%5C%22ai_info%5C%22%3A%7B%5C%22uid%5C%22%3A%5C%22900001708%5C%22%2C%5C%22nick%5C%22%3A%5C%22Mamae%20AlvianRizkhqy%20Chibichibicute%5C%22%2C%5C%22avatar%5C%22%3A%5C%22https%3A%2F%2Fscontent-hkg3-1.xx.fbcdn.net%2Fv%2Ft1.0-1%2Fc0.0.148.148%2Fp148x148%2F576037_262973327152122_1505688046_n.jpg%3F_nc_cat%3D0%5C%5Cu0026oh%3D600e061964f2e2a58e629a8c2e59b8be%5C%5Cu0026oe%3D5B347DB9%5C%22%2C%5C%22sex%5C%22%3A0%7D%7D%22%2C%22teamid%22%3A%22%22%2C%22sex%22%3A1%7D%7D&timestamp=1522227570&nonstr=enktwnkf-wty6-2fwf-sqmf-297tmqdth121&sign=951b49ecfae59d649b60a76dfb68169c85e49823&EIO=3&transport=

**Comment by lws-team** [comment]
This is being a client or a server?

**Comment by lws-team** [comment]
... and what version of lws exactly?

**Comment by zhoujianboy** [comment]
It is a client. We use tcpdump to capture package. It's clearly a client problem. The version  is v2.1-stable.

**Comment by lws-team** [comment]
It's a bit old, but there are a couple of things you can control in the context creation info struct

```
	short max_http_header_data;
	/**< CONTEXT: The max amount of header payload that can be handled
	 * in an http request (unrecognized header payload is dropped) */
```

and

```
	unsigned int pt_serv_buf_size;
	/**< CONTEXT: 0 = default of 4096.  This buffer is used by
	 * various service related features including file serving, it
	 * defines the max chunk of file that can be sent at once.
	 * At the risk of lws having to buffer failed large sends, it
	 * can be increased to, eg, 128KiB to improve throughput. */
```

Both of these default to 4096 though if you are not setting them to something else.

I checked it on master, client is sending a 2KB url fine using just defaults for everything.

**Comment by lws-team** [comment]
... also are you making your own "by hand" protocol to handle this http?  Also check the lws_protocols `.rx_buffer_size` and make that also bigger than 1024.

**Comment by zhoujianboy** [comment]
@lws-team I'll try. Thanks!

**Comment by zhoujianboy** [comment]
@lws-team I am a java programer. It is hard for me to read C code. Can you tell me which variable affects the result > "URL was truncated".

**Comment by lws-team** [comment]
The three things I mentioned above can affect it.  Since I can't see your code I don't know what you changed.

The first two are members of the lws context creation info struct.  So look in the code that creates the lws context to see if they were changed.

The last one is in struct lws_protocols... look for that in your code and see what .rx_buffer_size was set to.

**Comment by zhoujianboy** [comment]
@lws-team 你是台北的嗎？

**Comment by lws-team** [comment]
Yeah I live in Xiaobitan in Taipei.
