### ISSUE TITLE
example request: minimal-http-client-post

### ISSUE THREAD

**Issue by nospamcalfee** [warmcat/libwebsockets#1222]
Your help with the http server post stuff was great. And the new minimal examples really helped, so I got that working.

Now my next step is for my app to be able to POST json text from system to system. Your two existing minimal clients do GETs, and I don't understand how to send data in the first half of a client POST request. It appears it may be as simple as building up a proper lws_client_connect_info structure. Doing the client post write before getting back a response is not obvious.

Thanks, Steve

**Comment by lws-team** [comment]
This should be what you need (requires current master)

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-client/minimal-http-client-post

**Comment by nospamcalfee** [comment]
Excellent examples, thanks.

What I don't understand is can I have one http_callback for both client and host? They seem to have unique callback states, but the default exit is different - host transactions either return 0 or if complete call lws_http_transaction_completed. Clients callbacks return 0 or call lws_callback_http_dummy which seems to be an extension of the callback with huge conditional compilations for features like cgi, proxy etc. Does lws_cancel_service just terminate the client waiting, the description implies it affects host connections etc? How do I "complete" a client transaction?

It seems your sample code always exits with return 0, except state LWS_CALLBACK_COMPLETED_CLIENT_HTTP which will fall through to lws_callback_http_dummy - but it looks to me like in this case it will just do a return 0;

So in what case do I need to call lws_callback_http_dummy - and could you describe what lws_callback_http_dummy's true use is?
