### ISSUE TITLE
Certificate pinning / LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION

### ISSUE THREAD

**Issue by sp-stefano-lanza** [warmcat/libwebsockets#1224]
Hi, 

I am trying to add certificate pinning to a client - server SSL connection. The idea is to extract a public key from the server certificate and compare it with a local one in order to validate the server identity.
Based on my understanding of libwebsockets, ```LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION``` appears to be the best place to do the certificate pinning. My code is:
```
case LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS:
  SSL_CTX_set_cert_verify_callback((SSL_CTX*)user, always_true_callback, nullptr);
  break;
case LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION:
  {
  SSL* ssl = lws_get_ssl(wsi);
  LibWebsocketConnection* connection = (LibWebsocketConnection*)lws_wsi_user(wsi);
  ret = pkp_pin_peer_pubkey(ssl, connection->getPublicKey());
  }
  break;
```
As you can see, I am bypassing the certificate validation by setting a callback that always returns true. A connection is succesfully established but, unfortunately, the callback LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS  is never invoked. I spent days reading the API documentation and looking for examples with no luck. I even debugged the libwebsockets code and found out that this line in ss-client.c is hit
```
SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, OpenSSL_client_verify_callback);
```
yet ```OpenSSL_client_verify_callback``` is never called, which makes me think the actual problem lies in OpenSSL and not libwebsockets.
Do you know what could cause this issue ?
Btw, I´m using libwebsockets 2.4.2 and OpenSSL 1.0.2. Also in the same project I´m using libcurl; do you know if that could cause a conflict ?
Thanks a lot !

**Comment by lws-team** [comment]
> Btw, I´m using libwebsockets 2.4.2 and OpenSSL 1.0.2. Also in the same project I´m using libcurl;

Not being immortal I can't take care about everyone's specific mix of everything as if I was personally going to get any benefit from it.  Or even see the working code...

What I suggest you do is put that to one side, clone master and look at eg,

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-tls

There is a very small piece of code that we both have.

In master, there is an api for looking at the peer and vhosts certs

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L5990

Please realign your studies on that.

**Comment by sp-stefano-lanza** [comment]
Thank you Andy for the quick reply.
In the end, I fixed this issue by handling the certificate pinning in
the LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH
callback. Here I can obtain the SSL object of a socket by calling lws_get_ssl,
and then get the certificate and its public key by calling the relevant
OpenSSL functions.
I had a look at lws_tls_vhost_cert_info as per your advice. At the moment I
cannot use this function as it does not return the public key of a
certificate. See x509_get_X509_PUBKEY. Perhaps in the future you could
extend it with more LWS_TLS_CERT_INFO_* options ?
The original issue, that
LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION is never called,
persists, but I am not going to investigate further.
Thank you for your help.

**Comment by lws-team** [comment]
...you are not using client certs, right?  It "performs **client cert** verification"

```
LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION	= 23,
	/**< if the libwebsockets vhost was created with the option
	 * LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT, then this
	 * callback is generated during OpenSSL verification of the cert
	 * sent from the client.  It is sent to protocol[0] callback as
	 * no protocol has been negotiated on the connection yet.
	 * Notice that the libwebsockets context and wsi are both NULL
	 * during this callback.  See
	 *  http://www.openssl.org/docs/ssl/SSL_CTX_set_verify.html
	 * to understand more detail about the OpenSSL callback that
	 * generates this libwebsockets callback and the meanings of the
	 * arguments passed.  In this callback, user is the x509_ctx,
	 * in is the ssl pointer and len is preverify_ok
	 * Notice that this callback maintains libwebsocket return
	 * conventions, return 0 to mean the cert is OK or 1 to fail it.
	 * This also means that if you don't handle this callback then
	 * the default callback action of returning 0 allows the client
	 * certificates. */
```

> Perhaps in the future you could extend it with more LWS_TLS_CERT_INFO_* options ?

I thought your issue was a request to cooperate in implementing it.  If you want that to happen please paste the business end of your working code somewhere.  Lws supports mbedtls as a backend as transparently as possible, requiring two completely different implementations in lws for everything like this... the new api is set up to hide that for the user.  But it sure would be a help to get a working openssl side to start from, even if it is a 'bleeding chunk'.

**Comment by sp-stefano-lanza** [comment]
Hi,

Sorry I meant LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION  - I am
performing only server cert verification in my setup.
I´d be happy to help you extending LWS but I do not think I am the most
qualified person to do it as I have very little experience with networking
protocols.

**Comment by lws-team** [comment]
All I am asking is paste this part of your solution.

> I fixed this issue by handling the certificate pinning in the LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH callback. Here I can obtain the SSL object of a socket by calling lws_get_ssl, and then get the certificate and its public key by calling the relevant OpenSSL functions.

OpenSSL usually needs a lot of api testing and other meddling to have it work on various distros / platforms.  I don't mind doing that but it would be nice to not have to fiddle around trying to get even the basic implementation working myself.

**Comment by sp-stefano-lanza** [comment]
Here´s the code of my certificate pinning. It should be straightforward, please let me know if you any questions.

```
int callback_websocket(lws* wsi, lws_callback_reasons reason, void* user, void* in, size_t len)
{
  int ret = 0;
...
  case LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH:
  {
    const std::string_view& publicKey = ... // extract public key from user data
    if(!publicKey.empty())
    {
      lwsl_notice("Certificate pinning\n");
      if(!pkp_pin_peer_pubkey(lws_get_ssl(wsi), publicKey.data(), publicKey.length()))
      {
        lwsl_err("Certificate pinning failed\n");
        ret = -1;// close connection
      }
    }
  }
...
  return ret;
}


int pkp_pin_peer_pubkey(SSL* ssl, const char* publicKey, size_t publicKeyLength)
{
  unsigned char* buff1 = nullptr;
  X509* cert = nullptr;
  int result = 0;// fail
  unsigned long ssl_err;
  do
  {
    cert = SSL_get_peer_certificate(ssl);
    ssl_err = ERR_get_error();
    if(cert == nullptr)
    {
      lwsl_err("SSL_get_peer_certificate %lu\n", ssl_err);
      break;
    }
            
    const int len1 = i2d_X509_PUBKEY(X509_get_X509_PUBKEY(cert), nullptr);
    ssl_err = ERR_get_error();
    if(len1 <= 0)
    {
      lwsl_err("i2d_X509_PUBKEY (1) %lu\n", ssl_err);
      break;
    }
            
    buff1 = (unsigned char*)OPENSSL_malloc(len1);
    ssl_err = ERR_get_error();
    if(buff1 == nullptr)
    {
      lwsl_err("OpenSSL_malloc (1) %lu\n", ssl_err);
      break;
    }
            
    unsigned char* temp = buff1;
    const int len2 = i2d_X509_PUBKEY(X509_get_X509_PUBKEY(cert), &temp);
    ssl_err = ERR_get_error();
    if(len1 != len2 || (temp == nullptr) || (temp - buff1) != len1)
    {
      lwsl_err("i2d_X509_PUBKEY (2) %lu\n", ssl_err);
      break;
    }
            
    // Compare keys
    if(len1 != (int)publicKeyLength || memcmp(publicKey, buff1, publicKeyLength) != 0)
    {
      break;
    }
            
    result = 1;
  } while(0);
        
  if(buff1)
  {
    OPENSSL_free(buff1);
  }
        
  if(cert)
  {
    X509_free(cert);
  }

  return result;
}
```

**Comment by lws-team** [comment]
Thanks... the cert pubkey access is implemented in lws now and works for both OpenSSL and mbedTLS, although the representation of the pubkey is different for each, so they can only be compared to pubkeys read from the same backend.

There's a 'minimal example' showing how to access peer certificate info the official way

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-client/minimal-http-client-certinfo

It doesn't actually do the pinning check.  But you can get the peer pubkey now easily and compatibly with mbedTLS via lws, and the actual pinning check boils down to a memcmp in LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH.
