### ISSUE TITLE
Error installing 2.4 stable on Mac Os.

### ISSUE THREAD

**Issue by Triuman** [warmcat/libwebsockets#1227]
Hello, I first tried installing via brew but it installed an older version. So I cloned 2.4 stable version but it gives some errors when I say 'make && sudo make install'. I have OpenSSL 2.2.7 installed. What could be the problem?

Thank you.

ERRORS:

/Users/tracer/libwebsockets/lib/client/ssl-client.c:488:25: error: implicit declaration of function
      'TLS_client_method' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        method = (SSL_METHOD *)TLS_client_method();
                               ^
/Users/tracer/libwebsockets/lib/client/ssl-client.c:488:25: note: did you mean 'DTLS_client_method'?
/usr/local/opt/openssl/include/openssl/ssl.h:2389:19: note: 'DTLS_client_method' declared here
const SSL_METHOD *DTLS_client_method(void); /* DTLS 1.0 and 1.2 */
                  ^
/Users/tracer/libwebsockets/lib/client/ssl-client.c:488:11: error: cast to 'SSL_METHOD *'
      (aka 'struct ssl_method_st *') from smaller integer type 'int' [-Werror,-Wint-to-pointer-cast]
        method = (SSL_METHOD *)TLS_client_method();

**Comment by Triuman** [comment]
It says 'LibreSSL 2.2.7' when I run 'openssl version'.

**Comment by lws-team** [comment]
Well this builds on travis on mac.  So the problem depends on the ssl lib version / project... the right openssl api to use depends on the exact openssl version.  The code in lws is like this

```
	/* choose the most recent spin of the api */
#if defined(LWS_HAVE_TLS_CLIENT_METHOD)
	method = (SSL_METHOD *)TLS_client_method();
#elif defined(LWS_HAVE_TLSV1_2_CLIENT_METHOD)
	method = (SSL_METHOD *)TLSv1_2_client_method();
#else
	method = (SSL_METHOD *)SSLv23_client_method();
#endif
```

It looks like on your system cmake found `TLS_client_method()` which is the most modern version, and declared LWS_HAVE_TLS_CLIENT_METHOD.  But when we try to compile it, `TLS_client_method()` is somehow not existing.  The related cmake stuff is

```
CHECK_FUNCTION_EXISTS(TLS_client_method LWS_HAVE_TLS_CLIENT_METHOD)
CHECK_FUNCTION_EXISTS(TLSv1_2_client_method LWS_HAVE_TLSV1_2_CLIENT_METHOD)
```

Cmake learning if the function exists first should be enough.

libressl 2.2.7 is old, the latest is 2.7.2.  You can try upgrading that, then delete build/CMakeCache.txt and try again.

**Comment by lws-team** [comment]
I don't use mac and don't know what this keg-only stuff is... delete build/CMakeCache.txt and run cmake again, pasting the console info here.

**Comment by Triuman** [comment]
You can see the log in the link below.

[https://gist.github.com/Triuman/b4d5c9f5ac8e12568329cdf478b1d959](url)

**Comment by Triuman** [comment]
I installed OpenSSL from master. Now I am able to make libwebsockets. But on 'sudo make install', I get this error:

Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/pkgconfig/libwebsockets.pc
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/Users/tracer/libwebsockets/build/libwebsockets.pc" to
  "/usr/lib/pkgconfig/libwebsockets.pc".
make: *** [install] Error 1

**Comment by lws-team** [comment]
Does /usr/lib/pkgconfig/ exist?  If not maybe `mkdir -p` it.

**Comment by Triuman** [comment]
Yes, it exists.

**Comment by lws-team** [comment]
Does "/Users/tracer/libwebsockets/build/libwebsockets.pc" exist?  If so then why can't it be copied?  Permissions on the destination dir?

**Comment by Triuman** [comment]
Yes, it exists too. I have no idea. I will try to copy it myself even though I think it will not keep make from giving same error.

**Comment by Triuman** [comment]
I got 'Operation not permitted' error. :/

**Comment by Triuman** [comment]
I finally fixed all problems. Last problem was about installing to /usr folder instead /usr/local. So I changed my cmake commad to:

> OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig  cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_C_FLAGS="-fpic" ..

Now it is installed without any problem. Thank you very much for your effort.
