### ISSUE TITLE
SHA and md5 calculation for yocto build

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1234]
SUMMARY = "Canonical libwebsockets.org websocket library"
HOMEPAGE = "https://libwebsockets.org/"
LICENSE = "LGPL-2.1"
LIC_FILES_CHKSUM = "file://LICENSE;md5=e3393a657830d4a118c5a6ed35ba53d0"

DEPENDS = "zlib"

SRC_URI = "https://github.com/warmcat/libwebsockets/archive/v${PV}.tar.gz"

SRC_URI[md5sum] = "4df3be57dee43aeebd54a3ed56568f50"
SRC_URI[sha256sum] = "bcc96aaa609daae4d3f7ab1ee480126709ef4f6a8bf9c85de40aae48e38cce66"

The above is the yocto recipe for libwebsockets2.1.0,

**Comment by arunkvnss** [comment]
How to find out the same for libwebsocket 2.2.0 ?

**Comment by lws-team** [comment]
Not sure why that is anything to do with me...

$ wget -O/tmp/v2.2.0.tar.gz https://github.com/warmcat/libwebsockets/archive/v2.2.0.tar.gz && md5sum /tmp/v2.2.0.tar.gz && sha256sum /tmp/v2.2.0.tar.gz
