### ISSUE TITLE
`void *user` in callback is always NULL

### ISSUE THREAD

**Issue by bterrier** [warmcat/libwebsockets#1235]
I use the following code:

    lws_protocols protocols[3] = {
        {
               "http-only", 
               &MyClass::static_http_callback,
               0,
               0, 
               0,
               this
        },
        {
               "example-protocol",
               &MyClass::static_callback,
               0,
               0,
               0,
               this
        },
        { 0, 0, 0, 0, 0, nullptr }
    };

    lws_context_creation_info info = lws_context_creation_info();
    info.port = 8080;
    info.protocols = protocols;
    info.gid = -1;
    info.uid = -1;
    info.vhost_name = "localhost";
    info.user = this;
    context = lws_create_context(&info);
    int n = 0;
    while (n >= 0)
        n = lws_service(context, 1000);

It works as I can connect from a client and send/receive text messages.
However, whenever a callback is called, the `user` parameter is always `0`.
I would expect to have it set to `this`.

**Comment by lws-team** [comment]
They are different animals.

You can get a **per-connection** heap allocation in the user parameter of most callbacks, by filling in the size you want in struct lws_protocols.  That is usually what 'user" wants to be for a server, in the language of the examples and test apps it's a "pss".

If you just want to pass in a single external pointer, which is always the same, you can do what you are doing, but you need to use an accessor... it's not the same animal as is passed in to the callback `user`.

```
/**
 * lws_context_user() - get the user data associated with the context
 * \param context: Websocket context
 *
 * This returns the optional user allocation that can be attached to
 * the context the sockets live in at context_create time.  It's a way
 * to let all sockets serviced in the same context share data without
 * using globals statics in the user code.
 */
LWS_VISIBLE LWS_EXTERN void *
lws_context_user(struct lws_context *context);
```

**Comment by bterrier** [comment]
Thank you for the fast reply!

May I suggest to clarify the documentation.
The current for `lws_protocols` is not clear enough:

> void* lws_protocols::user
> ignored by lws, but user code can pass a pointer here it can later access from the protocol callback

Especially because one would expect 2 `void *user` variables to be related. And the fact that these 2, actually unrelated, variables are both internally stored in 2 `void *user_space` variables does not help either.

NB: The documentation of `lws_context_creation_info::user` is clear enough, but I started to look at `lws_protocols::user` first, because that is where the callbacks are set.

**Comment by lws-team** [comment]
If you are concerned about the documentation, feel free to send a patch.
