### ISSUE TITLE
CMake config ?

### ISSUE THREAD

**Issue by SiwonP** [warmcat/libwebsockets#1236]
Hello everybody !

I intend on using the libwebsockets library for a project (in C). 
I successfully built the library with CMake, but now when I try to compile my project I get the error 
```
/usr/local/include/libwebsockets.h:202:10: fatal error: 'openssl/ssl.h' file not found
```
I'm on macOS, using CMake version 3.9.2, OpenSSL 1.0.2n

What should I write in my CMakeLists.txt (Or flags for cmake) so that it finds this file ?

Thank you

**Comment by lws-team** [comment]
Hmmm if I understand it, this is nothing to do with cmake, or lws; lws built fine but you talk now about building your own app, without cmake.

You need to compile your project with information about where the openssl headers live.

For example (I have no idea where they go on a mac) if they were installed in /opt/openssl/include, you would need to put -I/opt/openssl/include on your compiler commandline.

**Comment by SiwonP** [comment]
Thank you for answering !
With a gcc [+FLAGS] command line, I made it work. I just can't find the right config for cmake, which I'm used to (It keeps my project "cleaner").

**Comment by JoakimSoderberg** [comment]
@SiwonP you should not edit `CMakeLists.txt`.

By default **CMake** will attempt to find OpenSSL:
https://github.com/warmcat/libwebsockets/blob/c271a95ca5b6461f76f369d101dca54cc8fae096/CMakeLists.txt#L1205

But on some systems it fails to find it for reasons... But in the Libwebsocket you can also manually supply these paths:
https://github.com/warmcat/libwebsockets/blob/c271a95ca5b6461f76f369d101dca54cc8fae096/CMakeLists.txt#L325-L326

```
cd <source dir>
mkdir build && cd build
cmake -DLWS_OPENSSL_LIBRARIES=/path/to/openssl.so -DLWS_OPENSSL_INCLUDE_DIRS=/path/to/open/ssl/include ..
make
```

Note the include dir should point to

**Comment by JoakimSoderberg** [comment]
... the include dir should point to the directory where the openssl dir is located, so if it's `/bla/openssl/ssl.h`. Then it should be `/bla`

**Comment by SiwonP** [comment]
@JoakimSoderberg, Thank you, I'mma try that ASAP !

**Comment by JoakimSoderberg** [comment]
oh I see now, I misunderstood the question. The error was not when building Libwebsockets, but rather your own application.

If you are using CMake to build your own application, look into `find_package` and OpenSSL...

Looking at a simpler project rather than Libwebsockets that has a huge file supporting multiple SSL libs might be a good idea to understand the entire chain.

**Comment by lws-team** [comment]
Thanks Joakim.  The OP edited his comment while we were replying... it's not actually related to lws just 'how to use cmake + openssl on a mac'.  Google knows...

**Comment by SiwonP** [comment]
Actually, it does find OpenSSL : 
```
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib
```
But the compiling error appears anyway

**Comment by lws-team** [comment]
https://cmake.org/cmake/help/v3.0/command/include_directories.html
