### ISSUE TITLE
_client_handshake: got bad HTTP response '101'

### ISSUE THREAD

**Issue by lalittmt** [warmcat/libwebsockets#1238]
Hello All
when we try to run "libwebsockets-test-echo --client echo.websocket.org" we get bad response error.
Please help me how to solve this issue

**Comment by lws-team** [comment]
Just update your lws.

For a few hours a few days ago master had a bug caused by refactoring, I was sent a fix which was applied the next morning

https://github.com/warmcat/libwebsockets/commit/17be89e64dba52d1b6fd472073612c8e82d91d87
