### ISSUE TITLE
How to send message to all connect web socket client 

### ISSUE THREAD

**Issue by lalittmt** [warmcat/libwebsockets#1242]
Hello All,
I want to send a same message from the server to multiple clients.I am able to send a message to one client at a time.
How to send to multiple clients at a time?
Please Help.

**Comment by lws-team** [comment]
Have a look at the minimal examples

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples

Eg,

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/ws-server/minimal-ws-server-ring
