### ISSUE TITLE
Can't build on Darwin

### ISSUE THREAD

**Issue by jjbailey** [warmcat/libwebsockets#1243]
Hello,

I'm trying to build 2.4 on Darwin.

macbook> uname -a
Darwin macbook.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

macbook> make
...
[ 21%] Building C object CMakeFiles/websockets.dir/lib/ssl-client.c.o
/Users/jjb/Git/passages-websocket/c-websocket/libwebsockets/lib/ssl-client.c:426:25: error:
      implicit declaration of function 'TLS_client_method' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        method = (SSL_METHOD *)TLS_client_method();
                               ^
/Users/jjb/Git/passages-websocket/c-websocket/libwebsockets/lib/ssl-client.c:426:25: note: 
      did you mean 'DTLS_client_method'?
/usr/local/include/openssl/ssl.h:2389:19: note: 'DTLS_client_method' declared here
const SSL_METHOD *DTLS_client_method(void); /* DTLS 1.0 and 1.2 */
                  ^
/Users/jjb/Git/passages-websocket/c-websocket/libwebsockets/lib/ssl-client.c:426:11: error:  
      cast to 'SSL_METHOD *' (aka 'struct ssl_method_st *') from smaller integer type 'int'
      [-Werror,-Wint-to-pointer-cast]
        method = (SSL_METHOD *)TLS_client_method();
                 ^
2 errors generated.
make[2]: *** [CMakeFiles/websockets.dir/lib/ssl-client.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2

Trying the previous releases from newest to oldest, I found libwebsockets-2.2.1 builds cleanly.

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/issues/1227
