### ISSUE TITLE
question: is there documentation on handling basic auth in a lws server?

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#1244]
I look and google and google and look and all I can find is a member in lws_http_mount called this:
basic_auth_login_file

I just need to add basic auth validation to the initial https connection to my lws server, but I don't see where to plug it in. Which callback should handle that?

It is just a matter of looking through the headers in the LWS_CALLBACK_ESTABLISHED callback and parsing out the auth header?

Thanks for any pointers you can provide.
I tried to look through the doxygen docs, but if there's a way to search it other than getting google to, I didn't see it.

**Comment by lws-team** [comment]
`git grep Basic`

**Comment by lws-team** [comment]
In other words, everything in doxygen comes from the sources.  Searching the sources is searching doxygen.

Here's a minimal example demonstrating how to use basic auth programmatically.

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-basicauth

**Comment by nixomose** [comment]
Thanks kindly. My grepping didn't yield me that. I'll check it out.

**Comment by lws-team** [comment]
I just added it :-)
