### ISSUE TITLE
EventSource wont work with libwebsockets https server 

### ISSUE THREAD

**Issue by HDKLog** [warmcat/libwebsockets#1246]
Hello.
I tried to use  libwebsockets https server with EventSource protocol with no success. All I get in console is
`
NOTICE:  forbidding on uri sanitation 
NOTICE: lws_return_http_status: return
`

library doesn't call protocol callback with LWS_CALLBACK_ESTABLISHED or LWS_CALLBACK_RECEIVE.

in index.htm i just simply call `var stream = new EventSource("/xiot");`. Does libwebsockets work with EventSource protocol? I Didn't found any example.

**Comment by lws-team** [comment]
Although Server Side Events are pure http, they don't "just work" on a webserver.  You have to return a magic `content-type` and follow some other simple formatting rules.  So "Eventsource won't work with lws" is not what is going on.  Your lws server just hasn't been configured to do it.

Here are two "minimal examples" (you need current master) that show how to do it, one as simple as possible the other with a ringbuffer and threads feeding events into it.  Whether you enable tls or not on the server doesn't change anything about SSE.

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-sse
https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-server/minimal-http-server-sse-ring
