### ISSUE TITLE
a bug when using http proxy 

### ISSUE THREAD

**Issue by bobbybin** [warmcat/libwebsockets#1247]
the http_proxy_address : /* If proxy auth is required, use format "username:password\@server:port" */
if password contains the character ‘@’, the function lws_set_proxy will get the wrong authstring and proxy address, for example : "test:1qaz@WSX@10.11.10.11"
"p = strchr(proxy, '@');" should be "p = strrchr(proxy, '@');"

**Comment by lws-team** [comment]
Thanks, I pushed a patch doing that on v2.4-stable and master.
