### ISSUE TITLE
Setting CMAKE_C_FLAGS causes a semicolon to get inserted by CMake in the build command

### ISSUE THREAD

**Issue by skyhisi** [warmcat/libwebsockets#1252]
Just seen the "Next lws release coming up" email so I've actually tried building!

When setting `CMAKE_C_FLAGS` the build command gets an extra semicolon added after `-O3` e.g if `CMAKE_C_FLAGS=-Wno-error` the build command has `-O3;-Wno-error`. This prevents the compile from working as the rest of the command line is truncated after the `;`.

I think this is due to how CMake makes lists out of things:
https://cmake.org/Wiki/CMake:VariablesListsStrings

Fix is to put the variable within the quotes:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 517ea33a..16868538 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -997,9 +997,9 @@ if (CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX OR (CMAKE_C_COMPILER_ID
     endif()
 
     if (CMAKE_BUILD_TYPE MATCHES "DEBUG")
-       set(CMAKE_C_FLAGS "-O0" ${CMAKE_C_FLAGS})
+       set(CMAKE_C_FLAGS "-O0 ${CMAKE_C_FLAGS}")
     else()
-       set(CMAKE_C_FLAGS "-O3" ${CMAKE_C_FLAGS})
+       set(CMAKE_C_FLAGS "-O3 ${CMAKE_C_FLAGS}")
     endif()
 
     if (UNIX AND NOT LWS_WITH_ESP32)
```

Thanks,
Silas

**Comment by lws-team** [comment]
Thanks a lot, it's pushed on master.
