### ISSUE TITLE
minimal-ws-server-threads example dropping when client connection lost 

### ISSUE THREAD

**Issue by lalittmt** [warmcat/libwebsockets#1254]
Hi,
We are facing a problem when I run minimal-ws-server-threads (server) client is ruling on other side communication works well for(multi-client).But, when from this anyone client is a connection is lost in function lws_ring_get_count_free_elements gives "dropping"  and sever not able to send messages to other client's. 
Please, Help how to resolve this issue??

**Comment by lws-team** [comment]
I understand... I'll study this tomorrow.

**Comment by lalittmt** [comment]
Hi,
did you find any solution on this?

**Comment by lws-team** [comment]
I started on it earlier today.  After spending the entire week on one lws thing or another.

If you want to send a patch though, feel free.

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/ws-server/minimal-ws-server-ring/protocol_lws_minimal.c

shows how to do it.
