### ISSUE TITLE
[HTTP] POST keep-alive operations and low-latency POST operations

### ISSUE THREAD

**Issue by ecionis** [warmcat/libwebsockets#1256]
Hi,

1. I want do low-latency POST operations = operation with one send function (without lws_client_http_body_pending+lws_callback_on_writable)

example:        
`
case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
{
            char *&p = (char*&)(*(char**)in); 
            p += sprintf(p, "content-length: %d\r\n" 
                            "content-type: application/x-www-form-urlencoded\r\n\r\ntext=1234&send=Send+the+form" , 28); 
break;
}`

but after this, program does: `p += sprintf(p, "\x0d\x0a");` at lws_generate_client_handshake().
May be change this line to `if(p[-2]=='\r' && p[-1]=='\n') p += sprintf(p, "\x0d\x0a");`

2. Current version dont work with method POST and keep-alive connection
I changed at lws_client_connect_2 two lines:

a. `if (meth && strcmp(meth, "GET")` to `if (meth && strcmp(meth, "GET") && strcmp(meth, "POST"))`
b. `if (meth && !strcmp(meth, "GET")` to `if (meth && (!strcmp(meth, "GET")||!strcmp(meth, "POST")) `

and it works..buy i dont know, its correct or not.

What do you think about it?

**Comment by lws-team** [comment]
Yes what you did is great.

I added it on master and adapted `minimal-http-client-post` to have a -m flag that issues 4 x client POSTs at once... this works on http/1.1 pipelined, and h2 in parallel.  On http/1.0 lws detects the lack of keepalive header and will do them entirely sequentially in four connections.
