### ISSUE TITLE
Illegal back-to-back write on HTTP dummy protocol

### ISSUE THREAD

**Issue by galuha** [warmcat/libwebsockets#1257]
Greetings. We are getting "Illegal back-to-back write"  on HTTP dummy protocol. According to documentation, the meaning of this is that "lws_write got called twice without going through the event loop". But we didn't touch the http dummy protocol. And our protocol code does call lws_write only once in a callback and doesn't call outside.

We have used template from libwebsockets/minimal-examples/ws-server/minimal-ws-server-ring
```
[libwebsockets]# git show
commit a2210d1bb158ebedee41aacf0f3475432b392c55 (HEAD -> master, origin/master, origin/HEAD)
Author: Andy Green <andy@warmcat.com>
Date:   Fri Apr 6 12:10:14 2018 +0800

ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: _write returned -1 from 139
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0000: 48 54 54 50 2F 31 2E 31 20 34 30 34 20 4E 6F 74    HTTP/1.1 404 Not
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0010: 20 46 6F 75 6E 64 0D 0A 63 6F 6E 74 65 6E 74 2D     Found..content-
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0020: 74 79 70 65 3A 20 74 65 78 74 2F 68 74 6D 6C 0D    type: text/html.
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0030: 0A 63 6F 6E 74 65 6E 74 2D 6C 65 6E 67 74 68 3A    .content-length:
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0040: 20 33 38 0D 0A 0D 0A 3C 68 74 6D 6C 3E 3C 62 6F     38....<html><bo
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0050: 64 79 3E 3C 68 31 3E 34 30 34 3C 2F 68 31 3E 3C    dy><h1>404</h1><
ESC[0mESC[31;1m[2018/04/27 09:43:19:2013] ERR: 0060: 2F 62 6F 64 79 3E 3C 2F 68 74 6D 6C 3E             /body></html>   
ESC[0mESC[31;1m[2018/04/27 09:43:19:2014] ERR: 
ESC[0mESC[31;1m[2018/04/27 09:43:19:2014] ERR: ** 0x25be620: vh: default, prot: http, Illegal back-to-back write of 109 detected...
ESC[0mESC[35;1m[2018/04/27 09:43:19:2830] NOTICE: error on reading from skt : 104
```

**Comment by galuha** [comment]
At first everything works fine. But after several days of server running this error is starting to appear

**Comment by galuha** [comment]
Ok, this was a hosting provider issue.

**Comment by lws-team** [comment]
What was the 'hosting provider issue' do we know?

**Comment by galuha** [comment]
We have noticed that error appeared only when we tried to connect from Russia.
We have moved this service from AWS to another server and it helped. While in AWS it was working only from outside Russia.
Looks like because of war between Telegram and Rospotrebnadzor (Russian law enforcement) our AWS server ip got banned from Russia by mistake. 20000000 ip's were banned recently

**Comment by lws-team** [comment]
I see, thanks for the info.  I guess it still boils down to some path in lws that need fixing, that whatever the extra proxying does triggers.  But if it's always a 404 is the second element, I guess it doesn't make much trouble (lws hangs up on the connection, provoking a "can't connect" type page in the browser instead of deliver the 404).
