### ISSUE TITLE
How to get http request method?

### ISSUE THREAD

**Issue by yonzkon** [warmcat/libwebsockets#1261]
I want to get the http request method, like "GET" or "POST" or "DELETE".
I have tried most of lws_token_indexes, but failed to find the proper one.

**Comment by lws-team** [comment]
One of `WSI_TOKEN_GET_URI`, `WSI_TOKEN_POST_URI` etc will have the uri, you can know the method from that.

For h2, `WSI_TOKEN_HTTP_COLON_METHOD` has it literally, eg, "get" etc.

**Comment by alexeadem** [comment]
Any reason why this in private.h
`lws_http_get_uri_and_method`

The thing about using the WSI_TOKEN_GET_URI & WSI_TOKEN_POST_URI is that a POST request can container tokens as an in a GET method.

I was wondering  how we can get the methods type as in 

onst char * const method_names[] = {
	"GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE", "CONNECT", "HEAD",

**Comment by lws-team** [comment]
I pushed a patch on master making this public since it does look generally useful.

When the uri is parsed, urlargs are parsed out separately regardless of the method and can be accessed via, eg, `lws_get_urlarg_by_name()`

**Comment by alexeadem** [comment]
you rock thx
