### ISSUE TITLE
Need support for modifying JSON data which is parsed by lejp

### ISSUE THREAD

**Issue by alisha22** [warmcat/libwebsockets#1264]
Hi,
I am trying to use libwebsockets/lib/misc/lejp.c to parse JSON files for my own purposes. 
What I really need to do in a scenario is for example, if my file contains the following

          {"Person1" : { "name":"ABC", "age":31, "city":"New York" }}

and the object "Person1" has been updated to the following

          {"Person1" : { "name":"ABC", "age":32, "city":"New York" }}

I want to parse the file 
and simply insert the updated data at the path Person1.
This is a simplistic scenario, my objects are of course nested.

Is there any way to do that using lejp?

**Comment by lws-team** [comment]
It's not really directly designed for it, it's just designed to stream-parse JSON.

You could hack something together with two lejp contexts that parse the old and new, and discover any difference and try to understand that until the "path" inside the JSON becomes the same again, ie, until both parsing contexts reached the end of "person 1" and we can understand those changes are finished.

But it's not that simple, you have to try to understand if a whole new record was inserted for example, or just records changed.  Maybe the changes that are possible are very constrained in your use-case.
