### ISSUE TITLE
crash in test-server-libevent when close the connectted websocket client

### ISSUE THREAD

**Issue by csy2002** [warmcat/libwebsockets#1268]
start the test-server-libevent program ,listen on 7681 port ; use websocket client can connect to server in browser, but program crash when close the connectted websocket client;
stack info:
libwebsockets-test-server-libevent.exe!lws_service_fd_tsi(lws_context * context=0xfeeefeeefeeefeee, lws_pollfd * pollfd=0x000000d6a8fded38, int tsi=0) Line 973
libwebsockets-test-server-libevent.exe!lws_service_fd(lws_context * context=0xfeeefeeefeeefeee, lws_pollfd * pollfd=0x000000d6a8fded38) Line 1701
libwebsockets-test-server-libevent.exe!lws_event_cb(__int64 sock_fd=440, short revents=4, void * ctx=0x000000d6ab3d8080) Line 64
event.dll!event_persist_closure(event_base * base=0x000000d6a9212fc0, event * ev=0x000000d6ab3d82c0) Line 1581
event.dll!event_process_active_single_queue(event_base * base=0x000000d6a9212fc0, evcallback_list *        activeq=0x000000d6a9215140, int max_to_process=2147483647, const timeval *    
endtime=0x0000000000000000) Line 1640
event.dll!event_process_active(event_base * base=0x000000d6a9212fc0) Line 1739
event.dll!event_base_loop(event_base * base=0x000000d6a9212fc0, int flags=0) Line 1961
event.dll!event_base_dispatch(event_base * event_base=0x000000d6a9212fc0) Line 1773
libwebsockets-test-server-libevent.exe!main(int argc=1, char * * argv=0x000000d6a9212ec0) Line 337	[External Code]	

libevent version：v2.1.8
libwebsocket version: v2.4.2

it maybe don't remove w_read.event_watcher and w_write.event_watcher object before free wsi object;

**Comment by csy2002** [comment]
os: windows

**Comment by lws-team** [comment]
Is master acting any differently?

**Comment by csy2002** [comment]
the master ok;

**Comment by lws-team** [comment]
Great.
