### ISSUE TITLE
inline problem and others

### ISSUE THREAD

**Issue by ecionis** [warmcat/libwebsockets#1269]
Hi,

Please, change all inline (at *.h) to LWS_INLINE

I founded at:
core\private.h
libwebsockets.h

ps. and wrong place of definition lws_usec_t t; at _lws_plat_service_tsi/lws-plat-win.c (in the middle of C code function)

**Comment by lws-team** [comment]
It'd be nice if windows would use the standard names and provide the standard things :-)

I fixed the things you mentioned in a patch on v3.0-stable and master.
