### ISSUE TITLE
Ran out of header data space

### ISSUE THREAD

**Issue by pokal4u** [warmcat/libwebsockets#1270]
HI,

I am getting error like "Ran out of header data space" when I try to connect mqtt with websockets.

Please explain what is this error.

Can anybody help me here

Thanks

**Comment by lws-team** [comment]
Literally what it says, more headers are coming than it could store.

Set `info.max_http_header_data` to something suitable when creating the lws context.  It defaults to 4096 on recent lws which should be enough.

**Comment by lws-team** [comment]
... you are connecting to something that actually speaks ws and not mqtt, right...?

**Comment by pokal4u** [comment]
yes, but I am working on test server, checking with two users only. So how can we get more headers

**Comment by lws-team** [comment]
Read my first reply...

**Comment by pokal4u** [comment]
OK, I will check conf file, and one more thing when I clear browser cache then working fine

**Comment by lws-team** [comment]
😓

**Comment by lws-team** [comment]
... or turn up lws logging to see exactly what it received for headers...

**Comment by pokal4u** [comment]
ok thanks you

**Comment by lws-team** [comment]
@iblender You can control it at context creation time with `info.max_http_header_data`

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n363-365

**Comment by iblender** [comment]
@lws-team Is there a location or specific file I can check? Im using an API which comes with lws so i haven't set this up myself but the header limit is stopping it from functioning properly for what i want it to do.
