### ISSUE TITLE
Question about retreiving non standard headers in a lws server.

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#1278]
The docs for LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION say...

"...you can use the public APIs lws_hdr_total_length() / lws_hdr_copy() to access all of the headers using the header enums lws_token_indexes from libwebsockets.h to check for and read the supported header presence and content..."

The implication is that it is not possible to get non-standard headers. Is that true? Is there no way at all to get non-standard headers from the web request?

I saw another note saying I could add a header of my own and rebuild the library. Is that the only option?

Thanks.

**Comment by nixomose** [comment]
let me know if there's some easier magic, but I ended up just adding my custom header to the lex files and went that route.

**Comment by lws-team** [comment]
That's the right move... it's not really so much standard / non-standard headers as 'one the parsing tables were built to understand' or not.  If not, the header will be ignored.

If your header has meaning for others and isn't completely random it can be included in lws.

**Comment by nixomose** [comment]
I added this: X-Client-S-DN
If you think it useful, I'll open a pull request.
