### ISSUE TITLE
lws_service(context, -1) is not working in test-client.cpp

### ISSUE THREAD

**Issue by sgawarikar** [warmcat/libwebsockets#1280]
Hi,

I want to block until an event occurs. I just change the timeout_ms from 500 to -1 in lws_service() of test-client.cpp and then compile and run it. So Verified the wireshark and found that the tcp connection is established but it is not creating the ws connection by sending ws packet on the tcp connection.

Am I doing something wrong?

**Comment by lws-team** [comment]
> Am I doing something wrong?

Yeah... you can't wait forever in the poll wait.  Timeouts and some other periodic processing have to come out of the wait at least once every 1s, even on a completely idle system.

That is why on every minimal example using poll wait, it shows 1000 (ms).

You can't do what you're doing anyway...
