### ISSUE TITLE
How to build libwebsockets with boringSSL?

### ISSUE THREAD

**Issue by jiangguoding** [warmcat/libwebsockets#1284]
Is there any document about building libwebsocktes using boringSSL on android? 
Please help list the detailed steps,  Thanks.

I successful compile OK.  but can not pass the SSL verification.
sad...

**Comment by jiangguoding** [comment]
error infomation:

8297(s):689(ms)--->   connected

8297(s):689(ms)--->   lws_set_timeout: 0xab533420: 20 secs

8297(s):689(ms)--->   lws_ssl_get_error: 0xab533668 -1 -> 2 (errno 11)

8297(s):727(ms)--->   lws_ssl_get_error: 0xab533668 -1 -> 1 (errno 0)

8297(s):727(ms)--->   lws_ssl_client_connect2: SSL_connect says -1

8297(s):727(ms)--->   closing conn at LWS_CONNMODE...SERVER_REPLY

8297(s):727(ms)--->   reason: lws_ssl_client_connect2 failed

**Comment by lws-team** [comment]
I have built lws with BoringSSL on OP-TEE... it worked fine.

BoringSSL IS OpenSSL with some hacks on it, so it should have no problem working.

It looks like you are trying a client connect over tls.

The get_error information is first SSL_ERROR_WANT_READ which is fine, and erro is 11 = EAGAIN which matches.

But then it is SSL_ERROR_SSL.  So I guess the problem is around certificates / CA setup.

**Comment by jiangguoding** [comment]
Thanks for your help! 
for lws_config.h:   I define the following to macro, is it OK?    or only one is OK?
#define LWS_WITH_BORINGSSL
#deinfe LWS_OPENSSL_SUPPORT

**Comment by jiangguoding** [comment]
I generate the lws_config.h file by the following step:
  1.  on ubuntu PC:   use LWS_OPENSSL_SUPPORT  in CMakefile.txt,  the cmake ---> generate  lws_config.h
  2.  modify  lws_config.h (from step1),  add LWS_OPENSSL_SUPPORT

**Comment by jiangguoding** [comment]
certificates file is OK.   because it can pass verification by using  Javascript websocket.

**Comment by lws-team** [comment]
You would have bigger problems if lws wasn't talking to boringssl OK.  lws + boringssl is talking to the server, getting something back and then complains.

> certificates file is OK. because it can pass verification by using Javascript websocket.

No I mean your client must have one or more CA cert it was told to trust.  Otherwise it can't judge the certs the server gave it.  The problem sounds like it's from that direction.

**Comment by jiangguoding** [comment]
#define SSL_CERT_CA_FILE_NAME "/data/local/tmp/aaa.crt"

int use_ssl = LCCSCF_USE_SSL | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;

int ws_init_context(char * url) 
{
  
    static char ssl_ca_path[256] = SSL_CERT_CA_FILE_NAME;
    struct lws_context_creation_info info;

 
    memset(&info, 0, sizeof(info));

    info.port = CONTEXT_PORT_NO_LISTEN;
    info.iface = _interface;
    info.protocols = protocols;
  
    if (use_ssl) {

        info.ssl_ca_filepath = ssl_ca_path; 
        info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    } 
    
    info.gid = -1;
    info.uid = -1;

    info.options |=  LWS_SERVER_OPTION_VALIDATE_UTF8;
    info.ws_ping_pong_interval = 30;  //30S 
    g_ws_context = lws_create_context(&info);
    if (g_ws_context == NULL) 
    {
         return RET_FAIL;
    }

    return RET_OK;


}


int ws_connect_server()
{


    char ads_port[286];
    const char *connect_protocol = NULL;
    char ws_uri[128] = {0};
    struct lws *wsi;

    struct lws_client_connect_info con_info;

    lwsl_notice("---ws_connect_server to %s:%u....\n",
            ws_address, ws_port);
  
    memset(&con_info, 0, sizeof(con_info));

    con_info.context = g_ws_context;
    con_info.address = ws_address;
    con_info.port = ws_port;
    con_info.ssl_connection = use_ssl;
    con_info.path = ws_uri;
    con_info.host = ads_port;
    con_info.origin = ads_port;
    con_info.protocol = connect_protocol;

    wsi = lws_client_connect_via_info(&con_info);
    if (!wsi) {
        lwsl_err("Client failed to connect to %s:%u\n",
             ws_address, ws_port);

    
        return RET_FAIL;
    }

    return RET_OK;

}

**Comment by jiangguoding** [comment]
It is very simple modification test from test-client.c.

**Comment by lws-team** [comment]
I don't have time to debug your platform, I have my own stuff to do.

On a PC, OpenSSL installs a trusted CA cert bundle and uses that.

On android, there will be some kind of system trust store for trusted CAs.  BoringSSL probably has no idea about it.

If you mean you are giving it the CA cert explicitly above that's good but make sure the PEM cert you give it also has any necessary intermediate certs appended.

**Comment by jiangguoding** [comment]
You mean:  warmcat/libwebsocket support PEM file only?
I change to PEM file,  it is the same failure.

------------------------------------------------------------------------------------------------------
On ubuntu PC,    I compile libwebsocket using OpenSSL,   and supply same .crt file.  It works well.

**Comment by lws-team** [comment]
... PEM is a format.  Your .crt file is PEM.

Lws doesn't care about it, it gives the job to the tls library.  They support PEM.

That's nothing to do with the problem.

**Comment by jiangguoding** [comment]
any thing to do with the error?   (the first one you say it is ok).
4770(s):325(ms)--->   lws_ssl_get_error: 0xab099728 -1 -> 1 (errno 0)

how to open SSL debug log function to see the  verification flow  in libwebsocket?

**Comment by lws-team** [comment]
Increase lws log level.  Normally that's -DCMAKE_BUILD_TYPE=DEBUG ... but I don't know how you build.  If not via cmake also try adding _DEBUG definition to the compiler commandline.

Then set the debug log level to, eg, 1151

**Comment by lws-team** [comment]
BoringSSL *is* openssl.  Just set it in lws cmake as if it was openssl.  You can also set LWS_WITH_BORINGSSL=1 as well.  But IIRC it just makes lws log "boringssl" instead of "OpenSSL".
