### ISSUE TITLE
lws_timingsafe_bcmp only compares first byte of buffers

### ISSUE THREAD

**Issue by skyhisi** [warmcat/libwebsockets#1288]
Just noticed this while looking through some of the sources, it appears (I haven't tested this) that the `lws_timingsafe_bcmp` function is only comparing the first byte of the buffers.

I think the sum calculation line is missing a `++` after the pointers.

https://github.com/warmcat/libwebsockets/blob/0d787fa312017d3cbe167bb07f812de2e4608c7d/plugins/ssh-base/sshd.c#L106

**Comment by lws-team** [comment]
Damn... not good... it's fixed on v2.4-stable, v3.0-stable and master (and libwebsockets.org).

Thanks for pointing it out.
