### ISSUE TITLE
Using libwebsocket  version 2.0 but have issue in voice quality can you help how to set TCP_NODELAY  

### ISSUE THREAD

**Issue by joicepj11** [warmcat/libwebsockets#1289]

**Comment by joicepj11** [comment]
in android, I am using libwebsocket library and cross-compiling for all platform for VoIP application we are having voice quality issue, due to latency can suggest what are parameters I need provide to avoid latency

**Comment by lws-team** [comment]
You need to debug where the latency is coming from.  And explain the problem clearly.

 - Why does this seem related to lws particularly?  It just uses poll() there's nothing to make it wait around once it understands an fd is active.

 - Latency problem is on rx, tx or both?

 - How are you measuring it?

 - Where does the audio come from, a file or something else?  v2.0 is tool old to have raw file support... so how are you making lws understand a new chunk of audio is available?

**Comment by joicepj11** [comment]
Why does this seem related to lws particularly? It just uses poll() there's nothing to make it wait around once it understands an fd is active.
- when we are using raw TCP/UDP protocol we are not observing latency issue however when we are using libwebsocket we are observing the latency, so we suspected some configuration/parameters we missed

Latency problem is on rx, tx or both?
-Latency problem is only on tx 

How are you measuring it?
- we are measuring latency by putting the timestamp whenever the packet is sent originator, and receiver side we will note down the timestamp 

Where does the audio come from, a file or something else? v2.0 is tool old to have raw file support... so how are you making lws understand a new chunk of audio is available?
- audio is captured directly by the device and sent to receiver for every 25ms and 200bytes 

do we need to set any size for variable protocol.tx_packet_size and protocol.rx_buffer_size during init time?

**Comment by lws-team** [comment]
> when we are using libwebsocket we are observing the latency

A lot of things changed at the same time when you use lws.  For example the way your code is integrated.  As you saw with Nagle just guessing the problem doesn't help.

> we are measuring latency by putting the timestamp whenever the packet is sent originator, and receiver side we will note down the timestamp

So, what kind of latencies are observed?  For each direction, rx and tx.

> audio is captured directly by the device and sent to receiver for every 25ms and 200bytes

So "captured directly by the device" means what?  There is a file in /dev and 8kHz / 8-bit audio is coming if you read it?  You should measure how long you spend waiting in that read() if so.

How does lws 'know' it should check that file or whatever it is at 40Hz?
