### ISSUE TITLE
lws_latency caused crash 

### ISSUE THREAD

**Issue by macong-earth** [warmcat/libwebsockets#129]
After updating to latest commit dfca3ab, libwebsocket crashed in lws_latency()

unsigned long long u;

sprintf(buf,  "Completion first try lat %luus: %p: ret %d: %s\n",
	u - wsi->latency_start, (void *)wsi, ret, action);

%lu means unsigned long int , but the variable (u - wsi->latency_start) passed in is unsigned long long int.

**Comment by warmcat** [comment]
Thanks... it was fixed a while back.
