### ISSUE TITLE
incorrect time_in_microseconds and win os

### ISSUE THREAD

**Issue by ecionis** [warmcat/libwebsockets#1297]
Hi,

file: lws-plat-win.c, function: time_in_microseconds

/* Windows file times are in 100s of nanoseconds. */

`
return (datetime.QuadPart - DELTA_EPOCH_IN_MICROSECS) / 10;
`

may be

`return (datetime.QuadPart/10) - DELTA_EPOCH_IN_MICROSECS;`

**Comment by lws-team** [comment]
Thanks, it's pushed on v3.0-stable and master.
