### ISSUE TITLE
[http] keap-alive wrong headers

### ISSUE THREAD

**Issue by ecionis** [warmcat/libwebsockets#1299]
Hi,

If i use keep-alive connection, program will use headers of first connection always.
but content length is different, and it will become dramatic.

file: roles\http\client\client.c

`
		
		//_lws_header_table_reset(wsi->http.ah); //work around..it works right...at first sight (but dont work with LWS_SSL_CAPABLE_MORE_SERVICE)
		
		len = 1;
		while (wsi->http.ah->parser_state != WSI_PARSING_COMPLETE &&
		       len > 0) {
			int plen = 1;

			n = lws_ssl_capable_read(wsi, &c, 1);
            
			lws_latency(context, wsi, "send lws_issue_raw", n,
				    n == 1);
			switch (n) {
			case 0:
			case LWS_SSL_CAPABLE_ERROR:
				cce = "read failed";
				goto bail3;
			case LWS_SSL_CAPABLE_MORE_SERVICE:
				return 0;
			}

            //putc(c, stdout); //TODO DEL here is good content-length
			if (lws_parse(wsi, &c, &plen)) {
				lwsl_warn("problems parsing header\n");
				goto bail3;
			}
		}

		/*
		 * hs may also be coming in multiple packets, there is a 5-sec
		 * libwebsocket timeout still active here too, so if parsing did
		 * not complete just wait for next packet coming in this state
		 */
		if (wsi->http.ah->parser_state != WSI_PARSING_COMPLETE)
			break;
		
		
		//        printf("!!!--------->%s %016x<------!!!\n", lws_hdr_simple_ptr(wsi,
            WSI_TOKEN_HTTP_CONTENT_LENGTH), wsi); //TODO DEL //here is content-length of first connection
		
`

**Comment by lws-team** [comment]
Please read through https://github.com/warmcat/libwebsockets/issues/1296

**Comment by ecionis** [comment]
I have read. But i am simple http client.  

lws_http_transaction_completed is not available (as i am client)
lws_http_transaction_completed_client is private

**Comment by lws-team** [comment]
Oh... you didn't mention it is client.  Then the server-related thing won't be the reason.

How are you using multiple client connections?  It's like

https://github.com/warmcat/libwebsockets/tree/master/minimal-examples/http-client/minimal-http-client-multi

or some other way?  If the server supports http/1.1 these should be pipelined on one connection (--h1 on the minimal test app).

**Comment by ecionis** [comment]
Yes, its like yours examples. I will call lws_client_connect_via_info after few time after event LWS_CALLBACK_COMPLETED_CLIENT_HTTP. I have seen it at log dump. But http.ah isn't reseted. And body-length (connection 2) was added to prev header. And lws_hdr_simple_ptr(wsi, WSI_TOKEN_HTTP_CONTENT_LENGTH) returned first body-length (connection 1).

**Comment by lws-team** [comment]
OK.  My examples work fine but for simplicity, they just fetch 8 x /, whatever that may be, eg, index.html.

I will add a way they can fetch different files in each stream, like 1.png, 2.png etc.  So they have different names and different content-length.

**Comment by ecionis** [comment]
See 391 and 394 content-length

`

←[32;1m[2018/06/04 01:32:03:7830] INFO: Initial logging level 1039
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO: Libwebsockets version: 3.0.0
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO: IPV6 not compiled in
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO:  LWS_DEF_HEADER_LEN    : 4096
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO:  LWS_MAX_PROTOCOLS     : 5
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO:  LWS_MAX_SMP           : 1
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO:  sizeof (*info)        : 448
←[0m←[32;1m[2018/06/04 01:32:03:7830] INFO:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
←[0m←[32;1m[2018/06/04 01:32:03:7840] INFO:  HTTP2 support         : not configured
←[0m←[32;1m[2018/06/04 01:32:03:7850] INFO: Using event loop: poll
←[0m←[32;1m[2018/06/04 01:32:03:7850] INFO: Default ALPN advertisment: http/1.1
←[0m←[32;1m[2018/06/04 01:32:03:7860] INFO:  default timeout (secs): 20
←[0m←[32;1m[2018/06/04 01:32:03:7860] INFO:  Threads: 1 each 30000 fds
←[0m←[32;1m[2018/06/04 01:32:03:7860] INFO:  mem: context:          5448 B (1352 ctx + (1
thr x 4096))
←[0m←[32;1m[2018/06/04 01:32:03:7860] INFO:  mem: http hdr rsvd:   151680000 B (1 thr x (4
096 + 960) x 30000))
←[0m←[32;1m[2018/06/04 01:32:03:7860] INFO:  mem: pollfd map:      480000
←[0m←[32;1m[2018/06/04 01:32:03:7930] INFO:  Compiled with OpenSSL support
←[0m←[32;1m[2018/06/04 01:32:03:7930] INFO: Doing SSL library init
←[0m←[35;1m[2018/06/04 01:32:03:8010] NOTICE: Creating Vhost 'default' (serving disabled),
 1 protocols, IPv6 off
←[0m←[32;1m[2018/06/04 01:32:03:8400] INFO: loaded ssl_ca_filepath
←[0m←[35;1m[2018/06/04 01:32:03:8410] NOTICE: created client ssl context for default
←[0m←[32;1m[2018/06/04 01:32:03:8410] INFO:  mem: per-conn:          440 bytes + protocol
rx buf
←[0m←[32;1m[2018/06/04 01:32:03:8410] INFO: lws_cancel_service
←[0m←[32;1m[2018/06/04 01:32:03:8410] INFO: lws_protocol_init
←[0m2
←[32;1m[2018/06/04 01:32:07:6822] INFO: lws_cancel_service
←[0m←[32;1m[2018/06/04 01:32:07:6822] INFO: lws_client_connect_via_info: protocol binding
to default
←[0m←[32;1m[2018/06/04 01:32:07:6822] INFO: lws_header_table_attach: wsi 00000000038D0A10:
 ah 0000000000000000 (tsi 0, count = 0) in
←[0m←[32;1m[2018/06/04 01:32:07:6822] INFO: _lws_create_ah: created ah 0000000003A62000 (s
ize 4096): pool length 1
←[0m←[32;1m[2018/06/04 01:32:07:6822] INFO: lws_header_table_attach: did attach wsi 000000
00038D0A10: ah 0000000003A62000: count 1 (on exit)
←[0m←[32;1m[2018/06/04 01:32:07:6822] INFO: lws_client_connect_2: 00000000038D0A10: addres
s libwebsockets.org
←[0m←[32;1m[2018/06/04 01:32:07:7642] INFO: lws_client_connect_2: 00000000038D0A10: addres
s libwebsockets.org
←[0m←[32;1m[2018/06/04 01:32:07:7652] INFO: lws_client_connect_2: 00000000038D0A10: addres
s libwebsockets.org
←[0m←[32;1m[2018/06/04 01:32:07:7662] INFO: lws_client_connect_2: wsi 00000000038D0A10: cl
ient creating own connection
←[0m←[32;1m[2018/06/04 01:32:07:8962] INFO: client connect OK
←[0m←[32;1m[2018/06/04 01:32:07:8962] INFO: lws_client_socket_service: HANDSHAKE2: 0000000
0038D0A10: sending headers on 00000000038D0A10 (wsistate 0x10000012 0x10000012)
←[0mHTTP/1.1 200 OK
x-frame-options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self' 'nonce-lwscaro' https://www.google.com
server: lwsws
Strict-Transport-Security: max-age=15768000 ; includeSubDomains
content-type: text/html
content-length: 391

!!!--------->391 00000000038d0a10<------!!!
←[32;1m[2018/06/04 01:32:07:9682] INFO: lws_client_interpret_server_handshake: incoming co
ntent length 391
←[0m←[32;1m[2018/06/04 01:32:07:9682] INFO: lws_client_interpret_server_handshake: client
connection up
←[0m←[32;1m[2018/06/04 01:32:07:9692] INFO: lws_http_transaction_completed_client: wsi: 00
000000038D0A10, wsi_eff: 00000000038D0A10
←[0muser_data:0000000095b904b4 status:0 len:391 t:0.287553060
←[32;1m[2018/06/04 01:32:07:9712] INFO: lws_http_transaction_completed_client: nothing pip
elined waiting
←[0m4
←[32;1m[2018/06/04 01:32:11:8825] INFO: lws_cancel_service
←[0m←[32;1m[2018/06/04 01:32:11:8825] INFO: lws_client_connect_via_info: protocol binding
to default
←[0m←[32;1m[2018/06/04 01:32:11:8835] INFO: lws_header_table_attach: wsi 0000000003A99B00:
 ah 0000000000000000 (tsi 0, count = 1) in
←[0m←[32;1m[2018/06/04 01:32:11:8845] INFO: _lws_create_ah: created ah 0000000003A9BF60 (s
ize 4096): pool length 2
←[0m←[32;1m[2018/06/04 01:32:11:8845] INFO: lws_header_table_attach: did attach wsi 000000
0003A99B00: ah 0000000003A9BF60: count 2 (on exit)
←[0m←[32;1m[2018/06/04 01:32:11:8855] INFO: applying 0000000003A99B00 to txn queue on 0000
0000038D0A10 (wsistate 0x10000010)
←[0m←[32;1m[2018/06/04 01:32:11:8865] INFO: lws_client_connect_2: wsi 0000000003A99B00: wa
iting to send headers (parent state 10)
←[0m←[32;1m[2018/06/04 01:32:11:8875] INFO: lws_client_socket_service: HANDSHAKE2: 0000000
003A99B00: sending headers on 00000000038D0A10 (wsistate 0x10000012 0x10000010)
←[0mHTTP/1.1 200 OK
x-frame-options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self' 'nonce-lwscaro' https://www.google.com
server: lwsws
Strict-Transport-Security: max-age=15768000 ; includeSubDomains
content-type: text/html
content-length: 394

!!!--------->391 00000000038d0a10<------!!!
←[32;1m[2018/06/04 01:32:11:9605] INFO: lws_client_interpret_server_handshake: incoming co
ntent length 391
←[0m←[32;1m[2018/06/04 01:32:11:9605] INFO: __lws_header_table_detach: wsi 0000000003A99B0
0: ah 0000000003A9BF60 (tsi=0, count = 2)
←[0m←[32;1m[2018/06/04 01:32:11:9615] INFO: __lws_header_table_detach: nobody usable waiti
ng
←[0m←[32;1m[2018/06/04 01:32:11:9615] INFO: _lws_destroy_ah: freed ah 0000000003A9BF60 : p
ool length 1
←[0m←[32;1m[2018/06/04 01:32:11:9625] INFO: __lws_header_table_detach: wsi 0000000003A99B0
0: ah 0000000003A9BF60 (tsi=0, count = 1)
←[0m←[32;1m[2018/06/04 01:32:11:9635] INFO: lws_client_interpret_server_handshake: client
connection up
←[0m←[32;1m[2018/06/04 01:32:11:9635] INFO: lws_http_transaction_completed_client: wsi: 00
000000038D0A10, wsi_eff: 0000000003A99B00
←[0muser_data:00000000fd495c45 status:0 len:391 t:0.081977463
←[32;1m[2018/06/04 01:32:11:9655] INFO: __lws_close_free_wsi: 0000000003A99B00: caller: qu
eued client done
←[0m←[32;1m[2018/06/04 01:32:11:9665] INFO: lws_same_vh_protocol_remove: removing same pro
t wsi 0000000003A99B00
←[0m←[32;1m[2018/06/04 01:32:11:9685] INFO: rops_destroy_role_h1: ah det due to close
←[0m←[32;1m[2018/06/04 01:32:11:9685] INFO: lws_http_transaction_completed_client: nothing
 pipelined waiting
←[0m←[32;1m[2018/06/04 01:32:16:9797] INFO: __lws_close_free_wsi: 00000000038D0A10: caller
: close_and_handled
←[0m←[32;1m[2018/06/04 01:32:16:9797] INFO: lws_same_vh_protocol_remove: removing same pro
t wsi 00000000038D0A10
←[0m←[32;1m[2018/06/04 01:32:16:9807] INFO: rops_destroy_role_h1: ah det due to close
←[0m←[32;1m[2018/06/04 01:32:16:9817] INFO: __lws_header_table_detach: wsi 00000000038D0A1
0: ah 0000000003A62000 (tsi=0, count = 1)
←[0m←[32;1m[2018/06/04 01:32:16:9817] INFO: __lws_header_table_detach: nobody usable waiti
ng
←[0m←[32;1m[2018/06/04 01:32:16:9827] INFO: _lws_destroy_ah: freed ah 0000000003A62000 : p
ool length 0
←[0m←[32;1m[2018/06/04 01:32:16:9827] INFO: __lws_header_table_detach: wsi 00000000038D0A1
0: ah 0000000003A62000 (tsi=0, count = 0)
←[0m
`

**Comment by lws-team** [comment]
OK I am looking at it.

**Comment by lws-team** [comment]
Right... now I catch up with your meaning, your solution was almost right from the start.

It just needs moving into `lws_http_transaction_completed_client()` as you suspected.

I pushed a patch on v3.0-stable with it

https://github.com/warmcat/libwebsockets/commit/3a499dd53de67cac2cd78c38346aea33e763e452

and the same patch on master together with the extra minimal-http-client-multi feature (-n) which makes each queued client fetch a different URL with different content-length.

**Comment by ecionis** [comment]
It works! Thx!
