### ISSUE TITLE
ipv6: winsock2 connect error 10049 The requested address is not valid in its context.

### ISSUE THREAD

**Issue by soliton4** [warmcat/libwebsockets#1301]
when i activate ipv6 support i get the error 10049 every time after connect.
i am trying to make my program run in a client network that uses ipv6 only. but so far i cant seem to be able to connect when ipv6 support is on.

**Comment by lws-team** [comment]
What exactly is "activate ipv6 support" for your code?  Are you setting iface?  To what

**Comment by soliton4** [comment]
thank you @lws-team for responding.
i prepare my build like this:
`cmake -D LWS_IPV6:BOOL=ON -G "Visual Studio 14 2015 Win64" ..`

when i connect to my websocket server the program always ends up here:
https://github.com/warmcat/libwebsockets/blob/v3.0-stable/lib/roles/http/client/client-handshake.c#L434
the error code that causes lws_plat_check_connection_error to fail is allways 10049 which translates to "the requested address is not valid in its context"

i also tried to run it against the test websocket server in this project that i compiled with the same sources.
i start the client with address localhost. the first time i get the same error as above but the test client immediately tries to connect a 2nd time and the 2nd connect seems to work.

when i try to connect to my existing websocket server it never works. also not with the test client.

**Comment by lws-team** [comment]
Did you notice these vhost options?

```
	LWS_SERVER_OPTION_DISABLE_IPV6				= (1 << 5),
	/**< (VH) Disable IPV6 support */
	LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY			= (1 << 16),
	/**< (VH) Enable LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE to take effect */
	LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE			= (1 << 17),
	/**< (VH) if set, only ipv6 allowed on the vhost */
```

**Comment by soliton4** [comment]
no. and what do i learn from noticing them?
arent these server options?
my problem is with the client

**Comment by lws-team** [comment]
> no. and what do i learn from noticing them?

Nothing apparently.

**Comment by soliton4** [comment]
that was not helpful at all
