### ISSUE TITLE
lws_callback_on_writable with already disconnected client

### ISSUE THREAD

**Issue by LabunskyA** [warmcat/libwebsockets#1302]
So, the question is in the title. In my case it is possible that one lws service thread will request callback on writable for the client on another lws service thread.

The basic situation:
t1: got active wsi pointer
t2: client associated with wsi disconnected
t1: is calling lws_callback_on_writable(wsi)
t2: ???

I want to know what will happen (if anything will) at ???. Undefined behavior?

**Comment by lws-team** [comment]
Asking for a writeable callback just sets some event bits for next time we enter poll() wait by default.  What it does with a different event library depends on the library and the platform.

If the underlying socket got a FIN, next time it enters poll)) wait, it will typically get a POLLIN indication yielding a zero-length read, meaning "I am dead" and provoking the logical wsi close flow, or a POLLHUP.  Different event libraries will ultimately get the same experience.

There's no pending POLLOUT wait entrails left over.  fds.events either had POLLOUT set, or it didn't.  When it closes that is recycled for a new connection.

**Comment by LabunskyA** [comment]
So there will be no SEGFAULT / memory corruption or anything deadly to the process, did I got this right? 
Really don't want to create critical sections)

**Comment by lws-team** [comment]
Because the underlying socket state happens to be disconnected?  No.

**Comment by LabunskyA** [comment]
Thanks, I just didn't knew how library is processing pointers to lws structure after client disconnection

**Comment by LabunskyA** [comment]
I'm not confusing them. 
The whole point of question was to understand if lws is freeing the memory for client structures after disconnection or trying to reuse them and keeping with some sort of "not active" flag for some if not determined, but possible for prediction time.

I know that it is not good pattern, but in the second case I would prefer to ignore race condition (everything is OK for me, until process is alive and memory corruption is not happened) and leave code without critical section and any locking, because in my code pointers will be alive after client disconnetion for a very, very (like, 10 processor instructions) short term.

But it seems that I need locking anyway. Thanks for explaining

**Comment by lws-team** [comment]
> I'm not confusing them.

In your mind you may well understand them correctly.

But in your communications, you cannot use "disconnect" in place of "destroy" and synchronize the same set of ideas to be under discussion.  Actually in your mind you were having one conversation and in reality we had a different discussion that followed the meaning of your words...

**Comment by LabunskyA** [comment]
Well, sorry if my question was not clear enough
