### ISSUE TITLE
Crash in lws_service_timeout_check on Windows on 1.7-stable

### ISSUE THREAD

**Issue by kcbanner** [warmcat/libwebsockets#1303]
I'm running into a crash where `fds[wsi->sock]` indexes into invalid memory. On Windows I believe the socket handles are opaque and not 0-indexed like they are on other platforms. 

Should this code should be using `fds[wsi->position_in_fds_table]`?

This appears fixed in 3.0-stable.

```
	/*
	 * if we went beyond the allowed time, kill the
	 * connection
	 */
	if ((time_t)sec > wsi->pending_timeout_limit) {
#if LWS_POSIX
		lwsl_notice("wsi %p: TIMEDOUT WAITING on %d (did hdr %d, ah %p, wl %d, pfd events %d)\n",
			    (void *)wsi, wsi->pending_timeout,
			    wsi->hdr_parsing_completed, wsi->u.hdr.ah,
			    pt->ah_wait_list_length,
			    pt->fds[wsi->sock].events);
#endif
```

**Comment by lws-team** [comment]
1.7 is too old to take care about... please use a later version.
