### ISSUE TITLE
libwebsockets wss connect error

### ISSUE THREAD

**Issue by qinaksd** [warmcat/libwebsockets#1305]
got libwebsocket-3.0-stable source and build,then try to run the follow command :
libwebsockets-test-client.exe wss://47.98.127.31:8082
←[35;1m[2018/06/07 14:20:16:1318] NOTICE: libwebsockets test client - license LG
PL2.1+SLE
←[0m←[35;1m[2018/06/07 14:20:16:1318] NOTICE: (C) Copyright 2010-2018 Andy Green
 <andy@warmcat.com>
←[0m←[35;1m[2018/06/07 14:20:16:1318] NOTICE:  Using SSL
←[0m←[35;1m[2018/06/07 14:20:16:1318] NOTICE:  Cert must validate correctly (use
 -s to allow selfsigned): 1
←[0m←[35;1m[2018/06/07 14:20:16:1318] NOTICE:  Requiring peer cert hostname matc
hes
←[0m←[35;1m[2018/06/07 14:20:16:1368] NOTICE: Creating Vhost 'default' (serving
disabled), 3 protocols, IPv6 off
←[0m←[35;1m[2018/06/07 14:20:16:2518] NOTICE: created client ssl context for def
ault
←[0m←[35;1m[2018/06/07 14:20:16:2598] NOTICE: using wss mode (ws)
←[0m←[35;1m[2018/06/07 14:20:16:2608] NOTICE: http: connecting
←[0m←[31;1m[2018/06/07 14:20:16:2988] ERR: SSL error: unable to get local issuer
 certificate (preverify_ok=0;err=20;depth=0)
←[0m←[31;1m[2018/06/07 14:20:16:2988] ERR: CLIENT_CONNECTION_ERROR: dumb: client
 connect failed
←[0m←[31;1m[2018/06/07 14:20:17:7988] ERR: Exiting

anyone know how to solve it?

**Comment by Babel-Fish** [comment]
Have you tried "-s"and/ or specifying the ssl options
`
{ "ssl-cert",  required_argument,	NULL, 'C' },
{ "ssl-key",  required_argument,	NULL, 'K' },
{ "ssl-ca",  required_argument,		NULL, 'A' },
`
also does it work without wss? just a thought
