### ISSUE TITLE
Not able to set proxy after context creation

### ISSUE THREAD

**Issue by turtiain** [warmcat/libwebsockets#1308]
I must be missing something obvious.

According to the documentation "lws_set_proxy() - Setups proxy to lws_context." But the parameter for lws_set_proxy is not lws_context but lws_vhost. Also according to the documentation "You should call this function right after creation of the lws_context and before call to connect."

Where do I get the lws_vhost pointer that I could use for lws_set_proxy? There is lws_get_vhost but it requires wsi which I get when calling lws_client_connect_via_info and then it is too late to call lws_set_proxy.

**Comment by lws-team** [comment]
Create the vhost explicitly, like this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n105

**Comment by lws-team** [comment]
"client" is a restriction you made for yourself.

Actually lws can have as many client connections as you want sharing incoming server connections on the same vhost.  Clients that bind to a particular vhost use related settings on that vhost.

**Comment by turtiain** [comment]
Well, to me ”client” is quite sensible restriction, after all I’m working on a websocket client.

As a minor issue, I think the documentation could be updated as the proxy is not set to a context but to vhosts. And I have to write the few extra lines of code for explicitly creating the vhost on the client :)

**Comment by turtiain** [comment]
You already have my everlasting overflowing gratitude for creating the websocket library that is clearly best suited for my purposes and I feel sorry for disturbing you with my honest question.
