### ISSUE TITLE
Can I add a custom header in client side when establishing a connection?

### ISSUE THREAD

**Issue by ghmlee** [warmcat/libwebsockets#1312]
Can I add a custom header in client side when establishing a connection?

I found this function but it seems not working for client side.

```
ws_add_http_header_by_name()
```

**Comment by lws-team** [comment]
```
	LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER		= 24,
	/**< this callback happens
	 * when a client handshake is being compiled.  user is NULL,
	 * in is a char **, it's pointing to a char * which holds the
	 * next location in the header buffer where you can add
	 * headers, and len is the remaining space in the header buffer,
	 * which is typically some hundreds of bytes.  So, to add a canned
	 * cookie, your handler code might look similar to:
	 *
	 *	char **p = (char **)in;
	 *
	 *	if (len < 100)
	 *		return 1;
	 *
	 *	*p += sprintf(*p, "Cookie: a=b\x0d\x0a");
	 *
	 *	return 0;
	 *
	 * Notice if you add anything, you just have to take care about
	 * the CRLF on the line you added.  Obviously this callback is
	 * optional, if you don't handle it everything is fine.
	 *
	 * Notice the callback is coming to protocols[0] all the time,
	 * because there is no specific protocol negotiated yet.
	 *
	 * See LWS_CALLBACK_ADD_HEADERS for adding headers to server
	 * transactions.
	 */
```

**Comment by ghmlee** [comment]
@lws-team Thank you.

**Comment by vinifr** [comment]
Hello. I am trying to bulid a full custom header like this:

_HTTP/1.1 101 Switching Protocols
Date: Thu, 09 Feb 2023 12:53:07 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: VRfr9zc8kLqZjX0NeDo53e96ELQ=
Sec-WebSocket-Extensions: permessage-deflate
Via: 1.1 google
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 796cbf016ee96f80-JDO_

But it is sending this:

_GET /socket.io/?EIO=3&transport=websocket HTTP/1.1
Pragma: no-cache
Cache-Control: no-cache
Host: ws.broker.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: hXbZ32nh8vxDuoR0izLt0A==
Sec-WebSocket-Version: 13
Date: Thu, 09 Feb 2023 20:46:34 GMT
Via: 1.1 google
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 796f7489fb706f7f-JDO_

Is it possible to build a full custom header like this? Cause I am getting: got bad HTTP response '403'
