### ISSUE TITLE
Send progressively messages to client

### ISSUE THREAD

**Issue by annagogolou** [warmcat/libwebsockets#1320]
Hello,

I compute something progressively (i.e., I have an aggregate function) and I want to send progressively messages to client. Libwebsockets seem not to support that, because they always send the message, when the full computation is done.

I am using LWS_CALLBACK_SERVER_WRITEABLE, where I do all the lws_write() calls. But this part of code in my callback protocol is being executed only when the full computation is done.

How can I call the callback function in order to send a partial result to client, while my computation algorithm continues to compute the aggregate value?

I am looking forward to your answer!
Thanks,
Anna

**Comment by lws-team** [comment]
By default one lws_write == one ws message.

But that's just the default.

Please take a look at how this minimal example is sequencing the write, allowing you to add to it when you have more until you reach the end of your "message" content.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-pmd-bulk/protocol_lws_minimal_pmd_bulk.c#n126-161

https://libwebsockets.org/git/libwebsockets/tree/lib/libwebsockets.h#n4910-4925

**Comment by annagogolou** [comment]
Thank you very much for your answer, but my issue is a little bit different. My protocol is the following:

case LWS_CALLBACK_RECEIVE: {
    exact_func(wsi);
    break;
}
case LWS_CALLBACK_SERVER_WRITEABLE: {
    /* code to send msg to client lws_write() */
    ....
    break;
}

In LWS_CALLBACK_SERVER_WRITEABLE I can use the code that you quoted in your examples in order to send chunks of messages. But my problem is that this part of code is executed only when the full computation of my aggregate function is done. My aggregate function is exact_func() in LWS_CALLBACK_RECEIVE, which is being called when a new request is received from the client.

I implement my aggregate function outside the protocol. I want to execute the LWS_CALLBACK_SERVER_WRITEABLE code, while my aggregate function still computes the final result. But LWS_CALLBACK_SERVER_WRITEABLE code is being executed only when my aggregate function is done. I want to send a message to client without stopping the execution of my aggregate function. How can I do that? How can I call the LWS_CALLBACK_SERVER_WRITEABLE code from my aggregate function while my aggregate function continues to compute the final result?

My issue is that LWS_CALLBACK_SERVER_WRITEABLE code is only executed after my aggregate function finishes computations.

Thank you very much,
Anna

**Comment by lws-team** [comment]
If I understand it, your problem is you have something that takes a long time to compute, and it blocks lws event loop if you just do it inline?

If that's what you are actually asking, you need to have another thread do the computation in the background without blocking lws.

When the computation ends, it can call `lws_cancel_service()` to signal lws there is something to do.

See

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n76-129

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n256-269
