### ISSUE TITLE
Multi-thread lws used together with unix domain socket causes errors

### ISSUE THREAD

**Issue by Zhang-Junzhi** [warmcat/libwebsockets#1324]
lws is compiled with -D LWS_UNIX_SOCK:BOOL=ON -D LWS_MAX_SMP=3 .

When using the following creation info,

static struct lws_context_creation_info info =
{
	.iface = "/tmp/lwstest",
	.options = LWS_SERVER_OPTION_UNIX_SOCK,
	.protocols = ...,
	.count_threads = 3,
};

The server gets errors:

[2018/07/07 12:49:07:2697] ERR: ERROR on binding fd 11 to "/tmp/lwstest" (-1 98)
[2018/07/07 12:49:07:2697] ERR: VH default: iface /tmp/lwstest port 12148 DOESN'T EXIST

if I change the count_threads to 1, or if I change to use an Internet socket, then the error is gone.

**Comment by lws-team** [comment]
I see.  Well, maybe you can debug it and send a patch.
