### ISSUE TITLE
Why websocket SSL verify fail on AWS?    while in test enviroment SSL OK. 

### ISSUE THREAD

**Issue by jiangguoding** [warmcat/libwebsockets#1327]
Enviroment:
Test enviroment:  Nigix           ------>  curl https OK.    warmcat/libwebsocket OK.
AWS:    aws/elb.                     -------> curl https OK.     warmcat/libwebsocket FAIL.

test condition:
-------------------------------------
1.   same CERT file.
2.  same websocket client exe.
3. same server code.

120(s):691(ms)--->   insert_wsi_socket_into_fds: 0xb0c75200: tsi=0, sock=14, pos-in-fds=1

120(s):692(ms)--->   lws_set_timeout: 0xb0c75200: 20 secs

120(s):694(ms)--->   Success---ws_connect_server to wss://xxxx/api/v1/device/connect....

121(s):66(ms)--->   lws_client_connect_2: 0xb0c75200: address xxxx.tclking.com

121(s):70(ms)--->   lws_set_timeout: 0xb0c75200: 20 secs

121(s):71(ms)--->   lws_ssl_get_error: 0xb11ca2c0 -1 -> 2 (errno 11)

121(s):448(ms)--->   SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=2)

121(s):449(ms)--->   lws_ssl_get_error: 0xb11ca2c0 -1 -> 1 (errno 0)

121(s):449(ms)--->   lws_ssl_client_connect2: SSL_connect says -1

121(s):449(ms)--->   closing conn at LWS_CONNMODE...SERVER_REPLY

121(s):449(ms)--->   reason: lws_ssl_client_connect2 failed

121(s):449(ms)--->   closed

121(s):450(ms)--->   --ws_status_callback -state = 5--

**Comment by lws-team** [comment]
Your OS doesn't have the CA cert trusted for the certificate your server is using.

**Comment by jiangguoding** [comment]
I specify the CA cert as 
        info.ssl_ca_filepath = ssl_ca_path; 
        info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

CA file is the same for testing  env and server env.
The same CA cert can be passed verification by libcurl/https. 



----------------------------------------------------------------------------------------
 lwsl_notice("-----------use--ssl--------------%d-------\n", g_use_ssl);
    if (g_use_ssl) {
        lwsl_notice("requiring server cert validation----%s---\n", ssl_ca_path);
        info.ssl_ca_filepath = ssl_ca_path; 
        info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    } 
    
    info.gid = -1;
    info.uid = -1;
    //info.options |=  LWS_SERVER_OPTION_VALIDATE_UTF8;

    info.ws_ping_pong_interval = 30;  //30S 
    info.timeout_secs = 60;

    lwsl_notice("-ws_init_context--lws_create_context-----\n");
    g_ws_context = lws_create_context(&info);
    if (g_ws_context == NULL)

**Comment by lws-team** [comment]
This problem is not on my side, so I don't know what you're expecting me to do about it.

OpenSSL is reporting it doesn't have the cert to verify what the server sent.

> SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=2)

Make sure the server is sending also any necessary intermediate cert.  But this isn't an lws issue...

**Comment by jiangguoding** [comment]
Thanks for your help indeed.  This issue bothers me long time.
I just want some guiding idea about this wired question.


My android is like: 
    libboringSSL + libcurl + warmcat\libwebsocekt

In test env: 
   libcur/boringSSL:   acessing https OK.
   websocket/boringssl:  asscess wss OK.

In AWS/ELB:
     libcur/boringSSL:   acessing https OK.
   websocket/boringssl:  asscess wss   FAIL.

**Comment by jiangguoding** [comment]
I wonder why  the same CERT and same boringSSL in one EXE file,    curl/https OK,  websocket/wss FAIL.

**Comment by lws-team** [comment]
> Make sure the server is sending also any necessary intermediate cert. But this isn't an lws issue...

**Comment by jiangguoding** [comment]
Thanks for your help indeed.
I will check the server side.

**Comment by jiangguoding** [comment]
Thanks for your guidance!
It is CERT file issue.  
including root cert into the file fix it.
and Thanks again.
