### ISSUE TITLE
Loading CA chain from memory

### ISSUE THREAD

**Issue by jimon** [warmcat/libwebsockets#1331]
Would be nice to be able, in addition to `client_ssl_ca_filepath`, to set ptr/len to this file in memory.

From what I understand it might be possible to do from `LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS` callback, but I'm yet to figure out how to do it exactly without including private parts of lws (I'm using mbedtls).

**Comment by lws-team** [comment]
Originally lws only supported openssl, and some callbacks are defined to provide the SSL pointer for corner cases.

However about 18mo ago I got a nice contribution of basic support for mbedtls.  After that was working, I faced a choice of following this scheme of passing the tls-library specific pointer as before, or making it private and providing tls-library-agnostic apis to let the user code get stuff done.

The latter has the advantage that the user code also then becomes agnostic to which tls library it was built with, which is highly desirable.  So I ran around adding generic apis for hash, hmac, rsa crypto etc with backend implementations on both tls libs equally.

The solution to what you want is add another lws_tls api which does the same on both openssl and mbedtls... patch implementing that is very welcome.

**Comment by jimon** [comment]
Ok, I did it for mbedtls, but now I'm stuck with openssl change, I'm doing following:

```
int
lws_tls_client_create_vhost_context(struct lws_vhost *vh,
				    const struct lws_context_creation_info *info,
				    const char *cipher_list,
				    const char *ca_filepath,
				    const void *ca_mem,
				    unsigned int ca_mem_len,
				    const char *cert_filepath,
				    const char *private_key_filepath) {
	...
	const unsigned char **ca_mem_ptr;
	X509 *client_CA;
	X509_STORE *x509_store;
	...
	ca_mem_ptr = (const unsigned char**)&ca_mem;
	client_CA = d2i_X509(NULL, ca_mem_ptr, ca_mem_len - 1);
	x509_store = SSL_CTX_get_cert_store(vh->tls.ssl_client_ctx);
	if (!client_CA || !X509_STORE_add_cert(x509_store, client_CA)) {
		lwsl_err("Unable to load SSL Client certs from ssl_ca_mem "
		    " x509 err -- "
		    "client ssl isn't going to work\n");
		lws_ssl_elaborate_error();
	} else {
		lwsl_info("loaded ssl_ca_mem\n");
	}
	if (client_CA)
		X509_free(client_CA);
	...
}
```

But `X509_STORE_add_cert` fails (returns 0) and I'm struggling to understand why or what is going wrong. Both `client_CA` and `x509_store` seem to be valid pointers. Any tips how to debug this?

**Comment by jimon** [comment]
merged to master
