### ISSUE TITLE
struct sockaddr_in visibility warning that generates an error

### ISSUE THREAD

**Issue by jimon** [warmcat/libwebsockets#1332]
When building for Android with mbedtls I get this visibility warning, which generates an error because of `-Werror` flag.

```
In file included from ../vendor/libwebsockets/lib/tls/mbedtls/wrapper/platform/ssl_pm.c:28:
../vendor/libwebsockets/lib/libwebsockets.h:5485:58: error: declaration of 'struct sockaddr_in' will not be visible outside of this function [-Werror,-Wvisibility]
lws_interface_to_sa(int ipv6, const char *ifname, struct sockaddr_in *addr,
                                                         ^
```

**Comment by lws-team** [comment]
So where does your version of android define struct sockaddr_in?

**Comment by jimon** [comment]
I could be very wrong, but it looks like `#include <netinet/in.h>` is not included on Android. I'm looking here https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L111-L114

**Comment by lws-team** [comment]
Yeah according to https://android.googlesource.com/platform/development/+/73a5a3b/ndk/platforms/android-20/include/netinet/in.h it's there via linux/in.h

Does this help?

```
diff --git a/lib/libwebsockets.h b/lib/libwebsockets.h
index 7bd9d4c7..912175d0 100644
--- a/lib/libwebsockets.h
+++ b/lib/libwebsockets.h
@@ -152,6 +152,7 @@ typedef unsigned long long lws_intptr_t;
 #endif
 
 #if defined(__ANDROID__)
+#include <netaddr/in.h>
 #include <unistd.h>
 #define getdtablesize() sysconf(_SC_OPEN_MAX)
 #endif
```

**Comment by jimon** [comment]
Ok, I though the same, but now I'm getting

```
../vendor/libwebsockets/lib/libwebsockets.h:153:10: fatal error: 'netaddr/in.h' file not found
#include <netaddr/in.h>
```

Super weird. I'll try to figure out why is that.

**Comment by jimon** [comment]
Ok, it's `netinet` not `netaddr`

https://github.com/warmcat/libwebsockets/pull/1333
