### ISSUE TITLE
lws_set_timeout to invoke LWS_CALLBACK_CLOSED

### ISSUE THREAD

**Issue by Babel-Fish** [warmcat/libwebsockets#1334]
When using lws_set_timeout to terminate a connection, it does not appear to invoke the LWS_CALLBACK_CLOSED callback if a connection was established. Is there a way to have it still invoke that callback?

**Comment by Babel-Fish** [comment]
LWS_CALLBACK_CLOSED was changed to LWS_CALLBACK_CLIENT_CLOSED

**Comment by Sleepingbug** [comment]
please tell me how to resolve this problem.
LWS_CALLBACK_CLIENT_CLOSED not invoked.
