### ISSUE TITLE
Calling lws_close_reason on ws, while handshake is in-flight, will crash your application.

### ISSUE THREAD

**Issue by jimon** [warmcat/libwebsockets#1335]
I'm trying to establish a websocket connection, and then for some external reason I need to stop it ASAP. I do understand that there are other ways to do it, but currently I'm trying to be straightforward and use `lws_close_reason` for that.

What's happening is I'm getting this on my callback:

```
DEBUG: LWS got LWS_CALLBACK_PROTOCOL_INIT
DEBUG: LWS got LWS_CALLBACK_WSI_CREATE
Assertion failed: (lwsi_role_ws(wsi)), function lws_close_reason, file vendor/libwebsockets/lib/roles/ws/ops-ws.c, line 858.
```

This assert is `assert(lwsi_role_ws(wsi));`. Ok makes sense :) But it feels like a poor user experience to me IMHO.

And in Release build, this assert is not available, so whole application goes down with segfault.

**Comment by lws-team** [comment]
LWS_CALLBACK_WSI_CREATE just means a wsi is allocated.  It's happening before the wsi is configured to do anything.

So don't try to do those things on the wsi at that callback... no example code even uses that callback.

> But it feels like a poor user experience to me IMHO.

Don't pick random callbacks to do stuff and your experience will be better.  The minimal examples are well worth reading through.

**Comment by jimon** [comment]
@lws-team I'm not doing this at callback specifically, but rather from external event. As external event arrives I need to shutdown ASAP. What would be a correct way to do it?

**Comment by jimon** [comment]
Ok, looks like it's only safe to call it between `LWS_CALLBACK_CLIENT_ESTABLISHED` and `LWS_CALLBACK_CLOSED` / `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`. Fair enough, though I still find it's weird that such limitations are not documented in API.

**Comment by lws-team** [comment]
Lws is singlethreaded, you can't just randomly do things from other threads, except lws_cancel_service() and callback on writeable.  Have a look in README.coding.md.

If you are literally shutting down, set a flag,  use lws_cancel_service() to abort any poll wait, and then destroy the context and exit instead of looping back for more service.

**Comment by jimon** [comment]
I think there is some miscommunication. I'm just doing this:

```
class Transport {
public:
  Transport() {
    ...
    ctx = lws_create_context(...);
    ...
    wsi = lws_client_connect_via_info(...);
  }
  ~Transport() {
    if (wsi)
      lws_close_reason(wsi, LWS_CLOSE_STATUS_NORMAL, nullptr, 0);
    lws_context_destroy(ctx);
  }
  void Poll() {
    lws_service(ctx, 50);
  }
private:
  struct lws_context * ctx;
  struct lws * wsi;
 ...
};
```

Constructor, destructor, and Poll are called from one thread. It's all singlethreaded.
As you can see, from this example it's not obvious that `lws_close_reason` can fail with segfault.

Maybe there are some hidden API expectations that are not surfaced? like only call lws functions from lws protocol callback?
