### ISSUE TITLE
Double bind of wsi to vh for server?

### ISSUE THREAD

**Issue by Babel-Fish** [warmcat/libwebsockets#1336]
I am running a test where the client and server is running on the same process and connecting to one another (in case that aspect is important). With this test, I believe I am seeing a double bind of wsi to a vhost which is stopping proper shutdown. 

I modified the bind/unbind log lines to ensure we are comparing the same pointers. Can you confirm my findings? Here are my modified log lines for clarity.
https://github.com/warmcat/libwebsockets/blob/master/lib/core/libwebsockets.c#L118
**lws_vhost_bind_wsi:** ```lwsl_info("%s: wsi %p, vh %s(%p): count_bound_wsi %d\n", __func__, wsi, vh->name, vh, vh->count_bound_wsi);```
https://github.com/warmcat/libwebsockets/blob/master/lib/core/libwebsockets.c#L133
**lws_vhost_unbind_wsi:** ```lwsl_info("%s: wsi %p, vh %s(%p): count_bound_wsi %d\n", __func__, wsi, wsi->vhost->name, wsi->vhost, wsi->vhost->count_bound_wsi);```

When the wsi is first created for the vhost, it is bound.  https://github.com/warmcat/libwebsockets/blob/master/lib/core/adopt.c#L67
```Function where bind occurs lws_create_new_server_wsi
--Logs---
level=16 msg=new wsi 0x61400001fa40 joining vhost default, tsi 0
level=8 msg=lws_vhost_bind_wsi: wsi 0x61400001fa40, vh default(0x61700000fc80): count_bound_wsi 2
level=16 msg=lwsi_set_state(0x61400001fa40, 0x200)
```

Later when the handshake occurs, it binds again but to same vhost. https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/server/server.c#L1466
```
level=32 msg=v13 hdrs done
level=8 msg=lws_handshake_server: parsed count 228
level=32 msg=lws_handshake_server: lws_parse sees parsing complete
level=8 msg=lws_select_vhost: vhost match to default based on port 1234
level=8 msg=lws_vhost_bind_wsi: wsi 0x61400001fa40, vh default(0x61700000fc80): count_bound_wsi 3
```

Isnt wsi already bound to vhost by this point since wsi->vhost resolves? Is it attempting to update the vhost? 

When teardown occurs my shutdown is stalling out. Here is the destroy of the client wsi for the server (but technically this was added twice)
```
level=16 msg=__lws_close_free_wsi_final: wsi 0x61400001fa40: fd 9
LWS_CALLBACK_WSI_DESTROY received at my app layer
level=8 msg=lws_vhost_unbind_wsi: wsi 0x61400001fa40, vh default(0x61700000fc80): count_bound_wsi 2
level=16 msg=__lws_free_wsi: 0x61400001fa40, remaining wsi 2
level=8 msg=__lws_close_free_wsi: 0x61400000fc40: caller: vh destroy
```

Here is the teardown of the wsi for the vhost
```
LWS_CALLBACK_UNLOCK_POLL received at app layer
level=16 msg=lwsi_set_state(0x61400000fc40, 0x1e)
level=16 msg=__lws_close_free_wsi_final: wsi 0x61400000fc40: fd 7
LWS_CALLBACK_WSI_DESTROY received at app layer
level=8 msg=lws_vhost_unbind_wsi: wsi 0x61400000fc40, vh default(0x61700000fc80): count_bound_wsi 1
level=16 msg=__lws_free_wsi: 0x61400000fc40, remaining wsi 1
```

https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/server/server.c#L1466
Is this line really needed or should it guard against binding to a vhost if it matches the vhost that wsi is already bound to?

When I modify the check to `if (vhost && wsi->vhost != vhost)` it passes. I can do a pull request but want to confirm I am not doing something wrong.

**Comment by lws-team** [comment]
Thanks for the patch, it's on master.
