### ISSUE TITLE
HTTP POST request hangs if the post body is empty

### ISSUE THREAD

**Issue by santosh0705** [warmcat/libwebsockets#1337]
Probably this is not an issue but I couldn't get any solution to handle a post request with empty body.
This I tested with the provided test server as well.

Steps to reproduce:
```
curl -X POST https://libwebsockets.org/testserver/formtest -d "" -v
```
Expected result was getting the html but curl exits with error.

If post body is empty than `callback_http()` is not called with reason `LWS_CALLBACK_HTTP_BODY`.

**Comment by ecionis** [comment]
I have same problem.

http/1.1
Site return "Content-Length: 0" (GET method)

LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ is not called
LWS_CALLBACK_RECEIVE_CLIENT_HTTP is not callded

**Comment by lws-team** [comment]
Thanks... I pushed on master a variation of ecionis' solution and a fix for the server side problem.

I also updated libwebsockets.org with them, the curl reproducer from Santosh works now.

Please give them a try.

**Comment by santosh0705** [comment]
It worked. 👍

**Comment by lws-team** [comment]
Great.
