### ISSUE TITLE
calling lws_get_peer_write_allowance() results in an access violation (HTTP/1.1)

### ISSUE THREAD

**Issue by gmondada** [warmcat/libwebsockets#1339]
When working with HTTP/1.1, IPv4, calling lws_get_peer_write_allowance() crashes with access violation (access to address 0x0). This is probably due to wsi->role_ops->tx_credit being NULL. Shouldn't this function return -1 in this case?

**Comment by lws-team** [comment]
Yeah... you are right.  I added a patch on master + v3.0-stable I will push shortly.
