### ISSUE TITLE
How can the libwebsockets-server  write to all active connections 

### ISSUE THREAD

**Issue by gyplol** [warmcat/libwebsockets#1341]
Hi, 
I did my own libwebsockets server on the ARM platform, and there is a websockets client web page on the boa server ported from this platform. But there is a problem: when there are more than two browsers to open the client web page, the server will take it as the same wsi, which will cause data to be transmitted separately without direction. 

How can the server data be transmitted simultaneously to the client end opened by multiple browsers to achieve synchronization.

And I used the same method in the sample source file test-server.c, called lws_callback_on_writable_all_protocol(context,lws_get_protocol(wsi)). But this didn't work on my code.   I'm not sure if it was used correctly.

my code be like:

struct lws_context *context;

static int callback_dumb_increment(struct lws *wsi, enum lws_callback_reasons reason,
					void *user, void *in, size_t len)
{
	int i;
	cJSON *node = NULL;
	cJSON *tnode = NULL;
    switch (reason) {

	case LWS_CALLBACK_ESTABLISHED:
		printf("[dumb Service] Connection established.\n");	
		lws_callback_on_writable(wsi);
		break;
				
	case LWS_CALLBACK_SERVER_WRITEABLE :
		//lws_rx_flow_allow_all_protocol( context,lws_get_protocol(wsi));
		pthread_mutex_lock(&lock);
		if( revc_buf[0] != '\0' )
		{
			websocket_write_back(wsi, revc_buf);
			memset(revc_buf,0,MAXSIZE);
		}		
		pthread_mutex_unlock(&lock);
                lws_rx_flow_allow_all_protocol( context,lws_get_protocol(wsi));
		lws_callback_on_writable(wsi);
		break;		
		
	case LWS_CALLBACK_RECEIVE:   
		
		node = cJSON_GetObjectItem(cJSON_Parse((char *)in),"data");
		pthread_mutex_lock(&lock);   
		size=cJSON_GetArraySize(node);
		for(i=0;i<size;i++){
			tnode = cJSON_GetArrayItem(node,i);
				   send_buf[i]=tnode->valueint;
		}	
		pthread_mutex_unlock(&lock); 
		lws_callback_on_writable_all_protocol(context,lws_get_protocol(wsi));
		break;
						
			
    case LWS_CALLBACK_CLOSED:
            printf("[dumb Service] Client close.\n");
			pthread_mutex_lock(&lock);
			for(i=0;i<15;i++)
			{
				send_buf[i]=cspro_stopmeter[i];
			}
			size = 15;
			pthread_mutex_unlock(&lock);
			memset(revc_buf,0,MAXSIZE);
			break;

    default:
            break;
    }

    return 0;
}

int main()
{
   ......
  context = lws_create_context(&info);
   while(1)
  {
     lws_service(context, 50);
   }    
}

**Comment by lws-team** [comment]
> when there are more than two browsers to open the client web page, the server will take it as the same wsi

... doubt that very much.

Why don't you have a look at the minimal examples here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples

You don't really explain what you're trying to do, but, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads

If you have problems with those I have that same code and we can talk about it reasonably.
