### ISSUE TITLE
Debug message before ws close: bad cont

### ISSUE THREAD

**Issue by matrixhacker** [warmcat/libwebsockets#1342]
I receive the following message when sending several back to back messages from the client to the server:
[2018/07/17 18:31:12:7185] DEBUG: 
[2018/07/17 18:31:12:7186] DEBUG: 0000: 03 EA 62 61 64 20 63 6F 6E 74                      ..bad cont      
[2018/07/17 18:31:12:7186] DEBUG: 
Immediately following the server closes the socket. Reconnecting works fine but the last couple messages the client sent in the group are lost.
I can't seem to find much to go on. Anyone have any thoughts?

**Comment by lws-team** [comment]
The debug dump is actually the contents of a CLOSE frame sent by the server.

"bad cont" refers to the client having sent an illegal TEXT / BINARY / CONTINUATION frame out of sequence.  Check the frame types and ws FINs you are sending more closely.

If you find mysterious messages like "bad cont", `git grep "bad cont"` is your friend.

**Comment by matrixhacker** [comment]
I had already found the lines where bad cont is printed, but I don't understand what's it's doing aside from processing the received frames. To my knowledge I don't have any control over client sending as it's a browser. Is there something else I should be aware of?

**Comment by matrixhacker** [comment]
First testing using lws-minimal-ws-server on Chrome and Firefox. Used the console to run: 'ws.send("msg1");ws.send("msg2");ws.send("msg3");ws.send("msg4");' Not all messages showed up on both browsers any time it was run. Sometimes the box would show msg1 and msg4, another time it showed msg1, msg3, and msg4, etc. When running multiple browsers/windows the output did not match. On neither browser did the socket close, but I will continue further testing.

**Comment by matrixhacker** [comment]
Duplicated above issue using lws-minimal-ws-server-pmd. Browsers do not list all messages sent but socket does not close.

**Comment by lws-team** [comment]
That sounds like something different... if the server finds anything illegal in the ws framing, it will always close the connection, since it doesn't know how to go on interpreting what was sent, can't know when there next message starts etc.

For simplicity that example doesn't use any ringbuffer, it says in the comment

```
 * This version holds a single message at a time, which may be lost if a new
 * message comes.  See the minimal-ws-server-ring sample for the same thing
 * but using an lws_ring ringbuffer to hold up to 8 messages at a time.
```

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-pmd/protocol_lws_minimal.c#n9-11

**Comment by matrixhacker** [comment]
I figured it out. I was modifying the in buffer within my callback as part of my parsing. Copying the data to a new buffer resolved the issue. Thanks for you help.
