### ISSUE TITLE
Error caused by wrong memory allocator

### ISSUE THREAD

**Issue by valileo-valilei** [warmcat/libwebsockets#1343]
Hello @lws-team,

I am using the libwebsockets library for a websocket client, where I use a custom memory allocation function. I discovered that in the roles/http/client/client-handshake.c function, the `wsi->client_hostname_copy` is allocated by `strdup`, which uses the standard `malloc` function.

```
163          if (!wsi->client_hostname_copy)
164            wsi->client_hostname_copy =
165              strdup(lws_hdr_simple_ptr(wsi,
166                _WSI_TOKEN_CLIENT_PEER_ADDRESS));
```

 whereas the memory is freed with the provided custom memory allocator.

```
587        lws_free_set_NULL(wsi->client_hostname_copy);
```

This causes an error when freeing the allocated buffer, because the custom memory allocation function is not designed to manage memory allocated by `malloc`.

I attempted to make a modification, to replace the `strdup` with the custom allocator and the problem was resolved, so the issue does seem to be caused by this.

```
165	  wsi->client_hostname_copy = lws_malloc(strlen(lws_hdr_simple_ptr(wsi,
166          _WSI_TOKEN_CLIENT_PEER_ADDRESS)) + 1, "client_hostname_copy");
167	  memcpy(wsi->client_hostname_copy, lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_PEER_ADDRESS),
168	         strlen(lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_PEER_ADDRESS)));
169	  wsi->client_hostname_copy[strlen(lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_PEER_ADDRESS))] = 0;
```

The platform on which this is running is an Ubuntu 16.04, and I am using the table 3.0.0 version of the library.

**Comment by lws-team** [comment]
Thanks, I see... there's actually already an `lws_strdup()` internally that does what's needed, I pushed a one-liner on v3.0-stable and master that fixes it with that.
