### ISSUE TITLE
Broken symlinks in repo

### ISSUE THREAD

**Issue by jimon** [warmcat/libwebsockets#1344]
Having symlinks that don't point to existing files (like https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/http-server/minimal-http-server-tls-80/mount-origin/w.txt ) breaks reproducable builds on teamcity. Please don't do this :)

**Comment by lws-team** [comment]
> Please don't do this :)

Is there any way to look at that and imagine it was intentional?

**Comment by jimon** [comment]
Btw, we found why our build was failing: https://github.com/gradle/gradle/issues/1365 :)
