### ISSUE TITLE
Crash in client handshake on Windows with IPV6 flag

### ISSUE THREAD

**Issue by jimon** [warmcat/libwebsockets#1348]
In `lib/roles/http/client/client-handshake.c` there are following lines:

```
       n = lws_getaddrinfo46(wsi, ads, &result);

#ifdef LWS_WITH_IPV6
	if (wsi->ipv6) {
		struct sockaddr_in6 *sa6 =
				((struct sockaddr_in6 *)result->ai_addr);

		if (n) {
			/* lws_getaddrinfo46 failed, there is no usable result */
			lwsl_notice("%s: lws_getaddrinfo46 failed %d\n",
					__func__, n);
			cce = "ipv6 lws_getaddrinfo46 failed";
			goto oom4;
		}
```

We think that if `lws_getaddrinfo46` fails, then result points to NULL and code will crash on `result->ai_addr` which happens before `if (n) {`.

For some reason it's only reproducible on Windows.

**Comment by lws-team** [comment]
Should have been fixed like 40 mins ago

https://github.com/warmcat/libwebsockets/commit/12ec2314118a5a1af8cbc85627d57c63859886ac

**Comment by jimon** [comment]
@lws-team such speed 👍
