### ISSUE TITLE
Maintaining timing ("real time") when adding threads to plugins

### ISSUE THREAD

**Issue by GordonMadden** [warmcat/libwebsockets#1350]
My existing lws project consists of:
   LSWSW running on a linux single-board computer with all libraries on board.
   A motor control plugin with two non-terminating threads, one for sending motor packets and one for receiving
   A GPS receive plugin with a single, non-terminating thread

This part of the project has been up for awhile and is running smoothly.
Recently, I tried to add a third plugin for a sensor using the same basic setup as my other two plugins. Adding the plugin caused the motor packets to vary their timing, so the motors ran rough. Even with most of the code commented out in the sensor plugin, it still affected the motors. Finally, I commented out the LWS_CALLBACK_SERVER_WRITEABLE case and the motors were smooth again.

Then, I thought I could add the sensor code to the motor plugin, but got similar results. Just adding another thread to the plugin affected the timing.
So, my question is: How do I structure my code within the lws framework so that all four threads can run? I'm assuming I am not taking advantage of part of lws and not running into a limit on the number of threads that can be processed.
Thanks for your help.

**Comment by lws-team** [comment]
So... in the new plugin, what exactly are you doing in LWS_CALLBACK_SERVER_WRITEABLE?

It sounds like you are doing something that blocks there for some time.

Use gettimeofday() around your writeable callback to understand what the existing code there wants to do that makes trouble.

**Comment by GordonMadden** [comment]
So, starting with the working system, I add a plugin (debug, rather than release), compile the library, add it to the config file. In the plugin, I create a thread (from lws init protocol) with an empty while loop. Here is the contents of callback server writable (JSON for ADC output of voltage, and calculated elevation):
```
                //---------------------------------------------------------------
		case LWS_CALLBACK_SERVER_WRITEABLE:
		//---------------------------------------------------------------
			n = lws_snprintf((char *)p, sizeof(buf) - LWS_PRE, 	\
				"{	\"SigV\"	:\"%d\",					\
					\"Elev\"	:\"%f\"}",					\
					im.signal,
					im.elevation );

			m = lws_write(wsi, p, n, LWS_WRITE_TEXT);
			if (m < n) {
				lwsl_err("ERROR %d writing to imeter socket\n", n);
				return -1;
			}
			break;
```
And the motors are choppy.
If I comment out everything in the above case statement (except the break), the motors run fine.
So, that bit of JSON is making a difference?
I have a setup that works, I just want to expand it a bit. There is practically nothing in the new plugin. Other than structs and protocol stuff for lws, I only create a thread with a while loop.

Posting entire  plugin below:
 `/*
*
*	INCLINOMETER LWSWS WEB SERVER PROTOCOL HANDLER
*
*	Project:	Satellite Dish Positioning System
*	
*	Purpose:	Calculates and sends elevation to GUI for display
*
*	Inputs:		Power to inclinometer sensor
*
*	Outputs:	Signal Reference (J1-3) and Signal Output (J1-4)
*
*	Narrative:	In addition to being based on motor position, elevation will be sensed by
*				a single-axis inclinometer with a ratiometric output and displayed on the GUI. 
*				The four (4) connections to the sensor are:
*					J1-1 - power supply (5Vdc)
*					J1-2 - ground
*					J1-3 - reference voltage out
*					J1-4 - signal out
*
*					J2-1 - Jumper pins will be shorted
*					J2-2 - 
* 
*				The ref voltage (Vcc/2) and signal voltage (0-Vcc) are both used in the
*				calculation of elevation. For any change in Vcc, the ref voltage will 
*				always be 50% of the supplied voltage. Therefore, the output will always
*				be proportional to elevation.  
*
*	Author:		Gordon Madden
*
*	Copyright:	©2018 Lime Rock LLC
*
*/

//--------------------------------------------//
//  PREPROCESSOR DIRECTIVES                   //
//--------------------------------------------//
#define _GNU_SOURCE

#define _POSIX_C_SOURCE 199309

//#define PRINT

#define LWS_DLL
#define LWS_INTERNAL

#define SYSCON_ADDRESS  0xe8000000

#include "../lib/libwebsockets.h"

#include <assert.h>		// Defines the assert() macro for program assertion
#include <errno.h>		// Error numbers
#include <fcntl.h>		// File control options, read/write functions
#include <math.h>		// for absolute value calculations
#include <pthread.h>	// for separate thread for sending motor packets
#include <sched.h>		// for changing scheduler priority for motor timing
#include <semaphore.h>  // mutex defs for threads
#include <signal.h>		// for signal handling for packet timer, SIG_EV signal and thread
#include <stdint.h>		// UNIX standard function definitions
#include <stdio.h>		// Standard buffered input/output
#include <stdlib.h>		// Standard library definitions
#include <string.h>		// String operations
#include <sys/mman.h>	// Memory management declarations -- used for mmap() here
#include <sys/signal.h> // 
#include <sys/stat.h>	// data returned by the stat() function
#include <sys/time.h>	// Time data for packet timing
#include <sys/types.h>	// Data types definitions
#include <sys/wait.h>	// 
#include <termios.h>	// Defines the terminal control structure and POSIX control functions
#include <time.h>		// Time data for packet timing, POSIX timers
#include <unistd.h>		// UNIX standard symbolic constants and types

#include "twsi.h"		// Two Wire Serial Interface definitions

//--------------------------------------------//
//  GLOBAL VARIABLES                          //
//--------------------------------------------//
pthread_t 						imThread;
int 							testPrint;

volatile unsigned int 			*data, *control, *status;
volatile long int 				delay;
static volatile sig_atomic_t 	gotAlarm = 0;			// Set nonzero on receipt of SIGALRM 

struct per_vhost_data__imeter {
	uv_timer_t timeout_watcher;
	struct lws_context *context;
	struct lws_vhost *vhost;
	const struct lws_protocols *protocol;
};

struct per_session_data__imeter {
	unsigned int signal;
	double elevation;
};

struct per_session_data__imeter im = {
	.signal   		= 0,
	.elevation		= 0
};

//--------------------------------------------//
//  FUNCTION DECLARATIONS                     //
//--------------------------------------------//

void 			InitTimer			( void );
void 			InitPosixTimer		( void );

void 			CreateImeterThread	( void );
void 			*CalculateElevation	( void *arg );

void 			InitADC 			( void );
unsigned int 	GetADC				( int channel );
void 			Twi_select			( unsigned char addr, unsigned char dir );
void 			Twi_write			( unsigned char dat );
unsigned char 	Twi_read			( void );
unsigned int 	Service_adc			( void );


//-------------------------------------------------------------------------------------
void CreateImeterThread ( void ) 
//-------------------------------------------------------------------------------------
{
	int err = -1; 

	err = pthread_create( &imThread, NULL, &CalculateElevation, NULL );

#ifdef PRINT
	if (err != 0)
            printf("\ncan't create IMETER thread :[%s]\n\n", strerror(err));
        else
            printf("\nIMETER THREAD created successfully\n\n");
#endif
}


//-------------------------------------------------------------------------------------
static void sigalrmHandler(int sig) 
//-------------------------------------------------------------------------------------
{
	gotAlarm = 1;
}


// Timer for inclinometer sampling (1000Hz). Uses kernel timer
//-------------------------------------------------------------------------------------
void InitTimer( void ) 
//-------------------------------------------------------------------------------------
{
	struct itimerval interval_IM;
	struct sigaction sa_IM;

	// Set up SIGHANDLER
	sigemptyset(&sa_IM.sa_mask);
	sa_IM.sa_flags = 0;
	sa_IM.sa_handler = sigalrmHandler;
	sigaction(SIGALRM, &sa_IM, NULL);

	// Set the starting value and interval
	interval_IM.it_value.tv_sec 	= 0;				// secs
	interval_IM.it_value.tv_usec 	= 10000;				// µsecs

	interval_IM.it_interval.tv_sec 	= 0;				// secs
	interval_IM.it_interval.tv_usec = 10000;				// µsecs, 1000µs = 1000Hz

	setitimer(ITIMER_REAL, &interval_IM, 0);
}


//-------------------------------------------------------------------------------------
void InitPosixTimer	( void )
//-------------------------------------------------------------------------------------
{
	int posixTimerOkay;
	posixTimerOkay = timer_create(clockid_t clockid, struct sigevent *evp, timer_t *timerid );
	printf("posix timer create returns: %d", posixTimerOkay);
}


//-------------------------------------------------------------------------------------
static void uv_timeout_cb_imeter(uv_timer_t *w
#if UV_VERSION_MAJOR == 0
		, int status
#endif
//-------------------------------------------------------------------------------------
)
{
	struct per_vhost_data__imeter *vhd = lws_container_of(w,
			struct per_vhost_data__imeter, timeout_watcher);
	lws_callback_on_writable_all_protocol_vhost(vhd->vhost, vhd->protocol);
}

//-------------------------------------------------------------------------------------
static int callback_imeter(struct lws *wsi, enum lws_callback_reasons reason,
			void *user, void *in, size_t len)
//-------------------------------------------------------------------------------------
{
	struct per_session_data__imeter *pss =
			(struct per_session_data__imeter *)user;
	struct per_vhost_data__imeter *vhd =
			(struct per_vhost_data__imeter *)
			lws_protocol_vh_priv_get(lws_get_vhost(wsi),
					lws_get_protocol(wsi));
	unsigned char buf[LWS_PRE + 512];
	unsigned char *p = &buf[LWS_PRE];
	int n, m;

	switch (reason) {
		//---------------------------------------------------------------
		case LWS_CALLBACK_PROTOCOL_INIT:
		//---------------------------------------------------------------
			vhd = lws_protocol_vh_priv_zalloc(lws_get_vhost(wsi),
					lws_get_protocol(wsi),
					sizeof(struct per_vhost_data__imeter));
			vhd->context = lws_get_context(wsi);
			vhd->protocol = lws_get_protocol(wsi);
			vhd->vhost = lws_get_vhost(wsi);
			uv_timer_init(lws_uv_getloop(vhd->context, 0),
				      &vhd->timeout_watcher);
			uv_timer_start(&vhd->timeout_watcher,
				       uv_timeout_cb_imeter, 500, 500);
			break;

		//---------------------------------------------------------------
		case LWS_CALLBACK_PROTOCOL_DESTROY:
		//---------------------------------------------------------------
			if (!vhd)
				break;
			lwsl_notice("imeter: LWS_CALLBACK_PROTOCOL_DESTROY: v=%p, ctx=%p\n", vhd, vhd->context);
			uv_timer_stop(&vhd->timeout_watcher);
			uv_close((uv_handle_t *)&vhd->timeout_watcher, NULL);
			break;


		//---------------------------------------------------------------
		case LWS_CALLBACK_ESTABLISHED:
		//---------------------------------------------------------------
  
  			break;

		//---------------------------------------------------------------
		case LWS_CALLBACK_SERVER_WRITEABLE:
		//---------------------------------------------------------------
			n = lws_snprintf((char *)p, sizeof(buf) - LWS_PRE, 	\
				"{	\"SigV\"	:\"%d\",					\
					\"Elev\"	:\"%f\"}",					\
					im.signal,
					im.elevation );

			m = lws_write(wsi, p, n, LWS_WRITE_TEXT);
			if (m < n) {
				lwsl_err("ERROR %d writing to imeter socket\n", n);
				return -1;
			}
			break;

		//---------------------------------------------------------------
		case LWS_CALLBACK_RECEIVE:
		//---------------------------------------------------------------
			if (len < 6)
				break;
			
			if (strcmp((const char *)in, "closeme\n") == 0) {
				lwsl_notice("imeter: closing as requested\n");
				lws_close_reason(wsi, LWS_CLOSE_STATUS_GOINGAWAY,
						 (unsigned char *)"seeya", 5);
				return -1;
			}
			break;

	default:
		break;
	}

	return 0;
}


#define LWS_PLUGIN_PROTOCOL_IMETER 										\
	{ 																	\
		"imeter-protocol", 												\
		callback_imeter, 												\
		sizeof(struct per_session_data__imeter), 						\
		10, /* rx buf size must be >= permessage-deflate rx size */ 	\
		0, NULL, 0 														\
	}


static const struct lws_protocols protocols[] = {
	LWS_PLUGIN_PROTOCOL_IMETER
};

//-------------------------------------------------------------------------------------
LWS_VISIBLE int init_protocol_imeter(struct lws_context *context,
			     struct lws_plugin_capability *c)
//-------------------------------------------------------------------------------------
{
	// Put init stuff here:
	//InitTimer			();
	//InitPosixTimer		();
	//InitADC				();
	CreateImeterThread	();

		// Clock to read data from the sensor?

		//im_rx_fd = InitPort("dev/ttts6", O_RDONLY | O_NOCTTY, B115200 );

		//InitUart();

	if (c->api_magic != LWS_PLUGIN_API_MAGIC) {
		lwsl_err("Plugin API %d, library API %d", LWS_PLUGIN_API_MAGIC,
			 c->api_magic);
		return 1;
	}

	c->protocols = protocols;
	c->count_protocols = ARRAY_SIZE(protocols);
	c->extensions = NULL;
	c->count_extensions = 0;

	return 0;
}

//-------------------------------------------------------------------------------------
LWS_VISIBLE int destroy_protocol_imeter(struct lws_context *context)
//-------------------------------------------------------------------------------------
{
	return 0;
}



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * *                               * * * * * * * * * * * * * * * *
 *		                       END OF WEB SERVER CODE                                  *
 * * * * * * * * * * * * *                               * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


//-------------------------------------------------------------------------------------
void *CalculateElevation( void *arg )
//-------------------------------------------------------------------------------------
{

	while( 1 ) {
			
	}
}


//-------------------------------------------------------------------------------------
void InitADC( void )
//-------------------------------------------------------------------------------------
{
	int fd = -1;
	unsigned int *twi_register;
	
	//Open '/dev/mem'
	fd = open("/dev/mem", O_RDWR|O_SYNC);
	assert(fd > 0);
	
	//Initialize twsi memory and wires
	twi_register = (unsigned int *)mmap(0, getpagesize(), PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0xF1011000);
	control	= twi_register + CONTROL;
	data	= twi_register + DATA;
	status	= twi_register + STATUS;
	
	//Select self as I2C master and send start signal
	twi_select(AVR_ADDR, WRITE);
	twi_write(OTP_R);
	twi_write(157);
	
	//Send stop signal
	*control = STOP|TWSIEN;

	printf("ADC init completed\n");
}


//-------------------------------------------------------------------------------------
unsigned int GetADC( int channel )
//-------------------------------------------------------------------------------------
{
	volatile long int delay, i;
	static unsigned int buffer[4];
	unsigned int value = 0;
	
	if(channel == 7) {
		channel = 5;
	}
	
	//Write channel information to slave
	twi_select(AVR_ADDR, WRITE);
	twi_write((1 << channel) | 0x40);

#ifdef PRINT
	printf("reading channel %d\n", channel);
#endif
	
	//Send stop signal
	*control = STOP|TWSIEN;
	for(delay = 0; delay < 25000; delay++); //Arbitrary timer
	
	//Read ADC and average result
	for(i = 4 - 1; i >= 1; i--){
		buffer[i] = buffer[i-1];
		value += buffer[i];
	}
	buffer[0] = service_adc() & 0xfff;
	value += buffer[0];
	value >>= 2;
	
	return value;
}


//-------------------------------------------------------------------------------------
void Twi_write(unsigned char dat)
//-------------------------------------------------------------------------------------
{
	volatile int delay;
	unsigned int cur_status;
	
	//Send data
	*data = dat;
	for(delay = 0; delay < 60; delay++); //Necessary timer
	
	//Send acknowledge signal
	*control = ACK;
	for(delay = 0; delay < 60; delay++); //Necessary timer
	
	//Wait for an I2C event
	while((*control & IFLG) == 0x0);

	cur_status = *status;
	//while( !(cur_status == ST_DATA_ACK) || !(cur_status == MT_DATA_ACK )); 
	//assert((cur_status == ST_DATA_ACK) || (cur_status == MT_DATA_ACK )); 

	if((cur_status == ST_DATA_ACK) || (cur_status == MT_DATA_ACK )) {
		//printf("write pass");
	} else {
		//printf("write fail");
	}
}

	
//-------------------------------------------------------------------------------------
unsigned char Twi_read( void )
//-------------------------------------------------------------------------------------
{
	volatile int delay;
	unsigned int cur_status;

	*control = (*control & ~IFLG) | ACK;
	for(delay = 0; delay < 60; delay++); //Necessary timer
	
	//Wait for an I2C event
	while((*control & IFLG) == 0x0);
	
	cur_status = *status;
	if((cur_status != SR_DATA_ACK) && (cur_status != MR_DATA_ACK)) return -1;

	return (unsigned char)*data;
}


//-------------------------------------------------------------------------------------
void Twi_select(unsigned char address, unsigned char write_read)
//-------------------------------------------------------------------------------------
{
	volatile int delay;
	unsigned int cur_status;

	//Loop until start is successful
	do{
		//Send start signal
		*control = START|TWSIEN;
		for(delay = 0; delay < 1000; delay++); //Arbitrary timer
		
		//Wait for control status
		while((*control & IFLG) == 0);
			
	} while((*status != MT_START) && (*status != MT_REP_START));
	
	/* The following for() delay is ABSOLUTELY NECESSARY otherwise
	 * the Marvel TWSI controller shifts out wrong data as the SLA+W.
	 * There is no official documentation or errata regarding this but
	 * there is a clue in Marvell supplied TWSI Linux code: 
	 * arch/arm/mach-mv88fxx81/Soc/mvTwsi.c line 276 after it adds an 
	 * arbitrary 1ms delay with a comment: "Wait 1 milli to prevent TWSI
	 * write after write problems"
	 *  
	 * The below for() loop however was the only one that seemed
	 * necessary for proper operation while testing.  However, after
	 * discovering that comment of code, delays were added after EVERY
	 * TWSI register write.  
	 *
	 * The number 60 is precisely 2x the required number of 30
	 * discovered during testing.  --joff
	 */
	
	//Send slave address + Write/Read
	*data = address | write_read;
	for(delay = 0; delay < 60; delay++); //Necessary timer
	
	//Send acknowledge signal
	*control = ACK|TWSIEN;
	for(delay = 0; delay < 60; delay++); //Necessary timer
	
	while((*control & IFLG) == 0);
	
	//Assert that the slave has acknowledged
	cur_status = *status;

	//while( !(cur_status == MT_SLA_ACK) || !(cur_status == MR_SLA_ACK));
	//assert((cur_status == MT_SLA_ACK) || (cur_status == MR_SLA_ACK));

	if((cur_status == MT_SLA_ACK) || (cur_status == MR_SLA_ACK)) {
		//printf("select pass");
	} else {
		//printf("select fail");
	}
}


//-------------------------------------------------------------------------------------
unsigned int Service_adc( void )
//-------------------------------------------------------------------------------------
{
	unsigned int read = 0, value = 0;
	
	//Read from the ADC
	twi_select(AVR_ADDR, READ);
	
	//Loop until 0xff00 is recieved
	while(1){
		read = twi_read() << 8;
		if(read == 0xff00) break;
		read |= twi_read();
		value = read;
	}
	
	//Send stop signal
	*control = STOP|TWSIEN;
	return value;
}


//-------------------------------------------------------------------------------------
static void Exit_gracefully() 
//-------------------------------------------------------------------------------------
{
	fprintf(stderr, "EXITING....\n");
	*control = STOP|TWSIEN; // Send stop signal
	exit(0);
}

`

**Comment by lws-team** [comment]
Happily I'm not responsible for your whole system, you are.  I don't have any reason to care about it outside of something wrong with lws.  So rather than doing a code dump on me and expecting a solution, tying your problem to something actionable in lws is the way to go --->

> Use gettimeofday() around your writeable callback to understand what the existing code there wants to do that makes trouble.

You say the writable callback existing makes trouble... how often is it called?  How long does it take?  Where's the evidence?  What are you asking me to do?  "make everything work"?  Not my problem...

**Comment by GordonMadden** [comment]
Sorry!
I'm sure I'll figure it out.
Thank you for your time.
