### ISSUE TITLE
for receive a file

### ISSUE THREAD

**Issue by gyplol** [warmcat/libwebsockets#1352]
I use the old version of Library file before (libwebsockets.so.10),and I use the follow code to receiving a file,it is still useful for me, but the writed content are disorder after i change the new version of Library file.The sender can't transmit the serial number for me. So I wanna got the reason in order to solve this problem .Thank you ! ps:I am a  rookie...

static int callback_file_increment(struct lws *wsi, enum lws_callback_reasons reason,
					void *user, void *in, size_t len)
{
	FILE *fd = fopen("/usr/local/boa/download.tar","ab+");
    switch (reason) {

        case LWS_CALLBACK_ESTABLISHED:
            printf("[File Service] Connection established.\n");	
            break;

        case LWS_CALLBACK_RECEIVE:
		
			if( !strcmp ("webpage_send_completed", (char *)in ))
			{
				fclose(fd);
				system("tar -xf /usr/local/boa/download.tar -C /usr/local/boa/");
				system_state();
				system("rm /usr/local/boa/download.tar");
			}	
			else if( !strcmp ("firmware_send_completed", (char *)in ) )
			{
				fclose(fd);
				lws_context_destroy(context);
				system("./restart.sh &");
				exit(0);
			}
			else
				fwrite((char *)in,len,1,fd);
			
			lws_callback_on_writable(wsi);
            break;
			
    case LWS_CALLBACK_CLOSED:
			printf("[File Service] Rev Over Client close.\n");
			break;

    default:
            break;
    }	
    return 0;
}

**Comment by lws-team** [comment]
> received content are disorder

You should find out what it means "disordered" exactly.

Compare what you sent and what you stored... how are they different?

websockets is on top of tcp, it can't receive stuff out of order.  So... how exactly is it different?

**Comment by gyplol** [comment]
oh~sorry ,this is wirte in file disorderedly,now it is ok after i change my core, thanks!
