### ISSUE TITLE
How to read custom http headers or body in client side when it is established or failed.

### ISSUE THREAD

**Issue by ghmlee** [warmcat/libwebsockets#1353]
First of all, thanks for building wonderful this open source.

I looked libwebsockets.h and found enum lws_token_indexes. So, there are pre-built keys for reading http headers with lws_hdr_copy() and lextable.h from lextable-string.h and minilex.c.

Is there another way to read http headers with custom keys? or can I get raw http body when it is established or failed?

**Comment by ghmlee** [comment]
@lws-team Thanks.

I am building a WebSocket API for an application. My point is that this API is only for authenticated users. I don't want to waste my WebSocket connection pools for non-authenticated users in server side. When it is established a connection between client and server, I just checked a kind of API key in http header. In a case of non-authenticated user, they will have a normal http response without websocket connection. At this time, server should return custom http header or body for graceful error handling to even non-authenticated users.

**Comment by lws-team** [comment]
You can use a standard header for this, `authorization`... it has the advantage it's defined that no intermediary should cache it.

https://tools.ietf.org/html/rfc7235#section-4.2

```
authorization: yourscheme whatever
```

So long as "yourscheme" doesn't collide with one of the 10 official schemes

http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

You can put what you like after the scheme name, consistent with http header syntax.  Eg basic auth uses bas64 coding for its content there.
