### ISSUE TITLE
Can i build lws in vs2010 ?(version tag 2.1 stable)

### ISSUE THREAD

**Issue by midGitub** [warmcat/libwebsockets#1356]
![image](https://user-images.githubusercontent.com/20261416/43451620-f089fbb4-94e7-11e8-9dca-d13f61f61b43.png)
when i use cmake and build the project  with vs 2010, it report these problems. and i need to build in this version of vs.

**Comment by lws-team** [comment]
No idea... the errors are in chinese even...

Lws master builds with 1 warning currently and no errors on appveyor with later ms compiler.

https://ci.appveyor.com/project/lws-team/libwebsockets/build/job/hj2256gwt4enj15p

So I think no problem on lws side.  We don't use any new language features or special api or dll or whatever afaik.

> and i need to build in this version of vs.

I don't... so while I'm willing to help if there's something small I can do to make it easier, you'll need to figure out what that might be.  Or upgrade your tools.

**Comment by midGitub** [comment]
thanks for your reply. the vs error seems that i need to build it with a higher vs  version. but my working project is a bit old. need to build it in vs2010. Can you build it in vs2010  compiler... or c99 standard.
and i suggest to build a gitter chat room for normal discussion .hah.

**Comment by midGitub** [comment]
i will try to checkout a old version to build the project later.

**Comment by lws-team** [comment]
Of course it builds under C99.

No point looking for old version of lws... as on appveyor it builds fine as it is.
