### ISSUE TITLE
Issue found during Static Analysis

### ISSUE THREAD

**Issue by sgawarikar** [warmcat/libwebsockets#1357]
Hi,

I am using coverity tool for static analysis. I ran the tool on this library as I am using this library(v3.0) for websocket & json parsing.
I have found the issue "Out-of-bounds read" in the lejp.c file as below snapshot:

![coverity_lib](https://user-images.githubusercontent.com/26919816/43459115-16354934-94ea-11e8-9de9-d219fbf32faf.PNG)

I would like to suggest to use static tool to capture such issues.

Solution: Can I add the check (of <255)before decrementing ctx->sp?

Regards,
Sumedha

**Comment by lws-team** [comment]
Lws is already checked by coverity

https://scan.coverity.com/projects/warmcat-libwebsockets

But I use their FOSS service, it has limits to the number of builds you can check in a short period; I can't check every push.  So I use it while leading up to a release to ensure there are no oustanding problems then.

If you don't have such a restriction, can you see if checking ctx->sp is nonzero before the decrement solves it?

**Comment by lws-team** [comment]
Never mind, looking at it there are a couple of things around there needing solving.  I pushed a patch on v3.0-stable and master.  And I ran master through coverity and fixed some other issues since last time on master.
