### ISSUE TITLE
[Question]How to make libwebsockets only trust my two specific root certificates

### ISSUE THREAD

**Issue by nezen** [warmcat/libwebsockets#1359]
I'm going to use libwebsockets as a client, can I make libwebsockets only trust my two specific root certificates? Thanks

**Comment by lws-team** [comment]
Yes... with OpenSSL TLS backend it will use your system CA store by default, but you can override it using this

https://libwebsockets.org/git/libwebsockets/tree/lib/libwebsockets.h#n2589-2591

With mbedTLS as your TLS backend it doesn't know about your system CA store even by default.

**Comment by nezen** [comment]
@lws-team Thanks, very nice of you!  so I have to use other TLS libs than OpenSSL to load my own CA ?
By the way, would you please give me a clue about how to adapt mbedTLS to libwebsockets and load my own CA?

**Comment by lws-team** [comment]
>  so I have to use other TLS libs than OpenSSL to load my own CA ?

Not at all... with OpenSSL you have to stop it using the system trusted CAs as I described.

Then, same as if using mbedTLS, you can pass it a PEM with your CAs in

```
	const char *client_ssl_ca_filepath;
	/**< VHOST: Client SSL context init: CA certificate filepath or NULL */
```
when you create the vhost(s).

With mbedTLS it doesn't know about your system CAs anyway so you can just do the second part.

If you want to use mbedTLS, then:

https://libwebsockets.org/git/libwebsockets/tree/CMakeLists.txt#n46

but mbedTLS is not a requirement.

**Comment by nezen** [comment]
@lws-team VERY HELPFUL, THANKS !

**Comment by nezen** [comment]
@lws-team Hi Mr. Green，sorry to bother you again, would you please tell me how to send and receive json with a libwebsockets client? 

I tried to send a json text like this:
case LWS_CALLBACK_CLIENT_WRITEABLE:
        l += sprintf((char *)&buf[LWS_PRE + l], "{\\\"key\\\":\\\"value}");
        n = lws_write(wsi, &buf[LWS_PRE], l, opts | LWS_WRITE_TEXT);

I tried LWS_WRITE_TEXT and LWS_WRITE_HTTP, but it seems sth is wrong, the server just closed my connection after I sent this msg.

**Comment by lws-team** [comment]
> value}");

You need another `\"` at the end of value.

**Comment by nezen** [comment]
@lws-team sorry for that, actually here is my real code:
`
l += sprintf((char *)&buf[LWS_PRE + l], "[{\\\"namespace\\\":\\\"playerVolume:1\\\",\\\"command\\\":\\\"setVolume\\\",\\\"householdId\\\":\\\"Sonos_Wx5DAdWiNP8P8TYGyH4LpZyO1P.FsMUr4m1ano-c0uCNuv6\\\",\\\"playerId\\\":\\\"RINCON_B8E937DB1A4001400\\\"},{\\\"volume\\\":80}]");
`

anything that might go wrong for this so far?

**Comment by nezen** [comment]
@lws-team or would you please give me a clue where can I find the specific code that sends that string into the websocket?

**Comment by lws-team** [comment]
You do not need all those backslashes, it isn't bash shell it's C.

Change every `\\\` to just `\`

There's no magic about "sending JSON".  Just don't turn it into junk with extra backslashes.

**Comment by BurakOzkan** [comment]
> https://libwebsockets.org/git/libwebsockets/tree/lib/libwebsockets.h#n2589-2591

can you show it in the new version @lws-team 
Thank you

Error:
Path 'lib/libwebsockets.h' doesn't exist in revision 'refs/heads/master'

**Comment by lws-team** [comment]
```
        LWS_SERVER_OPTION_DISABLE_OS_CA_CERTS                   = (1 << 6),
        /**< (VH) Don't load OS CA certs, you will need to load your
         * own CA cert(s) */
```

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n65-67
