### ISSUE TITLE
Error Cross Compile ARM9 (ARMv5)

### ISSUE THREAD

**Issue by beyonlo** [warmcat/libwebsockets#136]
Hello, I trying to compile the libwebsockets com arm9 (ARMv5).
Are there errors finding in6addr.h, vfork.h and zlib.h.
How I disable to don't get that erros?
I tryed "cmake -LH .." but nothing!

build$ cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_TOOLCHAIN_FILE=../cross-arm-linux-gnueabihf.cmake -DWITHOUT_EXTENSIONS=0 -DWITH_SSL=0
-- The C compiler identification is GNU 4.4.5
-- The CXX compiler identification is GNU 4.4.5
-- Check for working C compiler: /opt/arm-davinci-linux-uclibcgnueabi/bin/arm-davinci-linux-uclibcgnueabi-gcc
-- Check for working C compiler: /opt/arm-davinci-linux-uclibcgnueabi/bin/arm-davinci-linux-uclibcgnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/arm-davinci-linux-uclibcgnueabi/bin/arm-davinci-linux-uclibcgnueabi-g++
-- Check for working CXX compiler: /opt/arm-davinci-linux-uclibcgnueabi/bin/arm-davinci-linux-uclibcgnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_TOOLCHAIN_FILE='/home/pi/tmp/websocket/libwebsockets/cross-arm-linux-gnueabihf.cmake'
-- Found Git: /usr/bin/git  
Git commit hash: dfca3ab
-- Performing Test HAVE_inline
-- Performing Test HAVE_inline - Success
-- Performing Test HAVE___inline__
-- Performing Test HAVE___inline__ - Success
-- Performing Test HAVE___inline
-- Performing Test HAVE___inline - Success
-- Looking for bzero
-- Looking for bzero - found
-- Looking for fork
-- Looking for fork - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for in6addr.h
-- Looking for in6addr.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for zlib.h
-- Looking for zlib.h - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pid_t
-- Check size of pid_t - done
-- Check size of size_t
-- Check size of size_t - done
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindZLIB.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:459 (find_package)

-- Configuring incomplete, errors occurred!

------------------

Here is my cross-arm-linux-gnueabihf.cmake:

$ cat ../cross-arm-linux-gnueabihf.cmake 
#
# CMake Toolchain file for crosscompiling on ARM.
#
# This can be used when running cmake in the following way:
#  cd build/
#  cmake .. -DCMAKE_TOOLCHAIN_FILE=../cross-arm-linux-gnueabihf.cmake
#

set(CROSS_PATH /opt/arm-davinci-linux-uclibcgnueabi)

# Target operating system name.
set(CMAKE_SYSTEM_NAME Linux)

# Name of C compiler.
set(CMAKE_C_COMPILER "${CROSS_PATH}/bin/arm-davinci-linux-uclibcgnueabi-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_PATH}/bin/arm-davinci-linux-uclibcgnueabi-g++")

# Where to look for the target environment. (More paths can be added here)
set(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")

# Adjust the default behavior of the FIND_XXX() commands:
# search programs in the host environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search headers and libraries in the target environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

-------------------

Thank you.

**Comment by 249708193o** [comment]
have you resolver it?If you have resolution,it would be great thank for shareing!!

**Comment by warmcat** [comment]
These are just basic cross-build questions... you need to import native libs + includes to your build system to build against them with the cross compiler.

It's MUCH simpler to build the library native on the Arm board using native Arm gcc on there.

You can remove the dependency on libz by disabling extensions at cmake and in6addr.h by disabling IPV6 at cmake.
