### ISSUE TITLE
lws_context_attach_deprecated is missing

### ISSUE THREAD

**Issue by galuha** [warmcat/libwebsockets#1361]
Hello.
In the lws_context_deprecate() function description there is an lws_context_attach_deprecated() function reference, which is missing in the library.
If the lws_context_attach_deprecated() func is deprecated, what is an appropriate way to replace context with another? We need it when the certificates get updated.
Or maybe there is a better way to update certs for a wss server?

**Comment by lws-team** [comment]
Nothing is missing unless you're on windows... you just call `lws_context_deprecate()` ... look at how lwsws does it.

https://libwebsockets.org/git/libwebsockets/tree/lwsws/main.c#n92-97
https://libwebsockets.org/git/libwebsockets/tree/lwsws/main.c#n182-192
https://libwebsockets.org/git/libwebsockets/tree/lwsws/main.c#n250-263

**Comment by galuha** [comment]
Thanks.
I meant this:

[andrey@localhost libwebsockets]$ grep -nr lws_context_attach_deprecated
lib/libwebsockets.h:3088: *	context when it has been created using lws_context_attach_deprecated()
build/include/libwebsockets.h:3088: *	context when it has been created using lws_context_attach_deprecated()

lws_context_attach_deprecated() - mentioned but doesn't exist. It misguided me to think of implementing something different from main.c example. Thanks for your answer. But if it wasn't there I wouldn't have to ask.

**Comment by lws-team** [comment]
> But if it wasn't there I wouldn't have to ask.

Yeah.  That must be so annoying when the freebie that does exactly what you want has some outdated docs.

**Comment by galuha** [comment]
You are right). I'll make a pull request

**Comment by lws-team** [comment]
I already fixed it on master a few days ago... which was thanks to your pointing it out to be fair.

**Comment by galuha** [comment]
Cool
