### ISSUE TITLE
Private definitions shouldn't be in libwebsockets.h

### ISSUE THREAD

**Issue by ralight** [warmcat/libwebsockets#1370]
Could you please remove all of the definitions from libwebsockets.h that are not part of your public interface?

For example, you define ARRAY_SIZE, strcasecmp, getdtablesize() in libwebsockets.h and they are only needed internally to the project. If a project using libwebsockets defines any of those macros themselves then they will have lots of compile time warnings.

**Comment by lws-team** [comment]
It seems that'd be a good thing.

ARRAY_SIZE I thought had already gone in favour of LWS_ARRAY_SIZE... actually there is both defined, so it needed clearing out anyway.

ARRAY_SIZE is used in dozens of places outside the library part, in the examples, where the protocols can be built standalone.  But I agree it's better not to redefine such a common thing and use LWS_ARRAY_SIZE.

This will break user code who relied on us defining it... they just need to change to use LWS_ARRAY_SIZE().

But it's at least even before it's like this:

```
#ifndef ARRAY_SIZE
#define ARRAY_SIZE(x) (sizeof(x) / sizeof(x[0]))
#endif
```

if your other project had taken the same precaution that one at least should have worked fine... maybe complain at them for not even taking as much care as I did...

strcasecmp and getdtablesize are also our working around windows not having normal things, I guess the other project faced the same problems.

I pushed patches on v3.0-stable and master removing ARRAY_SIZE altogether, migrating internal users to LWS_ARRAY_SIZE and moving strcasecmp() and getdtablesize() into ./lib/core/private.h.

**Comment by ralight** [comment]
That's great, thanks.
