### ISSUE TITLE
Loading "big picture" from test server takes about 30 seconds on Windows

### ISSUE THREAD

**Issue by f69m** [warmcat/libwebsockets#1371]
Hi, love your library, it just does what I need and then gets out of the way. Thanks!

However, I noticed that on Windows loading the "big picture" from the test server takes about 30 seconds. Running the server on Linux it loads in about 0.5 seconds. This happens in both "master" and "v3.0-stable" branches.

The test server on Windows was compiled using the Visual Studio 2017 "Open Folder" feature that directly load CMakeLists.txt without generating project files first. LWS_WITH_SSL was set to OFF, everything else was left at default. Just to be sure, I tried both the x86-Release and the x64-Release builds.

This seems to be connected with LWS_CALLBACK_HTTP_WRITEABLE being called with some delay.

**Comment by lws-team** [comment]
The windows stuff is completely contributed... the quality of it depends on windows users looking after it.  I maintain it generally, look after the CI in Appveyor and fix build problems, but I don't have any windows here and don't want any.

This is a known problem with the WSA stuff used in the windows platform at the moment, it can't interrupt its poll wait from the server side... read through this (open) issue

https://github.com/warmcat/libwebsockets/issues/1291

It sits in a poll wait here

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/windows/windows-service.c#n128-173

You can work around it a bit by reducing the timeout value passed in the service call in the user code, it will exit from the poll wait more often then, but that has implications for idle CPU.

It would be great if you could find the time to help debug and fix the underlying problem and provide a patch...

**Comment by f69m** [comment]
Oops, I should have noticed that issue applies to mine, sorry. Thanks for the quick answer!

Honestly, the Windows API is not my strength either, but I did some reading up and found a good candidate for causing this: with WSAEventSelect the FD_WRITE event is not level-triggered, which means it is not triggered, whenever writing is possible. It is only triggered, when a socket is first connected (connect() or accept()), and after send() has failed with WSAEWOULDBLOCK. In other words: when sending some small amount of data goes well, FD_WRITE will not trigger on the next call to WSAWaitForMultipleEvents(), but it will return only after the timeout has elapsed. I guess that is exactly, what we are seeing here.

Now I thought, before starting to trace the calls, I just throw this at you, hoping for some reaction between "no, that's fine, we handle that" and "bingo, that's the issue". I am happy to help fixing this, but I hope for some guidance, as I don't really know the code well enough.

**Comment by lws-team** [comment]
Thanks a lot for stepping up to look at it.

I think what you're suggesting was also the subject of the other thread eventually... the WSA stuff is basically broken if you compare it to posix `poll()` semantics.

A few years ago we received a patch from a windows user introducing the WSA stuff adapting to the WSA semantics by adding a flag `wsi->sock_send_blocking` to try to track if he had seen the WSAEWOULDBLOCK.  The original patch (it has been refactored and cleaned along with everything else since then) is here

https://libwebsockets.org/git/libwebsockets/commit?id=0fc37b64f6553a7433218d09a96de0ed5138f873

Although the code has changed by refactor, this shows in a nutshell the original scope of the WSA support introduction and might be useful.

**Comment by f69m** [comment]
Yeah, those subtle differences, when things look almost the same, are a PITA. Oh well...

Thanks for the link, reading that older commit helped a lot! Looks like everything is handled properly, just needed to set the timeout to zero after servicing a writable socket.

**Comment by lws-team** [comment]
Thanks again for the patches :-)
