### ISSUE TITLE
Ways to send multiple client request on the same wsi

### ISSUE THREAD

**Issue by leon6827** [warmcat/libwebsockets#1372]
Hi,

I have two issues (maybe observations) which needs some clarifications:

1. Currently I send one H2 client request vis lws_client_connect_via_info(), it creates one network wsi (nwsi) and then one h2 child wsi (h2_wsi). When I return -1 in the callback, it frees h2_wsi only. Why nwsi is not close?

2. If I want to send the same request again, seems I need to call lws_client_connect_via_info() again which creates nwsi and h2_wsi again (i.e., SSL handshake again), is there a way I can reuse the previous allocated nwsi and h2_wsi?

Thanks
-Xi

**Comment by lws-team** [comment]
(This moved here

https://libwebsockets.org/pipermail/libwebsockets/2018-August/003810.html
)
