### ISSUE TITLE
how can i monitor the ws connections (server side)

### ISSUE THREAD

**Issue by kasseller** [warmcat/libwebsockets#1381]
first, our websocket clients build the connections successfully,
then our clients disable the network, or some other network problems (not close the connection), so the server side does not know this action. and the push-messages are also into the queue, so it may lead to the memory so huge if the amounts of the clients and the messages are big.

I use the libwebsockets-v1.6

**Comment by lws-team** [comment]
> I use the libwebsockets-v1.6

If you want to use this old version, that's fine, but you are on your own. 

On later versions there is support for timed ws ping-pong "alive" checks.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n314-325
