### ISSUE TITLE
could i use lws_set_timeout to detect the connection-sate?

### ISSUE THREAD

**Issue by kasseller** [warmcat/libwebsockets#1382]
#1381
1. add the libwebsocket_callback_on_writable_all_protocol (every 50ms) in the main-loop with libwebsocket_service(context, 50);
2. add lws_set_timeout in case LWS_CALLBACK_SERVER_WRITEABLE for 10 second;
3. push the messages into tx_queue for some wsi. 

because every 50ms we reset the lws_set_timeout, so if the connection is bad, after 10 second the connection should be closed.

Is that OK?
with the new version which supports Ping-Pong may be not suitable for us, because we only build the server-side, and the client-side are public for others, and we can not be sure, if the client supports Ping-Pong.

**Comment by lws-team** [comment]
> the new version which supports Ping-Pong may be not suitable for us

My time dealing with these sterile questions about ancient versions for free is not worth less than your time a) googling that PING and PONG are part of the ws spec and b) upgrading and seeing what happens.
