### ISSUE TITLE
Compiling error with -DLWS_WITH_STATS=ON option

### ISSUE THREAD

**Issue by niyamaka** [warmcat/libwebsockets#1383]
Hi. When compiling with WITH_STATS next error occurs:
libwebsockets-master/lib/core/libwebsockets.c: In function ‘lws_stats_log_dump’:
libwebsockets-master/lib/core/libwebsockets.c:3510:13: error: ‘struct lws’ has no member named ‘ah_wait_list’; did you mean ‘child_list’?
    wl = wl->ah_wait_list;

Perphaps must be 
    wl = wl->http.ah_wait_list;

Best regards
N.

**Comment by lws-team** [comment]
Thanks... yes there are a couple of places in there I missed while doing the big role refactor stuff before v3.0.  I pushed a patch on v3.0-stable and master that should solve it.
