### ISSUE TITLE
the confused action with callback_writable when network error?

### ISSUE THREAD

**Issue by kasseller** [warmcat/libwebsockets#1386]
Dear,

here is my code: (with libwebsockets-v1.6.3)
				while(1) {
						struct timeval tv;
						gettimeofday(&tv, NULL);
						ms = (tv.tv_sec * 1000) + (tv.tv_usec / 1000);
						if ((ms - oldms) > 50) {
							lws_callback_on_writable_all_protocol(context, &protocols[0]);
							oldms = ms;
						}
						lws_service(context, 50);
				}
My question is:
when my websocket client make the connection, then disable the network, and LWS_CALLBACK_SERVER_WRITEABLE can also be involved forever, and even can be made the "lws_write" with no error forever!

in the older version, the first time "lws_write" can be excuted, but then the wsi is not writable, then the timeout can be detected, so we can remove the websocket-connection.

how can i use this method in the version-v1.6.3? thanks in advance.

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/issues/1381#issuecomment-415648504
