### ISSUE TITLE
Abbreviated handshake for SSL connections

### ISSUE THREAD

**Issue by sergiohs84** [warmcat/libwebsockets#1387]
Hi there

We are using libwebsockets in our native clients. I'd like to know if it's possible to somehow retrieve the `sessionID` from the server's response during the SSL full-handshake and, therefore, if it would be possible to use that `sessionID` in order to establish a new connection afterwards. Theoretically, it would reduce the latency for reconnection significantly.

I found code to create of new SSL sessions, also to free them, but not to set them. Perhaps not looking at the right place? Maybe there's support for TLS tickets? because I spotted `TLS_ST_CR_SESSION_TICKET` but it seems to be unused.

If abbreviated handshake were not supported, we would be considering to submit a patch, in case it's doable. Of course, any guidance would be appreciated :)

Thanks in advance

**Comment by lws-team** [comment]
Yes the general name for this is "session tickets".  However they have some severe problems as implemented in TLS1.2, the current version widely in use.

https://blog.filippo.io/we-need-to-talk-about-session-tickets/

In TLS1.3 most of the problems are fixed, but that is still under development.

If you have to mandate TLS1.3 to make it safe, it may make more sense to use http/2 instead.  This will bind future connections to a single existing negotiated tls link: it's implemented in lws for http server, http client and ws-over-h2 on server.  It doesn't help if you have periodic connections.

If you want to implement it, patches are welcome... it should be default-off and work on both openssl and mbedtls the same (by adding a per-vhost .options flag to enable it).

For OpenSSL it seems the server side is already ready to use it, you just need to make a couple of calls on the client side

https://wiki.openssl.org/index.php/SSL/TLS_Client#Session_Reuse

The places for OpenSSL to do that would be

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/openssl-client.c#n233-243
https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/openssl-client.c#n369

mbedTLS seems very similar, the layout in lws is also similar, the corresponding file is

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/mbedtls/mbedtls-client.c

**Comment by sergiohs84** [comment]
Thank you, Andy. I will check with the server team whether they plan to support TLS1.3 soon or not. In the meantime, I think we go for the older protocol.

The links posted here are very useful. Unfortunately, we are using 2.4-stable and just swapping to 3.0-stable throws an undefined reference to `lws_uv_initloop()`, despite I called CMake with `-DLWS_WITH_LIBUV=1` as always (yes, we use libuv as event loop). I'm checking how to get 3.0 working and then I'll try to prepare a PR adding an option to enable session caching.

Regards

**Comment by lws-team** [comment]
In v3.0+ the event loops got refactored and the old, different ways to start the event loops are gone... the user code is the same just needing to set the options flag at context creation time.  This lets you write one clean app framework that can use any of the event loop backends the same.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib/minimal-http-server-eventlib.c

There are a large number of these minimal examples now, it's worth looking through them.

**Comment by sergiohs84** [comment]
I've checked the minimal-example, but it seems we would need to do plenty of changes to follow that approach. Our library runs in a single-thread with libuv as event-loop, which is used for timers and for async DNS lookups also. Additionally, the eventloop serves other purposes in every loop.

That said, correct me if I'm wrong, but the minimal example seems to use in an internal eventloop commanded by `lws_service()`. If I go that way, I'd need to rewrite timers and DNS resolution too apart from other stuff.

I checked the `minimal-http-server-eventlib-foreign` example too, but it does only timers and signals, so no sockets are listened to in there. I understand I need to add the `fd` of the connection socket to the `libuv` events, but still not sure how to do it. I guess it's on the `LWS_CALLBACK_ADD_POLL_FD`. I'll keep investigating tomorrow.

Thank you

**Comment by lws-team** [comment]
... no, obviously you want to follow the -foreign minimal example since what you describe is a foreign libuv loop you want to integrate with.

They're "minimal examples", not magic code from the future that already does your whole implementation just for you.  The timers and signals demonstrate operation with the foreign loop simply and repeatably, just because the "minimal example" isn't crapped up with every libuv feature (sockets, or threads, dynamic loading, files...) implies nothing about their working or not.  In libuv they're all variations on a handle and work the same.

The event loop support is not 'raw' where you personally have to create sockets, but integrated into lws.  So you select the event loop then use lws as normal, tls, sockets, vhosts and their associatted listen sockets client, server all 'just work'.

**Comment by sergiohs84** [comment]
Unfortunately I need to switch to a different task, but I'll come back soon to adapt our code for lws 3.0 and later will continue with the SSL session resumption for abbreviated handshakes. Sorry for the inconvenience.

**Comment by lws-team** [comment]
Well, we can reopen this if and when you get back on it.

**Comment by catalinr-m** [comment]
Hello, I've opened a PR with changes that allow a client to reuse SSL sessions: #2249
It does appear to be working fine, I only hope it was the correct approach.
