### ISSUE TITLE
how can we know the close-action is by client or by server

### ISSUE THREAD

**Issue by kasseller** [warmcat/libwebsockets#1388]
#1386 
finally i use the keepAlive to solve my problem.
I do not want to use the new ping/pong because i am not sure our clients can support it! we use even Android 4.4 websocket-clients now! obviously it can not support ping/pong, and the websocket protocol about the ping/pong is not mandatory.

so, my question is:
how can i know the connection is shut down by the keepalive mechanism or by user themself?
thanks

**Comment by lws-team** [comment]
> I do not want to use the new ping/pong because i am not sure our clients

Shrug...
