### ISSUE TITLE
lws_service return fail, the log is "websocket line WSAEnumNetworkEvents() failed with error 10038"

### ISSUE THREAD

**Issue by jasmine-zhu** [warmcat/libwebsockets#1391]
we use libwebsocket on the windows to help us connecting with testing console.
In our testing scenes,we would frequently establish and close the connection,and a few hours later. the connection will be unexpectedly terminated.
So we retried with logging, which showed us websocket line WSAEnumNetworkEvents() failed with error 10038.
We don't know why for now,  guessing something related to closing so many times and the socket is not really closed.

 ps the error turns out at 2018-08-29 11:22:34.118 in our log file(which has been attached).

[ws_service.zip](https://github.com/warmcat/libwebsockets/files/2347072/ws_service.zip)

**Comment by lws-team** [comment]
> Libwebsockets version: 2.3.0

Can you try it with master lws?  v2.3.0 is over a year old.

**Comment by jasmine-zhu** [comment]
ok ,the master is the same.log file is attached.
And when we try to update ,we met some problems,here.
1、VS tools have no stdint.h and inttypes.h,we fixed by copying them from NDK tools.
2、ENOCONN is not defined in errno.h of VS tools, we fixed by changing ENOCONN to WSAENOCONN
3、lws_get_internal_extensions is removed，we fixed by remove code as well.
[ws_service2.zip](https://github.com/warmcat/libwebsockets/files/2350877/ws_service2.zip)

**Comment by lws-team** [comment]
> VS tools have no stdint.h and inttypes.h

Hum... those are defined in C99 (as in 1999, 19 years ago)... I guess microsoft don't have enough money to implement these in their tools.

> ENOCONN is not defined in errno.h of VS tools, we fixed by changing ENOCONN to WSAENOCONN

I cannot find any ENOCONN in lws master.

```
[libwebsockets]$ git grep ENOCONN
[libwebsockets]$
```

> lws_get_internal_extensions is removed，we fixed by remove code as well.

Yes if you want extensions, now you must explicitly give a list at context creation time.  `lws_extension_callback_pm_deflate` is exported from the library so you can still use it.

I don't use windows, it blows in a windows API, and I can't see your code, so this is a bit tricky.

Can you describe exactly the lws part of your test code?  You mention extensions... these are in use?  Are there any threads flying around that touch lws?

**Comment by jasmine-zhu** [comment]
It's ENOTCONN in ssl.c line 230, sorry for my spelling fault
We have a main thread checking connections , using msg in the callback to communicate with our other threads.So there is only one thread use lws,i think.
Now we don't use extensions,but problem is the same.
[main_thread.zip](https://github.com/warmcat/libwebsockets/files/2351035/main_thread.zip)

**Comment by lws-team** [comment]
I want to make a "minimal example" that implements the flow of your test as closely as possible.  But I don't actually know what your test does.

I am thinking it should be a simple ws server, and if you visit its index.html, the javascript in the web page will continuously create ws client connections back to the server, each one maybe sends a short message and then closes... say 8 connections may be happening concurrently.  And it just keeps doing that until you close the web browser tab, or it blows up.

Is this similar to your test?  Something different it should do to be more like your test?

**Comment by jasmine-zhu** [comment]
Yes it's completely our test process, we use python to make connections, but the number of connections is not fixed.

**Comment by jasmine-zhu** [comment]
We captured the message on wire, which shows the last packet is not reset ,then the new connection is unexpectly reset.
the fail is at 16:56:15

**Comment by jasmine-zhu** [comment]
We captured the message on wire, which shows the last packet is not reset ,then the new connection is unexpectly reset.
the fail is at 16:56:15

**Comment by jasmine-zhu** [comment]
We changed our testcase, and then the error was disappeared now. But we still don't know why ,guessing it's related to  function called CloseHandle , which is used before CreateSemaphore.
Thank you.

**Comment by lws-team** [comment]
I added a minimal example that makes mass concurrent ws client connections to a ws server using the mirror protocol

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client-spam

I tested it with 10,000 connections with 200 conncurrently on the test server on Linux, it's happy.  By default it tests for 100 connections with 20 concurrent on libwebsockets.org, that is added to the CI build tests.
