### ISSUE TITLE
WebSocket doesn't connect on 3G/4G mobile operators (iOS only)

### ISSUE THREAD

**Issue by smitpatel88** [warmcat/libwebsockets#1392]
Cocos2d-x using Websockets 2.4.2
If we try to connect using mobile 3G/4G network then we are getting error.

```
2018-08-31 11:38:38.503 Game Name[1938:428444] Received response from request to url http://game_url_with_port
D/WebSocket.cpp (416): WebSocket thread start, helper instance: 0x149702830
D/WebSocket.cpp (880): scheme: ws, host: game.domain, port: NUMBER, path: /socket.io/1/websocket/?EIO=2&transport=websocket&sid=S1G_BY8seWkY1_eIAAAB
D/WebSocket.cpp (168): NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 on

D/WebSocket.cpp (168): NOTICE: created client ssl context for default

D/WebSocket.cpp (168): NOTICE: lws_client_connect_2: 0x149159dc0: address game.domain

D/WebSocket.cpp (1329): WebSocket (0x149572770) Unhandled websocket event: 32
D/WebSocket.cpp (1329): WebSocket (0x149572770) Unhandled websocket event: 29
D/WebSocket.cpp (168): NOTICE: Connect failed errno=65

D/WebSocket.cpp (1204): WebSocket (0x149572770) onConnectionError, state: 0 ...
D/WebSocket.cpp (1233): WebSocket (0x149572770) onConnectionClosed, state: 2 ...
D/WebSocket.cpp (1263): onConnectionClosed, WebSocket (0x149572770) is closing by server.
D/WebSocket.cpp (1286): WebSocket (0x149572770) onConnectionClosed DONE!
D/WebSocket.cpp (1329): WebSocket (0x149572770) Unhandled websocket event: 50
D/WebSocket.cpp (1329): WebSocket (0x149572770) Unhandled websocket event: 45
D/WebSocket.cpp (1329): WebSocket (0x149572770) Unhandled websocket event: 33
D/WebSocket.cpp (1233): WebSocket (0x149572770) onConnectionClosed, state: 3 ...
D/WebSocket.cpp (1204): WebSocket (0x149572770) onConnectionError, state: 3 ...
Websocket error received: 1
GameClass::onClose called
```

When iphone is on wifi then its working fine.
Same sim-card in Android mobile its working.
In iPhone other multiplayer games is working fine.
Tried with both `wss` & `ws` but getting error.
Please help me out.
If you need any more info then please let me know.
Here is Cocos2d-x issue thread : https://github.com/cocos2d/cocos2d-x/issues/17326

**Comment by lws-team** [comment]
This doesn't seem related to lws at all, but a problem between your proprietary platform + SIM card.

Errno 65 is 'no route to host'.   But lws will just use the system routing table.

**Comment by smitpatel88** [comment]
This is definitely related to lws.
As we are having issues with Vodafone which is very large operator. 
On same sim all other multiplayer games is working.
Same sim is working on Android also.
That means something is wrong with ios part code.
Please atleast double check before closing issue, if you do care.
Can you please share more info on Errno 65?
If you have any demo, which will help finding exact error then let me know pls.

**Comment by smitpatel88** [comment]
One more thing if that matters, i am getting handshake request at server and server accept properly and at that time only client side this error comes.

**Comment by lws-team** [comment]
Do I care about your problem on a proprietary platform I don't have?  Not really.  It's not like you care about lws, or contributed anything even though you get benefit from it in a commercial product, right?  I have even less reason to care about your problems.

Do I care if something is broken in lws?  Almost always... if I can understand it, I will usually take action to solve it.

What should I do if there's no reproducer (except jump on a plane to your region, buy an iphone and vodaphone sim, get a copy of your sources) and no actionable evidence, like a backtrace or so?  Light a candle and weep softly?  What's the point of your 'issue' being open if I can't do anything about it?

> One more thing if that matters, i am getting handshake request at server and server accept properly and at that time only client side this error comes.

That's actually incompatible with what the logs such as they are suggest... they imply the tcp `connect()` failed, so it never got to send anything... 

```
if (connect(wsi->desc.sockfd, (const struct sockaddr *)psa, n) == -1 ||
	    LWS_ERRNO == LWS_EISCONN) {
		if (LWS_ERRNO == LWS_EALREADY ||
		    LWS_ERRNO == LWS_EINPROGRESS ||
		    LWS_ERRNO == LWS_EWOULDBLOCK
#ifdef _WIN32
			|| LWS_ERRNO == WSAEINVAL
#endif
		) {
			lwsl_client("nonblocking connect retry (errno = %d)\n",
				    LWS_ERRNO);

			if (lws_plat_check_connection_error(wsi)) {
				cce = "socket connect failed";
				goto failed;
			}

			/*
			 * must do specifically a POLLOUT poll to hear
			 * about the connect completion
			 */
			if (lws_change_pollfd(wsi, 0, LWS_POLLOUT)) {
				cce = "POLLOUT set failed";
				goto failed;
			}

			return wsi;
		}

		if (LWS_ERRNO != LWS_EISCONN) {
			lwsl_notice("Connect failed errno=%d\n", LWS_ERRNO); <<<====
			cce = "connect failed";
			goto failed;
		}
	}

```

Are you confusing the server logs with different attempts, or the pasted lws logs are different?

If you build lws with `cmake -DCMAKE_BUILD_TYPE=DEBUG` and set the log verbosity to max (`lws_set_log_level()` with, eg, 1151) are there more suggestive logs?

**Comment by tamngonesv030** [comment]
mitpatel88 I same problem. pls help me. with user cocos2dx 3.17.1

**Comment by lws-team** [comment]
When you say it's the "same problem", literally everything is the same like everything works for LTE except on Vodaphone SIM?

Lws doesn't manage your SIM routing arrangements, if there's a system route lets it out on the internet it will use it, if not, that's a problem between the SIM and iOS to be solved, lws doesn't know what goes on in iOS SIM handling guts.

If it's the same, send some proper logs as described in comment #5.  If it's not the same back up and describe the actual problem, in a new issue if it's that different.

**Comment by smitpatel88** [comment]
@tamngonesv030 Dude switch to Websocketpp. This guy doesnt care anything, just read his comments above. He doesn't even know how to reply to a person properly. I am using Websockets++ from last 3 years now without any issue.

**Comment by tamngonesv030** [comment]
@smitpatel88 Thank for your reply. Sorry, but how i switch to Websocketpp while cocos2dx using libwebsockets?
