### ISSUE TITLE
How to broadcast messages to clients in the ws server？

### ISSUE THREAD

**Issue by yanpeipan** [warmcat/libwebsockets#1397]

**Comment by lws-team** [comment]
In lws the primitive is not "broadcast messages" but to ask that the wsi gets a WRITEABLE callback when it can write something.

There's more than one way to do it... you can track active clients using a prtocol in a list and tell them individually

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c#n134-137

Or you can use an lws api to do the same thing to all wsi that are on a given vhost and using a given protocol

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-writeable.h#n75-90
