### ISSUE TITLE
does libwebsockets support args-string from url using ws-connection?

### ISSUE THREAD

**Issue by kasseller** [warmcat/libwebsockets#1398]
I see in HTTP-Server it has the lws_get_urlarg_by_name or lws_hdr_copy to get the parameters.
But if our clients make the connection using "ws://ip?token=xxxx", how can we get the parameters?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n400-411

in LWS_CALLBACK_ESTABLISHED
