### ISSUE TITLE
LWS_ROLE_H1 error with minimal-http-server

### ISSUE THREAD

**Issue by clankill3r** [warmcat/libwebsockets#1404]
When I try to build the minimal-http-server I get the following error:

```CMake Error at CMakeLists.txt:56 (message):
  This project requires lws must have been configured with LWS_ROLE_H1
Call Stack (most recent call first):
  CMakeLists.txt:67 (require_lws_config)


-- Configuring incomplete, errors occurred!
See also "/Data/github/libwebsockets/minimal-examples/http-server/minimal-http-server/CMakeFiles/CMakeOutput.log".
See also "/Data/github/libwebsockets/minimal-examples/http-server/minimal-http-server/CMakeFiles/CMakeError.log".
```

I already removed the build directory. Then rebuilded with `cmake LWS_ROLE_H1=1 /Data/github/libwebsockets` and did `make` and `sudo make install` again but I still get the LWS_ROLE_H1 error.

**Comment by lws-team** [comment]
When building lws, did you actually install it?  As in `make && sudo make install`?

**Comment by clankill3r** [comment]
Yes, if I do it again I get `--Up_to_date: /usr/local/...` for all files (except `libwebsockets.a` and `libwebsockets.13.dylib`).

**Comment by lws-team** [comment]
Does `/usr/local/include/lws_config.h` exist then?  Does it mention LWS_ROLE_H1?

> cmake LWS_ROLE_H1=1 /Data/github/libwebsockets

It'd need to be `-DLWS_ROLE_H1=1`, but it's on by default anyway.

**Comment by lws-team** [comment]
Does this help?

https://stackoverflow.com/questions/23905661/on-mac-g-clang-fails-to-search-usr-local-include-and-usr-local-lib-by-def

**Comment by clankill3r** [comment]
I already have the command line tools installed. If I try to install again with `xcode-select --install` then it also tells me that it is already installed.

If I execute `cpp -v` then `/usr/local/include/` is part of the `#include <...> search starts here:`.

**Comment by lws-team** [comment]
What can I say... apple is proprietary and we're using cmake to try to avoid exactly this kind of issue.

Supporting apple doesn't pay my rent and not supporting apple has exactly the same effect.

I don't have any apple products so I can't debug it for you.

What do you think I should do about it?

**Comment by lws-team** [comment]
Lws does not seem to have any problem with this.

@annagogolou's problem was she had a libwebsockets.h in both /usr/local/include and /usr/include.  If that's also the problem here, you need to nuke one of them to control which one is used.
