### ISSUE TITLE
LWS_ROLE_WS error on minimal-ws-server-threads example

### ISSUE THREAD

**Issue by annagogolou** [warmcat/libwebsockets#1405]
Hello Andy,

following the LWS_ROLE_H1 error that clankill3r takes here [https://github.com/warmcat/libwebsockets/issues/1404](https://github.com/warmcat/libwebsockets/issues/1404)

I also take the error "This project requires lws must have been configured with LWS_ROLE_WS", when I try to compile the minimal-ws-server-threads code.

I am using Linux! Could you please give me any help on that issue?

What I have already done is the following:
1) I removed the build folder from the libwebsockets-master folder.
2) I installed libwebsockets again by running the following commands
mkdir build
cd build
cmake LWS_ROLE_WS=1 ..
make && sudo make install

echo $LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/lib
echo $LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH/libwebsockets.so.10
export LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH
sudo ldconfig

3) The file usr/local/include/lws_config.h exists, but there was no #define LWS_ROLE_WS.
4) I wrote manually #define LWS_ROLE_WS in the file usr/local/include/lws_config.h

Nothing works. I am still taking the same error when I run cmake . && make in order to compile the minimal-ws-server-threads code.

Any help?

Thank you very much,
Anna

**Comment by annagogolou** [comment]
I talk about this code [https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/README.md](https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/README.md)

I cannot compile it.

Thanks again!

**Comment by annagogolou** [comment]
I just installed the latest version (when I sent the previous message I was running a previous version of libwebsockets).

I continue taking the same error, although in the file usr/local/include/lws_config.h exists the line
#define LWS_ROLE_WS

Any recommendations?

Thanks,
Anna

**Comment by annagogolou** [comment]
Another question (more general):

what I want to do is to send asynchronously updates of a current computation to the client, while the computation continues being executed.

Do I look at the right example using minimal-ws-server-threads code?

**Comment by lws-team** [comment]
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH/libwebsockets.so.10
> The file usr/local/include/lws_config.h exists, but there was no #define LWS_ROLE_WS.

The minimal examples were introduced with lws v3.0, which has an soname of libwebsockets.so.13.
LWS_ROLE_WS was introduced at the same time (basically, you can now disable websockets role at build time if you're not going to use it).  The example wants to use WS ROLE, needs server support (also something you can disable at build-time) so it confirms the lws you have was built including what it needs in its CMakeLists.txt

```
require_pthreads(requirements)
require_lws_config(LWS_ROLE_WS 1 requirements)
require_lws_config(LWS_WITHOUT_SERVER 0 requirements)
```

So using an older lws with new minimal example can't work.  It looks like you had a different, self-inflicted problem than whatever is happening to "clankill3r", unless he's doing the same thing.  Or it could be some subtle manifestation of revenge from a clan he kill3d.

The Cmake stuff checks the situation about lws build config by building a test app

```
                        CHECK_C_SOURCE_COMPILES("#include <libwebsockets.h>\nint main(void) {\n#if defined(${reqconfig})\n return 0;\n#else\n fail;\n#endif\n return 0;\n}\n" HAS_${reqconfig})
```
so `${reqconfig}` is, eg,` LWS_ROLE_WS`.

Do you have a different libwebsockets.h in, eg, `/usr/include` without LWS_ROLE_WS that conflicts with your one in `/usr/local/include`?

> I just installed the latest version (when I sent the previous message I was running a previous version of libwebsockets).

Yeah.

I get this on current master (the first part is just making sure it will make from scratch).  Paste what you get.

```
$ cd /projects/libwebsockets/minimal-examples/ws-server/minimal-ws-server-threads
$ make clean
$ rm CMakeCache.txt 
$ cmake .
-- The C compiler identification is GNU 8.1.1
-- The CXX compiler identification is GNU 8.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Success
-- Performing Test HAS_LWS_WITHOUT_SERVER
-- Performing Test HAS_LWS_WITHOUT_SERVER - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/libwebsockets/minimal-examples/ws-server/minimal-ws-server-threads
$ make
Scanning dependencies of target lws-minimal-ws-server-threads
[ 50%] Building C object CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o
[100%] Linking C executable lws-minimal-ws-server-threads
[100%] Built target lws-minimal-ws-server-threads
$
```

minimal-ws-server-threads does what you want.  There's another way in minimal-ws-server-threadpool now, threadpool takes the approach to block the worker thread when it has output, until the lws service thread has sent it.  So the worker thread cpu usage is controlled by the remote client's ability to receive over the network.  By contrast he -threads example worker thread runs continuously unless it fills its ringbuffer, even if things aren't getting received.

**Comment by annagogolou** [comment]
Thank you very much for your answer!

Yes, I had another libwebsockets.h file in usr/include and I removed that. Is it ok?

I follow your steps to compile the minimal-ws-server-threads example and when I run the last command "make", I take the error:

~/libwebsockets-master/minimal-examples/ws-server/minimal-ws-server-threads$ make
Scanning dependencies of target lws-minimal-ws-server-threads
[ 50%] Building C object CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o
[100%] Linking C executable lws-minimal-ws-server-threads
CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o: In function `thread_spam':
minimal-ws-server.c:(.text+0x9c): undefined reference to `lws_ring_get_count_free_elements'
minimal-ws-server.c:(.text+0x163): undefined reference to `lws_ring_insert'
CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o: In function `callback_minimal':
minimal-ws-server.c:(.text+0x251): undefined reference to `lws_get_vhost'
minimal-ws-server.c:(.text+0x2ce): undefined reference to `lws_get_vhost'
minimal-ws-server.c:(.text+0x31e): undefined reference to `lws_pvo_search'
minimal-ws-server.c:(.text+0x3a6): undefined reference to `lws_get_vhost'
minimal-ws-server.c:(.text+0x3c7): undefined reference to `lws_ring_create'
minimal-ws-server.c:(.text+0x4e2): undefined reference to `lws_ring_destroy'
minimal-ws-server.c:(.text+0x522): undefined reference to `lws_ring_get_oldest_tail'
minimal-ws-server.c:(.text+0x5b2): undefined reference to `lws_ring_get_element'
minimal-ws-server.c:(.text+0x64b): undefined reference to `lws_ring_get_oldest_tail'
minimal-ws-server.c:(.text+0x681): undefined reference to `lws_ring_consume'
minimal-ws-server.c:(.text+0x6c8): undefined reference to `lws_ring_get_count_waiting_elements'
minimal-ws-server.c:(.text+0x712): undefined reference to `lws_ring_update_oldest_tail'
minimal-ws-server.c:(.text+0x72d): undefined reference to `lws_ring_get_element'
CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o: In function `main':
minimal-ws-server.c:(.text+0x824): undefined reference to `lws_cmdline_option'
CMakeFiles/lws-minimal-ws-server-threads.dir/minimal-ws-server.c.o:(.data.rel+0x8): undefined reference to `lws_callback_http_dummy'
collect2: error: ld returned 1 exit status
CMakeFiles/lws-minimal-ws-server-threads.dir/build.make:94: recipe for target 'lws-minimal-ws-server-threads' failed
make[2]: *** [lws-minimal-ws-server-threads] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lws-minimal-ws-server-threads.dir/all' failed
make[1]: *** [CMakeFiles/lws-minimal-ws-server-threads.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

What is the problem, please?

Another question:
my system runs with the previous version of libwebsockets (before 3.0). By installing the latest version of libwebsockets, I take segmentation fault in the early begining, when the client connects. Are not the two versions compatible?

If I work with the previous version of libwebsockets, could I use threads to execute what I want (i.e., sending asynchronously messages of the current computation to the client, while the computation continues running)? If yes, could I work in a similar way as in the minimal-ws-server-threads example?

Thanks,
Annna

**Comment by lws-team** [comment]
... so this mystery is solved afaik.

**Comment by dagelf** [comment]
I've run into the same problem as @annagogolou on current master. The cmake fails at the command "fail" - I'm not sure if this is intentional. I just skipped cmake and compiled manually: 
`gcc minimal-ws-server.c -o minimal-ws-server -lwebsockets `

(If you're on an older ubuntu, you might have to apt-remove libwebsockets-dev libwebsockets8)

**Comment by lws-team** [comment]
Cmake really concerns itself with caching to avoid running these expensive tests every time... if you, eg, did the minimal example cmake while you had distro lws pieces installed, re-running cmake after you removed them may not trigger it to rerun these 'probing' tests since it just uses the cached result.

You may find then just deleting ./CMakeCache.txt in the example dir and redo `cmake .` is all you need to 'fix' this.
