### ISSUE TITLE
Failing to request the client certificate

### ISSUE THREAD

**Issue by nldvos** [warmcat/libwebsockets#1411]
I want to enable client authentication in the minimal-http-server-tls program. However, I am experiencing difficulties succeeding when doing this.

I added this line of code (in order to request the certificate of the client):
        info.error_document_404 = "/404.html";
 	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
+	info.options |= LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT;
 	info.ssl_cert_filepath = "localhost-100y.cert";
 	info.ssl_private_key_filepath = "localhost-100y.key";

I thought this was enough to request the client certificate. As I understood, implementing a callback is not necessary as the dummy callback will always accept the certificate. 

Then, when running the server, I try to connect to it with firefox and with the minimal-http-client-certinfo. Both are failing. Firefox says that the SSL handshake failed (no acceptable set of parameters was negotiated).

The minimal server works correctly before adding this one line of code.

My ultimate goal is to access the client certificate and close the connection if my server does not recognize it.

What am I doing wrong?

I used the v3.0-stable branch.

**Comment by lws-team** [comment]
> I am experiencing difficulties succeeding when doing this.
>    info.options |= LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT;
>    info.ssl_cert_filepath = "localhost-100y.cert";
>    info.ssl_private_key_filepath = "localhost-100y.key";

You need to actually do the necessary pki and import the client cert into your browser, it is not turnkey like the 100 year localhost server cert lws provides to keep things simple.  See the section "Testing client certs".

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.test-apps.md

Lws provides a CA dir layout and helper script here

https://libwebsockets.org/git/libwebsockets/tree/scripts/client-ca

described in the docs.

**Comment by nldvos** [comment]
Thank you very much! 

It works now.
