### ISSUE TITLE
How to detect internet/connection break in libwebsocket without using TCPKeep alive 

### ISSUE THREAD

**Issue by shibinpp118** [warmcat/libwebsockets#1414]
Hi Everybody,
  Please help me out for the mentioned concern. I am working in  low power and low band width devices for cloud connect application. Basically I need to detect internet/or connection status before I attempt message send to server. TCP keep alive is not recommended anyway because of less band width. May I have any other solution to detect internet connection status before I attempt  data sending , also to avoid Internal buffering done by libwebsocket if there is no internet connection available.

**Comment by lws-team** [comment]
You want to know if you can send stuff before you send stuff.

There may be a platform-specific way for some cases, but the only known way to definitely confirm stuff is getting through is send something and get a response.

> avoid Internal buffering done by libwebsocket if there is no internet connection available.

Don't randomly blame lws. TCP/IP is designed to buffer stuff in kernel.
