### ISSUE TITLE
Cannot parse uri if incoming request was HTTP2 or spdy

### ISSUE THREAD

**Issue by cyclonstep** [warmcat/libwebsockets#1418]
Hey, In these past few days our team is struggling with this problem. When we are using lwsws, it seems that we cannot parse the uri when the request came to the server was a HTTP 2 protocol. It works fine when the request came to the server was HTTP 1.1 protocol. This is our code: 

```
lws_hdr_total_length(wsi, WSI_TOKEN_POST_URI)) {
lws_hdr_copy(wsi, us->endponint_uri,
      sizeof(us->endponint_uri) - 1, WSI_TOKEN_POST_URI);
}
```

the output for this block of code when it was HTTP 2 always come empty. 

What can we do to mitigate this situation? Is this a bug?
Your answer is very much appreciated. Thank you 👍

**Comment by lws-team** [comment]
On h2, it does not use h1 method-on-the-first-line like `GET / HTTP/1.1`.

Instead there's a `:method` 'pseudoheader' that carries the method.

In the lws http parser, this is available at a different token index, ..._COLON_METHOD.

However it looks like we fake up ...POST_URI from that, if :method was POST.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/h2/http2.c#n1437-1440

```
		p = lws_hdr_simple_ptr(h2n->swsi, WSI_TOKEN_HTTP_COLON_METHOD);
		if (!strcmp(p, "POST"))
			h2n->swsi->http.ah->frag_index[WSI_TOKEN_POST_URI] =
				h2n->swsi->http.ah->frag_index[WSI_TOKEN_HTTP_COLON_PATH];
```

This is also true on v3.0-stable... so dunno.
