### ISSUE TITLE
Minor nit in ./plugins/protocol_lws_mirror.c

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1422]
In protocol_lws_mirror.c on line 215 the return value of lws_get_urlarg_by_name() is null if the argument is **not** found :  
```
                if (lws_get_urlarg_by_name(wsi, "mirror", name,
                                           sizeof(name) - 1))
                        lwsl_debug("get urlarg failed\n");
```
This code erroneously indicates that the call has failed.  It should read :  
```
                if (!lws_get_urlarg_by_name(wsi, "mirror", name,
                                           sizeof(name) - 1))
                        lwsl_debug("get urlarg failed\n");
```
This is a very cool example, by the way.  I have learned a lot from it.

Respectfully,
Peter

**Comment by lws-team** [comment]
Thanks, it's pushed on master.
