### ISSUE TITLE
need to send string info as part of connection request from client/server in lws

### ISSUE THREAD

**Issue by Abhijit16** [warmcat/libwebsockets#1424]
Hi,

   I am trying to create a C++ websocket class that can connect as client/start listening as server, so as to establish a connection with other objects of the same class on other PCs.
    I am successfully able to establish a connection between a client & server too, however I wish to send some string (that would serve as an identifier easy for humans to remember, - each connection end is designed to have a unique string identifier - say for chat kind of application) from the remote socket to the callback:

static int ws_service_callback( struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)

when reason is either LWS_CALLBACK_ESTABLISHED or LWS_CALLBACK_CLIENT_ESTABLISHED, so that I can store the corresponding wsi along with it’s string identifier(as a key-value) in a map.

For example: if a client (with string identifier c1) sends a connection request to a server (with string identifier s1), after ws connection is successfully established, client should be able to access server’s identifier (s1) so that it can store it in it’s map for future reference/sending data,
And server too should get client’s identifier (c1) in it’s LWS_CALLBACK_ESTABLISHED, so that it too may store it.

 I am not able to find a way to pass this string identifier info - more specifically, I wish to get access to remote connection (ex: server vhost_name) info from (client’s) “wsi” in (client’s) ws_service_callback() & vice-versa when connection is successfully established - is it possible to do so ?

Thanks,
Abhi.

**Comment by lws-team** [comment]
> when reason is either LWS_CALLBACK_ESTABLISHED or LWS_CALLBACK_CLIENT_ESTABLISHED, so that I can store the corresponding wsi along with it’s string identifier(as a key-value) in a map.

Hm... I don't really understand your scenario from your description.   Whether it's C or C++ is irrelevant.

> For example: if a client (with string identifier c1) sends a connection request to a server (with string identifier s1), after ws connection is successfully established, client should be able to access server’s identifier (s1) so that it can store it in it’s map for future reference/sending data,

What does it mean?  The client, the user may have told it he wants to be known as "c1", okay.  The admin of s1, told the server that it should be known as "s1".

Somehow the client can transform his wish to talk to "s1" to a ws link to s1.  Maybe he opens a ws connection to "s1.mysite.com" or something.

> after ws connection is successfully established, client should be able to access server’s identifier (s1) so that it can store it in it’s map for future reference/sending data,

The client knows he wants "s1", and he knows how to talk to "s1".  He can open a ws connection to "s1" somehow.  So what's the problem?  When he opens the ws connection, s1 can send him any extra info the client wishes.

Your question is something different?  Try again with the asking.

**Comment by Abhijit16** [comment]
To elaborate, the client would connect to multiple servers during the course of time, and the servers could periodically (asynchronous event) send some data that is received by the client. Client would take different actions based on what server sent data to it. (The plan is to append the server name before the data to be send, so that client can extract the server name and take appropriate action)

The class that I am creating also has an additional purpose of being used by other users, and using identifiers is a way of making things easy for them, so that they can use strings rather than lws *wsi pointers to react to incoming data.

       If we do not have an identifier, we would need to compare the wsi, to see what server has sent data, and that could seem cumbersome for other users to use it.

**Comment by lws-team** [comment]
> To elaborate, the client would connect to multiple servers during the course of time, and the servers could periodically (asynchronous event) send some data that is received by the client

Well, okay.  It can do that.

There's a problem somewhere with these "identifiers" somehow?

The client must be able to "identify" the server perfectly well, or it can't connect to it.

So the problem is about the server figuring out which live connection belongs to which client it wants to talk to somehow?  Something else?

**Comment by Abhijit16** [comment]
yes, client can connect well since it has the address & port number of the server, but since 
1) there can be multiple connections of a server
2) and after connections, any activity is only associated with the lws *wsi, 

I am trying to plan of clients also passing their identifiers during connection (not found a way of doing so), so that whenever incoming data is bound, server can directly "lookup" in the map using the identfier(or an agent name as i would describe it), rather than remembering & comparing the available wsi in callback to respond.

  since incoming data has sender's name appended before it; finding the sender name wont be a problem, but then I would also have to check for each incoming data event (callback_receive:) to see if the name is already in map -> if not (as in the first time a client sends data to the server after connection), add it  to the map.
    Doing this check everytime (from possibly multiple connections) would be unnecessary, if the remote party sends it's name/identifier in  CALLBACK_ESTABLISHED case (because it would be called only once per successfully connection), so that this check could be avoided, plus it looks neat if it could be handled in CALLBACK_ESTABLISHED.

**Comment by lws-team** [comment]
> but then I would also have to check for each incoming data event (callback_receive:) to see if the name is already in map -> if not (as in the first time a client sends data to the server after connection), add it to the map.

AFAIK it sounds you can do it OK, you are just worrying about scalability.

> Doing this check everytime (from possibly multiple connections) would be unnecessary, if the remote party sends it's name/identifier in CALLBACK_ESTABLISHED case (because it would be called only once per successfully connection), so that this check could be avoided, plus it looks neat if it could be handled in CALLBACK_ESTABLISHED.

Well... I think maybe you are trusting the client too much because you don't mention authentication.  But ignoring that, where is the problem with that?

The client can send extra info available at ESTABLISHED by

 - putting the data in headers; the http headers lws supports are still available at ESTABLISHED

 - putting the data in the URL path (ws also get the url path, at ESTABLISHED it's in `in`), eg, blah.com/connect/c1 or blah.com/?id=c1

**Comment by Abhijit16** [comment]
I am trying to append header names like you suggested, both from client to server & vice-versa. Following is the code 

/*m_self_name is a string containing the identifier.
header is "server_identifier"
html_args is lws_process_html_args buffer provided by "in" during LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER.
*/

int WebSocket::set_header(lws* wsi, unsigned char *header_name, lws_process_html_args *html_args)
{
	unsigned char *p, *end;
	p = (unsigned char*)html_args->p + LWS_PRE;
	end = p + html_args->max_len - LWS_PRE;

	lws_add_http_header_by_name(wsi, header_name, (unsigned char*) m_self_name.c_str(), m_self_name.length()-1, (unsigned char**) &p, (unsigned char*) end);
	lws_finalize_http_header(wsi, &p, end);
	int n = lws_write(wsi, (unsigned char*) html_args->p + LWS_PRE, p - ((unsigned char*) html_args->p + LWS_PRE), LWS_WRITE_HTTP_HEADERS);


	if (n < 0)
		return 1;		
	else
		return 0;		
}

This returns 0, however, LWS_CALLBACK_ESTABLISHED never gets called from server side. Is anything wrong with setting up the header ? docs say that these apis should be used for response, so does that mean request headers can't use it (i could not find any separate api used for request headers)

**Comment by lws-team** [comment]
Hmmm if there's a problem with lws with something, the way to get me to worry about it is demonstrate it is my problem, usually with a patch on one of the minimal examples.  Or for legendary status, send me the fix.

I can't debug other people's code for free until they get to the point we don't have anything more to talk about any more and go away content.

**Comment by Abhijit16** [comment]
I am trying to append header names like you suggested, both from client to server & vice-versa. Following is the code 

/*m_self_name is a string containing the identifier.
header is "server_identifier"
html_args is lws_process_html_args buffer provided by "in" during LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER.
*/

client side header adding snippet:

// "ws_ptr_self" is the pointer to object of class "WebSocket".

case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:	// add headers to client transaction. This header will be read by server on "LWS_CALLBACK_ESTABLISHED".
{
	char **p = (char**)in;
	char *end = (*p) + len - LWS_PRE;
	ws_ptr_self->set_header(wsi, (unsigned char*)CLIENT_AGENT_NAME, (unsigned char*)*p, (unsigned char*) end);
	return 0;
}
break;


server side header adding snippet:

case LWS_CALLBACK_ADD_HEADERS:
	lws_process_html_args *http_args = (lws_process_html_args*)in;
	return ws_ptr_self->set_header(wsi, (unsigned char*)SERVER_AGENT_NAME, (unsigned char*)http_args->p, (unsigned char*) (http_args->p + http_args->max_len - LWS_PRE));


// the function that sets header.
int WebSocket::set_header(lws* wsi, unsigned char *header_name, lws_process_html_args *html_args)
{
	unsigned char *p, *end;
	p = (unsigned char*)html_args->p + LWS_PRE;
	end = p + html_args->max_len - LWS_PRE;

	lws_add_http_header_by_name(wsi, header_name, (unsigned char*) m_self_name.c_str(), m_self_name.length()-1, (unsigned char**) &p, (unsigned char*) end);
	lws_finalize_http_header(wsi, &p, end);
	int n = lws_write(wsi, (unsigned char*) html_args->p + LWS_PRE, p - ((unsigned char*) html_args->p + LWS_PRE), LWS_WRITE_HTTP_HEADERS);


	if (n < 0)
		return 1;		
	else
		return 0;		
}

This returns 0. However, LWS_CALLBACK_ESTABLISHED never gets called from server side. Is anything wrong with setting up the header on either end ? docs say that these apis should be used for response, so does that mean request headers can't use it (i could not find any separate/different api used for request headers)

**Comment by lws-team** [comment]
> header_name

You can add arbitrary headers with lws, but it only parses the ones it knows and discards the rest.  The supported headers are here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/lextable-strings.h

which correspond to these token indexes

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n209

>  LWS_CALLBACK_ESTABLISHED never gets called from server side

Look at the lws logs.

**Comment by Abhijit16** [comment]
Thanks for the help Andy
