### ISSUE TITLE
ERR: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=0)

### ISSUE THREAD

**Issue by jsveto** [warmcat/libwebsockets#1425]
Hi, i am trying to connect with libwebsockets library to pusher websocket. This is the output i get from websockets library:

[2018/10/05 23:27:23:9587] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[2018/10/05 23:27:23:9592] NOTICE: created client ssl context for default
[2018/10/05 23:27:24:1005] ERR: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=0)

I tried to use curl to connect to it and also got similar error:
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

I have added ca certificate which i obtained with openssl command to /etc/ssl/certs/ca-certificates.crt and after that curl did NOT report certificate verification failed error anymore. However libwebsockets error remained the same. I tried to set client_ssl_ca_filepath but it did not work.

The service i am connecting to is pro-pusher.com
Is there a way to completely disable certificate verification in libwesbockets?

**Comment by lws-team** [comment]
> Is there a way to completely disable certificate verification in libwesbockets?

You can accept "selfsigned", which is the situation if you meet a certificate signed by a CA you don't already trust.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n31-50

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n62-63

>  I tried to set client_ssl_ca_filepath but it did not work.

What happens if you set `.ssl_ca_filepath` to the same?

**Comment by jsveto** [comment]
> i do have SELFSIGNED flag set.

> Same error.

**Comment by jsveto** [comment]
> You can accept "selfsigned", which is the situation if you meet a certificate signed by a CA you don't already trust.
I do have selfsigned flag set.

> What happens if you set .ssl_ca_filepath to the same?

same error. :(

**Comment by lws-team** [comment]
On my Fedora box, I can accept the TLS connection to that site normally with lws.  I understand your situation is that in fact you don't have any trusted CA certs on your box.

Can you maybe attach the certs you stored on your system that made curl happy?

**Comment by jsveto** [comment]
-----BEGIN CERTIFICATE-----
MIIGVTCCBT2gAwIBAgIRAI8XG+3QyVX85eHlKWTxBAUwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTgwNDE5MDAwMDAwWhcNMTkwNDE5MjM1OTU5WjBSMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRcw
FQYDVQQDEw5wcm8tcHVzaGVyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAM7pWMnl2HENUU/RBhJvDp/Fn8czvh8OEjFJ7ZQ1ywF5mc/j1kapj5dD
lQTXo1Xlbu7x0VQmOAEJsFjNlIPB+mrM4Q6t1hA/8ISLKCCynfxm99Ej4Q6pwckp
x/5Bug7JOaRNVPT8T4E9gOH3xXwWfnOk8tN4NbyyWSNUKJAq4sjubd9xwlNODSyK
YjYgiY3aFsplzIdDU3MERUv2G4vgEPv3U3WF9M2HdARd7Rd0UwCItwHdaqB5f731
c2ZarnwoxjfNv6kPZW46XlKIrBdPVpFKY/SIsdVi4sPmgcm643VuwFYYAYaFY1Ku
fogazJZKPHPlwbTZhL6hcQwyfxeuzWUCAwEAAaOCAuUwggLhMB8GA1UdIwQYMBaA
FJCvajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBRzikrh8heDOTGPQtyZQp9N
h2an3jAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwTwYDVR0gBEgwRjA6BgsrBgEEAbIxAQICBzArMCkG
CCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8uY29tL0NQUzAIBgZngQwB
AgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5jb21vZG9jYS5jb20vQ09N
T0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCBhQYIKwYB
BQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LmNvbW9kb2NhLmNvbS9D
T01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCQGCCsG
AQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wLQYDVR0RBCYwJIIOcHJv
LXB1c2hlci5jb22CEnd3dy5wcm8tcHVzaGVyLmNvbTCCAQIGCisGAQQB1nkCBAIE
gfMEgfAA7gB1AO5Lvbd1zmC64UJpH6vhnmajD35fsHLYgwDEe4l6qP3LAAABYt7e
1tAAAAQDAEYwRAIgZSaQegy/c6Jsn/K9Iaw12r3JwN+x/vrZGTdogjOp6ggCIB/m
DVZBjgyfZwH4Tk7r0S+4wawfTNRPYQmZYuH8uBXrAHUAdH7agzGtMxCRIZzOJU9C
cMK//V5CIAjGNzV55hB7zFYAAAFi3t7T3AAABAMARjBEAiBmHRYO+zS4qKke/6Of
e+EzJ4cBPuw5cqy0sWCBIvzSSAIgXGEHBoBsw4VemstoVwY3lrih9ECZfOkivCT1
cc0I8xkwDQYJKoZIhvcNAQELBQADggEBAHXPp1/FNdc7o6N80SSWUY0aA1kKcZvf
1XjLCjtxCvu7vWwAItQLgfvINEGULWWx6ldci6ghK10tzccXRQgUddxUXHE+3Aex
uyUlWYMZ8Wze9ZTJxtB2OnJVNSs3p3tETJu/qx6n9fDiZ5dK8WqWE/qIV0H5n7CC
VmO0KTjHOB8gNzjOb4J75bSNiUrLQOySdrOun4dcyfS0GFTl6d3688kO6HYWkhm+
1xAQ8JNXUCgx+wnM8+Ghb5DsXX4GqBwiHKCnysXYhs7fijcVMmKcGxxZm8I+xHPC
PhdMG7MocnRMjK/aZRSenc8M5QlON71mxzGQYaMCO5Df9WpynApXwSg=
-----END CERTIFICATE-----

**Comment by jsveto** [comment]
obtained with:
openssl s_client -showcerts -connect pro-pusher.com:443

**Comment by lws-team** [comment]
Thanks... I will look at it later.

**Comment by jsveto** [comment]
i checked if wget can successfully connect to pro-pusher.com but it failed (Unable to locally verify the issuer's authority.)

Looks like i had wrong ca-certificate. this one was correct: http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt

However, i have no idea why curl was happy with the wrong certificate...

Sorry for false bug report. Keep up the good work!
