### ISSUE TITLE
Improvement: Detecting Connection Failure

### ISSUE THREAD

**Issue by serpentfabric** [warmcat/libwebsockets#1428]
Given the server is responsible for sending pings to libwebsockets:
Given cellular data is too costly for libwebsockets to redundantly send pings to the server:
Given tcp keepalives can be forged, rendering them unreliable for determining connectivity:

libwebsockets cannot determine when it has been silently/hard disconnected from the server, until it attempts to send data. 

There is a window of time between the silent/hard disconnect and the sending of data by libwebsockets wherein the server wishes to send the client data but cannot because the server lacks an active connection to the client and the client failed to reconnect because it's unaware it has disconnected.

We would like to remedy this without requiring the client (libwebsockets) to send pings and double the data usage for supervision: we propose a simple solution of just having a flag indicating the time when libwebsockets last received a ping, or something more advanced, like a list of subscribers who wish to be notified of a ping event.

**Comment by serpentfabric** [comment]
maybe it's enough to just check if wsi->ws->ping_payload_buf changed at some interval?

**Comment by serpentfabric** [comment]
I appreciate you taking time to respond. I agree, I was unfairly framing this as a lws problem when it's not. I apologize, that wasn't my intention.

However, given I have limited data allowance, I'm wondering if we can't leverage lws to overcome this issue: knowing that the server is periodically sending pings to my lws clients maybe we could use a timer to periodically compare the contents with wsi->ws->ping_payload_buf and if it hasn't changed after 3 intervals, we can assume the server has gone away?

**Comment by lws-team** [comment]
I'm not stopping you trying that...

**Comment by serpentfabric** [comment]
i know. i guess i'm asking do you see a flaw or unintended consequence :)

**Comment by lws-team** [comment]
If there's a problem, let me know.
