### ISSUE TITLE
Cannot upgrade connection after 082f096

### ISSUE THREAD

**Issue by joelittlejohn** [warmcat/libwebsockets#1435]
Hi Andy. Thanks a lot for your help! I thought I'd create an issue to cover this rather than continue the discussion in commit comments.

### The problem

After 082f09612355ef9607b3d3d5f9d9e6c789a019c1 we are unable to connect to our WebSocket server using LWS. The server is Jetty 9. After this recent commit, libwebsockets now sends `Connection: close, Upgrade` instead of simply `Connection: Upgrade`. Jetty responds with the following upgrade response:

```
HTTP/1.1 101 Switching Protocols
Connection: close
Connection: Upgrade
Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Upgrade: WebSocket
```

but LWS rejects this response because of this check:

https://github.com/warmcat/libwebsockets/blob/a5b2248e727b64e781ffb5659e3c9d1499055d17/lib/roles/ws/client-ws.c#L272

There is some further discussion about this in [082f096 commit comments](https://github.com/warmcat/libwebsockets/commit/082f09612355ef9607b3d3d5f9d9e6c789a019c1#r30942427).

@lws-team I'm not able to apply your patch, it fails. It's probably me doing something wrong, but I thought I'd just check: is it supposed to apply against the current HEAD a98919645532d2f44fb13b658b7b9b10bd75d8bd?

**Comment by lws-team** [comment]
That's on current master already atm.

It should solve it but I am not certain how the two headers will be combined... I can't trivially test it on your server.  So if still problems, dump the lws_hdr_cpy()'d string and lets see how they are combined.

**Comment by joelittlejohn** [comment]
Ah okay. The current HEAD on master definitely fails. We get the following:

```
[2018/10/18 10:09:21:5769] WARN: LWS_CALLBACK_CLIENT_CONNECTION_ERROR 'HS: UPGRADE malformed'
```

**Comment by lws-team** [comment]
OK... so dump buf here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/ws/client-ws.c#n271

**Comment by KhasanovRustam** [comment]
Hello, Andy! 

This happens on the server side when a subprotocol sent by client contains some delimiters like  "."

I think this is wrong because subprotocols can contain those delimiters.

I have fixed it in my local version by adding LWS_TOKENIZE_F_RFC7230_DELIMS into this call (server-ws.c file,  line 336):

	/*
	 * Select the first protocol we support from the list
	 * the client sent us.
	 */

	lws_tokenize_init(&ts, buf, LWS_TOKENIZE_F_COMMA_SEP_LIST |
				    LWS_TOKENIZE_F_MINUS_NONTERM
					| LWS_TOKENIZE_F_RFC7230_DELIMS
					);

**Comment by lws-team** [comment]
@KhasanovRustam  thanks it makes sense that might have broken... I added your fix to the patch that's trying to clean up the tokenizer adaptations, but what you describe seems a different problem than the OP's problem here.

@joelittlejohn : I can't reproduce your problem easily and you can.  So please add something like

`lwsl_err("%s: buf '%s'\n", __func__, buf);`

temporarily after the line I pointed out, so you can dump "buf" and I can maybe understand what is happening.

**Comment by joelittlejohn** [comment]
@lws-team thanks again for your help!

With the latest HEAD (3d3848e81cfd2fe487b15c5e484ff569bea0a03b) and with your line above added, I see the following output:

```
[2018/10/22 10:53:11:8112] ERR: lws_client_ws_upgrade: buf 'close  Upgrade'
```

the actual response from the server that came over the wire was:

```
HTTP/1.1 101 Switching Protocols
Connection: close
Connection: Upgrade
Sec-WebSocket-Accept: q2BKSfDtrariA4A8SaPRU5mB9s4=
Upgrade: WebSocket
```

**Comment by lws-team** [comment]
I saw your post by email... github has alzheimers at the moment (somebody must have told it microsoft owns it now) so it is lost as will this likely be, but the email notifications seem to be working OK.

I understand what's happening from that... does this make everything beautiful or just make the yuck pour out of somewhere else?

```
diff --git a/lib/roles/http/server/parsers.c b/lib/roles/http/server/parsers.c
index 96a77915..e5873525 100644
--- a/lib/roles/http/server/parsers.c
+++ b/lib/roles/http/server/parsers.c
@@ -516,13 +516,16 @@ LWS_VISIBLE int lws_hdr_copy(struct lws *wsi, char *dst, int len,
                return 0;
 
        do {
-               if (wsi->http.ah->frags[n].len >= len)
+               if (wsi->http.ah->frags[n].len + 1 >= len)
                        return -1;
                strncpy(dst, &wsi->http.ah->data[wsi->http.ah->frags[n].offset],
                        wsi->http.ah->frags[n].len);
                dst += wsi->http.ah->frags[n].len;
                len -= wsi->http.ah->frags[n].len;
                n = wsi->http.ah->frags[n].nfrag;
+
+               if (n)
+                       *dst++ = ',';
        } while (n);
        *dst = '\0';
 
```

**Comment by lws-team** [comment]
Well, it has been over a week... I added the above patch on master a while ago.  If it makes new  problems I'm sure I'll hear about them eventually.  It should have fixed this issue.

**Comment by joelittlejohn** [comment]
@lws-team Apologies for going quiet on this and thanks again for your help!

I gave this a test last week and was able to upgrade successfully, but wanted to check on another side effect of this change. I'll shout again
If I find anything else.

**Comment by joelittlejohn** [comment]
@lws-team Sorry for the delay and the additional context switching!

The fix applied in master gets us past the upgrade stage (the Connection header is now understood correctly, and the upgrade is successful) but as soon as the upgrade is completed the client disconnects. I assume that `Connection: close` on the response is being wrongly interpreted as 'Close the connection now' instead of 'Close the connection after the WebSocket is complete'.

**Comment by lws-team** [comment]
Are we testing current master?

**Comment by joelittlejohn** [comment]
Yes, that's right.

**Comment by lws-team** [comment]
> I assume that Connection: close on the response is being wrongly interpreted as 'Close the connection now' instead of 'Close the connection after the WebSocket is complete'.

There's no mentioned evidence supporting that.  From what you said, it just closes.  Either side could have closed it for whatever reason.

Can we see the logs around that at high logging level?  With no way to reproduce it nor any logs or other hints this isn't going to get solved.

**Comment by joelittlejohn** [comment]
> There's no mentioned evidence supporting that. From what you said, it just closes. Either side could have closed it for whatever reason.

Definitely a fair point. I'll do some more testing and info gathering. For the time being I've added a debug LWS log here: https://pastebin.com/raw/xQULbxMM

Our server logs a close status `1006 WebSocket Read EOF` which made me initially think this was a close driven by the client, however I will investigate the load balancer as well to narrow things down.

**Comment by lws-team** [comment]
The log enable thing is a bitfield... if you only enable DEBUG it misses out a lot of other information.  The log enables I use most are 1039 and 1151.  At any rate

> [2018/11/27 14:20:08:3131] DEBUG: 0x7f4310005a40: SSL_read says 0
> [2018/11/27 14:20:08:3132] DEBUG: lws_ssl_get_error: 0x7f4310007d30 0 -> 6 (errno 0)

6 is SSL_ERROR_ZERO_RETURN

https://github.com/openssl/openssl/blob/f1d49ed94707f5f0799541aa8e528dce67712948/include/openssl/ssl.h#L1174

```
For SSL_read() and SSL_peek() the following return values can occur:

> 0

    The read operation was successful. The return value is the number of bytes actually read from the TLS/SSL connection.

<= 0

    The read operation was not successful, because either the connection was closed, an error occurred or action must be taken by the calling process. Call SSL_get_error(3) with the return value ret to find out the reason.

    Old documentation indicated a difference between 0 and -1, and that -1 was retryable. You should instead call SSL_get_error() to find out if it's retryable.
```
https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html

```
SSL_ERROR_ZERO_RETURN

    The TLS/SSL connection has been closed. If the protocol version is SSL 3.0 or higher, this result code is returned only if a closure alert has occurred in the protocol, i.e. if the connection has been closed cleanly. Note that in this case SSL_ERROR_ZERO_RETURN does not necessarily indicate that the underlying transport has been closed.
```
https://www.openssl.org/docs/man1.1.0/ssl/SSL_get_error.html

**Comment by kristjanvalur** [comment]
I'm having this problem with the echo servers at echo.websocket.org.
The servers are closing the connection immediately on the TCP level, as indicated by wireshark:
> 41	2.859586	192.168.1.182	174.129.224.73	HTTP	296	GET / HTTP/1.1 
> 43	2.977268	174.129.224.73	192.168.1.182	TCP	60	80 → 56009 [ACK] Seq=1 Ack=243 Win=28032 Len=0
> 44	2.977401	174.129.224.73	192.168.1.182	HTTP	255	HTTP/1.1 101 Web Socket Protocol Handshake 
> 45	2.977500	174.129.224.73	192.168.1.182	TCP	60	80 → 56009 [FIN, ACK] Seq=202 Ack=243 Win=28032 Len=0

Spent a day scratching my head over this.  Hoping to find a way to disable the "close" header for compatibility with various WS servers.

**Comment by kristjanvalur** [comment]
Using the LCCSCF_PIPELINE option disables this, however, and the above servers work again.

**Comment by lws-team** [comment]
`connection: close, upgrade` is legal and useful... it defines what will happen to the http transaction if the upgrade failed and we stayed in http.  But most ws servers choke on it... the examples in RFC6455 just show `connection: upgrade` and it doesn't point out that `connection:` predates RFC6455 and has its own tokens already.

I pushed a patch on master disabling it.
