### ISSUE TITLE
Multiple websocket protocols

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1436]
Hi,

I am working with the various examples and trying to understand some behavior that I'm seeing.  Starting with protocol_lws_minimal_client_echo.c, the client side callback handler is installed at 'protocol 0', as follows :  
```
static struct lws_protocols protocols[] = {
        LWS_PLUGIN_PROTOCOL_MINIMAL_CLIENT_ECHO,
        { NULL, NULL, 0, 0 } /* terminator */
};
```
And the demo works.  I need a couple of different websockets, which is where things start going off of the rails.  Any websocket protocol based on minimal-client that is not in position 0 crashes, as follows : 

Looking at the test-server.c I see several websocket protocols working together, with 'plain old http' is in position 0.  Doing the same thing to client-echo,
```
static struct lws_protocols protocols[] = {
        { "http-only", lws_callback_http, 0, 0, },
        LWS_PLUGIN_PROTOCOL_MINIMAL_CLIENT_ECHO,
        { NULL, NULL, 0, 0 } /* terminator */
};
```
And change connect_client code accordingly to include : 
```
        i.protocol = "lws-minimal-client-echo";
```
Then the application crashes at 
```
        case LWS_CALLBACK_CLIENT_CLOSED:
                lwsl_user("LWS_CALLBACK_CLIENT_CLOSED\n");
                lws_ring_destroy(pss->ring);   <--  Here.
```
The problem is that the framework has changed its behavior slightly when this demo protocol is not in the first position.  In the debugger I see that the callback that has actually been called is LWS_CALLBACK_HTTP_BIND_PROTOCOL, which upon further inspection has the same integer value of 75 as LWS_CALLBACK_CLIENT_CLOSED, causing this callback to be misinterpreted in this example.  

Going back to the protocols in test-server, I see that they handle disconnecting clients slightly differently than the echo example.  They use a different callback :  
```
        case LWS_CALLBACK_CLOSED:
                /* detach our pss from the mirror instance */
                mi = pss->mi;
                if (!mi)
                        break;

```
I would like to understand why, even though they are both websocket clients, they use different callbacks.  Is one called in position 0 while the other is called in any other position?  Or, should 'echo' be also using LWS_CALLBACK_CLOSED?

Thanks for helping me understand things better :)

Respectfully,
Peter

**Comment by lws-team** [comment]
> LWS_CALLBACK_HTTP_BIND_PROTOCOL, which upon further inspection has the same integer value of 75 as LWS_CALLBACK_CLIENT_CLOSED

You mean CLIENT_HTTP_BIND_PROTOCOL.

Just update your master, this was fixed a while ago.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n361

**Comment by pblemel** [comment]
Ah, many thanks!  I try to understand what's going on before I post.  I guess I should always get the master before digging in.  My master is only a couple of weeks old :)  

Thanks again,
Peter

**Comment by lws-team** [comment]
Feel free to optimize this process even more than my already having fixed the problem by sending me fixes for my mistakes before I find them myself :-)

**Comment by pblemel** [comment]
I'm slowly coming up to speed :).  The examples are all very helpful, and very clearly demonstrate the concepts - which is great. 

I have enough years of coding under my belt to be helpful and possibly contribute once I get a better understanding of the overall architecture. At this point most of issues are more like questions about what I may be doing wrong as a newb, but I understand that this is a complex piece of software and there are latent issues. I have found links to the mailing list, but they don't work.  ``` https://libwebsockets.org/git/libwebsockets``` has a link to ```https://libwebsockets.org/mailman/listinfo/libwebsockets```, but it just goes to an empty page.  Is the mailing list still active, or is this the place for general q&a now?

**Comment by pblemel** [comment]
Interesting ... The list home page shows up empty on my Windows computers that I have both at home and at work (Windows 7 and Windows 10, Chrome and Firefox). There's no errors, and the page source is simply empty.  The page displays fine on my Fedora and Ubuntu Linux machines (two of which are VMs in Windows boxes). 

If I follow a link from the home page in Linux (e.g. https://libwebsockets.org/pipermail/libwebsockets) and copy the link to a Windows box, that page will open fine in Windows. Following the link at the top of the archive page back to 'mailman' results again in an empty page on all of my Windows computers. 

For what it's worth, home and work are on two different ISPs (Centurylink and Comcast respectively).  The difference seems to be something about Windows versus Linux. 

*shrug*

**Comment by lws-team** [comment]
Much as I dislike windows, it's really not intentional.

Does the js console on any of the windows boxes say anything?  Libwebsockets.org has "best practice" Content Security Policy for a couple of months, if it's related to that there'll be some logging there.

**Comment by lws-team** [comment]
> Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.

Hum... I think it's just complaining about belt and braces... we don't use iframes on the site and the CSP is just trying to blanket ban them from being injected. ffox 63 on Linux doesn't say any of that.  Our cert isn't pinned either, so that may just be noise.

It may be telling us something about lws cgi handling.  The sequencing to close the wsi is a bit fraught with cgi, since the cgi process must have closed the stdout to signal no more is coming, lws must have flushed its side of the stdout pipe, and in tls case, the tls library must have actually transmitted what it buffered too before it's OK to close the wsi.  There was a site where you could run various virtual browsers "on windows" remotely I might try dig that up later.

**Comment by pblemel** [comment]
FF63 here as well.  Chrome is 70.0.3538.77.

**Comment by lws-team** [comment]
I used my semi-expired free account at browserstack

https://www.browserstack.com/screenshots/22b71ca3a52ebbcf66b2f98a2fb825c6ba9226ce

Actually the CSP is blocking the logo at the top left, the src is on warmcat.com but the CSP says images only from self and some selected places for badges.  It looks like some browsers honour the CSP for that and some don't.

Otherwise it's normal actually... is your windows box going through a proxy?

**Comment by pblemel** [comment]
I don't have a proxy either at home or at work.  

I do have new information. I received a new Win 10 computer today and just finished setting it up. I haven't installed antivirus or any of my developer tools on it yet (except cygwin), but went ahead and installed Chrome and Firefox to see if the problem is also on this machine. The page loads fine in Edge, Chrome, and Firefox.

I am out of time for tonight, but the common denominator between home and work (other than my developer tools) is Bit Defender antivirus. I'll install that tomorrow and see if the page mysteriously disappears again. I wouldn't expect it to, but there has to be something getting in the way and it has to be in common between work and home.

**Comment by pblemel** [comment]
Today FireFox is complaining about the certificate, but the URL is being weird.  I don't know why I'm suddenly being redirected to ```https://ml.libwebsockets.org/mailman/listinfo``` instead of ```https://libwebsockets.org/mailman/listinfo/```, but AFAIK I didn't do anything different.  Does the listserv site do some slight of hand with URLs that might be confusing the browser or silently violating cross-site-scripting rules?
```
https://ml.libwebsockets.org/mailman/listinfo Peer’s Certificate issuer is not recognized. HTTP Strict Transport Security: true HTTP Public Key Pinning: false Certificate chain: -----BEGIN CERTIFICATE----- MIIDYzCCAkugAwIBAgIJAMrvDiCBve6aMA0GCSqGSIb3DQEBCwUAMFQxITAfBgNV BAMMGFVudHJ1c3RlZCBCaXRkZWZlbmRlciBDQTEMMAoGA1UECwwDSURTMRQwEgYD VQQKDAtCaXRkZWZlbmRlcjELMAkGA1UEBhMCVVMwHhcNMTQxMTA0MDAwMDAwWhcN MTkxMTAzMjM1OTU5WjBVMSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0 ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRowGAYDVQQDExFsaWJ3ZWJzb2NrZXRz Lm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMjc4xHEaZzLziI4 3GicLjXES0Upvylke5DGkVyvzB6meNmr6OfcF3niFTmDwpUaQBSY6AIZK6pnyG6L 6XdVF38ihW4eTXckyN0GCYO6AL1QG/2PcobClPhuGw2LkhY4fwSh2HBuCUBXArkC T+HQbn+yPnEW1R2DbHHTro6BHsRVBCjfOPx9PJIbR/+cliK3uZGDFBR4qjuIlTPb eGRokKYm/mj2rovEs5cUGrkzgghIf7hk3sM84bfSqkkoJG08YBlvPx77DUgJaEHA OdYT/fWKT4vomJ8dt8o9RXs5rFOirEH41eZLSIYSp9GTePKrM3Lvj45GH+kvgwM5 /bbKeiUCAwEAAaM3MDUwMwYDVR0RBCwwKoIRbGlid2Vic29ja2V0cy5vcmeCFXd3 dy5saWJ3ZWJzb2NrZXRzLm9yZzANBgkqhkiG9w0BAQsFAAOCAQEAG50TlhNg7SRO kx5Wj+518OkqOdUhm8MZbrVdI1XVZLC3tr7Gc4wf0EudMygFirv/SoseJOwn7Lxe Md6svVoYcReaHJBrQ6WyDTDsKhwVfLj+EmfzmGF3AVCKDg03IBi3/9jdBWbZaEmB Em0C6DSp/5QI/sWVE5p+MD9KUHq3f2DxWeHojCjcpbZfod2qNpJ/ju0FKX5GWN7R LXrAbBsa90dQwp++Hyz4o3IX98kGCexhjQ6VBwfmE8325esN0u86SBPkHuhwsUoE PdoLT4gnOscN9EE77Grh3NPD6E1PsnJTJnRhPudMKWL6sFu1HKulWJz371aGsAJX tVPrWFaXiA== 
-----END CERTIFICATE----- 
```
I am just speculating that it's the antivirus, but frankly its just grasping at straws to try to help understand why this is happening. It's very consistent across several machines, on two different ISP networks, so it seems my environment must be the common denominator since no one else sees the problem.  Now that I'm back at my office my next step sometime today is to try get with the network admin to disable this antivirus/antimalware software and see if it makes any difference.
