### ISSUE TITLE
Minor issue in protocol_lws_minimal_client_echo.c example

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1437]
Hi,

protocol_lws_minimal_client_echo.c line 270 defines 
```
#define LWS_PLUGIN_PROTOCOL_MINIMAL_CLIENT_ECHO\
```
Line 284 uses
```
LWS_PLUGIN_PROTOCOL_MINIMAL_client_echo
```
Note the case change in 'client_echo'.  This only matters for dynamic loading, since the code is ifdef'd out for the static example.

Respectfully,
Peter

**Comment by lws-team** [comment]
Thanks, I pushed a small patch on master.
