### ISSUE TITLE
The ssl_options_set is not used in the client's connections

### ISSUE THREAD

**Issue by KhasanovRustam** [warmcat/libwebsockets#1438]
Hello, Andy!

I noticed the "ssl_options_set" field in the "lws_context_creation_info" only used in server's connections, not in client's connections.
The same about the "ssl_options_clear" field.

In my local copy I have added following code block:

/////////////////////////////

	if (info->ssl_options_set)
		SSL_CTX_set_options(vhost->tls.ssl_client_ctx, info->ssl_options_set);

/* SSL_clear_options introduced in 0.9.8m */
#if (OPENSSL_VERSION_NUMBER >= 0x009080df) && !defined(USE_WOLFSSL)
	if (info->ssl_options_clear)
		SSL_CTX_clear_options(vhost->tls.ssl_client_ctx, info->ssl_options_clear);
#endif

/////////////////////////////

into the "lws_context_init_client_ssl" function - line 135 in the  "tls-client.c" file, right before the 

	wsl_notice("created client ssl context for %s\n", vhost->name);

line.

Tested with my project, seems this did not break anything (at least in my project).

Rustam.

**Comment by lws-team** [comment]
Thanks.. I get the point and agree it's missing... with TLS v1.3 out in the wild now it's even more interesting to be able to enforce selection of protocol version.  The only problem with your change is you may be creating a context or vhost that has both a serving SSL_CTX and a client one.  In that case the options you may want to enforce may be different for each.  Eg, strict serving but the application has to be able to talk to less secure external servers as a client.

I pushed a patch on master that instead adds a couple of new longs to the info struct to allow setting options on the client ssl ctx separately, and added the code for it (and support in lejp-conf so lwsws can also use it).
