### ISSUE TITLE
CMake failed due to GCC warning

### ISSUE THREAD

**Issue by leo-papa** [warmcat/libwebsockets#1439]
I'm trying to install libwebsockets on my Raspi by compiling the source, but so far I got following error when calling `cmake ..`

Steps:

1. mkdir build
2. cd build
3. cmake ..

/home/pi/temp/libwebsockets/lib/core/libwebsockets.c:3185:13: error: comparison is always false due to limited range of data type [-Werror=type-limits]
     if (num < 0)
             ^
/home/pi/temp/libwebsockets/lib/core/libwebsockets.c:3193:13: error: comparison is always false due to limited range of data type [-Werror=type-limits]
     if (num < 0)
             ^

**Comment by lws-team** [comment]
It's because num is a char... and on arm32 gcc char defaults to being unsigned.

I pushed a small patch that should solve it.

https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=e7ef4e494b5b00d0209b4d790b26a18537e7ffba
