### ISSUE TITLE
double free or corruption (out) when lws_context_destroy() ver2.3

### ISSUE THREAD

**Issue by jjiego** [warmcat/libwebsockets#1441]
Hello,
I am asking about libwebsocket ver 2.3 

When I usually call the **lws_context_destroy** function with single thread.
But It comes SIGABT with **"double free or corruption (out)"** message.
Do you have any idea with below the callstack from that crash ??
Please give me any idea. 
Thank you.

### Callstack
Minimal Core was generated by `/usr/bin/acr'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58        ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb)bt
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58
#1  0xb5444f24 in __GI_abort () at /usr/src/debug/glibc-2.24/stdlib/abort.c:89
#2  0xb54803e4 in __libc_message (do_abort=<optimized out>, fmt=<optimized out>) at /usr/src/debug/glibc-2.24/libio/../sysdeps/posix/libc_fatal.c:175
#3  0xb5486f60 in malloc_printerr (action=3, str=0xb553b81c "double free or corruption (out)", ptr=<optimized out>, ar_ptr=ar_ptr@entry=0xb555b7c4 <main_arena>) at /usr/src/debug/glibc-2.24/malloc/malloc.c:5147
#4  0xb5487eac in _int_free (av=0xb555b7c4 <main_arena>, p=0xaa0e4e58, have_lock=<optimized out>) at /usr/src/debug/glibc-2.24/malloc/malloc.c:3975
#5  0xb64dff82 in CRYPTO_free (str=0xaa0e4e60) at /usr/src/debug/openssl-1.0.2k/crypto/mem.c:434
#6  0xb656beea in ASN1_STRING_free (a=0xaa0e4bd8) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/asn1_lib.c:429
#7  0xb656149a in ASN1_primitive_free (pval=<optimized out>, it=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:244
#8  0xb6561a7c in asn1_item_combine_free (combine=0, it=0xb65f99d4 <ASN1_OCTET_STRING_it>, pval=0xab9fd5c4) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:108
#9  ASN1_item_free (val=<optimized out>, it=0xb65f99d4 <ASN1_OCTET_STRING_it>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:72
#10 0xb6564a78 in ASN1_OCTET_STRING_free (a=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_typ.c:76
#11 0xb655dcee in x509_cb (operation=<optimized out>, pval=<optimized out>, it=<optimized out>, exarg=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/x_x509.c:116
#12 0xb6561a40 in asn1_item_combine_free (combine=0, it=0xb65f9588 <X509_it>, pval=0xab9fd5fc) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:169
#13 ASN1_item_free (val=<optimized out>, it=0xb65f9588 <X509_it>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:72
#14 0xb655ddcc in X509_free (a=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/x_x509.c:143
#15 0xb65828cc in cleanup (a=0xaa0e5020) at /usr/src/debug/openssl-1.0.2k/crypto/x509/x509_lu.c:222
#16 0xb6544e30 in sk_pop_free (st=0xaa096520, func=0xb65828a9 <cleanup>) at /usr/src/debug/openssl-1.0.2k/crypto/stack/stack.c:327
#17 0xb6582c36 in X509_STORE_free (vfy=0xaa0964d0) at /usr/src/debug/openssl-1.0.2k/crypto/x509/x509_lu.c:261
#18 0xb6637c94 in SSL_CTX_free (a=0xaa0960b8) at /usr/src/debug/openssl-1.0.2k/ssl/ssl_lib.c:2140
#19 0xb599ab6e in lws_ssl_SSL_CTX_destroy (vhost=0xaa095ec8) at /usr/src/debug/libwebsockets-2.3.0/lib/ssl.c:857
#20 0xb5996356 in lws_vhost_destroy2 (vh=0xaa095ec8) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1250
#21 0xb5996d88 in lws_context_destroy2 (context=0xaa0cf2f8) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1444
#22 0xb5996eee in lws_context_destroy (context=<optimized out>) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1415
...

(gdb)bt full
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {0, 0, 1818439534, 1953391977, 1651076143, 1701013868, 761623406, 1634623853, 762471783, 1735748720, 1663921769, 1852139884, 1869819508, 926310922, 808465250, 912403760, 808739383, 1914712112, 544222509, 808464432, 808464433, 976445984, 857748273, 875770419, 538976288, 1966022688, 1815048819, 1664049769, 1918987897, 1819291489, 1852401525, 1768710959}}
        pid = <optimized out>
        tid = <optimized out>
#1  0xb5444f24 in __GI_abort () at /usr/src/debug/glibc-2.24/stdlib/abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {808464432, 1646276656, 858864179, 925971232, 538981686, 538976288, 1920169263, 1651076143, 761556015, 875703858, 175076142, 1681340002, 808464483, 926310957, 808477796, 762454064, 807432237, 808464432, 540028976, 809119792, 540024880, 926310922, 808477796, 912403760, 811754807, 1914712112, 544222583, 808464432, 808464432, 976236576, 807415856, 912394784}}, sa_flags = 1, sa_restorer = 0x109}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0xb54803e4 in __libc_message (do_abort=<optimized out>, fmt=<optimized out>) at /usr/src/debug/glibc-2.24/libio/../sysdeps/posix/libc_fatal.c:175
        ap = {__ap = 0xab9fd4b4}
        fd = 2
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = 2
#3  0xb5486f60 in malloc_printerr (action=3, str=0xb553b81c "double free or corruption (out)", ptr=<optimized out>, ar_ptr=ar_ptr@entry=0xb555b7c4 <main_arena>) at /usr/src/debug/glibc-2.24/malloc/malloc.c:5147
        buf = "aa0e4e60"
        cp = <optimized out>
        tname = "ACRAudioSampler"
        tid = 3036
        pid = <optimized out>
        url_str = "…"
#4  0xb5487eac in _int_free (av=0xb555b7c4 <main_arena>, p=0xaa0e4e58, have_lock=<optimized out>) at /usr/src/debug/glibc-2.24/malloc/malloc.c:3975
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
        __func__ = "_int_free"
#5  0xb64dff82 in CRYPTO_free (str=0xaa0e4e60) at /usr/src/debug/openssl-1.0.2k/crypto/mem.c:434
No locals.
#6  0xb656beea in ASN1_STRING_free (a=0xaa0e4bd8) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/asn1_lib.c:429
No locals.
#7  0xb656149a in ASN1_primitive_free (pval=<optimized out>, it=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:244
        utype = <optimized out>
        it = <optimized out>
        pval = 0xab9fd5c4
#8  0xb6561a7c in asn1_item_combine_free (combine=0, it=0xb65f99d4 <ASN1_OCTET_STRING_it>, pval=0xab9fd5c4) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:108
        tt = 0x0
        seqtt = <optimized out>
        asn1_cb = <optimized out>
        i = <optimized out>
        ef = <optimized out>
        cf = <optimized out>
        aux = <optimized out>
#9  ASN1_item_free (val=<optimized out>, it=0xb65f99d4 <ASN1_OCTET_STRING_it>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:72
No locals.
#10 0xb6564a78 in ASN1_OCTET_STRING_free (a=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_typ.c:76
No locals.
#11 0xb655dcee in x509_cb (operation=<optimized out>, pval=<optimized out>, it=<optimized out>, exarg=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/x_x509.c:116
        ret = 0xaa1e35f8
#12 0xb6561a40 in asn1_item_combine_free (combine=0, it=0xb65f9588 <X509_it>, pval=0xab9fd5fc) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:169
        tt = <optimized out>
        seqtt = <optimized out>
        asn1_cb = <optimized out>
        i = <optimized out>
        ef = <optimized out>
        cf = <optimized out>
        aux = <optimized out>
#13 ASN1_item_free (val=<optimized out>, it=0xb65f9588 <X509_it>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/tasn_fre.c:72
No locals.
#14 0xb655ddcc in X509_free (a=<optimized out>) at /usr/src/debug/openssl-1.0.2k/crypto/asn1/x_x509.c:143
No locals.
#15 0xb65828cc in cleanup (a=0xaa0e5020) at /usr/src/debug/openssl-1.0.2k/crypto/x509/x509_lu.c:222
No locals.
#16 0xb6544e30 in sk_pop_free (st=0xaa096520, func=0xb65828a9 <cleanup>) at /usr/src/debug/openssl-1.0.2k/crypto/stack/stack.c:327
        i = 15
#17 0xb6582c36 in X509_STORE_free (vfy=0xaa0964d0) at /usr/src/debug/openssl-1.0.2k/crypto/x509/x509_lu.c:261
        i = 1
        sk = 0xaa096550
        lu = <optimized out>
#18 0xb6637c94 in SSL_CTX_free (a=0xaa0960b8) at /usr/src/debug/openssl-1.0.2k/ssl/ssl_lib.c:2140
        i = <optimized out>
        a = 0xaa0960b8
        i = <optimized out>
#19 0xb599ab6e in lws_ssl_SSL_CTX_destroy (vhost=0xaa095ec8) at /usr/src/debug/libwebsockets-2.3.0/lib/ssl.c:857
No locals.
#20 0xb5996356 in lws_vhost_destroy2 (vh=0xaa095ec8) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1250
        protocol = <optimized out>
        context = 0xaa0cf2f8
        n = <optimized out>
        __func__ = "lws_vhost_destroy2"
#21 0xb5996d88 in lws_context_destroy2 (context=0xaa0cf2f8) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1444
        vh = <optimized out>
        vh1 = <optimized out>
        __func__ = "lws_context_destroy2"
#22 0xb5996eee in lws_context_destroy (context=<optimized out>) at /usr/src/debug/libwebsockets-2.3.0/lib/context.c:1415
        pt = <optimized out>
        vh = <optimized out>
        wsi = {u = {http = {ah = 0xb553b81c, ah_wait_list = 0xab9fd4bc, preamble_rx = 0xab9fd4d8 "…", stash = 0xaa1e3868, preamble_rx_len = 3059718556, new_wsi_list = 0x65306161, filepos = 12366837298568258868, filelen = 8028058265534481217, fop_fd = 0x706d6153, range = {start = 7723443814004978792, end = 8299680450665673581, extent = 7939396917215325537, agg = 3414420575881229413, budget = 7954884362807635043, buf = "u.bbs.read.screen?p_club_id=875&p_menu_id=37&message_id=2403734\000(\232_\266XN\016\252@\303\000\000\230\021\017\252\230\303_\266?U\265\003\000\000\000\254~H\265\350et\000\203\377M\266\000\000\000\000\000\260U\265\001\000\000\000\230?\253\230m\t\252\000\000\000", pos = -1442222696, state = 2853064288, start_valid = 85 'U', end_valid = 220 '\334', ctr = 85 'U', count_ranges = 182 '\266', did_try = 252 '\374', inside = 213 '\325', send_ctr = 159 '\237'}, multipart_content_type = "\230\303_\266\204\303_\266\003\000\000\000\000\360h\000\350et\000\203\377M\266\330K\016\252\353\276V\266\304?\253\233\024V\266?_\266}\032V\266\220\274~\266\330K\016\252\370\065\036\252\370\065\036\252", request_version = (HTTP_VERSION_1_1 | unknown: 3059080276), connection_type = (unknown: 2879378940), content_length = 13141437212453225368, content_remain = 13138650406978584579}, hdr = {ah = 0xb553b81c, ah_wait_list = 0xab9fd4bc, preamble_rx = 0xab9fd4d8 "…", stash = 0xaa1e3868, preamble_rx_len = 3059718556, ups = 1697669473, ues = (unknown: 808871220), lextable_pos = -11008, current_token_limit = 1095910209, esc_stash = 117 'u', post_literal_equal = 100 'd', parser_state = 105 'i'}, ws = {hdr = {ah = 0xb553b81c, ah_wait_list = 0xab9fd4bc, preamble_rx = 0xab9fd4d8 "…", stash = 0xaa1e3868, preamble_rx_len = 3059718556, ups = 1697669473, ues = (unknown: 808871220), lextable_pos = -11008, current_token_limit = 1095910209, esc_stash = 117 'u', post_literal_equal = 100 'd', parser_state = 105 'i'}, rx_ubuf = 0x706d6153 <error: Cannot access memory at address 0x706d6153>, rx_ubuf_alloc = 7497068, rx_draining_ext_list = 0x70747468, tx_draining_ext_list = 0x6b2f2f3a, time_next_ping_check = 1932424045, rx_packet_length = 1932419941, rx_ubuf_head = 1970498913, mask = "ng.n", ping_payload_buf = "et/club/club.menu.bbs.read.screen?p_club_id=875&p_menu_id=37&message_id=2403734\000(\232_\266XN\016\252@\303\000\000\230\021\017\252\230\303_\266?U\265\003\000\000\000\254~H\265\350et\000\203\377M\266\000\000\000\000\000\260U\265\001\000\000\000\230?\253\230m\t\252", ping_payload_len = 0 '\000', mask_idx = 0 '\000', opcode = 0 '\000', rsv = 152 '\230', rsv_first_msg = 109 'm', close_in_ping_buffer_len = 9 '\t', utf8 = 170 '\252', stashed_write_type = 96 '`', tx_draining_stashed_wp = 78 'N', final = 0, frame_is_binary = 1, all_zero_nonce = 1, this_frame_masked = 1, inside_frame = 0, clean_buffer = 0, payload_is_close = 0, ping_pending_flag = 0, continuation_possible = 0, owed_a_fin = 1, check_utf8 = 0, defeat_check_utf8 = 1, pmce_compressed_message = 0, stashed_write_pending = 1, rx_draining_ext = 0, tx_draining_ext = 1, send_check_ping = 1, first_fragment = 0}}, pending_timeout_limit = 0, context = 0xb65f9588 <X509_it>, vhost = 0xb655dc55 <x509_cb>, parent = 0xb6561a41 <ASN1_item_free+160>, child_list = 0xb65ad50c, sibling_list = 0xaa1e35f8, protocol = 0xaa096520, same_vh_protocol_prev = 0xaa0e5020, same_vh_protocol_next = 0xaa096520, timeout_list = 0xb65828a9 <cleanup>, timeout_list_prev = 0xaa0968d8, user_space = 0x0, opaque_parent_data = 0x677598 <CACRWebSocket::t_Main()::__func__>, rxflow_buffer = 0xb65828cd <cleanup+36> "F\335", <incomplete sequence \351>, trunc_alloc = 0x10 <error: Cannot access memory at address 0x10>, active_extensions = {0xb6544e31 <sk_pop_free+40>, 0x2}, act_ext_user = {0xaa096550, 0xaa0964d0}, ssl = 0xb6582c37 <X509_STORE_free+122>, client_bio = 0xf1, pending_read_list_prev = 0x0, pending_read_list_next = 0x677598 <CACRWebSocket::t_Main()::__func__>, desc = {sockfd = -1442225992, filefd = -1442225992}, position_in_fds_table = -1234837504, rxflow_len = -1441991944, rxflow_pos = 1, trunc_alloc_len = 3059973269, trunc_offset = 2106, trunc_len = 825510912, chunk_remaining = -1442226488, cache_secs = 1, hdr_parsing_completed = 0, http2_substream = 0, listener = 0, user_space_externally_allocated = 1, socket_is_permanently_unusable = 1, rxflow_change_to = 3, more_rx_waiting = 1, conn_stat_done = 0, cache_reuse = 1, cache_revalidate = 0, cache_intermediaries = 0, favoured_pollin = 1, sending_chunked = 1, already_did_cce = 1, told_user_closed = 1, waiting_to_send_close_frame = 0, ipv6 = 0, parent_carries_io = 1, parent_pending_cb_on_writable = 1, do_ws = 0, chunked = 0, client_rx_avail = 0, client_http_body_pending = 0, extension_data_pending = 0, use_ssl = 5, redirect_to_https = 1, handling_pollout = 0, leave_pollout_active = 1, c_port = 43887, count_act_ext = 153 '\231', ietf_spec_revision = 181 '\265', mode = 200 '\310', state = 94 '^', state_pre_close = 9 '\t', lws_rx_parse_state = 170 '\252', rx_frame_type = 87 'W', pending_timeout = 99 'c', pps = 153 '\231', tsi = 181 '\265', protocol_interpret_idx = 30 '\036', redirects = 118 'v', chunk_parser = 103 'g', reason_bf = 0 '\000'}
        n = <optimized out>
        m = <optimized out>
….

**Comment by lws-team** [comment]
Hm... generally, the only way to understand what happened with these is to run the app under valgrind, and look for the first sign of insanity.

I guess it's an lws bug, but 2.3 is 17 months old now.  I don't plan spending any more time on it when v3.0 has been out for 7 months.

My suggestion is upgrade to master and see if the problem still exists... I would guess whatever it is, it is already solved and then case closed.  If not, help me reproduce it on master and I will certainly try to take care of it.

**Comment by lws-team** [comment]
Well, if it exists in master, let me know.
