### ISSUE TITLE
.\test-apps\test-client.c(283): error C2275: “X509_STORE”: 将此类型用作表达式非法

### ISSUE THREAD

**Issue by ll393595574** [warmcat/libwebsockets#1451]
\test-apps\test-client.c(283): error C2275: “X509_STORE”: 将此类型用作表达式非法
4>          C:\Program Files (x86)\OpenSSL\include\openssl/ossl_typ.h(126) : 参见“X509_STORE”的声明
4>..\test-apps\test-client.c(283): error C2065: “store”: 未声明的标识符
4>..\test-apps\test-client.c(284): error C2275: “X509_LOOKUP”: 将此类型用作表达式非法
4>          C:\Program Files (x86)\OpenSSL\include\openssl/ossl_typ.h(130) : 参见“X509_LOOKUP”的声明
4>..\test-apps\test-client.c(284): error C2065: “lookup”: 未声明的标识符
4>..\test-apps\test-client.c(284): error C2065: “store”: 未声明的标识符
4>..\test-apps\test-client.c(284): warning C4047: “函数”:“X509_STORE *”与“int”的间接级别不同
4>..\test-apps\test-client.c(284): warning C4024: “X509_STORE_add_lookup”: 形参和实参 1 的类型不同
4>..\test-apps\test-client.c(286): error C2143: 语法错误 : 缺少“;”(在“类型”的前面)

**Comment by ll393595574** [comment]
v3.0 stable

**Comment by ll393595574** [comment]
build by visual studio 10

**Comment by lws-team** [comment]
So what is your OpenSSL version on that box?

**Comment by lws-team** [comment]
Translating from Chinese it's complaining at the start about X509_STORE that "Use this type as an expression illegal"... the related code is

```
			X509_STORE *store = SSL_CTX_get_cert_store((SSL_CTX*)user);
			X509_LOOKUP *lookup = X509_STORE_add_lookup(store,
							X509_LOOKUP_file());
```

the rest of the errors and warnings seem downstream of the first error.

The file `include\openssl/ossl_typ.h` mentioned in the error was only introduced to OpenSSL in 1.1.0 AFAICS... the line number matches so I guess that's your version.

https://github.com/openssl/openssl/blob/b1aec9e84e2d36b0c4b45633d5343a39cb1ac25f/include/openssl/ossl_typ.h#L126

However it's just a typedef to a struct.  There's no problem with the way lws uses that.  Lws doesn't attempt to redefine it.

So I guess whatever causes that, is on your end.

**Comment by wini3d** [comment]
Hi @lws-team, I am having the same error and using OpenSSL 1.0.1i (Windows/Visual Studio)

so what would be the OpenSSL version/build would you recommend using?

```
1>..\test-apps\test-client.c(285) : error C2275: 'X509_STORE' : illegal use of this type as an expression
1>        C:\OpenSSL32bit\include\openssl/ossl_typ.h(155) : see declaration of 'X509_STORE'
1>..\test-apps\test-client.c(285) : error C2065: 'store' : undeclared identifier
1>..\test-apps\test-client.c(286) : error C2275: 'X509_LOOKUP' : illegal use of this type as an expression
1>        C:\OpenSSL32bit\include\openssl/x509_vfy.h(135) : see declaration of 'X509_LOOKUP'
1>..\test-apps\test-client.c(286) : error C2065: 'lookup' : undeclared identifier
1>..\test-apps\test-client.c(286) : error C2065: 'store' : undeclared identifier
1>..\test-apps\test-client.c(286) : warning C4047: 'function' : 'X509_STORE *' differs in levels of indirection from 'int'
1>..\test-apps\test-client.c(286) : warning C4024: 'X509_STORE_add_lookup' : different types for formal and actual parameter 1
1>..\test-apps\test-client.c(288) : error C2143: syntax error : missing ';' before 'type'
```

**Comment by lws-team** [comment]
Looking closer at that (contributed...) code

```
		if (crl_path[0]) {
			/* Enable CRL checking of the server certificate */
			X509_VERIFY_PARAM *param = X509_VERIFY_PARAM_new();
			X509_VERIFY_PARAM_set_flags(param, X509_V_FLAG_CRL_CHECK);
			SSL_CTX_set1_param((SSL_CTX*)user, param);
			X509_STORE *store = SSL_CTX_get_cert_store((SSL_CTX*)user);
			X509_LOOKUP *lookup = X509_STORE_add_lookup(store,
							X509_LOOKUP_file());
			int n = X509_load_cert_crl_file(lookup, crl_path,
							X509_FILETYPE_PEM);
```

The code itself is OK but actually the original author mixes code and declarations, which isn't done in the main lws code.  Does this problem magically go away if you straighten that out, like

```
		if (crl_path[0]) {
			/* Enable CRL checking of the server certificate */
			X509_STORE *store;
			X509_LOOKUP *lookup;
			int n;
			X509_VERIFY_PARAM *param = X509_VERIFY_PARAM_new();
			X509_VERIFY_PARAM_set_flags(param, X509_V_FLAG_CRL_CHECK);
			SSL_CTX_set1_param((SSL_CTX*)user, param);
			store = SSL_CTX_get_cert_store((SSL_CTX*)user);
			lookup = X509_STORE_add_lookup(store,
							X509_LOOKUP_file());
			n = X509_load_cert_crl_file(lookup, crl_path,
							X509_FILETYPE_PEM);
```

... or still the same?

**Comment by wini3d** [comment]
@lws-team Works Great!

**Comment by lws-team** [comment]
I pushed a patch with that on master and v3.2-stable... it seems only windows toolchain cares about it since it builds either way on gcc / clang.
