### ISSUE TITLE
Uncaught ReferenceError: new_ws is not defined

### ISSUE THREAD

**Issue by Elektroingenieur** [warmcat/libwebsockets#1454]
Hello warmcat. 
I got this error when running `minimal-http-server-eventlib-demo`

> (index):564 Uncaught ReferenceError: new_ws is not defined at (index):564

![screen shot 2018-11-15 at 15 46 04](https://user-images.githubusercontent.com/1821493/48541144-91c0eb00-e8ee-11e8-8ed9-f3b5729ffdea.png)

**Comment by Elektroingenieur** [comment]
Specs: 
MacOs 10.14.1 (18B75)
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by Elektroingenieur** [comment]
![screen shot 2018-11-15 at 16 10 52](https://user-images.githubusercontent.com/1821493/48542166-0e54c900-e8f1-11e8-8bd1-c41cbaad6076.png)

**Comment by lws-team** [comment]
I pushed a patch on master that aligns the test JS for that minimal sample with the CSP-compatible test assets for the test server... that also fixes this bug.
