### ISSUE TITLE
lws_callback_function * callback is called very slow, cause receive and send msg very slow, delay about 20~30s

### ISSUE THREAD

**Issue by DonXiAn** [warmcat/libwebsockets#1456]
websocket client connect to libwebsockets server log:

[  INFO] [2018-11-10 05:33:52] (LWP 434)  [wsi 551882464] [Web Socket] LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION request.	 in ../src/WebSocketServer.cpp(431)
...
[  INFO] [2018-11-10 05:34:02] (LWP 434)  [wsi 551882464] [Web Socket] LWS_CALLBACK_ESTABLISHED. user (null) in  connectionCount is 2	 in ../src/WebSocketServer.cpp(372)
[ ALERT] [2018-11-10 05:34:02] (LWP 434)  libwebsocket~ lws_header_table_detach: wsi 0x20e50ee0: ah held 30s, ah.rxpos 1130, ah.rxlen 1130, mode/state 5 5,wsi->more_rx_waiting 0
	 in ../src/WebSocketServer.cpp(604)

lws_get_peer_addresses(wsi_in, lws_get_socket_fd(wsi_in),
                               peer_name, sizeof peer_name, ip, sizeof ip);

problem service instance peer_name value is gateway,         ip value is 172.30.0.177.
normal   service instance  peer_name value is  172.30.0.173, ip value is  172.30.0.173.

**Comment by DonXiAn** [comment]
use libwebsockets C service has two instances, deployed in two vms, one vm has this problem, the other no problem.

**Comment by lws-team** [comment]
How about the slow guy has broken / misconfigured DNS resolution?

**Comment by lws-team** [comment]
> why address resolution can cause this problem.

That's something outside lws you need to look into.

Hint... look into not only /etc/resolv.conf, and /etc/hosts but also /etc/nsswitch.conf

http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html

**Comment by DonXiAn** [comment]
> How about the slow guy has broken / misconfigured DNS resolution?

slow guy service instance run ok. misconfigured DNS resolution we are checking now.

**Comment by DonXiAn** [comment]
> > why address resolution can cause this problem.
> 
> That's something outside lws you need to look into.
> 
> Hint... look into not only /etc/resolv.conf, and /etc/hosts but also /etc/nsswitch.conf
> 
> http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html

ie

**Comment by DonXiAn** [comment]
> How about the slow guy has broken / misconfigured DNS resolution?

ie websocket client send heartbeat msg more frequently,   backend libwebsockets recieves client user trigger service msg  need longer time.

**Comment by DonXiAn** [comment]
lws_header_table_detach called time is late 10s than lws_header_table_attach called.

**Comment by lws-team** [comment]
It seems this is the point

> [ ALERT] [2018-11-10 05:34:02] (LWP 434) libwebsocket~ lws_header_table_detach: wsi 0x20e50ee0: ah held 30s, ah.rxpos 1130, ah.rxlen 1130, mode/state 5 5,wsi->more_rx_waiting 0
in ../src/WebSocketServer.cpp(604)

What version of lws is this?  Please see if you get the same situation on master if it's not master.

**Comment by DonXiAn** [comment]
> It seems this is the point
> 
> > [ ALERT] [2018-11-10 05:34:02] (LWP 434) libwebsocket~ lws_header_table_detach: wsi 0x20e50ee0: ah held 30s, ah.rxpos 1130, ah.rxlen 1130, mode/state 5 5,wsi->more_rx_waiting 0
> > in ../src/WebSocketServer.cpp(604)
> 
> What version of lws is this? Please see if you get the same situation on master if it's not master.

2.0.3

**Comment by lws-team** [comment]
Do we have any results from trying master instead of v2.0.3?

**Comment by DonXiAn** [comment]
> Do we have any results from trying master instead of v2.0.3?

No. Now our problem reason is found, which is our callback function call many times lws_get_addresses func, but lws_get_addresses excuting use about 10s. cause other msg process is delayed seriously.
why lws_get_addresses excuting using so long 10s, currently we not study.

**Comment by lws-team** [comment]
> Now our problem reason is found

Not really, you are back to your reverse DNS arrangements being to blame.

It sounds like you don't feel this is actually an lws issue either, since you don't check lws master.  V2.0 is 3 years old now... see https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.problems.md

Notice in later versions of lws there's an api `lws_get_peer_simple()` which returns a dotted-quad IP like 1.2.3.4 and avoids the rdns

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-network-helper.h#n61-72
