### ISSUE TITLE
minimal-ws-server multithreading error

### ISSUE THREAD

**Issue by miaohongbiao** [warmcat/libwebsockets#1458]
hello, if i change the minimal example minimal-ws-server only add "info.count_threads=5", the server doesn't seem to work properly, if one clinet connect to the server, it will be faild, why? can you help me?

version for 3.0.1

thank u

**Comment by lws-team** [comment]
Just changing that member is not enough.  Look at

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-smp

**Comment by miaohongbiao** [comment]
thanks, i will try do it.
