### ISSUE TITLE
OSX Build Error with pthread

### ISSUE THREAD

**Issue by Digicrat** [warmcat/libwebsockets#1464]
The library fails to build for me out of the box on OSX.  Looking at the CMakeLists.txt, I see two comments regarding this issue that attempt to guard the -pthread flag.

Unfortunately, that guard does not work (at least on my machine).  Manually commenting out those two lines fixed it.  

I think the first of the two guards in there should be explicitly checking for 'Clang', since the UNIX flag does apply to OSX...

**Comment by lws-team** [comment]
I changed it to this.  But it's difficult to know what that will break if anything.  Even if it passes travis, I don't know if it fixes your problem; it passed travis OSX before this change.  So it is much preferable if I get a patch for your kind of problem so I at least know it fixes your problem.  I can observe myself if the fix breaks travis then.

```
if ((CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX OR (CMAKE_C_COMPILER_ID MATCHES "Clang") ) AND NOT LWS_WITHOUT_TESTAPPS)
        if ((UNIX OR (CMAKE_C_COMPILER_ID MATCHES "Clang")) AND LWS_HAVE_PTHREAD_H)
        # jeez clang understands -pthread but dies if he sees it at link time!
        # http://stackoverflow.com/questions/2391194/what-is-gs-pthread-equiv-in-clang
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread" )
    endif()
endif()
```
