### ISSUE TITLE
lws-minimal-ws-client-tx core dumped

### ISSUE THREAD

**Issue by sackett** [warmcat/libwebsockets#1465]
gdb ./lws-minimal-ws-client-tx
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Reading symbols from ./lws-minimal-ws-client-tx...done.
(gdb) run
Starting program: /home/m/libwebsockets/minimal-examples/ws-client/minimal-ws-client-tx/lws-minimal-ws-client-tx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2018/12/17 13:39:30:6867] USER: LWS minimal ws client tx
[2018/12/17 13:39:30:6867] USER:   Run minimal-ws-broker and browse to that
[2018/12/17 13:39:30:6868] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off

Program received signal SIGSEGV, Segmentation fault.
0x0000555555555c9b in callback_minimal_broker (wsi=0x7fffffffd9d0, reason=LWS_CALLBACK_EVENT_WAIT_CANCELLED, user=0x0, in=0x0, len=0)
    at /home/m/libwebsockets/minimal-examples/ws-client/minimal-ws-client-tx/minimal-ws-client.c:252
252                     if (vhd->client_wsi && vhd->established)
(gdb) bt
#0  0x0000555555555c9b in callback_minimal_broker (wsi=0x7fffffffd9d0, reason=LWS_CALLBACK_EVENT_WAIT_CANCELLED, user=0x0, in=0x0, len=0)
    at /home/m/libwebsockets/minimal-examples/ws-client/minimal-ws-client-tx/minimal-ws-client.c:252
#1  0x00007ffff7b97c9a in lws_broadcast () from /usr/local/lib/libwebsockets.so.14
#2  0x00007ffff7ba0204 in rops_handle_POLLIN_pipe () from /usr/local/lib/libwebsockets.so.14
#3  0x00007ffff7b9f6ee in lws_service_fd_tsi () from /usr/local/lib/libwebsockets.so.14
#4  0x00007ffff7bbb8a1 in _lws_plat_service_tsi.part.1 () from /usr/local/lib/libwebsockets.so.14
#5  0x00007ffff7b9f825 in lws_service () from /usr/local/lib/libwebsockets.so.14
#6  0x0000555555555ec0 in main (argc=1, argv=0x7fffffffe2d8)
    at /home/m/libwebsockets/minimal-examples/ws-client/minimal-ws-client-tx/minimal-ws-client.c:322

**Comment by lws-team** [comment]
Thanks... the callback can get called earlier than before, before the vhd is set up.  I pushed a patch on master + v3.1-stable fixing it.
