### ISSUE TITLE
Parsing error when ws sub-protocol contains '.' characters.

### ISSUE THREAD

**Issue by cjakeway** [warmcat/libwebsockets#1467]
Parsing of a web socket sub-protocol appears incorrect if the sub-protocol contains '.' characters.  Example: "v2.bookings.example.net"

This is repeatable with libwebsockets 3.1.0.

See lib/roles/server-ws.c, within lws_process_ws_upgrade(), when selecting the protocol, the call to lws_tokenize_init() should probably be:

`lws_tokenize_init(&ts, buf, LWS_TOKENIZE_F_COMMA_SEP_LIST |
				    LWS_TOKENIZE_F_MINUS_NONTERM |
				    LWS_TOKENIZE_F_DOT_NONTERM |
				    LWS_TOKENIZE_F_RFC7230_DELIMS);`

Cheers.

Chris

**Comment by lws-team** [comment]
Sorry this took a long time.... overload mode.  It's pushed on master + v3.1-stable.

**Comment by KhasanovRustam** [comment]
Does not work yet when a sub-protocol contains '.' characters.
The first lws_tokenize_init in the  lws_process_ws_upgrade() function should also contain the LWS_TOKENIZE_F_RFC7230_DELIMS option, otherwise it hurts the whole buffer - treats the '.' as delimiters.

**Comment by lws-team** [comment]
Thanks... I pushed as you suggested on master.
