### ISSUE TITLE
upload file with POST: callback with LWS_UFS_FINAL_CONTENT missing

### ISSUE THREAD

**Issue by veezhang** [warmcat/libwebsockets#1468]
Hello,

When uploading a file with http post sometimes the fileupload-callback with LWS_UFS_FINAL_CONTENT doesn't get called.

There is a pcap file
[upload-missing-LWS_UFS_FINAL_CONTENT.zip](https://github.com/warmcat/libwebsockets/files/2705157/upload-missing-LWS_UFS_FINAL_CONTENT.zip)

**Comment by lws-team** [comment]
- what version of lws?

- what's the client?

- the problem is coming with master lws plus this ninimal example?

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-form-post-file

**Comment by veezhang** [comment]
Thanks!!
I get the LWS_UFS_FINAL_CONTENT callback in minimal-http-server-form-post-file example.
And I will try more with my code.
Thanks again!

**Comment by chrthi** [comment]
I'd like to resurrect this issue as I can reproduce it on current master (ea50c8722cfa792355e2e15436f193e08b0fd173) with the minimal-http-server-form-post-file example. It seems LWS_UFS_FINAL_CONTENT does not appear when the spa `max_storage` is a power-of-two plus 1 and the file size is a multiple of this power-of-two. Instead I get an LWS_UFS_CONTENT for the last part. Uploading client was a chromium 76.0.3809.100, but the issue seems to be independent of that.

To see what happens, make these changes to `minimal-http-server-form-post-file.c`:
```diff
--- a/minimal-examples/http-server/minimal-http-server-form-post-file/minimal-http-server-form-post-file.c
+++ b/minimal-examples/http-server/minimal-http-server-form-post-file/minimal-http-server-form-post-file.c
@@ -52,6 +52,7 @@ file_upload_cb(void *data, const char *name, const char *filename,
 
        switch (state) {
        case LWS_UFS_OPEN:
+               lwsl_user("open(%s, %s)\n", name, filename);
                /* take a copy of the provided filename */
                lws_strncpy(pss->filename, filename, sizeof(pss->filename) - 1);
                /* remove any scary things like .. */
@@ -76,9 +77,13 @@ file_upload_cb(void *data, const char *name, const char *filename,
                                lwsl_notice("Problem writing file %d\n", errno);
                        }
                }
-               if (state == LWS_UFS_CONTENT)
+               if (state == LWS_UFS_CONTENT) {
+                       lwsl_user("CONTENT (%d)\n", len);
                        /* wasn't the last part of the file */
                        break;
+               }
+
+               lwsl_user("FINAL_CONTENT (%d)\n", len);
 
                /* the file upload is completed */
 
@@ -128,7 +133,7 @@ callback_http(struct lws *wsi, enum lws_callback_reasons reason, void *user,
 
                if (!pss->spa) {
                        pss->spa = lws_spa_create(wsi, param_names,
-                                       LWS_ARRAY_SIZE(param_names), 1024,
+                                       LWS_ARRAY_SIZE(param_names), 1025,
                                        file_upload_cb, pss);
                        if (!pss->spa)
                                return -1;
```

**Comment by lws-team** [comment]
I'll take a look at this tomorrow... it sounds pretty specific and has a reproducer both of which are good.

**Comment by lws-team** [comment]
If I understood it, all we need to do is to report FINAL_CONTENT even if it's a zero-length content... this is the usual pattern for this kind of thing but it seems the existing code tries to suppress a zero length one under some conditions.  I pushed a patch on master that disables this and the reproducer can work OK then, reporting a 0 length FINAL_CONTENT under the problem conditions... not sure if that breaks some other scenario, but please give it a go.

**Comment by chrthi** [comment]
I haven't had any problems with HTTP POSTs after this change. Thanks for the fix!
