### ISSUE TITLE
A typo in the client-handshake.c file

### ISSUE THREAD

**Issue by KhasanovRustam** [warmcat/libwebsockets#1469]
There is wrong function name "lws_out(wsi," in the line 44, supposed to be "lws_set_timeout(wsi," I guess

**Comment by lws-team** [comment]
Thanks... it's line 500-and-something, not 44.  I pushed a fix on master.

**Comment by KhasanovRustam** [comment]
This happened again, I guess it is some "auto-replacement" issue

**Comment by lws-team** [comment]
Thanks... It seems I pushed some stuff on my laptop and forget to fetch it on my main machine... it's fixed again now.
