### ISSUE TITLE
TCP keep alive on windows bug

### ISSUE THREAD

**Issue by bitomaxsp** [warmcat/libwebsockets#1477]
On windows keepalivetime  and keepaliveinterval are in milliseconds. While ka_time and ka_interval are in seconds in LWS. 

Proposed solution is:
```
alive.keepalivetime = vhost->ka_time *1000;
alive.keepaliveinterval = vhost->ka_interval *1000;
```
instead of that:
```
alive.keepalivetime = vhost->ka_time;
alive.keepaliveinterval = vhost->ka_interval;
```

**Comment by lws-team** [comment]
Thanks, I made a patch as you suggested and pushed on master and v3.1-stable.
