### ISSUE TITLE
Question about lws_callback_on_writable

### ISSUE THREAD

**Issue by NuclearC** [warmcat/libwebsockets#1479]
Hello,

In issue #932 you said:
`Your code might ask ten times while the receiving side is not sending ACKs for some time, and eventually get one callback, not ten.`
So I am interested, is there any way to make sure that after 10 calls to lws_callback_on_writable I will get exactly 10 callbacks of LWS_CALLBACK_SERVER_WRITABLE ? (when socket becomes writable, of course) Because in my program I have to send packets to the endpoint many times per second, and I use queue of packets for that. But after some time I notice that queue is starting to fill up (I am pushing packet into queue and calling lws_callback_on_writable, then in the callback I send the front packet and remove it from queue).

**Comment by lws-team** [comment]
> is there any way to make sure that after 10 calls to lws_callback_on_writable I will get exactly 10 callbacks of LWS_CALLBACK_SERVER_WRITABLE ?

Not from lws side.  You may also get additional callbacks under some conditions, if you had pending requests.  You should think of calling on_writable() as expressing an interest in hearing if you can eventually write something on that wsi.  When you do get the callback, you must assess at that time what to do with it.

> program I have to send packets to the endpoint many times per second

If you think carefully about that... you may generate several packets per second... but:

 - conditions at the remote endpoint (whether it reads them fast enough, if the phone went out of battery, fell in the sea, the train goes into a tunnel)...

 - conditions at every hop inbetween you and the remote sink (packetloss, network cable fell out, [someone abused BGP and is routing all your packets through a malicious PoP to the other side of the world before forwarding them](https://scholarcommons.usf.edu/cgi/viewcontent.cgi?article=1050&context=mca))...

 - conditions on the server (kernel memory availability to buffer, congestion at the network interface, load from too many connections create latency)...

... decide what you're actually going to be able to do with getting your generated data to the remote peer.  Unlike say witing data to a local UART a few times a second where you can reasonably feel the data source is in control and can dictate to the sink, with "Network Programming" the source is not in control of the outcome.  Code that acts like it's in control will break.

> after some time I notice that queue is starting to fill up 

Normally you would do one or both of

 - if still something in the queue after you just sent something, ask for another on_writable() at the end of the WRITEABLE callback.

 - if multiple things in the queue and they're small, coalesce them.  This needs support in the protocol, but if so you can also consider doing the coalesce when small things added to the queue.

**Comment by NuclearC** [comment]
Thanks for your response!
I will try calling on_writable in the writable callback if there are any pending packets in queue. The only problem is that I am trying to make a game server for an existing game client, which has to serve in WebSocket protocol and has low number of active connections. So I can not change the game's protocol in any way here. But thanks for your advice anyway! I will take them in my future projects.
