### ISSUE TITLE
using minilex for reading custom http response header and the concern of the license

### ISSUE THREAD

**Issue by jooncheol** [warmcat/libwebsockets#1481]
Hello libwebsockets!

I have a question regarding to the client development which reads custom http header from the webserver.
My project uses customs header between server and the client.
I was able to implement the code where the client set the custom header for the ws request by using the callback LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER.
But when the client have to handle the server response for the exception case like 3xx/4xx/5xx instead of normal flow like 101 for ws mode switching, I wanted to read extra information from the custom header that is used in my project.

It seems that the libwebsocket API only allow to give response header value by using pre-defined index for standard header. Only the possible way for this is following steps like https://github.com/warmcat/libwebsockets/issues/608 for adding custom header by using minilex tool in the libwebsockets.

I can try to follow this solution but there's 1 concern regarding the license.
If I add custom header by using code generation tool approach in the link, I guess I MUST open the changed source code since it is also kind of modification of the LGPL S/W even though it is just adding a index for custom header by using the tool in the libwebsockets.

If I add custom index for custom header by using the minilex for my project, is this also the case that I have to open the modified code in somewhere to avoid license violation? or this kind of (automatic?) modification using the code generation tool minilex in same libwebsockets project is allowed as LGPL+SLE as part of build process?

Thanks!!

**Comment by lws-team** [comment]
Well... normally I would say "send us your patch so it's already in upstream" to avoid having to worry about making the sources available.  But nonstandard headers are not really interesting to other users.  The primary concern for me is make sure we get new features, patches and fixes for everyone to use in exchange for the guy doing the changes getting lws to use in the first place.

It is a modification to lws sources, to comply with my understanding of the license you'd just need to push the lws tree + your patch adding the header parsing support to github or whatever and point to it... it's not really much of a drag.

> But when the client have to handle the server response for the exception case like 3xx/4xx/5xx instead of normal flow like 101 for ws mode switching, I wanted to read extra information from the custom header that is used in my project.

Hm... you know 3xx/4xx/5xx can all take http bodies.  If you put your extra info in the body of the error response you wouldn't need any custom headers.

**Comment by jooncheol** [comment]
Thanks Andy for quick response!!
okay, I'll consider to fork this project in the GitHub and put some changes and point it in the COPYING in my project. :-)

BTW, do you have any plan to support the API/callback I/F that allows to access the custom response header? or Do you mind to accept the patch for this use case if someone provide?

> Hm... you know 3xx/4xx/5xx can all take http bodies. If you put your extra info in the body of the error response you wouldn't need any custom headers.
Yes, I know but there is some case that is better to have such data in the header. e.g if there are multiple custom info, the body should have certain format to carry multiple data by using JSON, XML, protobuf... whatever it is. by having such data format in the header, adding multiple custom headers (it if is small size string) is more easy in many case :-)

**Comment by lws-team** [comment]
> BTW, do you have any plan to support the API/callback I/F that allows to access the custom response header? or Do you mind to accept the patch for this use case if someone provide?

No, lws approach is ignore headers it doesn't understand and parse the ones it does know about.

> Yes, I know but there is some case that is better to have such data in the header. 

Well, it's up to you how to do.  But you can just have the whole body as raw JSON if it's only coming on an error response code, it's pretty human-readable.  There shouldn't be a reason to repeat an error in multiple formats.

**Comment by jooncheol** [comment]
Thanks again !

**Comment by jooncheol** [comment]
sorry, 1 more question.


what if I apply the modification by using minilex for custom header *in the build procedure*? like below

> ./configure --prefix=xxx
> cd lib
> cat libwebsockets.h | sed -e "s/XXX/WSI_TOKEN_CUSTOMXYZ" > libwebsockets.h 
> gcc minilex.c -o minilex
> ./minilex
> cd ..
> make
> make install


is this also the case I have to open the fixes in somewhere like github?
(I know this is more like philosophy question :-) )

If so, what if the configure script have the option for adding custom header in the build time? like this

> ./configure --prefix=xxx --with-customheader=X-Foo-Bar
> make
> make install

in this case, configure script executes the minilex in it.  In this case, I think that the consumer who requires to read custom response header doesn't need to have a place to open the modified source code by minilex. because addition of the custom header is part of the configure, nothing is modified by user.

what do you think about this idea? is this suggestion acceptable in the libwebsockets project?
