### ISSUE TITLE
smp maybe crash sometime

### ISSUE THREAD

**Issue by miaohongbiao** [warmcat/libwebsockets#1483]
hello,
i have some questions about the smp mode. i set the thread_count = 10, and sometimes the programs crash, i can find the coredump infomation such as
lws_service_tsi(optimized out, 1, optimized out) ......
but i can get the threadindex from by my program in that coredump,  [compile lws debug mode,  -g] why is that?
can you help me?

**Comment by lws-team** [comment]
> but i can get the threadindex from by my program in that coredump, [compile lws debug mode, -g] why is that?

To turn off compiler optimizations, give cmake `-DCMAKE_BUILD_TYPE=DEBUG`.  `-g` on its own doesn't affect the optimization level as does `-O0` on gcc.  It just says whether the extra debug information will be generated or not.

If you find a locking problem or other problem inside lws, if you can give me a way to reproduce it on the smp minimal example, I will look at it.

**Comment by miaohongbiao** [comment]
yes, i compile  lws by set cmake -DCMAKE_BUILD_TYPE=DEBUG, i will try agin

**Comment by lws-team** [comment]
Usually `make V=1 VERBOSE=1` will print the command invoking the compiler.

If it's wrong for your platform and toolchain, look in `CMakeLists.txt` (search for, eg `-g` to find the right place) and send a patch or at least describe your platform + toolchain and what the flags should be.
