### ISSUE TITLE
i can't receive LWS_CALLBACK_EVENT_WAIT_CANCELLED message

### ISSUE THREAD

**Issue by miaohongbiao** [warmcat/libwebsockets#1484]
hi, i use the lws im smp mode, and use lws_cancel_service_pt at other thread, but i can't receive the LWS_CALLBACK_EVENT_WAIT_CANCELLED callback message, why? 
can you help me ? tks

**Comment by lws-team** [comment]
I added a minimal example aimed at this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads-smp

It works no problem here.  Please pull latest master and try it.
