### ISSUE TITLE
http client  custom header not working

### ISSUE THREAD

**Issue by kzhdev** [warmcat/libwebsockets#1488]
I'm using libwebsockets as an REST client. It can data from the server if no custom header involved. When the GET request requires custom header, it seems libwebsockets is not sending the custom header to server. I am adding custom header in LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER callback as following:

```
case LWS_callback_CLIENT_APPEND_HANDSHAKE_HEADER: {
    unsigned char **p = (unsigned char**)in;
    unsigned char *end = (*p) + len -1;
    // adding user agent
    if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_USER_AGENT, (unsigned char*)"libwebsocket", 12, p, end)) {
        return -1;
    }

    // adding custom headers
    if (!req->request->headers.empty()) {
        for (auto& kvp : req->request->headers) {
            printf("**** %s:%s\n", kvp.first.c_str(), kvp.second.c_str());
            if (lws_add_http_header_by_name(wsi, (const unsigned char*)kvp.first.c_str(), (const unsigned char*)second.c_str(), (int)kvp.second.size(), p, end)) {
                return -1;
            }
        }
    }
    break;
```

The printf shows:
```
**** CB-ACCESS-KEY: xxxxxxx
**** CB-ACCESS-PASSPHRASE: xxxxxxx
**** CB-ACCESS-SIGN: xxxxx
....
```
However, the server responed {"message": "CB-ACCESS-KEY header is required."}. It seems the custom headers is not added correctly.

I tried to add custom headers fist then adding the User-Agent header, but still get same response.

I know the USER_AGENT is added because w/o that, server returns {"message":"User-Agent header is required."}

Please advise what is the correct way to add multiple custom headers. Thanks!

**Comment by lws-team** [comment]
> (const unsigned char*)second.c_str()

Do you not mean, ...`kvp.second.c_str()`... there?

**Comment by kzhdev** [comment]
Yes

**Comment by lws-team** [comment]
So that's the problem?

**Comment by kzhdev** [comment]
No, that's not the problem. That's just a typo. 

I figured out. The problem is that the name must have ":" in the end.

**Comment by lws-team** [comment]
All is well then :-)
