### ISSUE TITLE
No LWS_CALLBACK_FILTER_NETWORK_CONNECTION from client

### ISSUE THREAD

**Issue by SreyasSultan** [warmcat/libwebsockets#1489]

**Comment by SreyasSultan** [comment]
Here i use libWebsockets-1.7.6
what all reason where this callback would not return.

**Comment by lws-team** [comment]
> 1.7.6

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.problems.md

> No LWS_CALLBACK_FILTER_NETWORK_CONNECTION from client

This gets called on the **server** when a client connects..

```
	LWS_CALLBACK_FILTER_NETWORK_CONNECTION			= 17,
	/**< called when a client connects to
	 * the server at network level; the connection is accepted but then
	 * passed to this callback to decide whether to hang up immediately
	 * or not, based on the client IP.  in contains the connection
	 * socket's descriptor. Since the client connection information is
	 * not available yet, wsi still pointing to the main server socket.
	 * Return non-zero to terminate the connection before sending or
	 * receiving anything. Because this happens immediately after the
	 * network connection from the client, there's no websocket protocol
	 * selected yet so this callback is issued only to protocol 0. */
```

**Comment by lws-team** [comment]
Who knows since I can't see your code.  Or if your code is the server, or the client.

What I suggest you do if getting started is not use 1.7.6 but use latest master or last stable release, v3.1-stable branch.  And look at the >50 minimal examples for various scenarios.  You can build them try them, and if you feel there are problems, you can tell me how to reproduce the problem since we will both have the same code.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples

**Comment by SreyasSultan** [comment]
Ok thanks. Where can i get what all changes went in from 1.7.7 to latest. Just want to check will those changes might help my case.

**Comment by lws-team** [comment]
fetch or clone master, and then

```
git log v1.7.0.. --oneline
```

There are 1703 patches, and between v1.7.0 and v1.7.6 there are 85 patches.

Maybe this helps to understand why while you're completely at liberty to use whatever version you want, you had better be ready that nobody will help you with ancient versions.  That's true of lws and of anything else, Linux, windows, firefox, whatever.

**Comment by SreyasSultan** [comment]
Thanks. is there any standard way how to handle LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS..?

**Comment by lws-team** [comment]
You should back up and clearly describe what you are trying to do.  None of the minimal examples need to use it, and they cover a lot of use-cases.
