### ISSUE TITLE
causes of No LWS_CALLBACK_FILTER_NETWORK_CONNECTION

### ISSUE THREAD

**Issue by SreyasSultan** [warmcat/libwebsockets#1490]
If we didn't handle LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS callback, will it cause No LWS_CALLBACK_FILTER_NETWORK_CONNECTION

**Comment by lws-team** [comment]
There is no need to open a new issue

Dup of https://github.com/warmcat/libwebsockets/issues/1489
