### ISSUE TITLE
minimal-ws-server is not building on ubuntu 18.04

### ISSUE THREAD

**Issue by jahir1105** [warmcat/libwebsockets#1491]
I have built and installed lws on Ubuntu 18.04. I can see files at `/usr/lib/libwebsockets.*` `/usr/include/libwebsockets*` locations.

then I tried to build inside `minimal-examples/ws-server/minimal-ws-server` folder using `cmake . && make`. I got below errors. How can this be fixed?

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jahir/localview/libwebsockets/minimal-examples/ws-server/minimal-ws-server
[ 50%] Linking C executable lws-minimal-ws-server
CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: In function `callback_minimal':
minimal-ws-server.c:(.text+0x78): undefined reference to `lws_get_vhost'
minimal-ws-server.c:(.text+0xd0): undefined reference to `lws_get_vhost'
minimal-ws-server.c:(.text+0x11d): undefined reference to `lws_get_vhost'
CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: In function `main':
minimal-ws-server.c:(.text+0x3aa): undefined reference to `lws_cmdline_option'
minimal-ws-server.c:(.text+0x476): undefined reference to `lws_cmdline_option'
minimal-ws-server.c:(.text+0x4da): undefined reference to `lws_cmdline_option'
CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o:(.data.rel+0x8): undefined reference to `lws_callback_http_dummy'
collect2: error: ld returned 1 exit status
CMakeFiles/lws-minimal-ws-server.dir/build.make:94: recipe for target 'lws-minimal-ws-server' failed
make[2]: *** [lws-minimal-ws-server] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lws-minimal-ws-server.dir/all' failed
make[1]: *** [CMakeFiles/lws-minimal-ws-server.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lws-team** [comment]
I have an 18.04 VM right in front of me... I

1) cloned master

```
 $ git clone https://libwebsockets.org/repo/libwebsockets
```

2) and built and installed the library

```
 $ cd libwebsockets
 $ mkdir build
 $ cd build
 $ cmake ..
 $ make && sudo make install
```

**you can't skip the make install**

3) went into the example and built it

```
 $ cd ../minimal-examples/http-server/minimal-http-server
 $ cmake .
 $ make
```

It builds with no error.

Judging from your error, the libwebsockets.a your example build is picking up is from an earlier version of lws, perhaps the Ubuntu packaged version, or missing the library at all.  Ensure you did the `make install` when you built the library and try removing an existing lws package.

**Comment by lws-team** [comment]
Notice also by default the `make install` puts things in /usr/local/.... not /usr ...

**Comment by jahir1105** [comment]
It worked for me on another ubuntu device. I guess "the libwebsockets.a your example build is picking up is from an earlier version of lws" is the root cause. Andy, I appreciate your prompt help on this.
