### ISSUE TITLE
Is it possible to compile it as static library on Mac?

### ISSUE THREAD

**Issue by diuming** [warmcat/libwebsockets#1492]
Hi master,

I'm lucky finding websocket client for multi-platforms.
currently! I can compile it as dynamic library. But I prefer static library. 
So, Can I compile it as static library(.a) on Mac?
Thanks

**Comment by lws-team** [comment]
At least on Linux, by default it builds both the .so and the .a ... you can find the .a at `./build/lib/libwebsockets.a`.

It decides to build static or not based on `LWS_WITH_STATIC` which defaults to ON.

And I can't see anything in CMakeLists.txt turning that off based on BSD or APPLE or whatever.

Are you sure it's not created, actually?

**Comment by lws-team** [comment]
And Travis on OSX builds it...

https://travis-ci.org/warmcat/libwebsockets/jobs/489802099#L2789

**Comment by diuming** [comment]
@lws-team thanks for reply
Sorry! It's my mistake.
I found .a file in build folder
