### ISSUE TITLE
multi thread reuse iface&port error

### ISSUE THREAD

**Issue by BrentHuang** [warmcat/libwebsockets#1497]
**there are 2 threads:**
[ALWAYS demo_server 0x7f7fb8e95740 2019-02-15 20:35:30 457.495 app_frame.cpp:552] ws thread count: 2
[ALWAYS demo_server 0x7f7fb8e95740 2019-02-15 20:35:30 459.190 ws_threads.cpp:73] libwebsockets version: 3.0.1 unknown-build-hash

**thread #1 initialized successfully: (ens33:10000 for ws, ens33:10443 for wss)**
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 618.991 ws_controller.cpp:463] ws listen addr port: 192.168.8.138:10080
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 624.328 ws_controller.cpp:463] wss listen addr port: 192.168.8.138:10443
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 624.381 ws_controller.cpp:495] cert file: ../conf/xxx_com.crt
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 624.383 ws_controller.cpp:498] private key file: ../conf/xxx_com.key

**thread #2 initialized failed, but iface "ens33" is also used ok in thread #1:**
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 631.733 ws_controller.cpp:463] ws listen addr port: 192.168.8.138:10080
[ERROR demo_server 0x7f017b996740 2019-02-15 20:41:45 637.873 ws_threads.cpp:16] ERROR on binding fd 47 to port 10080 (-1 98)

[ERROR demo_server 0x7f017b996740 2019-02-15 20:41:45 638.108 ws_threads.cpp:16] VH default: iface ens33 port 10080 DOESN'T EXIST

[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 638.241 ws_controller.cpp:463] wss listen addr port: 192.168.8.138:10443
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 638.244 ws_controller.cpp:495] cert file: ../conf/xxx_com.crt
[ALWAYS demo_server 0x7f017b996740 2019-02-15 20:41:45 638.245 ws_controller.cpp:498] private key file: ../conf/xxx_com.key
[ERROR demo_server 0x7f017b996740 2019-02-15 20:41:45 644.993 ws_threads.cpp:16] ERROR on binding fd 50 to port 10443 (-1 98)

[ERROR demo_server 0x7f017b996740 2019-02-15 20:41:45 645.254 ws_threads.cpp:16] VH default: iface ens33 port 10443 DOESN'T EXIST

**Comment by BrentHuang** [comment]
I set LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE | LWS_SERVER_OPTION_LIBEVENT opts. And not create vhost by hand.

**Comment by lws-team** [comment]
More context needed...

What is your platform?

Putting your code I can't see to one side, what's happening when you run the smp example unchanged?

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-smp

**Comment by lws-team** [comment]
> version: 3.0.1

... and what happens on master lws

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.problems.md

**Comment by BrentHuang** [comment]
thank you very much!    I modify my code just  like 'minimal-http-server-smp', it's ok now.

but I find the cpu usage is not 0 when no events happen.  in the backtrace, I see epoll_wait's timeout is 1. Is it too small?  How to set the loop timeout when with libevent?

ps, my code: 'https://github.com/Confucius-Mencius/common_component/blob/master/ws_threads/src/ws_controller.cpp'

**Comment by lws-team** [comment]
You're right... it's a bug the "idle event" I added to libevent to follow libuv's idle event has a timer that's wrongly set EV_PERSIST.  It doesn't break anything but it's not properly idling since the EV_PERSIST makes it feel it should keep telling us it's idle over and over.

I pushed a patch fixing it on v3.1-stable and master.
