### ISSUE TITLE
In `lib/parsers.c` data type `char` assumed to be signed

### ISSUE THREAD

**Issue by djlauk** [warmcat/libwebsockets#150]
A while ago I cross compiled libwebsockets for an ARM based embedded device.

At first it would not work, giving the following error message:
~~~~~~
[  3%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
/usr/local/src/libwebsockets/lib/parsers.c: In function `libwebsocket_parse':
/usr/local/src/libwebsockets/lib/parsers.c:252: warning: comparison is always false due to limited range of data type
/usr/local/src/libwebsockets/lib/parsers.c:265: warning: comparison is always false due to limited range of data type
make[2]: *** [CMakeFiles/websockets.dir/lib/parsers.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
~~~~~~

The issue is, that in `lib/parsers.c`, line 165, function `char_to_hex`, the value `-1` is returned to indicate an error condition, while the return type is `char`. On a platform where `char` is unsigned, the comparisons on line 252 and 265 (`char_to_hex(c) < 0`) can never be true.

I have fixed the issue by changing the comparisons on lines 252 and 265.

**Comment by warmcat** [comment]
We changed it to signed char a while back.
