### ISSUE TITLE
Is it possible to add a helper address in protocols? for the very start

### ISSUE THREAD

**Issue by diuming** [warmcat/libwebsockets#1500]
Hi,
Is it possible to add a helper address in protocols for later use in callback function.
I try to add it in protocols, but no effect.
could you give me some advice?
thanks

simple swift code
---
```
class WebSocket {
    .
    .
    func setupProtocols() {
        self.protocols = UnsafeMutablePointer<lws_protocols>.allocate(capacity: 2)
        protocols.initialize(to: lws_protocols())
        let selfPtr = Unmanaged.passUnretained(self).toOpaque()
        self.protocols.advanced(by: 0).pointee.name = UnsafePointer<Int8>("my-protocol")
        self.protocols.advanced(by: 0).pointee.callback = lwsCallbackFunction
        self.protocols.advanced(by: 0).pointee.user = selfPtr <-- here
        .
        .
    }
}
```

**Comment by lws-team** [comment]
```
struct lws_protocols {
...
 void *user; /**< ignored by lws, but user code can pass a pointer
			here it can later access from the protocol callback */
```

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-protocols-plugins.h#n72-73

If you set this to point to some protocol-specific object, in the callback you can get it like this

```
    void *mydata = NULL;
    If (lws_get_protocol)
        mydata = lws_get_protocol(wsi)->user;
```

That's what you're doing and there's some problem?  What is the problem?  Or you want to do something different?

**Comment by diuming** [comment]
@lws-team thanks

Thank your, it works!

finally, I found the mistake.
I direct use `void *user` in callback function.

lws_callback_function(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len);

**Comment by lws-team** [comment]
> I direct use void *user in callback function.

Yes that's something different, per-connection private user data.  (In the examples, this is called `pss`).  For server it's auto-allocated for each incoming connection according to the size given in the protocol struct.  For client you can provide your own when you create the outgoing connection or again have it autoallocated.

In addition to per-protocol you found, there is also the chance to attach per-context and per-vhost user pointers if your app has data that makes sense to bind like that.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n314-322
