### ISSUE TITLE
How to make two vhosts (network and unix domain socket) simultaneously

### ISSUE THREAD

**Issue by nikitos1550** [warmcat/libwebsockets#1501]
Hi!

I am trying to process requests via network and UDS simultaneously. 
lws is build with -DLWS_UNIX_SOCK=ON.

First I am creating context with lws_create_context and emply info (only LWS_SERVER_OPTION_EXPLICIT_VHOSTS option).

Than using  lws_create_vhost to create several vhosts, one for network connection, another for UDS. The problem is that lws_create_vhost function (core/context.c line 709) check network or UDS socket via following code:

```
#ifdef LWS_WITH_UNIX_SOCK
	if (LWS_UNIX_SOCK_ENABLED(context)) {
		lwsl_notice("Creating Vhost '%s' path \"%s\", %d protocols\n",
				vh->name, vh->iface, vh->count_protocols);
	} else
#endif
	{
		switch(info->port) {
		case CONTEXT_PORT_NO_LISTEN:
			strcpy(buf, "(serving disabled)");
			break;
		case CONTEXT_PORT_NO_LISTEN_SERVER:
			strcpy(buf, "(no listener)");
			break;
		default:
			lws_snprintf(buf, sizeof(buf), "port %u", info->port);
			break;
		}
```

macro LWS_UNIX_SOCK_ENABLED defined as (core/private.h):
```
#ifdef LWS_WITH_UNIX_SOCK
#define LWS_UNIX_SOCK_ENABLED(vhost) \
    (vhost->options & LWS_SERVER_OPTION_UNIX_SOCK)
#else
#define LWS_UNIX_SOCK_ENABLED(vhost) (0)
#endif
```
So, lws_create_vhost checks context option value that was filled via lws_create_context, so there is no way to create two different vhots.

What is the proper way to solve my issue?
Mabe I can change LWS_UNIX_SOCK_ENABLED macro and check network or UDS not via context, but via vhost options or something other individual vhost param, but I am not very familiar with internal lws architecture, so I can also imagine, that lws doesn`t support simultaneous net and UDS and I can use only one transport via one context.

**Comment by lws-team** [comment]
>  #define LWS_UNIX_SOCK_ENABLED(vhost) \ (vhost->options & LWS_SERVER_OPTION_UNIX_SOCK)
> So, lws_create_vhost checks context option value that was filled via lws_create_context, so there is no way to create two different vhots.

Well... on master and v3.1-stable, it checks the vhost there, not the context.

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/vhost.c#n590-611
https://libwebsockets.org/git/libwebsockets/tree/lib/core/context.c?h=v3.1-stable#n543-564

However all that code does is log what it's listening on, it's cosmetic and in itself doesn't affect anything else.

So use master or v3.1-stable.
