### ISSUE TITLE
Get headers from http responce

### ISSUE THREAD

**Issue by ylaskin** [warmcat/libwebsockets#1507]
Hi,
I implemented a http client with lws. So now i'm trying to get http response headers like "set-cookie:", "token:". How can I do it? 

Thanks.

**Comment by lws-team** [comment]
Lws knows around 100 standard header strings

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/lextable-strings.h

When lws get http headers, it parses the known headers into an index number

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n214

There are apis to query the values of those headers

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n344-353
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n368-383

Headers that lws doesn't know about are ignored by lws.

So for set-cookie, you'd use the apis with WSI_TOKEN_HTTP_SET_COOKIE.  "token" is something lws can't read.  If it's a standard header in an RFC somewhere, I'll consider adding it to lws.

There's some example code for querying a header here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-broker/protocol_lws_minimal.c#n113

**Comment by ylaskin** [comment]
Trying to get header "Set-Cookie" from this response but it's not working.
While trying to get "Content-Type" it's working fine.

```
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Set-Cookie: si=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhaWQiOiJjODA0MjNkMy0xNTE4LTRlNWMtYTVkOC1lNGE1ZGI5Nzg5NTgiLCJpZCI6ImQ5MjllODY0LTU3ZDctNGIzMS1iNTVjLTQzZmY5N2IwMGEwMyIsInVpZCI6IjAwOjBDOjI5OjA0OkZGOjExOjAwOjAwIn0.DMALaIZMeHvgOvvonwkFxFUN9mIzG4DyYuyJXpjDYko
Date: Wed, 27 Feb 2019 11:13:24 GMT
Content-Length: 16
........
```

**Comment by lws-team** [comment]
"Not working" is not very useful information...

The copy api returns <0 if the length of your buffer isn't enough, is that what is happening?  If not, what exactly is happening?

**Comment by ylaskin** [comment]
> "Not working" is not very useful information...
> 
> The copy api returns <0 if the length of your buffer isn't enough, is that what is happening? If not, what exactly is happening?

Sorry my failed. Found the problem. 
Thanks for quick help.
