### ISSUE TITLE
Question: Supporting ws-over-h2 as client

### ISSUE THREAD

**Issue by yoshigev** [warmcat/libwebsockets#1508]
Hi,
We are currently evaluating LWS for a client application that would possibly open several WebSockets towards the same server.
We thought of using ws-over-h2 (RFC 8441) for minimizing the number of TLS connections.
I understand that LWS currently doesn't support ws-over-h2 (RFC 8441) for client side.

Do you think that it is a feature that will be added in the future, or is there some reason that made you decide that it will not be supported?

Thank you very much,
Yehoshua

**Comment by lws-team** [comment]
> Do you think that it is a feature that will be added in the future, or is there some reason that made you decide that it will not be supported?

Well... nobody paid me to do any of the h2 work, nor the RFC8441 server-side work.

The remarkable thing is not that there's no RFC8441 client-side support but more that any h2 / ws-over-h2 support exists for you to pick up and use for free.

I personally had a reason to want to see very low-end h2 and ws-over h2 server support, so I implemented it.  I don't to date have a use for ws-over-h2 client.  But that may change as soon as someone is willing to fund the work.

**Comment by yoshigev** [comment]
Thank you very much for the very quick reply.
I do appreciate the support that exists for h2 and server-side ws-over-h2 (though it's less relevant to our current project).
And I got the answer I was looking for regarding client-side ws-over-h2.
