### ISSUE TITLE
Server crashes after "ignoring, ah parsing incomplete"

### ISSUE THREAD

**Issue by nodi-andy** [warmcat/libwebsockets#1510]
Hello,
i let run a server overnight but i experience very often, that the server crashes after 100k msgs abouts:
"NOTICE: lws_http_transaction_completed: (from IP.IP.IP.IP) ignoring, ah parsing incomplete"

The IP addresses were once from china and other from argentine etc. seems to be random.

1- Does this happend because of someone checks random IP's (scanner) and libwebsocket dies in a endless loop?
2- Or is this any kind of ddos?
3- How can i prevent this, that libwebsocket just ignore this

Thanks in advance

**Comment by lws-team** [comment]
Well there are two aspects to that.... yes I have been seeing these for months on libwebsockets,.org.  I captured a packet from it and googled what was in it, it's a scripted attack aimed at a microsoft web server.  The script doesn't care it just spams everyone with a million broken http transactions.  Lws is immune to it and does just ignore it.

The second aspect is why you're crashing... make sure you're using latest master and then either run your server under valgrind, or attach gdb to the lwsws child process, if that's what you're running.

What kind of platform is it?  It may simply be the amount of logging killing you.

**Comment by nodi-andy** [comment]
i think the logging is killing me. How can i reduce log or exclude this error from logging?

**Comment by lws-team** [comment]
... couple of other points...

 - you can get rid of that logging by commenting this

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/server/server.c#n2033-2034

 - If you find lws under libuv is spinning at 100% cpu, this is libuv catching a SIGSEGV.  You can attach gdb (gdb -p <process>) to the lwsws child process and get a backtrace.

**Comment by nodi-andy** [comment]
now i have commented this line out and compiled new. It will take another 3-4 hours till the next attack. May be a protection mechanism would be better, if an ip send 10 broken transaction, then ignore it for 10minutes....

**Comment by lws-team** [comment]
AFAIK lws is completely immune to these attacks and has been since before they started... the only change I made when I saw them in the logs was to have it print the IP.  If something's crashing I'll be interested in the backtrace.

Please make sure it's built with `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` so the backtrace has source info.

**Comment by nodi-andy** [comment]
the failure is just gone. I think that was an system error because of MBs of error log. Still need a backtrace? you can just start an instance in google cloud and they will find you :)

**Comment by lws-team** [comment]
Well... good.  I run lws master myself on a dedicated server for https://libwebsockets.org and https://warmcat.com, so if there are problems "coming from the Internet" I stand a good chance to meet them first and fix them.

**Comment by nodi-andy** [comment]
i think you get a better chance to get a problem "coming from internet" if you run on aws or gcloud. I had time to time running databases on servers, never had an accicent, till i ran once on cloud. The ip range of cloud servers must be exposed and seen as vulnerable

**Comment by lws-team** [comment]
It's possible, but my server is a middling-cheap OVH dedicated box... it gets several of those particular scripted attacks a day and a wide range of other bogons and bots.  The idea of any server is "it's IP range is exposed", I think if you're looking at the raw internet nowadays everyone is under attack.

If I see persistant nastiness, I do a whois and if I don't see I ever want to hear from those guys legitimately, blackhole their entire netblock as a source with iptables.
