### ISSUE TITLE
lws_client_connect_via_info

### ISSUE THREAD

**Issue by ypiker** [warmcat/libwebsockets#1514]
I'm sorry. Maybe the description is wrong just now. If the server address is "ws://127.0.0.1:9651/CertDow", then using lws_client_connect_via_info to connect will get LWS_CALLBACK_CLIENT_CONNECTION_ERROR. If I need to be able to connect, what should I do? Thank you very much!
Part of the code is as follows:

   struct lws_client_connect_info tConnectInfo;
    memset(&tConnectInfo, 0, sizeof(tConnectInfo));
    tConnectInfo.context = s_ptContext;
    tConnectInfo.address = "127.0.0.1/CertInfo";
    tConnectInfo.port = 2012;
    tConnectInfo.path = "/";
    tConnectInfo.protocol = protocols->name;
    tConnectInfo.host = "127.0.0.1";
    clientWs = lws_client_connect_via_info(&tConnectInfo);

**Comment by lws-team** [comment]
Path would be /Certinfo... the address would just be 127.0.0.1

**Comment by ypiker** [comment]
> Path would be /Certinfo... the address would just be 127.0.0.1
I've tried this modification but still failed to connect to the service.
struct lws_client_connect_info tConnectInfo;
memset(&tConnectInfo, 0, sizeof(tConnectInfo));
tConnectInfo.context = s_ptContext;
tConnectInfo.address = "127.0.0.1";
tConnectInfo.port = 2012;
tConnectInfo.path = "/CertInfo";
tConnectInfo.protocol = protocols->name;
tConnectInfo.host = "127.0.0.1";
clientWs = lws_client_connect_via_info(&tConnectInfo);

**Comment by lws-team** [comment]
What do the logs say... can anyone connect to it?  Eg `telnet 127.0.0.1 2012` can connect at least in tcp sense?

**Comment by ypiker** [comment]
> What do the logs say... can anyone connect to it? Eg `telnet 127.0.0.1 2012` can connect at least in tcp sense?

The error description is as follows：HS: ACCEPT missing。    
I used webDemo to test that the connection was successful.

**Comment by ypiker** [comment]
> What do the logs say... can anyone connect to it? Eg `telnet 127.0.0.1 2012` can connect at least in tcp sense?


Wrong report in this place：
if (lws_hdr_total_length(wsi, WSI_TOKEN_ACCEPT) == 0) {
		lwsl_info("no ACCEPT\n");
		*cce = "HS: ACCEPT missing";
		goto bail3;
	}

**Comment by ypiker** [comment]
> What do the logs say... can anyone connect to it? Eg `telnet 127.0.0.1 2012` can connect at least in tcp sense?

This is Google Connection Debugging Information. I hope it will help you.
General：----------------------------------------------------------------------
Request URL: ws://127.0.0.1:2012/CertInfo
Request Method: GET
Status Code: 101 Switching Protocols
ResponseHeader：-------------------------------------------------------------
HTTP/1.1 101 Switching Protocols
Server: websocket-sharp/1.0
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: JAXMnKqUNl5ploCXhJhf5QLSCnI=
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; server_no_context_takeover
request headers------------------------------------------------------
GET ws://127.0.0.1:2012/CertInfo HTTP/1.1
Host: 127.0.0.1:2012
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Upgrade: websocket
Origin: http://www.blue-zero.com
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Sec-WebSocket-Key: gaP5ZpwfE1s/3d798IO4mg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Comment by ypiker** [comment]
> What do the logs say... can anyone connect to it? Eg `telnet 127.0.0.1 2012` can connect at least in tcp sense?
If I use the latest version, the error description is as follows：
HS: ws upgrade response not 101.

**Comment by lws-team** [comment]
What's teh debugging headers from google that matches this attempt using latest lws?

**Comment by lws-team** [comment]
> GET ws://127.0.0.1:2012/CertInfo

This shouldn't look like that.

It should just say "GET /Certinfo HTTP/1.1"

**Comment by ypiker** [comment]
> > GET ws://127.0.0.1:2012/CertInfo
> 
> This shouldn't look like that.
> 
> It should just say "GET /Certinfo HTTP/1.1"


I use win7.

**Comment by lws-team** [comment]
Even on windows 7 :-)

You should have this

```
tConnectInfo.path = "/Certinfo";
```

**Comment by ypiker** [comment]
> Even on windows 7 :-)
> 
> You should have this
> 
> ```
> tConnectInfo.path = "/Certinfo";
> ```

Do you have any ideas now?

**Comment by ypiker** [comment]
> tConnectInfo.path = "/Certinfo";

TConnectInfo. path = "/ Certinfo"; not working?

**Comment by lws-team** [comment]
"Not working" tells me nothing.

When you use latest lws, and set path like that, what does the google debug logs say?  What does lws say?

**Comment by ypiker** [comment]
> "Not working" tells me nothing.
> 
> When you use latest lws, and set path like that, what does the google debug logs say? What does lws say?

"Not working" tells me nothing.

I tested that both IE and Firefox were able to connect ws://127.0.0.1:2012/CertInfo successfully. Use the latest LWS connect  ws://127.0.0.1:2012/CertInfo  . an error:HS: WS upgrade response not 101.

**Comment by ypiker** [comment]
> "Not working" tells me nothing.
> 
> When you use latest lws, and set path like that, what does the google debug logs say? What does lws say?

I can send you websocket service Demo if necessary。

**Comment by lws-team** [comment]
> When you use latest lws, and set path like that, what does the google debug logs say? What does lws say?

**Comment by lws-team** [comment]
Well, let's reopen this if you want to provide the requested info.
