### ISSUE TITLE
Ping frame time interval is 1 second longer than expected ws_ping_pong_interval

### ISSUE THREAD

**Issue by echuaba** [warmcat/libwebsockets#1518]
**Observed:**
Regardless of time interval set for ws_ping_pong_interval (1s, 5s, 30s), time between ping frames is always 1 second greater than expected.

**Libwebsockets version:**
libwebsockets-2.4-stable

**Some debug findings:**
Whenever wsi->u.ws.time_next_ping_check is updated, it uses the current system time plus ws_ping_pong_interval, which will always increase 1 second more. 

**Potential solution:**
Original code: 
wsi->u.ws.time_next_ping_check = (time_t)lws_now_secs() + wsi->context->ws_ping_pong_interval;
Instead it should be
wsi->u.ws.time_next_ping_check = (time_t)lws_now_secs() - 1 + wsi->context->ws_ping_pong_interval;

**Comment by lws-team** [comment]
Well... I think you are right... but it's been like that for years and is something that doesn't need fixing isn't it?  Whatever is waiting on the PING can't judge it so tightly as to fail it after +1s.  A ping interval of 2^32-1 seconds is not going to be used.  These checks are done roughly at 1Hz, but on an idle system it depends on the poll timeout and on a loaded system what other work it did first exactly as to where inside a wallclock second the handling for this is done... it's just not that subsecond accurate anyway.

You can just adjust the interval you ask for by 1s to compensate...
