### ISSUE TITLE
how can i get Parameters from url when client connect to lws? 

### ISSUE THREAD

**Issue by missac** [warmcat/libwebsockets#1519]
in callback reason: LWS_CALLBACK_HTTP, i can use lws_get_urlarg_by_name to get the parameters.
but how to get url parameters in a  Upgrade request ?
like this：
GET /xxxx?x=11&y=22 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: xxxx
Origin: xxxx
Sec-WebSocket-Key: fQ04qe3yEk2C9cA159TiJA==
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol:

**Comment by lws-team** [comment]
The same way... the parsed http headers are still attached to the wsi when the `LWS_CALLBACK_ESTABLISHED` comes.

**Comment by missac** [comment]
i want get x=11 and y=22,  not the headers.. does x = 11 also parsed and saved in wsi ?

**Comment by missac** [comment]
thank you~~

**Comment by lws-team** [comment]
Yes.  Wsi that are in http mode attach another structure called an "ah" temporarily to contain the parsed http headers.  At the time of the ESTABLISHED callback, that wsi is about to transition to ws mode and have its ah detached.  But it's still attached at the time of the call, and all the related apis about http header querying work the same as if it was still in http mode.

Immediately after you return from ESTABLISHED callback, the ah is detached so it's freed up for use by another connection.  So for ws connections, ESTABLISHED is the time you should look up whatever you care about from the headers that upgraded it to ws.  That goes for the urlargs like x=y and whole header contents the same.
