### ISSUE TITLE
make fails at - 'Linking C executable bin/libwebsockets-test-client'

### ISSUE THREAD

**Issue by Choxmi** [warmcat/libwebsockets#1525]
I have cloned the master branch of the repo and installed the latest version of openssl (openssl-1.0.2r). Previously I was able to build the library with openssl 1.0.1 2014 version. I tried rolling back to openssl 1.0.2g which I was able to build the repo earlier. 

But now non of this work for me. build fails at 48%. May be an incorrect link to test-server I guess. @lws-team can you please help me with this. Your help is much appreciated.

Here is the log: 

`[ 47%] Building C object CMakeFiles/websockets.dir/lib/event-libs/poll/poll.c.o
[ 47%] Building C object CMakeFiles/websockets.dir/lib/misc/lejp.c.o
[ 48%] Building C object CMakeFiles/websockets.dir/lib/roles/http/server/lejp-conf.c.o
Linking C static library lib/libwebsockets.a
[ 48%] Built target websockets
[ 48%] Building C object CMakeFiles/test-client.dir/test-apps/test-client.c.o
Linking C executable bin/libwebsockets-test-client
lib/libwebsockets.a(ssl.c.o): In function `lws_ssl_destroy':
ssl.c:(.text+0x15b): undefined reference to `SSL_COMP_free_compression_methods'
lib/libwebsockets.a(ssl.c.o): In function `lws_ssl_context_destroy':
ssl.c:(.text+0x6bc): undefined reference to `SSL_COMP_free_compression_methods'
lib/libwebsockets.a(tls-server.c.o): In function `lws_tls_server_conn_alpn':
tls-server.c:(.text+0xd4): undefined reference to `SSL_get0_alpn_selected'
lib/libwebsockets.a(tls-server.c.o): In function `lws_context_init_server_ssl':
tls-server.c:(.text+0x318): undefined reference to `SSL_CTX_set_alpn_select_cb'
lib/libwebsockets.a(tls-server.c.o): In function `lws_server_socket_service_ssl':
tls-server.c:(.text+0x506): undefined reference to `SSL_get0_alpn_selected'
lib/libwebsockets.a(tls-server.c.o): In function `lws_context_init_alpn':
tls-server.c:(.text+0x92): undefined reference to `SSL_CTX_set_alpn_select_cb'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/libwebsockets-test-client] Error 1
make[1]: *** [CMakeFiles/test-client.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by lws-team** [comment]
- various versions of openssl add and remove various apis

 - lws has cmake inspects your libraries and generate various preprocessor flags that guide compilation according to what apis you have

 - cmake caches these in `./build`, mainly in `./build/CMakeCache.txt`

 - if you change your tls library so that it now has different apis, you must make cmake inspect it again by deleting `./build/CMakeCache.txt` and running cmake again... you will need to give any cmake `-D` flags again since they are also cached.

**Comment by Choxmi** [comment]
@lws-team I tried removing `./build/CMakeCache.txt` and deleting the entire build folder as well. But non of them worked for me. It always crashes at `Scanning dependencies of target test-client`. Could there be any other cached locations?

**Comment by lws-team** [comment]
> It always crashes

It's not crashing... it's just giving link-time build errors.

>  installed the latest version of openssl (openssl-1.0.2r). 

What exactly have you done to try to use 1.0.2r?

Considering the error you pasted

```
bin/libwebsockets-test-client lib/libwebsockets.a(ssl.c.o): In function lws_ssl_destroy':
ssl.c:(.text+0x15b): undefined reference to SSL_COMP_free_compression_methods' 
```

this is a linker error... so it found compiler headers with it OK.

You seem to be compiling it against 1.0.2 OpenSSL headers with the api and then linking it against some later (?) OpenSSL library which has removed the api.

**Comment by Choxmi** [comment]
> What exactly have you done to try to use 1.0.2r?

I got an error regarding HTTP2 when I was using 1.0.1 2014 version. Therefore I had to update openssl and I updated it to the latest.

> this is a linker error... so it found compiler headers with it OK.

Okay @lws-team thanks a lot. I went through the openssl installation and found that there is a file named `libssl.so` in `/usr/lib/x86_64-linux-gnu/` directory.

New openssl installation does not create a `.sso` file and `libwebsockets` is linked to that `.so` file. That may be the issue. Is there any way to change the link to `libssl.a` from the latest openssl version? Can I do that by changing `./build/CMakeCache.txt`?

**Comment by lws-team** [comment]
> I got an error regarding HTTP2 when I was using 1.0.1 2014 version.

If you want http2, it needs a tls library version that supports ALPN.  1.0.2 does and 1.0.1 doesn't.  So it's right, you can't mix and match those.

AFAIK there's no reason not to just use latest OpenSSL, currently 1.1.1b.  That's what I use on current Fedora.

> New openssl installation does not create a .sso file and libwebsockets is linked to that .so file

By default on 1.0.2 it only builds static (.a)... the default changed on later OpenSSL to shared.  But for 1.0.2. you have to tell the OpenSSL configure stuff to build 

If you build and install openssl from source like this (do a `make clean` first if you already built things there)

```
 $ ./Configure linux-x86_64 shared
 $ make -j12 && sudo make install
```
...he will put everything in `/usr/local/ssl` by default.  That's good, because if you trample on your OS openssl, you will kill packaged OS apps that dynamically link against the old one.

Both .so and .a can be found in `/usr/local/ssl/lib`

```
$ ls -l /usr/local/ssl/lib
drwxr-xr-x. 2 root root    4096 Mar 20 13:18 engines
-rw-r--r--. 1 root root 4570304 Mar 20 13:18 libcrypto.a
lrwxrwxrwx. 1 root root      18 Mar 20 13:18 libcrypto.so -> libcrypto.so.1.0.0
-r-xr-xr-x. 1 root root 2702784 Mar 20 13:18 libcrypto.so.1.0.0
-rw-r--r--. 1 root root  763866 Mar 20 13:18 libssl.a
lrwxrwxrwx. 1 root root      15 Mar 20 13:18 libssl.so -> libssl.so.1.0.0
-r-xr-xr-x. 1 root root  521712 Mar 20 13:18 libssl.so.1.0.0
```

By default lws will use your OS versions.  You can override it to your versions like this

```
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl
```

You may need to point /etc/ld.so.conf at /usr/local/ssl and then run `ldconfig` before it can bind to your openssl library.  You can use ldd to see what stuff is actually binding to

```
$ ldd ./lib/libwebsockets.so.14
	linux-vdso.so.1 (0x00007ffd1ed59000)
	libssl.so.1.0.0 => /usr/local/ssl/lib/libssl.so.1.0.0 (0x00007fc150b3c000)
	libcrypto.so.1.0.0 => /usr/local/ssl/lib/libcrypto.so.1.0.0 (0x00007fc1506e5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc150524000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007fc15051d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc1504fb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc150335000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc15032d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc150df3000)
```

**Comment by Choxmi** [comment]
@lws-team thank you very much for the response and I'm rally sorry for bothering. But I'm still stuck here.  I did cmake with `cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl`. I have those relevant openssl libraries there as well. But in cmake it always detect the old openssl path. 

`Compiling with SSL support
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/libcrypto.so (found version "1.0.1f") 
OpenSSL include dir: /usr/include
OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/libcrypto.so`

I tried removing openssl quite a few times. But non of them worked for me. I copied `libssl.so` from my 16.4 machine to the  `x86_64-linux-gnu/` of 14 machine. I was able to complete make and make install. But when I run my application  it shows `symbol lookup error: /usr/local/lib/libwebsockets.so.14: undefined symbol: SSL_CTX_set_alpn_select_cb` error.

> You may need to point /etc/ld.so.conf at /usr/local/ssl and then run ldconfig before it can bind to your openssl library. You can use ldd to see what stuff is actually binding to

And  I failed to get this output. I don't have a `./lib/libwebsockets.so.14` there.

Once again I'm really so for making some troubles for you. Your help is much appreciated. Thanks

**Comment by lws-team** [comment]
It worked for me when I tried it earlier today.

But there's a second way to define it explicitly...

```
 $ cmake .. -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/ssl/include/openssli -DLWS_OPENSSL_LIBRARIES="/usr/local/ssl/lib/libssl.so;/usr/local/ssl/lib/libcrypto.so"
```

... see if that's any different.

> And I failed to get this output. I don't have a ./lib/libwebsockets.so.14 there.

Right now you can't build it yet.

**Comment by Choxmi** [comment]
@lws-team That's awesome. It worked for me. Thanks a lot.

**Comment by 1393987347** [comment]
你好！在make 的时候出现了这样的的问题，生成libwebsockets.so失败，需要怎么样解决？
[ 88%] Building C object lib/CMakeFiles/websockets_shared.dir/event-libs/poll/poll.c.o
[ 88%] Building C object lib/CMakeFiles/websockets.dir/roles/ws/ops-ws.c.o
[ 89%] Building C object lib/CMakeFiles/websockets.dir/roles/ws/client-ws.c.o
[ 89%] Building C object lib/CMakeFiles/websockets.dir/roles/ws/client-parser-ws.c.o
[ 90%] Linking C shared library libwebsockets.so
CMake Error: failed to create symbolic link 'libwebsockets.so': operation not supported on socket
CMake Error: cmake_symlink_library: System Error: Operation not supported
lib/CMakeFiles/websockets_shared.dir/build.make:1244: recipe for target 'lib/libwebsockets.so.18' failed
make[2]: *** [lib/libwebsockets.so.18] Error 1
make[2]: *** Deleting file 'lib/libwebsockets.so.18'
CMakeFiles/Makefile2:1418: recipe for target 'lib/CMakeFiles/websockets_shared.dir/all' failed
make[1]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Building C object lib/CMakeFiles/websockets.dir/roles/ws/server-ws.c.o
[ 92%] Building C object lib/CMakeFiles/websockets.dir/roles/raw-file/ops-raw-file.c.o
[ 92%] Building C object lib/CMakeFiles/websockets.dir/roles/raw-skt/ops-raw-skt.c.o
[ 93%] Building C object lib/CMakeFiles/websockets.dir/roles/listen/ops-listen.c.o
[ 93%] Building C object lib/CMakeFiles/websockets.dir/roles/http/client/client-http.c.o
[ 94%] Building C object lib/CMakeFiles/websockets.dir/roles/netlink/ops-netlink.c.o

**Comment by lws-team** [comment]
@1393987347 Your problem is something completely different than OP's.

> [ 90%] Linking C shared library libwebsockets.so
> CMake Error: failed to create symbolic link 'libwebsockets.so': operation not supported on socket
> CMake Error: cmake_symlink_library: System Error: Operation not supported

Your platform seems to believe that anything `*.so` is a socket!  I have never seen that before.

What kind of OS are you building on?
