### ISSUE TITLE
Is there any way that user can give some events to the libwebsocket (user-callback) ?

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1529]
Hi,
Is there anyway that the user can give event to the user callback where we handle the connection established,connection close,writable,data recv reasons ?.

Actually i need to look up into a queue and send the queue element via websocket, currently i am checking the queue element continuously , which i don't think good.

**Comment by lws-team** [comment]
There are two basic scenarios:

 - you added data to your queue synchronously, ie, from inside the event loop.  Eg, as the result of processing a RECEIVE callback.  After adding to the queue, you can just call one of the `lws_callback_on_writable()` family to get a WRITEABLE callback on wsi you want to write to, where you can check your queue, send, and book another `on_writable()` for the wsi if more to send.

 - you added data to your queue asynchronously, ie, from another thread.  From the other thread after adding to the queue, you should signal the lws service thread(s) something happened by calling `lws_cancel_service()`... the lws service loop may be idle and sleeping, this interrupts the sleep and calls back `LWS_CALLBACK_EVENT_WAIT_CANCELLED` from the lws service thread context.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n774-779

From there, you can check your queue and do the `callback_on_writable()` on wsi that need to send stuff now in the queue.
