### ISSUE TITLE
porting guide

### ISSUE THREAD

**Issue by tushartp** [warmcat/libwebsockets#1531]
Hello,

is there any porting guide or documents available to port to different OS environment/architecture?
I want to port it STM32H753 hardware from STMicroelectronics.
I am running FreeRTOS OS, LWIP TCP/IP stack and FatFs filesystem.
mbedTLS as ssl library

Thanks,
Tushar

**Comment by lws-team** [comment]
I pushed a short README with the general flow on master.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.porting.md

The situation is a bit mixed atm... on the one hand, lws already supports ESP32, which is exactly freertos + lwip + mbedTLS stack.  So the code is there and there is no doubt it can work on another similar platform... it looks like STM32 has more assets / memory than ESP32 so there's also no doubt it will fit OK.

On the other hand, currently the support for freertos + lwip, and for ESP32 is not separated out properly.  So you have to do more work than should be necessary also duplicating preprocessor conditionals in core lws like `#if !defined(LWS_WITH_ESP32) ,,,` mainly aimed at disabling stuff that does not apply to freertos.  I intend to refactor this, so the freertos part can be selected separately, but not immediately.

It looks like the dev board is US$400 or so which is more than I care to pay without a use for it.  But I would be happy to help generally and integrate what you have when it's ready.  Presumably there's a free toolchain somewhere for reproducing build issues.

**Comment by tushartp** [comment]
Thanks for providing the answer. 
I will try to port it.
There is an cheaper board that you can try on STM32F769I-DISCO which is the same cortex m7 devices but uses less cpu frequency. 
I am using the free IDE from STM32 Atollic Trustudio to build my project.

Regards,
Tushar
