### ISSUE TITLE
How to enable LWS_WITH_THREADPOOL?

### ISSUE THREAD

**Issue by wirelessr** [warmcat/libwebsockets#1534]
Hi Andy,
I want to build the example minimal-ws-server-threadpool on ubuntu, but the cmake says:
`This project requires lws must have been configured with
  LWS_WITH_THREADPOOL`
I have installed the pthread, and it seems can be detected:
`Looking for pthread.h - found`
Is there any dependency I have to install?

**Comment by lws-team** [comment]
Libwebsockets is very configurable at build time... it has many features that are off by default to keep the default size down.  You can use `-DLWS_WITH_THREADPOOL=1` on libwebsockets' cmake to build lws with threadpool support.

The cmake stuff in the example is actually checking if lws was built with threadpool enabled.

**Comment by wirelessr** [comment]
I appreciate your prompt response. This is very helpful to me.
