### ISSUE TITLE
openssl-server.c build error: "incomplete definition of type 'struct ssl_ctx_st'"

### ISSUE THREAD

**Issue by iThinker** [warmcat/libwebsockets#1538]
I am trying to build latest master, with OpenSSL 1.1.0 and mostly default settings. But I encounter error like:
`.../libwebsockets/lib/tls/openssl/openssl-server.c:414:38: error: 
      incomplete definition of type 'struct ssl_ctx_st'
        x = sk_X509_value(vhost->tls.ssl_ctx->extra_certs, 0);`
The exact line may be different because I was building different commits.
Initially I've looked at `LWS_HAVE_SSL_EXTRA_CHAIN_CERTS` flag which is derived from `SSL_CTX_get_extra_chain_certs_only` symbol presence. If I force enable this flag, everything builds fine. But in 3.0 this symbols is not found as well, and 3.0 builds fine.
So I did more investigation and found out that another define was changed - `LWS_HAVE_OPENSSL_ECDH_H` was replaced with `OPENSSL_NO_EC` in commit `4edd5cad`. So I tried to make a build in this commit and commit before. And build with this change fails, but commit before succeeds.
Not sure what is the correct way to resolve this issue. Cmake team suggests not to use CHECK_SYMBOL_EXISTS https://gitlab.kitware.com/vtk/vtk/issues/17178 thus maybe correctly deriving `LWS_HAVE_SSL_EXTRA_CHAIN_CERTS` availability is the right approach.

**Comment by lws-team** [comment]
Hm all but one of the big block of checks in CMakeLists.txt necessary to work with openssl use CHECK_FUNCTION_EXISTS.  But for that particular one it's CHECK_SYMBOL_EXISTS.

Maybe what's happened it in some openssl it's a #define and in others a function (and in yet others, it doesn't exist in either form).  If so, you could try adapt CMakeLists.txt to both methods in temp vars and set the final LWS_HAVE_ if either were present.

Something to be careful of when switching versions is cmake caches all these tests aggressively.  You have to delete CMakeCache.txt in your build dir each time you swap versions of lws or dependent libs to recheck these presence tests and get sane results.  That goes triple if you feel you have been seeing confusing or contradictory results and have not been deleting CMakeCache.txt.

**Comment by iThinker** [comment]
Looking at `ssl.h`, `SSL_CTX_get_extra_chain_certs_only` is indeed a macro. So I doubt checking function will help. I will investigate more, and post if I find any way to properly find this symbol.

**Comment by iThinker** [comment]
Apparently my dependency resolution was bad, and openssl folder was set incorrectly. Sorry for the hassle, symbol check works fine.
