### ISSUE TITLE
NOTICE: kalki.io connection error! (HS: UPGRADE malformed)

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1541]
Hi i am using libwebsocket 3.1.0 version, When i connect to websocket-server the below mentioned error is coming.

NOTICE: kalki.io connection error! (HS: UPGRADE malformed)

**Comment by lws-team** [comment]
Turn your client lws logging up to eg, -d 1151 and paste what it says.

Trying to connect to it with lws demo protocols just gets me a 403, I guess you have to have the right protocol name to get anywhere with it.

**Comment by arunkvnss** [comment]
My server supports only one protocol, And it works fine with 3.0.0,
Verbose level is already maximum, And i got only the below message

[2019/04/05 14:55:55:3004] NOTICE:  connection error! (HS: UPGRADE malformed)

**Comment by lws-team** [comment]
Then build lws with `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` and retry.

**Comment by arunkvnss** [comment]
Okay that i will do, and let u know , And one more issue , if i go with libwebsocket 3.0.0 version 

I am getting an invalid pointer on user parameter under the LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION reason, so that i could not do any ssl functionality and its crashing too.

**Comment by arunkvnss** [comment]
And the above issue is happening in ubuntu 18.04 only,

**Comment by lws-team** [comment]
> I am getting an invalid pointer on user parameter under the LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION reason, so that i could not do any ssl functionality and its crashing too.

For that particular reason, it passes x509_ctx in place of user.

```
	LWS_CALLBACK_OPENSSL_PERFORM_CLIENT_CERT_VERIFICATION	= 23,
	/**< if the libwebsockets vhost was created with the option
	 * LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT, then this
	 * callback is generated during OpenSSL verification of the cert
	 * sent from the client.  It is sent to protocol[0] callback as
	 * no protocol has been negotiated on the connection yet.
	 * Notice that the libwebsockets context and wsi are both NULL
	 * during this callback.  See
	 *  http://www.openssl.org/docs/ssl/SSL_CTX_set_verify.html
	 * to understand more detail about the OpenSSL callback that
	 * generates this libwebsockets callback and the meanings of the
	 * arguments passed.  In this callback, user is the x509_ctx,
	 * in is the ssl pointer and len is preverify_ok
	 * Notice that this callback maintains libwebsocket return
	 * conventions, return 0 to mean the cert is OK or 1 to fail it.
	 * This also means that if you don't handle this callback then
	 * the default callback action of returning 0 allows the client
	 * certificates. */
```

If there's a crash, it'll be your code that's crashing...

**Comment by arunkvnss** [comment]
True, my application is only crashing,  I tried to cast the pointer to x509 store context, an then using as said above ,and the giver user pointer is no a proper x509 store context

**Comment by arunkvnss** [comment]
Put break point in callback and casted the user to the x509 store context , itz not a proper pointer of this type

**Comment by lws-team** [comment]
The code is all there... you can see for yourself where it comes from.

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/openssl-server.c#n41

**Comment by arunkvnss** [comment]
Mine is libwesocket client code and I am verifying the server certificates

**Comment by lws-team** [comment]
If there's a bug in lws, let me know.

Let's reopen this if you can send the logs requested before the topic changed to something urelated...
