### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by ypiker** [warmcat/libwebsockets#1543]
Does the HTTP protocol support CORS?

**Comment by lws-team** [comment]
Lws supports all the headers necessary but it leaves it to the user code to check and issue `Access-Control-Allow-Origin` in the user callbacks.

If you want to help implement it in the default serving, patches are welcome.  Although the first part of that would be to figure out how and where to express the user's cross-origin policy... per-mount or per-vhost.

**Comment by ypiker** [comment]
Thank you for your answer. Besides, I want to know how to handle Ajax JSON requests and responses through libwebsocket. Is there demo?

**Comment by lws-team** [comment]
The various demos that exist live here.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples
