### ISSUE TITLE
Redirect response is correct but nothing happens

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#1544]
I have two vhosts in my application: myserver.com:8080 and myserver.com:8081. I can reach them with no problems using their hostnames (i.e., host + port). But I want the user to be redirected to myserver.com:8081 if he requests myserver.com:8080/redirect. For this purpose, I'm calling `lws_http_redirect` in the myserver.com:8080 `LWS_CALLBACK_HTTP`. The client (Firefox browser) says I'm getting a correct response:

```
HTTP/1.1 301 Redirect
location: myserver.com:8081
content-type: text/html
content-length: 0
```

However, nothing happens. It also does not matter if I return 0 or != 0 after calling `lws_http_redirect`. So I'm confused. As I said, if I request myserver.com:8081 it works, but the redirect does not.

**Comment by lws-team** [comment]
It sounds like there's no problem except you need to set `location:` to a full URI like `https://myserver.com:8081/`.  When you type `myserver.com:8081` in the browser url bar, it follows some heuristics to guess what the full URIs should be tried for that in which order, eg hsts ruling out http://, assumes you mean / etc.  But a redirect should be unambiguous about http:// or https://.

**Comment by nidoro** [comment]
That fixed it. Sorry that's not a libwebsockets issue, but a programmers issue haha. Thank you Andy!
