### ISSUE TITLE
lws_write modify source buffer???

### ISSUE THREAD

**Issue by jiamuluo** [warmcat/libwebsockets#1548]
i use lws_write send data,like this
```
lwsl_hexdump_notice(pstPosTmp->data, pstPosTmp->len);
   n = lws_write(wsi,pstPosTmp->data + LWS_SEND_BUFFER_PRE_PADDING,pstPosTmp->len,LWS_WRITE_BINARY);
            INFO("Now write payload data %d %p %s ",n,pstPosTmp->data,(char *)(pstPosTmp->data + LWS_SEND_BUFFER_PRE_PADDING));
            lwsl_hexdump_notice(pstPosTmp->data, pstPosTmp->len);
```
the twice hexhump will show different content??? becase pstPosTmp->data has been modified in lws_write?

**Comment by lws-team** [comment]
Yes... for specifically ws client sending something, RFC6455 requires it to be xor-masked.  To save on memory, lws does the xor mask in-place.  Other formats like h2 don't modify the data, so lws_write only modifies up to LWS_PRE bytes before the start of the payload.

**Comment by jiamuluo** [comment]
just only modifies up to LWS_PRE bytes before the start of the payload????but my problem is whole buffer has been modified.And,if i free the buffer after lws_write return, Is there going to be a problem?

**Comment by lws-team** [comment]
Please read what I wrote... RFC6455 websockets requires the payload is masked.  OTHER FORMATS like h2 don't modify the data...

So long as you allocated the right amount on the heap, there's no problem coming from writing into the allocated area in terms of freeing it... it doesn't care who did what in there so long as it stays inside the allocated region.
