### ISSUE TITLE
Upgrade HTTP Example

### ISSUE THREAD

**Issue by inQonsole** [warmcat/libwebsockets#1554]
We are working currently work on a community plugin for UE4 which has libwebsockets as a third party library, the websocket part is working perfectly but the server we connect to requires a HTTP upgrade to WS, i have searched around and the information is kinda hard to find.

as my understanding you have to add headers at **LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER** for the upgrade connection to work.

Are there any examples for http to ws upgrade ?

**Comment by lws-team** [comment]
> the websocket part is working perfectly but the server we connect to requires a HTTP upgrade to WS, i have searched around and the information is kinda hard to find.

... you're going to have to explain your problem a bit better.

All ws connections start out as http and upgrade to ws.  Lws handles all that for you.

Information on that isn't 'hard to find'...

https://tools.ietf.org/html/rfc6455

Aince you say, 'the websocket part is working perfectly'... what exactly is the problem you're trying to solve?

**Comment by inQonsole** [comment]
> All ws connections start out as http and upgrade to ws. Lws handles all that for you.
so we don't have to send (manual) upgrade headers.

We are writing a client for socketcluster which is written in node.js, there are 2 handshakes in the connection phase
1. HTTP Upgrade handshake
2. Websocket Handshake (this custom code from the server)

Websocket handshake works, but the HTTP Upgrade handshake never gets called, 
with the following code the HTTP Handshake get's called.

`static struct lws_protocols protocols[] = {
	{
		"http-only",
		USCSocket::http_service_callback,
		0,
	},
	{
		"default-protocol",
		USCSocket::ws_service_callback,
		0,
	},
	{
		NULL,
		NULL,
		0
	}
};`

Sorry for the confusion English is not my first language, i hope it's bit more clear.

**Comment by inQonsole** [comment]
> > the websocket part is working perfectly but the server we connect to requires a HTTP upgrade to WS, i have searched around and the information is kinda hard to find.
> 
> ... you're going to have to explain your problem a bit better.
> 
> All ws connections start out as http and upgrade to ws. Lws handles all that for you.
> 
> Information on that isn't 'hard to find'...
> 
> https://tools.ietf.org/html/rfc6455
> 
> Aince you say, 'the websocket part is working perfectly'... what exactly is the problem you're trying to solve?

Thank you for the link, i was able to fix my issue. it was my own mistake, the client was not selecting the right protocol, everything works!

My apologies!

**Comment by lws-team** [comment]
No worries, glad you're working.
