### ISSUE TITLE
Incomplete messages with permessage-deflate enabled

### ISSUE THREAD

**Issue by Yimgo** [warmcat/libwebsockets#1555]
Hi Andy,

We came across an issue with lws v3.1.0 and permessage-deflate enabled.

Since [this](https://github.com/warmcat/libwebsockets/commit/a1b642f4feb09a5e583616e9a686e484ced6f4ea) commit, messages differ between what is passed to lws_write() and what is received after inflate.

Here is what we have in the logs:
```
lws_extension_callback_pm_deflate: TX: ebuf length 102497
tx held 5
TX rewritten with new effbuff len 1019, ret 1
write drain len 1019 (wp 0x1) SETTING tx_draining_ext
_lws_change_pollfd: wsi 0x807929400: fd 10 events 1 -> 5
lws_extension_callback_pm_deflate: tx opcode 0x42
lws_issue_raw: ssl_capable_write (1027) says 1027
lws_issue_raw_ext_access: written 1027 bytes to client

....

SERVICING TX EXT DRAINING
rops_write_role_protocol_ws: CLEARING tx_draining_ext
FORCED draining wp to 0x02 (stashed 0x02, incoming 0x02)
TX rewritten with new effbuff len 1, ret 0
PMD_CLIENT_NO_CONTEXT_TAKEOVER
lws_extension_callback_pm_deflate: tx opcode 0x80
lws_issue_raw: ssl_capable_write (7) says 7
lws_issue_raw_ext_access: written 7 bytes to client
rops_handle_POLLOUT_ws: : wsi->ws->tx_draining_ext 0
```

From what I understand, there is still data to be flushed in the deflate buffer but `tx.avail_in` is 0 so we do not call deflate for the last time but send a 1-length buffer instead.

Is there a more reliable way to check if the call to deflate() is necessary such as deflatePending ?

Many thanks,
Guillaume

**Comment by lws-team** [comment]
Can you see if current master acts the same?

`deflatePending()` sounds like it should be useful but to save me threshing around is the a way I can reproduce this so I can confirm the problem?  I think this must be a corner case because both v3.10-stable and master pass autobahn.

If you take a peek at minimal-ws-server-pmd-corner, can you possibly hack this to match what provokes the problem, and send the hack patch?  I'll be happy to try it and fix it if I can casually reproduce it.

**Comment by Yimgo** [comment]
Well, I ran minimal-ws-server-pmd-corner:

```
$ ./bin/lws-minimal-ws-server-pmd-corner 
[2019/04/24 13:22:59:9019] USER: LWS minimal ws server + permessage-deflate Corner Cases | visit http://localhost:7681
[2019/04/24 13:23:04:0590] ERR: callback_minimal: writable 1, 1012
[2019/04/24 13:23:04:0737] ERR: callback_minimal: writable 2, 1013
[2019/04/24 13:23:04:0864] ERR: callback_minimal: writable 3, 1014
[2019/04/24 13:23:04:0991] ERR: callback_minimal: writable 4, 1019
[2019/04/24 13:23:04:1110] ERR: callback_minimal: writable 5, 1024
```

Here what I get with master, on the client:

```
0 blob uncompressed length 1012
1 blob uncompressed length 1013
3 blob uncompressed length 1019
2 blob uncompressed length 1014
4 blob uncompressed length 1019
```

Do you notice that bloc 4 does not length 1024 ?

If I revert the commit https://github.com/warmcat/libwebsockets/commit/a1b642f4feb09a5e583616e9a686e484ced6f4ea, I get this on the client, which is the expected output in my understanding;

```
0 blob uncompressed length 1012
1 blob uncompressed length 1013
2 blob uncompressed length 1014
3 blob uncompressed length 1019
4 blob uncompressed length 1024
```

**Comment by lws-team** [comment]
Yeah... that's exactly the kind of reproducer I'm talking about :-)

I pushed a patch on v3.1-stable using as you suggested deflatePending() as well... it fixed it here for the pmd-corner example, please give it a try.

**Comment by Yimgo** [comment]
It works like a charm, many thanks !

Be careful though because deflatePending is not available in the zlib shipped within win32port.

**Comment by lws-team** [comment]
I patched the win32 zlib with just that function... I can't build-test it due to now windows but I checked the ingredients it uses already exist in that tree.  I updated the patch on v3.1-stable accordingly.

I added this stuff on master too, but I am working on that atm and will push it later.
