### ISSUE TITLE
Get Error [read failed] when try to establish SSL Connection

### ISSUE THREAD

**Issue by tayenderkumar** [warmcat/libwebsockets#1556]
Hello,
I am trying to connect my libwebsocket client to a socket.io server.
When i connect without SSL, i.e. using http, then connection establishes, though it breaks after 60 seconds. But if i try to connect the same server using https, i get LWS_CALLBACK_CLIENT_CONNECTION_ERROR with message "read failed".
I was able to connect to same server from a libcurl client using below 3 options
	curl_easy_setopt(handleCurl, CURLOPT_SSL_VERIFYPEER, 0L);
	curl_easy_setopt(handleCurl, CURLOPT_SSL_VERIFYHOST, 2L);
	curl_easy_setopt(handleCurl, CURLOPT_CAINFO, "***_CA.pem");
Could you please help?

I set below two values in libwebsocket client.
	ctxCreationInfo.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	ctxCreationInfo.ssl_ca_filepath = "***_CA.pem";

**Comment by lws-team** [comment]
>  though it breaks after 60 seconds

okay... so what do the lws logs say?

> if i try to connect the same server using https, i get LWS_CALLBACK_CLIENT_CONNECTION_ERROR with message "read failed".

okay... so what do the lws logs say?

Build with `cmake .. -DCMAKE_BUILD_TYPE=DEBUG` and increase the logging bitfied (like -d in the examples) to 1159 or so and paste the related logs.

**Comment by tayenderkumar** [comment]
In case of http , client received LWS_CALLBACK_CLOSED after 60 seconds of receiving data(LWS_CALLBACK_CLIENT_RECEIVE).
Actually i am building the client for an embedded device, in a separate environment, and logs can't be printed there.
I will make one sample for linux and will share the logs.

**Comment by lws-team** [comment]
When you face this kind of situation, usually the logs either hold a clue or the answer.  So deciding you can't see them is definitely making this problem harder to solve than it should be.

Depending on how embeedded you're talking, you can think about redirect stderr to /tmp/mylogs or whatever (myapp 2> /tmp/mylogs) and then scp /tmp/mylogs back to your PC, or if you mean REALLY embedded, then notice that lws allows you to set your own log emit function

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-logs.h#n161-175

presumably you have a serial port at least... you can make your own emit function that blocks issuing the logs to the serial port before returning.

**Comment by tayenderkumar** [comment]
lws_log level[4] Initial logging level 255
lws_log level[4] Libwebsockets version: 2.1.0 zhangmy@prolin-srv-
lws_log level[4] IPV6 compiled in but disabled
lws_log level[4] libev support not compiled in
lws_log level[4] libuv support not compiled in
lws_log level[4]  Threads: 1 each 1024 fds
lws_log level[4]  mem: platform fd map:  4096 bytes
lws_log level[4]  Compiled with OpenSSL support
lws_log level[4] Creating Vhost 'default' port -1, 1 protocols, IPv6 off
callback_JoinRoom reason[21] in[no_in]]
lws_log level[4]  mem: per-conn:          376 bytes + protocol rx buf
lws_log level[4]  canonical_hostname = D190-1260477540
libwebsocketWSConnect Connecting...]
lws_log level[4] lws_protocol_init
callback_JoinRoom reason[27] in[no_in]]
callback_JoinRoom reason[29] in[no_in]]
libwebsocketWSConnect Connection Established]
callback_JoinRoom reason[24] in[Äì]]
callback_JoinRoom Connection ERROR[read failed]]

**Comment by lws-team** [comment]
> lws_log level[4] Libwebsockets version: 2.1.0 zhangmy@prolin-srv-

This is too old to support.... please try master or v3.1
