### ISSUE TITLE
Integration with libevent

### ISSUE THREAD

**Issue by mankann** [warmcat/libwebsockets#1557]
Hello,
I have intergrated libevent in libwebsockets without problem in earlier version 2.0.
Now that I have upgraded to version 3.1 I get problem with signal handling. First of all, ctrl+c does not work any more and also it seems like my internal logic is interrupted and only triggers when I press ctrl+c.

I have compiled libwebsockets with these configurations.
`cmake .. -DLWS_WITH_SSL=OFF -DLWS_WITHOUT_BUILTIN_SHA1=OFF -DLIB_SUFFIX=64 -DLWS_WITH_LIBEVENT=ON -DLWS_WITHOUT_TEST_SERVER=ON`

I used the following configuration in the older version.

   
```
        memset(&info, 0, sizeof info);
	info.port = m_websocket_port;

	info.protocols = protocols;
	info.extensions = exts;
	info.ws_ping_pong_interval = m_pingPongInterval;

	info.gid = -1;
	info.uid = -1;
	info.max_http_header_pool = 1;
	info.options = opts | LWS_SERVER_OPTION_LIBEVENT;


	info.ssl_cert_filepath = nullptr;
	info.ssl_private_key_filepath = nullptr;
	info.user = this;

	m_context = lws_create_context(&info);
	if (m_context == NULL) {
		lwsl_err("libwebsocket init failed\n");
		throw "libwebsocket init failed";
	}


	// Don't use the default Signal Event Watcher & Handler
	lws_event_sigint_cfg(m_context, 0, nullptr);
	// Initialize the LWS with libevent loop
	lws_event_initloop(m_context, m_base, 0);

	timeout_watcher = event_new(m_base, -1, EV_PERSIST, ev_timeout_cb, this);
	struct timeval tv = {0, 50000};
	evtimer_add(timeout_watcher, &tv);

```
It seems like I have to remove the following lines in the new version of libwebsockets.

```
lws_event_sigint_cfg(m_context, 0, nullptr);
lws_event_initloop(m_context, m_base, 0);
```

The lws_service is being triggered using a libevent timer event, however in the new version of libwebsockets it seems like the lws_service method never returns.

```
void WebSocket::initializeRunner() {
	timeval hb 	= {1, 0};

	m_timer 	= event_new(m_base, -1, EV_PERSIST, run, this);
	if (!m_timer || event_add(m_timer, &hb) != 0)
	{
		std::stringstream mess;
		mess << "Error occured when trying create SCADA timer event ";
		m_logger->WriteMessage("ALARM", mess.str());
		throw std::runtime_error("Could not create timer");
	}
}

void WebSocket::run(evutil_socket_t fd, short what, void* arg) {
	auto obj = static_cast<WebSocket*>(arg);
	std::cout << "run" << std::endl;
	if( lws_service( obj->m_context, /* timeout_ms = */ 1 ) < 0 ) {
		throw "Error polling for socket activity.";
	}
	std::cout << "run end" << std::endl;
}
```

When I first implemented the solution I had a look at the following example.
https://libwebsockets.org/git/libwebsockets/tree/test-apps/test-server-libevent.c?id=61376bd734b6cb9b7e749f5de7a986228a1e5013

What am I doing wrong in the new version?

**Comment by lws-team** [comment]
From v3.1 on the event loop stuff was "normalized" so you can have the same code regardless of the event loop you end up using.  See these minimal examples:

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-demos
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

... check the minimal example nearest what you need works as it is for you... if so, align your code to match that.

**Comment by mankann** [comment]
Thanks!
Just for reference how I solved this in case somebody else is attempting to use libwebsockets together with libevent and C++ classes.

```

void WebSocket::initializeRunner() {
	timeval hb 	= {1, 0};

	m_timer 	= event_new(m_base, -1, EV_PERSIST, run, this);
	if (!m_timer || event_add(m_timer, &hb) != 0)
	{
		throw std::runtime_error("Could not create timer");
	}
}


void WebSocket::run(evutil_socket_t fd, short what, void* arg) {
	auto obj = static_cast<WebSocket*>(arg);

	obj->signal_cb((int)(lws_intptr_t)arg);
}

void WebSocket::signal_cb(int signum) {
        switch (signum) {
        case SIGTERM:
        case SIGINT:
                break;
        default:
                break;
        }

        lws_context_destroy(m_context);
}
`
```
