### ISSUE TITLE
Unix Signals and Deadlocks

### ISSUE THREAD

**Issue by filcuc** [warmcat/libwebsockets#1564]
This is more a question rather than an issue. 
We're facing a deadlock in our application that could be due to some implementation details of this library. 
Basically we suspect that the deadlock is caused by the double locking of a mutex from the same thread. We suspect that this double locking is caused by: 
1) the main thread try to log and acquires a syslog mutex (something deep in the libc sources)
2) the main thread is put to sleep while reading a file regarding the locales for computing the timestamp for logging
3) the main thread is waken up for handling a unix signal
4) the main thread try to log again but still have the mutex locked from 1

The question is: does this library call user code from a unix signal? i didn't check out the lws sources deeply so i'm asking that.
We suspect that this could be caused by a custom function passed to  lws_set_log_level that could be called in the internals of the library during a unix signal callback.

Can you confirm if libwebsockets could call user code from a unix signal callback?

**Comment by lws-team** [comment]
Well, first valgrind can be helpful with this kind of thing.

Lws relationship to signals depends largely on the event library being used... if it's the default poll(), then AFAIK lws itself does not do anything at all with signals.  For the others, it may try to capture SIGINT.

I think your trial explanation isn't making much sense... lws doesn't know about glibc mutexes and it won't somehow find them itself and lock them.  If the glibc mutexes for syslog can deadlock like that, it's a bug in glibc AFAIK.

What I'd do is disable your custom log emit function and see what happens... all is well?

**Comment by filcuc** [comment]
No we didn't got each other. I'm not saying that the lws library acquires syslog mutexes: it's my app that acquires it for logging during a lws callback (suppose when a message i received). However i see that that thread could be reused (woken up) by a posix signal while still holding a lock in the libc.
Something very similar to this stack trace:
https://lists.01.org/pipermail/connman/2012-April/010007.html
I'm just asking to the library author if the library register to any unix signal and calls user from there (for example the function registered through   lws_set_log_level)

**Comment by filcuc** [comment]
for example i see this one
https://github.com/warmcat/libwebsockets/blob/3c1eb97537b41d615f52bc2965c54df661381a6b/lib/plat/unix/unix-init.c#L69

**Comment by lws-team** [comment]
If you want to know about the code, grep it... you'll get a correct answer.

If I'm avoiding SIGPIPE, how does that fit into your scenario?

What is the result of ditching your custom log emit function?

**Comment by lws-team** [comment]
... also why can't you attach gdb and find the exact backtrace of the deadlock?  If it's in a signal handler, it will be shown there exactly which one.

I used to use syslog api but recently, systemd is completely happy taking my stderr and applying it to the journal.  So you can maybe consider just offloading that to systemd if you have it.

**Comment by filcuc** [comment]
I was so easily reproducible i wouldn't opened this issue that said i'll for sure try to find a way to reproduce it by stressing the system. What it happened it was on a release version so i couldn't attach.
That said thanks for your kindness in your answer....i'm try to find the answer to my question on my own. 
Have a nice day

**Comment by lws-team** [comment]
You can get backtraces on release builds, but you have to manually interpret the addresses via the map file your linker emitted.

If you find a way to reproduce it using just the example pieces, I'll be happy to try it.  But at a guess it's something specific to your setup.
