### ISSUE TITLE
windows plat can't receive LWS_CALLBACK_EVENT_WAIT_CANCELLED

### ISSUE THREAD

**Issue by miaohongbiao** [warmcat/libwebsockets#1565]
hello,
it's maybe some error about window and linux plat, such as i use the lws_cancel_service, but i can't recieve LWS_CALLBACK_EVENT_WAIT_CANCELLED on windows plat, but i can receive at linux plat, however, when i user lws_cancel_service, i can receive LWS_CALLBACK_SERVER_WRITEABLE, but linux can't, event so that, i receive the LWS_CALLBACK_EVENT_WAIT_CANCELLED, but can't get any thing that define by myself, so i can't do any thing by the wsi.
version 3.1
how can i get user_space by callback when the reason is LWS_CALLBACK_EVENT_WAIT_CANCELLED

**Comment by borrrden** [comment]
Did you ever get a resolution for this?  I am facing a similar problem.
