### ISSUE TITLE
Getting start with esp8266

### ISSUE THREAD

**Issue by Rjayone** [warmcat/libwebsockets#1566]
Hi everyone, i would to start using libwebsockets on my esp8266, but i really don't understand how to use it, what the components do i need to use ws-client?
I have built the main project, the headers files is located in /usr/local/include.
When i try to build my esp8266 firmware with included <libwebsockets.h> i faced with error: 
`/usr/local/include/libwebsockets.h:116:18: fatal error: poll.h: No such file or directory
 #include <poll.h>`
My make file provides the headers search path via ` CFLAGS += -I /usr/local/include`
MacOS Mojave 10.14.4

**Comment by lws-team** [comment]
I removed support for esp8266... the smallest supported thing now is ESP32.

esp8266 can't really handle even mbedtls... in 2019 if it can't do tls then there's not much point.

**Comment by Rjayone** [comment]
Can i find the oldest releases where esp8266 was supported?

**Comment by lws-team** [comment]
The last tree with it in was 31606054620155f5e2e9bb8cae2aa3080c6199e1

You can use `git reset --hard 31606054620155f5e2e9bb8cae2aa3080c6199e1` to pin it there.

You can see what was removed here:

https://github.com/warmcat/libwebsockets/commit/8487279e642370b090b12fe6acba8308580c4f79

But tbh trying to use something that's been removed is unlikely to give a happy result.  I'm not going to spend any time supporting it.
