### ISSUE TITLE
lws_ssl_client_bio_create: Unable to get hostname

### ISSUE THREAD

**Issue by mikeowens** [warmcat/libwebsockets#1567]
I am getting this error when trying to use valid certs from letsencrypt. The server indicates no problem loading them, yet the client side is having this issues only with SSL (problem does not appear unencrypted). It appears that lws_ssl_client_bio_create() in openssl-client.c when calling lws_hdr_copy() is not getting the hostname header -- there is no hostname header being returned. I am using explicity VHOST as follows:

```
        info.port             = 7681;
        info.protocols        = protocols;
        info.extensions       = extensions;    
        info.pt_serv_buf_size = 128 * 1024;
        
        info.options = LWS_SERVER_OPTION_VALIDATE_UTF8      |
                       LWS_SERVER_OPTION_EXPLICIT_VHOSTS    |
                       LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT |
                       LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;

        lws_context* c = lws_create_context(&info);
                        
        info.vhost_name               = "test.vrtql.com";
        info.ssl_ca_filepath          = "ssl/chain.pem";
        info.ssl_cert_filepath        = "ssl/server.cert";
        info.ssl_private_key_filepath = "ssl/server.key";
        lws_create_vhost(c, &info);
```

**Comment by lws-team** [comment]
When you created the client connection, did you fill in info.host?  It needs to be the cert CN address, like "warmcat.com" or "warmcat.com:443".

**Comment by mikeowens** [comment]
Forget it. This was my fault.

**Comment by mikeowens** [comment]
I just saw your comment after I posted and closed. That was exactly what happened. I was using a C++ stringstream which decided to do something weird and the hostname ended up being passed in as NULL. Sorry about this.
