### ISSUE TITLE
libwebsockets with CentOS 5

### ISSUE THREAD

**Issue by kayechica** [warmcat/libwebsockets#1568]
Is it possible to install and use libwebsockets with CentOS 5?
I have encountered build problems even with "include <sys/capability.h>".
I have read that libcap-dev should be installed but I cannot install it in CentOS 5 also.

**Comment by lws-team** [comment]
It should work on Centos 5. On that, the dev package would be 'libcap-devel'.  But it's only built if libcap pieces were found by cmake.

So it might be worth pasting the compile errors.

**Comment by kayechica** [comment]
Thank you for the immediate response. I have referred 2 sites for possible libcap package download but it only has CentOS 6 and 7.
https://pkgs.org/download/libpcap-devel

https://rpmfind.net/linux/rpm2html/search.php?query=libcap-devel

Thanks. 
 
 
  On Thu, May 9, 2019 at 7:51 PM, Andy Green<notifications@github.com> wrote:   
It should work on Centos 5. On that, the dev package would be 'libcap-devel'. But it's only built if libcap pieces were found by cmake.

So it might be worth pasting the compile errors.

**Comment by lws-team** [comment]
You should just be able to install it via yum from the default repos... `yum install libcap-devel`... you shouldn't need any third party sites.

**Comment by kayechica** [comment]
Oh I see... I'll try that.Thanks a lot. 
 
 
  On Thu, May 9, 2019 at 8:25 PM, Andy Green<notifications@github.com> wrote:   
You should just be able to install it via yum from the default repos... yum install libcap-devel... you shouldn't need any third party sites.
