### ISSUE TITLE
API provides no information about connection errors

### ISSUE THREAD

**Issue by snej** [warmcat/libwebsockets#1570]
The LWS API doesn't seem to provide any information about the specifics of connection errors. If my callback gets `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`, the only information provided is an English-language string that's of no use to my code. This is a big problem because I'm integrating LWS into a program that expects to know exactly why a connection failed, so it can take appropriate action, such as:

* If it gets an auth error (HTTP 401) it can prompt the user for credentials then retry.
* Some errors tend to be transitory, like timeouts or connection-refused; in that case we should pause and retry a couple of times. Others are more permanent.
* Providing a reasonably detailed description of the error to the user. It's bad UX to give a vague alert like "There was a network error". [OK, you do provide a string. But that doesn't help if the user doesn't speak English, and the text is pretty terse and not something I'd want to show an end user.]
* It's vital to log all errors for troubleshooting purposes. There's no way we can help customers with mysterious problems unless we can see a record of exactly what went wrong. (And these logs need to go through our API, not something libwebsockets writes.)

Frustratingly, LWS does log the details of the error, such as the errno code or HTTP status. But it doesn't look like there's any way to get that info programmatically without doing some nontrivial work on the code to preserve that info and put it somewhere that the client code can access.

**Comment by lws-team** [comment]
Patches welcome.

Http status is available programatically.

From the sound of it numeric codes with a severity encoded in the ms part and an ordinal in the ls part would suit it better.  For people who want the strings the middle could encode a string index or 0 if not available.

**Comment by snej** [comment]
How should this be implemented to avoid ABI incompatibility? Maybe a new code in `lws_callback_reasons`, like `LWS_CALLBACK_CLIENT_CONNECTION_ERROR_CODE`, then invoke the callback with that code before the regular `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`?

**Comment by lws-team** [comment]
Yeah... I can think of another couple of ways but there's not really anything to tell them apart advantagewise.

If we follow your suggestion, we can document the old way is deprecated for a couple of versions and then remove the callback ordinal for the old way.

**Comment by lws-team** [comment]
If patches are coming, they're still welcome.

**Comment by snej** [comment]
I've been on vacation for a few weeks. I've gotten legal approval from Couchbase to use LWS despite the letters G-P-L in the license, so I expect this change will happen at some point, depending on product schedules.

Until then I suggest you leave this issue open, since it is still a limitation of the software.

**Comment by lws-team** [comment]
Super.
