### ISSUE TITLE
Problem with HTTP2 without SSL.

### ISSUE THREAD

**Issue by ntllct** [warmcat/libwebsockets#1571]
I have a problem with connection via HTTP2 without SSL.

I try to start a test server:

./libwebsockets-test-server --port=7681

... and connect to it by curl:

curl --http2 http://localhost:7681/ -v -w "\n"

There is no response. One CPU core is 100%, but the server continues to serve HTTP1/1 queries.

The result is:

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7681 (#0)
> GET / HTTP/1.1
> Host: localhost:7681
> User-Agent: curl/7.64.1-DEV
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
> 
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
^C
```

But when I try with SSL:

./libwebsockets-test-server --port=7681 --ssl

... and:

curl --http2 --insecure https://localhost:7681/ -v -w "\n"

... everything is OK!

**Comment by lws-team** [comment]
H2 without tls isn't really supported... it relies on the ALPN negotiation to select h2.

It shouldn't spin though... what cmake options are you using?

**Comment by ntllct** [comment]
>> what cmake options are you using?

cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DLIB_SUFFIX=64 -DLWS_WITH_HTTP2=1 -DCMAKE_EXE_LINKER_FLAGS="-ldl" -DLWS_WITH_LIBEV=1 -DLWS_WITH_LIBUV=1 -DLWS_WITH_CGI=1 -DLWS_WITH_ZLIB=1 -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_WITH_PEER_LIMITS=ON -DLWS_WITH_ZIP_FOPS=ON -DLWS_WITH_GENCRYPTO=1 -DLWS_WITH_JOSE=1 -DLWS_ROLE_RAW_PROXY=1 -DLWS_WITH_PLUGINS=1 -DLWS_WITH_THREADPOOL=1 -DLWS_WITH_FTS=1 -DLWS_WITH_LWSAC=1 -DLWS_WITH_HTTP_STREAM_COMPRESSION=1 -DLWS_WITH_DISKCACHE=1 -DLWS_WITH_HTTP_PROXY=1 -DLWS_WITH_SMTP=ON -DLWS_WITH_SOCKS5=ON -DLWS_UNIX_SOCK=1 ..

**Comment by ntllct** [comment]
I also tried:

```
cmake -DLWS_WITH_HTTP2=1 -DLWS_WITH_LIBEV=1 ..
make
sudo make install
```

but one core has 100% load (libwebsockets-test-server process).

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```
`Linux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ntllct** [comment]
I just tried to run the server on Raspberry Pi 3 B+ and got the same result:
![lws_report](https://user-images.githubusercontent.com/28967080/57570838-368c3300-740f-11e9-8675-55e6df86a9d2.png)

**Comment by lws-team** [comment]
Yes it's nothing to do with the platform... since nobody actually uses h2 upgrade from inside h1, including me, although I implemented it it has rotted against improvements in the tls path.

I have fixed with with a patch that updates it to use the same steps as the tls h2 path and confirmed I can use curl with your switches without tls.  But unfortunately I am not going to be able to push it for a day or two.

**Comment by ntllct** [comment]
I was just afraid that someone could disrupt the normal operation of the server with such a request.

**Comment by lws-team** [comment]
Yes it's definitely good to fix it, thanks for the report.  I'll update here when it's pushed.

**Comment by lws-team** [comment]
It's pushed on master now.
