### ISSUE TITLE
libwebsocket 3.1 version

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1572]
Hi is it possible to load my vertificates (client CERT,client Private Key, CA to verify the server) in p12 format ?

I am using libwebsocket client with 3.1. version

**Comment by lws-team** [comment]
Lws doesn't try to deal with PKCS12... it wants the X509 pieces individually either in DER (raw ASN.1) or PEM (BASE64-encoded DER).

PKCS12 is a microsoft invention that lets you bundle the pieces

https://en.wikipedia.org/wiki/PKCS_12

however you can just concatenate PEM pieces to the same effect.

Both OpenSSL and mbedTLS have apis for dealing with p12 so I guess there's a case for wrapping it at lws.

Patches welcome...

**Comment by arunkvnss** [comment]
"ssl_private_key_password " what does this mean ! ?

**Comment by lws-team** [comment]
```
        const char *ssl_private_key_password;
        /**< VHOST: NULL or the passphrase needed for the private key. (For
         * backwards compatibility, this can also be used to pass the client
         * cert passphrase when setting up a vhost client SSL context, but it is
         * preferred to use .client_ssl_private_key_password for that.) */
```

If your cert private key is protected by a passphrase, you can point to it here.

**Comment by arunkvnss** [comment]
K then, i will go with as u said before, thanks
