### ISSUE TITLE
'make' errors using old gcc 4.1.2

### ISSUE THREAD

**Issue by kayechica** [warmcat/libwebsockets#1575]
Hello.

My cmake output was posted here
https://github.com/warmcat/libwebsockets/issues/1574
Thankfully it was clarified that the Not Founds were not an issue.

I proceed with 'make' and it gives errors such as:
---------------------------------------------------
```
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
cc1: error: unrecognized command line option "-Wignored-qualifiers"
cc1: error: unrecognized command line option "-Wtype-limits"
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
```
---------------------------------------------------

I guessed these options are not compatible with my gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-48) so I removed the options and it gave another set of errors:
---------------------------------------------------
```
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
In file included from /<path>/libwebsockets/include/libwebsockets.h:545,
                 from /<path>/libwebsockets/lib/core/private.h:129,
                 from /<path>/libwebsockets/lib/core/alloc.c:1:
/<path>/libwebsockets/include/libwebsockets/lws-genrsa.h:49: error: expected specifier-qualifier-list before ‘EVP_PKEY_CTX’

In file included from /<path>/libwebsockets/include/libwebsockets.h:547,
                 from /<path>/libwebsockets/lib/core/private.h:129,
                 from /<path>/libwebsockets/lib/core/alloc.c:1:
/<path>/libwebsockets/include/libwebsockets/lws-genec.h:38: error: expected specifier-qualifier-list before ‘EVP_PKEY_CTX’

make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1

make[1]: *** [CMakeFiles/websockets.dir/all] Error 2

make: *** [all] Error 2
```
---------------------------------------------------

Is there a way to solve these errors?
Is this because I removed some of the options I mentioned earlier?
I'd like to know if I still have options.
Any recommendations and thoughts will be of great help.

Thanks.

**Comment by lws-team** [comment]
Well there are a few things mixed together here.

First, CentOS 5 itself is out of security update coverage

http://mirror.centos.org/centos/5/readme

...so generally, you shouldn't be trying to use something that's already rotting...   But the other points still need looking at anyway on their own merits I think.

Second, we make assumptions about gcc flags we can use that aren't true for your older gcc.  Actually that should be fixed, it's not crazy in itself to want to use gcc 4.1 in 2019 for some reason.

I pushed a patch on master and v3.1-stable to do that.

The rest of it... I'm telling you what CentOS 5 has already been pushing your face into (ie, tls v1.x not supported in its openssl, cmake is too old to actually work with lws, repo mirrors all archived, not git in stock repos (!)), CentOS 5 is now unusable ancient software I'm not going to waste time on.  File it next to your commodore 64 and install something you can use securely.
