### ISSUE TITLE
Enumerating, or copying, all HTTP headers

### ISSUE THREAD

**Issue by snej** [warmcat/libwebsockets#1576]
There seems to be no way to enumerate the received _nonstandard_ (custom) HTTP headers & values. I can get the value of a custom header, but only if I know its name ahead of time. 

It also doesn't seem possible to copy the entire state of the headers and access them later.

Why this matters: The program I'm integrating libwebsockets into expects to be able to examine response header values later on, after the `LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH` or `LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP` callback have returned. Since LWS doesn't preserve the headers, I need to copy them. I've written code to enumerate all the header tokens and copy them into a map, but that only lets me save standard headers, and I may need to save nonstandard ones too.

**Comment by lws-team** [comment]
Lws took the approach it can trade off saving a lot of space vs lookup speed dealing with headers with a stream parser that only stores values for headers that might be consumed by user code into a fixed size lookup table in the ah.  That has the advantages of finding a sweet spot between memory usage, lookup speed and atomic fixed size ah allocation / re-use.  For h2 where the browser typically wants to create a dozen concurrently on busy pages, the savings from this approach adds up.

It wasn't designed to handle custom headers, and support for those is new on master and only then for h1.

However AFAIK for http transactions, the ah that holds these parsed header isn't dropped until stream close... that's so for http serving I think.  If you can identify where the ah is detached, it sounds like defeating that and delaying it until stream close where it'll be detached anyway might get you over the hump.
