### ISSUE TITLE
not found "lws_client_connect_via_info"

### ISSUE THREAD

**Issue by crud-boy** [warmcat/libwebsockets#1580]
Using the latest version of windows compiled by ci.appveyor.com, it was prompted that lws_client_connect_via_info could not be found. I checked it with the PE tool, and there was no such function.

**Comment by lws-team** [comment]
Make sure you didn't download the without client build...

Also those builds are old now, we filled up bintray's free offering and they don't provide tools to mass clean out old stuff.
