### ISSUE TITLE
minimal-ws-server-pmd-bulk example not working with wss

### ISSUE THREAD

**Issue by MarkusWeinand** [warmcat/libwebsockets#1581]
Hello,
Iam getting a SIG PIPE when trying to run the minimal-ws-server-pmd-bulk example with wss.
I added these Lines
```
info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
info.ssl_cert_filepath = "localhost-100y.cert";
info.ssl_private_key_filepath` = "localhost-100y.key";
```
Iam not sure if that is enough to setup wss.

**Comment by lws-team** [comment]
Sigpipe is a bit ambiguous... it means that the other side hung up on you basically.

The localhost certs are not recognized as legitimate by browsers without you telling the browser you trust that cert.  So you need to look at the other peer, browser, or curl or whatever and see if that wants to give you a clue as to why it hung up.

**Comment by MarkusWeinand** [comment]
Thats the only thing i get from Chrome
192.168.25.31/:4 GET https://192.168.25.31/example.js net::ERR_SPDY_FRAME_SIZE_ERROR 200
192.168.25.31/:7 GET https://192.168.25.31/libwebsockets.org-logo.svg net::ERR_SPDY_FRAME_SIZE_ERROR 200
/favicon.ico:1 GET https://192.168.25.31/favicon.ico net::ERR_TIMED_OUT
