### ISSUE TITLE
"time discontiguity" of 1000s on macOS

### ISSUE THREAD

**Issue by snej** [warmcat/libwebsockets#1582]
I have a repeatable failure in one of my unit tests, where I call `lws_vhost_destroy` but the vhost never gets closed nor do I get a `LWS_CALLBACK_PROTOCOL_DESTROY` event. My code is waiting for that event before continuing, so it gets stuck. (It's not running on the same thread that services LWS.)

The last time I ran this test I left it in the stuck state, and 16 minutes later it suddenly started up again and ran to completion!

The log shows a message warning of a "time discontiguity" of 1000 seconds, which is exactly the amount of time the process was stuck! Since the comments in the code say that a vhost is closed by a check that runs every second, it definitely seems like whatever timer LWS is using didn't get called for 1000 seconds.

Here's the log, with a blank line inserted to highlight the discontinuity:

```
13:23:36.459800| [WS] ***: LWSContext: Stopping LWSServer 0x6120000214c0 ...
13:23:36.459869| [WS]: libwebsocket: lws_vhost_destroy1
13:23:36.459925| [WS]: LWSContext: Stopped LWSServer 0x6120000214c0

13:40:16.428499| [WS]: libwebsocket: time discontiguity: at old time 1558470216s, new time 1558471216s: +1000s
13:40:16.428657| [WS]: libwebsocket: __lws_close_free_wsi: 0x615000010200: caller: vh destroy
13:40:16.428784| [WS] ***: LWSServer: **** LWS_CALLBACK_WSI_DESTROY
13:40:16.428826| [WS]: libwebsocket: lws_vhost_unbind_wsi: vh HTTPServer: count_bound_wsi 0
13:40:16.428884| [WS] ***: LWSServer: **** LWS_CALLBACK_PROTOCOL_DESTROY
```

**Comment by snej** [comment]
The 1000 second delay is because my LWS service thread does this:
```c++
            while (true) {
                lws_service(_context, 999999);
            }
```
I just picked a large number because I don't care how long the function waits. So it appears there's a bug in LWS wherein it waits for this entire timeout even though there's work that needs to be done, cleaning up after a closed vhost.

For now I can work around this by lowering the timeout to 1000ms, but I'd rather not keep that in the long term because it's bad for energy efficiency to keep waking up the process that often.

**Comment by lws-team** [comment]
If you don't go around the event loop, no events can happen, no timeouts can be seen, no socket traffic can be serviced... your service thread isn't servicing.

Lws seems to be doing exactly what it should do under these conditions.

**Comment by snej** [comment]
I think you're misunderstanding the situation. I _am_ running the event loop, as shown above; I'm just telling LWS that it's allowed to run as long as it wants up to 1000 seconds (since there's nothing else happening on that thread.) While inside `lws_service`, LWS should be able to handle whatever needs doing. 

For instance, when data arrives on a socket, LWS wakes up and processes it immediately. When I tell LWS I have data to send, it wakes up immediately and sends it. The behavior I'm reporting here is an exception, where something occurs that needs handling but LWS does not wake up in a timely manner.

The flow of control looks like this:
* My program wants to shut down an HTTP server.
* On another thread, I call `lws_cancel_service` to trigger an event on the LWS thread.
* The LWS thread (the one inside `lws_service`) dispatches a `LWS_CALLBACK_EVENT_WAIT_CANCELLED` event to my callback.
* My callback calls `lws_vhost_destroy`.
* The internal logic of `lws_vhost_destroy` apparently has to wait for some periodic call that realizes the vhost is closed and finishes the cleanup.
* That periodic call doesn't happen until the _next_ time `lws_service` is called ... which is the bug. Meanwhile, the current call of `lws_service` proceeds to call `poll` with a timeout of 1000 seconds, meaning that the vhost cleanup doesn't happen for 16 minutes.

**Comment by snej** [comment]
Note that my workaround of lowering the `lws_service` timeout to 1000ms would be a complete nonstarter were I developing for, say, a battery-powered ESP32 device. Bringing the CPU up to full-power mode every second would be terrible for battery life. We're actually coding for mobile phones (primarily), so this isn't quite so bad, but unnecessary polling loops are still frowned upon.

**Comment by lws-team** [comment]
You're required to reenter the service at 1Hz so timeouts and some other processing unrelated to network traffic can occur.  Other event loops set up a 1Hz timer for the same reason.

If you think it should be different... send patches.

**Comment by snej** [comment]
I'm not doing anything _except_ entering the service. When `lws_service` returns, I call it again a few nanoseconds later. I have a thread dedicated to this, whose entire code [I showed above](https://github.com/warmcat/libwebsockets/issues/1582#issuecomment-494598605). I don't see how I could be reentering the service any more rapidly than that.

**Comment by lws-team** [comment]
FYI on current master, there's now a unified sorted linked-list for all timed events in lws, the head of which is checked to reduce the poll wait / set up an event lib timer to match.

There's no longer any 1Hz background checking at all; stuff that wants periodic checking sets up its own lws_sul private timed callback.  The timeout_ms api stuff is kept for backwards compatibility but is ignored in favour of 22 day fixed default timeouts (reduced according to the earliest scheduled timed event if any).

**Comment by snej** [comment]
Thanks! I've been lazy about pulling from upstream, but I'll try to get to it soon and try this out.
