### ISSUE TITLE
HS: UPGRADE missing problem

### ISSUE THREAD

**Issue by aldam70** [warmcat/libwebsockets#1585]
Hi lws-team,

i'm using lws with version 3.1.0, and when i try to connect our server, always get below error message:

[2019/05/24 00:21:22:4306] NOTICE: callback_minimal_broker: LWS_CALLBACK_USER
[2019/05/24 00:21:23:1450] ERR: CLIENT_CONNECTION_ERROR: HS: UPGRADE missing

**Comment by lws-team** [comment]
So what headers are being sent by your server?

You should be able to see from lws side if you use -d1151 or equivalent log verbosity and build lws for debug, ie cmake .. -DCMAKE_BUILD_TYPE=DEBUG

**Comment by aldam70** [comment]
Hi lws-team,

Thank you very much for your quickly reply!  i'm wondering why we need to add string "close, " in the connection field, and it seems will terminate the connection and causes the "Upgrade missing" problem, after i change it as below, the connection established......
please correct me if i'm in a wrong way to use lws.
![image](https://user-images.githubusercontent.com/13232651/58307484-5bca6980-7e31-11e9-909b-3b499f09dfed.png)

**Comment by lws-team** [comment]
"close" is a valid token to have in the `connection:` header.  Your ws server should be able to handle it.

If you don't want to issue it, you can also add the flag `LCCSCF_PIPELINE` to the client info struct `.ssl_connection` member to get the same effect.

**Comment by aldam70** [comment]
Hi Andy Green,

Thank you very much for your help, it works, now i don't need to change the source code. 

BR
Adam
