### ISSUE TITLE
libwebsockets without callbacks

### ISSUE THREAD

**Issue by Nathan1852** [warmcat/libwebsockets#1587]
Is there any way I can handle the events lws generates myself, without having to wait for callbacks?
I'm trying to use libwebsockets with luajits ffi, and callbacks via lua, while possible, are slower than calling the handling c methods myself.
So my question is if there is any way to use libwebsockets as a pull-style api, instead of a push-style?

**Comment by lws-team** [comment]
The underlying reality of lws is 'non-blocking sockets'.  The choices about the architecture reflect that.

"callback on writable" == do the WRITEABLE callback when POLLOUT is signalled from poll().  RX callback is happening with POLLIN signalled and we read something.

Whatever you think a "pull-style api" would look like, it must also follow those two events.  There's no more efficient way to do it than inform the handler of the events... other types of approach assume infinite amounts of buffer memory.

You can write an adaptation layer in C between lws callbacks and your "pull style api"...  you're basically fighting lua ffi inefficiency not lws.
