### ISSUE TITLE
Example about multiple http requests?

### ISSUE THREAD

**Issue by lxlenovostar** [warmcat/libwebsockets#1588]
I want to use libwebsockets, I will build multiple http requests, for example HTTP A and HTTP B.
I build HTTP A first,  if HTTP A return 200, I build HTTP B. Or I build HTTP A after a timeout. 
Which example about this demand?

btw:  There is no relationship between HTTP requests  in `minimal_http_client_multi.c `

**Comment by lws-team** [comment]
The client-multi example pretty much shows everything.  There are too many variations to expect exactly what you want to always be the subject of its own minimal example.

You can start a new client connection wsi from inside an lws callback of another one, eg from CONNECTION_ERROR or HTTP callback of another one... it creates a fresh wsi that will have its own life on the event loop.  Depending on the host: port you ask to connect to and option flags, you can vontrol if it tries to bind to an already-existing connection using http/2 or h1 pipelining, or connects using its own independent connection.

**Comment by lxlenovostar** [comment]
```
 struct  agent {
      struct lws_context_creation_info info;                                         
      struct lws_context *context;
  
      //HTTP A                                                                          
      struct lws_client_connect_info client_A;
      struct lws *client_A_wsi;                                                            
          
      //HTTP B 
      struct lws_client_connect_info client_B;                                        
      struct lws *client_B_wsi;                                                       

      int bad;                                                                           
      int status;
  }; 

  const struct lws_protocols protocols[] = {
      {
          "http",
          callback_http_A,
          0,
          0,
      },
      {
          "http",
          callback_http_B,
          0,
          0,
      },
      { NULL, NULL, 0, 0 }
  };

```
I let HTTP A and HTTP B share` struct lws_context_creation_info and struct lws_context`,  It can't work. What am I getting wrong? Is there a document explaining the relationship of these data structures?  Thank you @lws-team

**Comment by lws-team** [comment]
"can't work", "doesn't work", "nothing happens", "fails", "hangs"... none of them give the right amount of information to move your problem on.

What do the logs say?  What do you observe?  Backtraces? Valgrind?
