### ISSUE TITLE
how to call a different protocol from client?

### ISSUE THREAD

**Issue by Suicosmos** [warmcat/libwebsockets#1598]
Hello, libwebsockets is my first attempt at learning how websockets work, i've studied the basic concepts and have been playing around with the minimal websocket examples. What would be the optimal way to call different protocols? Say I have the below for example, the client starts and automatically calls protocol[0] but how should i go about calling [1] or [2]?

example below:

static struct lws_protocols protocols[] = {
        {
                "connect_client",
                callback_connect_client,
                0,
                EXAMPLE_RX_BUFFER_BYTES,
        },
        {
                "json_update",
                callback_json_update,
                0,
                EXAMPLE_RX_BUFFER_BYTES,
        },
        {
                "receive_string",
                callback_receive_string,
                0,
                EXAMPLE_RX_BUFFER_BYTES,
        },
        { NULL, NULL, 0, 0 }
};

the lws_client_connect_info ccinfo has the first protocol listed as ccinfo.path = "connect_client"; so it gets calls it, but how would optimally or usually call the other two?

**Comment by lws-team** [comment]
I'm not quite sure what you're asking... you want to make another client connection using a different protocol?  If both sides use a different ws subprotocol name for that, you can just set info.protocol to that name when making the client connection.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n70

If it's that the other side uses the same protocol name but you want to bind it to a different one locally in specific cases, look at info.local_protocol_name

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n108-114

**Comment by Suicosmos** [comment]
I likely am confused I apologize, I'm having a hard time grasping some of the concepts of this library. I'll try to reword my statement so you can point me in the right direction :).

How do you call/use different callbacks from the client side? if that question does not make sense I apologize and i'll go look in the examples some more till i have a greater grasp of how things work.

**Comment by lws-team** [comment]
Yes you should look at the related examples.  You don't call the callbacks yourself... they are called when "something happens".  For example, in ws case, data was received.  Or you asked to be told when you could write something on that connection, and lws learned that was possible now.

**Comment by Suicosmos** [comment]
I understand. The minimal examples I've looked at so far only usually already perform something such as echo, the broker example and so forth. I guess I am looking for a way to, for example: write something on that connection when i want to use something so for example in a client gui a person clicks the connect button, I would use "lws_write" to write something and that would trigger the callback_connect_client example i gave in my first post?

**Comment by lws-team** [comment]
The examples pretty much all show how to use lws_callback_on_writable() and that you cannot randomly write things with lws but wait for the callback that says you way write something.

**Comment by Suicosmos** [comment]
thank you for helping. :D
