### ISSUE TITLE
lws_context_creation_info::client_ssl_private_key_password Doesn't Work

### ISSUE THREAD

**Issue by dleeds-cpi** [warmcat/libwebsockets#1599]
The struct member _client_ssl_private_key_password_ is never referenced. Applications may work around this bug by setting _ssl_private_key_password_, but the library should be checking the _client_ssl_private_key_password_ if it is in client mode.

Historical ticket #152 originally added support for private key passwords.

**Comment by lws-team** [comment]
Thanks, you're right.  I pushed patches on both v3.1-stable and master to fix the code to match the intended situation from the comments in the info struct.
