### ISSUE TITLE
Custom Domain Name fails - SSL error: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by vbbartlett** [warmcat/libwebsockets#1601]
I have been given(by our sysops) two endpoints on an AWS server, the basic endpoint and a custom domain name endpoint, along with AWS starfield cert file. Using that cert file, the basic endpoint works when creating a wss connection, however the custom  domain name doesn't work and I get the "unable to get local issuer certificate" as the error.  

For sanity I have added in the functionality to ignore the results in LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION callback as described in the header.  Ignoring the state of the cert verification works and the wss is created and the end point delivers the expected content.  

The other draw back i have is the code is running on an embedded system (we cross-compiled lws for it and it is working - other than this case).  So I don't have a lot of tools I normally would have on a normal machine.

Is there any basics that I am missing? Is this a bug or expected behavior or something else that is missing in my code? SSL is a black box to me... 

Thanks.

**Comment by lws-team** [comment]
Well... it seems that ignoring AWS this and that, if I understood you're making a client connection from the embedded side, and one server is OK and the other blows ssl cert complaints.

If so then you may be missing an intermediate cert needed by the "bad" server... or some similar problem like it's giving you certs belonging to a cdn or something.  I would stick this on the "bad" server and look closely at what it has to say compared to what trusted certs you have on the embedded box.

https://www.ssllabs.com/ssltest/

**Comment by vbbartlett** [comment]
Im not sure where the problem is, but I think the sysops have narrowed it down to some sort of cached cert that is hanging around.  The good server only has one the bad has two certs and one has an error on the ssltest. 
Thanks.
