### ISSUE TITLE
Arbitrary CGI scripts

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#1602]
Hi,

I am trying to configure my web server to run arbitrary cgi-scripts on an embedded device (where arbitrary is limited to only scripts found in my cgi-bin directory). I can not compile libuv due to porting issues, and therefore can't use lwsws. I am instead adding support manually, and not finding much in the way of documentation describing how to do this.

I have configured with ```-DLWS_WITH_CGI=1```, and am now trying to create the appropriate mount point.  What I **_want_** to do is tell LWS where my cgi scripts live, and leave it up to the web page to specify which script to run.  E.g. :

```
static const struct lws_http_mount cgi = {
    /* .mount_next */       &data,      /* linked-list "next" */
    /* .mountpoint */       "/cgi-bin",     /* mountpoint URL */
    /* .origin */           "/fs/emmc/web/cgi-bin", /* scripts dir */
    /* .def */          NULL,
    /* .protocol */         NULL,
    /* .cgienv */           NULL,
    /* .extra_mimetypes */      NULL,
    /* .interpret */        NULL,
    /* .cgi_timeout */      0,
    /* .cache_max_age */        0,
    /* .auth_mask */        0,
    /* .cache_reusable */       0,
    /* .cache_revalidate */     0,
    /* .cache_intermediaries */ 0,
    /* .origin_protocol */      LWSMPRO_CGI, 
    /* .mountpoint_len */       8,      /* char count */
    /* .basic_auth_login_file */    NULL,
};
```
Where the 'origin' field would be interpreted as a directory, and the script accessed using something like ```https://localhost/cgi-bin/test.cgi```

However, based on what I think that I'm seeing in ```lws_http_action()```, LWS only sets ```cmd[0] = hit->origin```, and ```lws_cgi()``` doesn't appear to pass the script any arguments. In other words, it appears that LWS wants a mount for **_each script_** - meaning (if I am understanding this correctly) that I instead need ;

```
static const struct lws_http_mount cgi = {
    /* .mount_next */       &data,      /* linked-list "next" */
    /* .mountpoint */       "/cgi-bin",     /* mountpoint URL */
    /* .origin */           "/fs/emmc/web/cgi-bin/test.cgi", /* handler  */
    /* .def */          NULL,
...
    /* .origin_protocol */      LWSMPRO_CGI, 
    /* .mountpoint_len */       8,      /* char count */
    /* .basic_auth_login_file */    NULL,
};
```

My first question is, "Is this correct? Or, have I misunderstood how LWS processes CGI scripts?"  If so, I can certainly dynamically build a list of mounts using ```scandir()``` (et al) but I don't think I'm reading this right.

Next, the server fails to run the CGI with the message 
```[2019/06/11 12:40:51:0029] NOTICE: CGI timeout: /fs/emmc/web/cgi-bin/test.cgi```

My test CGI is simple
```
#! /bin/sh
echo "<html>Hello, World! " $* " <html>"
```

```lib/roles/cgi/cgi-server.c``` is hard coded to use ```env_array[n++] = "PATH=/bin:/usr/bin:/usr/local/bin:/var/www/cgi-bin"``` while my scripts are in ```/fs/emmc/web/cgi-bin```, as specified in the origin.  Is this the source of the problem? 

In addition, it would seem that hard coding the PATH environment variable could allow a web page to run arbitrary commands (and using ports 80 and 443 requires running as root).  I would much rather set the PATH in the ```cgi_env``` field.

Any thoughts about how to get CGI scripts working in my server would be greatly appreciated!

Thanks,
Peter

**Comment by lws-team** [comment]
On 6/11/19 7:50 PM, pblemel wrote:
> Hi,
> 
> I am trying to configure my web server to run arbitrary cgi-scripts on 
> an embedded device (where arbitrary is limited to only scripts found in 
> my cgi-bin directory). I can not compile libuv due to porting issues, 
> and therefore can't use lwsws. I am instead adding support manually, and 
> not finding much in the way of documentation describing how to do this.
> 
> I have configured with |-DLWS_WITH_CGI=1|, and am now trying to create 
> the appropriate mount point. What I */want/* to do is tell LWS where my 
> cgi scripts live, and leave it up to the web page to specify which 
> script to run. E.g. :
> 
> |static const struct lws_http_mount cgi = { /* .mount_next */ &data, /* 
> linked-list "next" */ /* .mountpoint */ "/cgi-bin", /* mountpoint URL */ 
> /* .origin */ "/fs/emmc/web/cgi-bin", /* scripts dir */ /* .def */ NULL, 
> /* .protocol */ NULL, /* .cgienv */ NULL, /* .extra_mimetypes */ NULL, 
> /* .interpret */ NULL, /* .cgi_timeout */ 0, /* .cache_max_age */ 0, /* 
> .auth_mask */ 0, /* .cache_reusable */ 0, /* .cache_revalidate */ 0, /* 
> .cache_intermediaries */ 0, /* .origin_protocol */ LWSMPRO_CGI, /* 
> .mountpoint_len */ 8, /* char count */ /* .basic_auth_login_file */ 
> NULL, }; |
> 
> Where the 'origin' field would be interpreted as a directory, and the 
> script accessed using something like |https://localhost/cgi-bin/test.cgi|
> 
> However, based on what I think that I'm seeing in |lws_http_action()|, 
> LWS only sets |cmd[0] = hit->origin|, and |lws_cgi()| doesn't appear to 
> pass the script any arguments. In other words, it appears that LWS wants 
> a mount for */each script/* - meaning (if I am understanding this 
> correctly) that I instead need ;

That's right.

"Real" CGI scripts like mailman or cgit require a lot of configuration 
and additional mounts at specific urls also agreed with the script.  Eg 
cgit wants a per-vhost CGIT_CONFIG passing in the cgi environment, which 
can be done in the cgi mount config.

This whitelist approach also makes it harder to find a way to abuse it.

> |static const struct lws_http_mount cgi = { /* .mount_next */ &data, /* 
> linked-list "next" */ /* .mountpoint */ "/cgi-bin", /* mountpoint URL */ 
> /* .origin */ "/fs/emmc/web/cgi-bin/test.cgi", /* handler */ /* .def */ 
> NULL, ... /* .origin_protocol */ LWSMPRO_CGI, /* .mountpoint_len */ 8, 
> /* char count */ /* .basic_auth_login_file */ NULL, }; |
> 
> My first question is, "Is this correct? Or, have I misunderstood how LWS 
> processes CGI scripts?" If so, I can certainly dynamically build a list 
> of mounts using |scandir()| (et al) but I don't think I'm reading this 
> right.

It's designed to run the cgi(s) needed on https://libwebsockets.org... 
nowadays that's just mailman and cgit was replaced by gitohashi, which 
is proxied over a unix domain socket.

I guess you could add something to check if the cgi origin in the mount 
ended with * and allow anything (without .. ...) after that to get what 
you're looking for... patch welcome.

> Next, the server fails to run the CGI with the message
> |[2019/06/11 12:40:51:0029] NOTICE: CGI timeout: ./cgi-bin/test.cgi|
> 
> My test CGI is simple
> 
> |#! /bin/sh echo "<html>Hello, World! " $* " <html>" |
> 
> |lib/roles/cgi/cgi-server.c| is hard coded to use |env_array[n++] = 
> "PATH=/bin:/usr/bin:/usr/local/bin:/var/www/cgi-bin"| while my scripts 
> are in |/fs/emmc/web/cgi-bin|, as specified in the origin. Is this the 
> source of the problem?

Dunno... mailman is still working and that's a pretty recent lws.  I 
won't have time to look at it until the weekend.

> In addition, it would seem that hard coding the PATH environment 
> variable could allow a web page to run arbitrary commands (and using 
> ports 80 and 443 requires running as root). I would much rather set the 
> PATH in the |cgi_env| field.

Yes that's what it's for.

-Andy

**Comment by pblemel** [comment]
Thanks. I'll add some startup code to add cgis from a white list and maybe some extra verbose debugging to see if I can't figure out what's going on.

In the mean time, what I am really trying to accomplish right now is allowing the user to point their browser at a 'data' directory, where they can download files off of the device. I wasn't able to get LWS to present a list of files to the browser even with a '/fs/emmc/web/data' mount point, so my approach is to use a CGI to emit the file list wrapped in download tags.  Is there an easier way to do this?
 
Thanks again
Peter

**Comment by lws-team** [comment]
Lws doesn't generate directory listing html for you like eg, apache.
