### ISSUE TITLE
Client automatically following redirect and using wrong action

### ISSUE THREAD

**Issue by NickSchaf** [warmcat/libwebsockets#1603]
Using libwebsockets client to perform a POST to a given resource.  Server responds with status 303, providing a valid location header for the redirect.  The client immediately performs a POST to the resource in the location header, reusing the same wsi and user pointer.  As best I can tell, no callbacks are issued that would allow the client's caller to change the behavior.  For example: I wish the client to use GET on the new location, not POST, which is allowed based on my reading of RFC7231:
https://tools.ietf.org/html/rfc7231#section-6.4.4

**Comment by NickSchaf** [comment]
I've not yet tried modifying LWS.  I was in a severe time constraint when I ran into this; I worked around it by fudging the server to return 200 and having the client check for a location header during its callback so I could control spawning a new client connection for the redirect.
I wasn't reading the RFC on 303 to mean the POST body was ignored by the server, rather more like the old web forms where the form data was accepted (via POST) and the server is redirecting the browser to a "success" HTML page (which it should retrieve with GET).  From the RFC: "...which is intended to provide an **indirect response** to the original request." [emphasis mine]  In other words: "Thanks for your POST;  for my full response, go to [location]."

**Comment by lws-team** [comment]
> "Thanks for your POST; for my full response, go to [location]."

But that already works

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-form-post/minimal-http-server-form-post.c#n103-111

**Comment by NickSchaf** [comment]
From reading the RFC, I think the response codes have very different meanings. HTTP_STATUS_MOVED_PERMANENTLY (301) indicates the resource to which the client POSTed was permanently moved and should not be referenced again in the future.  Clients are supposed to update their references to use the new location.  303 implies the original request location was actually valid, but that the server would like the client to retrieve the response elsewhere.
Example:
`POST /users`
Response of 301 says: don't use `/users`, the new resource is `/usersnew`.
Response of 303 says: got your new user data, now visit `/newusersuccess.html` or `/newuserfailed.html`

It does look like some others use 302 for this, but that seems like a stretch of the definition.
Regardless, they're all handled the same way in LWS:
https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/client/client.c#n771

**Comment by lws-team** [comment]
Well... 5 months later...  Looking into this again I agree it needs to do something for 303... I pushed a patch on master that makes it retry / redirect with GET automatically and confirmed it works on h1 / h2 with the related minimal examples.  It needed an extra api so the user protocol code can understand if it's being called because it's doing the POST or doing the subsequent GET, see the patch changelog for details.
