### ISSUE TITLE
Not able to establish connection to same server using SSL connection

### ISSUE THREAD

**Issue by Tayender** [warmcat/libwebsockets#1606]
Hello,

I am using libwebsocket client to connect to a server and connection gets established successfully and message are sent and received successfully. 
But when i try to connect same server with wss://, connection doesn't establish .
get libwebsocket lib logs:
[319]print_lws_log(): created client ssl context for default
[319]print_lws_log():  SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
and in lws_protocols callback i get 
reason[1] in[client connect failed] user[] 

i did below extra changes for SSL connection
1. changed the port number from 80 to 443 lws_client_connect_info.port
2. set lws_client_connect_info.ssl_connection = LCCSCF_USE_SSL
3. set lws_context_creation_info.ssl_ca_filepath = "./data/_CA.pem"; // file exists
        lws_context_creation_info.ssl_cert_filepath = NULL;
        lws_context_creation_info.ssl_private_key_filepath = NULL;
4. set lws_context_creation_info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

Can you please help?

Thanks

**Comment by lws-team** [comment]
This is usually caused by the cert the server is handing out actually having been signed by an intermediate cert you don't have or trust.

Point this at your server and see what it says

https://www.ssllabs.com/ssltest/

If that's the problem, if you control the server you can solve it by adding the intermediate cert authority to the cert bundle the server issues.

**Comment by Tayender** [comment]
i get same error SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1), when i  don't provide the lws_context_creation_info.ssl_ca_filepath.
is it possible that lib is not even using it?

**Comment by Tayender** [comment]
Hello,
Can you please provide a sample , that explains how can i make ssl connection when i have ca cert file.
i couldn't find a good example on internet.

**Comment by lws-team** [comment]
Hmmm what do you mean by "CA cert"?  You mean you're the client and you have the CA certificate of a server who has its certificate issued by that CA?

This demonstrates it connection to warmcat.com over tls

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client

**Comment by Tayender** [comment]
You mean you're the client and you have the CA certificate of a server who has its certificate issued by that CA?
Ans:  Yes, i set that in info.ssl_ca_filepath.  info is lws_context_creation_info

**Comment by lws-team** [comment]
Let's ignore what you're doing and see if the unchanged minimal example above works for you on your platform.

**Comment by Tayender** [comment]
Ok, i will surely check that.
i have one more query , when i use the same certificate in lib-curl call, we set depth as 2
but in libwebsocket logs i get error SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1) , i.e. dapth=1.
Could that be the reason? Can i change the depth to 2?

**Comment by Tayender** [comment]
Hi, I ran the sample that you provided
getting below error
Unable to load SSL Client certs file from ./data/warmcat.com.cer -- client ssl isn't going to work
LWS_CALLBACK_CLIENT_CONNECTION_ERROR msg[read failed].
I am told that .cer is not supported on the machine that i am working on. 
i tried converting .cer to .pem using openssl but that gave error.

**Comment by lws-team** [comment]
".cer" is just a file suffix.  There is no strict relationship between file suffix and contents with tls certs.  What is inside there is already PEM and if it's the one lws provides, it's definitely parseable.

What tls library are you building lws against?  What version is it?

**Comment by Tayender** [comment]
The issue is fixed after we got a new certificate
Thankyou for you support :)
