### ISSUE TITLE
Minimal example link issue

### ISSUE THREAD

**Issue by nicovv44** [warmcat/libwebsockets#1607]
Hi,

The minimal example `libwebsockets/minimal-examples/ws-client/minimal-ws-client-tx` didn't compile saying `undefined reference to `lws_ring_get_count_free_elements'` and some others, so I changed the makefile.

[fix_minimal_example_compilation_issue.zip](https://github.com/warmcat/libwebsockets/files/3299440/fix_minimal_example_compilation_issue.zip)

I tried to submit with pull request but apparently I can't.

Cheers

**Comment by lws-team** [comment]
Your PR made it through but we should discuss it there... it patches one minimal example but there are about 50.  And it sounds like it bound itself to a different (distro?) lws than the one you built... either -DLWS_WITH_MINIMAL_EXAMPLES=1 to build the examples at the same time as the library or remove the conflicting distro lws should also have worked around it.  I'll close this for now and leave the PR open.

**Comment by nicovv44** [comment]
Distro: 
`Linux nemo 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
I tried again with `minimal-examples/ws-server/minimal-ws-server-ring`,
The `cmake` is ok, but the `make` gives:
```
Scanning dependencies of target lws-minimal-ws-server-ring
[ 50%] Building C object CMakeFiles/lws-minimal-ws-server-ring.dir/minimal-ws-server-ring.c.o
[100%] Linking C executable lws-minimal-ws-server-ring
CMakeFiles/lws-minimal-ws-server-ring.dir/minimal-ws-server-ring.c.o: In function `cull_lagging_clients':
minimal-ws-server-ring.c:(.text+0x27): undefined reference to `lws_ring_get_oldest_tail'
minimal-ws-server-ring.c:(.text+0x50): undefined reference to `lws_ring_get_count_waiting_elements'
minimal-ws-server-ring.c:(.text+0x14c): undefined reference to `lws_ring_get_count_waiting_elements'
[... etc ...]
[... etc ...]
collect2: error: ld returned 1 exit status
CMakeFiles/lws-minimal-ws-server-ring.dir/build.make:94: recipe for target 'lws-minimal-ws-server-ring' failed
make[2]: *** [lws-minimal-ws-server-ring] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lws-minimal-ws-server-ring.dir/all' failed
make[1]: *** [CMakeFiles/lws-minimal-ws-server-ring.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Consequently, the cmake patch I gave corrected my problem.
