### ISSUE TITLE
Libwebsocket connection fails on Ubuntu 18.04.2 platform

### ISSUE THREAD

**Issue by jaichahal** [warmcat/libwebsockets#1609]
Hello,

I am using libwebsocket client to connect to a server with **wss://** scheme on **Ubuntu 18.04.2 64 bit platform** and while connecting to the server I always get below error:

**[2019/06/18 04:27:50:4418] ERR: getaddrinfo failed: -2**

However when I use the same client code on MacBook 10.14.3 OS, it works perfectly.

Could you please help here understand this issue?

Thanks

**Comment by lws-team** [comment]
> getaddrinfo

So does DNS resolution work on your Ubuntu box?
