### ISSUE TITLE
NTLM Client Authentication

### ISSUE THREAD

**Issue by Dr-Emann** [warmcat/libwebsockets#1610]
I am trying to connect a websocket to a windows based websocket server, which requires authentication via either NTLM or Negotiate (kerberos or ntlm). The server requires Authentication on every request (not the connection, I can't pre-authenticate the socket (e.g. with libcurl) and somehow hand the connection to libwebsockets already authenticated)

1. Is it currently possible to do NTLM/Negotiate authentication when performing the websocket open? I'm pretty sure the answer is no, but I thought I'd check if I just missed something?
2. Would code to do NTLM/Negotiate be something which would be acceptable for libwebsockets to do? Would a pull request adding such authentication be considered?
    1. If so, do you have any hints on where in the library changes should be made in order to handle authentication methods like NTLM/Negotiate which require back-and-forth calls to authenticate?
    2. If not, is there another, more generic api you can think of which would allow the user code to provide callbacks to handle the back-and-forth authentication headers?

**Comment by lws-team** [comment]
No it doesn't support it already.  According to wikipedia, this is dead even to MS from win 8 onward

https://en.wikipedia.org/wiki/NTLMSSP

MS instead moved to kerberos.  Although I. really look forward to accepting new contributions if it's windows-only and it's dead, it sounds like a maintenence burden.  Doesn't it make more sense to look at kerberos?

**Comment by lws-team** [comment]
I'll close this for now since nothing for me to do, but please continue the topic here if you're still interested in kerberos.
