### ISSUE TITLE
compile error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'

### ISSUE THREAD

**Issue by maurerr** [warmcat/libwebsockets#1611]
Hi,

i'm building lws for an old broadcom mipsel kernel (2.6.22) using an openwrt inspired Makefile (https://github.com/maurerr/entware-packages/blob/entware-backports/libs/libwebsockets/Makefile) and I'm getting the following compile error:

> [ 28%] Building C object CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o
> /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/lib/tls/openssl/lws-genrsa.c: In function 'lws_genrsa_create':
> /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/lib/tls/openssl/lws-genrsa.c:75:10: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
>   ctx->rsa->e = ctx->bn[JWK_KEY_E];
>           ^
> CMakeFiles/websockets.dir/build.make:830: recipe for target 'CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o' failed
> make[5]: *** [CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o] Error 1
> make[5]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/websockets.dir/all' failed
> make[4]: *** [CMakeFiles/websockets.dir/all] Error 2
> make[4]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> Makefile:151: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> make[3]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> Makefile:102: recipe for target '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built' failed
> make[2]: *** [/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built] Error 2
> make[2]: Leaving directory '/home/debian/entware-backports/feeds/packages/libs/libwebsockets'
> package/Makefile:107: recipe for target 'package/feeds/packages/libwebsockets/compile' failed
> make[1]: *** [package/feeds/packages/libwebsockets/compile] Error 2
> make[1]: Leaving directory '/home/debian/entware-backports'
> Build failed - please re-run with -j1 to see the real error message
> /home/debian/entware-backports/include/toplevel.mk:216: recipe for target 'package/libwebsockets/compile' failed
> make: *** [package/libwebsockets/compile] Error 1
> 

how can I patch LWS to get around this issue?

Thanks

**Comment by lws-team** [comment]
It looks like cmake did not find RSA_set0_key() in your openssl.  That's OK, but then if so, openssl should be old enough to have RSA / struct rsa_st public so we can twiddle the key elements by hand.  But it seems it's new enough not to.  That means it's new enough to actually have RSA_set0_key().

I would guess there's some problem finding RSA_set0_key() in your cross-cmake... it's done via CHECK_FUNCTION_EXISTS(RSA_set0_key LWS_HAVE_RSA_SET0_KEY)... perhaps it's not bringing in the correct includes.

**Comment by maurerr** [comment]
I've pasted the complete rebuild log - maybe you can help me find the missing include.
debian@dont-delete-pls-1:~/entware-backports$ make package/libwebsockets/compile V=s -j40

> make[2]: Entering directory '/home/debian/entware-backports/scripts/config'
> make[2]: Leaving directory '/home/debian/entware-backports/scripts/config'
> Checking 'rsync'... ok.
> WARNING: your configuration is out of sync. Please run make menuconfig, oldconfig or defconfig!
> make[1]: Entering directory '/home/debian/entware-backports'
> make[2]: Entering directory '/home/debian/entware-backports/package/libs/toolchain'
> make[2]: Leaving directory '/home/debian/entware-backports/package/libs/toolchain'
> make[2]: Entering directory '/home/debian/entware-backports/feeds/packages/libs/libcap'
> make[2]: Entering directory '/home/debian/entware-backports/feeds/packages/libs/libuv'
> make[2]: Entering directory '/home/debian/entware-backports/package/libs/mbedtls'
> make[2]: Entering directory '/home/debian/entware-backports/package/libs/zlib'
> make[2]: Leaving directory '/home/debian/entware-backports/package/libs/zlib'
> make[2]: Leaving directory '/home/debian/entware-backports/feeds/packages/libs/libuv'
> make[2]: Leaving directory '/home/debian/entware-backports/package/libs/mbedtls'
> make[2]: Leaving directory '/home/debian/entware-backports/feeds/packages/libs/libcap'
> make[2]: Entering directory '/home/debian/entware-backports/package/libs/openssl'
> make[2]: Leaving directory '/home/debian/entware-backports/package/libs/openssl'
> make[2]: Entering directory '/home/debian/entware-backports/feeds/packages/libs/libwebsockets'
> rm -f /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built
> touch /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built_check
> CFLAGS="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float   -I/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/include -I/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/include -I/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/usr/include -I/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/include " CXXFLAGS="-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float   -I/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/include -I/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/include -I/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/usr/include -I/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/include " LDFLAGS="-L/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib -L/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0 -L/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/usr/lib -L/home/debian/entware-backports/staging_dir/toolchain-mipsel_mips32r2_gcc-5.4.0_uClibc-1.0.17/lib " make -j1 -C /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/. AR="mipsel-openwrt-linux-uclibc-gcc-ar" AS="mipsel-openwrt-linux-uclibc-gcc -c -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float " LD=mipsel-openwrt-linux-uclibc-ld NM="mipsel-openwrt-linux-uclibc-gcc-nm" CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB="mipsel-openwrt-linux-uclibc-gcc-ranlib" STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CROSS="mipsel-openwrt-linux-uclibc-" ARCH="mipsel" CMAKE_COMMAND='/home/debian/entware-backports/staging_dir/host/bin/cmake' CMAKE_DISABLE_cmake_check_build_system=1 ;
> make[3]: Entering directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> make[4]: Entering directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> make[5]: Entering directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> make[5]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> make[5]: Entering directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> [  0%] Building C object CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o
> /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/lib/tls/openssl/lws-genrsa.c: In function 'lws_genrsa_create':
> /home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/lib/tls/openssl/lws-genrsa.c:75:10: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
>   ctx->rsa->e = ctx->bn[JWK_KEY_E];
>           ^
> CMakeFiles/websockets.dir/build.make:830: recipe for target 'CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o' failed
> make[5]: *** [CMakeFiles/websockets.dir/lib/tls/openssl/lws-genrsa.c.o] Error 1
> make[5]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/websockets.dir/all' failed
> make[4]: *** [CMakeFiles/websockets.dir/all] Error 2
> make[4]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> Makefile:151: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> make[3]: Leaving directory '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0'
> Makefile:102: recipe for target '/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built' failed
> make[2]: *** [/home/debian/entware-backports/build_dir/target-mipsel_mips32r2_uClibc-1.0.17/libwebsockets-full/libwebsockets-3.1.0/.built] Error 2
> make[2]: Leaving directory '/home/debian/entware-backports/feeds/packages/libs/libwebsockets'
> package/Makefile:107: recipe for target 'package/feeds/packages/libwebsockets/compile' failed
> make[1]: *** [package/feeds/packages/libwebsockets/compile] Error 2
> make[1]: Leaving directory '/home/debian/entware-backports'
> Build failed - please re-run with -j1 to see the real error message
> /home/debian/entware-backports/include/toplevel.mk:216: recipe for target 'package/libwebsockets/compile' failed
> make: *** [package/libwebsockets/compile] Error 1

thanks

**Comment by lws-team** [comment]
This problem is happening at cmake, not at build.

**Comment by maurerr** [comment]
just found the options - although the library is newer - there is no support for LWS_HAVE_RSA_SET0_KEY

> Compiling with SSL support
> -- Found OpenSSL: /home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib/libcrypto.so (found version "1.1.1b")
> OpenSSL include dir: /home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/include
> OpenSSL libraries: /home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib/libssl.so;/home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib/libcrypto.so
> -- Looking for openssl/ecdh.h
> -- Looking for openssl/ecdh.h - found
> libuv include dir: /home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/include
> libuv libraries: /home/debian/entware-backports/staging_dir/target-mipsel_mips32r2_uClibc-1.0.17/opt/lib/libuv.so
> -- Looking for SSL_CTX_set1_param
> -- Looking for SSL_CTX_set1_param - not found
> -- Looking for SSL_set_info_callback
> -- Looking for SSL_set_info_callback - not found
> -- Looking for X509_VERIFY_PARAM_set1_host
> -- Looking for X509_VERIFY_PARAM_set1_host - not found
> -- Looking for RSA_set0_key
> -- Looking for RSA_set0_key - not found
> -- Looking for X509_get_key_usage
> -- Looking for X509_get_key_usage - not found
> -- Looking for SSL_CTX_get0_certificate
> -- Looking for SSL_CTX_get0_certificate - not found
> -- Looking for SSL_get0_alpn_selected
> -- Looking for SSL_get0_alpn_selected - not found
> -- Looking for SSL_set_alpn_protos
> -- Looking for SSL_set_alpn_protos - not found
> -- Looking for SSL_CTX_set_ciphersuites
> -- Looking for SSL_CTX_set_ciphersuites - not found
> -- Looking for SSL_CTX_get_extra_chain_certs_only
> -- Looking for SSL_CTX_get_extra_chain_certs_only - not found
> -- Looking for TLS_client_method
> -- Looking for TLS_client_method - not found
> -- Looking for TLSv1_2_client_method
> -- Looking for TLSv1_2_client_method - not found
> -- Performing Test LWS_HAVE_PIPE2
> -- Performing Test LWS_HAVE_PIPE2 - Failed
> -- Performing Test LWS_HAVE_TCP_USER_TIMEOUT
> -- Performing Test LWS_HAVE_TCP_USER_TIMEOUT - Failed
> Searching for OpenSSL executable and dlls
> OpenSSL executable: /usr/bin/openssl
>  GENCERTS = 0
> -- Looking for RPMTools... - rpmbuild NOT FOUND
> ---------------------------------------------------------------------
>   Settings:  (For more help do cmake -LH <srcpath>)
> ---------------------------------------------------------------------
>  LWS_WITH_STATIC = ON
>  LWS_WITH_SHARED = ON
>  LWS_WITH_SSL = ON (SSL Support)
>  LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
>  LWS_WITH_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
>  LWS_WITH_MBEDTLS = OFF (mbedTLS replacement for OpenSSL)
>  LWS_WITHOUT_BUILTIN_SHA1 = OFF
>  LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
>  LWS_WITHOUT_CLIENT = OFF
>  LWS_WITHOUT_SERVER = OFF
>  LWS_LINK_TESTAPPS_DYNAMIC = OFF
>  LWS_WITHOUT_TESTAPPS = ON
>  LWS_WITHOUT_TEST_SERVER = OFF
>  LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
>  LWS_WITHOUT_TEST_PING = OFF
>  LWS_WITHOUT_TEST_CLIENT = OFF
>  LWS_WITHOUT_EXTENSIONS = ON
>  LWS_WITH_LATENCY = OFF
>  LWS_WITHOUT_DAEMONIZE = ON
>  LWS_WITH_LIBEV = OFF
>  LWS_WITH_LIBUV = 1
>  LWS_WITH_LIBEVENT = OFF
>  LWS_IPV6 = ON
>  LWS_UNIX_SOCK = OFF
>  LWS_WITH_HTTP2 = 1
>  LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
>  LWS_MAX_SMP = 1
>  LWS_HAVE_PTHREAD_H = 1
>  LWS_WITH_CGI = ON
>  LWS_HAVE_OPENSSL_ECDH_H = 1
>  LWS_HAVE_SSL_CTX_set1_param =
>  LWS_HAVE_RSA_SET0_KEY =
>  LWS_WITH_HTTP_PROXY = OFF
>  LIBHUBBUB_LIBRARIES =
>  PLUGINS =
>  LWS_WITH_ACCESS_LOG = ON
>  LWS_WITH_SERVER_STATUS = ON
>  LWS_WITH_LEJP = ON
>  LWS_WITH_LEJP_CONF = ON
>  LWS_WITH_SMTP = OFF
>  LWS_WITH_GENERIC_SESSIONS = OFF
>  LWS_STATIC_PIC = OFF
>  LWS_WITH_RANGES = OFF
>  LWS_PLAT_OPTEE = OFF
>  LWS_WITH_ESP32 = OFF
>  LWS_WITH_ZIP_FOPS = OFF
>  LWS_AVOID_SIGPIPE_IGN = OFF
>  LWS_WITH_STATS = OFF
>  LWS_WITH_SOCKS5 = OFF
>  LWS_HAVE_SYS_CAPABILITY_H =
>  LWS_HAVE_LIBCAP = 1
>  LWS_WITH_PEER_LIMITS = OFF
>  LWS_HAVE_ATOLL = 1
>  LWS_HAVE__ATOI64 =
>  LWS_HAVE_STAT32I64 =
>  LWS_HAS_INTPTR_T = 1
>  LWS_WITH_EXPORT_LWSTARGETS = ON
> ---------------------------------------------------------------------
>

**Comment by lws-team** [comment]
Yeah.  But what seems to be as I said in the first reply, is that cmake doesn't think your openssl has that api.  But it seems to think wrong.  So, eg, maybe cmake is looking in the wrong place if your build system's own openssl is old.

You can hack your way around it in CMakeLists.txt by using set() to force LWS_HAVE_RSA_SET0_KEY to 1 after the test.

**Comment by maurerr** [comment]
fixed it by admin in the Makefile
    CMAKE_OPTIONS += -DLWS_HAVE_RSA_SET0_KEY=ON
    CMAKE_OPTIONS += -DLWS_HAVE_SSL_EXTRA_CHAIN_CERTS=ON

thank you very much for your help !!!
