### ISSUE TITLE
Is the member server_ssl_private_key_mem deprecated?

### ISSUE THREAD

**Issue by tli47** [warmcat/libwebsockets#1614]
My target to enable SSL mode in libwebsockets, and it is ok by set the below config.
>creationInfo.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
>creationInfo.ssl_cert_filepath = KEY_PUB_PATH.c_str();
>creationInfo.ssl_private_key_filepath = KEY_PRI_PATH.c_str();

I think I shouldn't use an explicit file path to get a key(key will not be exported to an explicit file), I could search server_ssl_private_key_mem to help this, actually, there's a build error 
>" 'struct lws_context_creation_info' has no member named 'server_ssl_private_key_mem_len'"

Is this member deprecated?

**Comment by lws-team** [comment]
Typically (eg, if you buy an SSL cert) the private key is provided as a PEM file.  If the key in your case is from memory, then yes the _mem stuff was added on master for that case.

This certainly exists in master

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n652

so the questions are... are you using master?  Are your libwebsockets includes coming from an install of a build of master?  (as opposed to, eg, distro libwebsockets in /usr/include)

**Comment by tli47** [comment]
The key is stored in a device secure position, I could get the key memory using some methods, and I don't want to expose the private key to a file on a filesystem.

It's from https://github.com/warmcat/libwebsockets/releases/tag/v3.1.0(89eedca),
I use the related *tar.gz.

**Comment by lws-team** [comment]
This server_ssl_private_key_mem_len stuff was introduced on master a few months ago... it doesn't exist in v3.1.  It can't be backported because it will change the v3.1 abi.

It sounds like you're looking at master headers but using v3.1... just use master if you want this.
