### ISSUE TITLE
Can't listen Server response. [FIN, ACK] sent after a write. No TLS.

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#1615]
Hi,
I wrote a client copied from minimal-ws-client-rx, but disabling SSL (TLS)

![image](https://user-images.githubusercontent.com/52041342/60018043-8145cf80-968a-11e9-8a22-72f05947a02c.png)

And transmiting an initial messege when I get connected to server:

![image](https://user-images.githubusercontent.com/52041342/60018087-a5a1ac00-968a-11e9-83fb-abf891cff30c.png)

But I found sniffing in the network that 1,5 miliseconds later of sending the message it sends a [FIN, ACK]:

![image](https://user-images.githubusercontent.com/52041342/60018164-e8638400-968a-11e9-8ee5-d6713b050ef1.png)

So the server doesn't response to my client.

This doesn't happen in the minimal examples because they work with TLS:

![image](https://user-images.githubusercontent.com/52041342/60018423-9cfda580-968b-11e9-9469-e51f8c7f4bb7.png)

Here is the code:

`/*
 * lws-minimal-ws-client
 *
 * Written in 2010-2019 by Andy Green <andy@warmcat.com>
 *
 * This file is made available under the Creative Commons CC0 1.0
 * Universal Public Domain Dedication.
 *
 * This demonstrates the a minimal ws client using lws.
 *
 * It connects to https://libwebsockets.org/ and makes a
 * wss connection to the dumb-increment protocol there.  While
 * connected, it prints the numbers it is being sent by
 * dumb-increment protocol.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <libwebsockets.h>
#include <json.h>

static int bExit;
static int interrupted, rx_seen, test;
static struct lws *client_wsi;
static char ping[LWS_PRE + 250];

static int
callback_dumb_increment(struct lws *wsi, enum lws_callback_reasons reason,
              void *user, void *in, size_t len)
{

        int n;

        json_object *jarray = json_object_new_array();
        json_object *jobj_type = json_object_new_object();
        json_object *jobj_ID = json_object_new_object();
        json_object *jobj_action = json_object_new_object();
        json_object *jobj = json_object_new_object();

        jobj_type = json_object_new_int(2); /* A call from client to server */

        jobj_ID = json_object_new_string("1946577");
        jobj_action = json_object_new_string("BootNotification");

        char *str = "{\
                \"chargePointVendor\": \"MilHouse\", \
                \"chargePointModel\": \"Fusion\", \
            }";

        //printf("str:\n---\n%s\n---\n\n", str);

        json_object_array_add(jarray,jobj_type);
        json_object_array_add(jarray,jobj_ID);
        json_object_array_add(jarray,jobj_action);

        jobj = json_tokener_parse(str);

        json_object_array_add(jarray,jobj);
        switch (reason) {

        /* because we are protocols[0] ... */
        case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
            lwsl_err("CLIENT_CONNECTION_ERROR: %s\n",
                     in ? (char *)in : "(null)");
            client_wsi = NULL;
            break;

        case LWS_CALLBACK_CLIENT_ESTABLISHED:
            lwsl_user("%s: established\n", __func__);
            lws_callback_on_writable(wsi);
            break;

        case LWS_CALLBACK_CLIENT_WRITEABLE:
            printf("[Test Protocol] The client is able to write.\n");

            // Write the buffer from the LWS_PRE index + 128 (the buffer size)

            int m;

            printf("jobj from str:\n---\n%s\n---\n", json_object_to_json_string_ext(jarray, JSON_C_TO_STRING_PLAIN));

            n = 0;

            n = snprintf((char *)ping + LWS_PRE, json_object_array_length(jarray),
                json_object_to_json_string_ext(jarray, JSON_C_TO_STRING_PLAIN));

            sprintf((char *)ping + LWS_PRE, json_object_to_json_string_ext(jarray, JSON_C_TO_STRING_PLAIN));

            lwsl_user("Sending PING %d...\n", n);

            m = lws_write(wsi, ping + LWS_PRE, n, LWS_WRITE_TEXT);
            if (m < n) {
                lwsl_err("sending ping failed: %d\n", m);
            }

            lws_callback_on_writable(wsi);
            break;

        case LWS_CALLBACK_CLIENT_RECEIVE:
                lwsl_user("RX: %s\n", (const char *)in);
                rx_seen++;
                if (test && rx_seen == 10)
                        interrupted = 1;
                break;

        case LWS_CALLBACK_CLIENT_CLOSED:
                client_wsi = NULL;
                break;

        default:
                break;
        }

        return lws_callback_http_dummy(wsi, reason, user, in, len);
}

static const struct lws_protocols protocols[] = {
        {
                "ocpp1.6",
                callback_dumb_increment,
                0,
                0,
        },
        { NULL, NULL, 0, 0 }
};

static void
sigint_handler(int sig)
{
        interrupted = 1;
}

int main(int argc, const char **argv)
{
        struct lws_context_creation_info info;
        struct lws_client_connect_info i;
        struct lws_context *context;
        const char *p;
        int n = 0, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE
                /* for LLL_ verbosity above NOTICE to be built into lws, lws
                 * must have been configured with -DCMAKE_BUILD_TYPE=DEBUG
                 * instead of =RELEASE */
                /* | LLL_INFO */ /* | LLL_PARSER */ /* | LLL_HEADER */
                /* | LLL_EXT */ /* | LLL_CLIENT */ /* | LLL_LATENCY */
                /* | LLL_DEBUG */;

        char inputURL[300] = "ws://192.168.1.19:8080/steve/websocket/CentralSystemService/Test1234";
        int inputPort = 80;

        const char *urlProtocol, *urlTempPath; // the protocol of the URL, and a temporary pointer to the path
        char urlPath[300]; // The final path string

        signal(SIGINT, sigint_handler);
        if ((p = lws_cmdline_option(argc, argv, "-d")))
                logs = atoi(p);

        test = !!lws_cmdline_option(argc, argv, "-t");

        lws_set_log_level(logs, NULL);
        lwsl_user("LWS minimal ws client rx [-d <logs>] [--h2] [-t (test)]\n");

        memset(&ping[LWS_PRE], 0, 250);

        memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */
        info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
        info.port = CONTEXT_PORT_NO_LISTEN; /* we do not run any server */
        info.protocols = protocols;
        info.extensions = NULL;
        /*
         * since we know this lws context is only ever going to be used with
         * one client wsis / fds / sockets at a time, let lws know it doesn't
         * have to use the default allocations for fd tables up to ulimit -n.
         * It will just allocate for 1 internal and 1 (+ 1 http2 nwsi) that we
         * will use.
         */
        info.fd_limit_per_thread = 1 + 1 + 1;

        context = lws_create_context(&info);
        if (!context) {
                lwsl_err("lws init failed\n");
                return 1;
        }

        memset(&i, 0, sizeof i); /* otherwise uninitialized garbage */

        if (lws_parse_uri(inputURL, &urlProtocol, &i.address, &i.port, &urlTempPath))
        {
            printf("Couldn't parse URL\n");
        }

        // Fix up the urlPath by adding a / at the beginning, copy the temp path, and add a \0 at the end
        urlPath[0] = '/';
        strncpy(urlPath + 1, urlTempPath, sizeof(urlPath) - 2);
        urlPath[sizeof(urlPath) - 1] = '\0';

        i.path = urlPath; // Set the info's path to the fixed up url path

        i.context = context;
        i.host = i.address;
        i.origin = i.address;
        i.ssl_connection = 0; // Don't use SSL for this test
        i.protocol = protocols[0].name; /* "dumb-increment-protocol" */
        i.pwsi = &client_wsi;

        if (lws_cmdline_option(argc, argv, "--h2"))
                i.alpn = "h2";

        lws_client_connect_via_info(&i);

        // Main loop runs till bExit is true, which forces an exit of this loop
        while (!bExit)
        {
            // LWS' function to run the message loop, which polls in this example every 50 milliseconds on our created context
            lws_service(context, 50);
        }

        lws_context_destroy(context);

        lwsl_user("Completed %s\n", rx_seen > 10 ? "OK" : "Failed");

        return rx_seen > 10;
}`

Any idea?

Thank you.

**Comment by fusionJose** [comment]
Here is everything I could see in the network, until the [FIN, ACK], also SSH communication with my app:

![image](https://user-images.githubusercontent.com/52041342/60020731-e8ff1900-9690-11e9-9623-5fb0cb4738a6.png)

**Comment by lws-team** [comment]
I'm not going to look at your code.

What about logs from lws?

**Comment by fusionJose** [comment]
Logs look like this:

![image](https://user-images.githubusercontent.com/52041342/60022085-704d8c00-9693-11e9-8505-bab8b1188cca.png)

I´m using QMAKE and I've configured he log level with all the flags:

![image](https://user-images.githubusercontent.com/52041342/60022139-88bda680-9693-11e9-857d-945d630229dc.png)

Is there anything more that I can see? 

Thanks.

**Comment by lws-team** [comment]
Did you build with cmake having -DCMAKE_BUILD_TYPE=DEBUG?

**Comment by fusionJose** [comment]
I'm using qmake, is there any way to build it with it? If not I will install the cmake. Thank you

**Comment by lws-team** [comment]
You can use what you want, it's foss.

But it's a bit brave just using qmake without referencing what cmake produces.  You should at least follow the supported cmake flow and then do the make with V=1 VERBOSE=1 and see what the gcc commandline looks like.

And it's a bit presumptious dragging me along for the ride when you hit problems.  Nobody said this works with qmake.

**Comment by fusionJose** [comment]
I´ve made the project with cmake, and still works the same. I´ve read the log and sais this:

' 0x0A (role=0x10000000) wsi->lextable_pos=238
[2019/06/25 10:54:11:6367] PARSER: known hdr 8
[2019/06/25 10:54:11:6367] PARSER: v00 hdrs done
[2019/06/25 10:54:11:6368] PARSER: lws_client_int_s_hs: protocol list 'ocpp1.6'
[2019/06/25 10:54:11:6368] DEBUG: Selected protocol ocpp1.6
[2019/06/25 10:54:11:6368] DEBUG: lws_ensure_user_space: 0x9007428 protocol pss 0, user_space=(nil)
[2019/06/25 10:54:11:6368] DEBUG: __lws_set_timeout: 0x9007428: 0 secs (reason 0)
[2019/06/25 10:54:11:6368] INFO: __lws_header_table_detach: wsi 0x9007428: ah 0x90084a8 (tsi=0, count = 1)
[2019/06/25 10:54:11:6368] INFO: __lws_header_table_detach: nobody usable waiting
[2019/06/25 10:54:11:6368] INFO: _lws_destroy_ah: freed ah 0x90084a8 : pool length 0
[2019/06/25 10:54:11:6369] INFO: __lws_header_table_detach: wsi 0x9007428: ah 0x90084a8 (tsi=0, count = 0)
[2019/06/25 10:54:11:6369] DEBUG: lws_role_transition: 0x9007428: wsistate 0x10000117, ops ws
[2019/06/25 10:54:11:6369] DEBUG: _realloc: size 4116: client frame buffer
[2019/06/25 10:54:11:6369] INFO: Allocating client RX buffer 4112
[2019/06/25 10:54:11:6369] DEBUG: handshake OK for protocol ocpp1.6
[2019/06/25 10:54:11:6369] USER: callback_dumb_increment: established
[2019/06/25 10:54:11:6369] DEBUG: _lws_change_pollfd: wsi 0x9007428: fd 6 events 1 -> 5
[2019/06/25 10:54:11:6370] DEBUG: _lws_change_pollfd: wsi 0x9007428: fd 6 events 5 -> 1
[2019/06/25 10:54:11:6370] DEBUG: lws_handle_POLLOUT_event: 0x9007428: non mux: wsistate 0x10000117, ops ws
[Test Protocol] The client is able to write.
jobj from str:
---
[2,"1946577","BootNotification",{"chargePointVendor":"MilHouse","chargePointModel":"Fusion"}]
---
[2019/06/25 10:54:11:6371] USER: Sending PING 93...
[2019/06/25 10:54:11:6371] INFO: lws_issue_raw: ssl_capable_write (99) says 99
[2019/06/25 10:54:11:6373] INFO: rops_handle_POLLIN_ws: LWS_SSL_CAPABLE_ERROR
[2019/06/25 10:54:11:6373] DEBUG: 0x9007428: Close and handled
[2019/06/25 10:54:11:6373] INFO: __lws_close_free_wsi: 0x9007428: caller: close_and_handled
[2019/06/25 10:54:11:6373] DEBUG: __lws_close_free_wsi: real just_kill_connection: 0x9007428 (sockfd 6)
[2019/06/25 10:54:11:6374] DEBUG: lwsi_set_state(0x9007428, 0x1000001e)
[2019/06/25 10:54:11:6374] DEBUG: __lws_close_free_wsi_final: wsi 0x9007428: fd 6
[2019/06/25 10:54:11:6374] INFO: lws_vhost_unbind_wsi: vh default: count_bound_wsi 0
[2019/06/25 10:54:11:6374] DEBUG: __lws_free_wsi: 0x9007428, remaining wsi 1
[2019/06/25 10:54:12:0409] DEBUG: _realloc: size 380: cbwsi
[2019/06/25 10:54:12:0410] DEBUG: _realloc: size 24: cbtmr
[2019/06/25 10:54:12:0410] DEBUG: lws_service_periodic_checks: timed cb: vh default, protocol lws-abs-cli-raw-skt, reason 1000


So it seems that after writing and sending the message it closes the socket. It calls to lws_close_free_wsi.

**Comment by lws-team** [comment]
> So it seems that after writing and sending the message it closes the socket. It calls to lws_close_free_wsi.

No... after sending it sees the socket had been closed by the remote peer.

So have a look at his logs.

**Comment by fusionJose** [comment]
Okey, but I don't understand the LWS_SSL_CAPABLE_ERROR issue. I have SSL disabled.

**Comment by lws-team** [comment]
Openssl, mbedtls and no ssl all have their errors summarized into the same enum.  Ssl-capable means it's an api that works the same (and produces the same internal error codes) whether its operating inside tls or not.

**Comment by fusionJose** [comment]
Of course the remote peer was closing.

I also noticed that the websocket client is sending in the HTTP header a Connection: close, upgrade, instead of only Connection: upgrade.

Is there anyway to change or configure the HTTP header?
I saw in the libwebsockets code that comes from here:

if (!wsi->client_pipeline)
                        conn1 = "close, ";
                p = lws_generate_client_ws_handshake(wsi, p, conn1);


Thank you

**Comment by lws-team** [comment]
Connection: close, upgrade is perfectly correct.

If your server blows up with it, set the flag `LCCSCF_PIPELINE` on client creation info .ssl_connection.

**Comment by fusionJose** [comment]
Okey, now works correctly. Thank you very much for all.
