### ISSUE TITLE
Raw TLS vhost?

### ISSUE THREAD

**Issue by zevv** [warmcat/libwebsockets#1619]
Is there a way to use SSL sockets without HTTP in libwebsockets? I'm looking for the equivalent of the `minimal-raw-vhost` example, but then allowing libws to take care of the SSL layer.

I'm probably missing something trivial, but here are my findings up to now:

The `raw-skt` role seems to be able to do a `LWS_ADOPT_ALLOW_SSL`, but when I want to create a vhost bound to the `raw-skt` role I need to set `LWS_SERVER_OPTION_ADOPT_APPLY_LISTEN_ACCEPT_CONFIG`, which causes `opts` to be set to `LWS_ADOPT_SOCKET` in `rops_handle_POLLIN_listen`, dropping the `LWS_ADOPT_ALLOW_SSL` bit that was set earlier.

Thank you!

**Comment by lws-team** [comment]
`raw-skt` is supposed to be able to do this.  If you change the line you mention setting LWS_ADOPT_SOCKET to OR it on instead, is it otherwise workable?  If so, please send a patch or at least let me know the result.

**Comment by zevv** [comment]
No luck; strace shows `poll()` keeps spinning with POLLIN available on the socket, but no one is picking it up. I'll investigate later, need to leave for today. Thanks so far.

**Comment by zevv** [comment]
Does this make sense? https://github.com/zevv/libwebsockets/commit/c4efa36f25fb09e1ede90a3e6de805c49031e2b3

**Comment by lws-team** [comment]
Thanks... I modified it a bit and fixed some related things... and added a -s option on minimal-raw-vhost... you can connect to it like this if you started it with -s

```
$ ncat --ssl -v 127.0.0.1 7681
```

please give current master that has your modified patch a try.

**Comment by zevv** [comment]
Thanks, that should do.
