### ISSUE TITLE
How can I increased the  rx_buffer_size , per_session_data_size ? 

### ISSUE THREAD

**Issue by KabeerSadiq123** [warmcat/libwebsockets#1626]

**Comment by lws-team** [comment]
what happens if you just increase them in the protocol definition, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c#n147

**Comment by KabeerSadiq123** [comment]
> what happens if you just increase them in the protocol definition, eg
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c#n147

That is already 65536, still it is showing below error: 
lwsts[3058]: 0x7efee9194060 new partial sent 14516 from 15692 total (after 2nd call ) 
and after that :
lwsts[11001]: ****** 0x7fdcc00037c0: Sending new 16191 (¦~?;{"status": 0, "), pending truncated ...
       It's illegal to do an lws_write outside of
       the writable callback: fix your code
 (above after 3rd call) 
No issue after first call.
I am calling lws_write 3 times, from  reason == LWS_CALLBACK_SERVER_WRITEABLE  condition.
Thanks

**Comment by lws-team** [comment]
That's two things completely unrelated to what you are asking about.

1) the tcp stack on your platform is refusing to take everything you offered it.  They will do that based on memory pressure and the size of the tcp window.  Networks are not limitless pipes you can shove anything you want into at any time.

Lws will conceal that problem by allocating memory to hold the left-over data that wasn't sent, will temporarily disable production of WRITEABLE callbacks, and will send the left-overs in the background.  When they're all gone, lws will produce WRITEABLE callbacks again so you can send something else.

2) Partial sends may happen at any time according to memory and network conditions.  Therefore you cannot do 3 x lws_write()s sequentially... you can only do 1 per WRITEABLE.  The first may have been a partial write.

On master lws these restrictions are relaxed a bit, it now uses lws_buflist internally and can allocate to cover multiple partial writes.  But they are still inefficient for memory and cpu... you should ideally send one thing that is around 1 x mtu in size per WRITEABLE callback, which is almost always accepted by the tcp stack on a connection that said it was WRITEABLE.  Websocket protocol has the concept of fragments to allow you to send large messages in smaller steps like this.  HTTP you can just write ~1mtu of content and ask for another callback on writable.

**Comment by KabeerSadiq123** [comment]
@lws-team 
Oky, thanks a lot for quick response.
