### ISSUE TITLE
multiple client Certificates

### ISSUE THREAD

**Issue by GeorgeShagov** [warmcat/libwebsockets#1630]
Hello
At this moment I am setting `struct lws_context_creation_info info;` as follows:

```
info.options          = LWS_SERVER_OPTION_VALIDATE_UTF8 | LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE
                        ;
info.options                 |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
                        | LWS_SERVER_OPTION_REQUIRE_VALID_OPENSSL_CLIENT_CERT
                        ;
info.ssl_cert_filepath        = "localhost-100y.cert";
info.ssl_private_key_filepath = "localhost-100y.key";                                 
info.client_ssl_cert_filepath = "local.cert";
info.client_ssl_private_key_filepath = "local.key";

```

This works fine
But I would like to issue multiple client certificates, using only one server.
Any chances in doing this with lws?

thx in advance

**Comment by lws-team** [comment]
Yes... client tls context lives in the vhost... if you don't specify one when you create the context, the default vhost is used.  And if you just create the lws context and no explicit vhosts, your settings are applied to the default vhost.

But you can create n vhosts, see eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n110
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n140

When the vhost is created, the info members related to tls are used for that specific vhost's client context.  You can bind your connection to a specific vhost when you create it using `.vhost` in the client info struct

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n92
