### ISSUE TITLE
Can't compile the lastest version under Linux Subsystem for Windows

### ISSUE THREAD

**Issue by 012345678987654321** [warmcat/libwebsockets#1633]
Hi!

Can't compile the lastest version under linux subsystem for windows. The library gets compiled without any error, but the resultig libwebsockets.so has a size of 0kb in windows explorer (19kb with ls -l in the bash)?

Have i missed something?

**Comment by lws-team** [comment]
I have actual Linux (as does Travis) and no problem.  I don't have windows.

As to whether you missed something who knows, you don't really describe what you did.  Make install?  Where is the .so?

The .so should be a symlink after install... maybe it is and windows doesn't really understand it.

**Comment by lws-team** [comment]
No info coming... I guess you were looking at the symlink libwebsockets.so and not the thing it actually pointed to.
