### ISSUE TITLE
not able to cross compile libwebsockets for ARM

### ISSUE THREAD

**Issue by nitu011** [warmcat/libwebsockets#1636]
+ cd ../libwebsockets/
+ cd build
+ sudo cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/nitu/master_latest/gateway-app/build/titan_e2c.cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -DLWS_WITH_SSL=1 -DLWS_WITH_LWSWS=1 -DLWS_WITH_LIBUV=1 -DLWS_LIBUV_LIBRARIES=/home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/lib/libuv.so -DLWS_LIBUV_INCLUDE_DIRS=/home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/include -DLWS_ZLIB_LIBRARIES=/home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/lib//libz.so -DLWS_ZLIB_INCLUDE_DIRS=/home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/lib/include
-- Compiled with LWS_WITH_DIR and LWS_WITH_DIR
-- CMAKE_TOOLCHAIN_FILE='/home/nitu/master_latest/gateway-app/build/titan_e2c.cmake'
Git commit hash: v3.1.0-230-g8ed67dfb
-- LWS_WITH_LWSWS --> Enabling LWS_WITH_PLUGINS and LWS_WITH_LIBUV
Compiling with SSL support
OpenSSL include dir: /opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include
OpenSSL libraries: /opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libssl.so;/opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libcrypto.so
libuv include dir: /home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/include
libuv libraries: /home/nitu/iot/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/lib/libuv.so
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl
 GENCERTS = 1
Generating SSL Certificates for the test-server...
Generating a 1024 bit RSA private key
.....++++++
................................++++++
writing new private key to '/home/nitu/master_latest/gateway-app/libwebsockets/build/libwebsockets-test-server.key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:SUCCESSFULLY generated SSL certificate
-- Looking for RPMTools... - rpmbuild NOT FOUND
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = 1 (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_WITH_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_WITH_MBEDTLS = OFF (mbedTLS replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = 0
 LWS_WITHOUT_SERVER = 0
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_EXTENSIONS = ON
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_WITH_LIBEV = OFF
 LWS_WITH_LIBUV = 1
 LWS_WITH_LIBEVENT = OFF
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = 1
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 1
 LWS_HAVE_PTHREAD_H = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H =
 LWS_HAVE_SSL_CTX_set1_param =
 LWS_HAVE_RSA_SET0_KEY =
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES =
 PLUGINS = protocol_dumb_increment;protocol_lws_mirror;protocol_lws_status;protocol_lws_table_dirlisting;protocol_lws_raw_test;protocol_deaddrop;protocol_lws_server_status;protocol_client_loopback_test;protocol_post_demo;protocol_lws_raw_proxy;protocol_lws_ssh_base;protocol_lws_sshd_demo
 LWS_WITH_ACCESS_LOG = 1
 LWS_WITH_SERVER_STATUS = 1
 LWS_WITH_LEJP = 1
 LWS_WITH_LEJP_CONF = 1
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
 LWS_WITH_RANGES = OFF
 LWS_PLAT_OPTEE = OFF
 LWS_WITH_ESP32 = OFF
 LWS_WITH_ZIP_FOPS = OFF
 LWS_AVOID_SIGPIPE_IGN = OFF
 LWS_WITH_STATS = OFF
 LWS_WITH_SOCKS5 = OFF
 LWS_HAVE_SYS_CAPABILITY_H =
 LWS_HAVE_LIBCAP =
 LWS_WITH_PEER_LIMITS = 1
 LWS_HAVE_ATOLL = 1
 LWS_HAVE__ATOI64 =
 LWS_HAVE_STAT32I64 =
 LWS_HAS_INTPTR_T = 1
 LWS_WITH_EXPORT_LWSTARGETS = ON
 LWS_WITH_ABSTRACT =
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nitu/master_latest/gateway-app/libwebsockets/build
+ echo /home/nitu/master_latest/gateway-app/libwebsockets/build
/home/nitu/master_latest/gateway-app/libwebsockets/build
+ sudo make
[  0%] Building C object CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o
****cc: fatal error: no input files
compilation terminated.
/bin/sh: 1: -O2: not found
CMakeFiles/websockets_shared.dir/build.make:62: recipe for target 'CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o' failed
make[2]: *** [CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o] Error 127
CMakeFiles/Makefile2:358: recipe for target 'CMakeFiles/websockets_shared.dir/all' failed
make[1]: *** [CMakeFiles/websockets_shared.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2****

**Comment by lws-team** [comment]
So what is in your cross toolchain file `titan_e2c.cmake`?

**Comment by nitu011** [comment]
set(CROSS_PATH /opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi)



# Target operating system name.

INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much
SET(CMAKE_SYSTEM_PROCESSOR arm)

# this is the location of the amd64 toolchain targeting the Raspberry Pi
SET(CMAKE_C_COMPILER ${CC})
if (CMAKE_BUILD_TYPE MATCHES RELEASE OR CMAKE_BUILD_TYPE MATCHES Release OR CMAKE_BUILD_TYPE MATCHES release)

        set(CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE} -O2)

        set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE} -O2)

endif()

set(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")



# Adjust the default behavior of the FIND_XXX() commands:

# search programs in the host environment only.

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)



# Search headers and libraries in the target environment only.

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

**Comment by lws-team** [comment]
I guess you need to override CC env var before running make / cmake.  Check the build instructions if you should have sourced a shell script before trying to build.

If you're building cross you need a cross toolchain, like arm-linux-eabi-gcc or whatever...the cmake toolchain file must point to it one way or another.

This isn't an lws issue, you should better ask the guys who gave you the cross toolchain cmake file how to use it.

**Comment by nitu011** [comment]
Its pointing only to that toolchain , if you see the build `logs ...files are not getting generated in this folder :
CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o'

**Comment by lws-team** [comment]
What is 'its'?  You think 'it's' pointing there but there's no evidence in what you pasted.

Lws doesn't have its own idea about it but just follows cmake.  Lws builds just fine with the supplied cross toolchain files.  So it's not an lws issue.

Try `make V=1 VERBOSE=1` and look at the compiler commandline.

**Comment by nitu011** [comment]
I cleaned the build directory and compiled again , now getting new error :
/opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/bits/wordsize.h:38:2: error: #error "__WORDSIZE is not defined"
 #error "__WORDSIZE is not defined"
  ^~~~~
/opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/bits/wordsize.h:42:5: error: "__MHWORDSIZE" is not defined, evaluates to 0 [-Werror=undef]
 #if __MHWORDSIZE == 32
     ^~~~~~~~~~~~
/opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/bits/wordsize.h:58:7: error: "__MHWORDSIZE" is not defined, evaluates to 0 [-Werror=undef]
 #elif __MHWORDSIZE == 64
       ^~~~~~~~~~~~
/opt/iotgw-sdk-prod/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/bits/wordsize.h:61:2: error: #error "Unknown __WORDSIZE detected"
 #error "Unknown __WORDSIZE detected"

Have you seen this type of error ?

**Comment by lws-team** [comment]
Again it's completely unrelated to lws but related to your toolchain... there are include dirs defined for internal toolchain includes like bits/ and should be another paraalel include dir like linux/ or so containing os-specific defines.  Maybe your toolchain is borked but whatever it is, it's not an lws ptoblem.

**Comment by nitu011** [comment]
thanks
