### ISSUE TITLE
when the file to download not found, 404 was not return

### ISSUE THREAD

**Issue by hjfbswb** [warmcat/libwebsockets#1638]
```
static const struct lws_http_mount mount = {
	/* .mount_next */	&mount_dyn,		/* linked-list "next" */
	/* .mountpoint */		"/",		/* mountpoint URL */
	/* .origin */		"/usr/bin/web",	/* serve from dir */
	/* .def */			"index.htm",	/* default filename */
	/* .protocol */			NULL,
	/* .cgienv */			NULL,
	/* .extra_mimetypes */		g_atExtraMimeTypes,
	/* .interpret */		NULL,
	/* .cgi_timeout */		0,
	/* .cache_max_age */		0,
	/* .auth_mask */		0,
	/* .cache_reusable */		0,
	/* .cache_revalidate */		0,
	/* .cache_intermediaries */	0,
	/* .origin_protocol */		LWSMPRO_FILE,	/* files in a dir */
	/* .mountpoint_len */		1,		/* char count */
	/* .basic_auth_login_file */	NULL,
};
```
When I call `lws_create_context`, I specified a `struct lws_http_mount`(please see above).
But when I use HTTP GET method to download a file that does't exist, lws did not return status code 404, but called my first protocol's callback.

I saw the code to return 404 was commented.
https://github.com/warmcat/libwebsockets/blob/7a626ef32077f29f63e9a815f88ff74d97cd6c14/lib/roles/http/server/server.c#L1582

I think this behave was confusing, because when my protocol callback was called, I have to check  
 if this request is what my callback was supposed to handle, or if it was transferred after failing to download the file.

**Comment by lws-team** [comment]
On current master, if I look at the minimal example minimal-http-server which seems to be constructed the same as you describe, I can't reproduce the problem... I get a 404.  If I comment the line that specifies the redirect for a 404, I still get a 404, just not so pretty.
