### ISSUE TITLE
Multiple client connection via same context

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1639]
Hi 
I am using libwebsocket 3.0.1 library version. And I would like to create multiple websocket client connection (only url is different) to a websocket server. So i have to create a context of lws, and create multiple connection instance by calling lws_connect_via_info ryt ?

**Comment by lws-team** [comment]
Yes, that's all you need to do.

But I would use more modern lws, even v3.1-stable.  See, eg,

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c
