### ISSUE TITLE
enquiry of async handler

### ISSUE THREAD

**Issue by lsching17** [warmcat/libwebsockets#164]
As libwebsocket is single-threaded, i guess it is important that all callback handler should not block.

If the handler need to perform time-consuming task (e.g. connect to database), it should be performed in separate thread.

it is quite easy to enqueue tasks to a thread-safe queue, but how can external thread request libwebsocket to output generated data?

Thanks in advance

**Comment by KumarShrawan** [comment]
Do we have some example code where this can be demonstrated where  handler need to perform time-consuming task (e.g. connect to database) ?

**Comment by warmcat** [comment]
No... but basically the user code would have another thread start to do the task and return from the handler with the task still in progress.

When the other thread is done, he can call libwebsocket_callback_on_writable() to get the lws service thread to call back with that wsi and WRITEABLE reason, where it can check the result of the other thread and react accordingly.

You have to also take care about cancel the task if you see the wsi is doing a CLOSE.
