### ISSUE TITLE
Is there a way to receive data with busy polling?

### ISSUE THREAD

**Issue by freedom0822** [warmcat/libwebsockets#1641]
I need reduce my recv latency, so select or epoll is not a good solution.  could libwebsockets has a way to recv data in busy polling,  like socket usage?  Thanks

**Comment by lws-team** [comment]
> I need reduce my recv latency, so select or epoll is not a good solution

Why do you say that?  There is no reason eg select() adds latency per se.

It sounds like you got the wrong idea about something.

 - what is your target latency?

 - what latency do you measure?

 - how did you measure it

 - how many sockets are active?

> busy polling

I think you have the wong idea.

**Comment by freedom0822** [comment]
only one socket is active, 

I just want handle data like below:
`while(true) {
  int ret = recv(fd, data, len, 0);
  if (no data)
    continue;
  # handle data
}`

**Comment by freedom0822** [comment]
only one socket is active,

I just want handle data like below:

> while(true) {
  int ret = recv(fd, data, len, 0);
  if (no data)
    continue;
  // handle data
}

**Comment by lws-team** [comment]
The point is select() or poll() should add latency measured in ns or us on a typical system.  I can't believe your latency target is on that scale.

If it is behaving differently, something else is wrong.  Eg, your arrangements for the lws service loop itself.

**Comment by freedom0822** [comment]
I'm working for a quant trading project, use websocket to receive market data, so even us latency is important for us.

**Comment by lws-team** [comment]
Then put your ws implementation in the kernel.

You're not going to be able to measure the difference from busywaiting.

**Comment by freedom0822** [comment]
do you mean lws didn't use select or epoll ? seems it doesn't occupy one cpu to handle data

**Comment by lws-team** [comment]
... lws uses poll() by default.

> seems it doesn't occupy one cpu to handle data

http://man7.org/linux/man-pages/man2/poll.2.html

**Comment by freedom0822** [comment]
so there's no way to forbid poll(), and occupy one cpu to recv data?

**Comment by freedom0822** [comment]
thanks indeed
