### ISSUE TITLE
lws_http_get_uri_and_method not returning right method

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#1642]
This is issue is related to issue  `How to get http request method? #1261` where `lws_http_get_uri_and_method` was made public

...
```
// Declaration
​extern const char * const method_names[];​

// Location to capture methods
​case LWS_CALLBACK_FILTER_HTTP_CONNECTION:
lwsl_debug("LWS_CALLBACK_FILTER_HTTP_CONNECTION --- %p\n", wsi);
// Using the function
int uri_len, meth = ​​lws_http_get_uri_and_method(wsi, &uri_ptr, &uri_len);
lwsl_debug("%u Method: '%s' (%d), request for '%s'\n", __LINE__, method_names[meth], meth, uri_ptr);​
```

I'm expecting to see the same result as the following internal function is returning
```static int
lws_h2_parse_end_of_frame(struct lws *wsi)

[2019/07/28 19:17:33:8034] INFO:     :method = GET
```
But instead I get with
```​lws_http_get_uri_and_method```
the following
```
[2019/07/28 19:17:33:8039] DEBUG: 1467 Method: ':path' (8), request for '/'
```
Same for delete
```
static int
lws_h2_parse_end_of_frame(struct lws *wsi)

[2019/07/28 19:17:33:7883] INFO:     :method = DELETE

​lws_http_get_uri_and_method

[2019/07/28 19:17:33:7885] DEBUG: 1467 Method: ':path' (8), request for '/520267355/232809336'
```
POST request work just fine.  So basically for everything else that is not a ```POST``` I'm getting a ```path``` as method

**Comment by lws-team** [comment]
Well... h2 != h1.  Lws does quite well concealing it and providing common behaviours so you can write the user code once.  But this (until now) internal API is showing an h2-specific difference driven by something that is actually different in h2.

On h1, the URL is placed into a method-specific header slot.  So GET uri path goes in `WSI_TOKEN_*_URI` where `*` is GET, POST, PATCH etc.  On h2 the url comes on a new `:path` header (`WSI_TOKEN_HTTP_COLON_PATH`) regardless of the method.  For GET and POST, lws copies the URI into the right path-specific header to look like it's still h1.  It doesn't do it for the others.

You could work around it by looking in `WSI_TOKEN_HTTP_COLON_METHOD` if you get `:path`, to find the real h2 method.  But I think as we're offering this as a public api lws should probably do more to hide the h1 / h2 difference.

I pushed a patch on master that on h2 does the duplication of `:path` for all the h1 methods, so the `lws_http_get_uri_and_method()` call should return the copy before hitting `:path`... please see if that helps.

**Comment by alexeadem** [comment]
That works perfectly. Thanks!

**Comment by lws-team** [comment]
Great.
