### ISSUE TITLE
Android NDK Build Issue

### ISSUE THREAD

**Issue by ashtondchen** [warmcat/libwebsockets#1644]
Hi, I am quite new to CMake and trying to compile libwebsockets using Android NDK but cannot figure what goes wrong in my CMakeLists.txt. Compilation error show that during the linking, there is an undefined reference to the built library. Can you take a quick look at my CMakeLists.txt as following to see what I am missing?

cmake_minimum_required(VERSION 3.4.1)

add_subdirectory(lib/libwebsockets)
include_directories (lib/libwebsockets/include)
include_directories(build/cmake/debug/x86/lib/libwebsockets)
include_directories (lib/openssl/x86/include)
#add_library (libwebsockets SHARED IMPORTED)

add_library(native-lib SHARED native-lib.c )

target_link_libraries( native-lib libwebsockets )

**Comment by lws-team** [comment]
Can you paste the error?

**Comment by ashtondchen** [comment]
After I change libwebsockets to websockets in the following, the linking error is gone.
target_link_libraries( native-lib libwebsockets )
