### ISSUE TITLE
Using HaProxy load balancer to balance the load on servers.

### ISSUE THREAD

**Issue by KabeerSadiq123** [warmcat/libwebsockets#1645]
Hi @lws-team ,
I am running HaProxy Load balancer to balance the load on the server. When I started the server (only one server) and Haproxy below logs are coming on server. client was not running that time. 

```
==============================================================
lwsts[24944]: lws_server_socket_service: wsi 0x7fd0ac0041a0 read 0
lwsts[24944]: Accepted wsi 0x7fd0ac0041a0 to context 0xc13b5d0, tsi 0
lwsts[24944]:  forbidding on uri sanitation
lwsts[24944]: lws_server_socket_service: wsi 0x7fd0ac0041a0 read 0
lwsts[24944]: Accepted wsi 0x7fd0ac0041a0 to context 0xc13b5d0, tsi 0
lwsts[24944]:  forbidding on uri sanitation
lwsts[24944]: lws_server_socket_service: wsi 0x7fd0ac0041a0 read 0
lwsts[24944]: Accepted wsi 0x7fd0ac0041a0 to context 0xc13b5d0, tsi 0
lwsts[24944]:  forbidding on uri sanitation
lwsts[24944]: lws_server_socket_service: wsi 0x7fd0ac0041a0 read 0
client_loop: send disconnect: Connection reset by peer
=============================================================
```
Seems like HAProxy is not getting ack from server. 
Please help.

**Comment by lws-team** [comment]
> forbidding on uri sanitation

What's the situation with tls?  If haproxy terminates the tls, the onward proxy action may be without ssl now, or vice versa.

**Comment by KabeerSadiq123** [comment]
In Haproxy config,  I commented on all the ssl related info, but still the same issue.

**Comment by lws-team** [comment]
So the lws part is also set up to not listen with tls?

Then use something like `tcpdump -ilo -s0 -X port 7681` (adjust it to the correct port and interface) and capture what is actually being sent by haproxy.

You can also tell the lws part to log more verbosely.  Make sure you built the library with cmake option CMAKE_BUILD_TYPE=DEBUG enabled and set the log level (usually by -d on lws examples) to 1151 or so.

**Comment by KabeerSadiq123** [comment]
Capture the packet:
Flags: 0X002 (SYN) ...and only SYN was set there.

**Comment by lws-team** [comment]
Doubt it... "forbidding on uri sanitation" means the parser received something that didn't look like valid http.  Turn up the lws logging as described above.

**Comment by KabeerSadiq123** [comment]
--lwsws.debug-level=7 was this in config 
and compiled lws with below setting 
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd` .. -DLWS_WITH_LWSWS=1 -DLWS_LIBUV_LIBRARIES=`pwd`/../../libuv/build/lib/libuv.so.1.0.0 -DLWS_LIBUV_INCLUDE_DIRS=`pwd`/../..//libuv/build/include -DCMAKE_BUILD_TYPE=DEBUG -DLWS_WITHOUT_DAEMONIZE=0

**Comment by lws-team** [comment]
7 is not very verbose, it's a bitfield.  Try 1151 there as suggested.

**Comment by KabeerSadiq123** [comment]
after 1151
==============================
lwsts[23769]: fd=14, revents=1
lwsts[23769]: accepted new conn  port 57448 on fd=9
lwsts[23769]: Accepted wsi 0x7ff244004240 to context 0xcffb5d0, tsi 0
lwsts[23769]: lws_set_timeout: 0x7ff244004240: 20 secs
lwsts[23769]: insert_wsi_socket_into_fds: 0x7ff244004240: tsi=0, sock=9, pos-in-fds=2
lwsts[23769]: lws_header_table_attach: wsi 0x7ff244004240: ah (nil) (tsi 0, count = 0) in
lwsts[23769]: lws_header_table_attach: wsi 0x7ff244004240: ah 0xd1faec0: count 1 (on exit)
lwsts[23769]: Attached ah immediately
lwsts[23769]: fd=9, revents=1
lwsts[23769]: lws_read: incoming len 35  state 0
lwsts[23769]: issuing 35 bytes to parser
lwsts[23769]: WSI_TOKEN_NAME_PART 'H' (mode=0)
lwsts[23769]: WSI_TOKEN_NAME_PART 'E' (mode=0)
lwsts[23769]: Unknown method - dropping
lwsts[23769]:  forbidding on uri sanitation
lwsts[23769]: lws_parse failed
lwsts[23769]: lws_header_table_detach: wsi 0x7ff244004240: ah 0xd1faec0 (tsi=0, count = 1)
lwsts[23769]: lws_header_table_detach: wsi 0x7ff244004240: ah 0xd1faec0 (tsi=0, count = 0)
lwsts[23769]: lws_close_free_wsi: shutting down connection: 0x7ff244004240 (sock 9, state 2)
lwsts[23769]: lws_set_timeout: 0x7ff244004240: 20 secs
lwsts[23769]: fd=9, revents=17
lwsts[23769]: lws_server_socket_service: wsi 0x7ff244004240 read 0
lwsts[23769]: lws_server_socket_service: read 0 len
lwsts[23769]: lws_close_free_wsi: real just_kill_connection: 0x7ff244004240 (sockfd 9)
lwsts[23769]: remove_wsi_socket_from_fds: removing same prot wsi 0x7ff244004240
lwsts[23769]: remove_wsi_socket_from_fds: wsi=0x7ff244004240, sock=9, fds pos=2, end guy pos=3, endfd=0
lwsts[23769]: not calling back closed mode=0 state=2
lwsts[23769]: ah det due to close
lwsts[23769]: lws_header_table_detach: wsi 0x7ff244004240: ah (nil) (tsi=0, count = 0)
lwsts[23769]: lws_header_table_detach: wsi 0x7ff244004240: ah (nil) (tsi=0, count = 0)
lwsts[23769]: lws_free_wsi: 0x7ff244004240, remaining wsi 1

**Comment by lws-team** [comment]
Lws doesn't support HEAD atm... what version of lws is it?

**Comment by KabeerSadiq123** [comment]
/* The Libwebsocket version */
#define LWS_LIBRARY_VERSION "2.1.0"
@lws-team , what is HEAD atm ?

**Comment by lws-team** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

Try a more recent lws, at least 3.1.

**Comment by KabeerSadiq123** [comment]
Hi @lws-team , 
Tried with new version of Lws, parsing issue is not there, there is no issue with tcp 3-way hand-shaking also, but server is sending bad request to HaProxy (HTTP/1.0 400 Bad Request (test/html )) and after that connection is getting closed. 
========================================================
Server Logs are below(only server and HaProxy are running, no client ). 
=========================================================
lwsts[30615]: accepted new conn port 43594 on fd=9
lwsts[30615]: _realloc: size 672: new server wsi
lwsts[30615]: new wsi 0x7ff768005170 joining vhost localhost, tsi 0
lwsts[30615]: lws_vhost_bind_wsi: vh localhost: count_bound_wsi 2
lwsts[30615]: lwsi_set_state(0x7ff768005170, 0x20000200)
lwsts[30615]: lws_role_transition: 0x7ff768005170: wsistate 0x20000015, ops h1
lwsts[30615]: __lws_set_timeout: 0x7ff768005170: 20 secs (reason 3)
lwsts[30615]: __insert_wsi_socket_into_fds: 0x7ff768005170: tsi=0, sock=9, pos-in-fds=2
lwsts[30615]: lws_header_table_attach: wsi 0x7ff768005170: ah (nil) (tsi 0, count = 0) in
lwsts[30615]: _realloc: size 976: ah struct
lwsts[30615]: _realloc: size 4096: ah data
lwsts[30615]: _lws_create_ah: created ah 0x7ff768005710 (size 4096): pool length 1
lwsts[30615]: _lws_change_pollfd: wsi 0x7ff768005170: fd 9 events 1 -> 1
lwsts[30615]: lws_header_table_attach: did attach wsi 0x7ff768005170: ah 0x7ff768005710: count 1 (on exit)
lwsts[30615]: __lws_set_timeout: 0x7ff768005170: 10 secs (reason 25)
lwsts[30615]: Attached ah immediately
lwsts[30615]: rops_handle_POLLIN_h1: 0x7ff768005170: wsistate 0x20000015
lwsts[30615]: lws_read_h1: h1 path: wsi state 0x15
lwsts[30615]: issuing 35 bytes to parser
lwsts[30615]: WSI_TOKEN_NAME_PART 'H' 0x48 (role=0x20000000) wsi->lextable_pos=0
lwsts[30615]: WSI_TOKEN_NAME_PART 'E' 0x45 (role=0x20000000) wsi->lextable_pos=102
lwsts[30615]: WSI_TOKEN_NAME_PART 'A' 0x41 (role=0x20000000) wsi->lextable_pos=1136
lwsts[30615]: WSI_TOKEN_NAME_PART 'D' 0x44 (role=0x20000000) wsi->lextable_pos=1137
lwsts[30615]: WSI_TOKEN_NAME_PART ' ' 0x20 (role=0x20000000) wsi->lextable_pos=1138
lwsts[30615]: known hdr 82
lwsts[30615]: WSI_TOK_(82) '/'
lwsts[30615]: WSI_TOK_(82) ' '
lwsts[30615]: WSI_TOK_(15) 'H'
lwsts[30615]: WSI_TOK_(15) 'T'
lwsts[30615]: WSI_TOK_(15) 'T'
lwsts[30615]: WSI_TOK_(15) 'P'
lwsts[30615]: WSI_TOK_(15) '/'
lwsts[30615]: WSI_TOK_(15) '1'
lwsts[30615]: WSI_TOK_(15) '.'
lwsts[30615]: WSI_TOK_(15) '1'
lwsts[30615]: WSI_TOK_(15) 'r'
lwsts[30615]: WSI_TOK_(15) 'n'
lwsts[30615]: WSI_TOK_(15) 'H'
lwsts[30615]: WSI_TOK_(15) 'o'
lwsts[30615]: WSI_TOK_(15) 's'
lwsts[30615]: WSI_TOK_(15) 't'
lwsts[30615]: WSI_TOK_(15) ':'
lwsts[30615]: WSI_TOK_(15) 'l'
lwsts[30615]: WSI_TOK_(15) 'o'
lwsts[30615]: WSI_TOK_(15) 'c'
lwsts[30615]: WSI_TOK_(15) 'a'
lwsts[30615]: WSI_TOK_(15) 'l'
lwsts[30615]: WSI_TOK_(15) 'h'
lwsts[30615]: WSI_TOK_(15) 'o'
lwsts[30615]: WSI_TOK_(15) 's'
lwsts[30615]: WSI_TOK_(15) 't'
'wsts[30615]: WSI_TOK_(15) '
lwsts[30615]: *
lwsts[30615]: WSI_TOKEN_SKIPPING_SAW_CR '
'
' 0x0D (role=0x20000000) wsi->lextable_pos=0
lwsts[30615]: WSI_TOKEN_NAME_PART '
' 0x0A (role=0x20000000) wsi->lextable_pos=238
lwsts[30615]: known hdr 8
lwsts[30615]: lws_handshake_server: parsed count 35
lwsts[30615]: lws_handshake_server: lws_parse sees parsing complete
lwsts[30615]: no host
lwsts[30615]: lwsi_set_state(0x7ff768005170, 0x20000209)
lwsts[30615]: __lws_set_timeout: 0x7ff768005170: 0 secs (reason 0)
lwsts[30615]: lws_handshake_server: 0x7ff768005170: No upgrade
lwsts[30615]: lwsi_set_state(0x7ff768005170, 0x20000117)
lwsts[30615]: lws_handshake_server: wsi 0x7ff768005170: ah 0x7ff768005710
lwsts[30615]: Method: 'HEAD' (7), request for '/'
lwsts[30615]: _realloc: size 8: user space
lwsts[30615]: __lws_set_timeout: 0x7ff768005170: 20 secs (reason 10)
lwsts[30615]: no hit
lwsts[30615]: _realloc: size 384: user space
lwsts[30615]: lwsi_set_state(0x7ff768005170, 0x20000118)
lwsts[30615]: lws_issue_raw: ssl_capable_write (404) says 404
lwsts[30615]: LWS_CALLBACK_HTTP closing
lwsts[30615]: __lws_close_free_wsi: 0x7ff768005170: caller: lws_read_h1 bail
lwsts[30615]: __lws_close_free_wsi: shutdown conn: 0x7ff768005170 (sk 9, state 0x118)
lwsts[30615]: __lws_close_free_wsi: real just_kill_connection: 0x7ff768005170 (sockfd 9)
lwsts[30615]: _lws_change_pollfd: wsi 0x2fc4a50: fd 14 events 1 -> 1
lwsts[30615]: lwsi_set_state(0x7ff768005170, 0x2000001e)
lwsts[30615]: __lws_close_free_wsi_final: wsi 0x7ff768005170: fd 9
lwsts[30615]: __lws_header_table_detach: wsi 0x7ff768005170: ah 0x7ff768005710 (tsi=0, count = 1)
lwsts[30615]: __lws_header_table_detach: nobody usable waiting
lwsts[30615]: _lws_destroy_ah: freed ah 0x7ff768005710 : pool length 0
lwsts[30615]: __lws_header_table_detach: wsi 0x7ff768005170: ah 0x7ff768005710 (tsi=0, count = 0)
lwsts[30615]: rops_destroy_role_h1: ah det due to close
lwsts[30615]: lws_vhost_unbind_wsi: vh localhost: count_bound_wsi 1
lwsts[30615]: __lws_free_wsi: 0x7ff768005170, remaining wsi 2

**Comment by lws-team** [comment]
AFAICS lws doesn't itself ever generate a 400.  If I try to reproduce this with the test server and no tls, I get a 404

```
$ (echo -n -e "HEAD / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n"; sleep 2 ) | nc 127.0.0.1 7681
HTTP/1.1 404 Not Found
content-type: text/html
content-length: 173

<html><head><meta charset=utf-8 http-equiv="Content-Language" content="en"/><link rel="stylesheet" type="text/css" href="/error.css"/></head><body><h1>404</h1></body></html>
```

Doing the same thing using GET returns the index.html page as expected

I pushed a small patch on v3.1-stable and master that fixes this so HEAD works as expected, at least if there's a mount there.  Please give it a try.

**Comment by KabeerSadiq123** [comment]
Using the below lws version:
#define LWS_LIBRARY_VERSION "3.1.99"

**Comment by lws-team** [comment]
Right it's master branch.  Just update to current master and rebuild / retry.

**Comment by lws-team** [comment]
... need more info...
