### ISSUE TITLE
libwebsockets client v3.1.0 disconnect with error

### ISSUE THREAD

**Issue by djole1973** [warmcat/libwebsockets#1650]
Environment:
server: apache-tomcat-9.0.16
client: lws 3.1.0

Client configuration:
	appl.connect_info.port = _port;
	lws_parse_uri(uri, &prot, &appl.connect_info.address, &appl.connect_info.port, &p);

	/* add back the leading / on path */
	if (p[0] != '/') 
	{
		_path[0] = '/';
		lws_strncpy(_path + 1, p, sizeof(_path) - 1);
		appl.connect_info.path = _path;
	}
	else
	{
		appl.connect_info.path = p;
	}

	if (!strcmp(prot, "http") || !strcmp(prot, "ws"))
	{
		_use_ssl = LCCSCF_PIPELINE;
	}
	if (!strcmp(prot, "https") || !strcmp(prot, "wss"))
	{
		if (!_use_ssl)
		{
			_use_ssl = LCCSCF_USE_SSL;
		}
	}

	appl.creation_info.port = CONTEXT_PORT_NO_LISTEN;
	appl.creation_info.protocols = protocols;
	appl.creation_info.gid = -1;
	appl.creation_info.uid = -1;

	//TODO: SSL

	appl.context = lws_create_context(&appl.creation_info);
	if (appl.context == NULL)
	{
		lwsl_err("rng: Creating libwebsocket context failed.\n");
		return;
	}

	appl.connect_info.ssl_connection = _use_ssl;
	appl.connect_info.context = appl.context;
	appl.connect_info.host = appl.connect_info.address;
	appl.connect_info.origin = appl.connect_info.address;
	appl.connect_info.ietf_version_or_minus_one = -1;

I've just try to connect and disconnect and got result as you can see:
![libwebsocket-client](https://user-images.githubusercontent.com/3696772/62528126-a0647f00-b83c-11e9-8c3c-8fb0b92de7ff.png)

on the other hand I tr to reproduce the problem with Chrome Smart Websocket Client:
![smartwebsocket-client](https://user-images.githubusercontent.com/3696772/62528368-05b87000-b83d-11e9-8dba-7785ce268ccc.png)

If you have any idea haw to deal  with the explained problem, I'll kind ask you for any tip?

**Comment by lws-team** [comment]
First of all use the latest v3.1-stable.

If you still have a problem, enable the lws logs, preferably after building lws with cmake .. -DCMAKE_BUILD_TYPE=DEBUG and set the log mask to, eg, 1151

**Comment by djole1973** [comment]
Attache log:
[TEST207.log](https://github.com/warmcat/libwebsockets/files/3471459/TEST207.log)

**Comment by lws-team** [comment]
You're literally using today's v3.1-stable, 58954691749449f123cb8803ef712450c06b5cb7 ?

**Comment by djole1973** [comment]
PS C:\Application\vcpkg> .\vcpkg.exe install libwebsockets:x64-windows
The following packages will be built and installed:
    libwebsockets[core]:x64-windows
Starting package 1/1: libwebsockets:x64-windows
Building package libwebsockets[core]:x64-windows...
-- Using cached C:/Application/vcpkg/downloads/warmcat-libwebsockets-v3.1.0.tar.gz
-- Using source at C:/Application/vcpkg/buildtrees/libwebsockets/src/v3.1.0-1c566e1539
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libwebsockets[core]:x64-windows... done
Installing package libwebsockets[core]:x64-windows...
Installing package libwebsockets[core]:x64-windows... done
Elapsed time for package libwebsockets:x64-windows: 1.302 min

Total elapsed time: 1.302 min

The package libwebsockets:x64-windows provides CMake targets:

    find_package(Libwebsockets CONFIG REQUIRED)
    target_link_libraries(main PRIVATE websockets_shared)


Also in the log:
[2019-08-06 12:05:32.325] [TEST207] [trace] Libwebsockets version: 3.1.0 unknown-build-hash

But anyway I will try to debug until I reach the point:
		//	if (!wsi->client_pipeline)
			conn1 = "close, ";		//		conn1 = "close, ";

**Comment by lws-team** [comment]
> /src/v3.1.0-1c566e1539

Use latest v3.1-stable.

**Comment by djole1973** [comment]
I see! :-)

**Comment by djole1973** [comment]
The problem still exist: 
![image](https://user-images.githubusercontent.com/3696772/62542381-f72d8100-b85b-11e9-9762-c9bda776809b.png)

And the log file:
[TEST207.log](https://github.com/warmcat/libwebsockets/files/3472360/TEST207.log)

**Comment by lws-team** [comment]
AFAICS the server hangs up on us... we think we opened a ws connection just fine.

Have a look in the server logs and see what it thinks was objectionable.

**Comment by djole1973** [comment]
With Chrome Smart Websocket Client everything work fine(just connect-disconnect).
Here is the traffic:
![image](https://user-images.githubusercontent.com/3696772/62543289-ebdb5500-b85d-11e9-9ca8-b3e52d96b6c6.png)

**Comment by lws-team** [comment]
Great... just use that then.

Otherwise let's debug the server logs...

**Comment by djole1973** [comment]
Thank you for help.

**Comment by djole1973** [comment]
One more thing: is there any way to send close reason just before web socket client disconnect?
Something like:
```
	lws_close_reason(wsi, LWS_CLOSE_STATUS_NORMAL, NULL, 0);
	lws_context_destroy(wsi);
```

**Comment by lws-team** [comment]
What you're doing there is contradictory... it's just logically setting the close reason to use when it closes the wsi, but you are immediately killing its ability to do anything at all by destroying the context and event loop.

You must a) cause the wsi to want to close after setting the reason (either return nonzero from most callbacks or use, eg,lws_set_timeout(..., LWS_TO_KILL_ASYNC)), and b) leave the event loop up until after the wsi has closed under its own steam, afterwards you can exit the event loop and destroy the context.  Consider the socket may not be ready right then to accept any more tx, you may have to wait a bit.

**Comment by djole1973** [comment]
It works! just return -1. Thank you.

![image](https://user-images.githubusercontent.com/3696772/62626132-fada0a00-b926-11e9-86ee-3a57db767ac5.png)

One more thin, why is the last TCP packet [RST, ACK] and not only [ACK].

**Comment by lws-team** [comment]
We already closed our side.
