### ISSUE TITLE
libwebsockets client v3.1-stable disconnect with error

### ISSUE THREAD

**Issue by djole1973** [warmcat/libwebsockets#1651]
Hi I saw you close issues. Unfortunately the problem still exist:

![image](https://user-images.githubusercontent.com/3696772/62542819-e16c8b80-b85c-11e9-8e52-2bed0172eac3.png)

And here is new log:
[2019-08-06 15:04:48.462] [TEST207] [trace] Libwebsockets version: 3.1.0 v3.1.0-90-g58954691

[TEST207.log](https://github.com/warmcat/libwebsockets/files/3472417/TEST207.log)

Please can you check it out?

**Comment by lws-team** [comment]
We don't need two issues.
