### ISSUE TITLE
Including libwebsockets.h in a c++ applications fails

### ISSUE THREAD

**Issue by jurlhardt** [warmcat/libwebsockets#1653]
In lws-retry.h in the declaration 

```C
lws_retry_get_delay_ms(struct lws_context *context, const lws_retry_bo_t *retry,
                       uint16_t *try, char *conceal);
```

the c++ reserved keyword try is used as a parameter.

This results in the following g++ error:
`/usr/include/libwebsockets/lws-retry.h:59:20: error: expected ‘,’ or ‘...’ before ‘try’
          uint16_t *try, char *conceal);`

**Comment by lws-team** [comment]
Yeah... my mistake.  It's changed to `ctry` on current master.

See the third para here for hints on how to follow master without headaches.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md
