### ISSUE TITLE
issue about when client request connection > max_http_header_pool at same time cause crash

### ISSUE THREAD

**Issue by breeze1234** [warmcat/libwebsockets#1654]
(gdb) bt
#0  0x0000000000e0e585 in lws_header_table_attach ()
#1  0x0000000000e11adf in lws_client_connect_via_info ()

**Comment by breeze1234** [comment]
the version is 1.7.5 ,   and the default max http header pool is 16,  when connection count max than 16 at the same time , it will crash, and if I set the http header pool to 200 or more large , it's OK and build connection OK.
could you help have a look?

**Comment by lws-team** [comment]
> the version is 1.7.5 

It's four years old... please upgrade it to, eg v3.1-stable which is still maintained.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

or at least update it to the last 1.7.x, 1.7.9

https://libwebsockets.org/git/libwebsockets/log?id=a085a0ab3838401c7ff9bf2ad8646af633746a14

**Comment by breeze1234** [comment]
thanks for reply, Does version 1.7.9 fix this problem?

**Comment by lws-team** [comment]
> Does version 1.7.9 fix this problem?

Try it and find out.
