### ISSUE TITLE
requesting a 3.1 patch release with fix "openssl: client: check wsi from openssl private data"

### ISSUE THREAD

**Issue by jnynw** [warmcat/libwebsockets#1655]
Hi lws team,
Would it be possible to release a 3.1 patch with following fix? I am facing the same crash on my client code.

Thanks

ede747f1bcd8fc52ba57369f84c00fee92b44807

Commits on Apr 3, 2019
openssl: client: check wsi from openssl private data  …

@lws-team
lws-team committed on Apr 3
v2.4 was patched to check NULL wsi in the verify callback,
nobody has reported it on later versions, but might as well
check it too.

**Comment by lws-team** [comment]
Sounds like a good idea... I picked it on to v3.1-stable
