### ISSUE TITLE
How to get url parameters with ws server

### ISSUE THREAD

**Issue by seamusmore** [warmcat/libwebsockets#1658]
I create a websocket server to transfer websocket connection to tcp connection. I must pass some parameters to the ws server by url(e.g. ws://192.168.9.139:3001/?rhost=192.168.8.236&rport=8100&sn=5848F19403907&chn=0) when establish a websocket connection. But the ws server will not trigger LWS_CALLBACK_HTTP status in callback, so I can't get the url parameters. Is there any way to get url paramters in ws server?

**Comment by lws-team** [comment]
You can also get them at the ESTABLISHED callback for ws connections.

Immediately after that the http ah that contains them is detached, since it's no long in http mode.

**Comment by seamusmore** [comment]
> You can also get them at the ESTABLISHED callback for ws connections.
> 
> Immediately after that the http ah that contains them is detached, since it's no long in http mode.

thanks for answer. I try to get parameter in ESTABLISHED callback, but the result is null.
here is my code:
`int ProtocolVideoWS::CallbackVideoWsServer(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) 
{
	int ret = 0;
	switch (reason) {
	case LWS_CALLBACK_PROTOCOL_INIT:
		/* Only once per protocol */
		ret = OnProtocolInit(wsi, user, in, len);
		break;
	case LWS_CALLBACK_ESTABLISHED:
		/* Connection established */
		{
			const char *host = lws_get_urlarg_by_name(wsi, "rhost=", (char *)in, len);
			const char *port = lws_get_urlarg_by_name(wsi, "rhost", (char *)in, len);
			printf("%s:%s\n", host, port);
		}
		ret = OnWebsocketConnected(wsi, user, in, len);
		break;
	case LWS_CALLBACK_RECEIVE:
		/* Recive data from client */
		ret = OnWebsocketRecive(wsi, user, in, len);
		break;
	case LWS_CALLBACK_SERVER_WRITEABLE:
		/* We can write to client now */
		ret = OnWebsocketWriteable(wsi, user, in, len);
		break;
	case LWS_CALLBACK_CLOSED:
		/* Connection closed */
		ret = OnWebsocketClose(wsi, user, in, len);
		break;

	default:
		break;
	}

	return ret;
}`

and print as:
![image](https://user-images.githubusercontent.com/35286167/62944240-d5f60300-be0e-11e9-94c1-27892f53a395.png)

**Comment by lws-team** [comment]
I just tried minimal-http-server-form-get and it works fine.

I also tried the mirror plugin and the test server, this also worked fine (http://127.0.0.1:7681/?mirror=xxxx prints

```
[2019/08/13 14:39:51:4297] N: Created new mi 0x8af2d0 'xxxx'
```
... this is literally done from the ESTABLISHED callback.  So I think no problem (this was on master).

**Comment by seamusmore** [comment]
I think it's because of the difference between http-server and websocket-server. I use ws:// protocol to connect server but you use http protocol. The http header will be dropped after handshake.

**Comment by lws-team** [comment]
No... it's not dropped until after the ESTABLISHED callback.

a and b will be in `.frags` if they are there.

Please try the test server and the same mirror url I tried earlier, and look at the logs.

**Comment by seamusmore** [comment]
I viewed the minimal-http-server-form-get example, and found the usage of the function lws_get_urlarg_by_name() is different from what I do in my code. Now I can get parameters from http header. Thanks very much!

**Comment by seamusmore** [comment]
The usage is :
`uint8_t buf[LWS_PRE + LWS_RECOMMENDED_MIN_HEADER_SPACE];
const char *val= lws_get_urlarg_by_name(wsi, "a", (char *)buf, sizeof(buf));`

but in my code I consider the return value 'val' is the parameter.
