### ISSUE TITLE
question: sometimes my client receives both -  previous and new one messages catted into one message, what could be wrong?

### ISSUE THREAD

**Issue by maxoodf** [warmcat/libwebsockets#1659]
server side, sent messages (LWS_CALLBACK_SERVER_WRITEABLE callback):
#1: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2868 typ srflx raddr x.x.x.x rport 60322 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":0,"sdpMid":"0"}}
#2: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2820 typ srflx raddr x.x.x.x rport 50272 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":1,"sdpMid":"1"}}
#3: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2934 typ srflx raddr x.x.x.x rport 49199 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":2,"sdpMid":"2"}}

client side, received messages (LWS_CALLBACK_RECEIVE):
#1: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2868 typ srflx raddr x.x.x.x rport 60322 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":0,"sdpMid":"0"}}
#2: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2924 typ srflx raddr x.x.x.x rport 49199 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":2,"sdpMid":"2"}}
#3: {"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2924 typ srflx raddr x.x.x.x rport 49199 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":2,"sdpMid":"2"}}{"candidate":{"candidate":"candidate:842163049 1 udp 1677729535 x.x.x.x 2819 typ srflx raddr x.x.x.x rport 50272 generation 0 ufrag jLPf network-cost 999","sdpMLineIndex":1,"sdpMid":"1"}}

You can see my server sent messages 1, 2 and 3. Client received messages 1, 3 and 3+2
I use v3.2.0 tag of libwebsockets

**Comment by lws-team** [comment]
This is udp?  This kind of thing should be completely expected if so.

**Comment by maxoodf** [comment]
No, TCP. 
```
$ netstat -lp | grep 8888
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      5085/./prxwss
```
I can reproduce this behaviour on Linux (Ubuntu 18.04) and MacOS (10.14). I think something is wrong with my code, but it's clear from my log - sent 1-2-3, received 1-3-3&2 (randomly)

Server:
```
    case LWS_CALLBACK_SERVER_WRITEABLE: {
        try {
            ...
            std::vector<unsigned char> buf = std::move(...);

            wsServer->m_logger->log(prx::logger_t::LL_DEBUG,
                                    "write: client {:p}, message: {:s}, size {:d}",
                                    fmt::ptr(_lws),
                                    std::string(reinterpret_cast<char *>(buf.data()), buf.size()),
                                    buf.size());

            if (lws_write(_lws, buf.data(), buf.size(), LWS_WRITE_TEXT) < 0) {
                wsServer->m_logger->log(prx::logger_t::LL_WARNING,
                                        "write: client {:p}, failed",
                                        fmt::ptr(_lws));
                return -1;
            }
        } catch (...) {
            wsServer->m_logger->log(prx::logger_t::LL_ERROR,
                                    "write: client {:p}, failed (out of memory?)",
                                    fmt::ptr(_lws));
            return -1;
        }

        break;
    }
```

Client:
```
        case LWS_CALLBACK_CLIENT_RECEIVE: {
            wsClient->m_logger->log(prx::logger_t::LL_DEBUG,
                                    "cbService: message received - {:s}, size: {:d}, remaining size: {:d}",
                                    std::string(static_cast<char *>(_data), _size),
                                    _size,
                                    lws_remaining_packet_payload(_wsi));

            wsClient->m_readBuf.insert(wsClient->m_readBuf.end(),
                                     static_cast<char *>(_data),
                                     static_cast<char *>(_data) + _size);

            // is it final part of message?
            if (!lws_is_final_fragment(_wsi) || (lws_remaining_packet_payload(_wsi) > 0)) {
                return 0; // no - wait for more data
            }
        }
```

**Comment by lws-team** [comment]
Mm I never know what C++ is doing just from looking at it.

What are the lengths of the RX in the three cases, at the callback?

**Comment by maxoodf** [comment]
>Mm I never know what C++ is doing just from looking at it.

**Comment by maxoodf** [comment]
>Mm I never know what C++ is doing just from looking at it.

` wsServer->m_logger->log()` logs exactly what is passed to `lws_write()` on the server side and ` wsClient->m_logger->log()` logs client's received data in the callback.

>What are the lengths of the RX in the three cases, at the callback?

64*1024. I tried 4 * 1024 with the same result

**Comment by lws-team** [comment]
I mean with C++, any operator can have side-effects.  So coming at it fresh, you have no idea what the code really does.

> 64*1024

These are more than one packet for a typical network interface... what happens if you dump the len argument of the callback for the rx, what does it actually say?

When you said

> Client received messages 1, 3 and 3+2

What does it actually mean?  You get 2 x RX with length 64K,  and then a third that says 128K?  I am talking about the RX callback's idea of lengths, not your code's idea of lengths.

**Comment by lws-team** [comment]
... also with these large sizes, if you're really talking about single packets like that on lo or whatever, you might want to run your stuff under valgrind.

**Comment by maxoodf** [comment]
>I mean with C++, any operator can have side-effects. So coming at it fresh, you have no idea what the code really does.

do not think so

>These are more than one packet for a typical network interface... what happens if you dump the len argument of the callback for the rx, what does it actually say?

I am trying to play with rx sizes...

>What does it actually mean? You get 2 x RX with length 64K, and then a third that says 128K?
No, I get message #1 (170-180 bytes), then #2 (170-180 bytes) and then I get message #3&#2 (~350 bytes)

**Comment by maxoodf** [comment]
the problem was an incorrect memory allocation, my mistake.
