### ISSUE TITLE
what is the command to download  (LWS_LIBRARY_VERSION "3.1.99" ) version. I want this version only. 

### ISSUE THREAD

**Issue by KabeerSadiq123** [warmcat/libwebsockets#1660]

**Comment by lws-team** [comment]
"3.1.99" was the version master reported after 3.1 was released and before v3.2 was released a few days ago.  So there are like a hundred or whatever trees that would tell you they are 3.1.99.  Today master tells you it's 3.2.99.

Master doesn't try to keep a coherent history either.  So even if you find the hash of the tree you want to duplicate's HEAD, there's no guarantee lws git stuff has it.  But at least if you work from the git HEAD (do `git log -n 1` on the original tree and look at the hex number) you stand a chance.

Clone master and try `git reset --hard XXXXX` where XXXXX is the hex hash from the other tree you found above.

**Comment by KabeerSadiq123** [comment]
Oky, thanks.
Is there any specific command from which I can clone 3.2 version always, not the master?

**Comment by lws-team** [comment]
When you do `git clone`, you are getting all versions.  By default it shows you current master.

You can use `git checkout` to pick what you want to see in your directory, eg, `git checkout v3.2.0`.

Use `git tag` to see what tags are available, and `git branch -a` to see what branches are around.

**Comment by KabeerSadiq123** [comment]
Oky , thanks a lot.
