### ISSUE TITLE
error on building with openssl 1.1.1c 

### ISSUE THREAD

**Issue by ananclub** [warmcat/libwebsockets#1662]
In file included from /home/anan/project/libwebsockets/include/libwebsockets.h:583:0,
                 from /home/anan/project/libwebsockets/lib/core/private-lib-core.h:133,
                 from /home/anan/project/libwebsockets/lib/core/alloc.c:1:
/home/anan/project/libwebsockets/include/libwebsockets/lws-genhash.h:80:18: error: field ‘ctx’ has incomplete type
         HMAC_CTX ctx;
                  ^
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2

**Comment by lws-team** [comment]
Actually lws is developed on Fedora, which is on 1.1.1c at the moment, and no problem here.

To cope with the api whiplashing around in OpenSSL, lws does a bunch of tests at CMake-time to discover which apis are available in the openssl it has been given, and adapt to use the latest available apis for what it has.  For example in that particular failing code

```
#if defined(LWS_HAVE_HMAC_CTX_new)
        HMAC_CTX *ctx;
#else
        HMAC_CTX ctx;
#endif
```

HMAC_CTX is opaque in some versions of OpenSSL and defined publicly in others... this problem seems to be about a mismatch between the CMake test results the build is using and the reality of the OpenSSL version headers the actual compile is seeing.

Try deleting ./build/CMakeCache.txt and rebuild, if that doesn't help, paste the results of the CMake after deleting ./build/CMakeCache.txt so we can see how it goes with the api testing.

**Comment by ananclub** [comment]
> Actually lws is developed on Fedora, which is on 1.1.1c at the moment, and no problem here.
> 
> To cope with the api whiplashing around in OpenSSL, lws does a bunch of tests at CMake-time to discover which apis are available in the openssl it has been given, and adapt to use the latest available apis for what it has. For example in that particular failing code
> 
> ```
> #if defined(LWS_HAVE_HMAC_CTX_new)
>         HMAC_CTX *ctx;
> #else
>         HMAC_CTX ctx;
> #endif
> ```
> 
> HMAC_CTX is opaque in some versions of OpenSSL and defined publicly in others... this problem seems to be about a mismatch between the CMake test results the build is using and the reality of the OpenSSL version headers the actual compile is seeing.
> 
> Try deleting ./build/CMakeCache.txt and rebuild, if that doesn't help, paste the results of the CMake after deleting ./build/CMakeCache.txt so we can see how it goes with the api testing.

[anan@dev build]$ cmake -DLWS_WITH_STATIC=1 -DLWS_WITH_SHARED=0 -DLWS_STATIC_PIC=1 ..
-- Compiled with LWS_WITH_DIR and LWS_WITH_DIR
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE=''
-- Found Git: /usr/bin/git
Git commit hash: v3.1.0-285-g772ce12
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Success
-- Performing Test LWS_HAVE___inline__
-- Performing Test LWS_HAVE___inline__ - Success
-- Performing Test LWS_HAVE___inline
-- Performing Test LWS_HAVE___inline - Success
-- Performing Test LWS_HAVE_MALLOC_TRIM
-- Performing Test LWS_HAVE_MALLOC_TRIM - Success
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE - Success
-- Looking for fork
-- Looking for fork - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for execvpe
-- Looking for execvpe - found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for getloadavg
-- Looking for getloadavg - found
-- Looking for atoll
-- Looking for atoll - found
-- Looking for _atoi64
-- Looking for _atoi64 - not found
-- Looking for _stat32i64
-- Looking for _stat32i64 - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for in6addr.h
-- Looking for in6addr.h - not found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for sys/capability.h
-- Looking for sys/capability.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for cap_set_flag in cap
-- Looking for cap_set_flag in cap - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Performing Test LWS_HAS_INTPTR_T
-- Performing Test LWS_HAS_INTPTR_T - Success
-- Performing Test LWS_HAS_PTHREAD_SETNAME_NP
-- Performing Test LWS_HAS_PTHREAD_SETNAME_NP - Success
-- Performing Test LWS_HAS_GETOPT_LONG
-- Performing Test LWS_HAS_GETOPT_LONG - Success
-- Performing Test LWS_HAVE_VISIBILITY
-- Performing Test LWS_HAVE_VISIBILITY - Success
-- Performing Test LWS_GCC_HAS_IGNORED_QUALIFIERS
-- Performing Test LWS_GCC_HAS_IGNORED_QUALIFIERS - Success
-- Performing Test LWS_GCC_HAS_TYPE_LIMITS
-- Performing Test LWS_GCC_HAS_TYPE_LIMITS - Success
Compiling with SSL support
-- Found OpenSSL: /usr/local/lib64/libcrypto.a (found version "1.1.1c")
OpenSSL include dir: /usr/local/include
OpenSSL libraries: /usr/local/lib64/libssl.a;/usr/local/lib64/libcrypto.a
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for EVP_PKEY_new_raw_private_key
-- Looking for EVP_PKEY_new_raw_private_key - not found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - not found
-- Looking for SSL_get0_alpn_selected
-- Looking for SSL_get0_alpn_selected - not found
-- Looking for SSL_set_alpn_protos
-- Looking for SSL_set_alpn_protos - not found
-- Looking for EVP_aes_128_cfb8
-- Looking for EVP_aes_128_cfb8 - not found
-- Looking for EVP_aes_128_cfb128
-- Looking for EVP_aes_128_cfb128 - not found
-- Looking for EVP_aes_192_cfb8
-- Looking for EVP_aes_192_cfb8 - not found
-- Looking for EVP_aes_192_cfb128
-- Looking for EVP_aes_192_cfb128 - not found
-- Looking for EVP_aes_256_cfb8
-- Looking for EVP_aes_256_cfb8 - not found
-- Looking for EVP_aes_256_cfb128
-- Looking for EVP_aes_256_cfb128 - not found
-- Looking for EVP_aes_128_xts
-- Looking for EVP_aes_128_xts - not found
-- Looking for RSA_verify_pss_mgf1
-- Looking for RSA_verify_pss_mgf1 - not found
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found
-- Looking for SSL_CTX_set_ciphersuites
-- Looking for SSL_CTX_set_ciphersuites - not found
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_EXTENSIONS = ON
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_WITH_LIBEV = OFF
 LWS_WITH_LIBUV = OFF
 LWS_WITH_LIBEVENT = OFF
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = 1
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 1
 LWS_HAVE_PTHREAD_H = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_HAVE_SSL_CTX_set1_param =
 LWS_HAVE_RSA_SET0_KEY =
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES =
 PLUGINS =
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
 LWS_WITH_LEJP = ON
 LWS_WITH_LEJP_CONF = ON
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = 1
 LWS_WITH_RANGES = OFF
 LWS_PLAT_OPTEE = OFF
 LWS_PLAT_FREERTOS = OFF
 LWS_WITH_ZIP_FOPS = OFF
 LWS_AVOID_SIGPIPE_IGN = OFF LWS_WITH_STATS = OFF
 LWS_WITH_SOCKS5 = OFF
 LWS_HAVE_SYS_CAPABILITY_H =
 LWS_HAVE_LIBCAP =
 LWS_WITH_PEER_LIMITS = OFF
 LWS_HAVE_ATOLL = 1
 LWS_HAVE__ATOI64 =
 LWS_HAVE_STAT32I64 =
 LWS_HAS_INTPTR_T = 1
 LWS_WITH_EXPORT_LWSTARGETS = ON
 LWS_WITH_ABSTRACT =
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anan/project/libwebsockets/build
[anan@dev build]$ make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
In file included from /home/anan/project/libwebsockets/include/libwebsockets.h:583:0,
                 from /home/anan/project/libwebsockets/lib/core/private-lib-core.h:133,
                 from /home/anan/project/libwebsockets/lib/core/alloc.c:1:
/home/anan/project/libwebsockets/include/libwebsockets/lws-genhash.h:80:18: error: field ‘ctx’ has incomplete type
         HMAC_CTX ctx;
                  ^
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2

**Comment by lws-team** [comment]
It believes you don't have `HMAC_CTX_new()` that indicates HMAC_CTX is opaque now.

```
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found
```

Is it perhaps finding an older `/usr/include/openssl/...` which really doesn't have it instead of your `/usr/local` one that does?  Have a look through READMEs/README.build.md for ways to guide it to your headers.

**Comment by ananclub** [comment]
Compiling with SSL support
-- Found OpenSSL: /usr/local/lib64/libcrypto.a (found version "1.1.1c")
OpenSSL include dir: /usr/local/include
OpenSSL libraries: /usr/local/lib64/libssl.a;/usr/local/lib64/libcrypto.a


openssl has detected,but not work.
I'll do more check, thanks.

**Comment by ananclub** [comment]
Check the CMakeError.log find like this error:

Determining if the function HMAC_CTX_new exists failed with the following output:
Change Dir: /home/anan/project/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_cba7d/fast && /usr/bin/gmake -f CMakeFiles/cmTC_cba7d.dir/build.make CMakeFiles/cmTC_cba7d.dir/build
gmake[1]: Entering directory `/home/anan/project/libwebsockets/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cba7d.dir/CheckFunctionExists.c.o
/usr/bin/cc -DKEYWORD=__inline  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers   -pthread -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -pthread -fPIE   -o CMakeFiles/cmTC_cba7d.dir/CheckFunctionExists.c.o   -c /data/cmake/share/cmake-3.15/Modules/CheckFunctionExists.c
Linking C executable cmTC_cba7d
/data/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cba7d.dir/link.txt --verbose=1
/usr/bin/cc -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers   -pthread -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -pthread    -rdynamic CMakeFiles/cmTC_cba7d.dir/CheckFunctionExists.c.o  -o cmTC_cba7d -lssl -lcrypto -lm 
//usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
//usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x334): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3f2): undefined reference to `dlerror'
//usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x461): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x4d9): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x512): undefined reference to `dlerror'
//usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x5b1): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x611): undefined reference to `dlerror'
//usr/local/lib64/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x672): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_cba7d] Error 1
gmake[1]: Leaving directory `/home/anan/project/libwebsockets/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_cba7d/fast] Error 2


adding "list(APPEND LIB_LIST dl)" manual，then it resolved。

**Comment by lws-team** [comment]
Whoa.. nice find.

I added it with some if (UNIX) protection... there was already something similar a few lines past that.  Thanks for sharing your findings.

**Comment by vaind** [comment]
This is (still/again?) broken in the current release, 3.2.1 which came out after the commit. Any plans for a release?

**Comment by vaind** [comment]
Actually, even the current master has this wrong, it appends to `LIB_LIST` after `CMAKE_REQUIRED_LIBRARIES` has been set from it so it still won't work. Block at line 1963 needs to move to 1950

**Comment by lws-team** [comment]
Thanks, I updated master with that and backported it to v3.2-stable.

I added a tag v3.2.2... although people should better follow vx.y-stable since whatever reason any patch wants a tag applies to any patch on there.

**Comment by 19504643** [comment]
I'm building V3.2.2 using openssl1.1.0 on mingw windows, but still not founding **HMAC_CTX_new**, all the libraries paths are correct
$ cmake -DLWS_WITH_HTTP2=1 -DLWS_WITHOUT_TESTAPPS=1 -DLWS_WITH_SHARED=0 -DLWS_WITH_LWSWS=1 -DOPENSSL_LIBRARIES=/F/api/library/libopenssl/lib/libssl.a  -DLWS_OPENSSL_LIBRARIES=/F/api/library/libopenssl/lib/libssl.a -DLWS_OPENSSL_INCLUDE_DIRS=/F/api/library/libopenssl/include -DLIBUV_LIBRARIES=/F/api/library/libuv-1.19.2/lib/libuv.a -DLIBUV_INCLUDE_DIRS=/F/api/library/libuv-1.19.2/include -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=D:/MinGW ..
$ make
![image](https://user-images.githubusercontent.com/4372492/77218436-46fc5680-6b66-11ea-8046-bd70ea16eac4.png)

**Comment by lws-team** [comment]
You need to look into `./build/CMakeFiles/CMakeError.log` and look for the last match for "HMAC_CTX_new" to find out what happened when cmake tried to compile a little test program trying to use that api to discover if it existed or not.  Please paste the section here.

**Comment by 19504643** [comment]
@lws-team 

openssl is static library, is there something wrong with it?
two files in openssl come with this error:
**t1_lib.c
statem_srvr.c**

F:/api/library/libopenssl/lib/libssl.a(t1_lib.o):t1_lib.c:(.text+0x23ed): undefined reference to `HMAC_CTX_new'

F:/api/library/libopenssl/lib/libssl.a(statem_srvr.o):statem_srvr.c:(.text+0x1616): undefined reference to `EVP_CIPHER_CTX_new'

F:/api/library/libopenssl/lib/libssl.a(statem_srvr.o):statem_srvr.c:(.text+0x161f): undefined reference to `HMAC_CTX_new'

F:/api/library/libopenssl/lib/libssl.a(statem_srvr.o):statem_srvr.c:(.text+0x16ad): undefined reference to `CRYPTO_free'

F:/api/library/libopenssl/lib/libssl.a(statem_srvr.o):statem_srvr.c:(.text+0x16b9): undefined reference to `EVP_CIPHER_CTX_free'

F:/api/library/libopenssl/lib/libssl.a(statem_srvr.o):statem_srvr.c:(.text+0x16c5): undefined reference to `HMAC_CTX_free'

**Comment by lws-team** [comment]
This isn't coming out of `./build/CMakeFiles/CMakeError.log`, right?

Are you also linking `libcrypto.a`?  Openssl is in two libraries not just one.

**Comment by 19504643** [comment]
It's exactly coming from ./build/CMakeFiles/CMakeError.log
yes, static openssl library are two files called libssl.a and libcrypto.a, but how can I add it to commands, it just can include one path 
-DOPENSSL_LIBRARIES=/F/api/library/libopenssl/lib/libssl.a
how to add it, tks

**Comment by lws-team** [comment]
This kind of thing

```
    cmake .. -DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/include/openssl -DLWS_OPENSSL_LIBRARIES="/usr/local/lib64/libssl.so;/usr/local/lib64/libcrypto.so"
```

**Comment by 19504643** [comment]
`-DLWS_OPENSSL_LIBRARIES="F:/api/library/libopenssl/lib/libssl.a;F:/api/library/libopenssl/lib/libcrypto.a" `

still the error, and all of functions can not be found

```
Compiling with SSL support
OpenSSL include dir: F:/api/library/libopenssl/include
OpenSSL libraries: F:/api/library/libopenssl/lib/libssl.a;F:/api/library/libopen
ssl/lib/libcrypto.a
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
libuv include dir: F:/api/library/libuv-1.19.2/include
libuv libraries: F:/api/library/libuv-1.19.2/lib/libuv.a
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for EVP_PKEY_new_raw_private_key
-- Looking for EVP_PKEY_new_raw_private_key - not found
```

**Comment by lws-team** [comment]
The reason in the ./build/CMakeFiles/CMakeError.log is the same?  This is appended to, you have you look at the end of the file to see the most recent results.

If so please list where your mingw came from and I'll try it myself on windows.

**Comment by 19504643** [comment]
my mingw env comes from http://sourceforge.net/projects/mingw/files

and now, the CMakeError log is
```
/D/MinGW/bin/gcc.exe -DKEYWORD=__inline @CMakeFiles/cmTC_eab9e.dir/includes_C.rsp -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden  -Wtype-limits -Wignored-qualifiers -D__USE_MINGW_ANSI_STDIO  -DLWS_HAVE_PIPE2   -o CMakeFiles/cmTC_eab9e.dir/src.c.obj   -c /F/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp/src.c
f:/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp/src.c: In function 'main':

f:/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp/src.c:4:9: error: implicit declaration of function 'pipe2' [-Werror=implicit-function-declaration]

  return pipe2(fd, 0);

         ^~~~~

cc1.exe: all warnings being treated as errors

make[1]: *** [CMakeFiles/cmTC_eab9e.dir/src.c.obj] Error 1
make[1]: Leaving directory `/f/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp'
make: *** [cmTC_eab9e/fast] Error 2


Source file was:
#define _GNU_SOURCE
#include <unistd.h>
int main(void) {int fd[2];
 return pipe2(fd, 0);
}

Performing C SOURCE FILE Test LWS_HAVE_TCP_USER_TIMEOUT failed with the following output:
Change Dir: F:/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/MinGW/msys/1.0/bin/make.exe cmTC_930e7/fast && /usr/bin/make -f CMakeFiles/cmTC_930e7.dir/build.make CMakeFiles/cmTC_930e7.dir/build
make[1]: Entering directory `/f/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_930e7.dir/src.c.obj

/D/MinGW/bin/gcc.exe -DKEYWORD=__inline @CMakeFiles/cmTC_930e7.dir/includes_C.rsp -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden  -Wtype-limits -Wignored-qualifiers -D__USE_MINGW_ANSI_STDIO  -DLWS_HAVE_TCP_USER_TIMEOUT   -o CMakeFiles/cmTC_930e7.dir/src.c.obj   -c /F/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp/src.c
f:/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp/src.c:1:25: fatal error: netinet/tcp.h: No such file or directory

 #include <netinet/tcp.h>

                         ^

compilation terminated.

make[1]: *** [CMakeFiles/cmTC_930e7.dir/src.c.obj] Error 1
make[1]: Leaving directory `/f/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp'
make: *** [cmTC_930e7/fast] Error 2


Source file was:
#include <netinet/tcp.h>
int main(void) { return TCP_USER_TIMEOUT; }


```

**Comment by lws-team** [comment]
Pipe2 doesn't exist on windows, it is not an error. You need to check the last entry in the error file for HMAC_CTX_new specifically.

**Comment by 19504643** [comment]
oh, got it, great thanks, is my openssl broken? how to solve it

```
Determining if the function **### HMAC_CTX_new** exists failed with the following output:
Change Dir: F:/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/MinGW/msys/1.0/bin/make.exe cmTC_730b5/fast && /usr/bin/make -f CMakeFiles/cmTC_730b5.dir/build.make CMakeFiles/cmTC_730b5.dir/build
make[1]: Entering directory `/f/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_730b5.dir/CheckFunctionExists.c.obj

/D/MinGW/bin/gcc.exe -DKEYWORD=__inline @CMakeFiles/cmTC_730b5.dir/includes_C.rsp -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden  -Wtype-limits -Wignored-qualifiers -D__USE_MINGW_ANSI_STDIO  -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new   -o CMakeFiles/cmTC_730b5.dir/CheckFunctionExists.c.obj   -c "/D/Program Files/CMake/share/cmake-3.15/Modules/CheckFunctionExists.c"
Linking C executable cmTC_730b5.exe

"/D/Program Files/CMake/bin/cmake.exe" -E remove -f CMakeFiles/cmTC_730b5.dir/objects.a
/D/MinGW/bin/ar.exe cr CMakeFiles/cmTC_730b5.dir/objects.a @CMakeFiles/cmTC_730b5.dir/objects1.rsp
/D/MinGW/bin/gcc.exe -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden  -Wtype-limits -Wignored-qualifiers -D__USE_MINGW_ANSI_STDIO  -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new    -Wl,--whole-archive CMakeFiles/cmTC_730b5.dir/objects.a -Wl,--no-whole-archive  -o cmTC_730b5.exe -Wl,--out-implib,libcmTC_730b5.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/cmTC_730b5.dir/linklibs.rsp
F:/api/library/libopenssl/lib/libcrypto.a(init.o):init.c:(.text+0x1b3): undefined reference to `GetModuleHandleEx'

F:/api/library/libopenssl/lib/libcrypto.a(init.o):init.c:(.text+0xb64): undefined reference to `GetModuleHandleEx'

F:/api/library/libopenssl/lib/libcrypto.a(b_addr.o):b_addr.c:(.text+0xa9): undefined reference to `getnameinfo'

F:/api/library/libopenssl/lib/libcrypto.a(b_addr.o):b_addr.c:(.text+0xbac): undefined reference to `getaddrinfo'

F:/api/library/libopenssl/lib/libcrypto.a(b_addr.o):b_addr.c:(.text+0xd44): undefined reference to `getaddrinfo'

F:/api/library/libopenssl/lib/libcrypto.a(b_addr.o):b_addr.c:(.text+0x869): undefined reference to `freeaddrinfo'

collect2.exe: error: ld returned 1 exit status

make[1]: *** [cmTC_730b5.exe] Error 1
make[1]: Leaving directory `/f/api/library/libwebsockets-3.2.2/build/CMakeFiles/CMakeTmp'
make: *** [cmTC_730b5/fast] Error 2
```

**Comment by lws-team** [comment]
Looks like some kind of toolchain problem, link against libc that provides getaddrinfo() should be implicit.  GetModuleHandleEx() I dunno but I think on windows link against system32.dll or whatever it is is also supposed to be implicit.

At any rate I don't think this is an lws issue.
