### ISSUE TITLE
some way to close the client connection

### ISSUE THREAD

**Issue by Rey1023** [warmcat/libwebsockets#1671]
dear sir,
Is there some way to close the connection from websocket server, sometime I want to force close the connection from the server(the client is sending data to server,but I want to close the connection).
thanks

**Comment by Rey1023** [comment]
I return -1 when the server received the data from the client, then the connection was closed, but I don't know whether or not I get the right way.

**Comment by lws-team** [comment]
Returning -1 from most callbacks is a good way.

In the case you decide you want to close the wsi when the decision isn't made from a network event, another way is you can close wsi like this (usually you want the ASYNC one)

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n77

These aren't threadsafe.

**Comment by Rey1023** [comment]
thank you  for your relay sir.
