### ISSUE TITLE
Max connections set

### ISSUE THREAD

**Issue by Rey1023** [warmcat/libwebsockets#1673]
hello sir:
     Is there any apis can set the max connetions of the client in the libwebsockets? I have search the api that I can ,but I can't find any api can set。

**Comment by lws-team** [comment]
Depends what you mean... if you are writing a server, by default lws allows as many client connection fds to be used as your process ulimit -n, typically 1024 on Linux by default.

For the client case where you only want to make one or a handful of client connections, you can use a more memory-efficient fd tracking scheme optimized for small numbers of fds by setting the max fd count you expect to use at context creation time

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n140
