### ISSUE TITLE
error in http/client building 3.2 "error: assignment of read-only location '*cce'"

### ISSUE THREAD

**Issue by nullr0ute** [warmcat/libwebsockets#1676]
When building 3.2 on Fedora 32 with gcc 9.2 and various hardening flags I get the folliwing build error:

<pre>
[ 47%] Building C object CMakeFiles/websockets_shared.dir/lib/roles/http/client/client.c.o
/usr/bin/cc -Dwebsockets_shared_EXPORTS -I/builddir/build/BUILD/libwebsockets-3.2.0/include -I/builddir/build/BUILD/libwebsockets-3.2.0/plugins -I/builddir/build/BUILD/libwebsockets-3.2.0/build -I/builddir/build/BUILD/libwebsockets-3.2.0/lib  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -DNDEBUG -fPIC   -o CMakeFiles/websockets_shared.dir/lib/roles/http/client/client.c.o   -c /builddir/build/BUILD/libwebsockets-3.2.0/lib/roles/http/client/client.c
make[2]: Leaving directory '/builddir/build/BUILD/libwebsockets-3.2.0/build'
BUILDSTDERR: /builddir/build/BUILD/libwebsockets-3.2.0/lib/roles/http/client/client.c: In function 'lws_client_socket_service':
BUILDSTDERR: /builddir/build/BUILD/libwebsockets-3.2.0/lib/roles/http/client/client.c:217:10: error: assignment of read-only location '*cce'
BUILDSTDERR:   217 |     *cce = "socks gen msg fail";
BUILDSTDERR:       |          ^
BUILDSTDERR: make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:612: CMakeFiles/websockets_shared.dir/lib/roles/http/client/client.c.o] Error 1
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/builddir/build/BUILD/libwebsockets-3.2.0/build'
</pre>

**Comment by lws-team** [comment]
This was fixed 8 days ago on v3.2-stable...

https://libwebsockets.org/git/libwebsockets/commit?id=aefecce938926d2794a82dab85e0f4a531ddcf70

...v3.2.0 is a tag, it's immutable once it's out there.  It's like saying "last monday was a rough day", it's in the past and it was whatever it was.  Use the -stable branches rather than tags.  And help me test master so we catch these things before they're tagged out.

**Comment by nullr0ute** [comment]
> ...v3.2.0 is a tag, it's immutable once it's out there. It's like saying "last monday was a rough day", it's in the past and it was whatever it was. Use the -stable branches rather than tags. And help me test master so we catch these things before they're tagged out.

I do understand how tagging works, it also provides distros with a stable means of providing the same thing across all distros so upstream can also see where the distros are without having to work out exactly where distros took a random snapshot along the time line. Maybe more tagged z releases would be useful, tags are cheap. It would give distros something more than a release ever ~8 months.

**Comment by lws-team** [comment]
I take your point.

But still, you reported a build error (it depends on SOCKS5 enabled IIRC which is why it made it through) in a tag.  All I can do about that is add a fix on the -stable branch.

**Comment by lws-team** [comment]
... on the -stable branches, after a patch has been out there for more than a few minutes I won't rewrite it as I commonly do on master.  So you are safe to repeatably identify any commit by hashes on these branches.  That should solve your problem.
