### ISSUE TITLE
was anyone actually able to connect to SSL websocket server ?

### ISSUE THREAD

**Issue by rottor12** [warmcat/libwebsockets#168]
I'm trying to establish a connection to a SSL websocket service

I'm trying to accept whatever certificate server sends to me ... I just want to connect regardless of certificate

I'm always getting SSL verification errors like:
21 X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE
or 27 X509_V_ERR_CERT_UNTRUSTED

here is my SSL client verify callback:
case LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS:
		SSL_CTX_set_verify_depth( (SSL_CTX *)user , 0); // when depth is set to 0 error is 21, when depth is 1 error is 27
		SSL_CTX_set_verify( (SSL_CTX *)user, SSL_VERIFY_NONE, mySSL_verify_callback);
                break;

and my verification callback which always returns 1:

static int mySSL_verify_callback(int preverify_ok, X509_STORE_CTX *ctx)
{
	return 1;
}

and I'm still getting SSL verification error

what do I need to do to connect to SSL websocket (ignoring the certificate)

**Comment by Wadimir** [comment]
I have this problem too:

[11907314380:3613] NOTICE: Initial logging level 7
[11907314380:3613] NOTICE: Library version: 1.3 unknown-build-hash
[11907314380:3613] NOTICE: IPV6 not compiled in
[11907314380:3613] NOTICE: libev support not compiled in
[11907314380:3613] NOTICE:  static allocation: 4736 + (12 x 30000 fds) = 364736 bytes
[11907314380:3633] NOTICE:  canonical_hostname = VIW00112
[11907314380:3633] NOTICE:  per-conn mem: 192 + 2140 headers + protocol rx buf
[11907314381:4964] ERR: server's cert didn't look good, X509_V_ERR = 20: error:00000014:lib(0):func(0):SSL lib
[11907314381:5464] NOTICE: libwebsocket_context_destroy

**Comment by warmcat** [comment]
Well... 

1)what server are you connecting to and what kind of cert does it have?

2) Does the test server work OK with his selfsigned certs?

SSL is supposed to reject certs he doesn't like, it is not necessarily a bug.

**Comment by VictorLaskin** [comment]
Got the same error with nginx forwarding... May be it would be nice to make 3 as ssl parameter to accept everything here:

    if ((n == X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT ||
    				     n == X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN) && wsi->use_ssl == 2)    {
    					lwsl_notice("accepting self-signed certificate\n");
    				} else {
    					lwsl_err("server's cert didn't look good, X509_V_ERR = %d: %s\n",
    						 n, ERR_error_string(n, (char *)context->service_buffer));
    					libwebsocket_close_and_free_session(context,
    							wsi, LWS_CLOSE_STATUS_NOSTATUS);
    					return 0;
    				}

**Comment by JonTerp** [comment]
Getting this as well. Can connect to a self signed WSS echo server just fine with use_ssl = 2 on connect.

However when connecting to another server with an actual SSL cert, I always get Error 20 even with `LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK | LCCSCF_ALLOW_EXPIRED all defined.`

**Comment by lws-team** [comment]
Eh.... this original bug was about server cert verification.  Are you sure you mean "client certs"?  You seem confused.

On current master, I just did

```
 $ libwebsockets-test-client https://warmcat.com
```

which uses a "real" server cert signed by a official CA intermediate cert.... it works no problem.

You have to have the cert CA bundle and anything else needed to validate the server cert, or it will be rejected (that is the whole idea, right?)

And you should look at the logs as to what ilws feels is happening, preferably on master.

**Comment by ab1jx** [comment]
I just did
libwebsockets-test-echo https://api.bitfinex.com/v1/pubticker
and it works.  On a Raspberry Pi with libwebsockets from the standard Raspbian debs.  SSL is a PITA.  Libwebsockets could use more documentation, I'm working from the headers and Googling.  The deb just didn't include much, I guess I was hoping for more working examples.  Cloning the git site is a little better.

**Comment by georgeh200** [comment]
Hi
workin on libwebsockets client trying to connect to our secure websocket 
`use_ssl = LCCSCF_USE_SSL |
    LCCSCF_ALLOW_SELFSIGNED |
    LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;`

I get client connection error
ERR: SSL connect error 336134278: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

but when I connect to wss://echo.websocket.org , it works normally

**Comment by lws-team** [comment]
Do you still have

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c#L618

in your client code?

**Comment by georgeh200** [comment]
Hi 
Thanks for your reply

I have this line in my client code 
 i.ssl_connection = use_ssl;

**Comment by georgeh200** [comment]
more information about above issue
this happens only with IOS device/simulator

it works perfect on mac OSX , with same server and same code

**Comment by lws-team** [comment]
Mmmm this is probably related to your ios openssl being ancient...eg it may not support the crypto needed by your cert / any intermediate certs.  Someone had something similar where using a more recent openssl solved it.

**Comment by georgeh200** [comment]
I use openssl-1.0.2k
here is the log from xcode console 


[2017/04/21 13:23:15:1729] NOTICE: lws_ssl_client_connect2: SSL_connect says -1
[2017/04/21 13:23:15:1731] ERR: SSL connect error 336134278: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
[2017/04/21 13:23:15:1732] ERR: CLIENT_CONNECTION_ERROR: dumb: lws_ssl_client_connect2 failed

**Comment by georgeh200** [comment]
Hi any help in this
I included my root certficate and passed it to this callback


 case LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS:
           
             {
                char* crl_path = file;
                /* Enable CRL checking of the server certificate */
                X509_VERIFY_PARAM *param = X509_VERIFY_PARAM_new();
                X509_VERIFY_PARAM_set_flags(param, X509_V_FLAG_CRL_CHECK);
                SSL_CTX_set1_param((SSL_CTX*)user, param);
                X509_STORE *store = SSL_CTX_get_cert_store((SSL_CTX*)user);
                X509_LOOKUP *lookup = X509_STORE_add_lookup(store, X509_LOOKUP_file());
                int n = X509_load_cert_crl_file(lookup, crl_path, X509_FILETYPE_PEM);
                X509_VERIFY_PARAM_free(param);
               // n=1;
                if (n != 1) {
                    char errbuf[256];
                    n = ERR_get_error();
                    lwsl_err("LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS: SSL error: %s (%d)\n", ERR_error_string(n, errbuf), n);
                    return 1;
                }
            }
            break;


and still the same



 lws_ssl_client_connect2: SSL_connect says -1
[2017/04/24 10:33:26:8920] ERR: SSL error: unable to get issuer certificate (preverify_ok=0;err=2;depth=1)
[2017/04/24 10:33:26:8922] NOTICE: lws_ssl_client_connect2: SSL_connect says -1
[2017/04/24 10:33:26:8923] ERR: SSL connect error 336134278: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by lws-team** [comment]
CRL is Certificate Revocation List, you are aware of that, right?

**Comment by georgeh200** [comment]
Thanks so much for ur reply
after about 16 hours investigation, finally got SSL connection working between our server and IOS, I can say it's COMODO/IOS issue, 
I included the root certificate , and passed it like this
` case LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS:
           
             {
                char* crl_path = file; // path to root certifcate file
             
                /* Enable CRL checking of the server certificate */
                X509_VERIFY_PARAM *param = X509_VERIFY_PARAM_new();
                X509_VERIFY_PARAM_set_flags(param, X509_V_FLAG_TRUSTED_FIRST);
                SSL_CTX_set1_param((SSL_CTX*)user, param);
                X509_STORE *store = SSL_CTX_get_cert_store((SSL_CTX*)user);
                X509_LOOKUP *lookup = X509_STORE_add_lookup(store, X509_LOOKUP_file());
                int n = X509_load_cert_file(lookup, crl_path, X509_FILETYPE_PEM);
                X509_VERIFY_PARAM_free(param);
             
                if (n != 1) {
                    char errbuf[256];
                    n = ERR_get_error();
                    lwsl_err("LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS: SSL error: %s (%d)\n", ERR_error_string(n, errbuf), n);
                    return 1;
                }
            }
            break;`

**Comment by lws-team** [comment]
Well, glad you are working and thanks for documenting the working code here.
