### ISSUE TITLE
Change to lws_service() behaviour appears to be broken

### ISSUE THREAD

**Issue by ralight** [warmcat/libwebsockets#1683]
I've used lws_service(context, 0) for ages in a few situations where this makes sense for me. The changes in 3.2.0 stop this working, because the timeout is ignored.

Using lws_service(context, -1) doesn't work either, no connections ever happen if I do that. I can reproduce this behaviour using the test-server and test-client apps. They work in 3.1.0, but not in 3.2.0.

My preference would be to have control of the timeout back again, but if you're dead set against it then how about -1 and 0 both being allowed with their old meaning, and >0 meaning that lws controls the timeout.

**Comment by lws-team** [comment]
There's an additional patch needed to make this work properly with the event lib cases, it's on v3.2-stable and master now and has passed CI.  AFAIK that's it for this change.

**Comment by tsl0922** [comment]
Similar issue on ttyd: https://github.com/tsl0922/ttyd/issues/223, I will test the new patches.

**Comment by shufps** [comment]
lol ... `-1` 😳 It works, thx for it
