### ISSUE TITLE
Does application code need adaption after upgrading to 3.2.0?

### ISSUE THREAD

**Issue by ideal** [warmcat/libwebsockets#1685]
Using ttyd (https://github.com/tsl0922/ttyd), after upgrading libwebsockets to 3.2.0, there is a problem seems that somewhere stucked.

<img width="1195" alt="屏幕快照 2019-09-14 下午3 57 09" src="https://user-images.githubusercontent.com/261698/64905289-7b4f1000-d708-11e9-8681-16e24d54a91f.png">

Most time is in `poll()`. With strace:

![image](https://user-images.githubusercontent.com/261698/64905294-91f56700-d708-11e9-99d0-fbccd8a33e4d.png)

So it seems that even if there is nothing to read, it is still polling on POLLIN until timeouts. So I added `lws_callback_on_writable(wsi);` in LWS_CALLBACK_RECEIVE callback, but seems no effect. Still haven't find some example code about this in `test-apps`.

So does application code need some adaption after upgrading to 3.2.0?

**Comment by lws-team** [comment]
In 3.2+ lws stays in the poll wait unless there is something to do.  It no longer breaks the poll wait every second or so, it will stay in the poll wait literally for weeks if it can.  Things in lws that used to rely on these periodic wait breaks have all been updated to schedule events in the future, the api for that is exported so user code can use it as well.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

**Comment by ideal** [comment]
Thanks.
