### ISSUE TITLE
http client 302 reset wsi lost pre protocol info.

### ISSUE THREAD

**Issue by jackim** [warmcat/libwebsockets#1686]
in lws_client_reset fucntion:
 ```
wsi->desc.sockfd = LWS_SOCK_INVALID;
lwsi_set_state(wsi, LRS_UNCONNECTED);
wsi->protocol = NULL;
wsi->pending_timeout = NO_PENDING_TIMEOUT;
wsi->c_port = port;
wsi->hdr_parsing_completed = 0;
_lws_header_table_reset(wsi->http.ah);
```
wsi->protocol = NULL ; 
may will lost prev wsi's protocol.
because wsi->protocol is not equal wsi->vhost->protocols[0]	

```
	if (local) {
		lwsl_info("%s: protocol binding to %s\n", __func__, local);
		p = lws_vhost_name_to_protocol(wsi->vhost, local);
		if (p)
			lws_bind_protocol(wsi, p, __func__);
	}
```

this code is good:
 ```
wsi->protocol = (*pwsi)->protocol;
```

**Comment by lws-team** [comment]
On master that line is actually commented out already... I think what you suggested is actually a NOP since wsi is `*pwsi`... commenting that line on v3.2-stable would solve this for you?

**Comment by jackim** [comment]
thank you for reply so quickly . i used v3.1.99.
and i watch v3.2's code about protocol's info.
i think v3.2 will solve this for me.

**Comment by lws-team** [comment]
OK.  I pushed a patch on v3.2-stable that aligns it to what is in master for that (commented the line setting protocol to NULL).
