### ISSUE TITLE
is it possible to do a batch read in client

### ISSUE THREAD

**Issue by iofo** [warmcat/libwebsockets#1687]
Is it possible to determine upon receiving a web socket message as a client that there are bytes still readable on the socket so we may have another message immediately following so we can batch the incoming messages and process in one go rather than one at a time?

In Python I do it like this:

```
import asyncio

import traceback
import websockets

async def main():
    uri = "wss://api.gemini.com/v1/marketdata/{}".format("BTCUSD")
    print(uri)
    while True:
        try:
            async with websockets.connect(uri) as websocket:
                msgs = []
                while True:
                    try:
                        while True:
                            msg = await asyncio.wait_for(websocket.recv(),timeout=0)
                            msgs.append(msg)
                    except asyncio.TimeoutError:
                        if len(msgs) > 0:
                            print("MSG Q LEN=",len(msgs),",".join([x for x in msgs]) )
                            msgs = []
                        msg = await websocket.recv()
                        msgs.append(msg)
        except:
            traceback.print_exc()
            return


asyncio.get_event_loop().run_until_complete(main())
```

Is there a way using libwebsockets?

Thank you,

Tom

**Comment by lws-team** [comment]
The question makes some assumptions that I don't think apply to lws.

If lws hears there's something to read on a socket, it will by default read up to 4K or so of what's there and parse through that.  If it's multiple protocol messages, it'll deal with them one by one.  After that it will return to the event loop.

If there was still more to read, it'll get another POLLIN and read another up to 4K etc.  But inbetweentimes, other sockets with things to do will get serviced as well.  Particularly in the cases you're taking data in, processing it and sending it back out; or you have multiple connections active, you want it to do what it's already doing.
