### ISSUE TITLE
Problem with Secure WebSocket and Firefox

### ISSUE THREAD

**Issue by MarkusWeinand** [warmcat/libwebsockets#1689]
Hello,
iam trying to send large messages over a WebSocket. I took the minimal-ws-server example and changed it, so it always replies with a message of 1 million chars. In Chrome everthing works fine, but in Firefox the Program gets a SIGPIPE.
I have added a Wireshark Snapshot and a Keyfile, to decrypt the Messages.
You can see that Firefox sends a GOAWAY Frame after it recieved some Packages over the WebSocket.
This Problem only occurs over the Secure WebSocket.

[firefox2.zip](https://github.com/warmcat/libwebsockets/files/3626159/firefox2.zip)

**Comment by lws-team** [comment]
Can I get the diff on the minimal example?

Does ffox console say anything, or the Network tab on the dev tools for that stream?

**Comment by lws-team** [comment]
I did this

```
diff --git a/minimal-examples/ws-server/minimal-ws-server/mount-origin/example.js b/minimal-examples/ws-server/minimal-ws-server/mount-origin/example.js
index 189f4640b..bed368794 100644
--- a/minimal-examples/ws-server/minimal-ws-server/mount-origin/example.js
+++ b/minimal-examples/ws-server/minimal-ws-server/mount-origin/example.js
@@ -59,7 +59,10 @@ document.addEventListener("DOMContentLoaded", function() {
        
        function sendmsg()
        {
-               ws.send(document.getElementById("m").value);
+               var s = "0123456789abcdef";
+
+               ws.send(s.repeat(128 * 1024));
+//             ws.send(document.getElementById("m").value);
                document.getElementById("m").value = "";
        }
       
```

It seems to work OK on Linux Firefox 69.  Sicne it's specific to tls you should also maybe look at your openssl version, I'm on 1.1.1c.

But... `GOAWAY`... you're telling ffox to use ws-over-h2?

**Comment by MarkusWeinand** [comment]
```
case LWS_CALLBACK_SERVER_WRITEABLE:
		if (!vhd->amsg.payload)
			break;

		if (pss->last == vhd->current)
			break;

		/* notice we allowed for LWS_PRE in the payload already */
                int length = 1000000;
                
                char *string = (char*)malloc((length + 1 + LWS_PRE) * sizeof(char));
                rand_string(string + LWS_PRE, length);
                
                m = lws_write(wsi, string + LWS_PRE, length, LWS_WRITE_TEXT);
                
		if (m < (int)vhd->amsg.len) {
			lwsl_err("ERROR %d writing to ws\n", m);
			return -1;
		}

		pss->last = vhd->current;
		break;
```

I just changed the write callback to send a random string everytime.

```
static char *rand_string(char *str, size_t size)
{
    const char charset[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJK...";
    if (size) {
        --size;
        for (size_t n = 0; n < size; n++) {
            int key = rand() % (int) (sizeof charset - 1);
           str[n] = charset[key];

        }
        str[size] = '\0';
    }
    return str;
}
```

Firefox Console gives me this error:
The connection to wss://192.168.25.71/ was interrupted while the page was loading.
Not verry much :(.
I also changed the example.js to only display the length of the message.
I hope this helps.

**Comment by lws-team** [comment]
Thanks.

Has firefox been told to use ws-over-h2?  It changes a lot of things.

**Comment by MarkusWeinand** [comment]
> But... `GOAWAY`... you're telling ffox to use ws-over-h2?
No iam not specifically telling ffox to do that

**Comment by lws-team** [comment]
This works for me but there's a small bug in your rand_string, it actually sends 0x00 at the end.  lws doesn't need a terminating 0x00 since it has the length... it's treated as content and sent in the ws packet.  When you send TEXT with ws, the receiver is supposed to check it's all valid UTF-8 and drop the connection if not.

(Also you should free `string` after the lws_write()).

It's really inefficient sending something big like this is doing... what happens is the write syscall copies all 1M from userspace mapping into kernelspace.  Then the actual write kernelside reports that it will only accept 4KB or whatever.  Lws copies the remaining 996KB into a malloc'd buffer and repeats the write process (not the malloc copying though) in the background.... again 996KB is copied by the syscall and maybe 2KB accepted, next time 994KB copied and 2KB accepted.

It shouldn't stop it working, but FYI the recommended way to do this is send smaller chunks related to mtu using the ws fragmentation stuff, you can see an example here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-pmd-bulk/protocol_lws_minimal_pmd_bulk.c#n133

**Comment by MarkusWeinand** [comment]
> It seems to work OK on Linux Firefox 69. Sicne it's specific to tls you should also maybe look at your openssl version, I'm on 1.1.1c.
My server is also on openssl version 1.1.1c.
Could it be that it is running on a Raspberry Pi?



> It shouldn't stop it working, but FYI the recommended way to do this is send smaller chunks related to mtu using the ws fragmentation stuff, you can see an example here

I know that ther is a better way of doing this, but in our application it it quit rarely that such a large message is send.

**Comment by lws-team** [comment]
Lws doesn't care you're on an rpi, in itself that makes zero difference to it.

I don't know how ffox might react to it... "rpi" means a lot of things nowadays the rpi4 can have 4G and is pretty capable, some of the other variants are much weaker and have less memory.

> I know that ther is a better way of doing this, but in our application it it quit rarely that such a large message is send.

If there's a bug in lws I'll take time to study it.  But all I can see so far is "ffox hangs up on me when I send a big packet over tls".  I can't reproduce it on my box.  So I don't see anything for me to do.  You're not actually asking me to do anything, right?

What you can do is look at using the ws fragmentation and see if that improves your situation.

**Comment by NicolasKiebel** [comment]
I've got the same Problem, but can't figure out why. It only occurs on Firefox when tls was enabled on the server.

**Comment by lws-team** [comment]
So how can I reproduce it?
