### ISSUE TITLE
lws_is_ssl() documentation

### ISSUE THREAD

**Issue by thomgree** [warmcat/libwebsockets#1695]
In the declaration of lws_is_ssl() it says 
```
 *	Returns 0 if the connection is not using SSL, 1 if using SSL and
 *	using verified cert, and 2 if using SSL but the cert was not
 *	checked (appears for client wsi told to skip check on connection)
```
https://github.com/warmcat/libwebsockets/blob/e7d72a107cfd7c841a768dbf4714cd1ce0b3684d/include/libwebsockets/lws-misc.h#L561

But from looking at the implementation it seems like it could only possibly return 0 or 1 (since LCCSCF_USE_SSL is 1, only the last bit of wsi->tls.use_ssl is relevant):
https://github.com/warmcat/libwebsockets/blob/65b2e685673663cb8369739f4b0d042162d13cb4/lib/core-net/wsi.c#L409

**Comment by lws-team** [comment]
Right... what happened is that the int holding this became overloaded with increasingly unrelated flags... a while back I chopped them all off for the purpose of this api result.  I have made the docs reflect that, I'll push the patch later.
