### ISSUE TITLE
Segmentation fault at  __lws_header_table_reset

### ISSUE THREAD

**Issue by Bharanitharan02** [warmcat/libwebsockets#1699]
Hi,

I am getting a seg fault.
Here is the core dump.Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./tunnel-server -d65535'.
Program terminated with signal 11, Segmentation fault.
#0  __lws_header_table_reset (wsi=0x7fcae080ddd0, autoservice=0) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c:162
162	/vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 openssl-libs-1.0.2k-12.el7.rks_5.2.0.0.3.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  __lws_header_table_reset (wsi=0x7fcae080ddd0, autoservice=0) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c:162
#1  0x0000000000420945 in lws_header_table_attach (wsi=0x7fcae080ddd0, autoservice=0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c:317
#2  0x0000000000423f52 in rops_adoption_bind_h1 (wsi=0x7fcae080ddd0, type=16777219, vh_prot_name=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/h1/ops-h1.c:871
#3  0x00000000004174e9 in lws_role_call_adoption_bind (wsi=0x7fcae080ddd0, type=16777219, prot=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/vhost.c:161
#4  0x000000000044aeeb in lws_adopt_descriptor_vhost (vh=0x21772c0, type=3, fd=..., vh_prot_name=0x0, parent=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/adopt.c:259
#5  0x000000000044b793 in rops_handle_POLLIN_listen (pt=0x211b088, wsi=0x2178530, pollfd=0x7fcb2e3bb488)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/listen/ops-listen.c:138
#6  0x000000000041cbd8 in lws_service_fd_tsi (context=0x211a740, pollfd=0x7fcb2e3bb488, tsi=6)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/service.c:1050
#7  0x0000000000441f66 in _lws_plat_service_tsi (context=0x211a740, timeout_ms=50, tsi=6)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/plat/unix/unix-service.c:185
#8  0x000000000041ce39 in lws_service_tsi (context=0x211a740, timeout_ms=50, tsi=6) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/service.c:1147
#9  0x00000000004109f5 in thread_service (threadid=0x6) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify//new_test/test-apps/tunnel/tunnel-server.C:1663
#10 0x00007fcb2d0c0e25 in start_thread () from /usr/lib64/libpthread.so.0
#11 0x00007fcb2cdeabad in clone () from /usr/lib64/libc.so.6
(gdb) bt full
#0  __lws_header_table_reset (wsi=0x7fcae080ddd0, autoservice=0) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c:162
        ah = 0x7fcae0527e70
        pt = 0x211b4c0
        pfd = 0x211b4c0
        __PRETTY_FUNCTION__ = "__lws_header_table_reset"
        __func__ = "__lws_header_table_reset"
#1  0x0000000000420945 in lws_header_table_attach (wsi=0x7fcae080ddd0, autoservice=0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/http/server/parsers.c:317
        context = 0x211a740
        pt = 0x211b4c0
        pa = {fd = 5, events = 3, prev_events = -528425520}
        n = 0
        __func__ = "lws_header_table_attach"
        __PRETTY_FUNCTION__ = "lws_header_table_attach"
#2  0x0000000000423f52 in rops_adoption_bind_h1 (wsi=0x7fcae080ddd0, type=16777219, vh_prot_name=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/h1/ops-h1.c:871
        __func__ = "rops_adoption_bind_h1"
#3  0x00000000004174e9 in lws_role_call_adoption_bind (wsi=0x7fcae080ddd0, type=16777219, prot=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/vhost.c:161
        ar = 0x665be0 <role_ops_h1>
        ppxx = 0x665ad0 <available_roles+16>
        n = 0
        __func__ = "lws_role_call_adoption_bind"
#4  0x000000000044aeeb in lws_adopt_descriptor_vhost (vh=0x21772c0, type=3, fd=..., vh_prot_name=0x0, parent=0x0)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/adopt.c:259
        context = 0x211a740
        pt = 0x211b4c0
        new_wsi = 0x7fcae080ddd0
        n = 19
        __func__ = "lws_adopt_descriptor_vhost"
#5  0x000000000044b793 in rops_handle_POLLIN_listen (pt=0x211b088, wsi=0x2178530, pollfd=0x7fcb2e3bb488)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/roles/listen/ops-listen.c:138
        cwsi = 0x7fcae080c770
        context = 0x211a740
        accept_fd = 4992
        fd = {sockfd = 4992, filefd = 4992}
        opts = 7
        cli_addr = {ss_family = 2, 
---Type <return> to continue, or q <return> to quit---
          __ss_padding = "g\256\177\000\000\001\000\000\000\000\000\000\000\000\220\376\215]\000\000\000\000\311\360A\000\000\000\000\000\020\252H\030\313\177\000\000\200\264;.\313\177\000\000\220f\027\002\000\000\000\000\210\260\021\002", '\000' <repeats 29 times>, "\020\200\000\000\000\000\000p\252H\030\313\177\000\000\265\353A", '\000' <repeats 12 times>, 
          __ss_align = 34713736}
        clilen = 16
        __func__ = "rops_handle_POLLIN_listen"
#6  0x000000000041cbd8 in lws_service_fd_tsi (context=0x211a740, pollfd=0x7fcb2e3bb488, tsi=6)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/service.c:1050
        pt = 0x211b088
        wsi = 0x2178530
        __PRETTY_FUNCTION__ = "lws_service_fd_tsi"
        __func__ = "lws_service_fd_tsi"
#7  0x0000000000441f66 in _lws_plat_service_tsi (context=0x211a740, timeout_ms=50, tsi=6)
    at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/plat/unix/unix-service.c:185
        ftp = 0x0
        next = 0x0
        vpt = 0x211b088
        pt = 0x211b088
        n = 1
        m = 0
        c = 159
        __func__ = "_lws_plat_service_tsi"
#8  0x000000000041ce39 in lws_service_tsi (context=0x211a740, timeout_ms=50, tsi=6) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify/lib/core-net/service.c:1147
        pt = 0x211b088
        n = 0
#9  0x00000000004109f5 in thread_service (threadid=0x6) at /vagrant/scg/common/services/messaging/libwebsockets-master_ssl_verify//new_test/test-apps/tunnel/tunnel-server.C:1663
No locals.
#10 0x00007fcb2d0c0e25 in start_thread () from /usr/lib64/libpthread.so.0
No symbol table info available.
#11 0x00007fcb2cdeabad in clone () from /usr/lib64/libc.so.6
No symbol table info available.

The system os is 
Centos 7

Could you please help.
Thanks.

**Comment by lws-team** [comment]
What is the exact version of lws?  Because the source line info is not very useful without knowing it.

> tsi 6

Is there any problem with a single service thread?

**Comment by Bharanitharan02** [comment]
Hi We are using version 3.1

**Comment by Bharanitharan02** [comment]
verison - 3.1

**Comment by lws-team** [comment]
Version 3.1.0?  Or something from v3.1-stable?  What's the git hash for the lws you're using?

**Comment by Bharanitharan02** [comment]
we are using version 3.1.0

**Comment by lws-team** [comment]
Please try master, and just the one service thread.

V3.1 is old and not maintained...

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

V3.1.0 is a worse idea since v3.1-stable has many bugfixes you're already ignoring.
