### ISSUE TITLE
prioritize write over read

### ISSUE THREAD

**Issue by jsveto** [warmcat/libwebsockets#1700]
Hi,

i am using libwebsockets to connect to several ws. I have a lot of receive data and can sometimes reach up to 50% CPU usage and over 40Mbit/s BW.

Occasionally i have to send out some data. Data must be sent out very fast! Currently it takes about 10ms before event loop WRITEABLE_CALLBACK is executed and this is too much.

If i reduce receive data, WRITEABLE_CALLBACK is executed faster (This is expected).

1.) Is there anyway i can prioritise WRITEABLE_CALLBACK over RECEIVE_CALLBACK so i can speed up TX data. 
2.) I know this is illegal use case, but, is there anyway i can use lws_write outside of event_loop? And if yes, what are the drawbacks.

Best regards,
jsveto

**Comment by lws-team** [comment]
Write outside of lws isn't a good way. You may jump in the middle of an incomplete existing write.  It 's especially difficult to talk on a muxed protocol randomly, like h2.

Basically with poll(), he tells us about every fd that has POLLIN or POLLOUT when he exits the wait.

I think you understand it already but there are many more POLLIN to deal with and maybe one POLLOUT hidden in there somewhere... it gets to it when it gets to it after wading through whatever POLLINs were before it.

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-service.c#n43-56

For poll() case that lws handles, you could consider some tricks.  First would be only do some small number of POLLIN processing in one time, ones you don't handle will still be set as POLLIN next time around the event loop.  Second would be hack the loop linked to above to cut and paste the loop, and first handle only POLLOUT guys.

Or if you only care about h1, you could just do a hack using a cheat api that checks if a wsi is writable synchronously (it also checks for partials ongoing)... 0 means you can do the write yourself

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h#n37-38

**Comment by jsveto** [comment]
Hi, i would just like to add some conclusion on how i "solved" my problem.

I have put "solved" in quotes since it is not regular solution but it works for me. So firstly i would like to state that quick response (TX packet out) is most important here. Each microsecond is important.

I have put lws_write outside of event loop.

Additionally i had to provide locking around lws_write function, to make sure only single lws_write is executed in a multithreaded application. This could be disastrous for performance in a multithreaded application which does a lot of TX, since each thread which write data must wait for previous call to finish writing. Writing thread is also blocked for longer period of time since it is responsible for writing to socket. Like i said it works perfect for my application which does little TX data but requires minimal delay.

Secondly i had to disable back-to-back write checking in libwebsockets library. This is done with following code change:
diff --git a/lib/core/output.c b/lib/core/output.c
index f820c02..37c7505 100644
--- a/lib/core/output.c
+++ b/lib/core/output.c
@@ -39,6 +39,7 @@ int lws_issue_raw(struct lws *wsi, unsigned char *buf, size_t len)
         * back-to-back writes in one WRITABLE (illegal) or calling lws_write()
         * from outside the WRITABLE callback (illegal).
         */
+#if 0
        if (wsi->could_have_pending) {
                lwsl_hexdump_level(LLL_ERR, buf, len);
                lwsl_err("** %p: vh: %s, prot: %s, role %s: "
@@ -50,6 +51,7 @@ int lws_issue_raw(struct lws *wsi, unsigned char *buf, size_t len)
 
                return -1;
        }
+#endif
 
        lws_stats_atomic_bump(wsi->context, pt, LWSSTATS_C_API_WRITE, 1);

Thank you for your help @lws-team 

Best regards.

**Comment by lws-team** [comment]
Newer lws (v3.2+) uses an lws_buflist to stash unfinished writes... so although it's inefficient actually it can handle cases where writes stack up.

I think few people can reuse your "solution"... but it's good to share what worked for you anyway.
