### ISSUE TITLE
LWS_ROLE_WS in minimal example

### ISSUE THREAD

**Issue by dengroc** [warmcat/libwebsockets#1702]
Hi, I was building minimal example in `minimal-examples/ws-client/minimal-ws-client-echo`. The steps I have done:

1. build libwebsocket itself following: https://libwebsockets.org/lws-api-doc-master/html/md_READMEs_README_8build.html. This step was successful after `sudo make install`

2. build minimal examples:

```
cd minimal-examples/ws-client/minimal-ws-client-echo
mkdir build
cd build
cmake ..
make
```

Then I get:
```  
This project requires lws must have been configured with LWS_ROLE_WS
```

Did I miss anything in the setup? I was using macOs on v3.2-stable tag.

Thanks!

**Comment by lws-team** [comment]
1) Do you have a `/usr/include/libwebsockets.h`?  This will take precedence over the one you built, which went into `/usr/local/include`.  If so, uninstall those other pieces

2) If not, what does it say in `/usr/local/include/lws_config.h` about `LWS_ROLE_WS`?

**Comment by dengroc** [comment]
> Do you have a /usr/include/libwebsockets.h? This will take precedence over the one you built, which went into /usr/local/include. If so, uninstall those other pieces

I don't have `user/include/libwebsockets.h` as `user/include` is deprecated by apple.

> If not, what does it say in /usr/local/include/lws_config.h about LWS_ROLE_WS?

at line 90 ` #define LWS_ROLE_WS`.

**Comment by lws-team** [comment]
Inside `libwebsockets.h` he has this...

```
#include "lws_config.h"
```

... to pick up the options that the installed lws was built with.

In the CMakeLists.txt, he does a compile build test like this

```
CHECK_C_SOURCE_COMPILES("#include <libwebsockets.h>\nint main(void) {\n#if defined(${reqconfig})\n return 0;\n#else\n fail;\n#endif\n return 0;\n}\n" HAS_${reqconfig})
```

to find out if the requirement is in there or not.  But I guess, there is some reason this test code won't compile on your platform.... maybe the (void) on main?

**Comment by dengroc** [comment]
main(void) should be fine on macOs as I can build cpp file with `int main(void){}`. I also tried comment out the line `require_lws_config(LWS_ROLE_WS 1 requirements)` then it gives me `'libwebsockets.h' file not found` at compile time. Do you think it might be related to installation of the lib itself?

**Comment by lws-team** [comment]
Maybe... it might matter if you use anglebrackets or quotes around the filename in the include.

Afaik it's normal to have /usr/local/include in the toolchain include path, if not on your platform maybe try with -I/usr/local/include

**Comment by lws-team** [comment]
If there's something I should do to improve compatibility with it, let me know.

**Comment by wini3d** [comment]
I am getting a similar error and cannot get the exact example to configure and generate the build files.
