### ISSUE TITLE
Compatibility with android websocket library "org.java-websocket:Java-WebSocket:1.4.0"

### ISSUE THREAD

**Issue by sarveshkhandu** [warmcat/libwebsockets#1703]
Trying to connect libwebsocket test-client (using dumb-increment protocol, version 2.0.0) on a linux machine to an android server running "org.java-websocket:Java-WebSocket:1.4.0". We get the callback "LWS_CALLBACK_CLIENT_CONNECTION_ERROR" and value of in is null.

The test-client and test-server are working and able to talk to each other.

**Comment by lws-team** [comment]
Use master... every path should have a non-null message.

But usually it meant the remote side hung up on us.  So go look in the server's logs.

Failing that, produce lws logs and look at those.
