### ISSUE TITLE
Reading Http data - No LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ received.

### ISSUE THREAD

**Issue by shassan111** [warmcat/libwebsockets#1705]
Hi,

I implemented an http connection and notice a weird phenomenon. (version 3.1),
I've observed an intermittent phenomenon where, even though LWS sends the LWS_CALLBACK_RECEIVE_CLIENT_HTTP callback (indicating that data is available), the data is not actually ready to be read as yet and no LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ is sent in response to lws_http_client_read() call. However, if I add  short wait before calling lws_http_client_read() , then I receive LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ  as expected.

Following is a stripped down version of my code.
```
case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
      {
            unsigned char **p = (unsigned char **)in, *end = (*p) + len;
            // Need to set content-type. We have no actual content to send so set content length to 0.
            if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_LENGTH,(unsigned char *)"0", 1, p, end))
            {     
               return -1;
            }
            if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_TYPE,(unsigned char *)"application/x-www-form-urlencoded",33, p, end))
            {
               return -1;
            }
            // inform lws we have http body to send 
            lws_client_http_body_pending(wsi, 1);
            lws_callback_on_writable(wsi);
         }
      }
      break;

   case LWS_CALLBACK_RECEIVE_CLIENT_HTTP:
      {
            char buffer[4096 + LWS_PRE];
            memset(&buffer,0,sizeof(buffer));
            char *px = buffer + LWS_PRE;
            int lenx = sizeof(buffer) - LWS_PRE;

            // LWS BUG?? I've observed an intermittent phenomenon where, even though LWS sends the LWS_CALLBACK_RECEIVE_CLIENT_HTTP 
            // callback (indicating that data is available), the data is not actually ready to be read 
            // as yet and no LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ is sent. A short wait before calling lws_http_client_read() addresses this issue.** 
            sleep(100);
            if (lws_http_client_read(wsi, &px, &lenx) < 0)
            {
               return -1;    // Error, close the connection
            }

           // Process the complete http response
            m_httpRespBuffer->processBuffer()
      }
      break;

   // Process http chunked data
   case LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ:
      {
            // Save the http resp - there may be multiple call backs depending on the number of chunks received.
            if (len > 0)
            {
               m_httpRespBuffer->appendBuffer((char *)in, len);
            }
         }
      }
      break;
```

**Comment by shassan111** [comment]
Sorry the code paste did no go as expected.

**Comment by lws-team** [comment]
The big secret is use three x backticks, like \`\`\` on the line before and the line after the code.

If this travels over tls, you should note that the events it uses are ultimately tls socket events, ie, events because there is something encrypted to read or can be written.  Under some conditions, the encrypted data sent may be consumed by the tls tunnel itself... then we saw something (encrypted...) ready to read, asked the tls library to read it and give us the decrypted payload, it reads the tls data (eg, rekeying) and there is not actually any payload.

Another way is if the data is sent with content-encoding chunked, lws strips the chunk headers.  If it happened that all was sent was the chunk header, like `200\r\n\r\n` but not yet the payload, this time lws will consume the header but after doing that... there's no payload to pass on.

Waiting a bit for completely different, new payload to arrive is unrelated for these cases.

**Comment by shassan111** [comment]
Thanks for the quick response. It is TLS, actually, Non-TLS works fine without the wait. I guess I should have mentioned that.
However I am not following how I should implement the code for TLS  (without a wait) in order for this to work. Your input is much appreciated. Thanks again.

**Comment by lws-team** [comment]
This is no different than receiving a zero-length packet... there was an event, but there was no payload.  So there is nothing for you to do but wait for the next event.  It doesn't represent any error condition (if it's what I am describing, anyway).

**Comment by shassan111** [comment]
Ahh.. I see.

I added a check to break if lenx==0, and I eventually got the LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ callback with the expected data!

Many thanks for your help and most of all quick responses! Much appreciated.

```
           if (lws_http_client_read(wsi, &px, &lenx) < 0)
            {
               m_amsLog->log(WCS_DEBUG_LOG_INFO, "WCSTranscoderAgentProcessor::lwsCallback:[%d] LWS_CALLBACK_RECEIVE_CLIENT_HTTP. ERROR reading http. Closing connection. State[%s]\n", lc->m_channelId, lc->getStateStr());
               return -1;    // Error, close the connection
            }
            
            if (lenx == 0)
            {
               break;
            }
```

**Comment by lws-team** [comment]
Great.
