### ISSUE TITLE
lws_get_peer_simple not working properly from client side IPv4

### ISSUE THREAD

**Issue by ggarber** [warmcat/libwebsockets#1713]
I'm calling `lws_get_peer_simple` after the WS connection is established and I get unexpected/random IPv6 addresses.

I think maybe the reason is because of this check `LWS_IPV6_ENABLED(wsi->vhost))` in the function that depends on the vhost value that maybe is only defined for server side websockets?

Could that logic change to decide if it is IPv4 or IPv6 based on `getpeername` response?

Something like this code works fine client side and I think should also work server side:  https://github.com/warmcat/libwebsockets/issues/908#issuecomment-305273085

Version: libwebsockets 3.0
Platform: Windows and Mac
Type: Bug/FeatureRequest

**Comment by lws-team** [comment]
It seems to work OK for me on linux, with IPv6 enabled and on systems with ipv4 only assigned and ipv4 + ipv6 assigned.

ipv4-only assigned:

```
[2019/10/12 12:12:28:4667] N: callback_dynamic_http: HTTP: connection ::ffff:127.0.0.1
```

both assigned... access over ipv4 and then over ipv6

```
[2019/10/12 13:52:38:0096] N: callback_dynamic_http: HTTP: connection ::ffff:127.0.0.1
[2019/10/12 13:53:28:4537] N: callback_dynamic_http: HTTP: connection ::1
```

You'll need to clarify exactly what happens on what platform... this is a windows-only issue actually, or even Mac / BSD is acting different?

**Comment by ggarber** [comment]
@lws-team You are also testing it in a WebSockets server, right?    The problem we see is when we try to use it in a WebSockets client.

Is it more clear?   We tested it in Windows and Mac and it doesn't work in any of them when used in the client side.

**Comment by lws-team** [comment]
I added this api call to the http client minimal example on master, it works fine here on Linux.  At least for mac, it's hard to see what will be different to break it.  If you still see the problem on master + the http client example with this in, please let me know.
