### ISSUE TITLE
lws_generate_client_handshake() dumps requests with puts()

### ISSUE THREAD

**Issue by taviso** [warmcat/libwebsockets#1714]
libwebsockets has started dumping requests to the console with `puts()` since 165696a4b85015f0d99851c2837278a50d7d6041

https://github.com/warmcat/libwebsockets/commit/165696a4b85015f0d99851c2837278a50d7d6041#diff-3ed171f9e8fa65a3aa885f568e0c33acR1243

This doesn't seem to be controllable, and dumps a lot of unnecessary output to the console.

**Comment by lws-team** [comment]
It'll go away soon... it's debugging collateral damage not a 'new feature'.

**Comment by lws-team** [comment]
It's gone away...
