### ISSUE TITLE
cmake on minimal-ws-client-ping fails with "This project requires lws must have been configured with LWS_ROLE_WS"

### ISSUE THREAD

**Issue by drorcohen** [warmcat/libwebsockets#1718]
either with master or with v3.2.0 I tried the following:
cmake .
make 
sudo make install
sudo ldconfig

then cd into minimal-examples/ws-client/minimal-ws-client-ping and run
cmake .

I get:
CMake Error at CMakeLists.txt:67 (message):
  This project requires lws must have been configured with LWS_ROLE_WS
Call Stack (most recent call first):
  CMakeLists.txt:78 (require_lws_config)

-- Configuring incomplete, errors occurred!
See also "/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeOutput.log".
See also "/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeError.log".

After reading https://github.com/warmcat/libwebsockets/issues/1702 I went and checked:
/usr/include/lws_config.h - doesn't exist
/usr/local/include/lws_config.h has a line "#define LWS_ROLE_WS"
manually compiling the attached test.txt works (gcc test.c -o test). You'll need to rename it to test.c (can't upload it with that name...)

[test.txt](https://github.com/warmcat/libwebsockets/files/3736952/test.txt)

What should be my next step?

**Comment by lws-team** [comment]
Cmake tries to build a little program to determine if the config option it wants exists... if the program builds, the option exists.

What's actually in `"/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeError.log"`?

**Comment by drorcohen** [comment]
Here it is:
Performing C SOURCE FILE Test HAS_LWS_ROLE_WS failed with the following output:
Change Dir: /home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0f44b/fast"
/usr/bin/make -f CMakeFiles/cmTC_0f44b.dir/build.make CMakeFiles/cmTC_0f44b.dir/build
make[1]: Entering directory '/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0f44b.dir/src.c.o
/usr/bin/cc   -DHAS_LWS_ROLE_WS   -o CMakeFiles/cmTC_0f44b.dir/src.c.o   -c /home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeTmp/src.c
/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeTmp/src.c:1:10: fatal error: libwebsockets.h: No such file or directory
 #include <libwebsockets.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_0f44b.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_0f44b.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_0f44b.dir/src.c.o] Error 1
make[1]: Leaving directory '/home/dror/projects/libwebsockets/minimal-examples/ws-client/minimal-ws-client-ping/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_0f44b/fast' failed
make: *** [cmTC_0f44b/fast] Error 2

Source file was:
#include <libwebsockets.h>
int main(void) {
#if defined(LWS_ROLE_WS)
 return 0;
#else
 fail;
#endif
 return 0;
}

Seems like it can't find the include file - but it is in /usr/local/include/

$ ls -la /usr/local/include/libwebsockets.h
-rw-r--r-- 1 root root 14577 Oct 16 17:37 /usr/local/include/libwebsockets.h

**Comment by lws-team** [comment]
If it's gcc, it should look there.

https://gcc.gnu.org/onlinedocs/gcc-3.1.1/cpp/Search-Path.html

When you build it manually, you are using /usr/bin/cc like the real test?

Try remove all generated cmake files in the dir and start again from `cmake .`

**Comment by drorcohen** [comment]
thanks for the help. Removing everything, re-cloning the repo and working through the steps worked. I guess one of my attempts confused cmake...

**Comment by lws-team** [comment]
Cmake is big on cacheing stuff... cmake in the discrete apps doesn't see that anything changed if you rebuilt the lib.  So my guess is you first tried to build the example before you built the lib.  And the example cmake cached that result such that even after you built and installed the lib it just regurgitated it.

It's definitely part of the toolkit working with cmake to rm -f CMakeCache.txt if things stop making sense.
