### ISSUE TITLE
Video streaming over websocket

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#1719]
Hi experts,

I know the libwebsocket library is highly efficient and experts are trying to mould it to support many protocols like mqtt and all. I would like to know whether the websocket supports Video streaming like RTSP, so that i can play my H.264 encode data in the browser.

**Comment by lws-team** [comment]
Can it support it?  Yes.

But good news, nobody contributed an RTSP protocol plugin for lws yet, so you can still be the one.
