### ISSUE TITLE
The web client error "Invalid frame header" when a larget data to client

### ISSUE THREAD

**Issue by windflowerly** [warmcat/libwebsockets#1720]
The web client already established a websocket connection. but the connection is broken when server send  large data(411867 byte)。

the error message : "Invalid frame header"

**Comment by lws-team** [comment]
So... how can I reproduce that (preferably using the minimal examples)?

**Comment by windflowerly** [comment]
i test this case with minimal examples (path : libwebsockets\minimal-examples\ws-server\minimal-ws-server)

my web scoket cofigure :
#define LWS_PLUGIN_PROTOCOL_MINIMAL \
	{ \
		"gangtise", \
		ws_callback_minimal, \
		sizeof(struct per_session_data__minimal), \
                0, \	
		0, NULL, 0 \
	}

**Comment by windflowerly** [comment]
Does it data size limit?

**Comment by lws-team** [comment]
OK... but what changes did you make to send something large?

Your device will not send a packet sized at 411K in one go, if you just try to send it, lws will buffer what the kernel didn't accept (probably > 400K) and send it in the background.  This isn't very efficient.

If you make other problems like lws_send() outside the writeable callback, you can make this problem.  So either make a diff I can apply to a minimal example to see the problem, or better look at how the bulk example sends smaller pieces in sequence using ws message continuation.

**Comment by windflowerly** [comment]
what kind of situation cause this error "Invalid frame header".
I send a packet size at 365K, it's succcessful...

would you apply minimal example to test this case.

**Comment by lws-team** [comment]
Why don't you send me a small patch on a minimal example that lets me see the problem, if you can reproduce it like that.

**Comment by windflowerly** [comment]
OK.

**Comment by windflowerly** [comment]
I got this problem.
Ajust pt_serv_buf_size to 1024 *1024*1 where application initialze. and the problem is gone;

	**info.pt_serv_buf_size = 1024 * 1024 * 1;**

but, why ?

**Comment by windflowerly** [comment]
another question:

Does I must to call lws_write to send message to client on LWS_CALLBACK_SERVER_WRITEABLE ?

how do i send message to client asynchronously without LWS_CALLBACK_SERVER_WRITEABLE..

**Comment by lws-team** [comment]
> Does I must to call lws_write to send message to client on LWS_CALLBACK_SERVER_WRITEABLE ?

Yes.  It adds the framing to make it ws protocol.

> how do i send message to client asynchronously without LWS_CALLBACK_SERVER_WRITEABLE..

You don't.  You can use `lws_cancel_service()` from another thread to break the wait in your communications thread

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-service.h#n91

From there you can ask for a callback on writable.
