### ISSUE TITLE
Created sockets should use SOCK_CLOEXEC where possible

### ISSUE THREAD

**Issue by socketpair** [warmcat/libwebsockets#1721]
In multi-threaded systems it is not enough to set O_CLOEXEC after file descriptor is created.
so, we should use `accept4(.....|SOCK_CLOEXEC)` and `socket(.... |SOCK_CLOEXEC)` where possible instead of, say, `lws_plat_apply_FD_CLOEXEC`

The same for almost every case in `open(...O_CLOEXEC)` used in this libray.

also `fopen("filename", "...e..")` where appropriate.

**Comment by lws-team** [comment]
SOCK_CLOEXEC + accept4 itself are linux-only extensions... FD_CLOEXEC / O_NOINHERIT re available more or less everywhere.

If you need what you're suggesting here, I'll be happy to receive a patch from you that doesn't break non-Linux platforms.

**Comment by lws-team** [comment]
Well... still happy to get a patch.
