### ISSUE TITLE
Stream merge latency spikes

### ISSUE THREAD

**Issue by deforation** [warmcat/libwebsockets#1725]
I'm using libwebsockets in the following scenario.

 - n clients (120) connect to a server A
 - server a connects to server B
 - server A receives approximatelly 70 messages per second.
What happens is basically, server A merges the data of the streams and forwards them to server B.

I could obwerve the following behaviour.
Each client sends a message and adds a timestamp to it.

When they arrive at A, they are immediatelly forwarded to server B without any changes them.
Server B then takes his timestamp and calculates the difference to the one in the message.

What i could observe, are strange latency spikes as they can be seen here (those range from milliseconds to multiple seconds).
https://ibb.co/Nsc80cZ

Am i doing something wrong or is this a typical behaviour that can happen with websockets over long distances (HongKong to Paris)?

Thanks in advance.

**Comment by lws-team** [comment]
> n clients (120) connect to a server A
> A receives approximatelly 70 messages per second.
> multiple seconds

Mm latency is a bit like measuring your bank balance... it gives you a number that tells you something is right or wrong but in itself the reason is not in the number it reports.

My guess is there are two problems...

 - every time around the event loop there are many more rx to service than tx.  With the singlethreaded event loop, on average pending tx is stuck waiting while you chew through the rx

 - if your tx aggregation is large, it exacerbates the first point since it sends it piecemeal each time around the event loop, and with websocket messages on non-ws servers, they buffer incoming message pieces until the whole ws message is received and 'see' it at once.  That means latency for the earliest aggregated parts of the message will become higher than it needs.

You can look at plotting tx message size vs latency I think that will show larger ws message = spikes of increasing latehcy as earliest aggregated messages in there get older and older waiting for the ws message tx to end... ie, the `___|\___` shape.

You should be able to reduce the height of the spikes by restricting the size of the ws message you are trying to tx to a few K instead of trying to clear your ringbuffer each time.  That way the earliest aggregated message has much more limited time stuck waiting for the tx ws message to complete.  It doesn't address the rx:tx ratio problem though.

**Comment by lws-team** [comment]
> Each one runs in a separate thread. Each thread creates its own connection, context and all other required objects in order to run libwebsockets.

You didn't mention this :-)

Still, what is the size of the discrete ws message that is sent from A -> B?  You don't mention that either and I think entries that were sent but not yet "received" at B as a complete message can explain well the pattern in your graph.  If that logical message is "big" it will explain at least half your problem... so maybe measure it...

**Comment by deforation** [comment]
Sorry. It came later into my mind that this is indeed an important point.
I also thought, that TCP may be the problem here, because on short distances within the same network, its barely noticable. But over those long distances, it literally explodes.

Each message is a json string with the size of about 310 characters.

Because the loss of a message in the scenario above is acceptable, you think it may be worth to try using UDP'

**Comment by lws-team** [comment]
> UDP

You should try to understand it... by recording the size of the ws messages you are sending, as suggested twice now.  If you can make a latency graph, recording the size of the ws messages is not very difficult.

**Comment by deforation** [comment]
I'll try

**Comment by deforation** [comment]
I have tracked the output of the written bytes by lws_write.
And as it seems, all messages have the same size of about 330 to 341 bytes.

So the tx/latency grapth would literally look like the one i linked in the first post.

**Comment by deforation** [comment]
`

    source = 1571683986320157, added = 1571683986324987, sent = 1571683986485720, size = 370, latency = (4830 / 160733)
    source = 1571683986490776, added = 1571683986500159, sent = 1571683986500185, size = 367, latency = (9383 / 26)
    source = 1571683986490812, added = 1571683986500242, sent = 1571683986500317, size = 367, latency = (9430 / 75)
    source = 1571683986320192, added = 1571683986325050, sent = 1571683986518339, size = 370, latency = (4858 / 193289)
    source = 1571683986320969, added = 1571683986326797, sent = 1571683986547941, size = 370, latency = (5828 / 221144)
    source = 1571683986321355, added = 1571683986326846, sent = 1571683986548182, size = 370, latency = (5491 / 221336)
    source = 1571683986349250, added = 1571683986350331, sent = 1571683986549253, size = 358, latency = (1081 / 198922)
    source = 1571683986344532, added = 1571683986351528, sent = 1571683986549540, size = 359, latency = (6996 / 198012)
    source = 1571683986379396, added = 1571683986387466, sent = 1571683986550613, size = 370, latency = (8070 / 163147)
    source = 1571683986379440, added = 1571683986387536, sent = 1571683986550966, size = 370, latency = (8096 / 163430)
    source = 1571683986379536, added = 1571683986387567, sent = 1571683986566108, size = 370, latency = (8031 / 178541)
    source = 1571683986379552, added = 1571683986387591, sent = 1571683986566184, size = 370, latency = (8039 / 178593)
    source = 1571683986382903, added = 1571683986391024, sent = 1571683986566366, size = 359, latency = (8121 / 175342)
    source = 1571683986583730, added = 1571683986593164, sent = 1571683986593193, size = 367, latency = (9434 / 29)
    source = 1571683986583766, added = 1571683986593250, sent = 1571683986593348, size = 367, latency = (9484 / 98)
    source = 1571683986623885, added = 1571683986631531, sent = 1571683986631564, size = 367, latency = (7646 / 33)
    source = 1571683986623919, added = 1571683986631665, sent = 1571683986631705, size = 367, latency = (7746 / 40)
    source = 1571683986623925, added = 1571683986633186, sent = 1571683986633242, size = 367, latency = (9261 / 56)
    source = 1571683986623954, added = 1571683986633263, sent = 1571683986633280, size = 367, latency = (9309 / 17)
    source = 1571683986384636, added = 1571683986391724, sent = 1571683986718823, size = 359, latency = (7088 / 327099)
    source = 1571683986418999, added = 1571683986419606, sent = 1571683986718932, size = 369, latency = (607 / 299326)
    source = 1571683986419036, added = 1571683986419670, sent = 1571683986721381, size = 369, latency = (634 / 301711)
    source = 1571683986414254, added = 1571683986422122, sent = 1571683986756771, size = 359, latency = (7868 / 334649)
    source = 1571683986422894, added = 1571683986430615, sent = 1571683986789134, size = 370, latency = (7721 / 358519)
    source = 1571683986422935, added = 1571683986430689, sent = 1571683986818685, size = 370, latency = (7754 / 387996)
    source = 1571683986490776, added = 1571683986500170, sent = 1571683986819191, size = 367, latency = (9394 / 319021)
    source = 1571683986490812, added = 1571683986500244, sent = 1571683986819998, size = 367, latency = (9432 / 319754)
    source = 1571683986583730, added = 1571683986593177, sent = 1571683986820322, size = 367, latency = (9447 / 227145)
    source = 1571683986583766, added = 1571683986593252, sent = 1571683986821350, size = 367, latency = (9486 / 228098)
    source = 1571683986623885, added = 1571683986631546, sent = 1571683986821812, size = 367, latency = (7661 / 190266)
    source = 1571683986623919, added = 1571683986631669, sent = 1571683986836848, size = 367, latency = (7750 / 205179)
    source = 1571683986623925, added = 1571683986633202, sent = 1571683986836946, size = 367, latency = (9277 / 203744)
    source = 1571683986623954, added = 1571683986633265, sent = 1571683986837110, size = 367, latency = (9311 / 203845)
    source = 1571683986920326, added = 1571683986943400, sent = 1571683986943432, size = 366, latency = (23074 / 32)
    source = 1571683986920363, added = 1571683986943488, sent = 1571683986943625, size = 366, latency = (23125 / 137)
    source = 1571683986920326, added = 1571683986943414, sent = 1571683986989607, size = 366, latency = (23088 / 46193)
    source = 1571683986920363, added = 1571683986943490, sent = 1571683986989728, size = 366, latency = (23127 / 46238)
    source = 1571683987096329, added = 1571683987104089, sent = 1571683987104118, size = 362, latency = (7760 / 29)
    source = 1571683987096329, added = 1571683987104100, sent = 1571683987104323, size = 362, latency = (7771 / 223)
    source = 1571683987096116, added = 1571683987105413, sent = 1571683987105437, size = 370, latency = (9297 / 24)
    source = 1571683987096116, added = 1571683987105423, sent = 1571683987105584, size = 370, latency = (9307 / 161)
    source = 1571683987096150, added = 1571683987105473, sent = 1571683987105764, size = 370, latency = (9323 / 291)
    source = 1571683987096150, added = 1571683987105475, sent = 1571683987105989, size = 370, latency = (9325 / 514)
    source = 1571683987205336, added = 1571683987210175, sent = 1571683987210208, size = 367, latency = (4839 / 33)
    source = 1571683987205336, added = 1571683987210190, sent = 1571683987210250, size = 367, latency = (4854 / 60)
    source = 1571683987205370, added = 1571683987210328, sent = 1571683987210370, size = 367, latency = (4958 / 42)
    source = 1571683987205370, added = 1571683987210332, sent = 1571683987210397, size = 367, latency = (4962 / 65)
    source = 1571683987205428, added = 1571683987210375, sent = 1571683987210419, size = 367, latency = (4947 / 44)
    source = 1571683987205428, added = 1571683987210377, sent = 1571683987210467, size = 367, latency = (4949 / 90)
    source = 1571683987205443, added = 1571683987210498, sent = 1571683987210555, size = 367, latency = (5055 / 57)
    source = 1571683987205443, added = 1571683987210504, sent = 1571683987210579, size = 367, latency = (5061 / 75)
    source = 1571683987316953, added = 1571683987343341, sent = 1571683987343378, size = 368, latency = (26388 / 37)
    source = 1571683987316953, added = 1571683987343356, sent = 1571683987343427, size = 368, latency = (26403 / 71)
    source = 1571683987316995, added = 1571683987343502, sent = 1571683987343548, size = 368, latency = (26507 / 46)
    source = 1571683987316995, added = 1571683987343506, sent = 1571683987343574, size = 368, latency = (26511 / 68)
    source = 1571683987435393, added = 1571683987447289, sent = 1571683987447322, size = 358, latency = (11896 / 33)
    source = 1571683987435393, added = 1571683987447304, sent = 1571683987447369, size = 358, latency = (11911 / 65)
    source = 1571683987631737, added = 1571683987637565, sent = 1571683987637603, size = 369, latency = (5828 / 38)
    source = 1571683987631737, added = 1571683987637581, sent = 1571683987637646, size = 369, latency = (5844 / 65)
    source = 1571683987631772, added = 1571683987637721, sent = 1571683987637731, size = 369, latency = (5949 / 10)
    source = 1571683987631772, added = 1571683987644472, sent = 1571683987646754, size = 369, latency = (12700 / 2282)
    source = 1571683987660727, added = 1571683987669910, sent = 1571683987669937, size = 371, latency = (9183 / 27)
    source = 1571683987660727, added = 1571683987669920, sent = 1571683987670078, size = 371, latency = (9193 / 158)
    source = 1571683987660763, added = 1571683987669986, sent = 1571683987670289, size = 371, latency = (9223 / 303)
    source = 1571683987660763, added = 1571683987669988, sent = 1571683987670440, size = 371, latency = (9225 / 452)
    source = 1571683987762339, added = 1571683987763202, sent = 1571683987763238, size = 371, latency = (863 / 36)
    source = 1571683987762339, added = 1571683987763217, sent = 1571683987763435, size = 371, latency = (878 / 218)
    source = 1571683987762378, added = 1571683987763290, sent = 1571683987763665, size = 371, latency = (912 / 375)
`

I made some more measurements (all values in microseconds).
 - Source is the timestamp in microseconds, when the client sent the message
 - Added, is the timestamp when it was added in the ringbuffer on Hub A
 - Sent is the timestamp before lws_write on Hub A is called
 - Size is the return value of lws_write
 - Latency contains ( added-source / send - added )

It seems like normally, it takes below 1 millisecond till the WRITABLE callback is called and the socket ready for data. But for some reasons, this suddenly jumps up to 1.4 seconds as far as i have seen yet.

**Comment by deforation** [comment]
I now also tried to collect the data provided by libwebsockets latency.
Unfotunately, it seems like the columns do not really match the description.

Anyways, the same behaviour can be seen.

`

    656925318361 w 0 0 0 0 12 370 370
    656925548270 w 0 0 0 0 229881 369 369
    656925548308 w 0 0 0 0 4 369 369
    656925548331 w 0 0 0 0 3 369 369
    656925556273 w 0 0 0 0 7921 369 369
    656925556868 w 0 0 0 0 572 369 369
    656925556944 w 0 0 0 0 57 369 369
    656925558200 w 0 0 0 0 1236 369 369
    656925558313 w 0 0 0 0 93 369 369
    656926472961 w 0 0 0 0 57 370 370
    656926848981 w 0 0 0 0 60 357 357
    656926852783 w 0 0 0 0 53 357 357
    656926853415 w 0 0 0 0 37 357 357
    656926864062 w 0 0 0 0 25 354 354
    656926872057 w 0 0 0 0 12 356 356
    656926872784 w 0 0 0 0 14 357 357
    656926873530 w 0 0 0 0 13 356 356
    656926874282 w 0 0 0 0 13 357 357
    656927404067 w 0 0 0 0 27 354 354
    656927658388 w 0 0 0 0 24 349 349
    656927680705 w 0 0 0 0 22 350 350
    656928051308 w 0 0 0 0 14 357 357
    656928061429 w 0 0 0 0 6 357 357
    656928489918 w 0 0 0 0 94 357 357
    656928635146 w 0 0 0 0 86 366 366
    656928635210 w 0 0 0 0 73 366 366
    656929066505 w 0 0 0 0 99 357 357
    656929067939 w 0 0 0 0 40 357 357
    656929366249 w 0 0 0 0 61 350 350
    656929370209 w 0 0 0 0 70 349 349
    656929526321 w 0 0 0 0 60 360 360
    656929871911 w 0 0 0 0 60 370 370
    656929871955 w 0 0 0 0 28 370 370
    656930444069 w 0 0 0 0 27 349 349
    656930445438 w 0 0 0 0 14 350 350
    656932020069 w 0 0 0 0 26 369 369
    656932028064 w 0 0 0 0 12 369 369
    656932028822 w 0 0 0 0 19 368 368
    656932028881 w 0 0 0 0 9 368 368
    656932325687 w 0 0 0 0 61 350 350
    656932329703 w 0 0 0 0 64 349 349
    656933294023 w 0 0 0 0 15 357 357
    656933326664 w 0 0 0 0 56 350 350
    656934176067 w 0 0 0 0 27 368 368
    656934184059 w 0 0 0 0 12 368 368
    656934185551 w 0 0 0 0 17 362 362
    656934548127 w 0 0 0 0 51 347 347
    656935372073 w 0 0 0 0 29 371 371
    656935380063 w 0 0 0 0 12 371 371
    656935382352 w 0 0 0 0 21 371 371
    656935382422 w 0 0 0 0 10 371 371
    656935508067 w 0 0 0 0 27 362 362
    656935521494 w 0 0 0 0 21 362 362
    656935531508 w 0 0 0 0 21 370 370
    656935531588 w 0 0 0 0 19 370 370
    656935535991 w 0 0 0 0 50 370 370
    656935536061 w 0 0 0 0 72 370 370
    656935537362 w 0 0 0 0 33 370 370
    656935537392 w 0 0 0 0 21 370 370
    656935540050 w 0 0 0 0 58 370 370
    656935540092 w 0 0 0 0 100 370 370
    656935544116 w 0 0 0 0 44 369 369
    656935544171 w 0 0 0 0 33 369 369
    656935546119 w 0 0 0 0 30 362 362
    656935546523 w 0 0 0 0 25 370 370
    656935546547 w 0 0 0 0 7 370 370
    656935648252 w 0 0 0 0 101664 362 362
`

**Comment by lws-team** [comment]
Is it possible you can implement server B script on server A?

Ie, do the same but eliminate the internet traversing?

**Comment by deforation** [comment]
I run it now for a while.

Now, the instance on Hub B run on the same server as Hub A.
I could observe latency spikes up to 2 milliseconds but nothing higher.

`

    661461275717 w 0 0 0 0 34 369 369
    661461275976 w 0 0 0 0 177 369 369
    661461296757 w 0 0 0 0 44 368 368
    661461297183 w 0 0 0 0 381 368 368
    661461302588 w 0 0 0 0 30 370 370
    661461302868 w 0 0 0 0 229 370 370
    661461305240 w 0 0 0 0 31 369 369
    661461305498 w 0 0 0 0 190 369 369
    661461307188 w 0 0 0 0 43 366 366
    661461307475 w 0 0 0 0 245 366 366
    661461308088 w 0 0 0 0 31 368 368
    661461308312 w 0 0 0 0 182 368 368
    661461315837 w 0 0 0 0 30 369 369
    661461316142 w 0 0 0 0 263 369 369
    661461323405 w 0 0 0 0 31 370 370
    661461323708 w 0 0 0 0 244 370 370
    661461325020 w 0 0 0 0 37 369 369
    661461325251 w 0 0 0 0 147 369 369
    661461328502 w 0 0 0 0 45 369 369
    661461328775 w 0 0 0 0 196 369 369
    661461330178 w 0 0 0 0 50 370 370
    661461330426 w 0 0 0 0 192 370 370
    661461337966 w 0 0 0 0 29 370 370
    661461338248 w 0 0 0 0 225 370 370
    661461340098 w 0 0 0 0 23 370 370
    661461340352 w 0 0 0 0 196 370 370
    661461349427 w 0 0 0 0 31 370 370
    661461349703 w 0 0 0 0 223 370 370
    661461351615 w 0 0 0 0 40 370 370
    661461351878 w 0 0 0 0 218 370 370
`

So it seems, as larget the distance between the server gets, the extremer these spikes get.

**Comment by lws-team** [comment]
Well, AFAIK it's just telling you about the path between the two servers over the Internet.

You won't get any WRITEABLE callback until poll() hears POLLOUT is set... if traffic is passing on the connection that boils down to a function of the tcp acks coming back from the peer.  For whatever reason (packetloss?) it seems these are sometimes delayed.

You can try another variation if you have a server available that's "closer" in hops and bandwidth than the original B, see how it acts eg to a server in California rather than Paris (I am just guessing the route to California is good from HK).  And try run eg, `mtr` https://en.wikipedia.org/wiki/MTR_(software) from server A towards B and see what the generic ICMP packet loss situation is.

**Comment by deforation** [comment]
Might definitely be something like this.

Because from HongKong to Japan, these spikes can also be identified, but they are much smaller.

**Comment by lws-team** [comment]
There's scope to meddle with Linux's default tcp settings, eg

https://cromwell-intl.com/open-source/performance-tuning/tcp.html

...but this to me anyway is more or less black magic.  If you find something that increases the effective tcp window though, it should directly impact the relationship between delayed /retried ack and sender stopping sending.

**Comment by deforation** [comment]
Do you think this might help?
Or might it be better to try using udp?

**Comment by lws-team** [comment]
Tcp is udp with retries built on top.

If your problem is packetloss you will also see it in your udp and have to retry manually.

The thing to look for in mtr is packetloss... if there isn't any we maybe miss the point.  You can set interval and packet size in mtr to match your situation more closely.

**Comment by deforation** [comment]
It doesn't seem like packet loss would be the main problem.
Showing some stats provided by linux show that there isn't any.

`

  sudo netstat -i
  Kernel Interface table
  Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
  ens5      9001 314696654      0      0 0      321954417      0      0      0 BMRU
  lo       65536    77303      0      0 0         77303      0      0      0 LRU
`

Also sudo ./dropwatch -l kas
doesn't show any dropped tcp packets.

**Comment by lws-team** [comment]
No... that's if your local interface is dropping them.  It has no clue about packetloss across the link like mtr does.

**Comment by deforation** [comment]
Ok i also did some tests using iperf.
This also seems to have a loss rate of 0%

**Comment by lws-team** [comment]
I don't know what causes this if not packetloss.  If you get more info, please add it here.
