### ISSUE TITLE
LWS_CALLBACK_TIMER did not come even though specified  time has passed

### ISSUE THREAD

**Issue by Sarah-Wang** [warmcat/libwebsockets#1726]
I set time with lws_set_timer_usecs(wsi, 20 * LWS_USEC_PER_SEC) in LWS_CALLBACK_TIMER reason. Like this:
``

	case LWS_CALLBACK_CLIENT_ESTABLISHED:
		lwsl_user("LWS_CALLBACK_CLIENT_ESTABLISHED\n");
		lwsl_user("set timer after CLIENT_ESTABLISHED\n");
		lws_set_timer_usecs(wsi, 5 * LWS_USEC_PER_SEC);
		break;

	case LWS_CALLBACK_TIMER:
		/* we want to send a ws PING every few seconds */
		lwsl_notice("LWS_CALLBACK_TIMER\n");
		pss->ping_st = TO_PING;
		lws_set_timer_usecs(wsi, 20 * LWS_USEC_PER_SEC);
		lws_callback_on_writable(wsi);
		break;
	case LWS_CALLBACK_CLIENT_WRITEABLE:
		lwsl_user("LWS_CALLBACK_CLIENT_WRITEABLE\n");
		//send ping here and set pss->ping_st = PING_OK;
		break;

``

I want to send ping to the wss server every 20 seconds.
The above code worked well for about 40 minutes, but then it got  a LWS_CALLBACK_CLIENT_CLOSED reason, and the connection was closed.

the log is:
**[2019/10/22 14:33:47:5084] N: LWS_CALLBACK_TIMER**
[2019/10/22 14:33:47:5088] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:33:47:5105] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:33:47:5564] U: LWS_CALLBACK_CLIENT_RECEIVE
[2019/10/22 14:33:47:5583] U: LWS_CALLBACK_CLIENT_WRITEABLE
**[2019/10/22 14:34:07:5124] N: LWS_CALLBACK_TIMER**
[2019/10/22 14:34:07:5128] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:34:07:5146] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:34:07:5603] U: LWS_CALLBACK_CLIENT_RECEIVE
[2019/10/22 14:34:07:5623] U: LWS_CALLBACK_CLIENT_WRITEABLE
**[2019/10/22 14:34:27:5164] N:  LWS_CALLBACK_TIMER**
[2019/10/22 14:34:27:5168] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:34:27:5185] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:34:27:5695] U: LWS_CALLBACK_CLIENT_RECEIVE
[2019/10/22 14:34:27:5715] U: LWS_CALLBACK_CLIENT_WRITEABLE
[2019/10/22 14:34:43:0521] U: LWS_CALLBACK_CLIENT_WRITEABLE
**[2019/10/22 14:36:18:0874] U: LWS_CALLBACK_CLIENT_CLOSED**

**Comment by lws-team** [comment]
Okay, but this is like saying you talked for 40 minutes 'and then the phone call ended'.  It doesn't actually say, "... and then I put the phone down".  The peer can have hung up on you due to its own policy about allowed connection time.  Or an intermediate router, or some government censorship policy baked into the local network could enforce it.

All you can do is reconnect and pick up where you left off... since the connection could be interrupted temporarily for many other reasons you probably want to do that anyway.

**Comment by Sarah-Wang** [comment]
Thank you for your advice! But I wonder why the  lws_set_timer_usecs(wsi, 20 * LWS_USEC_PER_SEC)  didn't invoke another  LWS_CALLBACK_TIMER reason at time [2019/10/22 14:34:47] since last LWS_CALLBACK_TIMER at [2019/10/22 14:34:27].

**Comment by lws-team** [comment]
I see, I missed your point.  Although reconnect is likely still a good idea.

What version of lws is it?

**Comment by Sarah-Wang** [comment]
Yes, I will take your advice.
It is libwebsockets-3.2-stable.

**Comment by lws-team** [comment]
I looked that the code but it's difficult to see how it can fail... looking closer at your log, the last one is different, it has an additional LWS_CALLBACK_CLIENT_WRITEABLE as the last thing 16s after the normal pattern is coming.

Is it possible this could cause your code to re set the hrtimer on the wsi, either for long enough in the future to mean it closes first, or to LWS_SET_TIMER_USEC_CANCEL to disable it?

**Comment by zhiwenzheng** [comment]
I encounter the same problem on master branch.
It is a ws server, after running for a hour and several minutes, the timer stopped firing,
the connection is ok, can still receive keepalive messages from client.

**Comment by lws-team** [comment]
Hum... then that makes it sound like 32-bit overflow somewhere... 2^32 / us_per_sec = 4096 which is suspiciously close to 3600 (secs per hr), also compatible with "40m" from Sarah.  But I can't see where it is from just looking at the code.  I'll try reproduce it.

**Comment by zhiwenzheng** [comment]
how about (ts.tv_sec * LWS_US_PER_SEC)  ?
LWS_US_PER_SEC is defined as 1000000, not 1000000ll.
```
 28 lws_usec_t
 29 lws_now_usecs(void)
 30 {
 31 #if defined(LWS_HAVE_CLOCK_GETTIME)
 32     struct timespec ts;
 33 
 34     if (clock_gettime(CLOCK_MONOTONIC, &ts))
 35         return 0;
 36 
 37     return (ts.tv_sec * LWS_US_PER_SEC) + (ts.tv_nsec / LWS_NS_PER_US);
 38 #else
 39     struct timeval now;
 40 
 41     gettimeofday(&now, NULL);
 42     return (now.tv_sec * 1000000ll) + now.tv_usec;
 43 #endif
 44 }
```

**Comment by lws-team** [comment]
Yes I patched this already with a 'paranoid casting' patch here.  And added code to dump the sul list and assert on any disorder.

I added a minimal example with 20s timer interval that keeps setting 60s timeout.

It's running now (for 20min so far) but I wonder if it depends on type of time_t or other libc types.  I'm on x86_64 maybe doesn't go wrong eithrr way.

**Comment by lws-team** [comment]
It has survived 1h 5m here on x86_64 Fedora 31, I don't think it particularly proves anything by itself but I pushed the patch on master... there's a minimal-ws-server-timer in there that lets it be tested without user code and some other things that looked like they should be cleaned / cast including the one you also spotted.

**Comment by zhiwenzheng** [comment]
change LWS_US_PER_SEC to 1000000ll can solve my problem, it has run 2 hours now.
my platform is illumos on x86_64, 64bit kernel, the app is 32bit, time_t is defined as long.

**Comment by lws-team** [comment]
Great... mine is still going as well with the patch I pushed, it includes a cast to uint64_t ultimately on that.

For gcc, long is usually the same as int

http://www.crasseux.com/books/ctutorial/Integer-variables.html

so time_t being 32-bit is the source of the problem.

On my platform sizeof(time_t) is 8 which is why no problem was coming for me.

**Comment by lws-team** [comment]
It turns out there are two copies of LWS_US_PER_SEC definition... I updated the master patch to do both and the related ones like US_PER_MS.

I also backported the patch to v3.2-stable.

**Comment by Sarah-Wang** [comment]
Thank you for your work!
I tried to reconnect to the service and the connection was kept.
I will apply the patch for v3.2-stable later.

**Comment by lws-team** [comment]
I'm guessing this is fixed, if it isn't please let me know here.
