### ISSUE TITLE
A null point problem at function lws_sul_wsping_cb

### ISSUE THREAD

**Issue by windflowerly** [warmcat/libwebsockets#1730]
sorry, my english is so bad. I will do my best to describe this problem clearly...

The problem of null pointer occurs under certain conditions at lws_sul_wsping_cb

code : libwebsockets\lib\roles\ws\ops-ws.c, line : 849
void lws_sul_wsping_cb(lws_sorted_usec_list_t *sul)
{
	struct lws *wsi = lws_container_of(sul, struct lws, sul_ping);

	/*
	 * The sul_ping timer came up... either it's time to send a PING
	 * (!wsi->ws->send_check_ping), or we didn't get the PONG in time
	 * (wsi->ws->send_check_ping)
	 */

        *************** there, wsi->ws, maybe null***************
	if ( **!wsi->ws->send_check_ping** ) {
		lwsl_info("%s: req pp on wsi %p\n", __func__, wsi);

		wsi->ws->send_check_ping = 1;
		lws_set_timeout(wsi, PENDING_TIMEOUT_WS_PONG_CHECK_SEND_PING,
				wsi->context->timeout_secs);
		lws_callback_on_writable(wsi);

		return;
	}

	if (wsi->ws->await_pong) {
		/* it didn't return the PONG in time */

		lwsl_info("%s: wsi %p: failed to send PONG\n", __func__, wsi);
		__lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS,
				     "PONG timeout");
	}
}
---------------------------------------------
how to cause this situation?
when I debug my websocket client. I create a client to connect server. 

client code (java script ):

         function WebSocketTest()
         {
            //   here, i make a breakpointer. 
            var ws = new WebSocket("ws://192.168.1.181:7681/websocket", "gangtise");  

            //   here, wait about 5 minutes, server LWS_CALLBACK_CLOSED event will be trig, wsi->ws is null
            if ("WebSocket" in window)
            {
               console.log("start WebSocket!");
               
               // 打开一个 web socket
               ws.onopen = function()
               {
                  // Web Socket 已连接上，使用 send() 方法发送数据
                  ws.send("abcdefg");
                  console.log("data sending ...");
               };
                
               ws.onmessage = function (evt) 
               { 
                  var received_msg = evt.data;
                  console.log("接收到服务端数据..." + evt.data);
//				   ws.close();
               };
                
               ws.onclose = function()
               { 
                  // 关闭 websocket
                  console.log("连接已关闭...");
               };
            }
            
            else
            {
               // 浏览器不支持 WebSocket
               console.log("您的浏览器不支持 WebSocket!");
            }
         }

the test case base on libwebsockets version 3.2....

hope I describle this situation clearly.

**Comment by lws-team** [comment]
Not really sure when that can happen... AFAIK it shouldn't race during close, maybe there is a condition where the ws upgrade fails, so no wsi->ws but still the ping timer.

I pushed a patch on v3.2-stable to at least suppress the NULL pointer access.

On master all this related code has been refactored to support the generic validity stuff, if still difficulties try master.

**Comment by windflowerly** [comment]
I reproduce over 3 times. i'm sure.

Thanks for you apply quickly.

I changed source code. it seem work...

lws_sul_wsping_cb(lws_sorted_usec_list_t *sul)
{
	struct lws *wsi = lws_container_of(sul, struct lws, sul_ping);

	/*
	 * The sul_ping timer came up... either it's time to send a PING
	 * (!wsi->ws->send_check_ping), or we didn't get the PONG in time
	 * (wsi->ws->send_check_ping)
	 */

       //  appand this code. it seem work.
	**if ( !wsi->ws ){
		return ;
	}**

	if (!wsi->ws->send_check_ping) {
		lwsl_info("%s: req pp on wsi %p\n", __func__, wsi);

		wsi->ws->send_check_ping = 1;
		lws_set_timeout(wsi, PENDING_TIMEOUT_WS_PONG_CHECK_SEND_PING,
				wsi->context->timeout_secs);
		lws_callback_on_writable(wsi);

		return;
	}

	if (wsi->ws->await_pong) {
		/* it didn't return the PONG in time */

		lwsl_info("%s: wsi %p: failed to send PONG\n", __func__, wsi);
		__lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS,
				     "PONG timeout");
	}
}
