### ISSUE TITLE
[Win10][VS2019] Compilation/integration errors: C2133: 'humanize_schema_si' unknown size

### ISSUE THREAD

**Issue by MaciekSipior** [warmcat/libwebsockets#1731]
During compilation of a project where we're using libwebsockets, I've encountered several compilation errors, e.g.:

> pkgs\ext\LibWebSockets\include\Windows\libwebsockets/lws-misc.h(897,70): error C2133: 'humanize_schema_si': unknown size

This originates from lws-misc.h:
```
LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si[];
LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si_bytes[];
LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_us[];
```
Encountered on Windows 10, MS Visual Studio 2019. Library itself compiles fine, but the problem occurs when it is used in the project.

I was able to make it work by simply adding the actual sizes of those arrays to declarations (based of definitions found in lib/core/libwebsockets.c), but I'm not sure if that's the way to fix this?

Patch for reference:
```
---
 include/libwebsockets/lws-misc.h | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/include/libwebsockets/lws-misc.h b/include/libwebsockets/lws-misc.h
index fe09303..0bc2603 100644
--- a/include/libwebsockets/lws-misc.h
+++ b/include/libwebsockets/lws-misc.h
@@ -894,9 +894,9 @@ typedef struct lws_humanize_unit {
        uint64_t factor;
 } lws_humanize_unit_t;

-LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si[];
-LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si_bytes[];
-LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_us[];
+LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si[7];
+LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_si_bytes[7];
+LWS_VISIBLE LWS_EXTERN const lws_humanize_unit_t humanize_schema_us[8];

 /**
  * lws_humanize() - Convert possibly large number to himan-readable uints
--
```

**Comment by lws-team** [comment]
Thanks... as it is, it's legal C.  But I don't know if it violates some version of C++ or just the microsoft compiler... either way, giving the length is not unreasonable for what this is.  I confirmed it builds OK on Linux / gcc with the change and pushed it on master.

**Comment by MaciekSipior** [comment]
Our linux targets were working without this patch, so it seems to be MS compiler related.

Thanks!

**Comment by vaind** [comment]
This fix doesn't seem to be ported to the latest stable 3.2. Could you do that please? Not sure if master is stable enough to follow directly...

**Comment by lws-team** [comment]
It's also pushed on v3.2-stable... I didn't realize this stuff was also on v3.2 since it was done very near that time.

Master has some basic stability level it never drops below because of the CI in mainly Travis, it runs a lot of tests on the build for various kinds of functionality.  It's also built 17 different ways on Linux, OSX and Windows 32-bit and 64-bit in CI, and I autobuild every push privately on 32-bit arm toolchain automatically as well.

The more people reporting issues on master so they can be solved, the less people will be hitting and reporting issues on v4.0.
