### ISSUE TITLE
websocket connected after waiting for long time

### ISSUE THREAD

**Issue by KyleLS** [warmcat/libwebsockets#1732]
Hi,

I have been using libwebsocket and it is great to use.

I am writing a client using libwebsocket, and a server not using this lib. 
When I deployed the server on a local virtual machine, the client connected immediately. But when I deployed the server on another LAN machine, the client takes long time to connect. If the server is deployed on the public Internet, it seems taking forever to connect.

I have captured the packets, but seeing that the tcp connection failed to establish for many times, and succeed at last (this did not happen on the same machine server).

![67be2bfedc4c8d79031b9608dbaa2e1](https://user-images.githubusercontent.com/11597679/67475904-9b6bda80-f689-11e9-93ce-763c96667dd0.png)

I also printed some output from the client...
![fa07a2445a042009c74734804ceb6be](https://user-images.githubusercontent.com/11597679/67476392-8d6a8980-f68a-11e9-93c5-e25cb7964d62.png)

Any idea about which part going wrong?

**Comment by lws-team** [comment]
Dunno... but... a lot of the client minimal examples reach out to libwebsockets.org or warmcat.com... you should try these where the server is a known quantity... still seeing problems?

**Comment by lws-team** [comment]
Well if there's more info please post it here, but nothing for me to do as it is.

**Comment by KyleLS** [comment]
It is working now, seems something went wrong in my network, nothing to do with the code.
Thanks.

**Comment by lws-team** [comment]
Thanks for updating.
