### ISSUE TITLE
value returned by lws_get_urlarg_by_name() contains the HTTP version

### ISSUE THREAD

**Issue by zhiwenzheng** [warmcat/libwebsockets#1733]
**Request headers**
> GET wss://d525/iostat?nic=rge0 HTTP/1.1
Host: d525
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Upgrade: websocket
Origin: https://d525
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: token=3d3fcbf735e145a448f63d58873b78b5cb324456e64ae561a4bed0a0cf7adab6
Sec-WebSocket-Key: lzsv2mcYj2XHautJ5IpEcA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: nic

**the parse code**
```
	case LWS_CALLBACK_ESTABLISHED:
		lwsl_user("nic LWS_CALLBACK_ESTABLISHED\n");

        if (lws_hdr_copy(wsi, buf, sizeof(buf), WSI_TOKEN_HTTP_COOKIE) > 0)
            lwsl_user("cookie: %s\n", buf);

        val = lws_get_urlarg_by_name(wsi, "nic", (char *)buf, sizeof(buf));
        if (!val)
            lwsl_err("nic: undefined\n");
        else
            lwsl_err("nic: (len %d) '%s'\n", (int)strlen((const char *)buf), buf);
```
**log**

> [2019/10/25 08:44:27:3083] E: nic: (len 16) 'nic=rge0HTTP/1.1'

"HTTP/1.1" is included in the result, is this expected?

**Comment by zhiwenzheng** [comment]
There is warning

> [2019/10/25 09:14:34:0108] W: Missing URI in HTTP request
[2019/10/25 09:14:34:0111] U: nic LWS_CALLBACK_ESTABLISHED
[2019/10/25 09:14:34:0113] U: cookie: token=3d3fcbf735e145a448f63d58873b78b5cb324456e64ae561a4bed0a0cf7adab6
[2019/10/25 09:14:34:0115] E: nic: (len 31) 'nic=rge0,lws=workaroundHTTP/1.1'

**Comment by zhiwenzheng** [comment]
This is related with websocket proxy.
If connecting directly to the ws server, I get

> [2019/10/25 10:28:02:6100] E: nic: (len 8) 'nic=rge0'

**Comment by zhiwenzheng** [comment]
the request proxy server send to ws server
>    localhost -> localhost    TCP D=6080 S=63617 Push Ack=1132234564 Seq=2129329089 Len=340 Win=32768 Options=<nop,nop,tstamp 53634963 53634962>

           0: 011a 0002 0000 019c 0000 0001 0000 0000    ................
          16: 0000 0000 0000 0000 6000 0000 0174 063c    ........`....t.<
          32: 0000 0000 0000 0000 0000 0000 0000 0001    ................
          48: 0000 0000 0000 0000 0000 0000 0000 0001    ................
          64: f881 17c0 7eea fbc1 437c 8744 8018 8000    ....~...C|.D....
          80: 0174 0000 0101 080a 0332 6793 0332 6792    .t.......2g..2g.
          96: 4745 5420 3f6e 6963 3d72 6765 3020 4854    GET ?nic=rge0 HT
         112: 5450 2f31 2e31 0d0a 5072 6167 6d61 3a20    TP/1.1..Pragma: 
         128: 6e6f 2d63 6163 6865 0d0a 4361 6368 652d    no-cache..Cache-
         144: 436f 6e74 726f 6c3a 206e 6f2d 6361 6368    Control: no-cach
         160: 650d 0a48 6f73 743a 2064 3532 353a 3434    e..Host: d525:44
         176: 330d 0a55 7067 7261 6465 3a20 7765 6273    3..Upgrade: webs
         192: 6f63 6b65 740d 0a43 6f6e 6e65 6374 696f    ocket..Connectio
         208: 6e3a 2055 7067 7261 6465 0d0a 5365 632d    n: Upgrade..Sec-
         224: 5765 6253 6f63 6b65 742d 4b65 793a 2052    WebSocket-Key: R
         240: 762f 446d 5361 4f51 344e 3166 7274 5952    v/DmSaOQ4N1frtYR
         256: 5455 6133 773d 3d0d 0a53 6563 2d57 6562    TUa3w==..Sec-Web
         272: 536f 636b 6574 2d50 726f 746f 636f 6c3a    Socket-Protocol:
         288: 206e 6963 0d0a 5365 632d 5765 6253 6f63     nic..Sec-WebSoc
         304: 6b65 742d 5665 7273 696f 6e3a 2031 330d    ket-Version: 13.
         320: 0a61 6363 6570 742d 6c61 6e67 7561 6765    .accept-language
         336: 3a20 656e 2d55 532c 656e 3b71 3d30 2e39    : en-US,en;q=0.9
         352: 0d0a 636f 6f6b 6965 3a20 746f 6b65 6e3d    ..cookie: token=
         368: 3364 3366 6362 6637 3335 6531 3435 6134    3d3fcbf735e145a4
         384: 3438 6636 3364 3538 3837 3362 3738 6235    48f63d58873b78b5
         400: 6362 3332 3434 3536 6536 3461 6535 3631    cb324456e64ae561
         416: 6134 6265 6430 6130 6366 3761 6461 6236    a4bed0a0cf7adab6
         432: 0d0a 0d0a

**Comment by zhiwenzheng** [comment]
change the request url from "wss://d525/iostat?nic=rge0" to "wss://d525/iostat/?nic=rge0" can workaround the issue.

**Comment by lws-team** [comment]
I pushed a patch on master that should solve this... thanks for tracking it down clearly.

**Comment by zhiwenzheng** [comment]
Yes. The patch fixed the problem.

**Comment by ADeRoy** [comment]
thanks.
