### ISSUE TITLE
what different between LWS_CALLBACK_CLIENT_WRITEABLE and LWS_CALLBACK_SERVER_WRITEABLE

### ISSUE THREAD

**Issue by windflowerly** [warmcat/libwebsockets#1734]
what different between LWS_CALLBACK_CLIENT_WRITEABLE and LWS_CALLBACK_SERVER_WRITEABLE ?

whick message trig action that send data to client?

**Comment by lws-team** [comment]
If you're writing a ws client

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client-tx/minimal-ws-client.c?h=master#n216

when your client can write something, you get `LWS_CALLBACK_CLIENT_WRITEABLE`.  If you are writing a ws server

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server/protocol_lws_minimal.c?h=master#n97

when you can write something back to a particular client, you get `LWS_CALLBACK_SERVER_WRITEABLE`.

Either way, you request to get the callback using `lws_callback_on_writable()` on the related wsi.

They are handled separately to make it possible to write one protocol callback, which handles both client and server callbacks.

**Comment by windflowerly** [comment]
Thanks
