### ISSUE TITLE
ws proxy: chrome complains "Received unexpected continuation frame."

### ISSUE THREAD

**Issue by zhiwenzheng** [warmcat/libwebsockets#1737]
![Screenshot_2019-10-28_09-49-30](https://user-images.githubusercontent.com/9572755/67646277-49b4a000-f968-11e9-8bc8-9fe6e9e31d0f.png)

seems the packets of the last transaction arrived out of order (870 should be ahead of 860)

**Comment by zhiwenzheng** [comment]
it works fine when connecting directly to the ws server.
I am on master branch.

**Comment by zhiwenzheng** [comment]
LWS_CALLBACK_SERVER_WRITEABLE in lws_callback_ws_proxy() use lws_dll2_get_head() instead of lws_dll2_get_tail() ?

**Comment by lws-team** [comment]
Yeah it's wrong as you say, I pushed a patch fixing it.

**Comment by zhiwenzheng** [comment]
is  LWS_CALLBACK_CLIENT_WRITEABLE trying to send packets received by LWS_CALLBACK_RECEIVE ? If so, lws_dll2_get_tail() need change to lws_dll2_get_head().

**Comment by lws-team** [comment]
Yes, same problem as in the other direction.  I added it to the patch.
