### ISSUE TITLE
lws_callback_ws_proxy: proxied ws connection excessive buffering: dropping

### ISSUE THREAD

**Issue by zhiwenzheng** [warmcat/libwebsockets#1738]
```
[2019/10/28 10:43:32:9396] E: lws_callback_ws_proxy: proxied ws connection excessive buffering: dropping
[2019/10/28 10:43:32:9398] N: lws_ws_handshake_client: client_rx_sm exited, DROPPING 1041
[2019/10/28 10:43:32:9400] U: lws_callback_ws_proxy: client closed: parent 8131758
[2019/10/28 10:43:32:9404] U: lws_callback_ws_proxy: closed
```

**Comment by zhiwenzheng** [comment]
wsi->parent->ws->proxy_buffered never get decremented.

the decrement should be done in LWS_CALLBACK_SERVER_WRITEABLE ?
       
add ```wsi->ws->proxy_buffered -= pkt->len;``` in LWS_CALLBACK_SERVER_WRITEABLE seems work.

**Comment by lws-team** [comment]
Don't think that's it... it is incremented in CLIENT_RECEIVE and already decremented in CLIENT_WRITEABLE when it sends it back out.  I think it just defeats the memory limit check.

What it's about is there's no flow control between the "client" side of the proxy and the proxied source at the moment.  I implemented this for a new project structured like gitohashi which is proxied over a Unix Domain Socket, but also uses ws.  But I had to switch to work on other things for $$$.  My project has an api based on JSON, it only sends relatively small ws messages around so it is happy with this as it is.

But if the local ws service that is being proxied just sends large messages, and the onward connection is slower or has larger latency, currently there's no flow control to inform it the proxy client side has filled up with its stuff and it should stop producing it for now.  Its policy today is if 8M is buffered, it will drop the connection to protect the whole server from OOM.

The correct solution is apply high / low water mark threshold testing to proxy_buffered and enable / disable `lws_rx_flow_control()` on the client wsi accordingly.  Setting flow control (enable=0) basically removes POLLIN so the client will not take any more rx.  When the server side has consumed some, you can remove the flow control (enable=1) and accept some more rx.

**Comment by lws-team** [comment]
Ugh... coffee has just sunk in... sorry, you're right it's decremented in the wrong place.

The flow control way is still needed.  But with this bug it will trigger the limit wrongly even if you just stick around sending small things.  I pushed a patch on master.

**Comment by zhiwenzheng** [comment]
I would like to lookup into the flow control problem If I have time, but I am busy with my project and a bit pressed for time, so I think I can live with the 8MB limit now.

**Comment by zhiwenzheng** [comment]
```
wsi->parent->ws->proxy_buffered -= pkt->len;
```
will cause memory violation in LWS_CALLBACK_SERVER_WRITEABLE, is it legal to use wsi->parent? I guess it should be ```wsi->ws->proxy_buffered -= pkt->len;``` ?

**Comment by lws-team** [comment]
Thanks, I fixed it in the related patch.
