### ISSUE TITLE
Disconnecting after 3 seconds.

### ISSUE THREAD

**Issue by hesa2020** [warmcat/libwebsockets#1741]
Hello i have a node.js ws server and a client using libwebsockets
I capture video in c++ and stream it to the browser as binary data.
Before i do this i can be connected for a long time and exchange simple utf8 messages.

But when i start sending binary data it disconnect after a very short time.

Here is my client source code:
[Header](https://hastebin.com/nadubowido.cpp)
[Source](https://hastebin.com/ixuruvetud.cpp)

No error it just disconnect with LWS_CALLBACK_CLIENT_CLOSED

Here is the code i use to send binary data:
`RemoteClient::GetInstance()->Send(encoderFrame, sizeof(frame_t) + encoded_size, server_type_binary);`

I dont know how i can debug this disconnect issue since everything is fine on node.js side and i do not get any error in c++
It just disconnect.

**Comment by lws-team** [comment]
Lws can produce extremely verbose logs... build as debug and enable more of them with, eg, -d1039 or -d1151 and look for what happened around where it closed.

Also your server should produce verbose logs on demand.

Generally, dumping code here looking for someone else to debug it when you didn't look for logs yourself is an unreasonable expectation about other peoples' time.

**Comment by hesa2020** [comment]
What do you mean with "-d1039 or -d1151" ?

**Comment by lws-team** [comment]
Look at any minimal example

**Comment by hesa2020** [comment]
Im not sure what im searching for in example but here is the log i got using :
lws_set_log_level(LLL_INFO | LLL_DEBUG | LLL_NOTICE, NULL);

[The Log](https://hastebin.com/picevegoko.pl)

Does this talk to you ?

**Comment by lws-team** [comment]
Your server told you its problem... lws logged it for you... your server won't handle a ws frame > 79K.

You're evidently sending such a thing... don't do that with that server then.  Look at using ws fragments.

**Comment by hesa2020** [comment]
Hey thanks when i saw that i though it wouldnt be why it disconnect, though the frame would just get ignored instead.

Raised the limit on node.js side and now it works fine, i will look into spliting into fragments hopefully lws handles this for me :)
