### ISSUE TITLE
Using the library through the dameon mode

### ISSUE THREAD

**Issue by ypiker** [warmcat/libwebsockets#1742]
Using the library through the dameon mode, the service can't start up。 the lws_service interface
will shut down the process。

The code is as follows：
void service_start()
{
	int port =8888;
	const char *interface = NULL;
	struct lws_context_creation_info info;
	struct lws_protocols protocol;
	struct lws_context *context;
	
	//* setup websocket protocol */
	protocol.name = "ws";
	protocol.callback = ws_service_callback;
	protocol.per_session_data_size = 0;
	protocol.rx_buffer_size = 0;

	//* setup websocket context info*/
	memset(&info, 0, sizeof info);
	info.port = port;
	//info.iface = interface;
	info.protocols = &protocol;
	//* create libwebsocket context. */
	context = lws_create_context(&info);
	if (context == NULL) {
		return;
	}
       
	//* websocket service */
	while (!destroy_flag) {
		lws_service(context, 50);
	}
	lws_context_destroy(context);
	
}

int main()
{
	if (daemon(0, 0) == -1)
		exit(EXIT_FAILURE);
	service_start();
    return 0;
}

**Comment by lws-team** [comment]
Daemonizing is a bit more complicated than manga makes it out to be.

You must deal with various dangling guts like stdin / out /err.

Although generally daemonizing is deprecated in favour of letting systemd take care of it, lws still provides a wrapper that does all the messy stuff

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h?h=master#n213-221
https://libwebsockets.org/git/libwebsockets/tree/lib/misc/daemonize.c?h=master

set `-DLWS_WITHOUT_DAEMONIZE=0` in cmake to enable it in the library.

**Comment by ypiker** [comment]
what is the  manga？  i  set  -DLWS_WITHOUT_DAEMONIZE=0 in cmak。Then  i need  to  use some api for   dealing  it 。

**Comment by lws-team** [comment]
Eg, Dorohedoro is a great manga with that theme... not for the faint of heart though.

Yes look at the first link in the previous post, it basically replaces your daemon() call.

**Comment by ypiker** [comment]
ok.Thank you very much ! I try it.
