### ISSUE TITLE
How can I include the port on the host?

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#1744]
I need to add the port on the Host:

![image](https://user-images.githubusercontent.com/52041342/67768295-8361d580-fa52-11e9-9303-ba70a0f05a5d.png)

**Comment by lws-team** [comment]
I am not really sure what you are asking since you don't really explain the circumstances... if you are being the client, you can set the host yourself

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h?h=master#n75

if that's not it, please explain a bit more.

**Comment by fusionJose** [comment]
I'm the client, and I'm trying to connect to a server that uses a specific port which is not 80. 
In my code I pass the full URL of the server to the lws_parse_uri function: 

`if (lws_parse_uri(url, &url_protocol, &(uio->cinfo.address), &(uio->cinfo.port), &url_tmp_path)) {
        logi("lws couldn't parse url %s", url);
        return -1;
    }`

It then completes all the client information: 
`uio->cinfo.path = strdup(cp_url_path); // Set the info's path to the fixed up url path

    uio->cinfo.context = lws_ctx;
    uio->cinfo.host = uio->cinfo.address;
    uio->cinfo.origin = uio->cinfo.address;
    uio->cinfo.ssl_connection = LCCSCF_PIPELINE;
    uio->cinfo.protocol = protocols[0].name;
    uio->cinfo.userdata = &uio->userdata;`

But when trying to establish the connection with the server, It doesn't includes the port in the Host:
![image](https://user-images.githubusercontent.com/52041342/67769460-d177d880-fa54-11e9-919c-2f3d4b2c5684.png)

And this server needs that. It is optional to include the TCP port number in the Host request header.

**Comment by lws-team** [comment]
It sounds like you need to set `uio->cinfo.host` to be "192.168.12.110:1234" or whatever.

**Comment by fusionJose** [comment]
Okey thanks. I thought there was a option to add it automatically
