### ISSUE TITLE
Is the behavior of lws_jwk_rfc7638_fingerprint() consistent across v3.1.0 and master? 

### ISSUE THREAD

**Issue by zhiwenzheng** [warmcat/libwebsockets#1746]
I use the following code to generate the key authorization file for http-01 chanllenge,
it works on v3.1.0, and not work on master, the letsencrypt server says the key authorization file not match.
```
                    p += lws_snprintf(p, end - p, "%s.", ac->chall_token);
                    lws_jwk_rfc7638_fingerprint(&vhd->jwk, digest);
                    n = lws_jws_base64_enc(digest, 32, p, end - p);
                    if (n < 0)
                        goto failed;
```

**Comment by zhiwenzheng** [comment]
>    "error": {

        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "The key authorization file from the server did not match this challenge \"6EX_Pa__e3Nkyc8wb3GErfh2MTnz7xiQbtZdryytItk.NhYuPpj_g82XDJhCOu7GsgbxPT9t1zZ9-pVf7jjoK2E\" != \"6EX_Pa__e3Nkyc8wb3GErfh2MTnz7xiQbtZdryytItk.NWJU1756IRhsJmNKUnJ4wzknc6qxkYZC2_6_3I68AdM\"",
        "status": 403

NhYuPpj_g82XDJhCOu7GsgbxPT9t1zZ9-pVf7jjoK2E is the expected value.

**Comment by zhiwenzheng** [comment]
{"d":"mGNyKPNMIPu0Qe-w3sPEjfGpfRpCOqZOGQjKUbefgWJpyoF6ztW5iez9zqC3gEXWxM6SSx8ZFdwaF-_xUVaiPYY_gJtdxm5_YvqzVBGHgj7rZXTNyuUK5uFzc8Zw1AKp2QlBRR1vZNxm68Z5N9DlXu_qFR4rgA3-tcBCcrfZ7ovxlnaA9yfpFFEEDufTBk5FNadamwlOpq8FgqGws0RKT4JVj4dgsi6FS-H08DxyZomyO9LF-zP8Hg306pwveONbGdIgvV-vW5NDg0USEqnvvhOxfVquJZrGqnX1vEncihx9KlF0u74Q8TaBaICwNM6BVLqx1VamQ1GFfXsue2gkXEV7I9hIi5NaUKSFODzr3dC3jPfi9EeYivqhSdEttYT511eRpWRkDVyjWSfv6QphtwdrWOZghX9MkJnEt0jSxlxROeFkczdDW-_jCF41wcOYJ-VvXO1r_ctEdL2mLlWNsz6Vgjt-l0gWMJ0vgJooZdXMZWKFOVxcz3yAZoFhTc_KrT_4_fqlHcgBh15oxZJ-IdATNkUoZ1v3nSuMeMcrbgAvUT3lKMkoSvfKtILRGVEOIRLVdcPyN4Ws3Q6nUfelaqOB-5o4qF0C-oEZFi2r8iN0LQS1ZIMV4i1VEOTYmGYln1Cw4NKq5gEg-KfnQHHNrnpfSpeqgW9z28RHV_cPnzk","e":"AQAB","kty":"RSA","n":"teCsXl4ToPLTeIAzr6DoqjbCHUR1rOVlndIOh4k3NWA58doQ5_zxg2Tmfe9PcSQkBbZv9puTLDKONAdyUNTB1O8TpTbqofi57lclLKcf5tFAZjGl0w-0pEGiaz8Hk_e6kh1yerWgyGm3bkUDTCV9HZ_OpIH2mi6paOpfnVxkQ8bhdeZnB9TsYzzYv99WSo2HimMuuHp9g0J1gG6jOWZMWtIM_0zm95mUrjpmsolZHtSyi-U18ebUtA8_4yMxyp0Vmt3JnBfpHXGpgus6MhSIovciphxtVi7a8mKMVH5ry_UMz35tQcpcdusCbwOdzgHPPYQyOF3uD2SptsyLWkQAC7wIkQ_3de_N9MQdhKKEyuRjNl4zhKNlQj__xUYUFiINd6lMxMAraxQb0N_sOTHy70L1wDRk1XGtRRhRJsMGCQa3E77DF_BrG0FWbw0qUbFlbyM9Xqu5eMSqioWhu548nk4oFadnewY6DQp2Vp0f9zLc0uGXgLnmJSsLuTGTaMUM6QzZGfZwPKJj8Ydx5skBJw9oerlX8G76GvOTDotfT_XJ3K5emU8TmNwTgEtwvuR6rQfzx9cBBUZpPXm2KQ0Ar0a4F0fsmMi8UVr6KcuvRW977r2V0EQgPC3z8P2qSqzLxpS0bTZ1mshRL_NUD1HbHzGjEVS9qWiSevqQx510Ipc","p":"7NwY-4PFB3x3kWchnqLkL6B7qoNkCUElmXGIa8Hgwm26bzKDhBs339Sd3DL98ETNDK-i1W-F42Jd0-3OlHEZMTUdVOeNMXnspb4ZSlWk9Mr02w9q3p30O-OzOfHJ9jt4ixksbXMmhK5gbZGOgzU9w4VnWvOZvU_pWdqZ6O7DEXDB9B8jHIosRrRPaGioMdajIH5p8yt7b9JOMvScOIjMmxbxy5a6pT3nTqO94TgTHfGAy3kiNUkditra7WMJcT9EJryqNFpHuDsTeX75bg6htu-rbQF1zbOYZRWBS27_L8Pkr8lxzwMhaDV8eo06R1MjesK9aVlsFB1OGxYHFT0xWw","q":"xJMp_0slQBshDXtM8ucRaavc_CC-d5wbVJcVkpGxje5LPKl_aak-W3zWa2FRjJ_bPYpTA6PSm6YxNgNr9e_nFma2Mx0hTNDu9ub4IsamvCf_bbCAzp5OlVg0dSvBUip6VekaM51jSU8s_IWcWV9iRFUnRMfdv5LC2ANXJ7-TGXN3aqzt5aDIg8iDWzytP6VjUiuK_5a8e8OQcpFhwsdFnbSj-EaYn5UauWM58GvjWgFFtJYFHmWPqpDUQj4J4hv-ASFUDwi8VNSyBIrCTxTJfJLE3r99m5ytPjZp3nfIyubNfwDzu38iGwtL0fQdCs0OMwT8aYrm3MHXoqXmCWX8dQ"}

**Comment by lws-team** [comment]
On v3.1 the only jwk support was for ACME... on master / v3.2 there's full generic JWK support for both mbedtls and openssl.  But by that time http-01 was deprecated... it's possible eg key element order is different.  But the generic JWK RSA stuff works on the later versions, there's quite a lot of unit tests about it, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/api-tests/api-test-jose/jwk.c

**Comment by zhiwenzheng** [comment]
lws_jwk_export() emits an extra '\n' on master.
```
801     p += lws_snprintf(p, end - p, "}\n");
```
Can we remove it ? ACMEv2 http-01 works after remove it.

**Comment by lws-team** [comment]
Well done for finding it... afaik you can always add or remove whitespace anywhere on JSON outside the quotes, it's there for human readability or you can completely eliminate it for size.  The far end should tolerate it, really.  I'll take a look at it in a few hours.

**Comment by lws-team** [comment]
I see... it hashes it... so it can't tolerate any deviation.  I pushed a patch on master that turns the _private arg to the export function into "flags", and added a flag to suppress the CRLF.  And use the flag in the fingerprint function.  So everything external is compatible but this can now be controlled.

If that's all that was needed for ACMEv2 that's great since my sites now use Let's Encrypt.  Last I looked a few months before the switchover they had changed the algorithm around more.

**Comment by zhiwenzheng** [comment]
OK. lws_jwe_create_packet() need some change, I plan to create a separate function in the acme client plugin. No other changes needed in the library.  I will send a pull request, so you can review it. This change only support http-01, I use dns-01 myself(for wildcard domain support), but that use a homebrew interface to set the dns record and some other changes in cert generation code, it need some more work to support the general case, I plan to push that change to my github repo when it can compile on master(it was written on v3.1.0), but I may not have time to implement the general case.
