### ISSUE TITLE
Client responses Ping Server (with a Pong) and replies with a new Ping

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#1753]
I am using a Client with libwebsockets, and I set the ws_ping_pong_interval with 300 seconds, a high value. A foreign server (which I am connected to) is sending a Ping every minute and my client is answering correctly with a Pong. But just next the client also sends a new Ping to the server. 

Here is the capture of the packets:
![image](https://user-images.githubusercontent.com/52041342/68210555-101e0d80-ffd6-11e9-9d0a-a8ec7aa45211.png)

**Comment by lws-team** [comment]
On master this stuff was rewritten to use a generic connection validation scheme that combines information from both directions and understands if connections are encapsulated in an outer network connection and don't need this.

If you care about that (this doesn't reflect an error, it's just less than optimal) use master and the connection validity stuff.

**Comment by fusionJose** [comment]
And how do I use the connection validity stuff? I am not really sure where can i configure that. Thanks a lot.

**Comment by lws-team** [comment]
Oh... I copied the url and forgot to paste it

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md
