### ISSUE TITLE
Testing on NodeJS websocket client/server

### ISSUE THREAD

**Issue by wini3d** [warmcat/libwebsockets#1754]
I am trying this simple NodeJS example as server, but cannot get any kind of respond. 

Is connecting to NodeJS websocket implementation supported (yet)?

```
// server.js

const WebSocket = require('ws')

const wss = new WebSocket.Server({ port: 8080 })

wss.on('connection', ws => {
  ws.on('message', message => {
    console.log(`Received message => ${message}`)
  })
  ws.send('Hello! Message From Server!!')
})
```

**Comment by lws-team** [comment]
I don't use node.js, but if it's ws it is supported.

Experience tells me the words "no response" are like "doesn't work" or "hangs" or "crashes", when these are followed by no more information or evidence or logs it just means you don't know what is or isn't happening.

Turn on verbose logs at lws side and whatever logs node.js has and look at what they are suggesting.

**Comment by wini3d** [comment]
I see. Here's the verbose output from the client example, it does not crash or exit, just stuck with connecting and seems to not find the server connection/listening. 

```
client 127.0.0.1 3000 -v
N: libwebsockets test client - license LGPL2.1+SLE
N: (C) Copyright 2010-2018 Andy Green <andy@warmcat.com>
N:  SSL disabled
N:  Cert must validate correctly (use -s to allow selfsigned)
N:  Requiring peer cert hostname matches
N: using  mode (ws)
N: dumb: connecting
N: mirror: connecting
```
server js works with the client js example..
```
const WebSocket = require('ws')
const url = 'ws://localhost:8080'
const connection = new WebSocket(url)
 
connection.onopen = () => {
  connection.send('Message From Client') 
}
 
connection.onerror = (error) => {
  console.log(`WebSocket error: ${error}`)
}
 
connection.onmessage = (e) => {
  console.log(e.data)
}
```

**Comment by lws-team** [comment]
Look at pretty much any minimal example, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client-echo/minimal-ws-client-echo.c?h=master#n99-105

But before that, there is no reason lws client example using lws subprotocols will connect to your server that has no idea about those subprotocols.

**Comment by wini3d** [comment]
Ok got it. Will the minimal echo examples work on the above node js counterpart? 

I just tested this [csharp implementation](https://github.com/sta/websocket-sharp) with node and it works straight out of the box with its simple example.

> But before that, there is no reason lws client example using lws subprotocols will connect to your server that has no idea about those subprotocols.

What can I do about this to be able to respond on the nodejs basic server?

**Comment by lws-team** [comment]
> I just tested this csharp implementation with node and it works straight out of the box with its simple example.

Great... use that.  Or read up on ws subprotocols so you understand why this isn't plug and play

https://tools.ietf.org/html/rfc6455#section-1.9

**Comment by wini3d** [comment]
> Great... use that. Or read up on ws subprotocols so you understand why this isn't plug and play

I see and sorry, that is just for cross testing and perhaps you can give me some tips on how I can make it work. I really need a c/c++ library.

I am trying to make the minimal example work, but getting this LWS_ROLE_WS CMake error.

`This project requires lws must have been configured with LWS_ROLE_WS`

**Comment by wini3d** [comment]
Finally, I got the minimal ws client echo example to work and it now connects with the nodejs server script. :+1:

lws client exe
```
U: LWS minimal ws client echo + permessage-deflate + multifragment bulk message
U:    lws-minimal-ws-client-echo [-n (no exts)] [-u url] [-p port] [-o (once)]
U: options 0, ads localhost
U: connecting to localhost:3000//
U: LWS_CALLBACK_CLIENT_ESTABLISHED
U: LWS_CALLBACK_CLIENT_WRITEABLE
U:  (nothing in ring)
U: LWS_CALLBACK_CLIENT_RECEIVE:   28 (rpp     0, first 1, last 1, bin 0)
U: LWS_CALLBACK_CLIENT_WRITEABLE
U:  wrote 28: flags: 0x0 first: 1 final 1
U: LWS_CALLBACK_CLIENT_WRITEABLE
U:  (nothing in ring)
```
server js
```
Received message => Hello! Message From Server!!
```

> Or read up on ws subprotocols so you understand why this isn't plug and play

It is not the point whether this library is plug and play, perhaps I am looking for more of an example or tips (since you are the author) that works with popular websocket implementations like nodejs which the minimal client echo example seemed setup to work. Most websocket/[socket.io](https://github.com/ikeralbeniz/cellophane.io/blob/master/examples/example_server.js) libraries include this for cross testing example.
