### ISSUE TITLE
NodeJS Connection Examples

### ISSUE THREAD

**Issue by wini3d** [warmcat/libwebsockets#1756]
More of a feature request/addendum to examples to test out with other implementations like NodeJS's websocket.

Reference: https://github.com/warmcat/libwebsockets/issues/1754#issuecomment-550306247

**Comment by lws-team** [comment]
This is FOSS... if you want that, contribute it.

**Comment by wini3d** [comment]
I already posted a basic example sources from the NodeJS side, as you are the author it would be easy to implement it on the lws c side, say for the client part. 

I can provide more reference if needed, here is a basic chat example:

https://medium.com/@martin.sikora/node-js-websocket-simple-chat-tutorial-2def3a841b61
