### ISSUE TITLE
3.2-stable: LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ not triggered for chunked http response

### ISSUE THREAD

**Issue by jnynw** [warmcat/libwebsockets#1757]
Hi,
I am using latest 3.2-stable and found the LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ is not triggered for chunked http response at all. checking the code, under lws_http_client_read(struct lws *wsi, char **buf, int *len)
```
struct lws *wsi_eff = lws_client_wsi_effective(wsi);

		if (
#if defined(LWS_WITH_HTTP_PROXY)
		    !wsi_eff->protocol_bind_balance ==
		    !!wsi_eff->http.proxy_clientside &&
#else
		    !!wsi_eff->protocol_bind_balance &&
#endif
		    user_callback_handle_rxflow(wsi_eff->protocol->callback,
				wsi_eff, LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ,
				wsi_eff->user_space, *buf, n)) {
			lwsl_info("%s: RECEIVE_CLIENT_HTTP_READ returned -1\n",
				   __func__);

			return -1;
		}
```

my "wsi_eff->protocol_bind_balance" is false, so the call back is never called.

should I rebuild with LWS_WITH_HTTP_PROXY to support chunked callback?

**Comment by lws-team** [comment]
Does this problem exist if you use eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client

and hack it to point to your chunked url?

**Comment by jnynw** [comment]
Thanks for the quick response, I will check with the sample. I am sending a POST request, with libuv as event lib. Not sure if this would help

**Comment by lws-team** [comment]
Event lib shouldn't matter nor the PROXY thing... the test there is to only let the rx come if we are bound to the protocol and not, eg, in the middle of shutting down or closing the wsi.  It seems it's not set somehow if so reproducing it is probably necessary to understand what happened.  There's a minimal-http-client-post if that helps

**Comment by jnynw** [comment]
Thanks for always responding so quickly

the minimal sample worked with chunked reponse, but unfortunately, we have to switch the server to "unchunked", so I no longer have the same environment to check why my code doesn't work.



It appears, the 3.2-stable added the extra check for "!!wsi_eff->protocol_bind_balance " with this commit "ff71e3cc0d5f94b7042f3f9d2cec1927af093d4f" close: after DROP_PROTOCOL no longer report traffic to callback


In my code which worked previously with 3.1, I need to handle both "chunked" and "unchunked" http response. Since moved to 3.2, I noticed some differences, e.g. because I can't get the LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ callback triggered, I have to
use lws_http_client_read in LWS_CALLBACK_RECEIVE_CLIENT_HTTP callback with even unchunked response,. And when the response is chunked, the buffer I read from lws_http_client_read in LWS_CALLBACK_RECEIVE_CLIENT_HTTP callback is not in the correct form.


My own code looks like below:
case LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ: 
           // (BEFORE) copy the read content
           //  (AFTER)  not triggered
case LWS_CALLBACK_RECEIVE_CLIENT_HTTP: 
           // (BEFORE) call lws_http_client_read ()
           // (AFTER)   call lws_http_client_read() and copy the read content
case LWS_CALLBACK_COMPLETED_CLIENT_HTTP:
          //  lws_cancel_service()
 case LWS_CALLBACK_CLOSED_CLIENT_HTTP:
          // release some memory, etc..



Is it possible that I am calling "cancel_service() so soon? or I shouldn't call it at all because I am using external libuv ?

**Comment by Jianxiong-Chen** [comment]
hi,set	i.protocol = protocols[0].name;
