### ISSUE TITLE
Re-open: 3.2-stable regression:  LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ not triggered

### ISSUE THREAD

**Issue by jnynw** [warmcat/libwebsockets#1761]
Hi team,
I am sorry I have to reopen this issue. (I closed the old one as some of the info are misleading)

The background of the problem is that after upgrade from 3.1-stable to 3.2-stable, the  LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ stopped working.

The verbose log output is attached at the end. Here is the short version:

1) I am using libwebsockets 3.2-stable with libuv as loop
2) on chunked http response, the sequence of callback is :
2.1)  RECEIVE_CLIENT_HTTP -> ( I call lws_http_client_read() here, it return length of "0")
2.2) COMPLETED_CLIENT_HTTP 
2.3) RECEIVE_CLIENT_HTTP -> (second time, when I call lws_http_client_read(), the length returned "3", the buf contains chunk content after "\n\n\r"...)

The main difference of between 3.1 and 3.2 is at the point of calling RECEIVE_CLIENT_HTTP_READ, 3.2 has an extra check against "wsi_eff->protocol_bind_balance"

On top of not receiving the expected RECEIVE_CLIENT_HTTP_READ callback, the second RECEIVE_CLIENT_HTTP callback after COMPLETED is also worrying. 

Could you please give me some advice on handling this case? 
I have tried the minimal sample, it worked with default lws loop.

> [2019/11/12 09:56:32:6259] D: lws_client_interpret_server_handshake: 0x556fed387e90: transitioning to h1 client
> [2019/11/12 09:56:32:6259] D: lws_role_transition: 0x556fed387e90: wsistate 0x10000117, ops h1
> [2019/11/12 09:56:32:6260] D: lws_ensure_user_space: 0x556fed387e90 protocol pss 0, user_space=0x556fed33c1c0
> [2019/11/12 09:56:32:6260] I: lws_client_interpret_server_handshake: client connection up
> [2019/11/12 09:56:32:6260] D: _lws_change_pollfd: wsi 0x556fed387e90: fd 14 events 1 -> 0
> [2019/11/12 09:56:32:6260] D: elops_io_uv: 0x556fed387e90: 9
> [2019/11/12 09:56:32:6260] D: 0x556fed387e90: SSL_read says 382
> [2019/11/12 09:56:32:6260] D: _lws_change_pollfd: wsi 0x556fed387e90: fd 14 events 0 -> 1
> [2019/11/12 09:56:32:6260] D: elops_io_uv: 0x556fed387e90: 5
> [2019/11/12 09:56:32:6260] I: chunk 375
> 09:56:32.540877608 140201068177280 DBG http_recev  1 , len: 0
> [2019/11/12 09:56:32:6260] D: _lws_change_pollfd: wsi 0x556fed387e90: fd 14 events 1 -> 0
> [2019/11/12 09:56:32:6261] D: elops_io_uv: 0x556fed387e90: 9
> [2019/11/12 09:56:32:6261] D: 0x556fed387e90: SSL_read says 5
> [2019/11/12 09:56:32:6261] D: _lws_change_pollfd: wsi 0x556fed387e90: fd 14 events 0 -> 1
> [2019/11/12 09:56:32:6261] D: elops_io_uv: 0x556fed387e90: 5
> [2019/11/12 09:56:32:6261] I: chunk 0
> [2019/11/12 09:56:32:6261] I: final chunk
> [2019/11/12 09:56:32:6261] I: lws_http_transaction_completed_client: wsi: 0x556fed387e90, wsi_eff: 0x556fed387e90 (http)
> 09:56:32.540978050 140201068177280 DBG http client connection completed
> [2019/11/12 09:56:32:6261] I: lws_callback_http_dummy: COMPLETED_CLIENT_HTTP: 0x556fed387e90 (parent (nil))
> [2019/11/12 09:56:32:6261] I: lws_http_transaction_completed_client: nothing pipelined waiting
> [2019/11/12 09:56:32:6262] D: lwsi_set_state(0x556fed387e90, 0x10000010)
> [2019/11/12 09:56:32:6262] D: __lws_set_timeout: 0x556fed387e90: 5 secs, reason 27
> 09:56:32.541028688 140201068177280 DBG http_recev  1 , len: 3
> [2019/11/12 09:56:32:6262] D: 0x556fed387e90: SSL_read says 0
> [2019/11/12 09:56:32:6262] D: lws_ssl_get_error: 0x556fed38dab0 0 -> 5 (errno 0)
> [2019/11/12 09:56:32:6262] D: 0x556fed387e90: ssl err 5 errno 0
> [2019/11/12 09:56:32:6262] D: 0x556fed387e90: Close and handled
> [2019/11/12 09:56:32:6262] I: __lws_close_free_wsi: 0x556fed387e90: caller: close_and_handled
> [2019/11/12 09:56:32:6262] D: __lws_close_free_wsi: real just_kill_connection: 0x556fed387e90 (sockfd 14)
> [2019/11/12 09:56:32:6262] D: elops_io_uv: 0x556fed387e90: -2147483637
> [2019/11/12 09:56:32:6262] D: elops_io_uv: 0x556fed387e90: 11
> [2019/11/12 09:56:32:6262] D: lwsi_set_state(0x556fed387e90, 0x1000001e)
> 09:56:32.541114326 140201068177280 DBG http client connection closed
> [2019/11/12 09:56:32:6266] D: elops_wsi_logical_close_uv: lws_libuv_closehandle: wsi 0x556fed387e90
> [2019/11/12 09:56:32:6266] D: lws_libuv_closehandle: 0x556fed387e90
> [2019/11/12 09:56:32:6266] I: __lws_close_free_wsi: 0x556fed387e90: caller: close_and_handled uv repeat test
> [2019/11/12 09:56:32:6267] I: lws_libuv_closewsi: 0x556fed387e90
> [2019/11/12 09:56:32:6267] I: __lws_header_table_detach: wsi 0x556fed387e90: ah 0x556fed388510 (tsi=0, count = 1)
> [2019/11/12 09:56:32:6267] I: __lws_header_table_detach: nobody usable waiting
> [2019/11/12 09:56:32:6267] I: _lws_destroy_ah: freed ah 0x556fed388510 : pool length 0
> [2019/11/12 09:56:32:6267] I: __lws_header_table_detach: wsi 0x556fed387e90: ah 0x556fed388510 (tsi=0, count = 0)
> [2019/11/12 09:56:32:6267] I: rops_destroy_role_h1: ah det due to close
> [2019/11/12 09:56:32:6268] I: lws_vhost_unbind_wsi: vh default: count_bound_wsi 0
> [2019/11/12 09:56:32:6268] D: __lws_free_wsi: 0x556fed387e90, remaining wsi 1
> [2019/11/12 09:56:32:6268] I: lws_libuv_closewsi: sa left 2: dyn left: 1 (rk 0)
>

**Comment by jnynw** [comment]
this is from 3.1 stable:
`[2019/11/14 10:11:42:3071] DEBUG: 0x55cff1c974e0: SSL_read says 1
[2019/11/14 10:11:42:3071] DEBUG: 0x55cff1c974e0: SSL_read says 1
[2019/11/14 10:11:42:3071] DEBUG: lws_client_interpret_server_handshake: 0x55cff1c974e0: transitioning to h1 client
[2019/11/14 10:11:42:3071] DEBUG: lws_role_transition: 0x55cff1c974e0: wsistate 0x10000117, ops h1
[2019/11/14 10:11:42:3071] DEBUG: lws_ensure_user_space: 0x55cff1c974e0 protocol pss 0, user_space=0x55cff1c6dc80
[2019/11/14 10:11:42:3072] DEBUG: __lws_set_timeout: 0x55cff1c974e0: 0 secs (reason 0)
[2019/11/14 10:11:42:3072] INFO: lws_client_interpret_server_handshake: client connection up
[2019/11/14 10:11:42:3072] DEBUG: _lws_change_pollfd: wsi 0x55cff1c974e0: fd 19 events 1 -> 0
[2019/11/14 10:11:42:3072] DEBUG: elops_io_uv: 0x55cff1c974e0: 9
[2019/11/14 10:11:42:3072] DEBUG: 0x55cff1c974e0: SSL_read says 31
[2019/11/14 10:11:42:3079] DEBUG: _lws_change_pollfd: wsi 0x55cff1c974e0: fd 19 events 0 -> 1
[2019/11/14 10:11:42:3079] DEBUG: elops_io_uv: 0x55cff1c974e0: 5
[2019/11/14 10:11:42:3080] INFO: chunk 25
10:11:42.308007675 139699905595264 DBG http_read  1 , len: 25
10:11:42.308040907 139699905595264 DBG http_receive client_read return:  1 , len: 0
[2019/11/14 10:11:42:3080] DEBUG: _lws_change_pollfd: wsi 0x55cff1c974e0: fd 19 events 1 -> 0
[2019/11/14 10:11:42:3080] DEBUG: elops_io_uv: 0x55cff1c974e0: 9
[2019/11/14 10:11:42:3080] DEBUG: 0x55cff1c974e0: SSL_read says 5
[2019/11/14 10:11:42:3080] DEBUG: _lws_change_pollfd: wsi 0x55cff1c974e0: fd 19 events 0 -> 1
[2019/11/14 10:11:42:3081] DEBUG: elops_io_uv: 0x55cff1c974e0: 5
[2019/11/14 10:11:42:3081] INFO: chunk 0
[2019/11/14 10:11:42:3081] INFO: final chunk
[2019/11/14 10:11:42:3081] INFO: lws_http_transaction_completed_client: wsi: 0x55cff1c974e0, wsi_eff: 0x55cff1c974e0 (http)
10:11:42.308135113 139699905595264 DBG http client connection completed
[2019/11/14 10:11:42:3081] INFO: lws_callback_http_dummy: COMPLETED_CLIENT_HTTP: 0x55cff1c974e0 (parent (nil))
[2019/11/14 10:11:42:3081] INFO: lws_http_transaction_completed_client: nothing pipelined waiting

`

**Comment by jnynw** [comment]
On 3.1, I got 
1) RECEIVE_CLIENT_HTTP_READ, len: 25
2) RECEIVE_CLIENT_HTTP  -> len: 0
3) COMPLETED_CLIENT_HTTP
4) RECEIVE_CLIENT_HTTP  -> len: 3 (again)

**Comment by lws-team** [comment]
I did some work around cgi + h1 on master, please see if it helps.

If it doesn't help, please let me know how to reproduce this, ie, a URL I can make the minimal http client go to that definitely has the wrong behaviour.
