### ISSUE TITLE
mbedtls_aes_crypt_cbc operates on full blocks input data

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#1762]
https://tls.mbed.org/api/aes_8h.html#a321834eafbf0dacb36dac343bfd6b35d

`mbedtls_aes_crypt_cbc` checks that input length is a multiple of the AES block size of 16 Bytes.

LWS doesn't check check it anywhere and `lws_jwe_encrypt` just fails in function `lws_genaes_crypt` when input length is not a multiple of 16.

**Comment by lws-team** [comment]
lws checking it will just make it fail earlier... if you think it's helpful to do that, please send a patch on this and the doxygen comment in the public header.

**Comment by lws-team** [comment]
Well, patch welcome.
