### ISSUE TITLE
libwebsockets stops processing to read incoming packets

### ISSUE THREAD

**Issue by paulobfsilva** [warmcat/libwebsockets#1763]
I have posted this issue on [stackoverflow](https://stackoverflow.com/questions/58822685/libwebsockets-stops-processing-to-read-incoming-packets), but somewhat it seems to me more appropriate to post it here. 
I am building a client/server protocol using libwebsockets library. In the poll thread, each callback on incoming packets triggers a certain method to either save data, respond accordingly, and so on. However, if there are other incoming packets that would trigger LWS_CALLBACK_CLIENT_RECEIVE, the processing of the previous task is left undone.

Is there a way to finish the tasks before dealing with the packets received? Should LWS_CALLBACK_CLIENT_RECEIVE start new threads to handle the processing of data?

**Comment by lws-team** [comment]
What to do depends on a few things like how relatively huge the incoming data can be vs the RAM on platform and how long you want it to wait.

If the incoming data isn't that huge, the best way is just put it into a ringbuffer and draw it down from the processing thread.

**Comment by paulobfsilva** [comment]
Thank you for the quick reply. The incoming data will never be that big, but rather short messages on a constant basis, depending on how big the number of other clients connected might be. The behavior I am facing is that the thread responsible for listening to the websockets callback doesn't have time to finish all the tasks and simply moves on to the next incoming packet. I am sorry I couldn't follow you on your suggestion about the ringbuffer. What do you mean by drawing it down from the processing thread?

**Comment by lws-team** [comment]
A ringbuffer has a head and a tail, the rx would add stuff at the head end and the service thread would consume it ("draw it down") from the tail end.  If on average the worker thread can empty the ringbuffer before the next transaction starts, a ringbuffer sized for one complete message should do.

If a single worker thread cannot keep up, you can have n ringbuffers being worked on by n threads, and recycle them for new rx when they are completed.  Lws has specialized support for this on the server side called "threadpool" but I'm not sure it'll just work for client stuff... you probably are better off rolling your own.

**Comment by paulobfsilva** [comment]
thank you that was helpful!
