### ISSUE TITLE
Differentiate ping and pong in LWS_CALLBACK_CLIENT_WRITEABLE

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#1764]
With libwebsocket client,

Is there a way to differentiate in LWS_CALLBACK_CLIENT_WRITEABLE if there is a ping to write (due to ws_ping_pong_interval timer) or a pong to answer to the server ping?

I need to differentiate for sending a ping with lws_write(... LWS_WRITE_PING) or to do nothing as it answers automatically with a pong to a server ping.

I noticed there is wsi->ws->ping_pending_flag but it is not accessible.

Thanks.

**Comment by lws-team** [comment]
The general idea is you don't have to take care of ping / pong manually.

Prior to master you can set an interval for sending pings at context creation time

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n435

In master there's a more general approach to ensure connections don't go above a certain duration without having passed traffic that proves its "validity", either by your own traffic that responded to other traffic, or if it's idle for a specified time, by generating its own PING / PONG... this is not ws-specific but also works on, eg, h2.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md

**Comment by fusionJose** [comment]
Okey thank you very much

**Comment by fusionJose** [comment]
But it automatically doesn´t send the ping, isn't it?

I mean you have to use lws_write with LWS_WRITE_PING function in LWS_CALLBACK_CLIENT_WRITEABLE
