### ISSUE TITLE
lws_is_final_fragment() is not working properly when using permessage-deflate

### ISSUE THREAD

**Issue by dbrichards** [warmcat/libwebsockets#1768]
This problem is likely the same as the one reported in issue #1226. @Triuman @lminiero

_lws_is_final_fragment_() seems to work fine when permessage-deflate is not used.
However, it doesn't always work properly when permessage-deflate is used.

I enabled debugging using -DCMAKE_BUILD_TYPE=DEBUG and compared the cases where _lws_is_final_fragment()_ worked and where it didn't.

I found that _lws_is_final_fragment()_ was giving the wrong result at times because _wsi->ws->rx_draining_ext_ was set, and that because _deflatePending()_ was called (in the LWS_EXT_CB_PAYLOAD_RX state of _lws_extension_callback_pm_deflate())_ and indicated there was pending data.

The problem is that _deflatePending()_ (provided by zlib) should not be used here for inflation, because is designed for use in deflation only. In fact, in this case _deflatePending()_ is referencing deflate state data that is actually overlayed on inflate state data, reslulting in undefined behaviour.
__

**Comment by lws-team** [comment]
Thanks... yes you are right that stuff does not belong at all in the inflate section.  I pushed a patch on master just removing it, since there's no equivalent for inflate AFAIK.  And it can pass autobahn for client and server.  So please give it a try.

**Comment by dbrichards** [comment]
Thanks Andy for the quick response and fix!  It works great so far. I will test further with another system on Monday, Have a great weekend!

**Comment by dbrichards** [comment]
Hi Andy. I did more testing with your fix today and it worked great. Thanks again,

**Comment by lws-team** [comment]
Great.

**Comment by lonnywong** [comment]
@lws-team I believe it's likely same as this one. https://github.com/warmcat/libwebsockets/issues/1158#issuecomment-1812965267

I tested it with the main branch. Most of the time it works. But sometimes it doesn't. It will continue after timeout. So if you don't pay attention to the time spent, you might think it works well.

**Comment by lonnywong** [comment]
@lws-team The `lws_extension_callback_pm_deflate` has more, but the main loop doesn't come back in time:
https://github.com/warmcat/libwebsockets/blob/2445069d34f5a97343d1996ae5ab21dc8c995153/lib/roles/ws/ops-ws.c#L646-L653

case 1:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/fbe70a7d-0bb3-426d-8ed4-17454a613b02)

case 2:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/cabd6d83-3e77-4802-ab82-8781c6f78ad1)

**Comment by lws-team** [comment]
I am not really following this but ../lib/core-net/service.c lws_service_adjust_timeout() should short circuit the wait if anyone on the event loop is draining ext rx

```
#if defined(LWS_ROLE_WS) && !defined(LWS_WITHOUT_EXTENSIONS)
        /* 1) if we know we are draining rx ext, do not wait in poll */
        if (pt->ws.rx_draining_ext_list)
                return 0;
#endif
```

Maybe it's no handled correctly for libuv after the wait?  You can check if this is applied before the wait.

**Comment by lonnywong** [comment]
> I am not really following this but ../lib/core-net/service.c lws_service_adjust_timeout() should short circuit the wait if anyone on the event loop is draining ext rx
> 
> ```
> #if defined(LWS_ROLE_WS) && !defined(LWS_WITHOUT_EXTENSIONS)
>         /* 1) if we know we are draining rx ext, do not wait in poll */
>         if (pt->ws.rx_draining_ext_list)
>                 return 0;
> #endif
> ```
> 
> Maybe it's no handled correctly for libuv after the wait? You can check if this is applied before the wait.

@lws-team Thanks. It saves me a lot of time. I'm debugging it, trying to understand them.

**Comment by lonnywong** [comment]
@lws-team Why is it `#if defined(LWS_ROLE_WS) && !defined(LWS_WITHOUT_EXTENSIONS)`, but not `#if !defined(LWS_WITHOUT_EXTENSIONS)`?

**Comment by lws-team** [comment]
Because LWS_WITHOUT_EXTENSIONS may not be set without LWS_ROLE_WS, but without the WS role, nothing will compile correctly for it and so that has to be taken care of.
