### ISSUE TITLE
Roadmap Visibility

### ISSUE THREAD

**Issue by frink** [warmcat/libwebsockets#1770]
Hate to sound like a child in the back seat. But wanted to find out when the next stable version is expected to drop. With the switch to MIT license this is a big deal for some. Is there anywhere on the website that I haven't seen where the roadmap is present?

**Comment by lws-team** [comment]
Yes... although it isn't very old there's also quite a bit of distance now between 3.2 and master in terms of features / some things that are heavily refactored to work right.

There's one particular thing I should get the chance to discuss in the next couple of weeks and find out how much work that is to do it before 4.0.  And I would like to try to "announce" the license change at the first MIT release, but I'm not really sure how to go about it.

At the beginning a release was a lot of work but gradually most of the work went into CI.  So practically, using master at the moment is going to be hard to tell apart from 4.0. The main thing I wish I had before a release is people testing the stuff they will suddenly start using after the release and find problems then.

**Comment by frink** [comment]
OpenSSL is going through similar growing pains in terms of licensing and announcements. As far as "announcement" there are many blogs and news aggregators. Mashable and Slashdot come to mind. But also some of the more esoteric blogs. It would be worth taking a weekend and cataloging the current blogs that exist about lws and then contacting those Bloggers to share with them what you are seeking to do. Most will be exited to write a review of the new features not the least of which is a much more permissive license...

I'd love to test more of the features but my build system is flaky as I'm purposely limiting my dev system to an Arm based Chromebook running Termux as my dev/build environment with clang. A lot of stuff does not play friendly with this. I can't get half the flags to build yet. Haven't investigated as to why the build fails just trying to flip switches to get familiar with things...

**Comment by frink** [comment]
Okay. Seems my arm + clang system is working good enough to play with LWS. I'm recompiling LWS often. So let me know which features you want tested and I'll do my best to give you good feedback...

**Comment by lws-team** [comment]
If you are interested in any of the lws_system stuff like dhcpc, ntpclient or async dns resolver, all these need testing.  They work on my setup for the things I tested them on, but some how I doubt that is going to cut it as soon as it meets more of the real world.

One hint, if you mess with cmake options, delete ./build/CMakeCache.txt and assertively give all the options your want at non-default state to cmake each time.  If you ever enabled anything once, it's stickily remembered into the cache and even if you run cmake again with no options, all the options you ever gave before since creating or deleting ./build/CMakeCache.txt apply.

**Comment by frink** [comment]
They all sound useful to my use case! (Evented SQL-scripted WebApp Server) - I'll do some testing and report back any errors or successes...

In the meantime, could you put some sort of Roadmap on the website?

Then we can close this issue. 😃

**Comment by lws-team** [comment]
If I wanted to put a roadmap on my site I would have done it...

**Comment by frink** [comment]
Sorry...

I thought that was why we were leaving this one open.

Guess I misunderstood.
