### ISSUE TITLE
when network ip changed, crashed

### ISSUE THREAD

**Issue by jimying** [warmcat/libwebsockets#1773]
Version 3.2.0,  wsi->ws is NULL, crash stack as follow:
#0  lws_sul_wsping_cb (sul=0x7fdf70008390) at /home/tst/libwebsockets/lib/roles/ws/ops-ws.c:853
853		if (!wsi->ws->send_check_ping) {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  lws_sul_wsping_cb (sul=0x7fdf70008390) at /home/tst/libwebsockets/lib/roles/ws/ops-ws.c:853
#1  0x00000000007c6fe9 in __lws_sul_check (own=own@entry=0x27ebba0, usnow=102736592063) at /home/tst/libwebsockets/lib/core-net/sorted-usec-list.c:100
#2  0x00000000007c2911 in _lws_plat_service_tsi (context=0x27ebab0, timeout_ms=<optimized out>, tsi=tsi@entry=0) at /home/tst/libwebsockets/lib/plat/unix/unix-service.c:119
#3  0x00000000007c29c7 in lws_plat_service (context=<optimized out>, timeout_ms=<optimized out>) at /home/tst/libwebsockets/lib/plat/unix/unix-service.c:222
#4  0x00000000007a800d in lws_service (context=0x27ebab0, timeout_ms=<optimized out>) at /home/tst/libwebsockets/lib/core-net/service.c:733
。。。。
(gdb) p wsi
$1 = (struct lws *) 0x7fdf700082c0
(gdb) p wsi->ws
$2 = (struct _lws_websocket_related *) 0x0

I currently add  code in the begin of lws_sul_wsping_cb（） to avoid crash:
if (!wsi || ! wsi->ws)
       return;

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/issues/1771

Nobody can fix an immutable tag.  So use v3.2-stable branch.
