### ISSUE TITLE
v3.2-stable building LWS_WITH_MBEDTLS and LWS_WITH_ACME

### ISSUE THREAD

**Issue by frink** [warmcat/libwebsockets#1774]
I built again and again with different flags I found a few problems problems. The biggest is when building LWS_WITH_MBEDTLS and LWS_WITH_ACME. However, I also found that simply doing `make clean` would not suffice to rebuild. Ultimately, to get repeatable results I had to `git clone` fresh every time. Apparently, there was some residue being left behind. Didn't investigate as to what. But thought it would be something to report...

```
/data/data/com.termux/files/home/libwebsockets/lib/tls/mbedtls/lws-genec.c:102:53: error: implicit
      conversion from enumeration type 'enum enum_lws_dh_side' to different enumeration type
      'mbedtls_ecdh_side' [-Werror,-Wenum-conversion]
                if (mbedtls_ecdh_get_params(ctx->u.ctx_ecdh, &kp, side))
                    ~~~~~~~~~~~~~~~~~~~~~~~                       ^~~~
/data/data/com.termux/files/home/libwebsockets/lib/tls/mbedtls/lws-genec.c:252:51: error: implicit
      conversion from enumeration type 'enum enum_lws_dh_side' to different enumeration type
      'mbedtls_ecdh_side' [-Werror,-Wenum-conversion]
        n = mbedtls_ecdh_get_params(ctx->u.ctx_ecdh, kp, side);
            ~~~~~~~~~~~~~~~~~~~~~~~                      ^~~~
2 errors generated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:869: CMakeFiles/websockets_shared.dir/lib/tls/mbedtls/lws-genec.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by lws-team** [comment]
>  Ultimately, to get repeatable results I had to git clone fresh every time.

No, you don't need to do that since if you have a build dir, building makes zero changes to the checkout outside the build dir.  The worst you would have to do is rm -rf build && mkdir build but usually the culprit is ./build/CMakeCache.txt, just delete that and put your options explicitly on cmake.

> LWS_WITH_MBEDTLS and LWS_WITH_ACME

In master, this is fixed, but on v3.2, the ACME support is old.  On master a contribution updated it, although it didn't take care about mbedtls only openssl.  If you want ACME, use master.

**Comment by frink** [comment]
Actually.... I got the same problem with master:

```
$ cmake. -DLWS_WITHOUT_TESTAPPS=ON \
       -DLWS_WITH_STATIC=ON \
        -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr \
        -DLWS_WITH_MBEDTLS=ON \
        -DLWS_WITH_ZIP_FOPS=ON \
        -DLWS_WITH_HTTP_PROXY=ON \
        -DLWS_WITHOUT_TEST_SERVER=ON \
        -DLWS_SSL_SERVER_WITH_ECDH_CERT=ON \
        -DLWS_WITHOUT_EXTENSIONS=OFF \
        -DLWS_WITOUT_DAEMONIZE=OFF \
        -DLWS_WITH_ACME=ON

$ make
...
building etc. -Then blam!
...
data/data/com.termux/files/home/libwebsockets/lib/tls/mbedtls/lws-genec.c:105:53: error: implicit
      conversion from enumeration type 'enum enum_lws_dh_side' to different enumeration type
      'mbedtls_ecdh_side' [-Werror,-Wenum-conversion]
                if (mbedtls_ecdh_get_params(ctx->u.ctx_ecdh, &kp, side))
                    ~~~~~~~~~~~~~~~~~~~~~~~                       ^~~~
/data/data/com.termux/files/home/libwebsockets/lib/tls/mbedtls/lws-genec.c:255:51: error: implicit
      conversion from enumeration type 'enum enum_lws_dh_side' to different enumeration type
      'mbedtls_ecdh_side' [-Werror,-Wenum-conversion]
        n = mbedtls_ecdh_get_params(ctx->u.ctx_ecdh, kp, side);
            ~~~~~~~~~~~~~~~~~~~~~~~                      ^~~~
2 errors generated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:843: CMakeFiles/websockets_shared.dir/lib/tls/mbedtls/lws-genec.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by lws-team** [comment]
It's something different... your toolchain is complaining that the type of an enum doesn't match the prototype, which isn't unreasonable to complain, but since enums are all ints, it's not unreasonable to not complain either.  Fedora GCC that I use, Ubuntu on travis and OSX on travis don't complain.

I pushed a patch on master with a cast that should satisfy your toolchain.

**Comment by frink** [comment]
Yes that seems to work. :-D

As I said in the other thread. I'm restrictively working on arm with clang. Interesting tool chain for sure. But maybe I can find a few oddities this way.

I've got a few more that I've found from switching flags...

I'll write some more issues on those.

Thanks for your help.
