### ISSUE TITLE
got bad HTTP response '200 OK'

### ISSUE THREAD

**Issue by KishanPala556** [warmcat/libwebsockets#1775]
I am getting following error when using libwebsocket as a client and trying to connect with my server.

WARN: lws_client_handshake: got bad HTTP response '200 OK'
ERR: CLIENT_CONNECTION_ERROR: ocpp1.6: 0x7fd5ca67dc10

**Comment by lws-team** [comment]
This is coming because you asked lws for a websocket upgrade connection.  But your server is acting like it only serves http.  With CLIENT_CONNECTION_ERROR, in argument usually points to a string describing something about the problem, in this case it should say, "HS: ws upgrade response not 101" which would have been a nice clue to understand the problem.

**Comment by KishanPala556** [comment]
yes you are right I have print the string it is HS: ws upgrade response not 101, is this problem is from server side or client side? I don't have any control server, if this problem is from client side how can I resolve it?

**Comment by lws-team** [comment]
lws believes it asked for a ws upgrade.  Server responded like it doesn't even know what that is, just sent back index.html or whatever with a 200.

It should be the server actually doesn't support ws, or you have to use a specific url path when trying to use ws on that server etc

**Comment by KishanPala556** [comment]
where do I specify url path in library?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n73

**Comment by KishanPala556** [comment]
my url something looks like "ws://some1.some2.some3.some4.some5:port_number/id1/id2"
will it work? what are the required information I need to give to connect with server?

**Comment by KishanPala556** [comment]
can you give me example of input and output of the function lws_parse_uri(char *p, const char **prot, const char **ads, int *port, const char **path) ?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/dbus-server/minimal-dbus-ws-proxy/protocol_lws_minimal_dbus_ws_proxy.c#n243

**Comment by KishanPala556** [comment]
I don't want code, I just want an example.

**Comment by KishanPala556** [comment]
Please let me know if my url is something like "ws://some1.some2.some3.some4.some5:port_number/id1/id2, then what should be parameters of structure lws_client_connect_info such as address, path, host, origin ?

**Comment by sshsu** [comment]
I also come accross the same problem, I use libwebsockets as server, when client connect to server, sometimes, server returns code  "http:/1.1 200 ok", header "connection: close"  and a strange data a html as below:

an abnormal request shows in wireshark as like this:
send:
```
GET / HTTP/1.1
Sec-WebSocket-Protocol: janus-protocol
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: A3HuZOv/2vxKwVYYUcK79Q==
Sec-WebSocket-Version: 13
Host: 120.77.244.84:8086
Accept-Encoding: gzip
User-Agent: okhttp/3.12.0
```
ack:
```
HTTP/1.1 200 OK
Connection: close
Content-Type: text/html;
Content-Length: 1015
<html><head><script>var ar=decodeURIComponent('http://120.77.244.84%3a8086%2f');t=setTimeout('location.replace(ar)',2000);var ct=0;function ck(){var x=document.createElement('script');x.src='http://localhost:100/src/onlineinfo.js?t='+new Date().getTime();document.body.appendChild(x);if(typeof is_online=='number'&&is_online===1){return;}if(ct>5){location=ar;return;}setTimeout(ck,500);ct++;}function it(){if(typeof(ac_krb_redirect)==='function'){clearTimeout(t);ck();}else{location=ar;}}var eUa=['Edge','Maxthon','MetaSr'];var a=1;var ua=navigator.userAgent;for(var i=0;i<eUa.length;++i){if(ua.indexOf(eUa[i])>-1){a=0;break;}}if(a){lJs('http://localhost:100/src/iwa/index.js?t=1574997218',it);}function lJs(src, f){var s=document.createElement('script');s.type='text/javascript';s.src=src;s.onload=s.onreadystatechange=function(){var r=s.readyState;if(r==='loaded'||r ==='complete'||!r){s.onreadystatechange=null;f();}};document.getElementsByTagName('head')[0].appendChild(s);};</script></head><body></body></html>
```

a normal request shows in wireshark as like this:
send:
```
GET / HTTP/1.1
Sec-WebSocket-Protocol: janus-protocol
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: jdpYj/3vYBI+kz/tG4ktRA==
Sec-WebSocket-Version: 13
Host: 120.77.244.84:8086
Accept-Encoding: gzip
User-Agent: okhttp/3.12.0

```

ack:
```
HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: J/vtHGTflGKx48ZWR0NNJMdERD4=
Sec-WebSocket-Protocol: janus-protocol

```

**Comment by lws-team** [comment]
In both cases it's a 'normal request'... it's the response that's broken.

Something's injecting js, probably locally since it links to localhost:100.  But it's too dumb to understand ws.

Sending back a 200 + js is broken already, it's nothing to do with lws.

**Comment by KishanPala556** [comment]
>

> Please let me know if my url is something like "ws://some1.some2.some3.some4.some5:port_number/id1/id2, then what should be parameters of structure lws_client_connect_info such as address, path, host, origin ?
??
in my case may be I am doing wrong configuration.

**Comment by lws-team** [comment]
I pointed to an example using that api, that's enough to figure it out.  Or just don't use that api if you don't understand it.  Either way I can't fix a P that EBKAC.

**Comment by hxswen** [comment]
> <htm
How did you deal with it？I had the same problem

**Comment by StoneFancy** [comment]
我也遇到了同样的问题，你们是如何解决的？

**Comment by lws-team** [comment]
You have some intermediary / proxy that is messing with your traffic.
