### ISSUE TITLE
How much is left to do before the 4.0 release?

### ISSUE THREAD

**Issue by rg-net** [warmcat/libwebsockets#1779]
I'm considering this for my company. They need to do a static build so they of course want the MIT license but they also want something considered production ready. I can't tell when that might be.

Is it months away or years away? - Any idea at all would be quite helpful.

**Comment by lws-team** [comment]
If your company is paying me, hit me up on my internal email and we can discuss.

If it's not, use master or last stable release.  Or use a different lib... this is FOSS, why does your schedule or choice of what to leech matter to me?  Or contribute resources and time to this project.

From my point of view people who have never contributed anything, not even pre release testing demanding to know when I have done enough free work for them comes over as kind of entitled.

**Comment by rg-net** [comment]
Obviously I hit a nerve.

Just trying to do my due diligence and didn't realize lws was a one man show. Website is well done and the API is super polished. Looked like a win. But as much as I like what I see I have to use a stable release and a permissive license so my hands are tied. Sorry dude. Maybe next project.

=) Later...

**Comment by lws-team** [comment]
Oh no... somebody isn't going to leech my stuff for $0.

Whatever will I do.
