### ISSUE TITLE
lws 3.2.0: Behavior of lws_b64_decode_string changed

### ISSUE THREAD

**Issue by falk-werner** [warmcat/libwebsockets#1782]
I noticed that bahavior of lws_b64_decode_string changed between version 3.1.0 and 3.2.0. The function seems to need more space in result buffer than before. The following code works in 3.1.0, but not in 3.2.0:

    char buffer[13];
    lws_b64_decode_string("SGVsbG8sIFdvcmxk", buffer, 13);
    
    ASSERT_STREQ("Hello, World", buffer);

For debugging puproses, please refer to [https://github.com/falk-werner/lws-base64](https://github.com/falk-werner/lws-base64).

If this change was intensional, please tell me which size should I use for result buffer.

**Comment by lws-team** [comment]
The difference there between v3.1-stable and v3.2-stable is pretty small

```
diff --git a/lib/misc/base64-decode.c b/lib/misc/base64-decode.c
index de2efc8fd..b46a94242 100644
index de2efc8fd..b46a94242 100644
--- a/lib/misc/base64-decode.c
+++ b/lib/misc/base64-decode.c
@@ -144,7 +144,7 @@ _lws_b64_decode_string(const char *in, int in_len, char *out, int out_size)
                                quad[i] = 0;
                }
 
-               if (out_size < (done + len - 1))
+               if (out_size < (done + len + 1))
                        /* out buffer is too small */
                        return -1;
 
```

IIRC the issue was about making sure there is always space for a NUL.

**Comment by falk-werner** [comment]
So, this is a bug, since strlen("Hello, World") is 12 and the buffer provided is able to store 13 characters ("Hello, World\0")?

As workaround, it should be save to use buffer size + 4?

**Comment by lws-team** [comment]
Well, I am not sure I would call it a bug.  The implementation wants an extra byte of buffer than you might expect.  FYI that implementation was refactored in master to support stateful / incremental base64 decode as well as the old apis needing it all in one place at one time.  There's it's even trickier to estimate the decoded length before the last quartet of input chars is seen.

Whatever you were doing before, the change suggests it'll be happy with +2.

**Comment by falk-werner** [comment]
Okay, I will use +2 instead than.
Thanks for the quick response.
