### ISSUE TITLE
More build issues on Android/Chrome OS

### ISSUE THREAD

**Issue by frink** [warmcat/libwebsockets#1783]
So it looks like it needs Android's built in liblog but it's not linking directly. I can't find the LD flags anywhere in make or CMake. But there is a lot of stuff generated in your build system. So I'm probably missing something...

Here's what I'm getting:
```
Scanning dependencies of target lws-api-test-async-dns
[ 64%] Building C object minimal-examples/api-tests/api-test-async-dns/CMakeFiles/lws-api-test-async-dns.dir/main.c.o
[ 64%] Linking C executable ../../../bin/lws-api-test-async-dns
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: ../../../lib/libwebsockets.a(unix-misc.c.o): in function `android_polyfill_syslog':
unix-misc.c:(.text+0x120): undefined reference to `__android_log_print'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: unix-misc.c:(.text+0x154): undefined reference to `__android_log_vprint'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [minimal-examples/api-tests/api-test-async-dns/CMakeFiles/lws-api-test-async-dns.dir/build.make:89: bin/lws-api-test-async-dns] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: minimal-examples/api-tests/api-test-async-dns/CMakeFiles/lws-api-test-async-dns.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

I'm looking on where to inject -llog for Android

It's a weird one for sure...

**Comment by frink** [comment]
P.S. This only started to surface when I tried building LWS_WITH_MINIMAL_EXAMPLES

I'd had problems building against my custom version for some of the minimal examples and I thought this might fix it. (Before it blew up missing RSA functions...)  So either way something busts the build..

**Comment by lws-team** [comment]
The only related thing in unix-misc.c is a reference to generic syslog()

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-misc.c#n54

It looks like the toolchain headers translates this to android specific apis that it doesn't know it should link against the related library, since it's entirely platform-specific.  Although the problem is reported at linking against an executable, the binding should be done during lws build IIUI.

I don't use android or ndk but I'd try something like this in CMakeLists.txt first

If (LWS_PLAT_ANDROID)
        list(APPEND LIB_LIST log)
endif()

You should be setting LWS_PLAT_ANDROID at cmake already.

**Comment by frink** [comment]
I'll check into this. Thanks.

Which CMakeLists.txt do I need to put this in. The test file or the make file?

**Comment by frink** [comment]
Okay. I just recompiled with LWS_PLAT_ANDROID. (didn't add the log thing just wanted to see if this would fix things...) Got a different error this time:

```
data/data/com.termux/files/home/dubious/libwebsockets/lib/plat/unix/android/android-resolv.c:48:14: error: use of undeclared
      identifier 'sa'
        n = ip32 == sa->sin_addr.s_addr;
                    ^
1 error generated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:1116: CMakeFiles/websockets_shared.dir/lib/plat/unix/android/android-resolv.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:156: CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by frink** [comment]
looks like line 48 should be:
```
n = ip32 == sa46->sa4.sin_addr.s_addr;
```

This at least allowed it to compile. Will submit a PR once I get this working.

**Comment by frink** [comment]
I tried it like this in both main and child CMakeLists.txt

```
if (LWS_PLAT_ANDROID)
    list(APPEND LIB_LIST log)
endif()
```

still no change...

I'm not sure that it's actually working,

**Comment by frink** [comment]
I'm gonna take this one up with Termux and see if there is something with their weird configuration. Keep this one open and I'll report back in a day or so...

**Comment by frink** [comment]
I've not been able to figure out how to incorporate this into cmake. But running `export LDFLAGS=" -llog"` before cmake and make seems to resolve this for me. See termux/termux-packages#4611

**Comment by lws-team** [comment]
The snippet I suggested above should do the same thing, but it's going to matter where you put it in CMakeLists.txt... eg here should be good

https://libwebsockets.org/git/libwebsockets/tree/CMakeLists.txt#n1937

**Comment by frink** [comment]
Thanks. I don't know CMake very well at all.

**Comment by frink** [comment]
Okay so now I'm past the log problem and back to compiling examples...

These don't look like tooling errors. I've not dug into them yet. I'll probably get into late next week.

```
Building C object minimal-examples/http-client/minimal-http-client-multi/CMakeFiles/lws-minimal-http-client-multi.dir/minimal-http-client-multi.c.o
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:39:8: error:
      redefinition of 'user'
struct user {
       ^
/data/data/com.termux/files/usr/include/sys/user.h:220:8: note: previous definition is here
struct user {
       ^
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:67:17: error:
      no member named 'index' in 'struct user'
                client_wsi[u->index] = NULL;
                           ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:78:7: error:
      no member named 'index' in 'struct user'
                        u->index, (int)len);
                        ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/include/libwebsockets/lws-logs.h:76:43: note: expanded from macro
      'lwsl_user'
#define lwsl_user(...) _lws_log(LLL_USER, __VA_ARGS__)
                                          ^~~~~~~~~~~
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:106:14: error:
      no member named 'index' in 'struct user'
                          wsi, u->index);
                               ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/include/libwebsockets/lws-logs.h:76:43: note: expanded from macro
      'lwsl_user'
#define lwsl_user(...) _lws_log(LLL_USER, __VA_ARGS__)
                                          ^~~~~~~~~~~
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:107:17: error:
      no member named 'index' in 'struct user'
                client_wsi[u->index] = NULL;
                           ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:120:26: error:
      no member named 'index' in 'struct user'
                if (u && client_wsi[u->index]) {
                                    ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:126:18: error:
      no member named 'index' in 'struct user'
                        client_wsi[u->index] = NULL;
                                   ~  ^
/data/data/com.termux/files/home/dubious/libwebsockets/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c:197:10: error:
      no member named 'index' in 'struct user'
        user[m].index = m;
        ~~~~~~~ ^
8 errors generated.
make[2]: *** [minimal-examples/http-client/minimal-http-client-multi/CMakeFiles/lws-minimal-http-client-multi.dir/build.make:63: minimal-examples/http-client/minimal-http-client-multi/CMakeFiles/lws-minimal-http-client-multi.dir/minimal-http-client-multi.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1177: minimal-examples/http-client/minimal-http-client-multi/CMakeFiles/lws-minimal-http-client-multi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by lws-team** [comment]
> /data/data/com.termux/files/usr/include/sys/user.h:220:8: note: previous definition is here
struct user {

That example has a struct user and so does the file quoted above on your system.  But on linux, osx, and windows there's no such conflicting definition.

**Comment by frink** [comment]
So is there a quick fix or do I need to dig on this one...?

**Comment by frink** [comment]
Oh wait. Half asleep here. I see it. The problem is because all of the Android specific junk. Duh.

**Comment by lws-team** [comment]
I pushed a patch on master renaming it in the example, its name doesn't really matter.

**Comment by frink** [comment]
I just merged into my branch. Building now.

**Comment by frink** [comment]
OKay that built beautifully. I'm sending a PR #1790 1790 with one line I changed to build. THanks. Closing this now...
