### ISSUE TITLE
LWSCM_WSCL_ISSUE_HANDSHAKE2

### ISSUE THREAD

**Issue by KishanPala556** [warmcat/libwebsockets#1784]
What are the causes of LWSCM_WSCL_ISSUE_HANDSHAKE2 error?

**Comment by lws-team** [comment]
How old is your lws?  That no longer exists on recent lws, even at 2 years old v3.1 it's now LRS_H1C_ISSUE_HANDSHAKE2.

Update your lws and see if you still have problems.

**Comment by KishanPala556** [comment]
it is 2.4, I will update and check.

**Comment by KishanPala556** [comment]
Hi lws-team,
We switched to version 3.2.
We have used minimal_ws_client_ping example in **c** and changed following things.
 ***server_address = "192.168.9.140" and port = 8887.**

Actually we are trying to connect with our local java based websocket server.

We are facing below issue:
```
[2019/12/03 18:16:53:5162] U: LWS minimal ws client PING
[2019/12/03 18:16:53:5200] W: lws_client_handshake: got bad HTTP response '404'
[2019/12/03 18:16:53:5200] E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
[2019/12/03 18:16:54:5201] N: callback_minimal_broker: LWS_CALLBACK_USER
[2019/12/03 18:16:54:5212] W: lws_client_handshake: got bad HTTP response '404'
[2019/12/03 18:16:54:5212] E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
[2019/12/03 18:16:55:5213] N: callback_minimal_broker: LWS_CALLBACK_USER
[2019/12/03 18:16:55:5224] W: lws_client_handshake: got bad HTTP response '404'
[2019/12/03 18:16:55:5224] E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
[2019/12/03 18:16:56:5225] N: callback_minimal_broker: LWS_CALLBACK_USER
[2019/12/03 18:16:56:5236] W: lws_client_handshake: got bad HTTP response '404'
[2019/12/03 18:16:56:5236] E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
```
What can be the  possible issues? Eagerly waiting for your response.

**_Note: We have verified successfully java based websocket client with java based websocket server._**

Thanks
Kishan Pala

**Comment by lws-team** [comment]
Hm... the server is sending you a 404... look in its logs to see why it feels it wanted to do that.

Also ws is not http, there is no "wget" or "curl" for ws because both sides must agree on the subprotocol.  If you randomly use any ws example that has its own expectation of the ws subprotocol or the path on the server you'll get nowhere.

> We have verified successfully java based websocket client with java based websocket server.

Great, just use that :-)

**Comment by KishanPala556** [comment]
Hi lws-team,
Thanks for your quick response.

If I use official "ws://echo.websocket.org" then which example will be suitable and what are the changes required to do?

> Great, just use that :-)
We have requirement in **C**.

**Comment by lws-team** [comment]
There's no description of echo in the websockets standard.  The lws echo connects to the server and expects to be given something to echo back... that's how the lws echo server and, eg, Autobahn work.

Still, lws echo client will connect to it just fine with `lws-minimal-ws-client-echo -s echo.websocket.org -p 80`...  as I already said   --->

> Hm... the server is sending you a 404... look in its logs to see why it feels it wanted to do that.

> Also ws is not http, there is no "wget" or "curl" for ws because both sides must agree on the subprotocol. If you randomly use any ws example that has its own expectation of the ws subprotocol or the path on the server you'll get nowhere.

**Comment by KishanPala556** [comment]
Have a look at below logs we are getting while connecting as you said:

**./lws-minimal-ws-client-echo -s echo.websocket.org -p 80
 U: LWS minimal ws client echo + permessage-deflate + multifragment bulk message
 U:    lws-minimal-ws-client-echo [-n (no exts)] [-u url] [-p port] [-o (once)]
U: options 0, ads echo.websocket.org
U: connecting to echo.websocket.org:80/ws://192.168.9.140:8887/CP01
W: lws_client_handshake: got bad HTTP response '404'
E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
U: Completed 3 failed**

**Comment by lws-team** [comment]
Here's my log from trying it yesterday before I replied... this is on lws master

```
$ ./bin/lws-minimal-ws-client-echo -s echo.websocket.org -p 80 -o
[2019/12/03 15:00:51:3244] U: LWS minimal ws client echo + permessage-deflate + multifragment bulk message
[2019/12/03 15:00:51:3244] U:    lws-minimal-ws-client-echo [-n (no exts)] [-u url] [-p port] [-o (once)]
[2019/12/03 15:00:51:3245] U: options 1, ads echo.websocket.org
[2019/12/03 15:00:51:3289] E: callback_ntpc: set up system ops for set_clock
[2019/12/03 15:00:52:3771] N: callback_ntpc: Unix time: 1575385252
[2019/12/03 15:00:52:3771] U: connecting to echo.websocket.org:80//
[2019/12/03 15:00:52:5514] U: LWS_CALLBACK_CLIENT_ESTABLISHED
^C[2019/12/03 15:01:05:0094] U: LWS_CALLBACK_CLIENT_CLOSED
[2019/12/03 15:01:05:0099] U: Completed 1 failed
```

Since it's difficult for you to connect to anything, and so easy here, I wonder if it's actually some intermediary on your side that is responding with these 400 or 200.  If you have a server you have ssh credentials on, that's on the internet I'd try build master lws there and do the same test.  That way you can eliminate the intfrastructure at your end.

**Comment by KishanPala556** [comment]
Hi lws-team,

We have checked the same on master and found following cmake error:

```
`libwebsockets-master/minimal-examples/ws-client/minimal-ws-client-echo/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Success
-- Performing Test HAS_LWS_WITH_CLIENT
-- Performing Test HAS_LWS_WITH_CLIENT - Success
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS - Success
CMake Error at CMakeLists.txt:58 (message):
  Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this
  project
Call Stack (most recent call first):
  CMakeLists.txt:68 (require_lws_config)


-- Configuring incomplete, errors occurred!
libwebsockets-master/minimal-examples/ws-client/minimal-ws-client-echo/build/CMakeFiles/CMakeOutput.log".
`
```

**Comment by lws-team** [comment]
That example needs permessage-deflate enabled... it's there to allow testing with Autobahn.

In lws itself, `cmake .. -DLWS_WITHOUT_EXTENSIONS=0 && make && sudo make install`.  Then retry building the echo client.

**Comment by KishanPala556** [comment]
Still facing the same issue.

```
`/libwebsockets-master/minimal-examples/ws-client/minimal-ws-client-echo/build$ cmake .. -DLWS_WITHOUT_EXTENSIONS=0
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Success
-- Performing Test HAS_LWS_WITH_CLIENT
-- Performing Test HAS_LWS_WITH_CLIENT - Success
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS - Success
CMake Error at CMakeLists.txt:58 (message):
  Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this
  project
Call Stack (most recent call first):
  CMakeLists.txt:68 (require_lws_config)


-- Configuring incomplete, errors occurred!
See also "libwebsockets-master/minimal-examples/ws-client/minimal-ws-client-echo/build/CMakeFiles/CMakeOutput.log".
`
```

Can we comment it temporary if it won't affect for connection?

**Comment by lws-team** [comment]
Did you do the sudo make install part?

Is there any other libwebsockets on this box, eg, does /usr/include/libwebsockets.h exist?  By default what you built is installed in /usr/local/...

**Comment by KishanPala556** [comment]
> Did you do the sudo make install part?

Yes initially in the main directory.

> does /usr/include/libwebsockets.h exist?

Yes, in /usr/local/include/libwebsockets.h.

We did following things:
```
apt-get remove libwebsockets-dev
wget https://github.com/warmcat/libwebsockets/archive/master.zip
unzip master.zip
cd libwebsockets-master/
mkdir build; cd build; cmake ..;make;
sudo make install
```

Then direct to /minimal-examples/ws-client/minimal-ws-client-echo/
```
mkdir build
cd build
cmake .. -DLWS_WITHOUT_EXTENSIONS=0 && make && sudo make install
```

but still getting the same **Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this**

**Comment by lws-team** [comment]
So two good things and one bad thing:

+ you removed the conflicting distro package

+ you build process is OK (but you should use && instead of ; ... the way you are doing it, even cmake fails you still try to do the make... && is the same as ; but aborts the chain of commands if one fails)

 - you forgot the actual cmake change we want to do to lws to resolve the problem

`cmake .. -DLWS_WITHOUT_EXTENSIONS=0`

**Comment by KishanPala556** [comment]
`you forgot the actual cmake change we want to do to lws to resolve the problem`
we made it inside /minimal-examples/ws-client/minimal-ws-client-echo/

> mkdir build
> cd build
> cmake .. -DLWS_WITHOUT_EXTENSIONS=0 && make && sudo make install

**Comment by lws-team** [comment]
No... I literally wrote:

> In lws itself, cmake .. -DLWS_WITHOUT_EXTENSIONS=0 && make && sudo make install. Then retry building the echo client.

The thing you're changing is whether lws library was built supporting permessage-deflate or not.  The echo example wants that feature, it helpfully checks if your lws library was built with it and explains the problem if it's missing.

**Comment by KishanPala556** [comment]
OK so this command (cmake .. -DLWS_WITHOUT_EXTENSIONS=0 && make && sudo make install) need to apply inside lws and then we can build the example with same command ? is it what you want to say?

**Comment by lws-team** [comment]
Yes do that in lws itself.

In the example, no need to modify cmake at all, just `cmake ..` is OK there.

**Comment by KishanPala556** [comment]
Thanks, that cmake issue is resolved now.
But facing another issue while executing client echo example. **W: lws_client_handshake: got bad HTTP response '400'**
```
/libwebsockets-master/minimal-examples/ws-client/minimal-ws-client-echo/build$ ./lws-minimal-ws-client-echo -s echo.websocket.org -p 80 -o
[2019/12/04 14:42:08:7249] U: LWS minimal ws client echo + permessage-deflate + multifragment bulk message
[2019/12/04 14:42:08:7249] U:    lws-minimal-ws-client-echo [-n (no exts)] [-u url] [-p port] [-o (once)]
[2019/12/04 14:42:08:7249] U: options 1, ads echo.websocket.org
[2019/12/04 14:42:08:7275] U: connecting to echo.websocket.org:80//
[2019/12/04 14:42:09:2053] W: lws_client_handshake: got bad HTTP response '400'
[2019/12/04 14:42:09:2053] E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101
[2019/12/04 14:42:09:2057] U: Completed 3 failed

```

**Comment by lws-team** [comment]
Yeah but I think the point is **you** are facing that issue.  I can't reproduce it.  So I think it's nothing to do with lws, it's something to do with your internet arrangements specifically where you are.

That's why I suggest repeat that test on a remote server hosted somewhere else (preferably another country if you're in some country that censors its internet heavily) instead of your local internet.

**Comment by KishanPala556** [comment]
Thank you Andy Green for your quick responses.

We are able to successfully connect after changing internet arrangement to hostspot. May be there are some issues in our network.

Thank you so much again.
