### ISSUE TITLE
lws-test-client/Windows seems not working on master. 3.2.0 is okay

### ISSUE THREAD

**Issue by bigblackdot** [warmcat/libwebsockets#1785]
Hey guys, i'm building libwebsocket-test-client from master and 3.2.0, looks like former is unable to connect when latter is fine. master's version hangs on "dumb: connecting/mirror: connecting" with no progress, looks like it eating up 100% CPU time on a core. Same story for the SSL-enabled builds, disabled it in attempt to isolate issue.

Steps to reproduce:
```
cmake -DLWS_WITH_SSL=0 ..
cmake —build . —config Release
bin\Release\libwebsockets-test-client.exe [linux host running libwebsockets-test-server from master branch]
```
Output, libwebsockets-3.2.0:
```
C:\test\libwebsockets-3.2.0\build>bin\Release\libwebsockets-test-client.exe 192.168.0.112
[:18:2942] N: libwebsockets test client - license LGPL2.1+SLE
[:18:2942] N: (C) Copyright 2010-2018 Andy Green <andy@warmcat.com>
[:18:3098] N: SSL disabled
[:18:3098] N: Cert must validate correctly (use -s to allow selfsigned)
[:18:3098] N: Requiring peer cert hostname matches
[:18:3254] N: using mode (ws)
[:18:3254] N: dumb: connecting
[:18:3410] N: mirror: connecting
[:18:3878] N: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[:18:3878] N: opened mirror connection with 59059 lifetime
[:26:5934] N: closing mirror session
[:26:5934] N: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0, rxb 0, rx_count 0
[:26:5934] N: mirror: connecting
[:26:6402] N: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[:26:6402] N: opened mirror connection with 70948 lifetime
[:35:5790] E: Exiting
[:35:5790] N: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=20300, rxb 0, rx_count 0
```

Output, libwebsockets-master:
```
C:\test\libwebsockets-master\build>bin\Release\libwebsockets-test-client.exe 192.168.0.112
[:47:2010] N: libwebsockets test client - license LGPL2.1+SLE
[:47:2010] N: (C) Copyright 2010-2018 Andy Green <andy@warmcat.com>
[:47:2010] N: SSL disabled
[:47:2166] N: Cert must validate correctly (use -s to allow selfsigned)
[:47:2166] N: Requiring peer cert hostname matches
[:47:2166] W: lws_create_context: LWS_WITHOUT_EXTENSIONS but extensions ptr set
[:47:2322] N: using mode (ws)
[:47:2322] N: dumb: connecting
[:47:2322] N: mirror: connecting
```

No problem for me, 3.2.0 is fine. Hope my two cents could help a bit.

**Comment by lws-team** [comment]
Connection process is very different on master to work with asynchronous DNS resolution support, it's tested to work on Linux OK but I don't use Windows.

Can you set debug mode build in cmake with -DCMAKE_BUILD_TYPE=DEBUG and turn the logging up with -d 1151 on the test app, and see what the spinning looks like.

**Comment by 4cad** [comment]
Just an FYI, I have the test-client working against localhost test-server on a clean default configuration Windows 10 64 bit build of the latest master (last commit Dec 8th, 2019)

**Comment by lws-team** [comment]
That's reassuring to know, thanks.

**Comment by lws-team** [comment]
It doesn't look like any more info is coming from OP.
