### ISSUE TITLE
How to support this .properties file types.

### ISSUE THREAD

**Issue by windflowerly** [warmcat/libwebsockets#1787]
i deploy a file : language.properties. 
I visit this file in  browers. but diplay a 415 error code.

How to do that to support .properties file to download.

**Comment by windflowerly** [comment]
PS.

I used default http proccessor : lws_callback_http_dummy

static struct lws_protocols protocols[] = {
	{ "http", lws_callback_http_dummy, 0, 0 },
	{ NULL, NULL, 0, 0 } /* terminator */
};

**Comment by lws-team** [comment]
I think you're asking, 'how can I add extra mimetype bindings in the http server?'.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-mimetypes/minimal-http-server-mimetypes.c#n22-27
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-mimetypes/minimal-http-server-mimetypes.c#n36

**Comment by windflowerly** [comment]
yes. 
thanks for you apply :)
