### ISSUE TITLE
the chance of bind different protocol.

### ISSUE THREAD

**Issue by jackim** [warmcat/libwebsockets#1788]
LWS_CALLBACK_HTTP_BIND_PROTOCOL				= 49,
	/**< By default, all HTTP handling is done in protocols[0].
	 * However you can bind different protocols (by name) to
	 * different parts of the URL space using callback mounts.  This
	 * callback occurs in the new protocol when a wsi is bound
	 * to that protocol.  Any protocol allocation related to the
	 * http transaction processing should be created then.
	 * These specific callbacks are necessary because with HTTP/1.1,
	 * a single connection may perform at series of different
	 * transactions at different URLs, thus the lifetime of the
	 * protocol bind is just for one transaction, not connection. */

how to bind different protocols?

**Comment by lws-team** [comment]
You're being a server or making a client connection?

**Comment by jackim** [comment]
being a server.

**Comment by lws-team** [comment]
When you define a mount, you can use the LWSMPRO_CALLBACK for .origin_protocol and set .protocol to the name of the protocol you want to bind the mount to.

**Comment by jackim** [comment]
thank you!
