### ISSUE TITLE
libwebsockets server disconnect failed

### ISSUE THREAD

**Issue by sshsu** [warmcat/libwebsockets#1789]
I use lws_set_timeout as below at server to disconnect a connection, but it sometimes will not triggles callbacks  LWS_CALLBACK_CLOSED and LWS_CALLBACK_WSI_DESTROY, anything wrong?
```
      lws_set_timeout(wsi, PENDING_TIMEOUT_CLOSE_SEND, LWS_TO_KILL_ASYNC);
```

**Comment by lws-team** [comment]
If the wsi was in an established state, eg if ws, it had gotten to do the ESTABLISHED callback, and you ask to close it, you should get the CLOSED callback.

When in your code are you doing the set_timeout you pasted above?  (and what vrrsion of lws)

**Comment by sshsu** [comment]
sorry for late, the ws have established and we use it to tranport data for a long time successfully( all message transportations are successfully ),  and then server want to disconnect for some reasons so it uses lws_set_timeout but no triggles callback;
I am not so sure what is the version of lws, I directly pull the master to use and the it's commit info as below
```
commit f13e04f155e605fca27312c45520d79766d0d6b5
Author: Andy Green <andy@warmcat.com>
Date:   Sun Aug 11 06:47:19 2019 +0100

    lws_dsh

```

**Comment by lws-team** [comment]
Well, try current master, that's from like 4 months ago.

**Comment by sshsu** [comment]
use the newest version for two days,  haven't seen the error, I will keep tracking of this, thanks

**Comment by lws-team** [comment]
Let's take it that it's solved then unless more problems coming.

**Comment by sshsu** [comment]
Hi, the problem still exists; 

And, I got a new result;  For client and server,  server will disconnects,  if the connection wasn't closed, then client will also perform disconnect; Then we find out the client socket doesn't exist, but server's corresponding socket still in status ` ESTABLISH`  in this tcp connection ( In tcp hangup , client socket sending 'FIN' should in status FIN_WAIT1 to wait for server response instread of disppearance )

server can find tcp connection with client port 41794
```
root@acnszavl00125:~# netstat -anop | grep 29638
tcp        0      0 172.25.0.21:8086        172.25.0.31:41794       ESTABLISHED 29638/janus      off (0.00/0/0)
```
but in client host, port 29638 are not used

both client's and server's hosts are keep running without reboot or shutdown or power off

**Comment by lws-team** [comment]
Hm 29638 is the pid of your process, not a port number (netstat -p)

I don't really understand the report from lws perspective.  KILL_ASYNC should still do the related callbacks even if the wsi.desc.sockfd is -1.  Have you tried running under valgrind?

**Comment by sshsu** [comment]
> Hm 29638 is the pid of your process, not a port number (netstat -p)
> 
> I don't really understand the report from lws perspective. KILL_ASYNC should still do the related callbacks even if the wsi.desc.sockfd is -1. Have you tried running under valgrind?

I am sorry  for this illustration error , and has corrected it

**Comment by sshsu** [comment]
not yet, haven't tried to use valgrind to check this, I'll try
