### ISSUE TITLE
libwebsocket for ESP32

### ISSUE THREAD

**Issue by KishanPala556** [warmcat/libwebsockets#1791]
Hello lws-team,
Is it possible to use libwebsocket V3.2 stable release with some modification for ESP32?
I know there is a separate lws-esp32-factory available, but failed to build on last commit of esp-idf as mentioned in README. Also not able to build with current esp-idf.

**Comment by lws-team** [comment]
Other people have been able to build -factory as specified just fine.  But it's pinned to old esp-idf... at the time though, that used master lws without changes.

Usefulness of esp32 depends mainly on memory used by mbedtls, the -factory stuff has a patched mbedtls with dynamic record buffer allocation to reduce this.  But mbedtls don't take any nontrivial patches (look at ther 200+ dead PRs) so there's no way forward for it.  They recognized they are "failing the community"

> Contributions from the community were often parked for months or even years without anyone taking time to look into them. We do not want to fail the community any more by ignoring the excellent work provided to the project. We will change that by opening the governance of this project more and more over the coming months, allowing partners and customers to have a say in shaping the library to fit their needs.

https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3

But it's not hard... they just need to decide if they want the topic of the PR or not and close it quickly if not, work with the contributor if so.  They seem to be saying they might at some point look at contributions if their customers tells them to, that's not going to really make mbedtls a normal open source project.

Recently this guy could build it against current esp-idf

https://github.com/warmcat/libwebsockets/pull/1621

But it doesn't solve the mbedtls problem.  The other issue for ws is rfc8441 ws-over-h2 availability and stability in browsers, a working version of this is coming in ffox 72, chrome has it but off by default.  Without that you need one tls tunnel per ws link.

Status is as I wrote at the end of the PR above.
