### ISSUE TITLE
How to integration libev?

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#1793]
Hello, my applications have used libev to handle all io, if integration libwebsocket, how to call lws_service(context, 0);

example:

```
int main(int argc, const char **argv) {
    // ...

    while(1) {
        lws_service(context, 0);
    }

    ev_run(EV_DEFAULT, 0); // required
}
```

I trying use libev timer call lws_service(), but it effect performance.

**Comment by lws-team** [comment]
No need for any conflict between lws service and libev... lws understands how to do its service from a 'foreign' libev loop directly and natively.  Give cmake -DLWS_WITH_LIBEV=1 and look at the 'event lib' examples, eg tell lws to use libev at runtime

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#n370

Tell lws about your foreign libev event loop object when creating the lws context

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#n287

Then just run the libev event loop and lws service is happening automatically.

**Comment by caobug** [comment]
Hello, I remoted lws_service() func from my code and added foreign_loops value, but protocol callback only received LWS_CALLBACK_PROTOCOL_INIT, LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED.

Why not call LWS_CALLBACK_CLIENT_ESTABLISHED, LWS_CALLBACK_CLIENT_WRITEABLE, LWS_CALLBACK_CLIENT_RECEIVE...

If I add `while lws_service()`, it will work normally.

**What did I do wrong?**

```
int init() {
    struct lws_context_creation_info info;
    struct lws_protocols protocol;
    struct ev_loop *loop = EV_DEFAULT;
    struct lws_client_connect_info connect_info;
    void *foreign_loops[1] = { loop };

    memset(&info, 0, sizeof info);
    info.foreign_loops = foreign_loops;
    info.pcontext = &context;
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.protocols = &protocol;
    info.iface = NULL;
    info.pvo = NULL;
    info.pt_serv_buf_size = BUF_SIZE;
    info.options = LWS_SERVER_OPTION_VALIDATE_UTF8 | LWS_SERVER_OPTION_LIBEV;
    info.ssl_cert_filepath = NULL;
    info.ssl_private_key_filepath = NULL;
    info.extensions = extensions;
    info.gid = -1;
    info.uid = -1;

    memset(&protocol, 0, sizeof protocol);
    protocol.name  = "client";
    protocol.callback = &callback;
    protocol.per_session_data_size = sizeof(struct client);
    protocol.rx_buffer_size = BUF_SIZE;
    protocol.id = 0;
    protocol.user = NULL;
    protocol.tx_packet_size = 0;

    context = lws_create_context(&info);
    if (!context) {
        lwsl_err("lws init failed\n");
        return 1;
    }

    memset(&connect_info, 0, sizeof(connect_info));
    connect_info.context = context;
    connect_info.host = host;
    connect_info.port = port;
    connect_info.path = path;
    connect_info.origin = address;
    connect_info.address = address;
    connect_info.ssl_connection = 0;
    connect_info.iface = NULL;
    connect_info.userdata = NULL;
    lws_client_connect_via_info(&connect_info)

    ev_run(loop, 0);
}
```

**Comment by lws-team** [comment]
> What did I do wrong

Does the foreign loop minimal example work if you build it and run with --ev?  I understand it's a server.

What do the verbose lws logs say?

You don't seem to check return code from lws_client_connect_via_info()... if it's NULL it broke there.

**Comment by caobug** [comment]
@lws-team  Hello, I tried run minimal-http-server-eventlib-foreign.c but have the same effect.
If I do n’t make any changes, I run `curl http://127.0.0.1:7681/index.html` directly, status will always be connecting.
If I change these code have got 404.html content (normal).
```
case TEST_STATE_CREATE_LWS_CONTEXT:
/* this only has to exist for the duration of create context */
foreign_loops[0] = foreign_loop;
info.foreign_loops = foreign_loops;

context = lws_create_context(&info);
if (!context) {
    lwsl_err("lws init failed\n");
    return;
}
lwsl_user("LWS Context created and will be active for 10s\n");
// lifetime = 11;
break;
```
```
case TEST_STATE_CREATE_LWS_CONTEXT:
/* this only has to exist for the duration of create context */
foreign_loops[0] = foreign_loop;
info.foreign_loops = foreign_loops;

context = lws_create_context(&info);
if (!context) {
    lwsl_err("lws init failed\n");
    return;
}
lwsl_user("LWS Context created and will be active for 10s\n");
// lifetime = 11;
while (1) {
    lws_service(context, 0);
}
break;
```
build libwebsockets from master:
``` 
mkdir build
cd build
cmake ../ -DLWS_WITH_LIBEVENT=0 -DLWS_WITH_LIBUV=0 -DLWS_WITH_LIBEV=1 -DLWS_WITH_MBEDTLS=1
```

**Comment by caobug** [comment]
Sorry, I have solved the problem.  I should not be used .a file in xcode, everything worked fine after I changed it to .dylib.

**Comment by lws-team** [comment]
Glad you fixed it, because there's no way I can look at your issue and figure that out.  It doesn't even mention it's on Apple platform.
