### ISSUE TITLE
how to use udp in client?

### ISSUE THREAD

**Issue by lewis-v** [warmcat/libwebsockets#1799]
how to use udp in client?

m code
```
...
_wsInstance = lws_create_adopt_udp(vhost, port, LWS_CAUDP_BIND, protocolName.c_str(),
                                       nullptr);
...
int fd = lws_get_socket_fd(_wsInstance);
        if (fd >= 0) {
            const lws_udp* udp = lws_get_udp(_wsInstance);
            if (udp != nullptr){
                lws_udp udp_p = *(udp);
                std::string message = "6666";
                char *bytes = (char *) malloc(message.length() + 1);
                // Make sure the last byte is '\0'
                bytes[message.length()] = '\0';
                strcpy(bytes, message.c_str());
                LOGD("send bef errno:%d\n", errno);

                int n = sendto(fd, bytes, sizeof(message.length() + 1), 0, &udp_p.sa, udp_p.salen);
                LOGD("send errno:%d\n", errno);
                if (n < (ssize_t) message.length()) {
                    LOGD("%s: send returned %d\n", __func__, n);
                }
                free(bytes);
            } else {
                LOGD("lws_get_udp is null");
            }

        } else {
            LOGD("fd is %d", fd);
        }
...
```
sendto is return -1 , errno is 22

**Comment by lws-team** [comment]
> errno is 22

That's EINVAL

> lws_udp udp_p = *(udp);

There is no need making a copy of it AFAIK

>  char *bytes = (char *) malloc(message.length() + 1);

FYI no need to malloc this, you can do it on the stack

>  int n = sendto(fd, bytes, **sizeof(message.length() + 1)**, 0, &udp_p.sa, udp_p.salen);

I dunno what else is wrong or what your code is doing, but the whole sizeof is nonsense, you mean message.length() + 1 without it.

What I would do is run the test under valgrind so I might hear about garbage or uninitialized in syscall parameters that might give EINVAL, and us lws_hexdump_notice() to dump the sockaddr.

**Comment by lewis-v** [comment]
the new code, sendto is success send to server.
```
int fd = lws_get_socket_fd(_wsInstance);
struct sockaddr_in ser_addr;
bzero(&ser_addr, sizeof(ser_addr));
ser_addr.sin_family = AF_INET;
ser_addr.sin_addr.s_addr = inet_addr(_urlParse.getHost().c_str());
ser_addr.sin_port = htons(_urlParse.getPort());
bytesWrite = sendto(fd, frame->getPayload(),
                    static_cast<size_t>(frame->getPayloadLength()), 0,
                    (struct sockaddr *) &ser_addr, sizeof(ser_addr));
```
if i use lws_get_udp to get lws_udp, udp_p.sa.sa_family is 1 (AF_UNIX/AF_LOCAL)
It seems that only local services are available.

the code is run in Android.

**Comment by lws-team** [comment]
Doubt this would return EINVAL.

If you can refer to any lws example code, we can look at the same code.

UDP is not like TCP where the connect() was always sufficient to describe the destination... any UDP socket can send anywhere send by send.  If your connect is the only destination, refer to eg ntpclient code

https://libwebsockets.org/git/libwebsockets/tree/lib/system/ntpclient/ntpclient.c#n84

You can use the udp adopt and then lws_write()

**Comment by lewis-v** [comment]
thank you
