### ISSUE TITLE
Colon missing in x-forwarded-for header name

### ISSUE THREAD

**Issue by chrthi** [warmcat/libwebsockets#1801]
In `lib/roles/http/lextable-strings.h:93`, the entry for the `x-forwarded-for` header is missing a colon at the end. This causes problems with some webservers when proxying.

**Comment by lws-team** [comment]
Thanks, this is pushed.

**Comment by chrthi** [comment]
Thanks! Should `lib/roles/http/lextable.h` be regenerated as well?

**Comment by lws-team** [comment]
Thanks for pointing it out... I guess so... I did it and updated the patches in place.
