### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by thefallentree** [warmcat/libwebsockets#1803]
under Linux 

various places redefines #_GNU_SOURCE  without checking if it exists first,  which causes error , just changes to 
```
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
```

Under mingw64, WIN32  , libevent
1. various places uses `int  fd`, where it should be using evutil_socket_t , which is long long int under windows, 
2. complain about `X509Name *xn `, which seems to be defined as an const under wincrypt.h  , so I had to disable openssl
3. complain about duplicated gettimeofday()

**Comment by lws-team** [comment]
Hm I can fix the first one easily enough.

But the others, I don't have or want windows, you'll need to paste the errors and tell me the exact lws commit so I can have a chance to figure out what to try.

**Comment by lws-team** [comment]
I adapted all instances of _GNU_SOURCE define as you suggested and pushed the patch on master.

For the others 1) I have no clue from "various places", I need to see the compiler errors / warnings, 2) wincrypt.h is not part of lws, I am not sure what I can do about that conflicting with tls library symbols, 3) the gettimeofday() in ./win32port/win32helpers/ is needed for windows build

Basically you'll need to send patches or at least more data / suggestion how to avoid gettimeofday() conflict to fix the rest.

**Comment by thefallentree** [comment]
Yeah, I have an bunch fixes , will send them shortly.

Thanks for the support!
