### ISSUE TITLE
WebSocket on Chrome not staring 

### ISSUE THREAD

**Issue by lailton-dev** [warmcat/libwebsockets#1805]
Hello,

On my FF the websocket using WSS is working perfect fine without any problem, but the CHROME
sometimes when I try to open the conenction I got this error on the console ( error 3 )

example.js:28 WebSocket connection to 'wss://localhost:7681/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 1, reserved3 = 1

Any idea why it happen?

Thanks

**Comment by lws-team** [comment]
What version of lws?

You're using permessage-deflate?

Problem is coming with unchanged minimal example?

Http/2 enabled on lws?

What version and plform of chrome?

**Comment by lailton-dev** [comment]
Hi @lws-team 
LWS version: 3.2.99
Chrome version: Version 77.0.3865.120 (Official Build) (64-bit)
Build with MacOSX last version

I am using the example: minimal-examples/ws-server/minimal-ws-server-threads

You're using permessage-deflate?
I dont know. how can I know it?

Problem is coming with unchanged minimal example?
I will check.

Http/2 enabled on lws?
I dont know. how can I know it?

Thanks

**Comment by lws-team** [comment]
You can find your config in ./build/lws_config.h

> minimal-examples/ws-server/minimal-ws-server-threads

Lws itself is not threadsafe.  So you can save a lot of time by trying the examples and find out at which point the problem starts coming... examples as they are or it needs your code?

**Comment by lailton-dev** [comment]
@lws-team 
The example works fine, I will try to identify where it happen on my code.
Thank you.
