### ISSUE TITLE
What is good way to use lws_write?

### ISSUE THREAD

**Issue by lailton-dev** [warmcat/libwebsockets#1807]
Hi @lws-team,

First of all, thanks for all your help and attention.
I have already good result with this project.

I think now that all my another issue is related to the code that I am using to write message from server side to client side.

```

MY_LWS_SESSION session = ( MY_LWS_SESSION ) getPointerSession( 1 );
	const char * szMsg = ( const char * ) getCharMsg( 2 );
	size_t len = strlen( szMsg );

	if( session != NULL && session->wsi != NULL && len > 0 ){

		unsigned char buffer[LWS_PRE + len];
		memset(&buffer[LWS_PRE], 0, len);
		strncpy((char*)buffer + LWS_PRE, szMsg, len);

		lws_write(session->wsi, &buffer[LWS_PRE], len, LWS_WRITE_TEXT);

	}

```
Can you give me any suggestion or tell me if I am doing something wrong here?

Thanks

**Comment by lws-team** [comment]
You should only call lws_write() from the WRITEABLE callback.

> Can you give me any suggestion or tell me if I am doing something wrong here?

Actually I don't want to guess about your code (or read it).  Just follow what the (70+) examples do.  If the examples don't work, then I will start to worry about it...  If you make up your own way and don't follow the examples, that's great, but your results aren't anything to do with me.
