### ISSUE TITLE
can server one context support ipv4 and ipv6 address at the same time?

### ISSUE THREAD

**Issue by jackim** [warmcat/libwebsockets#1816]
listen both ipv4 addr and ipv6 addr in one context at the same time.

**Comment by lws-team** [comment]
Yes... it's the default if you enable LWS_IPV6=1.

You can try it, libwebsockets.org itself serves using lws with ipv6 enabled, the server has has both ipv4 and ipv6 global addresses and A and AAAA DNS records.
