### ISSUE TITLE
Redirect issues with master branch

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#1820]
Intention and server setup:
http://SERVER/discovery: returns 302 response, Location is /nynp/ws/connect
http://SERVER/connect: this expects an Upgrade to websockets.
The code works when the lws client connects directly to /connect - the websocket is correctly created. The flow on the client does a few things that will become important in the later discussion (because they don't work well when the redirect is encountered):
- when calling ws_client_connect_via_info, the lws library calls lws_create_client_ws_object which allocates wsi->ws
- lws_generate_client_handshake checks the intended GET method. At the start of this method, around line 1160 of client-http.c, the code calls
    meth = lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_METHOD);
    which returns NULL, so the client handshake uses "GET".

```
char *
lws_generate_client_handshake(struct lws *wsi, char *pkt)
{
    const char *meth, *pp = lws_hdr_simple_ptr(wsi,
                _WSI_TOKEN_CLIENT_SENT_PROTOCOLS);
    char *p = pkt, *p1;
    meth = lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_METHOD);
    if (!meth) {
        meth = "GET";
        wsi->do_ws = 1;
    } else {
        wsi->do_ws = 0;
    }
```
When the lws client connects to /discovery, the server reports 302 with a location, and the lws client attempts to parse the response in lws_client_interpret_server_handshake. Redirect handling starts around line 800 - with an if containing
```
        (n == 301 || n == 302 || n == 303 || n == 307 || n == 308)
```
Line ca 890 in lws_client_interpret_server_handshake contains a call to lws_client_reset(). This, among other things, deallocates wsi->ws. lws_client_reset also contains code that stores information about the headers, including the method.

```
    for (n = 0; n < (int)LWS_ARRAY_SIZE(hnames2); n++)
        if (lws_hdr_total_length(wsi, hnames2[n])) {
            memcpy(p, lws_hdr_simple_ptr(wsi, hnames2[n]),
                lws_hdr_total_length(wsi, hnames2[n]) + 1);
            p += lws_hdr_total_length(wsi, hnames2[n]) + 1;
        } else
            *p++ = '\0';

```
Note that when n == 2, hnames[ 2 ] is _WSI_TOKEN_CLIENT_METHOD. lws_hdr_total_length() will then return 0, so the else branch is executed. This will later cause lws_hdr_simple_ptr() to start returning "" instead of NULL for _WSI_TOKEN_CLIENT_METHOD.
When the 2nd connection attempt is made (to the URL returned by the 302 Location), the generated request will have several problems:
1. Because lws_hdr_simple_ptr now returns NULL for method, lws_generate_client_handshake will use a method "" (empty string), which generates an invalid HTTP request - something like
" /connect HTTP/1.1"
(without the quotes; that is, no method, and starting with space)
lws_generate_client_handshake (and similar places) might thus need to be changed to interpret "" in the same way as NULL.
2. If I locally modify the code in such a way, it shows a 2nd problem: since wsi->ws was freed in lws_client_reset, the code will eventually crash. Thus, when lws_client_reset is called, the lws->ws structure probably needs to be allocated. I tried an ugly hack - right after the call to lws_client_reset(), add something like

```
        wsi->ws = lws_zalloc(sizeof(*wsi->ws), "client ws struct");
        wsi->ws->ietf_spec_revision = SPEC_LATEST_SUPPORTED;
```

(i.e. this is the contents of lws_create_client_ws_object, hardcoded just to prove whether or not it works - I don't have the lws_client_connect_info struct to call lws_create_client_ws_object again.)
And with this change, the redirected request can actually successfully complete a websocket upgrade even if the server initially returns 302 redirect.
The code changes mentioned here are hacks, and not really usable in production code, but they show places that would need looking into.

**Comment by jzer0** [comment]
Please also note that this behavior does not seem to affect the latest stable branch.

**Comment by lws-team** [comment]
Yes the immediate cause is improvements to the client stuff in master.  But trying to reproduce it I found the server side would favour just doing the ws connection before it checked for redirect... I changed it to check first and added a redirect https://libwebsockets.org/redir-testserver that points to /testserver and confirmed the other fixes worked with that.  So please give it a try.

**Comment by jzer0** [comment]
Thanks so much, you guys are lightning fast!  Tested the changes and everything seems to be working as expected now.  Thanks again!
