### ISSUE TITLE
Code correctness, possible issue concern - master branch

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#1821]
Question on code correctness, possible issue:

lws_client_reset contains - ~line 1062 or so of client-handshake.c
#if defined(LWS_WITH_TLS)
	if (!ssl)
		wsi->tls.use_ssl &= LCCSCF_USE_SSL;
	else
		wsi->tls.use_ssl |= LCCSCF_USE_SSL;
#else...

It seems that, if ssl is false, then use_ssl gets all OTHER bits reset. Perhaps it was meant to be
		wsi->tls.use_ssl &= ~ LCCSCF_USE_SSL;

?

**Comment by lws-team** [comment]
Thanks, it's fixed in master.  But I think this particular one would be caught elsewhere as a redirect tls downgrade.
