### ISSUE TITLE
mbedTLS hostname mismatch

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#1829]
I'm having trouble getting the LWS client to accept a (kind-of) self-signed certificate with mbedTLS whereas with OpenSSL it works fine. 

For tests, I'm using a certificate generated by github.com/jsha/minica - it creates a certificate authority and a server certificate. I've generated the certificate for an IP address, 127.0.0.1 and have configured the server to use the certificate and set up the client to load the CA's public key. 

As I've said above when linked against OpenSSL, it works fine (even after the hostname validation fix in the other issue). MbedTLS client however returns the following error: `server's cert didn't look good, X509_V_ERR = 62: Hostname mismatch`

Also, I'm pretty sure the CA public .pem is loaded properly because if I don't load it, it returns a different error (expected): `server's cert didn't look good, X509_V_ERR = 24: CA is not trusted`

I strongly suspect it has something to do with using the IP address, because when I've just (as a last resort :) ) set up an entry in /etc/hosts for `127.0.0.1     lwstest.com`, generated a certificate for that one and set it as a host, it connected just fine.

I'd be fine with using `localhost` if there's nothing that can be done about the IP address access for mbedTLS, however it doesn't work either with `connect failed` & `errno=111` for neither mbedTLS nor OpenSSL

**Comment by lws-team** [comment]
What are you setting `info.host` to?

At least in 2016, mbedtls just didn't do IP cert validation

https://github.com/ARMmbed/mbedtls/issues/466#issuecomment-214576894

**Comment by vaind** [comment]
> What are you setting `info.host` to?

`clientConnectInfo_.origin = clientConnectInfo_.host = clientConnectInfo_.address = hostname_.c_str();`

i.e. to `127.0.0.1`

**Comment by lws-team** [comment]
These two observations seem to conflict

>  lwstest.com, generated a certificate for that one and set it as a host, it connected just fine.

>  it doesn't work either with connect failed & errno=111 for neither mbedTLS nor OpenSSL

You mean that "localhost" resolved in /etc/hosts is somehow especially cursed compared to "lwstest.com" resolved there?

**Comment by vaind** [comment]
I don't "mean" anything, just stating the behaviour I see :)

I've figured out what's the issue with localhost - the client was connecting on ipv6 localhost by default. When I commented that entry out in /etc/hosts, localhost works.

I'd still rather use an IP address to make sure the test is portable across the dev/CI machines without requiring an environment change. 

Regarding IP-address as hostname in mbedTLS - it seems like it should be supported now? See "Special situations" section in https://tls.mbed.org/kb/how-to/use-sni

**Comment by lws-team** [comment]
> I don't "mean" anything, just stating the behaviour I see :)

I'm downstream of whatever you write here, if it conflicts, I can just get confused, ignore the whole thing or point out it conflicts.

> Regarding IP-address as hostname in mbedTLS - it seems like it should be supported now?

Well, it says

>> Sometimes certificates are issued for IP addresses and not DNS names. Unfortunately, Mbed TLS doesn't yet support using such certificates while SNI is turned on. This means that you may be able to set IP addresses with the mbedtls_ssl_set_hostname function, but it will result in non-compliant behavior and limited functionality.

In lws, we use SNI because that's way more valuable than IP certs.  If you want to see what happens if you disable SNI for mbedtls and offer a patch with reasonable integration (like a per-vhost options flag), I'd consider such a patch.  But I don't plan on doing it myself.

**Comment by vaind** [comment]
Wasn't sure about that. Thanks for the help, I'll try to figure something out. I guess we can close this for now if you're saying it's an mbedTLS "issue", not related to its integration in LWS

**Comment by lws-team** [comment]
Mbedtls itself in your link says it's incompatible with SNI and lws uses SNI... I don't plan on spending time on it because I don't use IP certs, I have never seen one in the wild and you're the first person inquiring about them in 10 years :-)
