### ISSUE TITLE
ARM64 build process failing - error: implicit declaration of function 'lws_tls_extant' 

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#1830]
NDK version: r17c
android API version: 27

So close in getting this built without issue, have both libuv and openssl 1.1.1d compiled and built for ARM64 using the above Android ARM64 tools.  The initial CMAKE goes perfectly, but the make process is failing:  

[ 28%] Building C object CMakeFiles/websockets_shared.dir/lib/tls/tls.c.o
/media/jzer0/Dev/workspace/libwebsockets/lib/tls/tls.c: In function 'lws_tls_use_any_upgrade_check_extant':
/media/jzer0/Dev/workspace/libwebsockets/lib/tls/tls.c:290:2: error: implicit declaration of function 'lws_tls_extant' [-Werror=implicit-function-declaration]
  if (!lws_tls_extant(buf)) {
  ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/websockets_shared.dir/lib/tls/tls.c.o] Error 1
make[1]: *** [CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [all] Error 2

To work around this I commented out the #if !defined around this function to ensure that is is not implicit:

//#if !defined(LWS_WITH_ESP32) && !defined(LWS_PLAT_OPTEE) && !defined(OPTEE_DEV_KIT)

static int
lws_tls_extant(const char *name)
{
	/* it exists if we can open it... */
	int fd = open(name, O_RDONLY), n;
	char buf[1];

	if (fd < 0)
		return 1;

	/* and we can read at least one byte out of it */
	n = read(fd, buf, 1);
	close(fd);

	return n != 1;
}
//#endif

and I am able to successfully make the libraries.  Not sure what kind of impact or instability this could introduce.  Tried with both master and 3.2 stable branch.

**Comment by lws-team** [comment]
Just going by what you pasted above, isn't it the same as saying you have defined LWS_WITH_ESP32 and / or one of the OPTEE defines?  None of those should be defined for Android case.

**Comment by jzer0** [comment]
I don't think I have, at least not intentionally.  Here is my cmake statement:

cmake ../ -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=27 -DCMAKE_TOOLCHAIN_FILE=/media/jzer0/Dev/development/libwebsockets/contrib/cross-aarch64.cmake -DLWS_WITH_SSL=1 -DLWS_WITH_LWSWS=1 -DLWS_WITHOUT_TESTAPPS=1 -DLWS_LIBUV_LIBRARIES=/media/jzer0/Dev/development/libuv/out/Debug/libuv.a -DLWS_LIBUV_INCLUDE_DIRS=/media/jzer0/Dev/development/libuv/include -DLWS_ZLIB_LIBRARIES=/media/jzer0/Dev/development/zlib-1.2.8/cmake/Debug/libz.so -DLWS_ZLIB_INCLUDE_DIRS=/media/jzer0/Dev/development/zlib-1.2.8/cmake/build/include -DLWS_OPENSSL_INCLUDE_DIRS=/media/jzer0/Dev/development/openssl-1.1.1d/include -DLWS_OPENSSL_LIBRARIES="/media/jzer0/Dev/development/openssl-1.1.1d/libssl.a;/media/jzer0/Dev/development/openssl-1.1.1d/libcrypto.a;"

**Comment by lws-team** [comment]
`contrib/cross-aarch64.cmake` has it, I originally wrote it when using lws with OPTEE... make a copy of it and remove the stuff like that in `CMAKE_C_FLAGS` that is unrelated to what you're doing.

**Comment by jzer0** [comment]
also, just so you are aware, the cross-aarch64.cmake file uses the old compiler naming, 

# Name of C compiler.
set(CMAKE_C_COMPILER "aarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-g++")

should be 

# Name of C compiler.
set(CMAKE_C_COMPILER "aarch64-linux-android-gcc")
set(CMAKE_CXX_COMPILER "aarch64-linux-android-g++")

**Comment by lws-team** [comment]
That may be 'old compiler naming" from Android perspective but it's a legit toolchain tuple that is in use in other contexts / platforms... the main point is the toolchain files given in lws are just starting points to make your own that match your toolchain and cross arrangements.

**Comment by jzer0** [comment]
Yep, all good now.  Thanks so much!

**Comment by lws-team** [comment]
Since I can see this coming up again for future Android users, I also pushed a patch on master adding a separate toolchain file `contrib/cross-aarch64-android.cmake` with the OPTEE stuff removed and using the tuple you mentioned above.

**Comment by liyoubdu** [comment]
what is your command line, which operating system you running?

**Comment by jzer0** [comment]
My cmake command is posted above.  This was on an x64 Ubuntu 18.04.4 LTS virtual machine.

**Comment by lws-team** [comment]
FWIW yesterday I added android NDK build to lws CI and documented how to build with NDK

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-android.md

Currently you can see the build of master against the NDK on arm64 here

https://libwebsockets.org/sai/index.html?task=4143c2c13876595bbb3bb491659fc0a402c061554d714ced68f53c3f590708ca
