### ISSUE TITLE
#error "If you want lws_dir onw windows, you need libuv"

### ISSUE THREAD

**Issue by Oozlum** [warmcat/libwebsockets#1831]
I'm getting this error when building for Windows using mingw64 on Mac OSX.  I have unchecked both LWS_WITH_DIR and LWS_WITH_LIBUV in the CMake GUI, as I don't want either.  It seems like it is ignoring the LWS_WITH_DIR setting?

**Comment by lws-team** [comment]
Cmake uses its CMakeCache.txt all the time... if you gave a -DX=Y one time and don't give it again, it will be applied in a sticky way from the cache file silently every time afterwards.

LWS_WITH_DIR is off by default for WIN32 but set if LWS_WITH_LEJP_CONF is set... if you didn't spend a while configuring it exactly how you like I'd delete CMakeCache.txt from your build dir and start over.

**Comment by Oozlum** [comment]
Great, thanks.

**Comment by Oozlum** [comment]
Sorry to re-open this, I thought I had it resolved.  I've tried building from a clean git clone and I'm still having this problem.  My [CMakeCache.txt](https://github.com/warmcat/libwebsockets/files/4086953/CMakeCache.txt) shows that LWS_WITH_DIR is off.

**Comment by lws-team** [comment]
The only way to get that file built is LWS_WITH_DIR set...

```
if (LWS_WITH_DIR)
        list(APPEND SOURCES lib/misc/dir.c)
endif()
```

Try deleting your ./build/Makefile I guess but I don't see how you manage to get that... this is current master is it or something else?

**Comment by Oozlum** [comment]
Current master, pulled a few minutes ago. Build directory completely blown away and CMake started from scratch. It tries to build that file every time.  Are there any other helpful files I can show?

**Comment by lws-team** [comment]
Hm... when you build with mingw64, does cmake actually feel that `WIN32` is defined as it does when you build natively under windows?

Which of these (somewhat redundant) messages is printed from this during the cmake action?

```
if (WIN32 OR LWS_PLAT_FREERTOS)
        message(STATUS "No LWS_WITH_DIR and LWS_WITH_DIR")
        set(LWS_WITH_DIR OFF)
        set(LWS_WITH_LEJP_CONF OFF)
        message("LWS_WITH_DIR ${LWS_WITH_DIR}")
else()
        message(STATUS "Compiled with LWS_WITH_DIR and LWS_WITH_DIR")
        set(LWS_WITH_DIR ON)
        set(LWS_WITH_LEJP_CONF ON)
endif()
```

**Comment by Oozlum** [comment]
`Compiled with LWS_WITH_DIR and LWS_WITH_DIR`

How is WIN32 derived in CMake?  WIN32 is certainly defined by mingw. 
[Output](https://github.com/warmcat/libwebsockets/files/4087191/defines_output.txt) of `gcc -E -dM` attached.

**Comment by lws-team** [comment]
> How is WIN32 derived in CMake

Who knows... it's a magic define set by the platform when you run cmake.  It's not about gcc, it's only cmake's symbol; what gcc thinks is unrelated (unless cmake gets it from gcc, but I doubt it).

We can understand if it's set or not by looking for the strings I mentioned above.

**Comment by Oozlum** [comment]
Ok, I think I'm getting somewhere.  The first lines of the CMake output are:
`Compiled with LWS_WITH_DIR and LWS_WITH_DIR
CMAKE_TOOLCHAIN_FILE='/Users/chris/src/libwebsockets/contrib/cross-w32.cmake'
Git commit hash: v3.1.0-485-g65527443
 GENCERTS = 0
RPM tools not available on Win32 systems`

The last line is generated by:
`IF (WIN32)
  MESSAGE(STATUS "RPM tools not available on Win32 systems")
ENDIF(WIN32)`

So `WIN32` is certainly true at that point.  It seems that `WIN32` is derived from `CMAKE_SYSTEM_NAME`, which is set in the toolchain file.  The toolchain file looks from the output like it is loaded after `LWS_WITH_DIR` is checked at the top.

**Comment by lws-team** [comment]
Yeah that seems to directly answer the mystery, on mingw `WIN32` suddenly makes an appearance partway through the cmake file.  Unfortunately cmake is mysterious about when it's loaded

> If cmake(1) is invoked with the command line parameter -DCMAKE_TOOLCHAIN_FILE=path/to/file, the file will be loaded early to set values for the compilers. The CMAKE_CROSSCOMPILING variable is set to true when CMake is cross-compiling.

https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

Can you possibly move this down the CMakeLists.txt until we find where the toolchain comes in?

```
if (WIN32)
 MESSAGE(FATAL_ERROR "keep trying")
endif(WIN32)
```

Then we can move the logic that uses WIN32 below whereever it is.

**Comment by Oozlum** [comment]
Line 274: `project(libwebsockets C)` causes WIN32 to be defined.

**Comment by lws-team** [comment]
Thanks... I moved the project line to be much earlier and pushed a patch on master for that and some spelling mistakes / refactor typos seen while looking at this.  Please give it a try.

**Comment by Oozlum** [comment]
Yep, that got it.  Thanks.

**Comment by lws-team** [comment]
Great, thanks for the help figuring it out.
