### ISSUE TITLE
OpenSSL/pthread clang error

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#1835]
Me again :) Having trouble building the latest v3.2.2 on MacOS.

Getting
```
/lws-genhash.h:79:18: error: field has incomplete type
      'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
```

Which is in turn almost certainly caused by OpenSSL not being recognized: getting stuff like `-- Looking for HMAC_CTX_new - not found` for all the openssl checks.

When I look into the CMakeError.log, I get the following clang error related to pthread:
```
Determining if the function HMAC_CTX_new exists failed with the following output:
Change Dir: ...lws-3.2.2-openssl-build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_75202/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_75202.dir/build.make CMakeFiles/cmTC_75202.dir/build
Building C object CMakeFiles/cmTC_75202.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DKEYWORD=__inline -I.../openssl-1.1.1b/include  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers  -DMDB_USE_POSIX_SEM=1 -Werror=return-type -Werror=gnu-conditional-omitted-operand  -Wno-deprecated-declarations -pthread -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -pthread -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -fPIE   -o CMakeFiles/cmTC_75202.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_75202
/usr/local/Cellar/cmake/3.12.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_75202.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers  -DMDB_USE_POSIX_SEM=1 -Werror=return-type -Werror=gnu-conditional-omitted-operand  -Wno-deprecated-declarations -pthread -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -pthread -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_75202.dir/CheckFunctionExists.c.o  -o cmTC_75202 .../openssl-1.1.1b/lib/libssl.a .../openssl-1.1.1b/lib/libcrypto.a -lm -ldl 
clang: error: argument unused during compilation: '-pthread'
clang: error: argument unused during compilation: '-pthread'
make[5]: *** [cmTC_75202] Error 1
make[4]: *** [cmTC_75202/fast] Error 2
```

I've found some possibly related comments WRT this in CmakeLists.txt but I'm not really sure how to get this fixed. Any ideas?

**Comment by lws-team** [comment]
> latest v3.2.2 

Although I'll backport fixes to v3.2-stable until the next release, all new development and fixes here happens on master

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

So, does this problem happen the same on master?  I seem to recall a patch about something similar it in the last weeks.

Also, lws is built in CI against OpenSSL on OSX, eg

https://travis-ci.org/warmcat/libwebsockets/jobs/640855712#L1360

Neither v3.2 nor master have this problem there.

**Comment by lws-team** [comment]
You might want to look here https://github.com/mesonbuild/meson/issues/2628 it seems it can be quirky on OSX / clang depending on what clang it is.

**Comment by vaind** [comment]
It happens on a rather old system. Clang version: `Apple LLVM version 8.0.0 (clang-800.0.42.1)`

I'll post here once I get to try the `master` and/or a newer clang on another system.

**Comment by vaind** [comment]
It's the same with `master`. Couldn't get to try on a newer clang, however this setup workes just fine with the previous version (3.1.0).

Also notably, we're not building against a os-provided/prebuilt OpenSSL but against a separately built one, with paths specified to the LWS

**Comment by lws-team** [comment]
>> clang: error: argument unused during compilation: '-pthread'

>  however this setup workes just fine with the previous version (3.1.0).

Basically your compiler says it doesn't understand -pthread "during compilation"... but AFAICS the v3.1-stable CMakeLists.txt has about the same for this, if anything it added a check on master

```
-set(CMAKE_REQUIRED_FLAGS "-pthread")   
-CHECK_C_SOURCE_COMPILES("#define _GNU_SOURCE 
-       #include <pthread.h> 
-       int main(void) { 
-               pthread_t th = 0;
-               pthread_setname_np(th, NULL);
-               return 0;
-       }" LWS_HAS_PTHREAD_SETNAME_NP)
+if (LWS_HAVE_PTHREAD_H)
+       set(CMAKE_REQUIRED_FLAGS "-pthread")
+       CHECK_C_SOURCE_COMPILES("#define _GNU_SOURCE
+               #include <pthread.h>
+               int main(void) {
+                       pthread_t th = 0;
+                       pthread_setname_np(th, NULL);
+                       return 0;
+               }" LWS_HAS_PTHREAD_SETNAME_NP)
+endif()
```

So I dunno why v3.1 should be any different, it's also doing `set(CMAKE_REQUIRED_FLAGS "-pthread")`.  Why don't you use `make VERBOSE=1` to see the actual compiler commandline in both cases, maybe we're adding it twice now or something?

**Comment by lws-team** [comment]
How about this

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d721a6a13..5218b6f90 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -935,7 +935,12 @@ CHECK_C_SOURCE_COMPILES("#include <stdint.h>
        }" LWS_HAS_INTPTR_T)
 
 if (LWS_HAVE_PTHREAD_H)
-       set(CMAKE_REQUIRED_FLAGS "-pthread")
+       if ((CMAKE_C_COMPILER_ID MATCHES "Clang") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
+               set(CMAKE_REQUIRED_FLAGS "-pthread -Wno-error=unused-command-line-argument")
+       else()
+               set(CMAKE_REQUIRED_FLAGS "-pthread")
+       endif()
+
        CHECK_C_SOURCE_COMPILES("#define _GNU_SOURCE
                #include <pthread.h>
                int main(void) {
@@ -1599,7 +1604,7 @@ if (COMPILER_IS_CLANG)
        # otherwise osx blows a bunch of openssl deprecated api errors
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-deprecated-declarations" )
        if (UNIX AND LWS_HAVE_PTHREAD_H)
-               set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread" )
+               set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread -Wno-error=unused-command-line-argument" )
        endif()
 endif()
 

```

**Comment by vaind** [comment]
Couldn't get the patch applied because of `patch unexpectedly ends in middle of line` but it did seem to work when I've changed the cmakelists.txt manually

**Comment by lws-team** [comment]
Thanks, I pushed it on v3.2-stable and master.

**Comment by prologic** [comment]
@lws-team Note that I reference this issue because I get the exact same error when trying to build a static linked version of [Netdata Agent](https://github.com/netdata/netdata) in our Docker-based Alpine-3.7 build environment (_yes I know its old, but upgrading this also exhibits other/different problems, so one step at a time_).

**Comment by prologic** [comment]
Note for ref, I've tried to upgrade to `v3.2.3` and `4.x` (_haven't tried the `master` branch_); same build failure.

**Comment by lws-team** [comment]
Have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

Note master has had a big refactor for cmake.  If we can understand your problem we can probably fix it on there if it still exists.

**Comment by prologic** [comment]
I solved it with the right set of `-D` flags.

**Comment by pvouzis** [comment]
@prologic can you share the -D flags you used?

**Comment by prologic** [comment]
> @prologic can you share the -D flags you used?

Sorry I should have mentioned the PR. I have to go find it again. What system were you having problems with, can you remind me? It might help me find the PR :)
