### ISSUE TITLE
Hosting webpage on HTTPS - decompression failure

### ISSUE THREAD

**Issue by aFilipMalinowski** [warmcat/libwebsockets#1837]
Hi folks.

**Environment:**
libwebsockets version: commit id 934da8629112a57d11ace8796c82d2f8342825cb (23.01.2020)
zlib version: 1.2.8
openssl version: 1.1.1d
operating system: Ubuntu 18.04.3 LTS

**What I'm doing:**
I created HTTP server. For that I created mount for custom-written http protocol (to support client-side routing, Angular webapp), for which I create then two vhosts. First one for http port 8080, second one for https port 8081. I believe that initialization is successful, taking look at the log:
```
[LIBWEBSOCKET][NOTICE]  Vhost 'localhost' using TLS mode
[LIBWEBSOCKET][NOTICE]    vhost localhost: cert expiry: 945d
```
**What is happening:**
When I try to access the webpage through https protocol (and port 8081), I get an error on Chrome side:
```
ERR_HTTP2_COMPRESSION_ERROR
```
as well as some strange log on libwebsockets side
```
[LIBWEBSOCKET][NOTICE] GOAWAY: last sid 0, error 0x00000009, string 'Framer error: 6 (DECOMPRESS_FAI'
[LIBWEBSOCKET][NOTICE] GOAWAY: last sid 0, error 0x00000009, string 'Framer error: 6 (DECOMPRESS_FAI'
[LIBWEBSOCKET][NOTICE] GOAWAY: last sid 0, error 0x00000009, string 'Framer error: 6 (DECOMPRESS_FAI'
```

Would love to receive some help with it.

**Comment by lws-team** [comment]
So https://warmcat.com and https://libwebsockets.org are running today's master at the moment and have h2 enabled.

I just opened up Chrome dev 81 and visited https://warmcat.com ... that works fine.

What about that is not a valid reproducer for the problem you described?

> I created mount for custom-written http protocol 

This ---^?

**Comment by aFilipMalinowski** [comment]
Hmm. Most likely I just did something wrong in it.
I will attach the source. Needed to change the extension from .c to .txt. Could you please take a look at it?

In the source code you'll see a bit of macros like slim_char. These are 1to1 mappings of normal char, etc.
[http_thread.txt](https://github.com/warmcat/libwebsockets/files/4126962/http_thread.txt)

**Comment by lws-team** [comment]
The only thing we have in common is we'd both prefer that lws worked like it's supposed to... I don't actually have any reason to make your sources work or spend any time looking at them.

If you think lws is broken somewhere, the way that works for both of us is either describe how to reproduce it with the stock pieces, or lightly modify one of the minimal examples to demonstrate the problem and provide the diff so I can reproduce it... I'll definitely look at it.
