### ISSUE TITLE
OpenSSL/ZLib question, possible build issue

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#1840]
Hi LWS,

Question about building zlib and openssl with relation to lws.  When building openssl and including the parameters to build with zlib, i.e.:

./Configure no-shared no-hw no-engine no-dso **zlib** --debug --with-zlib-include=/media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/include --with-zlib-lib=/media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/lib/libz.a  android-arm --prefix=/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug --openssldir=/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug

This seems to cause some problem between libwebsockets and openssl:

...
zlib/miniz include dirs: /media/jzer0/Dev/development/zlib-1.2.11/ARM/include
zlib/miniz libraries: /media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/libz.a
Compiling with SSL support
OpenSSL include dir: /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/include
OpenSSL libraries: /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libssl.a;/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libcrypto.a
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
libuv include dir: /media/jzer0/Dev/development/libuv/include
libuv libraries: /media/jzer0/Dev/development/libuv/libuv_Android_ARM/Debug/libuv.a
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for EVP_PKEY_new_raw_private_key
-- Looking for EVP_PKEY_new_raw_private_key - not found
...

Without the zlib specification LWS builds as expected:

Compiling with SSL support
OpenSSL include dir: /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/include
OpenSSL libraries: /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libssl.a;/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libcrypto.a
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
libuv include dir: /media/jzer0/Dev/development/libuv/include
libuv libraries: /media/jzer0/Dev/development/libuv/libuv_Android_ARM/Debug/libuv.a
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - found
...

I'm making sure to compile zlib and openssl for the same architecture that is intended for LWS.  I also have the same configuration failures if I specify the LWS_WITH_ZLIB=1 and provide the include and lib paths when building LWS (with/without zlib in openssl configure) .

**Comment by lws-team** [comment]
I take it you mean this as the "problems"...

```
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
```

take a look at the last instance of X509_VERIFY_PARAM in `./build/CMakeFiles/CMakeError.log` and paste the section about what it feels is wrong here for your toolchain / setup.  It's easiest to delete that file, delete CMakeCache.txt and then run cmake with your options, because otherwise that file gets appended to between sessions and can be big and misleading.

I can guess its problem is you told openssl to build against zlib, but openssl doesn't link to it.  Then the openssl lib is no longer "selfcontained" and these tests - making little executables - fail because these haven't been told to link against zlib.  But you say

> the same configuration failures

I think it's a good idea to actually go look at the compile / link errors as above to find out if they are actually "the same".

**Comment by jzer0** [comment]
The problem is that none of these aspects are found if zlib is specified in the configuration of openssl, but you are correct in that the failures are actually different.

Here are the failures reported in CMakeError.log:

- With LWS_WITH_ZLIB and paths to zlib include and static library:

Determining if the function SSL_CTX_set1_param exists failed with the following output:
Change Dir: /media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ad930/fast"
/usr/bin/make -f CMakeFiles/cmTC_ad930.dir/build.make CMakeFiles/cmTC_ad930.dir/build
make[1]: Entering directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ad930.dir/CheckFunctionExists.c.o
/media/jzer0/Dev/development/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/jzer0/Dev/development/android-ndk-r15c/sysroot -DKEYWORD=__inline -I/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions  -DCHECK_FUNCTION_EXISTS=SSL_CTX_set1_param -pthread -g -fPIE   -o CMakeFiles/cmTC_ad930.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
make[1]: *** No rule to make target '/media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/libz.a', needed by 'cmTC_ad930'.  Stop.
make[1]: Leaving directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ad930/fast' failed
make: *** [cmTC_ad930/fast] Error 2

- Without LWS_WITH_ZLIB and zlib paths:

Determining if the function SSL_CTX_set1_param exists failed with the following output:
Change Dir: /media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_84a24/fast"
/usr/bin/make -f CMakeFiles/cmTC_84a24.dir/build.make CMakeFiles/cmTC_84a24.dir/build
make[1]: Entering directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_84a24.dir/CheckFunctionExists.c.o
/media/jzer0/Dev/development/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/jzer0/Dev/development/android-ndk-r15c/sysroot -DKEYWORD=__inline -I/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions  -DCHECK_FUNCTION_EXISTS=SSL_CTX_set1_param -pthread -g -fPIE   -o CMakeFiles/cmTC_84a24.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_84a24
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_84a24.dir/link.txt --verbose=1
/media/jzer0/Dev/development/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/jzer0/Dev/development/android-ndk-r15c/platforms/android-23/arch-arm -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions  -DCHECK_FUNCTION_EXISTS=SSL_CTX_set1_param -pthread -g  -fPIE -pie -Wl,--gc-sections -Wl,-z,nocopyreloc  CMakeFiles/cmTC_84a24.dir/CheckFunctionExists.c.o  -o cmTC_84a24 /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libssl.a /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libcrypto.a /media/jzer0/Dev/development/libuv/libuv_Android_ARM/Debug/libuv.a -lm -ldl 
crypto/comp/c_zlib.c:136: error: undefined reference to 'inflateInit_'
crypto/comp/c_zlib.c:145: error: undefined reference to 'deflateInit_'
crypto/comp/c_zlib.c:160: error: undefined reference to 'inflateEnd'
crypto/comp/c_zlib.c:161: error: undefined reference to 'deflateEnd'
crypto/comp/c_zlib.c:180: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:201: error: undefined reference to 'inflate'
crypto/comp/c_zlib.c:354: error: undefined reference to 'inflateEnd'
crypto/comp/c_zlib.c:359: error: undefined reference to 'deflateEnd'
crypto/comp/c_zlib.c:387: error: undefined reference to 'inflateInit_'
crypto/comp/c_zlib.c:398: error: undefined reference to 'inflate'
crypto/comp/c_zlib.c:401: error: undefined reference to 'zError'
crypto/comp/c_zlib.c:450: error: undefined reference to 'deflateInit_'
crypto/comp/c_zlib.c:484: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:487: error: undefined reference to 'zError'
crypto/comp/c_zlib.c:531: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:536: error: undefined reference to 'zError'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_84a24.dir/build.make:100: recipe for target 'cmTC_84a24' failed
make[1]: *** [cmTC_84a24] Error 1
make[1]: Leaving directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_84a24/fast' failed
make: *** [cmTC_84a24/fast] Error 2

**Comment by lws-team** [comment]
The first one is a bit confusing... the compile seemed to work.  Does `/media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/libz.a` actually exist?

The second one is what I guessed before... you built a sort of booby-trapped openssl that's no longer selfcontained.  Anywhere you link to that it will fail unless you also feed it libz.

**Comment by jzer0** [comment]
Ugh, sorry about that, path was off a bit, zlib.a was in /lib.  With the path fixed the error is essentially the same as without LWS_WITH_ZLIB:

Determining if the function SSL_CTX_set1_param exists failed with the following output:
Change Dir: /media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4a700/fast"
/usr/bin/make -f CMakeFiles/cmTC_4a700.dir/build.make CMakeFiles/cmTC_4a700.dir/build
make[1]: Entering directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4a700.dir/CheckFunctionExists.c.o
/media/jzer0/Dev/development/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/jzer0/Dev/development/android-ndk-r15c/sysroot -DKEYWORD=__inline -I/media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include -isystem /media/jzer0/Dev/development/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi  -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions  -DCHECK_FUNCTION_EXISTS=SSL_CTX_set1_param -pthread -g -fPIE   -o CMakeFiles/cmTC_4a700.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_4a700
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4a700.dir/link.txt --verbose=1
/media/jzer0/Dev/development/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/jzer0/Dev/development/android-ndk-r15c/platforms/android-23/arch-arm -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers -march=armv5te -mthumb -msoft-float -mtune=xscale -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=23 -fexceptions  -DCHECK_FUNCTION_EXISTS=SSL_CTX_set1_param -pthread -g  -fPIE -pie -Wl,--gc-sections -Wl,-z,nocopyreloc  CMakeFiles/cmTC_4a700.dir/CheckFunctionExists.c.o  -o cmTC_4a700 **/media/jzer0/Dev/development/zlib-1.2.11/ARM/Debug/lib/libz.a** /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libssl.a /media/jzer0/Dev/development/openssl-1.1.1d/ARM/Debug/lib/libcrypto.a /media/jzer0/Dev/development/libuv/libuv_Android_ARM/Debug/libuv.a -lm -ldl 
crypto/comp/c_zlib.c:136: error: undefined reference to 'inflateInit_'
crypto/comp/c_zlib.c:145: error: undefined reference to 'deflateInit_'
crypto/comp/c_zlib.c:160: error: undefined reference to 'inflateEnd'
crypto/comp/c_zlib.c:161: error: undefined reference to 'deflateEnd'
crypto/comp/c_zlib.c:180: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:201: error: undefined reference to 'inflate'
crypto/comp/c_zlib.c:354: error: undefined reference to 'inflateEnd'
crypto/comp/c_zlib.c:359: error: undefined reference to 'deflateEnd'
crypto/comp/c_zlib.c:387: error: undefined reference to 'inflateInit_'
crypto/comp/c_zlib.c:398: error: undefined reference to 'inflate'
crypto/comp/c_zlib.c:401: error: undefined reference to 'zError'
crypto/comp/c_zlib.c:450: error: undefined reference to 'deflateInit_'
crypto/comp/c_zlib.c:484: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:487: error: undefined reference to 'zError'
crypto/comp/c_zlib.c:531: error: undefined reference to 'deflate'
crypto/comp/c_zlib.c:536: error: undefined reference to 'zError'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_4a700.dir/build.make:101: recipe for target 'cmTC_4a700' failed
make[1]: *** [cmTC_4a700] Error 1
make[1]: Leaving directory '/media/jzer0/Dev/development/libwebsockets/ARM/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4a700/fast' failed
make: *** [cmTC_4a700/fast] Error 2

**Comment by lws-team** [comment]
IIRC this kind of thing is related to ordering... the linker processes libz and says, "huh... nobody wanted that".  Only after it meets libcrypto does it understand it wants those imports from libz.  But it has "done libz" by then since it was earlier on the link commandline.

If you add here

https://libwebsockets.org/git/libwebsockets/tree/CMakeLists.txt#n1961

... something like...

```
    if (LWS_WITH_ZLIB AND NOT LWS_WITH_BUNDLED_ZLIB)
        set(LIB_LIST "${LIB_LIST} ${ZLIB_LIBRARIES}")
    endif()
```

...maybe it can help.

**Comment by jzer0** [comment]
Dude, thanks so much, you are a rock star!  Fixed it right up, everything is being found now.  Closing issue, thanks again!
