### ISSUE TITLE
Q: Is is possible to unit testing websocket servers single-threaded?

### ISSUE THREAD

**Issue by falk-werner** [warmcat/libwebsockets#1848]
I've written a small websocket server and, for unit test purposes, a websocket client too.
During unit test, the client connects to the server and some messages are exchanged.

This works fine in multithreaded contexts, where both, server and client, use their own `lws_context` and run in different threads.
In order to simplify unit test code, I've tried to put server and client in the same lws_context:

    lws_protocols protocols[] = { server_protocol, client_protocol, empty_protocol };

Unfortunately, this does not work as expected. I observed that after `lws_client_connect_via_info()` the server protocol gets all callbacks intended for the client protocol, such as `LWS_CALLBACK_CLIENT_ESTABLISHED`. This makes sence, since I've specifiend the name of the servers protocol in the `lws_client_connect_info` structure, because I want to connect to server.

    struct lws_client_connect_info;
    memset(&info, ...);
    info.protocol = "server";
    ...
    lws_client_connect_via_info(&info)

Is it possible to to associate the connection to the client protocol too, so that the server can be tested without spawning a separate thread?

**Comment by lws-team** [comment]
Are you maybe looking for this?

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n119-125

**Comment by falk-werner** [comment]
Yes, exactly!
Sorry, I've overlooked this.
