### ISSUE TITLE
v3.2 Stable. lws_hdr_custom_length

### ISSUE THREAD

**Issue by matthewwen** [warmcat/libwebsockets#1850]
Hello, so I had a custom header when I was using http. So I used `lws_hdr_custom_length` and `lws_hdr_custom_copy` to get the content for my specific header. However, I recently switched over to https, and these functions do not work anymore. Any reason why?

**Comment by lws-team** [comment]
It's not going to be related to https, but related to http/2... the current custom headers stuff is a hack that only works on h1.  If you force h1, by disabling h2 support at cmake or set the client .alpn...

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n126

...to "http/1.1", it'll work again.

**Comment by matthewwen** [comment]
Okay got it. Thank You!
