### ISSUE TITLE
How to send & receive HTTP headers during websocket connection

### ISSUE THREAD

**Issue by ludekvodicka** [warmcat/libwebsockets#1851]
Hello,

I would like to send (and receive) some HTTP headers during websocket connection initialization.

Is there any example of how to do that? I checked all examples as same as checked all closed questions here but without success.

Can you please point me how to do that? Thanks

**Comment by lws-team** [comment]
Well... making the ws connection will always "send and receive headers"... if lws understands the header, it will always parse it without you having to do anything else.

You can add your own headers to the handshake request like this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-custom-headers/minimal-http-client-custom-headers.c#n38

If you really have to receive a nonstandard header, you can do it like this (but only for h1)

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-custom-headers/minimal-http-client-custom-headers.c#n53-76

for ws reply, you'd look for the headers at ESTABLISHED callback

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client/minimal-ws-client.c#n107

**Comment by ludekvodicka** [comment]
Thanks a lot for a quick reply.

Can you please point me also how to receive such header on the server-side?

We need to implement some kind of easy authorization for our client-server protocol and because of wer're using 3.1 stable branch so we can't use LWS_CALLBACK_VERIFY_BASIC_AUTHORIZATION.

We tried to update to the latest but there are probably some breaking changes and our client/server stopped working.

**Comment by lws-team** [comment]
You don't deal with 'receiving' the header literally, lws takes care of it.

For a ws server, you'd use LWS_CALLBACK_ESTABLISHED to look at the client headers, but if it involves auth, you can look at them earlier at LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION so you can deny the ws connection before it was established.

The main change after v3.1 is lws_sul timing inside lws

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

Nobody can diagnose 'stopped working'... you need to look at the logs.

**Comment by ludekvodicka** [comment]
Thanks. 

In case that I use `lws_add_http_header_by_name` on client-side, what is the correct method to receive such header on the server side? 

We're currently using `lws_hdr_total_length` and `lws_hdr_copy` to receive URI/ARGS but I didn't find any `lws_hdr_copy_by_name`.

Thanks

PS: I know that "stopped working" isn't the best description. But currently, we don't have any better description. We only quickly tried to update from 3.1 to 3.2 and when our unit tests stopped working we reverted it back to 3.1 for now.

**Comment by lws-team** [comment]
Generally lws has a list of headers it understands and discards everything else.  For auth, you should use the standard Authorization header with your own scheme and avoid inventing new headers.

**Comment by ludekvodicka** [comment]
Thanks a lot. Your last reply explains it.

Here is my current code for anyone else:

```
case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
   unsigned char** p = (unsigned char**)in, * end = (*p) + len;
   lws_add_http_header_by_token(wsi,WSI_TOKEN_HTTP_AUTHORIZATION,val,length, p, end);
```

and on the server side:

```
case LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION:
lws_hdr_total_length(wsi, WSI_TOKEN_HTTP_AUTHORIZATION)
lws_hdr_copy(wsi, pstrAuth, nLength + 1, WSI_TOKEN_HTTP_AUTHORIZATION);
```

**Comment by ganl** [comment]
nginx returns 400 directly without forwarding to upstream

**Comment by dsugisawa-mixi** [comment]
Actualy I was spending a few days until just now on nginx returning 400/bad-request as well, but I just recently solved that problem, so I'd like to share it  if you don't mind,


### nginx /etc/nginx/sites-available/xxxx

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}
server {
        listen 443 ssl default_server;
        index index.html index.htm;
        ssl on;
        server_name example.com;
        ssl_protocols       sslv3 tlsv1 tlsv1.1 tlsv1.2 tlsv1.3;
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

        location = /xxxxx {
                proxy_pass http://127.0.0.1:xxxx;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
}
```

```cc

#include "signaltest_def.hh"

int websockets_callback(
    struct lws *wsi,
    enum lws_callback_reasons reason,
    void *user,
    void *in,
    size_t len 
);


// entry
int main(
    int argc,
    char* argv[]
)
{
    struct lws_protocols protocols[] = { 
        {   
            "signaling", websockets_callback,
            16384, 16384, 0, NULL, 0,
        },  
        {   
            NULL, NULL,
            0, 0, 0, NULL, 0,
        }   
    };  
    const unsigned LGLVL = (LLL_ERR|LLL_WARN|LLL_USER|LLL_NOTICE|LLL_INFO|LLL_CLIENT);
    lws_set_log_level(1151, NULL);

    struct lws_context_creation_info info;
    memset(&info, 0, sizeof(info));
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.protocols = protocols;
    info.gid = -1; 
    info.uid = -1; 
    info.user = NULL;
    info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    info.client_ssl_ca_mem = NULL;
    info.client_ssl_ca_mem_len =0;
    info.client_ssl_key_mem	= NULL;
    info.client_ssl_key_mem_len = 0;
    auto context = lws_create_context(&info);

    struct lws_client_connect_info ccinfo = {0};
    ccinfo.context = context;

    ccinfo.address = argv[1];
    ccinfo.port = atoi(argv[2]);
    ccinfo.path = "/signaling";
    ccinfo.host = argv[1];
    ccinfo.origin = argv[1];
    ccinfo.protocol = "signaling";
    ccinfo.local_protocol_name = "signaling";
    ccinfo.alpn = "http/1.1";
    ccinfo.iface = argv[3];
    ccinfo.ssl_connection =
        LCCSCF_USE_SSL |
        LCCSCF_ALLOW_SELFSIGNED |
        LCCSCF_ALLOW_EXPIRED |
        LCCSCF_ALLOW_INSECURE |
        LCCSCF_H2_PRIOR_KNOWLEDGE |
        LCCSCF_ACCEPT_TLS_DOWNGRADE_REDIRECTS |
        LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK |LCCSCF_PIPELINE;

    auto websocket = lws_client_connect_via_info(&ccinfo);
    if (!websocket) {
        throw std::runtime_error("Failed to lws_client_connect_via_info");
    }   
    while(true) {
        lws_service(context, 500);
    }

    lws_context_destroy(context);
    return(0);
}

int websockets_callback(
    struct lws *wsi,
    enum lws_callback_reasons reason,
    void *user,
    void *in,
    size_t len
)
{
    auto inst = (void*)lws_context_user(lws_get_context(wsi));

    printf(
        ">>>> websokets_callback(%d)\n",
        reason
    );
    switch(reason) {
    case LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION:
        printf("LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION\n");
        return(0);
    case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:{
        const char* connection = "Upgrade";
        const char* upgrade = "websocket";
        const char* language = "ja,en-US;q=0.9,en;q=0.8";
        const char* encoding = "gzip, deflate, br";
        const char* ua = "xxxx";
        char** p = (char**)in, *end = (*p) + len;

        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_CONNECTION, (unsigned char*)connection, strlen(connection), (unsigned char**)p, (unsigned char*)end))
            return(-1);
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_UPGRADE, (unsigned char*)upgrade, strlen(upgrade), (unsigned char**)p, (unsigned char*)end))
            return(-1);
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_ACCEPT_ENCODING, (unsigned char*)encoding, strlen(encoding), (unsigned char**)p, (unsigned char*)end))
            return(-1);
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_ACCEPT_LANGUAGE, (unsigned char*)language, strlen(language), (unsigned char**)p, (unsigned char*)end))
            return(-1);
        if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_USER_AGENT, (unsigned char*)ua, strlen(ua), (unsigned char**)p, (unsigned char*)end))
            return(-1);
        // additional
        const char* headers[][2] = {
            {"Sec-Websocket-Extensions", "permessage-deflate; client_max_window_bits"},
        };
        for (auto h : headers) {
            if (lws_add_http_header_by_name(wsi, (unsigned char*)h[0], (unsigned char*)h[1], strlen(h[1]),  (unsigned char**)p, (unsigned char*)end))
                return(-1);
        }
        break;
    }
    case LWS_CALLBACK_CLIENT_ESTABLISHED:
        printf("LWS_CALLBACK_CLIENT_ESTABLISHED\n");
        break;
    case LWS_CALLBACK_CLIENT_RECEIVE:
        printf("LWS_CALLBACK_CLIENT_RECEIVE\n");
        break;
    case LWS_CALLBACK_CLIENT_WRITEABLE:
        printf("LWS_CALLBACK_CLIENT_WRITEABLE\n");
        break;
    case LWS_CALLBACK_CLOSED:
    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
        printf("CLOSE\n");
        break;

    }
    return(lws_callback_http_dummy(wsi, reason, user, in, len));
}

```

**Comment by lws-team** [comment]
Thanks for sharing it.

**Comment by davehorton** [comment]
I'm not sure this was covered above, but I need to read the http headers when my ws client receives a failure status code, i.e. something other than a 101 upgrade.  In this case I would like to get
- the http response code, and
- all headers in the http response

right now, I am simply doing this:
```
    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
      {
        AudioPipe* ap = findAndRemovePendingConnect(wsi);
        lwsl_err("AudioPipe::lws_service_thread LWS_CALLBACK_CLIENT_CONNECTION_ERROR: %s\n", in ? (char *)in : "(null)"); 
```
which logs
```
connection failed: HS: ws upgrade response not 101
```
How can I get the actual http status code as well as any headers in the response?

**Comment by lws-team** [comment]
If the ah is still attached, you might be able to get it from

```
unsigned int
lws_http_client_http_response(struct lws *wsi)
```

**Comment by davehorton** [comment]
Thanks!  That did work. As far as retrieving the response headers at the same time, is there an api I can call for that?
