### ISSUE TITLE
Request: please enable lws_set_wsi_user() for server connections

### ISSUE THREAD

**Issue by andreysm** [warmcat/libwebsockets#1852]
Currently, `lws_set_wsi_user()` checks for `wsi->user_space_externally_allocated`, which makes it usable only for **client** connections.

It would be useful to allow lws_set_wsi_user() for the case when `wsi->protocol->per_session_data_size == 0`, for 'server' connections.

Well, I'm aware that opaque_user_data can be used for this case, but the `user` pointer is just more convenient and a bit faster than calling lws_get_opaque_user_data each time in a callback.

**Additional reasoning:**

This feature whould be useful for C++ code where z-allocing user_data is not enough because constructor isn't called. C++ users would instead like setting user data manually via `lws_set_wsi_user(wsi, new UserData())` on LWS_CALLBACK_ESTABLISHED and delete it on LWS_CALLBACK_CLOSED.

I tried to workaround it by storing my data in:
```
struct my_user_data {
	MyCppUserData * p;
};
```
But this results in an additional unwanted malloc.
It also makes things not consistent with the client connection code, where MyCppUserData is available directly in `user` as set via lws_client_connect_info. So I can't easily use one protocol callback for client and server connections.

**Comment by lws-team** [comment]
I think I understand what you're saying... opaque_user_data will indeed do it OK but IIUI, it just means add a clause to the test and allow it if the protocol pss size was zero.  I pushed a patch on master to do that.
