### ISSUE TITLE
How to read lws_close_reason on client side?

### ISSUE THREAD

**Issue by ludekvodicka** [warmcat/libwebsockets#1853]
Can you please point me how to read close_reason on the client side when connection is rejected via LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION?

```
case LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION:
lws_close_reason(wsi, LWS_CLOSE_STATUS_PROTOCOL_ERR, (unsigned char*)strError.GetPCXSTR(), strError.GetLength());
reaturn -1;

```

in the client side, I will receive:

```
on_lws_callback_function(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
...
case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
```

but variable in is nullptr and len is zero.

Thanks

**Comment by lws-team** [comment]
Not 100% sure what you're asking... an lws ws client may -- **may** -- get a `LWS_CALLBACK_WS_PEER_INITIATED_CLOSE` callback if the server closes on it.  But it is far from guaranteed, eg, if the tls tunnel breaks nothing can be sent and you will just get a tcp hangup.

`CLIENT_CONNECTION_ERROR` is something that comes if the connection fails before it reached `ESTABLISHED` state, so, eg, DNS lookup fail or server down or whatever.  You won't get any ws-land error code if you never reached an established ws connection in the first place.

**Comment by ludekvodicka** [comment]
Sorry, maybe I didn't describe it correctly.

What I would like to achieve is to notify the client-side of the ws connection when authentication failed.

When a client wants to connect to the server (both implemented by libwebsockets) the client use LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER to set WSI_TOKEN_HTTP_AUTHORIZATION.

When sever receives such connection, there is LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION handler where WSI_TOKEN_HTTP_AUTHORIZATION is checked.

In case that credentials doesn't match, the server returns -1 to close the connection.

What I understand from the doc and other comments here I can use lws_close_reason() to tell the client the close reason.

But I don't know how to read such a close reason on the client-side. How to tell the user that his credentials are invalid. Because currently, I can distinguish between for example invalid server address and invalid credentials, because both ends on CLIENT_CONNECTION_ERROR .

Hope it's more clear now. Thank you

**Comment by lws-team** [comment]
Well, all ws connections start out as http.  If things go well, the two sides may come to an agreement to do a one-way "upgrade" to use ws framing, after the negotiation, on that connection.

If things didn't go well - auth failure at http level is "not going well" - then actually the two peers never agreed to do the upgrade.  The connection is logically still passing http protocol stuff.  It means the way to inform about the problem is return 403 Forbidden as http.  I think you can send this in your handler for `LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION` before returning nonzero, these kind of apis are convenient to send back a 403

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-custom-headers/minimal-http-server-custom-headers.c#n76-85

**Comment by ludekvodicka** [comment]
Thank you, I will check it. This sounds like what I need.

And if I can ask, I still don't understand what `lws_close_reason` does and why exists. I believed (based on examples and docs) that this function is the way how to return error code back to the client.  

Thank you

**Comment by lws-team** [comment]
It's the way that a **ws** peer that wants to hang up can schedule that when he starts the close process, if possible he'll first send a ws CLOSE frame to the peer to indicate to him why the close is happening.

But if you started to make a connection, using http, and you never actually succeeded to negotiate the upgrade to ws protocol on that connection, neither side may start speaking ws framing, ie, nobody can start saying a ws CLOSE frame... nobody is talking ws.  The negotiation failed and both sides are still using http framing.  So if they want to indicate the problem, they must do it using http semantics, ie, a 403.

**Comment by ludekvodicka** [comment]
Thank you very much. It's clear now.
