### ISSUE TITLE
typ in JOSE header

### ISSUE THREAD

**Issue by dzakarias-verimatrix** [warmcat/libwebsockets#1854]
```lws_jws_jose_cb()```, the callback in jose.c the JOSE parser uses, only accepts 'JWT' as the value of a 'typ' element:

```
case LJJHI_TYP: /* Optional: string: media type */
		if (strcmp(ctx->buf, "JWT"))
			return -1;
		break;
```

This shouldn't be so restrictive in my opinion, e.g. a JWE's JOSE header could contain any value for 'typ'.

**Comment by lws-team** [comment]
I pushed a patch on master to store any typ in the jose object, is that solving your problem?

**Comment by dzakarias-verimatrix** [comment]
Yes, thank you!
