### ISSUE TITLE
Replace calls to the deprecated ERR_remove_state with ERR_remove_thread_state.

### ISSUE THREAD

**Issue by svetlin-mladenov** [warmcat/libwebsockets#186]
According to [official openssl doc](https://www.openssl.org/docs/crypto/ERR_remove_state.html) `ERR_remove_state` is deprecated. It has also been removed from some openssl clones (like boringssl for example). Luckily `ERR_remove_state` is called only twice in libwebsocket (in lib/ssl.c) and there is a drop in replacement - calls to `ERR_remove_state(0);` should be replaced by `ERR_remove_thread_state(NULL);`.

It would be great for this can be fixed so libwebsockets can be linked against boringssl and other openssl clones.

**Comment by liuqun** [comment]
Since OpenSSL 1.1.0, `ERR_remove_thread_state()` is deprecated too:
- `#include <openssl/err.h>`
```
DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
```

**Comment by lws-team** [comment]
Yeah... but lws tries to work with older and newer OpenSSL like this:

```
// after 1.1.0 no need
#if (OPENSSL_VERSION_NUMBER <  0x10100000)
// <= 1.0.1f = old api, 1.0.1g+ = new api
#if (OPENSSL_VERSION_NUMBER <= 0x1000106f) || defined(USE_WOLFSSL)
	ERR_remove_state(0);
#else
#if OPENSSL_VERSION_NUMBER >= 0x1010005f && \
    !defined(LIBRESSL_VERSION_NUMBER) && \
    !defined(OPENSSL_IS_BORINGSSL)
	ERR_remove_thread_state();
#else
	ERR_remove_thread_state(NULL);
#endif
#endif
```

... so what's your OPENSSL_VERSION_NUMBER that is building this but coming up deprecated?

**Comment by liuqun** [comment]
Wow, thanks for the quick reply

> ... so what's your OPENSSL_VERSION_NUMBER that is building this but coming up deprecated?

I was just trying to figure out which API should I use to depress those gcc warnings in my demo project with openssl both on CentOS 7.6 and Ubuntu. Thanks very much! The sample solution code above should work for me.

**Comment by lws-team** [comment]
I just pasted the code out of master... it's been like that for a while though.  So just updating lws to v3.1-stable or master should sort it.
