### ISSUE TITLE
Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this project

### ISSUE THREAD

**Issue by gareth41** [warmcat/libwebsockets#1860]
I'm trying to build minimal-ws-server-echo and get this error

Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-88-generic x86_64)

`-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:59 (message):
  Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this
  project
Call Stack (most recent call first):
  CMakeLists.txt:69 (require_lws_config)
`

**Comment by lws-team** [comment]
So... build lws first with `-DLWS_WITHOUT_EXTENSIONS=0`?

Many of the examples cannot work with default lws cmake config, eg, api test for full text search, full text search is disabled by default.  If you build the examples from inside lws build with `-DLWS_WITH_MINIMAL_EXAMPLES=1` it looks at all the example cmake files and figures out which ones can build the way you are building lws automatically,

If you go into the example manually and build it, you need to make sure you built lws with the right pieces for that example manually too.
