### ISSUE TITLE
lws_write return -1

### ISSUE THREAD

**Issue by x081x** [warmcat/libwebsockets#1862]
Server sends 20+MB data to client. After sends several data, lws_write failed. Then the connection is disconnected.

    static struct lws_protocols g_wsProtocols[] =
    {
        /* first protocol must always be HTTP handler /
        {
            "typhoon-wss", / name /
            WebsockserverCallback, / callback /
            0, / per_session_data_size /
            5000 * 1024, / max frame size / rx buffer /
        },
        { NULL, NULL, 0, 0 } / terminator */
    };

    for (unsigned int i = 0; i < dataSize; i++)
    {
        size_t bufSize = vecData[i].length();
        unsigned char* pBuf = new unsigned char[bufSize + LWS_SEND_BUFFER_PRE_PADDING + LWS_SEND_BUFFER_POST_PADDING];
        memcpy(pBuf + LWS_SEND_BUFFER_PRE_PADDING, (unsigned char*)vecData[i].c_str(), bufSize);

        iRet = lws_write(pClient, pBuf + LWS_SEND_BUFFER_PRE_PADDING, bufSize, LWS_WRITE_BINARY);

        std::cout << "lws_write: ["
	        << "SendBytes: " << bufSize << ", "
                << "Return: " << iRet << "]\n";

        delete[] pBuf;
        pBuf = nullptr;
    }

The console print: 
lws_write: [SendBytes: 16396, Return: 16396]
lws_write: [SendBytes: 16396, Return: 2064]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 1924]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 1924]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: 2068]
lws_write: [SendBytes: 16396, Return: -1]
lws_write: [SendBytes: 16396, Return: -1]
.
.
.
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:1919] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:1949] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:1994] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:2024] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:2059] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:2084] ERR: lws_buflist_append_segment: corrupt list points to self
lws_write: [SendBytes: 16396, Return: -1]
[2020/03/16 11:57:53:2114] ERR: lws_buflist_append_segment: corrupt list points to self

**Comment by x081x** [comment]
The Protocols:

static struct lws_protocols g_wsProtocols[] = {
	/* first protocol must always be HTTP handler */
	{
		"typhoon-wss",							/* name */
		WebsockserverCallback,					/* callback */
		0,										/* per_session_data_size */
		5000 * 1024,			    /* max frame size / rx buffer */
	},
	{ NULL, NULL, 0, 0 }						/* terminator */
};

**Comment by lws-team** [comment]
> for (unsigned int i = 0; i < dataSize; i++)

You cannot do this, not with lws or just send() on a socket.

The kernel doesn't make any such promise it will buffer whatever you throw at it and quite quickly will reject to take any more on a socket. Your machine may have a lot of memory (many don't) but it will eventually run out of heap as the backlog and number of sockets increase, the code is already broken on a small device.

The basic deal is

 - you can only write from the writeable callback

 - you can only write one thing, and ask for another writeable callback if more to do

Use a pss like the minimal examples do to hold state about what you're sending and change your loop to count via the pss and the event loop.

**Comment by x081x** [comment]
Thanks for your advice. I will improve the code.
