### ISSUE TITLE
lws crash libwebsockets\lib\roles\h1\ops-h1.c in line 263

### ISSUE THREAD

**Issue by danflu** [warmcat/libwebsockets#1872]
Hi lws team,

I'm struggling with a crash inside lws when using lws v3.2.0 inside Janus WebRTC Gateway.

The crash happens in file libwebsockets\lib\roles\h1\ops-h1.c in line 263

```c++
default:
    lwsl_err("%s: Unhandled state %d\n", __func__, lwsi_state(wsi));
    assert(0);
    goto bail;
```
The backtrace is below. Please let me know if you need any further information about this issue, or if this is fixed in some other version. 

It is not easy to reproduce...

Thanks a lot for your help!
Daniel

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/janus/bin/janus'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1747f06700 (LWP 19003))]
(gdb) bt

#0  0x00007f175be27e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f175be298db in __GI_abort () at abort.c:100
#2  0x00007f175be1939a in __assert_fail_base (fmt=0x7f175bfa07d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f1748f65d5d "0", file=file@entry=0x7f1748f65d28 "/home/iptv/janus/libwebsockets/lib/roles/h1/ops-h1.c", line=line@entry=263, function=function@entry=0x7f1748f66018 <__PRETTY_FUNCTION__.30247> "lws_read_h1") at assert.c:92
#3  0x00007f175be19412 in __GI___assert_fail (assertion=0x7f1748f65d5d "0", file=0x7f1748f65d28 "/home/iptv/janus/libwebsockets/lib/roles/h1/ops-h1.c", line=263, function=0x7f1748f66018 <__PRETTY_FUNCTION__.30247> "lws_read_h1") at assert.c:101
#4  0x00007f1748f30a50 in lws_read_h1 (wsi=0x6170000e1c80, buf=0x623000015610 "\201�\001\"0nS\222KL9�^\033 �\nL>�C\035\062�UL\177�R\001\067�\022T(�@\017*�_\017\067�\nL4�\035[6�QWf�\006]6�\003\\0�\002\rk�\002\f6�ST\r�\021\025\017�S\003\067�\022T\017�S\002:�S\006\f�^\b<�\022B\017�T\017'�lLi�\022\025\017�lL0�l2q�l2\017�C\v7�SC2�\003\062\017�\022\023\017�\034\062q�U2q�lL\017�\034\062q�B\017\064�lLi�\034\062q�U\037\017�\nZe�lL'�lLi�\004Wg�\tX`�ML\177�"..., len=298) at /home/iptv/janus/libwebsockets/lib/roles/h1/ops-h1.c:263
#5  0x00007f1748f3395d in rops_handle_POLLIN_ws (pt=0x623000015280, wsi=0x6170000e1c80, pollfd=0x7f174870ac98) at /home/iptv/janus/libwebsockets/lib/roles/ws/ops-ws.c:1194
#6  0x00007f1748f2697d in lws_service_fd_tsi (context=0x623000015100, pollfd=0x7f174870ac98, tsi=0) at /home/iptv/janus/libwebsockets/lib/core-net/service.c:663
#7  0x00007f1748f53343 in _lws_plat_service_forced_tsi (context=0x623000015100, tsi=0) at /home/iptv/janus/libwebsockets/lib/plat/unix/unix-service.c:49
#8  0x00007f1748f5381c in _lws_plat_service_tsi (context=0x623000015100, timeout_ms=2000000000, tsi=0) at /home/iptv/janus/libwebsockets/lib/plat/unix/unix-service.c:207
#9  0x00007f1748f53876 in lws_plat_service (context=0x623000015100, timeout_ms=50) at /home/iptv/janus/libwebsockets/lib/plat/unix/unix-service.c:222
#10 0x00007f1748f26acd in lws_service (context=0x623000015100, timeout_ms=50) at /home/iptv/janus/libwebsockets/lib/core-net/service.c:727
#11 0x00007f174918d6b6 in janus_websockets_thread (data=0x623000015100) at transports/janus_websockets.c:987
#12 0x00007f175d670195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f175c1e16db in start_thread (arg=0x7f1747f06700) at pthread_create.c:463
#14 0x00007f175bf0a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by lws-team** [comment]
>  v3.2.0

It's not a good idea to use .0 releases, use v3.2-stable.  Unfortunately most people ignore what's going on in master and only start caring when there's a release, consequently the debugging that should have happened before the release gets shunted to the next few weeks after release.  So you always want vx.y-stable or some point release off that.

In fact it looks like what you have is somewhat patched, the assert is on line 260 in actual v3.2.0

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/h1/ops-h1.c?id=94931cad003faf9d316e698b557bbb6d245f1f91#n260

There are no patches on v3.2-stable in that file AFAICS.

Can you make it print `lwsi_state(wsi)` before the assert so we can see what state the wsi is in that makes it surprised?

**Comment by danflu** [comment]
Hi, thanks for your quick reply!

Hummmmm, maybe it is patched...

Sure I can see `lwsi_state(wsi)`  in the log... is it printed in a specific file or in syslog ?

I used the folllowing to build lws:

```
cd libwebsockets/ && mkdir build && cd build  
sudo cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/opt/janus/ -DCMAKE_C_FLAGS="-fpic" -DCMAKE_BUILD_TYPE=DEBUG ..
sudo make && sudo make install
```
Is there any specific switch to enable logging ?

Thanks a lot!
Daniel

**Comment by lws-team** [comment]
No I mean hack in a line above the assert like

lwsl_notice("%s:  the bad state 0x%x\n", __func__, lwsi_state(wsi));

lws will always produce logs, I don't know what Janus does to quench, redirect or control lws logging

**Comment by danflu** [comment]
Ok. I will do that and post here as soon as the crash occurs...

**Comment by danflu** [comment]
Hi @lws-team,

I can extract any information from the core dump file. Easier than wait for another crash...

Please let me know if this helps...
Thanks!

```
#4  0x00007f1748f30a50 in lws_read_h1 (wsi=0x6170000e1c80, 
    buf=0x623000015610 "\201�\001\"0nS\222KL9�^\033 �\nL>�C\035\062�UL\177�R\001\067�\022T(�@\017*�_\017\067�\nL4�\035[6�QWf�\006]6�\003\\0�\002\rk�\002\f6�ST\r�\021\025\017�S\003\067�\022T\017�S\002:�S\006\f�^\b<�\022B\017�T\017'�lLi�\022\025\017�lL0�l2q�l2\017�C\v7�SC2�\003\062\017�\022\023\017�\034\062q�U2q�lL\017�\034\062q�B\017\064�lLi�\034\062q�U\037\017�\nZe�lL'�lLi�\004Wg�\tX`�ML\177�"..., 
    len=298) at /home/iptv/janus/libwebsockets/lib/roles/h1/ops-h1.c:263
263			assert(0);
(gdb) p lsi_state(wsi)
Invalid character '�' in expression.
(gdb) p len
$1 = 298
```

**Comment by lws-team** [comment]
Thanks, it's 0x11e, LRS_FLUSHING_BEFORE_CLOSE... it is valid... it's very transient and uncommon so it makes sense you (or anyone else) doesn't see it or the problem often.

I pushed a fix on master, v4.0-stable and v3.2-stable, it should solve it.  Thanks for the debugging to lead the way.

**Comment by danflu** [comment]
Thanlks! Updated!

**Comment by chandruraj85** [comment]
Hi lws-team, 

I am facing a similar assert (hitting the default unhandled state) on v4.3 stable or main branch on the same function. On enabling the debug prints, I found the lwsi_state is 0x11a (282). Please refer the below prints.

rops_handle_POLLIN_h1: [wsisrv|14|adopted]: start of func, wsistate 0x2000011a
rops_handle_POLLIN_h1: [wsisrv|14|adopted]:b4 is flowcontrol, wsistate 0x2000011a
rops_handle_POLLIN_h1: [wsisrv|14|adopted]: lws_with_server, wsistate 0x2000011a
rops_handle_POLLIN_h1: [wsisrv|14|adopted]:b4 h1_server_socket_service, wsistate 0x2000011a
lws_read_h1: h1 path: wsi state 0x11a
lws_read_h1: Unhandled state 282
libws/src_code/lib/roles/h1/ops-h1.c:297: lws_read_h1: Assertion failed.

Thread 18 received signal SIGABRT, Aborted.
[Switching to LWP 796]
0x452339e8 in raise () from /lib/libc.so.6
(gdb) 
(gdb)                              
(gdb) bt
#0  0x452339e8 in raise () from /lib/libc.so.6
#1  0x452377e4 in abort () from /lib/libc.so.6
#2  0x4522ccc8 in ?? () from /lib/libc.so.6
#3  0x4522cd90 in __assert_fail () from /lib/libc.so.6
#4  0x007ec6b0 in lws_read_h1 ()
#5  0x007ecaf8 in lws_h1_server_socket_service ()
#6  0x007ecf78 in rops_handle_POLLIN_h1 ()
#7  0x007db110 in lws_service_fd_tsi ()
#8  0x00807190 in _lws_plat_service_forced_tsi ()
#9  0x008075b8 in _lws_plat_service_tsi ()
#10 0x0080763c in lws_plat_service ()
#11 0x007db2f0 in lws_service ()

Is 0x11a is a valid state? This is consistently seen when running the nessus scan (which is a tool used to scan the vulnerabilities in the code). 

Any help would be appreciated.

**Comment by lws-team** [comment]
Yes 0x11a is also valid,. it's LRS_DOING_TRANSACTION (the higher bits like 0x100 are flags about the state characteristics).  Again it's not a state you are normally getting input events on.

But if you look at the code around the assert:

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/h1/ops-h1.c#n299

there is no security implication since the purpose of the default handler is to hang up straight away if doesn't expect the event in that state, so it "fails safe".  The assert will only fire when built in debug mode, it's there to help me find and deal with all the normal states the event will come in.

The "fix" for OP was just to add an explicit handler for his state to avoid the assert... probably now the better fix is remove the assert, it will still log noisily and hang up by default. 

```
diff --git a/lib/roles/h1/ops-h1.c b/lib/roles/h1/ops-h1.c
index b21b69e4b7..769490fe7e 100644
--- a/lib/roles/h1/ops-h1.c
+++ b/lib/roles/h1/ops-h1.c
@@ -297,7 +297,6 @@ ws_mode:
 
        default:
                lwsl_err("%s: Unhandled state %d\n", __func__, lwsi_state(wsi));
-               assert(0);
                goto bail;
        }
 
```

**Comment by chandruraj85** [comment]
Thanks for the quick response @lws-team. I am not sure why this is seen only in v4.3 stable and not in v4.2 stable or before.

I handled this specific state to ignore as below as I don't want the error prints also reported. Let me run the scan again and check if there are few more unhandled states exist. Hope this is fine.

diff --git a/lib/roles/h1/ops-h1.c b/lib/roles/h1/ops-h1.c
index 4590a49..f645d05 100644
--- a/lib/roles/h1/ops-h1.c
+++ b/lib/roles/h1/ops-h1.c
@@ -283,6 +283,7 @@ ws_mode:
        case LRS_SSL_ACK_PENDING:
                break;
 
+       case LRS_DOING_TRANSACTION:
        case LRS_FLUSHING_BEFORE_CLOSE:
                break;

**Comment by lws-team** [comment]
It's different since it allows the transaction to continue.  If you know what Nessus responds with is actually reasonable and lws handles it by continuing, that's OK.  If not, you should add its own specific `case` to handle it and just `goto bail;` there, ie, do the same flow as `default:` but without the log and assert.

**Comment by ruyzeng** [comment]
> Thanks for the quick response @lws-team. I am not sure why this is seen only in v4.3 stable and not in v4.2 stable or before.
> 
> I handled this specific state to ignore as below as I don't want the error prints also reported. Let me run the scan again and check if there are few more unhandled states exist. Hope this is fine.
> 
> diff --git a/lib/roles/h1/ops-h1.c b/lib/roles/h1/ops-h1.c index 4590a49..f645d05 100644 --- a/lib/roles/h1/ops-h1.c +++ b/lib/roles/h1/ops-h1.c @@ -283,6 +283,7 @@ ws_mode: case LRS_SSL_ACK_PENDING: break;
> 
> * ```
>     case LRS_DOING_TRANSACTION:
>     case LRS_FLUSHING_BEFORE_CLOSE:
>             break;
>   ```

Hi, I am get the same problem in v4.3, need change to v4.2 or before?

**Comment by lws-team** [comment]
@ruyzeng you just need to apply the patch that's now on main, on v4.3

https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=71ba0d53d36fc9621a00d9edb0846f1964400c1c

**Comment by ruyzeng** [comment]
> @ruyzeng you just need to apply the patch that's now on main, on v4.3
> 
> https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=71ba0d53d36fc9621a00d9edb0846f1964400c1c

Thanks for your quick reply. Updated.
