### ISSUE TITLE
lws_getaddrinfo46 failed 7 on Android

### ISSUE THREAD

**Issue by lincoln-b** [warmcat/libwebsockets#1875]
I'm getting runtime errors on Android. I've attached the project as a zip file for you to reproduce. I have compiled and run the same code on my Mac and it works as expected, so I wonder if there is an Android specific problem somewhere.

In a nutshell, lws_client_connect_via_info is failing at runtime with this error:

```
N: lws_client_connect_3_connect: lws_getaddrinfo46 failed 7
```

Here's the surrounding function that calls lws_client_connect_via_info, basically copied from the minimal-ws-client-ping example, but without the retry logic:

```
static void connect_client(lws_sorted_usec_list_t *sul) {
    struct lws_client_connect_info i;

    memset(&i, 0, sizeof(i));

    i.context = CONTEXT;
    i.port = SERVER_PORT;
    i.address = SERVER_ADDRESS;
    i.path = SERVER_PATH;
    i.host = i.address;
    i.origin = i.address;

    lws_client_connect_via_info(&i);
}
```

When I change SERVER_ADDRESS to the IP address of the test server I'm connecting to, I get this error instead:

```
W: Unable to open socket
```

Here are the settings that I built libwebsockets.a with:
```
    cmake \
        -DCMAKE_INSTALL_PREFIX="$PREFIX" \
        -DLWS_WITH_SHARED=OFF \
        -DLWS_WITH_STATIC=ON \
        -DLWS_WITH_SSL=OFF \
        -DLWS_WITHOUT_DAEMONIZE=ON \
        -DLWS_WITHOUT_TESTAPPS=ON \
        -DLWS_WITH_HTTP2=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DANDROID_NDK="$NDK_ROOT" \
        -DANDROID_ABI="<various abis>" \
        -DCMAKE_TOOLCHAIN_FILE="$NDK_ROOT/build/cmake/android.toolchain.cmake" \
        ..
```

As mentioned, I built the same source file (linking a libwebsockets built with the same flags, minus the toolchain file and the ABI flag) on my Mac and it worked without a hitch.

If the attached Android Studio project is convenient for you, you can reproduce by replacing NDK_ROOT in the build script and running the project. I left some more repro instructions in the zip.

[Attachment (too big for Github, hosted on Google Drive instead)](https://drive.google.com/file/d/1wZt7s2B3ATrJTTKwKzJXL8-IjOEltrRI/view?usp=sharing)

**Comment by lws-team** [comment]
Android seems to care about the user it runs under, running as root is actually unprivileged IIRC.

If I were you I'd debug it a bit, around here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/client/client-handshake.c#n34

finf out what it's objecting to... it looks pretty unobjectionable... find out what err 7 means, etc will get quicker result than just dumping it over here.

**Comment by lincoln-b** [comment]
Thanks for pointing that out to me -- getaddrinfo was failing with EAI_NODATA because I did not have the INTERNET permission declared in my AndroidManifest.xml file.
