### ISSUE TITLE
Proper way of handling lws_service in a single-threaded low-frequency loop?

### ISSUE THREAD

**Issue by bigblackdot** [warmcat/libwebsockets#1878]
Hey guys!

1. Client & server are both linux-based and powered by libwebsockets-4.0.1;
2. Client is single threaded with main loop tied to video swap rate, 60Hz:

```
int client_side_16ms_loop() {
	//... lot of other stuff
	lws_service( context, 0 );
}

```
3. Server sending a bunch of stuff to client with 4096 packets, logging progress with code like that:

```
case LWS_CALLBACK_SERVER_WRITEABLE:
	n = lws_write( wsi, data, len, LWS_WRITE_BINARY );
	bool choked = lws_send_pipe_choked( wsi );
	lwsl_user( "bytes sent: %d (%.1fms) %s",
			n, time, choked ? "CHOKED" : "non-choked" );

```
output(server side) is like that:

```
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) CHOKED
bytes sent: 4096 (120.4ms) CHOKED
bytes sent: 4096 (7.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) CHOKED
bytes sent: 4096 (14.6ms) CHOKED
bytes sent: 4096 (137.5ms) non-choked
bytes sent: 4096 (0.3ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.0ms) CHOKED
bytes sent: 4096 (111.5ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.0ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) CHOKED
bytes sent: 4096 (24.4ms) non-choked
bytes sent: 4096 (0.2ms) CHOKED
bytes sent: 4096 (176.5ms) non-choked
```
client-side network usage:
![Network stats before](http://axkew.com/misc/network_before.png)

4. Now, network throughput increases greatly even by employing such a silly-looking stuff on client side:
```
int client_side_16ms_loop() {
	//... lot of other stuff
	for( int i = 0; i < 100; i ++ ) lws_service( context, 0 );
}
```
output(server side) is now like that:

```
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) non-choked
bytes sent: 4096 (0.1ms) CHOKED
bytes sent: 4096 (113.7ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.2ms) non-choked
bytes sent: 4096 (0.3ms) non-choked
```
client-side network usage:
![Network stats after](http://axkew.com/misc/network_after.png)

Is there any options to reach optimal throughput in a sane way, kind of looping on lws_service while there's events in queue that's ready to be processed?
Understanding that moving lws to a separate thread is an ultimate solution, however i'd like to keep it for last resort.

Thanks for all the great work you're doing!

**Comment by lws-team** [comment]
> Understanding that moving lws to a separate thread is an ultimate solution, however i'd like to keep it for last resort.

IIUI the main point is to "tie" this thread to your VSYNC, you basically put the thread in a timed sleep somewhere else outside of lws.  But lws either wants to be the master of the thread and do that, or be the slave and have an event library do it outside of lws.  As it is, IIUI you have two sleeping systems that don't know about each other in conflict and each can arbitrarily sleep and block the other from doing its job... that's the actual issue.

If you can get the VSYNC as a posix descriptor event, if necessary by opening a pipe and having another thread - maybe using nonposix events like libdrm sleep - put bytes in there while you have it open as a RAW FILE in lws, you can just use lws event wait and have it woken every 16ms cleanly while being always able to wake normally to service its own network events, instead of being dead to the world in someone else's wait.

**Comment by bigblackdot** [comment]
What actually confused me is that even for(0..100) lws_service(); loop executes quite fast. Logged a bit to be exact:
```
loop time: 68 us
loop time: 62 us
loop time: 61 us
loop time: 59 us
loop time: 60 us
loop time: 59 us
loop time: 235 us
loop time: 61 us
loop time: 62 us
loop time: 61 us
loop time: 61 us
loop time: 60 us
loop time: 60 us
loop time: 59 us
loop time: 595 us
loop time: 59 us
loop time: 58 us
loop time: 60 us
loop time: 60 us
loop time: 60 us
loop time: 60 us
loop time: 59 us
loop time: 213 us
loop time: 107 us
loop time: 79 us
```

about a half a ms in a worst case, so in this scenario lws generally only captures up to 1/32 of total timespan. yet it's enough to increase throughput by an order. which in turn made me think that there's queue of events that for some reason doesn't get processed in one lws_service call.
anyway, if it's not, than it's not. I got you point. Thanks a lot! (:

**Comment by lws-team** [comment]
In v3.2+ the poll() based default event loop is aligned to work like event libs... you normally stay in the lws_service() and don't come back, same as you don't come back from starting a libuv loop.  Stuff proceeds by callbacks magically coming from somewhere.

I dunno what you're measuring but if already something to do, lws won't spend any time asleep and exit the wait immediately.  If you force it to continuously 'black out' like you're doing, when it wakes and gets cpu again there's an increased chance a POLLOUT wait can take more etc... lws isn't the problem, the basic conflict of two guys on one thread who want to control its sleep is what's logically wrong with what you're doing.
