### ISSUE TITLE
tcp seq numbers for websocket packets

### ISSUE THREAD

**Issue by zalmoxis2019** [warmcat/libwebsockets#1881]
Hello,

  This is not an issue but more of a question. I'm connecting to same websocket server multiple times using your lib, in order to receive faster some price updates the server sends to all connected clients. These messages don't contain a sequence number so i can't identify easily what message was first (since i receive same message multiple times for each lws client connected). I was wondering if i can obtain somehow the tcp packet seq number for each msg received? Or anything from the ws frame header that could help me identify the msg uniquely?
  I need this (or any other unique identifier) so that i know if the received message is new or a replay from the other active connections.
thanks a lot.

**Comment by lws-team** [comment]
> in order to receive faster

Not sure why that's faster... certainly if everybody does it, it's going to be slower...

> obtain somehow the tcp packet seq number

There is nothing like that at ws level that isnt a property of the individual connection, like the ws random packet mask.  And eg, intermediaries can proxy, refragment fragment or use additional packets compared to others meaning sequence numbers at the peer might not relate to what the originating server sent.

Lws and ws operate at tcp, not packet level like udp datagrams.  Data from multiple tcp packets is commonly coalesced by the time lws reads it.

You can ask the server operator to add a timestamp or uuid in the ws payload.

**Comment by zalmoxis2019** [comment]
Thank you for the superfast response:

> Not sure why that's faster... certainly if everybody does it, it's going to be slower...

The server keeps all client connections in some structure that is probably iterated to send these messages to each of them. If you're at the start of the iteration or at the end after...1m other users, is not the same....So i decided to be everywhere haha.

**Comment by lws-team** [comment]
Yeah... but it leads to actually having like 50 users who are all spawning cloned connections to "outsmart" the other 49 so it's tragedied-of-the-commons and slow for everyone.

> How can i get the ws random packet mask or the msg frame headers?

There's no api to expose this because it's not useful.  The random frame mask is a per-connection thing, there is no relationship between the mask used on one connection and another.  If you want to hack lws to get it, you have the sources.
