### ISSUE TITLE
Example for WebSocket Upgrade

### ISSUE THREAD

**Issue by ih8pinks** [warmcat/libwebsockets#1882]
I have viewed the documentation and example code and did not find an instance of how you can upgrade an existing HTTP connection to a WS connection. I am using "raw" sockets.

**Comment by lws-team** [comment]
When you say, 'existing http connection', but it's using raw_skt role, what does it mean?

What has actually been transferred on the socket up to that point?

This is the client or server side?  Http/1.1 kept-alive?  H2?

**Comment by ih8pinks** [comment]
I have a win32 application that has an existing socket created using socket/connect. I am attempting to use LWS for client-sided websocket. The socket has been newly opened and no traffic has been sent yet. In my code, I adopt the socket by calling `lws_adopt_descriptor_vhost(vhost, LWS_ADOPT_SOCKET, sock, protocols[0].name, NULL)`. I have the following callback registered, based on the example code provided in the example:
```
static int
callback_raw_test(struct lws *wsi, enum lws_callback_reasons reason,
	void *user, void *in, size_t len)
{

	switch (reason) {

		/* callbacks related to raw socket descriptor */

	case LWS_CALLBACK_RAW_ADOPT:
		lwsl_user("LWS_CALLBACK_RAW_ADOPT\n");
		lws_callback_on_writable(wsi);
		break;

	case LWS_CALLBACK_RAW_CLOSE:
		lwsl_user("LWS_CALLBACK_RAW_CLOSE\n");
		break;

	case LWS_CALLBACK_RAW_RX:
		lwsl_user("LWS_CALLBACK_RAW_RX (%d)\n", (int)len);
		lwsl_hexdump_level(LLL_NOTICE, in, len);
		break;

	case LWS_CALLBACK_RAW_WRITEABLE:
		if (lws_write(wsi,
			(uint8_t *)"GET / HTTP/1.1\xd\xa\xd\xa", 18,
			LWS_WRITE_RAW) != 18) {
			lwsl_notice("%s: raw write failed\n", __func__);
			return 1;
		}
		break;

	default:
		break;
	}

	return 0;
}
```

However, based on this example request makes a request to / with an HTTP GET. My question here is how do I go about making a request to / but immediately requesting the socket be upgraded to a websocket? Hopefully my explanation was a bit more clear.

Thanks!

**Comment by lws-team** [comment]
The socket adoption stuff is aimed at server side as it is.

Lws wants to do the name resolution, create the socket, manage the connection and the states inside the connection to progress the ws upgrade; it'll "just work" on lws side if you instead look at the client connection apis... leaving .method as NULL indicates you want a ws connection.

If for some reason that's impossible in your case, well OK, but you'll need to add stuff in lws, and you're perhaps underestimating how related the connection and upgrade actions are... eg you must provide headers like Host: and Origin, and the ws upgrade happens at http protocol, so there is auth, a URL path, etc.  The least impedance mismatch will be to use the existing client connection apis so you can provided the necessary information about what the socket is connected to, and add allow passing in a socket fd and indicate that you want to short-circuit the state to, eg,

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/private-lib-roles.h#n122

The role binding in lws also matters, the wsi needs to be bound to h1 role to upgrade to ws, it may rebind to h2 before if that's what's happening but it has to start at h1.

**Comment by ih8pinks** [comment]
I do not quite understand the meaning of role binding in LWS. The h1 and h2 roles do not make any sense to me. I will post my code to see if that can clarify some things.

https://gist.github.com/ih8pinks/8a3fb99884b70e560ad806a8c37db986

I do not have a `wsi` unless it is within the callback.

**Comment by lws-team** [comment]
The main point is your current approach isn't going to get to where you seem to want to go.

The meaning of "adopting" the fd in lws is to create a wsi object and bind it to your external fd.  So you do have a wsi, whether you hold a pointer on it outside the callback or not.

In lws, wsi bind to one of a bunch of "roles", that can be turned on and off at build-time.  All of the knowledge about the protocol of the role lives in the role and integrates into what the wsi is doing via an "ops struct".  In other words, if you want your wsi to act according to ws rules, it will bind to the ws role and then "know how to act" for ws.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/ws/ops-ws.c#n2041

In this way most of the approaches, apis and objects in lws stay the same even if the connection is using, eg, h2, or mqtt... the wsi just bound to a different role implementation.

Trying to use raw-skt role which is what you have atm is at odds with "acting like a ws connection"... it needs to bind to ws role to gain all the knowledge about how to do that.

But today in lws

 - adopted sockets are in server mode

 - if external app handled the connect, there is a lot of missing information to act like a ws connection, eg, Host: Origin: url path etc.  Lws knows how to deal with this information via the client connect apis

Therefore if you want to go on with trying to adopt an external fd and run it as a ws connection, you need to hack a bit on lws to teach the client connect apis to be able to use a socket you pass in and understand it's already jump-started to a connected state and wants to send headers as its next action.

That way forward doesn't look anything like the code you have today.
