### ISSUE TITLE
HTTP POST file interrupted due connection drop

### ISSUE THREAD

**Issue by LordHadder** [warmcat/libwebsockets#1883]
Hello

Basing my dev on the [minimal POST file sample](https://github.com/warmcat/libwebsockets/blob/master/minimal-examples/http-server/minimal-http-server-form-post-file/minimal-http-server-form-post-file.c), I systematically get "large" files (about 5 Mo) being canceled due to HTTP connection drop after 255 Ko uploaded.

Do I make something wrong?

My sample shares an HTTP protocol with a basic chat protocol.

Thank you for your help.

**Comment by lws-team** [comment]
You need to look at the lws logs and find out if there is some reason there that the connection closes.  At a guess, it might be a timeout, and that's why it's roughly always 5MB.  You can extend the timeout as some data is passing or just set it to a larger amount at the start of the POST.  But consult the logs and see.

**Comment by LordHadder** [comment]
Ok, but I will need some more help:

"You can extend the timeout as some data is passing": How/where can I set this timeout? I will test to see if even the amount of data saved changes.

"consult the logs and see": Can you remind me how to activate internal lib logs?

**Comment by lws-team** [comment]
> Can you remind me how to activate internal lib logs?

All the examples show logs.  Just don't do whatever you did to stop them showing.

> How/where can I set this timeout?

`lws_set_timeout(wsi, PENDING_TIMEOUT_HTTP_CONTENT, 10);` 

will give the connection another 10s of life... if you do that when it's sending something, it'll always allow 10s to send the next piece.

**Comment by LordHadder** [comment]
Continuing my investigation, I observed that it happens in a scenario like that:

1) let's consider 2 protocols (HTTP first and a dummy chat one)
2) start the server
3) connect client on chat protocol
4) then oepn a borwser (Chore/FF) and then try to upload a "big" file

Result:
The file being uploaded is interrupted with the reason LWS_CALLBACK_HTTP_DROP_PROTOCOL.

When reading[ this post](https://github.com/warmcat/libwebsockets/issues/598), i think something is missing on my side to avoid this such a situation.

Any idea or sample to see how to manage it?

**Comment by lws-team** [comment]
DROP_PROTOCOL happens as part of any close.  It's a part of the close sequencing, not the reason.

You need to look in the logs.  If not enough detail, then build with cmake `-DCMAKE_BUILD_TYPE=DEBUG` and set the log level to something like 1151, you will get a lot of logs.
