### ISSUE TITLE
LWS_ROLE_WS error on ws-client-echo?

### ISSUE THREAD

**Issue by dominhnhut01** [warmcat/libwebsockets#1885]
I tried to build the ws-client echo by vcpkg as the instruction in this link [by](https://libwebsockets.org/lws-api-doc-master/html/md_READMEs_README_8build.html) typing `cmake . && make` in the cmd but I've got this error:
```
- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Failed
CMake Error at CMakeLists.txt:57 (message):
  This project requires lws must have been configured with LWS_ROLE_WS
Call Stack (most recent call first):
  CMakeLists.txt:67 (require_lws_config)
```
Then, I have searched for the file lws_config and figured out that it is in this path `C:\Users\Admin\vcpkg\buildtrees\libwebsockets\x64-windows-dbg\include` and this path `C:\Users\Admin\vcpkg\buildtrees\libwebsockets\x64-windows-rel\include` . I think that to fix the error, I have to modify the path in somewhere but don't know how to do it. I have read the #1702, #1718, and #1405 but still have not figured out the solution. Please help me!

**Comment by lws-team** [comment]
There are a few different angles to that... first, I have been using lws on Windows recently, I wrote up a "modern" cheatsheet for builds

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

Second, as part of that I added a bunch of patches to master that allow using `-DLWS_WITH_MINIMAL_EXAMPLES=1` at cmake during lws build, it will go on to build all the minimal examples that are compatible with the other cmake options in one step.  So you should make sure you're using current master.

Third when you meet these kind of build test failures from cmake, it is trying to build a little throwaway test applet silently to confirm if the thing it is interested in is there or not.  If the test applet didn't build, it figures it's not there.  But there are many reasons it might not build, for example, didn't tell it where the headers are or where the .dll is or whatever.  You have to go look at the end of `./build/CMakeFiles/CMakeError.log` to see what actually happened when it tried to build the applet.

Windows doesn't seem to have as mature a setup for installing and finding headers and libs as linux... what I'd do is make sure I have master and try the `-DLWS_WITH_MINIMAL_EXAMPLES=1` route.  If that works, then you can `cd` to the example dir if it needs to run from there, and run it as, eg, `\Users\fred\libwebsockets\build\Debug\x64\lws-minimal-whatever.exe` from its dir in `./minimal-examples/ws-server/whatever` where all its assets like html files etc it needs are.
