### ISSUE TITLE
Compiling api-tests/api-test-async-dns/main.c

### ISSUE THREAD

**Issue by gvanem** [warmcat/libwebsockets#1886]
I'm just scraping the surface of this library. So in order to get acquainted, I' building some 
*minimal-examples*. But hit this error in 1st try:
```c
api-tests/api-test-async-dns/main.c(15,42): error: redefinition of 'exp' as different kind of symbol
static int interrupted, dtest, ok, fail, exp = 26;
                                         ^
```

Since `<math.h>` was included via `<uv.h>`.  I'm on Windows using MSVC-2019.
An easy fix is simply replace `exp`-> `Exp`.

*BTW*. This example requires `LWS_WITH_SYS_ASYNC_DNS`, but now-where in this 
 directory is that mentioned.  It's confusing as hell to figure out things like this.

**Comment by lws-team** [comment]
> Since <math.h> was included via <uv.h>

Well, OK... I did test build that but I am not using libuv, and there's no error coming.  But it's not a sound choice of symbol name clearly... I changed it to `_exp` and pushed a patch on master and v4.0-stable.

> BTW. This example requires LWS_WITH_SYS_ASYNC_DNS, but now-where in this
> directory is that mentioned. It's confusing as hell to figure out things like this.

Not so... look at CMakeLists.txt :68 in that dir.

If you use cmake and don't enable the necessary pieces -- which are explicitly tested for and documented in the CMakeLists.txt -- you'll get an informative error.

If you use `-DLWS_WITH_MINIMAL_EXAMPLES=1` lws will also build all minimal examples that can be built with your lws cmake options and skip those that can't.

If you ignore the provided build stuff, yes, you need to know what you're doing then.

**Comment by gvanem** [comment]
The same `exp` issue with other .c-files too. Check it or why isn't AppVeyor up for it?

**Comment by lws-team** [comment]
Feel free to send a patch...
