### ISSUE TITLE
build x86 so has TEXTREL

### ISSUE THREAD

**Issue by lewis-v** [warmcat/libwebsockets#1887]
version 3.2
I build 32-bit x86 so for Android,but the so has TEXTREL, it cannot debug in adnroid6.0
how can I remove TEXTREL?

check cmd:
`
readelf -a libwebsockets.so.15 | grep TEXTREL
`
print
`
 0x00000016 (TEXTREL)                    0x0

 0x0000001e (FLAGS)                      TEXTREL BIND_NOW
`

check cmd:
`
file libwebsockets.so.15
`
print
`
libwebsockets.so.15: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, with debug_info, not stripped
`

**Comment by lws-team** [comment]
If you build lws using cmake you get `-fPIC`.

If you roll your own build outside of the official stuff, you have to add your own flags.

**Comment by lewis-v** [comment]
I use cmake and CMAKE_C_FLAGS is 
`
CMAKE_C_FLAGS = -Wall -Wsign-compare -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers  -fpic  -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing  -Wno-deprecated-declarations -pthread
`
it had "-fpic",but libwebsockets.so.15 also have TEXTREL

**Comment by lws-team** [comment]
> it had "-fpic",but libwebsockets.so.15 also have TEXTREL

I think you're getting confused with lws and your build of lws on your toolchain with your build options.

If I build master lws on x86_64 (it shouldn't be any different on v3.2) on Fedora 32, there are a lot of .text sections but no .textrel sections AFAICT

```
$ objdump -x /usr/local/lib/libwebsockets.so.16 | grep text | wc -l
812
$ objdump -x /usr/local/lib/libwebsockets.so.16 | grep textrel | wc -l
0
```

If lws does something undesirable that's usually my problem... if your build on your host using your toolchain with your build options and your build script does something undesirable, what do you think I should do about that?  AFAIK -fPIC == no .textrel... I would check if your CFLAGS are actually going on the compiler commandline (`make VERBOSE=1 V=1` should print the compiler commandline).
