### ISSUE TITLE
Sorry- I write already to mailing list but need help ASAP

### ISSUE THREAD

**Issue by pezalot** [warmcat/libwebsockets#1893]
Hello libwebsocket-team,

Now I try to explain my issue.

In most situations lws_write works well, but in case I dont want to. In some test case when I have already websocket established I enter in my firewall- iptables this line:

sudo iptables -t filter -A INPUT -p tcp -s xxx.xxx.xxx.xxx -j REJECT --reject-with icmp-host-unreachable

where xxx.xxx.xxx.xxx is wss server

This iptables rule mean to Reject every tcp packet from source xxx.xxx.xxx.xxx, and yes its work.

But if my App send message to lowest layer- I mean some routines which are responsible and use lws_write, then message is pushed into transmit buffer and waiting for send. But we know that websocket is bi-directional and this rule actually prevent receiving msg from src. My OS is Ubuntu 18.04 libwebsocket version is 4.0 (final with ssl and pthreads and etc.). Now I wait for 60 seconds or some configurable parameter on my system to decide that there is no communication between my system and src. Arise 2 common issues:

1.Libwebsocket drop/destroy the connection and I must recreate again. Well done, but because of my situations with Authentication tokens include in json messages which are already send/buffered(into transmit buffer) durring this period of 60 seconds their ttl is expired, when connection come alive I must grab them, rewrite new token and send them via new wss. I need the content of this transmit buffer? How can I get it? Some function or ...?

2. If in some reason during this 60 sec same connection come alive in a wss context without needs of creation of new one, but I have new Authentication token, I need again to grab those messages exists already in transmit buffer and rewrite them

In this two cases I need oldest content into transmit buffer, to rewrite changes comes in, when connection is frozen.

Please help!!!

**Comment by lws-team** [comment]
I'll answer this on the ml.
