### ISSUE TITLE
Sending a message to a specific client

### ISSUE THREAD

**Issue by big50000** [warmcat/libwebsockets#1894]
Sorry for accidentally submitting an issue, I'm just trying to find issues already submitted to find my answer, but it came like this, and I can't delete my issue.
First of all, I'm really new to C/C++ programming and I'm not any familiar with this library.
I'm currently finding how to identify a client to send a message specifically. I've tried many of methods and they are not work.

**Comment by lws-team** [comment]
> identify a client to send a message specifically.

What does 'identity' mean here... ip address?

**Comment by big50000** [comment]
Yes, something like that.

I also tried to compare IP address to client, but it also does not work. Maybe I did something wrong with my code, and it also shoots up unreasonably high CPU load.

**Comment by lws-team** [comment]
'are not work', you did something and get a vague 'high cpu usage'... nobody can guess what's up from that.

You can get the peer IP cheaply using this

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-network-helper.h#n69-80

**Comment by big50000** [comment]
I tried lws_get_peer_simple(). Now it does not chew up my CPU load any more, and seems like it does work. But in the same host it does sent a random number (in between connections) instead. For other peers it works perfectly.

Any suggestions for more accurate results?

**Comment by lws-team** [comment]
"more accurate results"... I don't think lws is making up random numbers, it's calling the related posix api on the socket and telling ypu what the os told it.

You're taking care about if it's AF_INET or ipv6? checking the return code?  The possibilities for breaking stuff are endless.

**Comment by big50000** [comment]
Since my English skill is really bad, maybe I explain something wrong. Let me explain it again.

I want to find something like "socket id", similar to this: https://github.com/websockets/ws/issues/367, but I don't know how to do it on LWS. Only method I got it to work (but inaccurate) is to get the client's IP address.

Sorry if I made you confused.

**Comment by arthur-zou** [comment]
> I want to find something like "socket id"
I think what SysError99 want is that how to get an instance in an established connection.
Just like that int **peer_fd** = accept(listen_socket, count); in tcp socket programming.
The **peer_fd** is an identity to find a specific connection among all multiple connections at service endpoint.

I care about that, too.
Could you please give a help? @lws-team

**Comment by lws-team** [comment]
I'm not sure that was actually what OP wanted, but there is an api for that

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-writeable.h#n193-201

`.sockfd` in the returned type is the fd associated with the wsi.
