### ISSUE TITLE
http/2 post keep-alive

### ISSUE THREAD

**Issue by zalmoxis2019** [warmcat/libwebsockets#1897]
Hello, 

   I want to do a client http/2 post request that i indend to keep alive for a long time to send some data multiple times through it without close/reopen. I used www.ptsv2.com to see how my request looks and it seems the http header Connection: Keep-Alive is never added in the header while the other headers i send are there. On top of that my connection seems to close by itself at the end even though i never return -1. Why is that? Am i doing this right?

I used this at the context creation but not sure if that's applied to http requests?
`info.ka_time = 60;
 info.ka_probes = 5;
 info.ka_interval = 10;`

This is my callback, creating headers and then the body:

`

        case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
        {
            unsigned char **p = (unsigned char **)in, *end = (*p) + len;

            if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_LENGTH, (unsigned char *)mco->content_length.c_str(), mco->content_length.size(), p, end))
            {
                return -1;
            }
            if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_TYPE, (unsigned char *)mco->content_type.c_str(), mco->content_type.size(), p, end))
            {
                return -1;
            }
            if (lws_add_http_header_by_token(wsi, WSI_TOKEN_CONNECTION, (unsigned char *)"keep-alive", 10, p, end))
            {
                return -1;
            }
            if (lws_add_http_header_by_name(wsi, (unsigned char *)"api-expires:", (unsigned char *)mco->api_expires.c_str(), mco->api_expires.size(), p, end))
            {
                return -1;
            }
            if (lws_add_http_header_by_name(wsi, (unsigned char *)"api-signature:", (unsigned char *)mco->api_signature.c_str(), mco->api_signature.size(), p, end))
            {
                return -1;
            }
            if (lws_add_http_header_by_name(wsi, (unsigned char *)"api-key:", (unsigned char *)mco->api_key.c_str(), mco->api_key.size(), p, end))
            {
                return -1;
            }

            lws_client_http_body_pending(wsi, 1);
            lws_callback_on_writable(wsi);
        }
        break;

        case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
        {
            if (lws_http_is_redirected_to_get(wsi))
            {
                break;
            }

            strcpy(buf + LWS_PRE, mco->data.c_str());
            n = lws_write(wsi, (unsigned char *)&buf[LWS_PRE], strlen(&buf[LWS_PRE]), LWS_WRITE_HTTP);

            if (n < 0)
            {
                return -1;
            }
            lws_client_http_body_pending(wsi, 0);`

I intend to call lws_callback_on_writable(wsi) whenever i want to send something again but i'm not sure that this is how it should be done? 

thank you very much for help and this library

**Comment by lws-team** [comment]
H2 separates out the idea of the connection lifetime from the lifecycle of an unlimited amount of "streams" that share the same connection.

Each h2 "stream" corresponds to an old h1 "transaction".

h1 "keep-alive" is a signal that you want to keep the underlying connection open and idle after a transaction completes... with h2 the lifecycle of the underlying connection is detached from that of any single stream / transaction already.  So there is no "keep-alive".  However, when the last stream closes, by default there's a few seconds where the connection will stay up in case any other streams are coming.

h2 streams live for exactly one transaction and are permanently closed at the end of it.  But, you may ask for another client connection / transaction and if the old connection is still up, it will be shared / reused transparently.

There's an api that can put the stream into a "long poll" / read-only / half closed state, where it will stay open listening for incoming data from the server "permanently" if the server supports that.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n795-811

**Comment by zalmoxis2019** [comment]
It seems this lws_h2_client_stream_long_poll_rxonly will keep the stream open for incoming data only. What i need is the ability to send my post requests without reopening the connection for each of them.
   I basically need to send my data directly through the open socket while the socket is pooled for response when they are available. (same behaviour like the websocket but without the ws upgrade stuff).

   I tried the same setup with h1 too but the http keep-alive header is not there when i inspect the dump. Why is that?

The rest api where i connect my client supports HTTP Keep-Alive and cache SSL sessions.

thank you for answers,
regards

**Comment by lws-team** [comment]
> send my post requests without reopening the connection 

This is transparent in lws, you just make your client requests and lws will optimize using an existing connection if it's still up.  But it will only stay up for a few seconds after the last stream in it completes.

With http/1.1, keep-alive is the default.  Specifying it is only necessary on http/1.0.

H2 is quite different than h1 even though stream pass http.

**Comment by zalmoxis2019** [comment]
So can you confirm that the fastest i can reschedule a new post is by doing this?
lws_sul_schedule(shared.ctx, 0, &conn->sul, WSS_Broker::connect_client, 1);
or calling this from same thread: lws_client_connect_via_info(&conn->client_info);  ?

I was hoping i could just do some lws_write(wsi...) and send new data again.

2)  Do i have any control over the connection lifetime with this lws_context_creation_info.ka_time = some_big_number? To keep the connection open forever, waiting for the new request to reuse it?

the beer is on me if you ever come to Romania :)

**Comment by lws-team** [comment]
Starting the client connection directly should be ok, but you have to do the transaction completed processing.  Scheduling it will get it next time around the event loop so it's not going to hurt.

tcp keepalive and h1 keepalive are completely different and unrelated things.

I can't even leave my house atm :-)

**Comment by zalmoxis2019** [comment]
thank you
