### ISSUE TITLE
Direct struct access breaks compile against new OpenSSL (ssl_ctx_st)

### ISSUE THREAD

**Issue by LordOfDragons** [warmcat/libwebsockets#1899]
/usr/bin/cc  -I/project/extern/libwebsockets/include -I/project/extern/libwebsockets/plugins -I/project/extern/libwebsockets/lib/core -I/project/extern/libwebsockets/lib/core-net -I/project/extern/libwebsockets/lib/event-libs -I/project/extern/libwebsockets/include/abstract -I/project/extern/libwebsockets/lib/tls -I/project/extern/libwebsockets/lib/roles -I/project/extern/libwebsockets/lib/event-libs/libuv -I/project/extern/libwebsockets/lib/event-libs/poll -I/project/extern/libwebsockets/lib/event-libs/libevent -I/project/extern/libwebsockets/lib/event-libs/glib -I/project/extern/libwebsockets/lib/event-libs/libev -I/project/extern/libwebsockets/lib/jose/jwe -I/project/extern/libwebsockets/lib/jose/jws -I/project/extern/libwebsockets/lib/jose -I/project/extern/libwebsockets/lib/misc -I/project/extern/libwebsockets/lib/roles/http -I/project/extern/libwebsockets/lib/roles/http/compression -I/project/extern/libwebsockets/lib/roles/h1 -I/project/extern/libwebsockets/lib/roles/h2 -I/project/extern/libwebsockets/lib/roles/ws -I/project/extern/libwebsockets/lib/roles/cgi -I/project/extern/libwebsockets/lib/roles/dbus -I/project/extern/libwebsockets/lib/roles/raw-proxy -I/project/extern/libwebsockets/lib/abstract -I/project/extern/libwebsockets/lib/system/async-dns -I/project/extern/libwebsockets/lib/roles/mqtt -I/project/extern/libwebsockets/lib/plat/unix -I/project/extern/build/libwebsockets/unix -I/project/extern/libwebsockets/lib -I/project/extern/openssl/linux/64bit/static/include  -Wall -Wsign-compare -Wstrict-aliasing -Wuninitialized -Werror -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers   -O3 -DNDEBUG -fPIC   -o CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.o   -c /project/extern/libwebsockets/lib/tls/openssl/openssl-server.c
/project/extern/libwebsockets/lib/tls/openssl/openssl-server.c: In function 'lws_tls_server_certs_load':
/project/extern/libwebsockets/lib/tls/openssl/openssl-server.c:421:38: error: dereferencing pointer to incomplete type 'lws_tls_ctx' {aka 'struct ssl_ctx_st'}
  421 |  x = sk_X509_value(vhost->tls.ssl_ctx->extra_certs, 0);
      |                                      ^~
make[2]: *** [CMakeFiles/websockets.dir/build.make:700: CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.o] Error 1
make[2]: Leaving directory '/project/extern/build/libwebsockets/unix'
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/websockets.dir/all] Error 2
make[1]: Leaving directory '/project/extern/build/libwebsockets/unix'
make: *** [Makefile:152: all] Error 2

Using OpenSSL "OpenSSL_1_1_1-stable" branch.
Using libwebsockets "v4.0-stable" branch.
libwebsockets build command:
cmake -DLWS_WITHOUT_EXTENSIONS=ON -DLWS_WITHOUT_TESTAPPS=ON -DLWS_WITHOUT_TEST_CLIENT=ON -DLWS_WITHOUT_TEST_ECHO=ON -DLWS_WITHOUT_TEST_FRAGGLE=ON -DLWS_WITHOUT_TEST_PING=ON -DLWS_WITHOUT_TEST_SERVER=ON -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON -DLWS_WITH_NO_LOGS=ON -DLWS_WITH_RANGES=OFF -DLWS_WITH_SHARED=OFF -DLWS_WITH_ZIP_FOPS=OFF -DLWS_WITH_ZLIB=OFF -DLWS_STATIC_PIC=ON -DLWS_WITH_SSL=ON -DLWS_OPENSSL_LIBRARIES=\"/project/extern/openssl/linux/64bit/static/library/libcrypto.a;/project/extern/openssl/linux/64bit/static/library/libssl.a\" -DLWS_OPENSSL_INCLUDE_DIRS=\"/project/extern/openssl/linux/64bit/static/include\" -DCMAKE_BUILD_TYPE=Release \"/project/extern/libwebsockets\"

**Comment by lws-team** [comment]
Nope... have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

then look at why cmake detection of LWS_HAVE_SSL_EXTRA_CHAIN_CERTS is wrong on your platform.

**Comment by LordOfDragons** [comment]
The mystery solved itself. Found the problem while going through the huge log file. libwebsockets fails the detection part because the build system happened to set up LWS_OPENSSL_LIBRARIES with the static filenames in order "libcrypto.a" then "libssl.a". libwebsockets does not seem to like this ordering. Switching to "libssl.a" then "libcrypto.a" fixed the build. I didn't get it that I need to respect order in this config option.

**Comment by lws-team** [comment]
That's not an lws thing but a linker thing.  The linker decides what to use from the archive in the order it appears in the linker commandline... if you give it libcrypto first, it may not have met anything that wants to import apis from that yet.  Then you give it libssl, which wants loads of apis from libcrypto, but its chance to bring them in has passed.  In some cases, depending on global linker ordering, you must give library imports a second or even more times in order to satisfy it.

Lws isn't involved in any of that.

**Comment by LordOfDragons** [comment]
There is still an issue though. The unix build works but the windows build does not. I've got the same problem that the build system does not detect the symbols because compilation of the test code fails. With windows though the error is different. "crypt32.dll" needs to be included in the linkage of the test code but it seems not. Can I use some compile option to manually add this library (or adding "-lcrypt32" as compile flag)?

**Comment by lws-team** [comment]
> the windows build does not

**Your** windows build does not work maybe.  But building lws with openssl and windows demonstrably can work just fine including the cmake api detections for openssl

https://libwebsockets.org/sai/index.html?task=32bf7c4037daaef1685dc311b333afdbf20e7162eb8d8f3731dd704bb4517d43

Integrating openssl as a package seems to be a big mess on windows... I built my own openssl in the end as described here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

then cmake find module could autofind the pieces.

**Comment by LordOfDragons** [comment]
I'm using mingw cross-compiler on Linux, in case this helps.

**Comment by lws-team** [comment]
There are some notes in lws READMEs from previous people using mingw but I don't have the time to throw at multiple different toolchains on windows at the moment.  What I wrote up works on VS toolchain which is what I am using for CI.  I think for windows that's the canonical one.

If you want to use mingw that's great but I haven't used it and you'll have to debug what's needed yourself.

From what you wrote (and did not write) are you giving both openssl lib paths on the cmake commandline, separated by a comma?  That's how it wants to be fed IIRC, like ".../path/to/libssl.lib;...path/to/libcrypto.lib"

**Comment by LordOfDragons** [comment]
Yes, that's correct. Basically all I'm missing is having a way to configure libwebsockets to use "-lcrypt32" as link flag in addition to all the link flags it is using. If I can specify this I think I get farther.

**Comment by lws-team** [comment]
No we are talking across each other... ` -DLWS_OPENSSL_LIBRARIES=` **IS** the way you specify what you want linking for openssl support, and you feed it "x.lib;y.lib" for windows.  You have not pasted what you are actually feeding cmake so I have to guess that's what you are missing.

**Comment by LordOfDragons** [comment]
Sorry about that. The command line is this:

cmake -DLWS_WITHOUT_EXTENSIONS=ON -DLWS_WITHOUT_TESTAPPS=ON -DLWS_WITHOUT_TEST_CLIENT=ON -DLWS_WITHOUT_TEST_ECHO=ON -DLWS_WITHOUT_TEST_FRAGGLE=ON -DLWS_WITHOUT_TEST_PING=ON -DLWS_WITHOUT_TEST_SERVER=ON -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON -DLWS_WITH_NO_LOGS=ON -DLWS_WITH_RANGES=OFF -DLWS_WITH_SHARED=OFF -DLWS_WITH_ZIP_FOPS=OFF -DLWS_WITH_ZLIB=OFF -DLWS_STATIC_PIC=ON -DLWS_WITH_SSL=ON -DLWS_OPENSSL_LIBRARIES="/project/extern/openssl/windows/32bit/static/library/libssl.a;/project/extern/openssl/windows/32bit/static/library/libcrypto.a" -DLWS_OPENSSL_INCLUDE_DIRS="/project/extern/openssl/windows/32bit/static/include" -DCMAKE_TOOLCHAIN_FILE="/project/extern/cross-libwebsockets-mingw32.cmake" -DCMAKE_BUILD_TYPE=Release "/project/extern/libwebsockets" 

And the toolchain file is this:
set(CROSS_PATH /usr/bin)
set(CMAKE_SYSTEM_NAME Windows)
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_C_COMPILER "${CROSS_PATH}/i686-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_PATH}/i686-w64-mingw32-g++")
set(CMAKE_RC_COMPILER "${CROSS_PATH}/i686-w64-mingw32-windres")
set(CMAKE_C_FLAGS "-Wno-error")
set(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

With the CROSS_PATH set during configuration to point at the right directory that is.

**Comment by lws-team** [comment]
... and so what's telling us about the problem?

You can usually use `make VERBOSE=1` to see the final, actual commandline for things.

**Comment by LordOfDragons** [comment]
I could do this but the problem happened in detection code of the build system which is not affected by this. While googling around I found somebody claiming crypt32.dll can not be used in static builds only shared builds. Is there a way I can disable the use of crypt32.dll? Or is this a hopeless case.

**Comment by lws-team** [comment]
I doubt it's hopeless... I just don't have time to reproduce this toolchain and look at it.

The cmake tests should follow whatever openssl pieces are in use.  Normally with windows, it seems you give it a .lib file not the dll directly.

It's also possible to set the detection symbols in your toolchain file, eg, for mbedtls case

https://libwebsockets.org/git/libwebsockets/tree/contrib/cross-linkit.cmake#n41-55

**Comment by stephenchenKL** [comment]
I set CMAKE_FIND_ROOT_PATH, it does not complain the order of the "libcrypto.a" and "libssl.a".

cmake .. -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -DCMAKE_INSTALL_PREFIX=/opt/libwebsockets.v3.1_aarch64 -DCMAKE_FIND_ROOT_PATH=/opt/openssl-1.1.1k_aarch64 -DOPENSSL_INCLUDE_DIR=/opt/openssl-1.1.1k_aarch64/include
