### ISSUE TITLE
http request question

### ISSUE THREAD

**Issue by TryAgain2019** [warmcat/libwebsockets#1901]
Hi, 
   After i send a h1 request, 5seconds later or so LWS_CALLBACK_CLIENT_HTTP_DROP_PROTOCOL and LWS_CALLBACK_CLOSED_CLIENT_HTTP seem to appear closing the 'open socket' in my face. I understand this is normal behaviour but i'm not normal :)

1) I want to resend multiple other requests before this happens. Can I? Can I send AGAIN other headers + body by just calling lws_callback_on_writable to trigger the write callback again?
2) As a matter of fact, I don't want the drop + close to happen at all, only when i close my program.
I want that socket open and always available for me to write & read from it whenever i want? Is that possible?

**Comment by lws-team** [comment]
Look at this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi

h1 is built on "transactions", as a hack you can use keepalive / pipelining but the server typically won't play ball with a permanently open h1 connection that is idle.

You should look at using h2, it's easier to open a stream and make it immortal if the server allows it.  Server permitting that gives you a read-only stream keeping the connection open and you can join other transaction-orientated streams on the same connection how you like by just opening new connections to the same endpoint, lws will take care of noticing and reusing the existing connection.

**Comment by TryAgain2019** [comment]
I saw that example and i use keepalive/pipelining based on it but it doesn't show how i can rewrite and resend a new request once the context is created and first message sent... After first msg is sent it seems even if i trigger the write callback and try to rewrite again a new message. It won't work.
  Regarding the "h1 playing the ball" i was trying to send some sort of "heartbit" useless message the server understands, just to keep the connection alive. Would that do it?

 I also know about the h2 read-only streams but it's not what i need. I have to always write stuff (post,put,delete) messages, and send to the server, from my client (very rare a get). The server accepts only http1/2 requests unfortunately, but i would like to use them as you normally would use a normal raw socket, if possible. Once the connection is opened, write to that sock fd forever...

thanks

**Comment by lws-team** [comment]
It does show it... you simply open another client "connection".

Lws will deal with optimizing how to bind that to anything that already exists.  The connection does not need to know or be handled differently if it happens to be the first or is riding on a different one -- or is being implemented on h2.  Just create another one like the example does.

H2 RO "immortal" stream is just there to keep the connection with a reason to stay alive even when idle, that both the server and the client side can understand.  You would "just open" more connections to the same endpoint to create more streams on the connection held up by the immortal stream.

**Comment by TryAgain2019** [comment]
When i call again the lws_client_connect_via_info(i) from inside the main main event loop. I see DROP and CLOSE callbacks right before the CLIENT INSTANTIATED. Is that normal? I was hoping to never see them again haha.

`LWS_CALLBACK_CLIENT_HTTP_BIND_PROTOCOL:
[2020/04/28 22:33:29:6979] N: lws_vhost_active_conns: apply 0x1becc50 to txn queue on 0x1b6fa80 state 0x10000011
[2020/04/28 22:33:29:6979] N: _lws_generic_transaction_completed_active_conn: pipeline queue passed wsi 0x1b6fa80 on to queued wsi 0x1becc50
[2020/04/28 22:33:29:6979] U: callback_http: doing POST flow
LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED:
LWS_CALLBACK_CLIENT_HTTP_DROP_PROTOCOL !!!!!!
LWS_CALLBACK_CLOSED_CLIENT_HTTP:
[2020/04/28 22:33:29:6980] U: callback_http:LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH:
[2020/04/28 22:33:29:9359] U: LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP: idx: 0, resp 200`


regarding H2 RO immortal, if wouldn't be read only i would love it :)
thanks again

**Comment by lws-team** [comment]
1 x wsi = 1 x http transaction.  The wsi will drop its protocol binding and close at the end of the transaction whether the connection is reused or not.

You can create another wsi / transaction that will also close at the end, but he might reuse the tcp tunnel / tcp connection.

I really suggest you stop and play with the -multi example options first.  It works on both h1 and h2.

It does not matter that there's one immortal stream that is RO if you can have as many other streams as you like each doing their own independent - fully write capable - http transactions sharing the same connection... h2 is definitely better at this.

**Comment by TryAgain2019** [comment]
ok will do, thanks a lot for the answers! Your lib is great btw.
