### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by stevedanOgochu** [warmcat/libwebsockets#1903]
Please, how do i fix this issue
`/usr/bin/ld: /tmp/cc3Xn6xY.o: in function `callback_minimal':
minimal-ws-server.c:(.text+0x80): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0xd8): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0x11f): undefined reference to `lws_get_vhost'
/usr/bin/ld: /tmp/cc3Xn6xY.o: in function `main':
minimal-ws-server.c:(.text+0x3b1): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x47e): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x4e4): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x51b): undefined reference to `lws_cmdline_option'
/usr/bin/ld: /tmp/cc3Xn6xY.o:(.data.rel+0x8): undefined reference to `lws_callback_http_dummy'
collect2: error: ld returned 1 exit status
`

**Comment by lws-team** [comment]
It looks like you have an ancient libwebsockets.so or libwebsockets.a somewhere.

Often this is you installed the distro package for libwebsockets, it is installed in /usr/lib/ or similar and the linker is picking that up.

Uninstall the distro package if that's what is going on.

**Comment by stevedanOgochu** [comment]
How do i do that because I tried deleting websockets all together and reinstalling it but it still gave the same error.

**Comment by lws-team** [comment]
Are you even linking against lws?

When you're asking me I have no idea what you did or what you are trying to build or how, I'm not sitting there.  All I can do is guess what might cause that kind of problem.  Either you're not linking against lws at all (but you would have more errors than you pasted then) or linking against an ancient lws.

If you do don't know if you have a distro lws or not, well, try something like `find / -name "libwebsockets.so*"` and see what you have.  If you're not linking against it, add -lwebsockets to your link command.

**Comment by stevedanOgochu** [comment]
I am building the minimal ws server example. I found 3 files, libwebsockets.a, libswebsockets.so and libwebsockets.so.16, Should I delete all of them_

Thank you again for your help

**Comment by lws-team** [comment]
You have to build lws and `sudo make install && sudo ldconfig` it before trying to build the examples standalone.

See https://libwebsockets.org/git/libwebsockets/tree/minimal-examples

**Comment by stevedanOgochu** [comment]
i am still geting the error 
`/Documents/libwebsockets-master/build$ sudo make install && sudo ldconfig
sudo ldconfig
[ 47%] Built target websockets
[ 48%] Built target test-server-extpoll
[ 50%] Built target test-server
[ 98%] Built target websockets_shared
[ 99%] Built target test-client
[100%] Built target test-lejp
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/pkgconfig/libwebsockets.pc
-- Up-to-date: /usr/local/lib/pkgconfig/libwebsockets_static.pc
-- Up-to-date: /usr/local/include/libwebsockets
-- Up-to-date: /usr/local/include/libwebsockets/lws-cgi.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-dbus.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-optee.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-lwsac.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-genhash.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-tokenize.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-dll2.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-secure-streams-client.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-spa.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-genec.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-fts.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-ring.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-retry.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-lejp.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-test-sequencer.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-plugin-generic-sessions.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-service.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-secure-streams-policy.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-esp32.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-ws-state.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-writeable.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-context-vhost.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-genrsa.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-sequencer.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-system.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-misc.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-vfs.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-sha1-base64.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-freertos.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-x509.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-detailed-latency.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-threadpool.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-client.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-ws-close.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-gencrypto.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-write.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-secure-streams.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-protocols-plugins.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-jwk.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-timeout-timer.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-jwe.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-mqtt.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-ws-ext.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract
-- Up-to-date: /usr/local/include/libwebsockets/abstract/transports
-- Up-to-date: /usr/local/include/libwebsockets/abstract/transports/raw-skt.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract/transports/unit-test.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract/protocols.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract/abstract.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract/transports.h
-- Up-to-date: /usr/local/include/libwebsockets/abstract/protocols
-- Up-to-date: /usr/local/include/libwebsockets/abstract/protocols/smtp.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-purify.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-dsh.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-state.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-adopt.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-callbacks.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-jose.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-async-dns.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-jws.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-http.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-logs.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-stats.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-genaes.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-diskcache.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-network-helper.h
-- Up-to-date: /usr/local/include/libwebsockets/lws-struct.h
-- Up-to-date: /usr/local/lib/libwebsockets.a
-- Up-to-date: /usr/local/include/libwebsockets.h
-- Up-to-date: /usr/local/include/lws_config.h
-- Up-to-date: /usr/local/include/lws-plugin-ssh.h
-- Up-to-date: /usr/local/lib/libwebsockets.so.16
-- Up-to-date: /usr/local/lib/libwebsockets.so
-- Up-to-date: /usr/local/include/libwebsockets.h
-- Up-to-date: /usr/local/include/lws_config.h
-- Up-to-date: /usr/local/include/lws-plugin-ssh.h
-- Up-to-date: /usr/local/bin/libwebsockets-test-server
-- Up-to-date: /usr/local/bin/libwebsockets-test-server-extpoll
-- Up-to-date: /usr/local/bin/libwebsockets-test-lejp
-- Up-to-date: /usr/local/bin/libwebsockets-test-client
-- Up-to-date: /usr/local/share/libwebsockets-test-server/libwebsockets-test-server.key.pem
-- Up-to-date: /usr/local/share/libwebsockets-test-server/libwebsockets-test-server.pem
-- Up-to-date: /usr/local/share/libwebsockets-test-server/favicon.ico
-- Up-to-date: /usr/local/share/libwebsockets-test-server/leaf.jpg
-- Up-to-date: /usr/local/share/libwebsockets-test-server/candide.zip
-- Up-to-date: /usr/local/share/libwebsockets-test-server/libwebsockets.org-logo.svg
-- Up-to-date: /usr/local/share/libwebsockets-test-server/http2.png
-- Up-to-date: /usr/local/share/libwebsockets-test-server/wss-over-h2.png
-- Up-to-date: /usr/local/share/libwebsockets-test-server/lws-common.js
-- Up-to-date: /usr/local/share/libwebsockets-test-server/test.html
-- Up-to-date: /usr/local/share/libwebsockets-test-server/test.css
-- Up-to-date: /usr/local/share/libwebsockets-test-server/test.js
-- Up-to-date: /usr/local/share/libwebsockets-test-server/private/index.html
-- Up-to-date: /usr/local/share/libwebsockets-test-server/lws-ssh-test-keys
-- Up-to-date: /usr/local/share/libwebsockets-test-server/lws-ssh-test-keys.pub
-- Up-to-date: /usr/local/lib/cmake/libwebsockets/LibwebsocketsConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/libwebsockets/LibwebsocketsConfigVersion.cmake
-- Up-to-date: /usr/local/lib/cmake/libwebsockets/LibwebsocketsTargets.cmake
-- Up-to-date: /usr/local/lib/cmake/libwebsockets/LibwebsocketsTargets-noconfig.cmake

`
and i ran ran the minimum server example 

`
cmake . && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stevedan/Documents/websocket_c/minimal-ws-server/build
[ 50%] Linking C executable lws-minimal-ws-server
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: in function `callback_minimal':
minimal-ws-server.c:(.text+0x80): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0xd8): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0x11f): undefined reference to `lws_get_vhost'
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: in function `main':
minimal-ws-server.c:(.text+0x3b1): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x47e): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x4e4): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x51b): undefined reference to `lws_cmdline_option'
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o:(.data.rel+0x8): undefined reference to `lws_callback_http_dummy'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lws-minimal-ws-server.dir/build.make:84: lws-minimal-ws-server] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/lws-minimal-ws-server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

`

**Comment by lws-team** [comment]
I built the same thing here fine on current master, I don't think it's broken.

I don't really get why your build is complaining about those specific exports and not, eg, `lws_create_context()` it's also calling in the example.  It's getting that OK out of the libwebsockets .so?  But not the others?  It makes it sound like it's finding a really ancient libwebsockets.so since the ones it is complaining about didn't exist in, eg, v1.7 from several years ago.

If I do `make clean ; make VERBOSE=1` in the example dir, I can see the link commandline it's using like this

```
/usr/lib64/ccache/cc -rdynamic CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o -o lws-minimal-ws-server  -lwebsockets
```
If I run that by hand with strace

```
strace -F /usr/lib64/ccache/cc -rdynamic CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o -o lws-minimal-ws-server  -lwebsockets  2>&1 | grep libwebsockets.so | grep -v ENOENT
[pid 352139] openat(AT_FDCWD, "/usr/local/lib/libwebsockets.so", O_RDONLY) = 9
[pid 352139] openat(AT_FDCWD, "/usr/local/lib/libwebsockets.so", O_RDONLY) = 10
```
so as I would expect, it's getting libwebsockets.so from /usr/local/lib.  If we go check what that is, it's a symlink as I would expect

```
$ ls -l /usr/local/lib/libwebsockets.so
lrwxrwxrwx. 1 root root 19 Apr  6 11:57 /usr/local/lib/libwebsockets.so -> libwebsockets.so.16
```

There is a workaround to go around this, but it won't solve the problem, you can build lws with `-DLWS_WITH_MINIMAL_EXAMPLES=1` and it will build the examples at the same time as the library.  It's a bit awkward since then are in ./build/bin and the server type examples, you must run them with the current directory being the example directory.  And it doesn't find out the real problem, so please try the above with strace and see what's coming on your machine first.

**Comment by stevedanOgochu** [comment]
when i run the first command I get this 
bash: /usr/lib64/ccache/cc: No such file or directory
when i run the second, i get nothing
Finally, I get this when I run the last command

lrwxrwxrwx 1 root root 19 may  2 19:24 /usr/local/lib/libwebsockets.so -> libwebsockets.so.16

**Comment by lws-team** [comment]
You need to use the `make VERBOSE=1` above that to find out what command your platform uses to do the link.  Then cut and paste the results of that add add `strace -F` ... `2>&1 | grep libwebsockets.so | grep -v ENOENT` around whatever it was.  Then we will find out where your link is actually looking for the libwebsockets.so on your system.

I just gave what my (Fedora) system says as an example.

**Comment by stevedanOgochu** [comment]
`/usr/bin/cmake -S/home/stevedan/Documents/websocket_c/minimal-ws-server -B/home/stevedan/Documents/websocket_c/minimal-ws-server/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/stevedan/Documents/websocket_c/minimal-ws-server/build/CMakeFiles /home/stevedan/Documents/websocket_c/minimal-ws-server/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
make -f CMakeFiles/lws-minimal-ws-server.dir/build.make CMakeFiles/lws-minimal-ws-server.dir/depend
make[2]: Entering directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
cd /home/stevedan/Documents/websocket_c/minimal-ws-server/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/stevedan/Documents/websocket_c/minimal-ws-server /home/stevedan/Documents/websocket_c/minimal-ws-server /home/stevedan/Documents/websocket_c/minimal-ws-server/build /home/stevedan/Documents/websocket_c/minimal-ws-server/build /home/stevedan/Documents/websocket_c/minimal-ws-server/build/CMakeFiles/lws-minimal-ws-server.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
make -f CMakeFiles/lws-minimal-ws-server.dir/build.make CMakeFiles/lws-minimal-ws-server.dir/build
make[2]: Entering directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
[ 50%] Building C object CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o
/usr/bin/cc    -o CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o   -c /home/stevedan/Documents/websocket_c/minimal-ws-server/minimal-ws-server.c
[100%] Linking C executable lws-minimal-ws-server
/usr/bin/cmake -E cmake_link_script CMakeFiles/lws-minimal-ws-server.dir/link.txt --verbose=1
/usr/bin/cc   -rdynamic CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o  -o lws-minimal-ws-server -lwebsockets 
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: in function `callback_minimal':
minimal-ws-server.c:(.text+0x80): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0xd8): undefined reference to `lws_get_vhost'
/usr/bin/ld: minimal-ws-server.c:(.text+0x11f): undefined reference to `lws_get_vhost'
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o: in function `main':
minimal-ws-server.c:(.text+0x3b1): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x47e): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x4e4): undefined reference to `lws_cmdline_option'
/usr/bin/ld: minimal-ws-server.c:(.text+0x51b): undefined reference to `lws_cmdline_option'
/usr/bin/ld: CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o:(.data.rel+0x8): undefined reference to `lws_callback_http_dummy'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lws-minimal-ws-server.dir/build.make:84: lws-minimal-ws-server] Error 1
make[2]: Leaving directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/lws-minimal-ws-server.dir/all] Error 2
make[1]: Leaving directory '/home/stevedan/Documents/websocket_c/minimal-ws-server/build'
make: *** [Makefile:84: all] Error 2
`

**Comment by lws-team** [comment]
Yeah so try this

```
strace -F /usr/bin/cc   -rdynamic CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o  -o lws-minimal-ws-server -lwebsockets  2>&1 | grep libwebsockets.so | grep -v ENOENT
```

**Comment by stevedanOgochu** [comment]
`[pid 14892] stat("/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebsockets.so", {st_mode=S_IFREG|0644, st_size=158736, ...}) = 0
[pid 14892] openat(AT_FDCWD, "/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebsockets.so", O_RDONLY) = 8
[pid 14892] openat(AT_FDCWD, "/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebsockets.so", O_RDONLY) = 9
`

**Comment by lws-team** [comment]
> "/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebsockets.so"

Yeah, so you have another, older distro copy of the library that it is picking up on as I guessed in the first place.

You should remove the libwebsockets package using apt or dnf or whatever and get rid of that ancient libwebsockets library copy.

**Comment by stevedanOgochu** [comment]
You man, are a God, it worked but when i open the localhost server I saw error 404, which is strange, thank you so far for your help

**Comment by lws-team** [comment]
Make sure the current working directory is the minimal example dir, ie, `./minimal-examples/ws-server/minimal-ws-server/`... to keep the example code simple it looks in . to find files to serve.

**Comment by stevedanOgochu** [comment]
I ran it from that folder but still the 404.,
[2020/05/02 22:03:43:3308] U: LWS minimal ws server | visit http://localhost:7681 (-s = use TLS / https)
