### ISSUE TITLE
Gizpped PING received

### ISSUE THREAD

**Issue by shdxiang** [warmcat/libwebsockets#1905]
I am writing a WebSocket client. The server always gzip its data. I have added the `permessage-deflate` extension on client. But I still get gzipped PINGs from server on `LWS_CALLBACK_CLIENT_RECEIVE`. The library do not recognize that is a PING packet.

So, should I decompress the gzipped PING myself and send back the PONG manually? Or i am on the wrong way to use the `permessage-deflate` extension? Thanks.

**Comment by lws-team** [comment]
https://tools.ietf.org/html/rfc7692#section-6

6.  Framing

   PMCEs operate only on data messages.
