### ISSUE TITLE
SSL error: Hostname mismatch. How to provide hostname on client?

### ISSUE THREAD

**Issue by coderDec** [warmcat/libwebsockets#1908]
I am using selfsigned server.
I have a libwebsocket client with the following ssl flags for the connect_info
`ccinfo.ssl_connection = LCCSCF_USE_SSL| LCCSCF_ALLOW_SELFSIGNED;`

I want to do the hostname check and hence not using `LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;`

But it is unclear to me on the client side, how do we provide the hostname for check? Is there a setting where I can provide hostname? The self signed certificate I generated, was using the IP address of the server.

Following is my log:
```
[2020/05/05 23:08:20:2473] N: accepting self-signed certificate (verify_callback)
[2020/05/05 23:08:20:2473] E: SSL error: Hostname mismatch (preverify_ok=0;err=62;depth=0)
```

I tried setting the following and using the same .crt and .key files that I use on the server side. 
For context info:
```
info.client_ssl_cert_filepath = "domain.crt";
info.client_ssl_private_key_filepath = "domain.key";
```

But this does no help and I still get the same error. So that does not seem the right thing to do.
Let me know what I am missing here.

**Comment by lws-team** [comment]
The hostname is the address you asked to connect to when creating the client connection... you asked to connect to "warmcat.com" and you check that whatever you connected to actually has the private key for a cert signed by something you trust.

If you ask to connect to "123.123.123.123" AFAIK that should generally also work if the cert says its CN is "123.123.123.123".

x509 based on IP seems to be seldom used and doesn't seem supported in mbedtls itself FYI.

**Comment by coderDec** [comment]
I was using IP address for a test. I will try the FQDN and run my test. 
There is a part 2 of my question, Is there a callback that would be called for this mismatch?
I do not see `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` this being called. And the only callback for the client side mentioned is `LWS_CALLBACK_OPENSSL_PERFORM_SERVER_CERT_VERIFICATION` and do not see this callback being called either. When the hostname mismatch check happens which callback will be called?

**Comment by lws-team** [comment]
Have you bound the connection to a protocol using, eg,

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n119-125

else the callback will still come, but since no protocol negotiated yet, just not to your protocol callback...

**Comment by coderDec** [comment]
No not using local_protocol_name. Will try that. 

Also the part I was missing for my initial hostname mismatch error was:
Just putting here for future reference.
For the connect info I had: 
```
ccinfo.address = server_address;
ccinfo.host = lws_canonical_hostname( context );
```
When I changed that to : 
```
ccinfo.address = server_address;
ccinfo.host = ccinfo.address;
```
It worked fine.

**Comment by coderDec** [comment]
I have only one protocol, I registered it using the following:
On the connect info, (also i reverted my earlier changes as I want the client to throw error.
```
ccinfo.protocol = protocols[PROTOCOL_EXAMPLE].name;
ccinfo.local_protocol_name = ccinfo.protocol;
```
Still I do not receive a callback, trying to figure out which callback will be called on client side when there is a tls mismatch error .

**Comment by coderDec** [comment]
The callbacks are being called. Some how my printf were being blocked by the other log prints. 

You can close this issue.

**Comment by lws-team** [comment]
General rule is if you didn't get to whatever the role's _ESTABLISHED state is, you'll get _CONNECTION_ERROR.  If you did, you'll get some form of _CLOSE depending on the role.
