### ISSUE TITLE
error: array 'humanize_schema_si' assumed to have one element [-Werror]

### ISSUE THREAD

**Issue by 19504643** [warmcat/libwebsockets#1909]
Hi, I'm building libwebsockets-3.2.2 using mingw on win7
![image](https://user-images.githubusercontent.com/4372492/81177347-13bc3c80-8fd9-11ea-8bfe-737072f59209.png)

libwebsockets-3.2.2/include/libwebsockets/lws-misc.h:897:50: error: array 'humanize_schema_si' 
assumed to have one element [-Werror]
![image](https://user-images.githubusercontent.com/4372492/81177387-29c9fd00-8fd9-11ea-954e-0853eb4ed29e.png)

**Comment by lws-team** [comment]
Just use v3.2-stable, it has the fix already

https://libwebsockets.org/git/libwebsockets/commit?id=d642a3ee2ba4f4b019c14003bcfd969711fe304e

**Comment by lws-team** [comment]
I tagged the current v3.2-stable, including that patch, out as v3.2.3 if that's easier.
