### ISSUE TITLE
Trying to conect server and client 

### ISSUE THREAD

**Issue by stevedanOgochu** [warmcat/libwebsockets#1911]
I have created both server and client. The server seems to work but the client doesnot. The aim is to send binary file from the server to the client and print that file. Please can you help me

This is the result that came after compiling the client 
[2020/05/08 12:23:55:3178] N: lws_client_connect_3_connect: lws_getaddrinfo46 failed -2
[2020/05/08 12:23:55:3178] E: CLIENT_CONNECTION_ERROR: ipv6 lws_getaddrinfo46 failed

Segmentation fault (core dumped)
This is part of the sever code
`
	// Creating the context and the context infformation
	struct lws_context_creation_info info;
	struct lws_context *context;
	const char *p;
	int n = 0, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE
			/* for LLL_ verbosity above NOTICE to be built into lws,
			 * lws must have been configured and built with
			 * -DCMAKE_BUILD_TYPE=DEBUG instead of =RELEASE */
			/* | LLL_INFO */ /* | LLL_PARSER */ /* | LLL_HEADER */
			/* | LLL_EXT */ /* | LLL_CLIENT */ /* | LLL_LATENCY */
			/* | LLL_DEBUG */;

	signal(SIGINT, sigint_handler);

	if ((p = lws_cmdline_option(argc, argv, "-d")))
		logs = atoi(p);

	lws_set_log_level(logs, NULL);
	lwsl_user("LWS minimal ws server | visit http://localhost:8080 (-s = use TLS / https)\n");
	// lwsl_user("An option is to use: file://~/melodic_workspace/ropod/Oscilloscope/browser/index.html\n");

	struct lws_protocols null_termination_proto = {NULL, NULL, 0, 0, 0, NULL, 0}; /* terminator */
	struct info_from_callback recovered_info;
	recovered_info.mynum = 42;
	recovered_info.wsi = NULL;

	struct lws_protocols protocols[] = {
	// struct lws_protocols protocols[] = {
		{ "trial_01", callback_minimal, sizeof(struct per_session_data__minimal), 128, 0, (void *)&recovered_info, 0 },
		// { "trial_03", callback_minimal, sizeof(struct per_session_data__minimal), 128, 0, NULL, 0 },

		// { NULL, NULL, 0, 0, 0, NULL, 0 } /* terminator */
		null_termination_proto
	};

	// Defining context information

	memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */
	info.port = 8080;
	info.mounts = &mount;
	// info.protocols = (const struct lws_protocols[]) { {"lws-minimal", callback_minimal, sizeof(struct per_session_data__minimal), 128, 0, (void *)(&mynum), 0 } };
	info.protocols = protocols;
	info.vhost_name = "localhost";
	info.ws_ping_pong_interval = 10;
	info.options =
		LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;

	// info.protocols[0].user = (void *)(&mynum);
	// user_data = (void *)(&mynum);
	// info.user = (void *)(&mynum);`

This is the client code 
````
/*
 * lws-minimal-ws-client
 *
 * Written in 2010-2020 by Andy Green <andy@warmcat.com>
 *
 * This file is made available under the Creative Commons CC0 1.0
 * Universal Public Domain Dedication.

 */

#include <libwebsockets.h>
#include <string.h>
#include <signal.h>
#include "arrow_display_function.h"


static int interrupted;
struct msg {
        void *payload; /* is malloc'd */
        size_t len;

};

struct info_from_callback {
      struct msg msg_args;
      struct lws *client_wsi;
};
struct info_from_callback* information_received;

static void
__minimal_destroy_message(void *_msg)
{
        struct msg *msg = _msg;

        free(msg->payload);
        msg->payload = NULL;
        msg->len = 0;
}




static int
callback_minimal(struct lws *wsi, enum lws_callback_reasons reason,
                 void *user, void *in, size_t len)
{
      // Defining call back information


      switch (reason) {

      case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
            lwsl_err("CLIENT_CONNECTION_ERROR: %s\n",
                     in ? (char *)in : "(null)");
            information_received->client_wsi = NULL;
            break;

      case LWS_CALLBACK_CLIENT_ESTABLISHED:
          lwsl_user("%s: established\n", __func__);
          break;

      case LWS_CALLBACK_CLIENT_CLOSED:
            information_received->client_wsi = NULL;
            break;

      case LWS_CALLBACK_CLIENT_RECEIVE:

            information_received->msg_args.len = len;
            /* notice we over-allocate by LWS_PRE */
            information_received->msg_args.payload = malloc(LWS_PRE + len);
            if (!information_received->msg_args.payload) {
                    lwsl_user("OOM: dropping\n");
                    break;
            }


            gsize data_size_binary = (gsize)len;
            // gconstpointer data_buffer_binary = (gconstpointer) shared_user_info->msg_args.payload;
            memcpy(information_received->msg_args.payload + LWS_PRE, in, len);

            display_arrow_buffer(information_received->msg_args.payload,&data_size_binary);
            lws_callback_on_writable(wsi);

            break;

        default:
                break;
        }

        return lws_callback_http_dummy(wsi, reason, user, in, len);

}
static const struct lws_protocols protocols[] = {
        { "lws-minimal-client", callback_minimal, 0, 0, },
        { NULL, NULL, 0, 0 }
};

static void
sigint_handler(int sig)
{
        interrupted = 1;
}

int main(int argc, const char **argv)
{
      struct lws_context_creation_info info;
      struct lws_client_connect_info i;
      struct lws_context *context;
      const char *p;
      int n = 0, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE
             /* for LLL_ verbosity above NOTICE to be built into lws, lws
               * must have been configured with -DCMAKE_BUILD_TYPE=DEBUG
               * instead of =RELEASE */
             /* | LLL_INFO */ /* | LLL_PARSER */ /* | LLL_HEADER */
             /* | LLL_EXT */ /* | LLL_CLIENT */ /* | LLL_LATENCY */
             /* | LLL_DEBUG */;

      signal(SIGINT, sigint_handler);
      if ((p = lws_cmdline_option(argc, argv, "-d")))
             logs = atoi(p);

      // test = !!lws_cmdline_option(argc, argv, "-t");

      lws_set_log_level(logs, NULL);
      lwsl_user("LWS minimal ws client rx [-d <logs>] [--h2] [-t (test)]\n");
      memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */
      info.options = LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;
      info.port = CONTEXT_PORT_NO_LISTEN; /* we do not run any server */
      info.protocols = protocols;
// #if defined(LWS_WITH_MBEDTLS)
//         /*
//          * OpenSSL uses the system trust store.  mbedTLS has to be told which
//          * CA to trust explicitly.
//          */
//         info.client_ssl_ca_filepath = "./libwebsockets.org.cer";
// #endif

      info.fd_limit_per_thread = 1 + 1 + 1;

        context = lws_create_context(&info);
        if (!context) {
                lwsl_err("lws init failed\n");
                return 1;
        }

        memset(&i, 0, sizeof i); /* otherwise uninitialized garbage */
        i.context = context;
        i.port = 8080;
        i.address = "localhost:8080";
        i.path = "/";
        i.host = i.address;
        i.origin = i.address;
        i.ssl_connection = 0;
        i.protocol = protocols[0].name; /* "dumb-increment-protocol" */
        i.pwsi = &(information_received->client_wsi);

        if (lws_cmdline_option(argc, argv, "--h2"))
                i.alpn = "h2";

        lws_client_connect_via_info(&i);

        while (n >= 0 && information_received->client_wsi && !interrupted)
                n = lws_service(context, 0);

        lws_context_destroy(context);

        lwsl_user("Completed\n");


        return 0;
}
`
```

**Comment by lws-team** [comment]
I do not have time to get involved with user code and whatever users are doing there.

If there's a similar problem using the minimal examples, let me know how to reproduce it and I'll take a look.

>  lws_getaddrinfo46 

it looks like your platform name resolution arrangements are broken, it's nothing to do with lws if so.

**Comment by stevedanOgochu** [comment]
What do you mean when you platform name resolution arrangements ?

**Comment by lws-team** [comment]
Depends on your platform, which you don't describe.  Eg, /etc/resolv.conf, /etc/nsswitch.conf, something else for Android, something else for windows... `getaddrinfo()` is failing out immediately with -2 whatever that means on your platform.

**Comment by stevedanOgochu** [comment]
It is inux ubuntu
