### ISSUE TITLE
Misleading comment in header file

### ISSUE THREAD

**Issue by thomgree** [warmcat/libwebsockets#1915]
Since libwebsockets version 4, the Ping/Pong behaviour has changed ( https://github.com/warmcat/libwebsockets/blob/master/READMEs/README.lws_retry.md ).

But the lws-context-vhost.h header still has a comment about ws_ping_pong_interval that implies that it still does something:
https://github.com/warmcat/libwebsockets/blob/ba92f2ceb11ea6bd252b58350c442adeb5cdf14c/include/libwebsockets/lws-context-vhost.h#L446

In fact ws_ping_pong_interval now seems to be ignored, so this fact should be documented in this comment.

**Comment by lws-team** [comment]
Yeah... it became cruft... I pushed a patch removing the whole thing since it's now a NOP.
