### ISSUE TITLE
build error on windows with openssl v1.1.1d

### ISSUE THREAD

**Issue by vintonliu** [warmcat/libwebsockets#1916]
Compile with cmake, there are have build error on windows with openssl v1.1.1d, 
like: error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'.

**Comment by lws-team** [comment]
Have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

**Comment by lws-team** [comment]
... if you're building for Android, have a look at this too

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-android.md

**Comment by vintonliu** [comment]
I'm building for windows x86 with IDE vs2019, not android, and only enable ipv6 and ssl option LWS_WITH_SSL, set LWS_OPENSSL_INCLUDE_DIRS include and LWS_OPENSSL_LIBRARIES to static libs path, other options are default.

**Comment by lws-team** [comment]
> https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

If you read the link I gave before, you will learn what you need to look at and paste here to debug your problem.

**Comment by vintonliu** [comment]
[Output-CMake.txt](https://github.com/warmcat/libwebsockets/files/4637999/Output-CMake.txt)
Here is my cmake output, can you look for what's wrong?

**Comment by lws-team** [comment]
Damn, I write these documents to save you and me time

> When this happens, cmake indicates that apis that must be available are not available…
CMake keeps a log of what happened with the failed test programs in
./build/CMakeFiles/CMakeError.log. This is appended to, so the best way is blow
away the build dir and reconfig a new one from scratch, and go look in there to
find out what the compiler or linker was complaining about.

Go look in the file above and look for signs of the compiler or linker choking on something.

**Comment by vintonliu** [comment]
I have read CMakError.log before, there have some error like below, I don't know if it may cause the problem, because CMake generate success.
`libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertCloseStore@8 referenced in function _capi_find_key [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function _capi_find_cert [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFindCertificateInStore@24 referenced in function _capi_find_cert [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertDuplicateCertificateContext@4 referenced in function _capi_load_ssl_client_cert [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _capi_find_key [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertGetCertificateContextProperty@16 referenced in function _capi_cert_get_fname [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]

H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\Debug\cmTC_bc594.exe : fatal error LNK1120: 7 unresolved externals [H:\GitHub\libwebsockets\out\build\x86-Debug\CMakeFiles\CMakeTmp\cmTC_bc594.vcxproj]
`
[CMakeError.log](https://github.com/warmcat/libwebsockets/files/4638044/CMakeError.log)

**Comment by lws-team** [comment]
These are making the problem that they cause all the "probe" builds that cmake is doing to fail... it makes cmake believe that the api it's probing for isn't available.  But actually it's just failing because of this problem your tls library is built to require capi.

What happens if you add the path to the ws2_32.lib and crypt32.lib libraries on LWS_OPENSSL_LIBRARIES?

**Comment by vintonliu** [comment]
Seems to work well after added that two libraries as your opinion,  thanks for your help and forgive mine poor english !!!

**Comment by lws-team** [comment]
Glad you're working.
