### ISSUE TITLE
CLIENT_CONNECTION_ERROR: connect SSL err

### ISSUE THREAD

**Issue by XinrongHuang** [warmcat/libwebsockets#1917]
[1970/01/01 19:23:05:2078] N: accepting non-trusted certificate
[1970/01/01 19:23:05:2569] E: SSL error: certificate is not yet valid (preverify_ok=0;err=9;depth=0)
[1970/01/01 19:23:05:2684] E: CLIENT_CONNECTION_ERROR: connect SSL err 1: error:00000001:lib(0):func(0):reason(1)

when I use lws connect to wss server，have this error。
SSL library I am a separate compiled version of hisilicon

cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/xin/Downloads/libwebsockets-master/contrib/cross-arm-himix200-linux.cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/xin/Downloads/lws/cross -DLWS_WITH_LWSWS=1 -DLWS_WITHOUT_SERVER=0 -DLWS_OPENSSL_LIBRARIES="/home/xin/Downloads/openssl/install/lib/libcrypto.so;/home/xin/Downloads/openssl/install/lib/libssl.so" -DLWS_OPENSSL_INCLUDE_DIRS=/home/xin/Downloads/openssl/install/include/openssl -DLWS_LIBUV_LIBRARIES=/home/xin/Downloads/lws/cross/lib/libuv.so -DLWS_LIBUV_INCLUDE_DIRS=/home/xin/Downloads/lws/cross/include -DLWS_ZLIB_LIBRARIES=/home/xin/Downloads/lws/cross/lib/libz.so -DLWS_ZLIB_INCLUDE_DIRS=/home/xin/Downloads/lws/cross/include

**Comment by lws-team** [comment]
You must have a valid date to use tls... 1/1/1970 is no good.  Set your platform date with ntpclient or whatever and it will work.
