### ISSUE TITLE
libwebsockets: messages pending

### ISSUE THREAD

**Issue by xolok-cpp** [warmcat/libwebsockets#1918]
In my use case my messages are small but there are many and they come very fast. Some times my application has to respond. However, I want it to respond only if it has processed all the messages that it has received.

I receive messages in the following way:

    static int lws_event_callback(struct lws* conn, enum lws_callback_reasons reason, void* user, void* data, size_t len)
    {
        switch(reason)
        {
            case LWS_CALLBACK_CLIENT_RECEIVE:
            {
                my_callback_client_receive(data);
            }}}

I don't know much about the internals of libwebsockets, but conceptually I can imagine that it's possible that by the time that my_callback_client_receive is called, other messages have arrived.

In my ideal world there would be a variable n which meant "number of messages waiting in a buffer to be processed" that I could pass into my call back

    case LWS_CALLBACK_CLIENT_RECEIVE:
    {
        my_callback_client_receive(data, n);
    }

So that I would know not to respond until I've processed as many messages as possible. Something like:

    void my_callback_client_receive(data, n)
    {
        process(data);
        if (n>1):
            return; // this msg is not the most recent, keep processing
        else:
            send_response();
            return;
    }

Is this or something like this possible with LWS?

**Comment by lws-team** [comment]
... you don't know what may be in flight. Ultimately when the network device fires an interrupt to say there is more rx and creates the kernel buffer for, that can happen at any time, asynchronously.

In a real system, with tls, the tls library buffers rx until it has a complete logical record it can check the validity of, these may be up to 16KB and so consist of many tcp fragments.

So at any moment, you can't be sure about partial or async rx about to happen conditions.

Nor can lws know 'how many messages' until it parses the rx, when we read them waiting messages are coalesced, so 4 x 400 byte messages become one read of 1600 bytes, if the size of the messages are not fixed, we can't estimate how many that amount of coalesced data represents.

If there's any unread rx, the event loop will come straight back to read it again without sleeping.

What I'd suggest instead is maybe use an lws_sul to keep rescheduling the callback to 250ms or whatever in the future each time you handle rx.  Only when no new rx came for 250ms would the callback fire and request the tx.

**Comment by xolok-cpp** [comment]
> What I'd suggest instead is maybe use an lws_sul to keep rescheduling the callback to 250ms or whatever in the future each time you handle rx. Only when no new rx came for 250ms would the callback fire and request the tx.

Interesting, I will look into lws_sul. What you describe is already better than what I have right now, thank you. I was wondering if it's possible to do better still. The aspect that's not ideal about this solution is if rx arrives while I'm handling one message I would like to know so I don't send a response.

> you don't know what may be in flight. Ultimately when the network device fires an interrupt to say there is more rx and creates the kernel buffer for, that can happen at any time, asynchronously.

> If there's any unread rx, the event loop will come straight back to read it again without sleeping.

I understand that the biggest problem here might be that I don't understand the low level details well enough, but bear with me... Sure, you don't know what may be in flight, but I should know how much unread rx is left, no? If I could somehow know: there's some left vs there's none left, that's really all I needed.

**Comment by lws-team** [comment]
I think you will find, contrary to what you are thinking, that is not a useful piece of information to try to acquire.  If there is rx, you will come right back around the event loop and handle it.  If there isn't, you won't.  You cannot send directly from the rx callback but must anyway request the WRITEABLE and go around the event loop, even if not with any sleep since it's already WRITEABLE.  It's racy and fruitless to try to claim there's a way to know if no rx isn't just about to pop out of the tls library.  In short the way you're framing your problem doesn't sound like it is right.

It depends on how the information is created, but, eg if the sender has an idea about what it's going to send, it can inform the receive in-band about what its plans are and then the receiver can track when it reaches that point.

Otherwise you can reframe it to detect a certain threshold of idle for rx, you can definitely implement that much cleanly.

**Comment by xolok-cpp** [comment]
Oh I see what you mean. I don't plan on sending the response within LWS though. It's not a websocket response, apologies for the confusion. It's a communication mechanism external to LWS. Specifically it's a HTTP connection that I'm keeping open elsewhere, which I would like to contact as soon as possible, but not if I still have rx on the buffer. The LWS component of my application is for receiving only. Your lws_sul solution of reschuling the callback 250ms in the future would approach this, but effectively waste 250ms waiting.

In this scenario, do you agree it's useful information, if I want to "hold off on making the HTTP call untill I'm sure I've processed everything I've received on a best effort basis, while recognizing that yes, it might happen that something is inflight"? Surely the tls library has a way of asking it: do you have zero stuff or non-zero stuff?

> It depends on how the information is created, but, eg if the sender has an idea about what it's going to send, it can inform the receive in-band about what its plans are and then the receiver can track when it reaches that point.

Undersood. However I have no control over the sending. I'm just a subscriber.

**Comment by lws-team** [comment]
250ms can be 10ms or whatever.

It doesn't change anything if it's ws or http.

I don't think it's useful to add an api for this.  Lws knows internally is the tls layer has unread stuff.  It'll present it to you via an rx callback asap if so.

**Comment by xolok-cpp** [comment]
> Lws knows internally is the tls layer has unread stuff. It'll present it to you via an rx callback asap if so.

You say that it'll present it to me asap; I understand that. But before it does, it would like my call back to know. Fundamentally I want my callback to be:

    if tls layer has unread stuff: do X
    else X and Y

You seem to be saying that's not possible. Am I understanding correctly?

**Comment by lws-team** [comment]
I'm saying:

> I don't think it's useful to add an api for this.

...I explained why:

> It's racy and fruitless to try to claim there's a way to know if no rx isn't just about to pop out of the tls library. In short the way you're framing your problem doesn't sound like it is right.

...and I explained a way to reframe your problem that you can actually get a result on:

> ... to detect a certain threshold of idle for rx, you can definitely implement that much cleanly.

Lws is foss, you can just hack whatever you want to in if it feels that's what you need, you don't need to be blocked by my not wanting it.

**Comment by xolok-cpp** [comment]
Ok, thank you very much for your help! :-)

**Comment by xolok-cpp** [comment]
Not really a question, but let me just explain why the lws_sul solution feels off.

What I really want is to know, _as soon as_ my callback is fired: is there anything else unread. You suggested rescheduling N ms into the future. So I'll want to make N really really small. Ideally zero. But as it goes to zero, questions like the resolution of the clock start to matter. So to answer a question that has nothing to do with time I'm having to have a very precise clock. This doesn't sound the correct way of doing this (even though, as we've discussed, would be the cleanest way of doing it within lws features).

Anyway thank you again for your help :-)

**Comment by lws-team** [comment]
Yeah... as I said

> I think you will find, contrary to what you are thinking, that is not a useful piece of information to try to acquire.
