### ISSUE TITLE
lws_service_adjust_timeout always returning 0

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#1921]
Platform: Linux
Libwebsockets Version: 3.0.1
OpenSSL Version: 1.1.1c

I'm experiencing and issue with my external polling loop. It sometimes it gets stuck on the `while(!lws_service_adjust_timeout(...))` because it always returns false. I'm using external polling because I have 2 lws_context that I want to serve, one being a server (LWSContext1 in the code below), the other one being a client (LWSContext2). It gets stuck in the call with LWSContext1 (I have no open connections on LWSContext2).

My system does have pipe2.

The main loop looks like this:

```
while (serverIsRunning) {
        int pollResult = poll(fds, arrcount(fds), 50);
        
        if (pollResult > 0) {
            for (int i = 0; i < arrcount(fds); ++i) {
                if (fds[i].revents) {
                    lws_service_fd(LWSContext1, &fds[i]);
                    lws_service_fd(LWSContext2, &fds[i]);
                }
            }

            /* if needed, force-service wsis that may not have read all input */
            while (!lws_service_adjust_timeout(LWSContext1, 1, 0)) {
                lwsl_notice("extpoll doing forced service on LWSContext1!\n");
                lws_service_tsi(LWSContext1, -1, 0);
            }
            
            /* if needed, force-service wsis that may not have read all input */
            while (!lws_service_adjust_timeout(LWSContext2, 1, 0)) {
                lwsl_notice("extpoll doing forced service on LWSContext2!\n");
                lws_service_tsi(LWSContext2, -1, 0);
            }
        }
}
```

**Comment by lws-team** [comment]
External polling stuff is deprecated in recent lws, it's still in there but disabled by default.  And eventually the plan is it will go away.

What's stopping us doing everything inside one lws context?

**Comment by nidoro** [comment]
Well, they are initialized differently because they are used for different purposes:

LWSContext1 is used for the context of my actual server.
```
    lws_context_creation_info contextCreationInfo = {};
    contextCreationInfo.options = LWS_SERVER_OPTION_EXPLICIT_VHOSTS | LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    contextCreationInfo.ka_time = 10;
    contextCreationInfo.ka_interval = 10;
    contextCreationInfo.ka_probes = 6;
    contextCreationInfo.pt_serv_buf_size = KILO_BYTES(128);
    contextCreationInfo.user = &ctx;

    LWSContext1 = lws_create_context(&contextCreationInfo);
```

LWSContext2 will be used for a client of server that is not mine.
```
    lws_context_creation_info ctxCreationInfo = {};
    ctxCreationInfo.client_ssl_ca_filepath = clientSSLCAPath;
    ctxCreationInfo.port = CONTEXT_PORT_NO_LISTEN;
    ctxCreationInfo.protocols = neosClientProtocols;
    ctxCreationInfo.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    ctxCreationInfo.user = ctx;
    
    LWSContext2 = lws_create_context(&ctxCreationInfo);
```

Can I have both in one single context?

**Comment by nidoro** [comment]
I guess I could make this LWSContext2 a vhost inside the first context, is that correct?

**Comment by lws-team** [comment]
Yes you can just do it all in one vhost on one context, and align it with how the minimal examples work.

Inside the event loop, lws doesn't differentiate between wsi that are serving or doing client tasks, they can coexist just fine as many as you like and to different endpoints.  When they do callbacks, they have different sets of callback reasons for client and server, making it possible for one protocol handler to do both sides in one callback function.

The main way clients differ is in the tls arrangements, but even there one vhost has two tls contexts, one for server set up with the server certs and a different one used for client connections on the vhost.

As you described it it should be within the basic functionality you get from one context and its default, single vhost.  Which will simplify your code a lot...

**Comment by nidoro** [comment]
Nice! Thanks for explaining that. I just finished the necessary changes and it works just fine. And it really made the code much simpler. Thanks a lot!
