### ISSUE TITLE
LWS_CALLBACK_FILTER_NETWORK_CONNECTION issue

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#1922]
Hi,

If I use the event LWS_CALLBACK_FILTER_NETWORK_CONNECTION to reject one specific connection (by not returning 0) then the system no longer accepts any new connection afterwards.

Regards.

**Comment by lws-team** [comment]
Can you maybe try this on a minimal example and provide a little test diff if it still fails?  What is your platform?

**Comment by dev31337** [comment]
I was able to track down the issue in lib/roles/listen/op-listen.c:

                if ((wsi->vhost->protocols[0].callback)(wsi,
                                LWS_CALLBACK_FILTER_NETWORK_CONNECTION,
                                NULL,
                                (void *)(lws_intptr_t)accept_fd, 0)) {
                        lwsl_debug("Callback denied net connection\n");
                        compatible_close(accept_fd);
                        return LWS_HPI_RET_PLEASE_CLOSE_ME;
                }

This issue is that returning LWS_HPI_RET_PLEASE_CLOSE_ME makes the library close the wrong wsi, because the wsi for the connection has not been created yet.

I changed the return to LWS_HPI_RET_HANDLED and the issue is gone.

**Comment by lws-team** [comment]
Thanks... it looks wrong.  I pushed your patch on master + v4.0-stable.
