### ISSUE TITLE
lws_write interface will crash

### ISSUE THREAD

**Issue by zzb2019** [warmcat/libwebsockets#1925]
The lws_write interface will crash if a disconnected wsi is passed in. What should I do?
![截图](https://user-images.githubusercontent.com/42893521/82852187-ce828f00-9f34-11ea-8115-1abad531b001.png)

**Comment by lws-team** [comment]
- lws is not threadsafe
 - you cannot call lws_write() outside of the writeable callback
 - I provide 80 minimal examples that show how to use lws correctly, study and follow them, eg,

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads
