### ISSUE TITLE
  Unknown CMake command "require_lws_config".

### ISSUE THREAD

**Issue by stevedanOgochu** [warmcat/libwebsockets#1928]
I got this error while building the minimal ws server example. I tried to build in the same folder of the project and alone but still got the same error
```

CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:

    LwsCheckRequirements


CMake Error at CMakeLists.txt:10 (require_lws_config):
  Unknown CMake command "require_lws_config".


-- Configuring incomplete, errors occurred!
See also "/home/stevedan/Desktop/TESTING/minimal-ws-server/build/CMakeFiles/CMakeOutput.log".
```

**Comment by lws-team** [comment]
Yeah... this is caused by a recent huge refactor in CMake stuff in lws.

You can solve it with adding `set(CMAKE_MODULE_PATH ../../../cmake)` after the minimum required version, like this

```
diff --git a/minimal-examples/http-server/minimal-http-server/CMakeLists.txt b/minimal-examples/http-server/minimal-http-server/CMakeLists.txt
index 8a36d1cef..936fa39ef 100644
--- a/minimal-examples/http-server/minimal-http-server/CMakeLists.txt
+++ b/minimal-examples/http-server/minimal-http-server/CMakeLists.txt
@@ -1,5 +1,6 @@
 project(lws-minimal-http-server)
 cmake_minimum_required(VERSION 2.8)
+set(CMAKE_MODULE_PATH ../../../cmake)
 include(CheckCSourceCompiles)
 include(LwsCheckRequirements)
 
```

I'll add that missing line in on master in a few minutes (there are about 80 examples to do...)

**Comment by stevedanOgochu** [comment]
it is for the lws-minimal-ws-server

```
project(lws-minimal-ws-server)
cmake_minimum_required(VERSION 3.13.4)
set(CMAKE_MODULE_PATH ../../../cmake)

include(CheckCSourceCompiles)
include(LwsCheckRequirements)
```

**Comment by lws-team** [comment]
`/home/stevedan/Desktop/TESTING/minimal-ws-server/`

The workaround is for if you are building it inside lws tree.  I'm trying to figure out a more complete one.

**Comment by stevedanOgochu** [comment]
```
stevedan@stevedan-MXC6300:~/external_library/libwebsockets/minimal-examples/ws-server/minimal-ws-server/build$ cmake ..
CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    LwsCheckRequirements


CMake Error at CMakeLists.txt:11 (require_lws_config):
  Unknown CMake command "require_lws_config".


-- Configuring incomplete, errors occurred!
```
I still get the error, I will wait till you update it and install and try it again because I added the line and still did not work

**Comment by lws-team** [comment]
It's not working because you added a build subdir there, so you need an extra ..

`set(CMAKE_MODULE_PATH ../../../../cmake)`

**Comment by stevedanOgochu** [comment]
Works, thank you very much

**Comment by lws-team** [comment]
I figured out a way that works for -DLWS_WITH_MINIMAL_EXAMPLES=1, build directly in the tree, directly in the tree with ./build, and if you copy out the example dir.  current master should work for all the variations now.
