### ISSUE TITLE
LWS_LIBRARY_VERSION_NUMBER not an integer

### ISSUE THREAD

**Issue by pctj101** [warmcat/libwebsockets#1931]
In lws_config.h we see:

#define LWS_INSTALL_DATADIR "/usr/local/share"
#define LWS_LIBRARY_VERSION_MAJOR 4
#define LWS_LIBRARY_VERSION_MINOR 0
#define LWS_LIBRARY_VERSION_PATCH 99-v4.0.0-143-gcd3baf3f
/* LWS_LIBRARY_VERSION_NUMBER looks like 1005001 for e.g. version 1.5.1 */
#define LWS_LIBRARY_VERSION_NUMBER (LWS_LIBRARY_VERSION_MAJOR * 1000000) + \
                                        (LWS_LIBRARY_VERSION_MINOR * 1000) + \
                                        LWS_LIBRARY_VERSION_PATCH

The problem is that LWS_LIBRARY_VERSION_PATCH is a string which can't be added to LWS_LIBRARY_VERSION_NUMBER.  That causes crashes at compile time for other programs which depend on the "integer" nature of a _NUMBER define. 

Is there a way to use only int(99) for LWS_LIBRARY_VERSION_NUMBER and perhaps make a more fancy LWS_LIBRARY_VERSION_NAME ?

**Comment by lws-team** [comment]
> which depend on the "integer" nature of a _NUMBER define.

I changed it because I want the string in CPack produced filepaths, I didn't find another way to make that happen.  But you make a good point.

I pushed a patch on master, does that help?

**Comment by pctj101** [comment]
Looks good.  I'm going to run a compile through and let you know what happens.

**Comment by pctj101** [comment]
Works well!

**Comment by lws-team** [comment]
Great.
