### ISSUE TITLE
Signal function not working after create_context

### ISSUE THREAD

**Issue by GuoDangLang** [warmcat/libwebsockets#1933]
At first I signal(SIGINT, handler), then I memset the info and call creat_context to create context for my server's instance(at this point, I have not called lws_service or whatever lws's functions).
I run it, and the SIGINT signal would not be catched. What's the solution? thx.

**Comment by lws-team** [comment]
Are you using the default poll event loop or something else?

**Comment by GuoDangLang** [comment]
info.options = LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE | LWS_SERVER_OPTION_LIBEVENT | LWS_SERVER_OPTION_VALIDATE_UTF8;&nbsp;
does this mean that I used libevent?




------------------&nbsp;Original message&nbsp;------------------
From: "Andy Green"; 
Sendtime: Friday, May 29, 2020 4:24 PM
To: "warmcat/libwebsockets"; 
Cc: "阿添"<155292013@qq.com>; "Author"; 
Subject: Re: [warmcat/libwebsockets] Signal function not working after create_context (#1933)





 
Are you using the default poll event loop or something else?

**Comment by lws-team** [comment]
Yes things are different with the event libs because they want to handle the signals inside the event library.

If you want to use libevent, happens if you use the minimal examples for that, still the same problem?

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-demos

**Comment by GuoDangLang** [comment]
Oh, Thank you sir.  I'll try it.One more question, Can i register my own fd to the event loop?  and if so, Can I write to others from this fd's callback function using functions like lws_on_writable? 🙏

**Comment by lws-team** [comment]
You can run your own stuff on the same event loop however you like, but lws will not know about it.

You can also create an fd and have it "adopted" and added to the event loop by lws, and lws will create a wsi and manage it afterwards.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-adopt.h#n148
