### ISSUE TITLE
Issue of compiling libwebsockets in RHEL

### ISSUE THREAD

**Issue by opg7371** [warmcat/libwebsockets#1935]
Libwebsockets is compiling greatly in the Ubuntu OS. But it fails to compile the same for RHEL 6.8 OS. However, libwebsocket is compiling for CentOS 8. 

whenever after typing `cmake .`, then i type `make`, I get the following error - 

In file included from /root/kk/libwebsockets/lib/plat/unix/./private-lib-plat-unix.h:61,
                 from /root/kk/libwebsockets/lib/core/./private-lib-core.h:123,
                 from /root/kk/libwebsockets/lib/misc/base64-decode.c:43:
/usr/include/linux/if_packet.h:10: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:16: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:65: error: expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/if_packet.h:104: error: expected specifier-qualifier-list before ‘__u16’

In my OS, i know that these symbols are located in /usr/include/linux/types.h and i have tried to include it in the source code, but i do not feel that is working out. i am still stuck at the same error.

I know that it is not defined for RHEL platform when i look in the libwebsockets/lib/plat, 
then why is it compiling in RHEL 8. 

If it can be compiled in RHEL 8, then please help me out.
I have tried out most of the ways suggested by google, be it installing libcap, libcap-devel, libb64 or SSL related library.
i would however want to give shot to whatever method you will suggest.

Thanks for helping out in advance.

**Comment by opg7371** [comment]
When i ran make VERBOSE=1

I got the following output

/usr/bin/cmake -H/root/kk/libwebsockets -B/root/kk/libwebsockets --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /root/kk/libwebsockets/CMakeFiles /root/kk/libwebsockets/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/root/kk/libwebsockets'
make -f CMakeFiles/GENHDR.dir/build.make CMakeFiles/GENHDR.dir/depend
make[2]: Entering directory `/root/kk/libwebsockets'
cd /root/kk/libwebsockets && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/kk/libwebsockets /root/kk/libwebsockets /root/kk/libwebsockets /root/kk/libwebsockets /root/kk/libwebsockets/CMakeFiles/GENHDR.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/root/kk/libwebsockets'
make -f CMakeFiles/GENHDR.dir/build.make CMakeFiles/GENHDR.dir/build
make[2]: Entering directory `/root/kk/libwebsockets'
make[2]: Nothing to be done for `CMakeFiles/GENHDR.dir/build'.
make[2]: Leaving directory `/root/kk/libwebsockets'
/usr/bin/cmake -E cmake_progress_report /root/kk/libwebsockets/CMakeFiles
[  0%] Built target GENHDR
make -f lib/CMakeFiles/websockets.dir/build.make lib/CMakeFiles/websockets.dir/depend
make[2]: Entering directory `/root/kk/libwebsockets'
cd /root/kk/libwebsockets && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/kk/libwebsockets /root/kk/libwebsockets/lib /root/kk/libwebsockets /root/kk/libwebsockets/lib /root/kk/libwebsockets/lib/CMakeFiles/websockets.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/root/kk/libwebsockets'
make -f lib/CMakeFiles/websockets.dir/build.make lib/CMakeFiles/websockets.dir/build
make[2]: Entering directory `/root/kk/libwebsockets'
/usr/bin/cmake -E cmake_progress_report /root/kk/libwebsockets/CMakeFiles 21
[  1%] Building C object lib/CMakeFiles/websockets.dir/misc/base64-decode.c.o
cd /root/kk/libwebsockets/lib && /usr/bin/cc   -g -Wall -Wsign-compare -Wstrict-aliasing -Wuninitialized -fvisibility=hidden -Wundef  -Wtype-limits -Wignored-qualifiers   -Werror -pthread -I/root/kk/libwebsockets/include -I/root/kk/libwebsockets -I/root/kk/libwebsockets/lib -I/root/kk/libwebsockets/lib/. -I/root/kk/libwebsockets/lib/plat/unix/. -I/root/kk/libwebsockets/lib/tls/. -I/root/kk/libwebsockets/lib/core/. -I/root/kk/libwebsockets/lib/misc/. -I/root/kk/libwebsockets/lib/system/./async-dns -I/root/kk/libwebsockets/lib/event-libs/. -I/root/kk/libwebsockets/lib/event-libs/poll/../poll -I/root/kk/libwebsockets/lib/core-net/. -I/root/kk/libwebsockets/lib/roles/. -I/root/kk/libwebsockets/lib/roles/http/. -I/root/kk/libwebsockets/lib/roles/http/./compression -I/root/kk/libwebsockets/lib/roles/h1/. -I/root/kk/libwebsockets/lib/roles/h2/. -I/root/kk/libwebsockets/lib/roles/ws/. -I/root/kk/libwebsockets/lib/roles/raw-skt/. -I/root/kk/libwebsockets/lib/roles/raw-file/. -I/root/kk/libwebsockets/lib/roles/listen/.    -o CMakeFiles/websockets.dir/misc/base64-decode.c.o
  -c /root/kk/libwebsockets/lib/misc/base64-decode.c
In file included from /root/kk/libwebsockets/lib/plat/unix/./private-lib-plat-unix.h:61,
                 from /root/kk/libwebsockets/lib/core/./private-lib-core.h:123,
                 from /root/kk/libwebsockets/lib/misc/base64-decode.c:43:
/usr/include/linux/if_packet.h:10: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:16: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:65: error: expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/if_packet.h:104: error: expected specifier-qualifier-list before ‘__u16’
make[2]: *** [lib/CMakeFiles/websockets.dir/misc/base64-decode.c.o] Error 1
make[2]: Leaving directory `/root/kk/libwebsockets'
make[1]: *** [lib/CMakeFiles/websockets.dir/all] Error 2
make[1]: Leaving directory `/root/kk/libwebsockets'
make: *** [all] Error 2

**Comment by lws-team** [comment]
Right I actually test it in CI in Centos 8 now, so it's not news that it builds OK.

If I want to look at your situation from Centos side (because I am not going to pay RH), what CentOS version corresponds to your rhel version?

Basically your error seems to be internal OS or toolchain include issue, eg, problem with finding the right `sys/types.h` that defines `__be16` etc.  On my Fedora 32 box that ultimately comes out of `/usr/include/asm-generic/int-ll64.h`

It's nothing to do with libcap or SSL or whatever, the ultimate definition for it is in `/usr/include/linux/types.h` in fedora, and that file is owned by the `kernel-headers` package.  So if you messed with the kernel, make sure you installed matching kernel-headers for the right arch, etc.

If that's OK, I would strace gcc when it tries to build something that uses `__be16` and `#include <sys/types.h>` and see where it is going to find sys/types.h.

At any rate this is a problem with your OS / toolchain, it's not a problem with lws AFAICS.

**Comment by opg7371** [comment]
Output of strace is 


[root@callprocessing1 libwebsockets]# strace /usr/bin/gcc   -g -Wall -Wsign-compare -Wstrict-aliasing -Wuninitialized -fvisibility=hid den -Wundef  -Wtype-limits -Wignored-qualifiers   -Werror -pthread -I/root/kk/libwebsockets/include -I/root/kk/libwebsockets -I/root/k k/libwebsockets/lib -I/root/kk/libwebsockets/lib/. -I/root/kk/libwebsockets/lib/plat/unix/. -I/root/kk/libwebsockets/lib/tls/. -I/root /kk/libwebsockets/lib/core/. -I/root/kk/libwebsockets/lib/misc/. -I/root/kk/libwebsockets/lib/system/./async-dns -I/root/kk/libwebsock ets/lib/event-libs/. -I/root/kk/libwebsockets/lib/event-libs/poll/../poll -I/root/kk/libwebsockets/lib/core-net/. -I/root/kk/libwebsoc kets/lib/roles/. -I/root/kk/libwebsockets/lib/roles/http/. -I/root/kk/libwebsockets/lib/roles/http/./compression -I/root/kk/libwebsock ets/lib/roles/h1/. -I/root/kk/libwebsockets/lib/roles/h2/. -I/root/kk/libwebsockets/lib/roles/ws/. -I/root/kk/libwebsockets/lib/roles/ raw-skt/. -I/root/kk/libwebsockets/lib/roles/raw-file/. -I/root/kk/libwebsockets/lib/roles/listen/.    -o CMakeFiles/websockets.dir/mi sc/base64-decode.c.o /root/kk/libwebsockets/lib/misc/base64-decode.c
execve("/usr/bin/gcc", ["/usr/bin/gcc", "-g", "-Wall", "-Wsign-compare", "-Wstrict-aliasing", "-Wuninitialized", "-fvisibility=hidden", "-Wundef", "-Wtype-limits", "-Wignored-qualifiers", "-Werror", "-pthread", "-I/root/kk/libwebsockets/include", "-I/root/kk/libwebsockets", "-I/root/kk/libwebsockets/lib", "-I/root/kk/libwebsockets/lib/.", ...], [/* 23 vars */]) = 0
brk(0)                                  = 0x17fb000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f35abe39000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=39390, ...}) = 0
mmap(NULL, 39390, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f35abe2f000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\356\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1924768, ...}) = 0
mmap(NULL, 3750184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f35ab887000
mprotect(0x7f35aba11000, 2097152, PROT_NONE) = 0
mmap(0x7f35abc11000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18a000) = 0x7f35abc11000
mmap(0x7f35abc17000, 14632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f35abc17000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f35abe2e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f35abe2d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f35abe2c000
arch_prctl(ARCH_SET_FS, 0x7f35abe2d700) = 0
mprotect(0x7f35abc11000, 16384, PROT_READ) = 0
mprotect(0x7f35abe3a000, 8192, PROT_READ) = 0
munmap(0x7f35abe2f000, 39390)           = 0
brk(0)                                  = 0x17fb000
brk(0x181c000)                          = 0x181c000
open("/usr/lib/locale/locale-archive", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=99164480, ...}) = 0
mmap(NULL, 99164480, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f35a59f4000
close(3)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2512, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f35abe38000
read(3, "# Locale name alias data base.\n#"..., 4096) = 2512
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f35abe38000, 4096)            = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/gcc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
rt_sigaction(SIGINT, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGINT, {0x403017, [INT], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_IGN, [INT], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, 8) = 0
rt_sigaction(SIGHUP, {SIG_IGN, [HUP], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGHUP, {0x403017, [HUP], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_IGN, [HUP], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {0x403017, [TERM], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_IGN, [TERM], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPIPE, {0x403017, [PIPE], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f35ab8b9660}, {SIG_DFL, [], 0}, 8) = 0
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/bin", {st_mode=S_IFDIR|0555, st_size=36864, ...}) = 0
lstat("/usr/bin/gcc", {st_mode=S_IFREG|0755, st_size=263984, ...}) = 0
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/bin", {st_mode=S_IFDIR|0555, st_size=36864, ...}) = 0
lstat("/usr/bin/gcc", {st_mode=S_IFREG|0755, st_size=263984, ...}) = 0
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/", X_OK) = 0
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/", X_OK) = 0
access("/root/kk/libwebsockets/lib/misc/base64-decode.c", F_OK) = 0
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/specs", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/specs", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../x86_64-redhat-linux/lib/x86_64-redhat-linux/4.4.7/specs", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../x86_64-redhat-linux/lib/specs", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/gcc/x86_64-redhat-linux/specs", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/gcc/x86_64-redhat-linux/4.4.7/", X_OK) = 0
access("/tmp", R_OK|W_OK|X_OK)          = 0
gettimeofday({1590868064, 288923}, NULL) = 0
getpid()                                = 11397
open("/tmp/ccNaBUAK.s", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
close(3)                                = 0
stat("/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1", {st_mode=S_IFREG|0755, st_size=9350064, ...}) = 0
access("/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1", X_OK) = 0
vfork()                                 = 11398
wait4(11398, In file included from /root/kk/libwebsockets/lib/plat/unix/./private-lib-plat-unix.h:61,
                 from /root/kk/libwebsockets/lib/core/./private-lib-core.h:123,
                 from /root/kk/libwebsockets/lib/misc/base64-decode.c:43:
/usr/include/linux/if_packet.h:10: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:16: error: expected specifier-qualifier-list before ‘__be16’
/usr/include/linux/if_packet.h:65: error: expected specifier-qualifier-list before ‘__u16’
/usr/include/linux/if_packet.h:104: error: expected specifier-qualifier-list before ‘__u16’
/root/kk/libwebsockets/lib/misc/base64-decode.c:45:19: error: utils.h: No such file or directory
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 11398
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=11398, si_status=1, si_utime=8, si_stime=2} ---
stat("/tmp/ccNaBUAK.s", {st_mode=S_IFREG|0600, st_size=195, ...}) = 0
unlink("/tmp/ccNaBUAK.s")               = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by opg7371** [comment]
Anyway, I wanted you to know that there was certain problem with the file including. The file if_packet.h in /usr/include/linux/ was not able to include /usr/include/linux/types.h

I don't know why such behavior was observed.

Workaround that I found was just copying the contents of types.h into if_packets.h and the error were resolved. However, I will still try to get to the bottom of this problem regarding the including of header files in /usr/include/linux directory. 

Definitely, not a problem of LWS and will post the solution of system problems if found here.

Also, if you can redirect me towards some documentation as to how the test-client and test-server works particularly when we want to send a message built from the response of another message sent by test-client.

Thanks for all the help so quickly and please close this issue if you like.

**Comment by lws-team** [comment]
You need to do something like this for strace, `-f` tells it to follow forked children

```
$ strace -f gcc -c /tmp/test.c 2>&1 | grep "sys/types\.h"
read(4, "#include <sys/types.h>\n\n", 1024) = 24
stat("/usr/include/sys/types.h", {st_mode=S_IFREG|0644, st_size=5713, ...}) = 0
stat("/usr/include/sys/types.h", {st_mode=S_IFREG|0644, st_size=5713, ...}) = 0
openat(AT_FDCWD, "/usr/include/sys/types.h", O_RDONLY) = 5
```

> Anyway, I wanted you to know that there was certain problem with the file including.

I think you have that problem on your box, but I don't think RHEL, CentOS, lws or anybody else has that problem from what was described.

There is a handy feature of rpm, like

```
$ rpm -qV kernel-headers
```

it goes through the files installed by the package and reports any files with a different hash than the package installed, ie, verifies that its installed files are unchanged.  Since you changed one it (your willingness to do that to rhel-controlled files is a bit of a red flag you may have been willing to do other things to it, knowing or unknowing, that broke it) should find and report that but maybe some other things changed if you give it more packages like `glic-headers` and `gcc` or whatever the equivalent is in rhel.  If the problem is, eg, you did a make install of some things into `/usr` and it overwrote rhel-controlled things this is a way to detect that, if you give it the right package to check.
