### ISSUE TITLE
Where to obtain source code archives of official releases?

### ISSUE THREAD

**Issue by falk-werner** [warmcat/libwebsockets#1936]
I want to use libwebsockets in a [meson](https://mesonbuild.com/) project and create a meson wrap for it, so I can use libwebsockets as a subproject. Therefore I need a link to download source code archives (either zip or tar.gz) for the requested version.

Since this github repository is a mirror for the repository hosted at libwebsockets.org, I tried to use the archives obtained from there, e.g. [https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-v4.0.13.zip](https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-v4.0.13.zip).

Since meson checks the SHA256 checksum of those archives, the checksum of the downloaded archives must not change. Unfortunately the checksums of files download via the link above differ between downloads. I tried the following just a few minutes ago:

````
wget https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-v4.0.13.zip
sha256sum libwebsockets-v4.0.13.zip
42b9301947b1571b5df4c63e777cd6711768a96d04211a69bfe0f572ef7473ca libwebsockets-v4.0.13.zip

wget https://libwebsockets.org/git/libwebsockets/snapshot/libwebsockets-v4.0.13.zip
sha256sum libwebsockets-v4.0.13.zip
cc233698e9eb6e354b1fc54d530e2172b35a990fa9741fa6c0622e47699ec491 libwebsockets-v4.0.13.zip
````

Fortunately I notived, that the releases on github work fine.

**My question:** _Is it valid to use the releases on github instead for my use case or should I prefer another link to download released source archives of libwebsockets?_

**Comment by lws-team** [comment]
The canonical place is libwebsockets.org.

On there the archives are produced dynamically by gitohashi from the git repo directly, using libgit2 + libarchive.  If nothing else broken about the downloads, maybe the difference is around the datestamps on the files inside tbe archive, afaik the rest of it is deterministic.

If that's the right idea it could maybe be solved by teaching gitohashi to use the date of the head commit on the files.

I don't know meson but another way to get the commit contents repeatably is a shallow clone.

**Comment by lws-team** [comment]
Thanks...

Yes gitohashi has a big sophisticated server-side lru cache for things it generates... usually what it generates and caches is JSON, which is rendered by the browser to make the view on the repo for whatever the uri is looking at.

This sounds like a corner-case bug for either when it places it in the cache or reissues the same object from the cache, typically that's a JSON subobject embedded in larger JSON parent, the comma would be part of extracting it then but is junk for the generated archive.  I'll look at it in a bit and reply again.

**Comment by lws-team** [comment]
I think that should be solved with a one-line patch on gitohashi... thanks for the report.

**Comment by falk-werner** [comment]
This solves the issue. I tried it several time and got always the correct file with the correct hash `42...`.
Many thanks for your help.
