### ISSUE TITLE
Libwebsocket is aborting 

### ISSUE THREAD

**Issue by Joecpu** [warmcat/libwebsockets#1938]
Hi,

I am trying to connect 1000 clients to the server using libwebsocket. This issue is seen in 3.2 release version.
So what happens is my server using libwebsockets opens up sockets to upstream servers. After sending data to the server the socket is closed. This happens both during and after all 1000 clients connect. 
When the clients try to establish a connection the server aborts because it can find the entry in the wsi_lookup table. 

/libwebsockets/lib/plat/unix/unix-fds.c:54: insert_wsi: Assertion `context->lws_lookup[wsi->desc.sockfd - (0)] == 0' failed. 
[2020/06/01 14:52:41:7923] INFO: lws_vhost_bind_wsi: vh default: count_bound_wsi 552
[2020/06/01 14:52:41:7924] INFO: lws_header_table_attach: did attach wsi 0x7f735d260d70: ah 0x7f735d260fe0: count 2 (on exit)
Aborted (core dumped)

**the gdb is as attached below
[gdb_websockets.txt](https://github.com/warmcat/libwebsockets/files/4712697/gdb_websockets.txt)

1540 was opened as part of my upstream data socket, but it was closed. Within the same second i can see abort being called.

 [2020/06/01 14:52:41:7907] NOTICE: HandleTcpConnectionDown: TCP DOWN: DelEntryWithF0x7f7361216150: count 1 (on wsi fd 1557 associated to FD: 1540).

This is when using lws with SMP > 1. This bug does not show up very frequently maybe 1 in 50, and only when large number of client attach to the server.
Can you guys please help me with this. I am not sure why the wsi context is found for this fd. 

Thanks.

**Comment by lws-team** [comment]
> This is when using lws with SMP > 1

That is kind of experimental... and to the extent it works, if you are also doing client connections like that, you are exercising a lot of code in that mode.

gdb is not the right tool for debugging what is basically locking problems, you probably get better info from valgrind / helgrind.

> epoll_wait () 

Where did the epoll() come from?  You added that in or some event lib?

**Comment by Joecpu** [comment]
I have added that in for my set of sockets opened up for the upstream servers. Ok i will try with helgrind to see what i can find. It might take time, as i have mentioned before it does not happen quit often.

**Comment by lws-team** [comment]
Often with this stuff helgrind can identify the conditions that lead to the symptom without having to wait for the symptom.

Lws can mix and match client connections on the same event loop as the server ones itself without epoll.

**Comment by Joecpu** [comment]
Hi 
These are the set of "possible data race" from helgrind.  
[helgrind_report.txt](https://github.com/warmcat/libwebsockets/files/4722297/helgrind_report.txt)

**Comment by lws-team** [comment]
It's not interesting to debug v3.2 for me... can you try it with master lws and collect the same traces, if the problem is still coming?

**Comment by lws-team** [comment]
I guess that's a 'no' then.

**Comment by Joecpu** [comment]
Hi 
Sorry for the late response, after upgrading to version 4.0 i tried multiple times to reproduce the issue and was not able too I did not try with master yet. I was check in lws to see what has changed. But thanks for your support and suggestions.

**Comment by lws-team** [comment]
OK... the code that was making the problem in your backtraces doesn't exist any more in later lws.  That's why I suggest retry with master, but IIRC it's gone also in v4.0 too.

**Comment by Joecpu** [comment]
Oh i see. I first thought it will be better to check with 4.0 and then go to master. That's why it took time. Thanks again, really appreciate the help. :)
