### ISSUE TITLE
libwebsockets-test-server.key.pem no such file or directory

### ISSUE THREAD

**Issue by GuoDangLang** [warmcat/libwebsockets#1940]
Hi sir,
    when I cmake libwebsockets on Ubuntu14.04 TLS, it turned out this error. I don't know why. Please help. 
CMake Error at cmake_install.cmake:169 (file):
  file INSTALL cannot find
  "/data/libwebsockets-4.0.9/build/libwebsockets-test-server.key.pem": No
  such file or directory.
make: *** [install] Error 1

**Comment by lws-team** [comment]
>  Ubuntu14.04

You are going to have a lot of problems trying to use a 6 year old OS, like your cert bundle does not work with modern certificates on the internet.  It's workable at the moment on 16.04 / Xenial but even then you have to replace some packages for, eg, modern cmake.

> "/data/libwebsockets-4.0.9/build/libwebsockets-test-server.key.pem"

lws cmake creates some selfsigned test certificates for localhost, for use by the test server.  It looks like that failed earlier, look back in the cmake logs.  It's a good idea to delete everything in the build dir and try `cmake ..` again.

**Comment by GuoDangLang** [comment]
In fact, I have solved a problem when I try to execute "make".  I add this,
"DOPENSSL_INCLUDE_DIR=/usr/local/include/openssl -DOPENSSL_SSL_LIBRARY=/usr/local/lib64/libssl.so -DOPENSSL_CRYPTO_LIBRARY  /usr/local/lib64/libcrypto.so " to the cmake command, then succeeded making, then I have that problem during "sudo make install",   is there any possibility that this problem was caused by the precedent problem I solved?

**Comment by lws-team** [comment]
Dunno, I don't think this represents any issue inside lws though.

Glad you are working.
