### ISSUE TITLE
bind() is failed when specify interface name.

### ISSUE THREAD

**Issue by SeonahMoon** [warmcat/libwebsockets#1944]
Hello.

When i created lws_client_connect_info with interface name, bind() got failed.
I think invalid scope id is set to sockaddr if interface name is specified.

**[lws_socket_bind() in network.c]**
serv_addr6.sin6_scope_id = lws_get_iface_scope(iface);  // 'iface' is interface name.

**[lws_get_addr_scope() in network.c]**
lws_get_addr_scope(const char *ipaddr) // interface name is passed as 'ipaddr'.
{
... skipping...
		if (!strcmp(ip, ipaddr)) { // bug : interface name is compared with ip address. It is always failure.
			scope = if_nametoindex(addr->ifa_name); 
			break;
		}
}

According to [API reference](https://libwebsockets.org/lws-api-doc-master/html/structlws__client__connect__info.html#ad3cc6581d486c62de420b01d288c5fc1), iface can be interface name or IP But the codes consider IP address only.
Can you please check this issue?

Thanks.

**Comment by lws-team** [comment]
I pushed a patch on master for this, please give it a try.

**Comment by SeonahMoon** [comment]
It works normally after applying your patch.
Thanks :)
