### ISSUE TITLE
FreeBSD minimal-ws-server only listens on ipv6.

### ISSUE THREAD

**Issue by jsm222** [warmcat/libwebsockets#1947]
This is version 4.0.15. after building and building libwebsockets-4.0.15/minimal-examples/ws-server/minimal-ws-server the server only uses ipv6 even though ipv4 is enabled.  I found this issue working on a port of https://github.com/meetecho/janus-gateway/
The only way on FreeBSD to use ipv4 is to disable the IPV6 build option.. 
Do you have any hints on why this happens?

**Comment by jsm222** [comment]
Thank you :-) That works, I'll add a patch to my janus-gateway port that inserts that if the ip is ipv4 format.

**Comment by lws-team** [comment]
Great.
