### ISSUE TITLE
Add quotes for boundary 

### ISSUE THREAD

**Issue by fjzhangZzzzzz** [warmcat/libwebsockets#1948]
https://github.com/warmcat/libwebsockets/blob/280584ff8f147832f008b299d0e32fd4273024db/lib/roles/http/client/client-http.c#L1030

According to the [rfc2046 - 5.1.1 Common Syntax](https:/tools.ietf.org/html/rfc2046#section-5.1.1) standard, quotes should be added to the boundary to prevent http header syntax problems.

Actually, I ran into this problem. The server rejected my POST request because of the "/" in the boundary.

**Comment by lws-team** [comment]
Thanks for pointing it out clearly.  I pushed a patch on master and v4.0-stable to quote the boundary and also take care of that on server side of lws.
