### ISSUE TITLE
Building on Windows: x86 configuration

### ISSUE THREAD

**Issue by pecec** [warmcat/libwebsockets#1949]
I'm trying to build x86 version of lws. All rest for x86 (including recent version of OpenSSL) were build/gathered, but running

`$ ...build>cmake .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="..\prebuilt-dll-2-9-1-release\include" -DLWS_EXT_PTHREAD_LIBRARIES="..\prebuilt-dll-2-9-1-release\lib\x86\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1 -DCMAKE_GENERATOR_PLATFORM=x86`

I obtain " error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32.  "
more details:

`-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
CMake Error at CMakeLists.txt:66 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Curren
t/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 15.06.2020 2:47:45.
    Project "...\build\CMakeFi
les\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Micros
oft\VC\v160\Microsoft.CppBuild.targets(387,5): error MSB8013: This project doesn
't contain the Configuration and Platform combination of Debug|Win32. [...build\CMakeFiles\3.17.20032601-MSVC
_2\VCTargetsPath.vcxproj]
    Done Building Project "...\libwebsockets
\build\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj" (default targets)
-- FAILED.

    Build FAILED.

    "...\build\CMakeFiles\3.17
.20032601-MSVC_2\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Micr
osoft\VC\v160\Microsoft.CppBuild.targets(387,5): error MSB8013: This project doe
sn't contain the Configuration and Platform combination of Debug|Win32. [...\libwebsockets\build\CMakeFiles\3.17.20032601-MS
VC_2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.21

  Exit code: 1`
So, could I expect that in some future will be update with the x86 configuration?

P.S. If I run compile command without the key -DCMAKE_GENERATOR_PLATFORM=x86 and then build command
I get a lot errors like 
`openssl-tls.c
../lws-genhash.h(85,18): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st' [...\build\lib\websockets.vcxproj]`
so, it's definitely comes from x64/x86 modules mismatch as was found in the topic
https://github.com/warmcat/libwebsockets/issues/1776

**Comment by lws-team** [comment]
I build lws in CI now for 64-bit using msvc (and mingw32 and 64).  Msvc is using the "community" edition of vc 19.  Eg currently

https://libwebsockets.org/sai/index.html?task=cd947f56df3afaac059b014ad109e8cffda0590aea5758ebacb8206c35825d61

I don't build 32-bit on msvc but plus or minus some type warnings it should work if 64-bit is working.

There are no problems with openssl in CI either... that sounds like you maybe didn't delete your build dir to force cmake to reassess openssl api availability. 

The other errors seem to go off the rails when it can't run msbuild.exe... the CI build runs that fine to manage the build. So I would check your PATH in that console session etc.  You don't mention this early, fatal error for 64 bit build...

**Comment by pecec** [comment]
Thank you for rapid answer. But I delete libwebsockets/build directory before running cmake. Also, I changed system variables by adding
OPENSSL_ROOT_DIR equals to  C:\Program Files (x86)\OpenSSL
Without that it was an error pointing that OPENSSL_ROOT_DIR is not set. After that command
`cmake .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="..\prebuilt-dll-2-9-1-release\include" -DLWS_EXT_PTHREAD_LIBRARIES="..\prebuilt-dll-2-9-1-release\lib\x86\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1`
runs without fatal errors, but successive run
cmake --build . --config DEBUG (RELEASE as well)
runs till the end without any fatal error, but with big number of errors like
`openssl-tls.c 
../lws-genhash.h(85,18): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st' [...\build\lib\websockets.vcxproj]` 
and no binaries built in the corresponding directories.

Then, after deleting the build directory, running
```
git clean -f
git stash push --include-untracked
git stash drop
```
the run of compile command with -DCMAKE_GENERATOR_PLATFORM=x86 option
`cmake .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="..\prebuilt-dll-2-9-1-release\include" -DLWS_EXT_PTHREAD_LIBRARIES="..\prebuilt-dll-2-9-1-release\lib\x86\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1 -DCMAKE_GENERATOR_PLATFORM=x86`
returns the fatal error
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Micros
oft\VC\v160\Microsoft.CppBuild.targets(387,5): error MSB8013: This project doesn
't contain the Configuration and Platform combination of Debug|Win32.
```
So, maybe one should check if the lws sources contain some information for building for x86 platform? But, running
`libwebsockets>findstr /S Win32 *.*`
gives a lot results, so it seems one should be able to build lws for Win32

I should check another option, I built and installed OpenSSL using Visual Studio 14, but now try to build lws using msvs 2019 (because now it supports some socket features from unix, and with the 14th version it seems unable to build lws). Now I try to rebuild OpenSSL using msvs 2019. Another option that it seems there is other openssl stuff is on my computer in MinGW/msys directory pointed by the path variable. OK I will get back here when make clear with my openssls...

**Comment by lws-team** [comment]
The point is the CI builds for 64 bit repeatably just fine.  You should be able to do the same by looking at the cmake line it uses in the link from before.

Your error about 'this project' seems to be about your vc project, not lws.

For openssl, I also built it in my CI and captured the results in a zip, see the top of this for the link

https://libwebsockets.org/sai/index.html?task=b67cae1ffa47875a9913c11f4fb3b031b575c1702369d6da4b5cd9a46d26a882

That's what the lws ci successfully links against.

**Comment by pecec** [comment]
OK, it seems in the cmake command one needed to specify not x86 but Win32, then it works, but with the same result as without the option -DCMAKE_GENERATOR_PLATFORM=Win32
"Works" means doesn't produce any fatal error. I still see a lots of  "error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'" on running
`cmake --build . --config DEBUG`

OK, I will try to build x64 version and if it's OK, get back to x86 one.

BTW The installed cmake is not used, now MSVS has its own:
`$ where cmake
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Common
Extensions\Microsoft\CMake\CMake\bin\cmake.exe`
before that I've got the problem "Visual Studio 16 2019 could not find any instance of Visual Studio." and could it solve only by reinstalling VS. People say that one need to make a system variable
VS160COMNTOOLS="c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"
Next time if this is happen, I will try to set the variable.

**Comment by lws-team** [comment]
I can build it in CI using an externally-installed CMake and find it builds with no errors or warnings on that toolchain.

> "error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'" on running

There's some general hints here about how to debug problems with the CMake config probing

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

but you should sanity-check what the cmake is saying about probing, eg, LWS_HAVE_HMAC_CTX_new, basically those errors come when the probing results are wrong.

**Comment by pecec** [comment]
I ran with x64 configuration an obtained the same error C2079
the probing in console says:
`-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found`
and where I could find some hints how to fix this?
P.S. It looks the openssl.exe binary in C:\Program Files\OpenSSL\bin is corrupted, there is some error on launching it)) I do this all on Windows 7, if it may be important notice...

**Comment by lws-team** [comment]
Take a look at the link I gave last time.  "Not found" means it didn't succed to build a test program using that api.  But there are many reasons such a test program may, eg, fail to link.  Follow what it suggests in the article.

I just test and document on win10.

**Comment by pecec** [comment]
Thank you for your assistance and patience))
It seems I specified wrong path to libpthread's binaries 🤦 :
With right path to it some x86 lws binaries are built now, but there are still some errors:
`  Building Custom Rule .../libwebsockets/mi
  nimal-examples/ws-server/minimal-ws-server-threads-smp/CMakeLists.txt
  minimal-ws-server.c
libpthreadGC2.a(dofkfs00036.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00039.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00040.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00047.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00083.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00053.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00052.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00054.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
libpthreadGC2.a(dofkfs00057.o) : error LNK2026: module unsafe for SAFESEH image
. [...\libwebsockets\build\minimal-examples
\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp.vcxp
roj]
...\libwebsockets\build\bin\Debug\lws-minim
al-ws-server-threads-smp.exe : fatal error LNK1281: Unable to generate SAFESEH
image. ...\libwebsockets\build\minimal-exa
mples\ws-server\minimal-ws-server-threads-smp\lws-minimal-ws-server-threads-smp
.vcxproj]`
Need to test them if they work. x86 openssl.exe meets some run-time error, not like missing some dlls.
Can lws work properly without this libpthreads?

**Comment by lws-team** [comment]
It disables building stuff that needs pthreads if not given.

>SAFESH image

It seems you are mixing and matching some ancient random binary libs, that's not a problem with lws or anything I can solve for you.

 > x86 openssl.exe meets some run-time error

I don't know what you think I should understand from that... it's not obviously anything to do with lws but more breakage on your side.

**Comment by pecec** [comment]
> I don't know what you think I should understand from that... it's not obviously anything to do with lws but more breakage on your side.

You can figure out that openssl.exe is built but doesn't work, only this for now.

I tried to run lws-minimal-ws-client and it fails:
`$ lws-minimal-ws-client -s wss://www.example.com
[2020/06/16 00:46:46:7937] U: LWS minimal ws client
[2020/06/16 00:46:46:8737] N: lws_client_connect_3_connect: lws_getaddrinfo46 fa
iled 11001
[2020/06/16 00:46:46:8737] E: CLIENT_CONNECTION_ERROR: ipv6 lws_getaddrinfo46 fa
iled
[2020/06/16 00:46:49:0837] N: lws_client_connect_3_connect: lws_getaddrinfo46 fa
iled 11001
[2020/06/16 00:46:49:0837] E: CLIENT_CONNECTION_ERROR: ipv6 lws_getaddrinfo46 fa
iled
[2020/06/16 00:46:53:6337] N: lws_client_connect_3_connect: lws_getaddrinfo46 fa
iled 11001
[2020/06/16 00:46:53:6337] E: CLIENT_CONNECTION_ERROR: ipv6 lws_getaddrinfo46 fa
iled
[2020/06/16 00:46:53:6337] E: connect_client: connection attempts exhausted
[2020/06/16 00:46:53:6437] U: Completed`
But if I run without specifying a host, it seems to be working fine:
`C:\Users\v.semenenko\Documents\msvs\git\libwebsockets\build\bin\Debug>lws-minima
l-ws-client
[2020/06/16 00:51:45:6762] U: LWS minimal ws client
[2020/06/16 00:51:46:3362] U: callback_minimal: established
[2020/06/16 00:51:46:3362] N:
[2020/06/16 00:51:46:3362] N: 0000: 30
       0
[2020/06/16 00:51:46:3362] N:
[2020/06/16 00:51:46:3762] N:
[2020/06/16 00:51:46:3862] N: 0000: 31
       1
[2020/06/16 00:51:46:3862] N:
[2020/06/16 00:51:46:4262] N:
[2020/06/16 00:51:46:4362] N: 0000: 32
       2
[2020/06/16 00:51:46:4362] N:
[2020/06/16 00:51:46:4762] N:
[2020/06/16 00:51:46:4862] N: 0000: 33
       3
[2020/06/16 00:51:46:4862] N:
[2020/06/16 00:51:46:5362] N:
[2020/06/16 00:51:46:5362] N: 0000: 34
       4
[2020/06/16 00:51:46:5362] N:
[2020/06/16 00:51:46:5862] N:
[2020/06/16 00:51:46:5862] N: 0000: 35
       5
[2020/06/16 00:51:46:5862] N:
[2020/06/16 00:51:46:6362] N:
[2020/06/16 00:51:46:6362] N: 0000: 36
       6
[2020/06/16 00:51:46:6362] N:
[2020/06/16 00:51:46:6762] U: Completed`
So, is the usage
`lws-minimal-ws-client -s wss://www.example.com`
correct? Where it could be the trouble?

**Comment by lws-team** [comment]
I don't need or want to know about your non-lws related problems.  The whole issue is on your side ane a waste of time for me.

Just give -s the server name undecorated.

**Comment by pecec** [comment]
> It seems you are mixing and matching some ancient random binary libs, that's not a problem with lws or anything I can solve for you.

Yes, I now run compile command
`$ cmake .. -G"Visual Studio 16" -DLWS_WITH_MINIMAL_EXAMPLES=1 -DCMAKE_GENERATOR_PLATFORM=Win32`
and after that link command `cmake --build . --config DEBUG`
runs without any error.

Concerning to libpthreads, I was confused by the words in the README.build-windows.md:
"""
## Required: pthreads

It's amazing but after all these years windows doesn't offer pthreads compatibility
itself.  Just like the many other missing POSIX bits like fork().

I downloaded the latest (2012) zip release of pthreads-win32 from here

ftp://sourceware.org/pub/pthreads-win32

Then I created a dir "C:\Program Files (x86)\pthreads", and copied the `dll`,
`include` and `lib` subdirs from the `prebuilt` folder in the zip there.

The cmake incantation to build against pthreads set up like that is

"""
## Required: pthreads

It's amazing but after all these years windows doesn't offer pthreads compatibility
itself.  Just like the many other missing POSIX bits like fork().

I downloaded the latest (2012) zip release of pthreads-win32 from here

ftp://sourceware.org/pub/pthreads-win32

Then I created a dir "C:\Program Files (x86)\pthreads", and copied the `dll`,
`include` and `lib` subdirs from the `prebuilt` folder in the zip there.

The cmake incantation to build against pthreads set up like that is

```
 $ cmake .. -DLWS_HAVE_PTHREAD_H=1 -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1
```
"""
I thought "required" means it's mandatory to build against it.
Thank you very much for your time!

**Comment by lws-team** [comment]
As I said it's required to use any option like threadpool that needs pthreads.

Building lws for Sai, which is why I went to the trouble of writing up the process, needs threadpool

https://warmcat.com/git/sai2/tree/READMEs/README-build-windows.md

Those instructions demonstrably work fine on win 10 if you don't get the paths wrong.  If something different for win 7 or C++, well I don't use either, how about you research what that is and contribute a patch describing how to handle it.
