### ISSUE TITLE
lws_display_state repeated definition

### ISSUE THREAD

**Issue by SHASHENp** [warmcat/libwebsockets#1950]
"lws-display.h"

typedef uint8_t lws_display_state;

enum lws_display_state {
	LWSDISPS_OFF, /* managed in display_state */
	LWSDISPS_AUTODIMMED,
	LWSDISPS_ACTIVE,
};

This is reported as an error in my program.
But in your example it is compiled correctly.why is that!!   (~_~;)

**Comment by lws-team** [comment]
I dunno... but current master has the code a bit different than you pasted

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-display.h#n56

might be worth making sure you have master from the last few days

**Comment by lws-team** [comment]
Oh... does it work is you just remove this from lws-display.h?

> typedef uint8_t lws_display_state;

**Comment by lws-team** [comment]
Well, I fixed it in master by removing the extra line from the original patch.  I dunno why nothing cared here... but... nothing cared on any platform.  If it still makes trouble let me know.

**Comment by SHASHENp** [comment]
thanks for your help
