### ISSUE TITLE
Visual Studio 2019 C++ compiler can't handle lws-display.h code

### ISSUE THREAD

**Issue by pecec** [warmcat/libwebsockets#1951]
I'm trying to compile some my code using lws and with recent update (previous one I did in autumn and it was compiled/built well) and have this errors:
`1>...\libwebsockets\lws-display.h(56,6): error C2371: 'lws_display_state': redefinition; different basic types
1>...\libwebsockets\lws-display.h(32): message : see declaration of 'lws_display_state'
1>...\libwebsockets\lws-display.h(56,6): error C2371: 'lws_display_state': redefinition; different basic types
1>...\libwebsockets\lws-display.h(32): message : see declaration of 'lws_display_state'`
They definitely come from the code
`typedef uint8_t lws_display_state;

/*
 * This is embedded in the actual display implementation object at the top,
 * so a pointer to this can be cast to a pointer to the implementation object
 * by any code that is specific to how it was implemented.
 */

/*some code is here*/

/*
 * This contains dynamic data related to display state
 */

enum lws_display_state {
	LWSDISPS_OFF, /* managed in display_state */
	LWSDISPS_AUTODIMMED,
	LWSDISPS_ACTIVE,
};`
where lws_display_state type is redefined. Could you please help me how to avoid this error? Maybe some preprocessor directive should be switched on, like NO_MANAGING_DISPLAY_STATE? One more thing, my code is C++ code, I hope libwebsockets can be used with it. I checked the project settings of minimal-ws-client and haven't found anything special there but "Compile as C Code (/TC)", so this instruction brakes my C++ code and I can apply it.
 UPD: Checked a plain C version of code - and it is compiled/built successfully and even works! So it seems the problem in C/C++ conflict. I hope someone could help me.

**Comment by SHASHENp** [comment]
The latest code has been deleted

**Comment by SHASHENp** [comment]
https://github.com/warmcat/libwebsockets/issues/1950

**Comment by pecec** [comment]
> 
> 
> #1950

Thank You! Honesly, I googled lws_display_state, but nothing was found, that's why I opened new issue)
