### ISSUE TITLE
lws_write usage

### ISSUE THREAD

**Issue by ljcNaruto** [warmcat/libwebsockets#1954]
Can "lws_write" be invoked out of " lws_callback_function " without "lws_callback_on_writable" call ?

**Comment by lws-team** [comment]
No.

For example, partial sends are handled by suppressing writeable callback until the unsent, buffered part completes its send in the background.  In http2 where connection multiplexing and tx credit exist, streams must wait until it's their turn to used the shared connection, and there's enough credit.  And most of all nonblocking sockets can't otherwise regulate how much you are sending into a connection that is only being consumed at a slower rate.  Blocking sockets disable the thread by blocking if the user code thinks it can just send whatever it wants.  Nonblocking sockets regulate by deferring when the user code is allowed to send cooperatively.

Just follow the rules about it and stuff will work well.

**Comment by ljcNaruto** [comment]
I have a frame deque , in  other thread , frames are pushed into it one by one, once one frame is pushed into it , then call "lws_callback_on_writable" , and in  "lws_callback_function" , can I use lws_write to send frames during iterating this frame deuqe  with reason "LWS_CALLBACK_SERVER_WRITABLE ", in other words , "lws_write" is called in a loop until frame deque is iterated completely ?

**Comment by lws-team** [comment]
You can send stuff 'in a loop' but

 - you must ask for a new writeable callback each time

 - you should only do one lws_write() when it comes (or none if when you get it you realize nothing to send actually)

 - if more to send, ask for another writeable callback

If many connections ongoing, this way each will send as fast as it can according to specific connection throughput.

**Comment by ljcNaruto** [comment]
just like code below 

in other thread, we write like this :

void pushFrame(unsigned char * data , unsigned int size)
{
     ...  // lock
    Frame frame;
   frame.frameData = data;
  frame.frameSize = size;
    frameQue,push_back(frame);

    /*here we call lws_callback_on_writable*/
    ...// unlock
}

int lwsCallback(lws * wsi,lws_callback_reasons reason, void *user,void * in,size_t len)
{
   switch(reason)
  {
     ...
    case LWS_CALLBACK_SERVER_WRITABLE:
          ...// lock
          for(int i = 0; i < frameQue.size(); i++)
         {
               unsigned char * frameData =  frameQue[i]->frameData;
              unsigned int frameSize = frameQue[i]->frameSize;

              int writeSize = lws_write(wsi,frameData + LWS_PRE,frameSize,LWS_WRITE_BINARY);

              // Do you mean we call lws_callback_on_writeable here ? ? ?
         }

        ...// unlock
          break;
     ...
  }
}

**Comment by ljcNaruto** [comment]
so , after lws_write , it is not allowed to call lws_write at once until a lws_callback_on_writable is called

**Comment by lws-team** [comment]
Yes...

```
If (still_stuff_in_queue)
   lws_callback_on_writable();
```

Eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-ring/protocol_lws_minimal.c#n223-227

**Comment by lws-team** [comment]
In older lws you would lose data that way.  In modern lws, v3.2+, you will waste heap storing it locally if trying to send it on a connection when the network stack not ready to accept it.

The basic concept is, do not genetate output until right at the moment it can be sent out (broadly, the receiver and intermediate network decides when that is).  You get the WRITEABLE callback when the kernel will accept new data, that's close enough.

**Comment by ljcNaruto** [comment]
I have read your demo https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-ring/protocol_lws_minimal.c#n223-227 , 

in your way ,get and send a frame and then call lws_callback_on_writable , and then get and send next frame when reaceive reason LWS_CALLBACK_SERVER_WRITABLE , but  won't it be very low efficient ?  Could I do as below : 

  for(int i = 0; i < frameQue.size(); i++)
  {
         unsigned char * frameData = frameQue[i]->frameData;
         unsigned int frameSize = frameQue[i]->frameSize;

          int writeSize = lws_write(wsi,frameData + LWS_PRE,frameSize,LWS_WRITE_BINARY);

          lws_callback_on_writable(wsi);  // this operation is inside of for loop
     }

**Comment by ljcNaruto** [comment]
in your demo ,  just one frame  is picked out every time , and then send it out , then call lws_callback_on_writable  to get next frame ... and so loop...,, won't it be a little low efficient ?

**Comment by lws-team** [comment]
Sigh... if you use blocking semantics the kernel will make your 'efficient' thread sleep when no more can be accepted for send.  You had to create a thread per connection just so it can be forced to sleep like that.  Very 'efficient' and scaleable... not.

Using nonblocking, the service thread can handle other events instead, and just defer the writeable event for connections that are not ready... so long as the event loop overhead is less than the rate the peer accepts packets, nonblocking is more efficient and scaleable.

Anyway, if you don't get it no worries just use another library.

**Comment by ljcNaruto** [comment]
I'm sorry first ,maybe  I'm just not very accustomed to use interface provided by your library ,  maybe I'm not standing on a designer's view to think about it , at all , I'm very grateful for your help , thank you very much !
