### ISSUE TITLE
NOTICE: time discontiguity, no more pings

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#1955]
I am using libwebsockets as a client, I need to send pings automatically to the server to check if connection is still up. But there is a difference with my client date and the server date, so I get this error:

NOTICE: time discontiguity: at old time 1592301670s, new time 1592301972s: +302s

It then stops sending pings to the server. Is there a way to avoid this issue? And continue sending pings despite the time differences. 
Thanks

**Comment by lws-team** [comment]
It's telling you your local system time changed underneath it, it's not comparing time with another system.

Use a later lws, it switched to using monotonic time at v3.2 IIRC, that problem, the code reporting it and everything around intermal scheduling has gone away or been rewritten since then.
