### ISSUE TITLE
LEJP does not parse negative values

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#1957]
The issue comes from this file: lib/misc/lejp.c

The line:

case LEJP_MP_VALUE:
                  if (c >= '0' && c <= '9') {

Should be changed to:

case LEJP_MP_VALUE:
                  if (c == '-' || (c >= '0' && c <= '9')) {

**Comment by lws-team** [comment]
Thanks for the fix... LEJP does do the parsing work for negative numbers, but you're right, it's filtering them out earlier.  Just letting it go on lets it pick up and handle them correctly as you say.

I added a patch for your fix on master and v4.0-stable.

**Comment by dev31337** [comment]
Yes I should have said "fails to parse" instead of "does not parse".

Just to let you there is also another possible bug, either it is intended and the documentation is wrong, either this is a bug and the documentation is right.

When you have a large string you get it by chunks of "LEJPCB_VAL_STR_CHUNK" size, and there is no terminating NULL to the string ctx->buf which is fine. 

But the documentation states otherwise and says that you should get (LEJPCB_VAL_STR_CHUNK - 1) size. (and probably a NULL at the end)

I will let you decide which one to fix either the code or the documentation :)

Documentation:
LEJPCB_VAL_STR_CHUNK: We parsed LEJP_STRING_CHUNK -1 bytes of string data in ctx->buf, which is as much as we can buffer, so we are spilling it. If all your strings are less than LEJP_STRING_CHUNK - 1 bytes, you will never see this callback.

**Comment by lws-team** [comment]
> Yes I should have said "fails to parse" instead of "does not parse".

Well, it was broken... it's fair to say whatever... I wanted to explain it's not an entire failure to address them but a smaller bug, otherwise it is not so simple to fix as this.

I think the doc doesn't need to be so precise... that might have been true when the docs were written but since we provide the length dynamically, no need for the user to know or care (or expect a NUL).  I'll fix it in master and push later.

**Comment by dev31337** [comment]
Personally I looked at the content of every item in the structure:

https://libwebsockets.org/lws-api-doc-master/html/structlejp__ctx.html

And I wasn't able to find one which reliably contains the real length of the content in ctx->buf.

Don't hesitate to point me to it :)

**Comment by lws-team** [comment]
`npos` is used for the length of what's being called-back about.

**Comment by dev31337** [comment]
From memory I looked at it and it was not always the case so I ignored it.

Thanks for the clarification though.
