### ISSUE TITLE
Unable to create websockets on Ubuntu 18.04

### ISSUE THREAD

**Issue by chrisdonovan1006** [warmcat/libwebsockets#1960]
Hey,

I'm having and issue setting up a mosquitto broker with WebSocket support.  I am running on a ubuntu 18.04 instance, I know that in the past I had websocket support working perfect.  Been a while since I setup a broker, any help would be great.

Opening ipv4 listen socket on port 1883.
Opening websockets listen socket on port 9001.
Initial logging level 255
Libwebsockets version: 2.0.3 unknown-build-hash
IPV6 not compiled in
libev support compiled in but disabled
libuv support compiled in but disabled
	LWS_DEF_HEADER_LEN    : 1024
	LWS_MAX_PROTOCOLS     : 5
	LWS_MAX_SMP           : 32
	SPEC_LATEST_SUPPORTED : 13
	sizeof (*info)        : 280
	SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
	default timeout (secs): 20
	Threads: 1 each 1024 fds
	mem: context:         71488 bytes (67392 ctx + (1 thr x 4096))
	mem: http hdr rsvd:   68224 bytes (1 thr x (1024 + 3240) x 16))
	mem: pollfd map:       8192
	mem: platform fd map:  8192 bytes
Compiled with OpenSSL support
SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
Creating Vhost 'default' port -115381264, 1 protocols
	interface lo vs ▒7▒▒U
	interface eth0 vs ▒7▒▒U
	interface lo vs ▒7▒▒U
	interface eth0 vs ▒7▒▒U
	interface lo vs ▒7▒▒U
	interface eth0 vs ▒7▒▒U
	Unable to find interface ▒7▒▒U
	Failed to create default vhost
Error: Unable to create websockets listener on port 9001.

**Comment by lws-team** [comment]
> Libwebsockets version: 2.0.3 unknown-build-hash
> Creating Vhost 'default' port -115381264, 1 protocols

I can only say about the lws part... the lws seems really old, and the garbage in the port and iface (the broken characters in the network interfaces) makes it look like either the context creation info not memset to 0 before it was used, or it was built against a different lws with different content creation info struct layout.

**Comment by chrisdonovan1006** [comment]
Thank for the quick reply I installed via the `sudo apt install libwebsockets-dev` command, should I build the latest version of the library, I think in the past I was using 2.0.2.

**Comment by lws-team** [comment]
Dunno... you will probably have to build current mosquitto and lws to solve it.

**Comment by chrisdonovan1006** [comment]
Okay thanks again.
