### ISSUE TITLE
Support Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by bdkjones** [warmcat/libwebsockets#1961]
I realize it was just announced, but for apps that depend on `libwebsockets` to be able to rebuild as Universal apps, they'll first need access to a Universal build of `libwebsockets` itself on macOS.

Because Libwebsockets is already cross-platform by design, I imagine this process won't be *too* awful? I'm unsure if you'll need a new version of CMake to target Apple's ARM64 platform or if existing ARM targets would suffice.

Because ARM Macs are about six months away from being in the wild and because libwebsockets is a blocker for rebuilding my own apps as Universal, I'm opening this issue to track progress and any complications that must be addressed to have `libwebsockets` running on ARM Macs. Thanks for your help!

**Comment by lws-team** [comment]
> libwebsockets is a blocker for rebuilding my own

Lws builds for ios already in CI, there should be nothing to do at aarch64 level.

For anything else needed... lws is foss.  Please build it on the platform you care about and contribute patches and / or details of how to put it in CI and I'll look at it.
