### ISSUE TITLE
How can I make user in callback shared by all wsi clients ? 

### ISSUE THREAD

**Issue by ljcNaruto** [warmcat/libwebsockets#1962]
here

int LWSCallback(lws* wsi, lws_callback_reasons reason, void* user, void* in, size_t len);

How can I get a same user pointer for all wsi clients ?

**Comment by lws-team** [comment]
That's self-contradictory, since user is a per-wsi thing.

If you just want a pointer passed in from outside, there are opaque pointers you can set and get in the context, vhost and each protocol, and you can get each of those from the wsi.
