### ISSUE TITLE
distinguish which listen port the client connect in the lws_protocols callback

### ISSUE THREAD

**Issue by zangyongcan** [warmcat/libwebsockets#1965]
I am using libwebsockets for writing a websocket server. I create multiple listening ports on the same host, and multiple clients connect to multiple listening ports. But how can I distinguish which listen port the client connect in the lws_protocols callback?
Thank you.

**Comment by lws-team** [comment]
You can get the vhost the wsi is bound to, and either compare the pointer to when you created a given vhost or get the name of the vhost.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h?h=master#n1018-1032
