### ISSUE TITLE
Seg fault trying to lws_spa_create()

### ISSUE THREAD

**Issue by gupta05** [warmcat/libwebsockets#1967]
Hi,
Using the examples I setup a http client and server. I am able to successfully parse what I append to url path on client in the server http_callback. Now I am trying to send a string data from client and looks like I can append it in the form. I don't really need multipart data but wasn't sure how to do without it so I am using it. I am getting segmentation fault when I am trying to create parser.  Would really appreciate any pointers to what I am missing or doing wrong.

Thanks,
Puja 

**Server code:**
struct pss {    struct lws_spa *spa; };
static const char * const param_names[] = {    "text",};
static int
callback_http(struct lws *wsi, enum lws_callback_reasons reason,
            void *user, void *in, size_t len)
{
    struct pss *pss = (struct pss *)user;
    uint8_t buf[LWS_SEND_BUFFER_PRE_PADDING + 1024], *start = &buf[LWS_SEND_BUFFER_PRE_PADDING],*end = &buf[sizeof(buf) - LWS_SEND_BUFFER_PRE_PADDING - 1];
    int n;
    char *requested_uri = (char *)in;
   switch (reason) {
  case LWS_CALLBACK_HTTP_BODY:
        printf("LWS_CALLBACK_HTTP_BODY\n");
        if(!pss->spa) {
            pss->spa = lws_spa_create(wsi, param_names, LWS_ARRAY_SIZE(param_names), 1024, NULL, NULL);
            printf("spa created \n");
            if(!pss->spa)
                return -1;
        }
        if (lws_spa_process(pss->spa, in, (int)len))
            return -1;
        break;

**Client code:**
static int
callback_http(struct lws *wsi, enum lws_callback_reasons reason,
          void *user, void *in, size_t len)
{
    struct pss *pss = (struct pss *)user;
    char buf[LWS_SEND_BUFFER_PRE_PADDING + 1024];
    char *start = &buf[LWS_SEND_BUFFER_PRE_PADDING];
    char *end = &buf[sizeof(buf) - LWS_SEND_BUFFER_PRE_PADDING -1];
char *data = "hello";
 case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
        printf("LWS_CALLBACK_CLIENT_HTTP_WRITEABLE\n");
        if (lws_http_is_redirected_to_get(wsi))
            break;
        switch (pss->body_part++) {
        case 0:
            printf("Case 0\n");
            if (lws_client_http_multipart(wsi, "text", NULL, NULL,&start,end))
                return -1;
            lws_strncpy(start,data,sizeof(data));
            n = LWS_WRITE_HTTP;
            break;
        case 1:
            printf("Case 1\n");
            if (lws_client_http_multipart(wsi, NULL, NULL, NULL,&start+sizeof(data),end))
                return -1;
            lws_client_http_body_pending(wsi, 0);
            n = LWS_WRITE_HTTP_FINAL;
            break;
        default:
            return 0;
        }

        lws_write(wsi, (uint8_t *)start, sizeof(data), n);
        if (n != LWS_WRITE_HTTP_FINAL)
            lws_callback_on_writable(wsi);

        break;

**Comment by lws-team** [comment]
Let's not do that... if you think there's a problem in lws please give me a little patch on an existing minimal example so I can, eg, get a backtrace and easily see what your patch does.

**Comment by gupta05** [comment]
Sorry I didn't mean there is a problem with library..I think I am missing something in how to send a string from http client to server...I tried to follow the post example. I get this error on server 
LWS_CALLBACK_HTTP_BODY
Segmentation fault (core dumped)

**Comment by lws-team** [comment]
Yeah... so where is the backtrace?  You just need to do some obvious steps debugging of your own code before asking me.

**Comment by gupta05** [comment]
Here is the backtrace,  I will debug it. Wanted to check if there was anything obviously wrong in my code.

#0  0x0000555555554ecd in callback_http ()
#1  0x00001555550fc4d3 in lws_read_h1 (wsi=0x55555575ebe0,
    buf=0x55555575922a "hello", len=8)
    at /scratch/workspace/libwebsockets/lib/roles/h1/ops-h1.c:162
#2  0x00001555550fcacb in lws_h1_server_socket_service (wsi=0x55555575ebe0,
    pollfd=0x55555575a4a8)
    at /scratch/workspace/libwebsockets/lib/roles/h1/ops-h1.c:417
#3  0x00001555550fcebc in rops_handle_POLLIN_h1 (pt=0x555555758e20,
    wsi=0x55555575ebe0, pollfd=0x55555575a4a8)
    at /scratch/workspace/libwebsockets/lib/roles/h1/ops-h1.c:641
#4  0x00001555550e75cf in lws_service_fd_tsi (context=0x555555758be0,
    pollfd=0x55555575a4a8, tsi=0)
    at /scratch/workspace/libwebsockets/lib/core-net/service.c:710
#5  0x00001555550d0c9a in _lws_plat_service_forced_tsi (
    context=0x555555758be0, tsi=0)
    at /scratch/workspace/libwebsockets/lib/plat/unix/unix-service.c:49
#6  0x00001555550d1106 in _lws_plat_service_tsi (context=0x555555758be0,
    timeout_ms=2000000000, tsi=0)
    at /scratch/workspace/libwebsockets/lib/plat/unix/unix-service.c:207
#7  0x00001555550d1183 in lws_plat_service (context=0x555555758be0,
    timeout_ms=0)
    at /scratch/workspace/libwebsockets/lib/plat/unix/unix-service.c:221
#8  0x00001555550e775e in lws_service (context=0x555555758be0, timeout_ms=0)
    at /scratch/workspace/libwebsockets/lib/core-net/service.c:777
#9  0x0000555555555259 in main ()

**Comment by gupta05** [comment]
Not sure what I am doing wrong trying to create parser but I see that when I get LWS_CALLBACK_HTTP_BODY, data I passed from client is present void *in of the callback. Is it fine if I don't create parser since I don't need one and just use the string I passed directly?

**Comment by lws-team** [comment]
Sure, it's not that trivial to parse properly though.  But why would it be a good idea to add more of your code that seems broken and still not really understand how to debug it?  You should stop and learn some debugging skills.

> #0 0x0000555555554e78 in callback_http ()

So it's crashing in your code.  Build your code for debug (-g for gcc/clang or -DCMAKE_BUILD_TYPE=DEBUG if cmake etc) so you can see where.  Or keep stumbling around in the dark trying to use github (and my time...) to debug your own code.

**Comment by gupta05** [comment]
Thanks for the library. I am able to get it running.

**Comment by lws-team** [comment]
Great.
