### ISSUE TITLE
Example minimal-ws-client can not work

### ISSUE THREAD

**Issue by dream0310** [warmcat/libwebsockets#1972]
Hello,
    When I try to test the minimal-ws-client, it build error. the branch is v4.0-stable.
    minimal-examples/ws-client/minimal-ws-client. 
    after I did:  cmake . && make
   There are error, the error log as below:
![image](https://user-images.githubusercontent.com/54057201/87284695-3d3d9b00-c529-11ea-9954-669eaebe6b90.png)

**Comment by lws-team** [comment]
`sudo make install`?

**Comment by dream0310** [comment]
It works after i did sudo make install. Thanks
