### ISSUE TITLE
WS connection termination from LWS_CALLBACK_ESTABLISHED handler

### ISSUE THREAD

**Issue by Mirraz** [warmcat/libwebsockets#1973]
In my callback function (lws_callback_function) on reason=LWS_CALLBACK_ESTABLISHED I check Cookie headers and if check fails I immediately return -1, next I initialize some extra data in user struct and return 0. And I expect than if I returned -1 on reason=LWS_CALLBACK_ESTABLISHED than this ws connection will be closed and my callback will not be called with reason=LWS_CALLBACK_RECEIVE (or LWS_CALLBACK_SERVER_WRITEABLE). But actually it is called with reason=LWS_CALLBACK_RECEIVE and I get incompletely initialized user struct.
What should I do to terminate ws connection from LWS_CALLBACK_ESTABLISHED handler?

**Comment by lws-team** [comment]
> And I expect than if I returned -1 on reason=LWS_CALLBACK_ESTABLISHED than this ws connection will be closed 

Yes you are right... it's broken after some refactor a while back putting it in its own function.

I pushed a patch on master and v4.0-stable making sure it checks the return from the function that handles that properly.
