### ISSUE TITLE
Issue about callback event LWS_CALLBACK_EVENT_WAIT_CANCELLED

### ISSUE THREAD

**Issue by lonelybeansprouts** [warmcat/libwebsockets#1981]
I received the event LWS_CALLBACK_EVENT_WAIT_CANCELLED, but can't get any thing that defined by myself, so i can't do any thing by the wsi.

**Comment by lws-team** [comment]
Some events are not related to any specific wsi... WAIT_CANCELLED is one of them.  To keep up appearances, it provides a fake wsi with the context at least, so you can get the context pointer from it.  But WAIT_CANCELLED is not bound to any wsi, it's an event that happened to the event loop itself.  You shouldn't look for anything in the wsi that came with the event... there's nothing there.

**Comment by lonelybeansprouts** [comment]
Ok, thanks for the quick reply!!
