### ISSUE TITLE
LWS:lws_client_handshake: got bad HTTP response '400'

### ISSUE THREAD

**Issue by dream0310** [warmcat/libwebsockets#1982]
Recently i update libwebsocket to 4.0.0 from 1.7.9 in my project, but got the error "LWS:lws_client_handshake: got bad HTTP response '400'"
I set clientInfo.ssl_connection=2 for wss will occur this 400 error.

Then i tried to set the 
clientInfo.ssl_connection= LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK | LCCSCF_ALLOW_EXPIRED;
The 400 error gone, but get the LWS_CALLBACK_CLIENT_ERROR.

Can you give me some advice.
Thanks.

**Comment by lws-team** [comment]
First advice is .0 release quality depends on users testing it, eg, you testing master at the time before 4.0.0 release.  While thete's not enough user participation in testing, in any project, avoid .0 release when later available, I think it's up to v4.0.21 or so.

Second advice is the `in` parameter should contain a string if CONNECTION_ERROR, it will give a better clue.

Third advice is look at the minimal examples, they show the modern way to do things and you can test them as they are too.  Aligning your old code to a minimal example that works should result in new code that works.

**Comment by dream0310** [comment]
Thanks for your advice. I just set all the configuration as the same with minimal examples, it works now.

**Comment by lws-team** [comment]
Great.
