### ISSUE TITLE
LWS built with IPV6 support on Windows: When connecting from the client websocket to a domain name with only an IPv4 address, the connection fails.

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#1983]
Setup: libwebsockets built with  LWS_IPV6 = ON on Windows.
Problem: when connecting from the client websocket to a domain name with only an IPv4 address, the connection fails. This is what happens:
- lws_client_connect_2 is eventually called
- it calls lws_getaddrinfo46, which in turn calls getaddrinfo with hints.ai_family = AF_INET6 and hints.ai_flags = AI_V4MAPPED;
- getaddrinfo returns a V4 mapped address, for example ::ffff:127.0.0.1 (or whatever; using 127.0.0.1 as an example), of family AF_INET6
- lws_client_connect_2 then creates a socket( AF_INET6, ... )
- and attempts to connect to the address ::ffff:127.0.0.1
- this fails, because an AF_INET6 socket created on Windows is V6 only

The problem is that, even though RFC 3492 says that the default for IPV6_V6ONLY socket option should be off, Windows sets the default as enabled.
RFC link: https://tools.ietf.org/html/rfc3493#page-22
MSDN doc link: https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options
lws_getaddrinfo46 explicitly asks for V4 mapped addresses, but a socket created on Windows is unable to use them, unless it is explicitly configured using setsockopt to set IPV6_V6ONLY to false.
There are several possible ways to fix this, but the suggested code simply calls setsockopt if "ipv6only" is false after the socket is created, and it does so only on windows (to minimize potential problems on other platforms, which I can't test).

Change added to \lib\roles\http\client\client-handshake.c (ln 624) to address this issue:
```
#if defined(LWS_WITH_IPV6) && defined(WIN32)<br>
                /* The default for IPV6_V6ONLY on Windows is enabled, even though RFC 3493 says it should be disabled. */ 
                if (!ipv6only) {
                        int value = 0; 
                        if (setsockopt(wsi->desc.sockfd, IPPROTO_IPV6, IPV6_V6ONLY, 
                           (const void*)&value, sizeof(value)) < 0) { \
                                lwsl_err("Failed to set wsi socket option IPV6_V6ONLY to 0\n"); 
                                compatible_close(wsi->desc.sockfd); \
                                cce = "set socket opts IPV6_V6ONLY to 0 failed"; 
                                goto oom4; 
                         } 
                } 
#endif 
```

 Please let us know whether this might introduce other unexpected behaviors or issues.

**Comment by lws-team** [comment]
Thanks for the suggested code.

The code for this is very different on master than the previous release... it's smarter now about getting a mixture of ipv4 and ipv6 DNS results and making the right kind of socket for each, and trying each in turn before failing out.

Can you maybe eyeball the code on master around

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/client/client-handshake.c?h=master#n545-606

and see if that already addresses your issue?

**Comment by jzer0** [comment]
Sorry for the delay, was able to confirm this is working as expected with 4.0.  Thanks so much, closing this issue!
