### ISSUE TITLE
pwsi, userdata, opaque_user_data

### ISSUE THREAD

**Issue by parihaaraka** [warmcat/libwebsockets#1984]
Hello. Could you please explain an idea of these fields within `lws_client_connect_info`? I've read the comments but they look excessive. In `minimal-http-client-multi.c` you use `opaque_user_data`, making `pwsi` unnecessary (because `wsi*` is in the callback's arguments). And how `userdata` and `opaque_user_data` are intended to be used being both accessible?
Thank you.

**Comment by lws-team** [comment]
> I've read the comments but they look excessive.

If you personally don't need these pieces, you don't have to use them.  But there are so many users of lws doing so many different things, you're being a bit brave pronouncing that they are 'excessive'.

> opaque_user_data

This is often used for, eg, pointer to C++ object related to the wsi in user code.

> pwsi

`*pwsi` is set before exit from `lws_client_connect_via_info()`, so you can know the `wsi` inside callbacks that happen as part of the connection process.  You may be, eg, making a client connection as part of a proxying action, that is you may be binding the client connection to another connection, the wsi in the user callbacks that may be coming may be this other wsi, and you may need access to the client wsi there.

> userdata

For server connections, lws handles accepting new incoming connections randomly, and allocates this additional space for the user code's protocol handler to use for wsi-specific data.  If it has no meaning for you, you can set the size to 0 in the struct lws_protocols.  For client connection it's the same, per-wsi user data associated with the protocol handler.
