### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by 8vasu** [warmcat/libwebsockets#1987]
Certain documentation entries are currently unpopulated.

Example: https://libwebsockets.org/lws-api-doc-master/html/group__uv.html

I am not sure if this is by design.

Thank you.

**Comment by lws-team** [comment]
Unfortunately doxygen seems to be the best choice but last time I looked wasn't undergoing much development.  There were a few intractable issues like no search function without PHP IIRC and mixed scripts and html that's incompatible with modern CSP server.  So there will be some rough edges.

The related comment is this in include/libwebsockets/lws-service.h, it just doesn't generate any doxygen footprint by the look of it.

```
/*! \defgroup uv libuv helpers
 *
 * ##libuv helpers
 *
 * APIs specific to libuv event loop itegration
 */
///@{
#ifdef LWS_WITH_LIBUV
/*
 * Any direct libuv allocations in lws protocol handlers must participate in the
 * lws reference counting scheme.  Two apis are provided:
 *
 * - lws_libuv_static_refcount_add(handle, context) to mark the handle with
 *  a pointer to the context and increment the global uv object counter
 *
 * - lws_libuv_static_refcount_del() which should be used as the close callback
 *   for your own libuv objects declared in the protocol scope.
 *
 * Using the apis allows lws to detach itself from a libuv loop completely
 * cleanly and at the moment all of its libuv objects have completed close.
 */

LWS_VISIBLE LWS_EXTERN uv_loop_t *
lws_uv_getloop(struct lws_context *context, int tsi);

LWS_VISIBLE LWS_EXTERN void
lws_libuv_static_refcount_add(uv_handle_t *, struct lws_context *context);

LWS_VISIBLE LWS_EXTERN void
lws_libuv_static_refcount_del(uv_handle_t *);

#endif /* LWS_WITH_LIBUV */
```

These are definitely off the beaten track.

**Comment by 8vasu** [comment]
I understand. Unfortunately, I am not qualified to comment on the topic of documentation generators.

While online documentation makes the process straightforward, it is not much harder to discover api from the minimal examples; I figured out the libuv-specific api eventually. Thanks!
