### ISSUE TITLE
Upgrading libwebsockets 1.3 version to 3.2.3 version. Would it be backward compatible ?

### ISSUE THREAD

**Issue by Rajasekhar-topgear** [warmcat/libwebsockets#1988]
Hi Experts,

            I am new to libwebsockets.
 
            Currently some of our platforms using libwebsockets 1.3 version (pretty old version).  I am trying to compile 3.2.3 version. Could you please let me know if libwebsockets are backward compatible. Because filenames got changed and function names also got changed. For instance "handshake.c" in version 1.3 is not available in version 3.2.3 and functions in "handshake.c" is also not available in version 3.2.3.

          Please let me know if I can upgrade to 3.2.3, would it be backward compatible.

**Comment by lws-team** [comment]
> libwebsockets 1.3 version (pretty old version).

Yeah that is like 6+ years old.

> libwebsockets are backward compatible. Because filenames got changed and function names also got changed.

Generally it's backwards-compatible at api level.  There was an api naming rationalization back then where original apis that were called `libwebsockets_...` all became `lws_...`.

No growing project is going to retain the same internal filesystem layout over the years.  Lws has been cleaned and refactored many times to keep the code maintainable and that has involved new directories and code moving around.... all of that is just lws private business you shouldn't make any dependencies on.

What I'd suggest is if the build integration in your project is a mess, clean that up by treating lws as a library that you build separately, using cmake toolchain file arrangements if it's cross, and produce a `.a` or `.so` that you link against in your project.  Then you no longer care about what files are where inside lws and can configure the build using cmake options cleanly.

Then look at the minimal examples https://libwebsockets.org/git/libwebsockets/tree/minimal-examples to see the recommended, modern way to use lws that you can build and test standalone, then use to upgrade your old stuff.  There are cmake cross toolchain examples in ./contrib

**Comment by Rajasekhar-topgear** [comment]
Thanks for the explanation.
