### ISSUE TITLE
How to skip hostname verification from server for wss

### ISSUE THREAD

**Issue by CVVDN-S** [warmcat/libwebsockets#1990]
Hi, I'm trying wss server support with the help of libwebsocket with self signed certificate. These are the configurations done at server side.

if(use_ssl == 1) {
                sprintf(cert_path, "/system/bin/server_cus_cer.cer");
                sprintf(key_path, "/system/bin/server_cus_key.key");
                info.ssl_cert_filepath = cert_path;
                info.ssl_private_key_filepath = key_path;
                info.port = 443;
                info.ssl_cipher_list = NULL;
                info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;
                info.options |= LWS_SERVER_OPTION_VALIDATE_UTF8;
                info.options |= LWS_SERVER_OPTION_PEER_CERT_NOT_REQUIRED;
        }
It works good with firefox, with any ssl certificates. But in IE **Network Error 12038, The host name in the certificate is invalid or does not match** seems to appear since my device have static ips which can change according to user.
If an static ip is used for Common Name while certificate generation then it will work at first and if I change the IP, the above said error is seen.

I tried the following methods:
1.tried to disable the option in IE tools, warn about the hostname mismatch
2.tried to generate wildcard certificates still no hope

Is there any options available that need to be added in Server for this error to be rectified?

**Comment by lws-team** [comment]
I'm not sure there's any problem with lws here.  I just hands out whatever cert you give it.  If the CN on the cert does not match the hostname used by the client to reach the server, the cert should be rejected.

**Comment by lws-team** [comment]
Hm... in addition to the CN, on newer certs you're supposed to put server names in a "subjectAltName" / SAN field.  I have no idea if it's related but as I say, lws doesn't get involved in any of this just passes on what you gave it.
