### ISSUE TITLE
link error (Windows) when trying to use lws_genhmac_* functions

### ISSUE THREAD

**Issue by pecec** [warmcat/libwebsockets#1995]
Hello!

I'm trying to use the routines from lws_genhash.h file and obtain the errors:

```
1>main.obj : error LNK2019: unresolved external symbol __imp__lws_genhmac_size referenced in function "public: void __thiscall xxx
1>main.obj : error LNK2019: unresolved external symbol __imp__lws_genhmac_init referenced in function "public: void __thiscall xxx
1>main.obj : error LNK2019: unresolved external symbol __imp__lws_genhmac_update referenced in function "public: void __thiscall xxx
1>main.obj : error LNK2019: unresolved external symbol __imp__lws_genhmac_destroy referenced in function "public: void __thiscall xxx
```

I watched in notepad++ websockets.lib and haven't found there the *genhmac* symbols exported. So, how could I build the lib with them?

**Comment by lws-team** [comment]
If you get curious about how to enable things for build, grep for the filename they live in.  To get built, they must be mentioned in a `CMakeLists.txt` file, and in there you can see what their build is conditional on easily

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/CMakeLists.txt#n141

**Comment by pecec** [comment]
Yes, I'm curious how to use these functions lws_genhmac_* in some more beautiful way than copy-pasting them into my project. But I understand that it might be not very good for the project to export them in the lws lib. Who knows, maybe you will consider such an option in future.

**Comment by lws-team** [comment]
I did answer it... the link shows to give `-DLWS_WITH_GENCRYPTO=1` at cmake to enable them.  They are then exported.

**Comment by pecec** [comment]
Now got it. Thank you! Sorry, I'm not very familiar with linux make files. 5 years ago I've written a make file for compilation of a project with dozens of files in different modes (release and debug) and writing binaries to different directories, but now I still don't know that language, I just google a lot for successful using it)) I hope you haven't wasted your time answering my question, and it will help not only me.
