### ISSUE TITLE
UNIX socket HTTP server URI retrieval

### ISSUE THREAD

**Issue by BeatIdo** [warmcat/libwebsockets#1996]
Hi,
It seems I cannot manage to retrieve URI in LWS HTTP server while reading "void* in" parameter in LWS_CALLBACK_HTTP callback.
I just get "/" instead of "/myrui"
Here is the curl command I use to test.

```
curl -X GET --unix-socket /tmp/MyUnixSocket http://myuri
```

Here is the context I use to configrue LWS server. Did I forgot something ? It worked well until I switched from TCP to UNIX socket.

```
struct lws_context_creation_info context_info;
memset(&context_info, 0, sizeof context_info);
context_info.protocols = protocols;
// set unix socket :
context_info.iface = "/tmp/MyUnixSocket";
context_info.options = LWS_SERVER_OPTION_UNIX_SOCK;
```

Also, I compiled LWS without SSL using following flags: -DLWS_WITH_SSL=OFF -DLWS_HAVE_LIBCAP=OFF -DLWS_UNIX_SOCK=ON

Regards.

**Comment by lws-team** [comment]
The first part of the uri after the protocol is the host, like http://warmcat.com.  What's passed in with the callback is the url path on the host.  `http://myuri` refers to / on the host `myuri`.

**Comment by BeatIdo** [comment]
I can retrieve again /myuri if I pass http://anything/myuri to curl but not if I pass http:///myuri. Is it the expected behavior ?
Thanks for your previous wuick answer.

**Comment by lws-team** [comment]
I guess so, I never tested it with an empty host.  It's not wrong to have, eg, http://localhost/myuri for unix domain.

**Comment by BeatIdo** [comment]
You were faster than myself I shouldn't have edited my previous comment ^^
How may I retrieve the host name from LWS_CALLBACK_HTTP ? That would be hostname when sending http://hostname/ request.
Why is it different between UNIX and TCP sockets ? I would read /hostname in LWS_CALLBACK_HTTP in that case.

**Comment by lws-team** [comment]
> Why is it different between UNIX and TCP sockets ? I would read /hostname in LWS_CALLBACK_HTTP in that case.

Nope... what you provided as the path is given in `in` for both cases.  You can check with tcpdump and see what curl is sending, it should only be like `GET /myuri http/1.1` and that's what is provided at the callback.
