### ISSUE TITLE
[question] How to overcome lws_return_http_status 510 bytes limitation ?

### ISSUE THREAD

**Issue by BeatIdo** [warmcat/libwebsockets#1997]
I'm using lws_return_http_status to answer simple HTTP GET request.

It works perfectly until body size makes frame bigger than 510 bytes.

What would be the simplest way to overcome lws_return_http_status hard-coded 510 bytes frame size limit ?

https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/header.c#L424

**Comment by lws-team** [comment]
It's just a helper to simplify producing dumb replies.

If you need to return something bigger or more complex, you can do it yourself, eg, referencing how that helper does it, but allow multiple writeable callbacks to incrementally send a large body.

**Comment by BeatIdo** [comment]
Thanks I'm trying to use lws_write_http now.
I added required LWS_PRE space in my buffer before payload but curl complains receiving HTTP/0.9.

**Comment by lws-team** [comment]
> Thanks I'm trying to use lws_write_http now.

If the helper works, clearly trying to reproduce the helper on your side is not quite the same, just align it to what the helper actually does and it must work the same as the helper did.  No code, no logs, no packet dumps.... only you can fix what you have broken on your side.

**Comment by BeatIdo** [comment]
Indeed. It was just a problem on client side ... curl is less explicit than netcat or socat ...
Is there a better place/forum to be able to discuss with you and just get some hints to use LWS ?

**Comment by lws-team** [comment]
If we're getting paid by the same people, we can discuss as much as you need, no problem.  If you are generous with your time sending patches I will match your time helping you, if it's a problem in lws I will try to solve it, otherwise... there are the minimal examples.

**Comment by BeatIdo** [comment]
Fair enough :)
