### ISSUE TITLE
Error  while building Libwebsocket for QNX 6.5.0

### ISSUE THREAD

**Issue by SCRockz** [warmcat/libwebsockets#1998]
I am trying to build the libwebsocket for QNX 6.5.0 . 
I am getting below error while building .

Scanning dependencies of target GENHDR
[  0%] Creating build include dir
[  0%] Built target GENHDR
Scanning dependencies of target websockets_shared
[  1%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o
cc1: error: unrecognized command line option "-pthread"
cc: /opt/qnx650/host/linux/x86/usr/lib/gcc/arm-unknown-nto-qnx6.5.0eabi/4.4.2/cc1 error 1
lib/CMakeFiles/websockets_shared.dir/build.make:82: recipe for target 'lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o' failed
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o] Error 1
make[2]: *** Deleting file 'lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o'
CMakeFiles/Makefile2:1371: recipe for target 'lib/CMakeFiles/websockets_shared.dir/all' failed
make[1]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

**Additional Details** 
I am using the openssl 1.1.1g version.
From the CMakeCache.txt, I can confirm that ,all the openssl headers and library paths are properly identified .
On analyzing on the CMakeError.log,  pthread flag is not recognized due to that the cmake is not identifying openssl headers and functions.
[CMakeError.log](https://github.com/warmcat/libwebsockets/files/5031494/CMakeError.log)

In Qnx ,the pthread library is usually included automatically. I have edited the CMakelist.txt , to remove the -pthread flag ,Now the headers are identified  but the opessl functions are not .During the build, I got below error .

[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
In file included from /home/libwebsocket_qnx/libwebsockets-master/include/libwebsockets.h:600,
                 from /home/libwebsocket_qnx/libwebsockets-master/lib/core/private-lib-core.h:135,
                 from /home/libwebsocket_qnx/libwebsockets-master/lib/core/alloc.c:25:
/home/libwebsocket_qnx/libwebsockets-master/include/libwebsockets/lws-genhash.h:80: error: field 'ctx' has incomplete type
cc: /opt/qnx650/host/linux/x86/usr/lib/gcc/arm-unknown-nto-qnx6.5.0eabi/4.4.2/cc1 error 1
CMakeFiles/websockets.dir/build.make:82: recipe for target 'CMakeFiles/websockets.dir/lib/core/alloc.c.o' failed
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
CMakeFiles/Makefile2:998: recipe for target 'CMakeFiles/websockets.dir/all' failed
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

[CMakeError_withoutPthread.log](https://github.com/warmcat/libwebsockets/files/5031552/CMakeError_withoutPthread.log)

Command used to Build 
cmake  -DLWS_WITH_HTTP2=1 -DLWS_WITH_SHARED=1 -DCMAKE_TOOLCHAIN_FILE=qnx.cmake libwebsockets-master

It will be very helpful, If somebody can look it to the issue. 

Regards
SC

**Comment by lws-team** [comment]
> No rule to make target '/opt/qnx650/target/qnx6/armle-v7/usr/lib/libcrypto.so.1

So does this exist?

You're building cross on a proprietary OS nobody randomly has, you are using a toolchain file you're not sharing, there's no cmake cmdline options listed, you fixed a problem but don't provide a diff or patch.  So there are some missing ways you also can be "helpful".

Building cross is not that trivial when it comes to openssl, amongst the usual pitfalls you must take a lot of care that you do not accidentally provide the cross-builder's openssl headers if it has them, ie in the toolchain file

```
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
