### ISSUE TITLE
[question] LWS_CALLBACK_FILTER_NETWORK_CONNECTION socket descriptor

### ISSUE THREAD

**Issue by BeatIdo** [warmcat/libwebsockets#1999]
LWS_CALLBACK_FILTER_NETWORK_CONNECTION callback event is documented to contain socket's descriptor inside in parameter typed void*.
What cast should be performed to retrieve socket descriptor ? int32_t* ? char* ? Something else ?

**Comment by lws-team** [comment]
You can look at the code

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/listen/ops-listen.c#n130

```
(void *)(lws_intptr_t)accept_fd
```

`accept_fd` is a `lws_sockfd_type`, it's platform-dependent... on most platforms it's an int, but it may be a handle.

The casting is carefully chosen to pass up to `sizeof(void *)` bytes of int, or the full `void *` if it's a handle.

You must cast it back to the platform's sockfd type, for int `(int)(lws_intptr_t)in` or for a handle `(thehandle_t)in`.
