### ISSUE TITLE
Build error with wolfSSL

### ISSUE THREAD

**Issue by tmael** [warmcat/libwebsockets#2000]
Hello,

I'm running into a build error with wolfSSL and I wanted to confirm if there is a known missing piece since I found the following comments in libwebsockets/lib/tls/CMakeLists.txt:
		# Use wolfSSL as OpenSSL replacement.
		# TODO: Add a find_package command for this also.

I'm not too familiar with cmake but I did a bit digging. 

It appears that the cmake build options are not being propagated into libwebsockets/lib/tls/CMakeLists.txt  and the assignments of the following build variables don't seem to be working. 

USE_WOLFSSL
WOLFSSL_INCLUDE_DIRS
WOLFSSL_LIBRARIES

Here's a workaround cmake build options that works: 

cmake -DUSE_WOLFSSL=1 -DLWS_WITH_WOLFSSL=1 -DLWS_WOLFSSL_INCLUDE_DIRS=/tmp/install-dir/include -DLWS_WOLFSSL_LIBRARIES=/tmp/install-dir/lib/libwolfssl.so   -DWOLFSSL_INCLUDE_DIRS=/tmp/install-dir/include -DWOLFSSL_LIBRARIES=/tmp/install-dir/lib/libwolfssl.so -DCMAKE_INSTALL_PREFIX:PATH=/tmp/install-dir .. && make install

What am I missing? 

Steps to reproduce:

git clone https://github.com/wolfSSL/wolfssl.git   
cd wolfssl && ./autogen.sh && ./configure --enable-libwebsockets CFLAGS=-DHAVE_EX_DATA --prefix=/tmp/install-dir
make install

git clone https://github.com/warmcat/libwebsockets.git
cd libwebsockets && mkdir build && cd build && cmake -DLWS_WITH_WOLFSSL=1 -DLWS_WOLFSSL_INCLUDE_DIRS=/tmp/install-dir/include -DLWS_WOLFSSL_LIBRARIES=/tmp/install-dir/lib/libwolfssl.so  -DCMAKE_INSTALL_PREFIX:PATH=/tmp/install-dir .. && make install

In file included from /home/tesfa/junk/junk2/junk3/wolfssl/libwebsockets/include/libwebsockets.h:598:0,
                 from /home/tesfa/junk/junk2/junk3/wolfssl/libwebsockets/lib/core/./private-lib-core.h:140,
                 from /home/tesfa/junk/junk2/junk3/wolfssl/libwebsockets/lib/plat/unix/unix-caps.c:28:
/home/tesfa/junk/junk2/junk3/wolfssl/libwebsockets/include/libwebsockets/lws-genhash.h:85:18: error: field ‘ctx’ has incomplete type
         HMAC_CTX ctx;
                  ^~~
lib/CMakeFiles/websockets_shared.dir/build.make:62: recipe for target 'lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o' failed
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o] Error 1
CMakeFiles/Makefile2:1070: recipe for target 'lib/CMakeFiles/websockets_shared.dir/all' failed
make[1]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lws-team** [comment]
Please try current master, it has some patches to solve these issues and has wolfssl build added to CI.

**Comment by tmael** [comment]
Hi Andy,

Thanks but I'm still seeing the same build error with the current master. 
Is your wolfSSL CI build available for a review? 

To get a succesful build, I had to set the following cmake options:
-DLWS_WITHOUT_EXTENSIONS=0
-DUSE_WOLFSSL=1 
-DWOLFSSL_INCLUDE_DIRS=/tmp/install-dir/include 
-DWOLFSSL_LIBRARIES=/tmp/install-dir/lib/libwolfssl.so 

In addition to these default options:
-DLWS_WITH_WOLFSSL=1 
-DLWS_WOLFSSL_INCLUDE_DIRS=/tmp/install-dir/include 
-DLWS_WOLFSSL_LIBRARIES=/tmp/install-dir/lib/libwolfssl.so
-DCMAKE_INSTALL_PREFIX:PATH=/tmp/install-dir 

I shouldn't have to add the first set of options. Please let me know. 

Thanks,
Tesfa

**Comment by lws-team** [comment]
You can see the CI build here atm

https://libwebsockets.org/sai/index.html?task=957af13319c799b6d1a8de7f7b1319f69ab17a40e4afdff86ca2c0ef60e50dd4

I built wolfssl separately and installed it in `/usr/local`, then it builds against it with `cmake .. -DLWS_WITH_WOLFSSL=1 -DLWS_WOLFSSL_INCLUDE_DIRS=/usr/local/include -DLWS_WOLFSSL_LIBRARIES=/usr/local/lib/libwolfssl.so`

**Comment by lws-team** [comment]
> I'm still seeing the same build error 

If you change your CMakeLists.txt which is effectively what's happening with fetching current master, you should delete your CMakeCache.txt to force it to rediscover things... if that doesn't help, then have a look in `./build/CMakeFiles/CMakeError.log` for HMAC (it's appended to, so the last instance, or delete it and CMakeCache.txt and redo the cmake) and see what error it felt it met there,

**Comment by tmael** [comment]
Thanks Andy!! The issue is fixed now.
