### ISSUE TITLE
Question: how to read text (json) data properly from websocket?

### ISSUE THREAD

**Issue by georgii-ivanov** [warmcat/libwebsockets#2004]
I have asked this question on stackoverflow but nobody answered. (link: https://stackoverflow.com/questions/63368809/libwesockets-how-to-read-text-json-data-properly-from-websocket)

I have such websocket implementation and it worked before but now it doesn't because I upgraded library version.

```
	int Handle(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
		switch( reason ) {
			case LWS_CALLBACK_CLOSED: {
				lwsl_notice("Client Disconnected\n");
				break;
			}
			case LWS_CALLBACK_ESTABLISHED: {
				lwsl_notice("Client Connected\n");
				break;
			}
			case LWS_CALLBACK_RECEIVE: {
				lwsl_notice("Message: %s\n", in);
				break;
			}
			default:
				break;
		}

		return 0;
	}

	static struct lws_protocols protocols[] =
	{
		{
			"server",
			Handle,
			sizeof(struct Session),
			LWS_MESSAGE_CHUNK_SIZE,
		},
		{ NULL, NULL, 0, 0 }
	};

	int Start() {
		struct lws_context_creation_info info;
		memset( &info, 0, sizeof(info) );

		info.port = 3018;
		info.protocols = protocols;
		info.gid = -1;
		info.uid = -1;

		struct lws_context *context = lws_create_context( &info );

		while( 1 ) {
			lws_service( context, 1000000 );
		}

		lws_context_destroy( context );
	}
```

The problem is that data coming with some noise at the end.

If I send from one end `{}` I receive on another end `{}p` or `{"action":1}hh3KNRsDU=`. So `*in` contains this noise after actual message string.
How I can properly receive the data?

I tried different examples but they looks overcomplicated.

**UPD**: version is latest. It worked on very old version but since I've upgraded ubuntu it stopped.

**Comment by lws-team** [comment]
Only `len` bytes at *in are valid.  There is no promise that there ia a NUL at `in[len]`.  If you want to log it safely either use eg, lwsl_hexdump_notice(), or `..."%.*s\n", (int)len, (const char *)in);`

> I tried different examples but they looks overcomplicated.

Stuff that works reliably has to take care of whatever it has to do.  Or you can write code ignoring that and just go by if it looks simple to you.  Just don't expect anyone else to care about unbreaking your 'simple' code for you...

**Comment by georgii-ivanov** [comment]
I was managed to copy right amount of data to the string. Anyways I don't wanna argue with you that buffer shouldn't contain something irrelevant to the actual data read from the socket.

My solution:
```
		char data[len]; 
		memcpy(data, in, len);
    		data[len] = '\0';
```

**Comment by lws-team** [comment]
> Anyways I don't wanna argue with you that buffer shouldn't contain 

Good job you don't want to argue with me, since you are describing how your code is broken and overflowing the provided buffer.
