### ISSUE TITLE
lws_smd_class_t definition seems missing on Windows

### ISSUE THREAD

**Issue by smourier** [warmcat/libwebsockets#2006]
Hi, I'm using CMake to build libwebsockets on Windows with this command line (open ssl latest installed in program files). I just cloned the repo and ran this:

    cmake -G "Visual Studio 16 2019" . -DOPENSSL_ROOT_DIR="c:\program files\openssl-win64"

I also had to set LWS_WITH_SYS_SMD to OFF otherwise cmake doesn't finishes its work (there may be smarter tricks here).

Now, the only problem I have left is lws_smd_class_t definition seems missing, so I just added this (taken from lws_smd.h):

    typedef uint32_t lws_smd_class_t;

somewhere and now it builds fine, just for you to know.

**Comment by lws-team** [comment]
There seem to be two different issues there... one is build with LWS_WITH_SYS_SMD ON on windows... however I build with that scenario using MSVC in CI already without problems, eg,

https://libwebsockets.org/sai/index.html?task=957994e232b95cddde1fed5860088643f451daca4167eda2984789f05c826bd4

so it would be great to get a paste of whatever cmake errors happen on your setup / options when you try that.

The other problem is not everything taking care about LWS_WITH_SYS_SMD OFF, I can reproduce it and pushed a patch on master that should solve that.

https://libwebsockets.org/git/libwebsockets/commit?id=e8cbfea22d1ab632ab5ad8a47ee2ba59aecdd892

**Comment by smourier** [comment]
Hi, thanks for your response.

For the first question, yes, I was wrong, I didn't exactly remember, but I've reproduced what I tried to do. So, when I do this

    cmake -G "Visual Studio 16 2019" -DOPENSSL_ROOT_DIR="d:\program files\openssl-win64" .

Cmake works fine, but then I can't compile as pthread.h is missing.

So I tried this:

    cmake -G "Visual Studio 16 2019" -DOPENSSL_ROOT_DIR="d:\program files\openssl-win64" -DLWS_EXT_PTHREAD_INCLUDE_DIR="D:\Program Files\msys64\usr\include" -DLWS_EXT_PTHREAD_LIBRARIES="D:\Program Files\msys64\usr\libpthread.a" .
    
But now cmake fails with this:

    cmake -G "Visual Studio 16 2019" -DOPENSSL_ROOT_DIR="d:\program files\openssl-win64" -DLWS_EXT_PTHREAD_INCLUDE_DIR="D:\Program Files\msys64\usr\include" -DLWS_EXT_PTHREAD_LIBRARIES="D:\Program Files\msys64\usr\libpthread.a" .
    -- The C compiler identification is MSVC 19.28.29115.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
    -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.28.0.windows.1") 
    Git commit hash: v4.0.0-280-g7c9ead21
    -- Performing Test LWS_HAVE_inline
    -- Performing Test LWS_HAVE_inline - Success
    -- Performing Test LWS_HAVE___inline__
    -- Performing Test LWS_HAVE___inline__ - Failed
    -- Performing Test LWS_HAVE___inline
    -- Performing Test LWS_HAVE___inline - Success
    -- Performing Test LWS_HAVE_MALLOC_TRIM
    -- Performing Test LWS_HAVE_MALLOC_TRIM - Failed
    -- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE
    -- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE - Failed
    -- Looking for fork
    -- Looking for fork - not found
    -- Looking for getenv
    -- Looking for getenv - found
    -- Looking for malloc
    -- Looking for malloc - found
    -- Looking for memset
    -- Looking for memset - found
    -- Looking for realloc
    -- Looking for realloc - found
    -- Looking for socket
    -- Looking for socket - not found
    -- Looking for strerror
    -- Looking for strerror - found
    -- Looking for vfork
    -- Looking for vfork - not found
    -- Looking for execvpe
    -- Looking for execvpe - found
    -- Looking for getifaddrs
    -- Looking for getifaddrs - not found
    -- Looking for snprintf
    -- Looking for snprintf - not found
    -- Looking for _snprintf
    -- Looking for _snprintf - not found
    -- Looking for _vsnprintf
    -- Looking for _vsnprintf - not found
    -- Looking for getloadavg
    -- Looking for getloadavg - not found
    -- Looking for atoll
    -- Looking for atoll - found
    -- Looking for _atoi64
    -- Looking for _atoi64 - found
    -- Looking for _stat32i64
    -- Looking for _stat32i64 - found
    -- Looking for clock_gettime
    -- Looking for clock_gettime - not found
    -- Looking for in6addr.h
    -- Looking for in6addr.h - found
    -- Looking for memory.h
    -- Looking for memory.h - not found
    -- Looking for netinet/in.h
    -- Looking for netinet/in.h - not found
    -- Looking for stdint.h
    -- Looking for stdint.h - not found
    -- Looking for stdlib.h
    -- Looking for stdlib.h - not found
    -- Looking for strings.h
    -- Looking for strings.h - not found
    -- Looking for string.h
    -- Looking for string.h - not found
    -- Looking for sys/prctl.h
    -- Looking for sys/prctl.h - not found
    -- Looking for sys/socket.h
    -- Looking for sys/socket.h - not found
    -- Looking for sys/sockio.h
    -- Looking for sys/sockio.h - not found
    -- Looking for sys/stat.h
    -- Looking for sys/stat.h - not found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - not found
    -- Looking for unistd.h
    -- Looking for unistd.h - not found
    -- Looking for vfork.h
    -- Looking for vfork.h - not found
    -- Looking for sys/capability.h
    -- Looking for sys/capability.h - not found
    -- Looking for malloc.h
    -- Looking for malloc.h - not found
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Looking for inttypes.h
    -- Looking for inttypes.h - not found
    -- Performing Test LWS_HAVE_WIN32_AFUNIX_H
    -- Performing Test LWS_HAVE_WIN32_AFUNIX_H - Failed
    CMake Error at CMakeLists.txt:555 (message):
      No afunix.h in toolchain for LWS_UNIX_SOCK


    -- Configuring incomplete, errors occurred!
    See also "D:/github/libwebsockets/CMakeFiles/CMakeOutput.log".
    See also "D:/github/libwebsockets/CMakeFiles/CMakeError.log".

Maybe I'm misusing it?

**Comment by lws-team** [comment]
There are some notes about building on windows here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

> No afunix.h in toolchain for LWS_UNIX_SOCK

Hm... ms added support for unix sockets in 2017

https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

so we enable it by default also on windows now.  There's some troubleshooting tips on that article, or you can just turn it off with -DLWS_UNIX_SOCK=0 if you don't care about it.

The CI (which builds this) is just using windows sdk + msvc compiler + cmake with no special magic for unix sockets.

**Comment by smourier** [comment]
I didn't find that doc (not obvious to find, I did searched for it :-) ). But what I did was very similar. Strangely, when using pthread from what's pointed in the doc (instead of pthread from Msys which I was targeting initially) CMake generates successfully.

Unfortunately, I have other issues then:

   lws-genhash.h(85,18): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'

and 

    2>openssl-server.c
    2>D:\github\libwebsockets\lib\tls\openssl\openssl-server.c(421,40): error C2037: left of 'extra_certs' specifies undefined struct/union 'ssl_ctx_st'
    2>D:\github\libwebsockets\lib\tls\openssl\openssl-server.c(421,19): error C2198: 'sk_X509_value': too few arguments for call
    2>tls-client.c
    2>openssl-client.c
    2>D:\github\libwebsockets\lib\tls\openssl\openssl-client.c(588,3): error C2220: the following warning is treated as an error
    2>D:\github\libwebsockets\lib\tls\openssl\openssl-client.c(588,3): warning C4013: 'EVP_MD_CTX_destroy' undefined; assuming extern returning int

But I'm not sure I need SMD (don't know what it is).

**Comment by lws-team** [comment]
> pthread from Msys 

There are different animals, what I documented I confirmed worked.  I don't really have time or motivation to debug anything else and I can show you it building fine in CI just using ms and cmake pieces.

The CI also documents exactly how it was built, eg

> cd /Users/agreen\jobs\0-0.2\libwebsockets && mkdir build && cd build && set SAI_CPACK="-G ZIP" && cmake .. -DLWS_OPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib\libssl.lib;C:\Program Files\OpenSSL\lib\libcrypto.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\Program Files\OpenSSL\include" -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" && cmake --build . --config DEBUG && set CTEST_OUTPUT_ON_FAILURE=1 && ctest . -C DEBUG -j4 --output-on-failure

> lws-genhash.h(85,18): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'

This is a downstream effect of either not removing your build dir and redoing the cmake, or that something you gave cmake cannot build or link (eg, the openssl paths are wrong).  Look at your CMakeFiles/CMakeError.log and see what actually happened when cmake tried to build a test app to see which HMAC apis are available in your OpenSSL.  Notice that file is appended to, so look at the last entry or delete it and re-cmake.

**Comment by smourier** [comment]
Ok it was a pthread path issue. It doesn't break the whole CMake generation for some reason so I though it was ok. It works now, thanks!
