### ISSUE TITLE
LWS_CALLBACK_FILTER_NETWORK_CONNECTION / lws_get_peer_simple_fd / getpeername: Transport endpoint is not connected

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2009]
Hi,

We receive some fast connections/disconnections on libwesockets that prevent us from getting the IP of the remote attacker.

Basically even by calling lws_get_peer_simple_fd() at the LWS_CALLBACK_FILTER_NETWORK_CONNECTION, it's already too late because the connection is already closed and we get the error "getpeername: Transport endpoint is not connected".

So we can not get the IP of the attacker.

Would it be possible for libwesockets to get/store the IP at an early stage and give it to us somehow ?

Another thing to add, if we do not return(-1) to the LWS_CALLBACK_FILTER_NETWORK_CONNECTION event on that kind of attack we quickly receive the following error from libwesockets: "Ran out of header data space".

Regards.

**Comment by lws-team** [comment]
> Ran out of header data space

This is fatal for the connection, we would hang up on him, but it's not any problem for lws to deal with that, right?

> LWS_CALLBACK_FILTER_NETWORK_CONNECTION, it's already too late

It's called almost immediately after we accept()ed the connection, there is no earlier point we can do it.  AFAIK there is no way to look at what is in the listen queue before you accept it.

By the sound of it he has connected, sent something and dropped his connection before we in userland start to handle it... userland isn't in a position to intercept that then.

You can look with tcpdump what's happening on the network interface and find his IP(s) that way should work.

**Comment by dev31337** [comment]
Thank you for your reply.

In fact you get the remote IP in file: lib/roles/listen/ops-listen.c, function: rops_handle_POLLIN_listen(), the accept() call 2nd argument (cli_addr) is the remote IP.

In the source this remote IP is only used for the logging then discarded.

Do you think it could be possible to store it somewhere and provide it at the LWS_CALLBACK_FILTER_NETWORK_CONNECTION event ?

This would be great because at the accept() time the IP is valid and unfortunately no more at the getpeername().

**Comment by lws-team** [comment]
I see, if it's got correct data at the accept, then we should pass it through.

I pushed a patch on master that sends a pointer to a struct with this info in the `user_data` pointer of the callback, leaving `in` as it is.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n83-92

please give it a try.

**Comment by dev31337** [comment]
Yes I can confirm that it perfectly works and we can get the IP for each connection even if they are quickly diconnected.

I have one question about getting the socket fd from the wsi.

I can see that lws_get_socket_fd() and lws_get_peer_simple() act differently.

lws_get_peer_simple() calls lws_get_network_wsi() before getting the socket fd, while lws_get_socket_fd() does not.

Do we have to call lws_get_network_wsi() before calling lws_get_socket_fd() to ensure to always get the socket fd from a wsi ?

**Comment by dev31337** [comment]
Oh i see, so maybe it would be a good idea to call lws_get_network_wsi() in the function lws_get_socket_fd() for h2 connections.

I can't even imagine the next upcoming complexity with h3/quic :)

**Comment by lws-team** [comment]
No I think it's OK as it is... when the nwsi is connecting, you will get the filter callback on that; at that time it has not been able to talk to the server yet to negotiate h2 or whatever so everything is the same.

If later you ask for the sockfd of the mux child wsi you'll get -1, I don't want user code fiddling with the socket.

UDP + dtls is more complicated but the mux stuff was along the same lines last time I looked.

**Comment by dev31337** [comment]
I understand, in fact in the LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED I need to get the hostname and the only way I found was to use lws_get_peer_addresses() which requires both the wsi and the socket fd (not sure why?), so I need to call lws_get_socket_fd() to get it for the 2nd argument. (this is the only place in all my user code where I need the wsi fd)

**Comment by dev31337** [comment]
> 
> 
> I see, if it's got correct data at the accept, then we should pass it through.
> 
> I pushed a patch on master that sends a pointer to a struct with this info in the `user_data` pointer of the callback, leaving `in` as it is.
> 
> https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n83-92
> 
> please give it a try.

I have an optimization suggestion.

Instead of using user_data (which could be used by the user for personal data) why not using the second parameter "in" which currently (in previous version) contains the accepted socket fd.

This could be done by modifying your structure:

From:

struct lws_filter_network_conn_args {
	struct sockaddr_storage		cli_addr;
	socklen_t			clilen;
	lws_sockfd_type			accept_fd;
};

To:

struct lws_filter_network_conn_args {
        lws_sockfd_type			accept_fd;
	struct sockaddr_storage		cli_addr;
	socklen_t			clilen;
};

Passing this structure to "in" would not break backward compatibility and leave "usr" untouched.

What do you think ?

**Comment by lws-team** [comment]
> Passing this structure to "in" would not break backward compatibility

That is not the case, the fd is passed cast as a pointer type (because on some platforms, it's a handle / pointer).  But it's an fd, putting a pointer to an fd in in is something completely different and will break any existing code.  That's why it does what it does.

**Comment by dev31337** [comment]
Oh yes you are right, sorry I thought it was the pointer to the fd in "in".
