### ISSUE TITLE
[ CGI ] Bad performance

### ISSUE THREAD

**Issue by lailton-dev** [warmcat/libwebsockets#2012]
Hi @lws-team 

The CGI now are working ok on MacOSx but the perfomance when it is running with CGI is not good. and it have a little problem when receive multiples request.

I did a test to see quality it and the result was not so good.

ab -n 100 http://127.0.0.1:7681

Failed requests: 85
Requests per second: 13.30 [#/sec] (mean)

<img width="1171" alt="Screen Shot 2020-08-20 at 15 10 47" src="https://user-images.githubusercontent.com/58268709/90809111-61925180-e2f7-11ea-8873-f6ed2f529c5c.png">

Compared with a minimal http server

Failed requests: 0 GREAT!
Requests per second: 11911.85 [#/sec] (mean) GREAT!

<img width="1074" alt="Screen Shot 2020-08-20 at 15 10 51" src="https://user-images.githubusercontent.com/58268709/90809131-67883280-e2f7-11ea-9ee6-e507aaefb2d3.png">

The difference performance is to much, any idea why?

**Comment by lws-team** [comment]
Not really, and I don't have any time to spend on it.  You're very welcome to look into it.

**Comment by lailton-dev** [comment]
@lws-team 
Ok thanks, I will take look.
