### ISSUE TITLE
build failed on Macox

### ISSUE THREAD

**Issue by aipf** [warmcat/libwebsockets#2014]
[  0%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o
In file included from /Users/aipingfa/workspace/raspberry/libwebsockets/lib/plat/unix/unix-caps.c:28:
In file included from /Users/aipingfa/workspace/raspberry/libwebsockets/lib/core/./private-lib-core.h:140:
In file included from /Users/aipingfa/workspace/raspberry/libwebsockets/include/libwebsockets.h:602:
/Users/aipingfa/workspace/raspberry/libwebsockets/include/libwebsockets/lws-genhash.h:85:18: error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/usr/local/include/openssl/ossl_typ.h:102:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
1 error generated.
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o] Error 1
make[1]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by lws-team** [comment]
No the problem is earlier in cmake, it can't build a test app successfully to find out which kind of hmac api your tls lib has.

Look for a file CMakeError.txt in your build dir, it's in ./CMakeFiles/ on linux.  Look for what happened when it tried to build the hmac related test.

**Comment by aipf** [comment]
thanks, it's turn out to find wrong ssl lib, and I fixed it
