### ISSUE TITLE
0.3 BTC for fixing obviously broken libwebsockets client

### ISSUE THREAD

**Issue by deforation** [warmcat/libwebsockets#2018]
With this issue, i provide a bounty of 0.3 BTC to fix the following libwebsockets client issue.
[Issue: 2015](https://github.com/warmcat/libwebsockets/issues/2015)

**Problem:**
Libwebsockets performs worse compared to ordinary python libraries.
It might be, that the root cause is openssl or something else, but they fall indirectly under this
libwebsockets umbrella.

**Task:**
1) Crate a fix for the issue Nr. 2015. So that libwebsockets will perform equel or better to the python counterpart.
2) Give an explanation, what the issue was and which component is at fault.

**Guidlines:**
1) The fix must work under ubuntu 18.04
2) The fix should integrate nicely into libwebsockets  (obviously)
3) The fix should primarily use openssl and if not possible with that (wolfssl)
4) The fix should use one the integrated eventloops such as (libev, libuv, libevent or the default poll)
5) Me or im sure, @kutoga will try the fix for stability with other endpoints that have this issue.

**Bounty:**
I Provide a bounty of 0.3 BTC to the one who finds and fixes the issue.

**Why should i trust you?**
Good question. Don't trust anyone in the internet.
The only thing i can offer is the following:
1) You search some sort of trustworthy escrow service/counterparty, which makes the final transaction.
2) If @lws-team offers to take this role, i will send it to him and he can Release it.
3) If @lws-team agrees to point 2 and he fixes him self, nice, just keep it for this otherwise reall nice library.
4) You trust me, that i send it.

Thanks for your cooperation. 
And i hope @lws-team that you don't take it personally. 
Its all about improving the library and the parts within its umbrella (according to [lws-overview](https://github.com/warmcat/libwebsockets/raw/master/doc-assets/lws-overview.png))

**Comment by deforation** [comment]
I thank you @lws-team .
It solved the issues i had as well.

I don't know if i would have been able to come up with this solution.
You said, you will not take the offer, but i promised one.
So please let me know (does not need to be now), where i should send it to.
The amount is reserved.

Thanks again for your effort and time.

**Comment by kutoga** [comment]
I've done many tests and it really seems the issue is gone. I did not only test binance, but also some other endpoints. Here just a plot for binance with the "old" configuration and the new one (also wolfssl vs openssl). Looks pretty good now:
![plot](https://user-images.githubusercontent.com/19676199/91190631-1495ed00-e6f4-11ea-87e6-bb2e2b6e8bda.png)

Thanks for the help:)

@lws-team If you want to have the 1 ETH, I'll send it you

**Comment by lws-team** [comment]
IIUI the coalescing behaviour is decided by the server side before it encrypts and sends the tls record.  We just tell it during ws negotiation to compress the ws messages before the encryption serverside, and that seems to cause it to act differently... still serverside.

I guess if it gets busy enough serverside to produce the same amount of compressed data as when it made the symptom, it will start to show the old behaviour again.

I appreciate the offers but I will decline thanks.

**Comment by gnauq3mg6m64rs2n** [comment]
> I've done many tests and it really seems the issue is gone. I did not only test binance, but also some other endpoints. Here just a plot for binance with the "old" configuration and the new one (also wolfssl vs openssl). Looks pretty good now:
> ![plot](https://user-images.githubusercontent.com/19676199/91190631-1495ed00-e6f4-11ea-87e6-bb2e2b6e8bda.png)
> 
> Thanks for the help:)
> 
> @lws-team If you want to have the 1 ETH, I'll send it you

how did you do it?

**Comment by kutoga** [comment]
The "new" code was embedded into an existing application which then was used to measure the book age (=latency). Then it basically just exported this book age. I've embedded the code into this application, because it allowed me to do some more sophisticated testing. I'm still working on this.

**Comment by gnauq3mg6m64rs2n** [comment]
> The "new" code was embedded into an existing application which then was used to measure the book age (=latency). Then it basically just exported this book age. I've embedded the code into this application, because it allowed me to do some more sophisticated testing. I'm still working on this.

show please example binance_wolfssl

**Comment by kutoga** [comment]
Unfortunately, I cannot post the complete code, but it is basically the new binance example compiled with wolfssl.
