### ISSUE TITLE
[feature] Support multiple event sources in parallel

### ISSUE THREAD

**Issue by oliv3r** [warmcat/libwebsockets#2021]
This issue is just to raise (future) awareness and to start thinking of idea's on how to deal with this in the future.

Libwebsockets is great, but it currently only allows for a single event source. While this is fine for static compilation, when installing libwebsockets as a distro library, and we have 2 packages that depend on the two different flavors of websockets, we are in trouble.

Option 1)
    Install various variants into different directories.
    + No work here, all up to the packages for the various distro's to deal with
     - Applications don't know this path and they can't share the same name space. So applications would need to be told which version to use

Option 2)
    Install the various variants under different names
    + No work here, all work up for the downstream 'dependents' and the distro packagers, as they now link against libwebsockets-variant.so (maybe some .pkgconfig work?)
    - Duplicated libraries (fat)
    - Downstream users need to link against -libws-variant from now on (but as nobody uses special versions, this pain should be relatively small)

Option 3)
   Split the library into smaller junks e.g. libwebsockets-glib would depend on libwebsockets.so
   + As option 2, but without the fat
   + Only for actual users that need these extra features
   - Needs to be properly supported here

Option 4)
   Be able to enable all options without mutual exclusivity
   + Best for users, one library, no interface changes etc
   - Most work here

**Comment by lws-team** [comment]
There has already been head-scratching about that and a plan to deal with it

https://github.com/warmcat/libwebsockets/issues/1980

libevent and libev headers conflict, neither project is interested in ironing that out.  So what you list as option 3 and is my proposal in #1980 is the only way that can encapsulate the conflicting headers.  You can build in, eg, libuv, [libevent | libev], libglib into a single libwebsockets.so OK but it doesn't solve the whole thing.

If you want to do some earthmoving, patches are welcome... there is already libdl plugin support in unix plat, designed for protocol plugins, that can be redeployed do the actual plugin part.  And event lib support is already isolated in the code and via an ops struct... the biggest issue is they have footprints in private objects in parallel at build time atm and need to be changed to have a mutually exclusive objects instantiated according to which singular plugin is selected at runtime.  All of the event lib header inclusion outside of the related plugin would be torn out and forbidden then in the rest of lws.

**Comment by oliv3r** [comment]
You are right and I should have looked into more detail on #1980!

The initial focus of #1980 was about debian packaging, and while for debian focusing on glib makes sense, it really depends on how the library is used. But that is a conversation for that topic.

I think it's best we close this ticket, and focus the effort on #1980. In closing words though, I would say the best approach from a user's point of view (e.g. embedded linux scenario's) is to have the plugin system you suggest, so that you just depend on which ever plugin you want and that an application can make use of various plugins. I understand that this will take a while of course to take foot ;)

Meanwhile, this is the downstream approach I took with alpine, packaging in 5 times for the 5 variants and make the library mutually exclusive. Not pretty, but it's a good start :)

**Comment by lws-team** [comment]
>  packaging in 5 times for the 5 variants 

It makes sense as a workaround for alpine which tends to be "single-purpose", and can probably ignore that these packages would be mutually exclusive when done like that.

Most of the pieces are actually there it just needs one of those big painful reworks where everything ends up exactly the same except for one change most people will never notice.
