### ISSUE TITLE
Need help building one of the minimal examples "lws minimal ws server + permessage-deflate echo"

### ISSUE THREAD

**Issue by wb0gaz** [warmcat/libwebsockets#2022]
Beginner question (if this is not the appropriate venue for a beginner question, a pointer as to where to go for help would be greatly appreciated!)

I am trying to build one of the minimal examples "lws minimal ws server + permessage-deflate echo". I have no prior experience with libwebsockets or cmake.

I am using Ubuntu 18.04, with cmake 3.10.2 installed, libwebsockets-dev 2.0.3-3build1 installed using apt-get, and libwebsockets github (4.1.0) cloned (so in my working directory there is a sub-directory libwebsockets over which there are numerous include files, etc.)

The following example files are in my working directory (along with the sub-directory libwebsockets as noted above):

minimal-ws-server-echo.c
protocol_lws_minimal_server_echo.c
CMakeLists.txt

The environment variable CMAKE_PREFIX_PATH is set to /home/user/ws/, which is the path to the libwebsockets directory created when I cloned from github.

cmake command stops with the following text. The two cmake files mentioned (libwebsocketsConfig.cmake, libwebsockets-config.cmake) are nowhere to be found on the system.

Any advice/suggestion/request for clarification/suggestion as to where to go for help, greatly appreciated. 

###
cmake .
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:3 (find_package):
  Could not find a package configuration file provided by "libwebsockets"
  with any of the following names:

    libwebsocketsConfig.cmake
    libwebsockets-config.cmake

  Add the installation prefix of "libwebsockets" to CMAKE_PREFIX_PATH or set
  "libwebsockets_DIR" to a directory containing one of the above files.  If
  "libwebsockets" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/user/ws/CMakeFiles/CMakeOutput.log".

**Comment by lws-team** [comment]
> libwebsockets-dev 2.0.3-3build1 installed using apt-get, and libwebsockets github (4.1.0) cloned 

You can't take that approach to build anything, not just lws.  You have to pick one, you'd want the later version from git.

Remove the deb packages, enter the cloned dir then

```
$ mkdir build && cd build && cmake .. && make -j8 && sudo make install
```

Then you should be able to enter your dir with the example pieces, `rm -f CMakeCache.txt` and then `cmake . && make`

**Comment by wb0gaz** [comment]
I have removed the old version of libwebsockets and built/installed the current version per instruction above, which appears to be successful.

The build of the example itself (cmake . && make) was performed in the directory containing the three files from the example, with CMakeCache.txt removed. It fails as follows:

~/ws$ cmake . && make
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Success
-- Performing Test HAS_LWS_WITH_SERVER
-- Performing Test HAS_LWS_WITH_SERVER - Success
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS - Success
CMake Error at /usr/local/lib/cmake/libwebsockets/LwsCheckRequirements.cmake:52 (message):
  Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this
  project
Call Stack (most recent call first):
  CMakeLists.txt:14 (require_lws_config)


-- Configuring incomplete, errors occurred!
See also "/home/user/ws/CMakeFiles/CMakeOutput.log".

**Comment by lws-team** [comment]
If you are building the -binance example, as it says in its README

> Lws must have been built with LWS_ROLE_WS=1 and LWS_WITHOUT_EXTENSIONS=0

it means when you build lws (not the example) you need to give `cmake .. -DLWS_WITHOUT_EXTENSIONS=0` instad of just `cmake .. `

**Comment by wb0gaz** [comment]
Thank you so much for the quick reply.

`mkdir build && cd build && cmake .. -DLWS_WITHOUT_EXTENSIONS=0  && make -j8 && sudo make install`

built libwebsockets 4.1.0 without error, and

`cmake . && make`

built the example without error, resulting in a binary I can execute.
