### ISSUE TITLE
multiple lws vhost

### ISSUE THREAD

**Issue by shammi112** [warmcat/libwebsockets#2023]
Hello,
I have one threaded  websocket server running, having multiple url. I need to write libwebsocket based client , which will send data to 5-6 urls.

Should i need to create separate context for every url?  What will be the best approach. 

Regards,
SHAMMI

**Comment by lws-team** [comment]
For multiple client connections, you normally don't have to do anything special for vhost or context, you can just create multiple connections bound to the same vhost and context. See, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c

you can mix as many server and client connections as you like within the same vhost and context just fine.

**Comment by shammi112** [comment]
> For multiple client connections, you normally don't have to do anything special for vhost or context, you can just create multiple connections bound to the same vhost and context. See, eg
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c
> 
> you can mix as many server and client connections as you like within the same vhost and context just fine.
Hello i am using minimal ws-client-tx example, and i am able to communicate with my python flask threaded websocket. But i have to write data on different urls/paths on webserver . here i am planning to implement separate callback for  each url. Will it create any issue?

**Comment by lws-team** [comment]
With ws aside from the http url, you can request a specific subprotocol when you connect.

The struct lws_protocols and their callbacks (if that is what you're talking about with 'separate callback') are designed to bind to a specific ws subprotocol name.  So if the code for each case is quite different, the convenient way might be to use a different ws subprotocol for each case, which means a separate lws_protocols, separate ws protocol name and separate callback.

The alternative is have one ws protocol and so one callback, and look at the url path at ESTABLISHED to modify what it will do.

You can always break out your code into your own handler functions and call the right one from the lws callback as well.

**Comment by shammi112** [comment]
> With ws aside from the http url, you can request a specific subprotocol when you connect.
> 
> The struct lws_protocols and their callbacks (if that is what you're talking about with 'separate callback') are designed to bind to a specific ws subprotocol name. So if the code for each case is quite different, the convenient way might be to use a different ws subprotocol for each case, which means a separate lws_protocols, separate ws protocol name and separate callback.
> 
> The alternative is have one ws protocol and so one callback, and look at the url path at ESTABLISHED to modify what it will do.
> 
> You can always break out your code into your own handler functions and call the right one from the lws callback as well.

**In my case only path variable and data will change, for example path will be  /abc, /def, /xyz etc.**

**Comment by Ajuz369** [comment]
Hello in case of connecting to discrete clients using same context without creating vhosts how will i facilaitate diffrent tls certiicates to ecah connections? since the tls certificate path is linked to the parent context?

**Comment by Ajuz369** [comment]
> For multiple client connections, you normally don't have to do anything special for vhost or context, you can just create multiple connections bound to the same vhost and context. See, eg
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c
> 
> you can mix as many server and client connections as you like within the same vhost and context just fine.

Hello in case of connecting to discrete clients using same context without creating vhosts how will i facilaitate diffrent tls certiicates to ecah connections? since the tls certificate path is linked to the parent context?

**Comment by Ajuz369** [comment]
> You typically don't need to fill in any cert information to have tls client connections.
> 
> The tls library normally has a trust store containing common CAs, and this is enough to validate the remote server cert and do the tls. You only need to fill it in if using mutual / client-side tls auth. If not, one vhost (eg, the default one) is usually enough.

HI , i need to implement the mutual client-side tls auth for discrete and need to link same shared context to it. so that the usecase for me  how can I do that by passing client certificates to connect_info structure?

**Comment by lws-team** [comment]
Tls is handled in the vhost.  If you want n different tls certs you need n different vhosts and describe that by filling in the related members in struct lws_context_creation_info.  When making the individual client connections, you can bind the client connection to the right vhost - and its tls arrangements that suit it - by using the .vhost pointer there.
