### ISSUE TITLE
LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED / LWS_CALLBACK_CLOSED_HTTP / Remote IP

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2026]
Hi,

I would start by thanking you for providing the remote IP reliably through LWS_CALLBACK_FILTER_NETWORK_CONNECTION event.

The problem I'm having now is getting the remote IP from LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED since the same issue sometimes happens, lws_get_peer_simple(wsi) sometimes returns "getpeername: Transport endpoint is not connected".

Would you consider storing the remote IP along the wsi so we are sure to be able to get it reliably from LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED / LWS_CALLBACK_CLOSED_HTTP events ?

I tried from user code to do such linking (wsi <> IP), but the wsi given trough the LWS_CALLBACK_FILTER_NETWORK_CONNECTION is not the same than the wsi given through LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED so I can not reliably track the IP.

You may also point me to how I could modify lws to do it, any help would be much appreciated :)

Thanks.

**Comment by lws-team** [comment]
> Would you consider storing the remote IP along the wsi 

There are two reasons I didn't do this last time you suggested it... it doesn't do anything for getting peer info from client wsi but will increase wsi size there, and it will not apply to already-accepted but adopted sockets which is a supported way to integrate lws to other apps.

> wsi given trough the LWS_CALLBACK_FILTER_NETWORK_CONNECTION is not the same than the wsi given through LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED so I can not reliably track the IP.

These are not necessarily the same thing, with, eg, http/2 or ws-over-h2.  One wsi, aka "nwsi" or "network wsi" is responsible for the tcp and tls connection, and any number of other stream wsi can join it and share the connection.

If that's the case here, you can use this to make sure you have the network wsi either way

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h#n528-539
