### ISSUE TITLE
CMake Error: Set LWS_DBUS_INCLUDE2 to /usr/lib/ARCH-linux-gnu/dbus-1.0/include 

### ISSUE THREAD

**Issue by jsmolic** [warmcat/libwebsockets#2035]
Hello Andy
there are (again :-) ) some issues with building lws on Gentoo Linux. Referenced bug is at [1].
Specifically, CMake complains about `LWS_DBUS_INCLUDE2` on arm.

`dbus-arch-deps.h` is located on the system (arm architecture) in `/usr/lib/dbus-1.0/include/dbus/`. 
I found some code from https://github.com/warmcat/libwebsockets/commit/31dfc4aa12e1a733346d992c6b1173153173aedf#diff-af3b638bc2a3e6c650974192a53c7291R710, and CMake checks in `/usr/lib64/dbus-1.0/include`, but I can't find that logic in the code now.  Maybe the issue is that CMake is trying to find it only in `usr/lib64`, but not in `usr/lib`? I don't encounter this on `x86_64` system, where `dbus-arch-deps.h` is located in `/usr/lib64/dbus-1.0/include/dbus`.

[1] https://bugs.gentoo.org/740090

**Comment by lws-team** [comment]
>  some issues with building lws on Gentoo Linux.
> I don't encounter this on x86_64 system

CMake has been completely refactored in master... for this particular option, it defers to pkgconfig now.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/dbus/CMakeLists.txt

Can I suggest building master?  It will very shortly become v4.1.

**Comment by jsmolic** [comment]
> > some issues with building lws on Gentoo Linux.
> > I don't encounter this on x86_64 system
> 
> CMake has been completely refactored in master... for this particular option, it defers to pkgconfig now.
> 
> https://libwebsockets.org/git/libwebsockets/tree/lib/roles/dbus/CMakeLists.txt
> 
> Can I suggest building master? It will very shortly become v4.1.

Thanks, changes in `master` should solve this. I was able to provide a workaround for 4.0.20 for the sake of getting that version as stable in Gentoo.
