### ISSUE TITLE
Crash lws 3.2 stable

### ISSUE THREAD

**Issue by danflu** [warmcat/libwebsockets#2036]
Hi  @lws-team ,

Could you please take a look at an issue posted in Janus Gateway github?

https://github.com/meetecho/janus-gateway/issues/2349

We are not sure exactly where is the bug, but the crash always happens when sending a big buffer of data (127k) to firefox browser.

Janus is linked against lws v3.2 stable.

Thanks a lot for your attention.

**Comment by lws-team** [comment]
This is answered on the Janus issue.
