### ISSUE TITLE
callback error LWS_CALLBACK_CLIENT_CONNECTION_ERROR with null user?

### ISSUE THREAD

**Issue by beta-li** [warmcat/libwebsockets#2037]
client

LWS_CALLBACK_CLIENT_CONNECTION_ERROR 

null user？

typedef int lws_callback_function(struct lws *wsi, enum lws_callback_reasons reason,
		    void *user, void *in, size_t len);

**Comment by lws-team** [comment]
User allocation depends on, eg, which protocol you negotiated with the server.  If you didn't connect to it, that did not happen.
