### ISSUE TITLE
callback with LWS_CALLBACK_PROTOCOL_INIT is not invoked

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2040]
Hi,

I'm using v4.1-stabel and somehow I don't see the invoking callback() with LWS_CALLBACK_PROTOCOL_INIT reason.
My protocols are looking like the following:
```
static struct lws_protocols protocols[] = {
  { "http", lws_callback_http_dummy, 0, 0 },
  { "gcs", callback, sizeof(struct connection_data), 128, 0, NULL, 0 },
  { NULL, NULL, 0, 0 } /* terminator */
};
```
My context is initialized pretty close to the minimal-ws-threads-smp example (which is working pretty fine, btw) with foreign libuv loops and I use index.html + example.js from this example for testing purposes.

I'm pretty sure I do something wrong here but can't figure out what exactly. Would be grateful for any advice.

The list of reasons looks like following:

LWS_CALLBACK_EVENT_WAIT_CANCELLED
LWS_CALLBACK_EVENT_WAIT_CANCELLED
LWS_CALLBACK_HTTP_BIND_PROTOCOL
LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION
LWS_CALLBACK_ADD_HEADERS
LWS_CALLBACK_ESTABLISHED <== here I get SIGSEGV as the code tries to use non-allocated per-host data.

**Comment by lws-team** [comment]
What is your platform / os version?

Does minimal-http-server-eventlib-foreign --uv show the same problem?

**Comment by zbroyar** [comment]
Crash is reproducible on
`Linux dragon.mykola.org 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
and
`Darwin taran.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

`lws-minimal-http-server-eventlib-foreign --uv` works perfectly on both platforms.

<img width="917" alt="Знімок екрана 2020-09-09 о 12 27 23" src="https://user-images.githubusercontent.com/338701/92581597-8cd5e400-f298-11ea-8a28-8600d525ff16.png">
<img width="853" alt="Знімок екрана 2020-09-09 о 12 27 37" src="https://user-images.githubusercontent.com/338701/92581612-91020180-f298-11ea-9108-e5c023915e08.png">

**Comment by lws-team** [comment]
> lws-minimal-http-server-eventlib-foreign --uv works perfectly on both platforms.

So either align eventlib-foreign to your code so it starts showing the symptom and let's see the diff, or align your code to eventlib-foreign until you don't have the problem any more.

**Comment by lws-team** [comment]
... just in case we didn't understand each other, I was asking does eventlib-foreign do PROTOCOL_INIT?  The "crash" won't happen even without that if the application doesn't trap or do anything critical in PROTOCOL_INIT.

**Comment by zbroyar** [comment]
I don't know: there is no protocols definition in the code of eventlib-foreign. As far as I see, the context is created with info.protocols == 0.

**Comment by lws-team** [comment]
Lws knows how to serve file over http etc using a built-in default "dummy" handler if none others provided

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/dummy-callback.c#n266

**Comment by zbroyar** [comment]
Yes, and I don't see LWS_CALLBACK_PROTOCOL_INIT in the code of lws_callback_http_dummy(). Give me 20-30 mins...

**Comment by zbroyar** [comment]
Dummy callback is not called with PROTOCOL_INIT (= 27) reason. See the picture:
<img width="569" alt="Знімок екрана 2020-09-09 о 13 14 55" src="https://user-images.githubusercontent.com/338701/92586287-b72aa000-f29e-11ea-9991-df2c165d0270.png">

**Comment by lws-team** [comment]
OK I will look into it later.  You might want to try cmake option `-DLWS_WITH_EVLIB_PLUGINS=0` as a possible workaround

**Comment by zbroyar** [comment]
Library is already built with this flag. Let me try to remove it, btw...

**Comment by zbroyar** [comment]
OK.

If I allow evlib plugins on osx cmake can't build the libwebsockets-evlib_uv.dylib:

```
[100%] Linking C shared library ../../libwebsockets-evlib_uv.dylib
Undefined symbols for architecture x86_64:
  "_lws_mutex_refcount_lock", referenced from:
      _lws_libuv_closewsi in libuv.c.o
      _lws_uv_idle in libuv.c.o
      _lws_uv_sultimer_cb in libuv.c.o
  "_lws_mutex_refcount_unlock", referenced from:
      _lws_libuv_closewsi in libuv.c.o
      _lws_uv_idle in libuv.c.o
      _lws_uv_sultimer_cb in libuv.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libwebsockets-evlib_uv.dylib] Error 1
make[1]: *** [lib/event-libs/libuv/CMakeFiles/websockets-evlib_uv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target test-server
make: *** [all] Error 2
```

If I allow evlib plugins on Ubuntu it can't load the plugin with the following message: `lws_plat_dlopen: Error loading DSO: /usr/local/lib/libwebsockets-evlib_uv.so: undefined symbol: lws_mutex_refcount_lock`

In both cases the problem appear to be around `lws_mutex_refcount_lock`

Just in case, without `-DLWS_WITH_EVLIB_PLUGINS=0` I build the library as follows:
```
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DLWS_ROLE_WS=1 -DLWS_WITH_TLS=1 -DLWS_WITH_SERVER=1 -DLWS_WITH_LIBUV=ON -DLWS_WITH_THREADPOOL=1 -DLWS_MAX_SMP=32 -DLWS_WITH_MINIMAL_EXAMPLES=1
cmake --build build -j 8
sudo cmake --install build
```

**Comment by lws-team** [comment]
Do you possibly have some other libwebsockets pieces flying around, like brew libwebsockets.so?

**Comment by zbroyar** [comment]
Nope. After our previous conversation in email I carefully cleaned up both systems.

**Comment by lws-team** [comment]
Hm... it's a bit suspicious that same problem was solved and now suddenly isn't.

I can build current lws fine in CI on a mac mini with libuv and the plugins

https://libwebsockets.org/sai/index.html?task=90991d195bce2694ca75b2c4e9b4dacddd616e9741a404128f06db6ea1d45dcb

**Comment by zbroyar** [comment]
Basically, I'm personally good with disabled plugins: for now I plan to use lws with libuv only. Attempt to build lib with plugins was made in hope it will add invoking of callback with LWS_CALLBACK_PROTOCOL_INIT.

**Comment by zbroyar** [comment]
It looks like using LWS_SERVER_OPTION_LIBUV option prevent callback invocation with LWS_CALLBACK_PROTOCOL_INIT. If I start modified example with `-u` option it works until I send http requests only.

``` diff
diff --git a/minimal-examples/ws-server/minimal-ws-server/minimal-ws-server.c b/minimal-examples/ws-server/minimal-ws-server/minimal-ws-server.c
index 741d1741..264bce03 100644
--- a/minimal-examples/ws-server/minimal-ws-server/minimal-ws-server.c
+++ b/minimal-examples/ws-server/minimal-ws-server/minimal-ws-server.c
@@ -103,7 +103,10 @@ int main(int argc, const char **argv)
        if (lws_cmdline_option(argc, argv, "-v"))
                info.retry_and_idle_policy = &retry;
 
-       context = lws_create_context(&info);
+  if(lws_cmdline_option(argc, argv, "-u"))
+    info.options |= LWS_SERVER_OPTION_LIBUV;
+
+  context = lws_create_context(&info);
        if (!context) {
                lwsl_err("lws init failed\n");
                return 1;
```

**Comment by lws-team** [comment]
For your build problem, that symbol is only built in, or referenced, when LWS_MAX_SMP > 1, that is 1 by default and nothing in lws changes it, only the user from cmake.

That error can only come if you are trying to build the plugins with LWS_MAX_SMP > 1, but when the linker gets hold of the libwebsockets library to bind the plugin to, that library was built with LWS_MAX_SMP == 1.

So again, look around with find / -name "libwebsockets.so.*" for unexpected copies.

For the PROTOCOL_INIT thing, it's a uv-specific bug, not related to plugins or not... there's a fix on master and v4.1-stable.

**Comment by zbroyar** [comment]
Protocol init problem is fixed. Thanks a lot! :-)

About building problem: I checked twice on both systems and I don't see any unexpected copies of LWS libs. Since this is not critical for me I will not investigate the issue further. At least for now. Thanks again.

**Comment by lws-team** [comment]
Thanks for the bug report about the libuv... on the other thing since LWS_MAX_SMP seems implicated, you can try to make sure that's 1.
