### ISSUE TITLE
lws_client_connect_via_info  can be called twice to create two websockets connections?

### ISSUE THREAD

**Issue by Ssscy** [warmcat/libwebsockets#2042]
Hi,
I want to know 
1. One `struct lws_context `can only  create one `struct lws` by ` lws_client_connect_via_info()`?
2. Can I create multiple connections and only use one `struct lws_context` , one loop `lws_service(context,0);`  seems like:
```
struct lws *wsi = lws_client_connect_via_info(&con_info);
wsi = lws_client_connect_via_info(&con_info);
while(1){
    lws_service(context,0);
}
```
I tried,but it doesn't work.
I only receive one `LWS_CALLBACK_PROTOCOL_INIT` and can't connect to server

Look forward to your reply，thanks very much

**Comment by lws-team** [comment]
No you can have as many concurrent connections as you like in one context... client, server or any mix.

See https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi
