### ISSUE TITLE
Process level connection isolation

### ISSUE THREAD

**Issue by RichardAH** [warmcat/libwebsockets#2043]
We have a websocket application that has some tight security constraints, and we'd like to `fork()` immediately after `accept()` ideally with all other `FD`'s being closed in the child. The child process would go on to exclusively handle that connection including all the SSL overhead / processing and websocket frame buffering and management... the parent process would forget the connection ever existed other than keeping a count of child processes (and turning away new connections when there are too many children).

It seems like this should be possible with libwebsockets but `accept()` is buried deep in the code. Is there a straight forward way to do this, if not can it be added?

**Comment by lws-team** [comment]
> The child process would go on to exclusively handle that connection including all the SSL overhead / processing and websocket frame buffering and management... the parent process would forget the connection ever existed other than keeping a count of child processes 

IIUI you can do this already by something like this flow...

 - hook `LWS_CALLBACK_FILTER_NETWORK_CONNECTION` in protocols[0]

 - in the callback, you can recover the accepted `fd` by casting `in`.  To avoid forking in this awkward place, you can 1) `dup()` the fd and stash it in a linked-list, 2) use an lws_sul to schedule your own callback in +1us (ie, next time around the event loop), and then 3) reply nonzero rejecting the connection attempt cleanly and closing the original fd.

 - in the lws_sul callback in your code, you go through the linked-list of stashed fds and fork() for each one, passing the fd number in a temp inherited by the fork

 - in the original process, close the stashed fd and remove from the linked-list

 - in the fork you exit and then destroy the inherited lws_context and make your own new one, prepared with certs etc just for this fd

 - adopt the stashed linked list head fd into your new lws_context that only exists for that guy

it's not 100% clear how to destroy the inherited lws_context in the fork from inside it, but there should be a clean way.

**Comment by RichardAH** [comment]
> > The child process would go on to exclusively handle that connection including all the SSL overhead / processing and websocket frame buffering and management... the parent process would forget the connection ever existed other than keeping a count of child processes
> 
> IIUI you can do this already by something like this flow...
> 
> * hook `LWS_CALLBACK_FILTER_NETWORK_CONNECTION` in protocols[0]
> * in the callback, you can recover the accepted `fd` by casting `in`.  To avoid forking in this awkward place, you can 1) `dup()` the fd and stash it in a linked-list, 2) use an lws_sul to schedule your own callback in +1us (ie, next time around the event loop), and then 3) reply nonzero rejecting the connection attempt cleanly and closing the original fd.
> * in the lws_sul callback in your code, you go through the linked-list of stashed fds and fork() for each one, passing the fd number in a temp inherited by the fork
> * in the original process, close the stashed fd and remove from the linked-list
> * in the fork you exit and then destroy the inherited lws_context and make your own new one, prepared with certs etc just for this fd
> * adopt the stashed linked list head fd into your new lws_context that only exists for that guy
> 
> it's not 100% clear how to destroy the inherited lws_context in the fork from inside it, but there should be a clean way.

Thanks for the detailed reply! I will have a go

**Comment by lws-team** [comment]
IF there are problems feel free to continue here, but closing since nothing for me to do about it.
