### ISSUE TITLE
connect fail

### ISSUE THREAD

**Issue by helloword010** [warmcat/libwebsockets#2047]
I got this error when i tried to connect to a host .  i haved compared my code with the exampls very carefulily but i found nothing.
![image](https://user-images.githubusercontent.com/30803413/93155303-5a186980-f738-11ea-9e43-1730a7bf0354.png)
![image](https://user-images.githubusercontent.com/30803413/93155761-6224d900-f739-11ea-9522-c4882f4dbc6a.png)

what wrong things that i have do?   
i use the master version
[out.log](https://github.com/warmcat/libwebsockets/files/5222144/out.log)
[make.log](https://github.com/warmcat/libwebsockets/files/5222149/make.log)

**Comment by lws-team** [comment]
You show a backtrace but not the error itself... what is on client-handshake.c:620?

The minimal examples work?  If so the answer is to align your code to what they do until it works.

**Comment by helloword010** [comment]
> You show a backtrace but not the error itself... what is on client-handshake.c:620?
> 
> The minimal examples work? If so the answer is to align your code to what they do until it works.

The examples  in localhost work well.but when i change the  hostname  and port by my own is always dump.it corrupt in lws_client_connect_via_info（）.
![image](https://user-images.githubusercontent.com/30803413/93176695-39fe9f80-f764-11ea-86aa-b2c37e94f9c1.png)
and here is the code client-handshake.c:620

**Comment by lws-team** [comment]
> but when i change the hostname and port by my own is always dump.it corrupt in

This problem is coming if you use, eg, lws-minimal-ws-client and ONLY change the address to connect to?

**Comment by lws-team** [comment]
... what's coming from the lws logging, not the cmake or make log?

Did you do `sudo make install` after building lws?

What is your platform?

**Comment by helloword010** [comment]
> ... what's coming from the lws logging, not the cmake or make log?
> 
> Did you do `sudo make install` after building lws?
> 
> What is your platform?

my platform is centos 7.5 . i compile lws by default ,just cmake .   make , make install  with root.   Okay  i will read the manual  carefully  .  All in all, my question is how to compile a lws suitable for me, I just need to connect to a third-party server through websocket, no certificate is required

**Comment by lws-team** [comment]
Just the cmake defaults are fine for that.  The point is if the examples work, take the approach to modify those step by step and check it still works every time.

Feel free to continue the issue but closing since no lws problem.
