### ISSUE TITLE
Failed cross compile iOS 14: Macro redefined

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#2059]
Hello, I try cross compile to iOS 14, and got some errors:
```
private-lib-plat-unix.h:176:9: error: 'MSG_NOSIGNAL' macro redefined [-Werror,-Wmacro-redefined]
```
previous definition is here:
```
iPhoneSimulator14.0.sdk/usr/include/sys/socket.h:584:9
```
sys/socket.h:
```
#if __DARWIN_C_LEVEL >= 200809L
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
#endif /* __DARWIN_C_LEVEL */
```

If I undef or ignore the build error, it's working. however I don't know what side effects?
https://github.com/warmcat/libwebsockets/blob/c3c03ca6dbfa6d4ceae28685f70f321ea7e23b49/lib/plat/unix/private-lib-plat-unix.h#L186

```
/*
 * Mac OSX as well as iOS do not define the MSG_NOSIGNAL flag,
 * but happily have something equivalent in the SO_NOSIGPIPE flag.
 */
#ifdef __APPLE__
#undef MSG_NOSIGNAL
#define MSG_NOSIGNAL SO_NOSIGPIPE
#endif
```

**Comment by lws-team** [comment]
So is there an official way to check at the C compiler if it's ios14+?

Like, `#if IOS_SDK_VER > 14` or somesuch?

**Comment by lws-team** [comment]
... I don't actually understand why this has a problem, we #undef it before we define it... in what sense is there a "macro redefined" in the code you pasted?

It builds OK on slightly earlier iOS SDK

https://libwebsockets.org/sai/index.html?task=18ea38b01f587229158f20b7f0c248f017d74fbf3ed052677366a3fedd624fa3

**Comment by caobug** [comment]
Yes, I added `#undef MSG_NOSIGNAL` before #define, it will normal build.

xcode 11.x is ok, just can't build on xcode 12.

I'm trying to find the real reason.

**Comment by lws-team** [comment]
Oh I did not understand you added the #undef... it's probably OK to just do that then.  I am worrying that it builds OK on 11.5 beta so we shouldn't break it.  I am guessing the real reason is they added a define for it in their SDK where there was not any on 11.5.

I'll add a patch for the #undef later.

**Comment by lws-team** [comment]
Thanks... I updated my mac mini that does to CI to xcode 12 and after your undef patch he's also building fine now on that

https://libwebsockets.org/sai/index.html?task=926bc2f352e3b1dc2e6db23a03fe6aa015b2fd2a967e57016ea5c4febeee9bbb
