### ISSUE TITLE
[question] In lws_client_connect_via_info ssl_ca_filepath?

### ISSUE THREAD

**Issue by BurakOzkan** [warmcat/libwebsockets#2062]
[question] In lws_client_connect_via_info, how can i configure ssl_ca_filepath ?

**Comment by lws-team** [comment]
That's a member of a vhost.  You create a vhost (which has the corresponding SSL_CTX created) and then bind the client connection to the vhost whose SSL_CTX you want the connection to use

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n117

**Comment by BurakOzkan** [comment]
thank u
I'm implementing a client websocket.I just want to use external CA certificate or certificates(My central system websocket CA_Root cert.) to verify 
 server cert(Central System cert).




`   info_client.ssl_ca_filepath = "RootCA_RSA.pem";
`

but not work

[2020/09/24 12:16:09:4980] NOTICE: Initial logging level 7
[2020/09/24 12:16:09:4981] NOTICE: Libwebsockets version: 2.1.0 unknown-build-hash
[2020/09/24 12:16:09:4981] NOTICE: IPV6 not compiled in
[2020/09/24 12:16:09:4982] NOTICE: libev support not compiled in
[2020/09/24 12:16:09:4982] NOTICE: libuv support compiled in but disabled
[2020/09/24 12:16:09:4984] NOTICE:  Threads: 1 each 1024 fds
[2020/09/24 12:16:09:4985] NOTICE:  mem: platform fd map:  4096 bytes
[2020/09/24 12:16:09:4987] NOTICE:  Compiled with OpenSSL support
[2020/09/24 12:16:09:5194] NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 off
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 21 LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS 
[2020/09/24 12:16:09:6667] NOTICE:  mem: per-conn:          464 bytes + protocol rx buf
[2020/09/24 12:16:09:6668] NOTICE:  canonical_hostname = am335x-evmsk
[2020/09/24 12:16:09:6669] NOTICE: lws_protocol_init
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 27 LWS_CALLBACK_PROTOCOL_INIT 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 35 LWS_CALLBACK_LOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 32 LWS_CALLBACK_ADD_POLL_FD 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 36 LWS_CALLBACK_UNLOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 35 LWS_CALLBACK_LOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 34 LWS_CALLBACK_CHANGE_MODE_POLL_FD 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 36 LWS_CALLBACK_UNLOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 29 LWS_CALLBACK_WSI_CREATE 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 35 LWS_CALLBACK_LOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 34 LWS_CALLBACK_CHANGE_MODE_POLL_FD 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 36 LWS_CALLBACK_UNLOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 35 LWS_CALLBACK_LOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 34 LWS_CALLBACK_CHANGE_MODE_POLL_FD 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 36 LWS_CALLBACK_UNLOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 35 LWS_CALLBACK_LOCK_POLL 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 34 LWS_CALLBACK_CHANGE_MODE_POLL_FD 
WARN:callback_locus_client()@401: CLIENT: UNHANDLED REASON: 36 LWS_CALLBACK_UNLOCK_POLL 
**[2020/09/24 12:16:09:7070] ERR: SSL connect error 336134278: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed**
ERR:callback_locus_client()@300: CLIENT: LWS_CALLBACK_CLIENT_CONNECTION_ERROR
conn error.........

**Comment by lws-team** [comment]
This is too old to care about

> Libwebsockets version: 2.1.0

> `ssl_ca_filepath`

There are two SSL_CTX in the vhost, one for server connections and one for client connections.  That is for the server one.  Look at 

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n487

for the client one.
