### ISSUE TITLE
network disconnect callback

### ISSUE THREAD

**Issue by pinguo-wangqinlong** [warmcat/libwebsockets#2068]
hi, dear author，sorry to disturb you . I want to listen network disconnection messages. Is there a way in libwebsocket? I did not find it

**Comment by lws-team** [comment]
Lws doesn't monitor network interface states, it just uses POSIX socket apis to send stuff around.

If you want to add platform-specific monitoring, like netlink for linux, patches are welcome.

**Comment by pinguo-wangqinlong** [comment]
> Lws doesn't monitor network interface states, it just uses POSIX socket apis to send stuff around.
> 
> If you want to add platform-specific monitoring, like netlink for linux, patches are welcome.

I mean if I disconnect from the network, I can’t receive any callback message, is there a way to receive the lws closed message?

**Comment by lws-team** [comment]
I know what you meant, but there is no "the network".  There are just network interfaces that may be link-up or link-down, logically up or down, configured or not, and in the routing table or not.

POSIX sockets do not know about that, if the OS responds to a particular network interface linking down by closing sockets, lws will do the close flow.  If not, lws is not told about anything happening at socket level until much later, if ever.

If you care about network interface state (if you realize that is what you are talking about) you can monitor it in platform-specific ways like netlink, for linux.  If you want to add support for it, great, send patches.

**Comment by pinguo-wangqinlong** [comment]
sorry to disturb you again. I understand what you mean and pls check this issue

https://github.com/warmcat/libwebsockets/issues/756

Because we use okhttp send wss message on the android platform, we can immediately receive the websockets status change when we disconnect from the network. But I tested libwebsocket and found that there is no callback after disconnecting from the network. 

Can the heartbeat mechanism achieve this?

**Comment by lws-team** [comment]
> Because we use okhttp send wss message on the android platform,

Yeah someone has done the work so it gets notified about platform-specific network interface and / or routing table changes.  Eg, if it sees no gateway exists out to the internet in the routing table, it might decide to kill all its connections.  How you get informed about that is platform-specific and not in the POSIX sockets api.

You can use lws connection validity stuff to control how long it will tolerate not seeing transactions passing before assuming the connection is broken and closing the connection.  But it won't be the same result as getting informed about changes using a platform-specific api.

**Comment by pinguo-wangqinlong** [comment]
Okay, thanks for your reply . I understand. I saw that in answering other people’s questions, you mentioned using ping pong to detect whether we can also use ping pong to detect network connectivity？
