### ISSUE TITLE
Question about message passing from connection to connection

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2069]
Hi,

Let's say, I have few foreign loops in parallel threads(as in ws-server-threads-foreign-smp basic example), few logical groups of connections over separate rings and I have written a message into the target ring. What is the best way to let know all connections over this ring about the new data?

Thanks in advance.

**Comment by lws-team** [comment]
The details depend on exactly what you want, but generally, write your data to a shared area and then call lws_cancel_service().  That will wake each pt / loop separately and bring the service thread to your callback LWS_CALLBACK_EVENT_WAIT_CANCELLED.  From there you can use any normal lws api in the pt thread context.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads-foreign-smp/protocol_lws_minimal.c#n283

**Comment by zbroyar** [comment]
Thanks :-)
