### ISSUE TITLE
Can we pass File desc or unix domain stream socket desc over websockets?

### ISSUE THREAD

**Issue by gupta05** [warmcat/libwebsockets#2070]
Hi Andy,

Just wanted to check if there is existing support to pass file desc from server to client over the websocket protocol? something similar SCM_RIGHTS using which we can pass fd over unix domain socket? 

Thank you,

**Comment by lws-team** [comment]
IIUI SCM_RIGHTS is a kernel feature that only works over unix domain sockets.  The kernel doesn't support it over tcp / websocket.

Lws supports Unix Domain Sockets for client and server, but you would have to add something to do the SCM_RIGHTS message after the connection was established.
