### ISSUE TITLE
Server hanging with POST and Connection: close

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2072]
Hello, thank you for your great library.
I have a raspberry with a libwebsockets server running and available from the net. I get regularly http requests sent automatically by bots scanning the net. Some of these requests are crashing my server ie. no subsequent requests are processed and ctrl+c do not exit the program.

I managed to reproduce the crash with _libwebsockets-test-server_. Unlike my server which crashes every time, the test server only crashes certain times.

The request is:
`wget -d --post-data 'user=foo&password=bar' http://xxx.xxx.xxx.xxx:80 --header="Connection: close"`

When hanging, the last request receives a response (as expected) but all subsequent requests are left without response and the server do not exit with ctrl+c. 

I hope you can reproduce it and find a solution.
Regards.

**Comment by lws-team** [comment]
This one-liner should solve it

https://libwebsockets.org/git/libwebsockets/commit/include?id=8c88b857a92d562b271a8aece70dc9a453d25f37

but I could not see how it could "crash".

**Comment by Piero01** [comment]
Thanks, it's working.
