### ISSUE TITLE
LWS_WITH_SYS_SMD

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2073]
Hi,

JFYI: when building LWS on Windows this option is ON by default and require pthread.h which leads to compile-time errors.

**Comment by lws-team** [comment]
You can build lws with pthreads on windows

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

in the case you don't, SMD works fine without pthreads if you are only using it from the event loop thread context, and it's useful inside lws.  I pushed a patch on master that NOPs out the lws_mutex stuff if no pthreads header, I am not sure if that's enough or not.

**Comment by zbroyar** [comment]
OK, thanks.

Another problem: I used vcpkg (really nice way to install opensource packages on Win, btw) to install OpenSSL on my Windows machine and I have OPENSSL_ROOT_DIR pointing to c:/vcpkg/installed/x86-windows. CMake finds OpenSSL and says that configuration is OK.

But then on build stage I see lots of errors like: 
C:\Users\m\source\repos\libwebsockets\include\libwebsockets/lws-genhash.h(85,18): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st' [C:\Users\m\source\repos\libwebsockets\build\lib\websockets.vcxproj]
  windows-file.c

What am I doing wrong here? Did I miss something?

**Comment by lws-team** [comment]
Your lws can't build due to the broken cmake options you are giving it.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md
