### ISSUE TITLE
When permessage-deflate is used, LWS_CALLBACK_CLIENT_RECEIVE_PONG callbacks aren't called

### ISSUE THREAD

**Issue by kcbanner** [warmcat/libwebsockets#2076]
It seems that when `permessage-delflate` is used on a connection, the `LWS_CALLBACK_CLIENT_RECEIVE_PONG` callback doesn't come through. It seems to be due to: https://github.com/warmcat/libwebsockets/blob/150d431395d16539f9b827a78b75a971f28f56c6/lib/roles/ws/client-parser-ws.c#L556 

When the extension sees a non-compressed message, it returns `PMDR_DID_NOTHING`, which triggers the calling code to early out and not call the callback. 

I'm able to confirm that when I disable `permessage-deflate` (same client, but disable the extension on my server), the pong callbacks are received.

**Comment by lws-team** [comment]
Please try current master, there's a patch that attempts to solve that.

**Comment by kcbanner** [comment]
Confirming this is now fixed on master. Cheers!
