### ISSUE TITLE
how to process the http post

### ISSUE THREAD

**Issue by qq1033731787** [warmcat/libwebsockets#2083]
Hi,
my version is 4.1.2
when i sent a command like this, ` curl -d '{"action":"start","id":0,"to":"127.0.0.1:8005","to_id":"00000001-0002-4003-a004-000000000001"}' -X PUT 127.0.0.1:8005/api/json`, something was wrong.

The problem is when the lws_http_action called and run the line 1553 in lib/roles/http/server/server.c  `hit = lws_find_mount(wsi, uri_ptr, uri_len);` ,hit will be NULL because in function lws_find_mount, a put command not match the condition in  lib/roles/http/server/server.c  line 803. It will cause the 'user' be NULL.

so how should i process the http put?
here is my method

> LwsCallbackStatus lws_callback_OnHttpConnection(struct lws *wsi, void *user, void *in, size_t len) {
  ZF_LOGV("[SERVER] A client http is connected.");
  LwsConnectionSessionObject *session_object = (LwsConnectionSessionObject *)user;
  if ((lws_hdr_total_length(wsi, WSI_TOKEN_POST_URI) || lws_hdr_total_length(wsi, WSI_TOKEN_PUT_URI)) && !strncmp((const char *)in, kHttpApiJsonUri, strlen(kHttpApiJsonUri))) {
    session_object->connection = LwsConnection__Create(wsi);
    assert(session_object->connection);
  }
  http_request_info = (lws_http_request_info *)dcalloc(1, sizeof(lws_http_request_info));
  return (LwsCallbackStatus){false, 0};
}

**Comment by lws-team** [comment]
What version of lws?  Still exists on master lws?

Mentioning lws line numbers is good, but you must tell the filename and exact lws version, or nobody can go look at the right line.

**Comment by qq1033731787** [comment]
version

> What version of lws? Still exists on master lws?
> 
> Mentioning lws line numbers is good, but you must tell the filename and exact lws version, or nobody can go look at the right line.



> What version of lws? Still exists on master lws?
> 
> Mentioning lws line numbers is good, but you must tell the filename and exact lws version, or nobody can go look at the right line.

Discription updated. Version 4.1.2, the codes mentioned are in lib/roles/http/server/server.c  and still exest

**Comment by lws-team** [comment]
So in the first lws code you mention, if you add a clause in here

```
                             lws_hdr_total_length(wsi, WSI_TOKEN_GET_URI) ||
                             lws_hdr_total_length(wsi, WSI_TOKEN_POST_URI) ||
                             lws_hdr_total_length(wsi, WSI_TOKEN_HEAD_URI) ||
```

to also allow `WSI_TOKEN_PUT_URI`, it's enough to solve it?

**Comment by qq1033731787** [comment]
It works. Thanks.

**Comment by lws-team** [comment]
Great, I will push a patch in a bit for PUT / PATCH / DELETE there, thanks for letting me know.
