### ISSUE TITLE
Is there any method to know if the http request contains the body part when I receive LWS_CALLBACK_HTTP?

### ISSUE THREAD

**Issue by Halajohn** [warmcat/libwebsockets#2084]
Because clients could send PUT/POST to the server with the data attached to the address part or to the body part, and if the client attach the data to the address part, and the request doesn't contain a body, then LWS would not give me LWS_CALLBACK_HTTP_BODY (and LWS_CALLBACK_HTTP_BODY_COMPLETION, neither).

So the scenarios would be:

1) PUT/POST without a body

    LWS_CALLBACK_HTTP    ==> I have to put the data handling logic (1) here to process the request in this scenario. (because there will be no more callbacks)

2) PUT/POST with a body

    LWS_CALLBACK_HTTP
    LWS_CALLBACK_HTTP_BODY
    LWS_CALLBACK_HTTP_BODY_COMPLETION ==> I have to put the data handling logic (2) here to process the request in this scenario. (because I receive the whole request info when I receive this callback)

So I need a method to enable me to know which data handling logic (1 or 2) should be used to process the request. Is there any method to let me know the HTTP request is received completely?

It seems "wsi->http.rx_content_remain" is what I need, but I could not access this field because the whole struct is in a .c file, rather than in a .h file. And there is no function to access this field, too.

The method I could think about is to use lwd_hdr_copy() to check if the WSI_TOKEN_HTTP_CONTENT_LENGTH > 0 or not to determine if there is a body or not in the LWS_CALLBACK_HTTP callback, so that I could know if there will be LWS_CALLBACK_HTTP_BODY to come. I wonder if this is the correct way to do this? or is there any more official or correct way to get/know this?

**Comment by lws-team** [comment]
Http is a thrown-together protocol from 35 years ago... it can be ambiguous about what's in the request, it's not mandatory to send a content-length, instead you can just keep sending body until you close the socket.

You should provide the headers (eg, by tcpdump) and we can discuss individual cases.

**Comment by Halajohn** [comment]
Thanks for the reply, and if this is true, how could you determine what is the correct time to send LWS_CALLBACK_HTTP_BODY_COMPLETION?

**Comment by lws-team** [comment]
> and if this is true

Please back up a bit... what I said is it CAN be ambiguous, it is NOT MANDATORY to send a content-length, instead you CAN just keep sending body until you close the socket.

Or, you can send a content-length, and the peer can count the bytes of body it gets until it known the request body is complete, and so send a BODY_COMPLETION.

Which of these situations are you making this issue about?  Who knows, because you do not provide the related headers.

Hence: 

> You should provide the headers (eg, by tcpdump) and we can discuss individual cases.

Make sense?

**Comment by Halajohn** [comment]
Because I can not control the http clients in my use cases, I would like to know if there is some _general_ method to handle _all_ the situations during http PUT/POST w/ data in address or in body. Actually, my data is JSON, so I need to know if I will not get a body or when to completely get a full body to determine if I can successfully parse the JSON data or determine if there is a field in body has the same name with a field in the address part.

As you said, I think I need to have some ways (through doc or through providing a client SDK) to restrict the clients' behavior, so that they always put a content-length header field, or something like.

I'll provide some header examples asap when I test more and get more results. Thank you.

**Comment by lws-team** [comment]
Lws just reacts to what it was sent... if you find a case where it can and ought to do something better, we can discuss if we have the headers to make the situation clear.
