### ISSUE TITLE
send twice http command

### ISSUE THREAD

**Issue by qq1033731787** [warmcat/libwebsockets#2085]
Hi,
my version is 4.1.2.
The program  crashed when i sent twice post command like `curl -d '{"action":"start","id":0,"to":"127.0.0.1:8005","to_id":"00000001-0002-4003-a004-000000000001"}' -X PUT 127.0.0.1:8005/api/json`.
When i sent the command at the first time, server receive the correct message. When i sent the command at the second time,
i received the message like `{"action":"start","id":0,"to":"127.0.0.1:8005","to_id":"00000001-0002-4003-a004-000000000001"}dy></html>`. It is obvious that server received the redundant byte `dy></html>`.
Actual, i test the program in two computer, the same condition not appears in the second computer. When i listen the port, i found the first computer will reuse the connection but the second computer will create a new connection when send a command.
So, what caused this different way and how can i solve the problem?

**Comment by lws-team** [comment]
Does this problem exist on an unchanged, or lightly-changed minimal example?

**Comment by qq1033731787** [comment]
No, i write a callback in my project like `LwsCallbackStatus lws_callback_OnHttp(struct lws *wsi, void *user, void *in, size_t len, enum lws_callback_reasons lws_callback_reason)`, and check the received message from 'in' .

**Comment by lws-team** [comment]
I can help you if it's a problem in lws or the examples.  But you'll have to debug it yourself if it only happens with your code.

Notice that the callback has a length to show how much of `in` is valid.  You will read garbage beyond that.
