### ISSUE TITLE
VCPKG

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2086]
Hi,

I'm going to create PR to https://github.com/microsoft/vcpkg repo that will allow everyone there to use LWS with foreign libuv loop fixes. I'd be grateful if you recommend commit ID, branch or tag I shall use for the PR.

Thanks in advance.

**Comment by lws-team** [comment]
The best approach atm is probably (you should confirm it works for you, at least the patches are backported there...) v4.1-stable branch.  That will continue to receive fixes for stuff that exists in v4.1, at least until v4.2, but no new features.

**Comment by zbroyar** [comment]
I confirm it works in my setup but I don't see libuv-related commits in v4.1-stable now.

**Comment by lws-team** [comment]
Hum I confused the windows event loop changes for this... let me have a look at backporting

**Comment by lws-team** [comment]
Can you try _temp branch, which is v4.1-stable with the additional patches from master?  If it's OK I'll update v4.1-stable with it.

**Comment by zbroyar** [comment]
On it. Will let you know soon.

**Comment by zbroyar** [comment]
Everything looks good. Please, update v4.1-stable.

**Comment by lws-team** [comment]
It's pushed and tagged v4.1.3
