### ISSUE TITLE
Memory leak without calling functions.

### ISSUE THREAD

**Issue by Bunpasi** [warmcat/libwebsockets#2092]
This code causes a memory leak. The functions aren't even called. Is this a bug?

```
#define _CRTDBG_MAP_ALLOC

#include <crtdbg.h>
#include <libwebsockets.h>

void f(){
	lws_context_creation_info info;
	lws_create_context(&info);
}

int main(){
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
	return 0;
}
```

This is the result.

```
Detected memory leaks!
Dumping objects ->
{89} normal block at 0x000001B3307FAFF0, 32 bytes long.
 Data: <                > 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{88} normal block at 0x000001B3307FB290, 32 bytes long.
 Data: <                > 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
```

Commenting out `lws_create_context(&info);` removes the leak. Could someone have a look at this please?

**Comment by lws-team** [comment]
```
void f(){
	lws_context_creation_info info;
	lws_create_context(&info);
}
```

So... info is full of undefined trash.

As it shows in all the minimal examples, if you create the info struct on the stack, you must memset it to 0 first.

**Comment by Bunpasi** [comment]
OK. I'll try. I took an example of a different site. My mistake. Thank you!

**Comment by Bunpasi** [comment]
This time I copy-pasted `minimal-ws-client-ping.c` and made these adjustments to detect the leaks. I had the same results. I tried the Binance example as well.

On top of the page.
```
#define _CRTDBG_MAP_ALLOC
#include <crtdbg.h>
```

First statement in `main`.
```
_CrtSetDbgFlag ( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF );
```

Any advise?

**Comment by lws-team** [comment]
Your leak detecting method seems not as useful as valgrind, it doesn't tell you what allocated the leak.  Valgrind gives you a backtrace up to the malloc responsible.

Since you don't run any lws code, I dunno what code in lws you imagine has a 'bug', then it's your platform doing the allocation, not lws.
