### ISSUE TITLE
is this a code bug in lib/event-libs/libevent/libevent.c

### ISSUE THREAD

**Issue by bbqz007** [warmcat/libwebsockets#2095]
230 ptpr->w_sigint.watcher = evsignal_new(loop, SIGINT,
231						  lws_event_sigint_cb, pt);

157 void
158 lws_event_sigint_cb(evutil_socket_t sock_fd, short revents, void *ctx)
159 {
160 	struct lws_context_per_thread *pt = ctx;
161 	struct event *signal = (struct event *)ctx;

is that a bug in line 161.
may it be struct event *signal = pt_to_priv_event(pt)->w_sigint.watcher ?

**Comment by lws-team** [comment]
Thanks, it's some dust left from the big patch about event libs in plugins from a few weeks ago.  Your fix is pushed on main + v4.1-stable
