### ISSUE TITLE
lws automatically closes after a period of time

### ISSUE THREAD

**Issue by Ripple-qin** [warmcat/libwebsockets#2096]
Hi,sir

sorry to disturb you . 
I have a problem and hope to get your help
After successfully connecting to the wss server through lws, the client no longer sends other signaling to the server. A few minutes later, lws returns a message to close the link. Can you give me some advice?

```
Tue Oct 20 14:45:10 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Tue Oct 20 14:45:10 2020 INFO: received 0 byte ping, sending pong
Tue Oct 20 14:45:10 2020 INFO: issuing pong 0 on wsi 0x10a045570
Tue Oct 20 14:45:10 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Tue Oct 20 14:46:12 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Tue Oct 20 14:46:12 2020 INFO: received 0 byte ping, sending pong
Tue Oct 20 14:46:13 2020 INFO: issuing pong 0 on wsi 0x10a045570
Tue Oct 20 14:46:13 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Tue Oct 20 14:47:15 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Tue Oct 20 14:47:15 2020 INFO: received 0 byte ping, sending pong
Tue Oct 20 14:47:15 2020 INFO: issuing pong 0 on wsi 0x10a045570
Tue Oct 20 14:47:15 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Tue Oct 20 14:48:23 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Tue Oct 20 14:48:23 2020 INFO: received 0 byte ping, sending pong
Tue Oct 20 14:48:33 2020 INFO: rops_handle_POLLIN_ws: LWS_SSL_CAPABLE_ERROR
Tue Oct 20 14:48:33 2020 INFO: __lws_close_free_wsi: 0x10a045570: caller: close_and_handled

----------------------   75 is LWS_CALLBACK_CLIENT_CLOSED  ---------------
----------------------   1  is LWS_CALLBACK_CLIENT_CONNECTION_ERROR  ---------------

Tue Oct 20 14:48:33 2020  WebSocketWrapper (0x10a166e80) Unhandled websocket event: 75
Tue Oct 20 14:48:33 2020  WebSocketWrapper (0x10a166e80) onConnectionClosed, state: 1 ...
Tue Oct 20 14:48:33 2020  onConnectionClosed, WebSocketWrapper (0x10a166e80) is closing by server.
```

we use boringssl to build lws .

```
$ mkdir build
$ cd build
$ cmake ..
$ cmake .. -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_OPENSSL_LIBRARIES="xxx/xxx/libcrypto.dylib;xxx/xxx/libssl.dylib"    -DLWS_OPENSSL_INCLUDE_DIRS=xxx/boringssl/include/  -DLWS_WITH_BORINGSSL=1 -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_FLAGS=-w -DLWS_WITH_NETLINK=1
$ make
```

**Comment by lws-team** [comment]
> Tue Oct 20 14:48:33 2020 INFO: rops_handle_POLLIN_ws: LWS_SSL_CAPABLE_ERROR

The server seems to have hung up on the client, after we returned a PONG for its PING.

**Comment by Ripple-qin** [comment]
Sometimes after an error occurs, the following information is printed

```
	if (wsi->validity_hup) {
		lwsl_info("%s: wsi %p: validity too old\n", __func__, wsi);
		__lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS,
				     "validity timeout");
		return;
	}

```

**Comment by Ripple-qin** [comment]
> > Tue Oct 20 14:48:33 2020 INFO: rops_handle_POLLIN_ws: LWS_SSL_CAPABLE_ERROR
> 
> The server seems to have hung up on the client, after we returned a PONG for its PING.

After we send the pong message, we still wait for the server's response information? Then this message timed out?

**Comment by Ripple-qin** [comment]
> > Tue Oct 20 14:48:33 2020 INFO: rops_handle_POLLIN_ws: LWS_SSL_CAPABLE_ERROR
> 
> The server seems to have hung up on the client, after we returned a PONG for its PING.

After we send the pong message, are we still waiting for the server's response information and then this message timed out?

**Comment by lws-team** [comment]
You seem to be mixing two different issues.

Only the guy who sent the PING can know that communications are working in both directions when he gets the PONG.  They guy sending the PONG doesn't actually have any evidence his PONG got through.

The client has to send his own PING requests and receive the PONG come back to be sure the connection works in both directions.

Look at how the minimal example http client sets the policy for sending PINGs and requiring PONGs

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n26
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n240

**Comment by Ripple-qin** [comment]
> You seem to be mixing two different issues.
> 
> Only the guy who sent the PING can know that communications are working in both directions when he gets the PONG. They guy sending the PONG doesn't actually have any evidence his PONG got through.
> 
> The client has to send his own PING requests and receive the PONG come back to be sure the connection works in both directions.
> 
> Look at how the minimal example http client sets the policy for sending PINGs and requiring PONGs
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n26
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n240

yes, I understand what you mean, I just don't understand why the pong message has been sent, but the server can still hunp up the connection?So, I just assume what news is still waiting。 
 How can the server suspend our lws after receiving the pong message?
Sorry for the unprofessional question。

**Comment by Ripple-qin** [comment]
> You seem to be mixing two different issues.
> 
> Only the guy who sent the PING can know that communications are working in both directions when he gets the PONG. They guy sending the PONG doesn't actually have any evidence his PONG got through.
> 
> The client has to send his own PING requests and receive the PONG come back to be sure the connection works in both directions.
> 
> Look at how the minimal example http client sets the policy for sending PINGs and requiring PONGs
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n26
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n240

yes, I understand what you mean, I just don't understand why the pong message has been sent, but the server can still hunp up the connection?So, I just assume what news is still waiting。
How can the server suspend our lws after receiving the pong message? Is it through the websocket protocol?
Sorry for the unprofessional question。

**Comment by lws-team** [comment]
I can't guess what the server feels... you have to look in the server logs.

He sends us 3 x PING in 5s in your log in your first post, it seems he doesn't understand we sent the PONG.

Do you have permessage-deflate enabled?  Then make sure you use latest main or v4.1-stable, there was a bug under those conditions fixed a couple of weeks ago

https://libwebsockets.org/git/libwebsockets/commit/minimal-examples/http-client?id=27964ddaf2463794c46a12fe597533d27639f2f2

**Comment by Ripple-qin** [comment]
Currently, I am using the latest master branch code.
There may be any restrictions on the server, I will check the server log, thank you for your patient answers

**Comment by Ripple-qin** [comment]
I retested the problem and printed the time
```
Wed Oct 21 17:26:30 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:26:30 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:26:30 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:26:30 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:30 2020 INFO: wsi->socket_is_permanently_unusable state = 
Wed Oct 21 17:26:30 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Wed Oct 21 17:26:30 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:30 2020 INFO: wsi->socket_is_permanently_unusable state =  
Wed Oct 21 17:26:30 2020 INFO: lws_ws_client_rx_sm: client 0x10a92ab00 received pong
Wed Oct 21 17:26:30 2020 INFO: _lws_validity_confirmed_role: wsi 0x10a92ab00: setting validity timer 5s (hup 0)
Wed Oct 21 17:26:30 2020 EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x10af6f010 to ext
Wed Oct 21 17:26:30 2020 EXTENSION: Ext RX returned 0
Wed Oct 21 17:26:30 2020 EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
Wed Oct 21 17:26:30 2020 EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
Wed Oct 21 17:26:30 2020 INFO: Client doing pong callback
WebSocketWrapper (0x10a847cd0) Unhandled websocket event: 9
Wed Oct 21 17:26:35 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:26:35 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:26:35 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:26:35 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:35 2020 INFO: wsi->socket_is_permanently_unusable state = 
Wed Oct 21 17:26:35 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Wed Oct 21 17:26:35 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:35 2020 INFO: wsi->socket_is_permanently_unusable state =  
Wed Oct 21 17:26:35 2020 INFO: lws_ws_client_rx_sm: client 0x10a92ab00 received pong
Wed Oct 21 17:26:35 2020 INFO: _lws_validity_confirmed_role: wsi 0x10a92ab00: setting validity timer 5s (hup 0)
Wed Oct 21 17:26:35 2020 EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x10af6f010 to ext
Wed Oct 21 17:26:35 2020 EXTENSION: Ext RX returned 0
Wed Oct 21 17:26:35 2020 EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
Wed Oct 21 17:26:35 2020 EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
Wed Oct 21 17:26:35 2020 INFO: Client doing pong callback
WebSocketWrapper (0x10a847cd0) Unhandled websocket event: 9
Wed Oct 21 17:26:40 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:26:40 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:26:40 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:26:41 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:41 2020 INFO: wsi->socket_is_permanently_unusable state = 
Wed Oct 21 17:26:41 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Wed Oct 21 17:26:41 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:41 2020 INFO: wsi->socket_is_permanently_unusable state =  
Wed Oct 21 17:26:41 2020 INFO: lws_ws_client_rx_sm: client 0x10a92ab00 received pong
Wed Oct 21 17:26:41 2020 INFO: _lws_validity_confirmed_role: wsi 0x10a92ab00: setting validity timer 5s (hup 0
Wed Oct 21 17:26:41 2020 EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x10af6f010 to ext
Wed Oct 21 17:26:41 2020 EXTENSION: Ext RX returned 0
Wed Oct 21 17:26:41 2020 EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
Wed Oct 21 17:26:41 2020 EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
Wed Oct 21 17:26:41 2020 INFO: Client doing pong callback
Wed Oct 21 17:26:46 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:26:46 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:26:46 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:26:46 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:46 2020 INFO: wsi->socket_is_permanently_unusable state = 
Wed Oct 21 17:26:46 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Wed Oct 21 17:26:46 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:46 2020 INFO: wsi->socket_is_permanently_unusable state =  
Wed Oct 21 17:26:46 2020 INFO: lws_ws_client_rx_sm: client 0x10a92ab00 received pong
Wed Oct 21 17:26:46 2020 INFO: _lws_validity_confirmed_role: wsi 0x10a92ab00: setting validity timer 5s (hup 0)
Wed Oct 21 17:26:46 2020 EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x10af6f010 to ext
Wed Oct 21 17:26:46 2020 EXTENSION: Ext RX returned 0
Wed Oct 21 17:26:46 2020 EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
Wed Oct 21 17:26:46 2020 EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
Wed Oct 21 17:26:46 2020 INFO: Client doing pong callback
WebSocketWrapper (0x10a847cd0) Unhandled websocket event: 9
Wed Oct 21 17:26:58 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:26:58 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:26:58 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:26:58 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:58 2020 INFO: wsi->socket_is_permanently_unusable state = 
Wed Oct 21 17:26:58 2020 EXTENSION: lws_ws_client_rx_sm:    This RX frame Final 1
Wed Oct 21 17:26:58 2020 INFO: lws_ws_client_rx_sm
Wed Oct 21 17:26:58 2020 INFO: wsi->socket_is_permanently_unusable state =  
Wed Oct 21 17:26:58 2020 INFO: lws_ws_client_rx_sm: client 0x10a92ab00 received pong
Wed Oct 21 17:26:58 2020 INFO: _lws_validity_confirmed_role: wsi 0x10a92ab00: setting validity timer 5s (hup 0)
Wed Oct 21 17:26:58 2020 EXTENSION: lws_ws_client_rx_sm: +++ passing 0 0x10af6f010 to ext
Wed Oct 21 17:26:58 2020 EXTENSION: Ext RX returned 0
Wed Oct 21 17:26:58 2020 EXTENSION: lws_ws_client_rx_sm: post inflate ebuf in len 0 / out len 0
Wed Oct 21 17:26:58 2020 EXTENSION: lws_ws_client_rx_sm: removing from draining ext list
Wed Oct 21 17:26:58 2020 INFO: Client doing pong callback
Wed Oct 21 17:27:07 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: scheduling validity check
Wed Oct 21 17:27:07 2020 INFO: rops_handle_POLLOUT_ws: issuing ping on wsi 0x10a92ab00: ws z\204
 h2: 0
Wed Oct 21 17:27:07 2020 INFO: lws_issue_raw: ssl_capable_write (6) says 6
Wed Oct 21 17:27:14 2020 INFO: lws_validity_cb: wsi 0x10a92ab00: validity too old
Wed Oct 21 17:27:14 2020 INFO: __lws_close_free_wsi: 0x10a92ab00: caller: validity timeout
```

I don't quite understand why the sending interval of the last two ping requests exceeds 10 seconds ？
I had set secs_since_valid_ping = 5， secs_since_valid_hangup = 10.

**Comment by lws-team** [comment]
Is there a way I can see the same problem coming with just a minimal example, like the minimal-http-client example?

**Comment by Ripple-qin** [comment]
You can close this issue first, and after I test it on the minimal example, , if there is still a problem, I will re-open it again

**Comment by lws-team** [comment]
OK.  Eg, lws event loop blocked for a few seconds by user code will cause this.  But it's not an issue in lws then.

**Comment by Ripple-qin** [comment]
> OK. Eg, lws event loop blocked for a few seconds by user code will cause this. But it's not an issue in lws then.

Yes, thank you for your answer, it may be a problem with our server
