### ISSUE TITLE
lws_callback_on_writable() invoked sometimes make server  dump

### ISSUE THREAD

**Issue by helloword010** [warmcat/libwebsockets#2097]
In server code, i create a thread to start a lws client to connect a another server , it's not a single connection client. in another thread i invoke lws_client_connect_via_info to get a wsi, and invoked lws_callback_on_writable()  many times to send  peice of data .
we have more than 500 threads do things like this  .but sometimes it could make server down.

**Comment by helloword010** [comment]
the verison is v4.0.1

**Comment by lws-team** [comment]
> we have more than 500 threads do things like this

Okay... so how does that work, you make 500 lws_context?

How about making one lws_context and manage the 500 connections from lws event loop thread. Like, eg, all related examples show

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

**Comment by helloword010** [comment]
Yes, just only one lws_context,  connections saved in a static map.  I create a struct cantains connect state ,wsi,and other info . we found it by compare wsi and manage it.
when a request come , server create a thread ,this thread invoke lws_client_connect_via_info to get a wsi, and then send message to 
a third server

**Comment by lws-team** [comment]
OK... so the lws part can only get slow in his thread if too much to do... he can't kill your whole box.  And in himself, he can't stall the thread, he can just find it too hard to keep up.

I'd run it under valgrind + helgrind and look for locking problems... this slows it down further but it will let you know about any problem.

Conversely you can get better performance by building in `-DCMAKE_BUILD_TYPE=RELEASE` if not already.

**Comment by helloword010** [comment]
ok, i will try  as you say.

**Comment by lws-team** [comment]
I'm going to close this since nothing for me to do.  If some sign is coming it's an lws problem we can continue to discuss it.
