### ISSUE TITLE
How do i use mount-oringin?

### ISSUE THREAD

**Issue by asd617140123** [warmcat/libwebsockets#2098]
Hi ,
   I want to test "libwebsockets/minimal-examples/ws-server/minimal-ws-server/"  server sample.
and I use "mount-origin" folder to render web. 
   But I see web page that do not have effect.
Can you tell me how can I test folder in ws-server code?

thanks.

**Comment by lws-team** [comment]
The example mount definition says to find the directory in ./, it means you must run the example actually from the example dir that contains ./mount-origin/.  Is that what you are doing?

**Comment by asd617140123** [comment]
I think my fail reason is about my dir location is not correct.
thanks your reply.
You can close the issue.
