### ISSUE TITLE
Do this work for the Tizen platform

### ISSUE THREAD

**Issue by TheisStellaCare** [warmcat/libwebsockets#2100]
Hello. I was wondering if this work's for the Tizen platform?

**Comment by lws-team** [comment]
Yes, it is already part of the official Tizen

https://build.tizen.org/package/show/Tizen:4.0:Unified/libwebsockets

**Comment by TheisStellaCare** [comment]
That is Version 2.3. So 3 years old

**Comment by lws-team** [comment]
They should update it... but they put it in there in the first place, I can't update their tree.

You should be able to build current lws against tizen so long as you can run lws cmake.  If problems let me know.

**Comment by TheisStellaCare** [comment]
So how would i go about Compiling it. I could just put it in my project dir and including it in the tizen compiler and see if it works?

**Comment by lws-team** [comment]
... should you not better look at Tizen docs or their support for Tizen-specific question?

**Comment by lws-team** [comment]
Just a FYI, Tizen 6 from May has updated lws to a much more reasonable v3.2

https://docs.tizen.org/platform/release-notes/tizen-6-0-m1/
