### ISSUE TITLE
lws_client_connect_via_info（） error ：lws_dll2_add_sorted: Assertion `p != d' failed.

### ISSUE THREAD

**Issue by helloword010** [warmcat/libwebsockets#2102]
we create a context to manage multity connections that  works for others threads.  when we need a connection we invoke  lws_client_connect_via_info（）then we will get a wsi ,we mark it in wy own struct instance. It works fine with just single connection.
but when working  with server connects ，it will dump . The different things is just work for 4 hours or 6 hours.
we consider this library as a black box. we don't know a lot about rfc6645 protocol. So we feel confuse,when we get this error 
![image](https://user-images.githubusercontent.com/30803413/97400533-3d23a880-192a-11eb-94c3-a676e320fbdf.png)
![image](https://user-images.githubusercontent.com/30803413/97400569-4ca2f180-192a-11eb-8760-d8f230ebf423.png)
![image](https://user-images.githubusercontent.com/30803413/97400688-8673f800-192a-11eb-80df-f6bce7f52dc3.png)

It dump in the same fuction , but error is defferent.Can you tell me how to solve these problems or the direction to solve them?

**Comment by lws-team** [comment]
Everything is in a single thread?

**Comment by helloword010** [comment]
![image](https://user-images.githubusercontent.com/30803413/97401406-ba9be880-192b-11eb-9b5f-cdbd6d252d10.png)and this error

**Comment by helloword010** [comment]
No, connect create in anoter thread. we have pakage a class called ws_operator . it has a thread to run lws_service  and  some fuctions to do something. such as create connection,  invoke writeable.

**Comment by helloword010** [comment]
> Everything is in a single thread?

No, connect create in anoter thread. we have pakage a class called ws_operator . it has a thread to run lws_service  and  some fuctions to do something. such as create connection,  invoke writeable.

**Comment by lws-team** [comment]
You cannot do that, because lws is not threadsafe.

**Comment by lws-team** [comment]
>> No, connect create in anoter thread. 
> You cannot do that, because lws is not threadsafe.

I thought you mean creating the client connection api in a different thread than the event loop, which you cannot do.

But reading again I am not sure if you mean just whole of lws in its own thread, which is OK so long as no other thread calls lws apis.

**Comment by helloword010** [comment]
> > > No, connect create in anoter thread.
> > > You cannot do that, because lws is not threadsafe.
> 
> I thought you mean creating the client connection api in a different thread than the event loop, which you cannot do.
> 
> But reading again I am not sure if you mean just whole of lws in its own thread, which is OK so long as no other thread calls lws apis.

![image](https://user-images.githubusercontent.com/30803413/97406280-f2a72980-1933-11eb-8592-443b5d972f70.png)   
![image](https://user-images.githubusercontent.com/30803413/97406345-0eaacb00-1934-11eb-9811-013f1f543b96.png)

here it is the class define and connect function

**Comment by lws-team** [comment]
Showing me pieces of code doesn't really help understand your whole system.

The issue here is the assert is indicating a linked-list in lws is trashed, it should not be possible to do that if everything running serialized in one thread.  It's possible to happen if two threads collide in changing the linked-list.

So is it that only the event loop thread that owns the context calls lws apis?  Or other threads call lws apis on that context, eg, via your own class method wrappers?

**Comment by helloword010** [comment]
> Showing me pieces of code doesn't really help understand your whole system.
> 
> The issue here is the assert is indicating a linked-list in lws is trashed, it should not be possible to do that if everything running serialized in one thread. It's possible to happen if two threads collide in changing the linked-list.
> 
> So is it that only the event loop thread that owns the context calls lws apis? Or other threads call lws apis on that context, eg, via your own class method wrappers?
Yes ， other threads call lws apis on that context.

**Comment by helloword010** [comment]
> Showing me pieces of code doesn't really help understand your whole system.
> 
> The issue here is the assert is indicating a linked-list in lws is trashed, it should not be possible to do that if everything running serialized in one thread. It's possible to happen if two threads collide in changing the linked-list.
> 
> So is it that only the event loop thread that owns the context calls lws apis? Or other threads call lws apis on that context, eg, via your own class method wrappers?

Yes ， other threads call lws apis on that context.

**Comment by lws-team** [comment]
That's not how lws works... it doesn't "protect against itself" with locks, and is not threadsafe.  The idea of event loops is you can dispense with locking if you do everything on a single thread, serialized... a bunch of different things happening, but happening one at a time so there can never be any contention.

You must ask the event loop thread to do whatever it is you want, like starting a new client connection.  Take a look at

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

Your other thread can lock and configure a shared data structure to indicate what it wants, and then signal lws something to do

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n120-124

lws thread will wake up and do a callback specific to other thread cancelling its wait

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n266

in there, you can lock the shared data structure and find out what is being asked, and do it from lws event loop thread context.

**Comment by helloword010** [comment]
We are not a server but a simulated batch ws client

**Comment by helloword010** [comment]
we create multi connections to connect other server. 

> That's not how lws works... it doesn't "protect against itself" with locks, and is not threadsafe. The idea of event loops is you can dispense with locking if you do everything on a single thread, serialized... a bunch of different things happening, but happening one at a time so there can never be any contention.
> 
> You must ask the event loop thread to do whatever it is you want, like starting a new client connection. Take a look at
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c
> 
> Your other thread can lock and configure a shared data structure to indicate what it wants, and then signal lws something to do
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n120-124
> 
> lws thread will wake up and do a callback specific to other thread cancelling its wait
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c#n266
> 
> in there, you can lock the shared data structure and find out what is being asked, and do it from lws event loop thread context.

we create multi connections to connect other server.

**Comment by lws-team** [comment]
It makes no difference, the same technique will solve your problem.

It doesn't have to change your code that much either, the other thread can, eg, prepare the connection info struct itself, put it in the shared queue, and call `lws_cancel_service()` to alert the lws event loop that there is a request, when it sees what you want in the `LWS_CALLBACK_EVENT_WAIT_CANCELLED` callback, it can use the info struct to create the client from there safely.

**Comment by helloword010** [comment]
Invoke lws_client_connect_via_info（）in LWS_CALLBACK_EVENT_WAIT_CANCELLED callback ?

**Comment by lws-team** [comment]
Yeah, in there, it's happening from the lws event loop context and there are no thread safety issues in lws.

You must take care of locking between lws event loop thread and your other threads, for who owns your shared data structure.

**Comment by helloword010** [comment]
when i invoke  lws_cancel_service() twice  in succession,it only be in   LWS_CALLBACK_EVENT_WAIT_CANCELLED callback once.
it means lws_cancel_service() can alert itself? I should promice give  LWS_CALLBACK_EVENT_WAIT_CANCELLED callback enought time to run over?

**Comment by lws-team** [comment]
The semantics of `lws_cancel_service()` are similar to `lws_callback_on_writeable()`, it is just requesting the related callback.  If you ask twice but it didn't get to it yet, you still are "requesting a callback".  If multiple threads are calling it in an uncontrolled way any number of times, you are still "requesting a callback".

Once the callback comes it clears all pending callback requests, you must lock your shared object (usually, a linked-list or queue) and start with doing whatever was requested in there, be it one thing or ten things, there will be one callback.

**Comment by helloword010** [comment]
okay,thanks a lot
