### ISSUE TITLE
libwebsocket ws-server without echo-protocol

### ISSUE THREAD

**Issue by assistuelectronics** [warmcat/libwebsockets#2104]
Hi,

I have Web server client running on windows PC and another Linux machine with Websocket server built on javascript with 'echo-protocol' commented. When I connect with echo-protocol disabled then the websocket client running in windows PC is able to make connection and send data.

Now I replaced Linux machine with embedded Linux with "lws-minimal-ws-server-echo -p 8080" running. But it tries to make connection and then this error ": No supported protocol "xxxx".

How can I modify lws-minimal-ws-server-echo.c without echo protocol? May be I am not strong in Linux C at this moment, may solve over some period. But looking for some soon help.

JAVA Based websocket server code:
// var connection = request.accept('echo-protocol', request.origin);
    var connection = request.accept(null, request.origin);
    console.log((new Date()) + ' Connection accepted.');
    connection.on('message', function(message) {
        if (message.type === 'utf8') {
            console.log('Received Message: ' + message.utf8Data);
            connection.sendUTF(message.utf8Data);
        }
        else if (message.type === 'binary') {
            console.log('Received Binary Message of ' + message.binaryData.length + ' bytes');
            connection.sendBytes(message.binaryData);
        }
    });

**Comment by lws-team** [comment]
> May be I am not strong in Linux C at this moment, may solve over some period. But looking for some soon help.

If the examples work as they are, that's the starting point lws is giving you.  If you don't have the experience to adapt them, well OK but that is not an lws issue, you should think about hiring someone who does have the experience.

**Comment by assistuelectronics** [comment]
Hi,

I am able to communicate with our client to server built using lws. I used minimal-ws-server with minimal changes, to be specific changed the protocol name

I must say, the stack is written so beautifully and one can easily understand it. Appreciate your work.
