### ISSUE TITLE
Build failed with compression enabled

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2105]
Hi,

since some days it no longer compiles with compression enabled.

```
cmake .. -DLWS_WITH_HTTP_STREAM_COMPRESSION=1
make
```

> /home/pi/libwebsockets/lib/core-net/service.c: In function ‘lws_handle_POLLOUT_event’:
> /home/pi/libwebsockets/lib/core-net/service.c:117:20: error: ‘const struct lws_role_ops’ has no member named ‘write_role_protocol’
>    if (wsi->role_ops->write_role_protocol(wsi, NULL, 0, &wp) < 0) {
>                     ^~
> make[2]: *** [lib/CMakeFiles/websockets_shared.dir/build.make:570: lib/CMakeFiles/websockets_shared.dir/core-net/service.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1076: lib/CMakeFiles/websockets_shared.dir/all] Error 2
> make: *** [Makefile:163: all] Error 2

**Comment by lws-team** [comment]
Yes it's the role ops refactor patch, it missed out upgrading the compression specific code.

I updated the patch on main to take care of it, and added the compression option to DISTRO_RECOMMENDED that is tested in CI as well.
