### ISSUE TITLE
Libwebsocket (dumb-increment...)

### ISSUE THREAD

**Issue by Liab-Farhad** [warmcat/libwebsockets#2106]
Hello; 

I am very new to Linux and to programmering. I would like t know, if anone knows how i can run dumb-increment ?? 

I have got the libwebsocket folder. But i have tried everything to run plugins->protocol-dumb-increment..c but nothing happens. ,

any tut how to run it?

**Comment by lws-team** [comment]
Unfortunately it seems like you need to get some basic knowledge about compiling C under your belt before trying to use this.  That's not an lws issue.
