### ISSUE TITLE
socket io problem

### ISSUE THREAD

**Issue by Ripple-qin** [warmcat/libwebsockets#2109]
Hi，dear author

 sorry to disturb you again. 
I have a question for socket.io need your help. 

For libwebsockets, Does it support linking to the socket.io server?
I have test it , but failed. 

I know that many issues have discussed this issue。

1: For  [https://github.com/warmcat/libwebsockets/issues/531](url)
I have checked the relevant information and learned that socket.io has modified some websocket protocols, such as ping, pong, etc. As you said, Lws provides the websocket layer only, it has no idea what socket.io protocol on top of ws is , it cannot directly support connect socket.io.

2：For [https://github.com/warmcat/libwebsockets/issues/877](url)
I feel that you are not sure if libwebsockets can connect.

3: For https://github.com/warmcat/libwebsockets/issues/1754
The reporter said he was connected socket.io using the demo of echo and work well， I don't know how it was achieved and what is the plug and play?

4: For [https://warmcat.com/2011/03/06/libwebsockets-new-features.html](url)

> I also added v00 client support by request from a developer using the socket.io server library which doesn't support anything except 76 / 00. That means that in libwebsockets, both server and client support now covers all combinations of v00. v04, v05 and v06.

The meaning of this passage is that libwebsockets has already supports connecting to socket.io?

Pls give us some suggestions based on this information， thanks for your strong support. 

If libwebsocket cannot support socket.io,  we may have to reimplement the differences of ws protocol between them.

**Comment by lws-team** [comment]
I have never wanted to connect to anything with socket.io, so I did not spend time looking into it.

>>     I also added v00 client support by request from a developer using the socket.io server library which doesn't support anything except 76 / 00. That means that in libwebsockets, both server and client support now covers all combinations of v00. v04, v05 and v06.

> The meaning of this passage is that libwebsockets has already supports connecting to socket.io?

No, those are websocket RFC version numbers, the one published in RFC6455 was v13.

Wikipedia https://en.wikipedia.org/wiki/Socket.IO says "Socket.IO primarily uses the WebSocket protocol with polling as a fallback option", AFAIK from that description it's basically a custom subprotocol on top of normal ws, ie, it seems lws can handshake to it fine (although they do not specify a subprotocol name which is usually a bad sign).

It seems it's just some overloaded blob-aware JSON in there

https://github.com/socketio/socket.io-protocol

if you want to write and contribute an lws subprotocol handler then I will try to help with that and include it in lws.

**Comment by Ripple-qin** [comment]
ok,  I got it, thanks for your answer. you can close this question. 
I will continue to solve it.
