### ISSUE TITLE
LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS / Full path

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2112]
Hi,

When we use LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS and there is a connection as HTTP (instead of HTTPS) the redirection happens but it looses the path of the request. (basically "http://www.site.com/path/" redirects to "https://www.site.com")

Would it be possible to keep the full path in the redirection ?

Regards.

**Comment by lws-team** [comment]
This is pushed on main just now, please give it a go.
