### ISSUE TITLE
BigSur sysconf(3)

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2116]
Hi,

After upgrade to the new version of OSX, BigSur, `sysconf(_SC_OPEN_MAX)` started to return unreasonably big number, - 9223372036854775807, - which leads to two problems:

1. This value obviously does not fit into `int context->max_fds`
2. Changing the type to proper long (`sysconf(3)` returns long) leads to the attempt to allocate 9223372036854775807 bytes during context creation

Looks like we have to limit the max_fds on OSX somehow.

**Comment by lws-team** [comment]
Is it some mutant form of 64-bit signed -1?  -1 is a hack to to indicate the sysconf call failed

```
If	the call to sysconf() is not successful, -1 is returned	and errno is
     set appropriately.	
```

https://www.freebsd.org/cgi/man.cgi?query=sysconf

**Comment by zbroyar** [comment]
> Is it some mutant form of 64-bit signed -1?

Nope, I checked.

It’s the maximum positive value for signed int64 == 2^63-1

Looks like it’s a new way for Apple to say `unlimited`.

**Comment by lws-team** [comment]
I'm updating my mac mini used for CI and fix it when that's done.

**Comment by lws-team** [comment]
... actually I boldly say I'll fix it but if that information just isn't available from the OS any more, it means default to 1024 or something, and allow the user to override it via the context info struct as is already possible.

**Comment by zbroyar** [comment]
Yes, this looks like the only reasonable approach here.

**Comment by lws-team** [comment]
Is there maybe a bit more to this story?  I updated to big sur and fetched latest lws and rebuilt, at least on my mac mini, he is being told the max fds is 2560 for that process.

**Comment by zbroyar** [comment]
<img width="922" alt="Screenshot 2020-11-16 at 17 32 49" src="https://user-images.githubusercontent.com/338701/99273492-c8a99e80-2831-11eb-8e5c-0ef672d448fc.png">

**Comment by zbroyar** [comment]
On my mini I see the same picture:

<img width="903" alt="Screenshot 2020-11-16 at 17 34 49" src="https://user-images.githubusercontent.com/338701/99273774-22aa6400-2832-11eb-86e5-0cc542a965e5.png">

**Comment by lws-team** [comment]
Mac has `ulimit -n`, he's saying 2560 here

I'm guessing this is being set on your box somehow to "unlimited"

**Comment by zbroyar** [comment]
Yes, on my both os x machines `ulimit -n` says `unlimited`.

**Comment by lws-team** [comment]
I guess there's some other story about how OSX chooses to do that or sticks at 2560, but it doesn't matter, I added a patch locally to force any unreasonable ulimit -n (> 10M) to 2560 which is useful anyway.  But I am starting to look at your PR before pushing it.

**Comment by lws-team** [comment]
The patch for this is on main now.

**Comment by zbroyar** [comment]
Do you plan to add it to 4.1-stable?

**Comment by lws-team** [comment]
Yes it's there now.
