### ISSUE TITLE
Server binds to localhost only on windows.

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2118]
Hi,

How can I bind ws server to all interfaces on a local windows machine? The same code on linux and osx listen the port on all interfaces, but on windows it binds to localhost only.

What did I miss?

**Comment by lws-team** [comment]
Dunno... I didn't write windows... does it help to tell it to bind to 0.0.0.0, or that just confuses it worse?

**Comment by zbroyar** [comment]
The strange behaviour was due to LWS_IPV6=ON. AFAIU, this option make LWS to accept connections over ipv6 only.

**Comment by lws-team** [comment]
Thanks for updating with what you found.

What that option does is build the code related to ipv6, there are other flags and heuristics to figure out whether to make use of it or not.

'Binds to localhost' may be a bit misleading then, if you look in netstat or whatever it should show bound to ::1 which would have given the clue quicker.

**Comment by zbroyar** [comment]
Yes, I'm sorry. My question wasn't clear enough.
