### ISSUE TITLE
Build failed if set -DLWS_WITH_HTTP2=OFF with master branch

### ISSUE THREAD

**Issue by vsbc2010** [warmcat/libwebsockets#2119]
libwebsockets-4.1.4/lib/core-net/network.c: In function ‘lws_retry_sul_schedule_retry_wsi’:
libwebsockets-4.1.4/lib/core-net/network.c:445:57: error: ‘role_ops_h2’ undeclared (first use in this function)
  if (wsi->role_ops == &role_ops_h1 || wsi->role_ops == &role_ops_h2)
                                                         ^
libwebsockets-4.1.4/lib/core-net/network.c:445:57: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [lib/CMakeFiles/websockets.dir/build.make:564: lib/CMakeFiles/websockets.dir/core-net/network.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1345: lib/CMakeFiles/websockets.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**Comment by lws-team** [comment]
Thanks, I pushed a fix on main / master and added a scenario with `-DLWS_WITH_HTTP2=0 -DLWS_WITH_MINIMAL_EXAMPLES=1` in CI to catch any future ones.
