### ISSUE TITLE
Libevent load failure

### ISSUE THREAD

**Issue by moidroid** [warmcat/libwebsockets#2121]
Hi,
I am currently using libwebsocket 3.1 but I have now started to start using version 4.1 work and I have run into issues with loading libevent. I have had a look at the updated examples and they look very much like the working code I am using but I get an error at startup:

I am compiling libwebsockets with the libevent flag and adding libevent to the options in the code as well.

```
[2020/11/19 08:52:05:7328] E: lws_create_context: unable to load evlib plugin evlib_event
[2020/11/19 08:52:05:7328] E: libwebsocket init failed
```

In the code I have removed extensions and ping pong interval which I does not work like before.
Also, it doesn't seem to like the SSL part either, so that was also commented below.

What does the error message above mean and what is going wrong?

```
        lws_context_creation_info info = {};
	info.port = m_websocket_port;
	info.mounts = &mount;
	info.protocols = protocols;

	//info.extensions = exts;
	//info.ws_ping_pong_interval = m_pingPongInterval;

	info.gid = -1;
	info.uid = -1;
	info.max_http_header_pool = 1;
	info.pcontext = &m_context;
	info.options =
	        LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE |
	        LWS_SERVER_OPTION_LIBEVENT;


	//info.ssl_cert_filepath = nullptr;
	//info.ssl_private_key_filepath = nullptr;
	info.user = this;

	void *foreign_loops[1];
	foreign_loops[0] 	= m_base;
	info.foreign_loops 	= foreign_loops;

	int logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE; //| LLL_DEBUG;
	lws_set_log_level(logs, NULL);

	m_context = lws_create_context(&info);

	if (!m_context) {
		lwsl_err("libwebsocket init failed\n");
		throw std::runtime_error("libwebsocket init failed");
	}


	timeout_watcher = event_new(m_base, -1, EV_PERSIST, ev_timeout_cb, this);
	struct timeval tv = {0, m_ws_wakeupusec};
	evtimer_add(timeout_watcher, &tv);


	lwsl_notice("WebSocket started\n");
```

**Comment by lws-team** [comment]
Did you do the make install after making lws?  Otherwise the app won't be able to find the libevent plugin.

**Comment by moidroid** [comment]
Hi,
No, I have just copied the shared libraries to my own path and set the LD_LIBRARY_PATH path.
I have until now only used the libwebsockets.so.xx file but I noticed there is a libwebsockets-evlib_event.so as well.

Is the last shared library file also needed in this new version? 


Thanks

**Comment by lws-team** [comment]
Yes the code supporting the event lib you select is loaded at runtime now from its own plugin .so.

**Comment by moidroid** [comment]
I tried copying the libwebsockets-evlib_event.so to my folder but I still get the same problem.
Is it still possible to bundle the libwebsockets shared libraries with the project the way I am doing it?

**Comment by lws-team** [comment]
atm, no, it looks in the compiletime var LWS_INSTALL_LIBDIR, which is like `/usr/local/lib` or so (exactly what it is will be platform dependent, but it should always be something).

I guess I can make it look in LD_LIBRARY_PATH but it's existence is platform-dependent.

**Comment by lws-team** [comment]
I pushed a patch on main that changes the event lib plugin search rules to 1) current working dir, 2) INSTALL_LIBDIR, and 3) each entry in LD_LIBRARY_PATH
