### ISSUE TITLE
fatal error LNK1104: cannot open file 'ssl.lib'

### ISSUE THREAD

**Issue by astone2014** [warmcat/libwebsockets#2122]
Sorry if this has been asked before but I am very lost on why my build is failing.

What is `ssl.lib`? I thought openssl was `libeay32.lib` and `ssleay32.lib`

On Windows, using VS2015 x64 Native Tools Command Prompt,
when I run `cmake --build .`
I get some errors for ssl.lib
`LINK : fatal error LNK1104: cannot open file 'ssl.lib' [C:\source\dwextensions\dwabb\dependencies\build\lib\websockets_
shared.vcxproj]`

Building openssl
```bat
cd C:\source\dwextensions\dwabb\dependencies

del /F/Q/S C:\source\dwextensions\dwabb\dependencies\openssl-1.0.2u
7z x "openssl-1.0.2u.tar.gz" -so | 7z x -aoa -si -ttar
cd C:\source\dwextensions\dwabb\dependencies\openssl-1.0.2u

perl Configure no-asm --prefix=C:\openssl VC-WIN64A
ms\do_win64a
nmake -f ms\ntdll.mak
nmake -f ms\ntdll.mak install

cd C:\source\dwextensions\dwabb\dependencies
```

building libwebsockets
```bat
cd C:\source\dwextensions\dwabb\dependencies

del /F/Q/S C:\source\dwextensions\dwabb\dependencies\libwebsockets
7z x "libwebsockets.zip" -aoa

del /F/Q/S C:\source\dwextensions\dwabb\dependencies\build
md build
cd C:\source\dwextensions\dwabb\dependencies\build

cmake -G "Visual Studio 14 2015 Win64" -DOPENSSL_ROOT_DIR="C:\openssl" -DCMAKE_INSTALL_PREFIX:PATH="C:\libwebsockets" "C:\source\dwextensions\dwabb\dependencies\libwebsockets"
cmake --build .
cmake --install .
```

Any

**Comment by lws-team** [comment]
Please have a look here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

and you can also refer the (successful) CI windows builds and what they're doing, eg

https://libwebsockets.org/sai/index.html?task=12dae4291414812ca94f9574a6415f239556582a36c9532fc4c63575c6640340

```
 cmake .. -DLWS_OPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib\libssl.lib;C:\Program Files\OpenSSL\lib\libcrypto.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\Program Files\OpenSSL\include" -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" && cmake --build . --config DEBUG
```

**Comment by astone2014** [comment]
So with the latest openssl I get the libraries as expected.

It seems that...
Since version 1.1.0 OpenSSL have changed their library names from:
libeay32.dll -> libcrypto.dll
ssleay32.dll -> libssl.dll

Any suggestions on how to build using openssl 1.0.2u?

**Comment by lws-team** [comment]
> So with the latest openssl I get the libraries as expected.

Good... there's no general advantage to using ancient tls libs.

> Any suggestions on how to build using openssl 1.0.2u?

lws itself doesn't really know about openssl library naming habits on different platforms.  It has a cmake find helper for openssl that does try to know that

https://libwebsockets.org/git/libwebsockets/tree/cmake/FindOpenSSLbins.cmake#n75

You can either rely on that to sniff things out because the deps are placed in magic directories like C:\Program Files (x86)\libname or you can take the approach pasted above to explicitly set LWS_OPENSSL_LIBRARIES

**Comment by astone2014** [comment]
Actually yes `LWS_OPENSSL_LIBRARIES` works perfect.

This was my final cmake build command that worked.

```cmake -G "Visual Studio 14 2015 Win64" -DOPENSSL_ROOT_DIR="C:\openssl" -DCMAKE_INSTALL_PREFIX:PATH="C:\libwebsockets" -DLWS_OPENSSL_LIBRARIES="C:\openssl\lib\ssleay32.lib;C:\openssl\lib\libeay32.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\openssl\include" "C:\source\dwextensions\dwabb\dependencies\libwebsockets"```

🎉
Thank you very much! Excited to start using your library.
Have a great weekend.
