### ISSUE TITLE
LCCSCF_HTTP_X_WWW_FORM_URLENCODED

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2125]
Hi,

Is there some trick to know when using LCCSCF_HTTP_X_WWW_FORM_URLENCODED ?

I can't find an example with it.

When I try it, the request is sent without the body.

I double checked everything:

case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
lws_client_http_body_pending(wsi, 1);
lws_callback_on_writable(wsi);
break;

case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
lws_write(wsi, (uint8_t *)data, len, LWS_WRITE_HTTP_FINAL);
lws_client_http_body_pending(wsi, 0);
return(0);

Am I doing something wrong ?

Regards.

**Comment by lws-team** [comment]
This exists to support the corresponding feature using Secure Streams apis.  There's no lws api that lets you bind a content-length to the request for writeable as in Secure Streams.

**Comment by dev31337** [comment]
Sorry to ask for more information, does this mean that I should not use LCCSCF_HTTP_X_WWW_FORM_URLENCODED ?

If this is the case, can I write the Content-Type/Content-Length and the body myself ?

**Comment by dev31337** [comment]
I tried putting the Content-Type/Content-Lenght myself in LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER and it works :)

**Comment by lws-team** [comment]
Yes, nothing stops you just doing it at lws user code level.  That particular implementation is exposed for Secure Streams layer to use on top of lws and only works with that.
