### ISSUE TITLE
lws_add_http_header_by_name / Missing ':'

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2127]
Hi,

There is a small bug in the function "lws_add_http_header_by_name" I think.

The function does not add the ':' between the name and the value, so the name has to finish with a ':' in order for the function to work.

From the documentation it seems that it is not intended.

Regards.

**Comment by lws-team** [comment]
It is a bit unusual, but it is as intended... I updated the doxygen comment to clarify what it's expecting.

FWIW on h2 pseudoheaders exist that have a different format, eg, ":path" as the header name.

**Comment by dev31337** [comment]
Oh sorry then, thanks for the clarification :)
