### ISSUE TITLE
lws_service / timeout

### ISSUE THREAD

**Issue by dev31337** [warmcat/libwebsockets#2128]
Hi,

Sorry to open an issue for this but the goal is to have a clarification.

Since lws_service() does not accept a timeout anymore, how can we call lws to process current pending events and immediately return without waiting for more events ?

Regards.

**Comment by lws-team** [comment]
Attempting to share loops like that just gives garbage results and you shouldn't consider it.  It causes either increased latency for traffic, increased cpu, or both.

Lws is agnostic about what loop you are using, ie, it's possible to use the same code with a bunch of event loop libraries.  You can absolutely share those event loops with multiple libraries like libwebsockets, cleanly and with good performance, and I can recommend doing it.  But when you start an event lib loop, you do not return to the foreground thread, do not "exit lws_service()" until the loop stops, you cannot share loops like you are imagining.

As a stopgap lws_service() allows you to pass -1 for the timeout.  But lws is heading towards the poll loop acting the same as the event lib loops, not towards enabling these nasty hacks that perform badly.  So for new code, you should just not do that...

**Comment by dev31337** [comment]
Thank you for the detailed clarification.

Would you happen to have an example of connecting lws with an even lib loop ?

Another question the tests I made show that lws_service(context,0) returns every 1 second when there is no event, is that something which is intended, can we assume it will stay like this in the future ? 

Thank you also for the stopgap which still leaves a last resort option.

**Comment by lws-team** [comment]
There are several examples, this one is the most interesting

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

It shows how to select from libuv, libevent, glib and libev support in lws at runtime, and connect it to an event lib loop that is natively created using the event lib apis.    In a real implementation, you can throw out the code related to the other event libs you aren't using.  But the point is that linux distros etc you can build one lws that can work with different loops selected at runtime, and the whole lws_context is just being a guest on a loop that already existed before lws joined it and continues to exist afterwards just fine too.

For sharing you'd have your other code bind to the same event lib loop then add the lws_context to it.

> Another question the tests I made show that lws_service(context,0) returns every 1 second when there is no event, is that something which is intended, can we assume it will stay like this in the future ?

No for v4.1 this 1s thing was basically an accident, LWS_WITH_SEQUENCER was selected as on by default and he has a 1s heartbeat concept that has a timer associated with it even if no lws_sequencer objects in use.  On main, LWS_WITH_SEQUENCER is off by default, and even for the default poll loop, if lws is idle, then he will stay in the poll wait "forever" (like 3 weeks) until a scheduled event or a network event wakes it, which is ideal for power / cpu.

In the future it will align even more towards being the same as event lib -based loop, where he does not return from lws_service() at all until the context is being destroyed.

Even with 1s delay, this is not useful for scenarios where the non-lws code is trying to do bulk transfers or any kind of low-latency activity... the only real solution is don't try this broken polling / spinning sharing scheme, but make it only purely event driven for both sets of code.  It depends on the exact situation but the two basic ways are either split out the two "worlds" into their own event loop / threads so they can act well independently, or properly join them so both lws and this other code register their fds to be controlled by the same event loop / wait cleanly.  The best way to do the latter is by having both use a generic event library loop, you will be left with a clean way to add additional code into the loop using a standardized api while getting ideal event-driven behaviour from everything using one thread.

**Comment by dev31337** [comment]
Thank you again for this very detailed explanation.

I have one last question, I would like to use SIGHUP to reload the configuration, do you see a potential issue when the SIGHUP happens while your lws_service() is running ? Can I assume that the lws_service() will always return on SIGHUP in the future ?

**Comment by lws-team** [comment]
Signals are "events" for event libs, you can register handlers for them that are called from the event loop thread context.

In the event loop implementations, exiting the service loop is something that only happens when we call `lws_destroy_context()`.

So this isn't directly realated to a specific signal-interrupting-poll() behaviour showing up as looping on lws_service(), in the future you'll register a SIGHUP handler on your loop that will call lws_destroy_context() to indicate we don't want the context any more and stop `lws_service()`, then call it a second time to actually destroy the context finally.  It won't need to pay any attention to looping lws_service() and jumping in there.

BTW for this kind of SIGHUP behaviour for serving, lws has a more sophisticated way

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n877-899

you can mark the context instead as "deprecated" and then open a new context with the new configuration.  The old context gives up his listen sockets when marked as deprecated so the new one can bind to them.  And when his last client activity completes, he destroys himself.

**Comment by dev31337** [comment]
Thank you again !

**Comment by dev31337** [comment]
I forget to ask you one question, I'm using 4.1, can I turn LWS_WITH_SEQUENCER to OFF without any related issue ?

**Comment by lws-team** [comment]
Yes, nothing uses it by default.

**Comment by dev31337** [comment]
I implemented libuv (recompiled lws with support) and I run into one single issue (but an important one).

When using libuv LWS_CALLBACK_TIMER is not fired anymore by lws_set_timer_usecs.

Would you see any reason why ?

**Comment by dev31337** [comment]
Sorry I just saw in the documentation that it is only working with the default loop.

**Comment by dev31337** [comment]
I misread the documentation, I thought it was not supported with libuv but the documentation says it is ? (was it added after 4.1 ?)

**Comment by lws-team** [comment]
LWS_CALLBACK_TIMER should still work but it has been superceded with the lws_sul stuff... that is more flexible (you can have as many as you want, it doesn't have to bind to a wsi, and you can tell it where to call back to for each sul without involving the protocol callback).

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

**Comment by dev31337** [comment]
Thanks again for the answer, just to let you know, since I implemented the libuv loop I decided to move the timer I was using from lws LWS_CALLBACK_TIMER to libuv loop for consistency.

Everything is working fine with libuv, I'm now safe for any future update of lws :)

Thanks for your help and for this really great and flexible lws !

**Comment by dev31337** [comment]
Sorry I spoke too fast, LWS_CALLBACK_CLOSED is not triggered anymore as it should.

When using the default lws loop LWS_CALLBACK_CLOSED is called a few seconds after the remote web browser has done its requests.

When using the libuv loop LWS_CALLBACK_CLOSED is only called when I close the remote web browser. (closing the tab where the URL is is not enough)

I'm completely lost and don't see what the issue could be :(

**Comment by dev31337** [comment]
I made more test and LWS_CALLBACK_CLOSED is triggered exactly 2 minutes after the last request (using libuv) instead of 5 seconds (using default loop), this is so strange.

**Comment by dev31337** [comment]
Could it be some lws_set_timeout being different when using libuv ?

**Comment by dev31337** [comment]
Is it possible that the lws_set_timeout does not work when using libuv, do you know how I could check this ?

**Comment by lws-team** [comment]
What platform is this on?  Same behaviour is coming if you use main branch?

**Comment by dev31337** [comment]
I'm using ubuntu 4.1.

I just found a very easy way to check that, I just make a telnet to the web port of lws and do nothing.

When using main loop the connection is closed by lws after 10 seconds, if I use libuv loop the connection is never closed by lws.

So I can confirm you that lws_set_timeout does not work with libuv. (this is also explained why LWS_CALLBACK_TIMER stopped working).

I will try with master and let you know...

**Comment by dev31337** [comment]
I just tested with master and got the same issue.

The telnet (or netcat) to the web server port and doing nothing is a good test to verify it with any web server example.

**Comment by dev31337** [comment]
Not sure If I am close but in "lib/event-libs/libuv/libuv.c" the 2 tests below never calls uv_timer_start() because "us" is always 0.

        if (us)
                uv_timer_start(&pt_to_priv_uv(pt)->sultimer, lws_uv_sultimer_cb,
                               LWS_US_TO_MS(us), 0);

**Comment by dev31337** [comment]
Unfortunately I can't go further to find the issue by myself.

The difference I can see is that how 'pt' is retrieved.

With libuv it is retrieved like this:

       struct lws_pt_eventlibs_libuv *ptpr = lws_container_of(handle,
                struct lws_pt_eventlibs_libuv, idle);
        struct lws_context_per_thread *pt = lws_container_of(ptpr,
                struct lws_context_per_thread, evlib_pt);

With _lws_plat_service_tsi() which seems to be the main loop pt is retrieved like this:

 pt = &context->pt[tsi];

This may be the reason, I hope I helped you a bit :)

**Comment by dev31337** [comment]
I don't think it is related but if you compare every lib/events-lib/libev/ sources all of them (libev/libevent/glib) have a line:

        if (pt->destroy_self)
                lws_context_destroy(pt->context);

While libuv has not.

There is also a small variation on how this case is handled:

       if (!lws_service_adjust_timeout(pt->context, 1, pt->tid))
                /* -1 timeout means just do forced service */
                _lws_plat_service_forced_tsi(pt->context, pt->tid);

**Comment by lws-team** [comment]
> never calls uv_timer_start() because "us" is always 0

us is being set to when the next scheduled event is expected, if there are no more scheduled events expected, the interval timer to wake for the next scheduled event will not be enabled... it should be being enabled when you set a scheduled event like a timeout.

> if (pt->destroy_self)

libuv has some differences from the other event loops, the biggest one is libuv is the only loop to require to go around the event loop to close a handle.  It means that you must stage context destruction with libuv, indicate that you want to destroy the context but not able to free wsi or vhost or context objects until the libuv-side async close processing for the handles completes later.  So unlike the others, it reference-counts every fd / handle (even signals) on the libuv loop that it put there, and finalizes context destruction when that number falls to 0.  Therefore the destruction flow is quite different just for libuv (all this is concealed by lws).

> I just found a very easy way to check that, I just make a telnet to the web port of lws and do nothing.

Thanks I will look at it thismorning.

**Comment by lws-team** [comment]
On main branch of lws, I adapted `minimal-http-server-eventlib-foreign` to leave the context up for 30s instead of 10s

```
diff --git a/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c b/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c
index de289fb4af..1582659721 100644
--- a/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c
+++ b/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c
@@ -107,7 +107,7 @@ foreign_timer_service(void *foreign_loop)
                        return;
                }
                lwsl_user("LWS Context created and will be active for 10s\n");
-               lifetime = 11;
+               lifetime = 31;
                break;
 
        case TEST_STATE_DESTROY_LWS_CONTEXT:
```

and did a `telnet 127.0.0.1 7681` from another console when that was up... it closed after 10s as expected while the context continues to run.

This is on Fedora 33 libuv package 1.40.0

**Comment by dev31337** [comment]
> 
> 
> > never calls uv_timer_start() because "us" is always 0
> 
> us is being set to when the next scheduled event is expected, if there are no more scheduled events expected, the interval timer to wake for the next scheduled event will not be enabled... it should be being enabled when you set a scheduled event like a timeout.

In my case 'us' is always zero (i do a printf) even when there are timeouts, I believe this is the issue.

Can you please tell me on how to build the minimal examples, I looked in the README.md file in the mininal-examples folder but I did not find directions.

**Comment by dev31337** [comment]
Found it but I can't get around the build errors:

libuv include dir: /usr/include
libuv libraries: /usr/lib/x86_64-linux-gnu/libuv.so
libevent include dir: LIBEVENT_INCLUDE_DIRS-NOTFOUND
libevent libraries: LIBEVENT_LIBRARIES-NOTFOUND
libev include dir: LIBEV_INCLUDE_DIRS-NOTFOUND
libev libraries: LIBEV_LIBRARIES-NOTFOUND
-- Checking for one of the modules 'glib-2.0'
glib include dir: GLIB_INCLUDE_DIRS-NOTFOUND
glib libraries: GLIB_LIBRARIES-NOTFOUND
Extra libs: /usr/lib/x86_64-linux-gnu/libuv.so;LIBEVENT_LIBRARIES-NOTFOUND;LIBEV_LIBRARIES-NOTFOUND;GLIB_LIBRARIES-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

**Comment by dev31337** [comment]
It seems that it wants all the different eventlib installed for some reasons.

**Comment by lws-team** [comment]
Yes its job is to allow running the same code using an event library specified at runtime.

**Comment by dev31337** [comment]
I was able to compile minimal-http-server-eventlib to test it.

I can't reproduce the timer issue wit the example.

I stripped my application of everything and the timer issue is still here.

I'm lost :(

If you have any idea please let me know.

I must now consider the last resort lws_service(context -1) called regularly.

Can you please confirm me that lws_service(context, -1) processes all the pending events and not only a single one at each call ?

**Comment by dev31337** [comment]
I also have one other option (dropping libuv).

Is there a way to enable a repeating timer with lws that will be called during while(!lws_service(context,0)) ;

I think you mentioned lws_sul but I'm unable to find an example on how to do it.

**Comment by lws-team** [comment]
> I can't reproduce the timer issue wit the example.

OK well that's encouraging

>  If you have any idea please let me know.

Just align your code to follow the example code, it is CC0 / Public Domain to facilitate actually using the exact code, regardless of your license.

If there is like a slider where all the way to the left is the example code and all the way to the right is your existing code, if you add in your code step by step on the example, eventually it will all work or you will know what breaks in your code.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

I mentioned above explains how to use lws_sul (independent of which loop) and points where to look for example code.

**Comment by dev31337** [comment]
Thanks, I have two questions about lws_sul.

Can I make a repeatable timer with lws_sul_schedule() or do I have to lws_sul_schedule() it again at each tick ?

Can I destroy the lws context within the lws_sul_schedule() callback ? If yes, will that exit the lws_service(context,0) ?

**Comment by lws-team** [comment]
You have to schedule it again in the callback if that's what you want.  They are just one-shot and you don't need to do anything to clean up afterwards if they fire.

Any pending lws_sul in an object when you want to destroy the object must be cancelled with `lws_sul_cancel()`, it's a NOP if you cancel a sul that was not actually scheduled.

When you use an event lib with a foreign loop, you don't call lws_service(), you just run your foreign loop  The native event library foreign loop arrangements take care of making callbacks into lws when something to do on a timer or fd that lws owns.  When you want to start destroying the lws context, yes you call lws_destroy_context() to start that process and for libuv, it will complete asynchronously as the libuv handles are retired by further events on the foreign loop.

**Comment by dev31337** [comment]
Thanks again, I just need one last clarification, when _not_ using a foreign loop, is it fine to destroy the context in a lws_sul callback ?

My tests shows that it works and it stops the lws_service(), I just want to be sure that it is fine by you (and the future of your lws event loop changes) :)
