### ISSUE TITLE
event leak on Windows

### ISSUE THREAD

**Issue by missdeer** [warmcat/libwebsockets#213]
I'm trying the test-client on Windows, I found that if the server is down, the test-client couldn't connect to the server and exit the service loop then, but it doesn't close the event created with the socket.
I traced the source code, the function `remove_wsi_socket_from_fds` never calls `lws_plat_delete_socket_from_fds` which will close the event, it always jumps to `do_ext` when `--context->fds_count` results 0.
Or did I misunderstand the API?

**Comment by warmcat** [comment]
It's fixed
