### ISSUE TITLE
possibly redundant assignment to cmake option - why?

### ISSUE THREAD

**Issue by defaultbranch** [warmcat/libwebsockets#2130]
Hello @lws-team , there is that bit of Cmake code
```
if (LWS_WITH_LIBEV)
	set(LWS_WITH_LIBEV 1)
endif()
```
(from https://github.com/warmcat/libwebsockets/blob/5e3a241601f1bfeb6bcab3a1b7587602b4f2af24/CMakeLists-implied-options.txt#L338)
(similar for other event loop options)

Is this on purpose (normalize the boolean value) or is this a bug?
Do I need to do the same when adding support for another event loop?

**Comment by lws-team** [comment]
It looks like cruft... only CMakeLists.txt can care about the value of those symbols since the code itself gets a cmakedefine'd version and only tests if it's defined.  I'll remove the existing ones shortly.
