### ISSUE TITLE
wsi-timeout.c:308 Assertion 

### ISSUE THREAD

**Issue by GuoFlying** [warmcat/libwebsockets#2131]
Hello, my side in normal use, low probability of assertion, no other redundant logs, can you know what caused the problem? How do I deal with this problem? Thanks!

log:
libwebsockets/libwebsockets-4.0.21/lib/core-net/wsi-timeout.c:308: lws_validity_cb: Assertion `rbo->secs_since_valid_hangup > rbo->secs_since_valid_ping' failed.
Aborted

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/wsi-timeout.c?id=5b852b561bbb0a3e3aa2f0a136d8e2f7a44b04f5#n308

It believes that your timeout / backoff struct in use by this wsi has a hangup interval smaller than the ping interval, which is not allowed.  The timeout struct must have a lifetime as long as the wsi using it, eg, you can't define it on the stack.

Valgrind is your friend...
