### ISSUE TITLE
Problem serving files from zip mount

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2132]
Hello, I have some trouble to serve a zip file mount.
It seems that the problem occurs for files in the zip that are stored without compression.

I can reproduce it by replacing the original candide.zip file with a zip containing the same files without compression.
With https2, the document is not complete and jpeg images are not loading the majority of time. Chrome displays 3  errors messages:

> GET https://ip/ziptest/images/001_th.jpg net::ERR_CONNECTION_RESET 200		candide.html:142
> GET https://ip/ziptest/candide.html net::ERR_CONNECTION_RESET 200		candide.html:1
> GET https://ip/ziptest/images/002_th.jpg net::ERR_CONNECTION_RESET 200		candide.html:319

If I disable ssl on the server or http2 in the browser, the jpeg files are downloading well but some garbage is appended at the end of the html.

> GET https://ip/ziptest/candide.html net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)		candide.html:1

**Comment by lws-team** [comment]
> I can reproduce it by replacing the original candide.zip file with a zip containing the same files without compression.

Can you let me know exactly how you prepared this zipfile?

> If I disable ssl on the server or http2 in the browser, the jpeg files are downloading well but some garbage is appended at the end of the html.

This is coming with the candide example as it is?  Or also related to uncompressed zip contents?

**Comment by Piero01** [comment]
On linux,  in the folder with the html file and the folder containing the 2 images I use 
> zip candide.zip -r * -0

The candide example is always working with the provided candide.zip or one I create myself with the command above without -0.
It's related to uncrompressed zip content.

For information here is the beginning of the garbage:

> PK Õ:eJimages/UT ±®»X±®»XuxPK :cJò ÈÇéÇéimages/001_th.jpgUT R ¹XR ¹XuxÿØÿàJFIFHHÿá€ExifMM*>F(‡iNHH0210 0100 ÿÿÿáphttp://ns.adobe.com/xap/1.0/ 72 72 Inch Exif Version 2.1 FlashPix Version 1.0 Uncalibrated ÿÛC     %!'&$!$#).;2),8,#$3F48=?BCB(1HMH@M;AB?

It seems it is the following of the archive.

**Comment by lws-team** [comment]
I updated main and v4.1-stable to fix pointing to the right path for the original candide.zip and also to mount a new uncompressed version at "/uncommziptest/", eg, "/uncommziptest/candide.html" so we can test both easily.

It seems to work well with both, at least on 127.0.0.1:7681, with and without https / h2 and both chrome and firefox... can you give it a try?

**Comment by Piero01** [comment]
With your file it's working fine.
But it seems that the files of interest are not uncompressed.

> Zip file size: 3003221 bytes, number of entries: 16
**> -rw-rw-r--  3.0 unx   262537 tx defN 12-Nov-05 16:07 candide.html**
> drwxrwxr-x  3.0 unx        0 bx stor 17-Mar-05 07:22 images/
**> -rw-rw-r--  3.0 unx    59847 bx defN 17-Mar-03 07:16 images/001_th.jpg
> -rw-rw-r--  3.0 unx    56916 bx defN 06-Nov-12 06:00 images/002_th.jpg**
> -rw-rw-r--  3.0 unx      151 bx stor 19-Apr-19 10:50 404.html
> -rw-rw-r--  3.0 unx   211764 bx stor 19-Apr-03 01:59 candide.zip
> -rw-rw-r--  3.0 unx     1406 bx stor 19-Apr-03 01:59 favicon.ico
> -rw-rw-r--  3.0 unx     2046 bx stor 19-Apr-03 01:59 http2.png
> -rw-rw-r--  3.0 unx  2477518 bx stor 19-Apr-03 01:59 leaf.jpg
> -rw-rw-r--  3.0 unx     9606 bx stor 20-May-06 19:38 libwebsockets.org-logo.svg
> -rw-rw-r--  3.0 unx     3221 bx stor 20-May-06 19:38 lws-common.js
> -rw-rw-r--  3.0 unx    12446 bx stor 19-Apr-19 10:50 strict-csp.svg
> -rw-rw-r--  3.0 unx     4250 bx stor 19-Apr-19 10:50 test.css
> -rw-rw-r--  3.0 unx     7249 bx stor 19-Apr-19 10:50 test.html
> -rw-rw-r--  3.0 unx    57259 bx stor 19-Apr-19 10:50 test.js
> -rw-rw-r--  3.0 unx     2727 bx stor 19-Apr-03 01:59 wss-over-h2.png
> 16 files, 3168943 bytes uncompressed, 3000767 bytes **compressed:  5.3%**

 If I remove all the files in candide-uncompressed.zip and keep only candide.html and the two jpegs. I get exactly the same file as candide.zip.

If it can help, here is the file I use 
[candide-uncompressed_bad.zip](https://github.com/warmcat/libwebsockets/files/5623342/candide-uncompressed_bad.zip)

Is it possible that when serving uncompressed files from zip the header "content-encoding" is set to some compression but the data is not, which disturbs the browser?

**Comment by lws-team** [comment]
Thanks for sending your actual file.  I cut-and-pasted your zip command to produce the pushed one

```
$ zip candide.zip -r * -0
```

and it is much bigger than the normally-zipped one.  But with your actual file I can also see the crud at the end and fail to decode the first image in the browser.

> Is it possible that when serving uncompressed files from zip the header "content-encoding" is set to some compression but the data is not, which disturbs the browser?

If it was literally that it should see it as just all garbage, I wonder if the different zip utility behaviours are relevant.

Anyway I can go watch it fail now which is the first step.

**Comment by lws-team** [comment]
The problem's related to seeking inside the vfs read and restricting what can be read from the file correctly... it lasted this long because normally the gzip metadata is restricting it at the client.  But with uncompressed the over-reading bug is revealed.

Current main and v4.1-stable ought to just work for both cases now (and contain your "bad" zipfile).
