### ISSUE TITLE
how to connect a ws server without  subprotocols?

### ISSUE THREAD

**Issue by myseemylife** [warmcat/libwebsockets#2136]
i search the minal-examples,most of them are impls with subprotocols,
Now i use libwebsockets to connect a server without any sub protocols, i can set lws_context_creation_info.protocols = NULL to connetct,
but where the default  callbacks are?should i define a  default callbak ? just like i do when i use a subprotocols.
Plz hlp.Best regards!

**Comment by lws-team** [comment]
Normally your server provides explicit named subprotocols, and by providing an lws protocol of the same name, the connection binds to the right clientside lws protocol and callback during the ws upgrade negotiation.

When the server fails to provide an explicit subprotocol (not a good sign...) you can instead force the binding on the clientside by giving `.local_protocol_name` in the client creation info

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n133-139

**Comment by myseemylife** [comment]
wow~it works! thx a lot!
and then another question,is it a good idea that create many client connections and  share the same lws_context?or  one conn per context is better? need your suggestion.

**Comment by lws-team** [comment]
You want one context per process.

You can have a large number of sockets managed per context, I have tried 100K on linux but it needs ulimit -n updating from default (typ 1024) and latency can increase if lots are busy.  If mostly idle and latency not critical tens of thousands are possible.
