### ISSUE TITLE
Client: Overriding host-resolution

### ISSUE THREAD

**Issue by kutoga** [warmcat/libwebsockets#2139]
Hi

For some DNS-names there are multiple underlying IP-addresses, but I want to connect to one specific IP-address. The target host requires in this case usually that the `Host`-HTTP-header is set correctly.

My question: Is it possible to "override" the DNS host-resolution? This would imply that libwebsockets already sets the correct `Host`-header, but uses the provided IP-address to connect to.

Of course, if it is possible to override the `Host`-header as a user of the library, this also already solves the problem. In this case I would connect to "1.2.3.4" and just define the `Host`-header is "my-server.com".

I've tried to achieve this, but I'm not sure if these parts of the library are exposed.

Thank you very much

**Comment by lws-team** [comment]
You can set the Host: header in the client connection info struct

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n91-92

If you provide for the peer adress a name that has to be resolved, it will be resolved and the results sorted (in main lws branch) according to desirability and tried in turn.  If you provide an IP address, then just that is used directly.

**Comment by kutoga** [comment]
Thank you very much for the quick response!
