### ISSUE TITLE
Feature request: Proxy Protocol

### ISSUE THREAD

**Issue by jmillan** [warmcat/libwebsockets#214]
Hi,

I'm just wondering whether the Proxy Protocol[*] implementation is in the roadmap or if there is any interest at all.

It is useful for scenarios where the WebSocket server is behind a proxy, since it provides the IP:port information of the real WebSocket client, which is lost otherwise.

My understanding is that the content of such information, which comes previous to the HTTP request, could be stored in the allocated_headers struct under the token 'proxy ' so the information could be obtained as any other HTTP header is.

[*]: http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

Ie:

PROXY TCP4 192.168.0.1 192.168.0.11 56324 443\r\n
    GET / HTTP/1.1\r\n
    Host: 192.168.0.11\r\n
    \r\n

**Comment by socketpair** [comment]
this commit is here fdde0f0a03a711bc08c2069ce92a9fee1526d450

@warmcat @jmillan  
does it work for WSS ? I mean plaintext PROXY header before the first byte of TLS HELLO message ?
