### ISSUE TITLE
Retrieving Client/Server Connection Errors

### ISSUE THREAD

**Issue by bdonduprey** [warmcat/libwebsockets#2143]
Hi,

I am making an application for an embedded controller that needs to log various client connection errors when the happen. By “log”, I mean the error must be displayed on a UI. I was wondering what the best method to retrieve various connection errors would be?

I tried looking at LWS_CALLBACK_CLIENT_CONNECTION_ERROR, but most error strings returned do not translate to various errors that the controller needs to log. I noticed there is this function: lws_http_client_http_response that can be called to get the http response code. This will be helpful to retrieve the HTTP errors. However, I would also like to retrieve TLS, TCP, and DNS related errors.

Some example error situations that need to be logged:
TLS Client Certificate Expired / TLS Server Certificate Expired
TLS Client Certificate Revoked / TLS Server Certificate Revoked
TLS Client Certificate Authentication Failed / TLS Server Certificate Revoked
DNS Unavailable
DNS Name Resolution Failed
HTTP Response Syntax Error
HTTP Proxy Authentication Failed

Is there a similar method that could be called to get the TLS/SSL status code for a particular wsi? Essentially, these HTTP, TLS, etc., status codes need to be translated to internal error codes in the device.

My application uses libwebsockets and WolfSSL.

Thanks in advance for the help!

**Comment by lws-team** [comment]
>  most error strings returned do not translate to various errors that the controller needs to log.

The existing CCE  (Client Connection Errors) cover most things, because they are coming when the actual code doing the connection has concluded it has failed

```
	 *     	"getaddrinfo (ipv6) failed"
	 *     	"unknown address family"
	 *     	"getaddrinfo (ipv4) failed"
	 *     	"set socket opts failed"
	 *     	"insert wsi failed"
	 *     	"lws_ssl_client_connect1 failed"
	 *     	"lws_ssl_client_connect2 failed"
	 *     	"Peer hung up"
	 *     	"read failed"
	 *     	"HS: URI missing"
	 *     	"HS: Redirect code but no Location"
	 *     	"HS: URI did not parse"
	 *     	"HS: Redirect failed"
	 *     	"HS: Server did not return 200"
	 *     	"HS: OOM"
	 *     	"HS: disallowed by client filter"
	 *     	"HS: disallowed at ESTABLISHED"
	 *     	"HS: ACCEPT missing"
	 *     	"HS: ws upgrade response not 101"
	 *     	"HS: UPGRADE missing"
	 *     	"HS: Upgrade to something other than websocket"
	 *     	"HS: CONNECTION missing"
	 *     	"HS: UPGRADE malformed"
	 *     	"HS: PROTOCOL malformed"
	 *     	"HS: Cannot match protocol"
	 *     	"HS: EXT: list too big"
	 *     	"HS: EXT: failed setting defaults"
	 *     	"HS: EXT: failed parsing defaults"
	 *     	"HS: EXT: failed parsing options"
	 *     	"HS: EXT: Rejects server options"
	 *     	"HS: EXT: unknown ext"
	 *     	"HS: Accept hash wrong"
	 *     	"HS: Rejected by filter cb"
	 *     	"HS: OOM"
	 *     	"HS: SO_SNDBUF failed"
	 *     	"HS: Rejected at CLIENT_ESTABLISHED"
```

For example, getaddrinfo... errors are the DNS errors.

HTTP response codes are NOT CCEs... it connected just fine in order to get the 500 or whatever.  They are the http transaction result, welcome or not.

> Is there a similar method that could be called to get the TLS/SSL status code for a particular wsi?

That is not how tls works... there isn't any unified "status code" between say mbedtls and openssl.

It can be added so it can make a more specific error than `lws_ssl_client_connect1/2 failed`, if it's done compactly and works on both mbedtls and openssl like everything else does, patches are welcome.

**Comment by bdonduprey** [comment]
Thanks for the information! Much appreciated! I will investigate if the ssl errors could be enhanced and propose a patch if doable.

One last question: Are the OPENSSL callbacks valid for use with other SSL libraries (like WolfSSL) or just OpenSSL?

**Comment by lws-team** [comment]
Lws supports two apis, openssl (which covers wolfssl, boringssl and a bunch of other forks) and mbedtls.

Wolfssl broadly is openssl apis, but it has enough variations you have to build with specific lws config support for it.  Real openssl has a lot of api variations over time and wolfssl doesn't follow them all.

In the code everything related to tls lives in here

https://libwebsockets.org/git/libwebsockets/tree/lib/tls

the ./openssl and ./mbedtls subdirs have the same source layout exporting the same functions, and are the only places that know the specifics of the tls library internals.

For client failure I would look first here

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/tls-client.c#n164-224

This is where generic tls client connection actions become CCE strings when they fail.

You can see in there it calls `lws_ssl_client_connect1()` -> `lws_tls_client_connect()` and ends up doing `SSL_connect()`... it's there with wolfssl you should be able to query the related tls error and get more info like this

https://www.wolfssl.com/doxygen/group__Debug.html#gae30b3ae133f07c6b9d2b567367489b02

**Comment by bdonduprey** [comment]
@lws-team Thanks so much for all of the information you provided! It is very helpful! I am also amazed at the swiftness of the responses!

**Comment by lws-team** [comment]
Patches still welcome, closing this as nothing for me to do about it.
