### ISSUE TITLE
make lws_wsi_client_stash_item() public

### ISSUE THREAD

**Issue by parihaaraka** [warmcat/libwebsockets#2147]
It would be convenient to access method and path (at least) internal copies and do not store original values (applicable when creating headers). Thanks

**Comment by lws-team** [comment]
There's no use for this at user code AFAIK.  What it stashes was already settable by the user at the client creation info struct... it's basically stashing that info data into the ah so it can be recovered later around the event loop.

Can you explain more what you think making it public would be good for?

**Comment by parihaaraka** [comment]
Yes, that was settled already and out of scope during the loop. If I need path and method to compose a signature (timestamp dependent) within a http-header, then I have to store the values somewhere. But they are already stored by lws. If I try to get them out, then I need to make multiple private directories accessible for direct header include.

**Comment by lws-team** [comment]
For client, if you're doing it at the point an ah was assigned, you should be able to use `lws_hdr_copy()` with, eg, `_WSI_TOKEN_CLIENT_METHOD`, `_WSI_TOKEN_CLIENT_URI, ` to recover what you want.

**Comment by parihaaraka** [comment]
it works for me, thanks! 🤝🏼
