### ISSUE TITLE
can the client be configured not to check the server certificate?

### ISSUE THREAD

**Issue by JCYAO-gz** [warmcat/libwebsockets#2149]
when i connect a wss，it is fail，log:
`SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)`
i consult other issues，download the server .crt and config .client_ssl_ca_filepath ,but it doesn't work。
because my client only connect a few server, so the client be configured not to check the server certificate?
thanks

**Comment by lws-team** [comment]
> download the server .crt and config .client_ssl_ca_filepath ,but it doesn't work

No... unless it's "selfsigned", your server cert is itself signed by a CA cert.  You indicate which CA cert you trust to sign the server cert.

Eg letsencrypt only issues certs with 3 month validity, trusting the specific cert means update your app every 3 months.  Trusting the CA who signs the letsencrypt cert chain will be able to validate LE certs for 10 years or more.

Use eg ssllabs.com server check to find out the CA cert you need for that server, and google the fingerprint to download that cert from the CA site and give that to .client_ssl_ca_filepath.

**Comment by JCYAO-gz** [comment]
Thanks
my project is client，if i can no check the server  cert，so I don't need to care about certificate and expiration.

**Comment by lws-team** [comment]
Here's the selection of weapons for people who really have to shoot themselves in the feet

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n39-42

**Comment by JCYAO-gz** [comment]
thanks for you help!
add config LCCSCF_ALLOW_INSECURE is ok

**Comment by Non-Unruly** [comment]
> thanks for your help!
> add config LCCSCF_ALLOW_INSECURE is ok

it works!
my client code is running normally on x86 Linux and Win ， but "SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)" on embedded arm machine

then option "LCCSCF_ALLOW_INSECURE"
great!!!

**Comment by lws-team** [comment]
To be clear for other readers who happen across this issue, OP has removed any connection security on his embedded device with that flag.  Anyone can proxy the connection and feed it modified data, attack its parsing etc.

If you want tls to act as expected and securely validate the peer, follow the advice above:

> Use eg ssllabs.com server check to find out the CA cert you need for that server, and google the fingerprint to download that cert from the CA site and give that to .client_ssl_ca_filepath.
