### ISSUE TITLE
The server dump in lws_callback_on_writable ()

### ISSUE THREAD

**Issue by helloword010** [warmcat/libwebsockets#2150]
![image](https://user-images.githubusercontent.com/30803413/103399433-1c6f0d80-4b7c-11eb-895b-445be4f5ecd2.png)
[](url)
![1609383423(1)](https://user-images.githubusercontent.com/30803413/103399465-3a3c7280-4b7c-11eb-89a6-64ea56f7ff86.jpg)
The version is 4.0.22.
We use libwebsokets as a black box.so we do not know a lot about how it works of libwebsocket. It is a server program. we use libwebsockes to create serval clients in a context and use a static map to manage wsi(client) handle. It works  more than 2 days ,but this morning it dump. Can you give us some guidance to solve this problem?

**Comment by lws-team** [comment]
Does this problem exist on main branch?  4.0 is not even the last stable release.

**Comment by helloword010** [comment]
![1609383423(1)](https://user-images.githubusercontent.com/30803413/103399964-5f31e500-4b7e-11eb-9b64-688995ae501d.jpg)
![image](https://user-images.githubusercontent.com/30803413/103399988-71ac1e80-4b7e-11eb-819e-a449b35adc69.png)

**Comment by lws-team** [comment]
... also given the problem, are threads involved on your side?  You cannot call lws apis from threads other than the event loop thread, with very few exceptions.

**Comment by helloword010** [comment]
when we need a connection,we invoked lws_cancel_service() ,and do connect request in LWS_CALLBACK_EVENT_WAIT_CANCELLED. Then we will get a wsi ,and save it in a map. when wsi's state changed in loop thread ,we change it's state in the map.  when  need send message to server ,when invloke lws_callback_on_writable() with wsi we have saved in the map. moment latter ,we get LWS_CALLBACK_CLIENT_WRITEABLE in the thread loop to send message.

**Comment by lws-team** [comment]
> when invloke lws_callback_on_writable() with wsi we have saved in the map

That's not allowed in lws... same as for writes, you have to also signal the lws event loop thread with lws_cancel_service() and do the writeable request from the event loop thread.  Look at the examples like

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

if the other threads wants something to happen on the lws thread, it should describe it in (lock-protected) shared memory and call the lws_cancel_service().  In there, you should lock the shared memory and figure out what you have been asked to do, then do it from the lws thread.

**Comment by helloword010** [comment]
But we have more than 200 wsi  ,and one wsi will invoke to send audio stram per 80ms. After testing, the delay is serious
