### ISSUE TITLE
Undefined reference to  `lws_extension_callback_pm_deflate` 

### ISSUE THREAD

**Issue by MonsieurTea** [warmcat/libwebsockets#2155]
Hi all,

I tried to build the libwesockets from source, somehow it seemed to worked.

I used : 
`cmake -LWS_ROLE_WS=1 -LWS_WITHOUT_EXTENSIONS=0 ..
make
sudo make install
` 
and then I try to run the minimal example associated with the binance client listed on the github repository.
However, I keep getting linking errors. 

I inlcude `usr/local/include` and `usr/local/lib` (linker) directories and I linked the library `libwebsockets.so` but it keeps giving me : 

`usr/bin/ld: obj/Debug/main.o:(.data.rel.ro+0x8): undefined reference to `lws_extension_callback_pm_deflate'
collect2: error: ld returned 1 exit status`

If someone might helps that would be very appreciated. 

DISCLAIMER : I am a total noob in Cmake, building and co.

**Comment by lws-team** [comment]
1) cmake options must begin `-D`
2) additional commands like make need separating with &&

**Comment by MonsieurTea** [comment]
Yes pardon me, 
I did not fully check my first message.

The problem was due to your first point, thanks a lot for the quick response.

Best.
