### ISSUE TITLE
How to read arraybyte in C program?

### ISSUE THREAD

**Issue by sarath-crypto** [warmcat/libwebsockets#2156]
Hi,
I am sending arraybyte to "simple echo server" . How can I receieve it in echo server using libwebsockets. By client is below.
<script language = "javascript" type = "text/javascript">
        var wsUri = "ws://127.0.0.1:8080";
        var output;
        var key;
        var data;
        function init() {
                output = document.getElementById("output");
                initWebSocket();
        }
        function initWebSocket() {
                websocket = new WebSocket(wsUri);
                websocket.binaryType = "arraybuffer";
                websocket.onopen = function(evt) {
                        onOpen(evt)
                };
                websocket.onmessage = function(evt) {
                        onMessage(evt)
                };
                websocket.onerror = function(evt) {
                        onError(evt)
                };
        }
        function onOpen(evt) {
                writeToScreen("CONNECTED:"+websocket.binaryType);
                var str = "Isarath@gmail.com";
                const buffer = new ArrayBuffer(str.length*2);
                var bufView = new Uint16Array(buffer);
                const bytes = buffer.byteLength;
                for (var i=0, strLen=str.length; i < strLen; i++)bufView[i] = str.charCodeAt(i);
                Send(buffer);
        }

        function onMessage(evt) {                writeToScreen('<span style = "color: blue;">EVENT</span>'); 
                if(evt.data instanceof ArrayBuffer) {
                        writeToScreen('<span style = "color: red;">EVENT</span>'); 
                } else {
                        writeToScreen('<span style = "color: green;">EVENT</span>'); 
                }
                var msg = evt.data;
        }
        function onError(evt) {
                writeToScreen('<span style="color: red;">ERROR:</span> ' + evt.data);
        }
        function Send(message) {
                writeToScreen("SENT: " + message); 
                websocket.send(message);
        }
        function writeToScreen(message) {
                var pre = document.createElement("p"); 
                pre.style.wordWrap = "break-word"; 
                pre.innerHTML = message; output.appendChild(pre);
        }
        function ab2str(buf) {
                return String.fromCharCode.apply(null, new Uint16Array(buf));
        }
        function str2ab(str) {
                var buf = new ArrayBuffer(str.length*2); 
                var bufView = new Uint16Array(buf);
                for (var i=0, strLen=str.length; i < strLen; i++)bufView[i] = str.charCodeAt(i);
                return buf;
        }
        window.addEventListener("load", init, false);
</script>

My Server code in C is below.
        case LWS_CALLBACK_RECEIVE:
                fprintf(stderr,"Received:%d\n",(int)len);
                lwsl_user("LWS_CALLBACK_RECEIVE: %4d (rpp %5d, first %d, ""last %d, bin %d, msglen %d (+ %d = %d))\n",(int)len, (int)lws_remaining_packet_payload(wsi),lws_is_first_fragment(wsi),lws_is_final_fragment(wsi),lws_frame_is_binary(wsi), pss->msglen, (int)len,(int)pss->msglen + (int)len);
                if (len) {
                        char *p = (char *)in;
                        switch(*p){
                                case('I'):{
                                        fprintf(stderr,"INIT %d\n",(int)len);
                                        len--;
                                        p++;
                                        //credentails.token.apply(null, new Uint16Array(buf));
                                        memcpy(credentials.token,p,len);
                                        for (int i = 0; i < KEY_SIZE; i+=2)sprintf(&credentials.key[i],"%02X",rand() & 0xff);
                                        fprintf(stderr,"Token:%s\n",credentials.token);
                                        fprintf(stderr,"Key:%s\n",credentials.key);
                                        *(char *)in = 'I';
                                        memcpy(in+1,credentials.key,KEY_SIZE);
                                        len = KEY_SIZE;
                                        credentials.fp = fopen("pcm.ogg","rb");
                                        break;
                                }
my web page shows
WebSocket Test

CONNECTED:arraybuffer

SENT: [object ArrayBuffer]

EVENT
Can anyone guide me?
EVENT

**Comment by lws-team** [comment]
Just run lws-minimal-ws-server-echo unchanged (listening on 127.0.0.1:7681) and run this in the browser

```
<script>

var ab = new ArrayBuffer(256);
var bv = new Uint16Array(ab);
for (var i = 0; i < 256; i++)
	bv[i] = 'x';

var ws = new WebSocket("ws://127.0.0.1:7681");
ws.binaryType = "arraybuffer";

ws.onopen = function(evt) {
	console.log("ok");
	ws.send(ab);
}

ws.onmessage = function(m) {
	console.log("rx msg len " + m.data);
}
</script>
```
