### ISSUE TITLE
Building on Windows: undefined struct 'hmac_ctx_st'

### ISSUE THREAD

**Issue by mikelblaz6** [warmcat/libwebsockets#2157]
I build "libwebsocket" with CMake GUI without problems (configure + generate + build the project in Visual Studio), having the following output when I configure it.
```
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - found
```
However when I try to build with Visual Studio the my own project that makes use of the libwebsockets library, I have the following Issue and can´t solve it.
```
C:\Program Files (x86)\libwebsockets\include\libwebsockets/lws-genhash.h(85,18): error C2079: 'lws_genhmac_ctx::ctx' uses undefined struct 'hmac_ctx_st'
```

How could I fix it?

**Comment by lws-team** [comment]
Have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

Also windows is built various ways in CI.  So also reference how the CI succeeds to do it, eg,

```
cmake .. -DLWS_OPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib\libssl.lib;C:\Program Files\OpenSSL\lib\libcrypto.lib" -DLWS_OPENSSL_INCLUDE_DIRS="C:\Program Files\OpenSSL\include" -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files (x86)\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files (x86)\pthreads\lib\x64\libpthreadGC2.a" -DLWS_WITH_MINIMAL_EXAMPLES=1 && cmake --build . --config DEBUG
```

https://libwebsockets.org/sai/index.html?task=999c8f33441c55728d519ce531c7756908a45f32598f48ee46167d8fc7403523
