### ISSUE TITLE
How to add Authorization Bearer Token in client by libwebsockets

### ISSUE THREAD

**Issue by xajdlg** [warmcat/libwebsockets#2158]
1.i use jws create token,such as t1.t2.t3 , t1 and t2 is same as what other libraries create, but t3 is different,while all using hs256 and try encode b64 or not.
2.prompt error "E: CLIENT_CONNECTION_ERROR: read failed", when deal case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER where i call to lws_add_http_header_by_name(wsi,
(const unsigned char*)"Authorization", (const unsigned char*)"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMem82MITUisY2a2&tgsR2ckh&8Yt5TXRyaVyu7YlJaiIsImlhdCI6MTYxMDA4ODg1MiwiZXhwIwefsjEwMDkUiOpyfQ.B6Gu_xroQUioSmlGYsGeM-QkHc_YUZTZX&yuTNwE3Rw", 190, p, end)
3.can i.path be like "/a/b/c?d=e"?
Thanks!!!

**Comment by lws-team** [comment]
"t3 is different" doesn't tell me anything.  You mean result of hmac is wrong for same input?

"read failed" usually means "peer hung up on us".  Carefully read the documentation for the `name` parameter...

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n547-562

You must also provide the `:`.

Yes you can include ?x=y&a=b in the path.

**Comment by xajdlg** [comment]
wow, so fast-response,thanks
my code about LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER as follows  
 case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
    { 

        unsigned char **p = (unsigned char **) in, *end = (*p) + len;
            
        if (lws_add_http_header_by_name(wsi,
                                (const unsigned char*)"Content_type:",
                                (const unsigned char*)"application/json;charset=utf-8", 30, p, end))
            return -1; 

        if (lws_add_http_header_by_name(wsi,
                                (const unsigned char*)"Authorization:",
                                (const unsigned char*)"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMem91MzNjblY2a3JaR1R2ckhFckUyIrRyaVVlc3lJaiIsImlhdYCFWTYxMDA4ODg1MiwiZXhwIjYTDCEwMDkYgRFyfQ.B6Gu_xroQkAfkmlGrgNnM-QkHcyTGcTZXeKAmNHtsg3Rw", 190, p, end))
            return -1; 
                
        break;
    }   

so, the error of "read failed" is because server hung up on us.

**Comment by lws-team** [comment]
That string is 192 characters long, not 190.

**Comment by xajdlg** [comment]
sorry, after set len to 192, the same error "read failed" arise

**Comment by lws-team** [comment]
Take a look in the server logs, there's no reason to expect I can solve your problem for you when it is likely nothing to do with lws but your own code...

**Comment by xajdlg** [comment]
ok, thanks you very much
