### ISSUE TITLE
ws and wss enable at the same time on 2 different ports

### ISSUE THREAD

**Issue by CVVDN-S** [warmcat/libwebsockets#2159]
Hi,
Im using Libwebsockets version: 2.1.0, ws and wss is working good in my code. But either ws or wss can only be enabled at one time.
Is there a way to enable ws and wss at the same time on 2 different port? If it is possible how can it be done?

**Comment by lws-team** [comment]
> 2.1.0

It's 5 years old... if you find any bugs you're on your own.

> Is there a way to enable ws and wss at the same time on 2 different port?

Even on 2.1.0 "vhosts" (Virtual Hosts) are logically separate from the context... by default, for backwards compatibility, creating the context also creates a single default vhost.  But you can set this flag on the context creation info struct `.options` `LWS_SERVER_OPTION_EXPLICIT_VHOSTS`, it will no longer create the default vhost, instead you can create your own vhosts, reusing the context creation info struct.  This modern example shows the pattern

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c#n123

You set up the info struct to configure one vhost for tls / port 443 and the other without / port 80.

**Comment by CVVDN-S** [comment]
Thank you for the support. This is working.
