### ISSUE TITLE
Is there any way to know that this message is HTTP/2 message?

### ISSUE THREAD

**Issue by jinmuja-git** [warmcat/libwebsockets#2163]
In case of HTTP/1.1 message, I could check HTTP ver. with below.
lws_hdr_copy(wsi, Buf, sizeof(Buf), WSI_TOKEN_PROTOCOL);
And above method provides 'HTTP/1.1'.
But with HTTP/2 message, that api gave empty string.
Is there any way to check HTTP/2 message?

**Comment by lws-team** [comment]
h2 has its own headers that only exist on h2 connections, eg `WSI_TOKEN_HTTP_COLON_METHOD` which is ":method", an illegal header for h1

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h#n266

You can just look for these instead to know it is on h2.

**Comment by jinmuja-git** [comment]
Thank you. I will try that.
