### ISSUE TITLE
implicit declaration of function ‘lws_timed_callback_vh_protocol’

### ISSUE THREAD

**Issue by MNR85** [warmcat/libwebsockets#2165]
Hi. I wanted to use gitohashi that depends on lws.
I installed lws with this cmd
```
cmake .. -DLWS_FOR_GITOHASHI=1
```
and make was successful. But in gitohashi make I encountered this error:
```
undefined reference to `lws_timed_callback_vh_protocol'
```
and there was a warning about this function
```
warning: implicit declaration of function ‘lws_timed_callback_vh_protocol’; did you mean ‘lws_callback_all_protocol’? [-Wimplicit-function-declaration]
  408 |   lws_timed_callback_vh_protocol(lws_get_vhost(wsi),
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   lws_callback_all_protocol
```
I dont know exactly this is gitohashi problem or lws. But my question is that, is ```lws_timed_callback_vh_protocol``` correctly installed in my lws build?
With regards, Milad

**Comment by lws-team** [comment]
(I answered this on the same issue in gitohashi repo)
