### ISSUE TITLE
boost asio support

### ISSUE THREAD

**Issue by AlexCasual** [warmcat/libwebsockets#2167]
how can I add an increase ASIO event to libraries as a backend?

**Comment by lws-team** [comment]
Lws has nice support for adding event loops, see here

https://libwebsockets.org/git/libwebsockets/tree/lib/event-libs

and here is a patch recently adding sdevent, for reference

https://libwebsockets.org/git/libwebsockets/commit/lib/event-libs?id=b961e5f3518bd915da79624f44691041314d0de3

**Comment by lws-team** [comment]
If you have any other questions about it feel free.
