### ISSUE TITLE
lws_create_context always return when using libuv

### ISSUE THREAD

**Issue by LadMartin** [warmcat/libwebsockets#2171]
In order to fix #2129 it was introduced that when using libuv the lws_create_context will always return a context.

Therefore, we are no longer able to find out whether the context creation failed or not. (we used to check the return value for null)

 Is there another way how to check the state of the context?

**Comment by lws-team** [comment]
It's like that because it needs you to let the loop run with the half-baked, already-starting-destroy context.

He will clean up on the loop and then do the destroy flow.

What are you going to do different earlier if you know it did not complete context creation?

**Comment by LadMartin** [comment]
we would initiate a "stoping" procedure -  close loop and run an additional finite number of iterations to clean up stuff (like to close some other interfaces)

**Comment by lws-team** [comment]
Right but he's going to exit, hopefully cleanly, by himself if he didn't make it all the way through.

What breaks if you just roll with that?

**Comment by LadMartin** [comment]
The problem for us is that we use the same loop for other interfaces as well so we do not need to care about synchronization.
therefore, if we start up a in the kind of infinite run then there is always something in the loop planned if not by lws then by other interfaces, so the loop itself will never stop from emptiness.

And then basically we never find out that the lws resource died. Also, it's because we use it as a server so we are just waiting for the callbacks to be called. so the application logic just waits and waits not knowing that it waits for nothing.

**Comment by lws-team** [comment]
> so the loop itself will never stop from emptiness.

Lws knows about "foreign" loops... its approach is to count how many handles it personally added to the loop, and when destroying the lws context count backwards until there are handles left that lws added.  At that point, it will finalize the context destruction.

But (on main) it doesn't stop the foreign loop or expect zero handles on it, it is OK if the loop existed with its own handles before and after the context is destroyed.

If it got started adding things to the foreign loop then failed the context creation, it must be left alone to follow that path of closing things and backing itself out of the foreign loop until no trace left (and that requires the loop to be running for libuv, and so must be done asynchronously).

It might help avoid races to have an api that exposes the bit in the context that says it's started the destroy flow, but that'd be all.

I'm working on this today to make sure everything working before next release, so maybe some more patches coming, but the flow should be as described here.

**Comment by LadMartin** [comment]
> It might help avoid races to have an api that exposes the bit in the context that says it's started the destroy flow, but that'd be all.

That is actually exactly what would help us. We are fine with the flow as it is now, we just need to get to know that the init failed so we could then start closing the other guys as well.

**Comment by LadMartin** [comment]
I will actually help us with our

**Comment by LadMartin** [comment]
It might then actually help us with our second problem.
We have a kind of c++ lightweight wrapper around it, and of of the functions is that it calls lws_context_destroy in destructor
and so we also need to tell it not to call it the second time (which if forbidden), because then it has already been called in lws_create_context since it failed. Now, we get seg fault, of course.

**Comment by lws-team** [comment]
OK that exists now

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h?h=main#n1132-1148

I suggest updating to main since there are other fixes around libuv context lifecycle
