### ISSUE TITLE
lws_http_cookie_get() problem

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2172]
Hi,
with http2 and more than 1 cookie, the values returned by lws_http_cookie_get() are not correct.
I tested by adding 4 cookies "a", "bb", "ccc" and "dddd" with same value "12345678".
Here is what I read after calling lws_http_cookie_get():

> Cookie a: len=9 12345678
> Cookie bb: len=9 12345678
> Cookie ccc: len=9 12345678
> Cookie dddd: len=5 12345

For n cookies, it seems that the first n-1 are 1 char too long.
The last one is missing n-1 characters.

**Comment by lws-team** [comment]
That looks bad, but trying the same code lws uses in isolation

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int
lws_http_cookie_get(const char *name, char *buf,
		    size_t *max_len, const char *cookie, int len)
{
	int n, bl = (int)strlen(name);
	size_t max = *max_len;
	const char *p;
       char	*bo = buf;

	n = len;
	if (n < bl + 1)
		return 1;

	p = cookie;
	if (!p)
		return 1;

	p += bl;
	n -= bl;
	while (n-- > bl) {
		if (*p == '=' && !memcmp(p - bl, name, (unsigned int)bl)) {
			p++;
			while (*p != ';' && n-- && max) {
				*buf++ = *p++;
				max--;
			}
			if (!max)
				return 2;

			*buf = '\0';
			*max_len = (size_t)((char *)buf - (char *)bo);

			return 0;
		}
		p++;
	}

	return 1;
}

int
main()
{
	const char *c1 = "a=12345678; bb=12345678; ccc=12345678; dddd=12345678;";
	char r[100];
	size_t s;

	printf("%s: tests\n", __func__);
	s = sizeof(r);
	if (lws_http_cookie_get("a", r, &s, c1, strlen(c1)))
		printf("fail 1\n");
	else
		printf("%s: result %s len %d\n", __func__, r, (int)s);

	s = sizeof(r);
	if (lws_http_cookie_get("bb", r, &s, c1, strlen(c1)))
		printf("fail 2\n");
	else
		printf("%s: result %s len %d\n", __func__, r, (int)s);

	s = sizeof(r);
	if (lws_http_cookie_get("ccc", r, &s, c1, strlen(c1)))
		printf("fail 3\n");
	else
		printf("%s: result %s len %d\n", __func__, r, (int)s);

	s = sizeof(r);
	if (lws_http_cookie_get("dddd", r, &s, c1, strlen(c1)))
		printf("fail 4\n");
	else
		printf("%s: result %s len %d\n", __func__, r, (int)s);

	return 0;
}
```

gives correct results...

```
main: tests
main: result 12345678 len 8
main: result 12345678 len 8
main: result 12345678 len 8
main: result 12345678 len 8
```

Can you let me know the exact string the cookie is set to?

**Comment by lws-team** [comment]
... this is referencing the code in main, but I don't remember changing this for a long time.  So also what version of lws you use.

**Comment by Piero01** [comment]
I'm using version libwebsockets 4.1.99-v4.1.0-225-g42674b33.
When I disable http2 I'm getting the expected result.

I'm adding the cookies with the following command:
if (lws_add_http_header_by_name(wsi, (unsigned char*)"set-cookie:", (unsigned char*)"a=12345678", 10, &p, end))
	return 1;

**Comment by lws-team** [comment]
How does it work that you are expecting the client to give you a, bb, ccc, ddd etc?  You are adding it four times?

What is the raw string that lws is finding in the COOKIE header when you run the test?

**Comment by Piero01** [comment]
Yep I use the same function 4 times.

The string pointed by
`p = lws_hdr_simple_ptr(wsi, WSI_TOKEN_HTTP_COOKIE);`
is

> a=12345678\0;bb=12345678\0;ccc=12345678\0;dddd=12345

With http2 disabled it's the same as in your test code

> a=12345678; bb=12345678; ccc=12345678; dddd=12345678

**Comment by lws-team** [comment]
I see... looks like the problem is h2-specific maybe when the cookie is written out... I will take another look later

**Comment by lws-team** [comment]
Is lws the client part that is sending the headers, or just the server, or both?

**Comment by lws-team** [comment]
Hmmm you are adapting the length you give to the api each time, right?  "a=12345678" is length 10, but "bb=12345678" is 11, etc.

I can reproduce this magic shrinking value problem if I just tell it the strings are all length 10 when they aren't.

It was worth looking at anyway to add a patch to help it understand set-cookie: concatenation needs ; delimiters as well as  cookie:

**Comment by Piero01** [comment]
The client is a browser. lws is "only" sending the cookies and receiving them.

In my real case I only set 1 cookie with lws. The others are added by another server I have no influence on it.

By the way to reproduce it quickly with one of your minimal examples I modified minimal-http-server-dynamic.c

Right after case LWS_CALLBACK_HTTP:

```
char cookie[64];
size_t len = sizeof(cookie);

if (lws_http_cookie_get(wsi, "a", cookie, &len))
            printf("Cookie a not provided\n");
else
            printf("Cookie a: len=%d %s\n", len, cookie);

len = sizeof(cookie);
if (lws_http_cookie_get(wsi, "bb", cookie, &len))
            printf("Cookie bb not provided\n");
else
            printf("Cookie bb: len=%d %s\n", len, cookie);

len = sizeof(cookie);
if (lws_http_cookie_get(wsi, "ccc", cookie, &len))
            printf("Cookie ccc not provided\n");
else
            printf("Cookie ccc: len=%d: %s\n", len, cookie);

len = sizeof(cookie);
if (lws_http_cookie_get(wsi, "dddd", cookie, &len))
            printf("Cookie dddd not provided\n");
else
            printf("Cookie dddd: len=%d: %s\n", len, cookie);
```


and before the line
`if (lws_finalize_write_http_header(wsi, start, &p, end))`

```
if (lws_add_http_header_by_name(wsi, (unsigned char*)"set-cookie:", (unsigned char*)"a=12345678", 10, &p, end))
            return 1;
if (lws_add_http_header_by_name(wsi, (unsigned char*)"set-cookie:", (unsigned char*)"bb=12345678", 11, &p, end))
           return 1;
if (lws_add_http_header_by_name(wsi, (unsigned char*)"set-cookie:", (unsigned char*)"ccc=12345678", 12, &p, end))
           return 1;
if (lws_add_http_header_by_name(wsi, (unsigned char*)"set-cookie:", (unsigned char*)"dddd=12345678", 13, &p, end))
            return 1;

```

**Comment by lws-team** [comment]
Great... I can reproduce it as you say on :7682 / h2 only... I should have just requested this in the first place.  Let me take a look.

**Comment by lws-team** [comment]
I updated yesterday's patch on main that should solve it

https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=b567647db251d0c23ae6e3fc6b236e706a193356

**Comment by Piero01** [comment]
Yeah it's working on the example.
The drawback of this solution is that usercode need to allocate a buffer big enough to contain the biggest cookie otherwise the function returns an error. There is not this limitation on h1.

In my case I get additional cookies from another server and I have no means to know the length of the biggest cookie. So I need to allocate a buffer big enough but what is big enough?

**Comment by lws-team** [comment]
Yeah... I left that code alone since that's not where the problem came from.  But I take the point, I will look at that later.

**Comment by lws-team** [comment]
I rewrote the h2 stuff to work through the ah frags directly and updated the patch on main.
