### ISSUE TITLE
Building universal version(arm64 x86_64) of the library with minimum deployment target mac OS 10.9

### ISSUE THREAD

**Issue by Swetha-ch** [warmcat/libwebsockets#2175]
Hi,

I am trying to build universal version (arm64 x86_64) FAT static library of libraries. And have few challenges.

I need to support from mac OS 10.9 to mac OS 11.
When trying to build as universal with Xcode 12 using cmake .. -DLWS_IPV6=0 -DLWS_WITH_SSL=0 "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64", it builds as universal but  when trying to run on 10.9 it crashes with Symbol not found: _clock_gettime, since this is not available on OS lower than 10.11.

Tried building X86_64 alone using mac OS 10.9 SDK  and arm64 with mac OS 11 SDK. Planning to create a FAT file using **lipo create** Now I have two different header(lws_config.h) with LWS_HAVE_CLOCK_GETTIME defined for x86_64. and not defined for arm64 one.How do I go about using these headers with a FAT(universal) lib and excutable.

**Comment by lws-team** [comment]
> I am trying to build universal version (arm64 x86_64) FAT static library of libraries. And have few challenges.

Well, you have a lot less challenges than if it wasn't building and testing on x86_64 mac mini and an m1 mac mini individually already in CI, if not combined.  So at least the problem space is constrained.

> it builds as universal

Cmake is doing a great job there.

> _clock_gettime()

clock_gettime() one of many things is tested for at cmake so the code can adapt to what's around.

```
CHECK_FUNCTION_EXISTS(clock_gettime LWS_HAVE_CLOCK_GETTIME)
```

The toolchain you're building with has it, so cmake finds it and says we can use it, but evidently 10.9 platform itself doesn't have it. Obviously apple not putting POSIX things like that in until late in the day is not anything to do with lws.

For these tests, I think you can override at cmake commandline, eg `-DLWS_HAVE_CLOCK_GETTIME=0`... lws supports platforms that have monotonic and that don't

```
lws_usec_t
lws_now_usecs(void)
{
#if defined(LWS_HAVE_CLOCK_GETTIME)
	struct timespec ts;

	if (clock_gettime(CLOCK_MONOTONIC, &ts))
		return 0;

	return (((lws_usec_t)ts.tv_sec) * LWS_US_PER_SEC) +
			((lws_usec_t)ts.tv_nsec / LWS_NS_PER_US);
#else
	struct timeval now;

	gettimeofday(&now, NULL);
	return (((lws_usec_t)now.tv_sec) * LWS_US_PER_SEC) +
			(lws_usec_t)now.tv_usec;
#endif
}
```

but timers and things will act differently on suspend / resume if you don't use monotonic, you may or may not care depending on what you're doing.

If you want to use libdl or similar to decide it at runtime instead, patch is welcome.

> Now I have two different header(lws_config.h)

If I understand it, you must force-align those so it is the same code, one way or another, like the example above for arch differences, for platform version differences you can think about runtime export detection / binding, or if clang has the same, gcc supports __attribute((weak)), like a default value for symbols that didn't find an export to bind to.

**Comment by Swetha-ch** [comment]
Thank you for the quick response and the pointers, I will explore and update here which one worked for me

**Comment by lws-team** [comment]
OK feel free to update, I will close it for now since nothing for me to do atm.

It might be an idea to try to do the fat build at least on the M1 CI builder, so I am curious what flow you end up with or any sticking points.
