### ISSUE TITLE
OpenSSL private data indexes are regenerated on every context create causing connection failures

### ISSUE THREAD

**Issue by martlaak-gmail** [warmcat/libwebsockets#2178]
Global `int openssl_websocket_private_data_index` (and also `int openssl_SSL_CTX_private_data_index`) are re-generated at every context creation.
This is causing problems in multi-context usage, when one context starts TLS handshake and other one is creating a new context meanwhile, then first handshake fails on TLS verification with error:
`E: OpenSSL_client_verify_callback: can't get wsi from ssl privdata`

IMO, `openssl_websocket_private_data_index` and `openssl_SSL_CTX_private_data_index` should be tested if already generated, to achieve that they are generated only on first context create of the application.

For example, in the following modification of minimal-http-client-certinfo.c first connection fails:
```/*
 * lws-minimal-http-client-modified-to-do-multiple-context-connections
 *
 * Written in 2010-2019 by Andy Green <andy@warmcat.com>
 *
 * This file is made available under the Creative Commons CC0 1.0
 * Universal Public Domain Dedication.
 *
 * This demonstrates the a minimal http client using lws.
 *
 * It visits https://warmcat.com/ and receives the html page there.  You
 * can dump the page data by changing the #if 0 below.
 */

#include <libwebsockets.h>
#include <string.h>
#include <signal.h>

static int interrupted, bad = 1, status;
static struct lws *client_wsi;

static int
callback_http(struct lws *wsi, enum lws_callback_reasons reason,
	      void *user, void *in, size_t len)
{
	uint8_t buf[1280];
	union lws_tls_cert_info_results *ci =
		(union lws_tls_cert_info_results *)buf;

	switch (reason) {

	/* because we are protocols[0] ... */
	case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
		lwsl_err("CLIENT_CONNECTION_ERROR: %s\n",
			 in ? (char *)in : "(null)");
		client_wsi = NULL;
		break;

	case LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP:
		status = lws_http_client_http_response(wsi);
		lwsl_notice("lws_http_client_http_response %d\n", status);

		if (!lws_tls_peer_cert_info(wsi, LWS_TLS_CERT_INFO_COMMON_NAME,
					    ci, sizeof(buf) - sizeof(*ci)))
			lwsl_notice(" Peer Cert CN        : %s\n", ci->ns.name);

		if (!lws_tls_peer_cert_info(wsi, LWS_TLS_CERT_INFO_ISSUER_NAME,
					    ci, sizeof(ci->ns.name)))
			lwsl_notice(" Peer Cert issuer    : %s\n", ci->ns.name);

		if (!lws_tls_peer_cert_info(wsi, LWS_TLS_CERT_INFO_VALIDITY_FROM,
					    ci, 0))
			lwsl_notice(" Peer Cert Valid from: %s", ctime(&ci->time));

		if (!lws_tls_peer_cert_info(wsi, LWS_TLS_CERT_INFO_VALIDITY_TO,
					    ci, 0))
			lwsl_notice(" Peer Cert Valid to  : %s", ctime(&ci->time));
		if (!lws_tls_peer_cert_info(wsi, LWS_TLS_CERT_INFO_USAGE,
					    ci, 0))
			lwsl_notice(" Peer Cert usage bits: 0x%x\n", ci->usage);
		if (!lws_tls_peer_cert_info(wsi,
					    LWS_TLS_CERT_INFO_OPAQUE_PUBLIC_KEY,
					    ci, sizeof(buf) - sizeof(*ci))) {
			lwsl_notice(" Peer Cert public key:\n");
			lwsl_hexdump_notice(ci->ns.name, ci->ns.len);
		}
		break;

	/* chunks of chunked content, with header removed */
	case LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ:
		lwsl_user("RECEIVE_CLIENT_HTTP_READ: read %d\n", (int)len);
#if 0  /* enable to dump the html */
		{
			const char *p = in;

			while (len--)
				if (*p < 0x7f)
					putchar(*p++);
				else
					putchar('.');
		}
#endif
		return 0; /* don't passthru */

	/* uninterpreted http content */
	case LWS_CALLBACK_RECEIVE_CLIENT_HTTP:
		{
			char buffer[1024 + LWS_PRE];
			char *px = buffer + LWS_PRE;
			int lenx = sizeof(buffer) - LWS_PRE;

			if (lws_http_client_read(wsi, &px, &lenx) < 0)
				return -1;
		}
		return 0; /* don't passthru */

	case LWS_CALLBACK_COMPLETED_CLIENT_HTTP:
		lwsl_user("LWS_CALLBACK_COMPLETED_CLIENT_HTTP\n");
		client_wsi = NULL;
		bad = status != 200;
		lws_cancel_service(lws_get_context(wsi)); /* abort poll wait */
		break;

	case LWS_CALLBACK_CLOSED_CLIENT_HTTP:
		client_wsi = NULL;
		bad = status != 200;
		lws_cancel_service(lws_get_context(wsi)); /* abort poll wait */
		break;

	default:
		break;
	}

	return lws_callback_http_dummy(wsi, reason, user, in, len);
}

static const struct lws_protocols protocols[] = {
	{
		"http",
		callback_http,
		0,
		0,
	},
	{ NULL, NULL, 0, 0 }
};

static void
sigint_handler(int sig)
{
	interrupted = 1;
}

struct lws_context_creation_info info;
struct lws_client_connect_info i;

struct lws_context* createcontextandconnect()
{
  struct lws_context* context = lws_create_context(&info);
  if (!context) {
    lwsl_err("lws init failed\n");
    return NULL;
  }
  memset(&i, 0, sizeof i); /* otherwise uninitialized garbage */
  i.context = context;
  i.ssl_connection = LCCSCF_USE_SSL;

  i.port = 443;
  i.address = "warmcat.com";
  i.path = "/";
  i.host = i.address;
  i.origin = i.address;

  i.method = "GET";

  i.protocol = protocols[0].name;
  i.pwsi = &client_wsi;
  lws_client_connect_via_info(&i);
  return context;
}

int main(int argc, const char **argv)
{
  struct lws_context *context1;
  struct lws_context *context2;
  const char *p;
  int n = 0, o = 0, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE
		   /*
		    * For LLL_ verbosity above NOTICE to be built into lws,
		    * lws must have been configured and built with
		    * -DCMAKE_BUILD_TYPE=DEBUG instead of =RELEASE
		    *
		    * | LLL_INFO   | LLL_PARSER  | LLL_HEADER | LLL_EXT |
		    *   LLL_CLIENT | LLL_LATENCY | LLL_DEBUG
		    */ ;

	signal(SIGINT, sigint_handler);

	if ((p = lws_cmdline_option(argc, argv, "-d")))
		logs = atoi(p);

	lws_set_log_level(logs, NULL);
	lwsl_user("LWS minimal http client [<-d <verbosity>] [-l] [--h1]\n");

	memset(&info, 0, sizeof info); /* otherwise uninitialized garbage */
	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	info.port = CONTEXT_PORT_NO_LISTEN; /* we do not run any server */
	info.protocols = protocols;
	/*
	 * since we know this lws context is only ever going to be used with
	 * one client wsis / fds / sockets at a time, let lws know it doesn't
	 * have to use the default allocations for fd tables up to ulimit -n.
	 * It will just allocate for 1 internal and 1 (+ 1 http2 nwsi) that we
	 * will use.
	 */
	info.fd_limit_per_thread = 1 + 1 + 1;

#if defined(LWS_WITH_MBEDTLS)
	/*
	 * OpenSSL uses the system trust store.  mbedTLS has to be told which
	 * CA to trust explicitly.
	 */
	info.client_ssl_ca_filepath = "./warmcat.com.cer";
#endif

  context1 = createcontextandconnect();
  lws_service(context1, 0);
  lws_service(context1, 0);

  context2 = createcontextandconnect();

  while ((n >= 0 || o >= 0) && client_wsi && !interrupted)
  {
    n = lws_service(context1, 0);
    o = lws_service(context2, 0);
  }

  lws_context_destroy(context1);
  lws_context_destroy(context2);
  lwsl_user("Completed: %s\n", bad ? "failed" : "OK");

	return bad;
}
```

**Comment by lws-team** [comment]
Right I see the point, but there are other problems with multiple contexts in one process... there are 90 or something minimal examples now and none of them show more than one context.

Usually it's advantageous to have just the one context and one thread with no possibility of contention... what's the situation you're addressing with having more than one context?

**Comment by martlaak-gmail** [comment]
We simply were not aware (since now, when we started to use more OpenSSL), that having multiple contexts can cause problems. 
IMO it is so natural to assume that there shouldn't be any problems with that - or why the context creation exists in libwebsocktes then overall (instead of one, global context)?

We have custom C++ websocket client wrapper for the libwebsockets. We have huge GUI application that creates uses these wrapper client in many separate cases:
* by background websocket server tracking
* by user server connects to one of the servers (while background tracking is still running)

IMO, libwebsockets documentation should specifically note if there can no be more than one context per thread or application - so everyone can be aware.

**Comment by lws-team** [comment]
Yes in lws with two exceptions (global log mask, so you can log before and after the context, and the openssl specific indexes) everything is based in the context as you would expect.

The difficulty is some things like fd tables are process scope, the process decides the next fd you'll get on open so you have to allocate for ulimit -n on all contexts if serving.

Event loops' big thing is you can dispense with locking when you're in one thread.  So having n contexts with n threads means you are back having to protect them against other threads if they will interact.

And in the recent past, openssl blew up if one process inited it more than once, modern openssl has fixed it with internal refcounts.

It is written in the readmes somewhere from years ago that to get the benefits, you should use one context.

However I'm not trying to say that index thing is great, it's just cruft from years ago, I was asking your situation to see if unifying the contexts was what you really needed.  If not, a patch improving the indexes to work with it is welcome.

**Comment by martlaak-gmail** [comment]
But this is not only one-thread-with-multiple-contexes issue. 
Because the indexes are global one context creation in one thread can cause trouble to other thread that is in the middle of TLS handshake and is depending on the value not to be changed.
Can't you just put these indexes to be part of the context?

**Comment by lws-team** [comment]
Yeah, well as you see, everything went into the context, directly or in other objects referenced from it, there are hundreds of members all rooted in the context.  But a couple of things can't it turned out.

Those indexes are also processwide things in openssl... they were originally done that way because there was a blind callback specified by openssl for verification

https://libwebsockets.org/git/libwebsockets/tree/lib/tls/openssl/openssl-client.c?id=beacabbdb1f45945e6458a21b84c3e8ad9943958#n47-48

I can't get the context pointer from there, at least I don't know another way but the processwide index.

If you have a better idea I'm all ears.

**Comment by lws-team** [comment]
We got sidelined by "why are you using globals for this", I explained why no choice when building with openssl apis.  But it obscured that you already had a good idea for your actual problem

> IMO, openssl_websocket_private_data_index and openssl_SSL_CTX_private_data_index should be tested if already generated, to achieve that they are generated only on first context create of the application.

I added a global char flag to say they were set already, happily although you must register them you don't have to deregister them.

https://libwebsockets.org/git/libwebsockets/commit/lib/tls/openssl?id=cd598c20792a269baeeb342e7a9662016bf27066

... and pushed it on main, please give it a try.

**Comment by martlaak-gmail** [comment]
Yes this patch works! 
By the way, you could also cope without separate flag introduced, by setting the indexes initially to -1 and testing against that. ;)

**Comment by lws-team** [comment]
It's cheaper to add a 1-byte flag than carry around 4 bytes of bss to init it with... but you know, it's not a competition.
