### ISSUE TITLE
How to catch timeout reason？

### ISSUE THREAD

**Issue by Non-Unruly** [warmcat/libwebsockets#2182]
I use lws_set_timeout_us to set timeout period ,
But how doI get timeout-reason ?

I look around in lws_timeout_timer.h and example-code , there is no gains ....

**Comment by lws-team** [comment]
Timeout is just a close.

In the logs, timeout id reported as TIMED OUT on xxx, where xxx is the enum index from here

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n35-73

**Comment by Non-Unruly** [comment]
> Timeout is just a close.
> 
> In the logs, timeout id reported as TIMED OUT on xxx, where xxx is the enum index from here
> 
> https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n35-73

um ....
I want to distinguish between  _server error_ and _client timeout_ , but both of them are close 
so , Is it too complex to come true?

**Comment by lws-team** [comment]
> so , Is it too complex to come true?

The information it was a timeout exists, but whether it was caused server side or client side or inbetween cannot be known, the client didn't see what it wanted fast enough is all you can know.

The timeout enums just tell you what step it was waiting for, not where the problem really was.

If you think that's useful to know in close, why not propose a patch?

**Comment by Non-Unruly** [comment]
> > so , Is it too complex to come true?
> 
> The information it was a timeout exists, but whether it was caused server side or client side or inbetween cannot be known, the client didn't see what it wanted fast enough is all you can know.
> 
> The timeout enums just tell you what step it was waiting for, not where the problem really was.
> 
> If you think that's useful to know in close, why not propose a patch?

well , thanks
I might have alternative solution about it
