### ISSUE TITLE
Is there any way disable HTTP/2 from HTTP server app side?

### ISSUE THREAD

**Issue by jinmuja-git** [warmcat/libwebsockets#2183]
I could disable HTTP/2 with 'LWS_WITH_HTTP2=OFF' when build libwebsockets.
But I want to know, there are any ways disable H2 from server app side even using HTTP/2 enabled lib.
I'm eager to left libwebsockets for other server apps and only control my http server app separatly.

With client example, I could see below way to enforce h1 instead h2.
[[
struct lws_client_connect_info i;
memset(&i, 0, sizeof i); 
i.alpn = "http/1.1";  /* force h1 even if h2 available */
]]
It does not seem to be supported on the server app.

**Comment by lws-team** [comment]
At vhost creation time (which by default is at context creation time using the same info struct) you can define the alpn offer for the vhost.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n464-470

By default lws goes through the available roles and makes a list of supported role alpn types as the offer, eg, "h2,http/1.1".

Same as you can tell the client he should only accept "http/1.1" alpn offer to control it, you can use the member above to directly specify what the vhost is going to offer on alpn, again in your case "http/1.1".

**Comment by jinmuja-git** [comment]
It's working fine. Thank you.
