### ISSUE TITLE
Using lws_create_vhost() in multithread

### ISSUE THREAD

**Issue by SeonahMoon** [warmcat/libwebsockets#2184]
Hello.

I wonder lws_create_vhost() is thread-safety or not.

Assume there are three threads.
- Main thread: a main thread which creates lws context when init time.
- A thread: external poll is working for handling lws events.
- B thread: other thread.

In this case, if lws_create_vhost() is called in B thread, does it occur any problem?

**Comment by lws-team** [comment]
Only a very few apis in lws are threadsafe, the answer to "is lws_xxx() threadsafe" is going to be "no" unless it is `lws_cancel_service()` or another api that specifically state it is threadsafe.

The purpose of the event loop is to serialize accesses to anything owned by lws and so guarantee there can be no access contention, without any need for locking.  If you call lws apis outside of the serialized service thread, any kind of conflict can and will happen.

The general solution is ideally just put it all on lws event loop, if not possible indicate what the other thread wants in a locked, shared memory area and then call `lws_cancel_service()` to make the lws thread go look at what is wanted and handle it from the lws thread context.
