### ISSUE TITLE
client side certs cannot be changed when using multiple vhosts

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2186]
The following code will fail
```
...
	context = lws_create_context(&info);
	if (!context) {
		lwsl_err("lws init failed\n");
		return 1;
	}

	info.vhost_name = "test1";


	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}

	info.port = CONTEXT_PORT_NO_LISTEN;

	info.client_ssl_ca_filepath = "./ca";
	info.client_ssl_private_key_filepath = "./key";
	info.client_ssl_cert_filepath = "./cert";

	info.vhost_name = "test2";
	

	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}


	while (n >= 0 && !interrupted)
		n = lws_service(context, 0);

	lws_context_destroy(context);
...

```

with 

`[2021/01/28 17:30:04:8801] E: CLIENT_CONNECTION_ERROR: connect SSL err 1: error:00000001:lib(0):func(0):reason(1)
`

if I change to this:
```
	context = lws_create_context(&info);
	if (!context) {
		lwsl_err("lws init failed\n");
		return 1;
	}


	info.client_ssl_ca_filepath = "./ca";
	info.client_ssl_private_key_filepath = "./key";
	info.client_ssl_cert_filepath = "./cert";


	info.vhost_name = "test1";

	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}

	info.port = CONTEXT_PORT_NO_LISTEN;


	info.vhost_name = "test2";
	
	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}

	lws_init_vhost_client_ssl(&info, vhost);



	while (n >= 0 && !interrupted)
		n = lws_service(context, 0);

	lws_context_destroy(context);
```

with 

```
	info.client_ssl_ca_filepath = "./ca";
	info.client_ssl_private_key_filepath = "./key";
	info.client_ssl_cert_filepath = "./cert";

```

before the vhost creation, it works

For server-side certs, we don't have the same issue.

I'm using the minimal ws  proxy as an example
```
minimal-examples/client-server/minimal-ws-proxy/protocol_lws_minimal.c
minimal-examples/client-server/minimal-ws-proxy/minimal-ws-proxy.c
```

The idea is to be able to create vhosts (clients) on the fly and assign client-side certs so the can connect to different ws endpoints
```
client cmd (lws proxy)           => ws endpoint 1 (key, ca cert #1)
                                 => ws endpoint 2 (key, ca, cert #2)
```
      

Alex

**Comment by alexeadem** [comment]
I also tried this with no luck
```
	const char *cipher_list = info.client_ssl_cipher_list;

	memset(&info, 0, sizeof(info));
	//info.port = CONTEXT_PORT_NO_LISTEN;

	info.client_ssl_ca_filepath = "./ca";
	info.client_ssl_private_key_filepath = "./key";
	info.client_ssl_cert_filepath = "./cert";
	info.client_ssl_cipher_list = cipher_list;
	//info.provided_client_ssl_ctx = NULL;


	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

	lws_init_vhost_client_ssl(&info, vhost);
```
Looking into the ssl piece now

**Comment by lws-team** [comment]
Hm... don't think so.  Because there's code in wide use that does exactly this, generate n vhosts with different client validation arrangements, after the context was created.

> info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

vhost creation cares about options, but that one is only of interest to context creation, to use tls at all it must be set at context creation time.  You're also killing the other inherited options like `LWS_SERVER_OPTION_EXPLICIT_VHOSTS` it might care about by setting it that way.

You don't show the options in force when you create the context...

```
connect SSL err 1: error:00000001:lib(0):func(0):reason(1) 
```
... this looks like nothing set in the SSL_CTX... you don't show how you create the client connection, are you setting the .vhost in the client connection info struct to your second vhost?  Otherwise it will default to bind to your first vhost, which has no initialized SSL_CTX for client conns...

**Comment by alexeadem** [comment]
You're right.

Here is my working example also showing how the client connection happens
in `/minimal-examples/client-server/minimal-ws-proxy/minimal-ws-proxy.c`

```
...
	memset(&info, 0, sizeof info); 
	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT |  LWS_SERVER_OPTION_EXPLICIT_VHOSTS;

	context = lws_create_context(&info);
	if (!context) {
		lwsl_err("lws init failed\n");
		return 1;
	}

	info.vhost_name = "test1";
	info.ssl_cert_filepath = "localhost-100y.cert";
	info.ssl_private_key_filepath = "localhost-100y.key";
	info.port = 7681;
	info.mounts = &mount;
	info.protocols = protocols;

	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}


	memset(&info, 0, sizeof(info));

       /* need to add again cause I just cleared it */
	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT | LWS_SERVER_OPTION_EXPLICIT_VHOSTS;
	info.port = CONTEXT_PORT_NO_LISTEN;
	info.vhost_name = "test2";

	info.client_ssl_ca_filepath = "./ca";
	info.client_ssl_private_key_filepath = "./key";
	info.client_ssl_cert_filepath = "./cert";
	
	info.protocols = protocols;

	vhost = lws_create_vhost(context, &info);
	if (!vhost) {
		lwsl_err("vhost creation failed\n");
		return -1;
	}
...

...

and in `minimal-examples/client-server/minimal-ws-proxy/protocol_lws_minimal.c`

```
static void
sul_connect_attempt(struct lws_sorted_usec_list *sul)
{
	struct per_vhost_data__minimal *vhd =
	lws_container_of(sul, struct per_vhost_data__minimal, sul);

	vhd->i.context = vhd->context;

	if(!strcmp("test2", lws_get_vhost_name(vhd->vhost))) {

		lwsl_user("%s: vh %s\n", __func__, lws_get_vhost_name(vhd->vhost));

		vhd->i.address = "192.168.96.10";
		vhd->i.port = 6443;
		vhd->i.path = "/api/hello/endpoint";
		vhd->i.host = vhd->i.address;
		vhd->i.origin = vhd->i.address;
		vhd->i.ssl_connection = 1;

		//vhd->i.protocol = "dumb-increment-protocol";
		vhd->i.protocol = "";
		vhd->i.local_protocol_name = "lws-minimal-proxy";
		vhd->i.pwsi = &vhd->client_wsi;
		vhd->i.vhost = lws_get_vhost_by_name(vhd->context, "test2");

		lws_client_connect_via_info(&vhd->i);


	}

}

```

Thank You Andy!

**Comment by lws-team** [comment]
Glad you're working.
