### ISSUE TITLE
Compile LibWebSockets for Microsoft Game Development Kit 

### ISSUE THREAD

**Issue by jzer0** [warmcat/libwebsockets#2187]
Hi LibWebSockets,

I'm looking to build libwebsockets libs for use with applications compiled using the Microsoft Game Development Kit (https://www.microsoft.com/en-us/software-download/gdk) for the Gaming.Desktop.x64 and Gaming.Xbox.Scarlett.x64 platform configurations. Installing this package provides for the following configurations in Visual Studio:

![image](https://user-images.githubusercontent.com/8395705/106266652-fdba7000-6228-11eb-833e-c2317faf5b3e.png)

I would like to know whether it is currently possible or supported to compile libwebsockets for these platform configurations.

**Comment by lws-team** [comment]
Have I every built anything on that platform?  No.

Does it build fine on windows and a bunch of other platforms (24 in CI currently)... Yes.

Since lws uses cmake, it looks like your platform uses visual studio that nowadays understands cmake, just try build it and see what happens.

**Comment by lws-team** [comment]
If there are problems from lws side, let me know.
