### ISSUE TITLE
Build issues with some configs

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#2190]
`main` branch:

* `lws_metrics_hist_bump_priv_wsi()` is called but undefined if `LWS_WITH_SYS_METRICS=OFF`
* Windows MSVC: `lib\roles\h2\ops-h2.c(1321,13): error C2059: syntax error: '}'` with `LWS_WITHOUT_SERVER=ON`
* Windows MSVC: `lib\plat\windows\windows-sockets.c(184,11): error C2039: 'udp': is not a member of 'lws'` with `LWS_WITH_UDP=OFF `
* `lib\roles\http\server\server.c(808,52): error C2065: 'WSI_TOKEN_PUT_URI': undeclared identifier` (and the next two lines as  well) with `LWS_WITH_HTTP_UNCOMMON_HEADERS=OFF`
* Android armeabi-v7a: `socklen_t` is `int`, not `unsigned int`, thus `network.c:109:56` and `network.c:294:22` fail due to casting to `unsigned int`

**Comment by lws-team** [comment]
Thanks... you're really giving it a workout.

I pushed a patch fixing these and adding CI scenarios for most of them.

**Comment by vaind** [comment]
Any idee when this would land in the main branch on GH?
