### ISSUE TITLE
Close POST connection in LWS_CALLBACK_HTTP

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2191]
When server is receiving a POST, the connection is not closed if LWS_CALLBACK_HTTP returns !0.
In file `ops-h2.c` the function `lws_h2_bind_for_post_before_action()` do not use the return value when calling LWS_CALLBACK_HTTP.
Is it normal?

**Comment by lws-team** [comment]
No it seems wrong... does this solve it?

https://libwebsockets.org/git/libwebsockets/commit?id=ee062be40843a7fdf0aa3cda8744fe975bf79d11

**Comment by Piero01** [comment]
No it doesn't solve the issue.

I suspect line 824 in `ops-h2.c` :

```
   if (lws_http_get_uri_and_method(wsi, &uri_ptr, &uri_len) >= 0)
        wsi->a.protocol->callback(wsi, LWS_CALLBACK_HTTP,
        wsi->user_space, hit ? uri_ptr + hit->mountpoint_len : uri_ptr,
            (size_t)(hit ? uri_len - hit->mountpoint_len : uri_len));
```

callback is called with LWS_CALLBACK_HTTP reason and the return value is not checked so lws doesn't know it should close or continue.

**Comment by lws-team** [comment]
I see... you'll also need to deal with it as in the first patch as well though.  How about this then?

https://libwebsockets.org/git/libwebsockets/commit?id=611e6477fdb4c2f8318bce43bbfb6ab7760c2e1e

**Comment by Piero01** [comment]
It's working. Thank you.

**Comment by lws-team** [comment]
Great.
