### ISSUE TITLE
incompatible with openssl-3.0.0-alpha11.tar.gz 

### ISSUE THREAD

**Issue by HyunjunAhn** [warmcat/libwebsockets#2200]
When running make...

error: 'EC_KEY_new_by_curve_name' is deprecated .....

**Comment by lws-team** [comment]
So this deprecation is new in -alpha11... I do actually build against openssl v3 in CI for a while.

I pushed a patch on main to just not build the specific EC curve vhost support if it's v3 openssl, I don't think anyone uses that.  That makes this error go away for default builds with no other changes needed.

There's a bit of a wider problem, I knew for a while v3 deprecates some other apis that are used in `LWS_WITH_GENCRYPTO`, which definitely is in use by others.  The apis still exist, just marked deprecated.  I looked at updating them to the PKEY apis but it's a subproject of its own I don't have time for in the near future (patches are extremely welcome...)

This patch on main also adds a cmake option `-DLWS_SUPPRESS_DEPRECATED_API_WARNINGS=1`, this allows the build to proceed even for GENCRYPTO for when people start using openssl v3.  I added an extra case in the CI that checks we can still build everything including GENCRYPTO against v3-alpha11 if -DLWS_SUPPRESS_DEPRECATED_API_WARNINGS=1 is given.

So together these should solve it.
