### ISSUE TITLE
About the LWS_CALLBACK_SERVER_WRITEABLE call in V4.1.

### ISSUE THREAD

**Issue by kunio-fujiwara** [warmcat/libwebsockets#2202]
I changed libwebsockets from V3.1 to V4.1.
I'm using it for an application that sends data every 100ms, but after changing to V4.1, LWS_CALLBACK_SERVER_WRITEABLE is now called at 1Hz.
Apparently lws_service is running at 1Hz and lLWS_CALLBACK_SERVER_WRITEABLE is occurring immediately after calling lws_service.
How can I generate LWS_CALLBACK_SERVER_WRITEABLE at high speed in V4.1?

**Comment by lws-team** [comment]
> Apparently lws_service is running at 1Hz

No... it sleeps if nothing to do, when something to do it will wake.  If something internal has something to do at 1Hz, it will wake at 1Hz.

If you want to schedule things, the lws_sul apis allow you to schedule as many things as you like at us resolution (although depending on the platform, that may only have ms resolution)

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

You can specify the callback for each lws_sul independently, it's not tied to any wsi or protocol.

**Comment by kunio-fujiwara** [comment]
Thank you for quick reply.
I have called lws_callback_on_writable_all_protocol 10 times during this 1Hz, but LWS_CALLBACK_SERVER_WRITEABLE is not called. However, LWS_CALLBACK_SERVER_WRITEABLE is called immediately after the next lws_service call. Is this a specification?
V3.1 did not behave like this.

**Comment by lws-team** [comment]
What's your platform?  If it's windows, use main branch instead of v4.1.

**Comment by kunio-fujiwara** [comment]
First I tested libwebsocket on Ubuntu. This worked as expected.
Then when I tested libwebsockets in Yokto, I got this behavior.
Does Ubuntu and Yokto behave differently?

**Comment by lws-team** [comment]
It seems your Yocto acts different, but it is just another Linux distro.

Asking for a callback_on_writable() is the same as asking for POLLOUT event, you should build lws in CMAKE_BUILD_TYPE=DEBUG and dump the verbose logs and see if a clue in there.

**Comment by lws-team** [comment]
... also the provided `libwebsockets-test-server` has this kind of ws timed tx pattern at 20Hz, does that have the same problem or work OK?

**Comment by kunio-fujiwara** [comment]
Oh, I don't have much time to investigate it.
The purpose of using V4.1 is to send PING / PONG packets automatically. I used ws_ping_pong_interval in V3.1, but it didn't work, so I have no choice but to change to V4.1.
Does the function to automatically send PING / PONG packets work in V3.1? If so, please give me a good sample.

ちon't have much time to investigate it.
The purpose of using V4.1 is to send PING / PONG packets automatically. I used ws_ping_pong_interval in V3.1, but it didn't work, so I have no choice but to change to V4.1.
Does the function to automatically send PING / PONG packets work in V3.1? If so, please give me a good sample.

I'll try to investigation that you suggest.

**Comment by lws-team** [comment]
You should try the example, because there's no known problem like you're saying outside of windows.  And that was solved on main.

It's simpler to think there's something unusual about your code, if the "dumb-increment" protocol works fine in the example at 20Hz, then you can know there is no problem in lws and look at your code (bad usage of threads etc).  If it's the same problem just with lws code, then we know to look in that direction instead.

**Comment by kunio-fujiwara** [comment]
OK.
I'll check my code.

**Comment by lws-team** [comment]
If the test server doesn't work the same way, let me know.  Otherwise there's nothing for me to do about it.
