### ISSUE TITLE
crash with execute libwebsockets-test-server

### ISSUE THREAD

**Issue by jundai20** [warmcat/libwebsockets#2203]
Run libwebsocket-test-server on ubuntu 20.04 with latest version (2021/2/16), clean build
Tested both firefox & Chrome (Version 88.0.4324.150 (Official Build) (64-bit). 

Crashed backtrace and memory check result of valgrind  as below.

Program received signal SIGSEGV, Segmentation fault.
0x000055555555dc3c in callback_lws_status (wsi=0x5555555d7b70, reason=LWS_CALLBACK_ESTABLISHED, user=0x5555555d8030, in=0x0, len=0)
    at /home/judai/opensrc/libwebsockets/test-apps/../plugins/protocol_lws_status.c:120
120			vhd->count_live_pss++;
(gdb) p vhd
$1 = (struct per_vhost_data__lws_status *) 0x0
(gdb) bt
#0  0x000055555555dc3c in callback_lws_status (wsi=0x5555555d7b70, reason=LWS_CALLBACK_ESTABLISHED, user=0x5555555d8030, in=0x0, len=0)
    at /home/judai/opensrc/libwebsockets/test-apps/../plugins/protocol_lws_status.c:120
#1  0x000055555559477a in lws_server_init_wsi_for_ws (wsi=0x5555555d7b70) at /home/judai/opensrc/libwebsockets/lib/roles/ws/ops-ws.c:855
#2  0x0000555555598b25 in lws_process_ws_upgrade2 (wsi=0x5555555d7b70) at /home/judai/opensrc/libwebsockets/lib/roles/ws/server-ws.c:405
#3  0x0000555555599002 in lws_process_ws_upgrade (wsi=0x5555555d7b70) at /home/judai/opensrc/libwebsockets/lib/roles/ws/server-ws.c:634
#4  0x0000555555581f03 in lws_handshake_server (wsi=0x5555555d7b70, buf=0x7fffffffcda0, len=0) at /home/judai/opensrc/libwebsockets/lib/roles/http/server/server.c:2305
#5  0x000055555558575b in lws_read_h1 (wsi=0x5555555d7b70, buf=0x5555555d0779 "i7N6SXV7JHvN/qvEpkU=\r\nSec-WebSocket-Protocol: lws-status\r\n\r\n", len=489)
    at /home/judai/opensrc/libwebsockets/lib/roles/h1/ops-h1.c:78
#6  0x00005555555860c7 in lws_h1_server_socket_service (wsi=0x5555555d7b70, pollfd=0x5555555d19d8) at /home/judai/opensrc/libwebsockets/lib/roles/h1/ops-h1.c:444
#7  0x00005555555864ae in rops_handle_POLLIN_h1 (pt=0x5555555d0018, wsi=0x5555555d7b70, pollfd=0x5555555d19d8) at /home/judai/opensrc/libwebsockets/lib/roles/h1/ops-h1.c:635
#8  0x00005555555737a2 in lws_service_fd_tsi (context=0x5555555cfd60, pollfd=0x5555555d19d8, tsi=0) at /home/judai/opensrc/libwebsockets/lib/core-net/service.c:735
#9  0x00005555555a0954 in _lws_plat_service_forced_tsi (context=0x5555555cfd60, tsi=0) at /home/judai/opensrc/libwebsockets/lib/plat/unix/unix-service.c:49
#10 0x00005555555a0d5a in _lws_plat_service_tsi (context=0x5555555cfd60, timeout_ms=2000000000, tsi=0) at /home/judai/opensrc/libwebsockets/lib/plat/unix/unix-service.c:212
#11 0x00005555555a0def in lws_plat_service (context=0x5555555cfd60, timeout_ms=0) at /home/judai/opensrc/libwebsockets/lib/plat/unix/unix-service.c:231
#12 0x000055555557395c in lws_service (context=0x5555555cfd60, timeout_ms=0) at /home/judai/opensrc/libwebsockets/lib/core-net/service.c:805
#13 0x000055555555f78d in main (argc=1, argv=0x7fffffffe098) at /home/judai/opensrc/libwebsockets/test-apps/test-server.c:701

@VirtualBox:~/opensrc/libwebsockets/build/bin$ valgrind ./libwebsockets-test-server
==9561== Memcheck, a memory error detector
==9561== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9561== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==9561== Command: ./libwebsockets-test-server
==9561== 
[2021/02/15 21:24:48:7226] N: libwebsockets test server - license MIT
[2021/02/15 21:24:48:7846] N: (C) Copyright 2010-2018 Andy Green <andy@warmcat.com>
Using resource path "/usr/local/share/libwebsockets-test-server"
[2021/02/15 21:24:48:7909] N: LWS: 4.1.99-v4.1.0-277-g1be29f4f, loglevel 1031
[2021/02/15 21:24:48:7914] N: NET CLI SRV H1 H2 WS IPv6-absent
[2021/02/15 21:24:48:8512] N:  ++ [wsi|0|pipe] (1)
[2021/02/15 21:24:48:8595] N:  ++ [vh|0|netlink] (1)
[2021/02/15 21:24:48:8794] N:  ++ [vh|1|default] (2)
[2021/02/15 21:24:48:9132] N: lws_socket_bind: nowsi: source ads 0.0.0.0
[2021/02/15 21:24:48:9266] N:  ++ [wsi|1|listen|default||7681] (2)
[2021/02/15 21:24:56:6843] N:  ++ [wsisrv|0|adopted] (1)
[2021/02/15 21:24:56:7260] N:  ++ [wsisrv|1|adopted] (2)
[2021/02/15 21:24:57:0076] N:  ++ [wsisrv|2|adopted] (3)
[2021/02/15 21:24:57:1838] N:  ++ [wsisrv|3|adopted] (4)
[2021/02/15 21:24:57:3168] N:  ++ [wsisrv|4|adopted] (5)
==9561== Invalid read of size 4
==9561==    at 0x111C3C: callback_lws_status (protocol_lws_status.c:120)
==9561==    by 0x148779: lws_server_init_wsi_for_ws (ops-ws.c:855)
==9561==    by 0x14CB24: lws_process_ws_upgrade2 (server-ws.c:405)
==9561==    by 0x14D001: lws_process_ws_upgrade (server-ws.c:634)
==9561==    by 0x135F02: lws_handshake_server (server.c:2305)
==9561==    by 0x13975A: lws_read_h1 (ops-h1.c:78)
==9561==    by 0x13A0C6: lws_h1_server_socket_service (ops-h1.c:444)
==9561==    by 0x13A4AD: rops_handle_POLLIN_h1 (ops-h1.c:635)
==9561==    by 0x1277A1: lws_service_fd_tsi (service.c:735)
==9561==    by 0x154953: _lws_plat_service_forced_tsi (unix-service.c:49)
==9561==    by 0x154D59: _lws_plat_service_tsi (unix-service.c:212)
==9561==    by 0x154DEE: lws_plat_service (unix-service.c:231)
==9561==  Address 0x20 is not stack'd, malloc'd or (recently) free'd
==9561== 
==9561== 
==9561== Process terminating with default action of signal 11 (SIGSEGV)
==9561==  Access not within mapped region at address 0x20
==9561==    at 0x111C3C: callback_lws_status (protocol_lws_status.c:120)
==9561==    by 0x148779: lws_server_init_wsi_for_ws (ops-ws.c:855)
==9561==    by 0x14CB24: lws_process_ws_upgrade2 (server-ws.c:405)
==9561==    by 0x14D001: lws_process_ws_upgrade (server-ws.c:634)
==9561==    by 0x135F02: lws_handshake_server (server.c:2305)
==9561==    by 0x13975A: lws_read_h1 (ops-h1.c:78)
==9561==    by 0x13A0C6: lws_h1_server_socket_service (ops-h1.c:444)
==9561==    by 0x13A4AD: rops_handle_POLLIN_h1 (ops-h1.c:635)
==9561==    by 0x1277A1: lws_service_fd_tsi (service.c:735)
==9561==    by 0x154953: _lws_plat_service_forced_tsi (unix-service.c:49)
==9561==    by 0x154D59: _lws_plat_service_tsi (unix-service.c:212)
==9561==    by 0x154DEE: lws_plat_service (unix-service.c:231)
==9561==  If you believe this happened as a result of a stack
==9561==  overflow in your program's main thread (unlikely but
==9561==  possible), you can try to increase the size of the
==9561==  main thread stack using the --main-stacksize= flag.
==9561==  The main thread stack size used in this run was 8388608.
==9561== 
==9561== HEAP SUMMARY:
==9561==     in use at exit: 42,933 bytes in 66 blocks
==9561==   total heap usage: 129 allocs, 63 frees, 88,379 bytes allocated
==9561== 
==9561== LEAK SUMMARY:
==9561==    definitely lost: 0 bytes in 0 blocks
==9561==    indirectly lost: 0 bytes in 0 blocks
==9561==      possibly lost: 0 bytes in 0 blocks
==9561==    still reachable: 42,933 bytes in 66 blocks
==9561==         suppressed: 0 bytes in 0 blocks
==9561== Rerun with --leak-check=full to see details of leaked memory
==9561== 
==9561== For lists of detected and suppressed errors, rerun with: -s
==9561== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by lws-team** [comment]
If you look at his logs, has he had trouble during context init, eg failed on pulling in an old plugin or so?  Delete any plugins if so from the install path, rebuild, retry.

**Comment by lws-team** [comment]
Sorry I see I missed the point when I read this at 2am.

main has an update that fixes this, please give it a try.
