### ISSUE TITLE
something about building example ws-client/minimal-ws-client-binance

### ISSUE THREAD

**Issue by ahao1995** [warmcat/libwebsockets#2205]
sorry to bother you
when I want to run ws-client/minimal-ws-client-binance this example,there is some bugs I dont understand.

[root@VM-4-2-centos libwebsockets-4.1.0]# cd /root/libwebsockets-4.1.0/minimal-examples/ws-client/minimal-ws-client-binance
[root@VM-4-2-centos minimal-ws-client-binance]# mkdir build
[root@VM-4-2-centos minimal-ws-client-binance]# cd build
[root@VM-4-2-centos build]# cmake ..
-- The C compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAS_LWS_ROLE_WS
-- Performing Test HAS_LWS_ROLE_WS - Success
-- Performing Test HAS_LWS_WITH_CLIENT
-- Performing Test HAS_LWS_WITH_CLIENT - Success
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS
-- Performing Test HAS_LWS_WITHOUT_EXTENSIONS - Success
CMake Error at /usr/local/lib/cmake/libwebsockets/LwsCheckRequirements.cmake:52 (message):
  Lws configuration of LWS_WITHOUT_EXTENSIONS is incompatible with this
  project
Call Stack (most recent call first):
  CMakeLists.txt:15 (require_lws_config)

-- Configuring incomplete, errors occurred!

maybe something wrong about LWS_WITHOUT_EXTENSIONS,can you tell me how to run this example?
thank you!

**Comment by lws-team** [comment]
Build lws with cmake option `-DLWS_WITHOUT_EXTENSIONS=0`

**Comment by ahao1995** [comment]
> 
> 
> Build lws with cmake option `-DLWS_WITHOUT_EXTENSIONS=0`

you mean to build libwebsockets library with cmake -DLWS_WITHOUT_EXTENSIONS=0 .. and then build this demo?

**Comment by lws-team** [comment]
Yeah.
