### ISSUE TITLE
lws_dll2_add_sorted assert(p!=d) failed

### ISSUE THREAD

**Issue by codingtrack** [warmcat/libwebsockets#2210]
#3  0x00007f88d9c0a202 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000009a9fd9 in lws_dll2_add_sorted (d=0x7f88ac000c98, own=0x17b11b8, compare=0x979b79 <sul_compare>) at libwebsockets-4.1.2/lib/core/lws_dll2.c:192
#5  0x0000000000979c20 in __lws_sul_insert (own=0x17b11b8, sul=0x7f88ac000c98) at libwebsockets/libwebsockets-4.1.2/lib/core-net/sorted-usec-list.c:62
#6  0x0000000000979cc5 in lws_sul2_schedule (context=0x17b0f30, tsi=0, flags=0, sul=0x7f88ac000c98) at libwebsockets-4.1.2/lib/core-net/sorted-usec-list.c:84
#7  0x000000000097a098 in lws_sul_schedule (ctx=0x17b0f30, tsi=0, sul=0x7f88ac000c98, _cb=0x99f23e <lws_client_conn_wait_timeout>, _us=5000000) at libwebsockets-4.1.2/lib/core-net/sorted-usec-list.c:280
#8  0x000000000099fbc4 in lws_client_connect_3_connect (wsi=0x7f88ac000b00, ads=0x7f88ac000f68 "10.100.55.45", result=0x7f88ac0023c0, n=16, opaque=0x0) at libwebsockets-4.1.2/lib/roles/http/client/client-handshake.c:755
#9  0x00000000009a0416 in lws_client_connect_2_dnsreq (wsi=0x7f88ac000b00) at libwebsockets-4.1.2/lib/roles/http/client/client-handshake.c:1119
#10 0x00000000009a0d76 in lws_http_client_connect_via_info2 (wsi=0x7f88ac000b00) at libwebsockets-4.1.2/lib/roles/http/client/client-handshake.c:1550
#11 0x0000000000980786 in lws_header_table_attach (wsi=0x7f88ac000b00, autoservice=0) at libwebsockets-4.1.2/lib/roles/http/parsers.c:294
#12 0x000000000098a011 in rops_client_bind_h1 (wsi=0x7f88ac000b00, i=0x0) at libwebsockets-4.1.2/lib/roles/h1/ops-h1.c:995
#13 0x000000000097e95c in lws_client_connect_via_info (i=0x7f88beffb3f0) at libwebsockets-4.1.2/lib/core-net/connect.c:299

I use libwebsockets as client, shutdown server, and I do reconnect via call lws_client_connect_via_info every 5 seconds, sometimes it crashed here. I do connect in lws_service thread. do you know the reason?   libwebsockets version 4.1.2

**Comment by lws-team** [comment]
Looks like something isn't cleaning up its sul list?

4.1.2 is old, even on 4.1-stable, there's a 4.1.7.

This is in 4.1.3

https://libwebsockets.org/git/libwebsockets/commit?id=03a8fff42ad865259ed8ea0526cf112772465d26

I would use either v4.1-stable branch or main and see if it goes away.

**Comment by codingtrack** [comment]
https://libwebsockets.org/git/libwebsockets/commit?id=03a8fff42ad865259ed8ea0526cf112772465d26 
THIS commit will resolve the problem?

**Comment by lws-team** [comment]
Who knows!  Not you if you don't try a later version like v4.1-stable that already has dozens of fixes, including that one, you are ignoring.
