### ISSUE TITLE
what does "--" mean??

### ISSUE THREAD

**Issue by kboniadi** [warmcat/libwebsockets#2213]
Could I get some help with understanding what is happening at the bottom two lines. I'm initializing three websocket ports: 9000, 9002, 9001 in that order. At random, to any one of the ports, I'll get an output like the last two lines in the screenshot. Despite the client trying to connect, the LWS_CALLBACK_ESTABLISHED is never called.

![Screenshot_20210224_104053](https://user-images.githubusercontent.com/67992622/109049156-c5be1580-768c-11eb-958c-4f71af6c0df9.png)

**Comment by lws-team** [comment]
The `++` means something was created (a vhost or wsi or server wsi or whatever as described in the first part of the tag.

The `--` means the tagged things was destroyed.

Turn up the logging (build with cmake -DCMAKE_BUILD_TYPE=DEBUG and set the loglevel bitmap to, eg, 1039 or 1151 to see what's happening inbetween those two things.

**Comment by kboniadi** [comment]
Sorry, is this how you set the loglevel bitmap: `cmake --log-level=1039 .. -DCMAKE_BUILD_TYPE=DEBUG`?? I'm still getting loglevel 7 unfortunately. Thanks

**Comment by lws-team** [comment]
No the cmake thing gets the more verbose logs built in.  You can select what to show at runtime, in the examples, the -d switch is used to select which logs, eg, `-d 1039`, like this kind of thing

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-custom-headers/minimal-http-client-custom-headers.c?h=main#n161-164

**Comment by kboniadi** [comment]
ok so something weird is happening but here are my results. Using the loglevel 1039 I get this output which I still cant make to much sense of:

![image](https://user-images.githubusercontent.com/67992622/109065267-2e62bd80-76a0-11eb-9e71-2e237ebcc7ba.png)



NOW the weird part. So this issue that's been happening seems to be pretty random (sometimes everything works smoothly, sometimes the error above occurs). But running my code with loglevel 1151 hasn't produced that error even once (I've tried like 60+ times in a row already). I'm going to keep on trying till I get that error output with loglevel 1151 but does the above log output help you understand enough what could be my problem? Thanks

**Comment by lws-team** [comment]
You should name your vhosts when creating them yourself, they all need to have unique names in the context.  If you don't create your own explicit vhosts, it's OK to not bother and lws will name the default vhost created along with the context "default".  But it's not OK to call them all "default" if you make your own additional ones.  Refer to this

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost/minimal-http-server.c?h=main#n139

I dunno if that's behind your actual problem but it's easy to fix.

**Comment by kboniadi** [comment]
Thank you for the suggestion but unfortunately the problem still persists. Here is new logs:

  
![image](https://user-images.githubusercontent.com/67992622/109068760-235e5c00-76a5-11eb-9807-e1c1626f0598.png)

I just used a quick random string generator each time a vhost is created.

Like I said above.... still haven't been able to trigger this problem when using 1151 loglevel. Could this be related to the extra time that it take to print out extra log statements?

**Comment by kboniadi** [comment]
ok just did a comparison between logs when it work and when it doesn't and noticed that when it works there is only one instance of http-only and when it doesn't work there are two instances: (this is when it works)

![Screenshot_20210224_135148](https://user-images.githubusercontent.com/67992622/109070503-71745f00-76a7-11eb-9b9f-e2d6ff932b5f.png)

**Comment by lws-team** [comment]
They don't have to be random, just different, v1, v2 or whatever is OK.

(I was writing this when you also noticed it --->) Why does the log show http-only twice on that vhost?  Earlier your log shows dumb-increment coming twice... is your protocols list terminated with an empty one?  Or you're using plugins?

**Comment by lws-team** [comment]
... there's no threads involved in this part of your code, right?

**Comment by kboniadi** [comment]
just confirmed that the protocols list is null terminated:
```cpp
struct  lws_protocols protocols[] = {
    {
        "http-only",
        callback_http,
        65536,
        65536
    },
    {
        "dumb-increment-protocol",
        callback_dumb_increment,
        65536,
        65536
    },
    {
        NULL, NULL, 0   /* End of list */
    }
};
```

No, this section IS being called in multiple threads. If this is a problem would a mutex lock help???

**Comment by lws-team** [comment]
Lws is not threadsafe.

There's a single event loop thread for everything, which means no need for locking between everything that participates.

Why do you want threads?

**Comment by kboniadi** [comment]
I want to be able to create and destroy vhosts in different threads (as one might do with a regular network socket). For example I am calling `lws_create_vhost()` in potentially several different threads but to the best of my knowledge they are not called at the same time they are called in sequence. In this scenario should I add mutex locks? Could this possibly be causing the issue that I'm experiencing? 

`lws_callback_on_writable_all_protocol_vhost()` is a function that is call concurrently from several different threads. Could this cause an issue as well? And if so, do you think it can be resolved with mutex locks? Thank you.

**Comment by lws-team** [comment]
... no, it's just not threadsafe.  You can't do what you're doing.

You can have a context / event loop per thread.  But the fact you're not explaining why you need threads usually means you don't actually need them.
