### ISSUE TITLE
mingw compile problem

### ISSUE THREAD

**Issue by soermejo** [warmcat/libwebsockets#2214]
I have troubles compiling (make) with mingw on win 10. Is mingw still supported ?
i followed this guide https://libwebsockets.org/lws-api-doc-master/html/md_README_8build.html .
But i always get errors while doing make, i tried to comment some lines out, but there are too many errors. For example there is some problem with the gettimeofday.h a conflicting error in the redefinition of the struct timezone which is carried out in all of the other c files which use it.

Im using last version of mingw i just followed all the guidelines. Also the guideline seems a little be outdated as i had to add also some required headers in the mingw include folder to run make.

Is anyone capable of compiling libwebsockets on any windows system? Or does it exist a precompiled of this library?

**Comment by lws-team** [comment]
Windows builds on msvc and mingw are in CI, eg

https://libwebsockets.org/sai/index.html?task=8c9193418c90807522f7aecd47cded47dc16ce4bb34f4c6e61a1faef1f0290cb

... is the successful build for today's main branch on mingw 64 bit.

See how that builds it, using a toolchain file.

> But i always get errors while doing make

As an issue report, just telling you get 'errors' isn't something that leads to anyone being able to help you.
