### ISSUE TITLE
lws_service never returns

### ISSUE THREAD

**Issue by delasy** [warmcat/libwebsockets#2216]
Hey, Andy! First thing I should say that I appreciate huge amount of work done on this library and what you are doing to support it!
I've been searching through issues, through Google, through StackOverflow and couldn't find an answer for my issue. I found those issues: #1683, #1735, but they doesn't solve my issue.
My problem: I need to run `uv_run` myself. I tried a bunch of ways to prevent lws_service from blocking when using foreign loops but didn't found solution. Then I went through source code and found that I can just do
```c
uv_run(pt_to_priv_uv(&context->pt[tsi])->io_loop, UV_RUN_ONCE);
```
But unfortunately for myself I have no access to any of the context's properties. It simply fails `Incomplete definition of type 'struct lws_context'`. Also I tried
```c
lws_service(, -1);
lws_service(, 0);
```
But `lws_service` blocks entire thread until sigint.

<details>
  <summary>Here's my code</summary>
  
```c
uv_loop_t loop;
uv_loop_init(&loop);

struct lws_context_creation_info info;
memset(&info, 0, sizeof(info));

info.protocols = (struct lws_protocols []) {
  { "binary", lws_cb, sizeof(struct lws_session), 1024, 0, NULL, 0 },
  { NULL, NULL, 0, 0, 0, NULL, 0 }
};

info.port = config->port;
info.gid = -1;
info.uid = -1;
info.options = LWS_SERVER_OPTION_LIBUV;
info.vhost_name = config->host;
info.pt_serv_buf_size = 8192;

info.foreign_loops = (void **) {
  (void *) &loop
};

lws_set_log_level(0, NULL);
struct lws_context *ctx = lws_create_context(&info);

if (ctx == NULL) {
  uv_loop_close(&loop);
  return NULL;
}

lws_service(ctx, 0);
```
</details>

I guess the only way to accomplish this is to use libwebsockets without libuv and wrap call of lws_service in own `uv_timer_start` with repeat of 0? Is it possible that libwebsockets just add own listeners and give control of uv_run to external project?
Do you have any suggestions?

Thank you for help!

**Comment by lws-team** [comment]
> I need to run uv_run myself. I tried a bunch of ways to prevent lws_service from blocking when using foreign loops but didn't found solution.

You don't need to call lws_service() at all with a foreign loop.  It only exists to run the default, poll / select-based event loop and has no part if you're using an event library.

Rather than google look closer to home at the http-server-eventlib-foreign example and follow the flow there

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign?h=main

**Comment by delasy** [comment]
That's brilliant example, thank you for pointing in right direction!
<details>
  <summary>This is what I came up with</summary>

```c
#include <libwebsockets.h>
#include <uv.h>

static uv_loop_t loop;
static uv_timer_t timer;

struct lws_session {
  char addr[32];
};

int32_t lws_cb (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
  struct lws_session *session = user;

  switch (reason) {
    case LWS_CALLBACK_ESTABLISHED: {
      lws_get_peer_simple(wsi, session->addr, sizeof(session->addr));
      printf("CONNECT: %s\n", session->addr);
      break;
    }
    case LWS_CALLBACK_RECEIVE: {
      uint8_t *data = malloc(len);
      memcpy(data, in, len);
      printf("MESSAGE(%s): %s\n", session->addr, data);
      free(data);
      break;
    }
    case LWS_CALLBACK_CLOSED: {
      printf("DISCONNECT: %s\n", session->addr);
      break;
    }
    default: {
      break;
    }
  }

  return 0;
}

void timer_cb (uv_timer_t *t) {
  printf("Running\n");
}

struct lws_protocols lws_protocols[] = {
  { "binary", lws_cb, sizeof(struct lws_session), 1024, 0, NULL, 0 },
  { NULL, NULL, 0, 0, 0, NULL, 0 }
};

int32_t main () {
  lws_set_log_level(0, NULL);

  uv_loop_init(&loop);
  uv_timer_init(&loop, &timer);
  uv_timer_start(&timer, timer_cb, 0, 2000);

  void *foreign_loops[1];
  foreign_loops[0] = &loop;

  struct lws_context_creation_info info;
  memset(&info, 0, sizeof(info));

  info.protocols = lws_protocols;
  info.port = 8081;
  info.gid = -1;
  info.uid = -1;
  info.options = LWS_SERVER_OPTION_LIBUV;
  info.vhost_name = "localhost";
  info.pt_serv_buf_size = 8192;
  info.foreign_loops = foreign_loops;

  struct lws_context *ctx = lws_create_context(&info);

  if (ctx == NULL) {
    fprintf(stderr, "Error creating context\n");
    return 1;
  }

  return uv_run(&loop, UV_RUN_DEFAULT);
}
```
</details>

I got easily confused that I need to use `lws_service` to receive new connections, before I was using libwebsockets without libuv and I was using `lws_service` in loop.

Thank you for help!
