### ISSUE TITLE
Variable vhosts

### ISSUE THREAD

**Issue by ktb92677** [warmcat/libwebsockets#2217]
Hi! Is there a minimal example that I could reference that would show how to properly initialize several vhosts during run time based on user input? e.g. typing a specific query via console input would start a vhost on port 3000. later on a user could type in something else that would start a vhost on port 3001 etc.

**Comment by lws-team** [comment]
This example is how to do multiple vhosts, he is doing them all after context creation, but actually that's not required.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-multivhost?h=main

**Comment by ktb92677** [comment]
Just curious at what point in my program do I need to call this segment of code:

```c
while (n >= 0 && !interrupted)
                n = lws_service(context, 0);
```

I have an infinite loop right now running gathering user input in the main thread. It is not super clear to me whether I should start this while loop before or after calling lws_create_vhost. Also the example you have seems to show how to initialize a static number of vhosts. I am specifically looking on how to initialize a variable number of vhosts that could be allocated throughout the run time of my program.

**Comment by ktb92677** [comment]
Phrased slightly better where would my calls to scanf or cin go in the example code provided?

**Comment by ktb92677** [comment]
Just to avoid any further confusion I cannot just accumulate calls to create new vhosts from the user and create them all in one go. I need them listening and active as the user requests them.

**Comment by lws-team** [comment]
> Also the example you have seems to show how to initialize a static 

There are practical constraints on the number of examples I can sit here and make on the off-chance someone comes along years later and cares about it.  That shows how to do it, as I said

>> he is doing them all after context creation, but actually that's not required.

> Just to avoid any further confusion

I think neither of us will be confused if you read the above.

> Just curious at what point in my program do I need to call this segment of code:

That is the default event loop.  If you already have an event lib, like libuv or whatever, lws can work with that instead and not need its own.

> I have an infinite loop right now running gathering user input in the main thread.

Your thread is going to either be dedicated to your "event loop" or the lws one.  Or, if your input is from an fd like /dev/input, you can just put your input management into the lws loop as well.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/raw/minimal-raw-file/minimal-raw-file.c?h=main

**Comment by ktb92677** [comment]
So scanf is normally an infinite blocking function, will that cause problems if I put it inside the lws loop?

**Comment by lws-team** [comment]
Of course, it's a "nonblocking event loop".

**Comment by ktb92677** [comment]
Also can I have calls to lws_create_vhost inside of the lws_service while loop?

**Comment by lws-team** [comment]
Yes.

**Comment by ktb92677** [comment]
> Of course, it's a "nonblocking event loop".

Okay fair enough, I can use select() to make scanf non-blocking. With that added modification can I reasonably add a scanf call inside of the lws_service loop?

**Comment by ktb92677** [comment]
And finally I've read many many examples and I don't see any that are doing anything similar to what I am trying to accomplish, the lws_service while loop always only has the one call to lws_service. Why is that? Is what I am trying to do unusual?

**Comment by lws-team** [comment]
> Why is that? Is what I am trying to do unusual?

Yeah.  `scanf()` is a beginner mistake security apocalypse.

http://sekrit.de/webdocs/c/beginners-guide-away-from-scanf.html

of course you won't find it in lws.

**Comment by ktb92677** [comment]
That's not quite what I mean. I don't see any lws examples with complex lws_service while loops. Is there any specific reason for that? If it is possible to add different signals and user inputs within the lws_service while loop why not have at least one example of it?

Finally just confirming that non-blocking user input that triggers lws_create_vhost calls are absolutely allowed inside of the lws_service while loop?

**Comment by lws-team** [comment]
> I don't see any lws examples with complex lws_service while loops

Can I gently suggest you stop asking me questions about how and why event loops work, and use google?

**Comment by ktb92677** [comment]
Yes, apologies for the persistent questions. Thank you for the support
