### ISSUE TITLE
getaddrinfo -11 when creating over around 1,000 websocket connections

### ISSUE THREAD

**Issue by xCuri0** [warmcat/libwebsockets#2218]
I'm creating 1,300 connections to the same websocket server and at around the 1000th connection I start getting ```getaddrinfo``` -11 failed errors and subsequent connections don't work. Tried using async dns and it also gave the same error. I think it's running into some sort of system limit so it probably would be better to reuse the ```getaddrinfo``` from previous connections.

System is Arch Linux

**Comment by lws-team** [comment]
This sounds like your process default `ulimit -n` is 1024, if so, something will break before you get to 1300 connections, be it getaddrinfo or something else.

You can ask lws to try to override it

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h?h=main#n769-772

but the situation about what will be allowed is decided by your OS / kernel, you can google around for how to increase the limit with Arch.

**Comment by xCuri0** [comment]
@lws-team thanks i will try that. also is there a way to get libwebsockets to reuse getaddrinfo between same server  connections ?

**Comment by lws-team** [comment]
... by default getaddrinfo() is provided by your libc, if that caches results (it normally should...) then you don't need lws to do anything, calling it within the ttl of its last lookup, will provide you an answer out of its cache.  It is not normally application job to do the DNS result caching.

If you use `LWS_WITH_SYS_ASYNC_DNS` where you are using lws resolver, then that subsystem does provide such a DNS ttl cache for you.

What exactly are you looking at that said -11 and at what point?  -11 on Linux is errno EAGAIN, are you sure you are looking at what you think you are looking at?

**Comment by xCuri0** [comment]
@lws-team i got the error ```lws_client_connect_3_connect: lws_getaddrinfo46 failed -11```. Look at the code thats the return value from ```getaddrinfo```. Using async DNS gives an ```Unable to open socket``` error. Reusing ```getaddrinfo``` could speed up non async DNS but it wouldn't fix this issue as it's caused by running out of file descriptors which is likely also the cause of -11 (E_SYSTEM). So I am closing this issue as increasing ulimit is the only solution
