### ISSUE TITLE
change connection to another

### ISSUE THREAD

**Issue by ahao1995** [warmcat/libwebsockets#2229]
Sorry to bother you
I use `lws_client_connect_via_info `to connet to a webserver, at set intervals I need to change address and path in struct `lws_client_connect_info`,should I need to close origin connection and how to do it?or directly use `lws_client_connect_via_info `with a new `lws_client_connect_info `struct.
thanks.

**Comment by lws-team** [comment]
If you made a tcp connection to somewhere successfully, you cannot decide to connect it somewhere else later.

You can only close it and open a new tcp connection to the new place.

So in lws, you would take the same approach, you can either close a wsi by returning -1 from its protocol callback, or you can use this api to start the close process on a wsi

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n77-101

notice you can't use LWS_TO_KILL_SYNC to kill the wsi you are in the callback for.  Usually  `lws_set_timeout(wsi, 1, LWS_TO_KILL_ASYNC);` is what you want, it will start to close and destroy `wsi` next time around the event loop.

**Comment by ahao1995** [comment]
I have an another question, I want to retry connect forever, I use `lws_retry_sul_schedule_retry_wsithere ` to retry, is there a method to set `lws_retry_bo_t` to do this?
thanks

**Comment by lws-team** [comment]
You can set `.conceal_count` to `LWS_RETRY_CONCEAL_ALWAYS`, he should understand it means "never give up".

**Comment by ahao1995** [comment]
thanks~ it works
