### ISSUE TITLE
building errors on linux "error: unknown type name ‘va_list’"

### ISSUE THREAD

**Issue by marcelrv** [warmcat/libwebsockets#223]
I'm getting errors on compiling on some linux distributions

/usr/local/include/libwebsockets.h:117:71: error: unknown type name ‘va_list’
 LWS_VISIBLE LWS_EXTERN void _lws_logv(int filter, const char *format, va_list vl);

This can be fixed by adding to libwebsockets.h
` #include <stdarg.h>`

**Comment by JoakimSoderberg** [comment]
@warmcat  close this fixed issue
