### ISSUE TITLE
Question about loading client keys and certs using libwebsockets-1.3-chrome37-firefox30

### ISSUE THREAD

**Issue by Std1775** [warmcat/libwebsockets#2230]
Hi:

I am trying to include SSL support for websockets client side based on libwebsockets-1.3-chrome37-firefox30.
It is a very old version and for some reason we haven't upgraded it to a newer one yet.

I am trying to load client keys and certificates onto ssl_client_ctx which belongs to 
libwebsocket_context.

Questions:
1. At first, I tried to create my own ssl context with keys and certs loaded and then use it as provided_ssl_ctx for lws_context_creation_info.
But I couldn't find provided_ssl_ctx within struct lws_context_creation_info the for the version I've been using [here](https://gitlab.com/libwebsockets/libwebsockets/-/blob/v1.3-chrome37-firefox30/lib/libwebsockets.h).
Is that supported in libwebsockets-1.3-chrome37-firefox30?

2. With the current version I have, it looks like only way of providing ssl_client_ctx with keys and certs is to give these 2 directories:
    1. ssl_private_key_filepath 
    2. ssl_cert_filepath
  
    However, we would prefer loading certs via memory to doing it via files, so I also tried the following:
    Since ssl_client_ctx cannot be accessed from outside(it's in private-libwebsockets.h), I tried to get 
    the handle of context->ssl_client_ctx via callback reason: 
    LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS.
    But this callback is meant for client verifying extra certs from server side.
    And at this point, I think lws_context_init_client_ssl is finished.
    Therefore, I don't think ssl_client_ctx can still load client keys & certs by then. 
    Is that correct?

3. If I want to load keys and certs via memory like SSL_CTX_use_certificate and SSL_CTX_use_PrivateKey, how should I proceed in this case? 
Or,
Do we have to upgrade libwebsockets since libwebsockets-1.3-chrome37-firefox30 doesn't seem to support it?

I am kinda new to this area. Any advice is greatly appreciated.
Thank you very much.

**Comment by lws-team** [comment]
That's like 7 years old and is unsupported.  You can read the release policy here.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

More recent versions have in-memory cert and key support, I suggest you upgrade to main.
