### ISSUE TITLE
Libwebsockets 4.1.6 without libevent and external loop

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#2234]
Is there any option to integrate the libwebsocket with an external loop (i am using uloop) without depending of libevent?

I can´t use for example eventfd_write function of libwebsockets.

**Comment by lws-team** [comment]
... lws is agnostic about what loop you can use, it's not tied to libevent.  Currently it can use libuv, libev, libevent, glib and sdevent interchangeably.  Eg in this example

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-foreign

you can build lws with support for all the event loop backends, and select which one to actually use at runtime in the user code.

If "uloop" is the openwrt thing (google is a bit ambiguous), it would mean implement a event lib shim in lws for it... there's a plugin type scheme for them, the one for libevent looks like this

https://libwebsockets.org/git/libwebsockets/tree/lib/event-libs/libevent/libevent.c

**Comment by fusionJose** [comment]
okey thank you very much.

The main issue i have now is that i can´t get LWS_CALLBACK_ADD_POLL_FD if i compile lws with -DLWS_HAVE_EVENTFD=0

because there is a function eventfd_write which is a dependency of libevent library. So the libevent plugin will solve it? without depending of libevent.

**Comment by lws-team** [comment]
No they are not related.  eventfd is a Linux kernel / syscall thing all by itself

https://man7.org/linux/man-pages/man2/eventfd.2.html

The issue seems to be that `eventfd_write()` is a glibc-ism, from the manpage

```
Additional glibc features

The GNU C library defines an additional type, and two functions that attempt to abstract some of the details of reading and writing on an eventfd file descriptor:

    typedef uint64_t eventfd_t;

    int eventfd_read(int fd, eventfd_t *value);
    int eventfd_write(int fd, eventfd_t value);

The functions perform the read and write operations on an eventfd file descriptor, returning 0 if the correct number of bytes was transferred, or -1 otherwise. 
```

If you give `-DLWS_HAVE_EVENTFD=0` to get around that, then you are just saying for event loop cancel purposes, you want to use the traditional pipe2() method instead of an eventfd.  It should be perfectly OK to do that and get the same result.

I really recommend you DON'T use external loop support and `LWS_CALLBACK_ADD_POLL_FD`  if there is literally any other way.  If you want to use it, it's disabled for build by default since a couple of versions, check your lws_config.h and see if `LWS_WITH_EXTERNAL_POLL` was enabled for lws build.

**Comment by fusionJose** [comment]
okey thank you very much. That was the proble, i was compiling without LWS_WITH_EXTERNAL_POLL on.

I don´t have other way in my aplication that using an external loop, uloop.

**Comment by lws-team** [comment]
Makes sense... I will take a look at uloop, tbh I am not sure it is sophisticated enough, it doesn't have timers but has a "timeout" setting, maybe it is enough.  Then the lws_context would be able to join its loop natively and just work on its thread directly, without this gnarly external poll sharing mess.

**Comment by fusionJose** [comment]
okey thanks. Yes, uloop has timeouts, which for practical purposes are the same as timers. When you get the callback of the timeout you can set it again.

**Comment by lws-team** [comment]
I have built an openwrt image and the toolchain, but the docs I can find are silent on how to cross-build a project (ie, lws).  There's a contributed cross-makefile.... how are you using this to produce libs and executables in openwrt build system?

**Comment by fusionJose** [comment]
Actually I am not using openwrt for generating the image and toolchain. I use buildroot. What i do is to add openwrt libraries in buildroot, as libubox. Also libwebsockets, which I cross-compile with an arm-buildroot-linux-uclibcgnueabihf-gcc compiler and then I have my aplication as websocket client integrated in uloop.
So i can validate what you generate. If you need anything more tell me. Thank you very much.

**Comment by lws-team** [comment]
I see, I tried the same approach and I could build libubox on Fedora OK, I will take that way.

**Comment by fusionJose** [comment]
okey perfect, I wish you all the best. When you get something let me know and i will test it if you want. I think i am having some troubles with latest version and the external loop. Thanks.

**Comment by lws-team** [comment]
There's a patch on _temp branch that implements at least basic uloop functionality, it is plumbed in with the minimal-http-server-eventlib-foreign example using `--uloop` argument.

I didn't test it beyond that example, but it can serve files etc.

Due to the nature of uloop, there's no explicit loop because there's just one per process possible.  So it only supports foreign loop mode, but there is no loop to pass in.

**Comment by lws-team** [comment]
(this is pushed on libwebsockets.org git, eg https://libwebsockets.org/git/libwebsockets/log?h=_temp )

**Comment by fusionJose** [comment]
Great. I am going to test it as websocket client. Aligning code from minimal-http-server-eventlib-foreign example.

**Comment by lws-team** [comment]
You probably mainly just need to

 - create the whole lws context part from inside the pre-existing event loop
 
 - set `info.options |= LWS_SERVER_OPTION_ULOOP;` at context creation time

 - just return to the event loop after context creation, don't create any explicit lws service loop any more (it's just a participant in the existing uloop)

the foreign example is right to follow but uloop is much simpler than the other loops.

**Comment by fusionJose** [comment]
I have problems compiling it:

/lib/event-libs/uloop/uloop.c:28:70: error: ‘struct lws_context_per_thread’ has no member named ‘evlib_pt’

I compiled with -DLWS_HAVE_EVENTFD=0

Do I need libevent? I can´t install it because has conflicts with uloop.

**Comment by lws-team** [comment]
No it's nothing to do with "eventfd", the apis related to "event library support" in lws begin "evlib_..."

I had another event lib enabled, so it hid that I forgot a line in the CMakeLists.txt for uloop.  I updated the _temp branch with the fix.

**Comment by fusionJose** [comment]
okey, now we are closed but i have new compilation error:

/libwebsockets/lib/event-libs/uloop/uloop.c: In function ‘elops_io_uloop’:
/libwebsockets/lib/event-libs/uloop/uloop.c:206:64: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  unsigned int ulf = ((flags & LWS_EV_WRITE) ? ULOOP_WRITE : 0) |

**Comment by lws-team** [comment]
_temp branch is updated again...

**Comment by fusionJose** [comment]
okey now compilation worked fine. I can see it generated libwebsockets-evlib_uloop.so

Does it is included libwebsockets.so.17 on it?

**Comment by lws-team** [comment]
No, lws will go look for it at runtime when it sees you created the context with `LWS_SERVER_OPTION_ULOOP` flag.  This is so that a distro can build lws once, but it is able to support any event loop depending on what the user code asks for at runtime.

If you don't care about that and just want to build in uloop support alone into the libwebsockets.so, also use `-DLWS_WITH_EVLIB_PLUGINS=0` at cmake. 

I fixed a typo related to building without plugins, update against _temp branch again first.

**Comment by fusionJose** [comment]
okey i will build with -DLWS_WITH_EVLIB_PLUGINS=0

In mi aplication, I only perform those 3 steps:

- create the whole lws context part from inside the pre-existing event loop

- set info.options |= LWS_SERVER_OPTION_ULOOP; at context creation time

- just return to the event loop after context creation, don't create any explicit lws service loop any more (it's just a participant in 
the existing uloop)

But i don´t know well where i should call lws_client_connect_via_info with lws_client_connect_info

**Comment by lws-team** [comment]
You can also do it after context creation before returning to the loop.

**Comment by fusionJose** [comment]
I just do:

    context = lws_create_context(&info);
    if (!context) {
        lwsl_err("lws init failed\n");
        return 1;
    }

    uloop_init();

    timer_outer_uloop.cb = timer_cb_uloop;
    uloop_timeout_add(&timer_outer_uloop);

    uloop_timeout_set(&timer_outer_uloop, 1090);

    uloop_run();


and on timer_cb_uloop perform lws_client_connect_via_info 

But don´t do anything

**Comment by fusionJose** [comment]
I think i have some troubles in my remote device getting libwebsockets-evlib_uloop.so

Let me try with -DLWS_WITH_EVLIB_PLUGINS=0

**Comment by lws-team** [comment]
No... "create the whole lws context part from inside the pre-existing event loop" means start the loop before creating the lws context.   With event loop (not just uloop, but all of them), you don't return from `uloop_run()` until you kill the loop.

You can use the "outer timer" callback as a one-time way to get back control after the loop starts... create the context in the timer callback.  Reduce the delay to 1ms from 1000 so it comes immediately, and only call it once.  In the timer callback, called "from inside" the uloop, you can create the context and then the client connection.

**Comment by lws-team** [comment]
init uloop -> set up timer -> run uloop -> timer fires -> create context in timer cb -> create client conn -> ... go around uloop ...

**Comment by fusionJose** [comment]
okey perfect.

I run the client on my remote device but i have this error:

[2021/03/16 12:53:48:3807] N:    ./libwebsockets-evlib_uloop.so
[2021/03/16 12:53:48:3818] E: Scandir on '/opt/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/lib' failed, errno 2

This is because that directory is of my pc where i cross-compile lws, but my remote device needs to get libwebsockets-evlib_uloop.so from /usr/lib/ as it does with libwebsockets.so.17

How can i configure this directory on my remote device?

**Comment by fusionJose** [comment]
I mean i need to set runtime path

**Comment by lws-team** [comment]
For now you can start myapp` with `LD_LIBRARY_PATH=/path/to/plugins myapp`

**Comment by fusionJose** [comment]
It keeps with wrong scandir of runtime path

**Comment by lws-team** [comment]
Pretty sure that works because I used it myself during development

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/dir.c#n364

You can also explicitly tell it where to look at context creation time

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n611

something like

```
const char * const mydirs[] = { "/mypath/to/plugins", NULL };

...

info.plugin_dirs = mydirs;
```

**Comment by fusionJose** [comment]
First of all I am compiling libwebsockets with: -DLWS_HAVE_EVENTFD=0 -DLWS_WITH_ULOOP=1 -DLWS_WITH_PLUGINS=1 -DCMAKE_BUILD_TYPE=release

I have configured plugin_dirs at context creation time.

And myapp follow: init uloop -> set up timer -> run uloop -> timer fires -> create context in timer cb -> create client conn -> ... go around uloop ...

I got this log: (If you want i can compile libwebsockets in debug mode)

[2021/03/17 10:00:17:1500] U: LWS minimal ws client PING
[2021/03/17 10:00:18:2410] N: LWS: 4.1.99-v4.2-rc1-20-g21a1fce, loglevel 2047
[2021/03/17 10:00:18:2413] N: NET CLI SRV H1 H2 WS IPv6-absent
[2021/03/17 10:00:18:2741] N:    ./libwebsockets-evlib_uloop.so
[2021/03/17 10:00:18:2754] E: Scandir on '/opt/ingeteam/abw0001/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/lib' failed, errno 2
[2021/03/17 10:00:18:3130] W: lws_plat_dlopen: Failed to get export 'devices' from /usr/lib/libas_devices.so: Unable to resolve symbol
[2021/03/17 10:00:18:3211] W: lws_plat_dlopen: Failed to get export 'devices' from /usr/lib/libas_devices.so.1: Unable to resolve symbol
[2021/03/17 10:00:18:3299] W: lws_plat_dlopen: Failed to get export 'can_socket' from /usr/lib/libcanfestival_can_socket.so: Unable to resolve symbol
[2021/03/17 10:00:18:4658] W: lws_plat_dlopen: Failed to get export 'openssl' from /usr/lib/libgnutls-openssl.so: Unable to resolve symbol
[2021/03/17 10:00:18:5871] W: lws_plat_dlopen: Failed to get export 'openssl' from /usr/lib/libgnutls-openssl.so.27: Unable to resolve symbol
[2021/03/17 10:00:18:7357] W: lws_plat_dlopen: Failed to get export 'openssl' from /usr/lib/libgnutls-openssl.so.27.0.2: Unable to resolve symbol
[2021/03/17 10:00:18:7594] W: lws_plat_dlopen: Failed to get export 'pthread' from /usr/lib/libgpgme-pthread.so: Unable to resolve symbol
[2021/03/17 10:00:18:7985] W: lws_plat_dlopen: Failed to get export 'pthread' from /usr/lib/libgpgme-pthread.so.11: Unable to resolve symbol
[2021/03/17 10:00:18:8274] W: lws_plat_dlopen: Failed to get export 'pthread' from /usr/lib/libgpgme-pthread.so.11.13.0: Unable to resolve symbol
[2021/03/17 10:00:18:8366] W: lws_plat_dlopen: Failed to get export 'script' from /usr/lib/libjson_script.so: Unable to resolve symbol
[2021/03/17 10:00:18:8540] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:8722] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:8816] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:9160] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:9269] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:9431] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:18:9701] W: lws_plat_dlopen: Failed to get export 'genl-3' from /usr/lib/libnl-genl-3.so: Unable to resolve symbol
[2021/03/17 10:00:19:0028] W: lws_plat_dlopen: Failed to get export 'genl-3' from /usr/lib/libnl-genl-3.so.200: Unable to resolve symbol
[2021/03/17 10:00:19:0538] W: lws_plat_dlopen: Failed to get export 'genl-3' from /usr/lib/libnl-genl-3.so.200.20.0: Unable to resolve symbol
[2021/03/17 10:00:19:0943] W: lws_plat_dlopen: Failed to get export 'idiag-3' from /usr/lib/libnl-idiag-3.so: Unable to resolve symbol
[2021/03/17 10:00:19:1254] W: lws_plat_dlopen: Failed to get export 'idiag-3' from /usr/lib/libnl-idiag-3.so.200: Unable to resolve symbol
[2021/03/17 10:00:19:1522] W: lws_plat_dlopen: Failed to get export 'idiag-3' from /usr/lib/libnl-idiag-3.so.200.20.0: Unable to resolve symbol
[2021/03/17 10:00:19:2297] W: lws_plat_dlopen: Failed to get export 'route-3' from /usr/lib/libnl-route-3.so: Unable to resolve symbol
[2021/03/17 10:00:19:2638] W: lws_plat_dlopen: Failed to get export 'route-3' from /usr/lib/libnl-route-3.so.200: Unable to resolve symbol
[2021/03/17 10:00:19:3061] W: lws_plat_dlopen: Failed to get export 'route-3' from /usr/lib/libnl-route-3.so.200.20.0: Unable to resolve symbol
[2021/03/17 10:00:19:3394] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:19:3642] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:19:3895] E: lws_plat_dlopen: Error loading DSO: (null)
[2021/03/17 10:00:19:3954] N:  ++ [wsi|0|pipe] (1)
[2021/03/17 10:00:19:3965] N: elops_accept_uloop: wsi [wsi|0|pipe]
[2021/03/17 10:00:19:3976] N:  ++ [vh|0|netlink] (1)
[2021/03/17 10:00:19:3985] N: elops_accept_uloop: wsi [vh|0|netlink]
[2021/03/17 10:00:19:4471] N:  ++ [vh|1|default||-1] (2)
[2021/03/17 10:00:19:4504] N: timer_cb_uloop: connecting
[2021/03/17 10:00:19:4518] N:  ++ [wsicli|0|WS/h1/192.168.12.126] (1)
[2021/03/17 10:00:19:4533] N: elops_accept_uloop: wsi [wsicli|0|WS/h1/192.168.12.126]
[2021/03/17 10:00:34:4644] E: CLIENT_CONNECTION_ERROR: Unable to connect
[2021/03/17 10:00:34:4648] N:  -- [wsicli|0|WS/h1/192.168.12.126] (0) 15.013s

**Comment by lws-team** [comment]
>  -DLWS_WITH_PLUGINS=1

Unless you want to use lws protocol plugins, you can set  `-DLWS_WITH_PLUGINS=0 -DLWS_WITH_PLUGINS_API=1`

So this looks OK

```
[2021/03/17 10:00:18:2741] N: ./libwebsockets-evlib_uloop.so
[2021/03/17 10:00:18:2754] E: Scandir on '/opt/ingeteam/abw0001/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/lib' failed, errno 2
```

he picked up the plugin for uloop from the cwd, he's configured to look for other things in the bad path, but it's not a problem if nothing there.

```
[2021/03/17 10:00:18:3130] W: lws_plat_dlopen: Failed to get export 'devices' from /usr/lib/libas_devices.so: Unable to resolve symbol
...
```

this looks like noise from checking things to see if they are plugins... it's not killing us.

```
[2021/03/17 10:00:19:4533] N: elops_accept_uloop: wsi [wsicli|0|WS/h1/192.168.12.126]
[2021/03/17 10:00:34:4644] E: CLIENT_CONNECTION_ERROR: Unable to connect
```

It looks pretty reasonable but he times out.  Let me try something similar here with a client connection and uloop.

**Comment by fusionJose** [comment]
okey great, let me know when you have something.

The point is that if i set -DLWS_WITH_PLUGINS=0 then plugin_dirs is not defined.

**Comment by lws-team** [comment]
Well, the main thing is prove uloop support.... it works for server because we can use it with the minimal-http-server-eventlib-foreign --uloop example.  So I will look at that first.

**Comment by fusionJose** [comment]
fully agree.

**Comment by lws-team** [comment]
OK main branch eventlib-foreign example now also performs a http client GET when the context is brought up, and I can see it works correctly now with upoll.  So please try that.

**Comment by fusionJose** [comment]
Yes, now works fine:

[2021/03/17 12:35:15:4459] N: timer_cb_uloop: connecting
[2021/03/17 12:35:15:4486] N:  ++ [wsicli|0|WS/h1/192.168.12.126] (1)
[2021/03/17 12:35:15:4925] U: callback_minimal_pingtest: established 

and sends pings every retry.secs_since_valid_ping

I will be testing this more in my final app.

Thank you very much.

**Comment by fusionJose** [comment]
Are you going to update this stuff on next stable release?

**Comment by lws-team** [comment]
Great... for the noise at context startup, it's lws probing other .so to see if they are plugins... you can move your plugin dir elsewhere so it doesn't find them, and / or just reduce their verbosity, since it should ignore things that are not valid lws plugins

```
diff --git a/lib/plat/unix/unix-plugins.c b/lib/plat/unix/unix-plugins.c
index 43e9d018fd..55271bb59e 100644
--- a/lib/plat/unix/unix-plugins.c
+++ b/lib/plat/unix/unix-plugins.c
@@ -50,7 +50,7 @@ lws_plat_dlopen(struct lws_plugin **pplugin, const char *libpath,
 
        l = dlopen(libpath, RTLD_NOW);
        if (!l) {
-               lwsl_err("%s: Error loading DSO: %s\n", __func__, dlerror());
+               lwsl_info("%s: Error loading DSO: %s\n", __func__, dlerror());
 
                return NULL;
        }
@@ -64,7 +64,7 @@ lws_plat_dlopen(struct lws_plugin **pplugin, const char *libpath,
 
        hdr = (const lws_plugin_header_t *)dlsym(l, sym);
        if (!hdr) {
-               lwsl_warn("%s: Failed to get export '%s' from %s: %s\n",
+               lwsl_info("%s: Failed to get export '%s' from %s: %s\n",
                         __func__, sym, libpath, dlerror());
                goto bail;
        }
```

Yes main will become v4.2 in the next weeks, including this.

**Comment by fusionJose** [comment]
After 10 seconds of getting client connection established.

I have this:

[2021/03/18 12:14:51:0539] I: lws_validity_cb: [wsicli|0|WS/h1/192.168.12.126]: validity too old
[2021/03/18 12:14:51:0546] I: __lws_close_free_wsi: [wsicli|0|WS/h1/192.168.12.126]: caller: validity timeout
[2021/03/18 12:14:51:0551] D: __lws_close_free_wsi: real just_kill_connection A: [wsicli|0|WS/h1/192.168.12.126] (sockfd 14)
[2021/03/18 12:14:51:0556] I: __lws_close_free_wsi: real just_kill_connection: [wsicli|0|WS/h1/192.168.12.126] (sockfd 14)
[2021/03/18 12:14:51:0561] D: lwsi_set_state([wsicli|0|WS/h1/192.168.12.126], 0x10000020)
[2021/03/18 12:14:51:0566] I: __lws_close_free_wsi: [wsicli|0|WS/h1/192.168.12.126]: cce=1

And closes the websocket connection.

**Comment by lws-team** [comment]
You can control how long inactive connections will still be treated as valid

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md

Some of the examples set it to a few secs for testing, you should check what you have

**Comment by fusionJose** [comment]
okey thanks. I was configuring only secs_since_valid_ping.

I set secs_since_valid_hangup = secs_since_valid_ping + 10

**Comment by lws-team** [comment]
Sounds good

**Comment by fusionJose** [comment]
This is more a question about cmake and installation of libraries, but there is a way of setting runtime path at cmake? I have this:

-- Installing: /opt/abw0001/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/lib/libwebsockets-evlib_uloop.so
-- Set runtime path of "/opt/ingeteam/abw0001/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/lib/libwebsockets-evlib_uloop.so" to ""

It is doing something strange when installing libraries in my computer.

**Comment by lws-team** [comment]
I am not sure what "something strange" is... it's related to rpath, or being installed into an elaborated directory that includes the cross-build staging dir, or what?

**Comment by fusionJose** [comment]
I think info.plugin_dirs = mydirs; when configuring at context creation time is not doing anything.

Reading the lws code i only see that it only looks at this struct, searching for directories:
static const char * const dlist[] = {
	".",				/* Priority 1: plugins in cwd */
	LWS_INSTALL_LIBDIR,		/* Priority 2: plugins in install dir */
	NULL
};

**Comment by fusionJose** [comment]
It is calling only to if (!lws_plugins_init(&evlib_plugin_list,
				     dlist, "lws_evlib_plugin",
				     map[n].name, NULL, NULL))
			ok = 1;

at lws_create_context instead of at lws_plat_init

**Comment by lws-team** [comment]
It looks like you're right, the path list only affects protocol plugins.

You're meeting problems because it's cross and your LWS_INSTALL_LIBDIR is the fully elaborated build staging dir one.

Are you using DESTDIR to fill you staging dir, like make DESTDIR=./mystaging install ?

If you're looking in there, can you take a look at what happens with the getenv() here?  It should get the first bite at setting the plugins dir.

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/dir.c?h=main#n364

**Comment by fusionJose** [comment]
I cannot set LD_LIBRARY_PATH with a dir when calling my aplication, because I use an openwrt daemon which manages all the aplications starting and stopping them. 

So ld_env = getenv("LD_LIBRARY_PATH") is empty and enters the other while:

        while (d && *d) {
                lwsl_info("%s: trying %s\n", __func__, *d);
                if (!lws_dir(*d, &pa, lws_plugins_dir_cb))
                        ret = 0;

                d++;
        }


with this two directories:
static const char * const dlist[] = {
".", /* Priority 1: plugins in cwd /
LWS_INSTALL_LIBDIR, / Priority 2: plugins in install dir */
NULL
};

I need to configure that path at runtime in info context information:

lws_plugins_init(&context->plugin_list,
					 info->plugin_dirs,
					 "lws_protocol_plugin", NULL,
					 protocol_plugin_cb, context);

**Comment by fusionJose** [comment]
is it possible? I don´t want to change by hand lws here:
static const char * const dlist[] = {
".", /* Priority 1: plugins in cwd /
LWS_INSTALL_LIBDIR, / Priority 2: plugins in install dir */
NULL
};

**Comment by lws-team** [comment]
Afaik DESTDIR is the way to stage for cross without infecting the runtime paths, see what I wrote earlier. You're ising DESTDIR to install into ypur staging dir?

**Comment by lws-team** [comment]
No.  What does your make install and setting lws cmake install paths commands look like?

**Comment by fusionJose** [comment]
I don´t configure any DESTDIR I thing, I am a bit rookie in cmake.

I use this cmake to crosscompile:
#
# CMake Toolchain file for crosscompiling on ARM.
#
# This can be used when running cmake in the following way:
#  cd build/
#  cmake .. -DCMAKE_TOOLCHAIN_FILE=../cross-arm-linux-gnueabihf.cmake
#

set(CROSS_PATH /opt/ingeteam/abw0001/xenial/host/usr)

# Target operating system name.
set(CMAKE_SYSTEM_NAME Linux)

# Name of C compiler.
set(CMAKE_C_COMPILER "${CROSS_PATH}/bin/arm-buildroot-linux-uclibcgnueabihf-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_PATH}/bin/arm-buildroot-linux-uclibcgnueabihf-g++")

#
# Different build system distros set release optimization level to different
# things according to their local policy, eg, Fedora is -O2 and Ubuntu is -O3
# here.  Actually the build system's local policy is completely unrelated to
# our desire for cross-build release optimization policy for code built to run
# on a completely different target than the build system itself.
#
# Since this goes last on the compiler commandline we have to override it to a
# sane value for cross-build here.  Notice some gcc versions enable broken
# optimizations with -O3.
#
if (CMAKE_BUILD_TYPE MATCHES RELEASE OR CMAKE_BUILD_TYPE MATCHES Release OR CMAKE_BUILD_TYPE MATCHES release)
	set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O2")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2")
endif()

# Where to look for the target environment. (More paths can be added here)
set(CMAKE_FIND_ROOT_PATH "${CROSS_PATH}")

# Adjust the default behavior of the FIND_XXX() commands:
# search programs in the host environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search headers and libraries in the target environment only.
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

I do the make && make install in my PC and 
finally I copy libwebsockets.so and libwebsockets.so.17 to my remote device

**Comment by fusionJose** [comment]
Also now i copy libwebsockets-evlib_uloop.so to the remote device

**Comment by lws-team** [comment]
No the toolchain file is something else.

Cmake has to know where stuff should go in the target, you can override some paths from cmake like `CMAKE_INSTALL_BINDIR`, or `CMAKE_INSTALL_PREFIX`, you should leave these alone.

Instead if you want to install stuff in a staging dir `/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot`, you leave lws cmake thinking about /usr/bin or whatever, and do instead `make DESTDIR=/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot install`  then he will put all the pieces into `/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/...` but the build will not be contaminated with that path like it is now.

So remove any cmake overrides about `/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot`, and use DESTDIR at make install.  The uloop so should be installed in there cleanly as well.

**Comment by fusionJose** [comment]
Okey I understand. So I only have to configure this DESTDIR=/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot to say cmake to install in my computer.

In my target device stuff is going to be in /usr/lib so were I configure that?

Also I need to say to cmake that my c compiler which is in my pc is /xenial/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-gcc

**Comment by lws-team** [comment]
> In my target device stuff is going to be in /usr/lib so were I configure that?

/usr or /usr/local is already the default.  All you have to do is leave it alone.  You can try edit any xenial paths in build/CMakeCache.txt but maybe easier to delete and do a new cmake with just your toolchain file and maybe `-DCMAKE_INSTALL_PREFIX=/usr`

It's ok if the toolchain file knows the path to find the toolchain, and as the root paths for cross include/libs references.  But cmake pieces must otherwise not know you build cross staging path.

**Comment by fusionJose** [comment]
Okey thank you very much. I can see my CMakeCache.txt is too contaminated with /opt/ingeteam/abw0001/xenial/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot path

I will remove and try again only configuring the toolchain path. and the staging dir.
