### ISSUE TITLE
Tell us how to collect it?

### ISSUE THREAD

**Issue by StasToken** [warmcat/libwebsockets#2236]
I want to collect websockets.lib to use it to build another dll file, but I don't understand how to build it? You have so much here that I can't figure it out. can I have a simple instruction under windows ?

**Comment by lws-team** [comment]
```
Notes about building lws
========================

You can download and install lws using the [vcpkg](https://github.com/Microsoft/vcpkg/) dependency manager:
```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
vcpkg install libwebsockets
```
The lws port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg/) on the vcpkg repository.
```

from ./READMEs/README.build.md

**Comment by StasToken** [comment]
Thanks! - at least one good advice for the whole day!
