### ISSUE TITLE
OpenSSL issues on installation.

### ISSUE THREAD

**Issue by chriseyhorn** [warmcat/libwebsockets#2238]
During installation, the log output shows that OpenSSL has been found:

`-- Performing Test LWS_GCC_HAS_TYPE_LIMITS - Success`
`-- Performing Test LWS_GCC_HAS_NO_DEPRECATED_DECLARATIONS`
`-- Performing Test LWS_GCC_HAS_NO_DEPRECATED_DECLARATIONS - Success`
`-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") `
`zlib/miniz include dirs: /usr/include`
`zlib/miniz libraries: /usr/lib64/libz.so`
`-- Looking for eventfd_read`
`-- Looking for eventfd_read - found`
`-- Performing Test LWS_HAVE_PIPE2`
`-- Performing Test LWS_HAVE_PIPE2 - Success`
`-- Performing Test LWS_HAVE_TCP_USER_TIMEOUT`
`-- Performing Test LWS_HAVE_TCP_USER_TIMEOUT - Success`
`Compiling with SSL support`
`**-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") `
`OpenSSL include dir: /usr/include`
`OpenSSL libraries: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so;ssl;crypto**`
`-- Looking for openssl/ecdh.h`
`-- Looking for openssl/ecdh.h - found`
`-- Looking for SSL_CTX_set1_param`
`-- Looking for SSL_CTX_set1_param - found`
`-- Looking for SSL_set_info_callback`

But later on, when it attempts to generate a certificate, I receive the following message.

`-- Looking for TLSv1_2_client_method`
`-- Looking for TLSv1_2_client_method - found`
`Searching for OpenSSL executable and dlls`
`**OpenSSL executable: OPENSSL_EXECUTABLE-NOTFOUND`
` GENCERTS = 0**`
`DIR /root/libwebsockets CMP /root/libwebsockets/cmake`
`-- Configuring incomplete, errors occurred!`

I'm using the following in my dockerfile:

`# Install libwebsockets`
`RUN cd ~ \`
        ` && git clone https://github.com/warmcat/libwebsockets.git \`
        ` && cd libwebsockets \`
        ` && command cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_SUFFIX=64 -DCMAKE_C_FLAGS="-fpic"`
        `&& make \`
       ` && make install \`

**Comment by lws-team** [comment]
So /usr/bin/openssl or so exists in your image, PATH points there?

Check the openssl executable if there with ldd or objdump  and confirm all his dependent libs also exist and can be found in the image

**Comment by chriseyhorn** [comment]
If I run the **find** command here is the output.

`Step 10/11 : RUN find / -name openssl`
` ---> Running in e8e03c03ab0f`
`/usr/lib64/openssl`
`/usr/include/openssl`
`/etc/pki/ca-trust/extracted/openssl`

But when I run **which** command here is the output.

`Step 10/11 : RUN which openssl`
 `---> Running in d5d43ad6e18c`
`which: no openssl in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)`

I'm not familiar enough with these commands to understand why **which** is looking under that path.  OpenSSL was installed with yum on amazon linux 2 using the openssl-devel package.

Thank you for the help!

**Comment by lws-team** [comment]
This is nothing to do with lws, it's about your container with missing openssl executable, I can't help you with your own container.

The three things show in `find` don't look like places you would find the openssl executable, it looks like it is showing you matching directory names.

which is telling you that you don't have the openssl executable.

So you need to fix that before trying to build lws.

**Comment by chriseyhorn** [comment]
Just to close the loop here, once I installed both **openssl** and **openssl-devel** packages it works.

**Comment by lws-team** [comment]
Great.
