### ISSUE TITLE
How to use the lws raw socket protocol in SS?

### ISSUE THREAD

**Issue by hqfrank** [warmcat/libwebsockets#2240]
I am trying to use SS in my project.
The client and server were using tcp socket for communication.
Now I would like to insert SS+lws into my client, so that SS and lws will take care of the communication.
Without changing the existing server, how can I configure the SS policy so that the tcp socket can be used in my client?
I saw the updates in v4.1 saying lws raw socket protocol is supported in SS. Is it the same as tcp socket?
Any example using the lws raw socket protocol that I can refer to?

**Comment by lws-team** [comment]
Sai

https://warmcat.com/git/sai/tree

uses Secure Streams inside for a bunch of things.  It uses "raw" ie, just socket without additional protocol layer, Secure Streams to implement the Sai log proxy client function... the policy part

https://warmcat.com/git/sai/tree/src/device/d-sai.c#n71

and the Secure Stream info, rx / tx / state and helper to create streams from env vars

https://warmcat.com/git/sai/tree/src/common/ss-client-logproxy.c

this streamtype is a client that reaches out to a unix domain socket listener, so the logs from the process can be included in the CI build logs.

**Comment by hqfrank** [comment]
Thanks for pointing me to such useful materials.
Quick question: what is the "+" in "endpoint" value for? https://warmcat.com/git/sai/tree/src/device/d-sai.c#n71

**Comment by lws-team** [comment]
> Quick question: what is the "+" in "endpoint" value for?

It indicates that the address is a Unix Domain Socket in this case.  You can leave it off and give a dns resolveable string or 1.2.3.4 to get an IP connection instead of AF_UNIX.
