### ISSUE TITLE
Libwebsocket - ws-server-pmd-bulk url issue

### ISSUE THREAD

**Issue by CVVDN-S** [warmcat/libwebsockets#2243]
Hi,
Ive got an client which is requesting websocket connection in the form : "ws://localhost:8080/video/test_video.mp4". 
Ive got basic minimal-ws-server-pmd-bulk to read from a video mp4 file and send it to minimal-ws-client-pmd-bulk. 
But how will the url be decoded at the server end which is sent from the 1st client i mentioned. Since im new with this pmd data transfer, I couldn't understand how this connection url from client is understood by minimal-ws-server-pmd-bulk server in C lang.

**Comment by lws-team** [comment]
"pmd" is "per-message deflate", a compression extension option completely unrelated to anything else.  These examples also show how to enable negotiating the compression.

If you are sending video around, it's already compressed, you do not want to use stream compression on it again, it will waste time and memory getting results bigger than the original.

You can keep everything else the same and disable pmd negotiation by removing these lines

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-pmd-bulk/minimal-ws-server-pmd-bulk.c#n120-122

> But how will the url be decoded at the server end which is sent from the 1st client i mentioned. Since im new with this pmd data transfer, I couldn't understand how this connection url from client is understood by minimal-ws-server-pmd-bulk server.

Every ws connection starts as an http connection, that asks to "upgrade" the stream to "ws wire protocol".  So up to the time the ws upgrade is negotiated, ie, up to and including the ws _ESTABLISHED callback, you have access to the http headers using http apis.  To get the requested path part

```
		char mypath[64];

		if (lws_hdr_total_length(wsi, WSI_TOKEN_GET_URI)) {
			if (lws_hdr_copy(wsi, mypath, sizeof(mypath),
					 WSI_TOKEN_GET_URI) < 0)
				return -1;
		}
```
