### ISSUE TITLE
MT-Safe functions getgrgid_r, getgrnam_r, getpwuid_r, getpwnam_r

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#2244]
Hello. Consider changing functions `getgrgid` to `getgrgid_r`, `getgrnam` to `getgrnam_r`, `getpwuid` to `getpwuid_r` and `getpwnam` to `getpwnam_r` for multithread safety.

The current functions access the static memory internally which can cause races in multi-threaded applications.

**Comment by lws-team** [comment]
This is on main now

https://libwebsockets.org/git/libwebsockets/commit?id=1503bc72846c13c34f3afa8cedb594d9cc66da8f
