### ISSUE TITLE
LWS_WITH_RFC6724 option problem

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#2253]
cmake option `LWS_WITH_RFC6724` is not used anywhere in the project, and libwebsockets fails to compile when `LWS_IPV6=ON` and `LWS_WITHOUT_CLIENT=ON`

**Comment by lws-team** [comment]
The RFC6724 stuff is built by default on unix now, the option is cruft.

But starting from a blanks slate and just LWS_WITH_MINIMAL_EXAMPLES and the two you mention, I don't get any build problems.  What are the errors that you are seeing on your platform?

**Comment by pavelxdd** [comment]
No errors with your recent push to main branch.

I got `"RFC6724 requires CLIENT and LWS_IPV6"` before that.

**Comment by lws-team** [comment]
Oh right, it's part of the RFC6724 opton cruft I just cleared out... it's gone then.
