### ISSUE TITLE
 The log level has been changed, but the logs have not changed.

### ISSUE THREAD

**Issue by BurakOzkan** [warmcat/libwebsockets#2257]
I changed the log level as in the message below to find out the reason for the Accept missing error error for my debug operations.

however, the LWS log is completely gone.
I changed this:
   lws_set_log_level(2047  ,NULL);
to
lws_set_log_level(65535, lwsl_emit_syslog);

The pcap was a good idea, but the connection is ssl encrypted, so I can't tell anything useful from it.

The error is telling you that no Accept HTTP header came back in the response.

Crank up the logging on the lws side:
- cmake .. -DCMAKE_BUILD_TYPE=DEBUG
- if your app still has the switches from the test app template, do -d65535 otherwise in the code something likie lws_set_log_level(65535, lwsl_emit_syslog);

That will dump every character of the headers, get a run where it says Accept is missing and paste / upload the log here.

_Originally posted by @lws-team in https://github.com/warmcat/libwebsockets/issues/659#issuecomment-259305010_

**Comment by lws-team** [comment]
... if you want to emut to syslog, tell it to emit to syslog.

If you don't want to emit to syslog, set the second parameter to NULL, ie, don't change the emit function.
