### ISSUE TITLE
error on reading from skt ( last update of git )

### ISSUE THREAD

**Issue by mickae1** [warmcat/libwebsockets#226]
Hi,

my client send two request at the same time to my server. 

My server answer the first one correctly, but it failed to answer the second one :

This is my log :

.....
reason 12 LWS_CALLBACK_HTTP_BODY
23:06:37:350 =>create cookie !
23:06:37:352 =>call LWS_CALLBACK_HTTP_WRITEABLE
reason 15 LWS_CALLBACK_HTTP_WRITEABLE
23:06:37:353 =>loop LWS_CALLBACK_HTTP_WRITEABLE
23:06:37:356 =>write 4078
23:06:37:358 =>loop LWS_CALLBACK_HTTP_WRITEABLE
23:06:37:358 =>flush bail
reason 17 LWS_CALLBACK_FILTER_HTTP_CONNECTION
reason 11 LWS_CALLBACK_HTTP
reason 12 LWS_CALLBACK_HTTP_BODY
LWS_CALLBACK_HTTP_BODY: request=list&page=1&... len 36
23:06:37:374 =>create cookie !
23:06:37:375 =>call LWS_CALLBACK_HTTP_WRITEABLE
23:06:37:375 =>log 2 error on reading from skt

At the lines : 
call LWS_CALLBACK_HTTP_WRITEABLE

I'm doing the same thing as the test-server.c example : 
libwebsocket_callback_on_writable(this, wsi);
break;

At the line : 
23:06:37:358 =>flush bail

I'm doing the same thing as the test-server.c example : 

flush_bail:
			printfTools("flush bail\n");
			/* true if still partial pending */
			if (lws_partial_buffered(wsi)) {
				libwebsocket_callback_on_writable(this, wsi);
				break;
			}
			closeWeb(*pIndex);
			goto try_to_reuse;

**Comment by mickae1** [comment]
Ok, I've tried to put more log on this problem : 

23:35:58:024 =>call LWS_CALLBACK_HTTP_WRITEABLE
23:35:58:025 =>log 16 libwebsocket_read: read_ok
23:35:58:025 =>log 8 lws_server_skt_srv: read 0 len
23:35:58:026 =>log 16 closing http file
reason 5 LWS_CALLBACK_CLOSED_HTTP


My question is why do i get a LWS_CALLBACK_CLOSED_HTTP ?

This is what I do in the LWS_CALLBACK_HTTP_BODY : 

		p = buffer + LWS_SEND_BUFFER_PRE_PADDING;
		end = p + sizeof(buffer) - LWS_SEND_BUFFER_PRE_PADDING;
		// send header :
		if (lws_add_http_header_status(this, wsi, 200, &p, end))
			return 1;
		if (lws_add_http_header_by_token(this, wsi,
				WSI_TOKEN_HTTP_SERVER,
				(unsigned char *)"libwebsockets",
				13, &p, end))
			return 1;
		if (lws_add_http_header_by_token(this, wsi,
				WSI_TOKEN_HTTP_CONTENT_TYPE,
				(unsigned char *)"application/json",
				10, &p, end))
			return 1;
		if (lws_add_http_header_content_length(this, wsi,
				strlen(pAcReply), &p, end))
			return 1;
		{
			SDKToolsPrintfWithDate("write cookie !\n");
			n = sprintf(acCookieParam, "key=%s;Path=/;Max-Age=%d", (CHAR*)((apsDeviceContext[*pIndex]->bSession)?apsDeviceContext[*pIndex]->acKey:"0"), (INT)((apsDeviceContext[*pIndex]->bSession)?_WEB_COOKIE_LIFE:0));
			/*
			 * struct libwebsocket *wsi,
			    const unsigned char *name,
			    const unsigned char *value,
			    int length,
			    unsigned char **p,
			    unsigned char *end);
			 */
			if (lws_add_http_header_by_name(this, wsi,
					(unsigned char *)"set-cookie:",
					(unsigned char *)acCookieParam, n, &p, end))
				return 1;
		}

		if (lws_finalize_http_header(this, wsi, &p, end))
			return 1;
		n = libwebsocket_write(wsi,
				buffer + LWS_SEND_BUFFER_PRE_PADDING,
				p - (buffer + LWS_SEND_BUFFER_PRE_PADDING),
				LWS_WRITE_HTTP_HEADERS);

		/*
		 * book us a LWS_CALLBACK_HTTP_WRITEABLE callback
		 */
		SDKToolsPrintfWithDate("call LWS_CALLBACK_HTTP_WRITEABLE\n");
		libwebsocket_callback_on_writable(this, wsi);
		break;

**Comment by mickae1** [comment]
An another log, the second request worked, but not the first one : 

reason 17 LWS_CALLBACK_FILTER_HTTP_CONNECTION
reason 11 LWS_CALLBACK_HTTP
reason 12 LWS_CALLBACK_HTTP_BODY
23:52:24:613 =>write cookie !
23:52:24:615 =>call LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:616 =>log 16 libwebsocket_read: read_ok
23:52:24:617 =>log 8 lws_server_skt_srv: read 0 len
23:52:24:618 =>log 16 closing http file
reason 5 LWS_CALLBACK_CLOSED_HTTP
23:52:24:620 =>log 16 close: just_kill_connection
23:52:24:620 =>log 8 remove_wsi_socket_from_fds: wsi=0x2e6c8, sock=38, fds pos=3
23:52:24:621 =>log 16 calling back CLOSED_HTTP
reason 5 LWS_CALLBACK_CLOSED_HTTP
reason 29 LWS_CALLBACK_WSI_DESTROY
reason 15 LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:624 =>log 8 libwebsocket_ensure_user_space: 0x2fb30 protocol 0xb61468c8
23:52:24:626 =>log 8 HTTP POST request for '/request/Model.js'
reason 17 LWS_CALLBACK_FILTER_HTTP_CONNECTION
reason 11 LWS_CALLBACK_HTTP
reason 12 LWS_CALLBACK_HTTP_BODY
LWS_CALLBACK_HTTP_BODY: request=list&page=1&... len 36
23:52:24:639 =>write cookie !
23:52:24:640 =>call LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:642 =>log 16 libwebsocket_read: read_ok
reason 15 LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:644 =>loop LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:646 =>write 4078
23:52:24:646 =>loop LWS_CALLBACK_HTTP_WRITEABLE
23:52:24:647 =>flush bail
23:52:24:648 =>log 8 lws_http_transaction_completed: await new transaction
23:52:24:655 =>log 2 error on reading from skt

**Comment by mickae1** [comment]
Ok, I find out where the problem come from, it's here : 

			if (lws_partial_buffered(wsi)) {
				SDKToolsPrintfWithDate("partial pending\n");
				libwebsocket_callback_on_writable(this, wsi);
				break;
			}
			closeWeb(*pIndex);
			goto try_to_reuse;

I fixed it with goto bail ! ( it works because i don't want the connection to be keep alive )

**Comment by jhgoebbert** [comment]
and the length of "application/json" is 16 and not 10
```
            (unsigned char *)"application/json",
            10, &p, end))
```
