### ISSUE TITLE
Callback before connection

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#2260]
Hello, I suggest adding a callback function before connection

https://github.com/warmcat/libwebsockets/blob/8d14125b88ea6966d7820698d81771f0dd5648a5/lib/core-net/client/connect3.c#L446

https://developer.android.com/reference/android/net/VpnService#protect(int)

**Comment by lws-team** [comment]
OK... I pushed a patch on main for it, currently

https://libwebsockets.org/git/libwebsockets/commit?id=010c8c86b0105214f86512c756cf6fff66e8799e
