### ISSUE TITLE
Inconsistent handling of "%00" in URI

### ISSUE THREAD

**Issue by syldrathecat** [warmcat/libwebsockets#2262]
While doing some probing for basic security I noticed that specifying "%00" inside of a path has inconsistent behavior.

Using `minimal-http-server.c` as a test case:

- Requesting `http://localhost:7681/` returns the file `/index.html`.
- Requesting `http://localhost:7681/xxx%00` causes the connection to be closed.
- Requesting `http://localhost:7681/%00` returns the file `/index.html` .
- Requesting `http://localhost:7681/subdir/%00` returns the file `/subdir/index.html`.
- Requesting `http://localhost:7681/%00/xxx.jpg` returns the file `/index.html`.
- Requesting `http://localhost:7681/?foo=%00` causes the connection to be closed.

The instances where the connection is closed is caused by the check at [parser.c:817](https://github.com/warmcat/libwebsockets/blob/3092dbe0f9d3f3f1241cd79506ce75c501854306/lib/roles/http/parsers.c#L817) triggering. Stack trace:

```
#  function                     file           line
1  lws_parse_urldecode          parsers.c      818  
2  lws_parse                    parsers.c      1062 
3  lws_handshake_server         server.c       2037 
4  lws_read_h1                  ops-h1.c       78   
5  lws_h1_server_socket_service ops-h1.c       444  
6  rops_handle_POLLIN_h1        ops-h1.c       635  
7  lws_service_fd_tsi           service.c      735  
8  _lws_plat_service_forced_tsi unix-service.c 51   
9  _lws_plat_service_tsi        unix-service.c 216  
10 lws_plat_service             unix-service.c 235  
11 lws_service                  service.c      805  
```

The fact the behavior is inconsistent makes it seem unintentional, and that maybe parser is making a bad assumption.

I believe this could be a potential security issue in a situation where external URL filtering may block access to `http://localhost:7681/secret/` but allow access to `http://localhost:7681/secret/%00.jpg`. The inability to specify "%00" in a query string may also be a limitation if someone was encoding binary data in to a URI.

I'm not sure what the behavior should be. If the interfaces in libwebsockets are using null-terminated strings, consistently returning a 400 error might be the right thing to do. This is what nginx does for path components, but not query strings, I believe.

**Comment by lws-team** [comment]
Thanks for taking a look at it... I think we have to be rightfully cautious about %00 tricks, but...

> I believe this could be a potential security issue in a situation where external URL filtering may block access to http://localhost:7681/secret/ but allow access to http://localhost:7681/secret/%00.jpg

... your examples don't seem to provide a reason to "believe" that?  If you mean this...

```
Requesting http://localhost:7681/subdir/%00 returns the file /subdir/index.html.
```

... that does not succeed to obfuscate the `http://localhost:7681/subdir/` part that any external rule would match on.  So unless I miss your meaning, that's a bit of a reach on this data.

It's more scary if `../` tricks did something.  But there is a lot of effort in the parser to exterminate these.

> The fact the behavior is inconsistent makes it seem unintentional, and that maybe parser is making a bad assumption.
> The inability to specify "%00" in a query string may also be a limitation if someone was encoding binary data in to a URI.

Well, urlargs are handled as header data, the apis for those are all length-based not NUL-termination based.  If a NUL ends up in urlarg data, it can be handled properly.  The intention of the line in lws_parse_urldecode() is to stop %00 tricks, it may also stop %00 getting into urlargs (I will try it later) but that is a restriction, not a security issue.

Protecting itself by closing the connection if things look unacceptable is OK from a security perspective.  They way lws is constructed, it can be used as a web file server but it is also designed that user code can figure out what response it wants to send depending on what came, it is not a single-purpose thing like nginx.  If it's desirable to issue a 400 hardcoded is a reasonable idea, but it's a separate issue not really about security.

**Comment by syldrathecat** [comment]
Ah, I didn't include it as an example, but `/secret/%00.jpg` -- that is, a null byte at the *start* of a path component, with other characters trailing, doesn't cause the connection to reset and just truncates the URL leaving "/secret/".

In regards to potential security issues, we are assuming there is a second public-facing proxy doing the URL filtering (which is probably a questionable idea in the first place). Any filtering done in the libwebsockets application would presumably always see the truncated URL.

I was thinking about a situation where for some reason you would want to limit access to `/uploads/` itself, while explicitly whitelisting specifically `/uploads/*.jpg`. Its probably not likely to happen in practice, but URLs that say one thing and map to another unexpectedly can be bad.

One practical situation I could see is if you were explicitly trying to avoid serving `/uploads/index.html`, for example because the filenames are potentially attacker-writeable, and an attacker-hosted HTML file can be used for cookie stealing and other evil things. Being able to access `/uploads/` unexpectedly with a default filename of `index.html` set would allow an attacker-uploaded HTML file to be accessed as `/uploads/%00.jpg` in this case.

Another situation could be that the proxying webserver is doing API rate limiting, and the attacker uses silently discarded suffixes to mask the actual endpoint being hit.

Whether or not %00 should be acceptable in a URL in the first place, and behave as if it were truncated at that point though is probably something to consider separately from the issue of the server having surprising behavior (connection reset with no error response) in surprising situations (only when in certain places in the URL).

I was under the impression that the server was returning 403 in response to invalid requests, but it seems that is only true some of the time, so this almost isn't surprising if not for the fact that these are valid HTTP requests.

**Comment by lws-team** [comment]
I am not sure how how an attacker can get something useful out of the truncation as it stands.

> I was thinking about a situation where for some reason you would want to limit access to /uploads/ itself, while explicitly whitelisting specifically /uploads/*.jpg

Right, but that's not how people arrange these ACL type urls, /secret/* is forbidden with no pinholes.

> Being able to access /uploads/ unexpectedly with a default filename of index.html set would allow an attacker-uploaded HTML file to be accessed as /uploads/%00.jpg in this case.

The practical implementation for that in lws terms is a Basic Auth mount at /uploads.  /uploads/%00 is going to match on that mount and be subject to requiring the basic auth.  In the case the user code checks the path, he's going to also trigger whatever logic he has when he sees /uploads/ never mind the NUL.  That's why I think this class of issue is more worrying if ../ is able to be abused.

AFAICS once it's at lws level, getting /mountpoint/<default file> from /mountpoint/%00 isn't buying you anything different than just giving it /mountpoint/index.html or /mountpoint/.

> Another situation could be that the proxying webserver is doing API rate limiting, and the attacker uses silently discarded suffixes to mask the actual endpoint being hit.

Well, okay.

> URLs that say one thing and map to another unexpectedly can be bad.

Yes, it requires an effort to have some humility about what is possible.  While at the same time not becoming paralyzed.

>  the server having surprising behavior (connection reset with no error response) in surprising situations (only when %00 appears in certain places in the URL).

I do see that point of view.  But hanging up is pretty good medicine if the code concludes it's seeing something it doesn't want to deal with further.  It's OK if that's its policy to protect itself and the user.

While I'm not against cleaning this up a bit, the danger is without careful thinking through, normalizing the response to these things gives more opportunity for external bad things to get into more code.

**Comment by lws-team** [comment]
I spent some time looking at this today and added a patch.

https://libwebsockets.org/git/libwebsockets/commit/include/libwebsockets?id=5672f2a00c80b55f1cbf793f92599b429d336b48

I normalized the behaviour and added a README that lays out what the policy is supposed to be about it.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.http_parser.md?h=main

Basically %00 is now banned in the path part, or the urlarg name part, it will hang up if it sees them there.
However binary urlarg values (like, ?name=value) that are percent-encoded are supported and %00 is valid there.  Maybe later we can migrate the hangup to try to send a 400 or something, but I think it's not making any security issue as it is.

There will be plenty of user code that treats the path as a NUL-terminated string, there's no real advantage to allowing %00 in paths and plenty of scope for trouble.

In addition although the header fragment apis are length based, there's a `lws_get_urlarg_by_name()` api that returns a pointer to the value part without its valid length, ie, it can only be consumed as a NUL-terminated string.  I added a variant `lws_get_urlarg_by_name_safe()`, which returns the length and soft-deprecated the original api.  I converted the in-tree users to the new one and added notes in the docs.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-http.h?h=main#n497-521

Is this addressing your concerns or it feels there's more that should be done for safety?

**Comment by syldrathecat** [comment]
This looks like the change I was expecting. I agree that it makes little sense to accept null bytes in a path for the obvious reasons (the library already using null-terminated strings, existing practice in other servers, the danger of unexpected truncation when combined with filesystem APIs, and having very little practical use).

I think a HTTP error is a very good idea, given that you are rejecting what is a well-formed HTTP request, and can be made validly within the context of the Web. For example, someone embedding `<img src="http://lws-server/%00">` on another page causing a browser/proxy to behave inappropriately (re-trying multiple connection attempts for example), or causing a user's existing keep-alive or HTTP/2 session to be terminated. It would also allow the malicious request to be logged by the apache-style logging feature, if you wanted to keep tabs on that sort of thing.

I am happy to see the decision to accept `%00` inside of the query string, and the extra support to be able to make use of them. It would be annoying if GET requests were more restrictive than POST, and an application is going to have to deal with the possibility of null bytes in a lot of other places anyway. Its definitely a lot more likely that someone is going to try stuffing arbitrary binary data through a query parameter, than as a path component.

The only safety issue I was concerned about was the cases where the connection was *not* being closed, in the context of serving files from the filesystem. If every path with a null byte in it is rejected then there's no longer a chance of accessing paths in unexpected ways using a null byte in the middle of a path name.

Thanks!

**Comment by lws-team** [comment]
OK it sounds like as far as we can tell, there's no obvious issue after this.

>  or causing a user's existing keep-alive or HTTP/2 session to be terminated.

AFAIK that'd only kill the stream, not the outer, shared h2 network connection.  The headers belong to the stream and its context doesn't extend beyond that.

> given that you are rejecting what is a well-formed HTTP request, 

...all we know by then is it started with a verb like GET or POST, we don't know at the time we're parsing that path that the rest of it is well-formed http, we're still on the first line at that point and didn't even see the HTTP/1.1 or whatever.  If it's an h2 stream, we do definitely know it's supposed to be http at least.

I think the 400 is probably the way to go but it's a separate job I think.

Thanks again for your comments.
