### ISSUE TITLE
Hard to navigate documentation

### ISSUE THREAD

**Issue by fluffynukeit** [warmcat/libwebsockets#2263]
Hi. in #544 there was the documentation move to doxygen.  I'm finding the doxygen html very difficult to navigate.  For instance, here: https://libwebsockets.org/lws-api-doc-v4.1-stable/html/index.html

From this home page, how do I just get a list of the source files?  I can navigate to the [libwebsockets.h](https://libwebsockets.org/lws-api-doc-v4.1-stable/html/libwebsockets_8h.html) header easily by clicking the link on the homepage.  This is a nice categorization of functions, typedefs, etc.  I want to see that for every file in the codebase.

Another example is under the ["browse by api category" link](https://libwebsockets.org/lws-api-doc-master/html/modules.html) on the home page.  From that link, I can click on "JSON Parser" because I want to see what structs and functions are available for JSON parsing.  But instead, it goes to a [1-sentence page](https://libwebsockets.org/lws-api-doc-master/html/group__lejp.html) about LEJP, which sounds great, but provides no API information or links to the page generated by the [lejp.c source](https://libwebsockets.org/git/libwebsockets/tree/lib/misc/lejp.c?h=v4.1-stable).  I cannot figure out how to get to the HTML page generated from the lejp.c source file!  Multiple other links from that modules page have the same issue.

So I hope I'm just missing something obvious because there has clearly been a lot of effort to write proper doxygen comments in the source code, of which lejp.c is just one example, but I cannot for the life of me figure out how to get access to the rendered HTML for each of the source files.  I've been able to stumble on a few through the links I can find but unable to find many others.  I don't really care about categorizing each source file into a "module".  The source directory tree already provides better categorization.  

Thanks for your time and making this library available.  I'm hoping to learn it and start using it soon, which is why I'm trying to figure out these docs so earnestly.

**Comment by lws-team** [comment]
If you want a sectional overview, looking in the headers dir is pretty good

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets

The headers themselves contain the doxygen sources so they are also easy to read and informational.

Doxygen itself had kind of died upstream last time I looked, no way to do search consistent with CSP.

**Comment by lws-team** [comment]
Some other resources... for getting started the best way is look through the minimal examples and cut and paste them

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples

There are about 90 in there now.

There's a lot of READMEs on various topics

https://libwebsockets.org/git/libwebsockets/tree/READMEs

and some blog articles here on interesting apis

https://warmcat.com/

**Comment by fluffynukeit** [comment]
So is it true that there is no doxygen HTML navigation that is analogous to the git explorer?  I agree that the header files and examples git sources are helpful, and that's what I've been using in lieu of a similar offering on the doxygen page, but a doxygen HTML tree for the source with hyperlinks, object categorization, source code hidden, etc. is indeed more convenient and easier to navigate than the git source code navigation page.

I don't understand your comment about doxygen dying upstream.  Presumably doxygen is generating HTML documents for all the source and header files.  If so, my recommendation would be for those to be linked directly from the doxygen index.html homepage so they can be found easily.  They would offer value over simply examining the source code and headers directly.

**Comment by lws-team** [comment]
Everything doxygen produces is rsync'd to the web server.

The .dox file is provided in-tree at the top level dir, you can run it yourself to get local html, if it can produce something better, let me know how or provide a patch.

'Last time I looked' at Doxygen was an issue a couple of years ago asking for search, lws serving uses strict CSP for years, doxygen at that time produces inline js all over the place and proposed installing PHP (which I won't do) to run the search.  The linux kernel moved to Sphinx, I was left with the impression Doxygen was moribund.  But looking at their repo today, it's lively.

**Comment by fluffynukeit** [comment]
When I run doxygen locally on the libwebsockets.dox file using 1.8.17, I see a sidebar navigation and a top-bar with a 'File List" drop down, among other things, which is what I was requesting and what I expect to see on a doxygen output based on other doxygen experiences of mine.  However, both of these are missing when I open the doxygen docs hosted on libwebsockets.org (v 1.9.1).

Looking at the HTML, the content is the nearly identical.  So not a likely problem there.

Looking at the dev console, the libwebsockets version has several inline items blocked due to CSP.  So I think the issue here has just been the CSP that was blocking the functionality I was expecting to see. 

The functionality can be partially restored by making the following additions to READMEs/mainpage.md that will provide a hyperlink to the previously hidden doxygen pages.  I tested it on the libwebsocket urls and it works, at least on my browser.

```
Browse by <a href="modules.html">API category (module)</a>

Browse by <a href="files.html">file listing</a>

Browse by <a href="annotated.html">data structures</a>
```

**Comment by lws-team** [comment]
Yes CSP also blocks its search...  CSP isn't some cutting edge thing any more, it's a very strong "last line of defence" for your users if you're serving potentially attacker-controlled content that finds a way to get around your html escaping to inject scripts on them... with a strict CSP they may get delivered but the client just blocks them from executing as violating the CSP.

I did look a couple of years ago at fixing Doxygen to work with CSP, but got repelled by its problems, that's why I was left with the idea it is "dead"...

https://github.com/warmcat/libwebsockets/issues/1680

I'm afraid it's stuck like that until Doxygen modernizes and separates their content and scripts / style.
