### ISSUE TITLE
No comments. No examples.

### ISSUE THREAD

**Issue by gitcnd** [warmcat/libwebsockets#2264]
Thanks for building this awesome library for us.
It should only take a few more minutes to tell us how to use it, add comments to explain what it's doing, and implement some tests... - then it's ready to release.  (I'm specifically looking at the fix.py stuff, but the same problem is probably throughout.)

**Comment by lws-team** [comment]
... you meant to post this on some other poor guy's project?  There's about 90 examples, doxygen comments and no python in lws.
