### ISSUE TITLE
lws_http_cookie_get() extra character \0

### ISSUE THREAD

**Issue by Piero01** [warmcat/libwebsockets#2267]
Hello, I updated lws from version 4.1.99-v4.10-292-g0455c66e to latest version yesterday (4.1.99-v4.2-rc1-73-g5672f2a0).

With the new version, when getting cookie with **lws_http_cookie_get()**, in one particular case I get an extra character ('\0') at the end of the cookie (and len is 1 too much).
It is with Chrome and Edge, when receiving the WebSocket upgrade request (in callback LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION).
With firefox everything is ok and with "normal" http requests it seems ok whatever the browser.

Of course I can add a check in my code but I don't know if it is the best solution maybe there is some issue in libwebsockets because it was working before.

**Comment by lws-team** [comment]
Does the problem still exist if you trim back one patch, ie, `git reset --hard eeed0c07`?

There was a patch yesterday that could impact it, or other work some months ago that touched cookie parsing... both are inside your two tests.  If it's still broken if you trim off the last patch from yesterday, we know that is not related.

**Comment by Piero01** [comment]
Yeah no problem with the previous version, it seems it is related to the patch of yesterday.

**Comment by lws-team** [comment]
Thanks for testing it... this should be fixed on current main, please give it a try.

**Comment by Piero01** [comment]
Perfect, thank you very much.
