### ISSUE TITLE
HTTP redirect causes assertion failed in lws_mutex_refcount_assert_held() 

### ISSUE THREAD

**Issue by youmych** [warmcat/libwebsockets#2268]
Hello, I'd modified your minimal-ws-client to run the lws service in a separate thread/threads. I started other threads the same way as in minimal-http-server-smp.c.

When I connect to my own websocket server with redirection, I have an assertion
```
libwebsockets/lib/core/libwebsockets.c:1284: lws_mutex_refcount_assert_held: Assertion `mr->lock_owner == pthread_self() && mr->lock_depth' failed.
```

When no redirect then the example works correctly.

I made a demo: https://github.com/youmych/lws-test/releases/tag/this-fails-on-assert

**Comment by lws-team** [comment]
Thanks, I could reproduce it with the modified example with `-s 127.0.0.1 -p 8888 -n` and

```
$ echo -n -e "HTTP/1.1 301 Moved\r\nlocation: https://libwebsockets.org\r\n\r\n" | nc -l 8888
```

I pushed a patch that adds the missing locking for LWS_MAX_SMP > 1 case that will solve it.

**Comment by youmych** [comment]
Great thank! It works.

**Comment by lws-team** [comment]
Great.
