### ISSUE TITLE
[cmake] libwebsockets and FetchContent_Declare

### ISSUE THREAD

**Issue by ksergey** [warmcat/libwebsockets#2272]
Hello

Could you please fix cmake scripts to make possible to use libwebsockets via `FetchContent_Declare`?

Currently it's not possible without additional code because target `websockets`  (and `websockets_shared`) in CMakeLists.txt do not export include directories.

My workaround looks like:
```cmake
FetchContent_Declare(libwebsockets URL https://github.com/warmcat/libwebsockets/archive/refs/tags/v4.1.6.tar.gz)
FetchContent_MakeAvailable(libwebsockets)
add_library(websockets-fixed INTERFACE)
target_include_directories(websockets-fixed
  INTERFACE
    ${libwebsockets_SOURCE_DIR}/include
    ${libwebsockets_BINARY_DIR}/include)
target_link_libraries(websockets-fixed INTERFACE websockets)
...
target_link_libraries(app PRIVATE websockets-fixed)
```

After fix it should looks like:
```cmake
FetchContent_Declare(libwebsockets URL https://github.com/warmcat/libwebsockets/archive/refs/tags/v4.1.6.tar.gz)
FetchContent_MakeAvailable(libwebsockets)
...
target_link_libraries(app PRIVATE websockets)
```

To fix this need to add to `lib/CMakeLists.txt` something like:
```cmake
target_include_directories(websockets PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../include)
target_include_directories(websockets PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/..) # not sure about this where actually placed generated headers
```

Thanks

**Comment by lws-team** [comment]
I never heard of that cmake feature before, I'm not against helping it work.  But

> target_include_directories(websockets PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../include)

this is telling it to include things from `./lib/../include` or `./../include`?  Also

> ${CMAKE_CURRENT_BINARY_DIR}/..

IIUI this is not safe because the builder decides where to put the binary dir, it could have any relationship to the sources, the volume mountpoint or whatever.

**Comment by ksergey** [comment]
> this is telling it to include things from ./lib/../include or ./../include?

`./lib/../include`

> IIUI this is not safe because the builder decides where to put the binary dir, it could have any relationship to the sources, the volume mountpoint or whatever.

It's fine, `${CMAKE_CURRENT_BINARY_DIR}` in case of `lib` is the path where lib built. I'm not sure but you need to point `websockets` target where `lws_config.h` placed via `target_include_directories`.

Good reads about modern cmake:
http://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/
https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html

**Comment by lws-team** [comment]
>  Good reads about modern cmake:

If all I had to do was look after cmake, I would chase the latest and greatest stuff.  But everything about cmake is just a side-effect of something else I have to do.  18 months ago I spent a lot of time splitting out a monolithic top level CMakeLists.txt into what we have today, making sure that produced the same results on a variety of platforms exhausted my appetite for cmake orthodoxy.  So I am just glad if it is more maintainable and doing its cross-platform thing.

Your proposal above creates this

```
CMake Error in lib/CMakeLists.txt:
  Target "websockets" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/projects/libwebsockets/lib/../include"

  which is prefixed in the source directory.


CMake Error in lib/CMakeLists.txt:
  Target "websockets" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the build directory.


CMake Error in lib/CMakeLists.txt:
  Target "websockets" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the build directory.Target "websockets"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the source directory.


CMake Error in lib/CMakeLists.txt:
  Target "websockets_shared" INTERFACE_INCLUDE_DIRECTORIES property contains
  path:

    "/projects/libwebsockets/lib/../include"

  which is prefixed in the source directory.


CMake Error in lib/CMakeLists.txt:
  Target "websockets_shared" INTERFACE_INCLUDE_DIRECTORIES property contains
  path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the build directory.


CMake Error in lib/CMakeLists.txt:
  Target "websockets_shared" INTERFACE_INCLUDE_DIRECTORIES property contains
  path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the build directory.Target "websockets_shared"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/projects/libwebsockets/build/lib/.."

  which is prefixed in the source directory.
```

Can you try to produce a tested patch?

**Comment by ksergey** [comment]
> Can you try to produce a tested patch?

I will try today-tomorrow make a patch

**Comment by ksergey** [comment]
Done

Tested with cmake's `FetchContent` and `add_subdirectory(libwebsockets)`
Standalone compilation also works without issues

**Comment by lws-team** [comment]
It's pushed on main thanks.
