### ISSUE TITLE
release 4.2.0 fails to build on Mageia Cauldron

### ISSUE THREAD

**Issue by david-geiger** [warmcat/libwebsockets#2278]
Hi,

I tried to compile latest 4.2.0 release on Mageia Cauldron but it fails to build with:

> /home/iurt/rpmbuild/BUILD/libwebsockets-4.2.0/lib/plat/unix/unix-plugins.c: In function 'lws_plat_dlopen':
/home/iurt/rpmbuild/BUILD/libwebsockets-4.2.0/lib/plat/unix/unix-plugins.c:79:34: error: 'LWS_BUILD_HASH' undeclared (first use in this function)
   79 |  if (strcmp(hdr->lws_build_hash, LWS_BUILD_HASH))
      |                                  ^~~~~~~~~~~~~~
/home/iurt/rpmbuild/BUILD/libwebsockets-4.2.0/lib/plat/unix/unix-plugins.c:79:34: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [lib/CMakeFiles/websockets_shared.dir/build.make:191: lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-plugins.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....

Attached full compile log:
[build.x86_64.0.20210418080609.log](https://github.com/warmcat/libwebsockets/files/6330758/build.x86_64.0.20210418080609.log)

**Comment by lws-team** [comment]
OK... I will install Mageia Cauldron in a vm and try something similar.

**Comment by lws-team** [comment]
Building it with defaults (`cmake .. && make -j6`) works fine.

And pasting your cmake (adapt . to .. as recommended)...

```
/usr/bin/cmake -Wno-dev -S .. -B build -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/libexec -DCMAKE_INSTALL_RUNSTATEDIR:PATH=/run -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-DNDEBUG -DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed  -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags' -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DLWS_WITH_HTTP2=ON -DLWS_IPV6=ON -DLWS_WITH_ZIP_FOPS=ON -DLWS_WITH_SOCKS5=ON -DLWS_WITH_RANGES=ON -DLWS_WITH_ACME=ON -DLWS_WITH_LIBEV=ON -DLWS_WITH_LIBUV=ON -DLWS_WITH_LIBEVENT=OFF -DLWS_WITH_FTS=ON -DLWS_WITH_THREADPOOL=OFF -DLWS_UNIX_SOCK=ON -DLWS_WITH_HTTP_PROXY=ON -DLWS_WITH_DISKCACHE=ON -DLWS_WITH_LWSAC=ON -DLWS_LINK_TESTAPPS_DYNAMIC=ON -DLWS_WITHOUT_BUILTIN_GETIFADDRS=ON -DLWS_WITH_BUNDLED_ZLIB_DEFAULT=OFF -DLWS_WITHOUT_BUILTIN_SHA1=ON -DLWS_WITH_STATIC=OFF -DLWS_WITHOUT_CLIENT=OFF -DLWS_WITHOUT_SERVER=OFF -DLWS_WITHOUT_TESTAPPS=OFF -DLWS_WITHOUT_TEST_SERVER=OFF -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=OFF -DLWS_WITHOUT_TEST_PING=OFF -DLWS_WITHOUT_TEST_CLIENT=OFF -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_WITH_SQLITE3=ON -DDISABLE_WERROR=ON -DLIBEV_INCLUDE_DIRS=/usr/include/libev
```

also builds fine here.  Same if I try it in the source dir with --build build at cmake.

Can you explain to me how to try the rpmbuild flow?

**Comment by lws-team** [comment]
Oh... from your log

```
-- Found Git: /usr/bin/git (found version "2.31.1") 
fatal: not a git repository (or any of the parent directories): .git
Git commit hash: 
```

does this help?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2a887e586c..5612aff212 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -366,6 +366,10 @@ if(GIT_EXECUTABLE)
                set(LWS_BUILD_HASH ${GIT_USER}@${GIT_HOST}-${GIT_HASH})
        endif()
 
+       if ("${LWS_BUILD_HASH}" STREQUAL "")
+               set(LWS_BUILD_HASH "unknown")
+       endif()
+
        message("Git commit hash: ${LWS_BUILD_HASH}")
 endif()
 
```

**Comment by david-geiger** [comment]
Yeah this patch help and also with adding Buildrequires git.

Here is our Mageia structure packages for libwebsockets:

http://svnweb.mageia.org/packages/cauldron/libwebsockets/current/

And here our web Build System:

http://pkgsubmit.mageia.org/

**Comment by lws-team** [comment]
I pushed the patch on main and on v4.2-stable.
