### ISSUE TITLE
What does "HS: disallowed at ESTABLISHED" mean?

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#2280]
I'm trying to use the client APIs to connect to `https://www.google.com/recaptcha/api/siteverify` and I'm getting this error at `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`. What does that mean and how can I fix it?

**Comment by lws-team** [comment]
The protocol it bound to returned nonzero from `LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP`, indicating it wanted to stop the connection.

**Comment by nidoro** [comment]
Ah, that's right. Thanks Andy!
