### ISSUE TITLE
Availability of lws_sul_cancel in 4.0.1?

### ISSUE THREAD

**Issue by chinhodado** [warmcat/libwebsockets#2284]
I am trying to compile some code using libwebsockets. It compiles fine using the checked out master branch of libwebsockets, however on another machine where I only have the installed version of the library (libwebsockets-devel-4.0.1-2.el8.x86_64.rpm), the compilation fails with this error:

```
websocket.c: In function ‘callback_websocket’:
websocket.c:174:9: error: implicit declaration of function ‘lws_sul_cancel’; did you mean ‘lws_seq_name’? [-Werror=implicit-function-declaration]
         lws_sul_cancel(&vhd->sul);
         ^~~~~~~~~~~~~~
         lws_seq_name
websocket.c:174:9: error: nested extern declaration of ‘lws_sul_cancel’ [-Werror=nested-externs]
```

Here is the code, which was copied from one of the examples:

```
    case LWS_CALLBACK_PROTOCOL_DESTROY:
        vhd->finished = 1;

        if (vhd->ring)
        {
            lws_ring_destroy(vhd->ring);
        }

        lws_sul_cancel(&vhd->sul);
        pthread_mutex_destroy(&vhd->lock_ring);
        break;
```

My question is, is `lws_sul_cancel` not available on version 4.0.1? If so what can I use to replace it?

Alternatively is there a newer version of the package somewhere that is ready to use?

**Comment by lws-team** [comment]
You can cancel suls in 4.0 by calling lws_sul_schedule() again on it with the last arg as `LWS_SET_TIMER_USEC_CANCEL`.

v4.2 is out in the last days.  And it has many bugfixes and improvements compared to v4.0.  But I am not involved in the rh / centos packaging for lws.

**Comment by chinhodado** [comment]
Works great, thank you!
