### ISSUE TITLE
libwebsocket_context_destroy doesn't issue LWS_CALLBACK_CLOSED on Win32

### ISSUE THREAD

**Issue by andyque** [warmcat/libwebsockets#229]
It always return LWS_CALLBACK_GET_THREAD_ID and LWS_CALLBACK_LOCK_POLL.

Does anyone know how to solve this problem.

The version of libwebsockets is the latest release.

**Comment by andyque** [comment]
It's not a issue.

**Comment by danimihalca** [comment]
Hi. Can you explain with this is not an issue? I have the same problem you had. Same server code, after a client performs a session destroy, the server callback catches LWS_CALLBACK_CLOSED  on Linux, but on Windows with msvc2013 this doesn't happen.
