### ISSUE TITLE
Cannot bind to IPv4 address if IPv6 is enabled

### ISSUE THREAD

**Issue by notimaginative** [warmcat/libwebsockets#2290]
Attempting to specify an IPv4 bind address when a vhost has IPv6 enabled causes it to bind to all interfaces instead of a specific one.

Using libwebsockets-test-server version 4.0.20 and `ss -tpln` to confirm:

Bind to IPv4 address (does not work):
`libwebsockets-test-server -i 127.0.0.1` => `LISTEN    0         4096                     *:7681                   *:*`

Bind to IPv6 address (works):
`libwebsockets-test-server -i ::1` => `LISTEN    0         4096                 [::1]:7681                [::]:*`

Bind to IPv6-formatted IPv4 address (also works)
`libwebsockets-test-server -i ::ffff:127.0.0.1` => `LISTEN    0         4096                     [::ffff:127.0.0.1]:7681                   *:*`

However if the `LWS_SERVER_OPTION_DISABLE_IPV6` option is set then it works as expected and will bind to the specific IPv4 address.

**Comment by lws-team** [comment]
I pushed a patch on main which should help

https://libwebsockets.org/git/libwebsockets/commit?id=1822c503dcf9677d5f23885e391c072746cf1169

please give it a try.

**Comment by notimaginative** [comment]
That worked properly for all of my test cases where an address is specified, both IPv4 and IPv6.

However, I noticed a new issue where you *must* specify a valid iface if libwebsockets if built with IPv6 support. Using `NULL` will fail to bind to anything. If libwebsockets is built without IPv6 support the `NULL` does still work as expected.

**Comment by lws-team** [comment]
Thanks, yes I just noticed the wreckage in CI :-/  I'll update the patch shortly when I find what I did.

**Comment by lws-team** [comment]
This should be better

https://libwebsockets.org/git/libwebsockets/commit?id=57d715560446bc1fb9278621c1ffa867ebc000de

**Comment by notimaginative** [comment]
Excellent! Everything appears to be working as expected for me now.

**Comment by lws-team** [comment]
Great.
