### ISSUE TITLE
[Win32] Missing data exports

### ISSUE THREAD

**Issue by gvanem** [warmcat/libwebsockets#2292]
Trying to build some examples using a dynamic WebSocket lib seems almost
impossible due to missing symbols like `humanize_schema_si`.

Applying this patch:
```diff
--- a/include/libwebsockets/lws-misc.h 2021-05-09 17:49:47
+++ b/include/libwebsockets/lws-misc.h 2021-05-10 11:24:15
@@ -859,9 +859,9 @@
        uint64_t factor;
 } lws_humanize_unit_t;

-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_si[7];
-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_si_bytes[7];
-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_us[8];
+LWS_EXTERN const lws_humanize_unit_t humanize_schema_si[7];
+LWS_EXTERN const lws_humanize_unit_t humanize_schema_si_bytes[7];
+LWS_EXTERN const lws_humanize_unit_t humanize_schema_us[8];
```

all the `minimal-examples` program links fine.

But there are linking problems of `Websocket.dll` in some combinations involving OpenSSL. 
So I'm not sure what is a good fix an all-dynamic programs.

**Comment by lws-team** [comment]
> due to missing symbols like humanize_schema_si.

These are perfectly available on gcc / llvm, it seems msvc needs a different incantation to make data symbols visible?

> But there are linking problems of Websocket.dll in some combinations involving OpenSSL.

You are using cmake, right?  "linking problems" is not very useful to understand what you're talking about, but you must use the cmake tests to figure out what exports your openssl has available at build-time.

**Comment by gvanem** [comment]
> it seems msvc needs a different incantation to make data symbols visible?

Yes, that's old news. The relevant piece of the preprocessed output of `api-tests/api-test-lws_tokenize/main.c` is:
```c
extern const lws_humanize_unit_t humanize_schema_si[7];
```

whereas it needs to be:
```c
__declspec(dllimport) extern const lws_humanize_unit_t humanize_schema_si[7];
```
to use a dynamic Websocket. 

But the ifdef-soup in `libwebsocket.h` regarding import/exports does not make it easy to understand what's wrong
with export of data.

**Comment by lws-team** [comment]
Refactoring patch is welcome, if you are going to take care of all the platforms that lws works on :-)

**Comment by gvanem** [comment]
I found no Cmake option under `minimal-examples` that allows linking/using a `Websocket.dll`. I assume one simply
has to add a `-DLWS_DLL` (and have no `-DLWS_BUILDING_SHARED`).

Since the problems I had was with `humanize_schema_si` only, I simply patched like so:
```diff
--- a/include/libwebsockets/lws-misc.h 2021-05-09 17:49:47
+++ b/include/libwebsockets/lws-misc.h 2021-05-10 13:32:55
@@ -859,9 +859,15 @@
        uint64_t factor;
 } lws_humanize_unit_t;

-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_si[7];
-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_si_bytes[7];
-LWS_VISIBLE extern const lws_humanize_unit_t humanize_schema_us[8];
+#if defined(_WIN32) && defined(LWS_DLL)
+  extern __declspec(dllimport) const lws_humanize_unit_t humanize_schema_si[7];
+  extern __declspec(dllimport) const lws_humanize_unit_t humanize_schema_si_bytes[7];
+  extern __declspec(dllimport) const lws_humanize_unit_t humanize_schema_us[8];
+#else
+  LWS_VISIBLE const lws_humanize_unit_t humanize_schema_si[7];
+  LWS_VISIBLE const lws_humanize_unit_t humanize_schema_si_bytes[7];
+  LWS_VISIBLE const lws_humanize_unit_t humanize_schema_us[8];
+#endif
```

This works for MinGW too. (you do not support Borland).

So to work that backwards into something nicer, a section in `libwebsocket.h` could be:
```c
/* Building or using Websocket dynamically. _WIN32 implied
 */
#if defined(LWS_DLL)  
  #if defined(LWS_BUILDING)
   #define LWS_EXTERN         extern __declspec(dllexport)
  #else
    #define LWS_EXTERN        extern __declspec(dllimport)
  #endif
#endif

/* Building or using Websocket statically or on non-Windows.
 */
#ifndef LWS_EXTERN
#define LWS_EXTERN         extern
#endif
```
I'm simply ignoring the `LWS_INTERNAL` here. Why is that important?

**Comment by lws-team** [comment]
Closing this due to age.
