### ISSUE TITLE
Incorrect client connection binding in the multitreading mode (with LWS_MAX_SMP > 1)

### ISSUE THREAD

**Issue by millikk** [warmcat/libwebsockets#2295]
Hello everybody. Recently I've had a crash of my program which represents a modified client of the [ws-client/minimal-ws-client/minimal-ws-client.c](https://github.com/warmcat/libwebsockets/blob/main/minimal-examples/ws-client/minimal-ws-client/minimal-ws-client.c) The main difference is that it uses multithreading mode like this:
```c++
// ... the context is already inited for using NUM_OF_THREADS threads
lws_sul_schedule(context, 0, &mco.sul, connect_client, 1);
pthread_t pthread_service[NUM_OF_THREADS];
int n = 0;
for (n = 0; n < lws_get_count_threads(context); n++) {
    if (pthread_create(&pthread_service[n], NULL, thread_service, (void *)(lws_intptr_t)n))
        lwsl_err("Failed to start service thread\n");
}
// ...
```

After my investigation I noticed that there is a strange (and I think incorrect) logic of the connection binding in the function [ lws_client_connect_via_info() (connect.c:117)](https://github.com/warmcat/libwebsockets/blob/main/lib/core-net/client/connect.c#L117) file:
```c++
// function lws_client_connect_via_info()
for (n = 0; n < i->context->count_threads; n++)
    if (i->context->pt[n].service_tid == tid) {
        lwsl_info("%s: client binds to caller tsi %d\n", __func__, n);
        tsi = n;
        break;
    }
```

Here we try to find the service thread to bind to and the `tid` variable has zero value. All the service threads try to initialize their `service_tid` field in the [_lws_plat_service_tsi() (unix-service.c:114)](https://github.com/warmcat/libwebsockets/blob/main/lib/plat/unix/unix-service.c#L114) (here I chose the unix platform case for example). So the above code will bind the connection to the arbitrary thread which haven't initialized its own `service_tid` field yet - so we rely on race condition :((  
Moreover the above code won't choose the current thread because, by then, the current thread will have already set its `service_tid` to non zero value. So, this code, that running from, say, `thread 0` (with `tsi == 0`, so its context is `context->pt[0]`), will bind connection (i.e. `wsi`) to the , say, `thread 1` (`tsi == 1`, `context->pt[1]`) and then will continue the connection. And if the connection fails very fast (f.e. the target peer is a local host with closed port) there will be an error like `CLIENT_CONNECTION_ERROR: closed before established` and here we may have a race condition: the `thread 0` is still working with `wsi`, but the `thread 1` has already noticed connection error and it performs deletion of the `wsi` - and this is exactly my case of program crash.

### (POSSIBLE) SOLUTION
I think it would be better to bind connection to the current thread, so we need to init `tid` according to the [_lws_plat_service_tsi() (unix-service.c:114)](https://github.com/warmcat/libwebsockets/blob/main/lib/plat/unix/unix-service.c#L114):

```c++
if (!i->context->vhost_list) {
    lwsl_err("%s: bind error: no vhost\n", __func__);
    return NULL;
}

struct lws fake_wsi;
memset(&fake_wsi, 0, sizeof(fake_wsi));
fake_wsi.a->context = i->context;
tsi = -1;
tid = i->context->vhost_list->protocols[0].callback(
					fake_wsi,
					LWS_CALLBACK_GET_THREAD_ID,
					NULL, NULL, 0);
for (n = 0; n < i->context->count_threads; n++) {
    if (i->context->pt[n].service_tid_detected && i->context->pt[n].service_tid == tid) {
        lwsl_info("%s: client binds to caller tsi %d\n", __func__, n);
        tsi = n;
        break;
    }
}

if (tsi < 0) {
    lwsl_err("%s: bind error: no appropriate thread\n", __func__);
    return NULL;
}

```

BTW: I also noticed the strange code in [lws_client_connect_via_info() (connect.c:241)](https://github.com/warmcat/libwebsockets/blob/main/lib/core-net/client/connect.c#L241) because `tid` is set in a right way but it is not used further

**Comment by lws-team** [comment]
>  So the above code will bind the connection to the arbitrary thread which haven't initialized its own service_tid field yet - so we rely on race condition :((

Well, that it up to user code as to if there has been any service on the service threads before you start trying to create client connections... like the client connection creation call, the creation of the service threads is also something done by user code, so it has to be sequenced in user code.

Unless I miss the point I don't think the code is 'strange', it wants to figure out the tsi the client connection creation api is being called from so it can try to bind it there, it wants service threads to be able to open client connections on their own tid automatically.  I understand without the sequencing, the client connection can come before the service threads have been around the event loop and see uninitialized pt `service_tid` which matches tsi 0 on all threads.  But if you take care about it, it should be OK IIUI.

> the thread 0 is still working with wsi, but the thread 1 has already noticed connection error and it performs deletion of the wsi - and this is exactly my case of program crash.

Again unless I miss the point, this is just a downstream consequence of the user code not sequencing the client connection creation until after all the service threads have gone around the event loop at least once.

One way to do that would be set some bytes when each thread has started and wait in the initial thread to see the bytes all set, then proceed with starting client connections.

Also, it looks like you might be working with older lws code, a while back the fakewsi stuff was optimized into its own initial substruct, so you don't have to have to prepare whole wsis.

**Comment by lws-team** [comment]
On main / v4.2-stable, he has this

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n241-242

does it help with your scenario?

**Comment by millikk** [comment]
I also use the main branch. And, please, look at the usage of the `tid` variable: 

1. on [line 92](https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n92) it is initialized by 0
2. on [line 120](https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n120) the zeroed `tid` is compared with `service_tid` in order to find matching (so here we allways choose the thread with tsi == 0)
3. on [line 241](https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n241) it set to the thread_id but is never used after - so it's strange useless line

**Comment by millikk** [comment]
It looks nice and more logical here! But usage of the `pthread` is only applicable for unix-like systems, isn't it?
Small remark: the `n` variable in not needed here. 
I'm very happy that we could understand each other :)

**Comment by lws-team** [comment]
> But usage of the pthread is only applicable for unix-like systems, isn't it?

pthreads for Windows exists as described here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

... that works well since it's used in lws CI to build things on Windows as well as *nix.  Otherwise we support freertos, I don't think we are going to see LWS_MAX_SMP > 1 on freertos.  So it covers everything it needs to.

> the n variable in not needed here.

No it is still used further down; it was already there just moved, not added.

I pushed the patch on main, hopefully that solves it.
