### ISSUE TITLE
Crashes when call lws_callback_on_writable() function

### ISSUE THREAD

**Issue by Hermancg** [warmcat/libwebsockets#2296]
Hello，
     My server program crashes when call lws_callback_on_writable() function occasionally. It's caused by the assertion in _lws_change_pollfd() function. Could you please give me some clues to locate the error? My libwebsockets version is 4.2.

**Comment by lws-team** [comment]
Usually this kind of thing is caused by people using threads with a non-threadsafe event loop.  None of the lws apis are threadsafe except lws_cancel_service().
