### ISSUE TITLE
Javascript css resources are not loaded well

### ISSUE THREAD

**Issue by jongsun89** [warmcat/libwebsockets#2309]
@lws-team Hello. Great thanks to provide lws.
I have met the issue using lws 3.2.0.
I'm trying to use lws on embeded device.
It works well, but the issue sometimes happens that page is not loaded well in client browser.
As i tested, it happens most times in edge browser and when client first accesses the html page after server(lws) is on.
Of course , it works if refreshing the page is done. But clients have to do the refreshing.

Console error on the browser is like the below

Uncaught SyntaxError: unexpected token '<' in js file

Js file is good but , it looks the page could not load the resources like js css files at the time.
Can you help how to solve it

**Comment by lws-team** [comment]
I would update to most recent stable, ie, v4.2-stable and see if still any problem.  If so, we can discuss how to reproduce.

**Comment by lws-team** [comment]
If still problems after update, we can continue this issue.
