### ISSUE TITLE
LWS support TCP Fastopen ?

### ISSUE THREAD

**Issue by vsbc2010** [warmcat/libwebsockets#2310]
LWS will support TCP Fastopen?

Linux/MacOS/Win10 support TCP fastopen option now. 

Can get low delay with TCP fastopen feature.

**Comment by lws-team** [comment]
Fastopen is from 2011, before TLS 1.3 and h2, it is not as simple as "Can get low delay with TCP fastopen feature".  This guy notes

https://squeeze.isobar.com/2019/04/11/the-sad-story-of-tcp-fast-open/

it's disabled in the major browsers today, I can't even find it in about:config in ffox or chrome://flags any more.

In 2011 pages had to be fetched with multiple h1 connections so tcp connection time was critical.  Nowadays lws supports tls 1.3 and h2, that multiple connection problem is solved by muxing on the one tcp connection and tls 1.3 + tls session cache improves those parts.  You should look at these areas first (even though they do not contain the word "fast" in the name...).

I pushed a patch on main

https://libwebsockets.org/git/libwebsockets/commit?id=ad3aa5339ef27d0071606b539b61605debe09bbf

allowing enabling it per-vhost for serving, it requires more work than makes sense to me for client support, particularly in any real system the first guy to send anything is the tls layer.  But if you want to cooperate about it and provide patches, we can discuss.
