### ISSUE TITLE
max byte receive size?

### ISSUE THREAD

**Issue by kboniadi** [warmcat/libwebsockets#2318]
Hi,

I was wondering if there is a max amount of bytes you can received at once? I'm running into a problem where when I send anything above 4088 bytes, the message is broken up into separate chunks. So...

message size: 4090
chunk 1: 4088
chunk 2: 2

message size: 5000
chunk 1: 4088
chunk 2: 912

message size: 10000
chunk 1: 4088
chunk 2: 4096
chunk 3: 1816

**Comment by lws-team** [comment]
lws does not try to reassemble an atomic message, it passes what arrives through to the user code as it gets it.

In ws, messages may be literally endless.  If you want atomic messages you need to assemble them, you can use these tests to understand what the current chunk represents in the current message

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h

The size of the max rx buffer and how much can be filled is controlled by a few things

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n650-655
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-protocols-plugins.h#n57-65

Tls sends things  in atomic 'records' of up to 16K.  Up to the record size, decided by the sender, data will all appear at once.  Past that, tls will no longer conceal the chunky, bursty reality and appear in <=16KB lumps plus or minus read coalescing.
