### ISSUE TITLE
LWS_CALLBACK_CLIENT_RECEIVE - how to know message is text or binary?

### ISSUE THREAD

**Issue by chinhodado** [warmcat/libwebsockets#2319]
Hi, in a ws client callback, when the event is `LWS_CALLBACK_CLIENT_RECEIVE `, is there a way to know if the message received is text or binary?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h#n82-92

**Comment by chinhodado** [comment]
Thank you!
