### ISSUE TITLE
How to tell if I won't be called back again for a given struct lws

### ISSUE THREAD

**Issue by marcelo-gonzalez** [warmcat/libwebsockets#2321]
Hi, dont know how to label it as such but this is more of a question than an issue I guess.

Is there a good way to tell from inside a callback (the one that gets passed an enum lws_callback_reasons) if this will be that last callback? What I do is basically this:

```
struct my_struct *s = make_my_struct();
struct lws_client_connect_info info = {
...
.userdata = s,
...
};
lws_client_connect_via_info(&info)
```

then in my callback:

```
case LWS_CALLBACK_CLOSED_CLIENT_HTTP:
  free_my_struct(user);
  break;
case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
  do_something_on_error(user, in, len);
  break;
```

The issue is that sometimes LWS_CALLBACK_CLOSED_CLIENT_HTTP is called before LWS_CALLBACK_CLIENT_CONNECTION_ERROR, and sometimes it's the other way around, so it's hard to know where I should call free_my_struct();

To get the two different orders, one way could be gotten by calling lws_context_destroy() right after connecting to get a "closed before established" error, and for the other direction maybe send an HTTP PUT to some server with Content-Length > 0 and don't send any body and get a "read failed"

**Comment by lws-team** [comment]
Is this happening with current lws or some other version?

> The issue is that sometimes LWS_CALLBACK_CLOSED_CLIENT_HTTP is called before LWS_CALLBACK_CLIENT_CONNECTION_ERROR

That shouldn't be the case, you should get one or the other, once. 

> To get the two different orders, one way could be gotten by calling lws_context_destroy() right after connecting to get a "closed before established" error,

What does "connecting" mean here... tcp connection?  tls connection?

> end an HTTP PUT to some server with Content-Length > 0 and don't send any body and get a "read failed"

This is basically "have the server hang up on us", that can happen at any time.

**Comment by marcelo-gonzalez** [comment]
ahh wait sorry, I goofed here! The order isn't swapped, I was just doing something dumb in my code :)
