### ISSUE TITLE
lws_create_context() != 0 with LWS_SERVER_OPTION_GLIB and missing libwebsockets-evlib_glib.so

### ISSUE THREAD

**Issue by lucianoiam** [warmcat/libwebsockets#2322]
Let's say a program does this:

```C
struct lws_context_creation_info info;
memset (&info, 0, sizeof (info));
/* ... configure protocol, etc ... */
void *foreign_loops[1];
foreign_loops[0] = my_glip_loop;
info.foreign_loops = foreign_loops;
info.options = LWS_SERVER_OPTION_GLIB;
struct context *lws_context = lws_create_context (&info);
```

And the system where the program is running on lacks `libwebsockets-evlib_glib.so`

Shouldn't it be possible to catch the situation during runtime in order to fallback to a different event loop integration implementation?

Following the steps above apparently results in `context != 0` for the aforementioned scenario unless I am doing something wrong.

Background:

There are situations where the user libwebsockets cannot be assumed to be compiled with certain features enabled. One solution is rolling a custom integration based on LWS_WITH_EXTERNAL_POLL . That works nicely but is deprecated and again not guaranteed to be possible for users' installed .so builds. But in contrast to the (supposed) inability for checking LWS_SERVER_OPTION_GLIB, presence of LWS_WITH_EXTERNAL_POLL can be indirectly detected during runtime by monitoring the *_POLL_FD callbacks. Another solution is to use a thread, it works but it is not as nice as libwebsockets' built-in Glib integration. A custom solution without threads and without LWS_WITH_EXTERNAL_POLL is not possible because the fds are hidden by opaque types as far as I understand from reading the libwebsockets source.

**Comment by lws-team** [comment]
> Shouldn't it be possible to catch the situation during runtime in order to fallback to a different event loop integration implementation?

If you're using a specific foreign loop, that loop uses your event lib native apis and kind of makes your loop choice for you already.

There is an `LWS_WITH_DISTRO_RECOMMENDED` option in cmake that turns all the things on, but not everybody is using it.  The plugins approach allows them to be packaged separately, and make your application bring what it wants in as a dependency.

> LWS_WITH_EXTERNAL_POLL

I really don't recommend that.  There's a better option now on main, which lets you present an existing custom application loop as an event library fairly simply

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-custom/minimal-http-server.c?h=main

That is part of the core library stuff you can bank on existing.

> Following the steps above apparently results in context != 0 for the aforementioned scenario unless I am doing something wrong.

I guess it's defaulting to the internal poll loop if nothing found.

**Comment by lws-team** [comment]
... thinking about it you can probably cut and paste the glib event lib into your code, and pass it in using the context info struct mechanism the custom event lib stuff uses

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-custom/minimal-http-server.c?h=main#n323

that should be able to ensure you can use native glib loop whether the lib was built with the plugin or not.

**Comment by lucianoiam** [comment]
I was not aware of this method; it looks very good and will try it. Thanks.

**Comment by lucianoiam** [comment]
All this makes sense too

> > Shouldn't it be possible to catch the situation during runtime in order to fallback to a different event loop integration implementation?
> 
> If you're using a specific foreign loop, that loop uses your event lib native apis and kind of makes your loop choice for you already.
> 
> There is an `LWS_WITH_DISTRO_RECOMMENDED` option in cmake that turns all the things on, but not everybody is using it. The plugins approach allows them to be packaged separately, and make your application bring what it wants in as a dependency.
> 
> > LWS_WITH_EXTERNAL_POLL
> 
> I really don't recommend that. There's a better option now on main, which lets you present an existing custom application loop as an event library fairly simply
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-eventlib-custom/minimal-http-server.c?h=main
> 
> That is part of the core library stuff you can bank on existing.
> 
> > Following the steps above apparently results in context != 0 for the aforementioned scenario unless I am doing something wrong.
> 
> I guess it's defaulting to the internal poll loop if nothing found.
