### ISSUE TITLE
In FreeRTOS LWS_CALLBACK_HTTP_BODY is only called twice, then gets stuck in lwip_select

### ISSUE THREAD

**Issue by robhap** [warmcat/libwebsockets#2325]
I use libwebsockets as a HTTP server in an embedded project with FreeRTOS. When I send a PUT request with 3 kB of binary data to the server, all data is processed in two calls of LWS_CALLBACK_HTTP_BODY. If the binary data is > 4 kB, LWS_CALLBACK_HTTP_BODY is not called more than twice and not all data is processed. Libwebsockets gets stuck when calling the `lwip_select` function in the `_lws_plat_service_tsi` routine in freertos-service.c (line 141):
`n = select(max_fd + 1, &readfds, &writefds, &errfds, ptv);`
It will wait for new input from LwIP and the rest of the data will not be processed.

For debugging, I set `timeout_secs = 1000` in my context info.

Debugging showed that after the second call to LWS_CALLBACK_HTTP_BODY, there is a jump to `again` at line 104 in freertos-service.c. After that Libwebsockets gets stuck in `lwip_select`.

I found a solution for the problem: Moving the `again` label form line 104 in front of line 102:
```
again:

    /*
     * is there anybody with pending stuff that needs service forcing?
     */
    if (lws_service_adjust_timeout(context, 1, tsi)) {
```

Is this an adequate solution or is there a better one?

**Comment by lws-team** [comment]
What impact does that have on how long you're able to spend in the idle wait in select()?  It's still in select() the bulk of the time, or spinning?

**Comment by robhap** [comment]
By moving the label `lws_service_adjust_timeout()` decides if service() is called for the again loop too:

original:
```
    /*
     * is there anybody with pending stuff that needs service forcing?
     */
    if (lws_service_adjust_timeout(context, 1, tsi)) {
again:
...
    n = select(max_fd + 1, &readfds, &writefds, &errfds, ptv);
...
    } else
        a = 1;
...
    if (a)
        goto again;
```

modified:
```
again:
    /*
     * is there anybody with pending stuff that needs service forcing?
     */
    if (lws_service_adjust_timeout(context, 1, tsi)) {
...
    n = select(max_fd + 1, &readfds, &writefds, &errfds, ptv);
...
    } else
        a = 1;
...
    if (a)
        goto again;
```

In my test, `lws_service_adjust_timeout(context, 1, tsi)` is 0 only if there is data left from the body after the first and all subsequent calls of LWS_CALLBACK_HTTP_BODY. When the entire body is processed, select() is called as before. After the entire request is processed, it remains in select() until a new request is issued.

**Comment by lws-team** [comment]
OK, it sounds like it makes sense to me.  I have pushed the change on main and I'll update v4.2-stable later.  main is in the middle of some work at the moment.

**Comment by robhap** [comment]
Thanks for the quick reply and applying the change.
