### ISSUE TITLE
How to close server's listen socket.

### ISSUE THREAD

**Issue by SeonahMoon** [warmcat/libwebsockets#2327]
Hi.

I'm using a vhost with LWS_SERVER_OPTION_EXPLICIT_VHOSTS option.

I found that server's listen socket isn't closed even if vhost is destroyed because default wsi is remained in vhost.
Could you inform me how to close server's listen socket?

Following is the step which I tried to close the listen socket.

**1. Creates a vhost**
    lws_create_vhost();   // _lws_vhost_bind_wsi: vh default: wsi listen/vine-websocket-protocol, count_bound_wsi 1_
   
**2. Connects with a client** 
 _// lws_vhost_bind_wsi: vh vine-websocket-server: wsi none/none, count_bound_wsi 2_

**3. Destroys vhost**
  lws_vhost_destroy() _// lws_vhost_destroy: count_bound_wsi 2_

**4. Calls writable callback to disconnect with a client and then returns -1 in the callback**
 _// lws_close_free_wsi_final: wsi 0x7fd480001360: fd 9_
 _// lws_vhost_unbind_wsi: vh vine-websocket-server: count_bound_wsi 1_

**5. I expected that socket is closed but still remained.**
_netstat -l |grep 12345
tcp6       0      0 [::]:12345              [::]:*                  LISTEN_

**Comment by lws-team** [comment]
> I found that server's listen socket isn't closed even if vhost is destroyed because default wsi is remained in vhost.

I think I understand what you're relating above, but there is code to detach the listen wsi separately as part of the `lws_vhost_destroy()` flow

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/vhost.c?h=main#n1243-1303

wsi cannot just close synchronously, it has to be done around the event loop.  So shortly after starting the vhost destroy flow, it should close the wsi and then notice that the vhost has no active wsi any more and enter the second part of the vhost destroy.  What's actually happening with that in your case?

**Comment by SeonahMoon** [comment]
I used v4.0-stable. I found that the destroy logic was different from the link you shared.
It works after upgrading v4.2-stable.
Thanks for your help.

**Comment by lws-team** [comment]
Great.

**Comment by jiridanek** [comment]
Possibly relevant, for issue with lws_vhost_destroy() in v4.0 that is fixed in 4.2. https://libwebsockets.org/pipermail/libwebsockets/2021-January/008848.html
