### ISSUE TITLE
We encounted a crash which is crashed in lws

### ISSUE THREAD

**Issue by czh451060866** [warmcat/libwebsockets#2329]
#00 0x000a3e04 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
void std::swap<buf_mem_st*>(buf_mem_st*&, buf_mem_st*&)
/Users/lichao40/android-sdk-mac_x86/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/move.h:178:19
std::unique_ptr<buf_mem_st, bssl::internal::Deleter<buf_mem_st> >::reset(buf_mem_st*)
/Users/lichao40/android-sdk-mac_x86/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:342:0
bssl::ssl3_flush_flight(ssl_st*)
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/jnicore/boringssl/boringssl/build/../ssl/s3_both.cc:344:0
#01 0x0009f75b /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
bssl::ssl_run_handshake(bssl::SSL_HANDSHAKE*, bool*)
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/jnicore/boringssl/boringssl/build/../ssl/handshake.cc:604:13
#02 0x0008eb0d /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
std::unique_ptr<ssl_ctx_st, bssl::internal::Deleter<ssl_ctx_st> >::get() const
/Users/lichao40/android-sdk-mac_x86/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:305:16
std::unique_ptr<ssl_ctx_st, bssl::internal::Deleter<ssl_ctx_st> >::operator->() const
/Users/lichao40/android-sdk-mac_x86/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unique_ptr.h:299:0
bssl::ssl_do_info_callback(ssl_st const*, int, int)
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/jnicore/boringssl/boringssl/build/../ssl/ssl_lib.cc:371:0
SSL_do_handshake
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/jnicore/boringssl/boringssl/build/../ssl/ssl_lib.cc:892:0
#03 0x00086d35 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_tls_client_connect
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/tls/openssl/openssl-client.c:301:0
#04 0x00086969 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_ssl_client_connect1
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/tls/tls-client.c:34:0
#05 0x00084e4b /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_client_socket_service
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/http/client/client.c:341:0
#06 0x00081edb /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
rops_handle_POLLIN_h1
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/h1/ops-h1.c:675:0
#07 0x0007f71f /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service_fd_tsi+142)
                                                                             lws_service_fd_tsi
                                                                             /Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/core-net/service.c:615:0
#08 0x000853d1 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_client_connect_3
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/http/client/client-handshake.c:148:0
#09 0x000859cf /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_client_connect_2
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/http/client/client-handshake.c:559:0
#10 0x00084d6b /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
lws_client_socket_service
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/http/client/client.c:273:0
#11 0x00081edb /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
rops_handle_POLLIN_h1
/Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/roles/h1/ops-h1.c:675:0
#12 0x0007f71f /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service_fd_tsi+142)
                                                                             lws_service_fd_tsi
                                                                             /Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/core-net/service.c:615:0
#13 0x00088259 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (_lws_plat_service_tsi+504)
                                                                             _lws_plat_service_tsi
                                                                             /Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/plat/unix/unix-service.c:179:0
#14 0x0007f7a3 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service+44)
                                                                             lws_service
                                                                             /Users/lichao40/AndroidStudioProjects/MTDroidVNC5/app/src/main/mtra_server/libs/websockets/libwebsockets-3.2.0/lib/core-net/service.c:680:0
#15 0x00040291 /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (_ZN8WsClient13ws_event_loopEPv+20)
                                                                             WsClient::ws_event_loop(void*)
                                                                             /Users/chenzhihui/Desktop/rom_app_mtra_android/app/src/main/mtra_server/mtra_server/WsClient.cpp:303:13

The original backtrace is：
Build fingerprint: 'Android/rk3368_32/rk3368_32:6.0.1/MOB30J/121:userdebug/test-keys'
06-21 18:37:37.109  3028  3066 I System.out: Revision: '0'
06-21 18:37:37.109  3028  3066 I System.out: Author: collect by 'libunwind'
06-21 18:37:37.109  3028  3066 I System.out: ABI: 'armeabi-v7a'
06-21 18:37:37.109  3028  3066 I System.out: pid: 3028, tid: 3148, name: 3145  >>> com.sankuai.mtra_acr2 <<<
06-21 18:37:37.109  3028  3066 I System.out: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-21 18:37:37.109  3028  3066 I System.out: backtrace:
06-21 18:37:37.109  3028  3066 I System.out:     r0  ab4c2308  r1  00000000  r2  ab501c00  r3  000000ac
06-21 18:37:37.109  3028  3066 I System.out:     r4  ab6719c8  r5  ab6719c8  r6  df25442f  r7  df254418
06-21 18:37:37.109  3028  3066 I System.out:     r8  ab5ce6f8  r9  df254430  r10 00000000  r11 df254437
06-21 18:37:37.109  3028  3066 I System.out:     ip  df2543e8  sp  df254408  lr  e17f3619  pc  e17c3e04
06-21 18:37:37.109  3028  3066 I System.out:     #00 pc 000a3e04  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #01 pc 0009f75b  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #02 pc 0008eb0d  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #03 pc 00086d35  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #04 pc 00086969  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #05 pc 00084e4b  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #06 pc 00081edb  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #07 pc 0007f71f  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service_fd_tsi+142)
06-21 18:37:37.109  3028  3066 I System.out:     #08 pc 000853d1  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #09 pc 000859cf  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #10 pc 00084d6b  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #11 pc 00081edb  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so
06-21 18:37:37.109  3028  3066 I System.out:     #12 pc 0007f71f  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service_fd_tsi+142)
06-21 18:37:37.109  3028  3066 I System.out:     #13 pc 00088259  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (_lws_plat_service_tsi+504)
06-21 18:37:37.109  3028  3066 I System.out:     #14 pc 0007f7a3  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (lws_service+44)
06-21 18:37:37.109  3028  3066 I System.out:     #15 pc 00040291  /data/app/com.sankuai.mtra_acr2-1/lib/arm/libandroid_mtra.so (_ZN8WsClient13ws_event_loopEPv+20)
06-21 18:37:37.110  3028  3066 I System.out:     #16 pc 00041657  /system/lib/libc.so
06-21 18:37:37.110  3028  3066 I System.out:     #17 pc 00019233  /system/lib/libc.so

Can you help me find out the reason.TY

**Comment by lws-team** [comment]
Dunno... it's dying in boringssl trying to start a tls client handshake.

Boringssl is quite difficult to build against because it is an easy mistake to use build machine openssl headers instead of the ones you intended.  You can sanity-check if that by temporarily adding a syntax error in the installed boringssl headers you expect to consume and see if lws build breaks.  If it doesn't, you know it's getting some other headers from somewhere.

**Comment by lws-team** [comment]
If you want to debug it further, you'll need to build boringssl with debuginfo and look at exactly where it blows.
