### ISSUE TITLE
log tags cannot be added at vhost and wsi at creation

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2330]
I see there  is a new feature to add tags to the logs with 

```
void
__lws_lc_tag_append(lws_lifecycle_t *lc, const char *app)
```

I was planning to use this to track the vhosts transactions/life-cycle (FROM LWS_CALLBACK_ESTABLISHED... to ...CLOSED...)  by adding an unique identifier `uuid` to the logs and be able to regroup the logs based on that `uuid` afterward. This is useful when multiple concurrent connections happen at the same and you need to reassemble them in the logs.

Although I'm able to append the tag successfully I'm not able to add it at the `vhost` and `wsi`  at creation cause there is not way to pass the tag here:

`https://github.com/warmcat/libwebsockets/blob/6c339f84a245eba63075df49d660f5bcd29adb5b/lib/core-net/vhost.c#L610`

Unless I'm missing something...

You can see here the `uuid` `a854e607` is added successfully but not in the first log entries.
```
2021-06-21T19:33:50.226131+00:00 a178a97c914c 5 api:  ++ [wsicli|1|GET/h1/+/var/run/test.sock] (2)
2021-06-21T19:33:50.449287+00:00 a178a97c914c 5 api:  -- [vh|3|test||-1|a854e607] (3) 228.281ms
2021-06-21T19:33:50.450640+00:00 a178a97c914c 5 api:  -- [wsicli|1|GET/h1/+/var/run/test.sock|docker|a854e607] (1) 224.639ms
```

It would be great to pass traceid/uuid at creation.

**Comment by lws-team** [comment]
For vhost, you can control the vhost name at creation time, and that's part of the tag already.  I can add a client wsi creation-time tag fragment arg (or reuse fi_wsi_name) you can pass in.

**Comment by alexeadem** [comment]
Making the vhost name a unique identifier would be possible but maybe better to keep that read friendly...I think. It is more like an unique identifier that I can use to stitch all logs for a particular transaction together.
`e2fd747080c4`
or
`e0219895-fc62-432a-b6b4-14100e7a1ab9`

a `creation time` under
`struct lws_context_creation_info info`
or as argument to `lws_create_vhost`  that can be read by

```
__lws_lc_tag(&context->lcg[LWSLCG_VHOST], &vh->lc, "%s|%s|%d", buf,
			info->iface ? info->iface : "", info->port);
``
would be awesome

Thanks

**Comment by lws-team** [comment]
Spring cleaning old issues... if you'd like to suggest a patch for this, I'll take a look.  But I don't have any plans to add it myself.
