### ISSUE TITLE
Failed to build for Android NDK

### ISSUE THREAD

**Issue by dpingg** [warmcat/libwebsockets#2331]
I followed this readme: https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-android.md. By the way, is it the correct doc for Android?

Environment:
$ uname -a
Linux daping-VirtualBox 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ndk version: android-ndk-r21e

The error I got:
[ 15%] Built target mbedcrypto_static
[ 33%] Built target mbedcrypto
[ 18%] Built target mbedtls_test
[ 35%] Built target mbedx509_static
[ 37%] Built target mbedx509
[ 39%] Built target mbedtls
[ 42%] Built target mbedtls_static
make[2]: *** No rule to make target '../tests/suites/test_suite_psa_crypto_storage_format.v0.data', needed by 'tests/test_suite_psa_crypto_storage_format.v0.c'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:833: tests/CMakeFiles/test_suite_psa_crypto_storage_format.v0.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 42%] Built target test_suite_version
[ 43%] Built target test_suite_x509write
[ 44%] Built target test_suite_timing
[ 45%] Built target test_suite_rsa
[ 46%] Built target test_suite_ssl
[ 47%] Built target test_suite_psa_crypto_storage_format.misc
[ 48%] Built target test_suite_psa_crypto_se_driver_hal_mocks
make: *** [Makefile:141: all] Error 2

**Comment by lws-team** [comment]
>  is it the correct doc for Android?

It was when it was written.

Here is it building successfully in CI

https://libwebsockets.org/sai/index.html?task=724f80c154c5fc64a8392d7b7a30c434b72d9814860e8c32eb37070bc995d0d3

```
 42%] Built target mbedtls_static
make[2]: *** No rule to make target '../tests/suites/test_suite_psa_crypto_storage_format.v0.data', needed by 'tests/test_suite_psa_crypto_storage_format.v0.c'. Stop.
make[1]: *** [CMakeFiles/Makefile2:833: tests/CMakeFiles/test_suite_psa_crypto_storage_format.v0.dir/all] Error 2
```

That's some build problem with mbedtls, it's nothing to do with lws.

**Comment by fougere-mike** [comment]
I'm also running into problems with mbedtls trying to follow the android build instructions. 

When I first cloned `mbedtls`, I was getting an error about a missing `error.c` file. After some poking around I checked out the `master` branch instead of the default `development` branch, and that error went away.

The `make` call is still failing though:
```
[ 30%] Building C object library/CMakeFiles/mbedcrypto_static.dir/timing.c.o
[ 30%] Building C object library/CMakeFiles/mbedcrypto_static.dir/version_features.c.o
[ 30%] Building C object library/CMakeFiles/mbedcrypto_static.dir/version.c.o
[ 30%] Building C object library/CMakeFiles/mbedcrypto_static.dir/xtea.c.o
[ 30%] Building C object library/CMakeFiles/mbedcrypto.dir/xtea.c.o
[ 31%] Linking C shared library libmbedcrypto.so
[ 32%] Linking C static library libmbedcrypto.a
[ 32%] Built target mbedcrypto
Error running link command: No such file or directory
Scanning dependencies of target mbedx509
make[2]: *** [library/CMakeFiles/mbedcrypto_static.dir/build.make:1105: library/libmbedcrypto.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:490: library/CMakeFiles/mbedcrypto_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/x509_crl.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/pkcs11.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/x509_crt.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/x509_create.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/x509write_csr.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/x509.c.o
[ 33%] Building C object library/CMakeFiles/mbedx509.dir/certs.c.o
[ 34%] Building C object library/CMakeFiles/mbedx509.dir/x509write_crt.c.o
[ 34%] Building C object library/CMakeFiles/mbedx509.dir/x509_csr.c.o
[ 34%] Linking C shared library libmbedx509.so
[ 34%] Built target mbedx509
make: *** [Makefile:129: all] Error 2
```

Would it be possible to provide the specific `mbedtls` commit which the instructions were written against?

**Comment by lws-team** [comment]
mbedtls own build problems are really nothing to do with lws.

One tip, mbedtls have two build systems, cmake and Makefile.  Last time I looked at their dev banch, cmake one did not build, but the Makefile path did.

Questions about mbedtls build need to go to mbedtls project.

**Comment by fougere-mike** [comment]
I understand your point, but `mbedtls` builds fine by itself. The problems occur trying to build with the [toolchain file provided by lws](https://github.com/warmcat/libwebsockets/blob/main/contrib/cross-aarch64-android.cmake).

From the lws android build instructions:
> $ rm -f CMakeCache.txt && \
  cmake .. -DCMAKE_TOOLCHAIN_FILE=../libwebsockets/contrib/cross-aarch64-android.cmake \
  -DUSE_SHARED_MBEDTLS_LIBRARY=1 \
  -DENABLE_PROGRAMS=0 \
  -Wno-dev && \
  make -j && \
  cmake --install .

It seems that the mbedtls project has become incompatible with [README.build-android.md](https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-android.md) over time. Therefore, would it be possible to find which version of mbedtls _did_ work with the given instructions?
