### ISSUE TITLE
lws_create_context return nullptr when I open 

### ISSUE THREAD

**Issue by czh451060866** [warmcat/libwebsockets#2333]
lws_create_context return nullptr when I open LWS_WITH_SYS_ASNYC_DNS in cmake.
When I don't uses this config, lws_create_context return a context.
what's the probably reason?

**Comment by lws-team** [comment]
You are asking me to guess when you have the logs?  What do the logs say?

**Comment by czh451060866** [comment]
Sorry, I'll attach the log after rebuild an run

**Comment by lws-team** [comment]
...
