### ISSUE TITLE
ws connect return  CLIENT_CONNECTION_ERROR: connect SYSCALL 104

### ISSUE THREAD

**Issue by czh451060866** [warmcat/libwebsockets#2334]
When I use lws version 3.x, I never encountered this error before.
When I use version 4.1, I encountered this error occasionally.
Can you give me some clues about this

**Comment by lws-team** [comment]
SYSCALL is an error returned by the tls library, that it met a platform-specific error, the number is errno.

errno 104 is ECONNRESET on Linux.  The server or balancer or whatever hung up, or the connection was otherwise forcibly disconnected, during the tls negotiation.
