### ISSUE TITLE
issue building with LWS_WITH_GLIB

### ISSUE THREAD

**Issue by marcelo-gonzalez** [warmcat/libwebsockets#2338]
Hi, small issue to report when buildling with cmake -DLWS_WITH_GLIB=ON. Everything works if the the libglib headers are in one of the usual system paths (/usr/include, /usr/local/include, etc), but you get build failures if you try to set GLIB_INCLUDE_DIRS to point to some other path where you have a custom install.

It's fixed by this:
--- a/lib/event-libs/glib/private-lib-event-libs-glib.h
+++ b/lib/event-libs/glib/private-lib-event-libs-glib.h
@@ -23,7 +23,7 @@
  */
 
 #if defined(LWS_WITH_GLIB)
-#include <glib-2.0/glib.h>
+#include <glib.h>
 #endif /* LWS_WITH_GLIB */
 
 struct lws_pt_eventlibs_glib {

The issue is that GLIB_INCLUDE_DIRS already has the glib-2.0 on the end, so if you have an installation of glib in /usr/local/include, that will be used instead of the one provided with GLIB_INCLUDE_DIRS. Normally it goes unnoticed because the default value of GLIB_INCLUDE_DIRS does indeed get skipped, but then the compiler finds your headers after searching the normal system paths.

**Comment by lws-team** [comment]
Thanks... it seems it can just be told to use glib.h and no problem.  I pushed your patch on main and next time I update v4.2-stable it will be on that too.

**Comment by marcelo-gonzalez** [comment]
cool, thanks!
