### ISSUE TITLE
Bug in deprecated functions

### ISSUE THREAD

**Issue by nikias** [warmcat/libwebsockets#2346]
I know it's deprecated, but if `LWS_WITH_DEPRECATED_THINGS` is set it fails to compile:
```
/Users/nikias/coding/zimperium/zCLOUD/native/base/third_party/libwebsockets/lib/core-net/wsi-timeout.c:230:52: error: implicit conversion changes
      signedness: 'int' to 'enum lws_callback_reasons' [-Werror,-Wsign-conversion]
        tvp->protocol->callback((struct lws *)plwsa, tvp->reason, NULL, NULL, 0);
        ~~~                                          ~~~~~^~~~~~
/Users/nikias/coding/zimperium/zCLOUD/native/base/third_party/libwebsockets/lib/core-net/wsi-timeout.c:261:45: error: too many arguments to function
      call, expected 2, have 3
                         (lws_sorted_usec_list_t *)&p->sul.list, us);
                                                                 ^~
/Users/nikias/coding/zimperium/zCLOUD/native/base/third_party/libwebsockets/include/libwebsockets/lws-timeout-timer.h:356:24: note:
      '__lws_sul_insert' declared here
LWS_VISIBLE LWS_EXTERN int
                       ^
2 errors generated.
```
Now the first one can be fixed with a cast to `enum lws_callback_reasons`. The second seems like it should use `__lws_sul_insert_us` but then the first argument has a mismatching type:
```
/Users/nikias/coding/libwebsockets/lib/core-net/wsi-timeout.c:260:22: error: incompatible pointer types passing 'struct lws_dll2_owner (*)[2]' to
      parameter of type 'lws_dll2_owner_t *' (aka 'struct lws_dll2_owner *') [-Werror,-Wincompatible-pointer-types]
        __lws_sul_insert_us(&vh->context->pt[p->tsi_req].pt_sul_owner,
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/nikias/coding/libwebsockets/lib/core-net/./private-lib-core-net.h:57:20: note: expanded from macro '__lws_sul_insert_us'
                __lws_sul_insert(owner, sul)
                                 ^~~~~
/Users/nikias/coding/libwebsockets/include/libwebsockets/lws-timeout-timer.h:357:36: note: passing argument to parameter 'own' here
__lws_sul_insert(lws_dll2_owner_t *own, lws_sorted_usec_list_t *sul);
                                   ^
1 error generated.
```
I fixed it like this but I am not sure if this is correct:
```diff
@@ -257,7 +257,7 @@ lws_timed_callback_vh_protocol_us(struct lws_vhost *vh,

        p->sul.cb = lws_sul_timed_callback_vh_protocol_cb;
        /* list is always at the very top of the sul */
-       __lws_sul_insert(&vh->context->pt[p->tsi_req].pt_sul_owner,
+       __lws_sul_insert_us(&vh->context->pt[p->tsi_req].pt_sul_owner[0],
                         (lws_sorted_usec_list_t *)&p->sul.list, us);

        lws_vhost_lock(vh); /* vhost ---------------------------------------- */
```

**Comment by lws-team** [comment]
Yes your change would work... it became an array to separate out scheduled events that are important enough to wake the system from suspend for or not. [0] or [LWSSULLI_MISS_IF_SUSPENDED] means the event would be missed in suspend.

But I think I should remove this stuff... LWS_WITH_DEPRECATED_THINGS does not have a cmake api, you actually have to hack the sources to enable it to build.  I marked this with basically a #if 0 then over a year ago in May 2020 and you're the first person to remark on it.

These vhost-specific timers have significant problems compared to using lws_sul directly; you can have only one of them per vhost, whereas you can have as many lws_sul as you want, they don't have to bind to anything except the context.  In particular, they don't have to bind to a protocol callback, you declare them each with their own callback, or they can share callbacks.

If you are trying to support code that used them, the best way is adapt the code to use a user lws_sul... is that your issue?

**Comment by lws-team** [comment]
That's the best way out of it I think.  If any questions about the change feel free to ask.
