### ISSUE TITLE
cpu > 96%

### ISSUE THREAD

**Issue by gmmota** [warmcat/libwebsockets#235]
First thanks for the library.
I noticed that after a call libwebsocket_cancel_service in another thread, the CPU rises above 96%.
I tested also calling libwebsocket_callback_on_writable_all_protocol that same thread, showing the same thing.
This thread is simply by setting one flag (ws_flags_write_all) for the main thread calls libwebsocket_callback_on_writable_all_protocol.
The problem presents itself when enters 'y' via keyboard on which sets the flag and calls libwebsocket_cancel_service.
In this thread I can get around this by setting the flag and just never calling libwebsocket_cancel_service or libwebsocket_callback_on_writable_all_protocol,
using a small timeout in libwebsocket_service.
It is curious because libwebsocket_cancel_service just write the dummy pipe while libwebsocket_callback_on_writable_all_protocol do more things.

I'm running on the raspberry pi model b.

## My Thread:
```c
static volatile int ws_flags_write_all = 0;
 
static void * my_thread(void *arg){
    char buf[25];
 
    while(!force_exit) {
 
        printf("\n>>>");
        fflush(stdout);
 
        if(fgets(buf, 20, stdin)==NULL)
            continue;
                   
        if(buf[0] == 'q' || buf[0] == 'Q'){
            force_exit = 1;
            libwebsocket_cancel_service(context);
            break;
        }
 
        switch(buf[0]){
            case 'x': ws_flags_write_all = 1; break;  /* continue dumb protocol, cpu OK  */
            case 'X': ws_flags_write_all = 0; break;  /* pause dumb protocol, cpu OK     */
            case 'y':	                              /* pause dumb protocol cpu > 96% !!!! */
                ws_flags_write_all = 1;
                libwebsocket_cancel_service(context);
        }
    }
 
    return NULL;
}
```

## Part Main thread:
```c
	    pthread_t thr;
		if((n = pthread_create(&thr, NULL, &my_thread, NULL)) != 0){
			errno = n;
			perror("pthread_create");
			return -1;
		}
 
        n = 0;
        while (n >= 0 && !force_exit) {
                struct timeval tv;
 
                gettimeofday(&tv, NULL);
 
                /*
                 * This provokes the LWS_CALLBACK_SERVER_WRITEABLE for every
                 * live websocket connection using the DUMB_INCREMENT protocol,
                 * as soon as it can take more packets (usually immediately)
                 */
				if(ws_flags_write_all){  /* set only in my_thread */
					ms = (tv.tv_sec * 1000) + (tv.tv_usec / 1000);
					if ((ms - oldms) > 50) {
						libwebsocket_callback_on_writable_all_protocol(&protocols[PROTOCOL_DUMB_INCREMENT]);
						oldms = ms;
					}
				}
#ifdef EXTERNAL_POLL
 
                /*
                 * this represents an existing server's single poll action
                 * which also includes libwebsocket sockets
                 */
 
                n = poll(pollfds, count_pollfds, 50);
                if (n < 0)
                        continue;
 
 
                if (n)
                        for (n = 0; n < count_pollfds; n++)
                                if (pollfds[n].revents)
                                        /*
                                        * returns immediately if the fd does not
                                        * match anything under libwebsockets
                                        * control
                                        */
                                        if (libwebsocket_service_fd(context,
                                                                  &pollfds[n]) < 0)
                                                goto done;
#else
                /*
                 * If libwebsockets sockets are all we care about,
                 * you can use this api which takes care of the poll()
                 * and looping through finding who needed service.
                 *
                 * If no socket needs service, it'll return anyway after
                 * the number of ms in the second argument.
                 */
 
                n = libwebsocket_service(context, 50);
#endif
        }
 
#ifdef EXTERNAL_POLL
done:
#endif
 
        libwebsocket_context_destroy(context);
 
        lwsl_notice("libwebsockets-test-server exited cleanly\n");
 
#ifndef WIN32
        closelog();
#endif
 
		pthread_cancel(thr);
		pthread_join(thr, NULL);
 
        return 0;
```

## Console output:

>lwsts [31255]: libwebsockets test server - (C) Copyright 2010-2014 Andy Green ><andy@warmcat.com> - licensed under LGPL2.1
>Using resource path "/ home / pi / test-server"
>lwsts [31255]: Initial logging level 7
>lwsts [31255]: Library version: 1.3 080e6dd
>lwsts [31255]: IPV6 not compiled in
>lwsts [31255]: libev support not compiled in
>lwsts [31255]: static allocation: 4480 + (12 x 1024 fds) = 16768 bytes
>lwsts [31255]: = canonical_hostname raspberrypi
>lwsts [31255]: per-conn Memory: 144 + 2100 + protocol headers rx buf
>lwsts [31255]: Compiled with OpenSSL support
>lwsts [31255]: Using non-SSL mode
>lwsts [31255]: Listening on port 7681

Modified file test-server.c
http://pastebin.com/DMah3jNc

Thank U

**Comment by gmmota** [comment]
Compiled without SSL support (-DLWS_WITH_SSL = 0)
and the CPU is not longer tied when called libwebsocket_cancel_service() 
from another thread (Actually not even have to be from another thread, 
calling on the main thread already has the problem).
I suspect the problem is in the lws-plat-unix.c file when compiling 
with -DLWS_WITH_SSL = 1, lws_plat_service function() on line 111:
```c
#ifdef LWS_OPENSSL_SUPPORT
	/ * If we know we have non-network pending date, do not wait in poll * /
	if (context-> ssl_flag_buffered_reads)
		timeout_ms = 0;
#endif
```
I believe that somehow the timeout is being reset before reaching the poll() function 
when compiled with OPENSSL _SUPPORT and invoking libwebsocket_cancel_service ().

Thanks

**Comment by wonder-mice** [comment]
I confirm that issue. Didn't investigate it too deeply though, but it looks like the reason is that libwebsockets doesn't care what SSL wants: 
```
    if (n == SSL_ERROR_WANT_READ ||
        n == SSL_ERROR_WANT_WRITE) {
        ...
        libwebsocket_callback_on_writable(context, wsi);
```

So, even when SSL wants to READ lightheaded libwebsockets will set LWS_POLLOUT on the file descriptor. And since socket can accept writes it will be triggered on each event loop iteration. But since SSL wants to READ, not WRITE the process will continue to churn until socket become readable.

Also I noticed that libwebsockets doesn't reset LWS_POLLOUT after async connect was completed. But not sure whether it's part of the design or not.

**Comment by warmcat** [comment]
It's not that it 'doesn't care'.  It is because ssl protocol may need to write something more before anything further is sent by the peer, even though we try to use a 'read' api.

**Comment by wonder-mice** [comment]
There is a way to check the amount of pending write data, such as `BIO_ctrl_pending()` and `SSL_pending()`. If OpenSSL says it has nothing more to write, there is no need to set LWS_POLLOUT.

**Comment by warmcat** [comment]
Hm SSL_pending / BIO_ctrl_pending is about how much is waiting for read.

There is a BIO_ctrl_wpending()... that might do something.

**Comment by wonder-mice** [comment]
It's a bit tricky to figure out what exactly function should be used.
I only had experience with OpenSSL's async BIO without sockets (using external transport layer).
As I remember, I used BIO_ctrl_pending() because it says how much data you can READ from OpenSSL to WRITE it into network :)
But I believe with some testing/docs reading it should be clear what function to use.

**Comment by warmcat** [comment]
I can't reproduce this casually and don't really understand the root cause, so meddling with it blind is a bit optimistic.

I think I better try to reproduce it using the "call the cancel" method above and make sure I understand what is going on.

**Comment by wonder-mice** [comment]
I reproduce it with libwebsocket_client_connect() and libev event loop. I think it's better not to use localhost server to reproduce this one.
While my issue looks different, I believe they have somewhat related root cause.

**Comment by wonder-mice** [comment]
This patch fixes 100%CPU on the client during connect for me:
https://github.com/wonder-mice/libwebsockets/commit/23e938f8d10aaef82600b71ac4bd30c510103553

Didn't do enough testing though, probably break a lot. Also I doubt it could fix original problem this issue is about.

**Comment by warmcat** [comment]
I am not sure that hits the nail completely on the head.  Because it looks like the patch separating out the want read and write is a NOP in the case ssl decides that he does in fact want write, which means that problem is still there.

**Comment by wonder-mice** [comment]
My patch is unrelated to that issue. It solves 100% CPU on connect.
