### ISSUE TITLE
multithread call lws_callback_on_writable to send data ASAP

### ISSUE THREAD

**Issue by chllcy** [warmcat/libwebsockets#2358]
with main thread using the default poll() event loop, and four other thread（four wsi） call lws_callback_on_writable。
sometimes, it get LWS_CALLBACK_SERVER_WRITEABLE callback(to send data) after the next packet coming（for several seconds）。
how can I send data as soon as possible？

**Comment by lws-team** [comment]
> and four other thread（four wsi） call lws_callback_on_writable。

Nope, you cannot do this.

Lws works on a single event loop thread only, you cannot call any lws api except `lws_cancel_service()` from another thread,

There are a few choices, why don't you describe what considerations led to these being separate threads?

**Comment by chllcy** [comment]
> Lws works on a single event loop thread only, you cannot call any lws api except `lws_cancel_service()` from another thread,
I read [Aside from two APIs, directly calling lws apis from other threads is not allowed](https://github.com/warmcat/libwebsockets/blob/main/READMEs/README.coding.md).
>Therefore the two apis mentioned above that may be used from another thread are

>For LWS using the default poll() event loop, lws_callback_on_writable()

> For LWS using libuv/libev/libevent event loop, lws_cancel_service()

I'm using the default poll event loop. with one thread(send recv) + four thread (event handle)

**Comment by lws-team** [comment]
> For LWS using the default poll() event loop, lws_callback_on_writable()

Yeah... sorry that is just cruft now, it used to be the case on some platforms, but isn't supported any more.  I'll update the docs later to reflect that.

lws_cancel_service() is the only safe choice on all platforms.

If you are on Linux, you can try following the lws_callback_on_writable() with a lws_cancel_service() to force the main thread to wake and handle your change.

For platform specific reasons, that won't work on, eg, BSDs, they trash the pollfd .events when they come out of the wait, removing your change done while the main thread was in poll() or whatever.

And for event lib specific reasons, depending on the lib they cannot handle their apis being called from other threads to start the POLLOUT wait.

The other alternative is use lws_cancel_service() way.

**Comment by chllcy** [comment]
thanks @lws-team 
```
    lws_callback_on_writable(wsi_);
    lws_cancel_service_pt(wsi_);
```
I'm now using above code to force the main thread to send data,but sometimes it's still not send the data ASAP.

**Comment by lws-team** [comment]
What kind of delays are you seeing?

The delay between asking for it and getting it can be normal, for example the tcp window on the connection is full, the WRITEABLE won't come until you receive some new ACKs for what was already sent.

That's why the request for writeable and delivery of it is separate, so it regulates your transmission speed to match when it can send according to the connection parameters.

If it feels something wrong, then definitely try doing the lws_callback_on_writable() from the lws thread context in the `LWS_CALLBACK_EVENT_WAIT_CANCELLED` handler.

**Comment by chllcy** [comment]
>What kind of delays are you seeing?
the next packet coming（for 10 seconds） then the data send，and the data is small。
>If it feels something wrong, then definitely try doing the lws_callback_on_writable() from the lws thread context in the LWS_CALLBACK_EVENT_WAIT_CANCELLED handler.
this might help,in the log I see LWS_CALLBACK_EVENT_WAIT_CANCELLED. I will try next time.
```
case LWS_CALLBACK_EVENT_WAIT_CANCELLED:
    lws_callback_on_writable(wsi_);
```

**Comment by chllcy** [comment]
Crash reason:  SIGSEGV /0x00000080
Crash address: 0x0
Process uptime: not available

Thread 5 (crashed)
 0  app_server!_lws_change_pollfd.part.2 + 0xa3
    rax = 0x00007ff8c400a940   rdx = 0x617461642f343030
    rcx = 0x617461642f343030   rbx = 0x00007ff8e8000b20
    rsi = 0x00007ff8c40008d0   rdi = 0x00007ff8c400a940
    rbp = 0x00007ff8e8002ef0   rsp = 0x00007ff8f5616d30
     r8 = 0x0000000000000000    r9 = 0x00000000000000d8
    r10 = 0x0000000000000000   r11 = 0x00007ff8c40085cc
    r12 = 0x0000000000000000   r13 = 0x00007ff8e8000b20
    r14 = 0x0000000000000004   r15 = 0x0000000000000000
    rip = 0x0000561f113de5e3
    Found by: given as instruction pointer in context
 1  app_server!lws_callback_on_writable + 0xc6
    rbx = 0x00007ff8e8002ef0   rbp = 0x00007ff8c4007530
    rsp = 0x00007ff8f5616d80   r12 = 0x000000000000018b
    r13 = 0x00007ff8f5616de0   r14 = 0x00007ff8e8005780
    r15 = 0x00007ff8f8f61070   rip = 0x0000561f113df236
    Found by: call frame info
@lws-team ,it's true that cant' use  lws_callback_on_writable(wsi_); in another thread(it will be a small probability to crash) .
but if I used lws_callback_on_writable in LWS_CALLBACK_EVENT_WAIT_CANCELLED, I had to iterator all the wsi，it's not a good idea。

**Comment by lws-team** [comment]
Hm... the best way is to not use other threads and do everything on the event loop.  That is why I said originally

>> There are a few choices, why don't you describe what considerations led to these being separate threads?

If you are truly stuck with different threads, the way to deal with async wsi lifecycle is add your locking also in the wsi CLOSE handler, and action the loss of the wsi in the other thread there, before it is deleted after you return from the CLOSE.

The way to deal with many threads who may want something from the lws thread in EVENT_WAIT_CANCELLED is have a locked list of what needs to happen that the other threads and EVENT_WAIT_CANCELLED share.

But do you really need n threads or just directly do their job on the event loop and get rid of them all?

**Comment by liberize** [comment]
@lws-team 
In my case, I need to handle events with a third party library, which only offers time-cosuming synchronous interface and feeds me with data in it's internal threads. So yes, I need n threads to receive data from upstream and pump to lws event loop thread.
lws_cancel_service seems to trigger EVENT_WAIT_CANCELLED for all wsi (?), which is too heavy for me, I want to wake a single wsi on data coming.

**Comment by chllcy** [comment]
@liberize 
you can save writeable wsi in your context(such as std::set<struct lws*>) , and when EVENT_WAIT_CANCELLED callback trigger, you can get them to do lws_callback_on_writable。

**Comment by lws-team** [comment]
Yes @chllcy is right.  You can list what needs to be done in the event loop thread context in a mutex-protected shared area.

> lws_cancel_service seems to trigger EVENT_WAIT_CANCELLED for all wsi (?), which is too heavy for me,

That's not what happens... one callback goes to each protocol - vhost instantiation.  It scales OK because 1) EVENT_WAIT_CANCELLED relates to the event loop as a whole, the number of callbacks (typ "a few") is constant no matter how many wsi are active.  ... and 2) you can only go around the event loop so many times a second, as it gets busier, it spends more time serving active fds and then processes EVENT_WAIT_CANCELLED somewhat less per second, even if it is happening all the time.  Using a protected list in the shared area means everything will still get done at low latency.
