### ISSUE TITLE
Send a message to the server

### ISSUE THREAD

**Issue by tickox** [warmcat/libwebsockets#2359]
Good evening,

In the websocket binance client example, I don't understand how to send messages to server ...
I have looked at the other examples but I am really totally lost.

I am calling `` lws_callback_on_writable (wsi); `` in the switch `` LWS_CALLBACK_CLIENT_RECEIVE ``

As soon as I send a message in the LWS_CALLBACK_CLIENT_WRITEABLE switch I have this error:

```{" status ": 500," error ":" Server Error "," meta ": {}}```

Could you tell me what to add to send a message?

Thank you

**Comment by lws-team** [comment]
So what does your code look like for lws_write()?

The server wants BINARY or TEXT ws message?  What are you giving it?

Is your message well-formatted according to what the remote peer wants to see?

Is the link authenticated to send the message if it need it?

When you say, "I have this error", the peer server is sending you that JSON as a ws message in response, or something else?

**Comment by tickox** [comment]
Hello,

The message is not formatted well but I have inquired and it is not a problem, the server should just send me an error message to say that it is badly formatted.
The error message does not correspond to what I should receive (I tested with another library).

"Is the link authenticated to send the message if it need it?" I have no knowledge in the field so I can't tell you.

In ```LWS_CALLBACK_CLIENT_WRITEABLE``` I do this:

```cpp
char buff [LWS_PRE + 32];
lws_strncpy (& buff [LWS_PRE], "test", 4);
lws_write (wsi, & buf [LWS_PRE], 4, LWS_WRITE_TEXT);
```

In the binance example, I just added the line ``` lws_callback_on_writable (wsi) ``` and the code above.

Thanks

**Comment by lws-team** [comment]
> The message is not formatted well but I have inquired and it is not a problem, the server should just send me an error message to say that it is badly formatted.

You need to make sure you are only doing the lws_write() one time after the connection is ESTABLISHED, set a flag in ESTABLISHED and clear it after doing the write, break; out of WRITEABLE before doing the write if the flag is not set.

**Comment by tickox** [comment]
This is what I tried.

At the first message received in ```LWS_CALLBACK_CLIENT_RECEIVE``` I call ```lws_callback_on_writable (wsi)```.

In ```LWS_CALLBACK_CLIENT_WRITEABLE``` I changed my flag and I only called ```lws_write``` once, never changing my flag again.
I am on windows, can this have an impact?

Thanks

**Comment by lws-team** [comment]
Hm... let's stop wasting time with the guessing games, send me a patch on the existing binance example that shows the problem and I will look at it.
