### ISSUE TITLE
Add a way to distinguish libwebsockets versions.

### ISSUE THREAD

**Issue by ThomasDevoogdt** [warmcat/libwebsockets#2365]
There were already a lot of API-breaking changes in the past.  
There are few #defines to differentiate on, e.g. LWS_FEATURE_SERVE_HTTP_FILE_HAS_OTHER_HEADERS_ARG, but that's far from enough. 

I propose to add a version tag from the next release onwards. This will allow programmers to give support to multiple versions of the libwebsockets project. 

API changes I encountered:
- LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
- info.ssl_connection
- info.pwsi
- LWS_CALLBACK_CLIENT_CLOSED

**Comment by lws-team** [comment]
The changes you mention are all several years old... although there's no motive to make things difficult, sometimes things must be deprecated.  For example, both mbedtls and openssl have deprecated a lot of apis over the years.

Lws has had this kind of thing via lws_config.h, also part of the exported includes, for many years

```
#define LWS_LIBRARY_VERSION_MAJOR 4
#define LWS_LIBRARY_VERSION_MINOR 2
#define LWS_LIBRARY_VERSION_PATCH_ELABORATED 99-v4.2.0-133-gf45b455f6c
#define LWS_LIBRARY_VERSION_PATCH 99

/* LWS_LIBRARY_VERSION_NUMBER looks like 1005001 for e.g. version 1.5.1 */
#define LWS_LIBRARY_VERSION_NUMBER (LWS_LIBRARY_VERSION_MAJOR * 1000000) + \
                                        (LWS_LIBRARY_VERSION_MINOR * 1000) + \
                                        LWS_LIBRARY_VERSION_PATCH
```

The way lws itself deals with evolving libs like openssl and mbedtls is cmake checks for api availability and pick between implementations with the results of that.

And there is no support for lws older than the last stable release.
