### ISSUE TITLE
Can I create multiple contexts and use them in each thread?

### ISSUE THREAD

**Issue by tencho0221** [warmcat/libwebsockets#2366]
Hi. I'm thinking of creating and managing context in each thread and manage context in each thread
Are there any precautions in that case?

**Comment by lws-team** [comment]
It's not recommended, it did not used to work properly initializing openssl multiple times in the same process, but more recent openssl have fixed it.

You can't share streams on a single h2 connection across contexts.

It's better to just not have multiple threads and do everything in one context.  If you can't, it is possible to have n contexts.

**Comment by tencho0221** [comment]
Thank you.
I writed add question.

> It's not recommended, it did not used to work properly initializing openssl multiple times in the same process, but more recent openssl have fixed it.

・What is the FIX version
・The version of libwebsocket I'm using is 3.2.3

**Comment by lws-team** [comment]
For lws 3.2 is recent enough.

It looks like Opensssl 1.0.1 added reference-counting to the library init stuff.  But it's best to use the latest version of everything anyway.

**Comment by tencho0221** [comment]
Do I need any special build options or implementations for multithreading?
