### ISSUE TITLE
LNK2019 on Windows MSVC, LWS v4.2.1 with threadpools on

### ISSUE THREAD

**Issue by jdelapla** [warmcat/libwebsockets#2368]
Hello,
I recently cloned the main branch and made a 1 line change in CMakelists.txt to enable threadpools.
https://github.com/warmcat/libwebsockets/blob/main/CMakeLists.txt#L115 to 'ON'

  FAILED: bin/websockets.dll lib/websockets.lib 
  cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" 

...

lib\CMakeFiles\websockets_shared.dir/manifest.res" failed (exit code 1120) with the following output:
     Creating library lib\websockets.lib and object lib\websockets.exp
C:\Users\James\source\repos\libwebsockets\out\build\x64-Debug\close.c.obj : error LNK2019: unresolved external symbol lws_threadpool_wsi_closing referenced in function __lws_close_free_wsi
C:\Users\James\source\repos\libwebsockets\out\build\x64-Debug\ops-pipe.c.obj : error LNK2019: unresolved external symbol lws_threadpool_tsi_context referenced in function rops_handle_POLLIN_pipe
C:\Users\James\source\repos\libwebsockets\out\build\x64-Debug\bin\websockets.dll : fatal error LNK1120: 2 unresolved externals
  [173/179] Linking C executable bin\libwebsockets-test-server.exe
  FAILED: bin/libwebsockets-test-server.exe 
  
I am unsure if I have enabled threadpools incorrectly.
Repeating title, I'm on Windows 10 with Microsoft Visual Studio 2019.
Your help would be greatly appreciated.

**Comment by lws-team** [comment]
If you want to use threadpool, it definitely works on Windows since the Sai CI uses it.

The problem is going to be about arranging for pthreads on your system

See in here about how to do that on Windows

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md

**Comment by jdelapla** [comment]
Thank you for your quick reply. I'll look into the guide you provided.
