### ISSUE TITLE
lws_callback_on_writable() not hitting LWS_CALLBACK_CLIENT_WRITEABLE call back

### ISSUE THREAD

**Issue by rajendra-adimulam** [warmcat/libwebsockets#2374]
Hi, I do a client server program using lib websockets (version 2.4.2)
when I continuously want to send data out over websocket, I keep on calling lws_callback_on_writable(),
and wait for LWS_CALLBACK_CLIENT_WRITEABLE to hit. What I observe is some times, the WRITEABLE call back is missing,
and I am lossing of sending out data. My question is that does lws_callback_on_writable() should always corresponds to a CALLBACK? Is that we need to make a retry to lws_callback_on_writable() if we miss the WRITEABLE call back?

**Comment by lws-team** [comment]
> version 2.4.2

This is very old... only the last stable release (v4.2) and main are supported with bugfixes.

> What I observe is some times, the WRITEABLE call back is missing,
> My question is that does lws_callback_on_writable() should always corresponds to a CALLBACK?

The basic deal is:

a) You might get WRITEABLE when you didn't ask for it, and...

b) If you call callback_on_writeable() more than once before you actually get a WRITEABLE, **it does not keep count**, when it gives you a WRITEABLE it will not do any more until you ask again no matter how many times you asked before.  It's setting a bit when you ask, clearing it when it does the WRITEABLE, not keeping a count.

For these reasons you want a pattern where in the WRITEABLE, you look to see what you want to write, and if something to do, write it.  If there is more you see you want to write, you can call lws_callback_on_writable() from there and you'll come back.  You can also call it from other places, but the point is when you actually got the WRITEABLE it will do the right thing there.

**Comment by rajendra-adimulam** [comment]
Thankyou team,
Can you also please clarify me on the below
1. If I assume that a call to lws_callback_on_writable() must invoke LWS_CALLBACK_CLIENT_WRITEABLE, and I use a semaphore between these, is there a chance that i run into a deadlock (missing CALLBACK for WRITEABLE)?

2. What if I do retry the lws_callback_on_writable() until i recieve the LWS_CALLBACK_CLIENT_WRITEABLE, Are there any consequences with this approach? From your comment, I believe there is no harm, can you please confirm?

**Comment by lws-team** [comment]
>  I use a semaphore between these

If you mean semaphore in the synchronization object sense, no, they do not have that kind of relationship.  Inbetween asking for and getting WRITEABLE, you are exposed to the whole set of lifecycle issues for a tcp socket, the peer or even your side's tls library can decide to kill the connection at any time with no interest whatsoever in if you have been waiting to send.  One side may silently disconnect and sit a long time (eg, cat pulls their ethernet cable out).  The interval between asking and maybe getting conceals all the vagaries of network programming that may derail it.

If something goes wrong, lws will eventually make sure you get the related CLOSE callback if the connection proceeded far enough to be established.  But that might take minutes depending on your setup.

> What if I do retry the lws_callback_on_writable()

If you call it n times, it doesn't hurt anything.  But it has not lost your request, unless there's a bug somewhere, it will be waiting for some reason.

You know lws is not threadsafe, right?

**Comment by lws-team** [comment]
> You know lws is not threadsafe, right?

You might be interested in this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md?h=main
