### ISSUE TITLE
Messaging sequence at the client is going out of order at the server

### ISSUE THREAD

**Issue by rajendra-adimulam** [warmcat/libwebsockets#2375]
I observe that some of buffered messages sent over websockets periodically with a 1 second gap
were reaching the server out of order (missing the sequence)
I captured the sequence of messages at the client, but at the server, I do see a change of order.
The issue is not consistent, but quite often, it is observed. Is there a known bug or do we have a work around to see the correct sequence at both ends?
libwebsockets is version 2.4.2 and I follow below approach for writing
1. lws_callback_on_writable()
2. In LWS_CALLBACK_CILENT_WRITEABLE
    lws_write(LWS_WRITE_BINARY)

Thanks In Advance

**Comment by lws-team** [comment]
> were reaching the server out of order (missing the sequence)

This will be a bug on your side, ws goes over tcp and cannot lose things especially when it is in a tls tunnel.
