### ISSUE TITLE
How to parse json with schema correctly?

### ISSUE THREAD

**Issue by youmych** [warmcat/libwebsockets#2380]
I'm trying to parse a simple json using `lejp` and `lws_struct_map_t`. 
```json
{ 
   "schema": "com.google.test.schema", 
   "endpoints": { 
        "ws": { 
            "url": "https://example.net:12345/uplink_ws?a=b" 
        }, 
        "basic": {
            "url": "https://example.net/uplink?c=d" 
        } 
    } 
}
```
The source is there https://github.com/youmych/lws-test/blob/main/src/json-parser.c

The `lejp_parse()` call didn't returned an error, but the "endpoints" subobject is empty (NULL). I didn't understand why. I watched in the debugger that the parser handler copies all of three values to somewhere, but the result "endpoints" struct was NULL.

When I'm parsing only the "endpoints" object, I have both subobjects (ws.url and basic.url) parsed. 

I'm thinking I have incorrect meta information, but didn't find any documentation about it. Could you help?

**Comment by lws-team** [comment]
First thanks for the reproducing code which is in good shape.

One missing bit is LLL_INFO loglevel enabling, this reduces the confusion slightly and shows it allocating the subobjects.

There's a few lines missing in lws for CHILD_PTR handling like this, I pushed it on main

https://libwebsockets.org/git/libwebsockets/commit?id=6ecfb41ef87c28e40ac41dcb35407f0f7c2f8b8c

```
diff --git a/lib/misc/lws-struct-lejp.c b/lib/misc/lws-struct-lejp.c
index 081b0cef52..9efa803863 100644
--- a/lib/misc/lws-struct-lejp.c
+++ b/lib/misc/lws-struct-lejp.c
@@ -270,12 +270,21 @@ lws_struct_default_lejp_cb(struct lejp_ctx *ctx, char reason)
 		lwsl_info("%s: created '%s' object size %d\n", __func__,
 				pmap->colname, (int)pmap->aux);
 
-		if (pmap->type == LSMT_LIST) {
+		switch (pmap->type) {
+		case LSMT_LIST:
 			list = (struct lws_dll2 *)
 				 ((char *)ctx->pst[ctx->pst_sp].user +
 				 pmap->ofs_clist);
 
 			lws_dll2_add_tail(list, owner);
+			break;
+		case LSMT_CHILD_PTR:
+			lwsl_notice("pmap->ofs %d\n", (int)pmap->ofs);
+			*((void **)owner) = ctx->pst[ctx->pst_sp].user;
+			break;
+		default:
+			assert(0);
+			break;
 		}
 	}

```

...please give that a try.

**Comment by youmych** [comment]
Thank you for the fast reply. I'd added the patch and my example works correctly. Thank you!

**Comment by youmych** [comment]
Could you add the patch to 4.2 branch?
