### ISSUE TITLE
How to read a custom ws close reason sent from server?

### ISSUE THREAD

**Issue by veraconst** [warmcat/libwebsockets#2381]
Can you please help me with some information on how to read close_reason on the client side when connection is closed by server with a custom error code?
The client and the server are able to establish a connection, client sends server some identification information and server will close connection because some conditions are not met (this is expected behavior). Server closes connection with a custom defined error code (it should be 3008 for this example), but I can't seem to find a way to read it on the client side. The only thing I receive on the client side is this, where  _in_ is null and _len_ is zero :
```
static int websocket_event(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
switch (reason):
     case LWS_CALLBACK_WSI_DESTROY:
```

Server is implemented in ruby and according to the logs it does properly close the websocket and send the error code.

Thank you!

**Comment by lws-team** [comment]
You should be informed by one of these

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n436-444
