### ISSUE TITLE
How to build for iOS 

### ISSUE THREAD

**Issue by zgbilltalent** [warmcat/libwebsockets#2382]
1:I want to use libwebsokcets in my iOS app;
2:How to compile it with cmake ?
Thks

**Comment by zgbilltalent** [comment]
> 1:I want to use libwebsokcets in my iOS app;
> 2:How to compile it with cmake ?
> Thks

how copile then produce the llibwebsockets.a?

**Comment by lws-team** [comment]
lws CI tests iOS cross-build, eg

https://libwebsockets.org/sai/index.html?task=7900e4eb39cae1ee7e6451ef4e399f2c3db0d5b94ca54381abe1cd33654d0f3e

```
cmake .. -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_IOS_DEVELOPER_ROOT=/opt/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer -DCMAKE_TOOLCHAIN_FILE=contrib/iOS.cmake -DIOS_PLATFORM=OS -DLWS_WITH_SSL=OFF
```

it doesn't cover tls because you'll have to cross build openssl or mbedtls separately.  I don't actually have an iOS device so I didn't bother doing that for CI.

**Comment by zgbilltalent** [comment]
OK , thks 
 -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_IOS_DEVELOPER_ROOT=/opt/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer -DCMAKE_TOOLCHAIN_FILE=contrib/iOS.cmake -DIOS_PLATFORM=OS -DLWS_WITH_SSL=OFF
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CMake Error:
  The detected version of Ninja (GNU Make 3.81

  Copyright (C) 2006 Free Software Foundation, Inc.

  This is free software; see the source for copying conditions.

  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A

  PARTICULAR PURPOSE.

  

  This program built for i386-apple-darwin11.3.0) is less than the version of
  Ninja required by CMake (1.3).
  
Is there any problem of  cmke .. -DCMAKE_MAKE_PROGRAM=/usr/bin/make

**Comment by lws-team** [comment]
Dunno, none of that is related to lws.  What's shown works fine in CI here on a Mac Mini Intel.  That setup doesn't use Ninja but makefiles.

It looks like your CMake thinks it is using nija generator, you can try remove the -DCMAKE_MAKE_PROGRAM... part to go with that and see what happens.

**Comment by zgbilltalent** [comment]
Thank you very much
