### ISSUE TITLE
How to use custom event-lib when use lws as client?

### ISSUE THREAD

**Issue by renzibei** [warmcat/libwebsockets#2383]
Hi, thanks for the great work of lws. I find that the support for custom event-lib is added recently. That is a very cool feature. However I went into some problems when I wanted to use lws as a client.
My question is, after the client (this side) tries to create a connection via `lws_client_connect_via_info` , do I have to manually add this event of this connection into the event loop? For example, use the fd of this connection to register the callback for its read and write events into  the event loop. Or, does the lws automatically adds the event to the event loop in  `lws_client_connect_via_info`?
But I cannot find any operations in `lws_event_loop_ops` struct that is used for client. This struct only contains ops that designed for the server side like `sock_accept`.

Thanks!

**Comment by lws-team** [comment]
> do I have to manually add this event of this connection into the event loop?

No, the event lib ops get called during client creation to handle that.

Check that you are passing your client lws_protocols list into the context creation, like

```
	info.protocols = protocols;
```

otherwise, it will default to the built-in `http-only` protocol and discard your http data.

**Comment by lws-team** [comment]
There's a patch here adding a working client connection to the minimal example

https://libwebsockets.org/git/libwebsockets/commit?id=80dc9663c0d780eeb8475d80bc2a5f5b5f1ad2ce

**Comment by renzibei** [comment]
Thanks for your explanation! There is one place I'm still not clear about. What ops in `lws_event_loop_ops` will add the event to event loop when call `lws_client_connect_via_info`? In other words, what ops in `lws_event_loop_ops` must be implemented in order to support the adding of client connections?

The `lws_event_loop_ops` struct is
```c
struct lws_event_loop_ops {
	const char *name;
	/* event loop-specific context init during context creation */
	int (*init_context)(struct lws_context *context,
			    const struct lws_context_creation_info *info);
	/* called during lws_destroy_context */
	int (*destroy_context1)(struct lws_context *context);
	/* called during lws_destroy_context2 */
	int (*destroy_context2)(struct lws_context *context);
	/* init vhost listening wsi */
	int (*init_vhost_listen_wsi)(struct lws *wsi);
	/* init the event loop for a pt */
	int (*init_pt)(struct lws_context *context, void *_loop, int tsi);
	/* called at end of first phase of close_free_wsi()  */
	int (*wsi_logical_close)(struct lws *wsi);
	/* return nonzero if client connect not allowed  */
	int (*check_client_connect_ok)(struct lws *wsi);
	/* close handle manually  */
	void (*close_handle_manually)(struct lws *wsi);
	/* event loop accept processing  */
	int (*sock_accept)(struct lws *wsi);
	/* control wsi active events  */
	void (*io)(struct lws *wsi, unsigned int flags);
	/* run the event loop for a pt */
	void (*run_pt)(struct lws_context *context, int tsi);
	/* called before pt is destroyed */
	void (*destroy_pt)(struct lws_context *context, int tsi);
	/* called just before wsi is freed  */
	void (*destroy_wsi)(struct lws *wsi);
	/* return nonzero if caller thread is not loop service thread  */
	int (*foreign_thread)(struct lws_context *context, int tsi);

	uint8_t	flags;

	uint16_t	evlib_size_ctx;
	uint16_t	evlib_size_pt;
	uint16_t	evlib_size_vh;
	uint16_t	evlib_size_wsi;
};
```

**Comment by lws-team** [comment]
> What ops in lws_event_loop_ops will add the event to event loop when calling lws_client_connect_via_info? In other words, what ops in lws_event_loop_ops must be implemented in order to support the adding of client connections?

Nothing extra to the set in the minimal example originally for server.

If you try the patch adding client operations, you can satisfy yourself of that.

Despite the name `sock_accept()` does the same work for client and server, eg

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect3.c#n374-381

**Comment by renzibei** [comment]
Your words helped a lot! Thank you.
