### ISSUE TITLE
version  4.2 stable something wrong

### ISSUE THREAD

**Issue by zgbilltalent** [warmcat/libwebsockets#2384]
hello, when I update the version of libwebsockets,  lws_client_connect_via_info( &conn_info ); faile,  Can you tell me the difference of the newer version ?

**Comment by zgbilltalent** [comment]
E: lws_client_connect_via_info: lws not configured for tls

**Comment by zgbilltalent** [comment]
: LWS: 4.2.1-unknown, loglevel 1031
[0m[35;1m[2021/08/17 11:08:41:0148] N: NET CLI SRV H1 H2 WS ConMon IPv6-absent
[0m[35;1m[2021/08/17 11:08:41:0159] N:  ++ [wsi|0|pipe] (1)
[0m[35;1m[2021/08/17 11:08:41:0160] N:  ++ [vh|0|default||-1] (1)

**Comment by lws-team** [comment]
>  lws not configured for tls

As I mentioned in the other bug, the CI build for iOS doesn't build mbedtls or openssl, and turns off tls support.

If you want to use tls (you should) then you must build mbedtls or openssl, configure lws to use it (ie, ` -DLWS_WITH_SSL=1`) and if it's not installed in a cross-root where cmake can find it, tell lws where to find the tls library includes and libs.

**Comment by zgbilltalent** [comment]
Ok thank y

**Comment by zgbilltalent** [comment]
Andy ,the version of openssl match libwebsocket ?

**Comment by lws-team** [comment]
Lws supports a bunch of openssl versions from 1.02 up... you should use latest 1.1.1 if you have a choice.

During cmake, he checks what apis are available in the openssl you are giving him, and adapts accordingly.

But since you cross-build, you probably have to tell lws where to find your cross-built openssl, using something like this when you build lws

```
-DLWS_OPENSSL_INCLUDE_DIRS=mydir/openssl/include '-DLWS_OPENSSL_LIBRARIES=mydir/openssl/lib/libssl.dylib;mydir/openssl/lib/libcrypto.dylib'
```

`mydir/openssl` is just an example, you need to change to where you built your openssl.

**Comment by zgbilltalent** [comment]
OK ,
the file of libssl.dylib , Can I use libssl.a instand ?

**Comment by lws-team** [comment]
Should be able to.

**Comment by zgbilltalent** [comment]
OpenSSL executable: OPENSSL_EXECUTABLE-NOTFOUND 
the path of the file no prob,
![image](https://user-images.githubusercontent.com/5159607/129698154-85d5350a-87ff-4db5-a8bd-4542d2d2b8b2.png)
![image](https://user-images.githubusercontent.com/5159607/129698254-8a680362-b406-48cc-b492-4419a880b012.png)
What's the error ?

**Comment by zgbilltalent** [comment]
![image](https://user-images.githubusercontent.com/5159607/129698654-ead3b2bc-2d62-428f-8cf7-388fa6b9997b.png)

**Comment by lws-team** [comment]
OpenSSL executable means the openssl application, it's used by cmake for creating the test certificates.

It's unrelated and not a fatal error.

Does this thing exist at `/Users/fei/libwebstable/openssl/include/openssl/ssl.h` ?

**Comment by zgbilltalent** [comment]
Oh , exist

**Comment by lws-team** [comment]
Check it exists at the exact path `/Users/fei/libwebstable/openssl/include/openssl/ssl.h`, if it seems to, check the compiler commandline with

```
$ make VERBOSE=1
```

it should have `-I` listing the include path `/Users/fei/libwebstable/openssl/include`.

**Comment by zgbilltalent** [comment]
/Users/fei/libwebstable/libwebsockets/include/libwebsockets/lws-genhash.h:85:18: error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;

**Comment by zgbilltalent** [comment]
Hi Andy 
when I run make -j  
the error above ,Is anything wrong?

**Comment by lws-team** [comment]
As I mentioned cmake will assess your openssl to find out what apis are in it.

It does it by building little test apps using the apis and seeing if they can link or not.

If they give errors on link, it thinks you do not have the api in your openssl.

But there are many reasons it might not link.

You need to look at CMakeFiles/CMakeError.log in your build dir and search for `HMAC_CTX_new`, paste the section with the build and errors.

**Comment by zgbilltalent** [comment]
When I run "make VERBOSE=1" the error is 

In file included from /Users/fei/libwebstable/libwebsockets/include/libwebsockets.h:642:
/Users/fei/libwebstable/libwebsockets/include/libwebsockets/lws-genhash.h:85:18: error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/Users/fei/libwebstable/openssl/include/openssl/ossl_typ.h:102:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
1 error generated.
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o] Error 1
make[1]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
m

**Comment by lws-team** [comment]
No...

>> You need to look at CMakeFiles/CMakeError.log in your build dir and search for HMAC_CTX_new, paste the section with the build and errors.

**Comment by zgbilltalent** [comment]
Determining if the function HMAC_CTX_new exists failed with the following output:
Change Dir: /Users/fei/libwebstable/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_563f4/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_563f4.dir/build.make CMakeFiles/cmTC_563f4.dir/build
Building C object CMakeFiles/cmTC_563f4.dir/CheckFunctionExists.c.o
/usr/bin/clang -DKEYWORD=__inline -I/Users/fei/libwebstable/openssl-1.1.1k/include -Wall -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers -fembed-bitcode  -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -o CMakeFiles/cmTC_563f4.dir/CheckFunctionExists.c.o -c /Applications/CMake.app/Contents/share/cmake-3.19/Modules/CheckFunctionExists.c
Linking C executable cmTC_563f4
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_563f4.dir/link.txt --verbose=1
/usr/bin/clang -Wall -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers -fembed-bitcode  -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -Wl,-headerpad_max_install_names CMakeFiles/cmTC_563f4.dir/CheckFunctionExists.c.o -o cmTC_563f4 
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
Undefined symbols for architecture arm64:
  "_HMAC_CTX_new", referenced from:
      _main in CheckFunctionExists.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_563f4] Error 1
make: *** [cmTC_563f4/fast] Error 2

**Comment by zgbilltalent** [comment]
2



Determining if the function HMAC_CTX_new exists failed with the following output:
Change Dir: /Users/fei/libwebstable/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_3e5ab/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_3e5ab.dir/build.make CMakeFiles/cmTC_3e5ab.dir/build
Building C object CMakeFiles/cmTC_3e5ab.dir/CheckFunctionExists.c.o
/usr/bin/clang -DKEYWORD=__inline -I/Users/fei/libwebstable/openssl/include -Wall -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers -fembed-bitcode  -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -o CMakeFiles/cmTC_3e5ab.dir/CheckFunctionExists.c.o -c /Applications/CMake.app/Contents/share/cmake-3.19/Modules/CheckFunctionExists.c
Linking C executable cmTC_3e5ab
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3e5ab.dir/link.txt --verbose=1
/usr/bin/clang -Wall -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers -fembed-bitcode  -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -Wl,-headerpad_max_install_names CMakeFiles/cmTC_3e5ab.dir/CheckFunctionExists.c.o -o cmTC_3e5ab  /Users/fei/libwebstable/openssl/lib/libssl.a 
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
Undefined symbols for architecture arm64:
  "_HMAC_CTX_new", referenced from:
      _main in CheckFunctionExists.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_3e5ab] Error 1
make: *** [cmTC_3e5ab/fast] Error 2

**Comment by zgbilltalent** [comment]
Hi Andy I compile again , the error file I paste to to

**Comment by zgbilltalent** [comment]
[CMakeError.log](https://github.com/warmcat/libwebsockets/files/6999556/CMakeError.log)

**Comment by lws-team** [comment]
He doesn't show libcrypto.a

> /Users/fei/libwebstable/openssl/lib/libssl.a

Openssl builds into 2 libs, libssl and libcrypto.  You need to tell lws like

`-DLWS_OPENSSL_LIBRARIES=whatever/libssl.a;whatever/libcrypto.a`

**Comment by zgbilltalent** [comment]
cmake .. -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer  -DCMAKE_TOOLCHAIN_FILE=contrib/iOS.cmake -DIOS_PLATFORM=OS -DLWS_WITH_SSL=ON   -DLWS_OPENSSL_INCLUDE_DIRS=/Users/fei/libwebstable/openssl/include/ -DLWS_OPENSSL_LIBRARIES=/Users/fei/libwebstable/openssl/lib/libssl.a;/Users/fei/libwebstable/openssl/lib/libcrypto.a

**Comment by zgbilltalent** [comment]
OK I check it

**Comment by lws-team** [comment]
Because `;` is a shell delimiter, you must quote it

**Comment by zgbilltalent** [comment]
Does it like this ? 
cmake .. -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer  -DCMAKE_TOOLCHAIN_FILE=contrib/iOS.cmake -DIOS_PLATFORM=OS -DLWS_WITH_SSL=ON   -DLWS_OPENSSL_INCLUDE_DIRS=/Users/fei/libwebstable/openssl/include/   -DLWS_OPENSSL_LIBRARIES=‘/Users/fei/libwebstable/openssl/lib/libssl.a ; /Users/fei/libwebstable/openssl/lib/libcrypto.a’

**Comment by lws-team** [comment]
Not quite

 - no spaces around `;`
 - use apostrophe `'` character around the argument

**Comment by zgbilltalent** [comment]
Thank you very much Andy .

**Comment by zgbilltalent** [comment]
Clean the cmake build then rebuild ,It's ok ^^

**Comment by lws-team** [comment]
Super.
