### ISSUE TITLE
Build error on Windows without SSL

### ISSUE THREAD

**Issue by woodfe** [warmcat/libwebsockets#2385]
Compiler error at lws_plat_vhost_tls_client_ctx_init in  lib\plat\windows\windows-sockets.c
It could be disabled by adding #ifdef LWS_WITH_SSL

The cmake option I used:
    set(LWS_WITH_SHARED OFF CACHE BOOL "" FORCE)
    set(LWS_WITH_STATIC ON CACHE BOOL "" FORCE)
    set(LWS_ROLE_RAW_FILE OFF CACHE BOOL "" FORCE)
    set(LWS_WITH_HTTP2 OFF CACHE BOOL "" FORCE)
    set(LWS_UNIX_SOCK OFF CACHE BOOL "" FORCE)
    set(LWS_WITHOUT_TESTAPPS ON CACHE BOOL "" FORCE)
    set(LWS_WITH_SSL OFF CACHE BOOL "" FORCE)
    set(LWS_WITH_DIR OFF CACHE BOOL "" FORCE)
    set(LWS_WITH_LEJP_CONF OFF CACHE BOOL "" FORCE)

**Comment by lws-team** [comment]
Can you paste the error?

**Comment by woodfe** [comment]
D:\Work\roadtest\new\roadster\workers\build\_deps\libwebsockets-src\lib\plat\windows\windows-sockets.c(251,17): error C2065: “PCCERT_CONTEXT”: 未声明的标识符 [D:\Work\roadtest\new\roadster\workers\build\_deps
\libwebsockets-build\lib\websockets.vcxproj]
D:\Work\roadtest\new\roadster\workers\build\_deps\libwebsockets-src\lib\plat\windows\windows-sockets.c(251,17): error C2146: 语法错误: 缺少“;”(在标识符“pcc”的前面) [D:\Work\roadtest\new\roadster\workers\build\_deps
\libwebsockets-build\lib\websockets.vcxproj]
D:\Work\roadtest\new\roadster\workers\build\_deps\libwebsockets-src\lib\plat\windows\windows-sockets.c(251,21): error C2065: “pcc”: 未声明的标识符 [D:\Work\roadtest\new\roadster\workers\build\_deps\libwebsock
ets-build\lib\websockets.vcxproj]

**Comment by lws-team** [comment]
Does this help?

```
diff --git a/lib/plat/windows/windows-sockets.c b/lib/plat/windows/windows-sockets.c
index bb191caba9..2619fad278 100644
--- a/lib/plat/windows/windows-sockets.c
+++ b/lib/plat/windows/windows-sockets.c
@@ -244,6 +244,8 @@ lws_plat_change_pollfd(struct lws_context *context, struct lws *wsi,
        return 0;
 }
 
+#if defined(LWS_WITH_TLS)
+
 int
 lws_plat_vhost_tls_client_ctx_init(struct lws_vhost *vhost)
 {
@@ -401,6 +403,8 @@ lws_plat_vhost_tls_client_ctx_init(struct lws_vhost *vhost)
        return 0;
 }
 
+#endif
+
 const char *
 lws_plat_inet_ntop(int af, const void *src, char *dst, socklen_t cnt)
 {
```

**Comment by woodfe** [comment]
Yes.
Tested on VC2019 and it compiles without error.

**Comment by lws-team** [comment]
Thanks.  I will add that patch to main and v4.2-stable later.
