### ISSUE TITLE
Unable to use multiple callback mounts and a local FS mount

### ISSUE THREAD

**Issue by TeXniKK** [warmcat/libwebsockets#2387]
I'm trying to create an HTTP web server using this example: https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c

Main requirement for it - it should serve multiple rest endpoints (I'm using LWSMPRO_CALLBACK for this) and a files from local folder. 
HTTP paths for REST endpoints are like:
/endpoint1
/endpoint2

All other files are served from "/" endpoint.
Here are some code snippets:
    defprot = {"defprot", lws_callback_http_dummy, 0, 0, 0, NULL, 0};
    httpProt = {"http", HttpServer::callback, sizeof(this), 0, 0, this, 0};
    pprotocols[0] = &defprot;
    pprotocols[1] = &httpProt;
    pprotocols[2] = NULL;

// Init root 
        lws_http_mount newMount1;
        memset(&newMount1, 0, sizeof(newMount1));
        newMount1.mount_next = NULL;
        newMount1.mountpoint = "/"; //todo
        newMount1.mountpoint_len = 1;
        newMount1.origin = local.c_str();
        newMount1.origin_protocol = LWSMPRO_FILE;
        newMount1.def = "index.html";
        newMount1.protocol = NULL;
        newMount1.cgienv = NULL;
        newMount1.extra_mimetypes = &extra_mime;
        newMount1.interpret = NULL;
        newMount1.cgi_timeout = 0;
        newMount1.cache_max_age = 0;
        newMount1.auth_mask = 0;
        newMount1.cache_reusable = 0;
        newMount1.cache_revalidate = 0;
        newMount1.cache_intermediaries = 0;
        newMount1.basic_auth_login_file = NULL;

//Init rest 1
lws_http_mount newMount2;
        memset(&newMount2, 0, sizeof(newMount2));
        newMount2.mount_next = &newMount1;
        newMount2.mountpoint = "/endpoint1";
        newMount2.mountpoint_len = 10;
        newMount2.origin = NULL;
        newMount2.origin_protocol = LWSMPRO_CALLBACK;
        newMount2.def = NULL;
        newMount2.protocol = "http";
        newMount2.cgienv = NULL;
        newMount2.extra_mimetypes = NULL;
        newMount2.interpret = NULL;
        newMount2.cgi_timeout = 0;
        newMount2.cache_max_age = 0;
        newMount2.auth_mask = 0;
        newMount2.cache_reusable = 0;
        newMount2.cache_revalidate = 0;
        newMount2.cache_intermediaries = 0;
        newMount2.basic_auth_login_file = NULL;

// Init rest 2
lws_http_mount newMount;
        memset(&newMount, 0, sizeof(newMount));
        newMount.mount_next = &newMount2;
        newMount.mountpoint = "/endpoint2";
        newMount.mountpoint_len = 10;
        newMount.origin = NULL;
        newMount.origin_protocol = LWSMPRO_CALLBACK;
        newMount.def = NULL;
        newMount.protocol = "http";
        newMount.cgienv = NULL;
        newMount.extra_mimetypes = NULL;
        newMount.interpret = NULL;
        newMount.cgi_timeout = 0;
        newMount.cache_max_age = 0;
        newMount.auth_mask = 0;
        newMount.cache_reusable = 0;
        newMount.cache_revalidate = 0;
        newMount.cache_intermediaries = 0;
        newMount.basic_auth_login_file = NULL;

When I try to query any of /endpoint1 or /endpoint2 I'm getting 404 for some reason and HttpServer::callback is not being called.
Is LWS actually designed for such scenario of usage?
Thanks

**Comment by lws-team** [comment]
Yes lws can do those things.

But when I look at the -dynamic example, it nearly does what you want, one dynamic and one file serving mount.

If we back up a bit and just consider the example itself, does that work for you unchanged?

**Comment by TeXniKK** [comment]
Thank you for reply!
After rechecking my code I've found that I was't setting correct pointers to newMount.mountpoint due too std::vector<std::string> usage without calling to vector.reserve() in advance.
