### ISSUE TITLE
A potential bug in minimal-http-server-eventlib-custom regarding implementing deleting events

### ISSUE THREAD

**Issue by renzibei** [warmcat/libwebsockets#2388]
Hi, recently I'm reading the code in minimal-http-server-eventlib-custom. There may be a potential bug regarding the process of deleting events/closing events.

If my understanding is correct, the procedure for lws to close a connection should be like this:
```
custom_poll_run() // let's assume that when iterating the n0-th (iteration variable n=n0) pollfd in pollfds array, the lws decide to close a connection
... lws_service_fd()
...... wsi_logical_close_custom()
......... custom_poll_del_fd() // in this function, the last pollfd in pollfds array is moved to the n0-th position of the array
```

And when the iteration variable n increases by 1  (which is n0+1) in the loop of checking pollfds, the original last pollfd is not checked, because it is in the n0 position of pollfds.

Can Andy or anyone help check if my understanding is correct, or where there is a problem. Thanks!

**Comment by lws-team** [comment]
Yes IIUI you're right... in the lws internal default loop, it takes care of this.

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-service.c#n58-61

... but in the dummy poll loop in that example it doesn't.  However that dummy event loop is a stand-in for some other already-existing event loop, it wouldn't be something people cut-and-pasted itself.  But it is still wrong.

There's a fix here on main

https://libwebsockets.org/git/libwebsockets/commit?id=808bdc3b74f1cde0370f34260921cefc81cd62bb

**Comment by renzibei** [comment]
Thanks for you feedback and fix!
