### ISSUE TITLE
lws_service question

### ISSUE THREAD

**Issue by SelYui** [warmcat/libwebsockets#2389]
Hi,the server sends messages every 40ms, these messages are divided into several small ones, which are sent within 1 ms, as I understood from the work of lws _service (), several messages are processed in one call to lws _service (), because the number of passes through lws _service () I have < the number of hits in the callback function, the question is:
1) did I understand correctly how lws _service () works
2) is there some kind of flag so that information about each small message is not cut in the callback and everything can be processed in a large chunk?
that many messages overload traffic.

**Comment by lws-team** [comment]
lws_service() is just a thing for the default lws loop, it is not used when you use some other event library.

Generally, lws does not want to hold on to anything itself, it will hand over any incoming rx immediately to the user code as it comes in.

That's what you want if you are on a constrained device, or, eg, you are streaming audio or video at low latency.  It's expensive to allocate potentially huge linear heap buffers for every message and wait until you have it all before processing them.

If you are talking about ws protocol, there are apis so you can understand if a particular piece is the start, middle, or end of a message.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-state.h
