### ISSUE TITLE
How to iterate custom headers?

### ISSUE THREAD

**Issue by astone2014** [warmcat/libwebsockets#2391]
How do I iterate over all custom headers? Or even iterate all headers (custom or not).

I see it's fairly simple to extract custom headers
```c
lws_hdr_custom_length(wsi, "dnt:", 4);
```

But how do I iterate custom headers **if I don't know their name ahead of time**?

I'm trying to use LWS dynamically so that users can create webservers that serve and respond to any sort of custom protocol.

It seems like `lws_hdr_custom_length` is itterating to find the name in question. Is it possilbe to callback for each or to create some list?
```c
	ll = wsi->http.ah->unk_ll_head;
	while (ll) {
		if (ll >= wsi->http.ah->data_length)
			return -1;
		if (nlen == lws_ser_ru16be(
			(uint8_t *)&wsi->http.ah->data[ll + UHO_NLEN]) &&
		    !strncmp(name, &wsi->http.ah->data[ll + UHO_NAME], (unsigned int)nlen)) {
			n = lws_ser_ru16be(
				(uint8_t *)&wsi->http.ah->data[ll + UHO_VLEN]);
			if (n + 1 > len)
				return -1;
			strncpy(dst, &wsi->http.ah->data[ll + UHO_NAME + (unsigned int)nlen], (unsigned int)n);
			dst[n] = '\0';

			return n;
		}
		ll = lws_ser_ru32be((uint8_t *)&wsi->http.ah->data[ll + UHO_LL]);
	}
```

I tried to do this myself but it seems like everything I need access to is private in user context.

**Comment by astone2014** [comment]
```0x0000026228743404  00 07 00 01 00 00 00 24 76 61 6c 75 65 31 3a 31  .......$value1:1
0x0000026228743414  00 07 00 01 00 00 00 34 76 61 6c 75 65 32 3a 32  .......4value2:2
0x0000026228743424  00 07 00 01 00 00 00 00 76 61 6c 75 65 33 3a 33  ........value3:3
0x0000026228743434  50 6f 73 74 6d 61 6e 52 75 6e 74 69 6d 65 2f 37  PostmanRuntime/7
0x0000026228743444  2e 32 38 2e 33 00 2a 2f 2a 00 6c 6f 63 61 6c 68  .28.3.*/*.localh
0x0000026228743454  6f 73 74 3a 37 36 38 31 00 67 7a 69 70 2c 20 64  ost:7681.gzip, d
0x0000026228743464  65 66 6c 61 74 65 2c 20 62 72 00 6b 65 65 70 2d  eflate, br.keep-
0x0000026228743474  61 6c 69 76 65 00 00 00 00 00 00 00 00 00 0d 0a  alive...........
```
I can see the headers are there.
`value1:1`
`value2:2`
`value3:3`

I just need to extract them.

**Comment by astone2014** [comment]
So I was able to parse the individual custom headers and print them. Does something like this exist? Can we add it?

```c
#if defined(LWS_WITH_CUSTOM_HEADERS)
int lws_hdr_custom_foreach(struct lws *wsi, const char *name, int nlen) {
	ah_data_idx_t ll;

	if (!wsi->http.ah || wsi->mux_substream)
		return -1;

	ll = wsi->http.ah->unk_ll_head;
	while (ll) {
		if (ll >= wsi->http.ah->data_length)
			return -1;
		int name_length = lws_ser_ru16be((uint8_t *)&wsi->http.ah->data[ll + UHO_NLEN]);
		int value_length = lws_ser_ru16be((uint8_t *)&wsi->http.ah->data[ll + UHO_VLEN]);
		char name[256];
		char value[256];
		strncpy(&name, &wsi->http.ah->data[ll + UHO_NAME], name_length);
		name[name_length] = '\0';
		strncpy(&value, &wsi->http.ah->data[ll + UHO_NAME] + name_length, value_length);
		value[value_length] = '\0';
		printf("name[%d]: %s, value[%d]: %s\n", name_length, name, value_length, value);
		ll = lws_ser_ru32be((uint8_t *)&wsi->http.ah->data[ll + UHO_LL]);
	}

	return -1;
}
#endif
```

**Comment by lws-team** [comment]
Can I suggest a simpler way is just iterate any custom header names that are present?

`lws_hdr_custom_copy()` already has the machinery to provide the contents if you know the custom name.

**Comment by astone2014** [comment]
I don't always know the custom header name ahead of time.

You can iterate query params(uri args), why not headers, what about duplicate headers?

```c
n = 0;
while (lws_hdr_copy_fragment(wsi, buf, sizeof(buf),
                    WSI_TOKEN_HTTP_URI_ARGS, n) > 0) {
    lwsl_notice("URI Arg %d: %s\n", ++n, buf);
}
````

What if I wanted to simply log the full http request? The header information is very valuable.

I see why you did it this way. Why would I NEED a header that I don't even know exists?
We have users registering their own custom endpoints that may use any custom headers/query params/body etc.
Of course the user does define this ahead of time, they could simply provide the list of headers they expect.
Still, what if they are just testing and want to simply see what the client sent?

**Comment by lws-team** [comment]
> I don't always know the custom header name ahead of time.

Yes, I understood.  What I mean is a new api like you proposed, but that just iterates the custom names.

Then he calls that, and inside the user code for each iteration, he then does "always know the custom header names"... the iterator is giving them to him one by one.

If he knows what names are in there, he can use the existing api `lws_hdr_custom_copy()` to get the value (without introducing length limits).

Duplicate headers are defined to append, should take care of that already.

**Comment by lws-team** [comment]
Thanks for the patch, it's on main.
