### ISSUE TITLE
Observing a delay in receiving LWS_CALLBACK_CLIENT_WRITEABLE

### ISSUE THREAD

**Issue by rajendra-adimulam** [warmcat/libwebsockets#2392]
Hi, 
At the client side, after I make the call to lws_callback_on_writable(), 
I am observing a delay in receiving LWS_CALLBACK_CLIENT_WRITEABLE call back.
(This is happening a few minutes after the websocket is idel)
btw, the delay is in seconds(~5-10) and I use lws_service( context, /* timeout_ms = */ 1000 );

If I try sending a request from server, then I was able to overcome from this behavior on the client,
Since I use a queueing logic for reliability, I was able to send all the buffered messages (call back receives instantly this time for multiple messages)

I was using libwebsockets 3.2.0
Can you please suggest if there is a way to not make the websocket send part go idle like this

Thankyou
Prasad

**Comment by lws-team** [comment]
a) does this problem exist on a minimal example (ie, without your code?) so I can reproduce it?

b) does the problem exist on lws main?

c) are there logs for what happens during this gap?

**Comment by lws-team** [comment]
... and...

d) you know lws is not threadsafe, right?

**Comment by rajendra-adimulam** [comment]
> a) does this problem exist on a minimal example (ie, without your code?) so I can reproduce it?
>  I have not integrated the exact minimal example into my code base, but mostly the sameway
     I create websocket using lws_client_connect_via_info()
> b) does the problem exist on lws main?
>   Did not tested
> c) are there logs for what happens during this gap?
   Nothing is happening in the gap, neither I recieve any lws call back nor any client-server message exchange
   based on a timer, we try to send a becaon signal to the server periodically, and this is where I see the delay in receiving 
   writeable call back. Initially I do not see an issue, but after a few minutes, seeing this

**Comment by lws-team** [comment]
Assuming no threads involved, you should try lws main and if still broken, hack a minimal example to show the problem and I'll be happy to look at it (on main).

**Comment by rajendra-adimulam** [comment]
> ... and...
> 
> d) you know lws is not threadsafe, right?

Yes, I am aware of it, but I make sure the lws API surrounded by mutex locks
I doubt the thread that tries to request a writeable callback, is not always the same, does it create an issue here?

**Comment by lws-team** [comment]
> Yes, I am aware of it, but I make sure the lws API surrounded by mutex locks

Lws is not threadsafe, sticking mutexes on your threads so they don't do The Forbidden more than one at a time doesn't change anything.

Don't call lws apis from other threads!  On main, there is a detector for that now which will assert() if we get users that don't understand "not threadsafe".

Have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md
