### ISSUE TITLE
Doesn't work on some Windows

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#2396]
Hello,  LWS-4.2.1 does not work on **some** Windows, however 4.0.16 is ok.

I captured in the log: Unable to connect

That `lws_client_connect_info.address` only configures an IP address, not a domain name.

More LWS uses are as follows:

https://github.com/warmcat/libwebsockets/issues/2176#issuecomment-907566069

**Comment by lws-team** [comment]
Can you paste the log?  What's the ipv6 situation?

**Comment by lws-team** [comment]
... and ASYNC_DNS situation...

**Comment by caobug** [comment]
Hello, I only log the error level. The IP address is IPV4, and ASYNC_DNS is not configured.

I need to republish the software to my friend’s computer for specific error messages.

**Comment by lws-team** [comment]
Yes need better logs.  It's also interesting if LWS_IPV6 enabled at cmake.

**Comment by caobug** [comment]
1.1.1.1 is a fake IP
```
[2021-08-30 22:57:40] D __lws_vhost_unbind_wsi: vh default: count_bound_wsi 1
[2021-08-30 22:57:40] D __lws_free_wsi: [wsicli|34|WS/h1/1.1.1.1], tsi fds count 2
[2021-08-30 22:57:40] D  -- [wsicli|34|WS/h1/1.1.1.1] (1) 33.983ms
[2021-08-30 22:57:40] D _lws_change_pollfd: [wsicli|35|WS/h1/1.1.1.1]: fd 4448 events 784 -> 768
[2021-08-30 22:57:40] D elops_io_uv: [wsicli|35|WS/h1/1.1.1.1]: 10
[2021-08-30 22:57:40] D lws_client_connect_check: connect check take as FAILED: errno 10014
[2021-08-30 22:57:40] D lws_client_connect_3_connect: getsockopt check: conn fail: errno 10014
[2021-08-30 22:57:40] D elops_io_uv: [wsicli|35|WS/h1/1.1.1.1]: -2147483637
[2021-08-30 22:57:40] E Unable to connect
```

**Comment by caobug** [comment]
After I delete the connect related code, it can work normally. I don’t know what your consideration is to not use SO_ERROR on Windows?

```
static lcccr_t
lws_client_connect_check(struct lws *wsi)
{
	int en = 0;
	int e;
	socklen_t sl = sizeof(e);

	(void)en;

	/*
	 * This resets SO_ERROR after reading it.  If there's an error
	 * condition, the connect definitively failed.
	 */

	if (!getsockopt(wsi->desc.sockfd, SOL_SOCKET, SO_ERROR,
			&e, &sl)) {
		en = LWS_ERRNO;
		if (!e) {
			lwsl_debug("%s: getsockopt check: conn OK errno %d\n",
				   __func__, en);

			return LCCCR_CONNECTED;
		}

		lwsl_notice("%s: getsockopt fd %d says err %d\n", __func__,
			   wsi->desc.sockfd, e);
	}

	lwsl_notice("%s: connect check take as FAILED: errno %d\n", __func__, en);

	return LCCCR_FAILED;
}
```

**Comment by lws-team** [comment]
Is it possible the machines that don't like connect(fd, NULL, 0) have something hooking the connect syscall to wrongly filter it?  Like some kind of firewall type thing?  In that case passing "" instead of NULL might satisfy it.

**Comment by lws-team** [comment]
Spring cleaning old issues

**Comment by lws-team** [comment]
This seems to require some very specific circumstances, perhaps the AD thing.  My guess is under those conditions something "hooks" the WSA calls and that new something finds something to object to that the normal WSA flow thinks is fine.  Since you have the symptom you'll need to meddle with it and see what makes your symptom go away.

**Comment by jaumeMA** [comment]
Hi, Thanks for your quick response. After some trial/error tests Ive seen that if in the connect call inside the library i pass as third argument the size of sockaddr type it works ok, just to let you know (in the winsock2 documentatio says something like "This error (10014) is also returned if the sockaddr structure pointed to by the name parameter with a length specified in the namelen parameter is not in a valid part of the user address space. ").

**Comment by lws-team** [comment]
@jaumeMA thanks for the description, I pushed your change on main + v4.3-stable
