### ISSUE TITLE
undefined reference to ....

### ISSUE THREAD

**Issue by FabioDefilippo** [warmcat/libwebsockets#2397]
Hello Guys, how are You?
Could You help me to resolve this my problem?
I am trying to compile with gcc one tool of mines, in which I am using a WebSocket Secure connection, based on the minimal_example in repo. When I use connect_client() connection and lws_log, write and so on, the compiler can not find references.
this is my stderr:

/usr/bin/ld: /tmp/ccNZeJ4G.o: in function `connect_client()':
mytool.cpp:(.text+0xc7): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0xd6): undefined reference to `lws_client_connect_via_info'
/usr/bin/ld: /tmp/ccNZeJ4G.o: in function `callback(lws*, lws_callback_reasons, void*, void*, unsigned long)':
mytool.cpp:(.text+0x1ce): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x20b): undefined reference to `lws_callback_on_writable'
/usr/bin/ld: mytool.cpp:(.text+0x22f): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x251): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x29f): undefined reference to `lws_write'
/usr/bin/ld: mytool.cpp:(.text+0x2c8): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x2de): undefined reference to `lws_get_context'
/usr/bin/ld: mytool.cpp:(.text+0x2f5): undefined reference to `lws_get_random'
/usr/bin/ld: mytool.cpp:(.text+0x368): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x37d): undefined reference to `lws_set_timer_usecs'
/usr/bin/ld: mytool.cpp:(.text+0x38e): undefined reference to `lws_callback_on_writable'
/usr/bin/ld: mytool.cpp:(.text+0x39f): undefined reference to `lws_is_first_fragment'
/usr/bin/ld: mytool.cpp:(.text+0x3ae): undefined reference to `lws_is_final_fragment'
/usr/bin/ld: mytool.cpp:(.text+0x3bd): undefined reference to `lws_remaining_packet_payload'
/usr/bin/ld: mytool.cpp:(.text+0x3f0): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x416): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x448): undefined reference to `lws_callback_http_dummy'
/usr/bin/ld: /tmp/ccNZeJ4G.o: in function `main':
mytool.cpp:(.text+0x57d): undefined reference to `lws_create_context'
/usr/bin/ld: mytool.cpp:(.text+0x5a6): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x5d4): undefined reference to `lws_service'
/usr/bin/ld: mytool.cpp:(.text+0x5ef): undefined reference to `_lws_log'
/usr/bin/ld: mytool.cpp:(.text+0x5fe): undefined reference to `lws_context_destroy'
collect2: error: ld returned 1 exit status

I have tried all I can find resolutions in github and other sites, but I have not found anything about that.
Please, could you help me? thank You

**Comment by lws-team** [comment]
You have to link to libwebsockets.so or libwebsockets.a ...

**Comment by FabioDefilippo** [comment]
I will try it. thank You Sir!
