### ISSUE TITLE
Memory usage growth over time

### ISSUE THREAD

**Issue by nidoro** [warmcat/libwebsockets#2398]
Hello,

I've been using libwebsockets v. 3.0.1 + OpenSSL v. 1.1.1c for about 2 years to host a low traffic website (no ws, just http(s)). Everything works fine, except that the memory consumed by my process keeps growing over time. I've already checked for memory leaks, but didn't find anything. I use a memory pool for all my allocations, so I only call malloc once, at the start of the program. I know that it is normal for processes to consume more and more memory, until they reach a _plateau_, but in my case, I'm running the server in a very cheap VM with only 2GB of RAM with other memory consuming processes running on it as well, so I can't "wait" to see if the memory usage of my server will eventually stabilize.

I would like to ask some guidance on how can I investigate the issue further. What could be causing this memory usage growth? Can I tweek something in my libwebsockets / OpenSSL configuration so I can reduce their memory usage overtime growth? Does libwebsockets / OpenSSL do some kind of caching that could be causing the issue? I saw that more recent versions of the library have a `LWS_SERVER_OPTION_DISABLE_TLS_SESSION_CACHE` options, but I don't know what's the relevance of it.

One last note, I don't know if this is relevant or not, but I set the `pt_serv_buf_size` member of the context creation struct to 64kb to increase the throughput.

Any help is much appreciated! Thanks!

**Comment by lws-team** [comment]
> v. 3.0.1 + OpenSSL v. 1.1.1c

Both of those have many fixes in later versions, you should update them first.

>  I've already checked for memory leaks, but didn't find anything.

There are several allocation domains, not just from user code.  Lws does its own allocations from process heap, but since I develop using valgrind, leaks tend to get noticed and fixed.  Openssl does its own allocations from process heap, but those are driven by how many active connections and should be freed.  Getting a VM number is not very clear evidence of what if anything is actually using that space.

Heap allocators are not simple, their allocation of process memory from the kernel is disconnected from the amount of memory in use, and after some time there are holes.  You can try calling eg, https://man7.org/linux/man-pages/man3/malloc_trim.3.html periodically.  You can call mallinfo2() to find out the extent of the global heap allocations https://man7.org/linux/man-pages/man3/mallinfo.3.html and see if that is actually what is increasing.

**Comment by nidoro** [comment]
I didn't know about these malloc utilities. Thanks to you I believe I have found the cause of the issue, now I'm looking for a way to fix it.

Following your suggestion I tried calling mallinfo before and after making some requests on my website to see what the numbers would be. For my surprise, the struct returned was completely empty, everything was zero. After some investigation, I read somewhere that the [ASAN](https://github.com/google/sanitizers/wiki/AddressSanitizer) sanitizer intercepts mallinfo and returns an empty struct. And I do use ASAN and have been using it for a long time (`-fsanitize=address` compilation flag). It never occurred to me that that could be the reason for the constant memory growth. Then I compiled and ran my server without the option, and voilá, the memory usage was not increasing over time.

Just to make sure that it was not an issue with my server only, I recompiled the libwebsockets test server with the `-fsanitize=address` to see if the memory usage would continually increase as I made requests with my browser. And it did. The test was pretty amateur, I just opened ten browser tabs at `127.0.0.1:7681` and refreshed all of them a bunch of times. When compiled with ASAN, the memory continually increased, and without ASAN, it did not.

Now I know that the problem is related to `-fsanitize=address`, but I don't want to stop using it. Maybe I can disable something in ASAN that is causing this problem? I don't know if you have experience with ASAN, but I thought I would ask anyway.

**Comment by lws-team** [comment]
Same as valgrind, ASAN has to keep allocation tracking tables.  ASAN / valgrind are important parts of the puzzle but typically you don't deploy with them.

I use valgrind during development routinely so I can know about leaks or violations and fix them as I cause them.  Unless there is an issue ASAN can find that valgrind can't, I would suggest it's better to build normally and run under valgrind only when you have to.... and if you see no problems coming when under stress like that, deploy without it.

**Comment by nidoro** [comment]
I use ASAN on deploy not so much for its ability to detect memory related issues, but because of its nice stack trace printing on segmentation fault. That way, when a crash occurs, I can see where in the code it happened. I know there are other lighter ways to do that, such as using the `catchsegv` wrapper or linking with `libSegFault`, but as far as I know these solutions don't show the file name + line number.

Anyway, thanks again!
