### ISSUE TITLE
[feature] per-context log callback

### ISSUE THREAD

**Issue by liberize** [warmcat/libwebsockets#2399]
I run a http server and a websocket server in the same program, currently I can only set a global log callback with `lws_set_log_level`, but I want to separate logs from different services.
Can you provide a pre-context `lws_set_log_level` interface?

**Comment by lws-team** [comment]
This exists on main branch, read from "New logging context apis" here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.logging.md

These can apply log contexts to several kinds of object, context, vhost, ss, and wsi, they can have their own emit and loglevel.  Not everything in lws is migrated to them yet, but most logs are.

**Comment by liberize** [comment]
I tried the new log api, but only very few logs went into my log ctx.
It seems most logs are still process wide.

**Comment by lws-team** [comment]
>> Not everything in lws is migrated to them yet, but most logs are.
> I tried the new log api, but only very few logs went into my log ctx.

Patches welcome if there are specific logs you feel need migrating first.  It's not that difficult to switch them if you have an object like context, vhost, wsi or ss around already.
