### ISSUE TITLE
Why is the memory leak resolved? (Using amazon-kinesis-video-streams-webrtc-sdk-c)

### ISSUE THREAD

**Issue by pipsnh02** [warmcat/libwebsockets#2403]
A memory leak occurred when using amazon-kinesis-video-streams-webrtc-sdk-c.
The cause seemed to be libwebsockets.

You will find the latest information and additional questions about what you asked in [#1194 ](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1194).
Please refer to [#1194](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1194) for the problem and background.

After applying two patches to libWebSockets v3.2.3, the leak disappeared.
① [#2178 patch](https://github.com/warmcat/libwebsockets/commit/ffa0a38a1a721fc1ec96ad21916438846069bd77.patch)
② [#1190](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1190#issuecomment-888499671)
（Only some leaks were solved with ① alone, and all were solved with ① ＋ ②）

I think ① is a leak repair,
②is a patch for the purpose of solving another issue (the case where the connection to the signaling server ends with a timeout error).

I don't understand why the patch ② helps eliminate the leak.
Do you know why?

**Comment by lws-team** [comment]
Does the problem still exist on lws v4.2-stable?

**Comment by lws-team** [comment]
... on the second patch it's difficult to see what it did from your pasted comment, but `getaddrinfo()` behaviour with AF_UNSPEC is platform-dependent.

**Comment by pipsnh02** [comment]
> Does the problem still exist on lws v4.2-stable?

Using libwebsockets = v4.2.1 reduced the amount of leaks but did not eliminate them.

**Comment by lws-team** [comment]
When you say "reduced the amount of leaks", it's the thing about AF_INET left producing them?  Or some other path?

**Comment by lws-team** [comment]
NEEDINFO

**Comment by pipsnh02** [comment]
I don't know if AF_INET left a leak. It is a fact that the leak was resolved by using a patch ②. 
I want to know the theory.
