### ISSUE TITLE
Memory leak after libwebsockets upgrade

### ISSUE THREAD

**Issue by TomasKianica** [warmcat/libwebsockets#2404]
Hello Andy,

I have noticed one (maybe) issue after upgrade to newer version of libwebsockets (using libuv and running on Windows), previous version was 2.4.2 without SSL support and the new one is 4.2.2 with SSL support (1.1.1l).
The issue is: when the websocket connection is lost then my websocket client is destroyed and after some time is created new one that also wants to connect, but I can see that each connect attempt consumes some memory but when the client is destroyed the memory is not freed (see attached picture with memory diagnostic) - 
this can lead (after some time) to **no free memory**. As mentioned before this issue is not reproducible with older libwebsockets version.

![lws_4 2 2](https://user-images.githubusercontent.com/90180575/132182790-cf519918-9d66-480a-a68d-808f1f8d746b.PNG)

Could you please check what is wrong with attached (simplified) code?

[WSClient.txt](https://github.com/warmcat/libwebsockets/files/7114339/WSClient.txt)

Thank you!

BR,
Tomas

**Comment by lws-team** [comment]
Well... just adding some logs in your own code would show what isn't happening.  Or look at lws logs.

1) There's a loop and context per connection... why not just create the loop and the lws_context at init like the examples, and create connections on it?

2) Either peer can close a connection, but you don't handle the CLOSE callback.  You destroy your contexts only if your end closed it.

at any rate I don't think this is anything to do with lws
