### ISSUE TITLE
help make

### ISSUE THREAD

**Issue by fwebcc** [warmcat/libwebsockets#2406]
config.mk
WITH_WEBSOCKETS:=static

 apt-cache policy  libwebsockets-dev
libwebsockets-dev:
  已安装：2.0.3-2
  候选： 2.0.3-2
  版本列表：
 *** 2.0.3-2 500
        500 http://ftp2.cn.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

make

H_UNIX_SOCKETS -DWITH_WEBSOCKETS -DWITH_EPOLL -I../deps -Wall -ggdb -O2 -Wconversion -Wextra -DVERSION="\"2.0.12\"" -DWITH_BROKER -c websockets.c -o websockets.o
websockets.c:44:24: warning: excess elements in struct initializer
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:79:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:44:24: note: (near initialization for ‘protocols[0]’)
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:79:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:44:24: warning: excess elements in struct initializer
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:88:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:44:24: note: (near initialization for ‘protocols[1]’)
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:88:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:44:24: warning: excess elements in struct initializer
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:97:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:44:24: note: (near initialization for ‘protocols[2]’)
 #define WS_TX_BUF_SIZE (WS_SERV_BUF_SIZE*2)
                        ^
websockets.c:97:3: note: in expansion of macro ‘WS_TX_BUF_SIZE’
   WS_TX_BUF_SIZE      /* tx_packet_size v2.3.0 */
   ^~~~~~~~~~~~~~
websockets.c:106:3: warning: excess elements in struct initializer
   0         /* tx_packet_size v2.3.0 */
   ^
websockets.c:106:3: note: (near initialization for ‘protocols[3]’)
websockets.c: In function ‘callback_http’:
websockets.c:606:27: error: ‘LWS_POLLOUT’ undeclared (first use in this function)
     if(pollargs->events & LWS_POLLOUT){
                           ^~~~~~~~~~~
websockets.c:606:27: note: each undeclared identifier is reported only once for each function it appears in
websockets.c:630:27: error: ‘LWS_POLLHUP’ undeclared (first use in this function)
     if(pollargs->events & LWS_POLLHUP){
                           ^~~~~~~~~~~
websockets.c: In function ‘mosq_websockets_init’:
websockets.c:711:33: warning: conversion to ‘short int’ from ‘uint16_t {aka const short unsigned int}’ may change the sign of the result [-Wsign-conversion]
     info.max_http_header_data = conf->websockets_headers_size;
                                 ^~~~
websockets.c:736:6: error: ‘struct lws_context_creation_info’ has no member named ‘pt_serv_buf_size’
  info.pt_serv_buf_size = WS_SERV_BUF_SIZE;

**Comment by lws-team** [comment]
> ‘struct lws_context_creation_info’ has no member named ‘pt_serv_buf_size’
> 2.0.3-2

Your lws is too old.  Remove the debian package (and -dev package) and build from, eg, lws v4.2-stable branch.
