### ISSUE TITLE
observing pipe file descriptor leak with lws 4.2.1/4.2.2

### ISSUE THREAD

**Issue by codingspirit** [warmcat/libwebsockets#2407]
**OS**: Ubuntu 20.04
**libwebsockets version**: 4.2.1
**SSL**: mbedtls
**observed behavoir**:

```c
pLwsContext = lws_create_context(&creationInfo);
lws_context_destroy(pLwsContext);
```
We observed leaked pipe with sample code above:

before `pLwsContext = lws_create_context(&creationInfo);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
```

after `pLwsContext = lws_create_context(&creationInfo);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
lr-x------ 1 xxxx domain^users 64 Sep  8 06:50 3 -> /dev/urandom
lr-x------ 1 xxxx domain^users 64 Sep  8 06:50 4 -> 'pipe:[2529153]'
l-wx------ 1 xxxx domain^users 64 Sep  8 06:50 5 -> 'pipe:[2529153]'
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 6 -> 'socket:[2529154]'
```

after `lws_context_destroy(pLwsContext);`:
```bash
ls -l /proc/${PID}/fd
total 0
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 0 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 1 -> /dev/pts/3
lrwx------ 1 xxxx domain^users 64 Sep  8 06:50 2 -> /dev/pts/3
l-wx------ 1 xxxx domain^users 64 Sep  8 06:50 5 -> 'pipe:[2529153]'
```

This ` 'pipe:[2529153]'` will persist until we terminated the process.

**Comment by lws-team** [comment]
I cannot reproduce this by checking out v4.2.1 and this patch

```
diff --git a/minimal-examples/http-client/minimal-http-client/minimal-http-client.c b/minimal-examples/http-client/minimal-http-client/minimal-http-client.c
index 246b183256..38c3f77b46 100644
--- a/minimal-examples/http-client/minimal-http-client/minimal-http-client.c
+++ b/minimal-examples/http-client/minimal-http-client/minimal-http-client.c
@@ -409,6 +409,8 @@ int main(int argc, const char **argv)
 
 	lws_context_destroy(context);
 
+	sleep(1000);
+
 bail:
 	if ((p = lws_cmdline_option(argc, argv, "--expected-exit")))
 		expected = atoi(p);
```

then run `lws-minimal-http-client` and check proc of the process... it just has the stdin/out/err fds left after the context destroy.

Something more is needed?

**Comment by codingspirit** [comment]
Hi @lws-team , thanks for your quick rely,
but I can reproduce the exactly same issue on `minimal-http-client` if build lws with `DLWS_HAVE_EVENTFD=0`.
In this case, each time call `lws_create_context`, 2 pipe fds will be used. But when we do `lws_context_destroy`, only one pipe will be released...

**Comment by lws-team** [comment]
OK... I can reproduce it with that.

This should solve it

https://libwebsockets.org/git/libwebsockets/commit?id=788481609e8e7d2ae2f46e7a1934955dd02a5085

**Comment by codingspirit** [comment]
> OK... I can reproduce it with that.
> 
> This should solve it
> 
> https://libwebsockets.org/git/libwebsockets/commit?id=788481609e8e7d2ae2f46e7a1934955dd02a5085

Cool! I just verified at my side that `788481609e8e7d2ae2f46e7a1934955dd02a5085` can fix this issue. Should I keep this issue open until this commit was merged into main?

**Comment by lws-team** [comment]
It's also on main... it takes a while to get it to pass CI, since we test on 30 platforms.

It ended up slightly different as

https://libwebsockets.org/git/libwebsockets/commit?id=2a6dc124644f32f05862c8954eefc472613ca2c9

**Comment by lws-team** [comment]
...  if check out v4.3-stable, build it with defaults andI run, eg, `valgrind --track-fds=yes lws-minimal-http-client`, he just reports 

```
FILE DESCRIPTORS: 3 open (3 std) at exit.
```

as I would expect.  What happens for you?

**Comment by tencho0221** [comment]
@lws-team 
I'm using lws with the following SDK.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c

I was able to confirm that the leak was resolved by applying the patch, but the problem of # 2514 occurred.
So, when I applied the patch # 2514, a pipe fd leak occurred.
The version of lws used in the SDK is v4.2.2.

**Comment by lws-team** [comment]
Hm... I don't think there is any pipe leak in v4.3-stable.  So applying the patch just tries to close them twice and is making the problem all by itself.

I think you will get further if you remove the patch and check lws_context_destroy() is getting called by the SDK when expected.

**Comment by tencho0221** [comment]
Sorry. Forget about v4.3-stable.

I've applied the following patch to v4.2.2.
・# 2514
・https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-leak-pipe-fix. patch

My program has multiple threads in the process, and each thread has its own lws context.

The environment in which I am checking for leaks is just repeating the following API in an environment that is not connected to the NW.
1.lws_create_context()
2.lws_context_destroy()

**Comment by lws-team** [comment]
The patch you mentioned seems the same as

https://libwebsockets.org/git/libwebsockets/commit?id=2a6dc124644f32f05862c8954eefc472613ca2c9

which is already on v4.2-stable.  If I check v4.2-stable out and build it and repeat the valgrind test on the minimal example, there is no pipe leak.  If it was broken in lws in a simple way, it would show up like that.  So I guess something else goes on.
