### ISSUE TITLE
stat32i64 can't support path contain special character like 😂，suggest use _wstat32i64 instead.

### ISSUE THREAD

**Issue by 1322579329** [warmcat/libwebsockets#2408]
https://github.com/warmcat/libwebsockets/blob/006d66219864d54ff2ec3aa193e072748ac77c6e/lib/roles/http/server/server.c#L723

**Comment by lws-team** [comment]
Would you like to suggest a patch that deals with any unicode width conversion stuff needed?

**Comment by lws-team** [comment]
Thanks for the patch, it's pushed
