### ISSUE TITLE
HTTP 1.1 support, partial content

### ISSUE THREAD

**Issue by KimT** [warmcat/libwebsockets#241]
Hi,
I want to stream an mp3 file using the HTML5 audio tag on a webpage. The browser (Chrome) makes a HTTP/1.1 GET request containing the range field and connection keep-alive:
GET /binauralaudio.mp3 HTTP/1.1
Host: 172.24.155.22:8200
Connection: keep-alive
Accept-Encoding: identity;q=1, *;q=0
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
Accept: */*
Referer: http://172.24.155.22:8200/surrounddemo.html
Accept-Language: da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4
Range: bytes=0-

The libwebsockets server responds with:
HTTP/1.0 200 
server: libwebsockets
content-type: audio/mpeg3
content-length: 5630080

The browser downloads a big chunk and then plays audio for a while before trying attempting do download the rest of the audio track. In the mean time, the libwebsockets server times out waiting for the client to download the rest of the file. Then when receiving the request from the browser, the transfer starts all over again. So I never get to hear the entire audio track, the HTML5 player stops.

The HTTP 1.1 response should have looked something like this:
HTTP/1.1 206 Partial Content
Date: Fri, 30 Jan 2015 13:31:16 GMT
Server: Apache
Last-Modified: Thu, 29 Jan 2015 08:49:21 GMT
ETag: "c0d22b26-55e880-50dc6906fcf39"
Accept-Ranges: bytes
Content-Length: 5630080
disablevcache: true
Content-Range: bytes 0-5630079/5630080
Connection: close
Content-Type: audio/mpeg

I think it would be fine to split the content-range into smaller chunks instead of transferring the entire file right away (like in the example).

Is there any chance libwebsockets will support HTTP 1.1 soon?

Best Regards,
Kim

**Comment by KimT** [comment]
Is the description of my problem unclear?

Also, I get into problems when transferring big files using http because libwebsockets transfers the entire file before serving other requests. Lets say two users want to download a 1GB file from the server. User 1 opens a browser and downloads a 1GB file and at the same time user 2 opens a browser and starts downloading a 1GB file. Then user 2 has to wait for user 1 to finish downloading because the http server does not respond while downloading. User 2 can still make websocket requests but not HTTP requests while user 1 is downloading. User 1 can't make websocket requests while downloading the 1GB file.

I have run my tests on a modified version of the test-server.c example.
Am I right about the limitations?
Or am I just doing something wrong?

What I want to accomplish:
Live stream audio with very little delay through http (for HTML5 webaudio) and at the same time adjust some settings through a websocket interface.
To ensure the audio stream has little delay, I do not allow the client to buffer ahead more than 0.5 seconds of audio. 
The server must be able to handle 10+ simultaneous users/clients.

**Comment by warmcat** [comment]
It sounds like some interaction with timeout management and your application.  You'd need to cancel or radically extend the timeout after you start sending data.
