### ISSUE TITLE
MQTT over websockets

### ISSUE THREAD

**Issue by oz2mia** [warmcat/libwebsockets#2423]
Got the minimal-mqtt-client example working after client_id, username and password was changed to malloc string,
and not static strings.

But this example "only" use MQTT directly over TCP.
Is there an example where the protocol stack is MQTT/Websockets/TCP ?

Or what need to be changed in the example to add websockets in the connection ?

**Comment by lws-team** [comment]
> Got the minimal-mqtt-client example working after client_id, username and password was changed to malloc string,

... yes a patch on the mqtt stuff broke the example.  There's a fix for client_id non-malloc here

https://libwebsockets.org/git/libwebsockets/commit/minimal-examples?id=ef96857c44c453b3541b45c05109d9d0b0f3918a

it looks like the same thing needs doing to user/pass.

> Is there an example where the protocol stack is MQTT/Websockets/TCP ?

Currently it isn't supported.  As you would expect from "libwebsockets" the pieces are there but they don't have a way at the moment to be wired together.

It's probably not a huge job to add it.

**Comment by lws-team** [comment]
Spring cleaning old issues.
