### ISSUE TITLE
lws_callback_on_writable() call inside glib signal callback has no effect

### ISSUE THREAD

**Issue by AleXoundOS** [warmcat/libwebsockets#2428]
I use libwebsockets in conjunction with gstreamer for WebRTC signalling communication with Janus server. gstreamer's webrtcbin plugin calls user callback functions which are expected to send messages to a signalling server.

If I call `lws_callback_on_writable(wsi)` in the end of glib callback function the libwebsockets callback function **is not** called.

However, if I call `lws_cancel_service(lws_get_context(wsi))` right before `lws_callback_on_writable(wsi)` in the end of glib callback function the libwebsockets callback function **is** called. Is it intended behavior or just an unreliable side effect? It was just a silly experiment by me but it turned out to work despite I don't setup any event loop, but call `lws_service()` in a loop.

**Comment by lws-team** [comment]
This is a bit too esoteric for me to understand what that boils down to from lws perspective.

Somebody must have set up a glib foreign loop for lws_context despite you just 'call lws_service() in a loop'. The question then is everything happening on the same thread?  If so it should just work.  If not, behaviour is going to depend on platform, glib backend wait implementation (epoll, etc), and other thread state, lws can't guarantee anything.  For example, depending on platform if you change wait events while another thread is actually in the wait, changes are lost (OSX) or not observed until you reenter the wait (linux).  It sounds like the latter..

**Comment by lws-team** [comment]
... assuming that's it, the way to handle it is do the lws_cancel_service(), but instead of doing the writeable request as well, set a flag somewhere indicating that's what you need to do, and do that from the LWS_CALLBACK_EVENT_WAIT_CANCELLED callback in the lws thread context.

**Comment by AleXoundOS** [comment]
@lws-team, sorry, the original issue statement is wrong. The libwebsockets callback function **is** called in both cases. However, `lws_cancel_service(lws_get_context(wsi))` causes callback function to be called earlier "in the right time" (before another gstreamer callback that changes application state). Postponing the call resulted in a failure that I misinterpreted as libwebsockets callback not being called.

> The question then is everything happening on the same thread?

No. The `lws_service` loop and glib/gstreamer callbacks run in different threads.
But it is not like I manually create threads - gstreamer issues many threads (~20 in my case) to keep it's pipelines. I write no code that actually runs inside a different thread except the glib/gstreamer callback functions (which I do not call directly).

**Comment by lws-team** [comment]
This is a bit confused... the interval between asking to write and being able to write is openended.  Network and connection conditions control that.

It doesn't matter who made the threads... you can only safely call lws apis from fhe lws service thread.  As I wrote

>> the way to handle it is do the lws_cancel_service(), but instead of doing the writeable request as well, set a flag somewhere indicating that's what you need to do, and do that from the LWS_CALLBACK_EVENT_WAIT_CANCELLED callback in the lws thread context.

**Comment by AleXoundOS** [comment]
> This is a bit confused... the interval between asking to write and being able to write is openended. Network and connection conditions control that.

Maybe `lws_cancel_service()` somehow interrupts gstreamer threads, changes some priorities, affects scheduling overall...

**Comment by AleXoundOS** [comment]
> This is a bit confused... the interval between asking to write and being able to write is openended. Network and connection conditions control that.

Your confusion is correct. The original issue statement is still valid that `lws_callback_on_writable()` has no effect when being called from another thread. But indeed calling `lws_cancel_service()` from another thread causes `LWS_CALLBACK_EVENT_WAIT_CANCELLED` in the `lws_service` loop thread.

> the way to handle it is do the `lws_cancel_service()`, but instead of doing the writeable request as well, set a flag somewhere indicating that's what you need to do, and do that from the LWS_CALLBACK_EVENT_WAIT_CANCELLED callback in the lws thread context.

Thank you for the directions! I will be using `lws_cancel_service()` if it's enough for threads synchronization. (Indication of what to do is already being passed via `void* lws_protocols::user` callback argument.)

_I also confused myself because my libwebsockets callback was already handling `LWS_CALLBACK_EVENT_WAIT_CANCELLED` - ignoring it. Thus I did not notice the effect of it and callback was actually called after `lws_cancel_service()` without further `lws_callback_on_writable()`._

**Comment by lws-team** [comment]
> Your confusion is correct.

I meant what you are describing is a bit confused.  You can't impose sequencing on the threads vs when you can write, quite the opposite the gap between asking to write and when you can is there to represent the network situation on that connection and may be unpredictable.  That just reflects the network programming reality whatever you do, and it is what you need.

What you can do safely is call `lws_cancel_service()` from another thread, it will put a byte in a pipe2() that exists for this purpose, and will wake the lws event loop and it will then issue the EVENT_WAIT_CANCELLED so your code in lws event loop context can understand that happened.  The POSIX pipe is defined to be completely threadsafe.  If it's otherwise idle, the EVENT_WAIT_CANCELLED will usually come within ~200us after the lws_cancel_service().  And then you can do whatever you need to do with lws apis (in this case, ask for writeable callback) from there safely.  If otherwise idle and network connection OK, the WRITEABLE will come within ~200us, but as explained that particular timing is by design at the mercy of network conditions.
