### ISSUE TITLE
ping pong invalid

### ISSUE THREAD

**Issue by snysmtx** [warmcat/libwebsockets#2429]
Hi,

After upgrading the version from v2.2-stable to v4.0-stable
ws_ping_pong_interval and timeout_secs no longer take effect

I tried to run the test
server:
libwebsockets-test-server -P 5 -d 15
client:
libwebsockets-test-client  localhost -p 7681 -n -e -P3

Phenomenon still exists(main is also)
How should i use it?

**Comment by snysmtx** [comment]
![2021-09-29 11-18-21 的屏幕截图](https://user-images.githubusercontent.com/20901477/135197479-303cf231-3e03-4fec-83a0-c3e25ed62cfb.png)

**Comment by lws-team** [comment]
Have a look at https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md?h=main and, eg, 

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c?h=main#n26-29
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c?h=main#n308

the unit is seconds.

**Comment by wasphin** [comment]
The unit of `ws_ping_pong_interval` is second, but the variable seems unused.

After some debugging, we find this:
https://github.com/warmcat/libwebsockets/blob/aa2013a5e3027203212e1f53096e851864765c3c/lib/core-net/wsi-timeout.c#L342-L345
and
https://github.com/warmcat/libwebsockets/blob/aa2013a5e3027203212e1f53096e851864765c3c/lib/core/context.c#L545

`lws` use `rbo->secs_since_valid_ping` as the ping-pong interval, and the default value is 300 in seconds, which is definitely 5 minutes.

So is `ws_ping_pong_interval`  deprecated?

**Comment by snysmtx** [comment]
Thank you for quick response.

**Comment by lws-team** [comment]
Yes, it doesn't exist in main any more.  The validity stuff works automatically on any protocol that has PING / PONG, so also h2.  And you can explicitly tell lws that normal traffic showed the link is still valid, so it won't send PINGs it doesn't have to.

**Comment by snysmtx** [comment]
Thanks.
