### ISSUE TITLE
JSON-RPC support status

### ISSUE THREAD

**Issue by mlomb** [warmcat/libwebsockets#2436]
Hi, I need support for JRPC and found the `jrpc-wip` branch.
Is this branch ready to be used? Somewhat stable?

The last commit was in May 2020: https://libwebsockets.org/git/libwebsockets/commit?id=0278e8c26aed094e763d35b7ab9d4df504c827a5

**Comment by lws-team** [comment]
I rebased that patch on to current main from today, checked it passes its selftests and updated jrpc-wip with that.  So it claims to work as far as its selftests at least.

https://libwebsockets.org/git/libwebsockets/log?h=jrpc-wip

You can get a good idea about it quickly by building that with `-DLWS_WITH_JSONRPC=1 -DLWS_WITH_MINIMAL_EXAMPLES=1` and run `./bin/lws-api-test-jrpc`, add or modify things in there to play with it using your own JSON.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/api-tests/api-test-jrpc/main.c?h=jrpc-wip

For the public api

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-jrpc.h?h=jrpc-wip

if it looks like it's mostly what you want, we can discuss anything missing or broken.
