### ISSUE TITLE
How to use the path when configuring the websocket server? 

### ISSUE THREAD

**Issue by Earl-chen** [warmcat/libwebsockets#2438]
Hi,
I want to configure a websocket server, this server will carry the path, the format is as follows: 
`ws://127.0.0.1:8089/test/path`

How do I configure my websocket server?

**Comment by lws-team** [comment]
The ws server belongs to the vhost, if the subprotocol is negotiated on that vhost, then you will connect to the ws server whatever the url path.  The url path is additional data when the ws connection is negotiated.

You can get hold of the path part at the time the connection is upgraded to ws from http, at LWS_CALLBACK_ESTABLISHED, using, eg, `lws_hdr_copy()` with `WSI_TOKEN_GET_URI`.

**Comment by Earl-chen** [comment]
> The ws server belongs to the vhost, if the subprotocol is negotiated on that vhost, then you will connect to the ws server whatever the url path. The url path is additional data when the ws connection is negotiated.
> 
> You can get hold of the path part at the time the connection is upgraded to ws from http, at LWS_CALLBACK_ESTABLISHED, using, eg, `lws_hdr_copy()` with `WSI_TOKEN_GET_URI`.

Thank you very much for your answers. I finally solved the problem. 
The following is the code of this part, I attached it below, so that others can learn from it:
` 
char uribuf[32];
 if (lws_hdr_copy(wsi, uribuf, sizeof(uribuf), WSI_TOKEN_GET_URI) > 0)
{

    bool flag = !strcmp(uribuf, "/test");

    printf(" Get Uri from Client -->%s\n", uribuf);
    printf(" Get Uri flag            -->%d\n", flag);
    if(flag)
    {
        lwsl_notice("Client connect!\n"); 
    }
    else
    {
        lws_set_timeout(wsi, NO_PENDING_TIMEOUT, LWS_TO_KILL_ASYNC); // Close the current connection immediately
        lwsl_notice("Client connect Refuse !!\n");
    }
}
`
