### ISSUE TITLE
parsing error for working websocket upgrade response.

### ISSUE THREAD

**Issue by vinod82** [warmcat/libwebsockets#244]
I am using websocket library for a websocket connection with a cloud server for my project. Below are the request and response from wireshark.

Request:
GET /WebSocketServices/Register HTTP/1.1
Pragma: no-cache
Cache-Control: no-cache
Host: xx.yy.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: /ohySeRrh2fT42+reC4aSw==
Origin: http://xxxx.com
Sec-WebSocket-Protocol: xxx.yyy.http
Sec-WebSocket-Extensions: 
Sec-WebSocket-Version: 13
X-CUST-Authorization: Basic MDA0MDg0MjA3MTU5OjAwNDA4NDIwNzE1OQ==
Authorization: Basic MDA0MDg0MjA3MTU5Ojc4SDFWZWE4eUx5dGYwMDE=

Respose:

HTTP/1.1 101 Switching Protocols
Cache-Control: private
Upgrade: Websocket
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
Sec-WebSocket-Accept: xaf2+0RZr2l6LHQ24PRixvev4aM=
Connection: Upgrade
X-Powered-By: ASP.NET
Date: Fri, 20 Feb 2015 13:41:49 GMT

With libwebsocket1.2, it was working fine. But with latest code changes in the parser, libwebsocket is not ignoring the unknown tokens in the header.
It throws a parsing error and client goes ahead and closes the connection.
Is it now the custom header tokens are not supported. In Parser it check for the 6 tokens and if any of the new token does not matches, it throws the error ( though it got HTTP token earlier).

I have started using libwebsocket library recently and not well versed 
with the library implementation and protocol as a whole. Please let me know if the parser is not handling any tokens in the header apart from GET,POST,OPTIONS,PUT,PATH,DELETE.

**Comment by warmcat** [comment]
I think it must continue to ignore unknown headers just fine, since modern browsers send a ton of weirdo headers lws doesn't understand.

What you're talking about is unknown METHOD, that's different.

It should reject a request that it doesn't understand to be GET, etc.

I see a GET request, so if you have a problem it's something else than you are thinking.

Turn the debug level up (-d 65535 in the test server) and watch where it actually fails.

**Comment by vinod82** [comment]
Hi Andy,
 Thanks for the quick response.  I am facing the error at client side while parsing the response for GET.
 In particular with the token in the response which is .net specific. " X-AspNet-Version: 4.0.30319".
 GET request is processed correctly at server, but client is throwing a parsing error for the response. 
  
Regards

**Comment by vinod82** [comment]
issue fixed with latest patch.
