### ISSUE TITLE
Crash while lws_write

### ISSUE THREAD

**Issue by ajit216** [warmcat/libwebsockets#2460]
Hi, my application is crashing sometimes and in call stack it shows crash at
 **_0  myapplicatiion!lws_h2_frame_write [http2.c : 568 + 0x2]_** ,    i.e line`  *p++ = len >> 16;` below is funtion and line where it crashes.
 
Whenever there is crash I could see the `len` is more than 4771801

```
http2.c
int lws_h2_frame_write(struct lws *wsi, int type, int flags,
                       unsigned int sid, unsigned int len, unsigned char *buf)
{
        struct lws *nwsi = lws_get_network_wsi(wsi);
        unsigned char *p = &buf[-LWS_H2_FRAME_HEADER_LENGTH];
        int n;

        //if (wsi->h2_stream_carries_ws)
        // lwsl_hexdump_level(LLL_NOTICE, buf, len);

        *p++ = len >> 16;                          // Line 568
        *p++ = len >> 8;
        *p++ = len;
        *p++ = type;
        *p++ = flags;
        *p++ = sid >> 24;
        *p++ = sid >> 16;
        *p++ = sid >> 8;
        *p++ = sid;

        lwsl_debug("%s: %p (eff %p). typ %d, fl 0x%x, sid=%d, len=%d, "
                   "txcr=%d, nwsi->txcr=%d\n", __func__, wsi, nwsi, type, flags,
                   sid, len, wsi->h2.tx_cr, nwsi->h2.tx_cr);

```

Please help me to figure out what could be the issue.

**Comment by lws-team** [comment]
... then did you take care about LWS_PRE in the buffer you're passing to lws_write()?

**Comment by lws-team** [comment]
Yes, having a huge len is always ignoring how the network stack works... it will decide when it will take some more for tx, and you will only find out how much when you pass the data to be written on the socket.  It means for data bigger than a couple of MTU, lws has to temporarily hold the remainder on the heap and pass it out itself.  So it's very inefficient.

Inside a TLS tunnel, there's a record boundary length limit at 16KB, and for h2, the two sides negotiate the max length of a DATA frame, they usually set it to 16KB to match the TLS tunnel size.  When you call lws_write(), it tries to send your data in one h2 frame, which can be failed by the peer even if you managed to send it cleanly.

What you should do instead is send, eg, 4KB chunks of your data at a time, asking for a writeable callback again while still more to do.
