### ISSUE TITLE
libwebsockets RPM

### ISSUE THREAD

**Issue by fabaff** [warmcat/libwebsockets#247]
For the Fedora Package collection we need libwebsockets because it became a dependency with the latest mosquitto release. After building the package rpmlint complains about  setuid and setgroups.

```
libwebsockets.x86_64: E: missing-call-to-setgroups-before-setuid /usr/lib64/libwebsockets.so.4.0.0
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

**Comment by warmcat** [comment]
I just pushed a patch that should solve this by using initgroups().

If there are any more packaging-related problems let me know, if not, I will release what we have as 1.4

**Comment by fabaff** [comment]
Thanks for the fix. 

There are two other minor issues:
- client.c and private-libwebsockets.h have exec permissions.
- Two .cmake files are going into /usr/lib/cmake/libwebsockets/ during the installation.

Those issues are not blocking the package review because they are fix within the SPEC file.

**Comment by JoakimSoderberg** [comment]
Are you referring to the cmake Config files? Why is that a problem? Those are used by CMake to make it easier to find libs from other project files. Much like `pkg-config`. https://github.com/warmcat/libwebsockets/blob/master/cmake/LibwebsocketsConfig.cmake.in and https://github.com/warmcat/libwebsockets/blob/master/cmake/LibwebsocketsConfigVersion.cmake.in?

http://www.cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

**Comment by fabaff** [comment]
The location is problematic. libwebsockets will become an arch-depended package. This means that the default location for 64 bit is /usr/lib64/. I'm not sure how the exact guidelines in Fedora are about overwriting the path/location of a file in regards of the arch. But it seems that no other package is using /usr/lib64/cmake to store additional files. This could be because rpm is in charge for the whole dependency handling.

**Comment by warmcat** [comment]
If it's okay to just snip them out in the spec we can leave it like that.

I'll fix the exec permission thing in a moment.

**Comment by JoakimSoderberg** [comment]
You can change the desired location by doing:

```bash
cmake -D LWS_INSTALL_CMAKE_DIR=/usr/lib64/cmake ..
```

If that's an option?

I mean, these config files are not a replacement of RPM/debian packages or whatever. It is simply a means for other CMake projects to more easily find the install libraries and all their exported stuff.

OpenCV is another project that relies on this heavily, but all OS distributions seems to not care and simply remove all cmake files since I guess they don't know their use.
