### ISSUE TITLE
Issue with LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE option

### ISSUE THREAD

**Issue by ronf** [warmcat/libwebsockets#2470]
Thanks so much for your libwebsockets library! I needed a high-performance web server written in C where I could process dynamic requests from inside a libuv event loop, and libwebsockets was perfect for this task!

That said, I ran into a minor issue that I wanted to ask about regarding the LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE option. According to the documentation, this option is:

> Set to allow multiple listen sockets on one interface + address + port. The default is to strictly allow only one listen socket at a time. This is automatically selected if you have multiple service threads.

In my use case, I want to create a collection of independent Linux processes each with this own libuv event loop with a single-threaded instance of LWS serving up a simple REST API. All of these processes would be listening on a socket bound to the same interface, address, and port number, spreading the load across the different processes, with basically no data sharing between the processes once they are started up. This seemed like exactly what LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE was meant to support and in the end I did get it working, but I had to make a small change in the LWS code to make its behavior match the documentation above.

Specifically, I changed:

```patch
--- ../lib/roles/http/server/server.c.orig	2021-10-12 16:01:53.999110745 +0000
+++ ../lib/roles/http/server/server.c	2021-10-27 18:35:49.461777556 +0000
@@ -261,7 +261,7 @@
 		n = lws_check_opt(a->vhost->options,
 				  LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE);
 #endif
-		if (n && cx->count_threads > 1)
+		if (n || cx->count_threads > 1)
 			if (setsockopt(sockfd, SOL_SOCKET, SO_REUSEPORT,
 					(const void *)&opt, sizeof(opt)) < 0) {
 				compatible_close(sockfd);
```

As currently coded, the SO_REUSEPORT option is only enabled on the listening socket when the LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE is set _and_ count_threads > 1, where the documentation says that this option should be set whenever _either_ LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE is set or as a result of having multiple service threads.

In my example, since I have a different libuv event loop for each LWS instance, each instance has only a single service thread, and as a result setting LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE actually ended up being a no-op. I could only get the SO_REUSEPORT behavior by setting LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE _and_ setting count_threads on my context to be greater than 1, which I don't think is the intended behavior.

Once I changed the "&&" to an "||", I got the behavior described in the documentation, where SO_REUSEPORT would be set when either LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE was set (even with count_thread == 1) or when multiple threads were requested (even without setting LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE explicitly).

Given the documentation, does this change make sense?

**Comment by lws-team** [comment]
Thanks for the explanation and patch.

Yes it seems broken, it hasn't shown up because the lws way to use this is with LWS_MAX_SMP > 1 and multiple service threads anyway, so it "worked" as it is.  There isn't an lws example where there are n processes sharing the listen socket, although Linux also supports that, which would have revealed the bug.

It's pushed on main and v4.3-stable.

**Comment by ronf** [comment]
Thanks very much!
