### ISSUE TITLE
Simply send

### ISSUE THREAD

**Issue by hannesa2** [warmcat/libwebsockets#2471]
Hi, I want to simply send some data very fast from Raspberry and other clients should be able to listen.

I dig into `minimal-examples/client/hello_world` but to be honest it is to complicated for me. I don't want to read websites, etc.... I want only send some basic data (string or numbers) from sensors without any pointless delay.

Do you have a hint or much better an example to do so ?
Thank you

**Comment by lws-team** [comment]
> I don't want to read websites, etc.... I want only send some basic data (string or numbers) from sensors without any pointless delay.

What is the "pointless delay", learning how to do what you want?

> much better an example

er... how about you write a much better issue that describes what you actually want to do.  Eg, the rpi is being a server?  Http?  Ws?  What happens to the data at the server?  What consumes it ultimately, a browser?

Tbh it sounds like you are perhaps not aligned with using a C library but maybe would be more comfortable using node, or python or somesuch, if you don't care about how it works and its resource usage.  Even then you still have to actually learn how to use whatever it is...

**Comment by hannesa2** [comment]
> > I don't want to read websites, etc.... I want only send some basic data (string or numbers) from sensors without any pointless delay.
> 
> What is the "pointless delay", learning how to do what you want?

Ok, I do my best.
If it really helps you: I want to control over GSM a aircraft/glider. For this want to read gyro data on my mobile phone, when it's out of visual area.
My current solution with python has a delay, and for sure, the network/GSM has a big part of it ! That's why I'll test the whole round trip with C, if I can measure there some improvements. 
The goal is to measure if there is some improvement !

The server in C is now working on Raspberry.
Read-data in C is now working on Raspberry.
Now I want to to combine both and need a send-data on client. But I want to avoid a monolithic C server which read gyro data and provide it too.
Doing so, I want to add send-data to read-data program.

> > much better an example

Sorry to write this, but existing hello world client does too much for my point of view. For me it's not transparent how to send char/float **only**.

> er... how about you write a much better issue that describes what you actually want to do. 

I'll to my best

> Eg, the rpi is being a server? Http? Ws? What happens to the data at the server? What consumes it ultimately, a browser?

As I described above. rpi is the server. Http or Ws ? Anything which will work (best). I've no preference

> Tbh it sounds like you are perhaps not aligned with using a C library 

Yes of sure, I'm a bloody C beginner. But that's why I ask ! If I would know, there would be no reason to ask. That simple !

> but maybe would be more comfortable using node, or python or somesuch, if you don't care about how it works and its resource usage. Even then you still have to actually learn how to use whatever it is...

That's not the point. The caption is "_Simply send (data with this library)_"

As I want write now some code snippets I searched code and found `minimal-examples-lowlevel` (Till now I only searched in `minimal-examples`). There are more samples. I've to dive into them ....

**Comment by hannesa2** [comment]
I test https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c with my server, which have no ssl at all.

`./lws-minimal-ws-client -s easy -p 8086`

```
[2021/11/01 09:43:44:2561] U: LWS minimal ws client
[2021/11/01 09:43:44:2571] N: lws_create_context: LWS: 4.3.99-v4.3.0-64-g1440dae7, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent
[2021/11/01 09:43:44:2573] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2021/11/01 09:43:44:2592] N: __lws_lc_tag:  ++ [vh|0|default||-1] (1)
[2021/11/01 09:43:44:3556] N: __lws_lc_tag:  ++ [wsicli|0|WS/h1/default/easy] (1)
[2021/11/01 09:43:44:3613] N: [wsicli|0|WS/h1/default/easy]: lws_client_connect_3_connect: trying 192.168.178.74
[2021/11/01 09:43:44:3873] E: CLIENT_CONNECTION_ERROR: tls: error:00000001:lib(0)::reason(1)
[2021/11/01 09:43:44:3874] N: __lws_lc_untag:  -- [wsicli|0|WS/h1/default/easy] (0) 31.766ms
[2021/11/01 09:43:45:4035] N: __lws_lc_tag:  ++ [wsicli|1|WS/h1/default/easy] (1)
[2021/11/01 09:43:45:4067] N: [wsicli|1|WS/h1/default/easy]: lws_client_connect_3_connect: trying 192.168.178.74
^C[2021/11/01 09:43:45:4258] N: __lws_lc_untag:  -- [wsi|0|pipe] (0) 1.168s
[2021/11/01 09:43:45:4258] E: CLIENT_CONNECTION_ERROR: closed before established
[2021/11/01 09:43:45:4288] N: __lws_lc_untag:  -- [vh|0|default||-1] (0) 1.169s
[2021/11/01 09:43:45:4289] N: __lws_lc_untag:  -- [wsicli|1|WS/h1/default/easy] (0) 25.305ms
[2021/11/01 09:43:45:4289] U: Completed
```

What I've to do, to be able to connect ? I guess ssl is the main reason.

My Android client it able to connect with `ws://easy:8086`

**Comment by lws-team** [comment]
That example defaults to using tls.  You can give it `-n` to tell it not to do so.
