### ISSUE TITLE
lws_uv_getloop() not available due to undefined UV_ERRNO_MAP

### ISSUE THREAD

**Issue by ronf** [warmcat/libwebsockets#2476]
I'm trying to call the function lws_uv_getloop() to look up the current UV loop object, but the compiler was not finding it. Looking more closely at the lws-service.h header file, this call is protected by a `#if`:

```
#if defined(LWS_WITH_LIBUV) && defined(UV_ERRNO_MAP)
```

I found that this is defined in <uv.h>, but lws-service.h doesn't include <uv.h>. So, the methods within this `#if` are only declared if the calling file includes <uv.h> before including <libwebsockets.h>. My code had both of these includes, but in the opposite order, and as a result these LWS functions weren't declared.

I can work around this problem by reordering my includes, but I wanted to report this as the ordering dependency was unexpected. Given that this part of lws-service.h is already guarded by LWS_WITH_LIBUV, would it be possible to include <uv.h> within this guard, or otherwise not depend on the calling file's include ordering?

Thanks!

**Comment by ronf** [comment]
Actually, reordering my includes wasn't enough here -- it fixed the compile-time error, but I ended up getting a link error on lws_uv_getloop(), so I'm thinking it might not be getting marked properly as external when LWS is being built.

**Comment by ronf** [comment]
Digging a bit more, I see there is already an include of <uv.h> in libwebsockets.h prior to include lws-service.h. However, this is conditional on LWS_WITH_LIBUV_INTERNAL. When I built this, I defined LWS_WITH_LIBUV, but not LWS_WITH_LIBUV_INTERNAL. When using a foreign libuv event loop, are both of these options required?

**Comment by lws-team** [comment]
This api is actually cruft... it's a long story but at one point, libuv was optionally used internally in lws.  For lws itself, it was made completely agnostic about the loop, even for custom loops now.  So anything uv specific in the library apis is cruft.

You can pass `.user` at context creation time with the loop pointer if you want to be able to get it from lws pieces.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n610-618

**Comment by ronf** [comment]
Thanks -- setting a user pointer when creating the context and getting to that via lws_context_user() should work fine in my use case.

I also confirmed that setting both LWS_WITH_LIBUV and LWS_WITH_LIBUV_INTERNAL when building LWS did allow lws_uv_getloop() to work, but I'm going to stick with the solution you proposed with the context user pointer.

I really appreciate all your help here!

**Comment by lws-team** [comment]
No worries.
