### ISSUE TITLE
plugins/ssh-base/include/lws-ssh.h:581:15: error: unknown type name ‘u_char on musl

### ISSUE THREAD

**Issue by jsmolic** [warmcat/libwebsockets#2477]
I've ran into this issue while trying to build libwebsockets on musl system
```
#22 120.0 In file included from /usr/x86_64-multilib-linux-musl/tmp/portage/net-libs/libwebsockets-4.2/work/libwebsockets-4.2/plugins/ssh-base/telnet.c:26:
#22 120.0 /usr/x86_64-multilib-linux-musl/tmp/portage/net-libs/libwebsockets-4.2/work/libwebsockets-4.2/lib/../plugins/ssh-base/include/lws-ssh.h:581:15: error: unknown type name ‘u_char’; did you mean ‘char’?
#22 120.0   581 | poly1305_auth(u_char out[POLY1305_TAGLEN], const u_char *m, size_t inlen,
#22 120.0       |               ^~~~~~
#22 120.0       |               char
#22 120.0 /usr/x86_64-multilib-linux-musl/tmp/portage/net-libs/libwebsockets-4.2/work/libwebsockets-4.2/lib/../plugins/ssh-base/include/lws-ssh.h:581:50: error: unknown type name ‘u_char’
#22 120.0   581 | poly1305_auth(u_char out[POLY1305_TAGLEN], const u_char *m, size_t inlen,
#22 120.0       |                                                  ^~~~~~
#22 120.0 /usr/x86_64-multilib-linux-musl/tmp/portage/net-libs/libwebsockets-4.2/work/libwebsockets-4.2/lib/../plugins/ssh-base/include/lws-ssh.h:582:11: error: unknown type name ‘u_char’
#22 120.0   582 |     const u_char key[POLY1305_KEYLEN]);
#22 120.0       |           ^~~~~~
```
Including `sys/types.h` in plugins/ssh-base/include/lws-ssh.h fixes the issue

**Comment by lws-team** [comment]
Thanks, I pushed your change on main and v4.3-stable.

https://libwebsockets.org/git/libwebsockets/commit?id=252890d19c2000452ccb4a0e8a3a0b49f89b6da7

**Comment by jsmolic** [comment]
Thanks for commiting it quickly, howere I'm still hitting the same issue, but oddly compilations succedes if I remove the `if` guard, i.e. just include the missing header, so I guess the `if defined(LWS_HAVE_SYS_TYPES_H)` check is failing somehow which I don't understand since I see that CMake is looking for `sys/types.h` in the build log (attaching the full build log)
[build log](https://github.com/warmcat/libwebsockets/files/7477259/build.log), my guess is that the `CHECK_INCLUDE_FILE(sys/types.h LWS_HAVE_SYS_TYPES_H)` should also be included in the plugins CMakeLists as well, but not 100% sure

**Comment by lws-team** [comment]
Have a look at the second section here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

... to understand why a cmake test that should pass has failed.
