### ISSUE TITLE
Is there a way to specify network card for url/connection

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2479]
Hi Andy,

I use lws as http client. I have two network cards in one PC. 
Is there a way to specify network card for certain url/connection? I use one process and one lws_context currently. 

For example, I need to send http request to site A and B.
All site A connections use netcard0 while all site B connections use netcard1.
It's better if it's supported to specify first five connections to A use netcatrd0 while the 6 above connections use netcard1.

Thanks and regards.

**Comment by lws-team** [comment]
You can specify it manually, per connection

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n158-160
