### ISSUE TITLE
Some inconsistency between document and code

### ISSUE THREAD

**Issue by PeiweiHu** [warmcat/libwebsockets#2481]
I found some inconsistencies between the document (i.e. comment in header files) and code. 

+ **lws_genrsa_hash_sign**: In **lib/tls/openssl/lws-genrsa.c:395** it returns _used_ which comes from _sig_len_, a >=0 value. But the document says it returns <0 for error, or 0 for success

+ **lws_http_client_http_response**: it's better to append it also returns 0.

+ **lws_http_transaction_completed**: it returns 0, -1 and 1 while only 0 and 1 are included in the document. 

+ **lws_x509_parse_from_pem**:  it's better to append it also returns -1. 

+ **lws_tls_peer_cert_info** and **lws_tls_vhost_cert_info** have return values from _lws_tls_mbedtls_cert_info_, which may return 1. But only 0 and -1 are included in the document. 

+ **lws_tls_acme_sni_cert_create** may return 1 but only 0 and -1 are included in the document. 

+ **lws_tls_cert_updated** only returns 0 while the documents says zero and nonzero. 

+ It's better to append **lws_genhash_size** and **lws_genhmac_size** will return 0 with unknown type. 

+ **lws_jws_parse_jose** and **lws_jwe_parse_jose** return 0 and -1 instead of the amount and -1. 

+ **lws_jwk_strdup_meta** and **lws_jwk_generate** return 0 and 1 instead of 0 and -1. 

+ **lws_jws_sig_confirm_compact**, **lws_jws_sig_confirm_compact_b64**, and **lws_jws_sig_confirm** return 0 and -1 while only 0 is included in the document. 

+ The document says **lws_jws_sign_from_b64** returns length or -1. However, there is a 0 value when type is unknown. Althoug it can be treated as a special length in some aspect. Maybe it's better to state it in the document or change it to -1 ?

+ There is a comment for **lws_jwt_sign_token_set_cookie**, but I didn't find its definition. Does it migrate to lws_jwt_sign_token_set_http_cookie? 

+ The document says **lws_jrpc_obj_parse** returns >= 0 if completed. However, when there is an OOM, it returns 1. Should it be changed to an negative error code? 

+ **lws_genecdsa_hash_sign_jws** can return the positive values while the document says <0 or 0. 

+ **lws_write_numeric_address** and **lws_sa46_write_numeric_address** can return positive values while the document says <0 or 0. 

+ **lws_sspc_client_connect** always returns 0 while the document says it returns 0 if OK or nonzero if we have already failed.

+ **lws_sspc_set_metadata**: it's better to append it also returns 1.

**Comment by lws-team** [comment]
Thanks for taking the time to audit the docs on these.  I adapted most of them as you described.

https://libwebsockets.org/git/libwebsockets/commit?id=fe31dcd8acbdce676d9e68177fbacd2082ebd94e

>  lws_tls_cert_updated only returns 0 while the documents says zero and nonzero.

I think the code needs to change to match the comment, but leaving that one for now, since it will just not fail atm.

> The document says lws_jrpc_obj_parse returns >= 0 if completed. However, when there is an OOM, it returns 1. Should it be changed to an negative error code?

Right... I changed to it issue the (negative) lejp parser error LEJP_REJECT_UNKNOWN for OOM.

> lws_genecdsa_hash_sign_jws can return the positive values while the document says <0 or 0.

The openssl implementation conforms to the comment.  The mbedtls one returns the length...  I changed to to say that >=0 is success which covers both.
