### ISSUE TITLE
error in building libwebsockets 4.2.0

### ISSUE THREAD

**Issue by rajendra-adimulam** [warmcat/libwebsockets#2485]
libwebsockets-4.2.0/lib/tls/openssl/openssl-client.c:529:7: error: ‘X509_V_ERR_HOSTNAME_MISMATCH’ undeclared (first use in this function)
  case X509_V_ERR_HOSTNAME_MISMATCH:
       ^
steps followed: 
1. download libwebsockets.tar.gz and untar
2. cmake .
3. make

please help

**Comment by rajendra-adimulam** [comment]
libwebsockets 4.2.0
cmake version 3.22.0-rc2

**Comment by lws-team** [comment]
> libwebsockets 4.2.0

No point choosing that when 4.3 is out.

> cmake .

It's a much better idea to use a build subdir you can blow away when you're done, especially if the sources are not under git control.

>  ‘X509_V_ERR_HOSTNAME_MISMATCH’ undeclared 

This is an export from openssl.

I would check you do not have an ancient lws installed somewhere, like /usr/local/include, or /usr/include via a package.

If that is not it, where did your openssl come from, are you using the right include dir for it?  What is your platform?

**Comment by lws-team** [comment]
There's nothing for me to do here, so closing.  If there's more info on the problem, feel free to continue here.

**Comment by rajendra-adimulam** [comment]
the build error is due not specifying the ssl lib path in cmake, doing a cmake as below fixed the compilation issue
cmake .. -DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/include/openssl -DLWS_OPENSSL_LIBRARIES="/usr/local/lib64/libssl.so;/usr/local/lib64/libcrypto.so"
make
make install
