### ISSUE TITLE
server: no OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY when ssl_private_key_filepath is NULL

### ISSUE THREAD

**Issue by dhobsong** [warmcat/libwebsockets#2495]
According to the documentation of `ssl_private_key_filepath` in `lws_context_creation_info`

>   /**<  VHOST: filepath to private key if wanting SSL mode;
>     * if this is set to NULL but ssl_cert_filepath is set, the
>     * OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY callback is called
>     * to allow setting of the private key directly via openSSL
>     * library calls.   (For backwards compatibility, this can also be used
>     * to pass the client cert private key filepath when setting up a
>     * vhost client SSL context, but it is preferred to use
>     * .client_ssl_private_key_filepath for that.)

This worked fine in older versions of libwebsockets (prior to 3.0), but doesn't seem to be the case any more.
The server certificate specified in `ssl_cert_filepath` is not included in the `SSL_CTX` and I don't seem to get
the OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY callback.

It looks like the ssl context processing stops [here](https://github.com/warmcat/libwebsockets/blob/40a87eaf2a1da918061e4c9bc4e3c707f152e491/lib/tls/openssl/openssl-server.c#L183) when 
only `ssl_cert_filepath` is specified (I am not using the `mem_cert`,  `mem_private_key` settings).

I found though, that I can workaround this issue for now by specifying both the certificate and private key in the LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS callback.

**Comment by lws-team** [comment]
It looks like setting the info->options flag `LWS_SERVER_OPTION_IGNORE_MISSING_CERT` should also work around it with the old flow?

**Comment by dhobsong** [comment]
On the server side, I don' think that the `LWS_SERVER_OPTION_IGNORE_MISSING_CERT` makes any difference, does it?
`lws_tls_generic_cert_checks` exits [here](https://github.com/warmcat/libwebsockets/blob/f868f751f45f23c500bb5285f12a2ca1ae65ee63/lib/tls/tls-network.c#L143) before checking for that flag.  Maybe I'm looking in the wrong place?

**Comment by lws-team** [comment]
Yes, you're right.

**Comment by lws-team** [comment]
I think the generic cert checking stuff is right to take the approach the certs are unusable if the private key one is missing.

The problem seems to be some broken cruft from before those changes, the comment on generic_cert_checks() is recommending to use LOAD_EXTRA_SERVER_VERIFY_CERTS now.  So from a decrufting perspective, does it seem reasonable to just adapt the docs to reflect the current situation?

**Comment by dhobsong** [comment]
I think that still leaves the issue that the certificate given in `ssl_cert_filepath` is not loaded into the `SSL_CTX`, which is different from the old behavior.  
If the docs are updated to say that LOAD_EXTRA_SERVER_VERIFY_CERTS should be used, does that imply that the LWS_CALLBACK_OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY callback is no longer necessary (and should be removed?)

**Comment by lws-team** [comment]
> does that imply that the LWS_CALLBACK_OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY callback is no longer necessary (and should be removed?)

Yeah.

**Comment by dhobsong** [comment]
Apologies for leaving this in limbo for such a long time.  I've made a PR for the changes discussed above.

This still leaves a bit of a disconnect between the client-side and server-side handling adding certs and keys to the ssl context;
On the client side when a private_key_file is not provided, the cert_file will be added to the context before LOAD_EXTRA_CLIENT_VERIFY_CERTS is called, so only the key needs to be added in the callback.  However, on the server side, when no private_key_file is given, *both* the certificate and private key must be added in the callback.
