### ISSUE TITLE
What has replaced lws_timed_callback_vh_protocol?

### ISSUE THREAD

**Issue by pblemel** [warmcat/libwebsockets#2496]
Hello World,

I have some code that uses the lws_timed_callback_vh_protocol() function in 3.x to "schedule a callback" on a WSI.  When I upgraded to 4.0, I saw that it was deprecated and now in 4.3 it is gone.  What function (or set of functions) replaces lws_timed_callback_vh_protocol() in 4.3?
`void schedule_callback(struct lws *wsi, int reason, int secs)
{
	lws_timed_callback_vh_protocol(lws_get_vhost(wsi), lws_get_protocol(wsi), reason, secs);
}`

Thanks,
Peter

**Comment by lws-team** [comment]
There was a big change at v3.2 where the implementation for scheduled events was improved and unified using lws_sul() apis.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md

As part of that, a handful of single per-object timers like this were removed, in favour of the user code putting as many of its own timers as it wanted, whereever it wanted, without any requirement to handle using lws_protocols when they fired.  In this case, you should have a vhd that has the corresponding scope.

You define a struct to embody your timer

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/client/binance/binance-ss.c#n41

a callback for when it fires

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/client/binance/binance-ss.c#n81

schedule a future event, binding a callback

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/client/binance/binance-ss.c#n182-183

... and make sure to cancel any pending events before your related sul storage goes out of scope.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/client/binance/binance-ss.c#n190

You can have as many of those as you like pending, with their own callbacks.  The cb can recover the containing object if there is one using lws_container_of().

**Comment by pblemel** [comment]
Thanks for the detailed reply.
