### ISSUE TITLE
Duplicate call to LWS_CALLBACK_DEL_POLL_FD if LWS_WITH_EXTERNAL_POLL set

### ISSUE THREAD

**Issue by smartalock** [warmcat/libwebsockets#2500]
A duplicate call to the callback LWS_CALLBACK_DEL_POLL_FD is made for the same file descriptor.

This is due to __remove_wsi_socket_from_fds (pollfds.c) being called twice in __lws_close_free_wsi (close.c), once near line 723 and at the end of the function via a call to __lws_close_free_wsi_final

If the debug in __remove_wsi_socket_from_fds (pollfd.c) is enabled you can see, e.g.

```
[2021/11/22 15:19:17:9552] N: __remove_wsi_socket_from_fds: wsi=[wsisrv|4|adopted], skt=12, fds pos=4, end guy pos=5, endfd=12
[2021/11/22 15:19:17:9560] N: __remove_wsi_socket_from_fds: wsi=[wsisrv|4|adopted], skt=12, fds pos=-1, end guy pos=4, endfd=10

```

The fix is to modify __remove_wsi_socket_from_fds to only call the callback if the position in the fds table is not invalid - i.e place the callback inside the check on line 405

```
	if (m != LWS_NO_FDS_POS) {
		char fixup = 0;


	... other stuff

#if defined(LWS_WITH_EXTERNAL_POLL)
		/* remove also from external POLL support via protocol 0 */
		if (lws_socket_is_valid(wsi->desc.sockfd) && wsi->a.vhost &&
	    	wsi->a.vhost->protocols[0].callback(wsi, LWS_CALLBACK_DEL_POLL_FD,
						      wsi->user_space, (void *) &pa, 0))
			ret = -1;
#endif
	}
```

**Comment by lws-team** [comment]
Thanks, it's pushed on main and v4.3-stable.
