### ISSUE TITLE
What is the correct way to cancel a POST file upload?

### ISSUE THREAD

**Issue by jin-eld** [warmcat/libwebsockets#2507]
Hi,

I am extending my application so that it can accept files via POST in addition to the websocket communication.

I managed to get things to work by looking at `protocol_post_demo.c`, but I was not quite able to clearly understand how to abort the `lws_spa_fileupload_cb()` in a proper way so that I get a chance to reply with an error to the POSting client.

I have been testing the client side using curl, like this:
`curl -v -X POST -F 'file=@/tmp/somefile.jpg' http://127.0.0.1:45000/upload`

What I observed:
* returning `0` from the callback obviously means everything is fine, that case is clear
* returning `-1`  aborts the transfer right away, but I don't get a chance to send a reply, curl will show:
    ```
    > Expect: 100-continue
    > 
    * Done waiting for 100-continue
    * Send failure: Broken pipe
    * Closing connection 0
    curl: (55) Send failure: Broken pipe
    ```
*  returning `1` will continue calling the upload callback until all data has been sent by the client and then I indeed am able to respond with an error message (in this case I was returning 500):
    ```
    * Done waiting for 100-continue
    * We are completely uploaded and fine
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 500 Internal Server Error
    ```

My question is, how can I abort the transfer to the server (like when returning `-1`), but still provide my 500 answer?

While the `return 1` variant would do it, it means that I need to wait till the end of the transfer even if I know that I am not able to save the data due to whatever internal error I had. Is it possible to abort the transfer right away, but still reply to the client or is it an limitation of HTTP itself that you have to sit out the transfer, even if its going into nothing in order to reply?

Kind regards,
Jin

**Comment by lws-team** [comment]
Yes this is just http being http, there is no 'cancel' or 'abort' concept for request body that leaves the transaction intact.

There is just hanging up the underlying connection or stream early and realizing it failed partway, there is no transaction to reply to then.

It's nothing lws can solve on its end.
