### ISSUE TITLE
lws_http_cookie_get in Version 4.2.1-v4.2.2

### ISSUE THREAD

**Issue by DerKleinePunk** [warmcat/libwebsockets#2509]
If Cookie is X-API-KEY=123456789 it works.
If Cookie is X-API-KEY=12345678 it works not it return 1

Line 1575:
while (n-- > (int)bl) {

Why ? 
I Think 
while (n-- > 0) {

**Comment by lws-team** [comment]
I seem to remember a bug about this, can you try v4.3-stable?

**Comment by DerKleinePunk** [comment]
I have Update to 4.3.0 but the Problem is the same
LIne is now 1600 in parsers.c

**Comment by lws-team** [comment]
> I Think
> while (n-- > 0) {

Genau, just before that now is `n -= (int)bl;`, it should be as you say.

I pushed a patch on main and v4.3-stable.
