### ISSUE TITLE
Questions regarding lws with libuv

### ISSUE THREAD

**Issue by chill1n** [warmcat/libwebsockets#2511]
Lws in combination with libuv uses the uv_idle_ API to register callbacks with the libuv event loop.
Registration with the libuv "foreign" loop happens during lws context creation.

I have the following questions (for which I couldn't find a clear answer in the documentation):
1. How to unregister the associated uv_idle_t handle when desiring to terminate the associated ws channel?
2. With lws_service() the proposed method to trigger an LWS_CALLBACK_CLIENT_WRITEABLE event is: lws_cancel_service() -> LWS_CALLBACK_EVENT_WAIT_CANCELLED -> lws_callback_on_writable() -> LWS_CALLBACK_CLIENT_WRITEABLE. How to accomplish the same goal with libuv as event loop?

**Comment by lws-team** [comment]
The idle cb for libuv is a feature of the foreign loop being bound to the lws_context.  If there are no waking events, the idle cb won't be happening, so it doesn't cost anything.  You can completely remove the lws_context from the loop by destroying the context.

Everything in the flow you mention works the same no matter what the event loop... although creating and maybe destroying the context is a bit different using a foreign event loop, it should be concealed what's actually handling the event loop for all the other apis.

**Comment by chill1n** [comment]
It doesn't cost any runtime at lws side, but it does claim some resources at libuv side (both time and space). So it would be cleaner to have an lws function to unregister.

The encapsulation pattern is good, but somehow the behavior/usage is not what I expect.
With lws hooked into libuv, I see that lws is calling uv_run under the hood. I'm also still calling lws_service() in a loop, but lws_service() never exits if I call lws_cancel_service(). Without libuv, the (blocking) lws_service() call would exit. How is this intended to work with libuv?

**Comment by chill1n** [comment]
Using a top-level libuv I expected to get control back from lws after lws_cancel_service() so that libuv can handle other events (also on other lws threads). Is this use case possible?

**Comment by lws-team** [comment]
Here is a comprehensive example showing lws foreign event lib usage for any of the event libs (which one selected at runtime).

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign

**Comment by chill1n** [comment]
I have looked at that example, but it's a different use case. By the way, the example calls lws_context_destroy(context); twice. Looks like a bug.
Clearly this example runs everything in a single thread. Moreover, it doesn't use lws_service and lws_cancel_service. My tests show that these two API functions behave differently depending on the chosen event loop (in this case built-in vs libuv).

My use case is as follows:
Thread 1 has the main lws functions. It creates the context (with uv_loop_t) and creates the client connection to the remote server. It also defines the ws callbacks and processes them.
Thread 2 runs the libuv event loop and takes care of handling other external events. It also communicates with Thread 1 to pause processing (via lws_cancel_service()), or requests to terminate lws actions in Thread 1 altogether.

In this case lws_cancel_service does not cause lws_service in Thread 1 to exit. Is this a bug? What's the proper approach to get this pattern working with libuv (instead of the built-in event handler that handles it as expected)?

**Comment by lws-team** [comment]
It shows how to join and leave a foreign loop cleanly, that's  what you are asking how to do.

Calling destroy twice is not a bug, the destroy action is stateful, occurs partly on the loop and cannot finalize destroying itself until it has fully detached from the loop.

> Thread 1

Nope.  Libuv event loop thread is the only thread it is safe to call lws apis from, once that is the foreign loop.

I suggest using the example I pointed to and following how it works.

**Comment by chill1n** [comment]
The documentation says about lws_context_destroy(context):
```
This function closes any active connections and then frees the
context.  After calling this, any further use of the context is
undefined.
```
That's at least a bit confusing.

I'll have another look at the libuv docs and the lws example code, and see if I can get it working properly.

Off-topic:
With my current non-libuv implementation running three independent threads with each their own lws event loop, I'm getting an occasional segfault at
libwebsockets/lib/core/logs.c:515: lwsl_refcount_cx: Assertion `cx->refcount' failed

I assume that is some extra code to detect improper use and/or threading issues. In my case the assert is only occasionally triggered upon termination of the ws channels after
```
[2021/12/05 23:55:55:6949] N: __lws_lc_untag:
```

What is this refcount counting exactly? Any hint as to finding the root cause of this assertion?

**Comment by lws-team** [comment]
> I'll have another look at the libuv docs and the lws example code, and see if I can get it working properly.

You should be able to try the example without needing to "get it working properly".

> What is this refcount counting exactly?

When the context-sensitive logs are, eg, used to direct specific object logs to a file, it needs to keep count of how many objects are in use in the logging context so it knows when to open and close the related logging file.

The assert is telling you there's a mismatch between the number of objects created and destroyed in the logging context somehow, I would guess it's to do with your multi thread stuff.

**Comment by chill1n** [comment]
> You should be able to try the example without needing to "get it working properly".

That was related to my code, based on the example code.

> The assert is telling you there's a mismatch between the number of objects created and destroyed in the logging context somehow, I would guess it's to do with your multi thread stuff.

Given the type of behavior I would also guess that.
Thanks for the excellent support!
