### ISSUE TITLE
bio_create failed - libwebsockets 3.2.1

### ISSUE THREAD

**Issue by azadsagar** [warmcat/libwebsockets#2512]
I am using a libwebsockets with PAM module and generating a shared library. I was able to connect to websocket secure (wss) as a standalone application. But after compiling with PAM module I am seeing bio_create failed in "reason". Below is the sequence of "reason" callback.

```
21	LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS
31	LWS_CALLBACK_GET_THREAD_ID
71	LWS_CALLBACK_EVENT_WAIT_CANCELLED
27	LWS_CALLBACK_PROTOCOL_INIT
29	LWS_CALLBACK_WSI_CREATE
19	LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED
1	LWS_CALLBACK_CLIENT_CONNECTION_ERROR -----------> This is where i get "bio_create failed"
45	LWS_CALLBACK_CLOSED_CLIENT_HTTP
30	LWS_CALLBACK_WSI_DESTROY
28	LWS_CALLBACK_PROTOCOL_DESTROY
```

Is there a way I can further debug this and find out what I am doing wrong ? Is there additional feature that needs to be taken care when using libwebsockets with PAM shared object modules ?

**Comment by lws-team** [comment]
3.2 is old, we're up to 4.3 currently.

Lws has a huge amount of logging that explains what it thinks goes on.  You may need to build in debug mode `-DCMAKE_BUILD_TYPE=DEBUG` and up the log level to, eg, -d1151

**Comment by azadsagar** [comment]
Okay. I upgraded and manually set the log level to INFO. ```lws_set_log_level(LLL_INFO,lwsl_emit_syslog);```
After LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP, it tries to upgrade the connection. Now I am getting ```reason HS: ws upgrade response not 101```
Target websocket server is wss API gateway websocket. I am able to connect with browser or equivalent clients.

Although target server has valid ssl certificate, I have explicitly set below flags for ssl_connection
```
LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK
```

**Comment by lws-team** [comment]
FYI these `LLL_` things are or-ed together to select the different levels, not usually just pick the one.  You probably want `LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE | LLL_INFO`

> reason HS: ws upgrade response not 101

So your auth token or path or something is wrong.  With v4.3, you can select some handy cmake hacks, `-DLWS_TLS_LOG_PLAINTEXT_RX=1 -DLWS_TLS_LOG_PLAINTEXT_TX=1` will hexdump anything sent just before encyryption and received just after encryption, you will be able to review exactly what you are sending and what was responded.

**Comment by azadsagar** [comment]
After recompiling with cmake setting ```DLWS_TLS_LOG_PLAINTEXT_RX=1 -DLWS_TLS_LOG_PLAINTEXT_TX=1``` also added ```-DLWS_WITHOUT_EXTENSIONS=0```

Here is the ASCII dump:

```
GET /dev HTTP/1.
1..Pragma: no-ca
che..Cache-Contr
ol: no-cache..Ho
st: (null)..Upgr
ade: websocket..
Connection: Upgr
ade..Sec-WebSock
et-Key: ioxtajM4
LtfAHHaDxdQI5Q==
..Sec-WebSocket-
Extensions: perm
essage-deflate; 
client_no_contex
t_takeover; clie
nt_max_window_bi
ts..Sec-WebSocke
t-Version: 13...
.               
```
I see Host is set to null. And just after this dump I also see reason code ```LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP``` followed by that connection is terminated with reason code ```LWS_CALLBACK_CLIENT_CONNECTION_ERROR```

```
HTTP/1.1 500 Int
ernal Server Err
or..Date: Tue, 0
7 Dec 2021 13:02
:45 GMT..Content
-Length: 0..Conn
ection: keep-ali
ve....          
```



Attaching full logs
[log_masked.txt](https://github.com/warmcat/libwebsockets/files/7669194/log_masked.txt)

**Comment by lws-team** [comment]
> I see Host is set to null. 

Yes that will be enough to confuse the remote peer.

Just set `info.host` to the address of the host when you create the client connection, as done in the examples

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c?h=main#n318

**Comment by azadsagar** [comment]
```
char host[128];
lws_snprintf(host, sizeof(host), "%s:%u", *vhd->ads, *vhd->port);
.
.
.
.
i.host = host;
i.origin = host;
```
I am using above piece of code to set the host. Took this reference from ```protocol_lws_minimal_client_echo.c```
Shouldn't this be setting the host ?

**Comment by lws-team** [comment]
> Shouldn't this be setting the host ?

Dunno, what is the value of `*vhd->ads`?

you should log `host` and see what it is actually set to.

**Comment by azadsagar** [comment]
Andy, thank you so much for helping me out with thorough debugging. It was "host" address issue and memory leak in my code. I just wanted to ask one last question. Does **libwebsockets** blocks any **stdout** or similar calls ? Coz pam converse method ```pam_get_item``` is not able to print anything, unlesss libwebsockets connection is ended (while loop that keeps polling lws_service)

**Comment by lws-team** [comment]
No lws doesn't do anything with your stdout.
