### ISSUE TITLE
Client connect to IPv6 server lws_sort_dns: has no route out

### ISSUE THREAD

**Issue by cristianly** [warmcat/libwebsockets#2516]
Hello,
I had an issue about connecting to IPv6 server. That the client cannot connect to the IPv6 although that address is pingable. Is there any wrong with this or special configuration for IPv6 vs IPv4 ?
 

PING6:

> pc:# ping6 -I eth0  fe80::2fb5:ff4e:deb0:37ab
> ping6: Warning: source address might be selected on device other than: eth0
> PING fe80::2fb5:ff4e:deb0:37ab(fe80::2fb5:ff4e:deb0:37ab) from :: eth0: 56 data bytes
> 64 bytes from fe80::2fb5:ff4e:deb0:37ab%eth0: icmp_seq=1 ttl=64 time=0.495 ms
> 64 bytes from fe80::2fb5:ff4e:deb0:37ab%eth0: icmp_seq=2 ttl=64 time=0.301 ms
> 64 bytes from fe80::2fb5:ff4e:deb0:37ab%eth0: icmp_seq=3 ttl=64 time=0.324 ms
> ^C
> --- fe80::2fb5:ff4e:deb0:37ab ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 2112ms

Libwebsocket client - error "has no route out"

> [2021/11/11 23:55:25:0257] N: LWS: 4.2.1-c786120ef, loglevel 1039
> [2021/11/11 23:55:25:0257] N: NET CLI SRV H1 H2 WS ConMon IPV6-on
> [2021/11/11 23:55:25:0257] I: lws_create_context: ev lib path /usr/lib, '(null)'
> [2021/11/11 23:55:25:0257] I: lws_plugins_init: trying .
> [2021/11/11 23:55:25:0261] I: lws_plugins_init: trying /usr/lib
> [2021/11/11 23:55:25:0269] I:    trying /usr/lib/libwebsockets-evlib_event.so
> [2021/11/11 23:55:25:0272] N:    /usr/lib/libwebsockets-evlib_event.so
> [2021/11/11 23:55:25:0272] I: Event loop: libevent
> [2021/11/11 23:55:25:0272] I: lws_smd_register: peer 0xffff84009b90 (count 1) registered
> [2021/11/11 23:55:25:0273] I:  ctx:  6088B (1992 ctx + pt(1 thr x 4096)), pt-fds: 1024, fdmap: 8192
> [2021/11/11 23:55:25:0273] I:  http: ah_data: 4096, ah: 984, max count 1024
> [2021/11/11 23:55:25:0273] I:  mem: platform fd map:  8192 B
> [2021/11/11 23:55:25:0274] I: elops_init_pt_event: loop 0xffff84000b60
> [2021/11/11 23:55:25:0274] N:  ++ [wsi|0|pipe] (1)
> [2021/11/11 23:55:25:0274] I: rops_pt_init_destroy_netlink: creating netlink skt
> [2021/11/11 23:55:25:0275] N:  ++ [vh|0|netlink] (1)
> [2021/11/11 23:55:25:0276] I:  Compiled with OpenSSL support
> [2021/11/11 23:55:25:0276] I: Doing SSL library init
> [2021/11/11 23:55:25:0312] N:  ++ [vh|1|default||-1] (2)
> [2021/11/11 23:55:25:0312] I: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 on
> [2021/11/11 23:55:25:0317] I: lws_tls_client_create_vhost_context: vh default: created new client ctx 0
> [2021/11/11 23:55:25:0318] I: created client ssl context for default
> [2021/11/11 23:55:25:0318] I:  mem: per-conn:         1160 bytes + protocol rx buf
> [2021/11/11 23:55:25:0318] I: lws_plat_drop_app_privileges: not changing group
> [2021/11/11 23:55:25:0318] I: lws_plat_drop_app_privileges: not changing user
> 
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: ifidx 2
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: route list size 1
> [2021/11/11 23:55:25:0320] I: rops_handle_POLLIN_netlink: RTM 24
> .. {stripped}
> [2021/11/11 23:55:25:0329] I: _lws_routing_table_dump
> [2021/11/11 23:55:25:0330] I:  gw: 10.240.0.20,  ifidx: 2, pri: 1, proto: 20
> [2021/11/11 23:55:25:0330] I:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
> [2021/11/11 23:55:25:0330] I:  dst: 127.0.0.0/8,  ifidx: 1, pri: -1, proto: 3
> [2021/11/11 23:55:25:0330] I:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
> [2021/11/11 23:55:25:0330] I:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
> [2021/11/11 23:55:25:0331] I:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
> [2021/11/11 23:55:25:0331] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0331] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0331] I: rops_handle_POLLIN_netlink: RTA_DST: ::1
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: ifidx 1
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 2
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: route list size 7
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: RTA_DST: 2001::
> [2021/11/11 23:55:25:0332] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0333] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 4
> [2021/11/11 23:55:25:0333] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0333] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0333] I: rops_handle_POLLIN_netlink: RTA_DST: 2001::10
> [2021/11/11 23:55:25:0333] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 2
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: route list size 8
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: RTA_DST: 2001::
> [2021/11/11 23:55:25:0334] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: ifidx 2
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 4
> [2021/11/11 23:55:25:0335] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 4
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0336] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::215:adff:fe2f:fbe0
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: ifidx 2
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 2
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: route list size 9
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::215:adff:fe2f:fbe0
> [2021/11/11 23:55:25:0337] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 2
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: ifidx 2
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0338] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0339] I: rops_handle_POLLIN_netlink: RTA_DST: fec0::1111:0:0
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 4
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: RTA_DST: fec0::1111:0:1
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 2
> [2021/11/11 23:55:25:0340] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: RTA_DST: fec0::1111:0:0
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0341] I: rops_handle_POLLIN_netlink: RTA_DST: ff00::
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: ifidx 2
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: RTM 24
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: RTA_DST: ff00::
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: ifidx 4
> [2021/11/11 23:55:25:0342] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2021/11/11 23:55:25:0343] I: _lws_routing_table_dump
> [2021/11/11 23:55:25:0343] I:  gw: 10.240.0.20,  ifidx: 2, pri: 1, proto: 20
> [2021/11/11 23:55:25:0343] I:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
> [2021/11/11 23:55:25:0343] I:  dst: 127.0.0.0/8,  ifidx: 1, pri: -1, proto: 3
> [2021/11/11 23:55:25:0343] I:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
> [2021/11/11 23:55:25:0343] I:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
> [2021/11/11 23:55:25:0344] I:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
> [2021/11/11 23:55:25:0344] I:  dst: ::1/128,  ifidx: 1, pri: 0, proto: 2
> [2021/11/11 23:55:25:0344] I:  dst: 2001::10/128,  ifidx: 4, pri: 256, proto: 2
> [2021/11/11 23:55:25:0344] I:  dst: fe80::215:adff:fe2f:fbe0/128,  ifidx: 2, pri: 256, proto: 2
> [2021/11/11 23:55:25:0344] I: rops_handle_POLLIN_netlink: RTM 3
> [2021/11/11 23:55:25:0345] I: rops_handle_POLLIN_netlink: *** Unknown RTM_3
> [2021/11/11 23:55:25:0345] I: lws_state_notify_protocol_init: waiting for netlink coldplug
> [2021/11/11 23:55:25:0345] I: _report: system: prot_init: rejected 'INITIALIZED' -> 'IFACE_COLDPLUG'
> [2021/11/11 23:55:25:0345] I: lws_state_transition_steps: CONTEXT_CREATED -> INITIALIZED
> [2021/11/11 23:55:25:0441] I: lws_protocol_init
> [2021/11/11 23:55:25:0442] I: lws_protocol_init_vhost: init default.abc
> ...
> [2021/11/11 23:55:25:0443] I: _lws_smd_msg_destroy: destroy msg 0xffff8402e460
> [2021/11/11 23:55:25:0443] I: _lws_smd_msg_destroy: destroy msg 0xffff8402e550
> [2021/11/11 23:55:25:1440] I: lws_state_transition_steps: INITIALIZED -> OPERATIONAL
> 
> [2021/11/11 23:55:55:0456] I: lws_client_connect_via_info: role binding to h1
> [2021/11/11 23:55:55:0456] N:  ++ [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab] (1)
> [2021/11/11 23:55:55:0457] I: lws_header_table_attach: [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab]: ah (nil) (tsi 0, count = 0) in
> [2021/11/11 23:55:55:0457] I: _lws_create_ah: created ah 0xffff8402eee0 (size 4096): pool length 1
> [2021/11/11 23:55:55:0457] I: lws_header_table_attach: did attach wsi [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab]: ah 0xffff8402eee0: count 1 (on exit)
**> [2021/11/11 23:55:55:0457] I: lws_client_connect_2_dnsreq: [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab]: lookup fe80::2fb5:ff4e:deb0:37ab:66857
> [2021/11/11 23:55:55:0458] I: lws_getaddrinfo46: getaddrinfo 'fe80::2fb5:ff4e:deb0:37ab' says 0
> [2021/11/11 23:55:55:0458] I: lws_sort_dns: sort_dns: 0xffff8402e820
> [2021/11/11 23:55:55:0458] I: lws_sort_dns: unsorted entry (af 10) fe80::2fb5:ff4e:deb0:37ab
> [2021/11/11 23:55:55:0458] I: _lws_route_est_outgoing: returning (nil)
> [2021/11/11 23:55:55:0458] N: lws_sort_dns: fe80::2fb5:ff4e:deb0:37ab has no route out**
> [2021/11/11 23:55:55:0459] N: lws_sort_dns_dump: empty
> [2021/11/11 23:55:55:0459] I: __lws_close_free_wsi: [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab]: caller: client_connect3
> [2021/11/11 23:55:55:0459] I: __lws_close_free_wsi: real just_kill_connection: [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab] (sockfd -1)
> [2021/11/11 23:55:55:0459] I: __lws_close_free_wsi: [wsicli|0|WS/h1/fe80::2fb5:ff4e:deb0:37ab]: cce=0

Thank you!

**Comment by lws-team** [comment]
> ping6: Warning: source address might be selected on device other than: eth0

hm...

On my box that has a link-local address, it has a routing table entry

```
[2021/12/08 06:53:25:4447] I: _lws_routing_entry_dump:  dst: fe80::/64,  ifidx: 3, pri: 600, proto: 2
```

which tells it where to go, but the only ipv6 values in what you end up with are

```
[2021/11/11 23:55:25:0344] I: dst: ::1/128, ifidx: 1, pri: 0, proto: 2
[2021/11/11 23:55:25:0344] I: dst: 2001::10/128, ifidx: 4, pri: 256, proto: 2
[2021/11/11 23:55:25:0344] I: dst: fe80::215:adff:fe2f:fbe0/128, ifidx: 2, pri: 256, proto: 2
```

What does your routing table look like with `route -6 -n`?

**Comment by cristianly** [comment]
Here it is

```
route -6 -n
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
::1/128                        ::                         Un   0   5     0 lo
2001::/128                     ::                         Un   0   3     0 vlan3
2001::10/128                   ::                         Un   0   3     0 vlan3
2001::/96                      ::                         U    256 1     0 vlan3
fe80::/128                     ::                         Un   0   3     0 eth0
fe80::/128                     ::                         Un   0   3     0 vlan3
fe80::215:adff:fe2f:fbe0/128   ::                         Un   0   4     0 eth0
fe80::215:adff:fe2f:fbe0/128   ::                         Un   0   3     0 vlan3
fe80::/64                      ::                         U    256 6     0 eth0
fe80::/64                      ::                         U    256 2     0 vlan3
fec0::1111:0:0/128             ::                         Un   0   3     0 vlan3
fec0::1111:0:1/128             ::                         Un   0   3     0 vlan3
fec0::1111:0:0/96              ::                         U    256 1     0 vlan3
ff00::/8                       ::                         U    256 3     0 eth0
ff00::/8                       ::                         U    256 1     0 vlan3
::/0                           ::                         !n   -1  1     0 lo
```

**Comment by lws-team** [comment]
What version of lws is this?

**Comment by cristianly** [comment]
It is libwebsockets-4.2.1

**Comment by lws-team** [comment]
Could you see if the problem still exists on current main (v4.3-stable should be similar).

**Comment by cristianly** [comment]
Thank you, let me check!

**Comment by lws-team** [comment]
Also, how about asking it to connect to "fe80::2fb5:ff4e:deb0:37ab%eth0"?

**Comment by cristianly** [comment]
I implement as below:

```
  struct lws_client_connect_info info;
 ...
  info.address =[ipv6_address]
  info.port = [port]
...
lws_client_connect_via_info(&info)
```
 it works well for IPv4 but not for Ipv6. Is there any option need to specific for the IPv6? (I'm testing with the lastest lib but the problem may still appear)

**Comment by lws-team** [comment]
For global ipv6 addresses, it should work fine.

> (I'm testing with the lastest lib but the problem may still appear)

Is it the same actual problem with the lws routing table missing fe80::/64?  If not, you may need to % format mentioned above with link-local.

**Comment by cristianly** [comment]
--lws_create_context: LWS: 4.3.99-unknown

```
[2021/11/12 07:42:27:8887] N: lws_create_context: LWS: 4.3.99-unknown, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPV6-on
[2021/11/12 07:42:27:8888] I: lws_create_context: Event loop: libevent
[2021/11/12 07:42:27:8888] D: _realloc: size 72: news_smd_register
...
2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: NEWROUTE
[2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: RTA_DST: fe80::
[2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: ifidx 4
[2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
[2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: RTM 24
[2021/11/12 07:42:27:8960] I: rops_handle_POLLIN_netlink: NEWROUTE
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: RTA_DST: ff00::
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: ifidx 2
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: RTM 24
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: NEWROUTE
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: RTA_DST: ff00::
[2021/11/12 07:42:27:8961] I: rops_handle_POLLIN_netlink: ifidx 4
[2021/11/12 07:42:27:8962] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
[2021/11/12 07:42:27:8962] I: rops_handle_POLLIN_netlink: RTM 24
[2021/11/12 07:42:27:8962] I: rops_handle_POLLIN_netlink: NEWROUTE
[2021/11/12 07:42:27:8962] I: rops_handle_POLLIN_netlink: ifidx 4
[2021/11/12 07:42:27:8962] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
[2021/11/12 07:42:27:8962] I: _lws_routing_table_dump: 
[2021/11/12 07:42:27:8962] I: _lws_routing_entry_dump:  gw: 10.240.0.20,  ifidx: 2, pri: 1, proto: 20
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  dst: 127.0.0.0/8,  ifidx: 1, pri: -1, proto: 3
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  src: 10.240.2.213/0,  ifidx: 2, pri: -1, proto: 2
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  src: 127.0.0.1/0,  ifidx: 1, pri: -1, proto: 2
[2021/11/12 07:42:27:8963] I: _lws_routing_entry_dump:  dst: ::1/128,  ifidx: 1, pri: 0, proto: 2
[2021/11/12 07:42:27:8964] I: _lws_routing_entry_dump:  dst: 2001::10/128,  ifidx: 4, pri: 1, proto: 2
[2021/11/12 07:42:27:8964] I: _lws_routing_entry_dump:  dst: fe80::215:adff:fe2f:fbe0/128,  ifidx: 2, pri: 256, proto: 2

```
It is still not found on the _lws_routing_table_dump.


```
[2021/11/12 08:00:40:1281] I: lws_header_table_attach: did attach wsi [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: ah 0xffffb002f210: count 1 (on exit)
[2021/11/12 08:00:40:1281] D: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: __lws_set_timeout: 10 secs, reason 25
[2021/11/12 08:00:40:1281] D: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_http_client_connect_via_info2: stash 0xffffb002f130
[2021/11/12 08:00:40:1281] D: _realloc: size 31: strdup
[2021/11/12 08:00:40:1281] D: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_client_connect_2_dnsreq: new conn on no pipeline flag
[2021/11/12 08:00:40:1281] D: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lwsi_set_state: lwsi_set_state 0x10000200 -> 0x10000201
[2021/11/12 08:00:40:1282] I: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_client_connect_2_dnsreq: lookup fe80::2fb5:f34e:deb0:25a4%eth0:66857
[2021/11/12 08:00:40:1283] I: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_getaddrinfo46: getaddrinfo 'fe80::2fb5:f34e:deb0:25a4%eth0' says 0
[2021/11/12 08:00:40:1283] I: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_sort_dns: sort_dns: 0xffffb002e6a0
[2021/11/12 08:00:40:1283] D: _realloc: size 144: lws_sort_dns
[2021/11/12 08:00:40:1284] I: [wsicli|0|WS/h1/default/fe80::2fb5:f34e:deb0:25a4%eth0]: lws_sort_dns: unsorted entry (af 10) fe80::2fb5:f34e:deb0:25a4
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 2, pri 1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri -1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri -1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri -1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri -1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri -1
[2021/11/12 08:00:40:1284] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri 0
[2021/11/12 08:00:40:1285] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri 1
[2021/11/12 08:00:40:1285] D: _lws_route_est_outgoing: dest af 10, rou gw af 0, pri 256
[2021/11/12 08:00:40:1285] I: _lws_route_est_outgoing: returning (nil)
```

Could it be related to load the Ipv6 gateway?
I saw in the lib code
lws_route_t *
```
_lws_route_est_outgoing
...
 		/*
			 *  dest  gw
			 *   4     4    OK
			 *   4     6    OK with ::ffff:x:x
			 *   6     4    not supported directly
			 *   6     6    OK
			 */
```
But there was no Gateway v6 loaded.

**Comment by lws-team** [comment]
Maybe, it works here OK between two machines with link-local, but

1) I have an ipv6 gateway, it looks like

```
::/0                           fe80::baba:e15d:a7a1:d8db  UG   20100 9     0 eth0
```

2) I tell it to connect via that interface

```
./bin/lws-minimal-http-client --server fe80::baba:e15d:a7a1:d8db%eth0  -p 7681 --nossl
```

I think for link-local (only) he should be able also to work without an explicit gateway route, but lws may be insisting to see it atm.

**Comment by cristianly** [comment]
Many thanks for your support, I tested and it worked well if we point out the interface for link-local IPv6. Both versions of libwebsocket 4.2.1 and 4.3
