### ISSUE TITLE
using static lib by pkg-config

### ISSUE THREAD

**Issue by horchi** [warmcat/libwebsockets#2517]
While building and installing libwebsockets also a static lib ist installed (which I like to use):
`-rw-r--r-- 1 root root 859K Dez  8 11:43 /usr/local/lib/libwebsockets.a`

Is there a way using this by pkg-config?
I tried 
```
#> pkg-config --static --libs libwebsockets
-L/usr/local/lib -lwebsockets -lcap

#> pkg-config --static libwebsockets
```
also libs-only-other did not show alt least the libcap:
`#>pkg-config --libs-only-other libwebsocket`
this would help to build the static dependencies manually 

Thx and best regards

**Comment by horchi** [comment]
workaround
```
LIBS += $(shell pkg-config --libs libwebsockets | sed -e 's/ -lwebsockets//g')
LIBS += -l:libwebsockets.a

```

**Comment by lws-team** [comment]
Thanks for sharing the workaround.

**Comment by horchi** [comment]
Is a fix planned?

**Comment by lws-team** [comment]
Could you possibly provide a patch?  If not helping me understand the implications of why the workaround works without blocking out a chunk of time to research it will help.

**Comment by horchi** [comment]
`pkg-config --libs` returns the libraries needed to link with libwebsockets, that works so far.

According to the documentation (man pkg-config) `pkg-config --static` should return everything needed to link with the static libwebsockets:
```
 --static  Output  libraries  suitable for static linking.  That means including any private libraries in the output.  This relies on proper tagging in the .pc files, else a too large number of libraries will ordinarily be output.
```
So I assumed that this gets the linker flags with which you bind against the libwebsocks.a like
```
#> pkg-config --static --libs libwebsockets
-L/usr/local/lib -l:libwebsockets.a -lcap
```
But possibly I interpret this wrongly?

Thanks and best regards Jörg

**Comment by lws-team** [comment]
No I think your understanding isn't wrong.

It's like the guy with one arm and the guy with one leg, you have the correct output after a sed but don't know how to make CMake produce it, I can probably figure that part out but I don't understand what needs to change in the output.

Maybe show a diff of the current lws.pc output that is wrong, and the right output after the sed has done whatever it is?

**Comment by horchi** [comment]
With `pkg-config --static --libs libwebsockets` I get
`-L/usr/local/lib -lwebsockets -lcap`

But for static linking this is needed:
`-L/usr/local/lib -l:libwebsockets.a -lcap`
Therefore I remove remove `libwebsockets` by sed and and append `-l:libwebsockets.a` in the next line.

To what extent this is the task of pkg-config I unfortunately also do not know.

I'm not using cmake I'm using make directly.

**Comment by lws-team** [comment]
Thanks... the .pc is issued by lws CMake that's why I mention it.  Any fix will go in lws CMakeLists.txt.

I am getting the idea in fact the .pc is OK as it is for dynamic linking case, and what is needed, is to issue a second .pc as well, like libwebsockets-static.pc or something with the `:` in.  Would that actually solve it?

**Comment by horchi** [comment]
yes a libwebsockets-static.pc sounds perfect for me! 
Many Thanks!

**Comment by lws-team** [comment]
It already produces a libwebsockets_static.pc, it just doesn't have the right string in there.  How about this

```
diff --git a/lib/CMakeLists.txt b/lib/CMakeLists.txt
index 4207d9472b..8d21c12401 100644
--- a/lib/CMakeLists.txt
+++ b/lib/CMakeLists.txt
@@ -343,7 +343,7 @@ Name: libwebsockets_static
 Description: Websockets server and client static library
 Version: ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}
 
-Libs: -L\${libdir} -lwebsockets_static
+Libs: -L\${libdir} -l:libwebsockets${CMAKE_STATIC_LIBRARY_SUFFIX}
 Libs.private:
 Cflags: -I\${includedir}
 "
```

**Comment by horchi** [comment]
Thx! I will check it at least today evening, actually I have many meetings

**Comment by horchi** [comment]
sorry you are right! It was my fault, I hadn't noticed that the patch failed 
patching file CMakeLists.txt
Hunk #1 FAILED at 343.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej

**Comment by lws-team** [comment]
The patch is against main, anyway the change is the same ov v4.3-stable... if you did it manually, so it should also act well.

**Comment by lws-team** [comment]
Great, thanks for the help.

**Comment by horchi** [comment]
By the way ... I'm using your lib for this project: https://github.com/horchi/linux-p4d
