### ISSUE TITLE
Question related to multiple lws_service threads

### ISSUE THREAD

**Issue by chill1n** [warmcat/libwebsockets#2518]
The documentation states:
```
lws_service_tsi() - Service any pending websocket activity

Same as lws_service(), but for a specific thread service index. Only needed if you are spawning multiple service threads.
```

So is this call needed instead of lws_service() if I use one lws_service() loop per thread each with a unique lws_context per thread?

**Comment by lws-team** [comment]
Yes, refer to the minimal example

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-smp/minimal-http-server-eventlib-smp.c?h=main

**Comment by chill1n** [comment]
Thanks. That example shows the use of two lws_service_tsi() threads working with a *single* (static) lws_context. So it's not the same as a unique lws_context per thread.

**Comment by chill1n** [comment]
I think that the documentation could be improved to make this (explicitly) clear.

**Comment by lws-team** [comment]
Yes that is different, you don't need to handle pt /tsi at all if n contexts each with the default of one pt and their own event loop thread.

Lws is foss, if you want to improve the docs patches are welcome on that too, if it will reduce the support burden.

**Comment by chill1n** [comment]
I will send a PR for two doc improvements then.
