### ISSUE TITLE
Log file spammed with "N: lws_gate_accepts: on = 0"

### ISSUE THREAD

**Issue by chill1n** [warmcat/libwebsockets#2519]
By default the lws log setting generates many lines such as
```
N: lws_gate_accepts: on = 0
```
appearing on the console, or in a log file. They seem meaningless without context, and they don't seem to deserve log level N.
Proposal to lower the log level and add more context to this message.

**Comment by lws-team** [comment]
I pushed a patch on main, but isn't it quicker to just provide a patch than raise an issue and write it up?

**Comment by chill1n** [comment]
Not if it's not clear what the best solution is. But thanks for the quick fix anyway.
