### ISSUE TITLE
Bundled libraries

### ISSUE THREAD

**Issue by fabaff** [warmcat/libwebsockets#252]
The reviewer pointed out that libwebsockets contains bundled libraries. A requirement for Fedora packages is that there are no bundled libraries (https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries). It's possible to get an exception but perhaps it's faster/easier to get this fixed in libwebsockets.

The elements in question are:
- sha-1.c
- base64-decode.c
- ssl-http2.c

The review request https://bugzilla.redhat.com/show_bug.cgi?id=1198498 for details.

**Comment by warmcat** [comment]
Okay I'll discuss on the bugzilla.  Because there is no library that does what my http2 code does, and base64 and even sha1 are trivial.
