### ISSUE TITLE
high cpu usage on windows when idle

### ISSUE THREAD

**Issue by liberize** [warmcat/libwebsockets#2524]
I noticed 16-17% cpu usage on windows even when idle.

CPU profiling shows that WSAPoll used most of the cpu.

It seems lws_service_adjust_timeout always return zero on this line:

https://github.com/warmcat/libwebsockets/blob/51a0aee903f81bdb453c7f79d8efe8a1dfa0416f/lib/plat/windows/windows-service.c#L154

Trace down to this line:

https://github.com/warmcat/libwebsockets/blob/51a0aee903f81bdb453c7f79d8efe8a1dfa0416f/lib/core-net/service.c#L325

u is zero, so timeout_ms is set to zero too.

Similar to this line, but doesn't check if u is zero:

https://github.com/warmcat/libwebsockets/blob/51a0aee903f81bdb453c7f79d8efe8a1dfa0416f/lib/plat/windows/windows-service.c#L135

Is this the problem?

**Comment by liberize** [comment]
I changed to  `if (u && u < (lws_usec_t)timeout_ms * (lws_usec_t)1000)`.

The cpu usage is zero now.

**Comment by lws-team** [comment]
Thanks for looking into it... it seems you're right, it must check for that.  It doesn't "fail" without it but just won't spend time in the wait and keep waking.

I pushed your change on main, it'll go in v4.3-stable later.
