### ISSUE TITLE
Build for ESP32

### ISSUE THREAD

**Issue by matthias122** [warmcat/libwebsockets#2528]
Hi
I'm trying to build latest libwebsockets for ESP32 with latest ESP-IDF on a Windows PC.
I get a error regarding CMake command.
Could you please help.
 CMake Error at
  */esp-idf/components/libwebsockets/CMakeLists.txt:74 (project):
  project command is not scriptable

  Call Stack (most recent call first):

    */esp-idf/tools/cmake/scripts/component_get_requirements.cmake:106 (include)
  */esp-idf/tools/cmake/scripts/component_get_requirements.cmake:124 (__component_get_requirements)

Call Stack (most recent call first):
  */esp-idf/tools/cmake/build.cmake:494 (__component_get_requirements)
*/esp-idf/tools/cmake/project.cmake:382 (idf_build_process)
  CMakeLists.txt:6 (project)

**Comment by lws-team** [comment]
Lws doesn't need to go into esp-idf components any more.

1) First navigate to the esp-idf dir and just use `. ./export,sh` to set up your shell session to be able to use idf.py

2) Eg, copy the provided example for wrover kit somewhere to be the basis of your test project

```
 $ cp -rp /projects/libwebsockets/minimal-examples/embedded/esp32/esp-wrover-kit /tmp/mytest
 $ cd /tmp/mytest
```

3) Symlink to lws

```
 $ ln -sf /projects/libwebsockets libwebsockets
```

4) Build the test app

```
$ idf.py build
```

**Comment by matthias122** [comment]
Sorry I'm working on a Windows PC. Symlinks are not available under Windows. Is there a defined Way to build on a Windows PC?

**Comment by lws-team** [comment]
You can just copy or git clone libwebsockets into /tmp/mytest/libwebsockets

**Comment by lws-team** [comment]
... where `/tmp/mytest` is whatever, it's not important.

**Comment by matthias122** [comment]
Ok Thanks for your help.
I will get some steps forward. But I still get an error at ESP-IDF compilation
In file included from F:/Espressif/esp-idf/components/lwip/port/esp32/include/lwipopts.h:18,
                 from F:/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/opt.h:51,
                 from F:/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/errno.h:40,
                 from ../libwebsockets/lib/core/./private-lib-core.h:60,
                 from ../libwebsockets/lib/plat/freertos/freertos-init.c:25:
F:/Espressif/esp-idf/components/esp_system/include/esp_task.h:32:10: fatal error: freertos/FreeRTOS.h: No such file or directory
 #include "freertos/FreeRTOS.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Could you please help?

**Comment by lws-team** [comment]
> But I still get an error at ESP-IDF compilation

FWIW it's compiling lws pieces there.  

> freertos/FreeRTOS.h: No such file or directory

My esp-idf was from August and built OK, updating to today's HEAD I get a similar problem.  It was OK after doing set-target again, restoring sdkconfig from the lws version and rebuilding after this patch

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5d45faaa5d..549ff54873 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -82,6 +82,10 @@ if (ESP_PLATFORM)
        include_directories(
 		$ENV{IDF_PATH}/components/esp_hw_support/include/soc/
 		$ENV{IDF_PATH}/components/freertos/include/
+		$ENV{IDF_PATH}/components/freertos/esp_additions/include/
+		$ENV{IDF_PATH}/components/freertos/esp_additions/include/freertos/
+		$ENV{IDF_PATH}/components/freertos/FreeRTOS-Kernel/include/
+		$ENV{IDF_PATH}/components/freertos/FreeRTOS-Kernel/portable/linux/include/
 		$ENV{IDF_PATH}/components/xtensa/${CONFIG_IDF_TARGET}/include/
 		$ENV{IDF_PATH}/components/freertos/include/esp_additions
 		$ENV{IDF_PATH}/components/hal/include
@@ -825,6 +829,10 @@ if (CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX OR COMPILER_IS_CLANG)
 		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Wno-unused-parameter -Wconversion -Wsign-compare -Wstrict-aliasing -Wundef -nolibc")
 	endif()
 
+	if (ESP_PLATFORM AND (CONFIG_IDF_TARGET_ESP32 OR CONFIG_IDF_TARGET_ESP32S2 OR CONFIG_IDF_TARGET_ESP32S3))
+		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mlongcalls")
+	endif()
+
 	if ("${DISABLE_WERROR}" STREQUAL "OFF")
 		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
 	endif()
diff --git a/lib/drivers/button/lws-button.c b/lib/drivers/button/lws-button.c
index e937db6f61..43456fb541 100644
--- a/lib/drivers/button/lws-button.c
+++ b/lib/drivers/button/lws-button.c
@@ -471,8 +471,8 @@ lws_button_controller_destroy(struct lws_button_state *bcs)
 	lws_button_enable(bcs, 0, 0);
 
 #if defined(LWS_PLAT_TIMER_DELETE)
-	LWS_PLAT_TIMER_DELETE(&bcs->timer);
-	LWS_PLAT_TIMER_DELETE(&bcs->timer_mon);
+	LWS_PLAT_TIMER_DELETE(bcs->timer);
+	LWS_PLAT_TIMER_DELETE(bcs->timer_mon);
 #endif
 
 	lws_free(bcs);
diff --git a/lib/drivers/led/led-gpio.c b/lib/drivers/led/led-gpio.c
index 664a120c73..382c3e6305 100644
--- a/lib/drivers/led/led-gpio.c
+++ b/lib/drivers/led/led-gpio.c
@@ -81,7 +81,7 @@ void
 lws_led_gpio_destroy(struct lws_led_state *lcs)
 {
 #if defined(LWS_PLAT_TIMER_DELETE)
-	LWS_PLAT_TIMER_DELETE(&lcs->timer);
+	LWS_PLAT_TIMER_DELETE(lcs->timer);
 #endif
 	lws_free(lcs);
 }
```

**Comment by lws-team** [comment]
... I assume that solved it for you too...
