### ISSUE TITLE
hint to example for serving multiple vhosts

### ISSUE THREAD

**Issue by horsth** [warmcat/libwebsockets#2530]
I would want to have a server, that can accept websocket connections on different tcp ports with different TLS credentials.
Is there an example available for something similar to that?
I tried to search documentation and issues and found https://github.com/warmcat/libwebsockets/issues/2217#issuecomment-786254817 but it seems the example, that was referenced there does not exist any more.

Would the server for these different websocket connections be possible in single thread or would the different ports need to be served by multiple threads?

**Comment by lws-team** [comment]
Older Examples moved to minimal-examples-lowlevel on main.  So

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-multivhost?h=main

You can do what you want even on the same tcp port, tls ALPN will route you to the right one by matching the hostname to the vhost's name on the server.

Everything can live in the same lws_context on the same event loop / thread.

**Comment by horsth** [comment]
Hello Team,

thank you, this was a fast answer indeed!

I am afraid it will take me much more time to consume the answer and under stand the sample.

best regards,

Horst
