### ISSUE TITLE
[Request] Feature to add suffix to http_url in policy.json when using ss-ws

### ISSUE THREAD

**Issue by bellwood420** [warmcat/libwebsockets#2531]
Hi,

I just started developing a websocket client using secure streams(ss-ws).
It connects to some third party server which requires onetime random key in path like `wss://someserver/some/path/{KEY}`

The key is obtained by authenticating through https communication in advance.
And the key becomes invalid after a certain period of time, so, for keeping to be connected, I will need to retrieve new one and reconnect to another path on disconnection.

In `policy.json`, I define
```
...
"http_url": "some/path/"
...
```
Now I'm not able to append the `{KEY}` to `http_url` at runtime when I use ss-ws. 
It seems that there is no way to mod the `path` of `struct lws_client_connect_info` generated inside the secure streams API from outside of it.

Of course, it can be achieved by creating `struct lws_client_connect_info` and handling all events by myself, but then I won't get the benefit of abstractive secure streams API layer.

For now, I am managing it by applying the following quick-and-dirty patch (to v4.3-stable).
But hopefully an official solution will be implemented.

```
diff --git a/include/libwebsockets/lws-secure-streams.h b/include/libwebsockets/lws-secure-streams.h
index 8157c700..4c7c50b5 100644
--- a/include/libwebsockets/lws-secure-streams.h
+++ b/include/libwebsockets/lws-secure-streams.h
@@ -842,5 +842,8 @@ lws_aws_filesystem_credentials_helper(const char *path, const char *kid,
 
 #endif
 
+LWS_VISIBLE LWS_EXTERN void
+lws_ss_ws_set_url_suffix(struct lws_ss_handle *h, const char *suffix);
+
 ///@}
 
diff --git a/lib/secure-streams/private-lib-secure-streams.h b/lib/secure-streams/private-lib-secure-streams.h
index 6af59e47..a767a291 100644
--- a/lib/secure-streams/private-lib-secure-streams.h
+++ b/lib/secure-streams/private-lib-secure-streams.h
@@ -194,6 +194,7 @@ typedef struct lws_ss_handle {
 	uint8_t			inside_connect:1; /* set if we are currently
 						   * creating the onward
 						   * connect */
+	char			*ws_url_suffix;
 } lws_ss_handle_t;
 
 /* connection helper that doesn't need to hang around after connection starts */
diff --git a/lib/secure-streams/protocols/ss-ws.c b/lib/secure-streams/protocols/ss-ws.c
index eed62c5b..2f812597 100644
--- a/lib/secure-streams/protocols/ss-ws.c
+++ b/lib/secure-streams/protocols/ss-ws.c
@@ -237,6 +237,12 @@ secstream_connect_munge_ws(lws_ss_handle_t *h, char *buf, size_t len,
 			      &used_in, &used_out) != LSTRX_DONE)
 		return 1;
 
+	if (h->ws_url_suffix) {
+		if (lws_strexp_expand(&exp, h->ws_url_suffix, strlen(h->ws_url_suffix),
+							  &used_in, &used_out) != LSTRX_DONE)
+			return 1;
+	}
+
 	i->protocol = h->policy->u.http.u.ws.subprotocol;
 
 	lwsl_ss_info(h, "url %s, ws subprotocol %s", buf, i->protocol);
diff --git a/lib/secure-streams/secure-streams.c b/lib/secure-streams/secure-streams.c
index 489543db..6e7785ca 100644
--- a/lib/secure-streams/secure-streams.c
+++ b/lib/secure-streams/secure-streams.c
@@ -1837,3 +1837,9 @@ lws_ss_assert_extant(struct lws_context *cx, int tsi, struct lws_ss_handle *h)
 	assert(0);
 }
 #endif
+
+void
+lws_ss_ws_set_url_suffix(struct lws_ss_handle *h, const char *suffix)
+{
+	h->ws_url_suffix = suffix;
+}
```

**Comment by lws-team** [comment]
> I just started developing a websocket client using secure streams(ss-ws).

Nice.

> Now I'm not able to append the {KEY} to http_url at runtime when I use ss-ws.

SS has a generic way to handle this, known as "metadata". It's able to operate after the initial connection request.

You can use it a couple of ways... the first is define explicit metadata policy bindings from your metadata name to protocol-specific items like http headers... you want this style when your auth travels in a header on http / ws.  You declare a metadata section in the streamtype policy like

```
...
      "metadata":         [
              { "uptag":   "X-Upload-Tag:" },
      ],
...
```

and whatever you set the "uptag" metadata to goes out on an X-Upload-Tag: header.

For your case, you can also use expandable substrings with ${mysymbol} in the policy endpoint or path string, define a metadata symbol for the streamtype with an empty protocol mapping


```
...
      "metadata":         [
              { "myauth":   "" },
      ],
...
```

and set the metadata for the stream, eg, at CREATING state.

```
int LWS_WARN_UNUSED_RESULT
lws_ss_set_metadata(struct lws_ss_handle *h, const char *name,
                    const void *value, size_t len);
```

There's some documentation about SS policy possibilities here

https://libwebsockets.org/git/libwebsockets/tree/lib/secure-streams

and `./include/libwebsockets/lws-secure-streams.h` has more docs on the metadata apis.

**Comment by bellwood420** [comment]
Thank you so much for your prompt and detailed response to my noob question.

By using metadata you showed me, my issue was easily solved in official way :)
