### ISSUE TITLE
LWS_CALLBACK_CLIENT_CONNECTION_ERROR : DNS NXDOMAIN

### ISSUE THREAD

**Issue by p-i-** [warmcat/libwebsockets#2532]
I'm using libwebsockets to establish a websocket connection with wss://ws-api.kucoin.com/endpoint

However, I'm hitting against this error:
```
[2021/12/30 08:33:44:9929] N: lws_create_context: LWS: 4.3.0-v4.3.0-79-g141ebf37, NET CLI SRV H1 H2 WS ConMon IPv6-absent
[2021/12/30 08:33:44:9929] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2021/12/30 08:33:44:9929] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2021/12/30 08:33:44:9930] N: __lws_lc_tag:  ++ [vh|1|default||-1] (2)
[2021/12/30 08:33:44:9931] N: __lws_lc_tag:  ++ [wsicli|0|WS/h1/default/wss://ws-api.kucoin.com/endpoint] (1)
LWS_CALLBACK_CLIENT_CONNECTION_ERROR : DNS NXDOMAIN
[2021/12/30 08:33:45:0071] N: __lws_lc_untag:  -- [wsicli|0|WS/h1/default/wss://ws-api.kucoin.com/endpoint] (0) 13.999ms
```

NOTE: I am able to successfully get wss stream from binance, so this must narrow down the scope for error. I'm adapting the (working Binance) code to attenpt to connect to kucoin websockets.

Documentation for kucoin websockets is here: https://docs.kucoin.com/#websocket-feed 
Following this doc, first step is to get a token:
```
> curl -i -X POST  https://api.kucoin.com/api/v1/bullet-public
{"code":"200000","data":{"token":"2ne..7vA==","instanceServers":[{"endpoint":"wss://ws-api.kucoin.com/endpoint","encrypt":true,"protocol":"websocket","pingInterval":18000,"pingTimeout":10000}]}}
```

These values are then used when establishing a connection to the websocket:
```
        BinaCPP_websocket::init();
        struct lws * connection = 
        BinaCPP_websocket::connect_endpoint(ondata,
            ("?""token=" + token + "&""[connectId="+ connect_id + "]").c_str(),
            endpoint.c_str(),//"wss://push1-v2.kucoin.com/endpoint" "ws://echo.websocket.org"
            443
        );
```

Error is coming from within that `connect_endpoint` call.  Code is taken from https://github.com/tensaix2j/binacpp/blob/master/src/binacpp_websocket.cpp#L118
```
/* Connect if we are not connected to the server. */
  struct lws_client_connect_info ccinfo = {0};
  ccinfo.context   = context;
  ccinfo.address   = ws_host;
  ccinfo.port   = port;
  ccinfo.path   = ws_path;
  ccinfo.host   = lws_canonical_hostname( context );
  ccinfo.origin   = "origin";
  ccinfo.protocol = protocols[0].name;
  ccinfo.ssl_connection = (use_ssl ? LCCSCF_USE_SSL : 0) | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;

  struct lws* conn = lws_client_connect_via_info(&ccinfo);
```
^ `lws_client_connect_via_info` is returning `NULL`

(ref: [lws_client_connect_via_info](https://github.com/warmcat/libwebsockets/blob/v4.3-stable/lib/core-net/client/connect.c#L128))

The host-machine is able to DNS-resolve ws-api.kucoin.com (confirmed by `dig ws-api.kucoin.com`)

Also a Python implementation based from `kucoin-python` (https://github.com/Kucoin/kucoin-python-sdk) is working on the same machine.

So, one question is: What is the Python implementation doing correctly that the C++ implementation is doing incorrectly?

**Comment by lws-team** [comment]
> [wsicli|0|WS/h1/default/wss://ws-api.kucoin.com/endpoint] (1)

If you tell lws the DNS address is **wss://** ws-api-kucoin.com, it is going to hear from the resolver that is NXDOMAIN and pass that information back up to you.  Dig would do exactly the same.

**Comment by vinifr** [comment]
The address should be:
ccinfo.address 	= "wss://push1-v2.kucoin.com";
And the path:
ccinfo.path 	= "/endpoint";

So do not mix addres with path.

**Comment by vinifr** [comment]
> Yes... but the address also should be just the hostname, so `"push1-v2.kucoin.com"`.

In this case, how do I define if is "wss://host.com" or "ws://host.com" ?

**Comment by lws-team** [comment]
Your hostname, as needed for dns and for matching the tls certificate, is only `host.com`.

You can remove the wss:// by your own code before.
