### ISSUE TITLE
Failed to Succesfully Build the LWS on WIndows Visual Studio 15with multiple errors 

### ISSUE THREAD

**Issue by GliderFromNorth** [warmcat/libwebsockets#2538]
Dear LWS Team,

I am trying to Build this AWS 4.3 stable version for almost two weeks I am facing difficulties building the project after successfully converting source code to project using cmake.
let me guide you on what I have done so far.
1 Downloaded source code from [HERE](https://github.com/warmcat/libwebsockets/tree/v4.3-stable). 
2 Using CMAKE I build the project with CMAKE configuration as Mentioned Below.
    Inside root directory of libwebsocket

- md build
- cd build
- cmake -DLWS_WITH_STATIC=1 -DLWS_WITH_SHARED=0 -DCMAKE_GENERATOR_PLATFORM=x64 ..
- now after opening libwebsocket.sln file When I am trying to build the project with Release/Debug 64x bit OS. 
I am Facing tons of errors still failing to successfully build the project. moving ahead I'll be mentioning the errors and solution I did to rectify. 

1. C2079	'ctx' uses undefined struct 'hmac_ctx_st'   ---- Solved by changing 
    #if defined(LWS_HAVE_HMAC_CTX_new)
        HMAC_CTX *ctx;
     #else
        HMAC_CTX ctx;
     #endif
To..................................................................

    #if defined(LWS_HAVE_HMAC_CTX_new)
        HMAC_CTX *ctx = HMAC_CTX_new();
     #else
        HMAC_CTX *ctx;
     #endif
2. LNK1104 cannot open file '..\lib\Debug\websockets_static.lib' test-lejp    ------ Not Solved
3. LNK1104 cannot open file '..\lib\Debug\websockets_static.lib' test-client  ------ Not Solved
4. LNK1104 cannot open file '..\lib\Debug\websockets_static.lib' test-server  ------ Not Solved
5. Error C2220 warning treated as error - no 'object' file generated websockets  -------Even after updating the changes in visual studio for given project like changing it to NO, trat warning as error as NO... Still I am facing the same warning error. 

Kindly help me rectify these issues with setting and project... 

####################################Logs for Reference#####################################################
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
2>------ Build started: Project: GENHDR, Configuration: Debug x64 ------
3>------ Skipped Build: Project: Continuous, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: Experimental, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: Nightly, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: dist, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration 
2>  Creating build include dir
2>  Building Custom Rule D:/libwebsockets-4.3-stable/CMakeLists.txt
9>------ Build started: Project: websockets, Configuration: Debug x64 ------
9>  Building Custom Rule D:/libwebsockets-4.3-stable/lib/CMakeLists.txt
9>cl : Command line warning D9002: ignoring unknown option '/Zc:preprocessor'
9>cl : Command line warning D9002: ignoring unknown option '/experimental:preprocessor'
9>  windows-fds.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-file.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-init.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-misc.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-pipe.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-plugins.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-service.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  windows-sockets.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  gettimeofday.c
9>  tls.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  tls-network.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  tls-sessions.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-tls.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-x509.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-ssl.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-session.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  tls-server.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-server.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  tls-client.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  openssl-client.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>D:\libwebsockets-4.3-stable\lib\tls\openssl\openssl-client.c(778): warning C4013: 'EVP_MD_CTX_destroy' undefined; assuming extern returning int
9>  Generating Code...
9>  Compiling...
9>  alloc.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  buflist.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  context.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lws_dll2.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lws_map.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  libwebsockets.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  logs.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  vfs.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  base64-decode.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  prng.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lws-ring.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lws-cache-ttl.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  heap.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  file.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  dir.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lwsac.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  cached-file.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  sha-1.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lejp.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  system.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  Generating Code...
9>  Compiling...
9>  dummy-callback.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  output.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  close.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  network.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  vhost.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  pollfd.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  service.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  sorted-usec-list.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  wsi.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  wsi-timeout.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  adopt.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-pipe.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  state.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  client.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  connect.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  connect2.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  connect3.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  connect4.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  sort-dns.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  conmon.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  Generating Code...
9>  Compiling...
9>  header.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  date.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  parsers.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  server.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lws-spa.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  cookie.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  lejp-conf.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-h1.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  http2.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  hpack.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-h2.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-ws.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  client-ws.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  client-parser-ws.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>D:\libwebsockets-4.3-stable\lib\roles\ws\client-parser-ws.c(480): warning C4003: not enough actual parameters for macro 'lwsl_hexdump_wsi'
9>D:\libwebsockets-4.3-stable\lib\roles\ws\client-parser-ws.c(480): error C2059: syntax error: ')'
9>D:\libwebsockets-4.3-stable\lib\roles\ws\client-parser-ws.c(598): warning C4003: not enough actual parameters for macro 'lwsl_hexdump_wsi'
9>D:\libwebsockets-4.3-stable\lib\roles\ws\client-parser-ws.c(598): error C2059: syntax error: ')'
9>  server-ws.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-raw-skt.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-raw-file.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  ops-listen.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  client-http.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  poll.c
9>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
9>  Generating Code...
10>------ Build started: Project: test-client, Configuration: Debug x64 ------
11>------ Build started: Project: test-lejp, Configuration: Debug x64 ------
12>------ Build started: Project: test-server, Configuration: Debug x64 ------
10>  Building Custom Rule D:/libwebsockets-4.3-stable/test-apps/CMakeLists.txt
10>cl : Command line warning D9002: ignoring unknown option '/Zc:preprocessor'
10>cl : Command line warning D9002: ignoring unknown option '/experimental:preprocessor'
10>  test-client.c
11>  Building Custom Rule D:/libwebsockets-4.3-stable/test-apps/CMakeLists.txt
12>  Building Custom Rule D:/libwebsockets-4.3-stable/test-apps/CMakeLists.txt
11>cl : Command line warning D9002: ignoring unknown option '/Zc:preprocessor'
11>cl : Command line warning D9002: ignoring unknown option '/experimental:preprocessor'
11>  test-lejp.c
12>cl : Command line warning D9002: ignoring unknown option '/Zc:preprocessor'
12>cl : Command line warning D9002: ignoring unknown option '/experimental:preprocessor'
12>  test-server.c
10>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
10>  getopt.c
10>  getopt_long.c
10>  gettimeofday.c
11>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
11>  getopt.c
11>  getopt_long.c
12>D:\libwebsockets-4.3-stable\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
12>  getopt.c
11>  gettimeofday.c
12>  getopt_long.c
12>  gettimeofday.c
10>  Generating Code...
11>  Generating Code...
12>  Generating Code...
13>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
13>  Building Custom Rule D:/libwebsockets-4.3-stable/CMakeLists.txt
14>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
14>Project not selected to build for this solution configuration 
15>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
15>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 4 failed, 0 up-to-date, 8 skipped ==========

**Comment by lws-team** [comment]
So... lws builds on 30 platforms in CI, here is current main building fine on windows 10 + msvc

https://libwebsockets.org/sai/index.html?task=de1e633023ac1ba71ba4d44b000d1cf50b673e988eca8dbaf2cd0ed4abc2fc21

There's a long list of what I did to makethe windows build work in the READMEs

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md?h=main

> C2079 'ctx' uses undefined struct 'hmac_ctx_st' ---- Solved by changing

No that was already correct.

You should look at the second section of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md?h=main

and follow the suggestion there to find out what actually happened when cmake tried to find out if `LWS_HAVE_HMAC_CTX_new()` is available from your openssl or not... it seems it could not build that test for some other reason and that will tell you what is actually wrong.

**Comment by lws-team** [comment]
... any progress?
