### ISSUE TITLE
How to make the memory occupied by the program as small as possible? Can the startup parameters be set?

### ISSUE THREAD

**Issue by kunknu** [warmcat/libwebsockets#2539]
How to make the memory occupied by the program as small as possible? Can the startup parameters be set?
thank u very much

**Comment by lws-team** [comment]
When you create the context, you can control many settings at runtime.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h?h=main#n274

For lws heap allocations, you can get a log for each with the size and a string indicating what it is for, often the function name it being being allocated in.  The best way to go about optimizing heap is to hack these logs to come at eg, lws_notice()

https://libwebsockets.org/git/libwebsockets/tree/lib/core/alloc.c?h=main#n113-123

and look at the nontrivial ones in the code for how to tune them at context creation or other time.  It is able to log allocations with a size, but not free()s, but that's enough to triage what will return the effort.
