### ISSUE TITLE
Protocol name buffer is too small

### ISSUE THREAD

**Issue by kolis** [warmcat/libwebsockets#254]
The protocol name buffer is hardcoded in ```lws_handshake_server```

```
	char protocol_name[32];
```

any protocol name longer than this will fail during handshake. I'm not sure what a proper max length should be, maybe 1024, or some configuration variable? Right now I want to use an JWT token (http://jwt.io/) as protocol name, as a form of authentication.

**Comment by warmcat** [comment]
You'll need to hack the length, reserving 1K for the name is too bloaty for everyone else I think.
