### ISSUE TITLE
Invalid logic in LWS_TLS_CERT_INFO_COMMON_NAME

### ISSUE THREAD

**Issue by pavelxdd** [warmcat/libwebsockets#2542]
If x509 has other attributes after CN, libwebsockets will incorretly parse the common name attribute:
https://github.com/warmcat/libwebsockets/blob/9ef74f83d44ccee776ada14c4a610ef7f544f94c/lib/tls/openssl/openssl-x509.c#L130-L133

Because it copies everything that comes after `/CN=`, but there could be other attributes after it, for example email address. In this case LWS will return `*MY_COMMON_NAME*/emailAddress=test@example.com` for common name.

You can use this command and set Country, Common Name and Email attributes to reproduce this issue:
`openssl req -new -x509 -sha512 -days 1826 -key ca.key -out ca.crt`

**Comment by lws-team** [comment]
How about this?

```
diff --git a/lib/tls/openssl/openssl-x509.c b/lib/tls/openssl/openssl-x509.c
index dac4aa3915..8e42fcb0fc 100644
--- a/lib/tls/openssl/openssl-x509.c
+++ b/lib/tls/openssl/openssl-x509.c
@@ -89,7 +89,8 @@ lws_tls_openssl_cert_info(X509 *x509, enum lws_tls_cert_info type,
 #endif
        X509_NAME *xn;
 #if !defined(LWS_PLAT_OPTEE)
-       char *p;
+       char *p, *p1;
+       size_t rl;
 #endif
 
        buf->ns.len = 0;
@@ -128,8 +129,16 @@ lws_tls_openssl_cert_info(X509 *x509, enum lws_tls_cert_info type,
                        return -1;
                X509_NAME_oneline(xn, buf->ns.name, (int)len - 2);
                p = strstr(buf->ns.name, "/CN=");
-               if (p)
-                       memmove(buf->ns.name, p + 4, strlen(p + 4) + 1);
+               if (p) {
+                       p += 4;
+                       p1 = strchr(p, '/');
+                       if (p1)
+                               rl = lws_ptr_diff_size_t(p1, p);
+                       else
+                               rl = strlen(p);
+                       memmove(buf->ns.name, p, rl);
+                       buf->ns.name[rl] = '\0';
+               }
                buf->ns.len = (int)strlen(buf->ns.name);
                return 0;
 #endif
```

**Comment by pavelxdd** [comment]
Unfortunately, this will also work incorrect in case Common Name contains `/` inside, for example `cname/test=fdsfsdf`.

I think there should be more complex approach:

````
int get_common_name(X509_NAME *xn, char *buf, size_t len)
{
    int loc = X509_NAME_get_index_by_NID(xn, NID_commonName, -1);
    if (loc < 0)
        return -1;

    X509_NAME_ENTRY *entry = X509_NAME_get_entry(xn, loc);
    if (!entry)
        return -1;

    ASN1_STRING *cname = X509_NAME_ENTRY_get_data(entry);
    if (!cname)
        return -1;

    BIO *bio = BIO_new(BIO_s_mem());
    if (!bio)
        return -1;

    if (!ASN1_STRING_print_ex(bio, cname, 0)) {
        BIO_free(bio);
        return -1;
    }

    char *data;
    long size = BIO_get_mem_data(bio, &data);
    if (size <= 0 || (size_t)size >= len)
        return -1;

    lws_strncpy(buf, data, size);
    BIO_free(bio);
    return 0;
}
````

This works on OpenSSL 1.1.1m, I'm not sure if older versions of OpenSSL have all these methods. But it returns correct Common Name, and if needed it could be adapted to extract other certificate attributes by their NIDs.

**Comment by lws-team** [comment]
For tls host certs anyway, the consumers of the cert at the client have specific expectations of what's in CN... they want to see a dns hostname matching the dns name requested at the client.  This cannot contain '/' (which is why they use '/' as a delimiter for ancilliary data).

There are older openssl and openssl forks to contend with, it seems to me fixing what's there is the right way atm and isn't going to make anything worse.

If you want query-by-NID, that sounds interesting separately but as a new feature it wants a new public api and an implementation for mbedtls... if you're willing to help chew through the CI breakage (it tests older and forked openssls) a patch is very welcome.

**Comment by pavelxdd** [comment]
I am not sure I have time for this now, I simply reported what issues I found during my testing of fetching x509 attributes via libwebsockets. Eventually I've rewritten this in pure openssl methods in my project. If you think the approach with strchr('/') is enough for consumers, then it's fine by me.

**Comment by lws-team** [comment]
I went with the truncation scheme for now.
