### ISSUE TITLE
Question about the thread-safe APIs

### ISSUE THREAD

**Issue by wayneonway** [warmcat/libwebsockets#2549]
lws_callback_on_writable is still thread-safe? How to notify wsi the LWS_CALLBACK_CLIENT_WRITEABLE callback in another thread?

Mentioned in the README.coding.md of v4.3.-stable:
> The only lws api that's safe to call from other thread contexts is `lws_cancel_service()`.

compare with README.coding.md of v4.2-stable:
> Therefore the two apis mentioned above that may be used from another thread are
>  - For LWS using the default poll() event loop, `lws_callback_on_writable()`
>  - For LWS using libuv/libev/libevent event loop, `lws_cancel_service()`

**Comment by lws-team** [comment]
> lws_callback_on_writable is still thread-safe?

No.  Lws supports arbitrary underlying event libraries or custom event loop implementations that are non-threadsafe.

> compare with README.coding.md of v4.2-stable:

I wrote a big, friendly, detailed document about this situation and how to deal with it.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md?h=main
