### ISSUE TITLE
Not able to overwrite the function pointers inside library

### ISSUE THREAD

**Issue by madhanreddy433** [warmcat/libwebsockets#2552]
we are using LWS along with NATS, to support this we have added our own code in a new directory (ws-client) and merged it into the library. 
[WS]$ ls
cmake                           CMakeLists.txt  cscope.files  include  lib      Makefile.projbuild  websocket.sh
CMakeLists-implied-options.txt  component.mk    cscope.out    Kconfig  LICENSE  tags                **ws-client**

I also added ./include/libwebsockets/ws_client.h, and added all my API declarations here to access it outside by including this ws_client.h file.

now the issue is, I have declared few function pointers in ws_client.h and initialized with NULL and I am overwriting those functions from my process. I am able to access those function pointers and able to overwrite in in my process but same is not reflecting in the WS code.

I am trying to overwrite those function pointers but is not working, why is it so? same I tried with NATS Libraries it is working fine.

**Comment by lws-team** [comment]
> I am trying to overwrite those function pointers but is not working, why is it so?

Hm... this is asking me why your code, not lws code, "isn't working", right?  There's no reason I would magically know.

IIUI both the lib and the app are interested in this struct, if they can't agree that they are looking at the same thing, it sounds like the build of the lws lib and the build of the app might not agree about the definition of the struct.  Eg, maybe one build or the other gets to see an old copy of the include file from another directory.

If so, you can catch it out by printing the sizeof() the struct in the lib and in the app, and add an extra member to change the size, check if both sides see the correct struct size.

If not... who knows, it's your code :-)
