### ISSUE TITLE
[CMake] failed to install in non-standard directory

### ISSUE THREAD

**Issue by tiolan** [warmcat/libwebsockets#2553]
I am installing libwebsockets to a non-standard directory.

The user-code does `find_package(libwebsockets REQUIRED)`,
which leads to:
```
include could not find load file:

    LwsCheckRequirements
Call Stack (most recent call first):
  build/43d47d1f29cdec0402f909ad3c8ccd427505a066/Findlibwebsockets.cmake:181 (include)
  CMakeLists.txt:13 (find_package)
```

In the generated file from:
https://github.com/warmcat/libwebsockets/blob/main/cmake/libwebsockets-config.cmake.in
the variable `libwebsockets_DIR` is not set (at least not in my setup).

I can temporarily solve this by replacing `list(APPEND CMAKE_MODULE_PATH ${libwebsockets_DIR})` by `list(APPEND CMAKE_MODULE_PATH ${LWS_CMAKE_DIR})`
Another temporary fix for me is to comment out the line `include(LwsCheckRequirements)`.

Main Question:
Further I wonder that it seems this is done twice, once via `include(LwsCheckRequirements)` and once via `include(${LWS_CMAKE_DIR}/LwsCheckRequirements.cmake)`.

What is the intend of doing it twice?

**Comment by lws-team** [comment]
> Another temporary fix for me is to comment out the line include(LwsCheckRequirements).
> Further I wonder that it seems this is done twice,

Yes it looks like the second include is not needed.  It was added as part of bringing in "boilerplate" from lws example cmakes.  But the first include already should have solved it.

I'll add a patch later to remove the extra `include(LwsCheckRequirements).`

**Comment by lws-team** [comment]
This is pushed on main now.

https://libwebsockets.org/git/libwebsockets/commit?id=b43efccdc6e0b2f9d0cedcd83a395ce17f928fdb
