### ISSUE TITLE
question about async dns mode

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2557]
Hi Andy.

I'm using lws as http client and connect to several (<10) addresses.
I found it cost about 200us+ to call getaddrinfo and back.
Then I switch to async dns mode (with LWS_WITH_SYS_ASYNC_DNS on) it works much better (> 4 times faster). 

For our use case, are the results cached for each query?
Is it safe to use async dns mode? 

For dns query individually async dns mode is much faster. Is there extra time cost for async mode?
For the overall time of http lifecycle (from http request sent to http response received) which mode is faster?

Thanks and regards.

**Comment by lws-team** [comment]
Yes there is a small cache in heap.

It has some restrictions (UDP only and ipv4 upstream server only) but AFAIK it's "safe",

The difference is that lws Async DNS is done on the lws event loop thread, there is no blocking and synchronization, so it's slighly faster generally for that part.

If it has to go out to a DNS server to get the result, the wallclock time needed is controlled by that remote DNS server, not lws.  But the difference is the lws event loop thread will be literally blocked and dead to the world for 200ms or whatever it is with getaddrinfo, whereas lws will be doing whatever else needs doing for 200ms on the event loop before proceeding the connection that needed the DNS with lws Async DNS.  For that reason, it's typically a major advantage to use Async DNS.
