### ISSUE TITLE
Sending PONG while other message is truncated will cause assertion

### ISSUE THREAD

**Issue by asuuma** [warmcat/libwebsockets#256]
HI, I am using libwebsockets to make client that send and receive big message in high frequency.
Most of time, messages from client are truncated.
While messages are truncated, receiving PING from server will send back PONG immediately here:
https://github.com/warmcat/libwebsockets/blob/master/lib/client-parser.c#L295-L299
But assertion will be made because there are truncated messages at here:
https://github.com/warmcat/libwebsockets/blob/master/lib/output.c#L112

Defer PONG will resolve this problem, but I can't determined that I can just copy this code:
https://github.com/warmcat/libwebsockets/blob/93d947c924ea1a484b25444a6c0e6fb072dbea34/lib/parsers.c#L875-L917

Also I found that when deferred PONG has no payload, I will be ignored here:
https://github.com/warmcat/libwebsockets/blob/93d947c924ea1a484b25444a6c0e6fb072dbea34/lib/service.c#L95
PING and PONG can have none payload.

So please fix these problems.
Thank you!

**Comment by warmcat** [comment]
Yeah you're right... just trying to return the PONG there and then is too casual.

Server PONG handling is done properly already.

The second problem I just pushed a fix for, I'll see if the server code is reusable.

**Comment by warmcat** [comment]
I think it can re-use the same technique fine.  Please try current git HEAD.

**Comment by asuuma** [comment]
Awesome!!!
It looks good to me.
I greatly appreciate your very fast fix.
