### ISSUE TITLE
[Question]: Transporting payload from server to client

### ISSUE THREAD

**Issue by tiolan** [warmcat/libwebsockets#2560]
Hi @lws-team,

I currently try to design the following scenario. I read all the documentation and went through the examples.

Any generic kind of HTTP client does a PUT against a lws server listening without TLS.
This server shall act similar a proxy would, but without actually using the CONNECT package.
In fact it would forward the payload received by this generic client to an external HTTPS server, using an lws client with TLS enabled.
The server knows the target URI of that external HTTPS server and has the TLS certificates and everything.
I guess one would typically call this a reverse-proxy.

generic client ---HTTP/PUT---> [ lws server -> lws client ] ---HTTPS/PUT---> HTTPS server

So far I implemented both ends - left and right, but struggle with connecting them inside code.
There is one lws protocol with one lws callback implemented.
So all the client and server callbacks are handled in the same function. (Not sure if this is good practice)
Reason for this is, the lws server mallocs a pss (connection context) on connection setup, the lws client gets this instance assigned through its info struct, such that they share the same instance / structure.
This allows me to exchange headers, parameters and return codes between lws client and lws server during the different callbacks.

The missing part is now to also transport the payload (multiple MB in size, that I cannot store entirely in the server application).
This means the lws server needs to read a piece of payload, store it, the next callback of the client has to write/forward it, clean the memory, server can read again. Always in this order, the server must not e.g. read twice - resp. override data, when the client did not yet write.

In the examples I saw you implementing this using a ring buffer in between those.
That would definitely be one solution - if the ring buffer supports something like "is full - do not add more data".
 
Another approach would be something like in the read callback of the server, actively and directly write to the client.
But in the documentation I read, this should not be done. Maybe I missed something.
So I thought in the read callback of the server call `lws_callback_on_writable` and store `void* in`, `size_t len` in the shared pss (connection context). Then in the client write callback directly read from that and write on the socket.
However that feels dangerous and wrong to me.
I would need the guarantee, that after a server read always a client write callback is issued, otherwise I would loose data.
Also the client would directly read from server structures.

I read there is an example on `lws_callback_on_writable` in the testserver code. Where would I find that?

What are your thoughts?
Would appreciate any kind of idea you could share.

Thanks!

**Comment by tiolan** [comment]
Hey,
thanks for you answer.

I saw lws supports it directly.
But I think my use-case is a bit different.

The "proxy" does not know the URL where to forward the data at compile time.
It requests it from a different location, after an external client started the PUT. The URL is dynamic and can change per each request.
Further I need to manipulate headers, handover some, add some.

So I guess the built in reverse proxy does not fit my use case.
That's why I started doing it from scratch.
How would you handover data from the client to the server in that specific case?

Thanks

**Comment by tiolan** [comment]
I have now implemented a buffer in between the client and the server, that hands over the payload.
Using the flow control APIs I can regulate to not overflow the buffer.
Thanks for those hints.

I observed the following behavior and would like to ask if this expected.
When the client did the PUT against the external (non lws) server, this server sends back the response, that has some payload.
I am not interested in the payload, only the return status.
I get the return status inside `LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP` via `lws_http_client_http_response` and then return -1 in order to close the connection.
This gives me a `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` with reason `disallowed at ESTABLISHED` (obviously).

If I return 0 from `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`, the client connection idles until a timeout. I can see a TCP Zero-Window on the network.

I can ignore this "error", but still it does not feel correct.

What would be the the correct flow in this case?

**Comment by lws-team** [comment]
There's another way, call `lws_wsi_close(wsi, LWS_TO_KILL_ASYNC);` before return 0, it will force a close next time around the event loop.

**Comment by lws-team** [comment]
> LWS_CALLBACK_CLIENT_CONNECTION_ERROR

This means you could not "make the connection" with the peer.  For example, you could not connect at tcp level, or as in your case, the tls library vetoed the creation of the tls tunnel for whatever reason.

Although not "making the connection" becomes a bit ambiguous when your "connection" is not just those things but also, eg the upgrade to a specific ws protocol, generally is is meaning that we did not get as far as ESTABLISHED for your requested action.

That means you did not make it to issue any http transaction, there is no transaction to "complete", it is pining for the fjords before it got that far.,  Its next step after CCE is the close flow.
