### ISSUE TITLE
[Question] Usage of globals

### ISSUE THREAD

**Issue by lucianoiam** [warmcat/libwebsockets#2561]
I am planning to embed libwesockets in an audio plugins context, common practice is to link against static libs and avoid any kind of global/static data.

Does lws make use of any global / static data / singletons, etc behind the scenes?

Thanks.

**Comment by lws-team** [comment]
Generally, it avoids them like the plague and everything is rooted in the lws_context.

But there are a least two deviances

 - openssl requires global definitions for private data indexes, there are one or two instances of these as static scope global ints or so.

 - the logs have to work where there is no lws_context, eg, before it is created and after it is destroyed.  So if you don't use the logging apis that bind to specific objects (like lws_context, vhost, wsi, or ss), the default logs use the default logging context which is a static scope global.  The logging context has to know what runtime log levels it is supposed to emit and various overrides that are possible, it's a couple of dozen bytes.

**Comment by lucianoiam** [comment]
Great summary of everything involved, this saves lots of time thanks. Regarding OpenSSL that is a separate problem I hadn't thought about before...

For the logs, is it possible to completely disable them? they aren't useful in this context, other than for debugging purposes.

**Comment by lws-team** [comment]
The logs are pretty build-time configurable but in reality, anything to do with a network can go wrong at any time and without any logging, you will be stuck when it happens remotely.  There's no turnkey way to really eliminate everything but there is quite a lot of infrastructure for controlling which ones get built in, eg, see the second section here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.logging.md

You would probably need to tell cmake to snip all the log types at build-time and then patch in a little bit more to not even build the static global logging context.
