### ISSUE TITLE
assert on parent for rops_callback_on_writable_ws with proxy and thread

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2573]
Hello,

There is an assert that I'm hitting `assert(enc);` in the following scenario:

`ws -> proxy -> thread -> ws`

when the connection closes in
```
case LWS_CALLBACK_CLOSED:
```
I do `LWS_TO_KILL_ASYNC` to stop the client proxy
```
		if(pss->wsi->child_list)
			lws_wsi_close(pss->wsi->child_list, LWS_TO_KILL_ASYNC)
```

then I stop the thread
```
if(!pthread_join(pss->thread_id, NULL)) {
```
And I sent an mirror message indicating that the thread is gone using the mirror protocol but then the assert hits

It looks like the assert assumes that there is always a parent

/* we know then that it has an h2 parent */

https://github.com/warmcat/libwebsockets/blob/v4.3-stable/lib/roles/ws/ops-ws.c#L1949

if I change remove the assert and change the code to:
```
		if(!enc) {
			return 1;
		}
```
It fixes my issue. My question is that why can't we just check if parent `enc` is not there and then ignore the write? Or am I missing a parent check?

Thanks,

Alex

**Comment by lws-team** [comment]
You can't casually drop a thread into the equation like it's normal, unless there's a special reason why you took steps to make it safe, which you would have to spell out, it's illegal and doomed to blow up.

There's no locking at all in lws by default, one thread calling apis on an h2 stream while another thread services it is just waiting for the inevitable crash.

**Comment by alexeadem** [comment]
I hear you. Let me go back to the drawing board and understand the steps to make to make it safe.
