### ISSUE TITLE
Cannot connect to wss://api.gateio.ws

### ISSUE THREAD

**Issue by KrutayaAlpaca** [warmcat/libwebsockets#2574]
### 
	"release": "1",
	"product": "logger",
	"schema-version": 1,
	"retry": [{
		"default": {
			"backoff": [1000, 2000, 3000, 4000, 5000],
			"conceal": 65535,
			"jitterpc": 20,
			"svalidping": 30,
			"svalidhup": 35
		}
	}],
	"certs": [
		{
			"digicert_global_root": "MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsBCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7PT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbRTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/EsrhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJFPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0lsYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQkCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4="
		},
		{
			"digicert_baltimore_root": "MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoXDTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9yZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVyVHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKrmD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjrIZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeKmpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSuXmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZydc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/yejl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT929hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3WgxjkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhzksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLSR9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp"
		}
	],
		"trust_stores": [{
			"name": "binance_cert",
			"stack": ["digicert_global_root"]
		},
		{
			"name": "gateio_cert",
			"stack": ["digicert_baltimore_root"]
		}
	],
	"s": [
		{ "binance": {
			"endpoint":		"stream.binance.com",
			"port":			9443,
			"protocol":		"ws",
			"http_url":		"ws",
			"nailed_up":        	true,
			"ws_prioritize_reads":	true,
			"tls":			true,
			"tls_trust_store":	"binance_cert",
			"retry":		"default"
			}
		},
		{ "gateio": {
			"endpoint":		"api.gateio.ws",
			"port":			443,
			"protocol":		"ws",
			"http_url":		"ws/v4/",
			"nailed_up":        	true,
			"ws_prioritize_reads":	true,
			"tls":			true,
			"tls_trust_store":	"gateio_cert",
			"retry":		"default"
			}
		}
	]

###
Hello! This is what the file looks like policy.json . The connection to the binance works fine,but I can't figure out why the connection to the gate.io is not working.

**Comment by lws-team** [comment]
> I can't figure out why the connection to the gate.io is not working.

So what do the verbose debug logs say?

**Comment by KrutayaAlpaca** [comment]
### 
[2022/02/22 15:17:13:7857] N: lws_create_context: LWS: 4.3.99-v4.3.0-178-ga4700674, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent
[2022/02/22 15:17:13:7857] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2022/02/22 15:17:13:7858] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2022/02/22 15:17:13:7866] N: __lws_lc_tag:  ++ [vh|1|gateio_cert||-1] (2)
[2022/02/22 15:17:13:7870] N: __lws_lc_tag:  ++ [vh|2|binance_cert||-1] (3)
[2022/02/22 15:17:13:7873] N: __lws_lc_tag:  ++ [wsiSScli|0|gateio] (1)
[2022/02/22 15:17:13:7873] N: [wsiSScli|0|gateio]: lws_ss_check_next_state_ss: (unset) -> LWSSSCS_CREATING
[2022/02/22 15:17:13:7873] N: [wsiSScli|0|gateio]: lws_ss_check_next_state_ss: LWSSSCS_CREATING -> LWSSSCS_CONNECTING
[2022/02/22 15:17:13:7873] N: __lws_lc_tag:  ++ [wsicli|0|WS/h1/api.gateio.ws/([wsiSScli|0|gateio])] (1)
[2022/02/22 15:17:13:8879] N: [wsicli|0|WS/h1/api.gateio.ws/([wsiSScli|0|gateio])]: lws_client_connect_3_connect: trying 13.115.74.21
[2022/02/22 15:17:14:4960] N: [wsiSScli|0|gateio]: lws_ss_check_next_state_ss: LWSSSCS_CONNECTING -> LWSSSCS_UNREACHABLE
[2022/02/22 15:17:14:4961] N: __lws_lc_untag:  -- [wsicli|0|WS/h1/api.gateio.ws/([wsiSScli|0|gateio])] (0) 708.776ms
[2022/02/22 15:17:15:6814] N: [wsiSScli|0|gateio]: lws_ss_check_next_state_ss: LWSSSCS_UNREACHABLE -> LWSSSCS_POLL
[2022/02/22 15:17:15:6814] N: [wsiSScli|0|gateio]: lws_ss_check_next_state_ss: LWSSSCS_POLL -> LWSSSCS_CONNECTING

**Comment by lws-team** [comment]
"Verbose logs" means build with `-DCMAKE_BUILD_TYPE=DEBUG` and use, eg, -d1151 on the example commandline.

**Comment by lws-team** [comment]
You just randomly picked the Baltimore Cybertrust CA to trust for that server and then asked me to figure it out?  It does not appear to use certs signed by it.

**Comment by KrutayaAlpaca** [comment]
No, this gate.io certificate
![Screenshot from 2022-02-22 15-27-22](https://user-images.githubusercontent.com/22477446/155092611-4315364b-6992-4bb4-b0fe-9c5edc2e1d1c.png)

**Comment by KrutayaAlpaca** [comment]
Or am I wrong?

**Comment by lws-team** [comment]
There is no relationship between `api.gate.ws` and `gate.io` certificate arrangements.
