### ISSUE TITLE
Is there an example of using lws_adopt_socket_readbuf()?

### ISSUE THREAD

**Issue by Kevin-shc** [warmcat/libwebsockets#2576]
I'm trying to upgrade a foreign Unix socket to websocket with libwebsockets.
I have read https://github.com/warmcat/libwebsockets/issues/439 , but I can't find branch "test".
So I wanna find an example of using lws_adopt_socket_readbuf() to learn how to use it.

**Comment by lws-team** [comment]
There's no example (you're welcome to make one by adapting an existing ws server example).

It's a pretty self-explanatory api

```
struct lws *
lws_adopt_socket_readbuf(struct lws_context *context, lws_sockfd_type accept_fd,
			 const char *readbuf, size_t len);
```

You hand it your already-accepted socket fd you have already read from, along with whatever you had already read.  Lws will try to pick up from there and act as if it had accepted the socket and read the readbuf data itself.

**Comment by Kevin-shc** [comment]
Got it.Thanks.
