### ISSUE TITLE
server error: [null wsi]: lws_socket_bind: ERROR on binding fd xx to port xx (-1 98)

### ISSUE THREAD

**Issue by catseeker** [warmcat/libwebsockets#2585]
I wrote a server demo, perform deinitialization (lws_context_destroy()) when Ip changes, and then reinitialize lws_creat_context(), the following problems will occur
1. The execution time of lws_context_destroy() is very long
2. Reinitialization will report an error [null wsi]: lws_socket_bind: ERROR on binding fd xx to port xx (-1 98), how does lws use socket SOREUSEADDR ?

**Comment by lws-team** [comment]
It tries to use SO_REUSEADDR, but what happens there is to do with your libc and platform details.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/http/server/server.c#n234-239

you'll need to look at / add logs to see what happens on your box.
