### ISSUE TITLE
Async_DNS can work with external poll?

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#2586]
I have a service using libwebsockets as websocket client and needs to connect to a server.
This time uses externall polls and async_dns. Also needs IPV6 compliance.

I can see in logs that is unable to init lws-async-dns ans also it gets a poll assertion:

Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 10:06:04:3165] N: PARSING OPTION U
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 10:06:04:3934] N: PARSING OPTION F
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 10:06:04:3937] N: ubusx prefix 2
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 10:06:04:3989] I: Will serve dir '/www' for HTTP
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4012] D: Creating lwsl context
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4025] I: lws_create_context: ev lib path /usr/lib, '(null)'
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4026] D: _realloc: size 6448: context
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4029] D: _realloc: size 104: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4030] D: _realloc: size 105: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4031] D: _realloc: size 105: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4032] D: _realloc: size 105: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4033] D: _realloc: size 107: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4033] D: _realloc: size 110: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4034] D: _realloc: size 106: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4035] D: _realloc: size 102: lws_metric_create
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4036] N: lws_create_context: LWS: 4.3.0-10-376-g470eb95c89, NET CLI SRV H1 H2 WS ConMon ASYNC_DNS IPV6-on
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4081] D: [wsisrv|0|adopted]: lws_ensure_user_space: protocol pss 0, user_space=(nil)
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4570] D: _realloc: size 24: lws_metrics_tag_add
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4571] I: lws_async_dns_query: entry 8.8.8.8
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4572] I: [null wsi]: lws_adns_dump: ADNS cache 0 entries
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4573] I: lws_async_dns_query: 8.8.8.8 uncached
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4574] D: _realloc: size 132: adns-numip
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4575] I: [null wsi]: lws_adns_dump: ADNS cache 1 entries
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4576] I: [null wsi]: lws_adns_dump: cache: '8.8.8.8', exp: 3599999909us, incomp 0, fl 0x0, refc 0, res 0x6d2d98
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4577] D: [wsisrv|0|adopted|raw-skt]: lws_async_dns_complete: q: 0x7ea365c8, c: 0x6d2d58, refcount 0 -> 1
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4578] I: [wsisrv|0|adopted|raw-skt]: lws_sort_dns: sort_dns: 0x6d2d98
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4616] D: _realloc: size 124: lws_sort_dns
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4617] I: [wsisrv|0|adopted|raw-skt]: lws_sort_dns: unsorted entry (af 2) 8.8.8.8
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4618] I: [wsisrv|0|adopted|raw-skt]: lws_sort_dns_dump: 1: (2)8.8.8.8, gw (0)(unset), idi: 0, lbl: 0, prec: 0
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4619] D: lws_async_dns_freeaddrinfo: c 0x6d2d58, 8.8.8.8, refcount 1 -> 0
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4622] D: [wsisrv|0|adopted|raw-skt]: __insert_wsi_socket_into_fds: tsi=0, sock=11, pos-in-fds=2
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4623] D: [wsisrv|0|adopted|raw-skt]: lws_role_transition: wsistate 0x119, ops raw-skt
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4624] D: [wsisrv|0|adopted|raw-skt]: lws_ensure_user_space: protocol pss 0, user_space=(nil)
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4625] D: [vh|1|system||-1]: lws_protocol_init_vhost: not instantiating lws-async-dns
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4626] I: [vh|1|system||-1]: lws_protocol_init_vhost: init system.lws-async-dns
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4627] D: [vh|1|system||-1]: lws_protocol_init_vhost: not instantiating lws-async-dns
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4628] I: [vh|1|system||-1]: lws_protocol_init_vhost: init system.lws-async-dns
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4629] I: lws_create_context:  mem: per-conn:          936 bytes + protocol rx buf
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4629] D: lws_cancel_service: 
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4631] D: _realloc: size 712: lws_create_vhost
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4632] N: __lws_lc_tag:  ++ [vh|2|default||-1] (3)
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4633] D: _realloc: size 84: vh plugin table
Fri Mar  4 10:06:04 2022 daemon.err owsd[22987]: [2022/03/04 09:06:04:4634] D: _realloc: size 24: same vh list
Fri Mar  4 10:06:05 2022 daemon.err owsd[22987]: /usr/sbin/owsd: /home/output/build/libwebsockets-v4.3.1/lib/core-net/service.c: 658: lws_service_fd_tsi: Assertion `pollfd' failed.

**Comment by lws-team** [comment]
> This time uses externall polls 

I recommend you don't use `EXTERNAL_POLL`... it's OFF by default and literally says "not recommended" on the CMake help.

If you look at the assert rather than fire up github straight away, it has a comment explaining the problem

```
		/*
		 * calling with NULL pollfd for periodic background processing
		 * is no longer needed and is now illegal.
		 */
		assert(pollfd);
```

> lws_protocol_init_vhost: not instantiating lws-async-dns

I don't think this reflects any problem.

**Comment by fusionJose** [comment]
Yes but it is a buildroot service not programmed by me and it uses external poll, not uloop like i do it.

When I updated last libwebsockets version with async_dns, it fails.

They can live together external_poll and async_dns??

Thank you a lot
