### ISSUE TITLE
Is this a problem?

### ISSUE THREAD

**Issue by hujiaxing** [warmcat/libwebsockets#2589]
in lib/plat/windows/windows-service.c
function _lws_plat_service_tsi

	for (i = 0; i < pt->fds_count; ++i) {
		pfd = &pt->fds[i];

		if (!(pfd->events & LWS_POLLOUT))
			continue;

		wsi = wsi_from_fd(context, pfd->fd);
		if (!wsi || wsi->listener)
			continue;
		if (wsi->sock_send_blocking)
			continue;
		pfd->revents = LWS_POLLOUT;
		n = lws_service_fd(context, pfd);     <<==== why not  lws_service_fd_tsi        
		if (n < 0)
			return -1;

		/*
		 * Force WSAWaitForMultipleEvents() to check events
		 * and then return immediately.
		 */
		timeout_us = 0;

		/* if something closed, retry this slot */
		if (n)
			i--;
	}

**Comment by lws-team** [comment]
With the default LWS_MAX_SMP as 0, no, it's not a problem.

I have not tried LWS_MAX_SMP > 0 on windows.
