### ISSUE TITLE
rpm .spec file requires 'openssl-devel' for non-devel package

### ISSUE THREAD

**Issue by jmillan** [warmcat/libwebsockets#259]
Hi,

Just that; `libwebsockets.spec` file [requires](https://github.com/warmcat/libwebsockets/blob/master/libwebsockets.spec#L13) `openssl-devel` for non-devel .rpm package. Isn't that just necessary as a building requirement (BuildRequires) but not as a .rpm requirement (Requires)?

Thanks

**Comment by warmcat** [comment]
Yes thanks... I pushed a fix making openssl the requires and leaving openssl-devel the buildrequires.

**Comment by jmillan** [comment]
Thanks a lot
