### ISSUE TITLE
Can we specify source port with LWS4.2 in client mode

### ISSUE THREAD

**Issue by Rajasekhar-topgear** [warmcat/libwebsockets#2590]
Hi Experts,

                Could you please let me know if we can specify source port with  LWS4.2 in client mode. If possible, please let me know how to pass the source port to LWS4.2.

Thanks,
Rajasekhar.

**Comment by lws-team** [comment]
This feature exists on main thanks to a contribution 38a39a37108d9b0269c62a5e66dfefa5dca19b37

You can either try to backport it or use main.

**Comment by Rajasekhar-topgear** [comment]
Thanks for the info.
