### ISSUE TITLE
Getting Error lws_client_connect_3_connect: dns lookup failed -258.

### ISSUE THREAD

**Issue by sachusachin622** [warmcat/libwebsockets#2591]
Hi ,
I am facing lws_getaddrinfo46: getaddrinfo 'device.ab.bc.com' says -258 and lws_client_connect_3_connect: dns lookup failed -258 Here **device.ab.bc.com** is pinging from my device but showing this errors.
Here is the LWS logs.

Mar 24 11:52:24 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_client_dns_retry_timeout: dns retry
Mar 24 11:52:24 user.debug LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_client_connect_2_dnsreq: new conn on no pipeline flag
Mar 24 11:52:24 user.debug LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lwsi_set_state: lwsi_set_state 0x10000200 -> 0x10000201
Mar 24 11:52:24 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_client_connect_2_dnsreq: lookup device.ab.bc.com:443
Mar 24 11:52:24 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_getaddrinfo46: getaddrinfo 'device.ab.bc.com' says -258
Mar 24 11:52:24 user.notice LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_client_connect_3_connect: dns lookup failed -258
Mar 24 11:52:24 user.debug LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lwsi_set_state: lwsi_set_state 0x10000201 -> 0x10000200
Mar 24 11:52:25 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lws_sul_wsitimeout_cb: TIMEDOUT WAITING 25, dhdr 0, ah 0x16f9998, wl 0
Mar 24 11:52:25 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: __lws_close_free_wsi: caller: timeout
Mar 24 11:52:25 user.debug LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: __lws_close_free_wsi: real just_kill_connection A: (sockfd -1)
Mar 24 11:52:25 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: __lws_close_free_wsi: real just_kill_connection: sockfd -1
Mar 24 11:52:25 user.debug LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: lwsi_set_state: lwsi_set_state 0x10000200 -> 0x10000020
Mar 24 11:52:25 user.info LWS_CLIENT[1491]: [wsicli|3b8|WS/h1/device.ab.bc.com]: __lws_close_free_wsi: cce=0
Mar 24 11:52:25 user.err LWS_CLIENT[1491]: CLIENT_CONNECTION_ERROR: dumb: Closed before conn

Please help me to resolve this problem.

Thanks,
Sachin

**Comment by lws-team** [comment]
Lws is just telling you what the platform getaddrinfo() told it.  You will have to look at your libc / platform docs for your getaddrinfo() to find out what it means.

**Comment by sachusachin622** [comment]
Hi,
I tried with the same domain Name **device.ab.bc.com** with other application its working properly. getaddrinfo() is working fine. 
But in LWS continuously giving these error logs.
Please advice me if anything missed in our case.

Thanks

**Comment by lws-team** [comment]
>> Lws is just telling you what the platform getaddrinfo() told it. You will have to look at your libc / platform docs for your getaddrinfo() to find out what it means.
> Please advice me if anything missed in our case.

I did advise you, look up what -258 means on your platform as getaddrinfo() return.   It's not going to be surprising you get this behaviour only on the lws device if, eg, -258 means there is no DNS resolver configured on that device.  That's nothing to do with lws if so.

Let's reopen this if you bother to take the advice you asked for.
