### ISSUE TITLE
Question: Implement websocket client using existing AF_VSOCK connection 

### ISSUE THREAD

**Issue by ashlander** [warmcat/libwebsockets#2594]
Hello All,

I want to create websocket client, but with changing transport protocol to vsock. I found possibility to adopt existing sockets for server side client connection, but no sign to do exact thing for client side and benefit from protocol already implemented. So basically I need to change stream tcp to a stream vsock transport without touching messages content.

Currently I have used server side adopting, but treating it as client should, but this way I am forced to deal with manual raw messages generation. And in this case I fill this to be wrong approach, because I re-implementing full websocket protocol spec, e.g.

```
        case LWS_CALLBACK_RAW_ADOPT:
        {
            constexpr char buf[] = "GET /default HTTP/1.1\r\n"
                "Host: server.example.com\r\n"
                "Upgrade: websocket\r\n"
                "Connection: Upgrade\r\n"
                "Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==\r\n"
                "Sec-WebSocket-Protocol: default\r\n"
                "Sec-WebSocket-Version: 13\r\n"
                "Origin: http://example.com\r\n\r\n";
            constexpr int len = sizeof(buf)/sizeof(char);
            if (lws_write(wsi, (uint8_t*)&buf[0], len, LWS_WRITE_RAW) != len) {
                lwsl_notice("%s: raw write failed\n", __func__);
                return 1;
            }
            //if (caller) caller->set_connected(true);
        }
```
Is there a correct way of doing such a implementation, or at least how can I reuse messages/frames generation functionality ?

**Comment by lws-team** [comment]
> but with changing transport protocol to vsock

I dunno what "vsock" is, but if it is in fact set up using ws RFC, then you should use lws to set up a client ws or wss connection.

What happens after that is established that makes this thing "vsock" rather than "wss" then?

**Comment by ashlander** [comment]
Vsock is transport layer, which is used to communicate between virtual machines. By default libwsockets using tcp transport for communication. And in examples it is possible to find a way how to make own connection and attach it for server to be used.

https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/raw/minimal-raw-adopt-tcp/minimal-raw-adopt-tcp.c

But this is applied to server only (at least that's what I understood from the docs). My understanding is - after such a switch, libwsockets will be working es expected (will be responsible for creating messages and frames in proper format) but using provided transport.

In my case I am on clients side, and I need to do the similar stuff. So I am creating socket, and there is no dedicated function to adopt (attach) it to libsockets client part. Again I may miss something. And when I am using server part functions (see example), I violate things, and start using what should be server side as client, so no handshake goes to server any more.

So in this case I tested raw message in order to switch the protocol to websocket, and server replied with success. But if I will need to re-implement all the calls to server because of this, I see no need for libsockets library.

So I think I may be on the wrong tracks.

**Comment by lws-team** [comment]
I see... broadly this is analogous to Unix Domain... addresses don't need DNS lookup and need special AF_ handling.  And unix domain works fine in lws.  So it would mean adding some stuff that follows what unix domain support does, but for AF_VSOCK.

I would suggest grep for `unix_skt` and `LWS_WITH_UNIX_SOCK`... these are the places where the flow deviates to do Unix Domain Sockets.  If you audit those and create similar flag `vf_skt` and `LWS_WITH_VSOCK`, and handle the same places, that would get you most or all of the way.  Then you can use the normal ws flow but prepend the "address" CID string with a vosck char, like `+` is used to indicate you want a unix socket and the "address" is the path, eg ">1234" as the address means use AF_VSOCK and CID 1234,.

**Comment by ashlander** [comment]
Thanks for the tip. Wished there was an easier solution, kind of curl has... well that's still much better solution than implementing all by myself. Will look into it.

**Comment by lws-team** [comment]
Patch is welcome, then there will be "an easier solution" for the next guy.  You can create and connect the socket and then adopt it, but this is not any easier for you, and does nothing for the next guy.  This way you and others will be able to use normal lws apis to handle connect, retries etc same as can be done today with Unix Domain.  If you need any help send what you have and I will help (if you can describe how to create an AF_VSOCK "server" to connect to).

**Comment by lws-team** [comment]
> I see multiple ifdefs related to unix socket implementation, which needs careful testing

That's why there's very muscular CI for lws.
