### ISSUE TITLE
async dns doesn't work with /ets/hosts

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2597]
Hi Andy,

I use lws as http and ws client. To save time of dns lookup, I turn on LWS_WITH_SYS_ASYNC_DNS.
It works well under regular case. But when I add some config to /etc/hosts, it seems async dns doesn't adopt this file which leads to connection failure.

Is there a way to make async dns adopt config under /etc/hosts?

Thanks and regards

**Comment by lws-team** [comment]
> It works well under regular case

That's good to know.

> Is there a way to make async dns adopt config under /etc/hosts?

Yes I guess something can be done in plat.

**Comment by lws-team** [comment]
Please try current main, or backport these

https://libwebsockets.org/git/libwebsockets/commit?id=1fb161e815a27864de6ceecf1b3ce40da7b7922f
https://libwebsockets.org/git/libwebsockets/commit?id=143e531f61dbd1eedfa45e3a50e744c8eb63a514

**Comment by lws-team** [comment]
Well, if any problems, let me know.

**Comment by qdztxc** [comment]
Thanks for your quick enhancement.

I tried it and found now there is no SSL error. /etc/hosts is referenced by async dns.

I found another issue, it seems for http, the address under /etc/hosts is cached. 
But for ws, the address under /etc/hosts is not cached.

I turned LLL_INFO log and found such logs for ws.
[2022/04/06 08:11:33:4467] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:11:33:4504] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:11:38:4564] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:11:43:4600] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:13:23:4686] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:13:30:4719] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:14:00:4764] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:14:04:4795] I: lws_async_dns_query: xxxx uncached
[2022/04/06 08:14:28:4837] I: lws_async_dns_query: xxxx uncached
For http, it works well.
[2022/04/06 08:14:30:8855] I: lws_async_dns_query: yyyy: using cached, c->results 0x7fe4d8022ad0

**Comment by lws-team** [comment]
Hm... it doesn't know or care about ws or http or not for caching purposes.

Is it that the ws stuff is a numeric IP address?

**Comment by qdztxc** [comment]
Yes. Both http and ws are numeric. It looks like 
10.0.0.14 xxxx
10.0.0.14 yyyy

xxxx is for ws, yyyy is for http.
The only difference as I know is the request interval. For http, each request is sent around 1s. But for ws, the interval is much longer(1 mins or longer).

**Comment by lws-team** [comment]
The code sets a TTL for numeric caching (including /etc/hosts) of 1 hour.

The cache is of limited size, new things bump old things when it's full, as well as old things die when their TTL expires, maybe it's related to that.

**Comment by qdztxc** [comment]
> 

Any hint to debug this? What's the size of cache? My program uses about 5 addresses.

**Comment by lws-team** [comment]
Add logging at https://libwebsockets.org/git/libwebsockets/tree/lib/system/async-dns/async-dns.c#n606

and at

https://libwebsockets.org/git/libwebsockets/tree/lib/system/async-dns/async-dns.c#n1057

to understand what's happening with the cache maintenance.

There's some logging commented here that tells if something found in the cache

https://libwebsockets.org/git/libwebsockets/tree/lib/system/async-dns/async-dns.c#n540

The max cache entries is set to 10 atm

https://libwebsockets.org/git/libwebsockets/tree/lib/system/async-dns/private-lib-async-dns.h#n29
