### ISSUE TITLE
H2 post big files

### ISSUE THREAD

**Issue by orefkov** [warmcat/libwebsockets#2599]
When my server protocol processed POSTed big http body, my callback was not called with LWS_CALLBACK_HTTP_BODY_COMPLETION.
I debug code:
At first runned **lws_h2_bind_for_post_before_action**, and call LWS_CALLBACK_HTTP_BODY for firsts block of received data.
For next blocks runned **lws_read_h1**. In it checked _wsi->http.rx_content_remain_ for calling LWS_CALLBACK_HTTP_BODY_COMPLETION.
But in lws_h2_bind_for_post_before_action - _wsi->http.rx_content_length_ changed on reading data, but _wsi->http.rx_content_remain_ - not changed.

```
	while (((!wsi->http.content_length_given) ||
		  wsi->http.rx_content_length) &&
	       (blen = lws_buflist_next_segment_len(&wsi->buflist, &buffered))) {

		if ((size_t)wsi->http.rx_content_length < blen)
			blen = (size_t)wsi->http.rx_content_length;

		if (wsi->a.protocol->callback(wsi, LWS_CALLBACK_HTTP_BODY,
				wsi->user_space, buffered, blen))
			return 1;
		lws_buflist_use_segment(&wsi->buflist, blen);

		wsi->http.rx_content_length -= blen;
		>>> in it need add this: wsi->http.rx_content_remain -= blen;
	}

```

**Comment by lws-team** [comment]
Thanks, that does look right.  I pushed it on main and will backport it to v4.3-stable later.

**Comment by orefkov** [comment]
Now connection terminated by error at http2.c:
```
if (lws_hdr_total_length(h2n->swsi,
			WSI_TOKEN_HTTP_CONTENT_LENGTH) &&
	h2n->swsi->http.rx_content_length &&
	h2n->swsi->http.rx_content_remain <
				h2n->length && /* last */
	h2n->inside < h2n->length) {

	lwsl_warn("%s: %lu %lu %lu %lu\n", __func__,
			(unsigned long)h2n->swsi->http.rx_content_remain,
		(unsigned long)(lws_ptr_diff_size_t(iend, in) + 1),
		(unsigned long)h2n->inside, (unsigned long)h2n->length);

	/* unread data in frame */
	lws_h2_goaway(wsi,
				H2_ERR_PROTOCOL_ERROR,
		"More rx than content_length told");
	break;
}
```

**Comment by lws-team** [comment]
How about if you get rid of the `wsi->http.rx_content_length -= blen;` from before?

**Comment by orefkov** [comment]
Before I add `wsi->http.rx_content_length -= blen;` it was that:
File posted size = `11 558 243`
Content-length header in http request = `11 558 627`
No protocol error `More rx than content_length told`.
LWS_CALLBACK_HTTP_BODY called `2989` times, common len - `11 558 627`
Then pending timeout, then called LWS_CALLBACK_HTTP_DROP_PROTOCOL, with
`wsi->http.rx_content_length  = 11 542 252`
`wsi->rx_content_remain	= 16375` (it was readed early in lws_h2_bind_for_post_before_action)

As a temporary workaround, I'm still looking at the amount received in the LWS_CALLBACK_HTTP_BODY and comparing it with the Content-length in the header.

**Comment by lws-team** [comment]
Hum... I don't have time to unpick that atm.  I removed your patch for now since it doesn't seem to solve it.
