### ISSUE TITLE
Crash in lws_ext_callback_for_each_active()

### ISSUE THREAD

**Issue by vchernetsky** [warmcat/libwebsockets#260]
I have an occasional crash in lws_ext_callback_for_each_active() on iOS platform. The crash is rare. Out of few hundred sessions a day this crash happens once every day or two.

I was able to reproduce it once. Here is what I know:

Crash is SIGSEGV in this line:
		m = wsi->active_extensions[n]->callback(
			wsi->protocol->owning_server,
			wsi->active_extensions[n], wsi,
			reason,
			wsi->active_extensions_user[n],
			arg, len);
- n = 0
- There is a "garbage" in wsi->active_extensions[0] through [2]. Those pointers are not null pointers , but some random values.
- wsi->count_active_extensions = 103.
- wsi->state = WSI_STATE_FLUSHING_STORED_SEND_BEFORE_CLOSE

Everything else looks ok in wsi.

**Comment by warmcat** [comment]
Hum that's a bit difficult to diagnose.

Just having junk in the active extensions pointers and a nonzero count will make the crash itself.

But the fact he survived to get to flushing before close state suggests the overwrite (if that's what it is) happened very late in the connection's lifecycle.

And those members about extensions, are at the start of the wsi struct, and not in a union.  But the whole wsi is not overwritten; state seems sane.

That state can only be reached if you had an established ws connection; had a truncated send; and decided to close.  I couldn't see any problems around that except there's no timeout coverage for it, I pushed a patch to add it but it doesn't fix whatever this is.

It's difficult to understand from this if lws is doing it (you would think we would hear about it more...) or your code around it is doing it.

**Comment by vchernetsky** [comment]
Yeah, it is possible it could be a memory corruption in my code. Now, after your opinion it is even more likely. 

Thank you!
