### ISSUE TITLE
MSVC cl warning due to providing both /Zc:preprocessor and /experimental-preprocessor command line flags

### ISSUE THREAD

**Issue by botscholar-scott** [warmcat/libwebsockets#2600]
It looks like `/experimental-preprocessor` is obsolete in version Microsoft Visual Studio version 16.5 [1] so when I am building with a version of Visual Studio that has CMake MSVC_VERSION of 1929 I see warnings like,

"cl : command line warning D9035: option 'experimental:preprocessor' has been deprecated and will be removed in a future release" paired with "cl : command line warning D9036: use 'Zc:preprocessor' instead of 'experimental:preprocessor'"

whereas with recent builds on your Windows build machines [2], [3], and [4] I see the opposite,
"cl : command line warning D9002: ignoring unknown option '/Zc:preprocessor'"

Which I would suspect is due to providing both of them. 

I'm guessing it should probably use something like this diff,

diff --git a/CMakeLists.txt b/CMakeLists.txt
index adab70a5..08c9e478 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -901,7 +901,11 @@ if (MSVC)
     # Fail the build if any warnings
     add_compile_options(/W3 /WX)
     # Unbreak MSVC broken preprocessor __VA_ARGS__ behaviour
-    add_compile_options(/Zc:preprocessor /experimental:preprocessor /wd5105)
+    if (MSVC_VERSION > 1925)
+        add_compile_options(/Zc:preprocessor /wd5105)
+    else()
+        add_compile_options(/experimental:preprocessor /wd5105)
+    endif()
 endif(MSVC)

 if (MINGW)

Although I don't have those older versions of Visual Studio installed so I'm not entirely certain you don't have 1925 on your build machines?

I found that 1925 here [5]. 

I'd be happy to make a PR if that is your preference.

[1] https://docs.microsoft.com/en-us/cpp/build/reference/experimental-preprocessor?view=msvc-170&viewFallbackFrom=vs-2019
[2] https://libwebsockets.org/sai/index.html?task=e12ac7debcb834eefb4559abf78da17a55724e1d629b8c769da171bd70d80e23
[3] https://libwebsockets.org/sai/index.html?task=e12ac7debcb834eefb4559abf78da17a99fe803c2974f1cd270b9d8f607b658e
[4] https://libwebsockets.org/sai/index.html?task=e12ac7debcb834eefb4559abf78da17af9ed8c79de90c5d83fcfa50769f5be74
[5] https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd

**Comment by lws-team** [comment]
Thanks, I pushed it on main with a change to use CMake GREATER operator.
