### ISSUE TITLE
How to manage the process of switching from http protocol to websocket protocol

### ISSUE THREAD

**Issue by catseeker** [warmcat/libwebsockets#2602]
I want to add additional fields to the message of the http protocol switching websocket protocol for authentication. 
Since this process has been done internally in lws, how can I manage the process of this protocol switching by myself ?

**Comment by lws-team** [comment]
All ws connections start out as pure HTTP and upgrade.  If you bind the connection to your lws_protocol at connection creation info time (using `.local_protocol_name`) the related callback gets a chance to modify the upgrade request using callback reasons related to HTTP.

During creation of the CONNECT upgrade HTTP request for example, you will get a chance to handle `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER`.  There you can add headers to the (still HTTP) upgrade request as in 

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client-custom-headers/minimal-http-client-custom-headers.c?h=main#n38

**Comment by catseeker** [comment]
Thanks， but how do I get this special http request on the lws server and assemble the message to respond to the client by myself ?

**Comment by lws-team** [comment]
First, you mention the word "server" somewhere in your question :-)

The situation is the same, there is a `LWS_CALLBACK_ADD_HEADERS` for server-side that gives you the same chance to provide headers.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-callbacks.h#n270

If your ws lws_protocols is the first one, it should get this callback.

**Comment by catseeker** [comment]
I wrote a http_callback function to process http requests on the ws server(protocols[0]). 

But http (upgrade ws) request still use the built-in http processing method of lws, only http (non-upgrade ws) request can be captured. 

How do I go about capturing the http (upgrade ws) request without triggering the built-in http handling method in lws?

**Comment by lws-team** [comment]
So if I just do this and run `lws-minimal-ws-server`, I see the "hello" log.

```
diff --git a/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c b/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c
index 6e0ed9483b..ba35697ae7 100644
--- a/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c
+++ b/minimal-examples-lowlevel/ws-server/minimal-ws-server/protocol_lws_minimal.c
@@ -81,6 +81,10 @@ callback_minimal(struct lws *wsi, enum lws_callback_reasons reason,
                vhd->vhost = lws_get_vhost(wsi);
                break;
 
+       case LWS_CALLBACK_ADD_HEADERS:
+               lwsl_user("hello");
+               break;
+
        case LWS_CALLBACK_ESTABLISHED:
                /* add ourselves to the list of live pss held in the vhd */
                lws_ll_fwd_insert(pss, pss_list, vhd->pss_list);
```
