### ISSUE TITLE
LWS client disconnected: route lost triggered by POLLIN_netlink with RTA_DST NEWROUTE

### ISSUE THREAD

**Issue by wayneonway** [warmcat/libwebsockets#2603]
[Description] LWS client disconnected in some scene，it looks like the route to server lost (dst:192.168.88.89) when rops_handle_POLLIN_netlink with RTA_DST NEWROUTE，below is the logs recorded (_lws_routing_entry_dump is added temporarily for debug)：
> [2022/03/31 17:22:29:6900] I: rops_handle_POLLIN_netlink: route list size 20
> [2022/03/31 17:22:29:6900] D: _realloc: size 63: lws_smd_msg_alloc
> [2022/03/31 17:22:29:6900] D: lws_cancel_service: 
> [2022/03/31 17:22:29:6901] I: rops_handle_POLLIN_netlink: RTM 24
> [2022/03/31 17:22:29:6901] I: rops_handle_POLLIN_netlink: NEWROUTE
> [2022/03/31 17:22:29:6901] I: rops_handle_POLLIN_netlink: RTA_DST: (ipv6 unsupp)
> [2022/03/31 17:22:29:6901] I: rops_handle_POLLIN_netlink: ifidx 18
> [2022/03/31 17:22:29:6901] I: rops_handle_POLLIN_netlink: NEWROUTE rtm_type 1
> [2022/03/31 17:22:29:6901] I: _lws_routing_entry_dump:  dst: 192.168.88.89/32, gw: 192.168.2.200,  ifidx: 18, pri: 1, proto: 4
> [2022/03/31 17:22:29:6901] I: _lws_route_remove: deleting route
> [2022/03/31 17:22:29:6902] I: _lws_routing_entry_dump:  dst: (ipv6 unsupp)/64,  ifidx: 18, pri: 256, proto: 2
> [2022/03/31 17:22:29:6902] I: _lws_route_remove: deleting route
> [2022/03/31 17:22:29:6902] D: _realloc: size 104: rops_handle_POLLIN_netlink
> [2022/03/31 17:22:29:6902] I: _lws_routing_entry_dump:  dst: (ipv6 unsupp)/8,  ifidx: 18, pri: 256, proto: 3

I made a patch to fix the issue, it looks work well now:
```
diff --git a/lib/core-net/private-lib-core-net.h b/lib/core-net/private-lib-core-net.h
index fa0a503d..fc24755d 100644
--- a/lib/core-net/private-lib-core-net.h
+++ b/lib/core-net/private-lib-core-net.h
@@ -1449,6 +1449,7 @@ _lws_routing_table_dump(struct lws_context *cx);

 #define LRR_IGNORE_PRI                 (1 << 0)
 #define LRR_MATCH_SRC                  (1 << 1)
+#define LRR_MATCH_DST                  (1 << 2)

 lws_route_t *
 _lws_route_remove(struct lws_context_per_thread *pt, lws_route_t *robj, int flags);
diff --git a/lib/core-net/route.c b/lib/core-net/route.c
index 14f4beb0..c9fdc2ba 100644
--- a/lib/core-net/route.c
+++ b/lib/core-net/route.c
@@ -146,7 +146,7 @@ _lws_route_remove(struct lws_context_per_thread *pt, lws_route_t *robj, int flag
                lws_route_t *rou = lws_container_of(d, lws_route_t, list);

                if ((!(flags & LRR_MATCH_SRC) || !lws_sa46_compare_ads(&robj->src, &rou->src)) &&
-                   ((flags & LRR_MATCH_SRC) || !lws_sa46_compare_ads(&robj->dest, &rou->dest)) &&
+                   (!(flags & LRR_MATCH_DST) || !lws_sa46_compare_ads(&robj->dest, &rou->dest)) &&
                    (!robj->gateway.sa4.sin_family ||
                     !lws_sa46_compare_ads(&robj->gateway, &rou->gateway)) &&
                    robj->dest_len <= rou->dest_len &&
diff --git a/lib/roles/netlink/ops-netlink.c b/lib/roles/netlink/ops-netlink.c
index 846a9743..4f52a1e9 100644
--- a/lib/roles/netlink/ops-netlink.c
+++ b/lib/roles/netlink/ops-netlink.c
@@ -371,7 +371,8 @@ ana:
                        lws_pt_lock(pt, __func__);

                        /* returns zero on match already in table */
-                       rmat = _lws_route_remove(pt, &robj, LRR_MATCH_SRC |
+                       rmat = _lws_route_remove(pt, &robj,
+                                                               (h->nlmsg_type==RTM_NEWROUTE)?LRR_MATCH_DST:LRR_MATCH_SRC |
                                                            LRR_IGNORE_PRI);
                        lws_pt_unlock(pt);
```
[0001-fix-route-lost-triggered-by-POLLIN_netlink-with-RTA_.patch.txt](https://github.com/warmcat/libwebsockets/files/8424385/0001-fix-route-lost-triggered-by-POLLIN_netlink-with-RTA_.patch.txt)

**Comment by lws-team** [comment]
Thanks a lot for the patch... what was there was clearly mixing SRC and dest... it's on main now.

https://libwebsockets.org/git/libwebsockets/commit?id=1d8425d0ad3270b0396e62538fc4f2852b877bab
