### ISSUE TITLE
Implementation of lws_json_dump_context no longer present

### ISSUE THREAD

**Issue by egtvedt** [warmcat/libwebsockets#2605]
In commit 3f4623bb36b6079b3dc59560a9b3ffa1043e3474 the implementation of function `lws_json_dump_context()` was removed, however, the definition is still present in include/libwebsockets/lws-context-vhost.h.

Was it an accident to remove this implementation? Or should all traces of it be removed now?

**Comment by lws-team** [comment]
Right... this api and the protocol plugin duplicate some of lws_metrics that replaced it... so it's supposed to be removed.  I added a patch on main to remove the related public apis that got left hanging about.

https://libwebsockets.org/git/libwebsockets/commit?id=6e0ae67a1fd96799ae3d36100107dfb4f7e0dbb7
