### ISSUE TITLE
Unresolved external lws_threadpool_wsi_closing on windows

### ISSUE THREAD

**Issue by vulkan101** [warmcat/libwebsockets#2607]
Hi, I'm trying to build another repo which makes use of `libwebsockets`, so apologies in advance for the possible lack of clarity here. 

Looking for any hints or further information, rather than expecting a full on fix. 

Building on windows 10 with VS2019 native tools + strawberry perl, nasm. 

Some more detail around the of the issue is [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1288), but as above not expecting anyone to go deep into that. That issue has affected a few people (it's not my original post).

The main symptom is that (amongst others) the function `lws_threadpool_wsi_closing` is an unresolved external, which stops the configure of the repo, since the configure stage downloads and builds dependencies. When building all dependent libs as static, the configure completes, but the subsequent application build fails for the same reason of an unresolved external. 

I can see the resulting static library is exporting `lws_threadpool_wsi_closing`. One thing I'd like to know is where you would expect to pick this up, or if there's a way to include it in a static library build? 

I've seen reference to pthreads around this function in one of the posts I've read while trying to figure this out.. presumably this method isn't provided by pthreads - is it possible it hasn't been imported because pthreads couldn't be seen at build time?  Fwiw I have built a pthreads library and its location is passed to the cmake configure stage when building. No obvious complaints about it during the build of libwebsockets.

is it possible the cmake files in the repo above aren't switching on a flag that will generate the method `lws_threadpool_wsi_closing`? 
Any insight would be valuable. I'm not super clued up on CMake either, which isn't helping!

**Comment by lws-team** [comment]
So it seems to hinge on this from close.c is getting built

```
#if defined(LWS_WITH_THREADPOOL)
        lws_threadpool_wsi_closing(wsi);
#endif
```

...but not this from lib/misc/CMakeLists.txt that actually builds threadpool

if (LWS_WITH_THREADPOOL AND LWS_HAVE_PTHREAD_H)
        list(APPEND SOURCES misc/threadpool/threadpool.c)
endif()

It sounds like you need to either disable WITH_THREADPOOL if you don't need it, or force HAVE_PTHREAD__H.  Normally cmake will figure out if you have that in your path, and for linux or bsd or whatever, it is in your path.  Another way is add `&& defined(LWS_HAVE_PTHREAD_H)` to the #if in close.c mentioned above.

**Comment by lws-team** [comment]
Hm there is already code in CMakeLists.txt to force `LWS_HAVE_PTHREAD_H` because you gave `LWS_EXT_PTHREAD_INCLUDE_DIR`.

It seems like your lws build might be broken somehow... I would backup your CMakeCache.txt somewhere and do a full clean (eg, remove the .,/build dir contents) and rebuild from scratch... basically iterative builds with the same CMakeCache.txt and different cmake options can go into the weeds for various cmakey reasons, you should start by deleting CMakeCache.txt each time you change something to ensure that only your options deviating from the defaults are applied.

**Comment by vulkan101** [comment]
Thanks for taking a look so quickly, will chase up your suggestions today. In this situation lws is cloned (using 4.2.2 tag) and built as part of the wider sdk, it looks as though this happens fresh each time but I could be missing something.

It also might be as simple as adding `-DLWS_HAVE_PTHREAD_H` to the CMake options that are passed to the lws build! So I'll give that a whirl first.

hopefully a red herring but the build applies a patch to 4.2.2, which starts like this:
```
Author: Andy Green <andy@warmcat.com>
Date: Wed Sep 08 12:25:47 2021 +0200

cancel pipe: make sure we closed it on destroy with no EVENTFD case


diff --git a/lib/core/context.c b/lib/core/context.c
index 6194801..4f3bb45 100644
```
Could I remove the need for this by changing the version that is brought down?

**Comment by lws-team** [comment]
> 4.2.2

I'm looking at main branch, but it should be broadly similar.

After Aug 25th 2021 2cfa26 there's this on CMakeLists.txt that forces `LWS_HAVE_PTHREAD_H` if you give `LWS_EXT_PTHREAD_INCLUDE_DIR` that should make it simpler

```
@@ -620,6 +621,9 @@ CHECK_C_SOURCE_COMPILES("#include <pthread.h>\nvoid main(void) { while(1) ; } vo
 CHECK_C_SOURCE_COMPILES("#include <inttypes.h>\nvoid main(void) { while(1) ; } void xxexit(void){}" LWS_HAVE_INTTYPES_H)
 CHECK_C_SOURCE_COMPILES("#include <sys/resource.h>\nvoid main(void) { while(1) ; } void xxexit(void){}" LWS_HAVE_SYS_RESOURCE_H)
 
+if (LWS_EXT_PTHREAD_INCLUDE_DIR)
+       set(LWS_HAVE_PTHREAD_H 1)
+endif()
 
 if(CMAKE_SYSTEM_NAME MATCHES "Darwin")
        if(CMAKE_OSX_DEPLOYMENT_TARGET LESS "10.12")
```

> the build applies a patch to 4.2.2, which starts like this:
> Could I remove the need for this by changing the version that is brought down?

Yes that's on v4.3.0 (you should use v4.3-stable to get the latest stable update) as 372fdc7184

**Comment by vulkan101** [comment]
brilliant, thanks again for such a prompt response, I try this this morning

**Comment by vulkan101** [comment]
I manually set `LWS_EXT_PTHREAD_INCLUDE_DIR` in the CMakeCache of that project, and am able to build it using the visual studio solution that is generated. But I'm back to the `lws_threadpool` stuff being exported in the resulting `websockets_static.lib`.

**Comment by vulkan101** [comment]
thanks, that is exactly what I will do

**Comment by vulkan101** [comment]
- so first step done, I built with no pthread variables set, no issues. ✔️ 
- I set the pthread include directory and library locations, and the lws libraries don't contain threadpool functions. 😢 
- But, after also setting `-DLWS_WITH_THREADPOOL=ON` as an argument to CMake, I have the threadpool functions in the static library ✔️ 
- this should be enough for me to move forward with, I think I can either build the parent project with (static) dependencies and swap in this build after the fact, or build without dependencies and point at this build.
Many many thanks for you quick and helpful responses 🙏

**Comment by lws-team** [comment]
Yes threadpool is off by default... I also use threadpool + windows to build the CI runner for the windows vm, so I didn't expect any trouble standalone.  I'm not sure where the problem comes in the integrated build but I guess we can close this for now.
