### ISSUE TITLE
libwebsockets-test-echo doesn't work with echo.websocket.org 

### ISSUE THREAD

**Issue by thegautam** [warmcat/libwebsockets#261]
I can't get the test client to work against the echo websocket.org server. Do you know what might be going wrong?

Thanks!

./bin/libwebsockets-test-echo --client echo.websocket.org -d 511
[1428126579:7189] NOTICE: Built to support client operations
[1428126579:7189] NOTICE: Built to support server operations
lwsts[7697]: libwebsockets echo test - (C) Copyright 2010-2015 Andy Green <andy@warmcat.com> - licensed under LGPL2.1
lwsts[7697]: Running in client mode
lwsts[7697]: requiring server cert validation againts /usr/local/share/libwebsockets-test-server/libwebsockets-test-server.pem
lwsts[7697]: Initial logging level 511
lwsts[7697]: Library version: 1.4 9f02c5d
lwsts[7697]: IPV6 not compiled in
lwsts[7697]: libev support not compiled in
lwsts[7697]:  LWS_MAX_HEADER_LEN: 1024
lwsts[7697]:  LWS_MAX_PROTOCOLS: 5
lwsts[7697]:  SPEC_LATEST_SUPPORTED: 13
lwsts[7697]:  AWAITING_TIMEOUT: 5
lwsts[7697]:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
lwsts[7697]:  LWS_MAX_ZLIB_CONN_BUFFER: 65536
lwsts[7697]:  static allocation: 4536 + (16 x 1024 fds) = 20920 bytes
lwsts[7697]:  LWS_MAX_EXTENSIONS_ACTIVE: 3
lwsts[7697]:  canonical_hostname = ip-172-30-0-224
lwsts[7697]:  per-conn mem: 248 + 2140 headers + protocol rx buf
lwsts[7697]: Unable to load SSL Client certs file from /usr/local/share/libwebsockets-test-server/libwebsockets-test-server.pem -- client ssl isn't going to work
lwsts[7697]:   Protocol: default
lwsts[7697]: Client connecting to echo.websocket.org:80....
lwsts[7697]: libwebsocket_client_connect: direct conn
lwsts[7697]: libwebsocket_client_connect_2
lwsts[7697]: libwebsocket_client_connect_2: address echo.websocket.org
lwsts[7697]: insert_wsi_socket_into_fds: wsi=0xea51b0, sock=7, fds pos=1
lwsts[7697]: nonblocking connect retry
lwsts[7697]: libwebsocket_client_connect_2
lwsts[7697]: libwebsocket_client_connect_2: address echo.websocket.org
lwsts[7697]: connected
lwsts[7697]: WSI_TOKEN_NAME_PART 'P'
lwsts[7697]: WSI_TOKEN_NAME_PART 'P'
lwsts[7697]: Unknown method - dropping
lwsts[7697]: problems parsing header
lwsts[7697]: closing connection at LWS_CONNMODE...SERVER_REPLY
lwsts[7697]: close: just_kill_connection
lwsts[7697]: remove_wsi_socket_from_fds: wsi=0xea51b0, sock=7, fds pos=1
lwsts[7697]: not calling back closed
lwsts[7697]: libwebsocket_context_destroy
lwsts[7697]: libwebsockets-test-echo exited cleanly

**Comment by warmcat** [comment]
I reproduced it, but the problem is local to test-echo... he put "origin" as his origin and the echo.websocket.org server needs to see something more reasonable now (it didn't use to care).

I pushed a patch giving a proper origin string and he's working again.

**Comment by thegautam** [comment]
works. thanks!

On Apr 6, 2015, at 4:55 PM, Andy Green <notifications@github.com> wrote:

I reproduced it, but the problem is local to test-echo... he put "origin" as his origin and the echo.websocket.org server needs to see something more reasonable now (it didn't use to care).

I pushed a patch giving a proper origin string and he's working again.
