### ISSUE TITLE
A couple bug fixes and observations to address in a future update.

### ISSUE THREAD

**Issue by Moravien** [warmcat/libwebsockets#2611]
Hello LWS Team,

We have been working with the LWS code pretty extensively over the past year and have stumbled upon a couple areas that needed to be reworked.  Please find below my teams notes on the following issues.  Would it be possible if you included these fixes in a future update thanks!

Thanks & Best Regards,

Brandon Sloat

---

### Notes:

The context creation performs the `lws_async_dns_init()` twice on the same context. Performing this twice essentially makes a memory leak since new wsi structure pointers are created during this function and assigned to the `context->async_dns.wsi` data member. It was observed that the second call to this function during startup was creating a new wsi and overwriting the previous pointer assignment, thus not properly releasing that old pointer. This second call on the same context was also creating an extra file descriptor socket that is never used since the second wsi created would be the main one being used on this context during
LWS operations after startup. The solution is to provide a conditional check before calling this second init call to detect if async-dns initialization was already called on the same context.

---

### File(s):

- /lib/core/context.c

**BEFORE:**

_**Branch:** Main_

_**Line Number:** 1365-1368_

[Code Link](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/core/context.c#L1365-L1368)

```C
#if defined(LWS_WITH_SYS_ASYNC_DNS)
		lws_async_dns_init(context);
			//goto bail_libuv_aware;
#endif
```

---

**AFTER:**

```C
#if defined(LWS_WITH_SYS_ASYNC_DNS)
		if (context->async_dns.wsi == NULL)  
		{
		  lws_async_dns_init(context);
			//goto bail_libuv_aware;
		} 
#endif
```

---

### Notes:

It was observed that the async dns protocol callback was being entered twice during the `lws_broadcast` function with the
`LWS_CALLBACK_EVENT_WAIT_CANCELLED` reason. The system vhost was then observed to have 2 `lws_async_dns_protocol` entries in its list of protocols. During startup of LWS, the system vhost creation has logic that is adding the async dns protocol twice. The solution proposed involves checking the temp list of protocols in the progress of being created to see if it already contains the async dns protocol. If it is detected to be in the list already, the logic proposed
will skip adding it again to allow only one entry of async dns protocol structure to be in the system vhost protocol list.

---

### File(s):

- /lib/core-net/vhost.c

_**Branch:** Main_

_**Line Number:** 819-825_

[Code Link](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/core-net/vhost.c#L819-L825)

**BEFORE:**

```C
#if defined(LWS_WITH_SYS_ASYNC_DNS)
	if (!context->vhost_list) {
		memcpy(&lwsp[m++], &lws_async_dns_protocol,
		       sizeof(struct lws_protocols));
		vh->count_protocols++;
	}
#endif
```

**AFTER:**

```C
#if defined(LWS_WITH_SYS_ASYNC_DNS)
	if (!context->vhost_list) {
		
		unsigned char bAsyncAddedAlready = 0;
		for (n = 0; n < m; n++)
		{
			if (memcmp(&lwsp[n], &lws_async_dns_protocol, sizeof(struct lws_protocols)) == 0)
			{
				// Detected the same async_dns protocol is already in the list of protocols
				bAsyncAddedAlready = 1;
				break;
			}
		}

		if (bAsyncAddedAlready == 0)
		{
			memcpy(&lwsp[m++], &lws_async_dns_protocol,
			       sizeof(struct lws_protocols));
			vh->count_protocols++;
		}
  }
#endif
```

---

### Notes:

There is a bug here where the first vhost may not be a user vhost with the HTTP protocol, but a system vhost. Search for the first user vhost that exists, or until we run out of ones to look at.  This code in particular is critical as it allows the `lws_callback_on_writable` function to cancel the blocking `select()` below when new data needs to be transmitted.

---

### File(s):

- /lib/plat/unix/unix-service.c
- /lib/plat/windows/windows-service.c
  
_**Branch:** Main_

- _**Line Number Unix:** 109-119_
- [Code Link Unix](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/plat/unix/unix-service.c#L109-L119)

- _**Line Number Windows:** 75-85_
- [Code Link Windows](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/plat/windows/windows-service.c#L75-L85)

**BEFORE:**

```C
if (!pt->service_tid_detected && context->vhost_list) {
		lws_fakewsi_def_plwsa(pt);

		lws_fakewsi_prep_plwsa_ctx(context);

		pt->service_tid = context->vhost_list->protocols[0].callback(
					(struct lws *)plwsa,
					LWS_CALLBACK_GET_THREAD_ID,
					NULL, NULL, 0);
		pt->service_tid_detected = 1;
	}
```

**AFTER:**

```C
	if (!pt->service_tid_detected && context->vhost_list) {
		lws_fakewsi_def_plwsa(pt);

		lws_fakewsi_prep_plwsa_ctx(context);

    struct lws_vhost* pVhost = context->vhost_list;
    while((pVhost == context->vhost_system) && (pVhost != NULL))
    {
      pVhost = pVhost->vhost_next;
    }
    if(pVhost != NULL)
    {
      pt->service_tid = pVhost->protocols[0].callback(
        (struct lws *)plwsa, LWS_CALLBACK_GET_THREAD_ID,
        NULL, NULL, 0);
      pt->service_tid_detected = 1;
    }
  }
```

---

### Notes:

The implementation of the `lws_plat_asyncdns_init()` function seems to not handle all aspects of the native Windows code. An observation was made where certain window devices was failing its `GetNetworkParams()` function call which did not allow the DNS server addresses to be obtained correctly for LWS startup. The cause of the error was the `fi` argument being sent into the `GetNetworkParams()` was sized too small and could not fit all the network param data into this buffer for the particular windows device. A possible solution is to add additional error checking code for the return value of `GetNetworkParams()` to check for the particular error of `ERROR_BUFFER_OVERFLOW` which indicates the given buffer param is too small and a dynamic size of the network params should be utilized. `GetNetworkParams()` can be used to figure out this dynamic size.
Microsoft themselves provide examples of how to do this in their documentation within the "Examples" section.

https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getnetworkparams

---

### File(s):

- lib/plat/windows/windows-resolv.c

---

_**Branch:** Main_

_**Line Number:** 30-87_

[Code Link](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/plat/windows/windows-resolv.c#L30-L87)

---

### Notes:

It appears the assumption that the http protocol is always the first protocol in the list of callbacks is not always the case. We do not remember if us adding this actually fixed anything in particular, it was more so an observation to abide by this assumption.

---

### File(s):

- /lib/system/async-dns/async-dns.c

_**Branch:** Main_

_**Line Numbers:** 297-342_

[Code Link](https://github.com/warmcat/libwebsockets/blob/6589037217bc38af8edf74e3d3586b8c9595ffae/lib/system/async-dns/async-dns.c#L297-L342)

**BEFORE:**

```C
static int
callback_async_dns(struct lws *wsi, enum lws_callback_reasons reason,
		   void *user, void *in, size_t len)
{
	struct lws_async_dns *dns = &(lws_get_context(wsi)->async_dns);
	lws_async_dns_server_t *dsrv =
			(lws_async_dns_server_t *)wsi->a.opaque_user_data;


	switch (reason) {


	/* callbacks related to raw socket descriptor */


        case LWS_CALLBACK_RAW_ADOPT:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_ADOPT");
                break;


	case LWS_CALLBACK_RAW_CLOSE:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_CLOSE");
		break;


	case LWS_CALLBACK_RAW_RX:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_RX (%d)", (int)len);
		// lwsl_hexdump_wsi_notice(wsi, in, len);
		lws_adns_parse_udp(dns, in, len);
		break;


	case LWS_CALLBACK_RAW_WRITEABLE:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_WRITEABLE");
		lws_start_foreach_dll_safe(struct lws_dll2 *, d, d1,
					   dsrv->waiting.head) {
			lws_adns_q_t *q = lws_container_of(d, lws_adns_q_t,
							   list);


			if (//lws_dll2_is_detached(&q->sul.list) &&
			    !q->is_synthetic &&
			    (!q->asked || q->responded != q->asked))
				lws_async_dns_writeable(wsi, q);
		} lws_end_foreach_dll_safe(d, d1);
		break;


	default:
		break;
	}


	return 0;
}
```

**AFTER:**

```C
static int
callback_async_dns(struct lws *wsi, enum lws_callback_reasons reason,
		   void *user, void *in, size_t len)
{
	struct lws_async_dns *dns = &(lws_get_context(wsi)->async_dns);
  // <START MODIFICATION>
	int retVal = 0; 
  // <END MODIFICATION>

	switch (reason) {

	// <START MODIFICATION>
	case LWS_CALLBACK_GET_THREAD_ID:
	{
#if defined(WIN32) || defined(_WIN32)
		retVal = GetCurrentThreadId();
#elif defined(UNIX)
		retVal = syscall(SYS_gettid);
#endif
		break;
	}
	// <END MODIFICATION>

	/* callbacks related to raw socket descriptor */

        case LWS_CALLBACK_RAW_ADOPT:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_ADOPT");
                break;

	case LWS_CALLBACK_RAW_CLOSE:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_CLOSE");
		break;

	case LWS_CALLBACK_RAW_RX:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_RX (%d)", (int)len);
		// lwsl_hexdump_wsi_notice(wsi, in, len);
		lws_adns_parse_udp(dns, in, len);
		break;

	case LWS_CALLBACK_RAW_WRITEABLE:
		//lwsl_wsi_user(wsi, "LWS_CALLBACK_RAW_WRITEABLE");
		lws_start_foreach_dll_safe(struct lws_dll2 *, d, d1,
					   dns->waiting.head) {
			lws_adns_q_t *q = lws_container_of(d, lws_adns_q_t,
							   list);

			if (//lws_dll2_is_detached(&q->sul.list) &&
			    (!q->asked || q->responded != q->asked))
				lws_async_dns_writeable(wsi, q);
		} lws_end_foreach_dll_safe(d, d1);
		break;

	default:
		break;
	}
  // <START MODIFICATION>
	return retVal;  
  // <END MODIFICATION>
}
```

_**Note:** The code modifications have been marked with a `<START MODIFICATION>` & `<END MODIFICATION>` tag in the after code snippet to identify the difference more easily._

---

**Comment by lws-team** [comment]
Thanks for dumping the information.

The first two sound like bugs, I have patchified what you described and added those to main, thanks again.

On the fourth one, the existing code should be equivalent to Microsoft's example. it just does it with a single malloc in a while loop.  If you can see that it's not the same flow, please let me know what's wrong there (or even better, a patch that makes it work OK for you).  As far as I can see, it already does what the example code does, maybe I am just blind to what's wrong with it.

On the third and fifth one, I don't think that's a good way.  Lws has been around for 11 years now, over the years it went through various attempts to square the circle of being event loop driven when programmers insist to use threads.  The first attempts only worked under some conditions, they were replaced by the era that `LWS_CALLBACK_GET_THREAD_ID` comes from... the idea that you could call lws_callback_on_writable() from another thread and it could figure that out and take evasive actions.  After some struggle (especially with bsd poll()) hat worked better, but it blew up when people tried to use it with arbitrary event libraries that simply don't support their apis being called from other threads.

Finally lws arrived at the current era, no lws api calls are supported from other threads except lws_cancel_service() which is completely threadsafe. (it uses a pipe to wake the lws event loop).  This works on all event loops and is supported even on windows and freertos (two back:back UDP sockets are used instead of a pipe).  There's a detailed discussion of why it ended up like that here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

For the third patch, it looks like it's feeling its way to the async dns vhost without actually saying it, that's going to be a bit fragile over time.  And on the fifth patch, async dns doesn't have any business with the platform threading model, indeed the idea is to put all of that in user code because they widely differ even among pthreads by platform and version what the object types are, and even have multiple competing thread libraries that may be in use for some platforms.  So it doesn't seem right to add that (and it wouldn't deal with freertos as it is either).

I would suggest it's better to look at lws_cancel_service() flow which is the modern, supported way and then you don't need the third and fifth patches.

**Comment by Moravien** [comment]
@lws-team - Thanks for the quick response and addressing our observations!

Here is my takeaway, please let me know if I am understanding correctly?

- **Observation 1:** This will be fixed sometime in the future.
- **Observation 2:** This will be fixed sometime in the future.
- **Observation 3:** My team will need to go back to understand our implementation and fix it based on your recommendations.
- **Observation 4:** I apologize this was an oversight on my part.  I must have been looking at an older implementation of this function as it looks like the implementation provided as part of this patch https://github.com/warmcat/libwebsockets/commit/8dbe8507a3dc7e78b90b875e83729f6add7d7e88?diff=split will work for us in the future.
- **Observation 5:** My team will need to go back to understand our implementation and fix it based on your recommendations.

**Comment by lws-team** [comment]
Yes, the first two patches are already on main here, I'll push them in the next day or two.

It's kind of my fault for the confusing history of the apis... I can't easily get rid of them since user code written in that era relies on it.  But all the examples switched a few years ago and modern code should use lws_cancel_service(), which is bulletproof on all supported platforms and event libs.

**Comment by Moravien** [comment]
> Yes, the first two patches are already on main here, I'll push them in the next day or two.
> 
> It's kind of my fault for the confusing history of the apis... I can't easily get rid of them since user code written in that era relies on it. But all the examples switched a few years ago and modern code should use lws_cancel_service(), which is bulletproof on all supported platforms and event libs.

Awesome!! Thank you very much for your time and recommendations!  Have a good one!!
