### ISSUE TITLE
Fix for windows-plugins.c when compile with LWS_WITH_PLUGIN_API

### ISSUE THREAD

**Issue by dcpng** [warmcat/libwebsockets#2617]
Hi Team

Kindly ask if you may apply the following update to windows-plugins.c

Line 68
lwsl_err("%s: Failed to get '%s' on %s: %s\n", __func__, sym, libpath, lib.errmsg);

line 126
uv_dlclose(&p->u.lib); return 0;

**Comment by lws-team** [comment]
Thanks, this is pushed in main.
