### ISSUE TITLE
parser insted of ignoring custom headrers, throwing an error

### ISSUE THREAD

**Issue by calvin135** [warmcat/libwebsockets#262]
After upgrading libwebsocket 1.3 to 1.4, previously working setup is now throwing a parse error.
I see that instead of ignoring the custom headers coming in the HTTP response ( like asp.net headers which libwebsocket client has no control over ), parser is throwing a parse error , which in-turn results in the disconnection from client side. Has anyone been facing the same issue ??

**Comment by warmcat** [comment]
I just pushed a patch that should fix it.  Basically the client was wrongly also using some paranoid checking code that only makes sense on the server.

**Comment by calvin135** [comment]
Thanks a lot.. its working now..

**Comment by calvin135** [comment]
Hi Andy,  Thanks for the patch. any plans to release the official version
any-time soon ?.
