### ISSUE TITLE
libwebsocket got a crash ,caused by double free

### ISSUE THREAD

**Issue by ling1808509191** [warmcat/libwebsockets#2620]
i do a testing by running a wss client in a Android device,i found that wss would got a crash when the wifi connection is disconnect. it confuse me.Then i compile libwebsocket with asan ,and do it again. And i Found that libwebsockets will double-free wsi every time.
can we try to figure it out?

lws_vhost_unbind_wsi: vh default: count_bound_wsi 2
__lws_free_wsi: 0x70672c9c80, remaining wsi 3, tsi fds count 3
wsi 0x70672c9480: TIMEDOUT WAITING on 2 (did hdr 0, ah 0x7167be6480, wl 0)

__lws_close_free_wsi: 0x70672c9480: caller: timeout

__lws_close_free_wsi: 0x70672c9480: DROP_PROTOCOL login_call_service_protocol

__lws_close_free_wsi: closing in unestablished state 0x202

[CallbackLoginService]websocket connection error:closed before established]
__lws_close_free_wsi: real just_kill_connection: 0x70672c9480 (sockfd 11)
lwsi_set_state(0x70672c9480, 0x10000020)
__lws_close_free_wsi_final: wsi 0x70672c9480: fd 11
rops_destroy_role_h1: ah det due to close
__lws_header_table_detach: wsi 0x70672c9480: ah 0x7167be6480 (tsi=0, count = 2)
__lws_header_table_detach: wsi 0x70672c9480: ah held 30s, role/state 0x10000000 0x20,
__lws_header_table_detach: nobody usable waiting
_lws_destroy_ah: freed ah 0x7167be6480 : pool length 1
__lws_header_table_detach: wsi 0x70672c9480: ah 0x7167be6480 (tsi=0, count = 1)
lws_vhost_unbind_wsi: vh default: count_bound_wsi 1
__lws_free_wsi: 0x70672c9480, remaining wsi 2, tsi fds count 2
lws_client_conn_wait_timeout: connect wait timeout has fired
lws_client_connect_3_connect: lws_getaddrinfo46 failed 0
rops_destroy_role_h1: ah det due to close
__lws_free_wsi: 0x70672c9480, remaining wsi 1, tsi fds count 2

This is the log file. you can see that "__lws_free_wsi: 0x70672c9480" run twice. and it's the reason that made program got crashed.

**Comment by lws-team** [comment]
What version of lws is this?  Current stable release is v4.3.

**Comment by ling1808509191** [comment]
The lws version is 4.0.20. For some reason, we cannot upgrade lws right now.
Is it fixed in the latest version?
But, I avoid this bug by opening the Cmake operation LWS_WITH_SYS_ASYNC_DNS.

**Comment by lws-team** [comment]
As explained here

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.release-policy.md

I only continuously support the last stable release.  Because there is nobody else who wants to contribute the time to maintain the older releases.

I would assume whatever it is has been fixed or there would be a lot of complaints by now.  It's nice that ASYNC_DNS works around that for you.

If you update to v4.3-stable and still the same problem, let me know.

**Comment by ling1808509191** [comment]
thank you
