### ISSUE TITLE
Question: does lws official support for windows xp?

### ISSUE THREAD

**Issue by samhair** [warmcat/libwebsockets#2621]
Hi team,
It's found that lws use wsapoll on windows platform which not available in windows xp. Could you help to confirm this and any suggestion for windows xp compatibility?
Regards,
Sam

**Comment by lws-team** [comment]
Microsoft does not support XP any more, ie, no security updates since 2014

https://support.microsoft.com/en-us/windows/windows-xp-support-has-ended-47b944b8-f4d3-82f2-9acc-21c79ee6ef5e

... why would I run around supporting it?

**Comment by samhair** [comment]
Understand, thanks for your confirmation.
