### ISSUE TITLE
Doxygen documentation could be more convenient (attachement)

### ISSUE THREAD

**Issue by nick87720z** [warmcat/libwebsockets#2623]
Attachement: [libwebsockets.dox.gz](https://github.com/warmcat/libwebsockets/files/8531121/libwebsockets.dox.gz)

After first attempt to find and than learn documentation about libwebsockets (including examples), especially due to mentioned doxygen bug, where it doesn't honor some content policy, resulting to doxygen JS not work if opened from site, I got motivation to play a bit with libwebsockets.dox file, opened in doxywizard.

I already tried to write about this at mailing list, but not subscribed to it for not. Moreover, last libwebsockets.dox vesion was still not finished. At some moment I enabled two sort options, which clearly broke order in two cases - TOC and struct member order; where latest is especially unconvenient, because made impossible to determine correct order for struct initializers (without using C99 syntax like `.member = value,`). Such a tiny, but crucial mistake. I hope, this would be more convenient place to discuss my changes.

Total changes, based on version 4.3.0 (I have it from distro):

- Enabled undocumented elements to be shown, though this doesn't include static and private elements. This is most weightful change in usefulness. As sideeffect:
  - reduntant pages (some structs are mentioned on both manually defined sections and those, generated from files)
  - completely useless entries in files list, like png files (which it really tries to open like sources, gg) - probably, because doxygen scans everything included to sources, and `*.png` is there too.
- Enabled search entry. Although it's buggy (only first search works after page load/refresh, which requires to refresh before each search), also search capabilities are limited (can search def names, but not their return types or arguments), but I got it useful few times.
- Enabled graphviz-generated graphs with UML style, default (png) format, with UMLs and callgraphs. Struct boxes are clickable, leading to proper definitions. Doxy docs recommend using graphviz over builtin graph generator due to better quality. Although I don't remember if I met any real callgraphs in html output.
- Revealers - the only use I foudn for now is for above mentioned graphs (they are enough big to deserve revealers, at least in UML style, more over sometimes they are redundant because show no other structs besides described one, could due to some graph depth parameter).
- Enabled clang use (still can't determine if it makes reason - did it just because some editors / IDEs also prefer compiler integration instead of own reinvented parsers).
- Simple structs inline - makes related structs (from same file) to be easily observable.

- Man page generation.  
Well, I'm not sure, if it good to be on by default on anything pretending to be crossplatform. I expect them to be as useful as e.g. Xlib man pages - their comm
on requirement, is that you should know, what to type (`man -K` could make lightly easier start, but in my experience it's long, probably due to not using any sort of index).

**Comment by lws-team** [comment]
I tried this on main, but it spews a huge number of errors on processing the pngs, eg

```
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:509:98: warning: missing terminating ' character [-Winvalid-pp-token] [clang]
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:510:2: error: source file is not valid UTF-8 [clang]
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:510:3: error: source file is not valid UTF-8 [clang]
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:510:4: error: source file is not valid UTF-8 [clang]
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:510:9: warning: missing terminating ' character [-Winvalid-pp-token] [clang]
error: /home/agreen/projects/libwebsockets/doc-assets/jit-trust-paths.png:511:3: error: source file is not valid UTF-8 [clang]
```

**Comment by nick87720z** [comment]
Yeah, I had to append 2>/dev/null, besides that it completes
with success.

**Comment by lws-team** [comment]
I could work around it with

```
diff --git a/libwebsockets.dox b/libwebsockets.dox
index a0fcbf59d7..51dd2077cc 100644
--- a/libwebsockets.dox
+++ b/libwebsockets.dox
@@ -318,7 +318,7 @@ OPTIMIZE_OUTPUT_SLICE  = NO
 #
 # Note see also the list of default file extension mappings.
 
-EXTENSION_MAPPING      =
+EXTENSION_MAPPING      = png=none
 
 # If the MARKDOWN_SUPPORT tag is enabled then doxygen pre-processes all comments
 # according to the Markdown format, which allows for more readable
```

**Comment by nick87720z** [comment]
In Fri, 22 Apr 2022 23:08:18 -0700
Andy Green ***@***.***> wrote:

> I could work around it with
> 
> ```
> diff --git a/libwebsockets.dox b/libwebsockets.dox
> index a0fcbf59d7..51dd2077cc 100644
> --- a/libwebsockets.dox
> +++ b/libwebsockets.dox
> @@ -318,7 +318,7 @@ OPTIMIZE_OUTPUT_SLICE  = NO
>  #
>  # Note see also the list of default file extension mappings.
>  
> -EXTENSION_MAPPING      =
> +EXTENSION_MAPPING      = png=none
>  
>  # If the MARKDOWN_SUPPORT tag is enabled then doxygen pre-processes
> all comments # according to the Markdown format, which allows for
> more readable ```
> 

For me this makes no effect, probably due to this line:
```
error: Failed to map file extension 'png' to unsupported language
'none'.
```
(btw, resulting stderr output is 165Mb)

**Comment by lws-team** [comment]
I also went through and solved the remaining spew yesterday

https://libwebsockets.org/git/libwebsockets/commit?id=3ba037df3d923ad279043fa07375c0f026f69a05
