### ISSUE TITLE
Question: Are manually crafted http replies ever supported?

### ISSUE THREAD

**Issue by nick87720z** [warmcat/libwebsockets#2624]
Using evhttp with libevent is somewhat straightforward - I managed to get working both regular replies and chunked response. It's approach is straightforward - just fill evbuffer with data, optionally set some headers and send the reply. Any modern browsers are fine (tested those at webkit-gtk, palemoon and falkon). After first tests loading reply right from external file, I moved to reading embedded string resource without problem. Althoug libevent provides some higher-level auto buffers, I found no use for them.

As for libwebsockets - I did not expect it easy after first look; right now I'm struggling to get protocol callback doing at least anything useful. I can get reply request type and path, but unable to send anything besides return code with description, moreover even this is not without problems.

This line displays code with description in dillo, while surf (which I use for lone pages, webkigt-gtk based) says "Message Corrupt", curl says about incoming http-0.9, and telnet does nothing after I type "GET / HTTP/1.0", exiting after very short time - just enough to type that reply and hit enter (found advice about telnet at stackoverflow):
```
lws_return_http_status( wsi, 200, "It works");
```
Dillo showes some content length, but it seems to be obviously not reason for surf "Message Corrupt" result.
Also - curl makes it if gets option --http0.9, but received content seems including other reply part too, like headers and some binary data in very begining.

Attempt to feed external html file like this:
```
int c = lws_serve_http_file(wsi,
                            "./src/client/client.html",
                            "text/html", NULL, 0);
```
Results to mismatch between content-length (matching file size) and actual body length (just 0), as curl reports. However, this happens only if this call is followed by mentioned above status return.

It starts to look for me like manual content composition is discouraged, with only possible way is using all the burden like json descriptions, conception of http mount points for file directories (with all automagic url handling).

There is some example, attempt to use lws_write for HTTP reply, unlike file serving function, it doesn't event make browser to react immediately - this time even dillo gets nothing.
https://github.com/Wayne45/libwebsockets-http-example/blob/master/libwebsockets-example.c

So, exact question: What is necessary for manually crafted HTTP reply to be successful in libwebsockets?
(this part is completely uncovered by existing examples, all of which use only automagic http handling).

**Comment by lws-team** [comment]
Please refer first to the examples, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c

I can't help you if something you rolled yourself acts strange but if it is one of the examples with a small diff, I can also check any problem.

"http" is no longer just "http/1.1" where you can make the replies manually, it's also h2 for lws.  The lws apis work for both.

**Comment by nick87720z** [comment]
In Thu, 21 Apr 2022 07:59:00 -0700
Andy Green ***@***.***> wrote:

> Please refer first to the examples, eg
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c
> 
> I can't help you if something you rolled yourself acts strange but if
> it is one of the examples with a small diff, I can also check any
> problem.
> 
> "http" is no longer just "http/1.1" where you can make the replies
> manually, it's also h2 for lws.  The lws apis work for both.
> 

I looked examples, but could not find any, that sends other content
than files, stored in these mount points. Does it mean, that no
alternative ways supported?

I wanted intentionally to keep content embedded resource in executable,
since it's just one file.

**Comment by lws-team** [comment]
Please look at the example I linked to.

**Comment by nick87720z** [comment]
Oh, I really did not look that enough carefully. Thanks for hint, I
will look more carefully.
