### ISSUE TITLE
Is libwebsocket1.4 version officially released

### ISSUE THREAD

**Issue by sudhindra4** [warmcat/libwebsockets#263]
We see the version 1.4 on http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/ , but on the page https://libwebsockets.org/trac/libwebsockets it is mentioned that 1.3 is the latest release. Can you help me on which is the latest release.

**Comment by warmcat** [comment]
I updated the page to also tell 1.4.  Thans for pointing it out.
