### ISSUE TITLE
OpenSSL 1.1.1 link errors with v3.2.3

### ISSUE THREAD

**Issue by glenn-kaseya** [warmcat/libwebsockets#2631]
I have built v3.2.3 from source and am trying to link the static library with a C++ application on macOS.  These link errors appear when using OpenSSL 1.1.1g and 1.1.1n :

 Undefined symbols for architecture x86_64:
   "_EVP_PKEY_get_id", referenced from:
       _lws_tls_server_certs_load in libwebsockets.a(openssl-server.c.o)
   "_SSL_get1_peer_certificate", referenced from:
       _lws_tls_peer_cert_info in libwebsockets.a(x509.c.o)
 ld: symbol(s) not found for architecture x86_64

Any suggestions for fix or workaround?

**Comment by lws-team** [comment]
> v3.2.3

The last stable release is v4.3, try that.

**Comment by glenn-kaseya** [comment]
The Libwebsockets CMake search algorithm picked a different version of OpenSSL than the one used in the C++ application.
