### ISSUE TITLE
lws_http_compression_apply wrong logic

### ISSUE THREAD

**Issue by OurEra** [warmcat/libwebsockets#2633]
```c++
int
lws_http_compression_apply(struct lws *wsi, const char *name,
			   unsigned char **p, unsigned char *end, char decomp)
{
	size_t n;

	for (n = 0; n < LWS_ARRAY_SIZE(lcs_available); n++) {
		/* if name is non-NULL, choose only that compression method */
		if (name && !strcmp(lcs_available[n]->encoding_name, name))
			continue;
		/*
		 * If we're the server, confirm that the client told us he could
		 * handle this kind of compression transform...
		 */
		if (!decomp && !(wsi->http.comp_accept_mask & (1 << n)))
			continue;

		/* let's go with this one then... */
		break;
	}

	if (n == LWS_ARRAY_SIZE(lcs_available))
		return 1;

	lcs_available[n]->init_compression(&wsi->http.comp_ctx, decomp);
	if (!wsi->http.comp_ctx.u.generic_ctx_ptr) {
		lwsl_err("%s: init_compression %d failed\n", __func__, (int)n);
		return 1;
	}

	wsi->http.lcs = lcs_available[n];
	wsi->http.comp_ctx.may_have_more = 0;
	wsi->http.comp_ctx.final_on_input_side = 0;
	wsi->http.comp_ctx.chunking = 0;
	wsi->http.comp_ctx.is_decompression = decomp;

	if (lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_ENCODING,
			(unsigned char *)lcs_available[n]->encoding_name,
			strlen(lcs_available[n]->encoding_name), p, end))
		return -1;

	lwsl_info("%s: wsi %p: applied %s content-encoding\n", __func__,
		    wsi, lcs_available[n]->encoding_name);

	return 0;
}
```

lws_http_compression_apply() should choose compression from *lcs_available*, it not, exit by check *n*
```
	if (n == LWS_ARRAY_SIZE(lcs_available))
		return 1;
```

so, this statement should use break, not continue ?
```
		/* if name is non-NULL, choose only that compression method */
		if (name && !strcmp(lcs_available[n]->encoding_name, name))
			continue;
```

**Comment by lws-team** [comment]
Thanks for pointing this out... you're right, it is broken.  The exact original mistake is the `!strcmp()` part... it needs to be just `strcmp()`.

Its idea inside the loop is to `continue` for each reason it can't select it and then do the `break` at the end of the loop as a fallthrough if there were "no reasons to not select it".

Using `break` at the first check doesn't quite provide the same flow (of course... as you discovered, the existing broken code doesn't either :-) )... the `break` would skip the second "reason to not select it" check and select that built compression mode even if the vhost was not configured to provide it.

So I pushed your fix as a patch on main just removing the `!`.

https://libwebsockets.org/git/libwebsockets/commit?id=d8aada1e4618b6d12e870b679a4c4e14aeef6cca

Thanks again for looking into it and reporting it.
