### ISSUE TITLE
libweboscket 4.3 stable version compilation error on windows platform

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2635]
compiling libwebsocket using below cmake command :
openssl version: 1.1.1k

**cmake -G "NMake Makefiles" -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\\Program Files\\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\\Program Files\\libwebsockets" ..**

error when use nmake all install:

**D:\libwebsocket\libwebsockets\lib\roles\ws\client-parser-ws.c(480): error C2220: warning treated as error - no 'object' file generated
D:\libwebsocket\libwebsockets\lib\roles\ws\client-parser-ws.c(480): warning C4003: not enough arguments for function-like macro invocation 'lwsl_hexdump_wsi'
D:\libwebsocket\libwebsockets\lib\roles\ws\client-parser-ws.c(480): error C2059: syntax error: ')'
D:\libwebsocket\libwebsockets\lib\roles\ws\client-parser-ws.c(598): warning C4003: not enough arguments for function-like macro invocation 'lwsl_hexdump_wsi'
D:\libwebsocket\libwebsockets\lib\roles\ws\client-parser-ws.c(598): error C2059: syntax error: ')'
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'**

**Comment by lws-team** [comment]
This builds fine on visual studio 2019's MSVC.  Older msvc may be buggier.
