### ISSUE TITLE
support memory allocation/deallocation callback

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2636]
Hi Andy,

I'm using lws as ws and http client.
I notice there are many places in lws to allocate/deallcoate heap memory.
I have customized memory pool to optimize heap memory allocation/deallocation. 
Can lws provides interface to add callback to support customized memory allocation/deallocation?
Such as the one libcurl provides:
https://curl.se/libcurl/c/curl_global_init_mem.html

Thanks and regards

**Comment by lws-team** [comment]
For some reason I stopped getting github notifications by email and only noticed this now.

This exists already

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-misc.h?h=main#n687-695
