### ISSUE TITLE
How to validate the user authorization using libwebsockets

### ISSUE THREAD

**Issue by arunkumarvn** [warmcat/libwebsockets#2637]
Tried 3 methods to validate the user from LWS Client. 
1) Used minimal-http-client-post example provided in the minimal-examples-lowlevel folder to send user name and password like below.

```
info.path = "/user/login/"
info.method = POST
-----
inside Callback { 
    case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
     ---
switch (pss->body_part++) {
        case 0:
            qDebug()<<"Switch Case 0 =========";
            if (lws_client_http_multipart(wsi, "username=user&password=pass", NULL, text/html, &p, end))
                return -1;
            /* notice every usage of the boundary starts with -- */
            p += lws_snprintf(p, lws_ptr_diff_size_t(end, p), "my text field\xd\xa");
            break;
```
Every time I am getting **Connected with server response: 400**

2) Send Username and password using QNetwork Access Manager and received the cookies. 
**How to send cookies to Libwebsocket to authorize?**

3) Tried with LWS_WITH_HTTP_BASIC_AUTH. Getting buffer from the below API. Is the buffer a cookie? If so, how should this be validated? 
`lws_http_basic_auth_gen(ba_user, ba_password, b, sizeof(b))) 
`

The above request works and the server accepts the POST. If we send using POSTMAN and getting 204 as a status.

My question is, "is there an difference between the 'postman' POST and the libwebsocket POST that would explain why one is accepted and the other rejected? 
Are there additional calls into lws that I need to make to get the libwebsocket request to look more like the postman request?

Could you provide details to validate the user using LWS? or How to send cookies to LWS?

**Comment by lws-team** [comment]
If you want to pass auth on a particular server, you'll have to check everything the software running on the server expects from you.

> Every time I am getting Connected with server response: 400

That doesn't have to be anything to do with lws, nor can lws guarantee it can do everything needed to make that particular server happy.

> My question is, "is there an difference between the 'postman' POST 

You are in a position to answer that by looking at what each sends.
