### ISSUE TITLE
I need a little help to build client side for finnhub.io

### ISSUE THREAD

**Issue by NikolaosGian** [warmcat/libwebsockets#2642]
Hello everyone!
I want to build a client side to getting transaction notes in real-time but i dont know where i need to start & the all project gonna be writen in c.
I am new here.

**_NOTE: sorry if this is not the right spot for this post_**

**Comment by lws-team** [comment]
You should look at the binance-related examples

1) https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/client/binance?h=main
2) https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-binance?h=main

**Comment by NikolaosGian** [comment]
Thanks for the fast response i have a little problem again how to compile with those flags
First link: 
_build
Lws must have been built with LWS_ROLE_WS=1, LWS_WITH_SECURE_STREAMS=1, and
LWS_WITHOUT_EXTENSIONS=0_

Second: 
_build
Lws must have been built with LWS_ROLE_WS=1 and LWS_WITHOUT_EXTENSIONS=0_

**Comment by lws-team** [comment]
You must first build and install lws, eg, `cmake .. && make -j12 && sudo make install`

Afterwards you can build the examples.  If you have any older lws or lws packages from the OS installed, remove those first.

**Comment by NikolaosGian** [comment]
Can you give all the steps to remove lws files, and where i go to do this command at `libwebsockets/build` ?

**Comment by NikolaosGian** [comment]
I am try to compile this file client.c
[client.txt.txt](https://github.com/warmcat/libwebsockets/files/8771263/client.txt.txt)
with `gcc client.c -o client -lwebsockets` but i getting this
`usr/bin/ld: /tmp/ccrgEPXB.o:(.data.rel.ro+0x8): undefined reference to `lws_extension_callback_pm_deflate'
collect2: error: ld returned 1 exit status`

i just upload it with .txt not .c to be able to see the code

**Comment by lws-team** [comment]
If you want to use extensions, you have to enable them at cmake with `-DLWS_WITHOUT_EXTENSIONS=0` and rebuild / reinstall lws

**Comment by NikolaosGian** [comment]
I try to make my own file like this 


#include "libwebsockets.h"
#include <stdio.h>
#include <signal.h>

#include <string.h>
#include <ctype.h>
 
static volatile int exit_sig = 0;
#define MAX_PAYLOAD_SIZE 10 * 1024
static const uint32_t backoff_ms[] = { 1000, 2000, 3000, 4000, 5000 };

static struct lws_context *context;
static int interrupted;
 
void sighdl( int sig) {
    lwsl_notice( "%d traped", sig );
    exit_sig = 1;
}

static const lws_retry_bo_t retry = {
        .retry_ms_table			= backoff_ms,
        .retry_ms_table_count		= LWS_ARRAY_SIZE(backoff_ms),
        .conceal_count			= LWS_ARRAY_SIZE(backoff_ms),

        .secs_since_valid_ping		= 400,  /* force PINGs after secs idle */
        .secs_since_valid_hangup	= 400, /* hangup after secs idle */

        .jitter_percent			= 0,
};

typedef struct range {
        uint64_t		sum;
        uint64_t		lowest;
        uint64_t		highest;

        unsigned int		samples;
} range_t;

static struct my_conn {
        lws_sorted_usec_list_t	sul;	     /* schedule connection retry */
        lws_sorted_usec_list_t	sul_hz;	     /* 1hz summary */

        range_t			e_lat_range;
        range_t			price_range;

        struct lws		*wsi;	     /* related wsi if any */
        uint16_t		retry_count; /* count of consequetive retries */
} mco;


/**
 * Session context object, the structure can be customized according to needs
 */
struct session_data {
    int msg_count;
    unsigned char buf[LWS_PRE + MAX_PAYLOAD_SIZE];
    int len;
};
 




/**
 * When an event occurs on a connection under a certain protocol, the callback function executed
 *
 * wsi: pointer to WebSocket instance
 * reason: the event that caused the callback
 * The memory space allocated by the user library for each WebSocket session
 * in Some events use this parameter as a pointer to the incoming data
 * len Some events use this parameter to indicate the length of the incoming data
 */
int callback( struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    struct session_data *data = (struct session_data *) user;
    switch (reason) {
        case LWS_CALLBACK_CLIENT_ESTABLISHED://callback after connecting to the server
            lwsl_notice( "Connected to server ok!\n" );
            break;
 
        case LWS_CALLBACK_CLIENT_RECEIVE://The callback after receiving the server data, the data is in, and its length is len
            lwsl_notice( "Rx: %s\n", (char *) in );
            break;
        case LWS_CALLBACK_CLIENT_WRITEABLE://Callback when this client can send data
            if (data->msg_count <3) {
               //The first LWS_PRE bytes must be reserved for LWS
                memset( data->buf, 0, sizeof( data->buf ));
                char *msg = (char *) &data->buf[ LWS_PRE ];
                data->len = sprintf( msg, "Hello%d", ++data->msg_count );
                lwsl_notice( "Tx: %s\n", msg );
               //Send text messages via WebSocket
                lws_write( wsi, &data->buf[ LWS_PRE ], data->len, LWS_WRITE_TEXT );
            }
            break;
    }
    return 0;
}
 

static void
connect_client(lws_sorted_usec_list_t *sul)
{
        struct my_conn *mco = lws_container_of(sul, struct my_conn, sul);
        struct lws_client_connect_info conn_info;

        conn_info.context = context;
        conn_info.address = "ws.finnhub.io/";
        conn_info.port = 443;
        conn_info.path = "/?"
                     "token=ca5ucrqad3ib7i7rrcpg";

        conn_info.ssl_connection = LCCSCF_USE_SSL | LCCSCF_PRIORITIZE_READS;
    
        conn_info.host = conn_info.address;
        conn_info.origin = conn_info.address;
        conn_info.protocol = NULL;
        conn_info.retry_and_idle_policy = &retry;

        if (!lws_client_connect_via_info(&conn_info))
                /*
                 * Failed... schedule a retry... we can't use the _retry_wsi()
                 * convenience wrapper api here because no valid wsi at this
                 * point.
                 */
                if (lws_retry_sul_schedule(context, 0, sul, &retry,
                                           connect_client, &mco->retry_count)) {
                        lwsl_err("%s: connection attempts exhausted\n", __func__);
                        interrupted = 1;
                }
}


static void
range_reset(range_t *r)
{
        r->sum = r->highest = 0;
        r->lowest = 999999999999ull;
        r->samples = 0;
}

static uint64_t
get_us_timeofday(void)
{
        struct timeval tv;

        gettimeofday(&tv, NULL);

        return (uint64_t)((lws_usec_t)tv.tv_sec * LWS_US_PER_SEC) + (uint64_t)tv.tv_usec;
}


static void
sul_hz_cb(lws_sorted_usec_list_t *sul)
{
        struct my_conn *mco = lws_container_of(sul, struct my_conn, sul_hz);

        /*
         * We are called once a second to dump statistics on the connection
         */

        lws_sul_schedule(lws_get_context(mco->wsi), 0, &mco->sul_hz,
                         sul_hz_cb, LWS_US_PER_SEC);

        if (mco->price_range.samples)
                lwsl_notice("%s: price: min: %llu¢, max: %llu¢, avg: %llu¢, "
                            "(%d prices/s)\n",
                            __func__,
                            (unsigned long long)mco->price_range.lowest,
                            (unsigned long long)mco->price_range.highest,
                            (unsigned long long)(mco->price_range.sum / mco->price_range.samples),
                            mco->price_range.samples);
        if (mco->e_lat_range.samples)
                lwsl_notice("%s: elatency: min: %llums, max: %llums, "
                            "avg: %llums, (%d msg/s)\n", __func__,
                            (unsigned long long)mco->e_lat_range.lowest / 1000,
                            (unsigned long long)mco->e_lat_range.highest / 1000,
                            (unsigned long long)(mco->e_lat_range.sum /
                                           mco->e_lat_range.samples) / 1000,
                            mco->e_lat_range.samples);

        range_reset(&mco->e_lat_range);
        range_reset(&mco->price_range);
}

static uint64_t
pennies(const char *s)
{
        uint64_t price = (uint64_t)atoll(s) * 100;

        s = strchr(s, '.');

        if (s && isdigit(s[1]) && isdigit(s[2]))
                price = price + (uint64_t)((10 * (s[1] - '0')) + (s[2] - '0'));

        return price;
}
static int
callback_minimal(struct lws *wsi, enum lws_callback_reasons reason,
                 void *user, void *in, size_t len)
{
        struct my_conn *mco = (struct my_conn *)user;
        uint64_t latency_us, now_us;
        uint64_t price;
        char numbuf[16];
        const char *p;
        size_t alen;

        switch (reason) {

        case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
                lwsl_err("CLIENT_CONNECTION_ERROR: %s\n",
                         in ? (char *)in : "(null)");
                goto do_retry;
                break;

        case LWS_CALLBACK_CLIENT_RECEIVE:
                /*
                 * The messages are a few 100 bytes of JSON each
                 */

                // lwsl_hexdump_notice(in, len);

                now_us = (uint64_t)get_us_timeofday();

                p = lws_json_simple_find((const char *)in, len,
                                         "\"depthUpdate\"", &alen);
                /*
                 * Only the JSON with depthUpdate init has the numbers we care
                 * about as well
                 */
                if (!p)
                        break;

                p = lws_json_simple_find((const char *)in, len, "\"E\":", &alen);
                if (!p) {
                        lwsl_err("%s: no E JSON\n", __func__);
                        break;
                }
                lws_strnncpy(numbuf, p, alen, sizeof(numbuf));
                latency_us = now_us -
                                ((uint64_t)atoll(numbuf) * LWS_US_PER_MS);

                if (latency_us < mco->e_lat_range.lowest)
                        mco->e_lat_range.lowest = latency_us;
                if (latency_us > mco->e_lat_range.highest)
                        mco->e_lat_range.highest = latency_us;

                mco->e_lat_range.sum += latency_us;
                mco->e_lat_range.samples++;

                p = lws_json_simple_find((const char *)in, len,
                                         "\"a\":[[\"", &alen);
                if (p) {
                        lws_strnncpy(numbuf, p, alen, sizeof(numbuf));
                        price = pennies(numbuf);

                        if (price < mco->price_range.lowest)
                                mco->price_range.lowest = price;
                        if (price > mco->price_range.highest)
                                mco->price_range.highest = price;

                        mco->price_range.sum += price;
                        mco->price_range.samples++;
                }
                break;

        case LWS_CALLBACK_CLIENT_ESTABLISHED:
                lwsl_user("%s: established\n", __func__);
                lws_sul_schedule(lws_get_context(wsi), 0, &mco->sul_hz,
                                 sul_hz_cb, LWS_US_PER_SEC);
                mco->wsi = wsi;
                range_reset(&mco->e_lat_range);
                range_reset(&mco->price_range);
                break;

        case LWS_CALLBACK_CLIENT_CLOSED:
                lws_sul_cancel(&mco->sul_hz);
                goto do_retry;

        default:
                break;
        }

        return lws_callback_http_dummy(wsi, reason, user, in, len);

do_retry:
        /*
         * retry the connection to keep it nailed up
         *
         * For this example, we try to conceal any problem for one set of
         * backoff retries and then exit the app.
         *
         * If you set retry.conceal_count to be larger than the number of
         * elements in the backoff table, it will never give up and keep
         * retrying at the last backoff delay plus the random jitter amount.
         */
        if (lws_retry_sul_schedule_retry_wsi(wsi, &mco->sul, connect_client,
                                             &mco->retry_count)) {
                lwsl_err("%s: connection attempts exhausted\n", __func__);
                interrupted = 1;
        }

        return 0;
}




/**
 * Array of supported WebSocket sub-protocols
 * The sub-protocol is the element of the second parameter array of the JavaScript client WebSocket (url, protocols)
 * You need to provide a callback function for each protocol
 */
struct lws_protocols protocols[] = {
    {
       //Protocol name, protocol callback, receiving buffer size
        "ws", callback_minimal, sizeof( struct session_data ), MAX_PAYLOAD_SIZE,
       // NULL, callback,0,128
    },
    {
        NULL, NULL, 0,0//The last element is fixed to this format
    }
};
 






int main(int argc, const char **argv) {
   //signal processing function
    signal( SIGTERM, sighdl );
    int n = 0;

 
   //Parameters used to create vhost or context
    struct lws_context_creation_info ctx_info ;//= {0 };
    memset(&ctx_info, 0, sizeof ctx_info);
    lws_cmdline_option_handle_builtin(argc, argv, &ctx_info); // to print in command line

    lwsl_user("lws_context_creation_info CTX_INFO \n");

    ctx_info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    ctx_info.port = CONTEXT_PORT_NO_LISTEN;
    //ctx_info.iface = NULL;
    ctx_info.protocols = protocols;
    //ctx_info.gid = -1;
    //ctx_info.uid = -1;
    ctx_info.fd_limit_per_thread = 1 + 1 + 1;
    
   //ssl support (specify CA certificate, client certificate and private key path, turn on ssl support)
   // ctx_info.ssl_ca_filepath = "../ca/ca-cert.pem";
  //  ctx_info.ssl_cert_filepath = "./client-cert.pem";
  //  ctx_info.ssl_private_key_filepath = "./client-key.pem";
    
 
   //Create a WebSocket handler
    struct lws_context *context = lws_create_context( &ctx_info );
    if (!context){

        lwsl_err("lws init failed\n");
        return 1;
    }
    lws_sul_schedule(context, 0, &mco.sul, connect_client, 1);

    while(n >= 0 && !interrupted)
        n = lws_service(context, 0);

    lws_context_destroy(context);
    lwsl_user("Completed\n");

    return 0;
   
    struct lws_client_connect_info conn_info ;//= {0 };
    memset(&conn_info, 0, sizeof(conn_info));
    

    conn_info.context = context;
    conn_info.address = "ws.finnhub.io/";
    conn_info.port = 443;
    conn_info.path = "/?"
                     "token=ca5ucrqad3ib7i7rrcpg";

    conn_info.ssl_connection = LCCSCF_USE_SSL | LCCSCF_PRIORITIZE_READS;
    
    conn_info.host = conn_info.address;
    conn_info.origin = conn_info.address;
    conn_info.protocol = NULL;
 
   //The following call triggers the LWS_CALLBACK_PROTOCOL_INIT event
   //Create a client connection
    struct lws *wsi = lws_client_connect_via_info( &conn_info );
    while (!exit_sig) {
       //Execute the event loop (Poll) once, and wait for a maximum of 1000 milliseconds
        lws_service( context, 1000 );
       /**
         * The meaning of the following call is: when the connection can accept new data, trigger a WRITEABLE event callback
         * When the connection is sending data in the background, it cannot accept new data write requests, and all WRITEABLE event callbacks will not be executed
         */
        lws_callback_on_writable( wsi );
    }
   //Destroy the context object
    lws_context_destroy( context );
 
    return 0;
}

**and i am getting this:**

[2022/05/26 01:37:42:5203] U: lws_context_creation_info CTX_INFO
[2022/05/26 01:37:42:5207] N: lws_create_context: LWS: 4.3.99-v4.3.0-242-g96a548ca, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent
[2022/05/26 01:37:42:5209] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2022/05/26 01:37:42:5210] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2022/05/26 01:37:42:5229] N: __lws_lc_tag:  ++ [vh|1|default||-1] (2)
Segmentation fault (core dumped)

**the make file have:**

#!/bin/bash

libdir=libwebsockets
 
g++ -g -o client2 client2.c -I$libdir/include -L$libdir/build/lib -lwebsockets -DLWS_WITHOUT_EXTENSIONS=0

for first step i need to connect with websocket of finnhub.io and after that to use json parse to get infomation for change of values at web site ws
Any idea to solution this?
