### ISSUE TITLE
http/https client timeout issue

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#2648]
I am getting http connection error 
E: CLIENT_CONNECTION_ERROR: Unable to connect
for http client if there is some delay between lws_client_connect_via_info and lws_service.
Getting this error when trying to connect with libwebsockets.org or developers.google.com or any other site.
[minimal-http-client-post.zip](https://github.com/warmcat/libwebsockets/files/8796557/minimal-http-client-post.zip)

Using following functions:

lws_create_context();
lws_client_connect_via_info();

// delay of 15 seconds

lws_service(context, 0);

But if delay is less than 10 seconds then the connection established successfully.

Please suggest how to handle the case of delay? Whether delay is 15 seconds or 1 minute the connection should not be closed.

**Comment by ManojKumarChauhan** [comment]
Hi,
Thanks for the suggestion. Now there is no connection error but I can't send the data for more than one time on same connection as the connection is closed after sending the data at first time.  
This is because of LWS_CALLBACK_COMPLETED_CLIENT_HTTP event.   
When the client is done to send data to server at first time, LWS_CALLBACK_COMPLETED_CLIENT_HTTP event comes which sets a timeout.  When I try to send the data again the connection is broken due to LWS_CALLBACK_CLOSED_CLIENT_HTTP.
Is there any solution  for this?

**Comment by lws-team** [comment]
> but I can't send the data for more than one time on same connection
> LWS_CALLBACK_COMPLETED_CLIENT_HTTP

If you want to send another http transaction, create another client wsi.  This way each transaction can control its endpoint, arguments, path etc

It will reuse the tcp and tls connection under some conditions, the next transaction must indicate pipelining:

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h?h=main#n59

it must happen before the original connection times out waiting, it must be possible for the http type.

**Comment by ManojKumarChauhan** [comment]
Thanks it's working but not stable. Sometimes unable to send data after creating new wsi, also taking time. Creating context and wsi again working fine.
