### ISSUE TITLE
Getting kernel timestamps of packets while using libwebsockets

### ISSUE THREAD

**Issue by rohith2506** [warmcat/libwebsockets#2649]
According to this Kernel documentation ( https://docs.kernel.org/networking/timestamping.html )

By setting socket options with `SO_TIMESTAMPING`

```
               // Enabling kernel based timestamp
               int timestamp_options = SOF_TIMESTAMPING_RX_SOFTWARE | SOF_TIMESTAMPING_TX_SOFTWARE | SOF_TIMESTAMPING_SOFTWARE;
               if (setsockopt(fd, SOL_SOCKET, SO_TIMESTAMPING,
                              &timestamp_options, sizeof(timestamp_options)) < 0)
                       return 1;
```

and using the socket call `recvmsg` instead of `recv` by passing the `msghdr` struct, we should be able to get the kernel timestamps of each received packet. 

The problem is for secure connections, libwebsockets rely on `SSL_read` which internall uses `recv` socket call. I looked into openssl documentation whether they provide any other API which internally uses `recvmsg` but unfortunately none.  

What are my best options in order to tackle this problem?

1. I am thinking of using LD_PRELOAD and override some of the internal openssl functions such as `BIO_read` with my custom function call which uses `recvmsg` but I am not sure whether this works or not.
2. I already looked into the past issues whether someone had similar needs. I couldn't find anything but still asking whether there is any better alternative to do this.

**Comment by lws-team** [comment]
> The problem is for secure connections, libwebsockets rely on SSL_read which internall uses recv socket call.

This is not a problem, it's how it has to be done for tls.  We want the "cooked", decrypted data not the "raw" encrypted data and then we have to get it via the tls library api.

Lws does the socket creation and tcp connect handling, you could add setting the setsockopt() at lws side.

There are a wide range of tls libs and related api levels, for openssl or openssl-like libs such as wolfssl, boringssl, libressl etc I am not sure injecting a strong binding for the BIO_ apis will generally solve it, but it might be enough to solve it for the openssl you are using.

mbedtls doesn't have a BIO concept but it does have callbacks for socket io that appear in lws plat that gives you a way to do what you want in lws... 

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/freertos/freertos-sockets.c?h=main#n374
https://libwebsockets.org/git/libwebsockets/tree/lib/plat/unix/unix-sockets.c?h=main#n630
