### ISSUE TITLE
lws_sul_schedule stagged delay minimum?

### ISSUE THREAD

**Issue by simplyorganic** [warmcat/libwebsockets#2654]
Hi there, was wondering if there's a minimum for the us param in `lws_sul_schedule`? I see sample code supplying it as 10*LWS_US_PER_MS but was curious if setting it to 1us causes any issues. Reason I ask is I'm seeing some odd behavior I can't seem to understand and wanted to ensure I'm within the bounds of what's allowed. I have read almost all the READMEs.

**Comment by lws-team** [comment]
Yes you can do so.  In reality it means "do it next time around the event loop without waiting", which will typically take 100-300us depending on the platform.
