### ISSUE TITLE
include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2655]
Hi I am getting below error while compiling with below option:

 cmake -G "NMake Makefiles" -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Wi
n64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\libwebsockets" ..
-- The C compiler identification is MSVC 19.16.27048.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
SMD requires pthreads
-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Success
-- Performing Test LWS_HAVE___inline__
-- Performing Test LWS_HAVE___inline__ - Failed
-- Performing Test LWS_HAVE___inline
-- Performing Test LWS_HAVE___inline - Success
-- Performing Test LWS_HAVE_MALLOC_TRIM
-- Performing Test LWS_HAVE_MALLOC_TRIM - Failed
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE - Failed
-- Looking for fork
-- Looking for fork - not found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - not found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - not found
-- Looking for execvpe
-- Looking for execvpe - found
-- Looking for getifaddrs
-- Looking for getifaddrs - not found
-- Looking for snprintf
-- Looking for snprintf - not found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for getloadavg
-- Looking for getloadavg - not found
-- Looking for atoll
-- Looking for atoll - found
-- Looking for _atoi64
-- Looking for _atoi64 - found
-- Looking for _stat32i64
-- Looking for _stat32i64 - found
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for localtime_r
-- Looking for localtime_r - not found
-- Looking for gmtime_r
-- Looking for gmtime_r - not found
-- Looking for ctime_r
-- Looking for ctime_r - not found
-- Looking for getgrgid_r
-- Looking for getgrgid_r - not found
-- Looking for getgrnam_r
-- Looking for getgrnam_r - not found
-- Looking for getpwuid_r
-- Looking for getpwuid_r - not found
-- Looking for getpwnam_r
-- Looking for getpwnam_r - not found
-- Looking for timegm
-- Looking for timegm - not found
-- Looking for in6addr.h
-- Looking for in6addr.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - not found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for sys/capability.h
-- Looking for sys/capability.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - not found
-- Performing Test LWS_HAVE_WIN32_AFUNIX_H
-- Performing Test LWS_HAVE_WIN32_AFUNIX_H - Success
-- Looking for cap_set_flag in cap
-- Looking for cap_set_flag in cap - not found
-- Looking for 3 include files stdlib.h, ..., string.h
-- Looking for 3 include files stdlib.h, ..., string.h - found
-- Performing Test LWS_HAS_INTPTR_T
-- Performing Test LWS_HAS_INTPTR_T - Success
-- Performing Test LWS_HAS_GETOPT_LONG
-- Performing Test LWS_HAS_GETOPT_LONG - Failed
-- Performing Test LWS_HAVE_RTA_PREF
-- Performing Test LWS_HAVE_RTA_PREF - Failed
-- Performing Test LWS_HAVE_SUSECONDS_T
-- Performing Test LWS_HAVE_SUSECONDS_T - Failed
-- Found ZLIB: C:/Program Files (x86)/zlib/lib/zlib.lib (found version "1.2.11")
zlib/miniz include dirs: C:/Program Files (x86)/zlib/include
zlib/miniz libraries: C:/Program Files (x86)/zlib/lib/zlib.lib
-- Performing Test LWS_HAVE_PIPE2
-- Performing Test LWS_HAVE_PIPE2 - Failed
-- Performing Test LWS_HAVE_TCP_USER_TIMEOUT
-- Performing Test LWS_HAVE_TCP_USER_TIMEOUT - Failed
Compiling with SSL support
-- Found OpenSSL: C:/Program Files/OpenSSL-Win64/lib/libcrypto.lib (found version "1.1.1k")
OpenSSL include dir: C:/Program Files/OpenSSL-Win64/include
OpenSSL libraries: C:/Program Files/OpenSSL-Win64/lib/libssl.lib;C:/Program Files/OpenSSL-Win64/lib/libcrypto.lib
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
-- Looking for SSL_set_info_callback
-- Looking for SSL_set_info_callback - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
-- Looking for X509_VERIFY_PARAM_set1_host
-- Looking for X509_VERIFY_PARAM_set1_host - not found
-- Looking for RSA_set0_key
-- Looking for RSA_set0_key - not found
-- Looking for X509_get_key_usage
-- Looking for X509_get_key_usage - not found
-- Looking for SSL_CTX_EVP_PKEY_new_raw_private_key
-- Looking for SSL_CTX_EVP_PKEY_new_raw_private_key - not found
-- Looking for SSL_CTX_get0_certificate
-- Looking for SSL_CTX_get0_certificate - not found
-- Looking for SSL_get0_alpn_selected
-- Looking for SSL_get0_alpn_selected - not found
-- Looking for SSL_set_alpn_protos
-- Looking for SSL_set_alpn_protos - not found
-- Looking for EVP_aes_128_cfb8
-- Looking for EVP_aes_128_cfb8 - not found
-- Looking for EVP_aes_128_cfb128
-- Looking for EVP_aes_128_cfb128 - not found
-- Looking for EVP_aes_192_cfb8
-- Looking for EVP_aes_192_cfb8 - not found
-- Looking for EVP_aes_192_cfb128
-- Looking for EVP_aes_192_cfb128 - not found
-- Looking for EVP_aes_256_cfb8
-- Looking for EVP_aes_256_cfb8 - not found
-- Looking for EVP_aes_256_cfb128
-- Looking for EVP_aes_256_cfb128 - not found
-- Looking for EVP_aes_128_xts
-- Looking for EVP_aes_128_xts - not found
-- Looking for EVP_aes_128_ofb
-- Looking for EVP_aes_128_ofb - not found
-- Looking for EVP_aes_128_ecb
-- Looking for EVP_aes_128_ecb - not found
-- Looking for EVP_aes_128_ctr
-- Looking for EVP_aes_128_ctr - not found
-- Looking for RSA_verify_pss_mgf1
-- Looking for RSA_verify_pss_mgf1 - not found
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found
-- Looking for EVP_PKEY_new_raw_private_key
-- Looking for EVP_PKEY_new_raw_private_key - not found
-- Looking for SSL_SESSION_set_time
-- Looking for SSL_SESSION_set_time - not found
-- Looking for EC_KEY_new_by_curve_name
-- Looking for EC_KEY_new_by_curve_name - not found
-- Performing Test LWS_HAVE_SSL_EXTRA_CHAIN_CERTS
-- Performing Test LWS_HAVE_SSL_EXTRA_CHAIN_CERTS - Failed
-- Performing Test LWS_HAVE_EVP_MD_CTX_free
-- Performing Test LWS_HAVE_EVP_MD_CTX_free - Failed
-- Performing Test LWS_HAVE_OPENSSL_STACK
-- Performing Test LWS_HAVE_OPENSSL_STACK - Success
-- Looking for ECDSA_SIG_set0
-- Looking for ECDSA_SIG_set0 - not found
-- Looking for BN_bn2binpad - not found
-- Looking for EVP_aes_128_wrap
-- Looking for EVP_aes_128_wrap - not found
-- Looking for EC_POINT_get_affine_coordinates
-- Looking for EC_POINT_get_affine_coordinates - not found
-- Looking for TLS_client_method
-- Looking for TLS_client_method - not found
-- Looking for TLSv1_2_client_method
-- Looking for TLSv1_2_client_method - not found
Searching for OpenSSL executable and dlls
DEBUGAssuming OpenSSL release 1.1.1k >= 1.1.0 for dll discovery
VERBOSECRYPTO32_NAME=libcrypto-1_1.dll
VERBOSECRYPTO64_NAME=libcrypto-1_1-x64.dll
VERBOSESSL32_NAME=libssl-1_1.dll
VERBOSESSL64_NAME=libssl-1_1-x64.dll
VERBOSEOPENSSL_EXECUTABLE_PATH=C:/Program Files/OpenSSL-Win64/bin
DEBUGREGEX_MATCH=""
DEBUGCMAKE_MATCH_1=""
VERBOSEOPENSSL_EXECUTABLE_BIN_PATH=
VERBOSELIBCRYPTO_BIN=C:/Program Files/OpenSSL-Win64/bin/libcrypto-1_1-x64.dll
VERBOSELIBSSL_BIN=C:/Program Files/OpenSSL-Win64/bin/libssl-1_1-x64.dll
OpenSSL executable: C:/Program Files/OpenSSL-Win64/bin/openssl.exe
 GENCERTS = 1
Generating SSL Certificates for the test-server...
OPENSSL_INPUT_WIN_PATH = C:\libweb\build_test\openssl_input.txt
cmd = "C:/Program Files/OpenSSL-Win64/bin/openssl.exe" req -new -newkey rsa:2048 -days 10000 -nodes -x509 -keyout "C:/libweb/build_test/libwebsockets-test-server.key.pem" -out "C:/libweb/bu
ild_test/libwebsockets-test-server.pem"

CMake Warning at lib/tls/CMakeLists.txt:491 (message):
  !!! Failed to generate SSL certificate for Test Server using cmd.exe !!!:
  OpenSSL return code = 1

OpenSSL dlls found:
  Libeay:
  SSLeay:
DIR C:/libweb/build_test CMP C:/libweb/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: C:/libweb/build_test

PS C:\libweb\build_test> nmake all install

Microsoft (R) Program Maintenance Utility Version 14.16.27048.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target GENHDR
[  0%] Creating build include dir
[  0%] Built target GENHDR
Scanning dependencies of target websockets
[  0%] Building C object lib/CMakeFiles/websockets.dir/plat/windows/windows-fds.c.obj
windows-fds.c
C:\libweb\include\libwebsockets/lws-genhash.h(85): error C2079: 'ctx' uses undefined struct 'hmac_ctx_st'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
PS C:\libweb\build_test>

could you please let me the reason behind it

**Comment by sush126** [comment]
it says 
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found
while doing cmake , and error also similar ,could you please let me know the reason behind it?

**Comment by lws-team** [comment]
Have a look at the second section here https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md
