### ISSUE TITLE
policy json http_url parameter maximum length restriction?

### ISSUE THREAD

**Issue by dforsber** [warmcat/libwebsockets#2656]
I know I should be using the metadata API at the end probably to set query parameters to `http_url` programmatically. However, the examples have these, so I'm wondering what the length limit for this parameter is? Just trying to validate things early on.

I'm trying to add long query parameters string (1620 chars)  into the `http_url` in the policy JSON document itself. On the "textual" hexdump I can see the `GET /` string starting. However, it is missing tons of chars (1524 to be precise) after '/', and has about 96 chars of the end of the `http_url` parameter. However, I get longer hexdump output if I add more "/" in the start of the `http_url`, which is confusing. The same query param string works with `wscat` as is, so the format of it must be right.

The above probably does not make much sense so my question is that:

- Does `http_url` string parameter in the policy JSON have maximum size limit?

**Comment by dforsber** [comment]
Hmm, the hexdump is only partial :D - so this is probably a non-issue.

**Comment by lws-team** [comment]
The metadata itself doesn't have any special limits, but after being metadata, it ends up being part of an http wsi header, which does have an overall length limit of 4096 as the default.

You can control this limit with context creation time info member `.max_http_header_data`.

**Comment by dforsber** [comment]
Hmm, its not the hexdump dropping things but something earlier. I get this line that says the len is 387, even though the plain `http_url` parameter in the policy is over 1600. The hexdump shows that the `http_url` is stripped from the start and last 95 bytes are picked up only.

```
lws_ssl_capable_write: len 387
```

**Comment by lws-team** [comment]
These are just chunks being written going out on the wire.  Stuff may be written before, and / or after.

**Comment by dforsber** [comment]
```
"http_url":		"/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade",

[2022/06/13 16:46:31:8765] N: GET //stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade HTTP/1.1..t
[2022/06/13 16:46:31:8765] N: ragma: no-cache..Cache-Control: no-cache..Host: fstream.binance.com..Origin: https://:
[2022/06/13 16:46:31:8765] N: stream.binance.com..Upgrade: websocket..Connection: Upgrade..Sec-WebSocket-Key: P0KoHi
[2022/06/13 16:46:31:8765] N: Jex/4NRTFHmq1q6Q==..Sec-WebSocket-Version: 13....

"http_url":		"/longPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/longPath9/longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/longPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/longPath9/longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade",

[2022/06/13 16:56:45:3736] N: GET /ongPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdtn
[2022/06/13 16:56:45:3736] N: aggTrade HTTP/1.1..Pragma: no-cache..Cache-Control: no-cache..Host: fstream.binance.ct
[2022/06/13 16:56:45:3736] N: m..Origin: https://fstream.binance.com..Upgrade: websocket..Connection: Upgrade..Sec-o
[2022/06/13 16:56:45:3737] N: ebSocket-Key: RPIMN4zOTesx+mpOp47t4g==..Sec-WebSocket-Version: 13....
```

Is the above as it should be?

**Comment by lws-team** [comment]
> Ok, so the hexdump showing cropped http url request parameters is ok then and you're saying that the http_url json policy parameter ending up in the request is working as it should. 

I did not say any of that.  I have no idea what your code is doing, where your hexdump came from etc.  It's OK I don't want to know either.  It's evidently not using metadata as the examples at the moment so you should fix that.

This is why there are so many examples, so we both have the same code, you can talk to me about my examples, I can reproduce them, see what the code does, fix them if they are broken.

**Comment by dforsber** [comment]
It is not my code, it is the code from this repo. Nothing added by me, only tuned the `http_url` parameter in the example-policy.json.

Anyway, with the c code example you provided, the hexdump looks correct. The same example mininmal binance.

```
[2022/06/14 06:40:27:9354] N: GET //longPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/b
[2022/06/14 06:40:27:9354] N: ongPath9/longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/lo3
[2022/06/14 06:40:27:9354] N: gPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/longPath9p
[2022/06/14 06:40:27:9354] N: longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@agg/
[2022/06/14 06:40:27:9354] N: rade HTTP/1.1..Pragma: no-cache..Cache-Control: no-cache..Host: fstream.binance.com..r
[2022/06/14 06:40:27:9354] N: rigin: https://fstream.binance.com..Upgrade: websocket..Connection: Upgrade..Sec-WebSc
[2022/06/14 06:40:27:9355] N: cket-Key: aw3SwauTuMYokDH317/HCw==..Sec-WebSocket-Version: 13....

```

So, I suspect there is something fishy when the parameter is in the policy json document as then the hexdump only shows it partially, loosing most of the path.

**Comment by lws-team** [comment]
> So, I suspect there is something fishy when the parameter is in the policy json

That second parameter there is for an optional http header to take the metadata.  It doesn't do what you thought nor does anything say that it should.

**Comment by dforsber** [comment]
Ok, maybe I misunderstood the `http_url` parameter then. Examples in this repo show that it can have path and query params, but when I add them long enough they get stripped away.

Here is the modified main.c that works and produces correct hex dump:

```
int main(int argc, const char **argv)
{
	struct lws_context_creation_info info;
	struct lws_ss_handle *h;
	const char *mypath = "/longPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/longPath9/longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/longPath/longPath2/longPath3/longPath4/longPath5/longPath6/longPath7/longPath8/longPath9/longPath10/longPath11/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade";
	// "http_url": "/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade",

	lws_context_info_defaults(&info, "example-policy.json");
	lws_cmdline_option_handle_builtin(argc, argv, &info);
	signal(SIGINT, sigint_handler);

	lwsl_user("LWS minimal Secure Streams binance client\n");

	info.extensions = extensions;

	cx = lws_create_context(&info);
	if (!cx)
	{
		lwsl_err("lws init failed\n");
		return 1;
	}

	if (lws_ss_create(cx, 0, &ssi_binance_t, NULL, &h, NULL, NULL))
	{
		lwsl_cx_err(cx, "failed to create secure stream");
		interrupted = 1;
	}

	if (lws_ss_set_metadata(h, "path", mypath, strlen(mypath)))
	{
		lwsl_err("%s: failed to use metadata %s\n", __func__, mypath);
		return 1;
	}

	lws_context_default_loop_run_destroy(cx);

	/* process ret 0 if actual is as expected (0, or--expected-exit 123) */

	return lws_cmdline_passfail(argc, argv, test_result);
}
```

**Comment by dforsber** [comment]
> > So, I suspect there is something fishy when the parameter is in the policy json
> 
> That second parameter there is for an optional http header to take the metadata. It doesn't do what you thought nor does anything say that it should.

```
"http_url": "/service?param=value1"
```

There is no 2nd parameter.
