### ISSUE TITLE
lws_hdr_custom functions backwards compatibility?

### ISSUE THREAD

**Issue by simplyorganic** [warmcat/libwebsockets#2658]
Hey Andy,

Recently performed a _significant_ lws upgrade from 4.0 -> 4.3 in order to debug some odd behavior and after re-compiling, I get 
```
error: use of undeclared identifier 'lws_hdr_custom_next'
error: use of undeclared identifier 'lws_hdr_custom_next_length'
error: use of undeclared identifier 'lws_hdr_custom_next_name_copy'
error: use of undeclared identifier 'lws_hdr_custom_next_value_copy'
error: use of undeclared identifier 'lws_hdr_custom_next'
```

I seem to have mistakenly had the impression LWS was backwards compatible. With that being said, I was hoping for some guidance on what these were replaced with? Or if it's "safe" to port the old definitions forward? (Figured there was a reason they were removed so wanted to ask first)

Thanks!

**Comment by lws-team** [comment]
`lws_hdr_custom_next` is not an lws api even in v4.0.

You should look closer into where they came from originally.
