### ISSUE TITLE
Connect "Update Speed: Real-time" via wss://stream.binance.com:9443

### ISSUE THREAD

**Issue by joaoguariglia** [warmcat/libwebsockets#2659]
Good night, I would like to receive information on 1 currency pair for example bnbusdt in real time via streaming I don't know how I should configure the client, it connects but nothing does:

![image](https://user-images.githubusercontent.com/23190903/173956613-c830c9f0-d239-4325-adc8-17c7153fad8f.png)

![image](https://user-images.githubusercontent.com/23190903/173956646-dc097171-d847-4c70-b6af-b904efe36b5e.png)

**Comment by lws-team** [comment]
Is the binance minimal example working OK before you changed the path?

The address in the example if **f**stream.binance.com

The example path was "        i.path = "/stream?streams=btcusdt@depth@0ms/btcusdt@bookTicker/btcusdt@aggTrade";

**Comment by joaoguariglia** [comment]
Hello, thanks for the answer, yes I used the default way and it worked, but in terms of performance if I use the address I mentioned because it is "in live" wouldn't it be much faster to collect information?

**Comment by lws-team** [comment]
Dunno... it sounds like you should talk to binance not me.  If they send something on the connection, we should receive it.

If they don't send anything, what am I supposed to do about that?

**Comment by joaoguariglia** [comment]
Right, it was more to have a suggestion, because in the Binance manual it says to use this address:
![image](https://user-images.githubusercontent.com/23190903/174307644-aea9c2d7-1fec-4044-9147-6292becab074.png)
and I saw that calling the address by this method the data is live stream without the need to put the "seconds"
![image](https://user-images.githubusercontent.com/23190903/174307962-135e7d06-3693-4c78-a696-f15b21ecf419.png)

so I tried to do as it says in their manual, what happens is that it connects but nothing does, so I wanted to know if I'm doing something wrong.

**Comment by lws-team** [comment]
You can check to see if we're being sent anything by temporarily using `LWS_TLS_LOG_PLAINTEXT_RX` at cmake, it will show what we receive before it is processed by the library (it will spew if there is a lot of traffic).

If we're not being sent anything, you can also use `LWS_TLS_LOG_PLAINTEXT_TX` to see exactly what we sent the server.  If that looks right, you need to talk to the owners of the server.

**Comment by joaoguariglia** [comment]
ok thanks
