### ISSUE TITLE
LWS_MAX_SMP on debian

### ISSUE THREAD

**Issue by coldsource** [warmcat/libwebsockets#2660]
Hi,

On debian 11, libwebsockets is compiled with LWS_MAX_SMP=1. On previous version it was 32.

Does this mean that I can't use lws_service_tsi() to have multiple threads handle websocket connections ?

If so, why not compiling library with a max >1 so the client can decide whether or not to use multiple threads ?

Regards,

**Comment by lws-team** [comment]
Whomever maintains it on Debian can choose what options suit them best.  You can always just build it yourself.

Using multiple threads is generally less stable because I don't run it like that myself.  But there are users of it, and on and off, they find problems and send patches.
