### ISSUE TITLE
libwebsockets-test-server and libwebsockets-test-server-extpoll identical (4.3.2 and higher)

### ISSUE THREAD

**Issue by tetti-de** [warmcat/libwebsockets#2661]
The binary code of the test-apps  libwebsockets-test-server and libwebsockets-test-server-extpoll are identical !

Reason, in libwebsockets/test-apps/CMakeLists.txt is the cmake cmd set_property(
    PROPERTY COMPILE_DEFINITIONS
      EXTERNAL_POLL
wrong.

It should be 
LWS_WITH_EXTERNAL_POLL instead of EXTERNAL_POLL

**Comment by lws-team** [comment]
Thanks for pointing this out, I pushed a patch with your fix on main and v4.3-stable.
