### ISSUE TITLE
TLS False Start support

### ISSUE THREAD

**Issue by qdztxc** [warmcat/libwebsockets#2663]
Hi Andy,

I'm using lws as http client. I need to send request to a https server fequenctly.
From the tcpdump data it seems lws doesn't open TLS false start by default. Is there a way to open it to reduce RT?

Thanks and regards.

**Comment by lws-team** [comment]
That's a TLS1.2 thing AIUI, as such I don't plan to support it.  You should use TLS 1.3 and make sure the session cache is enabled, LWS_WITH_TLS_SESSIONS.

If it's that frequently, you should use h2 and set this to something bigger than the server to maximize your chance to reuse an existing connection.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-context-vhost.h#n352
