### ISSUE TITLE
How to link to dl for custom openssl?

### ISSUE THREAD

**Issue by simplyorganic** [warmcat/libwebsockets#2665]
Hi there, I have a build where when linking to libcrypto.a, fails to supply `-ldl` and thus results in undefined refereces to dlopen()/dlsym()/etc and ultimately fails. This brings up issues for all test apps: client, server, server-extpoll, and lejp. How can I supply it these values? I've added dl to `${LIB_LIST_AT_END}` and `${LIB_LIST` to no avail. 

`[cmake] [2022-06-21 01:30:20] [INFO]/bin/g++ -pthread -fstack-protector -fstack-protector-strong -fexceptions -frtti -ffunction-sections -fdata-sections -O3 -DNDEBUG -Wl,--as-needed -pthread -g -rdynamic CMakeFiles/test-client.dir/test-client.c.o -o ../bin/libwebsockets-test-client  -static-libstdc++ -static-libgcc ../lib/LibwebsocketsStatic.a -ldl -lpthread -lm -ldl -static-libstdc++ -static-libgcc <path to dependency dir>/libssl.a <path to dependency dir>/libcrypto.a `

**Comment by lws-team** [comment]
It seems a link ordering thing since there are 2 x -ldl in what you pasted.

For the test apps on main, they should use the AT_END stuff at the end AFAICS

https://libwebsockets.org/git/libwebsockets/tree/test-apps/CMakeLists.txt#n118

**Comment by simplyorganic** [comment]
Still seeing 2x ldl but that shouldn't be an issue with how smart linkers are nowadays. Managed to work around this by adding -ldl to this line in the root cmake file: https://libwebsockets.org/git/libwebsockets/tree/CMakeLists.txt#n882
e.g.,
`	list(APPEND LIB_LIST_AT_END -lpthread -ldl)
`
