### ISSUE TITLE
how to make lws_service non blocking

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#2669]
lws_service is a blocking call as it uses a default timeout of 23 days.
Is there any way to make it non blocking? 
If I call lws_cancel_service from another thread then this may cause issues like data loss.

**Comment by lws-team** [comment]
If you call lws_cancel_service() from another thread, it will wake the event loop immediately.

It's not blocking, it is waiting for events, file or socket or scheduled ones.

It sounds like you should have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

**Comment by ManojKumarChauhan** [comment]
It's correct that lws_cancel_service will wake the event loop but what about a case when the connection is closed? 
Assuming a case when the callback function receives LWS_CALLBACK_CLIENT_CLOSED and at the same time I call lws_cancel_service/lws_callback_on_writable from another thread?

**Comment by lws-team** [comment]
>   I call lws_cancel_service/lws_callback_on_writable from another thread

Those two are not the same.  You may ONLY call lws_cancel_service() from another thread, all other lws apis are forbidden to be called from other threads.
