### ISSUE TITLE
Seemingly random, missing method definitions for secure streams

### ISSUE THREAD

**Issue by PopusBenedictus** [warmcat/libwebsockets#2671]
I wanted to give secure streams a go, and I've noticed that when adapting parks of the ws-client example there are some methods and/or macro definitions either missing or the methods certain macros drop in their place are not there.

I'm including libwebsockets.h, as the example does. What I've noticed being inaccessible so far is: LWS_SS_USER_TYPEDEF, lws_ss_from_user(), lwsl_ss_user() and lws_ss_cx_from_user(). Using CLion, if I go look at the headers in which these things are defined per the docs, they are not being ignored/excluded.

I am using the MSVC (VS2022, Windows 11) with cmake 3.21. I used vcpkg originally to install the library and pull it into the project. Then since it was a couple minor versions behind (4.3.0) what came from vcpkg, I instead pulled libwebsockets in as a git submodule, checked out v4.3.2. The issue persists even with this arrangement. My top level CMakeLists.txt for the project pertaining to lws looks like so:

```
option(LWS_WITH_SHARED OFF)
option(LWS_WITH_EXPORT_LWSTARGETS OFF)
option(LWS_WITHOUT_TESTAPPS ON)
option(LWS_WITH_MINIMAL_EXAMPLES OFF)
option(LWS_WITH_LIBUV ON)
option(LWS_WITH_SECURE_STREAMS ON)
option(LWS_WITH_SECURE_STREAMS_PROXY_API ON)

add_subdirectory("third-party/libwebsockets")
link_directories("${CMAKE_BINARY_DIR}/third-party/libwebsockets/lib")
get_property(XRC_PRIVATE_LINK_DIRECTORIES DIRECTORY PROPERTY LINK_DIRECTORIES)
set_property(GLOBAL PROPERTY XRC_GLOBAL_LINK_DIRECTORIES ${XRC_PRIVATE_LINK_DIRECTORIES})
```

In the core library for the project I then add this

```
get_property(XRC_GLOBAL_LINK_DIRECTORIES GLOBAL PROPERTY XRC_CORE_LINK_DIRS)
link_directories(${XRC_CORE_LINK_DIRS})
target_link_libraries(xrc-core websockets_static)
```

I was marking the option to not include server functions, but I thought maybe that could be contributing to the issue and so I abstained from this. LWS finds OpenSSL on its own e.g. I didn't make any special arrangements for it.

I know secure streams is enabled by default, but I turned it and the proxy api on since I'm out of ideas.

Thoughts? I don't necessarily need it to be a submodule or statically linked, that's just where I ended up trying to find a solution.

Thank you.

**Comment by lws-team** [comment]
Are you bringing in the libwebsockets.h that you think you are, or one belonging to an older lws than the examples you're following?  Isn't it that those 'random missing' apis only exist in lws main branch?
