### ISSUE TITLE
get netlink bind failed

### ISSUE THREAD

**Issue by orgoldshmidt** [warmcat/libwebsockets#2673]
HI,
When calling lws_create context while using a foreign event loop I get the message "rops_pt_init_destroy_netlink: netlink bind failed".
As I saw, the error comes from rops_pt_init_destroy_netlink function while trying to bind the new socket he creates.
any reason why the problem occurs?
The process runs on root privileges.

**Comment by lws-team** [comment]
A process is only allowed by the kernel to open one netlink socket / have one lws_context if Netlink support is enabled.
