### ISSUE TITLE
error: implicit declaration of function 'lws_default_loop_exit' is invalid in C99

### ISSUE THREAD

**Issue by diuming** [warmcat/libwebsockets#2674]
libwebsockets 4.3.2
macOS Monterey 12.4

I try to build server from your sample that I encounter some errors in C99.

error: implicit declaration of function 'lws_default_loop_exit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
error: implicit declaration of function 'lws_context_info_defaults' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
error: implicit declaration of function 'lws_context_default_loop_run_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
error: implicit declaration of function 'lws_cmdline_passfail' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

How do i solve my problems?
thx

**Comment by lws-team** [comment]
Are you using examples from main branch and v4.3 lws?  Either use examples from main with main lws or examples from v4.3 lws with v4.3 lws.

**Comment by diuming** [comment]
Sorry! my mistake.

libwebsockets library from tag 4.3.2
examples from main branch

ths
