### ISSUE TITLE
Is it possible to create web socket server without http protocol?

### ISSUE THREAD

**Issue by diuming** [warmcat/libwebsockets#2675]
I try to use libwebsockets library to create a web socket server(ws://) and I refer to some examples.
```
static struct libwebsocket_protocols protocols[] = {
  /* first protocol must always be HTTP handler */
  { "http-only", callback_http, 0 },
  { "lws-protocol", callback_lws, 0 },
  { NULL, NULL, 0 }
};
```

Can I create a pure web socket server without http protocol.

thx

**Comment by lws-team** [comment]
No, ws connections always start out as http and may choose to upgrade to ws.  So in RFC6455, ws is always dependent on http first.
