### ISSUE TITLE
unable to generate SSLKEYLOGFILE using version 4.3.2

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2676]
Hi All,
unable to generate file in SSLKEYLOGFILE path withversion 4.3.2 . It is Working with old commit hash.

My CMakeCache.txt is not showing LWS_HAVE_SSL_CTX_set_keylog_callback is set to 1.
LWS_HAVE_SSL_CTX_set_keylog_callback  option is not available in CMakeCache.txt with version 4.3.2
.
Does set_keylog_callback support is added in 4.3.2 ?

**Comment by lws-team** [comment]
> Does set_keylog_callback support is added in 4.3.2 ?

No.

**Comment by sush126** [comment]
so which version supports LWS_HAVE_SSL_CTX_set_keylog_callback ?

**Comment by lws-team** [comment]
It's only in main at the moment.

**Comment by sush126** [comment]
Thanks for quick response . Could you please let me know is there any plan to release this feature in next release ?

**Comment by lws-team** [comment]
Yes,  When is the next release?  Dunno.

**Comment by sush126** [comment]
Nope , but it will there in next release ?

**Comment by zzblydia** [comment]
> It's only in main at the moment.

same here. i am also working with SSLKEYLOGFILE to decrypt tls traffic.
Could you please let me know is there any plan to release this feature in some release in the future?

**Comment by lws-team** [comment]
New features can't go in existing release.  It's available in main - you're using it.  I have to work on things unrelated to lws atm... the result is no new release due to no reason to spend time on it.

You're free to pin a hash on main and target that.
