### ISSUE TITLE
Error response for certificate

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#2677]
I am getting an error while using websocket to make connection using. The error is coming when websocket calls LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER.

Error shown by websocket:
lws_client_ws_upgrade: got bad HTTP response '503'

While debugging, I found that lws_parse function of libwebsockets is showing following buffer:
HTTP/1.0 503 Service Unavailable
cache-control: no-cache
content-type: text/html

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

Any idea how to solve that?

**Comment by lws-team** [comment]
That's nothing to do with any certificate.

The server decides how or if to respond to whatever the client did.  "service unavailable" is usually some problem on the server side stops your request being passed on to it.
