### ISSUE TITLE
Disable LWS logs at program start?

### ISSUE THREAD

**Issue by simplyorganic** [warmcat/libwebsockets#2680]
Hi, on program start I get a couple of lines of logs from LWS, for example:
`[2022/06/29 09:29:37:5820] N: lws_create_context: LWS: 4.3.2-unknown, NET CLI SRV H1 H2 WS ConMon IPv6-absent
[2022/06/29 09:29:37:5825] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2022/06/29 09:29:37:5836] N: __lws_lc_tag:  ++ [vh|0|default||-1] (1)`

These are breaking some of my testing outputs that redirect std::out and parses results. How can I disable these?

**Comment by simplyorganic** [comment]
Can just set log level to warn/error and not notice.

**Comment by lws-team** [comment]
Hm... they go out on stderr by default, not stdout.

You can make an empty log emit function and set it before creating the context (logs work without needing an lws_context).  Or you can try setting the log mask to 0.

See https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-logs.h#n714-735
