### ISSUE TITLE
Error while compilation  with -DLWS_MAX_SMP=3 in windows for libwebsocket when i include pthreads

### ISSUE THREAD

**Issue by Paramveer24b** [warmcat/libwebsockets#2689]
Description:-
Hello team,

I am trying to build libwebsocket with  -DLWS_MAX_SMP=3 flag
Below is the full command:-
cmake -G "NMake Makefiles" -DLWS_MAX_SMP=3 -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\libwebsockets"  ..

After this command configuration and compilation gets successful, but after installation the macro in below file
C:\Program Files\libwebsockets\include\lws_config.h does not changed it remain **#define LWS_MAX_SMP 1** 

it suppose to change like **#define LWS_MAX_SMP 3**

Then I tried below command in which I have included pthread  lib and dir.

cmake -G "NMake Makefiles" -DLWS_MAX_SMP=3 -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DCMAKE_BUILD_TYPE=RELEASE -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\libwebsockets" -DLWS_EXT_PTHREAD_INCLUDE_DIR="C:\Program Files\pthreads\include" -DLWS_EXT_PTHREAD_LIBRARIES="C:\Program Files\pthreads\lib\x64\pthreadVC2.lib" ..

after this command configuration gets successful but while compilation below error occurs

\libwebsockets-4.3.2\lib\tls\openssl\openssl-tls.c(77): error C2440: 'type cast': cannot convert from 'pthread_t' to 'unsigned long'
\libwebsockets-4.3.2\lib\tls\openssl\openssl-tls.c(77): warning C4033: 'lws_openssl_thread_id' must return a value 

So can you help me to solve this issue ?

**Comment by lws-team** [comment]
I don't recommend forcing SMP on Windows, unless you want it so bad you're going to fix any problems.  It's only tested on Linux.

**Comment by Paramveer24b** [comment]
I am creating a server in windows and giving a finalize callback , it should be called when call lws_vhost_destroy() api
On linux its working fine but on windows callback does not get called by libwebsopcket.

There is a check in vhost.c file 
#if LWS_MAX_SMP > 1
	/* alert other pts they also need to do dieback flow for their wsi */
	lws_cancel_service(context);
#endif

In linux above check working because LWS_MAX_SMP = 3 ,
But in windows due to LWS_MAX_SMP = 1 there for lws_cancel_service() does not called due to this finalize callback does not gets called.

It there any other way to destroy vhost for server in windows or I am missing something?

**Comment by Paramveer24b** [comment]
sorry for late reply....

Thanks for the solution ... it's working now
