### ISSUE TITLE
Libwebsockets 4.2.3[Windows] no longer sends data on request

### ISSUE THREAD

**Issue by HalfenD** [warmcat/libwebsockets#2690]
On my project I upgraded libwbsockets from version 3 to 4 and afterwards messages were only send sporadically.
The project uses a websocket for a request/response scenario.

Old app version:
- libwebsockets v3.0.1
- compiled using default parameters for **Windows**
- OpenSSL Version 1.1

New app version:
- libwebsockets 4.2.3
- compiled using default parameters for **Windows**
- OpenSSL Version 3.0.2

In my new app version data is no longer sentd over the websocket when I request it with `lws_callback_on_writable`.
Most requests are initiated from my app.

A request now only seems to be sent after some data has been received over the socket or when `lws_context_creation_info.retry_and_idle_policy.secs_since_valid_ping` timer runs out.

For me it seems to relate to something around this line of code:
https://github.com/warmcat/libwebsockets/blob/b0a749c8e7a8294b68581ce4feac0e55045eb00b/lib/plat/windows/windows-service.c#L160

If I change the timeout value in `WSAPoll` to a fixed value for example 100ms, the program works again.

I would appreciate if someone could have a look at this and confirm my suspicion and make a suggestion on how the behaviour could be fixed.

BTW: tried the same program on Linux and everything worked great.

**Comment by lws-team** [comment]
Same situation in lws main?  Is there a minimal example that shows the problem if so?

**Comment by HalfenD** [comment]
On the main-branch it is still the same behaviour.  
Unfortunately I don't have a minimal example.  But I can try to create one an provide it later.

**Comment by lws-team** [comment]
Closing this until there's a reproducer to look at.

**Comment by lws-team** [comment]
You can't call lws apis from another thread, except lws_cancel_service().  See

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

and, eg,

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-server/minimal-ws-server-threads

**Comment by HalfenD** [comment]
Thanks for the advice. I thought that it was safe to call `lws_callback_on_writable` from only one other thread. As it was written here:
https://github.com/warmcat/libwebsockets/blob/v4.2-stable/READMEs/README.coding.md

> If you are using the default poll() event loop, one "foreign thread" at a time may call lws_callback_on_writable() directly for a wsi. You need to use your own locking around that to serialize multiple thread access to it.

But this seems now outdated. 

To fix my problem I tried to replace `lws_callback_on_writable` with `lws_cancel_service` and call `lws_callback_on_writable` directly inside the callback `LWS_CALLBACK_EVENT_WAIT_CANCELLED`. But this somehow leads to a crash.

**Comment by lws-team** [comment]
Cancel service is not associated with any wsi.  It happens to the whole event loop.

The wsi passed into the callback for that is not a real wsi.  It just has, eg, context, vhost and protocol pointers set.

In the CANCELLED callback you must instead lock and look at a fifo or other structure set from the other threads that describes what needs doing on the lws thread.

**Comment by HalfenD** [comment]
Thank you for the clarification. I think this solves the problem.
