### ISSUE TITLE
Unreal Engine has slow response on iOS device with network disconnect

### ISSUE THREAD

**Issue by jo-codegirl** [warmcat/libwebsockets#2691]
I am using libwesockets in Unreal Engine which currently provides v3.0.0. I establish a session with a server. When network is interrupted (eg. wifi goes off) the client receives a response LWS_CALLBACK_CLIENT_CLOSED. On Android, this is received instantly. On iOS it consistently takes about 1 minute to receive the callback. I can resolve this by using ping-pong with server, however the behaviour on iOS and Android will still be different for users.

Has anyone else encountered this problem and how have they resolved it?

I think that the latest version (4+) of libwesockets will provide a way to resolve this - is this in fact true? Do you have any information about building libwebsockets for UE4.27?

Similar issue with response I found:
https://github.com/warmcat/libwebsockets/issues/1877

The libwebsockets versions currently provided by Unreal:
https://github.com/EpicGames/ThirdParty

**Comment by lws-team** [comment]
Recent lws on Linux monitors netlink to understand when connection are invalidated by losing their route or source address, and react quickly.

Otherwise it depends on to OS to take action on interface loss, we don't do anything special for android or ios.  So I guess android does something ios doesn't do.

**Comment by jo-codegirl** [comment]
Recent meaning v4?

**Comment by jo-codegirl** [comment]
I appreciate that lws comes with UE. I take it they are solely responsible for maintaining their package of it (linked above)? Curious that even UE5 doesn't come with a more recent version than 3.0.0.

**Comment by lws-team** [comment]
There's no point not using last stable release if you want stable, it's the only version supported with updates (v4.3-stable currently).

Yes same as all lws users, they just consume it at their own pace, it's up to them what they do.
