### ISSUE TITLE
Unable to bind when give adaptor name when do lws_create_vhost

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2693]
I am on Windows x64 platform, i want to bind server with specific nic , i am addind nic name to lws_context_creation_info *pcreatInfo;
**pcreatInfo->iface="{1FD76C52-E6E0-45E5-BCF3-122B9E884350}"**

but it is unable to bind with Transport name :

**getmac /v output :**

Connection Name Network Adapter Physical Address    Transport Name
=============== =============== =================== ==========================================================
Wi-Fi           Intel(R) Wi-Fi  5C-80-B6-FF-EB-AF   \Device\Tcpip_{E552AC7C-1002-4ED0-83A0-DD02A02518DE}
Ethernet 2      Zscaler Network 00-FF-85-1D-12-53   Media disconnected
VMware Network  VMware Virtual  00-50-56-C0-00-08   \Device\Tcpip_{1FD76C52-E6E0-45E5-BCF3-122B9E884350}
Ethernet        Intel(R) Ethern 38-22-E2-48-E3-C4   Media disconnected
Bluetooth Netwo Bluetooth Devic 5C-80-B6-FF-EB-B3   Media disconnected
vEthernet (nat) Hyper-V Virtual Disabled            Disconnected

**Comment by lws-team** [comment]
You can debug server socket preparation from `_lws_vhost_init_server_af()` in `lib/core-net/roles/http/server/server.c`
