### ISSUE TITLE
A Question about LEJP

### ISSUE THREAD

**Issue by NikolaosGian** [warmcat/libwebsockets#2694]
Hello everyone!,
I want to use json parser but i cant find an example using lejp and make it difficult.
I need it to read the data receiving from finnhub.io and to do some work about the trades with different symbols.
Any help about this?

**Comment by lws-team** [comment]
Build lws (with -DLWS_WITH_MINIMAL_EXAMPLES=1 if not main branch) and make install it.

Paste some representative JSON into a file and pass it to libwebsockets-test-lejp like

```
$ cat /tmp/myjson | libwebsockets-test-lejp
```

Basically it will parse it and break down each step from the parser.

Once you see what that's doing, you can generally follow the very simple sources of the test-lejp app in your code to get started

https://libwebsockets.org/git/libwebsockets/tree/test-apps/test-lejp.c

There's additional info in the headers for it and

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.json-lejp.md
