### ISSUE TITLE
lws_callback_all_protocol doesn't work after upgrade from v2.0.2 to v4.3.2

### ISSUE THREAD

**Issue by neilkaus** [warmcat/libwebsockets#2697]
Hi! 

I recently upgraded from version v2.0.2 to v4.3.2 and my protocol callbacks no longer receive callbacks from lws_callback_all_protocol. I've narrowed down the issue to the fact that in the new version the lws_create_context (and subsequently lws_create_vhost) copy the protocol from the lws_context_creation_info to the vhost rather than simply taking the pointer from the info struct like in old versions. I found that this was changed without explanation in commit [8d473ad78c4d816d3e872f6d2d67e59a0e92b84f](https://github.com/warmcat/libwebsockets/commit/8d473ad78c4d816d3e872f6d2d67e59a0e92b84f) - smtp: make abstract (lib/core-net/vhost.c lines 598 to 608 and 625-626) where even if you weren't using plugins or explicit vhost initialization it would make a copy of the protocols rather than just set the vhost->protocols pointer to the one given by info->protocols.

My question was what is the correct way to use lws_callback_all_protocol in newer versions or is there a different approach that should be taken entirely and an example that could be referenced for that? For reference I am using lws_callback_all_protocol to inform the protocol in question that there has been physical input on the device (using the LWS_CALLBACK_USER reason) that is relevant to the protocol. Then in the protocol callback I call lws_callback_on_writable to queue a data send on the websocket. I searched the examples and all I found was test-apps/test-client.c was using lws_callback_on_writable_all_protocol but was doing the same thing as me where it passed the pointer to the statically assigned protocol struct it declared for context creation which wouldn't work as they are now stored in a copy and not the same location.

Thanks for any information you can provide on this issue.

**Comment by lws-team** [comment]
The main reason for those changes is that protocols may be instantiated with different configurations on different vhosts, not instantiated on some vhosts etc.  Although they're using the same callback, practically they are different protocols then.

The protocols can be scalably configured for each vhost by passing in 'pvo' trees, "per-vhost objects".

For each vhost-protocol combination PROTOCOL_INIT / PROTOCOL_DESTROY gets called and many examples use that to allocate a user 'vhd' object to hold stuff for that vhost-protocol combination.

You can still do what you were doing.  But you must get the right protocol instantiation for the vhost to pass to `lws_callback_on_writable_all_protocol()`

```
const struct lws_protocols *
lws_vhost_name_to_protocol(struct lws_vhost *vh, const char *name)
```

**Comment by neilkaus** [comment]
Thanks for the information I really appreciate the quick response!
