### ISSUE TITLE
lws_ssl_client_connect2 failed, reason =1

### ISSUE THREAD

**Issue by liuxiaofeng8888** [warmcat/libwebsockets#2698]
hi，in the demo minimal-ws-client,i changed the server address with my company ip address.it run well,web socket connection established.but when i copy it to docker env ,used alios xmake build it out.it cannot work.the error is : error = lws_ssl_client_connect2 failed.  connect invalid: LWS_CALLBACK_CLOSED_CLIENT_HTTP. any advice?

**Comment by lws-team** [comment]
> any advice?

Look at the detailed lws logs to see what it feels is happening to it.

**Comment by liuxiaofeng8888** [comment]
> > any advice?
> 
> Look at the detailed lws logs to see what it feels is happening to it.

 this is my log:
`07-15 17:00:44.090  9378  9651 I NUI.myCompany/myCompany: myCompany ClientConversationBase = 0xeda42440
07-15 17:00:44.104  9378  8826 I NUI.myCompany/myCompany: run from start
07-15 17:00:44.142  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info begin, 267
07-15 17:00:44.245  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info end, 269
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1, error = lws_ssl_client_connect2 failed
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: connect invalid: LWS_CALLBACK_CLOSED_CLIENT_HTTP
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :33
07-15 17:00:44.308  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :30
07-15 17:00:44.426  9378  9706 I tts/myCompany: myCompany NlsClient = 0xa2486390
07-15 17:00:44.431  9378  8830 I tts/myCompany: ZYX run from start
07-15 17:00:44.439  9378  8830 I tts/myCompany: ZYX from_url get instance, ws=0xa24868d0, from [wss://speech-vgw-qa.ebanma.com:8443]
07-15 17:00:44.440  9378  8830 I tts/myCompany: run begin to communicate, ws status =2
07-15 17:00:44.613  9378  8830 I tts/myCompany: handWsStatusCallback status = 3
07-15 17:00:44.614  9378  9706 I tts/myCompany: sendData begin
07-15 17:00:44.616  9378  9706 I tts/myCompany: sendData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.768  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end`

**Comment by liuxiaofeng8888** [comment]
format my code
`07-15 17:00:44.090  9378  9651 I NUI.myCompany/myCompany: myCompany ClientConversationBase = 0xeda42440
07-15 17:00:44.104  9378  8826 I NUI.myCompany/myCompany: run from start
07-15 17:00:44.142  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info begin, 267
07-15 17:00:44.245  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info end, 269
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1, error = lws_ssl_client_connect2 failed
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: connect invalid: LWS_CALLBACK_CLOSED_CLIENT_HTTP
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :33
07-15 17:00:44.308  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :30
07-15 17:00:44.426  9378  9706 I tts/myCompany: myCompany NlsClient = 0xa2486390
07-15 17:00:44.431  9378  8830 I tts/myCompany: ZYX run from start
07-15 17:00:44.439  9378  8830 I tts/myCompany: ZYX from_url get instance, ws=0xa24868d0, from [wss://speech-vgw-qa.ebanma.com:8443]
07-15 17:00:44.440  9378  8830 I tts/myCompany: run begin to communicate, ws status =2
07-15 17:00:44.613  9378  8830 I tts/myCompany: handWsStatusCallback status = 3
07-15 17:00:44.614  9378  9706 I tts/myCompany: sendData begin
07-15 17:00:44.616  9378  9706 I tts/myCompany: sendData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.768  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end`

**Comment by liuxiaofeng8888** [comment]
07-15 17:00:44.090  9378  9651 I NUI.myCompany/myCompany: myCompany ClientConversationBase = 0xeda42440
07-15 17:00:44.104  9378  8826 I NUI.myCompany/myCompany: run from start
07-15 17:00:44.142  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info begin, 267
07-15 17:00:44.245  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info end, 269
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1, error = lws_ssl_client_connect2 failed
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: connect invalid: LWS_CALLBACK_CLOSED_CLIENT_HTTP
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :33
07-15 17:00:44.308  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :30
07-15 17:00:44.426  9378  9706 I tts/myCompany: myCompany NlsClient = 0xa2486390
07-15 17:00:44.431  9378  8830 I tts/myCompany: ZYX run from start
07-15 17:00:44.439  9378  8830 I tts/myCompany: ZYX from_url get instance, ws=0xa24868d0, from [wss://speech-vgw-qa.ebanma.com:8443]
07-15 17:00:44.440  9378  8830 I tts/myCompany: run begin to communicate, ws status =2
07-15 17:00:44.613  9378  8830 I tts/myCompany: handWsStatusCallback status = 3
07-15 17:00:44.614  9378  9706 I tts/myCompany: sendData begin
07-15 17:00:44.616  9378  9706 I tts/myCompany: sendData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.768  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end

**Comment by liuxiaofeng8888** [comment]
> > any advice?
> 
> Look at the detailed lws logs to see what it feels is happening to it.

this is my log:
07-15 17:00:44.090  9378  9651 I NUI.myCompany/myCompany: myCompany ClientConversationBase = 0xeda42440
07-15 17:00:44.104  9378  8826 I NUI.myCompany/myCompany: run from start
07-15 17:00:44.142  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info begin, 267
07-15 17:00:44.245  9378  8826 I NUI.myCompany/myCompany: run lws_client_connect_via_info end, 269
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1, error = lws_ssl_client_connect2 failed
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: client connection error, reason = 1
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: connect invalid: LWS_CALLBACK_CLOSED_CLIENT_HTTP
07-15 17:00:44.307  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :33
07-15 17:00:44.308  9378  8826 I NUI.myCompany/myCompany: close or destroy error, reason :30
07-15 17:00:44.426  9378  9706 I tts/myCompany: myCompany NlsClient = 0xa2486390
07-15 17:00:44.431  9378  8830 I tts/myCompany: ZYX run from start
07-15 17:00:44.439  9378  8830 I tts/myCompany: ZYX from_url get instance, ws=0xa24868d0, from [wss://speech-vgw-qa.ebanma.com:8443]
07-15 17:00:44.440  9378  8830 I tts/myCompany: run begin to communicate, ws status =2
07-15 17:00:44.613  9378  8830 I tts/myCompany: handWsStatusCallback status = 3
07-15 17:00:44.614  9378  9706 I tts/myCompany: sendData begin
07-15 17:00:44.616  9378  9706 I tts/myCompany: sendData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.648  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.768  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback type = 2
07-15 17:00:44.771  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerAudioData  end
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback  type = 1
07-15 17:00:44.811  9378  8830 I tts/myCompany: handleWsMessageCallback, onServerData end

**Comment by lws-team** [comment]
Enable the detailed lws logs, not whatever that is.  Eg, -d1151 on the examples, build with -DCMAKE_BUILD_TYPE=DEBUG

**Comment by liuxiaofeng8888** [comment]
> Enable the detailed lws logs, not whatever that is. Eg, -d1151 on the examples, build with -DCMAKE_BUILD_TYPE=DEBUG

i have another question:The libwebsockets.so is 64 bits which i build out. how to build a 32 bits library?

**Comment by lws-team** [comment]
That's a cmake thing, not an lws thing

`-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32` on cmake might help.
