### ISSUE TITLE
when compile libwebsockets to WASM, fatal error: 'asm/types.h' file not found

### ISSUE THREAD

**Issue by geonoon** [warmcat/libwebsockets#2699]
when I try to build libwebsocket using emscripten
The error below pop up:
/home/smith/Dev_projects/libwebsockets-main/lib/roles/netlink/ops-netlink.c:34:10: fatal error: 'asm/types.h' file not found.

My steps (in Ubuntu):
1.git clone https://github.com/warmcat/libwebsockets.git
2.cd libwebsockets/
3.mkdir build
4.cd build
5.emmake cmake .. -DLWS_WITHOUT_EXTENSIONS=1 \
-DLWS_WITH_SSL=0 \
-DLWS_WITH_ZLIB=0 \
-DLWS_WITH_ZIP_FOPS=0 \
-DLWS_WITH_SHARED=0 \
-DLWS_WITHOUT_TESTAPPS=1 \
-DLWS_WITHOUT_TEST_SERVER=1 \
-DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1 \
-DLWS_WITHOUT_TEST_PING=1 \
-DLWS_WITHOUT_TEST_CLIENT=1
6.emmake make
Just in the process of the step 6, the error occurred as below:
----------------------------------------------------------------------------------
/home/smith/Dev_projects/libwebsockets-main/lib/roles/netlink/ops-netlink.c:34:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
emcc: error: '/home/henry/Dev_tools/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=15 -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home/henry/Dev_tools/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DLWS_BUILDING_STATIC -I/home/henry/Dev_projects/libwebsockets-main_a/include -I/home/henry/Dev_projects/libwebsockets-main_a/build -I/home/henry/Dev_projects/libwebsockets-main_a/lib -I/home/henry/Dev_projects/libwebsockets-main_a/lib/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/secure-streams -I/home/henry/Dev_projects/libwebsockets-main_a/lib/plat/unix/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/core/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/misc/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/misc/misc/jrpc -I/home/henry/Dev_projects/libwebsockets-main_a/lib/system/./async-dns -I/home/henry/Dev_projects/libwebsockets-main_a/lib/system/smd/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/system/metrics/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/core-net/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/http/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/http/./compression -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/h1/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/h2/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/ws/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/raw-skt/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/raw-file/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/roles/listen/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/event-libs/. -I/home/henry/Dev_projects/libwebsockets-main_a/lib/event-libs/poll/../poll -I/home/henry/Dev_projects/libwebsockets-main_a/lib/secure-streams/. -Wno-deprecated-declarations -Wno-deprecated -Wall -Wextra -Wno-unused-parameter -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef -Wuninitialized -Wtype-limits -Wignored-qualifiers -Werror -Wno-deprecated-declarations -pthread -MD -MT lib/CMakeFiles/websockets.dir/roles/netlink/ops-netlink.c.o -MF CMakeFiles/websockets.dir/roles/netlink/ops-netlink.c.o.d -c -matomics -mbulk-memory /home/henry/Dev_projects/libwebsockets-main_a/lib/roles/netlink/ops-netlink.c -o CMakeFiles/websockets.dir/roles/netlink/ops-netlink.c.o' failed (returned 1)
make[2]: *** [lib/CMakeFiles/websockets.dir/build.make:1238: lib/CMakeFiles/websockets.dir/roles/netlink/ops-netlink.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3873: lib/CMakeFiles/websockets.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
emmake: error: 'make' failed (returned 2)
--------------------------------------------------------------------------

How to fixe this issue? I will appreciate an early help.

**Comment by lws-team** [comment]
Hm... netlink can only work on Linux platform.  You'll be better off disabling it in lws I think with cmake -DLWS_WITH_NETLINK=0

**Comment by geonoon** [comment]
Thanks l lot for your quick reply.
However, my dev environment is just in Linux(Ubuntu), and I compile libwebsockets into WASM to be used in Android and iOS platform.
Do I have to disable netlink ? If I do so, any downsides for use in Android or IOS?

**Comment by lws-team** [comment]
I don't think wasm on eg, ios will magic up netlink messages.  At any rate you can't build it so if you want to try it, that's the way.
