### ISSUE TITLE
how to implement a program as client ,also as server with libwebsockets?

### ISSUE THREAD

**Issue by zelda112** [warmcat/libwebsockets#2701]
Sorry to commit a issue, because I don't know how can I commit a quesion on this board.

My question is that I want to implement a program that receive data of serval clients as server side, and then send the result 
from processing these data to another server as client side. How to implement it? Can I use two thread , and run the loop 
of lws_service in per-thread? Can the lws_service in a thread call its-own callback function and work well?

**Comment by zelda112** [comment]
Is these any simple example? Thanks.

**Comment by lws-team** [comment]
For lws, it wants you to do everything related to it in one lws_context, one thread, one event loop.  On that, you can have as many client and server connections ongoing asynchronously as you like.  Incoming connections to the server will have wsi created on the loop automatically and if you make outgoing client connections, you can also have as many of those as you like created by your code.

There are three main things to take care of... 1) blocking the event loop

In the simple case, you block the event loop while you "process" data... you might want to just do it like that to get started and prove the flow.

In a situation where the "processing" blocking the event loop is unreasonable, you have to pass the work to another thread

2) thread safety

You can only use lws_cancel_service() from another thread.  Have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

3) independent lifetime management of bound connections

If you have a pattern where you will bind two or more connections, you can't avoid the reality that any of the bound connections may terminate at any time at the network layer.  When that happens, lws will also destroy his wsi for the connection as soon as possible, possibly the next time around the event loop, in other words when you return from whatever callback you are handling.  It means that you must monitor CLOSE callbacks for any connections that will be bound and clean out any references you may be holding to its wsi in your own lists.

You might start here (but nothing about this is limited to raw protocol)

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-server/minimal-ws-raw-proxy/minimal-ws-raw-proxy.c

**Comment by zelda112** [comment]
Thanks very much.
