### ISSUE TITLE
error: undefined symbol: initgroups, when compile libwebsockets examples to Webassembly 

### ISSUE THREAD

**Issue by geonoon** [warmcat/libwebsockets#2703]
Dear Andy,

I ask for your kind help for the problem described below.

The steps:
1. git clone https://github.com/warmcat/libwebsockets.git

2. cd libwebsockets
   (e.g. Now in the directory: /home/aaa/Dev_projects/wasm_libwebsockets/libwebsockets)
   
3. mkdir build_wasm

4. cd build_wasm

5. source (/path-to-emsdk)/emsdk/emsdk_env.sh
e.g. use the command:
   source /home/aaa/Dev_tools/emsdk/emsdk_env.sh

6. emcmake cmake .. -DLWS_WITHOUT_EXTENSIONS=1 \
   -DLWS_WITH_SSL=0 \ 
   -DLWS_WITH_ZLIB=0 \
   -DLWS_WITH_ZIP_FOPS=0 \
   -DLWS_WITH_SHARED=0 \
   -DLWS_WITHOUT_TESTAPPS=1 \
   -DLWS_WITHOUT_TEST_SERVER=1 \
   -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1 \
   -DLWS_WITHOUT_TEST_PING=1 \
   -DLWS_WITHOUT_TEST_CLIENT=1 \
   -DLWS_WITH_NETLINK=0

7. emmake make
  Now we have got a compiled wasm library file libwebsockets.a (in the directory: /home/aaa/Dev_projects/wasm_libwebsockets/libwebsockets//build_wasm/lib)

8. make install

   Then to choose a libwebsockets example to compile to WASM (i.e. Webasembly).
   For example, the minimal-ws-server as below:  
10.  cd /home/aaa/Dev_projects/wasm_libwebsockets/libwebsockets/minimal-examples-lowlevel/ws-server/minimal-ws-server
     mkdir build
     cd build

11. source (/path-to-emsdk)/emsdk/emsdk_env.sh
  e.g. use the command:
   source /home/aaa/Dev_tools/emsdk/emsdk_env.sh

12. emcmake cmake ..
13. emmake make
      (here comes the error displayed as below:)
  make: make
[ 50%] Building C object CMakeFiles/lws-minimal-ws-server.dir/minimal-ws-server.c.o
[100%] Linking C executable lws-minimal-ws-server.js
error: undefined symbol: initgroups (referenced by top-level compiled C/C++ code)
warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _initgroups may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/home/aaa/Dev_tools/emsdk/node/14.18.2_64bit/bin/node /home/aaa/Dev_tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpey0ypnai.json' failed (returned 1)
......

When I search "initgroups" (in the libwebsockets repo source code), it exists in the file  /home/aaa/Dev_projects/wasm_libwebsockets/libwebsockets/lib/plat/unix/unix-caps.c

How can I solve this problem?

I will appreciate your early reply and kind help.

**Comment by lws-team** [comment]
This is a bit late, but you can probably override `-DLWS_HAVE_LIBCAP=0` at cmake to turn of libcap support

**Comment by geonoon** [comment]
I stiil got the same error "undefined symbol: initgroups (referenced by top-level compiled C/C++ code)", even if I overrided -DLWS_HAVE_LIBCAP=0 at cmake to turn of libcap support.

Can you further help?

Thanks in advance

**Comment by lws-team** [comment]
You may need to delete your CMakeCache.txt first if you want to override discovered build state.

**Comment by geonoon** [comment]
Yes, I had deleted all files (including CMakeCache.txt) before re-doing the compiling process. But the same error still occured.

**Comment by loryruta** [comment]
Same issue here.

As far as my understanding, `initgroups` can't be avoided with any definition (outside every `#ifdef` block):

https://github.com/warmcat/libwebsockets/blob/v4.3-stable/lib/plat/unix/unix-caps.c#L218

Is libwebsockets supposed to support WebAssembly?

**Comment by loryruta** [comment]
> Does it say anywhere it works with it? No.

That's why I was asking 😃 

initgroup is a function which is not supported by emscripten and thus the compilation with it fails. That's why I was looking for a definition to skip it 😆
