### ISSUE TITLE
The client get error "websocket: close 1006 (abnormal closure): unexpected EOF"

### ISSUE THREAD

**Issue by 2007lf** [warmcat/libwebsockets#2704]
Hi, thank you for open source this project, I get a problem, I use libwebsockets to create a websocket server, and then use the client written in Go to connect to use it, when I send messages very quickly, it can be understood as sending messages concurrently, my Go code got an error of "websocket: close 1006 (abnormal closure): unexpected EOF" when reading the message, I don't know what is the reason, is there any configuration, or is it a problem with use? I hope to get your help, thank you.

**Comment by lws-team** [comment]
What does it mean 'send messages concurrently'?  You cannot send on one socket multiple ws messages concurrently.  If they are in multiple fragments, they will interrupt each other partway through and turn the stream to gibberish.

You can have n sockets each with its own isolated ws message stream running concurrently.
