### ISSUE TITLE
Trying to 'attach' dynamically created client with alternate protocol handler.

### ISSUE THREAD

**Issue by mfallavol** [warmcat/libwebsockets#2706]
I have the need for my websocket server to create a client connection to to perform an exchange over TCP (using raw socket) before responding to the original client.  I seem to be able to create the client connection okay (testing with localhost for now) but all of the events are going to the protocol handler of the websocket server vhost instead of to the "other" protocol handler. 

'''
// Global protcol definition
struct lws_protocols other_prot =
	{ "other",		callback_other, sizeof(struct other_t),	0, 0, NULL, 0 };

		// This code is in my server handler and creates the RAW connection.
		struct lws *new_wsi;
		struct lws_client_connect_info	cci;
		extern struct lws_context	*Context;		// Global context
		extern struct lws_protocols other_prot;

		cci.context	= Context;
		cci.method	= "RAW";
		cci.address	= "localhost";
		cci.host	= "localhost";
		cci.port	= 15355;
//		cci.local_protocol_name = "other";
		cci.protocol = vpXML_prot.name;
		
		if ((new_wsi = lws_client_connect_via_info(&cci)) == NULL)
		{
			lwsl_err("Client creation failed.\n");
		}
'''		
I can see the LWS_CALLBACK_RAW_CONNECTED, and LWS_CALLBACK_RAW_WRITEABLE events coming into my server's protocol handler.  Can anyone tell me the right way to associate this client with the correct protocol?

**Comment by lws-team** [comment]
You can use `.local_protocol_name` to bind the client to another lws_protocols.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n171-177

**Comment by mfallavol** [comment]
I've tried that as well with the lines below, separately of course.  (You can see one of the attempts commented out in the original post but the comment seems to have pulled it out of the code block.)
'''
cci.local_protocol_name = "other";
cci.local_protocol_name = other_prot.name;
'''
 Neither made any difference.  The events still went to the wrong protocol.

**Comment by lws-team** [comment]
You have to use three backticks with github markdown, apostrophes don't seem to work the same (and hid your code in this case).

IIRC you have to leave .protocol NULL in that case, else it takes precedence.

**Comment by lws-team** [comment]
... oh it's the other way around, local takes precedence and protocol is used for the ws negotiation.

Still the same problem on main branch?  I'm afraid you'll have to trace the code to see what is happening.

**Comment by mfallavol** [comment]
I tried explicitly setting .protocol to NULL but it made no difference.  Does the problem have anything to do with trying to use RAW mode on the socket?

**Comment by mfallavol** [comment]
I was able to solve this by setting .vhost to a vhost I created that uses the same protocol.
