### ISSUE TITLE
How to make use of the X-Forwarded-For header

### ISSUE THREAD

**Issue by hardillb** [warmcat/libwebsockets#2708]
I'm trying to work out how to patch mosquitto to use the value of X-Forwarded-For header when clients connect over websockets behind a reverse proxy.

I can see from the history that libwebsockets supports this, but I don't appear to be able to find an example or where in the docs to look.

My best guess is that I need to add something to the `lws_context_creation_info` stuct, but that's about as far as I've managed to get.

https://github.com/eclipse/mosquitto/blob/master/src/websockets.c#L664

Don't suppose you can give me a pointer.

Thanks.

**Comment by lws-team** [comment]
At LWS_CALLBACK_ESTABLISHED you should be able to query for headers.  Eg

```
if (lws_hdr_copy(wsi, buf, sizeof(buf), WSI_TOKEN_X_FORWARDED_FOR) > 0) {
    /* buf contains the x-forwarded-for string */
}
```

**Comment by hardillb** [comment]
Thanks, for that working
