### ISSUE TITLE
ssl_pm_new: mbedtls_ssl_setup() return -0x5e80

### ISSUE THREAD

**Issue by tsl0922** [warmcat/libwebsockets#2710]
origin issue and logs: https://github.com/tsl0922/ttyd/issues/964

from: https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/ssl.h
```
/** Invalid value in SSL config */
#define MBEDTLS_ERR_SSL_BAD_CONFIG                        -0x5E80
```

libwebsockets: 4.3.2
mbedtls: 3.1.0

It works on openssl backend with the same code.

**Comment by lws-team** [comment]
Since you can see the error, what I would do is instrument the failing mbedtls api with logs and find out why it returns that.

**Comment by tsl0922** [comment]
I've tested the following:

- lws 4.3.2 + mbedtls 3.1.0: not work
- lws 4.2.1 + mbedtls 2.16.8: work
- lws 4.3.2 + mbedtls 2.16.8 work

so there maybe compatibility issue with lws 4.3.2 and mbedtls 3.1.0, I'm going to revert to mbedtls 2.x version.

**Comment by lws-team** [comment]
...maybe it's nothing to do with lws and just mbedtls change... you can't debug this without finding out why mbedtls feels it wants to return the error.

If reverting is enough for you then okay...

**Comment by tsl0922** [comment]
Thanks, I'm ok with reverting mbedtls.

(I was building ttyd in a cross compiling environment, it's may take long time to setup the debug environment, so reverting is prefererd for now)

**Comment by leoadonia** [comment]
mbedtls adds [ssl_conf_version_check](https://github.com/Mbed-TLS/mbedtls/blob/v3.1.0/library/ssl_tls.c#L3193) since v3.1.0:

```c
#if defined(MBEDTLS_SSL_PROTO_TLS1_2)
    if( mbedtls_ssl_conf_is_tls12_only( ssl->conf ) )
    {
        MBEDTLS_SSL_DEBUG_MSG( 4, ( "The SSL configuration is tls12 only." ) );
        return( 0 );
    }
#endif
```

mbedtls only support TLS 1.2 by default, the `mbedtls_ssl_config::min_tls_version` and `mbedtls_ssl_config::max_tls_version`  must be `0x303`. And the `min_tls_version` in libwebsockets is `0x301` now.

Change `min_tls_version` to `0x303` will be fine.

```c
--- a/third_party/libwebsockets/lib/tls/mbedtls/wrapper/platform/ssl_pm.c
+++ b/third_party/libwebsockets/lib/tls/mbedtls/wrapper/platform/ssl_pm.c
@@ -183,7 +183,7 @@ int ssl_pm_new(SSL *ssl)
         mbedtls_ssl_conf_min_version(&ssl_pm->conf, MBEDTLS_SSL_MAJOR_VERSION_3, version);
     } else {
         mbedtls_ssl_conf_max_version(&ssl_pm->conf, MBEDTLS_SSL_MAJOR_VERSION_3, MBEDTLS_SSL_MINOR_VERSION_3);
-        mbedtls_ssl_conf_min_version(&ssl_pm->conf, MBEDTLS_SSL_MAJOR_VERSION_3, 1);
+        mbedtls_ssl_conf_min_version(&ssl_pm->conf, MBEDTLS_SSL_MAJOR_VERSION_3, MBEDTLS_SSL_MINOR_VERSION_3);
     }
```
