### ISSUE TITLE
Schedule different callbacks in different time

### ISSUE THREAD

**Issue by mattermat** [warmcat/libwebsockets#2716]
Is there a way to use `lws_sul_schedule` multiple times?

I'm trying to schedule different callback functions, but if I use consecutively the `lws_sul_schedule` func, only the last one callback is effectively scheduled.

**Comment by lws-team** [comment]
It sounds like you are using the same sul over and over, which is to say rescheduling the one sul.

If you have n scheduled events, you should use n sul objects, they can use the same callback if you know from other state indications why you got the callback, or individual callbacks or some mixture of the two.  But every event must be tracked by its own sul object.

**Comment by mattermat** [comment]
Thanks a lot! You described perfectly the problem.
Every event needs its own sul object. Now it is working properly.

Thanks again!
