### ISSUE TITLE
couldn't connect wss - callback LWS_CALLBACK_WS_PEER_INITIATED_CLOSE

### ISSUE THREAD

**Issue by coenky** [warmcat/libwebsockets#2720]
ws client connect wss server and send a msg to server, 
then recieve LWS_CALLBACK_WS_PEER_INITIATED_CLOSE.

source like this
        case LWS_CALLBACK_WS_PEER_INITIATED_CLOSE:
            printf("reason = %d, len = %d\n", reason, len);
            if (len>2) {
                printf("0x%02X 0x%02X\n", ((unsigned char *)in)[0], ((unsigned char *)in)[1]);
                printf("%s\n", ((char *)in)+2);
            }
            break;

and it print:
reason = 38, len = 116
0x03 0xEF
A WebSocket text frame was received that could not be decoded to UTF-8 because it contained invalid byte sequences

and then close the connect

**Comment by lws-team** [comment]
So... it could connect just fine.

But it feels you sent it junk once you were conndcted.... usuall sending BINARY on a TEXT ws link.

So it hung up on you and told you why.
