### ISSUE TITLE
lws_buflist_append_segment: buflist reached sanity limit

### ISSUE THREAD

**Issue by catseeker** [warmcat/libwebsockets#2723]
Hi,

I wrote a lws server to transmit video(1080*1920 24f/s)， using lws_wirte() to send 1460 bytes of data at a time, and lws will report such an error："lws_buflist_append_segment: buflist reached sanity limit"。

**Comment by lws-team** [comment]
You're writing packets faster than your network stack can send it.  So it's piling up in a buflist.  If there wasn't a (huge) sanity check for buflist member count, you'd be telling me that you OOM'd instead.

You're asking for WRITEABLE when you can send more as you must, right?  So your production of data is regulated by the ability of the network to absorb it?
