### ISSUE TITLE
Assert hit using secure streams on LWSSSCS_SERVER_UPGRADE

### ISSUE THREAD

**Issue by metacean** [warmcat/libwebsockets#2725]
I am attempting to bring up a simple websockets server, and have been using libwebsockets to implement it - on the main branch, it seems that there is a potentially redundant call to lws_ss_check_next_state_ss, which results in the 'SERVER_UPGRADE -> SERVER_UPGRADE' case falling through and asserting.

it seems that, upon connecting, disconnecting and reconnecting to a secure streams server, the servers previous state remains as SERVER_UPGRADE.

in the code here:

https://github.com/warmcat/libwebsockets/blob/5b224c913f84767c7ef945bcb3ee28d8b7a5e0db/lib/roles/ws/server-ws.c#L325

there is no check to see if the connection state is already SERVER_UPGRADE. i replaced it with:

```
if (wsi->a.vhost->ss_handle->prev_ss_state != LWSSSCS_SERVER_UPGRADE){
                (void)lws_ss_event_helper(wsi->a.vhost->ss_handle,
                        LWSSSCS_SERVER_UPGRADE);
            }
```

and this avoids the issue for me, but I am unsure if this is a problem with my configuration, incomplete resetting of connection state, a lack of acceptance of 'same->same' state transitions as valid, a bug in just this particular codepath, or reflective of an issue further up the chain of processing.. I have no prior experience with libwebsockets and is is a complex codebase to grok, however my fix is presented here in the hope that is useful.

**Comment by pragmaxwell** [comment]
I ran into this today as well. This happens to me when multiple clients connect in short succession. It seems like the server's base stream never changes state away from `LWSSSCS_SERVER_UPGRADE`.

In fact, looking at `lib/secure-streams/secure-streams.c` it seems the only valid states are:
```
(1 << LWSSSCS_SERVER_TXN) |
(1 << LWSSSCS_TIMEOUT) |
(1 << LWSSSCS_DISCONNECTED) |
(1 << LWSSSCS_DESTROYING),
```

This is a fairly limited set of states, and in the case of a ws protocol server, I only receive upgrades, no http tx so we never go to LWSSSCS_SERVER_TXN.

It seems to me like the correct fix would be to allow LWSSSCS_SERVER_UPGRADE to transition to LWSSSCS_SERVER_UPGRADE, which the below diff accomplishes in the correct way.

```
diff --git a/lib/secure-streams/secure-streams.c b/lib/secure-streams/secure-streams.c
--- a/lib/secure-streams/secure-streams.c
+++ b/lib/secure-streams/secure-streams.c
@@ -175,7 +175,8 @@ const uint32_t ss_state_txn_validity[] = {
 					  (1 << LWSSSCS_TIMEOUT) |
 					  (1 << LWSSSCS_DESTROYING),
 
-	[LWSSSCS_SERVER_UPGRADE]	= (1 << LWSSSCS_SERVER_TXN) |
+	[LWSSSCS_SERVER_UPGRADE]	= (1 << LWSSSCS_SERVER_UPGRADE) |
+                      (1 << LWSSSCS_SERVER_TXN) |
 					  (1 << LWSSSCS_TIMEOUT) |
 					  (1 << LWSSSCS_DISCONNECTED) |
 					  (1 << LWSSSCS_DESTROYING),

```

I'm using this as I continue setting up my application and will reply again if I find something that invalidates this.

**Comment by lws-team** [comment]
Thanks for the patches... I pushed pragmaxwell's patch on main.  I am not sure why it sees that state twice, the real fix is probably somewhere else and so either patch would work around it OK.
