### ISSUE TITLE
There is no  lws_ client_ Connect  in the <build> directory  after  successfully compiled

### ISSUE THREAD

**Issue by MontelukastNa** [warmcat/libwebsockets#2730]
Hi, lws's cool guys.
Recently, I met a confused problem.

`The v4.3.0 version of libwebsockets, `
`in the operating system centos7, `
`gcc version 4.4.7 20120313 (Red Hat 4.4.7-23), `
successfully compiled the product in the 'build' directory, but the header file 'libwebsockets. h' in the 'build' directory has no corresponding interface in the demo, such as lws_ client_ Connect, but only send, recv, etc

how to fix it? 
thx

**Comment by lws-team** [comment]
Use `sudo make install` to place the headers in (by default) `/usr/local/include`.  The full set of headers should be in there then.

**Comment by MontelukastNa** [comment]
> Use `sudo make install` to place the headers in (by default) `/usr/local/include`. The full set of headers should be in there then.

Cool !!!  
thanks, Andy
