### ISSUE TITLE
LWS_CALLBACK_SERVER_WRITEABLE very slow in windows10 20h2

### ISSUE THREAD

**Issue by zamxqun** [warmcat/libwebsockets#2731]
Dear All:
The Libwebsockets worked well when my Windows System is 1803,   But now the LWS_CALLBACK_SERVER_WRITEABLE call back became slow while My System update to Windows10 20H2.   Almost cost 100 ms wait for LWS_CALLBACK_SERVER_WRITEABLE while the code is the same.   Could you please tell me what can I do?   Thanks for any help!

**Comment by lws-team** [comment]
If this is an old lws version, try current main.

**Comment by zamxqun** [comment]
> 

version is 3.1.99

**Comment by lws-team** [comment]
Then try main.

**Comment by zamxqun** [comment]
> Then try main.

the app collapsed while run  lws_create_context(&info);  lwsl_refcount_cx(context->log_cx, 1);
if (_new > 0)
		cx->refcount++;

**Comment by lws-team** [comment]
That seems to be a problem with your code... only you have that.

**Comment by zamxqun** [comment]
> 

Thank you for your help,    I use main now, have another problem,   I can not enter LWS_CALLBACK_HTTP and LWS_CALLBACK_HTTP_WRITEABLE.
 ```
static int
callback_dynamic_http(struct lws *wsi, enum lws_callback_reasons reason,
	void *user, void *in, size_t len)
{
	struct pss *pss = (struct pss *)user;
	uint8_t buf[LWS_PRE + HTTPBUFFERLENGTH], *start = &buf[LWS_PRE], *p = start,
		*end = &buf[sizeof(buf) - LWS_PRE - 1];
	time_t currentTime;
	int protocalFlag;

	switch (reason) {
	case LWS_CALLBACK_HTTP:

		

		return 0;

	case LWS_CALLBACK_HTTP_WRITEABLE:

		
		return 0;

	default:
		break;
	}

	return lws_callback_http_dummy(wsi, reason, user, in, len);
	//return 0;

}

```

**the initialized code:**
```
static const struct amz_protocols protocol =
{ "http", callback_dynamic_http, sizeof(struct pss), 0 };
static const struct amz_protocols protocolsamz =
{ "ws", protocol_ws_callback, sizeof(struct session_data), MAX_PAYLOAD_SIZE };

static const struct amz_protocols *pprotocolsws[] = { &protocolsamz,&protocol, NULL };


static const struct lws_http_mount mount_dyn = {
	/* .mount_next */		NULL,		/* linked-list "next" */
	/* .mountpoint */		"/qry",		/* mountpoint URL */
	/* .origin */			NULL,	/* protocol */
	/* .def */			NULL,
	/* .protocol */			"http",
	/* .cgienv */			NULL,
	/* .extra_mimetypes */		NULL,
	/* .interpret */		NULL,
	/* .cgi_timeout */		0,
	/* .cache_max_age */		0,
	/* .auth_mask */		0,
	/* .cache_reusable */		0,
	/* .cache_revalidate */		0,
	/* .cache_intermediaries */	0,
	/* .origin_protocol */		LWSMPRO_CALLBACK, /* dynamic */
	/* .mountpoint_len */		4,		/* char count */
	/* .basic_auth_login_file */	NULL,
};

/* default mount serves the URL space from ./mount-origin */

static const struct lws_http_mount mount = {
	/* .mount_next */	&mount_dyn,		/* linked-list "next" */  //&mount_dyn
	/* .mountpoint */		"/",		/* mountpoint URL */
	/* .origin */		"./mount-origin",	/* serve from dir */
	/* .def */			"index.html",	/* default filename */
	/* .protocol */			"http",
	/* .cgienv */			NULL,
	/* .extra_mimetypes */		NULL,
	/* .interpret */		NULL,
	/* .cgi_timeout */		0,
	/* .cache_max_age */		0,
	/* .auth_mask */		0,
	/* .cache_reusable */		0,
	/* .cache_revalidate */		0,
	/* .cache_intermediaries */	0,
	/* .origin_protocol */		LWSMPRO_FILE,	/* files in a dir */
	/* .mountpoint_len */		1,		/* char count */
	/* .basic_auth_login_file */	NULL,
};

struct lws_context_creation_info info = { 0 };
	struct lws_context *context;
	const char *p;
	int n = 0, logs = LLL_ERR;// | LLL_WARN;// LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE
		/* for LLL_ verbosity above NOTICE to be built into lws,
		 * lws must have been configured and built with
		 * -DCMAKE_BUILD_TYPE=DEBUG instead of =RELEASE */
		 /* | LLL_INFO */ /* | LLL_PARSER */ /* | LLL_HEADER */
		 /* | LLL_EXT */ /* | LLL_CLIENT */ /* | LLL_LATENCY */
	/* | LLL_DEBUG */;


	if ((p = lws_cmdline_option(argc, argv, "-d")))
		logs = atoi(p);

	lws_set_log_level(logs, wsocketLogCall);


	info.port = LISTERN_PORT;
	info.iface = NULL;
	info.pprotocols = pprotocolsws;
	info.gid = -1;
	info.uid = -1;

	info.mounts = &mount;
	info.vhost_name = "http";
```
	
	
	Then I visit url like:http://127.0.0.1:7089/ask?method=get_ses&id=all
	
	Use this old version ,it can enter LWS_CALLBACK_HTTP and LWS_CALLBACK_HTTP_WRITEABLE, but now it can not work

**Comment by lws-team** [comment]
Lws has logs so you stand a chance to understand what is happening.  Turn the non-ERR logs back on and paste what they say when you try to connect.

**Comment by zamxqun** [comment]
> Lws has logs so you stand a chance to understand what is happening. Turn the non-ERR logs back on and paste what they say when you try to connect.

12:27:44.406	libwebsockets Log:[2022/09/21 12:27:44:1408] N: http: lws_create_context: LWS: 4.3.99-unknown, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent

12:27:44.422	libwebsockets Log:[2022/09/21 12:27:44:1447] N: http: __lws_lc_tag:  ++ [wsi|0|pipe] (1)

12:27:44.453	libwebsockets Log:[2022/09/21 12:27:44:2245] N: http: __lws_lc_tag:  ++ [vh|0|http||8021] (1)

12:27:44.469	libwebsockets Log:[2022/09/21 12:27:44:2265] N: [vh|0|http||8021]: lws_socket_bind: source ads 0.0.0.0

12:27:44.484	libwebsockets Log:[2022/09/21 12:27:44:2265] N: http: __lws_lc_tag:  ++ [wsi|1|listen|http||8021] (2)

12:27:59.312	libwebsockets Log:[2022/09/21 12:27:59:0856] N: http: __lws_lc_tag:  ++ [wsisrv|1|http|(null)] (2)

12:27:59.328	libwebsockets Log:[2022/09/21 12:27:59:0946] N: http: __lws_lc_tag:  ++ [wsisrv|2|http|(null)] (3)

12:28:07.656	libwebsockets Log:[2022/09/21 12:28:07:4291] N: http: __lws_lc_untag:  -- [wsisrv|2|http|(null)] (2) 8.334s

12:28:14.344	libwebsockets Log:[2022/09/21 12:28:14:1093] N: http: __lws_lc_untag:  -- [wsisrv|1|http|(null)] (1) 15.023s

12:28:14.359	libwebsockets Log:[2022/09/21 12:28:14:1123] N: http: __lws_lc_tag:  ++ [wsisrv|3|http|(null)] (2)

**Comment by zamxqun** [comment]
> Lws has logs so you stand a chance to understand what is happening. Turn the non-ERR logs back on and paste what they say when you try to connect.

If I chang 
static const struct lws_protocols *pprotocolsws[] = { &protocol,&protocolsamz, NULL };
to
static const struct lws_protocols *pprotocolsws[] = { &protocolsamz,&protocol, NULL };

then can not enter
 static int protocol_ws_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) 

It seems that only first protocal valid? How can both valid.

**Comment by zamxqun** [comment]
The invalid function only receive LWS_CALLBACK_EVENT_WAIT_CANCELLED

**Comment by lws-team** [comment]
The first protocol is used for handling incoming http where there's no other information about routing it.  For, eg, ws connections, the client can indicate the protocol name it wants to bind to, but not so for http.

The second protocol should be live but there must be some other way to bind to it, eg, by the client sending the ws subprotocol name it wants.

**Comment by zamxqun** [comment]
> The first protocol is used for handling incoming http where there's no other information about routing it. For, eg, ws connections, the client can indicate the protocol name it wants to bind to, but not so for http.
> 
> The second protocol should be live but there must be some other way to bind to it, eg, by the client sending the ws subprotocol name it wants.

Thank you for your help,   How could I change the code ,   make the ws connection handle by first protocal,  while http request handle by second protocal?

**Comment by lws-team** [comment]
That's not the best way to handle it.  Leave the http one as the first, "zero-th" one.

You can mark protocols with a pvo indicating that this protocol is to be used when the incoming ws connection did not tell what protocol it wanted.  Ideally, the incoming ws connections should announce the protocol name it speaks at connection upgrade time, then you can support multiple ws protocols per vhost.  If you can't do that because you didn't do it from the start and now you're stuck with it, you can change the protocol that will be used for that case.

This kind of thing should bind ws connections with no protocol indication at upgrade time to your protocol "my-protocol-name"

```
static const struct lws_protocol_vhost_options pvo_default = {
        NULL,
	NULL,
	"default",		/* pvo name */
	NULL  /* pvo value */
};

static const struct lws_protocol_vhost_pvo = {
	NULL,				/* "next" pvo linked-list */
	&pvo_default,		/* "child" pvo linked-list */
	"my-protocol-name",	/* protocol name we belong to on this vhost */
	""				/* ignored */
};

...

        info.pvo = &pvo;
```

**Comment by zamxqun** [comment]
> That's not the best way to handle it. Leave the http one as the first, "zero-th" one.
> 
> You can mark protocols with a pvo indicating that this protocol is to be used when the incoming ws connection did not tell what protocol it wanted. Ideally, the incoming ws connections should announce the protocol name it speaks at connection upgrade time, then you can support multiple ws protocols per vhost. If you can't do that because you didn't do it from the start and now you're stuck with it, you can change the protocol that will be used for that case.
> 
> This kind of thing should bind ws connections with no protocol indication at upgrade time to your protocol "my-protocol-name"
> 
> ```
> static const struct lws_protocol_vhost_options pvo_default = {
>         NULL,
> 	NULL,
> 	"default",		/* pvo name */
> 	NULL  /* pvo value */
> };
> 
> static const struct lws_protocol_vhost_pvo = {
> 	NULL,				/* "next" pvo linked-list */
> 	&pvo_default,		/* "child" pvo linked-list */
> 	"my-protocol-name",	/* protocol name we belong to on this vhost */
> 	""				/* ignored */
> };
> 
> ...
> 
>         info.pvo = &pvo;
> ```

Thank you for your help!!
