### ISSUE TITLE
LibwebsocketConfig.cmake or libwebsocketConfig.cmake

### ISSUE THREAD

**Issue by stephenchenKL** [warmcat/libwebsockets#2733]
When I compile libwebsockets from git source code v3.1, LibwebsocketConfig.cmake is generated.

However some application (mosquitto mqtt) looks for libwebsocketConfig.cmake. Because it is case sensitive, so it fails.

Should I change mosquitto or libwebsockets? How?

**Comment by lws-team** [comment]
V3.1 is many years old, current stable is v4.3.

Another way is drop a symlink in the directory that symlinks what you want to what you have.

**Comment by lws-team** [comment]
It's dying when making the test server... for whatever reason... you can just skip making that `-DLWS_WITHOUT_TESTAPPS=1`
