### ISSUE TITLE
How to handle the return  code "LWS_CALLBACK_WS_PEER_INITIATED_CLOSE   = 38"

### ISSUE THREAD

**Issue by kanli201904** [warmcat/libwebsockets#2743]
After i received the code "LWS_CALLBACK_WS_PEER_INITIATED_CLOSE   = 38", 

How to ensure the integrity of the sent data ？ And how to avoid such problems？

**Comment by lws-team** [comment]
If you get PEER_INITIATED_CLOSE, the peer is nicely telling you it's closing your connection.  That's all.

If you think it's because you're sending junk, then you must find why you are sending it junk.  That doesn't seem to be anything anyone else can help you with.

**Comment by kanli201904** [comment]
Hello Andy,
   Thank you very much for the above answer. It seems there are some  things wrong with the sending data or the format of the sending buffer?  are there funtions that we can use to get the error string ?   are there special limits for the format of the string buffer? 
  Thanks .
Kan
