### ISSUE TITLE
how to get websocket scheme from struct lws *wsi

### ISSUE THREAD

**Issue by shubhangikhandeka** [warmcat/libwebsockets#2746]
Hi Andy,Is there any API to get information of web socket scheme (ws:// or wss://) when we get lwscallback for WS_CONN_STATE_SRV_ACCEPTED case .
        
        using below API , i am able to get ip address from struct lws *wsi , but i need Connection mode (ws or wss )
        lws_get_peer_addresses (struct lws *wsi, lws_sockfd_type fd, char *name, int name_len, char *rip, int rip_len);

**Comment by lws-team** [comment]
No.  It just tells you about the IP situation not what is traveling on it.

However you should know about https or not based on the listening vhost.  You can get the vhost name the wsi is associated with by  by `lws_get_vhost_name(lws_get_vhost(wsi))`.

**Comment by shubhangikhandeka** [comment]
Hello Andy, Thank you for quick query resolution. I have used lws_get_vhost_name(lws_get_vhost(wsi)) however, I am not getting web socket scheme from these 2 APIs. Is there any other way or API that I can use?

**Comment by lws-team** [comment]
A particular vhost will normally require https or not.  So the vhost name it came in on implies it's listening via tls, you know it's conndcted via https / wss.
