### ISSUE TITLE
Can I switch protocol in callback while connection is established ?

### ISSUE THREAD

**Issue by hanshuhuang** [warmcat/libwebsockets#2747]
I need to build multi connection at the first, and wait for server tell me which one can survive, and I will close the other connections, and start processing different logic(protocol).

I want to specify this two phase to two protocol named A, B, and I want to use A to find the survived connection, and then switch to the protocol B, could libwebsockets do that?  I do not find any doc/code about the above usage.

**Comment by hanshuhuang** [comment]
@lws-team  please tell me how to do, thanks~

**Comment by lws-team** [comment]
ws does not support switching an already negotiated protocols.  So this is not an lws question.

Your protocol and do whatever it wants, including sending a packet indicating it wants to talk differently inside your protectol for whatever reason.

we supports a "subprotocol" which is protocol netgotiation chosen by the server based on what the client has to offer.  But that is a one-time thing selected by the server before th client is talking to it.

**Comment by hanshuhuang** [comment]
ok, thanks
