### ISSUE TITLE
help! LWS_CALLBACK_CLIENT_RECEIVE_PONG trap into An infinite loop

### ISSUE THREAD

**Issue by hanshuhuang** [warmcat/libwebsockets#2749]
I want to do something when receiving pong, but my code will cause an infinite loop.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/32003283/197398884-dcebc4c5-1bac-4609-b666-a6aa2d23be0d.png">

According to gdb, I found it will never minus in -= out, so the loop happed.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/32003283/197398640-ce81775a-fa6d-40a8-b416-a5192eb4b271.png">
code is in:roles/ws/client-parser-ws.c:643 

n is equal PMDR_NOTHING_WE_SHOULD_DO(5), which make it never process minus.

how can I do my thing just once at a pong packet.

**Comment by lws-team** [comment]
What do you think I should do about that?

**Comment by hanshuhuang** [comment]
@lws-team you reply is so quick.
I just want to know how to process LWS_CALLBACK_CLIENT_RECEIVE_PONG reason whout infinite loop.
I have no idea to deal with the problem.

**Comment by hanshuhuang** [comment]
in addition, I recently learn libwebsockets, but it is so hard to understand the whole code architecture, any book or blog can provide to me for learning libwebsockets?

**Comment by lws-team** [comment]
This seems something to do with permessage-deflate, you should be able to work around it by disabling that.

**Comment by hanshuhuang** [comment]
but i want to use deflate feature, it will affact pong message?

**Comment by lws-team** [comment]
Then I suggest you debug it and send a patch, I do not have time to look at it.

**Comment by hanshuhuang** [comment]
ok, any place to record this "bug"? I'm afraid I forget.
