### ISSUE TITLE
Getting started. How to add to ringbuffer from a thread?

### ISSUE THREAD

**Issue by drfrankencopter** [warmcat/libwebsockets#2751]
Hi Folks, thanks for all the work on this library. I'm not sure if "Issues" is the right place to put this, but I didn't see a "Discussions" tab on this repo. Feel free to move it/close it as required.

I'm writing a small server app that is looking to use websockets to broadcast data to browser clients. I've got libwebsockets built and demo apps running, but I'm not really sure where the best place to look for getting to understand how to use the library is. Any guidance here would be most appreciated.

More specifically, what I'm trying to figure out at the moment is how to trigger lws callback from another thread. What I was hoping that I could do was look at the mirror.c protocol as an example, but instead of filling the ring buffer when data is received on the same websocket, I want to add to the ring buffer upon receipt of new data from a connected process (sending it to me via regular local UDP socekt).

For now, to get started I've just simulated the UDP receive by running a simple thread in a timed while loop...just incrementing a dumb counter, similar to dumb_increment, but outside of the protocol's callback. I want to then add the increment value to the ring buffer, and have it sent to all clients when writable. But I'm having difficulty understanding how to access the ringbuffer, as it seems in the example that it is passed along by pointer *user in the callback itself.

Here's my simple sample thread...

`
  void* mySampleThread1(void* arg) {
	//This is just a dumb thread that counts/echos to the screen

	int i=0;

	printf("mySample Thread1 has been spawned\n");
	while (1) {
		i++;
		printf("My sample thread1 is writing to console: %d\n", i);
		Sleep(1000); // About 1 Hz
		//Add to the ringbuffer here!
	}
	return 0; // I'm done!
  }  // end sampleThread
`

How do I go about adding my data to the ringbuffer(s) from this thread? I need to somehow expose their pointers to my thread...

Sorry if it's a dumb question, but I'm confused at the moment.

Thanks!

PS: Also can't figure out how to use the code markup in this forum...not sure why I puts my function name and closeing bracket/comments outside the code block. I'll google that one :)

**Comment by drfrankencopter** [comment]
Reading a bit more (closed issues)...am I just supposed to  call lws_cancel_service() on my context when I have new data to add, shove it in some visible variable, and then in the protocol callback fill my ring buffers for the LWS_CALLBACK_EVENT_WAIT_CANCELLED reason?

https://libwebsockets.org/lws-api-doc-main/html/group__service.html#ga53e3d0801dfda7960a7249dd559e68a2

I have a feeling this is the way I'm supposed to do it...but reassurance would be nice :)

**Comment by drfrankencopter** [comment]
Am still confused...when I receive a LWS_CALLBACK_EVENT_WAIT_CANCELLED, the user pointer is null. This was where I was hoping to store/update the local copy of the data

**Comment by lws-team** [comment]
The user pointer is a member of a wsi.  EVENT_WAIT_CANCELLED affects the whole lws_context, it is not related to any wsi.

vhost and the context also have their own user pointer for use at those scopes.

You would normally lock, and manage a list of things you want doing from other threads, then unlock and cancel the lws wait so it can wake up and lock and go through your list.

When referring to wsi from different threads, you must track their ..._CLOSE in the lws thread, since that is usually close to the last callback before wsi destruction.  You would lock and clean the wsi off any lists held by other threads then.  There's more background here:

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md
