### ISSUE TITLE
what is right way to use lws_http_redirect ?

### ISSUE THREAD

**Issue by jongsun89** [warmcat/libwebsockets#2752]
Hi .
I'm setting up server with lws .
I put some logic on callback of LWS_CALLBACK_CHECK_ACCESS_RIGHTS for page A.
If users has no permission to the page A, the server redirects(lws_http_redirect ) to another page B(also serviced with lws) in the callback.
and return -1 for the callback .
simply like ..

case LWS_CALLBACK_CHECK_ACCESS_RIGHTS :
   lws_http_redirect(wsi, 200, "/pageB", ..); // for unacceptable wsi
   return -1;

From now , i've got an issue somtimes.
normally, page A redirected to page B .
But, sometimes, page A gets 401 error and not redirected.
This looks timing issues , because server redirects and returns -1 on access right callback.
Am I right doing ? i wonder how always success to redirect .. Thanks!

**Comment by lws-team** [comment]
It sounds like the redirect is racing the close... if so, http/2 should solve it.

Or something like set up a sul in the wsi user data, return 0, and when the sul fires, `lws_wsi_close(wsi, LWS_TO_KILL_ASYNC);`  Make sure to also `lws_sul_cancel()` this new sul in the _CLOSE callback in case it closes by itself first.

**Comment by jongsun89** [comment]
@lws-team , hi , thanks for reply.
sorry i don't get you . 
I'm checking for lws_sul_schedule() .

Is this what you meant ?
- call lws_sul_schedule() in LWS_CALLBACK_CHECK_ACCESS_RIGHTS callback 
- call lws_wsi_close in stagger_cb(), when stagger_cb() fired
If it's right, how to pass wsi pointer to the stagger_cb(). 
Like global var looks dangerous, if another access fires LWS_CALLBACK_CHECK_ACCESS_RIGHTS  again ,before sul is fired .

**Comment by lws-team** [comment]
You can call the cb for the sul what you like, "stagger" is named like that because it's what the client example does by making connections at intervals (staggered) instead of all at once.  You might call it `sul_cb_close_delay()` or somesuch.

Yes don't use a global for anything, that is the meaning of what I wrote "set up a sul in the wsi user data", put the sul object for this in what the examples call the `pss`, use data, specific to a wsi.  And make sure you cancel it when the wsi closes so it doesn't leak.  It's fine to cancel a sul that might not be active just in case.  That way, if you have 0 or 20 or 2000 wsi, there will be a sul for anything needed and nothing wasted when not.

**Comment by jongsun89** [comment]
@lws-team Hi. i tried your advice but failed. 


```cpp
struct per_session_data__developer {
    lws_sorted_usec_list_t sul;
    struct lws *wsi;
};

static void
stagger_cb(lws_sorted_usec_list_t *sul)
{
    struct lws *wsi = (struct lws*)(sul - sizeof(lws_sorted_usec_list_t));
    lws_set_timeout(wsi, PENDING_TIMEOUT_ESTABLISH_WITH_SERVER, LWS_TO_KILL_ASYNC);
}

int access_rights(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
    struct per_session_data__developer *data = (struct per_session_data__developer*)user;
    data->wsi = wsi;
    struct lws_context *context = lws_get_context(wsi);

    lws_sul_schedule(context, 0, &(data->sul), stagger_cb, 100 * LWS_US_PER_MS);
    return 0;
}


int http(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
    return lws_callback_http_dummy(wsi, reason, user, in, len);

}

int closed(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
    struct per_session_data__developer *data = (struct per_session_data__developer*)user;
    struct lws_context *context = lws_get_context(wsi);

    lws_sul_schedule(context, 0, &(data->sul), NULL, LWS_SET_TIMER_USEC_CANCEL);
    return lws_callback_http_dummy(wsi, reason, user, in, len);
}
```


i expected ,
- access_right -> stagger_cb -> closed
but, real work
- access_right -> http -> killed process and dumped in lws_callback_http_dummy

am i have wrong  ?

**Comment by jongsun89** [comment]
I've some tested ..
1. if sul is set as global variable, process is not killed .. I guess that user data is deleted before sul is triggered ? it means that sul can't be used per each wsi ..?
2. even though stagger_cb triggered (with global sul variable), call sequence is not what i expected .
- access_right ->  http -> stagger_cb
- http can also make racing with redirection
