### ISSUE TITLE
No API access to server set-cookie headers when server redirects. (Cookies broken?)

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#2753]
I have an HTTP server which is returning a response with set-cookie headers and a redirect.

I've written a client using libwebsocket v3.2.3 and I don't see how I'm supposed to fetch the cookie(s) sent by the server.

I've tried the following code to see if there is any callback stage at which I can see the set-cookie headers. There is none. 

I do see that internally, at some point, these headers are added to the internal header map and wsi->http.ah->frag_index[WSI_TOKEN_HTTP_SET_COOKIE] == 14 but by the time it does a callback, these have been erased and wsi->http.ah->frag_index[WSI_TOKEN_HTTP_SET_COOKIE] == 0

```
static int callback_http(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
   // for all callbacks, check if we can see our server set-cookie headers
    int len2 = lws_hdr_total_length(wsi, WSI_TOKEN_HTTP_SET_COOKIE);
    if (len2)
        fprintf(stderr, "reason=%d len=%d\n", reason, len2);
```

**Comment by lws-team** [comment]
3.2 is too old to care about.  Try main or v4.3-stable.
