### ISSUE TITLE
can one lws_context object connect to several server address?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2754]
I want to collect data from several websocket servers.

can i bind all address in in lws_context? could you provide a demo?

I also tried use thread_pool to do this.

but it crashed in lws_service? is there anything i should know? any advice? thanks

**Comment by lws-team** [comment]
You can use a single lws_context just fine.

You can't randomly throw threads on event loop code.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

I spent many man-months of time providing demos already.  You can look at https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client-multi to see how the multiple client connections should be handled.  And at https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client and other ws client examples to see how to handle ws particularly.
