### ISSUE TITLE
LibWebSockets vs uWebSocket

### ISSUE THREAD

**Issue by pkrumins** [warmcat/libwebsockets#2755]
Hi allz,

The new modern and hot library on the block is uWebSocket. It's claiming impressive benchmark numbers but there no comparison to LibWebSockets. Has anyone benchmarked LWS against uWebSocket? Would love to see which one is the winner.

Thx!

**Comment by lws-team** [comment]
There have been lots of libraries doing ws since 2010 when lws came out, lots focused on 'speed'.  In some cases speed is all you care about, but usually other considerations matter more.

Either way, this is FOSS.  Use (and contribute to...) whatever suits you best.
