### ISSUE TITLE
Error when trying to clone the git.libwebsockets.org repo: [errno=Connection refused]

### ISSUE THREAD

**Issue by guilleprfc** [warmcat/libwebsockets#2756]
Hi,

I have a Dockerfile used to install the janus gateway that uses the libwebsockets library and today, when trying a clean build I noticed the following error:

` > [apisgateway-janus-server  8/11] RUN cd /root && git clone git://git.libwebsockets.org/libwebsockets &&      cd libwebsockets &&     git checkout v3.2-stable &&     mkdir build &&  cd build &&     cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" .. &&     make &&         make install:
#0 0.578 Cloning into 'libwebsockets'...
#0 42.76 fatal: unable to connect to git.libwebsockets.org:
#0 42.76 git.libwebsockets.org[0: 31.53.12.215]: errno=Connection refused
#0 42.76 git.libwebsockets.org[1: 31.53.12.215]: errno=Connection refused`

To fix it I changed "git clone git://git.libwebsockets.org/libwebsockets" to  "git clone https://github.com/warmcat/libwebsockets.git", but I raise this issue it looks like it happened due to an error/expiration of certificates etc

Best regards

**Comment by lws-team** [comment]
I'm no longer going to serve using git:// ... github removed support for it last year

https://github.blog/2021-09-01-improving-git-protocol-security-github/

You should be able to continue to get it fine using https, eg

```
$ git clone https://libwebsockets.org/repo/libwebsockets
Cloning into 'libwebsockets'...
remote: Enumerating objects: 53210, done.
remote: Counting objects: 100% (53210/53210), done.
remote: Compressing objects: 100% (11363/11363), done.
remote: Total 53210 (delta 42018), reused 52418 (delta 41358), pack-reused 0
Receiving objects: 100% (53210/53210), 33.79 MiB | 12.86 MiB/s, done.
Resolving deltas: 100% (42018/42018), done.
$ 
```
