### ISSUE TITLE
cannot clone from 'https://libwebsockets.org/repo/libwebsockets/'

### ISSUE THREAD

**Issue by eshoubak** [warmcat/libwebsockets#2757]
When running a script I get this error message 

Cloning into 'libwebsockets'...
fatal: unable to access 'https://libwebsockets.org/repo/libwebsockets/': Failed to connect to libwebsockets.org port 443: Connection refused

I will try to change the script to point to this GIT repo, but letting you know of the issue. This seems the domain libwebsockets.org is down.

**Comment by lws-team** [comment]
I have moved the server yesterday, it seems you're still using the old DNS record is all, since I turned off lwsws on the old server yesterday too.

If you try again it should be propagated to you by now.

The new server is working OK since yesterday.

**Comment by alien999999999** [comment]
Don't know if this is related, but i seem to get timeout on libwebsocket.org ... i was trying to get the minimal example to compare why my code was not working: https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-client/minimal-ws-client-rx

but i got connection timeout...
