### ISSUE TITLE
Is there a limit for how many lws_client_connect_info can bind for one lws_context?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2760]
in connect with websocket server.

For some reason, i want to bind many connect_info with one lws_context and expect these connect meassge can return in this lws_context.

but I found when i build many connects, the messages will be stopped.

is there a setting in libwebsocket, or i need to ask to the server side?

**Comment by lws-team** [comment]
There's no limit, you can refer to the -multi client examples.
