### ISSUE TITLE
HTTP Auth Digest

### ISSUE THREAD

**Issue by simon0356** [warmcat/libwebsockets#2764]
Hello,

I'm trying to connect to a secure websocket server configured with http digest auth.
I didn't know very well libwebsockets but as I understand digest auth is not handled, even in server mode (following https://github.com/warmcat/libwebsockets/issues/1635)

I have configured a simple apache2 server with digest authentification and I was wondering if it was possible to handle the digest auth in the following way : 
Using the minimal-http-client add the following callback event handling :
LWS_CALLBACK_RECEIVE_CLIENT_HTTP
Read data from http to handle server digest authentification challenge
Send to the server the digest 
Once the connection and authentification should be completed.
Will be then possible to transform the libwebsockets connexion handle from HTTP to Websocket to perform the Websocket Upgrade ?

Thanks
Simon

**Comment by lws-team** [comment]
Someone needs to do some work in lws to have that.  If you're the guy to do the work, you should look closer at the stuff I did for #1635 first.

**Comment by simon0356** [comment]
Hello,

I will try to implement the feature for http/ws client but i will need some help :

I have dig a little bit into the library and i'm now able to generate the Authorization digest response header from user callback 
My current work is available here : https://github.com/simon0356/libwebsockets/commit/1afae78c167ef09339e8ea113a2fa9ca21505486
This is still work in progress and I know it is currently not acceptable for a PR

The computation of Digest auth is mostly copy-pasted from Curl Library.
I was firstly thinking that catching the 401 and www-authenticate token in lws_client_interpret_server_handshake will allow me to ask for user Authorization token but it did not work since the HTTP get request need to be replayed again after the 401 response from server with the computed Authorization digest.

My question is where should I consider the 401 and Authorization Token to make callback ask for User and Password, generate the  Authorization  Digest response and replay the HTTP GET with Authorization header set ?
And how to properly replay this Get request ? 

I will continue to search on my own, but your help will be welcome to put me on the good path to see my modification acceptable

Thanks
Simon

**Comment by lws-team** [comment]
> The computation of Digest auth is mostly copy-pasted from Curl Library.

Curl has an unusual license, it's not directly MIT

https://curl.se/docs/copyright.html

whatever it is can probably be rewritten to use ah memory + lws_snprintf() once it works and the rewrite can be tested.

> I was firstly thinking that catching the 401 and www-authenticate token in lws_client_interpret_server_handshake will allow me to ask for user Authorization token but it did not work since the HTTP get request need to be replayed again after the 401 response from server with the computed Authorization digest.

Lws "stashes" connection details at client connect api

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n85

this is partly so it can return to the caller user code quickly without needing possibly stack-based strings and things passed to the client connection api to still exist afterwards, it has a copy of them.  If the wsi stash is still around when you get the 401, you can use that info to go again with the auth.

Another way is expose the difficulty to the user code.  So he is involved in making the first connection, handling the 401, and he makes the second connection himself feeding in the auth data from the first one somehow.  That has some advantages for implementing it cleanly.

**Comment by simon0356** [comment]
> > The computation of Digest auth is mostly copy-pasted from Curl Library.
> 
> Curl has an unusual license, it's not directly MIT
> 
> https://curl.se/docs/copyright.html
> 
> whatever it is can probably be rewritten to use ah memory + lws_snprintf() once it works and the rewrite can be tested.
> 
I agreed it is strictly WIP and testing purpose 
> > I was firstly thinking that catching the 401 and www-authenticate token in lws_client_interpret_server_handshake will allow me to ask for user Authorization token but it did not work since the HTTP get request need to be replayed again after the 401 response from server with the computed Authorization digest.
> 
> Lws "stashes" connection details at client connect api
> 
> https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/client/connect.c#n85
> 
> this is partly so it can return to the caller user code quickly without needing possibly stack-based strings and things passed to the client connection api to still exist afterwards, it has a copy of them. If the wsi stash is still around when you get the 401, you can use that info to go again with the auth.
From the callback ? I'm sorry but I didn't find in any example or library source how i can go again with the auth without re-opening a TCP socket (which will invalidate the challenge previously send by server). 
> 
> Another way is expose the difficulty to the user code. So he is involved in making the first connection, handling the 401, and he makes the second connection himself feeding in the auth data from the first one somehow. That has some advantages for implementing it cleanly.


Thanks
Simon

**Comment by lws-team** [comment]
> without re-opening a TCP socket (which will invalidate the challenge previously send by server).

For h1 with pipelining flag enabled, or h2, lws can bind separate http transactions to the same tcp / tls connection, the h2 way is better since h1 pipelining is itself sort of a hack at the protocol level.

So the first connection brings up the tcp part, and then the tls part, does the first connection's transaction but leaves the now idle tcp and tls up for some grace time (default is 5 or 10 secs or something).  If a whole other wsi comes along to the same coordinates, it picks up the lukewarm tcp + tls from the first connection and uses it directly for the subsequent ones.  Eventually there's nothing else for the connection and it times out and closes the tcp + tls.

Separate from that, there's stuff to "reset" a wsi so it can do redirects without changing the wsi object that was told to the user code when it first started the connection.  And separate from that again, it should be possible to reset also the ah bound to the wsi (which carries the headers) and reset the wsi state so it thinks it's just connected and should make the client's outgoing headers again.

**Comment by simon0356** [comment]
Thanks for this informations I will look toward the pipelining flag and trying to reset the WSI.

I will keep you up to date :) 
Simon

**Comment by simon0356** [comment]
I'm now able to perform the auth digest without any modification in library, thanks a lot for your help.
I will now try to do the same with a websocket upgrade.
If you want too I will be happy to wrote an example of http client with digest authentification with cleaner challenge processing.
Could you please send me any link related to code-style/indentation or contribution requirement before ? 

Thanks
Simon

**Comment by lws-team** [comment]
Great... yes working examples I can point to would be good.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.contributing.md
