### ISSUE TITLE
how to set protocol to match default new WebSocket(url)

### ISSUE THREAD

**Issue by alien999999999** [warmcat/libwebsockets#2765]
I tried using protocol "" and protocol "*" to match the default javascript "new Websocket(url)" case, but it seems not to work.

How can i match in the protocols when no subprotocol is specified in the websocket connection?

**Comment by lws-team** [comment]
You can just set the subprotocol in the Websocket constructor, it's the second argument.  It will match by protocol name field then with nothing else to do.

Otherwise you must use vhost pvos to specify a protocol name using "default" key.
