### ISSUE TITLE
libwebsockets.org "pipermail" seems not to be up

### ISSUE THREAD

**Issue by tzAcee** [warmcat/libwebsockets#2766]
Hey,
I've been trying to browser for a problem with my code and if I google for it I stumble upon some pipermail threads, which aren't reachable anymore.
![image](https://user-images.githubusercontent.com/50580688/201055436-cc11dd23-934d-493d-a13d-c7f82b440ce6.png)

Is there any way to access them?
Im always getting 404 Not found.

One example link would be: https://libwebsockets.org/pipermail/libwebsockets/2017-March/003284.html

( Before I ask for my problem in here, I wanted to solve it myself because of my big codebase. )

**Comment by lws-team** [comment]
That should be OK now.

But since mailman2 uses python2 and no modern OS provides it any more, I don't have a solution at the moment for anything but the archives.
