### ISSUE TITLE
protocol specific user member: cannot find it in callback?

### ISSUE THREAD

**Issue by alien999999999** [warmcat/libwebsockets#2767]
The documentation mentions that the "user" member of struct lws_protocols ( https://libwebsockets.org/lws-api-doc-main/html/group__Protocols-and-Plugins.html#structlws__protocols ) : "ignored by lws, but user code can pass a pointer here it can later access from the protocol callback"
but how can i get this in the callback? it does not seem to be the user argument in the callback function (at least in the LWS_CALLBACK_RECEIVE reason case)?

**Comment by lws-team** [comment]
`lws_get_protocol(wsi)` should do.

**Comment by alien999999999** [comment]
oh yeah, i can get it directly from the protocol, thanks
