### ISSUE TITLE
How to get lws_client_connect_via_info error message?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2768]
I build websocket connection by lws_client_connect_via_info.

in most situation, it works well.

but sometims, it failed, return a nullptr.

how can i know the message, and is there any method can avoid this?

**Comment by lws-team** [comment]
It will return NULL if it couldn't really get started with that connection for some reason.

However if you handle `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`, depending on what happened it will try to give you some more details like a human-readable string about it in `in` before returning NULL to the caller.

**Comment by nealworking** [comment]
does it means i can try catch this error? could you write a demo for how to catch this human-readable string?

**Comment by lws-team** [comment]
Can you grep for `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` in the hundred plus examples?

**Comment by nealworking** [comment]
thanks for reply. I checked, but, when lws_client_connect_via_info return null, my callback of LWS_CALLBACK_CLIENT_CONNECTION_ERROR seems no feedback.

**Comment by nealworking** [comment]
> Can you grep for `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` in the hundred plus examples?

sorry andy, I think my connect_via_info failed, return nullptr, and no feedback from callback functions;

the demo i read seems not work for me, could you kindly provide a tiny demo? thanks very much

**Comment by lws-team** [comment]
Even the simplest existing ws example already shows it if you bother to look

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c#n96

Put github away and trace where it fails if there is no other information - you have your code.
