### ISSUE TITLE
what does the message "N: __lws_lc_untag:  -- [wsicli|1|WS/h1/default/fstream.binance.com] (0) 2.019min" mean?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2771]
i use lws to get data from binance.

it works well at the beginning, but several minutes later:

i got this:

`[2022/11/12 23:18:11:8321] N: __lws_lc_untag:  -- [wsicli|1|WS/h1/default/fstream.binance.com] (0) 2.019min
`

could you let me know what does this message mean?

**Comment by lws-team** [comment]
I'm not your personal tech support.
