### ISSUE TITLE
what is difference between binding several connections to one lws_context and several lws_context?

### ISSUE THREAD

**Issue by nealworking** [warmcat/libwebsockets#2772]
After connecting to websocket server, I need to send 3000 requests to server, each requests i created a connection, in order to subscribe market data.

i am worrying about too heavy load for one context. so i tried to create several contexts.

for these two, the main code is:

one context:

```
while (1) {
  lws_service(ctx, 0);
}
```

several contexts:
```
while (1) {
  for (auto ctx : ctxs) lws_service(ctx, 0);
}
```

i found the several contexts are easy to crashed, could you let me know what is the difference between these two methods, and which one is better?

**Comment by lws-team** [comment]
Look for related documentation in the READMEs.
