### ISSUE TITLE
Support of SSL_ERROR_WANT_ASYNC 

### ISSUE THREAD

**Issue by SreedharRe** [warmcat/libwebsockets#2773]
Team, 
  Does LWS support SSL_ERROR_WANT_ASYNC Handling? Basically I am trying to establish websocket connection in client mode and connection fails with following log.

2022/11/04 18:13:22.827073930 {ida_ws_R0-0}{1}: [ida_ws] [6636]: UUID: 0, ra: 0 (debug): **lws_ssl_client_connect2**: SSL_connect says -1
2022/11/04 18:13:22.827080510 {ida_ws_R0-0}{1}: [ida_ws] [6636]: UUID: 0, ra: 0 (info): **lws_http_client_socket_service**: closing conn at LWS_CONNMODE...SERVER_REPLY, [wsicli|9|WS/h1/10.0.0.170], state 0x204
2022/11/04 18:13:22.827082790 {ida_ws_R0-0}{1}: [ida_ws] [6636]: UUID: 0, ra: 0 (info): reason: **connect unk 9**
2022/11/04 18:13:22.827087650 {ida_ws_R0-0}{1}: [ida_ws] [6636]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 1 - **CLIENT_CONNECTION_ERROR** 

Looking into Code - 
**lws_http_client_socket_service** -> 
      case LRS_WAITING_SSL:
                 **lws_ssl_client_connect2**->
                         if (lwsi_state(wsi) == LRS_WAITING_SSL) {
                          n = lws_tls_client_connect(wsi, errbuf, len);
                                         lwsl_err("%s: SSL_connect says %d\n", __func__, n);

In **lws_tls_client_connect**(struct lws *wsi, char *errbuf, size_t elen)
        n = **SSL_connect**(wsi->tls.ssl);
         m = lws_ssl_get_error(wsi, n);
....
            lws_snprintf(errbuf, elen, "connect unk %d", m);

So SSL_connect is returning SSL_ERROR_WANT_ASYNC whose value is 9 and seems like LWS is not handling it and hence closing connection.

Is it a known issue or not supported or Am I doing something wrong

**Comment by SreedharRe** [comment]
Yes .. We are setting SSL_MODE_ASYNC using SSL_CTX_set_mode(sslctx,SSL_MODE_ASYNC) and pass this ssl_ctx to LWS. This is needed because of our platform guidelines

So are you saying LWS doesn't support SSL ASYNC mode?

"You can try faking it into SSS_WANT_READ if so and see what happens."
>>> Even if I do this, on the same flow, LWS is closing connection too, so I guess it may not work

**Comment by lws-team** [comment]
> So are you saying LWS doesn't support SSL ASYNC mode?

Yes, it doesn't set that mode, why would it support it.

It sounds like you need to retry when your ENGINE completes whatever it's doing.  It's out of scope for lws to know anything about that.

**Comment by SreedharRe** [comment]
Converting SSL_ERROR_WANT_ASYNC to SSS_WANT_READ worked. Can this patch be taken for next release to support ASYNC Engines please?

Diff is  ( Not git diff though )

60,64c60
<     if(m == SSL_ERROR_WANT_ASYNC) {
<         lwsl_debug("%s: SREE: Converting SSL_ERROR_WANT_ASYNC to SSL_ERROR_WANT_READ",__func__);
<         m = SSL_ERROR_WANT_READ;
<     }
< 	lwsl_debug("%s: %p %d -> %d (errno %d)\n", __func__, wsi->tls.ssl, n, m,
---
> 	lwsl_debug("%s: %p %d -> %d (errno %d)\n", __func__, wsi->tls.ssl, n, m,

**Comment by SreedharRe** [comment]
lib/tls/openssl/openssl-ssl.c
