### ISSUE TITLE
Allow static building of mbedtls

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [warmcat/libwebsockets#2775]
Hi I'm new to libwebsockets and I have an issue: I want to build libwebsockets with mbedtls statically for my microcontroller. With option LWS_WITH_MBEDTLS enabled it seems I'm forced to also specify LWS_MBEDTLS_LIBRARIES and LWS_MBEDTLS_INCLUDE_DIRS (looking at the example [here](https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build.md)). However of course the libraries are not dynamically built so I can't provide those *.so files. Is there an alternative way? Here's what I have so far:

Project CMakeLists.txt
```
...
# mbedtls

FetchContent_Declare(mbedtls
    GIT_REPOSITORY https://github.com/Mbed-TLS/mbedtls.git
    GIT_TAG "origin/master"
    GIT_PROGRESS true
    QUIET
)
FetchContent_GetProperties(mbedtls)
if(NOT mbedtls_POPULATED)
    FetchContent_Populate(mbedtls)
    add_subdirectory(${mbedtls_SOURCE_DIR} ${mbedtls_BINARY_DIR})
endif()

# libwebsockets

FetchContent_Declare(libwebsockets
    GIT_REPOSITORY https://github.com/warmcat/libwebsockets.git
    GIT_TAG "origin/main"
    GIT_PROGRESS true 
    QUIET
)
FetchContent_GetProperties(libwebsockets)
if(NOT libwebsockets_POPULATED)
    FetchContent_Populate(libwebsockets)

    set(LWS_WITH_MBEDTLS ON CACHE BOOL "Requires mbedtls")
    set(LWS_MBEDTLS_INCLUDE_DIRS ${mbedtls_BINARY_DIR}/include)
    #??? set(LWS_MBEDTLS_LIBRARIES "/tmp/cross/lib/libmbedcrypto.so;/tmp/cross/lib/libmbedtls.so;/tmp/cross/lib/libmbedx509.so")

    set(LWS_WITH_LWSWS ON CACHE BOOL "Requires LWSWS for win portability")

    add_subdirectory(${libwebsockets_SOURCE_DIR} ${libwebsockets_BINARY_DIR})
endif()
...
```

Any advice is greatly appreciated!

**Comment by lws-team** [comment]
Static linking of mbedtls is used with, eg, ESP32 support.  Look at that and see how it is done.

**Comment by MartyMcFlyInTheSky** [comment]
I had a look. If I define ESP_PLATFORM then CMake will call `include_directories()` on each required directory of the esp components according to `$ENV{IDF_PATH}`. This also includes mbedtls and I belive the mbedtls targets. But what if I want to link statically against mbedtls and I'm not on an esp32? I tried this:

cmake -S .. -B . -G "Visual Studio 17 2022" -DLWS_WITH_SSL=ON -DLWS_WITH_STATIC:Bool=ON -DLWS_WITH_MBEDTLS=ON -DLWS_HAVE_MBEDTLS_NET_SOCKETS=ON

But it complains that it cannot find the missing libs:

-- Could NOT find MBEDTLS (missing: LWS_MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)

Even if I were to provide static libs, your CMake checks

```
		if ("${LWS_MBEDTLS_LIBRARIES}" STREQUAL "" OR "${LWS_MBEDTLS_INCLUDE_DIRS}" STREQUAL "")
			message(FATAL_ERROR "You must set LWS_MBEDTLS_LIBRARIES and LWS_MBEDTLS_INCLUDE_DIRS when LWS_WITH_MBEDTLS is turned on.")
```

So I have to provide the libs in any case. Or am I missing something?
