### ISSUE TITLE
Read buffer len is 4080 since version 4.0

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#2782]
I'm updating my 3.2 code to latest 4.3.
In 3.2 I would send a _buffer_ and _buffer-len_ in `lws_http_client_read().`
Since 4.0, lws only uses the first 4080 bytes and calls recvfrom with len=4080 even though I provide a _buffer_ that is 32k bytes.
This means I needs to do many more recvfrom system calls and memcpys if I need to read a contiguous byte array.
Is there some way for me to restore the behaviour as it was to read up to 32k into contiguous memory?

**Comment by lws-team** [comment]
Have a look at struct lws_protocols declaration in the headers.

**Comment by wreuven** [comment]
Didn't help. Still 4080 at a time.


#define MAX_READ_BUFFER (100*1000)

static const struct lws_protocols protocols[] = {
	{
		"http",
		callback_http,
		0,
		MAX_READ_BUFFER  // rx_buffer_size - i think only works after version 4.0
	},
	{ NULL, NULL, 0, 0 }
};
