### ISSUE TITLE
Connect ROS-Bridge Websocket Server failed

### ISSUE THREAD

**Issue by tanhangbo** [warmcat/libwebsockets#2783]
![img_v2_8276d639-8401-49ed-b331-205905466aag](https://user-images.githubusercontent.com/10526252/202977026-a3ceb850-877b-4c93-b67d-89c40a749357.jpg)

ROS Bridge websocket Server Will check HTTP Header port, libwebsockets does not take this port in handshake step:

https://github.com/warmcat/libwebsockets/blob/main/lib/roles/http/client/client-http.c

	/*
	 * 04 example client handshake
	 *
	 * GET /chat HTTP/1.1
	 * Host: server.example.com
	 * Upgrade: websocket
	 * Connection: Upgrade
	 * Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
	 * Sec-WebSocket-Origin: http://example.com
	 * Sec-WebSocket-Protocol: chat, superchat
	 * Sec-WebSocket-Version: 4
	 */

	p += lws_snprintf(p,  lws_ptr_diff_size_t(end, p),
			  "Host: %s\x0d\x0a",
			  lws_hdr_simple_ptr(wsi, _WSI_TOKEN_CLIENT_HOST));

By the way, connect to 80 port of ros-bridge is OK.

**Comment by lws-team** [comment]
You control the content of the host header in your user code.

If you want the port there, put it there in your code.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n126-127

**Comment by tanhangbo** [comment]
Thanks, modify host solved my problem.
