### ISSUE TITLE
After calling lws_create_context  a random port gets open in Listen mode .

### ISSUE THREAD

**Issue by Paramveer24b** [warmcat/libwebsockets#2787]
I have client-server communication running.

I checked number of ports used by both the processes.
there is an extra port has been used by each process.
like below 

tcp        0      0 0.0.0.0:37459           0.0.0.0:*               LISTEN   client
  
tcp        0      0 0.0.0.0:32833           0.0.0.0:*               LISTEN  server

above ports are random after every time I ran the applications.

My query is -
Why this port has been created ?
Are they secure ? because ports are in listening mode. 
Or , Is there any way to avoid this ?

**Comment by lws-team** [comment]
Lws does whatever you tell it to... if you create the "client" context or vhosts telling it a listen port then it will listen there.  If you don't want it set the listen port to `CONTEXT_PORT_NO_LISTEN`.
