### ISSUE TITLE
Makefile not working as expected. 

### ISSUE THREAD

**Issue by joyantamishu** [warmcat/libwebsockets#2788]
Hello everyone, I was trying to build libwebsocket for one of my Bazel project. The configuration of my host machine as follows:

```
Host OS: CENTOS 8
cmake version 3.20.2
Bazel version 5.0.1
```

Now, when I try to run cmake . it does work fine. But when I try to run the make command, I get the following errors:

> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/vagrant/.cache/bazel/_bazel_vagrant/6d691af1e94d4c3588e1025065383f7d/sandbox/linux-sandbox/37/execroot/__main__/bazel-out/k8-fastbuild/bin/api/websocket_github.build_tmpdir
> Scanning dependencies of target GENHDR
> [  0%] Creating build include dir
> [  0%] Built target GENHDR
> Scanning dependencies of target websockets
> [  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-caps.c.o
> In file included from /home/vagrant/.cache/bazel/_bazel_vagrant/6d691af1e94d4c3588e1025065383f7d/sandbox/linux-sandbox/37/execroot/__main__/external/websocket/lib/core/./private-lib-core.h:44,
>                  from /home/vagrant/.cache/bazel/_bazel_vagrant/6d691af1e94d4c3588e1025065383f7d/sandbox/linux-sandbox/37/execroot/__main__/external/websocket/lib/plat/unix/unix-caps.c:28:
> /usr/include/stdlib.h:539:28: error: expected ')' before '__size'
>  extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
>                             ^~~~~~~
>                             )
> /usr/include/stdlib.h:549:23: error: expected identifier or '(' before 'void'
>  extern void *realloc (void *__ptr, size_t __size)
>                        ^~~~
> make[2]: *** [lib/CMakeFiles/websockets.dir/build.make:82: lib/CMakeFiles/websockets.dir/plat/unix/unix-caps.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:608: lib/CMakeFiles/websockets.dir/all] Error 2
> make: *** [Makefile:171: all] Error 2

To my wonder, it's saying error in the system header file! **/usr/include/stdlib.h** 

So is there any particular reason why this is failing? Really appreciate if someone please give pointers what's wrong here.

**Comment by lws-team** [comment]
It's failing on your platform, it doesn't fail on a very wide variety of other platforms.

Is there something funky on your larger build environment that is #defining malloc and friends globally?

**Comment by joyantamishu** [comment]
Hi @lws-team

> Is there something funky on your larger build environment that is #defining malloc and friends globally?

 I don't think so. But definitely I would re-check. But why should that be a problem, just asking :)

**Comment by lws-team** [comment]
It dies in the middle of your stdlib.h after the token "malloc".

if you have defined malloc to be something nasty at the preprocessor, that would explain how it can "know" to blow up exactly there.

Is it my problem to debug your build environment or explain anything about it though?  No.

**Comment by joyantamishu** [comment]
Thanks @lws-team
