### ISSUE TITLE
RPM creation error

### ISSUE THREAD

**Issue by cejkato2** [warmcat/libwebsockets#279]
Hi,
thanks for 26fd0d260 it is much better solution.

Unfortunately, RPM creation still failed due to some .cmake files...

Can be fixed using e.g.: https://github.com/cejkato2/libwebsockets/commit/40157c01e1407a8756b83a79de9e6abdc417a046

I'm not sure whether it can be easily merged after that reverts. Is it necessary to install those files?

Output:

    RPM build errors:
        Installed (but unpackaged) file(s) found:
       /usr/lib/cmake/libwebsockets/LibwebsocketsTargets-release.cmake
       /usr/lib/cmake/libwebsockets/LibwebsocketsTargets.cmake
    make[3]: *** [CMakeFiles/libwebsockets_rpm] Error 1```

**Comment by warmcat** [comment]
No they are not part of anything used by lws, they should not be in make install path.

Let me take a look at it, again adding them to the rpm will work around it for you for now but it's actually just wrong at cmake end now.

**Comment by warmcat** [comment]
I pushed a patch removing the CMake bit that adds them to the install.  Joakim added that I am sure he had a reason but no package on my Fedora box populates those files so unless it makes a new problem, I think better to get rid of them.
