### ISSUE TITLE
New feature request: high performance blocking ring-buffer with built-in flow-control

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#2791]
It seems to me that there is a common programming challenge faced by many users of libwebsockets and I was wondering if there is sample code to solving this challenge. Or perhaps a better approach. Or perhaps room for a new feature.

For many applications, libwebsockets single-threaded design leads to the need for ring-buffers between the single lws thread producing streams and synchronous client threads consuming them. Indeed, libwebsockets supports ring-buffers – presumably for this purpose.

Consumers may likely care about HTTP metadata such as cookies and this too can be made available over the ring-buffer.

To maintain performance, the ring-buffer should limit use of mutex, blocking, system calls, and redundant copying. We don’t want to grab a mutex every time we read a single byte from the ring-buffer.

Reading from an empty queue should block the consumer (unless error, end-of-stream, timeout) 
Writing to a full queue should “block” the producer (actually it should flowcontrol-xoff the socket since the producer thread only blocks on polling)

Unblocking should be based on low and high watermarks so as to avoid block/unblock thrashing. 

Implementing all this is tricky with plenty of gotchas in avoiding race-conditions. For example, flow control xoff in the writer happens in the lws thread context whereas xon needs to be triggered by the reader thread (presumably using lws_cancel_service).

Looking at this as an API, it would look something like this:

// note that the following functions are all MUTEX free as long as we don’t hit full/empty
// we need this so that we don’t read too much from the socket
freespace = ringbuffer.get_freespace(ringbuffer)

// if writing fills the ringbuffer, this call will xoff the associated socket
write_payload (ringbuffer, payload)
write_metadata (ringbuffer, metadata)

// if nothing in the ringbuffer, this call will block
// if call results in watermark space available in the ringbuffer, the associated socket will xon 
read(ringbuffer, &payload, &metadata)

p.s. I would have written this first to the mailing list but it is not working for me. Has the link changed?

**Comment by lws-team** [comment]
Take a look at the mirror protocol

https://libwebsockets.org/git/libwebsockets/tree/plugins/protocol_lws_mirror.c

I don't have a solution currently for the ml, mailman uses python 2 which Rocky doesn't support.
