### ISSUE TITLE
Support of SSL_ERROR_WANT_ASYNC ( Cont )

### ISSUE THREAD

**Issue by SreedharRe** [warmcat/libwebsockets#2793]
Hi,
  In continuation of https://github.com/warmcat/libwebsockets/issues/2773 , I changed the LWS code to mimic SSL_ERROR_WANT_ASYNC to SSS_WANT_READ and it is working. So have couple of questions - 

1. For our immediate use, can we change the code and use in our company builds. Basically what are the implications of GPL or licences ( because we are publishing the change and trying to incorporate into new versions of LWS ). Can we use this modified code?
2. Can you please integrate this change to new versions of LWS. We have tested normal cases works and also ASYNC case also works.

Diff :
lib/tls/openssl/openssl-ssl.c
62,67d61
<
<         if(m == SSL_ERROR_WANT_ASYNC) {
<             lwsl_debug("%s: SREE: Converting SSL_ERROR_WANT_ASYNC to SSL_ERROR_WANT_READ",__func__);
<             m = SSL_ERROR_WANT_READ;
<         }
<

Please let us know

Regards,
Sreedhar

**Comment by lws-team** [comment]
LWS is mainly MIT-licensed, the examples are cc0.  It was lgpl-2.1 with static linking exception until a few years ago.

So you can use your modifications just fine according to the license, see LICENSE in the top level dir.

Yes I will go through pending jobs in the next weeks for lws.

**Comment by SreedharRe** [comment]
Thank you.
