### ISSUE TITLE
CMakeList.txt CYASSL_INCLUDE_DIRS bug

### ISSUE THREAD

**Issue by marcin-stachowiak** [warmcat/libwebsockets#280]
There is a bug in the CMakeLists.txt in line 528.
Should be "foreach(inc ${CYASSL_INCLUDE_DIRS})" instead of "foreach(inc ${CYASSL_LIBRARIES})".

**Comment by wonder-mice** [comment]
https://github.com/warmcat/libwebsockets/pull/283

Sorry about that.
