### ISSUE TITLE
endless repeated messages after websocket connection

### ISSUE THREAD

**Issue by sackett** [warmcat/libwebsockets#2800]
Hello!

There is a non standard behavior with Kucoin exchange via wss (endless "welcome" message).
Could you take a look please? Official python API works at Kucoin (one welcome message), but libwebsockets does not. 

I have modified minimal-ws-client-binance to show this case:
https://github.com/sackett/libwebsockets/tree/main/minimal-examples-lowlevel/ws-client/minimal-ws-client-binance

wss address and public key we have to obtain with bullet-public command:

curl -d "" https://api.kucoin.com/api/v1/bullet-public > bullet-public.json
./lws-minimal-ws-client-binance

Thank you!

**Comment by lws-team** [comment]
I appreciate you made a reproducer but I don't see anything 'nonstandard' or wrong with lws in the description that makes it my problem.

If that thing is literally sending endless packets why is it anything to do with lws?

**Comment by sackett** [comment]
Thanks for reply!
There is repeated callback_minimal() with LWS_CALLBACK_CLIENT_RECEIVE reason.
I test with tcpdump and I know that Kucoin server does not send this messages.
Somehow lws could not "stop receive" it.

**Comment by lws-team** [comment]
Then does this problem exist if you disable permessage-deflate?

**Comment by sackett** [comment]
I will try it

**Comment by sackett** [comment]
> Then does this problem exist if you disable permessage-deflate?

no such problem when I turned off "permessage-deflate"

**Comment by lws-team** [comment]
I'm probably not going to look at it I'm afraid.  If you want to poke around to see what's happening on the read path I will try to help.

**Comment by sackett** [comment]
OK, thanks! If I figure something out I'll write (but I'am not so experienced in lws...).
