### ISSUE TITLE
openwrt x86 cmake error

### ISSUE THREAD

**Issue by 1163167506** [warmcat/libwebsockets#2804]
openwrt-21-x86 cmake report an error
https://downloads.openwrt.org/releases/21.02.2/targets/x86/64/
cmake: symbol lookup error: cmake: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21

**Comment by lws-team** [comment]
Hmm... this error is from building cmake itself?  Or when it builds lws?

What's the context of the error?
