### ISSUE TITLE
poll() support for client

### ISSUE THREAD

**Issue by shaohme** [warmcat/libwebsockets#2805]
Hi,

I have been experimenting with libwebsockets 4.3.2 recently, and I'm
interested in using the libwebsockets library as a client, with
my own poll() loop.

I see several examples of how to do this using libwebsockets to run as
server, but not as client.

It is supported, and am I missing something obvious?

**Comment by lws-team** [comment]
Yes lws doesn't care between one or more server and one or more client, or a mixture.

**Comment by shaohme** [comment]
It just seems like LWS_CALLBACK_ADD_POLL_FD is not called in my code even though libwebsockets is compiled with LWS_WITH_EXTERNAL_POLL.

**Comment by lws-team** [comment]
Dunno... you can try the custom event loop demo - on main - that shows how to integrate with someone else's poll() directly.

**Comment by shaohme** [comment]
well, thanks anyway
