### ISSUE TITLE
Close connection problem

### ISSUE THREAD

**Issue by marcin-stachowiak** [warmcat/libwebsockets#281]
When javascript client close connection there is a LWS_CALLBACK_SERVER_WRITEABLE callback instead of LWS_CALLBACK_CLOSED callback. On javascript client there is no onclose callback. When I close the browser then on server is LWS_CALLBACK_CLOSED callback.

As I remember before LWS_CALLBACK_CLOSED callback appear when javascript close socket and then client get onclose callback.

**Comment by cyring** [comment]
What about this js callback
```
ws.close();
```
[Here] (http://github.com/cyring/WebSocket/blob/master/http/scripts/wsclient.js) is how I've implemented it in client, and [there] (http://github.com/cyring/WebSocket/blob/master/WebSocket.c) in server.

**Comment by warmcat** [comment]
Please try current HEAD if this is still a problem foryou.

**Comment by lws-team** [comment]
I'm closing this and #306 because I think it should be fixed, if not, please reopen.
