### ISSUE TITLE
How do I start the epoll model

### ISSUE THREAD

**Issue by yangjian1851** [warmcat/libwebsockets#2811]
I compiled with LWS_WITH_LIBEVENT enabled and the libevent dynamic library path specified. How do I make sure the current libwebsockets are running in the epoll model

**Comment by lws-team** [comment]
Use the "foreign event loop" style where you create the libevent loop and pass it to lws to participate on.

Tell libevent to use epoll() if that's want you want before passing the loop to lws.  lws then doesn't get involved in anything and just uses what you gave it.

**Comment by yangjian1851** [comment]
Do you have demo code?

**Comment by lws-team** [comment]
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign
