### ISSUE TITLE
 lws_create_context: unable to load evlib plugin evlib_event

### ISSUE THREAD

**Issue by yangjian1851** [warmcat/libwebsockets#2812]
Hello, I call as follows code:
struct event_base* loop_event = event_base_new();
event_base_loop(loop_event, 0);
struct lws_context_creation_info info;
void* foreign_loops[1];
foreign_loops[0] = loop_event;
info.foreign_loops = foreign_loops;
lws_create_context(&info);

Startup Times error message:  lws_create_context: unable to load evlib plugin evlib_event

**Comment by lws-team** [comment]
Did you `make install` lws?

**Comment by yangjian1851** [comment]
I didn't make install lws, but my project did specify the lws library directory

**Comment by yangjian1851** [comment]
I didn't do make install lws, but my project did specify the lws library directory and the libevent library directory

**Comment by lws-team** [comment]
Hm... you can run it via strace to see how it really feels about that

**Comment by yangjian1851** [comment]
I want to make sure I'm using the external loop libevent the right way?

**Comment by yangjian1851** [comment]
Thank you, problem solved, copy the corresponding library to the corresponding directory

**Comment by lws-team** [comment]
Yes that's what sudo make install ought to do.  Strace would show you where lws is looking for the library.
