### ISSUE TITLE
Can lws_set_timeout() be called from a different thread? What can be called?

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#2816]
The following comment implies that lws_set_timeout() can be called "outside the callback" (i.e. in another thread).
Is this correct? Is there a full list of functions that can be called from outside of the lws thread.

#define LWS_TO_KILL_ASYNC -1
/**< If LWS_TO_KILL_ASYNC is given as the timeout sec in a lws_set_timeout()
  call, then the connection is marked to be killed at the next timeout
  check.  **This is how you should force-close the wsi being serviced if
  you are doing it outside the callback** (where you should close by nonzero
  return).
 */

**Comment by lws-team** [comment]
No, it doesn't imply that.  You may be outside the callback on the same thread depending on your loop arrangements.

See https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md
