### ISSUE TITLE
How to deal with assertion in `_lws_route_get_uidx`?

### ISSUE THREAD

**Issue by jin-eld** [warmcat/libwebsockets#2819]
Hi,

I have a setup where the network can get reconfigured at runtime (the system is running NetworkManager). Once in a while my application which uses libwebsockets runs into the following error:
```
/usr/src/debug/libwebsockets/4.2.2-r0/git/lib/core-net/route.c:117: _lws_route_get_uidx: Assertion `0' failed.
```

I am not sure if I understand the code in route.c correctly, but wouldn't it be a valid scenario that the routing table changes on the fly which would mess up what `_lws_route_get_uidx` is doing? This does not sound like an lws bug, rather like something that can just happen, so why the assert? Or am I misunderstanding it?

I figured, OK, the case is handled (there is a `return 0` in there), so I looked if I could disable asserts, but I saw that they are already disabled?

`component.mk:	cmake $(COMPONENT_PATH)  -DLWS_C_FLAGS="$(CFLAGS) -DNDEBUG=1" \`

Still, the assert is happening... what am I missing?

At this point I am not entirely sure how to proceed, so some guidance would be highly appreciated.

Kind regards,
Jin

**Comment by lws-team** [comment]
The routing table is tracked by netlink.  This tells us about events kernelside like routing changes synchronously through a socket.  So things can only be understood to have changed when the netlink socket is serviced, ie, synchronous to the event loop.

Are you actually using component .mk?  Or you just randomly noticed it in the tree?  You would normally use cmake with -DCMAKE_BUILD_TYPE=RELEASE to nuke asserts.

**Comment by jin-eld** [comment]
I grepped for `NDEBUG`, so you got a point there - it was a wrong assumption on my side, I will look into the cmake parameter. I am cross compiling using Yocto, I guess they did not configure a "RELEASE" build by default.

So your suggestion would be to get rid of asserts and leave it alone otherwise, i.e. it would be safe to do so?

**Comment by lws-team** [comment]
You wanted to turn off asserts... that's how.

Yocto is using the last stable release which is quite behind main branch.  I would munge the recipe to use current main and see if the problem goes away.

Another possibility is turn off netlink with LWS_WITH_NETLINK=0

**Comment by jin-eld** [comment]
Thank you for the pointers, I have several things that I could try now.

How stable is the main branch, i.e. is it safe to use in a production environment?

**Comment by lws-team** [comment]
It's generally in good shape, but like the license says, there's no warranty.
