### ISSUE TITLE
lws_close_free_wsi() Interface usage

### ISSUE THREAD

**Issue by yangjian1851** [warmcat/libwebsockets#2820]
Hello, I want to do a timeout to the front end at the server side. After the front end connects to the server, no message from the front end is received within 5 minutes, so I will disconnect voluntarily. Can you use lws_close_free_wsi interface

**Comment by lws-team** [comment]
No, that's an internal function you can't call from a callback.  It will probably destroy the wsi, but if you are in the callback, the parent caller may still hold references to the wsi.  It's why it isn't exported.

There's a helper lws_wsi_close()

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-timeout-timer.h#n121-122

which uses the timeout stuff to close the wsi shortly afterwards, not immediately, and not from the callback, although it is safe to call the helper from there.
