### ISSUE TITLE
a callback LWS_CALLBACK_SERVER_WRITEABLE

### ISSUE THREAD

**Issue by yangjian1851** [warmcat/libwebsockets#2821]
Hello, I found that after the client connected to the service, every five minutes to a callback LWS_CALLBACK_SERVER_WRITEABLE, this time can be set by what interface

**Comment by yangjian1851** [comment]
My purpose is to periodically detect whether the client is active, inactive client server take the initiative to disconnect it

**Comment by lws-team** [comment]
f it is websocket protocol, lws will send PINGs at intervals to confirm the connection is workable.

You can control it with, eg, https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-server/minimal-ws-server-timer/minimal-ws-server.c#n56

After sending a PING, there's uncertainty about if we used up a requested write, so we add a requested write each time.
