### ISSUE TITLE
The call interface lws_set_timeout(wsi, PENDING_TIMEOUT_CLIENT_CONN_IDLE, 1) crashed

### ISSUE THREAD

**Issue by yangjian1851** [warmcat/libwebsockets#2822]
I wanted to actively close some inactive connections. Using the lws_set_timeout(wsi, PENDING_TIMEOUT_CLIENT_CONN_IDLE, 1) interface, the program crashed. The stack information is as follows:

#0  0x00007f4b342282f0 in lws_dll2_remove (d=0x1922ba0) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/core/lws_dll2.c:148
#1  0x00007f4b3423e3a7 in lws_set_timeout (wsi=0x1922a90, reason=PENDING_TIMEOUT_CLIENT_CONN_IDLE, secs=1) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/core-net/wsi-timeout.c:147
#2  0x000000000046e40c in ServerMgr::OnWsReceiveData (this=0x1917f50, wsi=0x1963650, 
    data=0x192612e "{\"op_id\":0,\"open_id\":\"jQXG1673959144853274\",\"item_id\":135,\"course_id\":4391}ade\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, l"..., len=75) at /home/yangtongyu/server/doctor/lbgs/src/servermgr_ws.cpp:94
#3  0x000000000049281a in wsServer::callback_server (wsi=0x1963650, reason=LWS_CALLBACK_RECEIVE, user=0x19246e0, in=0x192612e, len=75) at /home/yangtongyu/server/doctor/lbgs/src/ws/wsServer.cpp:76
#4  0x00007f4b3423beef in user_callback_handle_rxflow (callback_function=0x49255e <wsServer::callback_server(lws*, lws_callback_reasons, void*, void*, size_t)>, wsi=0x1963650, 
    reason=LWS_CALLBACK_RECEIVE, user=0x19246e0, in=0x192612e, len=75) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/core-net/wsi.c:303
#5  0x00007f4b3426287f in lws_ws_frame_rest_is_payload (wsi=0x1963650, buf=0x7fffc9c96210, len=0) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/roles/ws/server-ws.c:970
#6  0x00007f4b342629ce in lws_parse_ws (wsi=0x1963650, buf=0x7fffc9c96210, len=75) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/roles/ws/server-ws.c:1052
#7  0x00007f4b342500ca in lws_read_h1 (wsi=0x1963650, 
    buf=0x1926179 "ade\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 NetType/WIFI MicroMessenger/7"..., len=81) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/roles/h1/ops-h1.c:243
#8  0x00007f4b3425e178 in rops_handle_POLLIN_ws (pt=0x1925d00, wsi=0x1963650, pollfd=0x7fffc9c96340) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/roles/ws/ops-ws.c:1184
#9  0x00007f4b3423ab43 in lws_service_fd_tsi (context=0x1925ac0, pollfd=0x7fffc9c96340, tsi=0) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/core-net/service.c:719
#10 0x00007f4b3398c1aa in lws_event_cb (sock_fd=17, revents=2, ctx=0x1963998) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/event-libs/libevent/libevent.c:142
#11 0x00000000004b1885 in event_process_active_single_queue ()
#12 0x00000000004b436f in event_base_loop.clone.6 ()
#13 0x00007f4b3398c8b0 in elops_run_pt_event (context=0x1925ac0, tsi=0) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/event-libs/libevent/libevent.c:322
#14 0x00007f4b3423acaf in lws_service (context=0x1925ac0, timeout_ms=0) at /home/yangtongyu/server/3rdparty/libwebsockets-4.1-stable/lib/core-net/service.c:782

**Comment by lws-team** [comment]
This kind of thing is usually because the wsi you stored somewhere in your code, are already closed and destroyed.  Then you try to use the dead wsi.

Any wsi can close any time you return to the event loop.  Any socket can close at any time from either side whether you expect it or not.  So if you will keep hold of wsi pointers,you must take care to watch CLOSE or similar callbacks on those wsi and clean your list when they are done.

Valgrind is very good for giving you insight into this kind of heap problem.

**Comment by yangjian1851** [comment]
Thank you for your answer. I just cleaned the callback in LWS_CALLBACK_WSI_DESTROY, do I need to clean it in LWS_CALLBACK_CLOSED

**Comment by lws-team** [comment]
Dunno, since the backtrace shows you're using a different wsi when it crashes than the callback came in on (which should exist OK) I can guess it's a dead pointer, that's all.

Valgrind can show you in detail when it became dead, it could be a long time before.

**Comment by yangjian1851** [comment]
I mean my code is just cleaning up the LWS_CALLBACK_WSI_DESTROY callback, is it possible that the front-end disconnect is just taking the LWS_CALLBACK_CLOSED callback? Instead of going to the LWS_CALLBACK_WSI_DESTROY callback

**Comment by lws-team** [comment]
Dunno.  Valgrind can tell you what's up with your actual code I don't have, which is a much better kind of information than my 2am guesses about sequencing of a big codebase I wrote 12 years ago, while having no info about your code.

**Comment by yangjian1851** [comment]
Salute the great God
