### ISSUE TITLE
Using LWS to service a single socket/ No listing for new connections.

### ISSUE THREAD

**Issue by cygnuson** [warmcat/libwebsockets#2823]
Hello Team! Great work on LWS btw its been a great library!

I currently exec* or fork a process with an orphaned FD and ask LWS to adopt it.  It appears that using **zero** for the **port** on the `lws_context_creation_info` object allows LWS to service the orphaned FD without listening for new connections.   By having **zero** for the port number, I am able to run multiple process without issue and **without** `LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE`

Is this a valid use case? 

I am using v4.3, and its documentation doesn't appear to have any info on the 'port' member of the `lws_context_creation_info`
doc: https://libwebsockets.org/lws-api-doc-v4.3-stable/html/structlws__context__creation__info.html
also: Compiled with default options except IPv6 support enabled.

**Comment by lws-team** [comment]
Yes... although `CONTEXT_PORT_NO_LISTEN` as the port will be better.

**Comment by cygnuson** [comment]
Thanks for the quick answer!
