### ISSUE TITLE
unable to get HANDSHAKE_TRAFFIC_SECRET in SSLKEYLOGFILE

### ISSUE THREAD

**Issue by shubhangikhandekar** [warmcat/libwebsockets#2833]
Hi,

I am trying to get new session key/ticket after session timeout. 

The by deafult  tls_session_timeout is 300s however, I am getting new session ticket after 2 hours (i.e. ssl_session_timeout default value). Also, i have observed that the SSLKEYLOGFILE is not updated even after 2 hours.

I am using main branch main branch https://github.com/warmcat/libwebsockets to get SSLKEYLOGFILE

 I have requirement to modify the tls_session_timeout and get SSLKEYLOGFILE updated whenever new session created.

**Comment by lws-team** [comment]
> I have requirement to modify the tls_session_timeout and get SSLKEYLOGFILE updated whenever new session created.

Well, I don't have that requirement.  So I guess you need to patch it.
