### ISSUE TITLE
what does [wsicli|0|WS/h1/default/wsaws.okx.com]: lws_client_ws_upgrade: got bad HTTP response '404' mean?

### ISSUE THREAD

**Issue by arockiereborn** [warmcat/libwebsockets#2837]
libwebsockets is great!

but i got "[wsicli|0|WS/h1/default/wsaws.okx.com]: lws_client_ws_upgrade: got bad HTTP response '404'" when i want to build connection with websocket server.

could you let me know what error does this mean?

is there anything i should check?

lws_client_connect_info i have checked many times.

**Comment by lws-team** [comment]
Server sent you a 404.

Check what you are actually sending the server if it's unexpected.  Eg -DLWS_TLS_LOG_PLAINTEXT_TX=1 at cmake.

**Comment by 123zhj** [comment]
I have a problem "[2024/05/21 17:44:57:5382] W: [wsicli|e|WS/h1/default/m-579da5db.kinesisvideo.ap-southeast-1]: lws_client_ws_upgrade: got bad HTTP response '403'
2024-05-21 17:44:57.538 WARN    lwsWssCallbackRoutine(): Client connection failed. Connection error string: HS: ws upgrade response not 101"
I don't know how to solve this problem.

**Comment by lws-team** [comment]
Server sent you a 403... follow the advice above and see what you're actually sending it.  It's probably complaining for lack of auth, or other missing or wrong header and decides it won't talk to you.
