### ISSUE TITLE
Is there any way to check the tls version at receiving end?

### ISSUE THREAD

**Issue by Paramveer24b** [warmcat/libwebsockets#2839]
I have client and server communication

I want to fetch client's tls version at server side when i received any packet inside lwscallback function

There is a function `SSL_CTX_get_options() `which will give me all options of the tls but its not useful in my scenario.

So is it even possible to know client's tls version at server side ? or vice versa ?

**Comment by lws-team** [comment]
That's a question about openssl, not lws.

https://www.openssl.org/docs/man1.1.1/man3/SSL_get_version.html

**Comment by Paramveer24b** [comment]
Thanks for the input

I am getting unresolved external symbols for above functions.
I tried to build libwebsocket 

cmake -G "NMake Makefiles" -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_SSL_SERVER_WITH_ECDH_CERT=1 -DLWS_WITH_SSL=1 -DLWS_WITH_NETWORK=1 -DCMAKE_BUILD_TYPE=RELEASE -DSSL_EAY_DEBUG="C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.LIB" -DSSL_EAY_RELEASE="C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib" -DOPENSSL_ROOT_DIR="C:\\\\Program Files\\\\OpenSSL-Win64" -DCMAKE_INSTALL_PREFIX="C:\\\\Program Files\\\\libwebsockets" ..


libwebsocket has these functions inside libwebsockets-4.3.2\lib\tls\mbedtls\wrapper\library\ssl_lib.c

but how to access those?

**Comment by lws-team** [comment]
Lws isn't stopping you linking to openssl or nothing could work.

Openssl manpage says SSL_get_version introduced in 1.1.0 - so how old is your openssl?

**Comment by Paramveer24b** [comment]
my openssl version is :-  OpenSSL 1.1.1k

**Comment by Paramveer24b** [comment]
issue resolved now... I just needed to link openssl explicitly in cmake..

I thought it will automatically get included by libwebsocket.

But its resolved now.. no linking error.
