### ISSUE TITLE
lws_protocols protocols *user not return in callback?

### ISSUE THREAD

**Issue by arockiereborn** [warmcat/libwebsockets#2840]
I pass a pointer into lws_protocals when construct, i expected this pointer return in callback.

here is the contruct code:
`struct lws_protocols protocols[] = {{"depth", &event_cb, 4096, 65536, 1, &conn_map}, {NULL, NULL, 4096, 0, 3, NULL}};
printf("%p\n", &conn_map);`

`conn_map `is a `std::unordered_map` object

this the callback function:
```
int WsBase::event_cb(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
  std::unordered_map<lws*, ConnData>* conn_map = (std::unordered_map<lws*, ConnData>*)(user);
  INFO("c:%p\n", user);
}
```

i found the printed address of user is not same, could you help on this?

**Comment by lws-team** [comment]
callbacks also get events that are not related to any particular wsi, but related to the event loop or system.  In those cases a fake wsi is used so you can still get access to, eg, lws_context from it.  But there won't be any protocol and that's legal.
