### ISSUE TITLE
debian package version outdated

### ISSUE THREAD

**Issue by mhaberler** [warmcat/libwebsockets#285]
www.machinekit.io uses libwebsockets, and so far we've built our own debian package since we rely on a newer API version than what is available stock: https://github.com/zultron/libwebsockets-deb

eventually we'd like to switch to a stock debian libwebsockets package, which would require upgrading what is there  - https://tracker.debian.org/pkg/libwebsockets is over two years old

I would be grateful for suggestions how to address this issue

**Comment by ralight** [comment]
I made my own version of an updated debian package without realising you'd made a start on it. My copy is at https://github.com/ralight/libwebsockets-debian

I've emailed the debian maintainer about it and if he doesn't respond will be trying to get it uploaded another way.

I'd respectfully point out that your package has some regressions - you've dropped Multi-Arch support but still report it as being supported, and you've not updated the shared library package SO version to match the 1.4 release. These both have the potential to cause big problems.

**Comment by saghul** [comment]
@ralight Thanks for putting it together, much appreciated! :+1:

**Comment by ralight** [comment]
There is a bug for getting the package updated here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794476

**Comment by ralight** [comment]
This has been making progress, the debian maintainer has done a load of updates and sent some minor patches to the list:

http://ml.libwebsockets.org/pipermail/libwebsockets/2015-October/001901.html

Hopefully it will be uploaded soon.

**Comment by ralight** [comment]
Thanks to Peter Pentchev, Gianfranco Costamagna and László Böszörményi there is now an updated package for debian in the unstable distribution:

https://packages.qa.debian.org/libw/libwebsockets/news/20151221T215622Z.html

If there are no problems, this should migrate to the testing distribution (stretch) before the new year.

I think that means this issue can be closed.

**Comment by lws-team** [comment]
Thanks a lot guys.
