### ISSUE TITLE
why the websocket connection silence closed?

### ISSUE THREAD

**Issue by dotkt** [warmcat/libwebsockets#2850]
i write a simple callback client,connec to gate.io to get account info.
the connection is succ. and i register account info succ :
![图片](https://user-images.githubusercontent.com/49758966/226161006-e1d09fdd-c479-497f-837f-448f84235129.png)

but ,when the sever sends me account info, the connection will break!
i have no idea why this happen.
![图片](https://user-images.githubusercontent.com/49758966/226161095-96f9c73f-1846-495d-9d50-28b12ac42ece.png)

![图片](https://user-images.githubusercontent.com/49758966/226161020-6a95b487-e1a9-4f80-9d61-14a4c9acf446.png)

**Comment by lws-team** [comment]
There's a lot of logging produced by lws to tell you how it feels about stuff... you're ignoring everything and wondering why you don't know what is happening.

**Comment by dotkt** [comment]
thanks for reply ,but i check many reason code,cant figure out what is the reason.pls give me a glue. 

I found that if I send data packets to the server and the server responds with data packets, the program can receive packets normally and the connection will not be interrupted. But if the server actively pushes data, the connection will be interrupted.

![图片](https://user-images.githubusercontent.com/49758966/226163330-0f75b4ba-c0fa-4550-a247-0d2aeecf3f8e.png)

**Comment by dotkt** [comment]
i found i have received  the packet,but just part of it ,then the connection breaks.
![图片](https://user-images.githubusercontent.com/49758966/226163779-0d271ec9-4fa9-4c5f-a930-fac903842d5b.png)

**Comment by dotkt** [comment]
well,i "fixed" it .now it works.but i dont really understand it .can you please explain it to me?
![图片](https://user-images.githubusercontent.com/49758966/226164025-8ecfcb5b-1ab8-4fc6-b7b8-78152e8b8cda.png)

**my solve way: change the receive buffer from 5 bytes to 5000 bytes.**
![图片](https://user-images.githubusercontent.com/49758966/226164044-e5dc5739-0227-4c6a-99da-1757d4da7472.png)

**Comment by dotkt** [comment]
actually ,according to the solve way ,i think it may be a bug.
