### ISSUE TITLE
E: accept: errno 24 (too many open files)

### ISSUE THREAD

**Issue by alien999999999** [warmcat/libwebsockets#2852]
After my app is running for like more than a month, i suddenly have this error, and i'm wondering if i need to do anything specific for closing disconnections... maybe something stays open that didn't get closed?

**Comment by lws-team** [comment]
Use `lsof` <pid> to find out what those things that are lying around are open on

https://linux.die.net/man/8/lsof

**Comment by alien999999999** [comment]
netstat claims them udp6 sockets, so likely not lws-related, since i'm using websockets on tcp for this

**Comment by lws-team** [comment]
... tcp runs over ipv6 just fine, they are not somehow mutually exclusive.

There's too many eyes on lws for it to leak internally easily nowadays, it's extremely likely to be other code in the same process doing it... your callback code or something totally unrelated to lws that just happens to be in the same pid.

**Comment by alien999999999** [comment]
I said **udp6**, not **ipv6** :-)

It could've been my fault by using it wrong or forgetting to release something, but it's another thing within the same process which starves lws for open files (likely)
