### ISSUE TITLE
Websocket is not reconnecting in retry with GSM Interface

### ISSUE THREAD

**Issue by Ap040** [warmcat/libwebsockets#2863]
Hello,
We have used v4.3-stable branch for our use and we are able to retry using Wifi and Ethernet. However, while we are using the same with the GSM interface, it is not reconnecting to our WebSocket server.
Below are the debug logs for your reference. first portion of logs, are successful connections, and after that for disconnection logs.

Our system Details: Linux phyboard-segin-imx6ul-2 4.14.93-bsp-yocto-i.mx6ul-pd19.1.0 #1 SMP Fri Mar 17 04:49:40 UTC 2023 armv7l GNU/Linux

[gsm_con_discon.txt](https://github.com/warmcat/libwebsockets/files/11176807/gsm_con_discon.txt)

**Comment by lws-team** [comment]
I would guess it's related to netlink on that interface for whatever reason.  You can try disabling it with -D LWS_WITH_NETLINK=0 or try main branch and see if that helps.

**Comment by Ap040** [comment]
Hello LWS-Team,
Thanks for the quick replay, as per my research I got this may be there is a Netlink issue and for this, I have modified my .bb file with -DLWS_WITH_NETLINK=OFF. It didn't work for me. I have one doubt regarding changes like at which option I should need to enable it as so many options are available in .bb to add option -DLWS_WITH_NETLINK=OFF.

![image](https://user-images.githubusercontent.com/78598609/230571765-1d44cf4b-0662-42be-ad6c-c184c6cca8b7.png)

**Comment by lws-team** [comment]
This isn't an lws thing but a yocto thing.

You can stick it at the beginning of `EXTRA_OECMAKE` definition to get it always applied.  The others are dependent on what packageconfig options you have on or off.

**Comment by Ap040** [comment]
Hello Team,
Thanks for your reply.
Let me try and check as per your suggestion.

**Comment by Ap040** [comment]
Hello,
I changed in .bb file as per the below screenshot. Now, it is working as a connection up-and-down scenario.

![image](https://user-images.githubusercontent.com/78598609/230581141-f25fee2d-bbf3-4156-9e4a-77f14cda5b19.png)
