### ISSUE TITLE
Websocket client not able to receive data

### ISSUE THREAD

**Issue by bpsinghtech** [warmcat/libwebsockets#2866]
Hi, 
I am facing one bizarre issue that is I have a websoket client ( based on websocket library version 3.1.0) is not able to receive data from server. Same code was working when I was using websocket library 1.2. But after upgrade to version 3.1.0, I am seeing this issue. 
After upgrading to Libwebsocket to 3.1.0, using lws_client_connect_via_info() API to connect with server. Connection is successful.
Client is sending message to sever, server receives the message and in response it send 3-4 messages to client, these messages reaching to client IP interface (checked using wireshark) but not reaching to client daemon.

Another thing, not seeing any websocket debug log after upgrade. With 1.2 I was getting websocket logs.
using below API to set log level
lws_set_log_level(LLL_CLIENT|LLL_DEBUG|LLL_ERR|LLL_NOTICE|LLL_INFO, libwebsocket_log);
There is no firewall rules configured on client side which can filter the data.
Could you help on this.

**Comment by lws-team** [comment]
> libwebsocket_log

is that log handler actually getting called?

> these messages reaching to client IP interface (checked using wireshark) but not reaching to client daemon.

1.2 is literally from 10 years ago... back then at some point client and server callbacks were split out, you need `LWS_CALLBACK_CLIENT_RECEIVE`.  Check the minimal examples dir in v3.1 for clues.

**Comment by bpsinghtech** [comment]
Hi,

Thanks for your response.

> > libwebsocket_log
>> is that log handler actually getting called?
>
I could see log handler is getting called and could see 2 different logs also.
2023-04-12 07:47:05:LWS: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
2023-04-12 07:47:05:LWS: created client ssl context for default


>> 1.2 is literally from 10 years ago... back then at some point client and server callbacks were split out, you need `LWS_CALLBACK_CLIENT_RECEIVE`. Check the minimal examples dir in v3.1 for clues.
>
I have verified my code and I am using LWS_CALLBACK_CLIENT_RECEIVE in callback. Checked minimal exmaple code also in 3.1 and matched it with my code, I don't see any difference.

When it was working I was using websocket library 1.2 which uses TLS 1.2,
now I have moved to websocket lib 3.1 which uses TLS 1.3. 

This might be related to TLS version ?

**Comment by bpsinghtech** [comment]
Thank you for quick response.

> These are printing OK then?
>
> The logging stuff changed underneath after v3.1 but not before AFAIK. Perhaps you accidentally set "LWS_WITH_NO_LOGS"?
> 
> You'll have to trace what happens to the logging apis in your build.

Checked library code both prints are "NOTICE" only. It means log level I am setting from my code is not effective. 
> > LWS_CALLBACK_CLIENT_RECEIVE
> 
> Is this callback perhaps going to the wrong protocol? You can grep lws for where that is called and print protocol->name to see.

So you mean in library code I need to put logs ? but since logs are not getting printed, won't be able to see them. 

> > This might be related to TLS version ?
> 
> No, but in later lws you have to tell it you will use the tls library if you want to use tls, this is to stop problems where more than one thing in the process thinks it's his job to initialize the library. Eg some other library linked in also knows about tls and initializes it. So you need something like `info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;` now. Later openssl doesn't blow up any more if it happens.

Ok. will try this one.

**Comment by lws-team** [comment]
You can just use printf() or puts() in lws.

**Comment by bpsinghtech** [comment]
Hi,

One more thing I want to highlight I could see packets in receive queue increasing:
tcp      207     0 10.110.217.8:37264      10.110.134.252:443      ESTABLISHED 15294/dev-ca
tcp      315     0 10.110.217.8:37264      10.110.134.252:443      ESTABLISHED 15294/dev-ca

Any clue around it what I might be missing ?

**Comment by bpsinghtech** [comment]
Hi,

Able to fix this issue. used lws_service() to receive this packet. I had added it but not at right place in code. After moving it at right place in code, it worked.

So I have one question, is it mandatory to use this API lws_service() in 3.1 because in 1.2 it was not in code ?
