### ISSUE TITLE
LWS_CALLBACK_CLOSED is never called

### ISSUE THREAD

**Issue by maxmarsc** [warmcat/libwebsockets#2881]
*First of all sorry if this post is a bit of a mess, it's my first time working with websocket, and I'm having a hard time learning lws. I tried to make it as clear as possible*

I'm trying to write a dead simple ws client that write simple messages to a ws server. So far no security of any kind is needed, so because I don't wanna have to embed a JSON file I went to use the "low-level" API previous to Secure Streams.

---

The client workflow is the following :
 1. A dedicated pthread monitors a data queue. When enough data is available, it aggregates the data, write it to a structure, and schedule a write call using `lws_callback_on_writable`
 2. When the lws callback is called, it reads the structure (thread safe), serialize it and send it over the connection using `lws_write`
 
On the server side, I tried both Python and LWS but the idea is the same : when it receives a message, it prints it.

 ---
 
I've written a test, to first monitor how things goes, the workflow of the test is the following :

0. start a ws server on `localhost:9000` (either manually or in the test code itself)
1. Start the ws client, check it connects with the server (by waiting for `LWS_CALLBACK_CLIENT_ESTABLISHED`)
2. Fill the data queue with values
3. Wait a bit, in the background the client should notice the queue has enough data so it should schedule a write
4. Destruct the client object, which should close the connection.

The way I close the connection is : my client have an `std::atomic_bool should_stop_` flag that I set to true. When `LWS_CALLBACK_CLIENT_WRITEABLE` happens, the flag is read, if set to true the callback returns `-1` to signal the connection should close. Then I wait for the callback to be called with `LWS_CALLBACK_CLOSED` and then stop.

In practice, here is what happens :
 1. first `lws_service` called into my client thread takes **ages** to run, I don't why. I though this was a non blocking operation (what is the point of having an event loop if operations are blocking ? I've read both [lws_sul README](https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md) and [Considerations around Event Loops](https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md) but I couldn't understand why)
 2. It take so long (>20s) than most of the time the flag `should_stop` is set before the first `LWS_CALLBACK_CLIENT_WRITEABLE` callback happens. (sometimes it happens after, but that does not change the ending)
 3. After a long time a `LWS_CALLBACK_CLIENT_WRITEABLE` is called, checks the atomic flag, return -1
 
 Then, nothing
 
 My main client thread is waiting on a `lws_service` loop for the connection to close, but `LWS_CALLBACK_CLOSED` is never called.
 
 Would anyone know what I'm missing ?
 
 ---
 Here is some snippet of my code to help understand better :
 
 Client init :
 ---
 ```cpp
  [[nodiscard]] int init(utils::LockFreeQueue<NumClasses>& queue,
                         Parameters& parameters) {
    PORTABLE_ASSERT(status_ == Status::kEmpty);
    INIT_CHECK(this->initAggregator(2) == 0);
    this->initQueue(queue);
    should_stop_                   = false;
    serialization_function_        = parameters.serialization_function;
    aggregate_result_.is_available = false;

    // Create the LWS protocol
    protocols_[0] = lws_protocols{wsProtocolName().data(),
                                  lwsCallback,
                                  0,
                                  0,
                                  0,
                                  static_cast<void*>(this),
                                  0};

    // Prepare to create the LWS context
    auto context_creation_info      = lws_context_creation_info{};
    context_creation_info.port      = CONTEXT_PORT_NO_LISTEN;
    context_creation_info.protocols = protocols_;
    context_creation_info.gid       = -1;
    context_creation_info.uid       = -1;

    // Create the LWS context
    context_ = lws_create_context(&context_creation_info);
    if (context_ == nullptr)
      return 1;

    // Prepare the client connection
    auto client_connect_info     = lws_client_connect_info{};
    client_connect_info.context  = context_;
    client_connect_info.address  = parameters.server_adress.data();
    client_connect_info.port     = parameters.port;
    client_connect_info.path     = parameters.path.data();
    client_connect_info.host     = lws_canonical_hostname(context_);
    client_connect_info.origin   = "origin";
    client_connect_info.protocol = protocols_[0].name;

    // Connect the client
    instance_ = lws_client_connect_via_info(&client_connect_info);
    if (instance_ == nullptr)
      return 2;

    // Start the thread routine
    status_.store(Status::kConnecting);
    INIT_CHECK(this->initThread(threadRoutine, this) == 0);

    // Wait for the connection to establish or fail
    while (status_ == Status::kConnecting) {
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    // Check if connection succeeded
    PORTABLE_ASSERT(status_ == Status::kConnected ||
                    status_ == Status::kFailed);
    if (status_ != Status::kConnected) {
      should_stop_            = true;
      [[maybe_unused]] auto _ = this->joinThread();
      return 3;
    }

    return 0;
  }
 ```
 
 Client thread routine :
 ---
 ```cpp
   static void* threadRoutine(void* args) {
    auto* exporter = reinterpret_cast<This*>(args);

    while (!exporter->should_stop_.load()) {
      lws_service(exporter->context_, 0);
      if (!exporter->queue_->empty()) {
        // Feed the aggregator with data from the queue
        auto aggregator_is_full = exporter->aggregateFromQueue();
        if (aggregator_is_full) {
          // If enough data has been aggregated, we can send a message
          auto result_is_exportable = exporter->consumeAggregateIfPossible();
          if (result_is_exportable)
            lws_callback_on_writable(exporter->instance_);
        }
      }
    }


    if (exporter->status_ == Status::kConnected)
      exporter->waitForConnectionClose();

    lws_context_destroy(exporter->context_);
    return nullptr;
  }
 ```
 
 The client callback :
 ---
 ```cpp
 static int lwsCallback(lws* wsi, lws_callback_reasons reason, void*, void*,
                         size_t) {
    switch (reason) {
      case LWS_CALLBACK_CLIENT_ESTABLISHED: {
        // Connection is established
        auto* exporter = getExporterFromInstance(wsi);
        exporter->status_.store(Status::kConnected);
        break;
      }
      case LWS_CALLBACK_CLOSED: {
        // Connection is closed
        auto* exporter = getExporterFromInstance(wsi);
        exporter->status_.store(Status::kStopped);
        return -1;
        break;
      }
      case LWS_CALLBACK_CLIENT_CONNECTION_ERROR: {
        // Failed to establish connection
        auto* exporter = getExporterFromInstance(wsi);
        exporter->status_.store(Status::kFailed);
        break;
      }
      case LWS_CALLBACK_CLIENT_WRITEABLE: {
        // Received a callback for data export
        auto* exporter = getExporterFromInstance(wsi);
        if (exporter->should_stop_)
          return -1;
     
        PORTABLE_ASSERT(exporter->status_.load() == Status::kConnected);
        PORTABLE_ASSERT(exporter->aggregate_result_.is_available);
        unsigned char msg_buffer[LWS_PRE + maxMsgSize()];
        auto msg_size = exporter->serializeAggregateResult(
            reinterpret_cast<char*>(msg_buffer));
        lws_write(wsi, &msg_buffer[LWS_PRE], msg_size, LWS_WRITE_TEXT);
        break;
      }
      default: {
        // Nothing to do
        break;
      }
    }

    //TODO: add error handling
    return 0;
  }
 ```
 
 And the function where it waits for the connection to close :
 ```cpp
 void waitForConnectionClose() {
    PORTABLE_ASSERT(status_ == Status::kConnected);
    // We make sure the callback is called at least once to acknowledge the
    // should_stop_ flag
    lws_callback_on_writable_all_protocol(context_, protocols_);

    while (status_ == Status::kConnected) {
      lws_service(context_, 0);
    }

    PORTABLE_ASSERT(status_ == Status::kStopped);
  }
 ```

Maybe worth noticing the `status_` variable is also stored in an atomic lock-free variable.

**Comment by lws-team** [comment]
`LWS_CALLBACK_CLIENT_CLOSED`?
