### ISSUE TITLE
Why does sample program call lws_cancel_service(lws_get_context(wsi)); after callback events ???

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#2886]
In minimal-http-client/minimal-http-client.c:

lws_cancel_service(lws_get_context(wsi)); is called after: 

if (!lws_client_connect_via_info(&i))
LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
LWS_CALLBACK_COMPLETED_CLIENT_HTTP:
LWS_CALLBACK_CLOSED_CLIENT_HTTP:

Why? Should my program do this too? Seems redundant (if we are in the callback then we are not in the poll so why exit the poll)?

**Comment by lws-team** [comment]
> so why exit the poll)?

This was to do with either non-socket communication (eg, using UART or SPI to transfer the data case) or workaround for staged context destroy on some weird event loop.  Either way I don't think you need to follow it for more normal operation.
