### ISSUE TITLE
Facing SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=0)

### ISSUE THREAD

**Issue by Paramveer24b** [warmcat/libwebsockets#2888]
I am trying to connect with server but after initialization of client I am facing below error

 D: lws_client_create_tls: lws_ssl_client_connect1: 0
 E: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=0)

Cli connection failed with reason: server's cert didn't look good,  X509_V_ERR = 20: error:00000014:lib(0):func(0):reason(20)

I am facing this issue first time.
Is there anything I am missing ?

**Comment by lws-team** [comment]
The client is missing an intermediate certificate.  If the server has non well-known certificates in its chain, for good compatibility, it should provide them in its response along with the server's own certificate.  Eg, if the server's chain is like `[ well-known CA cert ] -> [ funky intermediate cert ] -> [ server cert ]` and your server only sends `[ server cert ]`, it might be that while your client does trust `[ well-known CA cert ]` OK, and the server gave it `[ server cert ]`, it simply doesn't have a copy of `[ funky intermediate cert ]`.  Your server should send both the server cert and any intermediates that may be needed to confirm the server cert is signed by something signed by a trusted CA, concatenated together.
