### ISSUE TITLE
lws_write crash with unknown error

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#2891]
I am using `libwebsockets `to do websockets in cpp.

it's very convenient to use and stable.

but recently i got unknown crash on `lws_write `function. the `gdb `info is:

```
(gdb) where
#0  0x00007fa979025ae7 in lws_write () from /usr/local/lib/libwebsockets.so.19
#1  0x00007fa9792ae839 in WsBase::send_request (wsi=wsi@entry=0x24b26c0, req="{\"id\":\"123\", \"op\":\"find\", \"args\":[{\"clOrdId\":\"ALL0\"}]}")
    at /root/ws_base.cpp:27
```

the send_request function is here:
```
void WsBase::send_request(struct lws *wsi, const std::string& req) {
  if (req.empty()) return;
  printf("%p Sending Request %s\n", wsi, req.c_str());
  uint8_t buf[LWS_PRE + 4096] = {0};
  size_t rsize = lws_snprintf((char*)buf + LWS_PRE, sizeof(buf) - LWS_PRE, "%s", req.c_str());
  size_t m = lws_write(wsi, buf + LWS_PRE, rsize, LWS_WRITE_TEXT);
  if (m < rsize) perror("BAD\n");
}
```

the call is: `send_request(wsi, "{\"id\":\"123\", \"op\":\"find\", \"args\":[{\"clOrdId\":\"ALL0\"}]}")`

I checked the log, which shows the connection is alive and no other message.

is there anything i should check before it do lws_write?

thanks a lot!

**Comment by lws-team** [comment]
You cannot just call lws_write().  You must call lws_callback_on_writable(), and call lws_write() from the WRITEABLE callback.

You need to take the approach to keep state in the wsi, and when perhaps immediately after returning to the event loop, or perhaps much later, you have an opportunity to write in WRITEABLE callback, figure out from the state what it is that needs to be sent and send it.  If more must be sent, ask for another callback_on_writable() on the wsi before returning from WRITEABLE.
