### ISSUE TITLE
why i shall call lws_write after lws_callback_on_writable()?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#2897]
i know the correct call `lws_write `should be after `lws_callback_on_writable`

but i do care about the latency, i think in 99.9% situation, just call `lws_write `works.

so, could you let me know why i should call `lws_callback_on_writable()` first, what does it do?

and will it slow down the `lws_write `because need to callback?

thanks a lot

**Comment by lws-team** [comment]
> i think in 99.9% situation, just call lws_write works.

... you have written your code to act like it's threaded / blocking, but actually, it's async and a participant on an event loop.  The time your thread would have been stalled by write() that cannot send yet, unscheduled and dead to the world, the event loop uses to get other work done until something to do on your connection.  With threaded / blocking, the latency to regulate throughput is still there, just the thread blocks until it can write more and doesn't show any sign it waited doing nothing.  You just don't "see" it until you want to do something that illuminates your thread has narcolepsy.

`lws_callback_on_writable()` creates an event when something more can be written, so it can be scheduled on the event loop and something written.  This happens immediately if the socket or whatever other transport it is can take a write immediately.  But if communication is choked, blocked or has failed silently, it is handled by delaying the next WRITEABLE so your memory doesn't fill up with stuff you could generate, but couldn't send.

If you want it to work reliably, you have to take the advice and write it in an async manner.
