### ISSUE TITLE
Async DNS Query

### ISSUE THREAD

**Issue by SreedharRe** [warmcat/libwebsockets#2901]
Hi ,
  I am trying to do a async DNS Query and it fails. Am I missing something?
Log as Below in reverse chronological
Regards,
Sreedhar Reddy

|WS/h1/default/54.185.64.48]: ah 0x5585bce800: count 1 (on exit)
2023/06/04 19:09:25.813499530 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8134] D: [wsicli|0|WS/h1/default/54.185.64.48]: __lws_set_timeout: 10 secs, reason 25
2023/06/04 19:09:25.813507690 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] D: [wsicli|0|WS/h1/default/54.185.64.48]: lws_http_client_connect_via_info2: stash 0x5585bce730
2023/06/04 19:09:25.813520330 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] D: _realloc: size 32: strdup
2023/06/04 19:09:25.813529390 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] D: [wsicli|0|WS/h1/default/54.185.64.48]: lws_client_connect_2_dnsreq: new conn on no pipeline flag
2023/06/04 19:09:25.813538560 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] D: [wsicli|0|WS/h1/default/54.185.64.48]: lwsi_set_state: lwsi_set_state 0x10000200 -> 0x10000201
2023/06/04 19:09:25.813546460 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] I: [wsicli|0|WS/h1/default/54.185.64.48]: lws_client_connect_2_dnsreq: lookup ec2-35-162-112-40.us-west-2.compute.amazonaws.com:443
2023/06/04 19:09:25.813553490 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] I: [wsicli|0|WS/h1/default/54.185.64.48]: lws_client_connect_2_dnsreq: Sreedhar: ASync Mode
2023/06/04 19:09:25.813561650 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] I: lws_async_dns_query: entry ec2-35-162-112-40.us-west-2.compute.amazonaws.com
2023/06/04 19:09:25.813569900 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] I: [null wsi]: lws_adns_dump: ADNS cache 0 entries
2023/06/04 19:09:25.813578830 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8135] I: lws_async_dns_query: ec2-35-162-112-40.us-west-2.compute.amazonaws.com uncached
2023/06/04 19:09:25.813607960 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] W: lws_async_dns_init: no valid dns server, retry
2023/06/04 19:09:25.813615380 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] N: lws_async_dns_query: init failed
2023/06/04 19:09:25.813622110 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] N: lws_async_dns_query: failed
2023/06/04 19:09:25.813631340 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] N: [wsicli|0|WS/h1/default/54.185.64.48]: lws_client_connect_3_connect: dns lookup failed -1
2023/06/04 19:09:25.813639310 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] D: [wsicli|0|WS/h1/default/54.185.64.48]: lwsi_set_state: lwsi_set_state 0x10000201 -> 0x10000200
2023/06/04 19:09:25.813649140 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] I: [wsicli|0|WS/h1/default/54.185.64.48]: __lws_close_free_wsi: caller: client_connect2

**Comment by lws-team** [comment]
It feels you don't have any valid DNS server to look up with

2023/06/04 19:09:25.813607960 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] W: lws_async_dns_init: no valid dns server, retry
2023/06/04 19:09:25.813615380 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] N: lws_async_dns_query: init failed
2023/06/04 19:09:25.813622110 {ida_ws_R0-0}{1}: [ida_ws] [6733]: UUID: 0, ra: 0 (ERR): [2023/06/04 19:09:25:8136] N: lws_async_dns_query: failed

see context info struct

```
        const char                              **async_dns_servers;
        /**< CONTEXT: NULL, or a pointer to an array of strings containing the
         * numeric IP like "8.8.8.8" or "2001:4860:4860::8888" for a list of DNS
         * server to forcibly add.  If given, the list of strings must be
         * terminated with a NULL.
         */
```

**Comment by SreedharRe** [comment]
But how do we set one...
Only way is to have entry in /etc/resolve.conf?

**Comment by SreedharRe** [comment]
But how do we set one...
Only way is to have entry in /etc/resolve.conf?

Regards,
Sreedhar Reddy
________________________________

**Comment by lws-team** [comment]
You can set it using the contect info struct.  On some platforms it will get it out of resolv.conf at context creation time.

**Comment by SreedharRe** [comment]
Can you let me know the APIs to set one?

Also I did not find the file/code where the following is present?
        const char                              **async_dns_servers;

**Comment by lws-team** [comment]
There's no api, just set at context creation time.

If you're not using main branch, you'll find it in main branch.

**Comment by SreedharRe** [comment]
Ok..thanks Andy
________________________________
