### ISSUE TITLE
Service turnaround time

### ISSUE THREAD

**Issue by martinvana** [warmcat/libwebsockets#2905]
I am using LWS in raw mode to implement a simple control protocol receiving and processing commands and returning response. The messages and acknowledgement are only a few bytes each. All seems to be working fine.
However, it appears that the time between sending a command and receiving a response is (repeatedly) around 20 ms.
That (including how repeatable it is) suggests that at some level there is a service loop being serviced in 10 ms time slices. This probably makes a lot of sense for typical use (not to starve the calling application) but in my case with many (small) messages this adds up.
Is the service loop turnaround something that can be set as a parameter or could you please navigate me to the module responsible for the timing? (I searched for 'usleep', 'nanosleep' and similar suspects but was unsuccessful.
Or am I barking at a wrong tree and is this a property of NGINX layer?
Thanks for any pointers! Martin

**Comment by lws-team** [comment]
> However, it appears that the time between sending a command and receiving a response is (repeatedly) around 20 ms.

Your code to open your raw fd is not using the default blocking mode, right?

**Comment by martinvana** [comment]
> But with raw you can open your own fd with your own code and adopt it in lws.

Do I understand properly that this is the path to reduce the turnaround? 
Or to word it differently: Is the timing that I see expected when using the default path?
Is there an example of what you suggested you might point me to?
Thanks a lot!

**Comment by martinvana** [comment]
Mea culpa! I took the statement of my colleague at the client side at the face value and kept searching for hours for timing at the server end (lws). 
Only later I wrote my own test to profile the timing and the turnaround is around 3ms. I think this makes a difference.
Thank you for your help - closing the issue.
If, however, you may still point me to an example how to write custom code and adopt in lws I would love to give it a try.
Thanks!
