### ISSUE TITLE
Does not compile on GCC13

### ISSUE THREAD

**Issue by tomzdotorg** [warmcat/libwebsockets#2907]
Due to -Werror and new GCC13 enum-int-mismatch warning

e.g. 
`./lib/tls/openssl/openssl-server.c:713:1: error: conflicting types for ‘lws_tls_server_abort_connection’ due to enum/integer mismatch; have ‘int(struct lws *)’ [-Werror=enum-int-mismatch]`

Potential fix: Change the return type of function `lws_ssl_capable_status` from `int` to `enum lws_ssl_capable_status `

**Comment by lws-team** [comment]
Hm on main branch it has been like that since 89cb55ea589 in 2017, 6 years ago, which means any halfway recent release is all like that too.

Just update to a recent release like v4.3.

**Comment by tomzdotorg** [comment]
I was using 4.3.2, and the problem is indeed there  (note there is a copy-paste typo in my original post, the function name is lws_tls_server_abort_connection)

e.g. here
libwebsockets-4.3.2/lib/tls/openssl/openssl-server.c

`int lws_tls_server_abort_connection(struct lws *wsi`)`

and a similar conditional definition in 
libwebsockets-4.3.2/lib/tls/mbedtls/mbedtls-server.c

**Comment by lws-team** [comment]
OK it got a bit confused one way and another.  713 on main happens to be one line below the return type that is involved in your problem and looked like what you're talking about.

I took the approach to build it in f38 and got your actual problem.  I fixed that and pushed on main and v4.3-stable.
