### ISSUE TITLE
WebSocket periodic writes

### ISSUE THREAD

**Issue by karlisolte** [warmcat/libwebsockets#2913]
I have a WebSocket connection on which I would like to perform periodic writes. For simplicity, I would love to be able to do this from a single thread.

The timeout parameter for `lws_service()` is not used anymore so the only sensible way seems to be to create another thread which calls `lws_callback_on_writable()` periodically:

```
    while(1) {
        // TODO: ensure thread safety
        lws_callback_on_writable(client_wsi);
        sleep(1);
    }
```

Could someone confirm this is the idiomatic way to do that?

**Comment by lws-team** [comment]
> For simplicity, I would love to be able to do this from a single thread.

Yes, that's the good approach.

> sleep(1);

No, that's never a good idea for single threaded event loop.

Have a look at these

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md?h=main

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_sul.md?h=main
