### ISSUE TITLE
lws_log_cx issue with Qt

### ISSUE THREAD

**Issue by lgammo** [warmcat/libwebsockets#2914]
The file lws-logs.h contains this structure:
/*
 * This is the logging context
 */

typedef struct lws_log_cx {
        union {
                lws_log_emit_t          emit; /* legacy emit function */
                lws_log_emit_cx_t       emit_cx; /* LLLF_LOG_CONTEXT_AWARE */
        } u;

I am using libwebsockets with Qt.

Qt uses a macro 'emit' to generate its qt signal/slot handling code. It does that by selectively defining and redefining the macro 'emit'.

As you guess, this causes havoc when libwebsocket.h is included in the Qt code.

I tried various tricks to work around this issue, but nothing is working so far.

Any suggestions would be greatly appreciated.

Thank you.

**Comment by lws-team** [comment]
Well it's not great that qt has a non-namespaced common keyword in the preprocessor.

But doesn't it just need you to include lws includes before the qt ones?

**Comment by lgammo** [comment]
I do include first, but the same header file is included by other include files that have Qt first.

I tried and still trying various combinations.

**Comment by lws-team** [comment]
Should still be OK if you explicitly put lws header first in the C or C++ files, lws has reinclude protection symbols, so it will no longer parse the include later, if it already did it first.

**Comment by lgammo** [comment]
Qt processes files twices. In one context, 'emit' is expected to be empty (evaluates to nothing) and in the other context it evaluates to some internal signal handling code (don't know the details of hand). I think each time is separate, so the file inclusion guard does not apply.

**Comment by lgammo** [comment]
I found a workaround. It was actually simple enough.
#undef emit
#include <libwebsockets.h>
#define emit

Duh!
