### ISSUE TITLE
[FIN, ACK] when connecting multiple websocket clients

### ISSUE THREAD

**Issue by fusionJose** [warmcat/libwebsockets#2918]
I am using last release, with ASYNC DNS and uloop integration. I am trying to connect multiple websocket clients pipelined to a server with same lws context, they first need to resolve async dns URL, when done that, they start sending [FIN, ACK] each to the server. Is there any configuration missing?

`
ws_open{ubox_io *uio){

 if(!lws_ctx){
        logi("init lws ctx");
        if(ws_io_init() == -1){
            ws_connecting[uio->cp_index] = false;
            uio->connecting_retries = 0;
            lets_offline(uio);

        }
    }

    uio->wsi = NULL;

    //$ Fill in cinfo
    memset(&uio->cinfo, 0, sizeof(uio->cinfo)); /* otherwise uninitialized garbage */
    //$ Parse url/uri
    strcpy(url_cpy,uci_ocppd_internal_backend_url_get());
    url = url_cpy;
    if (lws_parse_uri(url, &url_protocol, &(uio->cinfo.address), &(uio->cinfo.port), &url_tmp_path)) {
        logi("lws couldn't parse url %s", url);
        return -1;
    }

    uio->cinfo.path = cp_url_path; // Set the info's path to the fixed up url path
    uio->cinfo.context = lws_ctx;
    uio->cinfo.origin = uio->cinfo.address;
    uio->cinfo.ssl_connection = LCCSCF_PIPELINE;
    uio->cinfo.protocol = protocols[0].name;
    uio->cinfo.userdata = &uio->userdata;
    uio->cinfo.pwsi = &(client_wsis[cp_index].wsi);

    retry.secs_since_valid_ping = uci_ocppd_internal_ping_pong_interval_get();
    retry.secs_since_valid_hangup = uci_ocppd_internal_ping_pong_interval_get() + 10;
    retry.secs_since_valid_ping = UINT16_MAX - 10;
    retry.secs_since_valid_hangup = UINT16_MAX;
        
    uio->cinfo.retry_and_idle_policy = &retry;

    if(!lws_client_connect_via_info(&(uio->cinfo))){
        logi("client connect null");
        ws_connecting[uio->cp_index] = false;
        uio->connecting_retries = 0;

        lets_offline(uio);
    }
    uio->wsi = client_wsis[cp_index].wsi;
}
`
![wshark_capture](https://github.com/warmcat/libwebsockets/assets/52041342/18202a20-f629-44e9-8318-77cf5c6b99b3)

**Comment by lws-team** [comment]
... what are the lws logs telling you?  Asking wireshark, asking me... it's not going to tell you what the logs may already be telling you.

**Comment by fusionJose** [comment]
Unfortunately, i cannot take logs...
