### ISSUE TITLE
Patch: pad LWS_SEND_BUFFER_PRE_PADDING to word size to avoid unaligned reference.

### ISSUE THREAD

**Issue by BrucePerens** [warmcat/libwebsockets#292]
Word-sized references to the memory right after LWS_SEND_BUFFER_PRE_PADDING-sized padding fail because they aren't word-aligned. Pad the pad size to sizeof(void *) on all architectures for which there isn't a specific size defined. On Intel x86-64, pad it to the Intel-recommended 16 bytes for best performance. See https://software.intel.com/en-us/articles/data-alignment-when-migrating-to-64-bit-intel-architecture

```
diff -Naur libwebsockets-old/lib/libwebsockets.h libwebsockets/lib/libwebsockets.h
--- libwebsockets-old/lib/libwebsockets.h	2015-06-07 14:45:03.735748063 -0700
+++ libwebsockets/lib/libwebsockets.h	2015-06-07 15:08:27.294148729 -0700
@@ -1205,7 +1205,21 @@
  * the big length style
  */
 
-#define LWS_SEND_BUFFER_PRE_PADDING (4 + 10 + (2 * MAX_MUX_RECURSION))
+// Pad LWS_SEND_BUFFER_PRE_PADDING to the CPU word size, so that word references
+// to the address immediately after the padding won't cause an unaligned access
+// error. Sometimes the recommended padding is even larger than the size of a void *.
+// For example, for the X86-64 architecture, in Intel's document
+// https://software.intel.com/en-us/articles/data-alignment-when-migrating-to-64-bit-
intel-architecture
+// they recommend that structures larger than 16 bytes be aligned to 16-byte
+// boundaries.
+// 
+#if __x86_64__
+#define _LWS_PAD_SIZE 16		// Intel recommended for best performance.
+#else
+#define _LWS_PAD_SIZE sizeof(void *)	// The pointer size on any unknown arch.
+#endif
+#define _LWS_PAD(n) (((n) % _LWS_PAD_SIZE) ? (n + (_LWS_PAD_SIZE - (n % _LWS_PAD_SIZE
))) : (n))
+#define LWS_SEND_BUFFER_PRE_PADDING _LWS_PAD(4 + 10 + (2 * MAX_MUX_RECURSION))
 #define LWS_SEND_BUFFER_POST_PADDING 4
 
 LWS_VISIBLE LWS_EXTERN int
```

**Comment by JoakimSoderberg** [comment]
Great, you should create this as a Pull Request instead so that it's easier to merge.

**Comment by warmcat** [comment]
Thanks it's pushed.

But note this only helps the situation your streamed struct is aligned to the start of the received packet.

In the general case that your struct with bigger-than-char members may appear with uncontrolled alignment, to be portable at least across gcc arches you have to go with __attribute__((packed)) and eat the efficiency hit.
