### ISSUE TITLE
LWS sending Client Hello 15sec after TCP Establishment

### ISSUE THREAD

**Issue by SreedharRe** [warmcat/libwebsockets#2922]
Hi,
  We are seeing that in some cases LWS is sendind Client Hello more than 15Sec after TCP establishement. In other cases, it is OK.
Please let us know what could be the problem and/or how to debug further.

Failure Case Logs: ( Please see there is nothing between  2023/06/27 20:10:26.961311267 to 2023/06/27 20:10:42.456543645 , Hence peer closes connection since its TCP/TLS timeout is 15 Sec )

2023/06/27 20:10:26.940797176 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 32 - ADD_POLL_FD
2023/06/27 20:10:26.940838497 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS callback: Success to read select Websocket: fd(24) - Success)
2023/06/27 20:10:26.940840617 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 36 - UNLOCK_POLL
2023/06/27 20:10:26.940842737 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 35 - LOCK_POLL
2023/06/27 20:10:26.940850137 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:26:9408] D: [wsicli|0|WS/h1/default/52.35.169.167]: _lws_change_pollfd: fd 24 events 1 -> 1
2023/06/27 20:10:26.940851457 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 34 - CHANGE_MODE_POLL_FD
2023/06/27 20:10:26.940852777 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 36 - UNLOCK_POLL
2023/06/27 20:10:26.940859378 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:26:9408] D: [wsicli|0|WS/h1/default/52.35.169.167]: __lws_set_timeout: 20 secs, reason 2
2023/06/27 20:10:26.940861418 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 105 - CONNECTING
2023/06/27 20:10:26.941001340 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:26:9409] D: [wsicli|0|WS/h1/default/52.35.169.167]: lws_client_connect_3_connect: connect: fd 24 errno: 115
2023/06/27 20:10:26.941005460 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 35 - LOCK_POLL
2023/06/27 20:10:26.941011541 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:26:9410] D: [wsicli|0|WS/h1/default/52.35.169.167]: _lws_change_pollfd: fd 24 events 1 -> 5
2023/06/27 20:10:26.941012621 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 34 - CHANGE_MODE_POLL_FD
2023/06/27 20:10:26.941013981 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 36 - UNLOCK_POLL
2023/06/27 20:10:26.941020861 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:26:9410] D: [wsicli|0|WS/h1/default/52.35.169.167]: lws_client_connect_via_info: adoption cb 19 to h1 ida-protocol
2023/06/27 20:10:26.941022341 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 19 - SERVER_NEW_CLIENT_INSTANTIATED
2023/06/27 20:10:26.941077342 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (note): Connect_server:: FD: 24
2023/06/27 20:10:26.951204784 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (note): Service client fd:: fd(24), n: 0
2023/06/27 20:10:26.951227465 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (note): Connect_server:: FD: 24
2023/06/27 20:10:26.961311267 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (note): Service client fd:: fd(24), n: 0
2023/06/27 20:10:42.456543645 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (note): Service client fd:: fd(24), n: 1
2023/06/27 20:10:42.456614926 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): LWS Callback:: REASON: 35 - LOCK_POLL
2023/06/27 20:10:42.456643807 {ida_ws_R0-0}{255}: [ida_ws] [10398]: UUID: 0, ra: 0 (ERR): [2023/06/27 20:10:42:4566] D: [wsicli|0|WS/h1/default/52.35.169.167]: _lws_change_pollfd: fd 24 events 5 -> 1

**Comment by SreedharRe** [comment]
![image](https://github.com/warmcat/libwebsockets/assets/118266969/4057dca8-fd5c-4e2b-a44f-b4952ef4dc6d)

**Comment by lws-team** [comment]
If you block the lws event loop thread, eg, read something with a blocking fd, he will just be dead until the blocking completes.  Do you have any file or socket IO happening that is not through lws?

Everything lws does itself (except DNS lookup by default) is nonblocking, you can use async dns cmake option to make that nonblocking too.

**Comment by SreedharRe** [comment]
Hi,
  You mean if there is any other process that is in a blocking fd call can cause this? We dont know as this is a moderately complex system with many processes. Is there anyway to check or alleviate this ( at least for testing purposes ?)
Regards,
Sreedhar Reddy
________________________________

**Comment by SreedharRe** [comment]
May be by enabling some logs at LWS or by adding some logs in a specific function in LWS?

Regards,
Sreedhar Reddy
________________________________

**Comment by lws-team** [comment]
No.  I mean in the same process, on the lws event loop thread.

So for example, in a user callback or if you have some mysterious things in the outer event loop, in there.

**Comment by SreedharRe** [comment]
No.. Because the same code on a different unit works perfectly.

Is there any function in LWS where appropriate we can log saying Client Hello being tried and Done ( Dont think so as we call just SSL_Handshake ), but checking

Regards,
Sreedhar Reddy
________________________________

**Comment by SreedharRe** [comment]
Hi,
  Please close this Ticket. Seems like we were not polling after few attempts on the platform where there was a problem. Thanks
