### ISSUE TITLE
libwebsocket build for 32 bit 

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2923]
Hi Andy, 
            Is it possible to build libwebsocket for 32 bit on linux ? if possible could you please let me know how to build it for 32bit .

**Comment by lws-team** [comment]
The way to do this is purely at cmake level using a cmake "toolchain file".

The main step is set -m32 to tell your compiler and linker to use 32-bit, in the toolchain file

```
set(CMAKE_CXX_FLAGS "-m32")
set(CMAKE_SHARED_LINKER_FLAGS "-m32")
```

The toolchain file is basically an external CMakeLists.txt include fragment that goes first, it's the same to send things in as cmake switches, so

```
-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_SHARED_LINKER_FLAGS=-m32
```

will also do this.  That you can make x86 code with the same compiler hides the fact this is actually a full-on cross-build action, even when the code is built, you must link to, eg, x86 versions of the dependent libs, not your usual x86_64 pieces.  There's an even worse situation possible that you accidentally use your x86_64 includes, while forcing x86 libs, the versions of the includes for your x86_64 build machine pieces may not then match the x86 library apis and cause disasters.

If you have a formal x86 cross-root at, eg, /var/my-x86-root/ that then contains .../usr/lib/libssl.so etc, you can inform cmake about it with

-DCMAKE_FIND_ROOT_PATH=/var/my-x86-root -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY 

this will both stop it finding things in your default build machine places like /usr/include, and tell it where to look for the x86 ones.

If you're trying to use x86 packages on your distro, where it puts the stuff inside depends on your distro.
