### ISSUE TITLE
lws_write() return indicates success even though connection peer has shutdown, resulting in potential data loss

### ISSUE THREAD

**Issue by sgilbo618** [warmcat/libwebsockets#2929]
### The scenario is as follows:
- LWS client has made a successful connection to a websocket server
- LWS client has successfully sent some data to said server
- LWS client asks for a writable callback to send more data
- The server ends the remote end of the connection (in this specific example, I have killed the remote server and it is completely shutdown)
- LWS client gets its writable callback and attempts to send using lws_write()
- lws_write() returns success (the return equals the number of bytes attempted to be sent) 
- LWS client client recognizes the connection has closed and closed on its end

### The issue:
I would expect lws_write()'s return to indicate the connection has closed and the data was not successfully sent, seeing as the server has shutdown and the connection has been closed on the other end. From the LWS logs, it seems that the connection error is being caught (errno 32 - broken pipe), but it is caught after the 'successful' write and is not relayed to the writeable callback. Perhaps I am missing something though. Any advice or insight to the issue will be much appreciated.

### Some logs (includes both LWS logs and some of my own debug logging):
[wsicli|0|WS/h1/default/localhost]: lws_client_ws_upgrade: handshake OK for protocol wss_poller_protocol
In LWS_CALLBACK_CLIENT_ESTABLISHED
[wsicli|0|WS/h1/default/localhost]: _lws_change_pollfd: fd 6 events 1 -> 5
[wsicli|0|WS/h1/default/localhost]: _lws_change_pollfd: fd 6 events 5 -> 1
[wsicli|0|WS/h1/default/localhost]: lws_handle_POLLOUT_event: non mux: wsistate 0x10000119, ops ws
In LWS_CALLBACK_CLIENT_WRITEABLE
Client is writing data of size 12
lws_write() returned: 12
successfully sent message 1
checking errno: 0
[wsicli|0|WS/h1/default/localhost]: _lws_change_pollfd: fd 6 events 1 -> 5
[wsicli|0|WS/h1/default/localhost]: _lws_change_pollfd: fd 6 events 5 -> 1
[wsicli|0|WS/h1/default/localhost]: lws_handle_POLLOUT_event: non mux: wsistate 0x10000119, ops ws
In LWS_CALLBACK_CLIENT_WRITEABLE
Client is writing data of size 12
lws_write() returned: 12
successfully sent message 2
checking errno: 0
[wsicli|0|WS/h1/default/localhost]: SSL_read says 0
lws_ssl_get_error: 0x55c4889e3d50 0 -> 1 (errno 32)
[wsicli|0|WS/h1/default/localhost]: ssl err 1 errno 32
[wsicli|0|WS/h1/default/localhost]: lws_service_fd_tsi: Close and handled
[wsicli|0|WS/h1/default/localhost]: __lws_close_free_wsi: real just_kill_connection A: (sockfd 6)
[wsicli|0|WS/h1/default/localhost]: lwsi_set_state: lwsi_set_state 0x10000119 -> 0x10000020
[wsicli|0|WS/h1/default/localhost]: __lws_vhost_unbind_wsi: vh default: count_bound_wsi 0
[wsicli|0|WS/h1/default/localhost]: __lws_free_wsi: tsi fds count 2

### Packet capture showing the remote end connection has aborted
4:25:09.745247 IP localhost.42026 > localhost.https: Flags [P.], seq 742:782, ack 2994, win 512, options [nop,nop,TS val 512055493 ecr 512049903], length 40
14:25:09.745265 IP localhost.https > localhost.42026: Flags [R], seq 765419401, win 0, length 0

### The writable callback:
`	case (LWS_CALLBACK_CLIENT_WRITEABLE):
	{
		std::cout << "In LWS_CALLBACK_CLIENT_WRITEABLE" << std::endl;

		std::vector<unsigned char> sendBuff(LWS_PRE + strlen(MESSAGE));
		strncpy((char*)(sendBuff.data() + LWS_PRE), MESSAGE, strlen(MESSAGE));

		std::cout << "Client is writing data of size " << strlen(MESSAGE) << std::endl;

		res = lws_write(wsi, &sendBuff[LWS_PRE], strlen(MESSAGE), LWS_WRITE_BINARY);
		std::cout << "lws_write() returned: " << res << std::endl;
		if (res < 0)
		{
			std::cout << "failure at lws_write()" << std::endl;
			return -1;
		}
		else if (res < strlen(MESSAGE))
		{
			std::cout << "lws_write() failed to send entire message" << std::endl;
			return -1;
		}
		else
		{
			count++;
			std::cout << "successfully sent message " << count << std::endl;
			std::cout << "checking errno: " << errno << std::endl;
		}
		break;
	}`

Please let me know if more information is necessary.

**Comment by lws-team** [comment]
That is how posix works.  Even with blocking calls, when write() returns, there is no other assurance your data has gone anywhere than to the kernel on your machine and not even out your network interface let alone to the destination.

Long delays you may see sometimes bamboozling you into your alternate belief system "gee this packet is taking a long time to get to the destination machine", is actually (possibly much) earlier packets getting to the destination making space in the tcp window on the sender side, so that the local kernel will accept to hold on to some newer data kernelside until it can be sent.  There is zero implication that it has, can, or ever will actually be physically sent, if something has happened that was not obvious enough for the sender side kernel to understand the tcp connection has forcibly finished, eg, cat pulled out ethernet cable on intermediary machine or router.

**Comment by sgilbo618** [comment]
Right, there is no assurance the data goes anywhere, but with TCP based protocols there is awareness as to whether or not the data got where we want it to go. If the connection is lost or there is too long of a delay, etc, the protocol produces an error. If I were to call SSL_write() or send() directly on a TCP socket when the other end has closed, I would get an error return of some sort to indicate as such, and would then know my data didn't arrive.

In the case above, there is an error reported to LWS (errno 32, as seen in the logs), but that error is not propagated back to the user in the lws_write call or the writable callback as far as I can tell. This leads to an assumption that the data was sent, perhaps a bad assumption on how lws_write() should work on my part. Is there somewhere else the user can get access to these kinds of errors then that I am missing?

**Comment by lws-team** [comment]
If SSL feels something was wrong, it will return its own error code and lws will react.

But the point is, you can arrive at a situation where the link will stay up and no traffic passing for a long while.  You seem to think that's an lws thing, but it is a network programming reality.

**Comment by sgilbo618** [comment]
My issue is not related to a delay. The issue is I have sent data on a broken connection, my data does not actually get sent, but I get a success return. Immediately after, LWS recognizes the issue and reacts, as you say, by closing down the client end of the connection. But my data didn't get sent and I don't get the error returned to me. How am I supposed to know if my send was successful or not if I don't get the error?

**Comment by lws-team** [comment]
> The issue is I have sent data on a broken connection, my data does not actually get sent, 

Your data won't get sent if a cat pulls out the ethernet on an intermediate machine.  Each side won't find out about that until they try to do something.

lws_write() happy just says the next layer took that data and didn't tell it an error.  I am afraid you will have to get used to this situation just being a reality, lws or not.... successfully writing the data locally is not assuring you about the data going on the wire or reaching the other side.  lws is still correct to tell you it passed the data on successfully.

That's why there are validity checks like PING / PONG and assertive transaction completion notifications from the other side in the world... not just in lws.

**Comment by sgilbo618** [comment]
I understand what you are saying, that as far as lws_write is concerned, it has done its job so there will be no error info available there. That is a misinterpretation of the documentation on my part. 

So in the case that a connection closes due to an error, is there any way for a user to get the error information?

Like this case:

[wsicli|0|WS/h1/default/localhost]: SSL_read says 0
lws_ssl_get_error: 0x563f002a6ab0 0 -> 6 (errno 0)
[wsicli|0|WS/h1/default/localhost]: ssl err 6 errno 0
[wsicli|0|WS/h1/default/localhost]: lws_service_fd_tsi: Close and handled
[wsicli|0|WS/h1/default/localhost]: __lws_close_free_wsi: real just_kill_connection A: (sockfd 6)
[wsicli|0|WS/h1/default/localhost: lwsi_set_state: lwsi_set_state 0x10000119 -> 0x10000020

There is a ssl err and the connection must be abandoned. The next callback reason is LWS_CALLBACK_CLIENT_CLOSED and then LWS_CALLBACK_WSI_DESTROY- is there any way to get the error info in these? I can check for an errno here, but that is not useful in the case of a ssl error.

**Comment by lws-team** [comment]
Not really... his main concern is that he shut down properly and clean up well, the user will get a callback so that he can understand the connection is over.

On main there's additional metrics can be kept about the fate of connections but I don't think it goes into collecting errno.
