### ISSUE TITLE
LWS_CALLBACK_HTTP_BODY only called twice, then gets stuck over HTTPS

### ISSUE THREAD

**Issue by select-this** [warmcat/libwebsockets#293]
For some reason, when uploading files that require the `LWS_CALLBACK_HTTP_BODY` to be called multiple times, after the second call nothing further happens.

According to GDB, the library appears to get stuck in `lws_plat_service()` (which is called somewhere in the `libwebsocket_service()` function) and never returns from there. Other than that, I don't have a lot more debugging information to go on yet.

Could there be something else at play here that's causing something to block when it shouldn't? Any files that get sent entirely in one call to `LWS_CALLBACK_HTTP_BODY` work just fine.

I'm using Ubuntu 14.04, so presumably the `lws-plat-unix.c` version is being called.

ADDENDUM: Okay, I recompiled libwebsockets with debug symbols and it appears that the following line is never returning:

`if (context->fds[wsi->sock].revents & POLLIN) {`

It also seems that this only happens when uploading files over HTTPS; HTTP files work just fine, so it seems to be something related to the SSL side of things.

**Comment by ralight** [comment]
This is the same issue as is addressed in https://github.com/warmcat/libwebsockets/issues/295 and https://github.com/warmcat/libwebsockets/pull/298
