### ISSUE TITLE
build issue when use mbedTls with libuv

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2930]
Hi @lws-team ,
                        i am trying to cross compile libwebsocket  for arm-none-eabi (Generic system)  with mbedTLS .but while cross compiling libuv for arm-none-eabi compiler it gives me error because libuv not supported for non posix system. so could you please let me know the alternative for libuv so that i can cross compile libwebsocket for  arm-none-eabi (Generic system) .

**Comment by lws-team** [comment]
I guess you're actually running on linux, but libuv is reading into this "none" that it's a bare metal system without a normal OS (such as you would use to build a bootloader or whatever).  You're saying with that, that there are no syscalls available from the OS and so you can't use normal libc functions that get work done by syscalls (like posix).

The easiest way is don't use that "none" toolchain for this when you want "linux".  Use a toolchain with linux in the triplet describing it and it should "just work".

**Comment by sush126** [comment]
yes mine is bare metal system , so i need libwebsockets porting for  freeRTOS . if you have any link regarding this could you please share it ?

**Comment by lws-team** [comment]
Oh... well you can't use libuv on bare metal.

lws can do it at least for ESP32, you should look down lib/plat/freertos.  Basically your freertos build has to provide things like socket() etc via some other tcp stack project.

**Comment by sush126** [comment]
i am trying to provide socket and other dependancy using FreeRTOS-tcp IP , also i am using mbedTLS below is the build options i have used to build libwebsocket  but facing below error : 
**/libwebsockets/lib/tls/mbedtls/wrapper/platform/ssl_pm.c:552:14: error: 'MBEDTLS_SSL_SERVER_NEW_SESSION_TICKET' undeclared (first use in this function); did you mean 'MBEDTLS_SSL_TLS1_3_NEW_SESSION_TICKET'?
  552 |         case MBEDTLS_SSL_SERVER_NEW_SESSION_TICKET:**

MBEDTLS_SSL_SERVER_NEW_SESSION_TICKET is not define in mbedTLS as well .

**Comment by lws-team** [comment]
This is changed by mbedtls here

```
commit a357cf4d4c200d6b7790124e7cf38b9d3ac17509
Author: Jerry Yu <jerry.h.yu@arm.com>
Date:   Tue Jul 12 05:36:45 2022 +0000

    Rename new_session_ticket state
    
    Both client and server side use
    `MBEDTLS_SSL_NEW_SESSION_TICKET` now
    
    Signed-off-by: Jerry Yu <jerry.h.yu@arm.com>
```

if  you look at what the commit does, it's basically

```
-    MBEDTLS_SSL_SERVER_NEW_SESSION_TICKET,
+    MBEDTLS_SSL_NEW_SESSION_TICKET,
```

you can try that instead.
