### ISSUE TITLE
Why libwebsocket still send ping when has recieved or sended data

### ISSUE THREAD

**Issue by hwboboy** [warmcat/libwebsockets#2931]
.secs_since_valid_ping          = 20,  /* force PINGs after secs idle */
       .secs_since_valid_hangup        = 40,  /* hangup after secs idle */

When I set this in my code, the libwebsocket will send ping every 20 seconds. Even some data has sended to or received from server. 
While version 2.1.0 has no such problem.

**Comment by lws-team** [comment]
That is not a "problem".  lws got a better concept about "connection validity"... both at the network level and at the server / proxy routing level, connections can fail unidirectionally.  The fact the remote thing is sending you something, does not mean it is listening to you or processing what you sent, if may just be able to spam you.

For that reason lws insists on proof that the connection is still valid, if you don't provide it yourself by telling it that you just saw some proof the remote is processing your transactions bidirectionally using lws_validity_confirmed(), it will forcibly prove it by PING / PONG.

```
/*
 * lws_validity_confirmed() - reset the validity timer for a network connection
 *
 * \param wsi: the connection that saw traffic proving the connection valid
 *
 * Network connections are subject to intervals defined by the context, the
 * vhost if server connections, or the client connect info if a client
 * connection.  If the connection goes longer than the specified time since
 * last observing traffic that can only happen if traffic is passing in both
 * directions, then lws will try to create a PING transaction on the network
 * connection.
 *
 * If the connection reaches the specified `.secs_since_valid_hangup` time
 * still without any proof of validity, the connection will be closed.
 *
 * If the PONG comes, or user code observes traffic that satisfies the proof
 * that both directions are passing traffic to the peer and calls this api,
 * the connection validity timer is reset and the scheme repeats.
 */
LWS_VISIBLE LWS_EXTERN void
lws_validity_confirmed(struct lws *wsi);
```
