### ISSUE TITLE
Vhosts should only be rebound if they are using the same listening socket

### ISSUE THREAD

**Issue by marwisihans** [warmcat/libwebsockets#2933]
Imagine following scenario:
We have two vhosts bound to devices, where we have a 1-to-1 mapping to an interface, like so.

192.168.0.1:80 <-> vhost1 (vhost_name: "example.com")
192.168.1.1:80 <-> vhost2 (vhost_name: "example.com")

If any vhost rebinding should take place, it feels like it should only happen if the vhost it tries to bind **to** uses the same listening socket as the one it is **from**. Otherwise you could have issues with lws_get_vhost(wsi) returning different vhosts, for example.

**Comment by lws-team** [comment]
Sorry I am a long way away from when I wrote this code... I assume we're talking about it being a server... when the accepted wsi is created, he should know which vhost he is coming into existence for.  Why is he wanting to switch to a different one?

**Comment by marwisihans** [comment]
Yes, sorry, this is when it is acting as a server. LWS version 4.3.2.

Initially when a the connection is accepted (_LWS_CALLBACK_WSI_CREATE_), the vhost/interface used seems to be the one which received the request from a client. Later in the lifecycle of the wsi however (_LWS_CALLBACK_HTTP_WRITEABLE_ or _LWS_CALLBACK_WSI_DESTROY_, for example), the wsi might have been rebound to another vhost (**server.c:2268 - lws_select_vhost()** + **server.c:2273 - lws_vhost_bind_wsi()**) if they have the same vhost_name. The first vhost to match is picked. This can cause issues if the interfaces don't work under the same circumstances, different NIC:s/Adapters, firewall config, etc..

I think it would be logical for a request arriving on interface x to also have its response be sent on interface x.

**Comment by lws-team** [comment]
The vhosts have to have unique names, that should be enough to solve it IIUI
