### ISSUE TITLE
Cannot build on non-EOL OpenSSL

### ISSUE THREAD

**Issue by raul-guerrero** [warmcat/libwebsockets#2934]
Hi,

I tried to build this on linux and MacOS x86_64 but it seems it requires the much older OpenSSL 1.0.x distribution which was EOL a while back.
Is there a branch to be able to build libwebsockets using a newer version of OpenSSL?

Cheers

**Comment by lws-team** [comment]
lws generally builds fine against openssl3 since before openssl3 came out.

You are a bit vague about what actually happened when you tried that.

**Comment by raul-guerrero** [comment]
@lws-team you're right, I'm sorry for missing adding concrete details.

While building, I get the following error related to openSSL:
```
libwebsockets-src/include/libwebsockets/lws-genhash.h:85:18: error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/usr/local/opt/openssl@3/include/openssl/types.h:135:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
1 error generated.
```

Problem is that reference to context is not exposed anymore, the API was changed as of OpenSSL 1.1.

As you mention it builds using OpenSSL 3.x, then which branch is that? I cloned from main, but maybe I'm missing something?
Also, I'm not sure how the cmake script works, when doing findOpenSSL() the include dir is set under variable OPENSSL_INCLUDE_DIR, but on your script it uses OPENSSL_INCLUDE_DIRS plural, I have to pass the following flag to cmake to build in the first place: -DOPENSSL_INCLUDE_DIRS=/path/to/openssl/include

I'd be really thankful if you could guide me on how to build it. I want to use the library on a project that's an app on both MacOS using the x86_64 arch and on Linux.

Thanks

**Comment by lws-team** [comment]
This is a general thing with cmake trying to make adaptations to lws based on which openssl api epoch it finds that you have, but it can't succeed to assess it properly because something stops it building the little test probes it uses to figure it out.

See the second section here https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

**Comment by raul-guerrero** [comment]
At the moment i found libwebsockets through the homebrew package manager, I'll install it from there, although I would like to continue trying to build from source as a learning experience.
If you mention that you guys support OpenSSL 3, then I'll try to figure out how to build using it, thanks for hte README reference.

**Comment by je3f0o** [comment]
I cannot build on MacOS too.
```
$ brew info openssl@3
==> openssl@3: stable 3.1.2 (bottled)
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@3/3.1.2 (6,495 files, 30.0MB) *
```
and this is my build command:
```
cmake .. -DOPENSSL_INCLUDE_DIR='/usr/local/Cellar/openssl@3/3.1.2/include' -DOPENSSL_LIBRARIES='/usr/local/Cellar/openssl@3/3.1.2/lib' | grep HMAC
```
I tried with OpenSSL version 1.1 and 3 with `OPENSSL_INCLUDE_DIRS` and `OPENSSL_INCLUDE_DIR` both. Still not found:
```
-- Looking for HMAC_CTX_new
-- Looking for HMAC_CTX_new - not found
```

Output error message:
```
error: field has incomplete type 'HMAC_CTX' (aka 'struct hmac_ctx_st')
        HMAC_CTX ctx;
                 ^
/usr/local/Cellar/openssl@3/3.1.2/include/openssl/types.h:135:16: note: forward declaration of 'struct hmac_ctx_st'
typedef struct hmac_ctx_st HMAC_CTX;
               ^
1 error generated.
```
looks like I got included correct path. In my CMakeError.log:
```
Determining if the function HMAC_CTX_new exists failed with the following output:
Change Dir: <my libs dir>/libwebsockets/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_46cf4/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_46cf4.dir/build.make CMakeFiles/cmTC_46cf4.dir/build
Building C object CMakeFiles/cmTC_46cf4.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DKEYWORD=__inline -I/usr/local/Cellar/openssl@3/3.1.2/include -Wno-deprecated-declarations -Wno-deprecated -Wall -Wextra -Wno-unused-parameter -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers   -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -o CMakeFiles/cmTC_46cf4.dir/CheckFunctionExists.c.o -c /usr/local/Cellar/cmake/3.19.2/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_46cf4
/usr/local/Cellar/cmake/3.19.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_46cf4.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wno-deprecated-declarations -Wno-deprecated -Wall -Wextra -Wno-unused-parameter -Wconversion -Wsign-compare -Wstrict-aliasing -fvisibility=hidden -Wundef  -Wuninitialized -Wtype-limits -Wignored-qualifiers   -Werror -Wno-deprecated-declarations -pthread -Wno-error=unused-command-line-argument -DCHECK_FUNCTION_EXISTS=HMAC_CTX_new -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_46cf4.dir/CheckFunctionExists.c.o -o cmTC_46cf4  /usr/local/Cellar/openssl@1.1/1.1.1u/lib/libssl.dylib /usr/local/Cellar/openssl@1.1/1.1.1u/lib/libcrypto.dylib -lssl -lcrypto 
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_46cf4] Error 1
make: *** [cmTC_46cf4/fast] Error 2
```
In the error log has `ld: library not found for -lssl`. I don't know why.

**Comment by davehorton** [comment]
@je3f0o I am having the same issue / at the same place as you.  CMakeError.log complains it cant find -lssl yet the command seems to be passing the correct location.  were you able to get yourself unstuck?

**Comment by je3f0o** [comment]
> @je3f0o I am having the same issue / at the same place as you. CMakeError.log complains it cant find -lssl yet the command seems to be passing the correct location. were you able to get yourself unstuck?

I ended up compiled without ssl. because I don't need ssl in my case.
