### ISSUE TITLE
Can sending and receiving messages only be in callback functions?

### ISSUE THREAD

**Issue by mrsanshui** [warmcat/libwebsockets#2936]
Can sending and receiving messages only be in callback functions? So, should I proactively push messages to the client?

**Comment by lws-team** [comment]
The wsi callback is how your code is made aware that it can send something or can receive something on the connection.

I'm not sure how you get from that to "should I proactively push messages to the client".  Generally, if one side has something it wants to send, it can send it unannounced so long, eg, as you're not already in the middle of a different ws message.  But it feels like I don't understand what you're asking.

**Comment by mrsanshui** [comment]
Wow, the reply was so fast~Sorry, my English is quite poor I made a mistake in expressing myself. What I meant was how to send messages outside the callback function. Currently, I can only listen to messages sent by the client through the `LWS_CALLBACK_RECEIVE` event and make corresponding responses.

I know this is an event loop, so I try to call `lws_cancel_service(context)` externally to trigger `LWS_CALLBACK_EVENT_WAIT_CANCELLED` events, and call `lws_callback_on_writable(wsi)` in the event, but an error will occur

**Comment by lws-team** [comment]
I see... yes well if messages are coming from the server, doing things in the receive callback is good.

If you want to initiate sending things from some other thread, what you did with cancel_service sounds right.  What's the error that is coming?

**Comment by mrsanshui** [comment]
this is my demo.
As long as I write `lws_callback_on_writable(wsi)` in the `LWS_CALLBACK_EVENT_WAIT_CANCELLED `event it stays at this line with error saying: Access Violation

```C++
//global
lws_context* context;
map<lws*, BOOL> connMap;

//test external send msg
void SendMsg()
{
	while (true)
	{
		Sleep(5000);
		for (auto& it : connMap)
		{
			lws_cancel_service(context);
		}
	}
}

//callback
int EvHandler(lws* wsi, lws_callback_reasons event_type, void* user, void* in, size_t len)
{
	session_data* data = (session_data*)user;

	switch (event_type)
	{
	case LWS_CALLBACK_EVENT_WAIT_CANCELLED:
	{
		if (connMap.empty())break;
		lws_callback_on_writable(wsi);
		break;
	}
	case LWS_CALLBACK_ESTABLISHED:
	{
		//save connect
		connMap[wsi] = TRUE;
		break;
	}
	case LWS_CALLBACK_SERVER_WRITEABLE:
	{
		cout << "come in" << endl;
		string msg = "Msg";
		const unsigned char* stringData = reinterpret_cast<const unsigned char*>(msg.c_str());
		size_t stringLength = msg.length();

		if (stringLength <= MAX_PAYLOAD_SIZE)
		{
			memcpy(&data->buf[LWS_PRE], stringData, stringLength);
			data->len = stringLength;
		}

		lws_write(wsi, &data->buf[LWS_PRE], data->len, LWS_WRITE_TEXT);
		break;
	}
	default:
		break;
	}
	return 0;
}


int main()
{
	static lws_protocols protocols[] = {
		{"ws", EvHandler, sizeof(session_data), MAX_PAYLOAD_SIZE },
		{ NULL, NULL, 0, 0 }
	};

	lws_context_creation_info info;
	memset(&info, 0, sizeof(info));

	info.iface = "127.0.0.1";
	info.port = 8989;
	info.protocols = protocols; 
	info.gid = -1;
	info.uid = -1; 
	info.options = LWS_SERVER_OPTION_VALIDATE_UTF8;

	context = lws_create_context(&info);
	if (!context)
	{
		cerr << "Failed to create libwebsocket context" << endl;
		return -1;
	}

	//test external send msg
	thread myThread(SendMsg);
	myThread.detach();

	while (true) lws_service(context, 500);

	lws_context_destroy(context);

	return 0;
}
```

![image](https://github.com/warmcat/libwebsockets/assets/52669366/7e772e83-dc2f-4e8d-8d6e-13d418030e21)

**Comment by lws-team** [comment]
Yes it's correct to blow up.

When you cancel the event loop wait, that is a global event for the event loop, it's not related to any particular wsi... the wsi passed in to the callback for this kind of non-wsi-related event is a fake one just enough so you can get the context pointer from it.  Similarly it's not related to any particular vhost.  It's confusing you that you typically only have one wsi active to a server at a time and just assume "it knows", it doesn't know, the wsi to this event loop scope callback is faked just to keep up appearances in case the callback, eg, dereferences it to get ahold of the lws_context * locally.

You have to separately manage a list of active wsi on the client side, adding to the list when the wsi is created and removing it from the list when it sees it is being CLOSED.  You can get valid wsi pointers from this list during EVENT_WAIT_CANCELLED then.  If it can only ever have one active connection to one server, the "list" can just be a wsi pointer.

**Comment by mrsanshui** [comment]
I'm really sorry to bother you again and again.
Yes, what you said is fine on the client side.
But the code snippet I just posted is the server side...
As a server, how can I actively send messages to the client

**Comment by lws-team** [comment]
There's no difference in approach for this.  The callbacks you use to collect and maintain a list of active clients are slightly different for server is all.

You can keep state about the connection to the client in the wsi pss (user allocation) somewhere, if there are multiple threads it's in a composed struct that the other thread can also understand and protected by a mutex in there typically.  You can iterate through the alive wsi in the CANCELLED callback seeing if they are in a state where they have anything they want to do, eg, didn't catch up with a ringbuffer of events yet on that particular connection.  Then you are in a good, safe place to ask for writeable callbacks on any wsi that want to write something.  And actually write it again according to the state you find in the WRITEABLE callback for the wsi when that comes.

**Comment by mrsanshui** [comment]
Thanks a lot, it was a great help!
