### ISSUE TITLE
cross compile issue when compiling libwebsocket for bare metal 

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#2937]
Hi Andy ,
i am cross compiling libwebsocket for arm-none (generic ) platform , facing below error ,
 home/projects/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ../../../lib/libwebsockets.a(ssl_pm.c.obj): in function `ssl_pm_new':
ssl_pm.c:(.text.ssl_pm_new+0x62): undefined reference to `mbedtls_net_init'

**Comment by lws-team** [comment]
This is the subject of a config-time existence test in lib/tls/CMakeLists.txt

```
CHECK_FUNCTION_EXISTS(mbedtls_net_init LWS_HAVE_mbedtls_net_init PARENT_SCOPE)
```

it's likely that something is wrong with how the probe tests for that are building, and it thinks it's there when it isn't.

See the second section here https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.cmake.md

**Comment by sush126** [comment]
Okay  Thanks @lws-team.
Could you please let me know how i can disable all logs is there any cmake flag that i can pass to cmakelists.txt ?

**Comment by lws-team** [comment]
See READMEs/README.logging.md, either defeat everything by setting LWS_LOGGING_BITFIELD_CLEAR to everything, or set your own emit function and have it discard them.
