### ISSUE TITLE
How do I get the reason for the shutdown

### ISSUE THREAD

**Issue by TDCQ886** [warmcat/libwebsockets#2939]
How do I get the reason when the socket is closed.for example  closed by self or other side or abnormal closed,thank you very much

**Comment by TDCQ886** [comment]
Now I know that callback function will be called always with LWS_CALLBACK_CLOSED. However how do i get the reason when the socket is closed by a unnoraml way so that i can dispose it according to the actual condition

**Comment by lws-team** [comment]
Sometimes there is just no information, eg, went out of range of Wifi.

If the ws peer did a controlled ws close, you will get

```
        LWS_CALLBACK_WS_PEER_INITIATED_CLOSE                    = 38,
        /**< The peer has sent an unsolicited Close WS packet.  in and
         * len are the optional close code (first 2 bytes, network
         * order) and the optional additional information which is not
         * defined in the standard, and may be a string or non human-readable
         * data.
         * If you return 0 lws will echo the close and then close the
         * connection.  If you return nonzero lws will just close the
         * connection. */
```
