### ISSUE TITLE
Libwebsocket sends FIN ping after 5 minutes for connection validity, is it compulsory ?

### ISSUE THREAD

**Issue by Paramveer24b** [warmcat/libwebsockets#2940]
Libwebsocket sends FIN ping after 5 minutes for connection validity .. is it compulsory ?

There is retry policy in context which has been to connection validity 
static const lws_retry_bo_t retry = {
	.secs_since_valid_ping = 10,
	.secs_since_valid_hangup = 20,
};

My question is ... is this mandatory for TCP ? if yes can you share any reference... if not then is there any way to avoid this ?

**Comment by lws-team** [comment]
What's closing... an outgoing client connection?  If so and it really used that retry struct, it should be sending pings every 10s if idle.

What does the verbose logs say when it closes?

**Comment by Paramveer24b** [comment]
I have used a server with libwebsocket and it's been connected to a client which I am not sure using libwebsocket (same or old version or may be not)..
unfortunately I can't get any logs... 

After five minutes server sends FIN .. but client does not send PONG so connection gets closed.
I know this suppose to happen .. but can we avoid this ? do not send PING at all. :)

**Comment by Paramveer24b** [comment]
structure I have mentioned above for just for information 
static const lws_retry_bo_t retry = {
.secs_since_valid_ping = 10,
.secs_since_valid_hangup = 20,
};

actually server is using default values i.e 5 minutes

**Comment by lws-team** [comment]
>>  actually server is using default values i.e 5 minutes
> unfortunately I can't get any logs...

You need to get logs for at least your side, not just expect help with no information.

Server should send a PING to the client after .secs_since_valid_ping, it's some time before it will close, you would see it in the verbose logs.  If your client is noncompliant, doesn't understand PING should make it send PONG, it will result in this kind of behaviour.  Or if the server never sent the PING it would be the same.

**Comment by Paramveer24b** [comment]
Thanks for the update.

I will check for the logs again.

sorry for asking again...  is there any way to disable FIN PING ?
