### ISSUE TITLE
Connected websocket is dead

### ISSUE THREAD

**Issue by jongsun89** [warmcat/libwebsockets#2942]
@lws-team  Hello.

I made a server pushing realtime encoded videostream through connected websocket to client.
But, after sometime websocket connection is closed.
so i open lws logs and got the logs that session socket is dead.
why this happens? any way to prevent closed.
after 40 min, connection is closed in the last test.
- lws version 3.2.3
Your idea will be helpful , Thanks!

D: _lws_change_pollfd: wsi 0xafa07818: fd 58 events 1 -> 5
D: _lws_change_pollfd: wsi 0xafa07818: fd 58 events 5 -> 1
D: lws_handle_POLLOUT_event: 0xafa07818: non mux: wsistate 0x20000117, ops ws
I: lws_issue_raw: ssl_capable_write (9329) says 9329
**D: Session Socket 0xafa07818 (fd=58) dead**
I: __lws_close_free_wsi: 0xafa07818: caller: close_and_handled
D: __lws_close_free_wsi: 0xafa07818: DROP_PROTOCOL videostream
__lws_close_free_wsi: real just_kill_connection: 0xafa07818 (sockfd 58)
_lws_change_pollfd: wsi 0xafa01138: fd 45 events 1 -> 1
lwsi_set_state(0xafa07818, 0x2000001e)

**Comment by lws-team** [comment]
This doesn't have any meaning for lws other than when it went to write on it, it found the underlying socket's connection had finished.  Eg, the peer or intermediary had hung up on it; you should look at the peer logs if nothing in lws ones.

You can handle the CLOSE callback that will also be coming with that and reopen a new connection if you need it nailed up.
