### ISSUE TITLE
websocket connection closes with "Ran out of header data space"

### ISSUE THREAD

**Issue by yvvarun** [warmcat/libwebsockets#2944]
i’m trying to make a websocket connection from a UI to a server that uses libwebsockets library with v4.3.0 version and in the UI i can see that the websocket connection is getting closed.
i enabled debug logs for websocket in the server and i can see this error -
: INFO, tardis.janus.stdout, [libwebsockets][ERR] [2023/08/02 15:20:53:4160] E: Ran out of header data space

i’ve also tried this in incognito and cleared cookies, it didn’t help.

let me know if you need any more logs or configs.

**Comment by lws-team** [comment]
Increase this in the context creation info struct.

```
        unsigned short max_http_header_data;
        /**< CONTEXT: The max amount of header payload that can be handled
         * in an http request (unrecognized header payload is dropped) */
```
