### ISSUE TITLE
attaching header for username and password

### ISSUE THREAD

**Issue by khan-hannan** [warmcat/libwebsockets#2948]
Hello !

i need to attach an extra header containing Authentication: password which i do as follows 
```
        int callback_dumb_increment(struct lws *wsi, enum lws_callback_reasons reason,
			void *user, void *in, size_t len)
{
	int n;
	WebSockets::Protocol * p  = 0;
	if ((WebSockets::Protocol*)lws_get_protocol(wsi))
		p  =  (WebSockets::Protocol*)lws_get_protocol(wsi)->user;
	std::cout<<reason<<std::endl;
	switch (reason) {
       ...... <some code here>


        case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
        {
                 unsigned char **p = (unsigned char **)in, *end = (*p) + len;

			  if (lws_add_http_header_by_name(wsi,
								  (const unsigned char *)"Authorization",
							  (const unsigned char *)"password", sizeof("password"), p, end))
					  return -1;
					  
					  break;
        }

       ...... <some code here>
```

but it gives me the following error 

W: [wsicli|0|WS/h1/default/uat.coinroutes.io]: lws_client_ws_upgrade: got bad HTTP response '400'
E: CLIENT_CONNECTION_ERROR: HS: ws upgrade response not 101

the header/username,password works well when using python's websocket library.

**Comment by lws-team** [comment]
> the header/username,password works well when using python's websocket library.

Great!  Just use that then.

**Comment by khan-hannan** [comment]
It was just for reference that the header is fine. If you could help me on fixing this i would be greatful.

**Comment by khan-hannan** [comment]
i was able to solve it by the following
lws_add_http_header_by_name(wsi,  (const unsigned char *)"Authorization",  (const unsigned char *)"password", sizeof("password")-1, p, end))

turns out the function was placing an extra value at the end of the password so we can send sizeof("password") -1 to fix it. 

regards.
