### ISSUE TITLE
How set handshake path for wss

### ISSUE THREAD

**Issue by vinifr** [warmcat/libwebsockets#2949]
Hi.

How can I get this handshake (google chrome):
_GET wss://ws.broker.com/socket.io/?EIO=3&transport=websocket HTTP/1.1
Host: ws2.broker.com_

Instead (libwebsocket):
_GET /socket.io/?EIO=3&transport=websocket HTTP/1.1
Host: ws2.broker.com_

I tried:
ccinfo.address 	=  "ws2.broker.com"
ccinfo.path 	        =   "wss://ws2.broker.com/socket.io/?EIO=3&transport=websocket"
/-----
ccinfo.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;

And I get this with "/" in the beginning:
_GET /wss://ws2.broker.com/socket.io/?EIO=3&transport=websocket HTTP/1.1
Host: ws2.broker.com_

The reason for this is because I am receiving: 
[2023/08/05 08:20:04:1601] W: [wsicli|0|WS/h1/default/ws2.broker.com]: lws_client_ws_upgrade: got bad HTTP response '403'

**Comment by lws-team** [comment]
Dunno.

GET does not work like that

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

if that server (or perhaps proxy) requires that nonsense you'll have to hack lws to send the crap it wants without the slash.

**Comment by vinifr** [comment]
"if that server (or perhaps proxy) requires that nonsense you'll have to hack lws to send the crap it wants without the slash.". Ok, That was what I thought, really does not make sense!. Alright, thanks.
