### ISSUE TITLE
Infinite loops in SSL handling

### ISSUE THREAD

**Issue by AndyNewmanWelcomDigital** [warmcat/libwebsockets#295]
Using the latest master from git as at 2015-06-18 (commit 3ae1badae7a05e0982e0dfbcb078da3d4b92a81d)
SSL.C line 440 reads:

    if (!wsi->pending_read_list_next && !wsi->pending_read_list_prev) {

and this results in a linked list that loops back onto itself if the item being added was already the only item in the list.  I am fairly sure it should read like this:

    if (!wsi->pending_read_list_next && !wsi->pending_read_list_prev && !(wsi == context->pending_read_list)) {

The infinite linked lists it creates as it stands usually clean up, and so aren't noticed, but sometimes the loop in lws-plat-linux.c in lws_plat_service will spin forever at 100% CPU because it isn't removing an item that links to itself.

**Comment by warmcat** [comment]
It now does perform that test thanks.
