### ISSUE TITLE
[question]  libwebsocket 4.3-stable blocks external main loop 30 seconds with -DLWS_WITH_EXTERNAL_POLL=ON

### ISSUE THREAD

**Issue by dandan626** [warmcat/libwebsockets#2951]
I recently use the 4.3 stable version and compiled it with -DLWS_WITH_EXTERNAL_POLL=ON option.

I found that the poll() blocks 30 seconds, the back trace like this:

lws_service->lws_plat_service->_lws_plat_service_tsi->poll()

using the strace to find below information:

poll([{fd=28, events=POLLIN}, {fd=29, events=POLLIN}, {fd=20, events=POLLIN}], 3, 30000) = 0 (Timeout)

My question is why the libwebsocket still using the poll internally even compiled with  -DLWS_WITH_EXTERNAL_POLL=ON option.

**Comment by lws-team** [comment]
Dunno... but it sounds like you can find out pretty easy by running under gdb and then getting a bt when you ^C.

**Comment by dandan626** [comment]
@lws-team Yes, true.
Interesting thing is, we use the 4.0-stable version, the poll has a 1 second delay but when we upgrade to 4.3 stable, the time out became to 30 seconds.

In the external poll, we have totally 16 fds, but in the poll in the libwebsocket, it only has 3 fds. So when libwebsocket polls, it can't response to other fds' activities.

**Comment by lws-team** [comment]
No... it's just your model of the situation lws is to blame, based on strace telling you it's stuck in a poll().

Your app is a co-production between your code and a bunch of libs, maybe openssl or at least a libc, with a resolver, which may use poll(), as well as lws.

Why don't you take a moment to do what I suggested and objectively show where that poll() is (which will guide us where to look next).

**Comment by lws-team** [comment]
Hmmm... external poll is a crappy hack from a decade ago I have been trying to deprecate ever since (mosquitto latched on to it making it difficult to just get rid of it).  I tries to say it's "not recommended" and replaced it with much better solutions.

At any rate, the idea of it is in the name - External Poll.  The poll happens external to lws when you use it.  You do not call lws service apis.  lws does its wait on your poll(), you do not call lws_service() at all.  They don't fight - it uses your wait.  Just don't call that api.

**Comment by dandan626** [comment]
Maybe another way to avoid the long timeout is to forcely set the timeout value to 0 second before calling the poll, it will return at once. If there is a polled fd, then process it, otherwise, return to the external poll procedure and we can also polled the fds in the inner poll fd sets.

**Comment by lws-team** [comment]
This isn't a new topic... have a read of this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

After 3.2, lws moved completely away from periodic wakes so if nothing to do, he will sleep "forever", wakes are scheduled on the event loop itself.  The README above discusses the options and tells the best way.

**Comment by dandan626** [comment]
Realy thanks @lws-team.

I found an interesting thing that when I called the API with a -1 timeout, It quickly returns.
`	lws_service(g_context, -1);
`
See the timeline as below: (I noticed that the last input argument of poll is 0)
`
04:24:09.450063 poll([{fd=28, events=POLLIN}, {fd=29, events=POLLIN}, {fd=30, events=POLLIN}], 3, 0) = 0 (Timeout)
04:24:09.450662 timerfd_settime(10, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
04:24:09.451175 timerfd_settime(10, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=4, tv_nsec=999502819}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
04:24:09.451615 poll([{fd=30, events=POLLIN}, {fd=34, events=POLLIN}, {fd=35, events=POLLIN}, {fd=33, events=POLLIN}, {fd=26, events=POLLIN}, {fd=24, events=POLLIN}, {fd=22, events=POLLIN}, {fd=20, events=POLLIN}, {fd=18, events=POLLIN}, {fd=16, events=POLLIN}, {fd=14, events=POLLIN}, {fd=12, events=POLLIN}, {fd=11, events=POLLIN}, {fd=10, events=POLLIN}, {fd=9, events=POLLIN|POLLPRI}, {fd=8, events=POLLIN}], 16, -1
`
So I think I can just modify my code to use the -1 as the timeout value and then the API will return at once. It meets my requirement.
