### ISSUE TITLE
 E: info->ka_interval can't be 0 if ka_time used

### ISSUE THREAD

**Issue by disa6302** [warmcat/libwebsockets#2952]
Hello,

I am currently integrating my project with LWS 4.2.2 version. There are times I see this error:

```
E: info->ka_interval can't be 0 if ka_time used
```

However, in my application, I do set these values:

```
struct lws_context_creation_info creationInfo;
creationInfo.ka_time = 3;
creationInfo.ka_interval = 1;
```

When I try to create the LWS context like this:
`struct lws_context *lwsContext = lws_create_context(&creationInfo);`

The lwsContext seems to be NULL. These are the LWS specific logs I see:

```
[2023/08/15 00:26:31:9207] N: LWS: 4.2.1-v4.2.2, loglevel 7
[2023/08/15 00:26:31:9207] N: NET CLI H1 H2 WS ConMon IPv6-absent
[2023/08/15 00:26:31:9207] E: info->ka_interval can't be 0 if ka_time used
```

A little about the build script (I am including this as an ExternalProject:

```
ExternalProject_Add(project_libwebsockets
    GIT_REPOSITORY    https://github.com/warmcat/libwebsockets.git
    GIT_TAG           v4.2.2
    PATCH_COMMAND     ${PATCH_COMMAND}
    PREFIX            ${CMAKE_CURRENT_BINARY_DIR}/build
    LIST_SEPARATOR    |
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${OPEN_SRC_INSTALL_PREFIX}
        -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
        -DLWS_WITH_HTTP2=1
        -DLWS_HAVE_HMAC_CTX_new=1
        -DLWS_HAVE_SSL_EXTRA_CHAIN_CERTS=1
        -DLWS_HAVE_OPENSSL_ECDH_H=1
        -DLWS_HAVE_EVP_MD_CTX_free=1
        -DLWS_WITHOUT_SERVER=1
        -DLWS_WITHOUT_TESTAPPS=1
        -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1
        -DLWS_WITHOUT_TEST_PING=1
        -DLWS_WITHOUT_TEST_CLIENT=1
        -DLWS_STATIC_PIC=1
        -DLWS_WITH_STATIC=1
        -DLWS_WITH_SHARED=${LWS_WITH_SHARED}
        -DLWS_WITH_MBEDTLS=${LWS_WITH_MBEDTLS}
        -DLWS_WITH_MINIMAL_EXAMPLES=1
        -DLWS_HAVE_PTHREAD_H=1 
        -DLWS_WITH_THREADPOOL=${LWS_WITH_THREADPOOL}
        -DLWS_WITH_ZLIB=0
        -DLWS_HAVE_EVENTFD=0
    BUILD_ALWAYS      TRUE
    TEST_COMMAND      ""
)
```
The build uses openssl. Why do I see LWS context creation fail? The interesting part is it is not 100% reproducible, so any leads would be appreciated.

**Comment by lws-team** [comment]
The examples do the `struct lws_context_creation_info creationInfo;` on the stack because they then enter the event loop and the info never goes out of scope until we exit the example.  So lws can always find your info as it was originally written.

It sounds like you have maybe put it on the stack, but then immediately left the function and took it out of scope; the stack memory will be getting reused for random things.

**Comment by disa6302** [comment]
Hmm. Thank you for your response. Could you point me to the sample you are talking about so that I can take a look?

**Comment by lws-team** [comment]
Literally any of the examples that use the default loop.  https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c#n350

**Comment by disa6302** [comment]
@lws-team , 

QQ. I am looking at the example you linked to, that is exactly what I am doing, except once the context is created, I exit the function unlike what is happening here:

```
        while (n >= 0 && !interrupted)
                n = lws_service(context, 0);
```

As you said, the context never goes out of scope until the event loop exists in the examples' case. Does it mean the `lws_context_creation_info` object needs to be in memory for the duration of the application run? 

I am looking at the source code of LWS but I do not see anything needing the `lws_context_creation_info` once context is created. Please correct me if I am wrong. 

Also, this is not a 100% reproducible issue. It seems to be happening frequently, but not every time. The code I have sets up the context in one function and then the context is used in different parts of the codebase when `lws_service` is invoked.
