### ISSUE TITLE
[question] DNS lookups for websockets

### ISSUE THREAD

**Issue by sln-adatt** [warmcat/libwebsockets#2953]
Hi there,

When does libwebsockets websocket code query DNS?

**Comment by lws-team** [comment]
... not sure what you're asking that's specific to lws... when you ask it to resolve an an address.  Eg, making a client connection.

**Comment by sln-adatt** [comment]
The intention was to clarify the frequency of libwebsockets DNS queries (in particular, the calls to getaddrinfo in the synchronous DNS case)...does these happen only at WS connection time? Does libwebsockets perform any DNS caching?

**Comment by lws-team** [comment]
You're welcome to grep the sources...
