### ISSUE TITLE
E: info->ka_interval can't be 0 if ka_time used

### ISSUE THREAD

**Issue by disa6302** [warmcat/libwebsockets#2955]
https://github.com/warmcat/libwebsockets/issues/2952

Opening this since the above issue was closed. 

@lws-team ,

QQ. I am looking at the example you linked to, that is exactly what I am doing, except once the context is created, I exit the function unlike what is happening here:

        while (n >= 0 && !interrupted)
                n = lws_service(context, 0);
As you said, the context never goes out of scope until the event loop exists in the examples' case. Does it mean the lws_context_creation_info object needs to be in memory for the duration of the application run?

I am looking at the source code of LWS but I do not see anything needing the lws_context_creation_info once context is created. Please correct me if I am wrong.

Also, this is not a 100% reproducible issue. It seems to be happening frequently, but not every time. The code I have sets up the context in one function and then the context is used in different parts of the codebase when lws_service is invoked. Also, there is no event where the `creationInfo` could actually be overwritten on stack. It is a single thread program. So I would like to understand the importance of `lws_context_creation_info` better beyond the creation of context.

Providing some code snippets for context:
```
void createContext(MainObj** pmainObj) {
             MainObj* mainObj = (MainObj*) calloc(1, sizeof(MainObj)); // This has a member pLwsContext
             struct lws_context_creation_info creationInfo;
             creationInfo.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
             creationInfo.port = CONTEXT_PORT_NO_LISTEN;
             creationInfo.protocols = pSignalingClient->signalingProtocols;
             creationInfo.timeout_secs = SIGNALING_SERVICE_API_CALL_TIMEOUT_IN_SECONDS;
             creationInfo.gid = -1;
             creationInfo.uid = -1;
             creationInfo.client_ssl_ca_filepath = pChannelInfo->pCertPath;
             creationInfo.client_ssl_cipher_list = "HIGH:!PSK:!RSP:!eNULL:!aNULL:!RC4:!MD5:!DES:!3DES:!aDH:!kDH:!DSS";
             creationInfo.ka_time = SIGNALING_SERVICE_TCP_KEEPALIVE_IN_SECONDS;
             creationInfo.ka_probes = SIGNALING_SERVICE_TCP_KEEPALIVE_PROBE_COUNT;
             creationInfo.ka_interval = SIGNALING_SERVICE_TCP_KEEPALIVE_PROBE_INTERVAL_IN_SECONDS;
             creationInfo.retry_and_idle_policy = &retryPolicy;
             mainObj->pLwsContext = lws_create_context(&creationInfo);
             // other things.....
             pmainObj = mainObj;
      }
```
Then I have a couple of other functions that use LWS to make some API calls where I use this context similar to the one below:

```
void doSomething(MainObj* mainObj) {
           INT32 retVal = lws_service(mainObj->pLwsContext, 0);
}
```

**Comment by lws-team** [comment]
Oh.  You don't memset it to 0 first.  So there is just trash in anything you didn't explictly write.

**Comment by disa6302** [comment]
My bad. I do memset, missed adding that line here when I was adding the snippet.
Kindly reopen. Thanks

**Comment by disa6302** [comment]
I also ended up forking this repo and adding a bunch of notice logs inside the function. And something really weird is happening:

ka_time is set to 3 and ka_interval is set to 2 right before invoking lws_create_context. Howerem the values that actually get printed here: https://github.com/disa6302/libwebsockets-local/blob/add-logs/lib/core/context.c#L371 are 2 and 0. However, right outside the function call, the values are still 3 and 2. So there is some sort of weird structure modification happening and I am not sure where it is coming from.

```
printf("ka values before: %d, %d\n", ka_time, ka_interval); // value is 3 and 2
pSignalingClient->pLwsContext = lws_create_context(&creationInfo); // inside this function, the very first line orints out 2 and 0
printf("ka values after: %d, %d\n", ka_time, ka_interval); // value is 3 and 2
```

**Comment by lws-team** [comment]
It sounds like a problem where the version of the lws includes the different bits of your code are built with are not the same.  For example, you have 3.2 dev package installed that some code is using the includes from that.  Lws that you're linking against is 3.3 or whatever and was built against its own 3.3 includes.

Then all the code think it's doing the right thing, but the layout of the struct differs in each of their opinions and they can't share a common reality.

That's a problem that only exists in your build situation.

**Comment by disa6302** [comment]
Thank you for your response @lws-team !

When you say installed package, do you mean something installed with package manager? Not sure I understand. I have been consistently using 4.2.2 version. Also, if the situation is what you say could be happening, it should be 100% reproducible, but the build structure does not change across builds. Its consistent and has all the flags I added in my previous issue. Is there something I am not understanding here?

**Comment by lws-team** [comment]
I don't have a crystal ball.... if you are saying a struct member has one value from your code and a different value from inside lws, one way that explains how that can happen is as I described - lws and your code built against different lws headers.  On Linux, you can fall into this situation with dev packages installing headers in /usr/include and apps accidentally finding whatever is in there, whether it matches what you wanted or not.

Lws builds against its own in-tree headers, so that can't really go wrong.  Therefore if this is the problem, your app is bringing in wrong lws headers or otherwise has some attribute (eg, sizeof (void *) or sizeof(int)) different from the lws build.

You can prove or disprove if it is the problem by also printing `(int)(((uint8_t *)&info->ka_interval) - (uint8_t *)info)` or similar, its the distance between ka_interval and the start of the info struct.  Is it the same in your code and in lws?  If yes, I dunno.

**Comment by disa6302** [comment]
> lws and your code built against different lws headers. On Linux, you can fall into this situation with dev packages installing headers in /usr/include and apps accidentally finding whatever is in there, whether it matches what you wanted or not.

I see what you are saying. But this would be the case if I installed lws with the package manager. However, I build LWS as an external project from source. 

Anyways, this is a strange problem I am encountering which makes absolutely no sense. I will try printing out the distance and see what happens. Will add my findings here. Thanks for your response.

**Comment by lws-team** [comment]
Just some free advice, if there's a way to objectively check it, do that.  It's good when a thesis tells you how you can cheaply rule it in or out.  It's bad to assume your existing model of what is happening - which has no explanation for what you are observing - was born perfect, and can beat out any other information to the contrary.
