### ISSUE TITLE
Minimal example modification not working

### ISSUE THREAD

**Issue by a412h** [warmcat/libwebsockets#2957]
I am trying to modify the minimal example:
minimal-examples/client/binance
for the Deribit websocket:
https://docs.deribit.com/
By adding the lines:
```
static char subscribe_msg[] = "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"public/subscribe\",\"params\":{\"channels\":[\"deribit_price_index.btc_usd\"]}}";
```
```
    case LWS_CALLBACK_CLIENT_ESTABLISHED:
        lwsl_user("%s: established\n", __func__);
        lws_write(wsi, (unsigned char *)subscribe_msg, sizeof(subscribe_msg) - 1, LWS_WRITE_TEXT);
```
the connection is established and maintained, but no update message is received.
Is there a compatibility problem ? If no, how should I modify the minimal example for this case ?

**Comment by lws-team** [comment]
Why is that anything to do with me?

**Comment by a412h** [comment]
Well, any help would be greatly appreciated.

**Comment by a412h** [comment]
Because any help would be greatly appreciated.
