### ISSUE TITLE
[Bug] Compile error while using mbedTLS-3

### ISSUE THREAD

**Issue by xuchao0915170** [warmcat/libwebsockets#2958]
Hi，

There is a compile error when I build lws-4.3.0 with mbedtls-3.2.1：
![image](https://github.com/warmcat/libwebsockets/assets/31056281/3c20b7c2-56db-4b06-b006-fb017f183d3a)

then I found that `MBEDTLS_PRIVATE` macro is defined twice, both by `libwebsockets.h` and `mbedtls-3.2.1/include/mbedtls/private_access.h`：
![image](https://github.com/warmcat/libwebsockets/assets/31056281/81a01cf3-8d58-4c55-9c98-4075aa792e89)
![image](https://github.com/warmcat/libwebsockets/assets/31056281/345bbbf5-1a5f-4025-824c-d226e8689d10)

I deleted  the macro from `private_access.h`, and it worked. But I'm aware that it is not the best way to fix this issue.
So I report this, and hope you guys will find a better way.

Thanks!

**Comment by lws-team** [comment]
This problem doesn't exist on the combination of later lws and later mbedtls.  You might want to use last stable lws (v4.3-stable  branch) at least.
