### ISSUE TITLE
LibWebsocket Crash when Server Restarts (With Compression, Deflate Protocol applied)

### ISSUE THREAD

**Issue by Anu2599** [warmcat/libwebsockets#2959]
Hello,
I am using Libwebsocket 2.3.0 Version.
First of all, it's an old version. However, my code is compatible with this version only. Tried to port to upper versions. But, it's a separate task for me. If possible current issue needs to be solved with this version only.

I am facing an issue with Server Restart given Compression is enabled.

Previously I was working without Compression and in that process destroys context and vhost smoothly and reconnects to Server without any crash.
After this new connection establish and no crash.

I tried my best to figure out the reason behind such abnormal behavior in case of compression. But, unable to do so.
Please guide me on this.
What's the exact reason and how it could be handled.

Thanks in advance.

**Comment by lws-team** [comment]
> What's the exact reason and how it could be handled.

Why would I know... this is your (C++) code that happens to link to some ancient lws.

Your best move is 1) Use latest lws and 2) if still problems, run it under valgrind to get the earliest indication of where it goes off the rails, at your code or lws.
