### ISSUE TITLE
Question: how to send extensions from client

### ISSUE THREAD

**Issue by kvasilye** [warmcat/libwebsockets#2960]
Hi,

Sorry for posting a question here but I can't figure it out from the docs / header files.

I'm trying to make a LWS client negotiate a custom extension. Tried doing this:

```
static lws_extension gExtensions[] =
{
        { "foo", extension_callback_ext_foo, "foo" },
        { nullptr, nullptr, nullptr }
};

void connect(....) {
    ...

    struct lws_context_creation_info creationInfo
    creationInfo.extensions = gExtensions;

    ....
}
```

The connection is established, but the request to the server does not contain the `Sec-WebSocket-Extensions` header.

The extension callback function on the client isn't getting called either.

What am I missing?

**Comment by lws-team** [comment]
New extensions aren't something you can create so casually... the stuff you're using is just enabling an existing extension, in fact the only extension that was defined AFAIK, permessage_deflate.

Implementing permessage-deflate requires deep hooking, so there is a whole other api to manage extensions getting their own callbacks for internal activity

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-ws-ext.h

... and the business end of the extension is implemented internal / private.

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/ws/ext

... do you really need an extension?   Or just a protocol...

**Comment by kvasilye** [comment]
Thank you. Might be able to use a protocol - I just need to negotiate _something_ between the client and the server during the initial round-trip.

A related question - how do I enable the standard deflate compression (assuming it's already enabled on the server side)? I've seen sample code snippets but they seem rather terse.

**Comment by lws-team** [comment]
> I've seen sample code snippets but they seem rather terse.

It only takes a few lines, isn't that a good thing?

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-binance/main.c#n106-115

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-binance/main.c#n354

**Comment by kvasilye** [comment]
Thank you. I enabled the extension by copying the code from the sample and also built LWS with `LWS_WITH_HTTP_STREAM_COMPRESSION=ON`

But when I dump client request headers on the server, I don't see `Sec-WebSocket-Extensions`.

Here is what I see:

```
Header: Upgrade = [websocket]
Header: Sec-Websocket-Version = [13]
Header: User-Agent = [foobar]
Header: Pragma = [no-cache]
Header: Origin = [https://foobar.com]
Header: Connection = [Upgrade]
Header: Sec-Websocket-Key = [bUTxQzOadD0j5ENB/8Q0RA==]
Header: Sec-Websocket-Protocol = [blah.blah.blah]
Header: Cache-Control = [no-cache]
```

**Comment by kvasilye** [comment]
Checking `lws-config.h` I see:

```
#define LWS_WITH_HTTP_STREAM_COMPRESSION
...
#define LWS_WITH_GZINFLATE
```

**Comment by lws-team** [comment]
> LWS_WITH_HTTP_STREAM_COMPRESSION

That is something completely different, it says 'http stream'.

`-DLWS_WITHOUT_EXTENSIONS=0`

**Comment by kvasilye** [comment]
Yep working now, thank you!
