### ISSUE TITLE
undefined symbol: lws_http_transaction_completed

### ISSUE THREAD

**Issue by kvasilye** [warmcat/libwebsockets#2962]
Hello,

I'm using LWS as client only, on Android, cross compiling with CMake.

Trying to enable compression, I added `LWS_WITH_HTTP_STREAM_COMPRESSION=ON` and unfortunately LWS builds are now failing with

```
  ld: error: undefined symbol: lws_http_transaction_completed
  >>> referenced by ops-h1.c:618 (/.../android/.cxx/Debug/463m5v3m/arm64-v8a/external/src/Websockets/lib/roles/h1/ops-h1.c:618)
  >>>               ops-h1.c.o:(rops_handle_POLLIN_h1) in archive external/lib/libwebsockets.a
```

I tried the current head commit of LWS and the issue is present there.

The LWS CMake configuration:

```
            -DOPENSSL_INCLUDE_DIRS=${OPENSSL_INCLUDE_DIRS}
            -DOPENSSL_LIBRARIES=${OPENSSL_LIBRARIES}
            -DLWS_WITH_SSL=ON
            -DLWS_WITH_BORINGSSL=ON
            -DLWS_WITH_SHARED=OFF
            -DLWS_WITH_HTTP_STREAM_COMPRESSION=ON
            -DLWS_HAVE_LIBCAP=OFF
            -DLWS_WITHOUT_SERVER=ON
            -DLWS_WITHOUT_TESTAPPS=ON
```

Changing `LWS_WITHOUT_SERVER=ON` to `LWS_WITHOUT_SERVER=OFF` fixes the error, but I would like to continue building LWS as a client only library, without the server.

**Comment by lws-team** [comment]
As pointed out, this isn't actually the option you want for ws extensions.  And you can just continue to enable the (default on) server support build to get around it.  Or send a patch.
