### ISSUE TITLE
Password in Proxy Credentials

### ISSUE THREAD

**Issue by SreedharRe** [warmcat/libwebsockets#2964]
Hi,
  Password provided in username:password@proxy , I presume takes only plaintext password - which is a security concern for us. Is there any way to pass encrypted password with type 6 or any mechanism to secure it from being shown is plain text to users?
Regards,
Sreedhar

**Comment by lws-team** [comment]
... what kind of proxy are we talking about, http_proxy?  Something else?

**Comment by SreedharRe** [comment]
Hi,
  Yes.. About http_proxy

**Comment by lws-team** [comment]
So http_proxy is usually set in an env var, lws also supports that.  But it's in plaintext.

If it's encrypted, I don't know that really helps when it is decrypted on running the app, they can just use a copy of the "encrypted" credentials with a copy of the app as much as they like without needing to know the actual password to the proxy.

You can set the proxy explicitly (including auth) with

```
/**
 * lws_set_proxy() - Setups proxy to lws_context.
 * \param vhost:        pointer to struct lws_vhost you want set proxy for
 * \param proxy: pointer to c string containing proxy in format address:port
 *
 * Returns 0 if proxy string was parsed and proxy was setup.
 * Returns -1 if proxy is NULL or has incorrect format.
 *
 * This is only required if your OS does not provide the http_proxy
 * environment variable (eg, OSX)
 *
 *   IMPORTANT! You should call this function right after creation of the
 *   lws_context and before call to connect. If you call this
 *   function after connect behavior is undefined.
 *   This function will override proxy settings made on lws_context
 *   creation with genenv() call.
 */
LWS_VISIBLE LWS_EXTERN int
lws_set_proxy(struct lws_vhost *vhost, const char *proxy);
```

Where you got the string from and how the ingredients were obfuscated is up to you then.
