### ISSUE TITLE
Obtaining the connection URI of a client that requests an upgrade to a WebSocket connection

### ISSUE THREAD

**Issue by tomomomo0000** [warmcat/libwebsockets#2969]
Hi.

I am creating a websocket server with libwebsocket.

When a websocket connection request comes in from a client, is there any way to get the connection URI before the connection is completed?

I can get it with the LWS_CALLBACK_HTTP argument "in" for clients that are not requesting to upgrade to a websocket connection, but I cannot get it for clients that are requesting to upgrade to a websocket connection.

**Comment by lws-team** [comment]
> I can get it with the LWS_CALLBACK_HTTP argument "in" for clients that are not requesting to upgrade to a websocket

Right... it's not quite what you want but you can get it at ESTABLISHED, and the http headers are still available at that point.  Until you leave ESTABLISHED with a 0 return, no information has been transferred from the server using ws.

**Comment by tomomomo0000** [comment]
I understood.

I would like to check client information during a session and cancel the session if the client is unexpected. 
Is there any way to do this? For example, IP address.

**Comment by tomomomo0000** [comment]
Self resolved.

Since I can get the http header with LWS_CALLBACK_HTTP_CONFIRM_UPGRADE, I will check the connection URI there.

Thanks for your response.
