### ISSUE TITLE
If an unsupported protocol is received from the client.

### ISSUE THREAD

**Issue by tomomomo0000** [warmcat/libwebsockets#2971]
If I receive an unsupported protocol from a client, can I send a response without the Sec‑WebSocket‑Protocol header?

Even if a client connects using a protocol that does not match the protocol name registered on the server, I would like to connect with the client by sending a response without the Sec-WebSocket-Protocol header.

Even if I set the first argument of protocol to "default" or "", I was not satisfied.

struct lws_protocols protocols[] = {
     { "default", callback_default, 0},
     { NULL, NULL, 0 }
};

struct lws_protocols protocols[] = {
     { "", callback_default, 0},
     { NULL, NULL, 0 }
};

**Comment by lws-team** [comment]
You're coming at it from the wrong end... what if you need two or more ws connections to different servers with different protocols requirements?

IIRC for a client connection that uses this unwise "no protocol header" thing, just leave this NULL

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n130-131
