### ISSUE TITLE
Reading byte-by-byte vs. chunks

### ISSUE THREAD

**Issue by kutoga** [warmcat/libwebsockets#2972]
Hello

First of all thanks for the libwebsockets library. I use it daily and it works great for my use-cases.

This issue describes more a question and it's not really a problem:

The function `lws_ws_handshake_client` copies the payload of a websocket frame into its own buffer. This is done by [calling `lws_ws_client_rx_sm` for each byte](https://github.com/warmcat/libwebsockets/blob/7ef2065fdf38f74d196238ebc618b7009e25e408/lib/roles/ws/client-ws.c#L82C15-L82C15). `lws_ws_client_rx_sm` finally [copies the byte into the target buffer](https://github.com/warmcat/libwebsockets/blob/main/lib/roles/ws/client-parser-ws.c#L350).

Is there a reason why this is not done with a single `memcpy` (compared to doing a func-call for each byte)? Maybe it's conceptually not possible. Sorry for asking in that case. I'm just curious about that, because this could bring some performance benefit.

Thanks a lot

**Comment by lws-team** [comment]
As I recall the major considerations were around correctness and security under all conditions

 - the variety of problems / corner cases possible with coalescing of the http -> ws or raw transition (or even http -> eg, compressed http) inside a single packet... on any given byte (the end of the headers) there may be major side-effects on state that completely change how the remaining buffer must be dealt with.

 - On other kinds of parsing there is the possibility of fragmentation attacks, that's eliminated by this bytewise state machine approach for both h1 and h2 headers.

For bulk data (as opposed to http headers) the data is collected and provided in blocks (also accounting for http chunking and compression if still in http, or ws fragment size / extensions for ws), for a given http transaction or ws connection, this only happens per transaction or once per ws establishment.  It depends on your compiler if there's really a function call there or if the function is inlined inside the loop.  It never made a bottleneck for anything I used it for so it's as it is.

**Comment by kutoga** [comment]
Thanks for the explanation:)!
