### ISSUE TITLE
Example for two contexts?

### ISSUE THREAD

**Issue by dylanetaft** [warmcat/libwebsockets#2978]
Is there an example for two contexts - ie two lws_context_creation_info structs have been populated, one for a listening port, one for a client connecting to another service - and wanting one event loop or event library to manage both?

I originally went the route of using the LWS_CALLBACK_ADD_POLL_FD, LWS_CALLBACK_DEL_POLL_FD, LWS_CALLBACK_CHANGE_MODE_POLL_FD callbacks - and maintaining a list of FDs - but I ran into portability issues on windows.

All of the examples I see are for managing a client or server socket, not both, so far.

**Comment by dylanetaft** [comment]
I may need to review more documentation, I may be able to use the same context, and use lws_connect_via_info to connect to multiple endpoints.  If I can use one single context, I think I can just use default event handling.  There's not a good example of this I don't think.

**Comment by dylanetaft** [comment]
Yeah, I went down the wrong path entirely with this.
Listening Sockets:
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-multivhost

Client Sockets:
Haven't tested, but lws_client_connect_via_info

**Comment by lws-team** [comment]
Right... content == event loop.  So you just want the one of those so everything is in the same thread context, and so no need for locking.  You can have as many vhosts and client connections ongoing as you like on the one lws_context.
