### ISSUE TITLE
IPV6_PREFER_SRC_PUBLIC socket option for lws_client_connect_via_info()?

### ISSUE THREAD

**Issue by dylanetaft** [warmcat/libwebsockets#2979]
Libwebsockets doesn't offer a way to get at the socket fd prior to connect to set an option, does it?

I see lws_client_connect_info stuct has an iface option that can take an IP.   I don't think IPV6_PREFER_SRC_PUBLIC works on Windoes, just Posix\Linux.  

Windows, the standard is to try to identify the IP off enumerating network devices to the best I can tell if you do not want to use the IPV6 privacy address outbound.  

I want to connect outbound on a SLAAC IPV6 configured host with privacy address using the public network IP. 

I am going down a rabbit hole of using libnl to grab the kernel's route table, the default route, and then the network interface, and pulling addressses off of it, and I can feed that to the iface field in the LWS struct I suppose. 

The other option I think would be to I think getsockname() off a socket established with that option to get the address the OS used with that hint, and then feed that to iface. 

I see the socket fd in the lws struct but accessing it is probably not a normal thing to do.

**Comment by lws-team** [comment]
> I am going down a rabbit hole of using libnl to grab the kernel's route table,

Lws knows about netlink, and a single process can only open a single netlink socket at a time.  libnl has an incompatible license for lws so it has to do its own.  You can iterate network interfaces in a kinda-standard way with getifaddrs() too.  But it sounds you just want lws to set a socket flag.

> Libwebsockets doesn't offer a way to get at the socket fd prior to connect to set an option, does it?

No but you can add it quicker than fiddling with libnl and send a patch.

enum lws_client_connect_ssl_connection_flags in include/libwebsockets/lws-client.h declares a load of option flags including ones to control IP options.  You can add one here (you probably want to use currently absent 1 << 15 one) for your feature, something like LCCSCF_IPV6_PREFER_PUBLIC.  You can set this flag in `client_creation_info.ssl_connection` in your code when creating the info struct for the client creation call (it uses that for historical reasons).

`lws_plat_set_socket_options_ip()` in the platform-specific code (ie, there are different implementations of it per platform) is called just after client socket creation.  You can test the flag in there (see the linux one in `lib/plat/unix/unix-sockets.c` for an already-existing example of testing for those flags) and set your socket option in there.  I don't know either what windows wants but you can do whatever that is in the implementation in `lib/plat/windows/windows-sockets.c` the same way.

**Comment by dylanetaft** [comment]
Ok, how is this as a general statement?  I need to do a bit more testing but it appears to be working,

**Comment by dylanetaft** [comment]
As for Windows, I am going to dig a bit more into it.  I am going to post on MSDN Q\A.  I do not see that Microsoft supports it as a sockopt. As far as a standard, it looks like IBM AIX and Linux support RFC 5014.

Windows may require something weird, where you identify the interface upon a connection initiation, and then enumerate the IPs and pick the one that has the longest TTL.  That would be done outside libwebsockets, and it would be appropriate to stuff the ip in lws_client_connect_info::iface

Maybe MSDN Q\A devs have a better answer.

**Comment by dylanetaft** [comment]
Closing, I will update with Windows code as a sample when I have it.  MS definitely doesn't support the standard and one would have to just bind the socket to the right IP.
