### ISSUE TITLE
Documentation for using LWS with CMake\git submodule?

### ISSUE THREAD

**Issue by dylanetaft** [warmcat/libwebsockets#2981]
It's pretty straightforward with cmake's find_package if you your evironment supports pkg_config, ie  msys2 or a normal Linux env.

I am trying to use LWS now pulled down with git as a submodule in my project's repo and static link.

I made a quick test case...well it wasn't quick, it took me now 4 hours of looking at sources and reading and asking ChatGPT questions 😂
Is this "correct?"

https://github.com/dylanetaft/lws_cmake_testcase
I found stuff in LibwebsocketsTargets.cmake - definitions for libraries for static linking, and include directories. 

I am not seeing any examples anywhere for building LWS as a submodule of an existing project and static linking.  I see a few questions in issues here on cmake builds.  This DOES work, I am not sure if it is "right" :)

cmake_minimum_required(VERSION 3.12)
project(tc)
#set(CMAKE_C_COMPILER gcc)
#set(CMAKE_CXX_COMPILER g++)
OPTION (LWS_WITH_MINIMAL_EXAMPLES "" OFF)
OPTION(LWS_IPV6 "" ON)
add_subdirectory(extern_libs/libwebsockets)

add_executable(test testcase.c)
target_link_libraries(test websockets)
target_include_directories(test PRIVATE LIBWEBSOCKETS_INCLUDE_DIRS)

**Comment by lws-team** [comment]
Like cross-build with cmake, this is a generic cmake thing.  It doesn't scale that every project using cmake is supposed to run around documenting how cmake works in all its aspects to make up for cmake not doing it.
