### ISSUE TITLE
The client frame set the reserved bits to [4] for a message with opCode [7] which was not supported by this endpoint

### ISSUE THREAD

**Issue by NoahJinghao** [warmcat/libwebsockets#2982]
the issue was happened when I try to send a message by libwebsockets
![image](https://github.com/warmcat/libwebsockets/assets/148037603/fecec771-6929-4e49-a22c-71b7827cf662)

and here is my code:
![image](https://github.com/warmcat/libwebsockets/assets/148037603/f35ade35-31fa-41a6-b58d-f16612f9c2f7)
Looking forward to your reply, thanks

**Comment by lws-team** [comment]
You are calling lws_write() for ws with `LWS_WRITE_HTTP`?

**Comment by NoahJinghao** [comment]
> You are calling lws_write() for ws with `LWS_WRITE_HTTP`?

yes，Here is my code
![image](https://github.com/warmcat/libwebsockets/assets/148037603/7a449ffe-2038-4871-a10e-2dec9ea3a20d)

**Comment by lws-team** [comment]
Yeah.  I am asking it, but I mean to say gently, "do not do that".

If you look at the examples

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-tx/minimal-ws-client.c#n237-238

and the options for what can go there

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-write.h#n36-70

... you will see the problem.

**Comment by NoahJinghao** [comment]
> Yeah. I am asking it, but I mean to say gently, "do not do that".
> 
> If you look at the examples
> 
> https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/ws-client/minimal-ws-client-tx/minimal-ws-client.c#n237-238
> 
> and the options for what can go there
> 
> https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-write.h#n36-70
> 
> ... you will see the problem.

Thanks for your reply, But if use LWS_WRITE_HTTP, I can't see the string I want to send by wireshark, is it a normal phenomenon;
It's the string send by websocket:
![image](https://github.com/warmcat/libwebsockets/assets/148037603/e0cec222-3838-4d26-b06e-f53d4b221ca7)
![image](https://github.com/warmcat/libwebsockets/assets/148037603/6300b4c0-aae8-42ee-a4f8-c4899f907fff)
the real string I wanna send:
{"method":"p2pMessage","param":{"description":"CAASEQoNAQTAqO4BBAKfRgUBABAA","session":"f6a82a75-2cfc-a06e-c0e6-17a43cde0ec3"}}\n

**Comment by lws-team** [comment]
https://datatracker.ietf.org/doc/html/rfc6455#section-5.3
