### ISSUE TITLE
lws_client_connect_via_info - how to add additional protocol(s)?

### ISSUE THREAD

**Issue by dylanetaft** [warmcat/libwebsockets#2986]
I turned this into a minimal test case
See comments "THIS" and "AND THIS"
You can set protocols in
lws_context_creation_info
You can also seemingly add them with lws_create_vhost()

There's no parallel with clients - to be able to define a protocol and add it to the LWS context, is there?

I DO see you can bind a client connection to a VHOST, but it's not clear what that is for.

https://libwebsockets.org/lws-api-doc-main/html/group__client.html#structlws__client__connect__info

I am building a small p2p app, so like a C++ class will both have a listening server socket plus clients that use the same underlying protocol - like a gnutella "servent".

The overall LWS context is created outside of that class, and a pointer is passed in.

Do I want lws_plugins_init(), maybe?  Or, when would you bind a client socket to a vhost?  What is the parallel to adding a protocol for a client, like you can with a vhost?

I could, I guess, in the C++ class that I am making, have a getProtocols() function that returns lws_protocols, and add them to LWS at the point of context creation.

This threw me for a loop a bit.  I am checking issues and sources before posting, sorry for so much communication here.

#include <libwebsockets.h>
#include <string.h>

static int callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    switch (reason) 
    {
        case LWS_CALLBACK_CLIENT_ESTABLISHED:
            lwsl_notice("I am a client that connected to a server");
            break;
        case LWS_CALLBACK_ESTABLISHED:
            lwsl_notice("I am a server and a client connected to me");
            break;
        case LWS_CALLBACK_PROTOCOL_INIT: //server is ready
            lwsl_notice("Initialize");
            break;
    };
    return 0;
};

static int http_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    return 0;
};

int main() {

    struct lws_http_mount mnt;
    memset(&mnt,0,sizeof(struct lws_http_mount)); 
    mnt.mountpoint = "/p2p";
    mnt.protocol = "p2p";
    mnt.origin_protocol = LWSMPRO_CALLBACK; //use proto callback
    mnt.mountpoint_len = strlen(mnt.mountpoint);

    struct lws_protocols protos[3];
    memset(&protos[0],0,sizeof(struct lws_protocols));
    protos[0].name = "http";
    protos[0].callback = http_callback;
    memset(&protos[1],0,sizeof(struct lws_protocols));
    protos[1].name = "p2p";
    protos[1].callback = callback;
    memset(&protos[2],0,sizeof(struct lws_protocols)); //list terminator

    struct lws_context_creation_info ctx_info;
    memset( &ctx_info, 0, sizeof(ctx_info) );
    ctx_info.options = LWS_SERVER_OPTION_EXPLICIT_VHOSTS|LWS_SERVER_OPTION_HTTP_HEADERS_SECURITY_BEST_PRACTICES_ENFORCE;
    ctx_info.gid = -1;
    ctx_info.uid = -1;
    //ctx_info.protocols = protos; //////////THIS

    struct lws_context *ctx = lws_create_context( &ctx_info );
   
    struct lws_context_creation_info ctx_info2;
    memset( &ctx_info2, 0, sizeof(ctx_info2) );
    ctx_info2.port = 8080;
    ctx_info2.protocols = protos; ///AND THIS
    ctx_info2.mounts = &mnt;
    ctx_info2.vhost_name = "p2p";

    if (!lws_create_vhost(ctx, &ctx_info2)) {
        lwsl_err("Failed to create second vhost\n");
        return -1;
    }
            lwsl_notice("HI!!");
            struct lws_client_connect_info c_info;
            memset(&c_info,0,sizeof(c_info));
            c_info.address = "127.0.0.1";
            c_info.port = 8080;
            c_info.protocol = "p2p";
            c_info.context = ctx;
            c_info.path = "/p2p";
            lws_client_connect_via_info(&c_info);
    while( 1 )
	{
		lws_service( ctx, 0 );
	}  

}

**Comment by dylanetaft** [comment]
If it's not clear, I am expecting LWS_CALLBACK_PROTOCOL_INIT  to be called once for the client connection, and once for the vhost, as it would be if I add the protocol at the context level first.

I don't think the client can find the protocol handler without it first being added to the LWS context, so the client callbacks won't work.  In some other test code I have I wasn't even seeing a warning that the client connection can't find the protocol handler, that's what made me write the test case to figure it out.

**Comment by dylanetaft** [comment]
Hm...no this is a chicken and egg scenario.  The LWS context needs to be created first before you can create vhosts or client connections on it.  I don't see a way to add protocols after a context has been created outside of adding new vhosts which don't make sense for client sockets I don't think.    lws_plugins_init() could be used but it really looks like it's meant to load externally compiled plugin libraries.

I think the least obtuse thing for me to do is to build some sort of data structure that contains a list list of a list of lws_protocols to bootstrap lws_context with.  Each class can initialize it's own list of protocols it manages, and then an external controller class can just compile everything into a single std::vector and I can pull the array with .data()

I have a workaround, that's good enough I think.    I'm going to close this.  If this is egregious wrong, please correct me.  If not, someone else will see it, there's a pretty good knowledge base built up in the closed issues list.

**Comment by dylanetaft** [comment]
Hm...no this is a chicken and egg scenario. The LWS context needs to be created first before you can create vhosts or client connections on it. I don't see a way to add protocols after a context has been created outside of adding new vhosts which don't make sense for client sockets I don't think. lws_plugins_init() could be used but it really looks like it's meant to load externally compiled plugin libraries.

I think the least obtuse thing for me to do is to build some sort of data structure that contains a list list of a list of lws_protocols to bootstrap lws_context with. Each class can initialize it's own list of protocols it manages, and then an external controller class can just compile everything into a single std::vector and I can pull the array with .data()

I have a workaround, that's good enough I think. I'm going to close this. If this is egregious wrong, please correct me. If not, someone else will see it, there's a pretty good knowledge base built up in the closed issues list.

**Comment by lws-team** [comment]
> I DO see you can bind a client connection to a VHOST, but it's not clear what that is for.

The vhost contains the SSL_CTX the client connection will go out on, eg, what CAs it will trust.  You can have different vhosts with different trust for different purposes, and bind your client to the appropriate one for its purpose.

>  What is the parallel to adding a protocol for a client, like you can with a vhost?

Protocol plugins are a context thing.  Lws looks for and loads any it finds .so style at runtime.  All vhosts can see these.

code protocol lists are a vhost thing.  So you have the protocol available in the vhost, and bind the client connection to the vhost.

If you are using ws, which protocol is actually used is negotiated at upgrade-time.   You can set the initial protocol binding for the connection with client connection info `.local_protocol_name`.

To deal with protocol plugins, for backwards compatibility if you only have the default vhost, then all protocols known to the vhost, including plugins, are negotiable on it.  If you have multiple vhosts, you also have to pass pvos to the vhost enabling specific protocols on that vhost.  This is for the case some of the available protocols are sensitive and should not appear to all users of all vhosts.  Eg, this kind of thing to enable my-protocol at vhost-creation time.

```
static const struct lws_protocol_vhost_options pvo = {
    NULL,
    NULL,
    "my-protocol",
    ""
};

...

    vhost_info.pvo = &pvo;
...

**Comment by dylanetaft** [comment]
Hm, thanks!  So maybe it is appropriate to use VHOSTs here.  I can bind the client to the server vhost with the client creation info struct. What's throwing me off is because I am familiar with vhosts in Apache and Lighttpd, or server blocks in nginx.    It's sorta parallel to that in LWS, vhost creation structs have a lot in them that don't have anything to do with client side connections so it was throwing me off.

**Comment by lws-team** [comment]
Yes vhosts were originally just a server thing.  But in lws a lot of the infrastructure (like SSL_CTX) is reused for client connections too (which apache doesn't have the problem to support).
