### ISSUE TITLE
Question: how to match request and response using libwebsocket http2?

### ISSUE THREAD

**Issue by guoxiaoyong** [warmcat/libwebsockets#2988]
When using http2 client to send multiple requests, how do we match the returned responses with the requests? 
What is the idiomatic way of doing this in libwebsocket?

I have read this article
[HTTP/2 and How it Works](https://cabulous.medium.com/http-2-and-how-it-works-9f645458e4b2)

which says:

> Moreover, the corresponding request and response are sharing the same stream ID. With it, the browser can match its requests and responses.

But in this [example](https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/http-client/minimal-http-client/minimal-http-client.c), I don't see stream_id or sid in the callback parameter.

**Comment by lws-team** [comment]
Each connection has its own `wsi` in lws, it's true for client, server, http, ws or whatever.

The wsi comes as an argument to the protocol callback, when callbacks are happening on the related connection.

For client, when you create the connection, you can use `info->opaque_user_data` to ensure when the wsi is created, it's tagged with your own pointer or int or whatever you put in there.  In the callback later, for callbacks that come from a real wsi, you can call `lws_get_opaque_user_data(wsi)` to recover the value you gave it and use that to understand "which connection it is".

**Comment by guoxiaoyong** [comment]
`info->opaque_user_data`  stores per-connection data, not per-request data.  

Consider this scenario:
1. `wsi` is created and an http2 connection established
2.  send request A and request B (req B sent before any response is received)
3.  2 responses received,  { "status": "success"}, {"status": "failed"},  how do I know  which responses matches which requests? Is it that request A succeeded and B failed or B succeeded and A failed?

To my understanding, Http2 uses stream id to do this request-response match.  When a http2 request is sent, a stream id is assigned, say stream-id = 3, later a response is received, we check the response 's stream id, if it is 3, then this response matches the request, otherwise it belongs to another request.

In python hyber library, which support http2, the usage is like this:
```python
from hyper import HTTPConnection
c = HTTPConnection('http2bin.org')
first = c.request('GET', '/get', headers={'key': 'value'})
second = c.request('POST', '/post', body=b'hello')
third = c.request('GET', '/ip')
second_response = c.get_response(second)
first_response = c.get_response(first)
third_response = c.get_response(third)
```

Each time conn.request is called, a stream id is returned, later we use this stream id to get the corresponding response.

So My question is: how to do similar thing in libwebsocket?

**Comment by guoxiaoyong** [comment]
Thank you very much for the detailed explanation, it solves my problem.
