### ISSUE TITLE
ml.libwebsockets.org

### ISSUE THREAD

**Issue by danimihalca** [warmcat/libwebsockets#299]
Hello,

I have recently started to use libwebsockets, and whenever I was searching for issues regarding my miss-usage on Google, different mailing list related posts appeared in my search list (from ml.libwebsockets.org).
My problem is that I cannot connect to that website.
Is this website still up? Is there somewhere a backup of the mailling list?

Thanks!

**Comment by select-this** [comment]
The mailing list appears to have had intermittent stability issues over the last few days; at the time of writing, it's back up, but I've seen it go AWOL multiple times so who knows whether it'll stay that way.

**Comment by danimihalca** [comment]
Ok, I understand.
I thought I had some issues connecting to the mailing list (blocked IP/country).
Thanks for notifying me that it is back up and explaining the situation!
