### ISSUE TITLE
Question: how to parse custom header in the http2 lws client?

### ISSUE THREAD

**Issue by MengXii** [warmcat/libwebsockets#2991]
Example,In http/1.1, I can
```
case LWS_CALLBACK_RECEIVE_CLIENT_HTTP: { 
  if (lws_hdr_custom_length (wsi, "dnt:", 4) < 0) {
     // xxx 
  } else { 
   char value[32];
    auto n = lws_hdr_custom_copy(wsi, value, sizeof(value), "dnt:", 4); 
  } 
} 
```

**Comment by lws-team** [comment]
Looking at the related sources (`lib/roles/http/parsers.c:598`), it's not supported for h2 in lws.

**Comment by MengXii** [comment]
thanks

**Comment by sikalyur** [comment]
Is there any other way to read custom headers for http/2 connection in http server or it is impossible for now?

**Comment by lws-team** [comment]
Obviously h2 does parse headers in order to function, you can add headers to the list of tokens that knows and regenerate the parsing table so it treats them as normal headers.
