### ISSUE TITLE
[Question] Is it possible to have both an HTTP client and server in a libwebsockets application?

### ISSUE THREAD

**Issue by Dolphindalt** [warmcat/libwebsockets#2996]
Hello libwebsockets maintainers,

I am writing an application that requires both an HTTP server and an HTTP client for two way communication. My HTTP server implementation is working just fine and I plan to also add HTTP client code to the http_callback function but I wanted to know if this is doable with libwebsockets as there is no example for both an HTTP client and server in a single application.

Best,
Dalton

**Comment by lws-team** [comment]
There is actually an example of this in

https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c

It's complicated a bit by the foreign loop pieces but it does show how to do it.

Multiple vhosts and as many client connections as you like can be ongoing in the same context ok.

**Comment by Dolphindalt** [comment]
Thank you for the quick response! I will take a look at the example.
