### ISSUE TITLE
Can't compile on x86_64 platforms

### ISSUE THREAD

**Issue by ackfull** [warmcat/libwebsockets#300]
Hi

While compiling on armv61 works fine, i can't compile libwebsockets on my x86_64 platforms. I get the following error

cmake ..

...

/user/bin/ld: CMakeFiles/websockets_shared.dir/lib/base64-decode.c.o: relocation R_X86_64_325 against '.rodata' can not be used when making a shared object; recompile with -fPIC.

How can i do this? I don't have any knowledge about cmake and it's outputted files.

Thank you! :)

**Comment by warmcat** [comment]
I build it on x86_64 all the time.

Nuke your cmake build dir and redo in a fresh one.
