### ISSUE TITLE
v4.3.2 lwsws *** stack smashing detected ***: terminated on cgi request

### ISSUE THREAD

**Issue by nikitos1550** [warmcat/libwebsockets#3005]
Hello!

I am running libwebsockets 4.3.2 lwsws with cgi script and it fails for some reason.

For some reason after lwsws fails it does not exit, process is still alive, but it cannot serve any requests (even cannot serve ordinary files), I have to kill it with Ctrl+C.

I am looking for any debug suggestions and improving lwsws.

Here is large run log https://pastebin.com/c7wdvMTE (it is too big to post here)

**Comment by lws-team** [comment]
Build using -DCMAKE_BUILD_TYPE=DEBUG and run it under valgrind or gdb, this error is detected processwide and can come from any code in the failing process using your libc, not just lws.
