### ISSUE TITLE
Websocket binary payload gets segmented 

### ISSUE THREAD

**Issue by fun-works** [warmcat/libwebsockets#3009]
We have a client which uses libwebsocket and server which uses something else(not sure though). When the LWS client sends a payload of around 500 bytes, it gets fragmented into multiple chunks and sent out. I have no clue where to look to avoid this as the payload is not large enough to get fragmented.

With any other clients, with same server messages are fine. So, I think the server is fine but the client with LWS has some issues.

Could you please point me to some configuration issues I could have ?

**Comment by lws-team** [comment]
> it gets fragmented into multiple chunks and sent out

You meant ws fragments?  Or tcp packets?

It's not strange if one ws fragments goes out in several tcp packets, it's inevitable on most networks when the size gets near the network MTU.  Lws will do it earlier depending on the protocol's rx_buf_size setting.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-protocols-plugins.h#n57

lws leaves it up to you how to cut your payload into ws fragments.

**Comment by fun-works** [comment]
Thanks for the reply. This is resolved now.
