### ISSUE TITLE
getaddrinfo leak in libwebsockets_get_peer_addresses

### ISSUE THREAD

**Issue by danimihalca** [warmcat/libwebsockets#301]
Hello,

I recently ran a websocket server with valgrind and saw that libwebsockets_get_peer_addresses has some memory leaks (ipv4 library version):

==30515==    at 0x4C29F90: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30515==    by 0x59BA660: gaih_inet (in /usr/lib/libc-2.21.so)
==30515==    by 0x59BCE6D: getaddrinfo (in /usr/lib/libc-2.21.so)
==30515==    by 0x4E3A8C8: libwebsockets_get_addresses (libwebsockets.c:353)
==30515==    by 0x4E3B2C7: libwebsockets_get_peer_addresses (libwebsockets.c:425)

Issue #255 had a solution for the leaks caused by getaddrinfo and was later comitted https://github.com/warmcat/libwebsockets/commit/7fb366a9ef6d232699a3066882a031fb212a7b43 .

Could something similar be applied for  libwebsockets_get_peer_addresses ?
I tried to do the same way and now valgrind says that there are only some reachable blocks in the same function caused by getnameinfo:

[...]
==2842==    by 0x59E080D: gethostbyaddr_r@@GLIBC_2.2.5 (in /usr/lib/libc-2.21.so)
==2842==    by 0x59E88EF: getnameinfo (in /usr/lib/libc-2.21.so)
==2842==    by 0x4E3A8B0: libwebsockets_get_addresses (libwebsockets.c:345)
==2842==    by 0x4E3B2E7: libwebsockets_get_peer_addresses (libwebsockets.c:428)

Also, would it be possible to call getaddrinfo without calling getnameinfo in advance (to not allocate a name buffer in advance)?

**Comment by warmcat** [comment]
It should be solved by f94dd2e
