### ISSUE TITLE
`-DLWS_WITH_HTTP2=OFF` and `lws_extension_callback_pm_deflate` doesn't work with HTTPS.

### ISSUE THREAD

**Issue by lonnywong** [warmcat/libwebsockets#3011]
Refer to https://github.com/tsl0922/ttyd/issues/1254

I thought `v4.3.3` solves the issue, since `v4.3.3` works with `-DLWS_WITH_LIBUV=ON -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_WITH_MBEDTLS=ON`, while `v4.3.2` doesn't. But the fact is that it also related to `-DLWS_WITH_HTTP2=OFF`.

The relevant cmake options are `-DLWS_WITH_LIBUV=ON -DLWS_WITHOUT_EXTENSIONS=OFF -DLWS_WITH_MBEDTLS=ON -DLWS_WITH_HTTP2=OFF`.

Some test cases:

| libwebsockets version | LWS_WITH_MBEDTLS | LWS_WITH_HTTP2 | test result |
| :-----: | :-----: | :-----: | :-----: |
| v4.3.2 | OFF | OFF | X |
| v4.3.2 | OFF | ON | √ |
| v4.3.2 | ON | OFF | X |
| v4.3.2 | ON | ON | X |
| v4.3.3 | OFF | OFF | X |
| v4.3.3 | OFF | ON | √ |
| v4.3.3 | ON | OFF | X |
| v4.3.3 | ON | ON | √ |

It is  also related to `LWS_WITHOUT_EXTENSIONS`. If `-DLWS_WITHOUT_EXTENSIONS=ON`, the issue doesn't exist without `lws_extension_callback_pm_deflate`.

**Comment by lws-team** [comment]
We're being the client, or server, or both?

If we're workable with both mbedtls and openssl so long as we have h2, on v4.3-stable / 4.3.3 and main, that's not a bad situation.  I can't fix tagged releases except by issuing a new tag so 4.3.2 isn't really interesting if 4.3.3 is already 'better'.

h2 has its own (much better) methods for rx flow management, once it's upgraded to ws that's the major difference in that the ws data is inside an h2 stream at that point.

**Comment by lonnywong** [comment]
Yes, `4.3.3` is better. We can bypass it simply by enabling HTTP2.

We are the server, and the client is Chrome. The request and response header shows HTTP/1.1, I'm not  sure it's HTTP2 or not.

**Comment by lws-team** [comment]
Without h2, any http serving will be h1 done with a discrete tcp + tls connection per transaction.  The ws link will be established from its own tcp + tls + h1 -> ws connection.  The upgrade seems to go OK but it seems it can't deal with the received (?) bulk data correctly.

With h2, there's a single tcp + tls connection used for everything, http and a single stream of that is upgraded to ws + compression inside the h2 stream.  h2 provides a modern credit-based flow control lws understands to precisely control how much the browser will send and when.  So whatever problem is coming under those conditions with the h1 method + compression, where the peer will just spew whatever data is available at you, seems to be avoided via h2 flow management.

**Comment by lonnywong** [comment]
Here is another screenshot with `-DLWS_WITH_HTTP2=OFF`:

![image](https://github.com/warmcat/libwebsockets/assets/20320324/ec527d46-6747-497f-b99f-d40a62e900ed)

**Comment by lonnywong** [comment]
@lws-team 
1. Some buffer left in:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/823b7b75-7938-456a-9818-480ee93c9ce2)

2. The left buffer being changed:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/5c07efbe-75e8-4740-8bac-c895a5d7d3c7)

3. The buffer is `ebuf.token`:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/3fd3e8f0-225b-478e-a2e3-dececcff9da5)

4. We need to copy the buffer somewhere:
![image](https://github.com/warmcat/libwebsockets/assets/20320324/92c3ee77-9d54-4086-9b5a-1ac0773dbb9d)

**Comment by lws-team** [comment]
Is this perhaps the case disabled for build at extension-permessage-deflate.c:242?
```
#if 0
		/*
		 * don't give us new input while we still work through
		 * the last input
		 */

		if (priv->rx.avail_in && pmdrx->eb_in.token &&
					 pmdrx->eb_in.len) {
			lwsl_wsi_warn(wsi, "priv->rx.avail_in %d while getting new in",
					priv->rx.avail_in);
	//		assert(0);
		}
#endif
```

**Comment by lonnywong** [comment]
> Is this perhaps the case disabled for build at extension-permessage-deflate.c:242?

It's a warning, and has been removed by `#if 0`.

The issue is that `priv->rx.next_in` using `pmdrx->eb_in.token` directly: https://github.com/warmcat/libwebsockets/blob/a4a7e0a49b1e464e09caf78257df3be8ab92fc4a/lib/roles/ws/ext/extension-permessage-deflate.c#L256

And The `pmdrx->eb_in.token`'s content may be changed by `lws_ssl_capable_read` : https://github.com/warmcat/libwebsockets/blob/a4a7e0a49b1e464e09caf78257df3be8ab92fc4a/lib/roles/ws/ops-ws.c#L1133
