### ISSUE TITLE
CMakeLists.txt shared library disable issue on platforms other then unix and windows

### ISSUE THREAD

**Issue by diecyde** [warmcat/libwebsockets#302]
cmake breaks when defining "no shared library" on platforms other then windows and apple.

I created an patch for this issue:

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 43630f7..b442a1f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -445,9 +445,11 @@ elseif(APPLE)
                set_property(TARGET websockets_shared PROPERTY MACOSX_RPATH YES)
        endif()
 else()
-       set_target_properties(websockets_shared
-       PROPERTIES
-       OUTPUT_NAME websockets)
+       if (LWS_WITH_SHARED)
+               set_target_properties(websockets_shared
+               PROPERTIES
+               OUTPUT_NAME websockets)
+       endif()
 endif()
 
 # Set the so version of the lib.

**Comment by JoakimSoderberg** [comment]
Nice, but could you create a pull request instead maybe? A patch in the form of a comment is not the best :)

**Comment by diecyde** [comment]
sure, will do.
did not know I was allowed to :P
