### ISSUE TITLE
[2023/11/28 20:21:24:3639] W: rops_pt_init_destroy_netlink: netlink bind failed?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3022]
I met this error in a multi-thread situation.

I used `libwebsockets `for a longtime, it's reliable and fast(i am very sensitive to latency)

the difference i made is, before, i used multi-process to connect to different websocket server.

currently, i make it in one process, with different thread.

could you help on this error?

ps. could you evaluate two methods below, which can get best speed if i need to connect to three server to get data feedback.

option1:  in one process, `lws_client_connect_via_info `three times, bind three` lws*` to one `lws_context`, loop to check the data.

option2: in one process, create three thread, each `lws_client_connect_via_info `bind with one single `lws_context`, each thread check one `lws_context`.

in my understanding, option2 is better, because if there are two data back at the same time, one won't block the other.

**Comment by lws-team** [comment]
Linux only allows one netlink socket per process.  In effect, it means one lws_context per process if you enable netlink.

Read through this to understand other restrictions on threading + lws.

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

If you think there are some choices, benchmark them rather than ask me.

**Comment by pppaulpeter** [comment]
> netlink socket
Hi Andy,

'''Linux only allows one netlink socket per process'''this is not true, right? please check the following link as the reference:
different pthreads of the same process each can have their own netlink socket for the same netlink protocol type
[https://github.com/mwarning/netlink-examples/blob/master/articles/Why_and_How_to_Use_Netlink_Socket.md](url)

**Comment by lws-team** [comment]
You literally can't open the second netlink socket on your process and are simultaneously complaining about it and telling me it is not true.

**Comment by pppaulpeter** [comment]
> You literally can't open the second netlink socket on your process and are simultaneously complaining about it and telling me it is not true.

thanks for your reply, i will write a demo code to check it in my computer and my device.

**Comment by pppaulpeter** [comment]
> Linux only allows one netlink socket per process

Hi Andy, 

sorry, according to my demo test, it seems in my computer it can't bind the second NETLINK socket.
Could this affect any features in libwebsockets (LWS) if the NETLINK socket binding failed ? @lws-team

**Comment by pppaulpeter** [comment]
> You literally can't open the second netlink socket on your process and are simultaneously complaining about it and telling me it is not true.

this is the test demo code ：
_// test_netlink_multi.c
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/socket.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>

static int bind_netlink(int nl_pid, unsigned int groups, int *out_assigned_pid) {
    int fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
    if (fd < 0) {
        perror("socket(AF_NETLINK)");
        return -1;
    }

    struct sockaddr_nl addr;
    memset(&addr, 0, sizeof(addr));
    addr.nl_family = AF_NETLINK;
    addr.nl_pid    = nl_pid;   // 0 = kernel assigns unique port-id
    addr.nl_groups = groups;   // e.g. RTMGRP_LINK | RTMGRP_IPV4_IFADDR | RTMGRP_IPV6_IFADDR

    if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        int e = errno;
        fprintf(stderr, "bind(nl_pid=%d) failed: %s\n", nl_pid, strerror(e));
        close(fd);
        errno = e;
        return -1;
    }

    // Find out what nl_pid was actually used
    struct sockaddr_nl got = {0};
    socklen_t sl = sizeof(got);
    if (getsockname(fd, (struct sockaddr *)&got, &sl) == 0) {
        if (out_assigned_pid) *out_assigned_pid = got.nl_pid;
    }

    return fd;
}

int main(void) {
    const unsigned int groups = RTMGRP_LINK | RTMGRP_IPV4_IFADDR | RTMGRP_IPV6_IFADDR;

    printf("Test 1: two sockets with the SAME nl_pid = getpid() (%d)\n", getpid());
    int pid = (int)getpid();
    int a_pid = -1, b_pid = -1;

    int fd_a = bind_netlink(pid, groups, &a_pid);
    if (fd_a < 0) {
        fprintf(stderr, "First bind with explicit nl_pid failed; run as a normal user is usually fine.\n");
        return 1;
    }
    printf("  socket A bound: nl_pid=%d\n", a_pid);

    int fd_b = bind_netlink(pid, groups, &b_pid);
    if (fd_b < 0) {
        printf("  socket B with same nl_pid failed as expected (EADDRINUSE)\n");
    } else {
        printf("  socket B unexpectedly succeeded with same nl_pid=%d\n", b_pid);
        close(fd_b);
    }

    close(fd_a);

    printf("\nTest 2: two sockets with AUTO nl_pid (kernel assigns)\n");
    int x_pid = -1, y_pid = -1;
    int fd_x = bind_netlink(0, groups, &x_pid);
    if (fd_x < 0) return 1;
    printf("  socket X bound: assigned nl_pid=%d\n", x_pid);

    int fd_y = bind_netlink(0, groups, &y_pid);
    if (fd_y < 0) return 1;
    printf("  socket Y bound: assigned nl_pid=%d\n", y_pid);

    if (x_pid != y_pid)
        printf("  Success: multiple netlink sockets in same process (different nl_pid values)\n");
    else
        printf("  Unexpected: got identical nl_pid; something’s off\n");

    close(fd_x);
    close(fd_y);

    return 0;
}_
and result on my device:
_# cp /nfs/test_netlink_multi /home/
# cd /home/
# ./test_netlink_multi 
Test 1: two sockets with the SAME nl_pid = getpid() (31349)
  socket A bound: nl_pid=31349
bind(nl_pid=31349) failed: Address already in use
  socket B with same nl_pid failed as expected (EADDRINUSE)

Test 2: two sockets with AUTO nl_pid (kernel assigns)
  socket X bound: assigned nl_pid=31349
  socket Y bound: assigned nl_pid=-469009696
  Success: multiple netlink sockets in same process (different nl_pid values)_

conclusion:
you can open multiple NETLINK_ROUTE sockets per process—just don’t bind them with the same nl_pid. Use nl_pid = 0(let the kernel assign unique ids) or generate another nl_pid for example  pid|tid.
