### ISSUE TITLE
lws_service doing nothing for 30 seconds

### ISSUE THREAD

**Issue by ipasipas** [warmcat/libwebsockets#3026]
I have this strange problem. I am using lws4.1.6 on raspberry pi both client and server application. 
The problem is that is that the lws_service seems doing nothing for exactly 30 seconds before the next loop runs. It is not responding on lws_callback_on_writable when this is called. So the callback is done after this 30 seconds period. 

I want to send a message withing the WRITABLE callback, but not have to wait for 30 seconds before is is sent. 

When I connect with another websocket client -  library ( IOS Starscream ) the sever seems working fine/faster. (1 second)

I tried it also with this simple client example sending a random number. This lws_service of the clientdoes also wait 30seconds 
https://github.com/iamscottmoyers/simple-libwebsockets-example/blob/master/client.c

The random number is send every 30 seconds because of the lws_server wait. 

I print TICK after the lws_service on the server
		lws_service(context, 0);
		sprintf(__logString, "TICK ");

This result this logging of the server with timestamps

2023-12-9 14:44:45 -> DEBUG   - WEBSOCKET    - LWS_CALLBACK_RECEIVE: 1 fragments received from Client 1 results into message: 1804289383
 
2023-12-9 14:44:45 -> DEBUG   - WEBSOCKET    - Adding inboud message to the Queue from client 1 
2023-12-9 14:44:45 -> INFO    - WEBSOCKET    - TICK  
2023-12-9 14:45:10 -> INFO    - WEBSOCKET    - TICK  
LWS_CALLBACK_RECEIVE NODES
2023-12-9 14:45:15 -> DEBUG   - WEBSOCKET    - LWS_CALLBACK_RECEIVE: 1 fragments received from Client 1 results into message: 846930886
2023-12-9 14:45:15 -> DEBUG   - WEBSOCKET    - Adding inboud message to the Queue from client 1 
2023-12-9 14:45:15 -> INFO    - WEBSOCKET    - TICK  

What am I missing here ? I read everything possible .. and am stuck at this point.

**Comment by ipasipas** [comment]
Thanks for the quick reply :) The only thing I want is the lws_service to act as fast as possible when I give the lws_callback_all_protocol command. But the lws_service does not respond after it comes out of the loop wich is 30 seconds. And it looks like this problem only exist when I use the lws library also for the client.

**Comment by lws-team** [comment]
Why do you think my reply has a link in it along with the explanation of what your actual problem is...

**Comment by ipasipas** [comment]
Aah.. I did not read your reply correctly. Problem fixed. I upgraded to the latest stable and everything is working ultra fast. Thanks a lot man! this lib is awesome!
