### ISSUE TITLE
big latency between lws_callback_on_writable and event_cb event LWS_CALLBACK_CLIENT_WRITEABLE?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3030]
I need to send heartbeat request to the `websocket `server for maintaining the connection.

so i start a single thread to send heartbeat request by sleep(interval)

i read the code, so, when i do send_request, i put the request string in the buffer, then call `lws_callback_on_writable`.

after `LWS_CALLBACK_CLIENT_WRITEABLE `event received, i sent the buffered request.

in my plan, the `LWS_CALLBACK_CLIENT_WRITEABLE `will be received very soon. but i checked the sample, sometimes it will 10s.

could you provide some advice and explanation based on your experience?

and for the best performance, can i send request without `lws_callback_on_writable`? what's the risk?

thanks very much.

**Comment by lws-team** [comment]
> so i start a single thread 

lws is single-threaded.  You cannot randomly call lws apis for a context with an event loop in one thread, from any other thread.

Have a read of this:

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md
