### ISSUE TITLE
How to monitor the lws_event is flooding?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3031]
I have a very intensive event callback.

I found it flooded, because the `WRITEABLE `event comes back 8 seconds after i called `lws_callback_on_writable`.

in my understanding, the reason is, the event callback is very busy, there are a lot of event waiting to be handled.

so the `lws_callback_on_writable `registered a event, and according to the queue, it be executed after 8s.

the question is:

how can i confirm this is the reason, and is there anything i can do to solve this?

**Comment by lws-team** [comment]
Nothing of the sort it happening.  The thread you want to do something is blocked asleep in poll().  If you change its waitlist from another thread, it's undefined what happens.  On bsd the next time poll() wakes, it replaces your change from the other thread with the waitlist from the time it enered the wait, removing itt.

Take the advice from thismorning and stop trying to use threads.  Read through the readme I pointed you to then properly.
