### ISSUE TITLE
cleint request path

### ISSUE THREAD

**Issue by chenjh1225** [warmcat/libwebsockets#3033]
in ws server, hao to get client request path, i have give path in lws_client_connect_info obj in the ws client, but have no callback in service with reason LWS_CALLBACK_FILTER_HTTP_CONNECTION

**Comment by lws-team** [comment]
Use `LWS_CALLBACK_ESTABLISHED` as the place for this kind of thing.

You can still access the http headers using, eg, `lws_hdr_copy(wsi, buf, sizeof(buf), WSI_TOKEN_GET_URI)`
