### ISSUE TITLE
Connection not released on -1 return from callback

### ISSUE THREAD

**Issue by sjames1958gm** [warmcat/libwebsockets#304]
My understanding is that if -1 is returned from the callback function then the connection will be released. When my server needs to disconnect it sets a flag that causes the next run of the callback function to return -1. I see from my traces that I am hitting the return -1; but I don't see a release.

As far as the version; when I run the test server the following is shown:
Library version: 1.3 8ec7802

**Comment by warmcat** [comment]
Can you reopen and give us a clue what the reason id for the call was when you returned -1, if this still matters to you?

**Comment by sjames1958gm** [comment]
The reason is LWS_CALLBACK_CHANGE_MODE_POLL_FD. Basically I have an external event that sets a flag indicating diconnect. The next time through the call back function, if the flag is set then -1 is returned.

**Comment by warmcat** [comment]
I pushed a patch that improves checking on callback reasons that normally 'can't fail'
