### ISSUE TITLE
understanding of event loop, not multi-thread

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3040]
Hi, Andy.

in the previous discussion, two threads, each creates a `lws_context`, each context owns only one `lws_client_connect_via_info `, then the context loop to get event.

for performance consideration, it's same with one lws_context, binding with two  `lws_client_connect_via_info `, loop to get event.

because the event is handled one by one in hardware level. am i right?

if this is correct, does it mean:
1. even the libwebsockets runs on different process, it will still be serial, not paralleled ? the performance will be the same with one thread handle all? 
2. the network package is serial comes in network card, this is the hard limits for network operation?

much Thanks for your help

**Comment by lws-team** [comment]
I politely decline your offer to hold your hand through your journey of discovery about how networking and event loops work.

If someone else feels they want to donate their time, which I guarantee will be a one-way process, they're welcome to reply instead.
