### ISSUE TITLE
How to disable HTTP/2 dynamically?

### ISSUE THREAD

**Issue by markmaker** [warmcat/libwebsockets#3042]
How can I disable HTTP/2 _dynamically_ in a server? 

I know `LWS_WITH_HTTP2=0`, but I need a dynamically programmable option.

I've searched all options/flags known to me, but found nothing. The dynamic option could be by context, vhost, connection, it doesn't matter.

**Comment by lws-team** [comment]
In `struct lws_context_creation_info`

```c
        const char *alpn;
        /**< CONTEXT: If non-NULL, default list of advertised alpn, comma-
         *            separated
         *
         *     VHOST: If non-NULL, per-vhost list of advertised alpn, comma-
         *            separated
         */
```

If you want h1 or h2, just leave it `NULL`.  Else, eg, `"h1"`.
