### ISSUE TITLE
How to enable automatic server WebSocket ping-pong? (formerly ws_ping_pong_interval)

### ISSUE THREAD

**Issue by markmaker** [warmcat/libwebsockets#3043]
In [earlier version](https://libwebsockets.org/lws-api-doc-v2.1-stable/html/structlws__context__creation__info.html), I see the `ws_ping_pong_interval` member of `struct lws_context_creation_info` to enable automatic ping pong when there was no traffic on the connection. 

> `unsigned short lws_context_creation_info::ws_ping_pong_interval`

> CONTEXT: 0 for none, else interval in seconds between sending PINGs on idle websocket connections. When the PING is sent, the PONG must come within the normal timeout_secs timeout period or the connection will be dropped. Any RX or TX traffic on the connection restarts the interval timer, so a connection which always sends or receives something at intervals less than the interval given here will never send PINGs / expect PONGs. Conversely as soon as the ws connection is established, an idle connection will do the PING / PONG roundtrip as soon as ws_ping_pong_interval seconds has passed without traffic

How can I do that in newer versions?

**Comment by lws-team** [comment]
This became generalized for different protocols like h2 as well as ws, and extended to cover exponential backoff for retries for Secure Streams.

https://github.com/warmcat/libwebsockets/blob/main/include/libwebsockets/lws-retry.h

For server, you can bind a policy about these things when creating the vhost

```c
        const lws_retry_bo_t *retry_and_idle_policy;
        /**< VHOST: optional retry and idle policy to apply to this vhost.
         *   Currently only the idle parts are applied to the connections.
         */
```

Something like this should do it is not using SS retries

```
static const lws_retry_bo_t retry = {
        .secs_since_valid_ping = 5,
        .secs_since_valid_hangup = 10,
};
```
