### ISSUE TITLE
host port mismatches vhost port with CONTEXT_PORT_NO_LISTEN / CONTEXT_PORT_NO_LISTEN_SERVER

### ISSUE THREAD

**Issue by markmaker** [warmcat/libwebsockets#3044]
I'm using libwebsockets with adopted sockets, i.e., the server is not listening itself, which is achieved by setting  `.port = CONTEXT_PORT_NO_LISTEN_SERVER` as [described here](https://libwebsockets.org/lws-api-doc-v3.0-stable/html/structlws__context__creation__info.html#a424a5ce268d6903e42243be94487ab85). 

This works with HTTP/2 but when disabling HTTP/2 in favor of HTTP/1.1 (see #3042), I get a "host port X mismatches vhost port".

https://github.com/warmcat/libwebsockets/blob/f88792df3723f85bc0f9fbdcce7c59fbc7c458c2/lib/roles/http/server/server.c#L2156-L2158

Should this be changed to something like this?

```C++
	if (wsi->a.vhost->listen_port != CONTEXT_PORT_NO_LISTEN &&
	    wsi->a.vhost->listen_port != CONTEXT_PORT_NO_LISTEN_SERVER &&
	    wsi->a.vhost->listen_port != port) {
		lwsl_info("%s: host port %d mismatches vhost port %d\n",
			  __func__, port, wsi->a.vhost->listen_port);
		return 1;
	}

```

**Comment by markmaker** [comment]
Thanks for the quick answer. 

To understand better: why does it not happen with HTTP/2? 

Should I make a PR?

**Comment by lws-team** [comment]
It looks like it checks at upgrade time for h1 if `LWS_SERVER_OPTION_VHOST_UPG_STRICT_HOST_CHECK` set.  But for h2, it normally negotiates what protocol you want at tls negotiation time, using alpn, and there is no h1->h2c upgrade used.  There is an h2c upgrade mechanism supported, but eg browsers do it at tls time instead by alpn.

Once h2 is connected, streams inside the connection inherit the outside port.

If you checked it works for your adoption case, yes open a PR or just let me know your From: string and paste the change and I'll do it.

**Comment by markmaker** [comment]
Ah, I understand. Here's the patch:

```c
From 18e26a7a6dce0617e7d14d98655efd0e59b7170d Mon Sep 17 00:00:00 2001
From: markmaker <mark@makr.zone>
Date: Mon, 8 Jan 2024 14:53:30 +0100
Subject: [PATCH] Ignore a vhost port mismatch when using
 CONTEXT_PORT_NO_LISTEN_SERVER.

---
 lib/roles/http/server/server.c | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/lib/roles/http/server/server.c b/lib/roles/http/server/server.c
index 9bf1eba2..ff5b1255 100644
--- a/lib/roles/http/server/server.c
+++ b/lib/roles/http/server/server.c
@@ -2153,7 +2153,8 @@ lws_confirm_host_header(struct lws *wsi)
 		if (e != LWS_TOKZE_ENDED)
 			goto bad_format;
 
-	if (wsi->a.vhost->listen_port != port) {
+	if (wsi->a.vhost->listen_port != port &&
+		wsi->a.vhost->listen_port != CONTEXT_PORT_NO_LISTEN_SERVER) {
 		lwsl_info("%s: host port %d mismatches vhost port %d\n",
 			  __func__, port, wsi->a.vhost->listen_port);
 		return 1;
-- 
2.40.1

```

**Comment by lws-team** [comment]
Thanks, it's pushed on main
