### ISSUE TITLE
what's the difference between unique protocols and protocols with a terminator?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3051]
some demos creates lws_protocols(or extensions) as:

`struct lws_protocols protocols[] = {{"depth", &event_cb, sizeof(*this), 65536, 1, &conn_map_}, {NULL, NULL, 4096, 0, 3, NULL}};`
which marks the second protocol is a terminator.

but i tested with removing the terminator as this: 
`struct lws_protocols protocols[] = {{"depth", &event_cb, sizeof(*this)};`
it also works good.

could you let me know what's the purpose of terminator? secure to other reason? thanks

**Comment by lws-team** [comment]
If you 'test' driving without a seatbelt, often that will appear to 'work good'.  You can't conclude from that you can remove seatbelts from your car.  (Also your 'works good' example is missing a close brace and wouldn't compile as is)

I wrote the examples to follow so stuff will really "work good" without having to explain everything.  If you want to understand why you need to provide the terminator, you have the sources and are welcome to trace through how the array you're providing is iterated to see why it's needed.
