### ISSUE TITLE
for arm toolchain

### ISSUE THREAD

**Issue by rahulrock213** [warmcat/libwebsockets#3052]
zen@zen-V330-20ICB-AIO:/tmp/libwebsockets/build$ make
[  0%] Creating build include dir
[  0%] Built target GENHDR
[  0%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-caps.c.o
[  0%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-misc.c.o
[  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-init.c.o
[  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-file.c.o
[  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-pipe.c.o
[  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-service.c.o
[  1%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-sockets.c.o
[  2%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-fds.c.o
[  2%] Building C object lib/CMakeFiles/websockets.dir/plat/unix/unix-plugins.c.o
[  2%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_cert.c.o
[  2%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_lib.c.o
[  2%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_methods.c.o
[  3%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_pkey.c.o
[  3%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_stack.c.o
[  3%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/library/ssl_x509.c.o
[  3%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/platform/ssl_pm.c.o
[  3%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/wrapper/platform/ssl_port.c.o
[  4%] Building C object lib/CMakeFiles/websockets.dir/tls/tls.c.o
[  4%] Building C object lib/CMakeFiles/websockets.dir/tls/tls-network.c.o
[  4%] Building C object lib/CMakeFiles/websockets.dir/tls/tls-sessions.c.o
[  4%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-tls.c.o
[  4%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-extensions.c.o
[  5%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-x509.c.o
[  5%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-ssl.c.o
[  5%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-session.c.o
[  5%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/lws-genhash.c.o
/tmp/libwebsockets/lib/tls/mbedtls/lws-genhash.c: In function ‘lws_genhmac_init’:
/tmp/libwebsockets/lib/tls/mbedtls/lws-genhash.c:279:13: error: implicit declaration of function ‘mbedtls_md_init_ctx’; did you mean ‘mbedtls_md_init’? [-Werror=implicit-function-declaration]
  279 |         if (mbedtls_md_init_ctx(&ctx->ctx, ctx->hmac))
      |             ^~~~~~~~~~~~~~~~~~~
      |             mbedtls_md_init
cc1: all warnings being treated as errors
make[2]: *** [lib/CMakeFiles/websockets.dir/build.make:426: lib/CMakeFiles/websockets.dir/tls/mbedtls/lws-genhash.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3995: lib/CMakeFiles/websockets.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
zen@zen-V330-20ICB-AIO:/tmp/libwebsockets/build$ cd /tmp/libwebsockets/lib/tls/mbedtls/

**Comment by lws-team** [comment]
Did cmake have any complaints before this?

**Comment by lws-team** [comment]
Basically all the tests that involve cmake-time compile are failing for a specific reason other than the test being false.  It leaves cmake having wrongly selected platform adaptations.  Have a look at the second part here https://github.com/warmcat/libwebsockets/blob/main/READMEs/README.cmake.md to find out what the actual problem causing that is.
