### ISSUE TITLE
libwebsockets.org is down

### ISSUE THREAD

**Issue by UR3IQO** [warmcat/libwebsockets#3055]
It looks like libwebsockets.org is offline for several days

**Comment by lws-team** [comment]
It's actually up just fine, but lacks internet connectivity atm for 'reasons'.  It will reappear later.

Git content related to lws is mirrored up to date on github.  Services like mirror demo can be built and run locally from lws tree.  There's no reason to expect my services or myself to be available ongoing for free, as opposed to the code which lays out what you can expect in LICENCE.
