### ISSUE TITLE
WSI_STATE_RETURNED_CLOSE_ALREADY triggers an unrequested LWS_CALLBACK_SERVER_WRITEABLE

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#306]
Since commit 4bca6cd367824e54999295b7219c8833cf3d0247 registered callback receives LWS_CALLBACK_SERVER_WRITEABLE on client initiated connection close.
This poses difficulties for the callback implementation: the call is totally unexpected, invocations of libwebsocket_write fail and there're no means to get the state of WSI.

**Comment by warmcat** [comment]
Please try current HEAD

**Comment by lws-team** [comment]
I'm closing this and #281 because I think it should be fixed, if not, please reopen.
