### ISSUE TITLE
Missing string termination in lws_hdr_custom_name_foreach

### ISSUE THREAD

**Issue by horchi** [warmcat/libwebsockets#3069]
lws_hdr_custom_name_foreach calls the CB with a not terminated 'name', 'nlen' provide the length of the name but not the name of the value or of the whole string, 
This means that it is not possible to determine the end of the string in the CB method.

lws_hdr_custom_copy, on the other hand, terminates the string properly.

Regards Jörg

**Comment by lws-team** [comment]
> This means that it is not possible to determine the end of the string in the CB method.

The idea is you only need the name, since you can call `lws_hdr_custom_copy()` with the `name` + `nlen` in the callback to get a copy of the value for ones you are interested in.

**Comment by horchi** [comment]
In this case, the user has the same problem as with lws_hdr_custom_copy() - he has to keep a buffer with a fixed estimated size. It would be nice if you didn't have to call lws_hdr_custom_copy separately (also less code and less operations).

In my opinion it would be sufficient to pass the length of the complete string ('len') to the CB instead of 'nlen', 'nlen' is superfluous as the colon delimits the name

**Comment by lws-team** [comment]
You can use `lws_hdr_custom_length()` to get the length from the `name` + `nlen` and allocate from that before doing the `lws_hdr_custom_copy()`.  So I think it already covers all the bases.

> In my opinion it would be sufficient to pass the length of the complete string ('len') to the CB instead of 'nlen', 'nlen' is superfluous as the colon delimits the name

It takes the approach to not need a NUL-terminated name atm and so the related apis that take a name, need nlen.

**Comment by horchi** [comment]
> It takes the approach to not need a NUL-terminated name atm and so the related apis that take a name, need nlen.
to provide the full length instead of the name length also not need a null termination.

Okay sure it' possible to use lws_hdr_custom_length and lws_hdr_custom_copy in the CB. 
This results in two more strncmp although you already have all the information at hand in lws_hdr_custom_name_foreach.
(just my three cents).

But okay calling all three methods in sequence works and to the job.

**Comment by horchi** [comment]
why does the name of the header attribute contain the colon ?

**Comment by lws-team** [comment]
Does it make any problem?

**Comment by horchi** [comment]
you can trade it, but I find it confusing and in my opinion it is not part of the name according to the definition

**Comment by lws-team** [comment]
Changing an established public api will definitely make trouble (although there are no in-tree users for some of this, it was added by request to be used in high-volume products) and so it's unlikely to change.  If it bothers you, you can trim `npos` back by 1 if there's a `:` at the end.

In h2 eg, `:method`some header names do include the colon.  But it turned out for technical reasons the custom headers are only supported on h1.
