### ISSUE TITLE
Bug in HTTP2 form POST file upload

### ISSUE THREAD

**Issue by gmfcd128** [warmcat/libwebsockets#3070]
How to reproduce:
*System is Ubuntu 22.04.3
1.Clone latest source from Github
2.Configure source code according to documentation
3.After doing above, run code combining minimal-http-server-form-post-file & minimal-http-server-tls-mem example
4.Start the compiled example, connect with clean incognito browser window
5.Fill the form with text 'abc' and a file
5.After submit the form , the webpage won't redirect, and the upload data shown in working directory is less than the size it should be

![圖片](https://github.com/warmcat/libwebsockets/assets/32321100/06c189ca-6fe5-4f2b-a76e-8c2eaa6f7010)
[code.txt](https://github.com/warmcat/libwebsockets/files/14318398/code.txt)

**Comment by lws-team** [comment]
I pushed a patch on main branch that may help.

**Comment by gmfcd128** [comment]
Thanks, the issue is now resolved.
