### ISSUE TITLE
HTTP2 ah count keeps going up when using custom event lib

### ISSUE THREAD

**Issue by gmfcd128** [warmcat/libwebsockets#3071]
If HTTP2 is enabled (by providing SSL data into minimal-http-server-eventlib-custom), can be observed from debug window that the ah list incremented in size after a page load without going down, even after the browser is closed.
![圖片](https://github.com/warmcat/libwebsockets/assets/32321100/3f774b51-0846-42fd-9b54-363d1ce54d74)

**Comment by lws-team** [comment]
H2 connections are kept around for 5s by default when idle, in case there are more transactions coming.  At least in ffox, closing the tab may not close the h2 socket that the tab may have (although literally closing the browser should).

**Comment by gmfcd128** [comment]
The original behavior when custom evlib is not engaged will free the ah list after firefox browser is closed.It seems to be decision in code that cause the issue mentioned earlier.
If we compare the debug log produced by both cases side by side, inside the specific lws_http_transaction_completed after 'file completed', lws_http_transaction_completed will call lws_close_free_wsi.
The debug log shows that the sockfd of the wsi is -1, when using the custom evlib with the way of the example, the value passed into wsi->a.context->event_loop_ops->wsi_logical_close will make it return 1, and prevent  __lws_close_free_wsi_final after that from executing, so LWS_ROPS_destroy_role that frees the ah will not execute .
![圖片](https://github.com/warmcat/libwebsockets/assets/32321100/a8305cff-1965-4094-a54f-4d43a899c4e0)

**Comment by gmfcd128** [comment]
Yes, thank you for your help.
