### ISSUE TITLE
feature request: extension allow use rsv and opcode

### ISSUE THREAD

**Issue by liudongmiao** [warmcat/libwebsockets#3076]
In websocket protocol, there are 3 RSV bits, and 0x3-0x7, 0xB-0xF reserved frames.

   RSV1, RSV2, RSV3:  1 bit each

      MUST be 0 unless an extension is negotiated that defines meanings
      for non-zero values.  If a nonzero value is received and none of
      the negotiated extensions defines the meaning of such a nonzero
      value, the receiving endpoint MUST _Fail the WebSocket
      Connection_.

   Opcode:  4 bits

      Defines the interpretation of the "Payload data".  If an unknown
      opcode is received, the receiving endpoint MUST _Fail the
      WebSocket Connection_.  The following values are defined.

      *  %x3-7 are reserved for further non-control frames

      *  %xB-F are reserved for further control frames

libwesockets may allow custom extensions using these reserved bits and opcode.

- update rsv and opcode, it can be done in `LWS_EXT_CB_PACKET_TX_PRESEND`, however, it's only available if `LWS_WITHOUT_EXTENSIONS=OFF`, and this is something like only for `extension-permessage-deflate`.
- read rsv and opcode, currently there is `lws_get_reserved_bits`, no `lws_get_opcode`. Even is build with extension, reserved opcode would cause `LWS_CLOSE_STATUS_PROTOCOL_ERR`.

So, it maybe a way for libwebsockets provide such way for custom extensions, which means only for update / access rsv and opcode.

**Comment by liudongmiao** [comment]
For write, we can use `LWS_WRITE_RAW`. However, for read, there is no simple way.

**Comment by lws-team** [comment]
AFAIK there's only one standardized ws extension still, permessage-deflate.  It required a lot of hooking into the extensions stuff to allow it to gzip finished written content of different sizes etc and caused a lot of difficulty.

If you will do the work to make another extension (which must be negotiated on ws server connect) then you can send me patches for any necessary changes to consider.
