### ISSUE TITLE
Parameter validation and return value checking

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#308]
Setting `lws_context_creation_info::ka_interval to zero` along with a positive `lws_context_creation_info::ka_time` value results in a quite time-consuming debugging.

`libwebsocket_create_context` does not validate input parameters.
`lws_plat_set_socket_options` bails out with an error not having set non-blocking mode.
`lws_context_init_server` (as well as `lws_server_socket_service`) silently ignores return value of `lws_plat_set_socket_options`.

As a result `lws_server_socket_service` blocks in accept.

PS: Ubuntu 14.04, commit 3ae1badae7a05e0982e0dfbcb078da3d4b92a81d

**Comment by warmcat** [comment]
It complains and fails now.
