### ISSUE TITLE
AES function is misdocumented as RSA function

### ISSUE THREAD

**Issue by PJBoy** [warmcat/libwebsockets#3085]
https://github.com/warmcat/libwebsockets/blob/779915a2e9bb6634335de0ee798fdfc28079791e/include/libwebsockets/lws-genaes.h#L92

**Comment by lws-team** [comment]
Thanks, I pushed the fix on main + v4.3-stable

**Comment by PJBoy** [comment]
Swiftly addressed, nice one. But you misspelt AES as AS (`genas`)

**Comment by lws-team** [comment]
Thanks, I updated the patches.
