### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by horchi** [warmcat/libwebsockets#3086]
probably a stupid question but I couldn't find anything about it. As I understand it [here](https://websockets.readthedocs.io/en/stable/topics/compression.html) the communication via WebSocktets is always compressed by default? 
Does the libwebsockets do this automatically when sending or do I have to configure something, set an option or something similar?
Thx and best regards

**Comment by lws-team** [comment]
RFC6455 defining websockets came out in 2011 without any compression support, the permessage-deflate extension was added in RFC7692 in 2015 .  So ws itself in the RFC6455 sense has no idea about compression and cannot use it by default.

Particular implementations might try to use permessage-deflate extension by default but there's no requirement for it to exist either end.  The client doesn'trequest it by default, you have to add some code, see either

../minimal-examples-lowlevel/ws-client/minimal-ws-client-pmd-bulk/minimal-ws-client-pmd-bulk.c   or
../minimal-examples-lowlevel/secure-streams/minimal-secure-streams-binance/main.c

If the client requests it, it's OK if the server doesn't support it, it will just not succeed to be negotiated.  If both ends can agree on it then it will be automatically applied.

**Comment by horchi** [comment]
Thanks, I'll take a look and give it a try. My goal is to compress the communication since a slightly larger packet that rarely needs to be transmitted to the client slows down the communication a bit on bad connections

**Comment by lws-team** [comment]
... if the client supports it and asks for it, and the server supports it, both sides will negotiate to use compression during the normal ws upgrade.

For lws client, you need to add the boilerplate from the examples I mentioned to enable permessage-deflate extension request and then that should be enough if the server supports it.

**Comment by horchi** [comment]
I use libwebsockets as server. I added the permessage-deflate to the client side (javascript).
The permessage-deflate is requested by the client but not in the response as far as I can see here:
![grafik](https://github.com/warmcat/libwebsockets/assets/5390688/4a85a479-a119-4aa1-96a8-ed60e0e54007)

**Comment by lws-team** [comment]
Lws needs to be built with `-DLWS_WITHOUT_EXTENSIONS=0`

**Comment by horchi** [comment]
Thx, now it looks better, it seems I need both, building the lib with `-DLWS_WITHOUT_EXTENSIONS=0`
and setting this on server side:
```
static const struct lws_extension extensions[]
{
   { "permessage-deflate", lws_extension_callback_pm_deflate, "permessage-deflate"
         "; client_no_context_takeover; client_max_window_bits" },
   { NULL, NULL, NULL }
};
```
![grafik](https://github.com/warmcat/libwebsockets/assets/5390688/86e23ca0-6c7b-42f7-b6cb-7dc56cb5fbeb)
