### ISSUE TITLE
feature request: support SSLKEYLOGFILE for openssl

### ISSUE THREAD

**Issue by liudongmiao** [warmcat/libwebsockets#3087]
There're lws_ssl_capable_read and lws_ssl_capable_write, however it's mainly for debug:
https://github.com/warmcat/libwebsockets/blob/main/READMEs/README.debugging.md#traffic-dumping

SSLKEYLOGFILE can be used by Wireshark to decrypt tls traffic.
It should works well in OoenSSL, BoringSSL, LibreSSL and wolfSSL with a simple `SSL_CTX_set_keylog_callback`.

If this can be acceptable, I'd like to make a PR.

Documents from curl's source code.
```c
/*
 * Whether SSL_CTX_set_keylog_callback is available.
 * OpenSSL: supported since 1.1.1 https://github.com/openssl/openssl/pull/2287
 * BoringSSL: supported since d28f59c27bac (committed 2015-11-19)
 * LibreSSL: supported since 3.5.0 (released 2022-02-24)
 */
```

**Comment by lws-team** [comment]
This already exists on main... released versions can't take public api changes.

**Comment by liudongmiao** [comment]
@lws-team Thanks. Just found the codes. It even introduce a new field like `keylog_file`.
(IMO, only standard `SSLKEYLOGFILE` should be supported.)

And it seems there is no for mbedlts. There is a hack: https://github.com/Lekensteyn/mbedtls/commit/68aea15
(refered from Wireshark's TLS Wiki.)
