### ISSUE TITLE
Issue receiving large messages (> 4096 Bytes) with SSL enabled

### ISSUE THREAD

**Issue by jmillan** [warmcat/libwebsockets#309]
Hi,

I'm using the latest libwebsocket version from git.
This issue is only present when WSS is used. Using plain WS everything is fine.

Incoming messages bigger than 4096 Bytes do not fire the protocol callback with reason `LWS_CALLBACK_RECEIVED`. 

The protocol `rx_buffer_size` is set to 65535.

It properly works if I manually set the macro `LWS_MAX_SOCKET_IO_BUF` to a value bigger than 4096.

This is the handshake log:

````
v13 hdrs completed
libwebsocket_parse sees parsing complete
checking sip
prot match 1
libwebsocket_ensure_user_space: 0x7fffbc001c40 protocol 0xbff9d0
lws_parse calling handshake_04
libwebsocket_ensure_user_space: 0x7fffbc001c40 protocol 0xbff9d0
libwebsocket_ensure_user_space: 0x7fffbc001c40 protocol pss 65552, user_space=-1140766752
WSI_TOKEN_EXTENSIONS = 'permessage-deflate; client_max_window_bits'
issuing resp pkt 158 len
callback_sip: LWS_CALLBACK_ESTABLISHED
Received network connect from 192.168.100.101:55817
    get  = /
    host: = 192.168.100.100:8000
    connection: = Upgrade
    upgrade: = websocket
    origin: = https://local-tryit.jssip.net
    sec-websocket-extensions: = permessage-deflate; client_max_window_bits
    sec-websocket-protocol: = sip
    http/1.1  = HTTP/1.1
    accept-encoding: = gzip, deflate, sdch
    accept-language: = en-US,en;q=0.8,es;q=0.6
    pragma: = no-cache
    cache-control: = no-cache
    sec-websocket-key: = x5gsAS5dhGtkrYg168gSnw==
    sec-websocket-version: = 13
    user-agent: = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2471.2 Safari/537.36
Allocating RX buffer 65557
accepted v13 connection
````
When the server receives a message bigger than 4096, the only log line I can see is:

````

libwebsocket_read: read_ok
```

Only when a second message is sent from the client, the protocol callback with reason `LWS_CALLBACK_RECEIVED` is fired and the two messages can be handled.

Any test I can do in order to give you more information, please just tell me and I'll provide it.

**Comment by jmillan** [comment]
Note:

When using plain WS, data is taken from the socket using `recv()`. When using WSS, data is taken from `SSL_read()`. In both cases data is copied into the buffer `context->service_buffer` which length is 4096 (LWS_MAX_SOCKET_IO_BUF). 

For messages greater that 4096 Bytes, when using plain WS, `libwebsocket_service_fd()` is fired twice. the first one fills the `context->service_buffer` totally and leaves some pending data in the socket. The second one gets the rest of the data and then the protocol callback with reason `LWS_CALLBACK_RECEIVED` is called.

For messages greater that 4096 Bytes, when using WSS, `libwebsocket_service_fd()` is only fired once. The `context->service_buffer` is totally filled and leaves some pending data in the SSL BIO. `libwebsocket_service_fd()` is never called again unless a new message comes from the client.

For that reason, if I increased `LWS_MAX_SOCKET_IO_BUF` to a value big enough to get the data from `SSL_read()`at once, there problem doesn't happen.

**Comment by jmillan** [comment]
Note: I'm not sure the following is relevant or not..,

libwebsockets is not compiled with libev support. I use libev on my own, so I call `libwebsocket_service_fd` for each file descriptor read event fired by libev.

**Comment by ralight** [comment]
I believe that this may be the same issue as is addressed in #295 and #298

**Comment by jmillan** [comment]
This is not my case since I use `libwebsocket_service_fd()` instead of `libwebsocket_service()` as noted previously.

`lws_plat_service()` is not called if using `libwebsocket_service_fd()`. For that reason, only when the client sends more data through the WS is that the the protocol callback with reason `LWS_CALLBACK_RECEIVED` is fired; because `SSL_read()` is executed again; only after more data is received.

**Comment by jmillan** [comment]
I've been unsuccessfully trying to avoid using the libwebsockets internal SSL pending data handling mechanism by indicating OpenSSL to just buffer the indicated size of data and leave for the next file description read the remaining data.

Based on the OpenSSL docs, this is achieved by `SSL_set_read_ahead()` and `BIO_set_buffer_size()`. 

So I made the following change in ssl.c:

```
@@ -536,10 +537,13 @@ lws_server_socket_service_ssl(struct libwebsocket_context *context,
 #ifdef USE_CYASSL
                CyaSSL_set_using_nonblock(new_wsi->ssl, 1);
 #else
+               SSL_set_read_ahead(new_wsi->ssl, 0);
                SSL_set_mode(new_wsi->ssl, SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);
                bio = SSL_get_rbio(new_wsi->ssl);
-               if (bio)
+               if (bio) {
                        BIO_set_nbio(bio, 1); /* nonblocking */
+                       BIO_set_read_buffer_size(bio,LWS_MAX_SOCKET_IO_BUF);
+    }
```

AFAIK, this change should made `SSL_read()` just buffer the specified amount of data (which corresponds with `LWS_MAX_SOCKET_IO_BUF` value) and hence no pending data should exist in the SSL buffer, so `SSL_pending()` should return 0.

Given the previous rationale, the next time the file descriptor is read, the same operation will be repeated until a full TCP chunk is read and then the user callbacks should be called. This method would avoid the libwebsockets internal SSL pending data management and simplify the task IMHO.

Unfortunately my changes don't work as expected and for big contents, SSL still buffers the extra data, ruining my hole plan :-(

Any insight on what I may doing wrong to avoid SSL buffer that extra data is very welcome.

**Comment by jmillan** [comment]
I was mistaken in my assumption that I could just read a specific amount of data without buffering anything in OpenSSL.

The whole SSL/TLS record must be received (max 16KB) before it can be processed and decrypted, and thus retrieved by `SSL_read()`. Meaning that unless reading 16KB on `SSL_read()`, having pending data `SSL_pending()` is legitimate and will occur whenever the received record is bigger than the read size specified to `SSL_read()`.

**Comment by Guid75** [comment]
I encounter to the same issue. I am forced to reduce my websocket messages size to 4096 for now :(
