### ISSUE TITLE
Connection error moving from version 4.1.6-3 to  version 4.3.2-4

### ISSUE THREAD

**Issue by marcoevang** [warmcat/libwebsockets#3098]
I successfully used libwesockets version 4.1.6-3 in my project  [camilladsp-setrate](https://github.com/marcoevang/camilladsp-setrate)  on a Raspberry Pi 4/dietpi v9.2.1. 
Other users also had success with version 4.1.6-3 on Raspberry Pi/Raspberry Pi OS. 
Note that:
- The server and the client run on the same computer
- 4.1.6-3 is the latest version available on dietpi.

I then built that project on Raspberry Pi 4/Ubuntu 23.10, where libwebsockets is at version 4.3.2-4.
On this environment, immediately after a successful connection to the websocket server, the callback function is called with reason "LWS_CALLBACK_CLIENT_CONNECTION_ERROR" and the associated info contains the following message:
"HS: Rejected at CLIENT_ESTABLISHED". 
Other users had the same experience.
The environment in which the issue occurs differs only in the operating system and the version of libwebsockets.
Note that:
- Downgrading libwebsockets to version 4.1.6-3 (on Ubuntu 23.10), everything works well as expected.

**Comment by lws-team** [comment]
Check that your handler for `LWS_CALLBACK_CLIENT_ESTABLISHED` returns 0 - otherwise later lws feels you are denying the connection.

**Comment by marcoevang** [comment]
Indeed the callback function returned the value of al local variable that, in a particular case, was not assigned. Hence that value was random, and the correct or wrong operation was pure chance!!!

Thanks a lot. And, please, close this issue due to a bug in my software.
