### ISSUE TITLE
High cpu usage observed while using lws_cancel_service_pt() to achieve high reliability

### ISSUE THREAD

**Issue by anmol-ap** [warmcat/libwebsockets#3103]
Using lws_cancel_service_pt to generate immediate interrupt to wake up the event loop causes very high cpu usage.

The program sends around 200 events per second to the server. Events are added to the ring buffer as soon as they are generated.

Expected behaviour is : LWS_CALLBACK_EVENT_WAIT_CANCELLED should be generated as soon as the event is ready to be sent and event should be sent to the server immediately.

Observed behaviour is : LWS_CALLBACK_EVENT_WAIT_CANCELLED callback is called around 1/10 times of the events generated, due to which events are still in the ring buffer queue. If lws_cancel_service_pt() is used in a for loop (along with lws_service which is always used), the cpu usage is too high and keeps increasing although it is mentioned that it is a cheap call. Without using lws_cancel_service_pt(), the cpu usage is normal.

Requirement is event should be sent as soon as it is added to queue as priority is server receives the event as soon as it is generated at client.

What am I doing wrong ? How can I achieve fast event rate (although achieved using lws_cancel_service_pt but causes high cpu usage) ?

**Comment by lws-team** [comment]
You don't mention your platform.  Or show your code.  Or the lws version.

> the cpu usage is too high and keeps increasing although it is mentioned that it is a cheap call.

If you do something expensive in the callback, this can easily be the result.  Or if the platform is slow.

You can see if -DCMAKE_BUILD_TYPE=RELEASE helps.  Otherwise showing a minimal reproducer is the way.

**Comment by anmol-ap** [comment]
Hi, Sorry for not posting all the information.
Let me share the details, I am stuck in this problem for quite a while now.

root@ip-xx:/home/ubuntu# uname -a
Linux ip-xxx 5.15.0-1055-aws #60~20.04.1-Ubuntu SMP Thu Feb 22 15:49:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Version - v4.3.2

`static int
callback_minimal_broker(struct lws *wsi, enum lws_callback_reasons reason,
                        void *user, void *in, size_t len)
{
    vhdGlobal = (struct per_vhost_data__minimal *)
        lws_protocol_vh_priv_get(lws_get_vhost(wsi),
                                 lws_get_protocol(wsi));
    const struct msg *pmsg;
    void *retval;
    int n, m, r = 0;

    switch (reason)
    {

    /* --- protocol lifecycle callbacks --- */
    case LWS_CALLBACK_CLIENT_RECEIVE:
        
        
        memset(control_command_buf, 0, PATH_MAX*16);
        lws_strncpy(control_command_buf, in, PATH_MAX*16-1);
        process_control_command(control_command_buf);

        break;
    case LWS_CALLBACK_PROTOCOL_INIT:

        vhdGlobal = lws_protocol_vh_priv_zalloc(lws_get_vhost(wsi),
                                                    lws_get_protocol(wsi),
                                                    sizeof(struct per_vhost_data__minimal));
        vhdGlobal->context = lws_get_context(wsi);
        vhdGlobal->protocol = lws_get_protocol(wsi);
        vhdGlobal->vhost = lws_get_vhost(wsi);
        
        char *rec_data = (char *)lws_context_user(vhdGlobal->context);
        
        vhdGlobal->event = rec_data;

        vhdGlobal->ring = lws_ring_create(sizeof(struct msg), ring_buffer_size,
                                              __minimal_destroy_message);
        if (!vhdGlobal->ring)
            return 1;

        pthread_mutex_init(&vhdGlobal->lock_ring, NULL);

        if (connect_client(&vhdGlobal->sul)) {
            lws_sul_schedule(vhdGlobal->context, 0, &vhdGlobal->sul,
                 connect_client_sul_cb, LWS_US_PER_SEC); // this is milli seconds per second, means takes milliseconds as value and 1 second is passed
        }
        break;

    case LWS_CALLBACK_PROTOCOL_DESTROY:

        vhdGlobal->finished = 1;

        if (vhdGlobal->ring)
            lws_ring_destroy(vhdGlobal->ring);

        lws_sul_cancel(&vhdGlobal->sul);

        pthread_mutex_destroy(&vhdGlobal->lock_ring);

        conn_established = 0;

        return r;

    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
        vhdGlobal->client_wsi = NULL;
        conn_established = 0;
            int wait_sec = random_connect_wait();
            FPRINTF_FL("waiting for random 5-15 seconds before next retry : %d\n", wait_sec);
            lws_sul_schedule(vhdGlobal->context, 0, &vhdGlobal->sul,
                 connect_client_sul_cb, wait_sec * LWS_US_PER_SEC);
        break;
        /* --- client callbacks --- */

    case LWS_CALLBACK_CLIENT_ESTABLISHED:
        vhdGlobal->established = 1;
        conn_established = 1;
        
        break;

    case LWS_CALLBACK_CLIENT_WRITEABLE:

            FPRINTF_FL("%s\n", "In callback minimal : LWS_CALLBACK_CLIENT_WRITEABLE");

            pthread_mutex_lock(&vhdGlobal->lock_ring); /* --------- ring lock { */
            pmsg = lws_ring_get_element(vhdGlobal->ring, &vhdGlobal->tail);
            if (!pmsg)
                goto skip;

            /* notice we allowed for LWS_PRE in the payload already */
            m = lws_write(wsi, ((unsigned char *)pmsg->payload) + LWS_PRE,
                        pmsg->len, LWS_WRITE_TEXT);
            if (m < (int)pmsg->len)
            {
                pthread_mutex_unlock(&vhdGlobal->lock_ring); /* } ring lock */
                lwsl_err("ERROR %d writing to ws socket\n", m);
                return -1;
            }
            lws_ring_consume_single_tail(vhdGlobal->ring, &vhdGlobal->tail, 1);

        skip:
            pthread_mutex_unlock(&vhdGlobal->lock_ring); /* } ring lock ------- */
        break;

    case LWS_CALLBACK_CLIENT_CLOSED:
        FPRINTF_FL("%s\n", "In callback minimal : LWS_CALLBACK_CLIENT_CLOSED");
        vhdGlobal->client_wsi = NULL;
        vhdGlobal->established = 0;
        conn_established = 0;
        int wait_sec1 = random_connect_wait();
        FPRINTF_FL("waiting for random 5-15 seconds before next retry LWS_CALLBACK_CLIENT_CLOSED : %d\n", wait_sec1);

        lws_sul_schedule(vhdGlobal->context, 0, &vhdGlobal->sul,
                 connect_client_sul_cb, wait_sec1 * LWS_US_PER_SEC);
        break;

    case LWS_CALLBACK_EVENT_WAIT_CANCELLED:

        /*
         * When there is an add message to the ringbuffer,
         * they create this event in the lws service thread context
         * using lws_cancel_service().
         *
         * We respond by scheduling a writable callback for the
         * connected client, if any.
         */
        // FPRINTF_FL("%s\n", "In callback minimal : LWS_CALLBACK_EVENT_WAIT_CANCELLED");
        if (vhdGlobal && vhdGlobal->client_wsi && vhdGlobal->established)
            lws_callback_on_writable(vhdGlobal->client_wsi);
        break;

    default:
        break;
    }

    return lws_callback_http_dummy(wsi, reason, user, in, len);
}


void send_from_queue(char *data_to_send, char* parent_id) {

    if (NULL == vhdGlobal) {
        // FPRINTF_FL("Websocket client not connected yet, dropping event : %s", data_to_send);
        nr_free(data_to_send);
        return;
    }

    FPRINTF_FL("%s\n", "In callback minimal : send_from_queue");

    pthread_mutex_lock(&vhdGlobal->lock_ring);
    struct msg amsg;
    int len = strlen(data_to_send), index = 1, n, size;
    n = (int)lws_ring_get_count_free_elements(vhdGlobal->ring);
    
    amsg.payload = nr_malloc(LWS_PRE + len + 1);
    n = lws_snprintf((char *)amsg.payload + LWS_PRE, len + 1, "%s", data_to_send);

    nr_free(data_to_send);
    data_to_send = NULL;
    amsg.len = n;
    n = lws_ring_insert(vhdGlobal->ring, &amsg, 1);
    if (n != 1)
    {
        FPRINTF_FL(“Not able to put message in ring buffer, dropping : %zu bytes : message : %s", amsg.len, (char*)(amsg.payload + LWS_PRE));
        __minimal_destroy_message(&amsg);
        pthread_mutex_unlock(&vhdGlobal->lock_ring);
        
    }
    else
    {
        pthread_mutex_unlock(&vhdGlobal->lock_ring);
    }
    // callback_minimal_broker(vhdGlobal->client_wsi, LWS_CALLBACK_EVENT_WAIT_CANCELLED, NULL, NULL, 0);
    // lws_cancel_service_wrapper();
    // size = lws_ring_get_count_waiting_elements(vhdGlobal->ring, NULL);
}

void send_data(char* data, bool is_health_check) {
    send_from_queue(data, NULL);
    if (is_health_check) { // reset
        …
    }
}
`

send_data is called by the program to send max 4KB data to the server.

The problem is, without using lws_cancel_service, the event_wait_cancelled callback is delayed and is not called.

grep "In callback minimal : send_from_queue" abc.log | wc -l
2636
grep "In callback minimal : LWS_CALLBACK_CLIENT_WRITEABLE" abc.log | wc -l
145

I am just writing the event to server through writable, I am not sure why the for loop for lws_cancel_service_pt is causing high cpu usage.

**Comment by lws-team** [comment]
On linux, lws_cancel_service() just adds a byte into a pipe.  The pipe is automatically added to the event wait.  So as soon as somebody adds a byte there, the service loop on the lws thread will wake and get on with it.  There's no big cpu going on.

If you're adding small things to the ring very quickly, the overhead of asking for the write, getting it, locking, writing the entry and unlocking and the additional times around the event loop will add up, maybe that's the source of the cpu.  (Also much more logging and other delays come from building in debug mode, it might help to use on cmake -DCMAKE_BUILD_TYPE=RELEASE for lws).

You may be able to reduce your problem by looping in the WRITEABLE callback concatenating multiple entries in the ring buffer into one write on the wire.  So instead of n writes going on for n ringbuffer entries, you can fit as many as will fit into your, say, 2K or 4K buffer and consume all those ringbuffer entries with one write.

**Comment by anmol-ap** [comment]
This is very helpful @lws-team. I have looked up a couple of other threads and read your comments on those threads. One was particularly helpful : https://github.com/warmcat/libwebsockets/issues/1833#issuecomment-579288487

I looked up the examples and added 

`/* more to do for us? */
			if (lws_ring_get_element(vhdGlobal->ring, &vhdGlobal->tail))
				/* come back as soon as we can write more */
				lws_callback_on_writable(wsi);`

inside LWS_CALLBACK_CLIENT_WRITEABLE
and added

`lws_cancel_service(lws_get_context(vhdGlobal->client_wsi));
pthread_mutex_unlock(&vhdGlobal->lock_ring);`

in the send_from_queue method.

I am seeing a stable CPU and Memory usage so far (the test is still running).

I have one more request from you regarding the timeout for lws_service().

Let me share the problem first :
I have a limitation that I cannot create more that one thread in the application. Now that single thread is being used for infinite loop for lws_service() which is mandatory. Also, that same thread is being used to send healthcheck and other data for which 5-10 seconds delay don't really matter. But I have some other task which I need to do every 10 seconds which is sometimes getting delayed to 30 seconds (lws_service() is in the same while loop). I cannot call lws_cancel_service() from main thread with any loop.

Although this question has been asked before also and I referred to this : https://github.com/warmcat/libwebsockets/issues/3026#issuecomment-1848431699

Could you help me understand how I can use lws_sul to wake up lws_service() after 10 seconds. I enabled the logging of the library also, but I could not understand what is waking up lws_service() with a timeout of 30 seconds when no callback is received and how I can make it to 10 seconds.
This would be greatly appreciated.

**Comment by anmol-ap** [comment]
Thank you very much for all the help.
The issue created was a coding mistake.
Thanks for the wonderful and efficient library.
