### ISSUE TITLE
Out of date build instructions for wolfSSL support

### ISSUE THREAD

**Issue by 0xg0nz0** [warmcat/libwebsockets#3116]
Currently the documentation here:

https://libwebsockets.org/lws-api-doc-master/html/md_READMEs_README_8build.html#wolf

states the following:

> NOTE: wolfssl needs to be compiled using the `--enable-opensslextra` flag for this to work.

Per discussion with the wolfSSL team, the correct flag for LWS support is`--enable-libwebsockets`:

https://github.com/wolfSSL/wolfssl/issues/7432#issuecomment-2059883136

If you just specify `--enable-opensslextra` you will get lws compile errors when using wolfSSL.

**Comment by lws-team** [comment]
Thanks... I did test this back in the day and the wolfssl I had lacked that switch, it built with opensslextra.  I changed the docs according to what you wrote on main and v4.3-stable.
