### ISSUE TITLE
How to pass the query component to connect web server?

### ISSUE THREAD

**Issue by nikunjp26** [warmcat/libwebsockets#3117]
Dear Team,

we are using this library for our websocket connection. now we are trying to connect the wss link as per below.

![MicrosoftTeams-image (3)](https://github.com/warmcat/libwebsockets/assets/31069430/74d9373b-2920-4253-873b-c087cbe0aa65)
![MicrosoftTeams-image (1)](https://github.com/warmcat/libwebsockets/assets/31069430/0b82ce39-3526-458f-b45a-d9f0c105ce83)

Below is our server url which we need to connect 
wss://url/ws?query=value

so can you please guide us how we need to connect this? or will be appreciate if you can share the sudo example code.

best regards,
Nikunj patel

**Comment by lws-team** [comment]
See eg, minimal-examples-lowlevel/ws-client/minimal-ws-client/minimal-ws-client.c

Adapt `i.path` (line 65) to include the query.
