### ISSUE TITLE
Passing the HTTP reject error code returned by server to the client application

### ISSUE THREAD

**Issue by MGadkari** [warmcat/libwebsockets#312]
Problem - If connection request parameters sent by client are not valid then server will return appropriate error code in initial http handshake process according to HTTP RFC (https://tools.ietf.org/html/rfc2616#page-39)
This error code (status code and response frame) received from server is required to be notified to the client application by libwebsockets library as per project requirement. Based on the status code and response frame, the client application needs to take corrective action.

Analysis - As per libwebsockets default behavior for current version, When server rejects http handshake and returns any error code, library sends no parameter (NULL) to client application in connection error callback. The libwebsockets library does not pass the status code and response frame received from server to the client application in callback. 
file - /lib/client.c

Int lws_client_interpret_server_handshake(struct libwebsocket_context *context, struct libwebsocket *wsi)
{
...
bail2:
	if (wsi->protocol)
		wsi->protocol->callback(context, wsi,
			'''LWS_CALLBACK_CLIENT_CONNECTION_ERROR,'''
					wsi->user_space,''' NULL, 0''');
...
}

Solution - Code modifications required to fix this problem are as below -  
1. Read the received status code and response frame from server when connection is rejected
2. Pass the string to client application in connection error callback

Impacted functionalities of the libwebsockets library due to modifications - Connection error callback will include the HTTP reject status code and response frame received from server. This string passed in Connection error callback can be read or ignored by client application based on client application requirement

The fix for this issue has been submitted in Pull request 311

**Comment by JoakimSoderberg** [comment]
This I guess could've been included directly in the #311 PR :)

I'm just saying that so that the link here should show up in that PR by using #

**Comment by warmcat** [comment]
Ah it's pushed already thanks.

**Comment by vinod82** [comment]
can similar approach be used to propagate SSL errors to the client ?.
I am getting SSL error 9 from libwebsockets. If i can get SSL err codes at client side, application 
can act on it depending on the err code.
