### ISSUE TITLE
Linker errors due to missing systemd symbols

### ISSUE THREAD

**Issue by dddaniel** [warmcat/libwebsockets#3129]
/usr/bin/ld: /usr/local/lib/libwebsockets.so: undefined reference to sd_is_socket_inet
/usr/bin/ld: /usr/local/lib/libwebsockets.so: undefined reference to sd_is_socket_unix
/usr/bin/ld: /usr/local/lib/libwebsockets.so: undefined reference to sd_listen_fds

These linker errors occur when linking aginst libwebsockets with this simple example program:
`#include <libwebsockets.h>

static struct lws_protocols protocols[] = {
	{
		.name = "lws",
		.callback = NULL,
		.per_session_data_size = 0,
		.rx_buffer_size = 65536,
		.tx_packet_size = 0,
		.id = 0,
		.user = NULL
	},
	{ NULL, NULL, 0, 0, 0, NULL, 0 }
};

static struct lws_context_creation_info lws_info = {
	.protocols = protocols,
	.port = 8000,
};

int main()
{
	struct lws_context *lws_ctx;

	lws_ctx = lws_create_context(&lws_info);
	if (lws_ctx == NULL) {
		fprintf(stderr, "lws_create_context failed\n");
		return -1;
	}
	return 0;
}
`

`cmake_minimum_required(VERSION 3.5)
project(example C)

add_definitions(-g3 -O2 -Wall -Wextra)
add_executable(example main.c)
target_link_libraries(example websockets)
install(TARGETS example RUNTIME DESTINATION bin)
`

Libwebsockets has been build from the latest main branch with these options:
`-DCMAKE_BUILD_TYPE=Release
-DLWS_IPV6=on
-DLWS_WITH_EXTERNAL_POLL=ON
-DLWS_WITH_MBEDTLS=on
-DLWS_WITH_ULOOP=ON
-DLWS_WITHOUT_TESTAPPS=on
-DLWS_WITHOUT_TEST_SERVER=ON
-DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON
-DLWS_WITHOUT_TEST_PING=ON
-DLWS_WITHOUT_TEST_CLIENT=ON
`

Sorry for the messy format, but the code tags don't seem to work in github.

**Comment by lws-team** [comment]
LWS_WITH_ULOOP == with systemd

**Comment by lws-team** [comment]
The mbedtls thing was reported last week for v3.6, see here for workaround https://github.com/warmcat/libwebsockets/issues/3127 or use 3.5

**Comment by dddaniel** [comment]
> The mbedtls thing was reported last week for v3.6, see here for workaround #3127 or use 3.5

I know, but I am still confused about that systemd uloop thing. 
When ignoring the warnings with -DDISABLE_WERROR=ON and building with -DLWS_WITH_ULOOP=OFF ,
 libwebsockets builds, but the systemd symbols are still required when building the example program.

**Comment by lws-team** [comment]
Sounds like you're working...  btw LWS_WITH_EXTERNAL_POLL is not a good idea and won't work with event lib support.

**Comment by dddaniel** [comment]
> Sounds like you're working... btw LWS_WITH_EXTERNAL_POLL is not a good idea and won't work with event lib support.

I want to use external polling, without any systemd/uloop event loops.
That's why I build with these options now:
`-DLWS_WITHOUT_TESTAPPS=on -DCMAKE_BUILD_TYPE=Release -DLWS_IPV6=on -DLWS_WITH_EXTERNAL_POLL=ON -DLWS_WITH_MBEDTLS=on -DLWS_WITH_ULOOP=OFF -DLWS_WITHOUT_TEST_SERVER=ON -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON -DLWS_WITHOUT_TEST_PING=ON -DLWS_WITHOUT_TEST_CLIENT=ON -DDISABLE_WERROR=ON -DLWS_WITH_SDEVENT=OFF`

But the issue is still present. libwebsockets build with these options is referencing systemd library symbols.

**Comment by lws-team** [comment]
It's foss, so you can do what you like according to LICENSE.  But that doesn't cover my running around supporting it like we have some kind of SLA.

**Comment by dddaniel** [comment]
> It's foss, so you can do what you like according to LICENSE. But that doesn't cover my running around supporting it like we have some kind of SLA.

Sorry, I wrongfully assumed you care about bugs in your software.

**Comment by lws-team** [comment]
Bye.
