### ISSUE TITLE
insecure websockets sometimes fail when LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT option is used

### ISSUE THREAD

**Issue by thomgree** [warmcat/libwebsockets#313]
When using the LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT and using non-ssl websockets they fail for me about 1 in 100 times.

I have worked out why this happens:
in ssl.c recv() is called with MSG_PEEK to see if the forthcoming output is ASCII (implying HTTP, and if so jumps to accept anyway); if that data hasn't arrived yet it usually returns -1 and you the get SSL_ERROR_WANT_READ from the SSL_accept().
However, if the data arrives precisely between the (failed) recv(MSG_PEEK) and the
subsequent SSL_accept(), the SSL_accept() fails because it is not expecting plain HTTP (i.e. the code "protecting" the SSL_accept() from the HTTP failed to work).

**Comment by thomgree** [comment]
Confirmed that this was the reason by checking the OpenSSL error queue after the failed SSL_accept()
I get "error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request"

**Comment by warmcat** [comment]
Please try current HEAD if this is still a live issue for you.

**Comment by thomgree** [comment]
This does not seem to work.

I think https://github.com/warmcat/libwebsockets/commit/dbbd31141a1bddf727cb50b4137a987277c6c882 is wrong:

`if (n == 0 || n == LWS_EAGAIN || n == LWS_EWOULDBLOCK)` line needs to be checking errno values not the return code from recv()

**Comment by thomgree** [comment]
Even if I change that line, the set-up I used to reproduce the problem is not working when using current HEAD so I guess something else has changed.
I have stopped using LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT in my application anyway, so I do not have much time to try to debug this.

**Comment by lws-team** [comment]
Well, I fixed the errno thing thanks and checked it still works normally here.  If you or someone else gets problems again please reopen.
