### ISSUE TITLE
How to access struct ssl_st and socket fds used by libwebsockets client for integrating with io_uring?

### ISSUE THREAD

**Issue by alptugp** [warmcat/libwebsockets#3131]
I'm currently working on integrating io_uring for polling into my libwebsockets (lws) client application. As part of this process, I need to use OpenSSL BIO to interface OpenSSL with io_uring. Additionally, I also need to access the socket file descriptors (fds) used by the libwebsockets client to perform read syscalls with io_uring.

To achieve this integration, I require access to the struct ssl_st that my libwebsockets client uses to set up the BIOs, as well as the socket fds that it utilizes for read syscalls.

However, I'm unsure about how to access these components within the libwebsockets client context.

Could someone please provide guidance on how I can access both the struct ssl_st and the socket fds used by my libwebsockets client?

Any help or pointers would be greatly appreciated!

Thank you.

**Comment by lws-team** [comment]
SSL is opaque and depends on your OpenSSL.  If you just want to pass it to OpenSSL apis it should be ok.

`lws_get_socket_fd(wsi)` can get the fd.

For openssl, you can also use `SSL* lws_get_ssl(wsi)`
