### ISSUE TITLE
 Issue with Integrating libev Loop with lws for WebSocket Client

### ISSUE THREAD

**Issue by alptugp** [warmcat/libwebsockets#3132]
I'm developing a WebSocket client that connects to a server sending approximately 120 messages per minute. I integrated libev with lws using the "foreign event loop" style, i.e., by telling lws about my libev event loop object when creating the lws context and then running the libev event loop. I checked the example in [minimal-http-server-eventlib-foreign.c](https://github.com/warmcat/libwebsockets/tree/main/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign) and followed its approach to integrate libev with lws. 

When utilizing the currently commented-out lws_service loop below instead of ev_run, everything works perfectly fine, and the client receives WebSocket messages as expected. However, upon using ev_run instead of the lws_service loop, the socket_cb function is never called, and the program hangs after printing the provided terminal output. I'd appreciate some guidance on how to proceed further to ensure that my libev loop, which will be used for polling the socket fd, properly integrates and works with lws. Being able to see "socket_cb is called" in the terminal is my objective.

Terminal output when ev_run is used:
aap221@pixel31:lws$ ./main
[2024/05/08 21:28:14:4851] U: LWS client rx [-d <logs>] [--h2] [-t (test)]
[2024/05/08 21:28:14:4856] N: lws_create_context: LWS: 4.3.99-v4.3.0-361-gf28a4524, NET CLI SRV H1 H2 WS SS-JSON-POL ConMon IPv6-absent
[2024/05/08 21:28:14:4857] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2024/05/08 21:28:14:4858] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2024/05/08 21:28:14:4889] N: __lws_lc_tag:  ++ [vh|1|default||-1] (2)
[2024/05/08 21:28:14:5516] N: __lws_lc_tag:  ++ [wsicli|0|WS/h1/default/ws.bitmex.com] (1)
[2024/05/08 21:28:14:6009] N: [wsicli|0|WS/h1/default/ws.bitmex.com]: lws_client_connect_3_connect: trying 172.64.155.181

Code Snippet:
```
static void socket_cb (EV_P_ ev_io *w, int revents) {
        puts ("socket_cb is called");
}

static struct lws *client_wsi;
static struct ev_loop *loop_ev; 
ev_io socket_watcher;
ev_timer timeout_watcher;

int main(int argc, const char **argv)
{
	struct lws_context_creation_info info;
	struct lws_client_connect_info i;
	struct lws_context *context;
        const char *p;
	int n = 0, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE;

	signal(SIGINT, sigint_handler);

	lws_set_log_level(logs, NULL);
	lwsl_user("LWS client [-d <logs>] [--h2] [-t (test)]\n");

	memset(&info, 0, sizeof info);
	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT | LWS_WITH_LIBEV;
	info.port = CONTEXT_PORT_NO_LISTEN; 
	info.protocols = protocols;
	
	loop_ev = EV_DEFAULT;
        void *foreign_loops[1];
        foreign_loops[0] = loop_ev;
        info.foreign_loops = foreign_loops;

	info.fd_limit_per_thread = 1 + 1 + 1;

	context = lws_create_context(&info);
	if (!context) {
		lwsl_err("lws init failed\n");
		return 1;
	}

	memset(&i, 0, sizeof i);
	i.context = context;
	i.port = 443;
	i.address = "ws.bitmex.com";
	i.path = "/realtime?subscribe=orderBookL2_25:XBTUSD";
	i.host = i.address;
	i.origin = i.address;
	i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_PRIORITIZE_READS;
	i.protocol = NULL; 
	i.pwsi = &client_wsi;

	lws_client_connect_via_info(&i);

        ev_io_init (&socket_watcher, socket_cb, lws_get_socket_fd(client_wsi), EV_READ);
        ev_io_start (loop_ev, &socket_watcher);
        
        ev_run (loop_ev, 0);

	// while (n >= 0 && client_wsi && !interrupted)
	// 	n = lws_service(context, 0);

	lws_context_destroy(context);

	return 0;
}
```

**Comment by lws-team** [comment]
You can't do this hack of trying to cram the client connect in with event loops before starting them.

Study https://libwebsockets.org/git/libwebsockets/tree/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign and instead set an almost immediate native libev timer when creating the loop, in the timer event, once the loop is up, do the client connect.
