### ISSUE TITLE
Does libwebsocket has API which will directly  access certificate store.

### ISSUE THREAD

**Issue by sush126** [warmcat/libwebsockets#3142]
Hi @lws-team , "I want to access the Windows Certificate Store to find a certificate. Is there an API in libwebsockets that can do this?"

**Comment by lws-team** [comment]
If you use OpenSSL, and set -DLWS_SSL_CLIENT_USE_OS_CA_CERTS=1 then lws will import CA certs from the OS trust store.

If that's not it, you can at least take the code from lib/plat/windows/windows-sockets.c lws_plat_vhost_tls_client_ctx_init()
