### ISSUE TITLE
could not decode a text frame as utf-8

### ISSUE THREAD

**Issue by limingyuxia** [warmcat/libwebsockets#3144]
continuous writing text, browser come cross this error. and set the rx_buffer_size to 1M

**Comment by lws-team** [comment]
Not sure what you're expecting me to do about it... it sounds like there is a problem sending on the wire everything you want to send.  But what does your code look like?

**Comment by limingyuxia** [comment]
sorry, I write some text contains binary byte. have already solve it.

**Comment by lws-team** [comment]
Well, thanks for recording the reason.
