### ISSUE TITLE
How do I send the answer for POST asynchronously

### ISSUE THREAD

**Issue by horchi** [warmcat/libwebsockets#3167]
I like to implement a WEB server with answers POST requests. 

POST requests from several clients are to be processed simultaneously. Preparing the data for the response takes some time. How can I send the response as soon as it is ready without blocking the server for so long? 

Basically I lookm for a solution like the WS with LWS_CALLBACK_SERVER_WRITEABLE.

As far as I can see, the response to the HTTP callback is expected directly at LWS_CALLBACK_HTTP_BODY or LWS_CALLBACK_HTTP_BODY_COMPLETION?

**Comment by lws-team** [comment]
No, it's inherently async... to send a response anyway relies on callback_on_writeable() which can take as long as it likes.

You can just start your process, return 0, ask for the writeable callback (in the lws thread / process...) when you have a response to send.

**Comment by horchi** [comment]
perfects thanks that's what I looking for :) 
What I have tried using LWS_CALLBACK_HTTP_WRITEABLE but it's not called.

callback_on_writeable() is a method? I can't find it searching all the headers, can you please give me a hint?

**Comment by lws-team** [comment]
`lws_callback_on_writable()`

**Comment by lws-team** [comment]
If you will hold the wsi, be aware it can close at any time and be invalid by the time you want to start the reply.  You must monitor the appropriate _CLOSE callback and mark the wsi as invalid for when the process ends.

**Comment by horchi** [comment]
Thanks it's working now.
I had called lws_callback_on_writable_all_protocol with the wrong protocol sorry for the stupid question
