### ISSUE TITLE
Compilation warning "implicit declaration of function ‘mbedtls_x509_get_name’; did you mean ‘mbedtls_pk_get_name’"

### ISSUE THREAD

**Issue by CoinFuMasterShifu** [warmcat/libwebsockets#3169]
[This line](https://github.com/warmcat/libwebsockets/blob/4abdfa810a53321efd3b46857248c0fc3a20f492/lib/tls/mbedtls/mbedtls-extensions.c#L253) triggers a compilation warning
```
libwebsockets-4.3.3/lib/tls/mbedtls/mbedtls-extensions.c:253:23: warning: implicit declaration of function ‘mbedtls_x509_get_name’; did you mean ‘mbedtls_pk_get_name’? [-Wimplicit-function-declaration]
  253 |                 ret = mbedtls_x509_get_name( p, end, &rfc822Name );
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       mbedtls_pk_get_name
```
because the declaration 
```
int mbedtls_x509_get_name(unsigned char **p, const unsigned char *end,
                          mbedtls_x509_name *cur);
```
[is in an internal file `x509_internal.h`](https://github.com/Mbed-TLS/mbedtls/blob/7c52100fbd882437b5fb46e639c5db57bcc56b15/library/x509_internal.h#L24-L25) not exposed to `mbedtls` library headers.

**Comment by lws-team** [comment]
This depends on the version of mbedtls you are building against.

In order to use mbedtls with a minimal amount of certs instantiated, lws needs to be able to find the AKID and SKID on the certs to bring out the certs needed for a validation path.  This isn't supported on mbedtls directly so it has to reproduce some internal mbedtls code to find the AKID and SKID from ASN.1.  That works fine, until mbedtls removed the export needed for it.

You can work around it by using a slightly earlier mbedtls, or manually adding back the export at mbedtls.

**Comment by CoinFuMasterShifu** [comment]
I think you should just add this explicit declaration [here](https://github.com/warmcat/libwebsockets/blob/4abdfa810a53321efd3b46857248c0fc3a20f492/lib/tls/mbedtls/mbedtls-extensions.c#L215) above the function:
```
int mbedtls_x509_get_name(unsigned char **p, const unsigned char *end,
                          mbedtls_x509_name *cur);
```
For old versions of mbedtls it won't hurt to have the declaration twice (in your code and in mbedtls') and for new versions you silence the warning this way. The implicit declaration is doing nothing else than what you would do with the explicit declaration I proposed above. 
I don't see any reason why you wouldn't do that. Do I miss something?

**Comment by lws-team** [comment]
Oh... I guess I misunderstood your problem...

That's confusing then because I already added a declaration beforehand, in `lib/tls/mbedtls/private-lib-tls-mbedtls.h`

```
#if (MBEDTLS_VERSION_MAJOR == 3) && (MBEDTLS_VERSION_MINOR >= 6)
        int mbedtls_x509_get_name(unsigned char **p, const unsigned char *end,
                                                  mbedtls_x509_name *cur);
#endif
```

what is the version of mbedtls you're building against?

**Comment by CoinFuMasterShifu** [comment]
Version is 3.5.1.

**Comment by lws-team** [comment]
I pushed a patch on main and v4.3-stable changing the declaration to apply if mbedtls >= 3.5 rather than 3.6
