### ISSUE TITLE
lws_hdr_total_length, lws_hdr_copy deadlock

### ISSUE THREAD

**Issue by septag** [warmcat/libwebsockets#317]
Calling these functions inside the protocol callback causes the program to deadlock. is this ok ?

**Comment by warmcat** [comment]
No... but you can only call these http header accessors before the headers are deleted, at the point it switches to websocket protocol.  See the readme.coding here

http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tree/README.coding.md#n204

Availability of header information
----------------------------------

From v1.2 of the library onwards, the HTTP header content is `free()`d as soon
as the websocket connection is established.  For websocket servers, you can
copy interesting headers by handling `LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION`
callback, for clients there's a new callback just for this purpose
`LWS_CALLBACK_CLIENT_FILTER_PRE_ESTABLISH`.
