### ISSUE TITLE
Possibility on separating LWS client from the main context 

### ISSUE THREAD

**Issue by gmfcd128** [warmcat/libwebsockets#3174]
In my current project I have a LWS running mainly as server and sometimes client, and I recently want to use LWS client elsewhere in my code, which may contact remote server under certain conditions.
I think that I may get by creating a new context and a new set of http protocol callback function as needed, but in practice it seems not working.
I want to know what is the recommended way of doing this? I am a little reluctant to put all the logic into one single protocol callback for the main lws_context

**Comment by lws-team** [comment]
The recommended way is a single context for everything.  Any number of client or server listens / adopted connections can coexist inside the context.

You can bind a client connection to a specific local lws_protocol by name in the client connection info struct.  See https://github.com/warmcat/libwebsockets/blob/main/include/libwebsockets/lws-client.h#L176
