### ISSUE TITLE
How to transfer wss protocal to ws?

### ISSUE THREAD

**Issue by bethebest0622** [warmcat/libwebsockets#3179]
My Server Side is based on wss://$host.

Recently, it support ws://$host, how can i tranfer in my setting?

just revise port from 443 to 80? like this:

  ```
struct lws_client_connect_info ccinfo = {0};
  ccinfo.context = ctx_;
  ccinfo.address = cd.ws_setting_.host_.c_str();
  ccinfo.path = cd.ws_setting_.path_.c_str();
  ccinfo.port = ;  // from 443->80???
  ccinfo.host = cd.ws_setting_.host_.c_str();
```

**Comment by lws-team** [comment]
If you want tls, then you should set the bit LCCSCF_USE_SSL on ccinfo.ssl_connection.  If you don't want tls, don't set it.
