### ISSUE TITLE
Dangerous check for __func__

### ISSUE THREAD

**Issue by jacereda** [warmcat/libwebsockets#3181]
Hi,

This will potentially break code including the header:

://github.com/warmcat/libwebsockets/blob/8674bf1585c0196f071eb6f0ae2184c9ca053301/include/libwebsockets.h#L146

`__func__` is not a preprocessor macro, so this test will redefine the builtin mechanism potentially breaking macros that use __func__ in the ways c99 allows.

It should probably check if we're on >=C99.

**Comment by lws-team** [comment]
I guess this is trying to make some really old or gnarnly toolchain work from back in the day before __func__, I added a dependency on it being <C99 as suggested
