### ISSUE TITLE
memory leaks for windows

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#3182]
While using libwebsocket for windows, I noticed there are some memory leaks for following cases.

Case 1: memory leak when destroy context (call lws_context_destroy)
If we call  lws_context_destroy then it doesn't  free the context because of following condition which is true.
pt->inside_lws_service

But in case of unix, it destroys the context in _lws_plat_service_tsi. Following code do that:
if (pt->destroy_self) {
		lws_context_destroy(pt->context);
		return -1;
	}

This code was committed in 2020.
commit 271ca836c89ae3fc54aae222baddc32d8866148c
Author: Andy Green <andy@warmcat.com>
Date:   Thu Jan 23 11:12:28 2020 +0000

When I tried the same code for windows, memory leak issue got fixed.
Can I use this same code & is it confirm that it will not make any impact?
OR am I using libwebsocket in wrong way & don't need to use this code?
Please suggest.

2. While sending/receiving data we call lws_service & send/receive data in our callback which is called by websocket. I found memory is also increasing while using lws_service. We are allocating memory in _lws_change_pollfd & destroy this only when the context is deleted. Should I call any other function to free the memory allocated by lws_service?
To  send any data I call lws_callback_on_writable before lws_service.

Please suggest.

**Comment by lws-team** [comment]
I pushed the change on main and v4.3-stable.
