### ISSUE TITLE
LWS_SERVER_OPTION_LIBUV ignored if LWS_WITH_LIBUV not set

### ISSUE THREAD

**Issue by davidrohr** [warmcat/libwebsockets#3186]
I just had the problem that after gentoo linux OS update one of my libwebsocket-based application no longer worked.
After debugging for a while, it turned out that libwebsockets was no longer build against libuv, so the libuv event loop didn't trigger the libwebsocket callbacks anymore.

I would have expected that `lws_create_context` if `lws_context_creation_info::options` contains `LWS_SERVER_OPTION_LIBUV`, but apparently this option is silently ignored in this case. To me this is very confusing and not easy to catch. I added an `#ifndef LWS_WITH_LIBUV` to throw an error for now, but I think it would be good to handle this on the libwebsocket side.

**Comment by lws-team** [comment]
Thanks, I pushed a patch on v4.3-stable and main that should take care about making clearer errors if there's a runtime selection of a supposedly built-in event lib that doesn't exist.  The built-in event libs were superceded by runtime plugins loaded dynamically for the selected runtime event lib, this would already have given an error.
