### ISSUE TITLE
File serve api not sending Content-Disposition header in response

### ISSUE THREAD

**Issue by athukuria** [warmcat/libwebsockets#3188]
Hi,

here is the code to serve a file via https, But I receive response without header  variable "Content-Disposition:attachment; filename=logs.zip" and recieved content of the file in response body !
Am I missing anything here ?

here is the response headers
![Screenshot from 2024-07-24 12-20-03](https://github.com/user-attachments/assets/a25213aa-f474-44c6-a654-f88212fb554e)

```
	if (lws_serve_http_file(wsi, "/tmp/log.zip", "application/zip", NULL, 0) < 0) {
		lwsl_err("Failed to serve file: %s\n", "/tmp/log.zp");
		lws_return_http_status(wsi, HTTP_STATUS_INTERNAL_SERVER_ERROR, NULL);
		print_info("FILE SERVE FAILED\n");
		return ;
	}
	
```
here is is my mount details:
struct lws_http_mount mount = {
	/* .mount_next */				NULL,				/* linked-list "next" */
	/* .mountpoint */				"/",				/* mountpoint URL */
	/* .origin */					"var/www/", 	/* serve from dir */
	/* .def */						NULL,				/* default filename */
	/* .protocol */					NULL,
	/* .cgienv */					NULL,
	/* .extra_mimetypes */			NULL,
	/* .interpret */				NULL,
	/* .cgi_timeout */				0,
	/* .cache_max_age */			0,
	/* .auth_mask */				0,
	/* .cache_reusable */			0,
	/* .cache_revalidate */			0,
	/* .cache_intermediaries */		0,
	/* .origin_protocol */			LWSMPRO_FILE,		/* files in a dir */
	/* .mountpoint_len */			1,					/* char count */
	/* .basic_auth_login_file */	NULL,
};

Thanks

**Comment by athukuria** [comment]
I also tried 

char disphdr[80];
	snprintf(disphdr, sizeof(disphdr), "Content-Disposition: attachment; filename=%s", "logs.zip");
	int len = strlen(disphdr);

	if (lws_serve_http_file(wsi, "/tmp/logs.zip", "application/zip", disphdr, len) < 0) {
		lws_return_http_status(wsi, HTTP_STATUS_INTERNAL_SERVER_ERROR, NULL);
		print_info("FILE SERVE FAILED\n");
		return ;
	}
	
	But http response has error:
	Parse Error: There seems to be an invalid character in response header key or value in postman

**Comment by lws-team** [comment]
`-DLWS_TLS_LOG_PLAINTEXT_RX=1 -DLWS_TLS_LOG_PLAINTEXT_TX=1` will show what it actually sends

**Comment by athukuria** [comment]
I tried that here is what I see Header seems okay

Jul 29 11:30:20   httpd[1092]: HEADER: Content-Disposition: attachment; filename=logs.zip len: 50
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3148] N: lws_ssl_capable_write: len 148
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3149] N:
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3150] N: 0000: 48 54 54 50 2F 31 2E 31 20 32 30 30 20 4F 4B 0D    HTTP/1.1 200 OK.
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3154] N: 0010: 0A 63 6F 6E 74 65 6E 74 2D 74 79 70 65 3A 20 61    .content-type: a
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3155] N: 0020: 70 70 6C 69 63 61 74 69 6F 6E 2F 7A 69 70 0D 0A    pplication/zip..
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3156] N: 0030: 63 6F 6E 74 65 6E 74 2D 6C 65 6E 67 74 68 3A 20    content-length:
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3157] N: 0040: 32 37 34 31 39 0D 0A 63 61 63 68 65 2D 63 6F 6E    27419..cache-con
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3158] N: 0050: 74 72 6F 6C 3A 20 6E 6F 2D 73 74 6F 72 65 0D 0A    trol: no-store..
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3159] N: 0060: 43 6F 6E 74 65 6E 74 2D 44 69 73 70 6F 73 69 74    Content-Disposit
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3160] N: 0070: 69 6F 6E 3A 20 61 74 74 61 63 68 6D 65 6E 74 3B    ion: attachment;
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3161] N: 0080: 20 66 69 6C 65 6E 61 6D 65 3D 6C 6F 67 73 2E 7A     filename=logs.z
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3161] N: 0090: 69 70 0D 0A                                        ip..
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3162] N:
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3166] D: [wsisrv|0|adopted]: lwsi_set_state: lwsi_set_state 0x20000119 -> 0x20000015
Jul 29 11:30:20   httpd[1092]: [2024/07/29 11:30:20:3168] D: [wsisrv|0|adopted]: _lws_change_pollfd: fd 12 events 1 -> 5

**Comment by athukuria** [comment]
This worked
	char disphdr[80] = "Content-Disposition: attachment; filename=\"logs.zip\"\r\n";
