### ISSUE TITLE
libwebsocket_service hangs if the server is not running, doesn't even timeout

### ISSUE THREAD

**Issue by hamarisuraksha** [warmcat/libwebsockets#319]
//on ws
//on commit - 3ae1badae7a05e0982e0dfbcb078da3d4b92a81d 
    websocket->impl = libwebsocket_client_connect( context_t, address, port, ssl_conn,
                           path, address, "origin",
                            NULL, -1);
 	while(!force_exit)
	{
        
        if(context_t != NULL){
            libwebsocket_service(context_t, 100); //hangs indefinitely in second iteration.
        }

        if(websocket->impl == NULL && context_t != NULL)
        {
            websocket->impl = libwebsocket_client_connect( context_t, address, port,ssl_conn,
                                        path, address, "origin",
                                        NULL, -1);
        
        }
    }

This is the callback, where I am setting the lws instance to NULL

     int
      callback_lib(struct libwebsocket_context *context,
	 	struct libwebsocket *wsi,
	 	enum libwebsocket_callback_reasons reason, void *user,
	 						   void *in, size_t len)
      { 	switch(reason)
	    {
	    case LWS_CALLBACK_CLIENT_ESTABLISHED:
                libwebsocket_callback_on_writable(context, wsi);
                websocket->impl = wsi;
                break;
	   case LWS_CALLBACK_CLIENT_RECEIVE:
                websocket->impl = wsi;
                break;
	   case LWS_CALLBACK_CLIENT_WRITEABLE:
                websocket->impl = wsi;
                break;
           case LWS_CALLBACK_CLOSED:
           case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
           case LWS_CALLBACK_WSI_DESTROY:
           case LWS_CALLBACK_PROTOCOL_DESTROY:
                 websocket->impl = NULL;
                 break;
	    default:
                break;
	}
    on_message_callback(websocket, convertenum(reason), in, len);
    return WS_SUCCESS;
}

**Comment by JoakimSoderberg** [comment]
Some pointers:
1. Did you get the [test-server/test-client.c](https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c) working? Work from that example and see what you're doing differently.
2. Is it the same for all versions of libwebsockets? You mention a specific commit
3. Use `lws_set_log_level` to turn on all debugging for libwebsockets to see if you get any clues.
4. Run the program using `gdb` and break when it gets stuck, to see where. (Or xcode/visual studio depending on platform)

**Comment by hamarisuraksha** [comment]
I referred to the code from test-client.c only. 
In previous versions of libwebsockets  - specifically 29-03-15, I see that the connection gets broken every 60 seconds, and isn't reported unless we try to send some data. Hence, had to move to the latest. On the latest bumped this one!

I will enable logs, and will try gdb...

**Comment by JoakimSoderberg** [comment]
>  I see that the connection gets broken every 60 seconds, and isn't reported unless we try to send some data

Are you controlling the server you're testing towards as well? Sounds suspiciously as if the server kills the connection. Note that if the server is expecting websocket pings, those are not automatically sent by libwebsockets.

**Comment by warmcat** [comment]
It's worth checking how the test client himself acts if you point him at a machine that doesn't exist, has no server or is firewalled.  Here, on Linux

 - no route (192.168.3.3 when no 192.168.3.0/24 route): immediate LWS_CALLBACK_CLIENT_CONNECTION_ERROR

 - no server, firewalled to drop (192.168.1.1 in my case): 5 seconds timeout passes and then LWS_CALLBACK_CLIENT_CONNECTION_ERROR

 - no server,no firewall (localhost with no server running): immediate LWS_CALLBACK_CLIENT_CONNECTION_ERROR

This represents no problem: If you get different results with the same code please reopen and we can discuss.
