### ISSUE TITLE
SSLKEYLOGFILE : ssl log file is getting locked by multiple process on windows

### ISSUE THREAD

**Issue by VaibhavTekale1** [warmcat/libwebsockets#3191]
[@lws-team](https://github.com/lws-team) Hi, with reference to merged pull request : **[#3066]**

Facing file lock problem (Windows):
If we set the environment variable "**SSLKEYLOGIFLE**," it results in logging SSL keys into a logfile. However, the environment **variable name is generic**, causing multiple processes on Windows to handle that file. As a result, the **log file gets locked** and cannot be deleted until all processes that have handled the log file are **terminated**.

**Possible solutions**:
1.Instead of using a hardcoded environment variable name, can we make it **configurable** ?
For example, if a user wants to export SSL keys for their application, they could specify an environment variable to LWS that is configurable at build time.

2.Can we rename "**SSLKEYLOGIFLE**" to "**LWS_SSLKEYLOGFILE**"  or any other names suggestions ?

Or, are there any other possible solutions you can suggest to prevent the SSL log file from **getting locked**?

Attached Image for the same : 
![File_Lock](https://github.com/user-attachments/assets/4e022f0a-ff9c-40df-a69b-4627079740c1)

**Comment by lws-team** [comment]
At least on *nix, you can control the environment that a process is going to see when you start the process, eg MYVAR=123 myapp   I think it is the same for windows.  You do not have to set some kind of superglobal environment at the "grandmother of all processes" so all processes it spawns, even your desktop and browser, inherit the same environment variable.
