### ISSUE TITLE
Should I use libwebsockets for a bunch of computers sending real time data to a central server?

### ISSUE THREAD

**Issue by lucas-mior** [warmcat/libwebsockets#3194]
Suppose I have some (~10) computers running across the country, producing data with a time sample of 1 second.
Would it be advisable to install a server made with libwebsockets on each of them so that they send the data to a central server which will store it? What would be the security implications? Also performance?
I ask it for learning purposes.

**Comment by lws-team** [comment]
Nobody knows what you 'should' do.  What you can do is put an lws client on each to a central server.  Your data is all in one place so you need to take more care about it.  Performance, is it a big issue at 1 chunk a second assuming they have reliable and fast comms?
