### ISSUE TITLE
Application got stuck due to default timeout of 23 days  

### ISSUE THREAD

**Issue by ManojKumarChauhan** [warmcat/libwebsockets#3195]
lws_service calls _lws_plat_service_tsi which is using a default timeout of 23 days for windows & unix both.
timeout_ms = 2000000000;
poll/wsapoll using this timeout.  
In case if there is no response from remote then wsapoll got stuck for this duration.

Is there any solution available for this for windows?
Is it ok to change the timeout value to 15 minutes?

**Comment by lws-team** [comment]
If nothing to do, no network activity, then it should do nothing.

If something to do, look at setting an lws_sul up to wait for when you wanted to do it.  Grep the examples and there's also a README about it.
