### ISSUE TITLE
How to attach a websocket to a specific path in the URL?

### ISSUE THREAD

**Issue by ribes96** [warmcat/libwebsockets#3198]
Hi
What is the proper way to install to a libwebsockets server a websocket protocol that will be accessible only from a specific path?
For example, a websocket upgrade request to the URL `http://myhost/websocket1` should be handled by one specific websocket protocol, and a websocket upgrade request to the URL `http://myhost/websocket2` should be handled by another websocket protocol.

This should be independent from the subprotocol chosen. Ideally it should be possible to have a subprotocol collision as long as the request path is different.

Is this possible using a single vhost?

**Comment by lws-team** [comment]
I think the url path might still be available at the ESTABLISHED callback.  In which case you can confirm it's what you expect in each protocol's ESTABLISHED, else immediately hang up.

**Comment by ribes96** [comment]
If this is THE way, I can certainly do it. I was just expecting some more straightforward way to direct a request to the appropriate websocket protocol without filtering and re-routing myself

**Comment by lws-team** [comment]
Life's So Haaaard!

**Comment by ribes96** [comment]
Thanks for the fast reply
