### ISSUE TITLE
libwebsocket partial write

### ISSUE THREAD

**Issue by edudev** [warmcat/libwebsockets#320]
I've searched for this issue a lot and couldn't find a straight answer.
I've found 2-year old messages from mailing lists and months old github issues, and I can't be sure what is currently valid.

The `test-fraggle.c` example shows how to handle partial reads and that is great.
But how should partial writes be handled?
I've read about a `no_buffer_all_partial_tx` flag, which I can't find in the current sources.
I've read that the TCP send buffer is set to the `rx_buffer_size` of the protocols struct, which is all good unless you send many frames before receiving a TCP ACK (which is a possibility).
I've read that libwebsocket will presumably handle partial writes internally if no extensions mess with it's buffer.

With all that said, I can't know how to use `libwebsocket_write` correctly.
If I attempt a write and it's only partially sent, can I repeat the write (on the next callback) with a new offset? Will this send 2 fragments with the `FIN` flag set accordingly only on the last one? Will this send only 1 fragment?
How will a partial write work with extensions?
Looking at `libwebsocket_wirte`'s source code, on success it will return `orig_len`. And this is fine.
But on a partial write it will return `n - (pre + post);`. Is this correct if the length was changed by an extension?

It would be nice if `test-fraggle.c` or one of the READMEs included an example of how to handle a partial write.
All I know for sure is that I can use `libwebsocket_write` with 1-byte lengths and `LWS_WRITE_NO_FIN`, and adding the `FIN` flag at the last byte. This approach will work, but it's... stupid...

**Comment by warmcat** [comment]
Ehhhh... look closer at test-fraggle.c

http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tree/test-server/test-fraggle.c#n150

**Comment by edudev** [comment]
test-fraggle.c uses `libwebsocket_write` twice. Both times it returns -1 in case of a partial write (lines 175 and 198).
```
			if (n < chunk) {
				lwsl_err("Partial write\n");
				return -1;
			}
```
and
```
			if (n < 4) {
				lwsl_err("Partial write\n");
				return -1;
			}
```

My question was regarding such situations. Returning a negative value (as it is done in test-fraggle.c) will drop the connection. I do not want this.
Is there really no way to handle a partial write? (By "handle" I do not mean dropping the connection.)
