### ISSUE TITLE
DOCUMENTATION: Documentation lacking re: using lws for http client from multiple threads

### ISSUE THREAD

**Issue by wreuven** [warmcat/libwebsockets#3200]
https://chatgpt.com/share/7297e314-b1a2-4681-9133-b3cac5b8a63b

The lack of documentation/ complete examples for this basic use case is reflected by ChatGPT in the above conversation. ChatGPT is in fact so confused from the documentation and the many examples it has seen on the Internet that it hallucinates that lws_ring or lws_sul must be re-entrant and even produces fake source code for these functions to prove it.

My understanding from the documentation is that ONLY the lws_cancel_service may be called from an external thread.

This raises a very basic question of **what is the best practice for using lws to implement http client calls from multiple threads.**

The documentation clearly pushes towards running a single context.
The documentation does show the use of lws_cancel_service as a mechanism to get the lws threads attention.
There does not seem to be any recommendation on how to communicate between the client thread and lws.
Using utilities such as  lws_ring (e.g. adding a mutex around it) conflicts with the documentation directive that this is not one of the functions that should be run outside of the lws service thread - but it seems that some projects do this anyway.

I guess that the "real" answer is that I should change my project to a single threaded architecture with a reactor pattern - but that is not always a practical option.

**Comment by lws-team** [comment]
Well, I can't help you with getting nonsense from ChatGPT.

Yes it's in the nature of a single threaded event loop it implies it's happening on a single thread.  It's a basic architectural  decision to do that or use threads.  If your stuff is infected with multiple threads, and that's where your head is at, you might find it simpler to just use some thread-based library instead.  If you want to get rid of threads, you can look at having that code also join the event loop thread.

If you need the two to work together though, yes, you can do it with lws_cancel_service() synchronizing events from other threads to the lws one.  The lws event loop thread will be woken shortly after lws_cancel_service() on any other thread, and have a chance to lock and decide what to do in response to what it finds from in-memory state shared between the lws thread and others.  Similarly for lws-side events, it can lock and add to a FIFO and indicate with a semaphore or whatever to a waiter on another thread.  There are minimal examples around this kind of flow (with -thread in the name).

**Comment by wreuven** [comment]
I want to use lws because I do believe in the single threaded architecture. But it will take time to change all my code base which is as you say "infected with threads". I don't think I am unique in this situation and I think it would be helpful to people in this situation to have clear guidance on best practices to handle this case without having to also bring in libcurl.

**Comment by lws-team** [comment]
There is a lot of docs and examples, eg

https://github.com/warmcat/libwebsockets/blob/main/READMEs/README.event-loops-intro.md
https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

There are more examples but there's nothing in it for me to sit there and make more examples.  If you have a specific question you can try asking it.

**Comment by wreuven** [comment]
Okay.

Other than lws_cancel_service , are there any other functions that are re-entrant and can be called safely from outside the lws thread?

Are there other functions that can safely be called outside the lws thread if wrapped by a mutex? e.g. lws_ring and lws_sul  functions.

**Comment by lws-team** [comment]
No, lws_cancel_service() is safe because it uses a pipe() in Linux to queue events from any thread.  That's your only way to get the attention of the lws thread from anywhere.  What you're asking to have happen is in a user-defined shared structure protected with a mutex.  Any number of threads can call lws_cancel_service after locking the shared structure.  In the other direction, you can have sync objects in the shared structure like semaphores and so on the other threads can wait on, and lws thread can signal.  And as far as it goes it is solid and safe.

You can't use other lws apis (except standalone ones like linked-lists) because the lws thread does not observe any locking when it uses structures they are associated with.  Eg, lws_sul is working with the lws_context list.

**Comment by wreuven** [comment]
Thanks.
