### ISSUE TITLE
Help need with _lws_plat_service_tsi

### ISSUE THREAD

**Issue by JianBoGo** [warmcat/libwebsockets#3201]
while using libwebsockets for windows, I noticed there is a problem while using _lws_plat_service_tsi as following:

int
_lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi)

When the parameter "timeout_ms" I passed in is greater than 0, the following judgment code will set the "timeout_ms" to 20000000000, and when the "timeout_ms" is turned to "timeout_us", it will be out of bounds, resulting in a negative "timeout_us", 

if (timeout_ms < 0)
		timeout_ms = 0;
	else
		/* force a default timeout of 23 days to timeout_ms*/
		timeout_ms = 20000000000;
	timeout_us = ((lws_usec_t)timeout_ms) * LWS_US_PER_MS;

When I use this function in the following scenario, i.e., the network is disconnected and then restored, the timeout_us becomes negative, and the following code falls into infinite waiting and cannot continue to execute, At this point, the external thread will stuck in an infinite loop

int d = WSAPoll((WSAPOLLFD *)&pt->fds[0], pt->fds_count, (int)(timeout_us / LWS_US_PER_MS));

So I'd like to ask, why "timeout_ms" set to 200000000000 when the value passed in is greater than 0, this code is in in line 160 of "windows-service.c"

**Comment by lws-team** [comment]
Isn't there an extra 0 in there?  The idea was set it to < (2^31) - 1 exactly to avoid problems with signed.  Does it help if you change the constant t 2 * 1000 * 1000 * 1000 ?

**Comment by JianBoGo** [comment]
Changing the constant t is helpful, but I would like to ask, does changing this constant t cause other problems?

**Comment by JianBoGo** [comment]
> Isn't there an extra 0 in there? The idea was set it to < (2^31) - 1 exactly to avoid problems with signed. Does it help if you change the constant t 2 * 1000 * 1000 * 1000 ?

Changing the constant t is helpful, but I would like to ask, does changing this constant t cause other problems?

**Comment by lws-team** [comment]
Looking at the code, it's already correct (2G) in there, actually.  It's only in your transcription of it in this issue that has 10 zeroes instead of 9.  So I guess I didn't understand the problem.

Can you see at which point the timeout becomes negative?

**Comment by JianBoGo** [comment]
> Looking at the code, it's already correct (2G) in there, actually. It's only in your transcription of it in this issue that has 10 zeroes instead of 9. So I guess I didn't understand the problem.
> 
> Can you see at which point the timeout becomes negative?

I'm so sorry that the previous code was copied wrong，timeout_us becomes negative in windows-service.c line 92，because when I use the function _lws_plat_service_tsi, the timeout_ms passed in is a positive value
`int
_lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi)
{
	struct lws_context_per_thread *pt;
	struct lws_pollfd *pfd;
	lws_usec_t timeout_us;
	struct lws *wsi;
	unsigned int i;
	int n;

	/* stay dead once we are dead */
	if (context == NULL)
		return 1;

	pt = &context->pt[tsi];

	if (!pt->service_tid_detected && context->vhost_list) {
		lws_fakewsi_def_plwsa(pt);

		lws_fakewsi_prep_plwsa_ctx(context);

		pt->service_tid = context->vhost_list->
			protocols[0].callback((struct lws *)plwsa,
					LWS_CALLBACK_GET_THREAD_ID,
						  NULL, NULL, 0);
		pt->service_tid_detected = 1;
	}

	if (timeout_ms < 0)
		timeout_ms = 0;
	else
		/* force a default timeout of 23 days */
		timeout_ms = 2000000000;
	timeout_us = ((lws_usec_t)timeout_ms) * LWS_US_PER_MS;`

**Comment by JianBoGo** [comment]
> Looking at the code, it's already correct (2G) in there, actually. It's only in your transcription of it in this issue that has 10 zeroes instead of 9. So I guess I didn't understand the problem.
> 
> Can you see at which point the timeout becomes negative?

59.	int
60.	_lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi)
61.	{
62.	 struct lws_context_per_thread *pt;
63.	 struct lws_pollfd *pfd;
64.	 lws_usec_t timeout_us;
65.	 struct lws *wsi;
66.	 unsigned int i;
67.	 int n;
68.	
69.	 /* stay dead once we are dead */
70.	 if (context == NULL)
71.	  return 1;
72.	
73.	 pt = &context->pt[tsi];
74.	
75.	 if (!pt->service_tid_detected && context->vhost_list) {
76.	  lws_fakewsi_def_plwsa(pt);
77.	
78.	  lws_fakewsi_prep_plwsa_ctx(context);
79.	
80.	  pt->service_tid = context->vhost_list->
81.	   protocols[0].callback((struct lws *)plwsa,
82.	     LWS_CALLBACK_GET_THREAD_ID,
83.	        NULL, NULL, 0);
84.	  pt->service_tid_detected = 1;
85.	 }
86.	
87.	 if (timeout_ms < 0)
88.	  timeout_ms = 0;
89.	 else
90.	  /* force a default timeout of 23 days */
91.	  timeout_ms = 2000000000;
92.	 timeout_us = ((lws_usec_t)timeout_ms) * LWS_US_PER_MS;
93.	
94.	 if (context->event_loop_ops->run_pt)
95.	  context->event_loop_ops->run_pt(context, tsi);
96.	
97.	 for (i = 0; i < pt->fds_count; ++i) {
98.	  pfd = &pt->fds[i];
99.	
100.	  if (!(pfd->events & LWS_POLLOUT))
101.	   continue;
102.	
103.	  wsi = wsi_from_fd(context, pfd->fd);
104.	  if (!wsi || wsi->listener)
105.	   continue;
106.	  if (wsi->sock_send_blocking)
107.	   continue;
108.	  pfd->revents = LWS_POLLOUT;
109.	  n = lws_service_fd(context, pfd);
110.	  if (n < 0)
111.	   return -1;
112.	
113.	  /*
114.	   * Force WSAWaitForMultipleEvents() to check events
115.	   * and then return immediately.
116.	   */
117.	  timeout_us = 0;
118.	
119.	  /* if something closed, retry this slot */
120.	  if (n)
121.	   i--;
122.	 }
123.	
124.	 /*
125.	  * service pending callbacks and get maximum wait time
126.	  */
127.	 {
128.	  lws_usec_t us;
129.	
130.	  lws_pt_lock(pt, __func__);
131.	  /* don't stay in poll wait longer than next hr timeout */
132.	  us = __lws_sul_service_ripe(pt->pt_sul_owner,
133.	         LWS_COUNT_PT_SUL_OWNERS,
134.	         lws_now_usecs());
135.	  if (us && us < timeout_us)
136.	   /*
137.	    * If something wants zero wait, that's OK, but if the next sul
138.	    * coming ripe is an interval less than our wait resolution,
139.	    * bump it to be the wait resolution.
140.	    */
141.	   timeout_us = us < context->us_wait_resolution ?
142.	     context->us_wait_resolution : us;
143.	
144.	  lws_pt_unlock(pt);
145.	 }
146.	
147.	 if (_lws_plat_service_forced_tsi(context, tsi))
148.	  timeout_us = 0;
149.	
150.	 /*
151.	  * is there anybody with pending stuff that needs service forcing?
152.	  */
153.	
154.	 if (!lws_service_adjust_timeout(context, 1, tsi))
155.	  timeout_us = 0;
156.	
157.	// lwsl_notice("%s: in %dms, count %d\n", __func__, (int)(timeout_us / 1000), pt->fds_count);
158.	// for (n = 0; n < (int)pt->fds_count; n++)
159.	//  lwsl_notice("%s: fd %d ev 0x%x POLLIN %d, POLLOUT %d\n", __func__, (int)pt->fds[n].fd, (int)pt->fds[n].events, POLLIN, POLLOUT);
160.	 int d = WSAPoll((WSAPOLLFD *)&pt->fds[0], pt->fds_count, (int)(timeout_us / LWS_US_PER_MS));
161.	 if (d < 0) {
162.	  lwsl_err("%s: WSAPoll failed: count %d, err %d: %d\n", __func__, pt->fds_count, d, WSAGetLastError());
163.	  return 0;
164.	 }
165.	// lwsl_notice("%s: out\n", __func__);
166.	
167.	#if defined(LWS_WITH_TLS)
168.	 if (pt->context->tls_ops &&
169.	     pt->context->tls_ops->fake_POLLIN_for_buffered)
170.	  pt->context->tls_ops->fake_POLLIN_for_buffered(pt);
171.	#endif
172.	
173.	 for (n = 0; n < (int)pt->fds_count; n++)
174.	  if (pt->fds[n].fd != LWS_SOCK_INVALID && pt->fds[n].revents) {
175.	//   lwsl_notice("%s: idx %d, revents 0x%x\n", __func__, n, pt->fds[n].revents);
176.	   lws_service_fd_tsi(context, &pt->fds[n], tsi);
177.	  }
178.	
179.	 return 0;
180.	}

**Comment by JianBoGo** [comment]
> Looking at the code, it's already correct (2G) in there, actually. It's only in your transcription of it in this issue that has 10 zeroes instead of 9. So I guess I didn't understand the problem.
> 
> Can you see at which point the timeout becomes negative?

I'm so sorry for the previous code was copied incorrectly, the timeout_us becomes negative in windows-service.c line 92 as following, because when using _lws_plat_service_tsi, the timeout_ms passed in is a positive value

87.    if (timeout_ms < 0)
88.	  timeout_ms = 0;
89.	 else
90.	  /* force a default timeout of 23 days */
91.	  timeout_ms = 2000000000;
92.	 timeout_us = ((lws_usec_t)timeout_ms) * LWS_US_PER_MS;
93.

**Comment by lws-team** [comment]
What is sizeof(timeout_us) and sizeof(timeout_ms) on your platform then?

**Comment by JianBoGo** [comment]
> What is sizeof(timeout_us) and sizeof(timeout_ms) on your platform then?

sizeof(timeout_us) is 8, and sizeof(timeout_ms) is 4
