### ISSUE TITLE
LWS context create API lws_create_context() is failing.

### ISSUE THREAD

**Issue by bpsinghtech** [warmcat/libwebsockets#3207]
Hi, 

1- I am seeing this error while creating lws context. 
This issue is coming when there is connectivity loss between client and server. 
Initially when network is fine, websocket connection is fine. If in between network connectivity is gone, client retries connection and below error is coming. 
Also if I kill process which is creating lws context and restart, it works perfectly fine.

2024-08-14 07:08:51 8092 AD.c:2336:call lws_create_context
2024-08-14 07:08:51:LWS: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
 
2024-08-14 07:08:51:LWS: Unable to load SSL Client certs file from ap-s1-s1-w6n6gslzbm.cloud.abc.com -- client ssl isn't going to work
 
2024-08-14 07:08:51:LWS: lws_tls_client_create_vhost_context: doing private key filepath
 
2024-08-14 07:08:51:LWS: use_PrivateKey_file ''
 
2024-08-14 07:08:51:LWS: lws_create_vhost: lws_context_init_client_ssl failed
 
2024-08-14 07:08:51:LWS: Failed to create default vhost

2- what is it trying to do when it throws this error ? It seems it is trying to load client certificate from server URL ap-s1-s1-w6n6gslzbm.cloud.abc.com, but client device certificate is present on device itself why is it trying from server URL ? 

2024-08-14 07:08:51:LWS: Unable to load SSL Client certs file from ap-s1-s1-w6n6gslzbm.cloud.abc.com -- client ssl isn't going to work

3- "local_protocol_name" in lws_client_connect_info is mandatory parameter, what will happen if we don't set this parameter ?

Thanks.

**Comment by bpsinghtech** [comment]
Thanks for quick reply. client info structure, you mean this lws_client_connect_info. yes, I am memsetting this. But we are getting error during lws_create_context(). I am also memsetting this lws_context_creation_info parameter before calling lws_create_context()

Here is the value we are setting:

struct lws_context_creation_info lws_info;

memset(&lws_info, 0, sizeof(lws_info));

    lws_info.port = CONTEXT_PORT_NO_LISTEN;

    lws_info.protocols = protocols;

    lws_info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

    lws_info.gid = -1;

    lws_info.uid = -1;

    if(context == NULL){

         context = lws_create_context(&lws_info);

     }

**Comment by lws-team** [comment]
It really sounds like you are defining lws_info on the stack.  The examples can do it, because they do it in main() and it never goes out of scope until the process exits.  But if you do it in a function, the pointers kept to it in the context are invalidated after you leave the function, basically what it points to changes depending on the call stack, it's not workable to do this.

Have the caller provide a pointer to an lws_info in memory that is a filescope static, malloc'd or otherwise won't go out of scope.

**Comment by bpsinghtech** [comment]
lws_info is global, sope is file level:

static struct lws_context_creation_info lws_info;

Then, it is initialized in main() as below

memset(&lws_info, 0, sizeof(lws_info));

lws_info.port = CONTEXT_PORT_NO_LISTEN;

lws_info.protocols = protocols;

lws_info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

lws_info.gid = -1;

lws_info.uid = -1;

if(context == NULL){
     context = lws_create_context(&lws_info);
}

After initialization, It is used in other functions for context creation.

**Comment by bpsinghtech** [comment]
Memsetting and re-initialize the lws_context_creation_info parameter lws_info before calling lws_create_context() during connection retry solved the problem. But, this should have not happened since lws_info is global parameter and initialized in the very beginning of main function.  I am still not why it worked after re-initialization.

**Comment by lws-team** [comment]
Maybe something else is trashing it, valgrind is a good friend to have for these kind of problems.
