### ISSUE TITLE
H default: iface port 0 DOESN'T EXIST error

### ISSUE THREAD

**Issue by DarkSov** [warmcat/libwebsockets#3214]
Trying to run minimal-ws-server [example](https://github.com/warmcat/libwebsockets/tree/main/minimal-examples-lowlevel/ws-server/minimal-ws-server) on embedded device, but getting  these errors. 

> [1970/01/01 00:20:55:2906] U: LWS minimal ws server | visit http://localhost:7681 (-s = use TLS / https)
> [1970/01/01 00:20:55:2931] E: VH default: iface port 0 DOESN'T EXIST
> [1970/01/01 00:20:55:2951] E: lws_plat_drop_app_privileges: cannot find name for gid 7681
> Segmentation fault

What may cause it?

**Comment by lws-team** [comment]
It really sounds like your build-time headers you are using are of a different version than the runtime lws library on your embedded device.  So your code's layout of the context info struct does not match what the library you have expects, you think you're telling it to listen on port 7681, the wrong layout you're using for the struct corresponds to telling it to switch to group 7681.

**Comment by DarkSov** [comment]
You are right, but after installing right version I started getting another error

>  E: ERROR opening socket

**Comment by lws-team** [comment]
What port are you listening on?  Is there another process already listening on that port?  sudo netstat -pltn show anything else listening on the port already?

Where did the kernel come from, does any other network operations work OK on it?

If you have strace on the device, you can try running the test app under strace and find out about the error on socket() or whatever is happening.

**Comment by DarkSov** [comment]
I'm using the port 7681 as in the example, nothing else is running on that port. It's an AD device, so I'm using their [kernel](https://github.com/analogdevicesinc/linux). I had a http server running without issues.

**Comment by lws-team** [comment]
netstat?  strace?

Maybe selinux enabled and not willing to open a socket on 7681?

It's not the kernel so much as the kernel config... eg. does it have network, sockets etc enabled.  If something else works then if it's the same kernel, dunno.

**Comment by DarkSov** [comment]
Here's strace output after libraries load

> mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f82000
> set_tls(0xb6f824d0, 0xb6f82bd0, 0xb6f89060, 0xb6f824d0, 0xb6f89060) = 0
> mprotect(0xb6d7b000, 8192, PROT_READ)   = 0
> mprotect(0xb6e69000, 4096, PROT_READ)   = 0
> mprotect(0xb6a62000, 4096, PROT_READ)   = 0
> mprotect(0xb6e1c000, 4096, PROT_READ)   = 0
> mprotect(0xb6c3c000, 4096, PROT_READ)   = 0
> mprotect(0xb6c29000, 4096, PROT_READ)   = 0
> mprotect(0xb6b6f000, 16384, PROT_READ)  = 0
> mprotect(0xb6b8d000, 4096, PROT_READ)   = 0
> mprotect(0xb6bab000, 4096, PROT_READ)   = 0
> mprotect(0xb6bca000, 4096, PROT_READ)   = 0
> mprotect(0xb6be1000, 4096, PROT_READ)   = 0
> mprotect(0xb6c06000, 4096, PROT_READ)   = 0
> mprotect(0xb6d9c000, 4096, PROT_READ)   = 0
> mprotect(0xb6e42000, 4096, PROT_READ)   = 0
> mprotect(0xb6f10000, 16384, PROT_READ)  = 0
> mprotect(0xb6f56000, 4096, PROT_READ)   = 0
> mprotect(0x20000, 4096, PROT_READ)      = 0
> mprotect(0xb6f88000, 4096, PROT_READ)   = 0
> set_tid_address(0xb6f82078)             = 24578
> set_robust_list(0xb6f82080, 12)         = 0
> rt_sigaction(SIGRTMIN, {0xb6e48854, [], SA_RESTORER|SA_SIGINFO, 0xb6c6a390}, NULL, 8) = 0
> rt_sigaction(SIGRT_1, {0xb6e48910, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0xb6c6a390}, NULL, 8) = 0
> rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
> ugetrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
> rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0xb6c6a380}, {SIG_DFL, [], 0}, 8) = 0
> brk(0)                                  = 0x22000
> brk(0x43000)                            = 0x43000
> clock_gettime(CLOCK_MONOTONIC, {11897, 192955182}) = 0
> ugetrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
> clock_gettime(CLOCK_MONOTONIC, {11897, 194948556}) = 0
> openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_LARGEFILE) = 3
> fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
> clock_gettime(CLOCK_MONOTONIC, {11897, 198707682}) = 0
> eventfd2(0, O_NONBLOCK|O_CLOEXEC)       = 4
> uname({sysname="Linux", nodename="user", ...}) = 0
> socket(PF_INET6, SOCK_STREAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
> ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
> gettimeofday({11897, 208258}, NULL)     = 0
> openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> write(2, "\33[31;1m[1970/01/01 03:18:17:2082"..., 62[1970/01/01 03:18:17:2082] E: ERROR opening socket
> ) = 62
> clock_gettime(CLOCK_MONOTONIC, {11897, 211697688}) = 0
> write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
> clock_gettime(CLOCK_MONOTONIC, {11897, 213872691}) = 0
> poll([{fd=4, events=POLLIN}], 1, 981)   = 1 ([{fd=4, revents=POLLIN}])
> read(4, "\1\0\0\0\0\0\0\0", 8)          = 8
>

**Comment by DarkSov** [comment]
Yep, it solve the problem
