### ISSUE TITLE
Obtaining SSL_R_NO_SHARED_CIPHER error after a connection attempt

### ISSUE THREAD

**Issue by AssemblyJohn** [warmcat/libwebsockets#3216]
Hello!

I am trying to obtain the SSL connection error ( I see it is queried here: https://github.com/warmcat/libwebsockets/blob/c980be7cf7a6c49b87ecf31c1a854b54982bdf3f/lib/tls/mbedtls/mbedtls-client.c#L264 ), specifically the SSL_R_NO_SHARED_CIPHER error (193). It would be ideal to be able to get any error on a connection fail. 

I've tried the following code with no success, the returned error is 0:

```
case LWS_CALLBACK_CLIENT_CONNECTION_ERROR: {
        std::cout << "CLIENT_CONNECTION_ERROR: " << (in ? reinterpret_cast<char*>(in) : "(null)");
        ERR_print_errors_fp(stderr);

        unsigned long err_code = ERR_get_error();
        if (err_code) {
            char err_buf[128];
            ERR_error_string_n(err_code, err_buf, sizeof(err_buf));
            std::cout << "OpenSSL error: " << err_buf;
        }      
}
```

Any ideas much appreciated!

**Comment by lws-team** [comment]
I think if you want more details in the CCE string, you will have to patch lws core pieces to report it in the string.  It's not like you're not getting a CCE just you want more details IIUI.

**Comment by AssemblyJohn** [comment]
As per: https://libwebsockets.org/lws-api-doc-main/html/group__usercb.html#ggad62860e19975ba4c4af401c3cdb6abf7ad8c6207b0c4e732f3d507f0fb79370e8
you can see that the error string is not always relevant to the problem, SSL errors a bit missing. 

I would like not necessarily a string but a way to extract the int error code. Is that possible without crating my own libwebsocket branch, or do I need to fork it?

**Comment by lws-team** [comment]
lws is FOSS, you can propose a patch.

lws is agnostic about the tls library, eg, mbedtls or openssl, and this information either needs unifying into an lws enum that can describe the situation without exposing tls library-specific data, or put into the string that already claims to describe the problem (again, it shouldn't refer to mbedtls-specific enums or whatever in the string, just text like "no shared cipher").

I guess if mbedtls has more verbose CCE string, that's not the end of the world and if someone else cares for openssl case, they can do the same.

**Comment by AssemblyJohn** [comment]
Understood. The agnostic enum seems to be a better idea for this purpose, will propose a patch.

**Comment by lws-team** [comment]
The PR is pushed on main

**Comment by AssemblyJohn** [comment]
Closed with: https://github.com/warmcat/libwebsockets/pull/3223
