### ISSUE TITLE
Changing the default page 

### ISSUE THREAD

**Issue by Somritag** [warmcat/libwebsockets#3218]
Hi Andy,

Am using lws_http_mount -> where origin is the filesystem with a default file name as a landing page using LWSMPRO_FILE as the callback.

My application requirement needs the default page to be changed on the fly. 

Is there a method where we can change the default file after we start the server.

Thanks,

**Comment by lws-team** [comment]
Look at the dynamic example

https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/http-server/minimal-http-server-dynamic/minimal-http-server-dynamic.c
