### ISSUE TITLE
i just notice there is a Valgrind-clean version, what version should i choose if i want to uses libwebsocket?

### ISSUE THREAD

**Issue by pppaulpeter** [warmcat/libwebsockets#3228]
Hi Andy

this is general question.
Does that mean all other versions including the newest version 4.3.3 is not Valgrind-clean? so we should choose Valgrind-clean version, correct?
thanks!

**Comment by lws-team** [comment]
4.3.3 is just a tag made from v4.3-stable.

The current stable (v4.3-stable) and main are all trying to be valgrind-clean.  Any tag just inherits how well they were doing at that time.

**Comment by pppaulpeter** [comment]
Hi,
Thank you so much for your prompt response!
