### ISSUE TITLE
if i send large data by lws_write() for example 10Mbytes, it will still return immeditely and will not block the reading opertation or other websocket connection?

### ISSUE THREAD

**Issue by pppaulpeter** [warmcat/libwebsockets#3241]
Hi Andy,

if all data need be sent in protocol callback function and it can't send large data by lws_write() , that means the lws user need buffer larger data themself (the best practice) and send small chunck of data everytime for not block other opertation. it seems the lws is not very friendly for resource-constrained devices since it need extra space when sending data. 

>               lws_write() never blocks, in lws the socket fds are all nonblocking.
> 
> It will add protocol-specific headers behind what you gave it, and try to send() it all.
> 
> The send() may return an error that nothing could be sent due to hangup on the connection etc, a sent length which was all of it, or a "partial send" length that the kernel side actually accepted.
> 
> (Notice that the way the send syscall works, the data you are trying to send is ALL copied into kernelspace before the send attempt.  So if you set this buffer huge, send() will become very cpu intensive and slow, even if it's not able to send any of the buffer once it tries.  So trying to send huge amounts each time is not the solution.)
> 
> If a partial send happens, the remainder is buffered on the heap by lws and it will not let your code see any further WRITEABLE callbacks for that connection until lws itself has iteratively drained this partial buffer itself, by swallowing WRITEABLEs, sending what it can, and asking for new ones.  So in this way lws will take responsibility for making it work transparently and concealing the partial via the heap, but obviously that is more expensive.
> 
> Partial sends are not good, but since POSIX only indicates an event on the socket that it can be written to, not by how much (TIOCOUTQ is only supposed to apply to ttys and isn't going to be very portable)  and this can change dynamically kernelside, the middle way is only try to send one or two ethernet frames' worth (~1400) a WRITEABLE.  If you got a WRITEABLE indication, that much is probably going to be accepted on Linux anyway.
> 
> You can try anothe SO_SNDBUF option to preset the output buffer size kernelside.  But I think no guarantee the kernel will listen to your request and again behaviour won't be portable.
> 
> Many video sending schemes use UDP packet writes on a timer instead.
> 
> _Originally posted by @lws-team in https://github.com/warmcat/libwebsockets/issues/2994#issuecomment-1788497228_

**Comment by lws-team** [comment]
This quoting of old issue text inside a new issue is really unhelpful.

The text you quoted answers your question already.

**Comment by pppaulpeter** [comment]
> This quoting of old issue text inside a new issue is really unhelpful.
> 
> The text you quoted answers your question already.

Hi Andy,

how could i know the data is acutally send out by lws_write since it is not block. if the data  is not send out i need resend it later. @lws-team

**Comment by lws-team** [comment]
You can only actually know this (with any implementation) if you receive an explicit notification that the remote peer received, processed at the user level, and understood that it received something.  Knowing that you sent something is not telling you the same thing at all, as that the peer received and processed it.  There are many ways for this to fail with network programming.

You might feel you said something to the old guy in the wheelchair, but did he hear you?  If he heard you, did he understand you?  If he understood you, did he process this information like he cared?  You can only know it if he says something back that is relevant to what you said.  Just feeling that you "said something" is useless by comparison.

So you have to take care of this in your protocol if you really want to be sure.

**Comment by pppaulpeter** [comment]
ok, clear, thanks! @lws-team
