### ISSUE TITLE
lws_write dont work

### ISSUE THREAD

**Issue by vadinabronin** [warmcat/libwebsockets#3242]
why can't I send a message to a websocket normally through your library, the lws _write function works like crap and I constantly have segmentation falut 

void WsApi::run() {
        while(true) {
            lws_service(context, 0);
        }
    }

    int WsApi::callback(struct lws *wsi, enum lws_callback_reasons reason,
                               void *user, void *in, size_t len) {
        
        switch (reason) {
            case LWS_CALLBACK_CLIENT_ESTABLISHED:
                std::cout << "WebSocket connection established." << std::endl;
                lws_callback_on_writable( wsi );
                break;

            case LWS_CALLBACK_CLIENT_RECEIVE:
                std::cout << (char*)in << std::endl;
                break;
            
            case LWS_CALLBACK_CLIENT_CLOSED:
                std::cout << "WebSocket connection closed." << std::endl;
                break;

            case LWS_CALLBACK_CLIENT_WRITEABLE:
    			break;
            
            default:
                break;
        }
        return 0;
    }

    void WsApi::write(const std::string& s) {
        std::cout << wsi << std::endl;
        int m = lws_write(wsi, (unsigned char*)s.c_str(), s.size(), LWS_WRITE_TEXT);
        lws_service(context, 0);
        std::cout << m << std::endl;
        if (m < 0) {
            lwsl_err("Error writing to socket\n");
            return;
        }
        lwsl_info("Sent: %s\n", s);
    }

double free or corruption (out)
WebSocket connection closed.
Aborted

why the hell is it done this way that nothing can be done properly

**Comment by vadinabronin** [comment]
the most user unfriendly library

**Comment by vadinabronin** [comment]
in your library you can only listen via sockets normally, the rest is not possible at all

**Comment by lws-team** [comment]
Did you try any of the examples?  I am guessing not.

Please feel free to share your wisdom with some other lucky library.
