### ISSUE TITLE
Is there an official component for ESP IDF 5.3.

### ISSUE THREAD

**Issue by PoltoS** [warmcat/libwebsockets#3246]
The existing component has old syntax and is not compatible with modern ESP IDF.

**Comment by lws-team** [comment]
I do have a diff that allows the example apps to work with the latest esp-idf... is that what you're talking about?

**Comment by PoltoS** [comment]
Yes, would be nice as the example we found online just does not compile. We are looking if we should use LWS on ESP too or rather use ESP standard components. Code unification is definitely better for us.

**Comment by lws-team** [comment]
ESP keep changing IDF for the past years, you're going to be disappointed if you expect anything about IDF that once compiled will still compile on any later version of it, unless people are spending time updating their works for latest IDF.

I can make the last lot of ESP32 code in minimal examples work on current IDF , but that is not the same as the original ESP32 stuff I did which was comprehensively broken by IDF changes.  You'll probably get an easier life if you try to make do with IDF pieces.

I plan to integrate the patches later when they're workable for what I am using them for.

**Comment by PoltoS** [comment]
Agree, it is pain to adopt to each of their major change. Ok, we will use their standard stuff and maintain two branches for ESP and desktop. Please share your examples once you have it working.

Thank for your support

**Comment by lws-team** [comment]
The changes do work as far as the stuff in `minimal-examples/embedded/lhp` and let probably all these (it's tested on one) build and work on latest IDF, for what they do, eg, with client wifi.  However pushing the changes means adapting and testing all the variants since they all broke on the same IDF churn so this might not happen quickly.

**Comment by PoltoS** [comment]
Thanks for the effort. We followed your suggestion and switched to their native WS server in ESP, keeping LWS only for "big" host system. So you can close this issue
