### ISSUE TITLE
LWS_CALLBACK_PROTOCOL_DESTROY immediately after startup

### ISSUE THREAD

**Issue by wburgers** [warmcat/libwebsockets#325]
Hi,

Since recent commit 05fc6bab0dbde1594e807db978b255126368d24e, LWS sends a LWS_CALLBACK_PROTOCOL_DESTROY immediately after startup.
It can still receive messages, but it won't write to the socket anymore.

Best regards,
Willem

**Comment by warmcat** [comment]
The test server doesn't show it on http or https... he can do the test normally.  Is there something specific about your test so I can try reproduce it?

**Comment by warmcat** [comment]
Does your callback maybe return nonzero for LWS_CALLBACK_RECEIVE_PONG?

**Comment by wburgers** [comment]
I have not specified the LWS_RECEIVE_CALLBACK_PONG, so it goes to my default behavior in the switch statement. That will return 0. So I have no clue why I get the protocol_destroy.
Only case where I return nonzero is when libwebsocket_write fails.

**Comment by warmcat** [comment]
I can't see how that patch would break it.  Do you mean that if you drop that patch, your symptom goes away?

**Comment by wburgers** [comment]
When I do a git checkout on 5400f47efe74df5f26304a12884c5af78b634f0b (commit before), I don't have the problem. When I checkout 05fc6bab0dbde1594e807db978b255126368d24e, I do have the problem.
I'll do a pull on master and revert this commit to see if that also works.

**Comment by wburgers** [comment]
Yup, only with that specific patch, I get a protocol_destroy.

**Comment by warmcat** [comment]
Ha... okay I'll try to catch it sending it.

Test server works normally with that patch tho.

**Comment by wburgers** [comment]
Thanks Andy,

My code can be found [here] (https://github.com/wburgers/Open-Zwave-Socket-Server/blob/Test/Server/Main.cpp#L650) if needed.

I may be doing something stupid I'm not seeing

**Comment by warmcat** [comment]
Basically the only code in lws to send the CONTEXT_DESTROY is in libwebsocket_context_destroy().  And the only place that calls that from the library, is if context create fails (returns NULL).

So if you're not sending it (doubt it!) and you don't see your warning about context create fail in your code, you must be exiting your main loop and calling libwebsocket_context_destroy() there to produce it.  Can you maybe instrument that and see if that logic hangs together?

**Comment by wburgers** [comment]
Ok, that was weird.
After I tried to add some debug messaging to my code, the problem was gone.
Maybe I didn't clean my project properly, even though I recompiled?
Anyway, thanks very much for helping me out!
Enjoy the rest of you holiday and sorry for bothering you!

Best regards,
Willem

**Comment by warmcat** [comment]
No worries, from that I could guess your problem... you must memset info to 0 if you allocated from the stack.  Otherwise uninitialized members hold undefined data, not zero.

**Comment by wburgers** [comment]
Ha.. Ok.
That has been in the test server since feb 2013.
Weird that I never noticed that.
Fixed in my code now.

Thanks very much!
Keep up the great work!
