### ISSUE TITLE
 The address and path in the lws_client_connect_info structure are too long and truncated

### ISSUE THREAD

**Issue by hxj122** [warmcat/libwebsockets#3253]
Hi@Team
I pulled the latest code, compiled it, and tested the client. If the length of address and path in the structure lws_client_connect_info exceeds 1024, the client will not initiate a connection to the server, and no errors are seen in the print log. How can this problem be solved?

**Comment by lws-team** [comment]
There are limits on the sizes of headers and such, the main one is set in the context creation info struct member `max_http_header_data`.  They default if left to zero to reasonable sizes for the platform, but you can control the limit, eg, set to 8K if you expect this kind of header block size.

If not that, you need to look closer at which limit you are hitting.
