### ISSUE TITLE
The address and path in the lws_client_connect_info structure are too long and truncated

### ISSUE THREAD

**Issue by hxj122** [warmcat/libwebsockets#3254]
Hi Andy,
    struct lws_context *context = NULL;
    struct lws_client_connect_info ccinfo;
    struct lws_context_creation_info info;
    memset(&info, 0, sizeof(info));
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.protocols = protocols;
    info.gid = -1;
    info.uid = -1;
    info.client_ssl_cert_filepath = NULL;
    info.client_ssl_private_key_filepath = NULL;
    info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    context = lws_create_context(&info);
    memset(&ccinfo, 0, sizeof(ccinfo));
    ccinfo.context = context;
    ccinfo.port = 443;
    ccinfo.path = path;
    ccinfo.address = address;
    ccinfo.host = address;
    ccinfo.origin = address;
    ccinfo.ssl_connection = 1;
    ccinfo.protocol = "wss";
    ccinfo.pwsi=ws_client_connect_via_info(&ccinfo);
    while (recog_channel->interrupted)
    {
        lws_service(context, 50);
    }
    
When the path is too long, the client will truncate it when initiating a request. Could you please help me figure out how to modify this?

**Comment by lws-team** [comment]
What part of this reply could not be understood?

> There are limits on the sizes of headers and such, the main one is set in the context creation info struct member max_http_header_data. They default if left to zero to reasonable sizes for the platform, but you can control the limit, eg, set to 8K if you expect this kind of header block size.

> If not that, you need to look closer at which limit you are hitting.

**Comment by hxj122** [comment]
I only set max_http_header_data and it didn't work. After setting pt_serv_buf_size and max_http_header_data at the same time, it worked. Thank you very much for your reply. Thank you for your trouble.

**Comment by lws-team** [comment]
That's good to hear.
