### ISSUE TITLE
option to compile without libcap

### ISSUE THREAD

**Issue by johnhe4** [warmcat/libwebsockets#3259]
Would be nice to have a cmake option to compile without libcap since I don't need it for my use case.

I statically build libwebsockets into my dynamic lib. Nothing fancy in terms of websocket use cases, mostly text-based graphql subscriptions. Everything compiles and links fine for my dynamic lib, but when loading my lib into an app I get undefined references to libcap calls.

I prefer not to require consuming apps to add `-lcap` to their linker flags if they don't need to.

I created #3260

**Comment by lws-team** [comment]
The PR should be pushed on main now.
