### ISSUE TITLE
Please add a bit more info about LWS_WRITE_TEXT, LWS_WRITE_CONTINUATION and LWS_WRITE_NO_FIN

### ISSUE THREAD

**Issue by PoltoS** [warmcat/libwebsockets#3263]
Based on the doc and examples I was trying to understand how to properly use `LWS_WRITE_TEXT`, `LWS_WRITE_CONTINUATION` and `LWS_WRITE_NO_FIN`

I've noticed your [comment](https://github.com/warmcat/libwebsockets/issues/1055#issuecomment-336314258) stating:
> notice how the single message (it turns up in the JS as one seamless message) is cut into ws fragments using `LWS_WRITE_TEXT`, `LWS_WRITE_CONTINUATION` and `LWS_WRITE_NO_FIN` according to if it's the first fragment of the message, the middle fragments or the last.

Please confirm that to send a big multi-chunk **text** message I need to set the following flags:
- first fragment: `LWS_WRITE_TEXT | LWS_WRITE_NO_FIN`
- middle fragments: `LWS_WRITE_CONTINUATION | LWS_WRITE_NO_FIN`
- last fragment: `LWS_WRITE_CONTINUATION`

For **binary** we change only the first packet to `LWS_WRITE_BINARY | LWS_WRITE_NO_FIN`

For **HTTP**:
- first fragment: `LWS_WRITE_HTTP`
- middle fragments: `LWS_WRITE_HTTP`
- last fragment: `LWS_WRITE_HTTP_FINAL`

-----------------------------------------------------------------------------

And for consistency, for single-frame message:

For **text**:
- `LWS_WRITE_TEXT`

For **binary**:
- `LWS_WRITE_BINARY`

For **HTTP**:
- `LWS_WRITE_HTTP_FINAL`

-----------------------------------------------------------------------------

Can we add clarity to the doc in https://libwebsockets.org/lws-api-doc-v2.4-stable/html/group__sending-data.html#ga98b099cf8c1c7e38ad78501f270e193d (I know, you love examples, but it would save a lot of time!) Or even add defines `LWS_WRITE_TEXT_SINGLE_FRAME, LWS_WRITE_TEXT_FISRT_FRAME, LWS_WRITE_TEXT_MIDDLE_FRAME, LWS_WRITE_TEXT_LAST_FRAME` ?

**Comment by lws-team** [comment]
There's a helper in lws for ws writing:

```

/**
 * lws_write_ws_flags() - Helper for multi-frame ws message flags
 *
 * \param initial: the lws_write flag to use for the start fragment, eg,
 *		   LWS_WRITE_TEXT
 * \param is_start: nonzero if this is the first fragment of the message
 * \param is_end: nonzero if this is the last fragment of the message
 *
 * Returns the correct LWS_WRITE_ flag to use for each fragment of a message
 * in turn.
 */
static LWS_INLINE int
lws_write_ws_flags(int initial, int is_start, int is_end)
{
        int r;

        if (is_start)
                r = initial;
        else
                r = LWS_WRITE_CONTINUATION;

        if (!is_end)
                r |= LWS_WRITE_NO_FIN;

        return r;
}
```

... which manages this sequencing logic for you.  You give the BINARY or TEXT type initially and then two bools to say if it is the first or last fragment.

For HTTP it's as you say.

The docs on v2.4 are from 2017 FWIW.

**Comment by PoltoS** [comment]
Missed this function, but made the same in my code ;)

It was a bit confusing that examples like minimal-examples-lowlevel/ws-server/minimal-ws-server-echo/protocol_lws_minimal_server_echo.c doesn't use LWS_WRITE_CONTINUATION and NO_FIN flags. Yes, you don't need for a simple echo, but when you start with such examples, you don't have any hint that you should change it. So, using this lws_write_ws_flags function would make it more clear.

Anyway, thanks for you answer.
