### ISSUE TITLE
about ws_ping_pong_interval

### ISSUE THREAD

**Issue by dayDPTR** [warmcat/libwebsockets#3269]
Hi experts,

I hope you are doing well.

I have an application using this library version 2.4.2 currently, now need to upgrade 4.2.2, it seems that _ws_ping_pong_interval_ field was removed from _struct lws_context_creation_info_ at the [commit](https://github.com/warmcat/libwebsockets/commit/280c81278dcb88c074aa19cbf8de809e366a9ece#diff-ad31623078059c02523c410754ce3d92da37ae563953cb0bae92bb282ea4e075L450), are there examples such as test-apps guiding us to adapt applications to the library. I read the [README](https://github.com/warmcat/libwebsockets/blob/main/READMEs/README.lws_retry.md) carefully, but i cannot totally understand it.

could you help or give any suggestions ?

Thanks
Ryan

**Comment by lws-team** [comment]
This was upgraded to use `lws_retry_bo_t` just before the patch that removed the old way.  See, eg, b95ff02f53e61ffab311504157b0b4bed2910d8e and examples that use `lws_retry_bo_t`.
