### ISSUE TITLE
max connections to libwebsockets on windows limited to 64

### ISSUE THREAD

**Issue by bhaskar-priya** [warmcat/libwebsockets#327]
The library quits working after accepting about 62 incoming websocket connections.

The error can be traced to WSAWaitForMultipleEvents failing because the maximum number of events it can wait on is 64 (https://msdn.microsoft.com/en-us/library/windows/desktop/ms742219%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by warmcat** [comment]
Yeah... windows is crap.

I don't have any windows machines for many years, all the windows pieces are contributed.

If someone cares enough to send a patch using an alternate windows api (I seem to recall it being discussed) I'll be happy to take it.
