### ISSUE TITLE
lws_now_usecs() doesn't work as documented on Linux

### ISSUE THREAD

**Issue by stevensonkd** [warmcat/libwebsockets#3270]
`include/libwebsockets/lws-misc.h` states:

```c
/**
 * lws_now_usecs(): return useconds since 1970-1-1
 */
```

But if compiled with `LWS_HAVE_CLOCK_GETTIME`, it uses `CLOCK_MONOTONIC`.

From `lib/plat/unix/unix-misc.c`:

```c
lws_now_usecs(void)
{
#if defined(LWS_HAVE_CLOCK_GETTIME)
	struct timespec ts;

	if (clock_gettime(CLOCK_MONOTONIC, &ts))
		return 0;

	return (((lws_usec_t)ts.tv_sec) * LWS_US_PER_SEC) +
			((lws_usec_t)ts.tv_nsec / LWS_NS_PER_US);
#else
```

On Linux, `CLOCK_MONOTONIC` returns time since boot, not time since 1970-1-1.

**Comment by lws-team** [comment]
Yeah.  It needs to use MONOTONIC to work properly, and was changed to use that where possible.

**Comment by stevensonkd** [comment]
Thanks. I figured as much, but then the documentation should be fixed.
