### ISSUE TITLE
Connections past the H2SET_MAX_CONCURRENT_STREAMS limit are dropped, is there any waiting list mechanism available?

### ISSUE THREAD

**Issue by BhanuPrakash-P** [warmcat/libwebsockets#3271]
Hi Andy,

I have setup a http2 server with H2SET_MAX_CONCURRENT_STREAMS as 8. When Client sends more than 8 requests, server is closing all the streams.
<img width="473" alt="image" src="https://github.com/user-attachments/assets/788d9046-36ac-40c5-af9c-507313904644">

Do we have any mechanism currently to maintain a waitlist for the concurrent streams after crossing the limit?
If not, this needs to be implemented in library or in the application?

Thanks.

**Comment by BhanuPrakash-P** [comment]
Thanks @lws-team for the quick response. I agree with you on resource limitation.

Let’s assume I have a server setup with HTML, CSS, JS, and image files under a mount path. The default landing page is index.html, which includes some JS files and image files.

When the client (Chrome or Firefox browser) tries to connect to the server(https://localhost:7681), it receives the MAX_CONCURRENT_STREAMS(8) in HEADERS and somehow does not honor it, sending more than 8 requests(either for images or JS files).

In resource-limited environments, sending a GOAWAY is completely understandable.
Suppose there is no limitation on resources, can over-the-limits streams/requests be buffered?

**Comment by lws-team** [comment]
If there's no problem serving more streams simultaneously resource-wise, you can control what the server sends out for CONCURRENT_STREAMS.  If it's freertos (a guess because it seems to be 8 for you by default), eg

```
diff --git a/lib/plat/freertos/freertos-init.c b/lib/plat/freertos/freertos-init.c
index 49f5b5d9..15f0916d 100644
--- a/lib/plat/freertos/freertos-init.c
+++ b/lib/plat/freertos/freertos-init.c
@@ -60,7 +60,7 @@ const struct http2_settings lws_h2_defaults_esp32 = { {
        1,
        /* H2SET_HEADER_TABLE_SIZE */                    512,
        /* H2SET_ENABLE_PUSH */                            0,
-       /* H2SET_MAX_CONCURRENT_STREAMS */                 8,
+       /* H2SET_MAX_CONCURRENT_STREAMS */                 16,
        /* H2SET_INITIAL_WINDOW_SIZE */                    0,
        /* H2SET_MAX_FRAME_SIZE */                     16384,
        /* H2SET_MAX_HEADER_LIST_SIZE */                 512,
```

**Comment by BhanuPrakash-P** [comment]
> If there's no problem serving more streams simultaneously resource-wise, you can control what the server sends out for CONCURRENT_STREAMS. If it's freertos (a guess because it seems to be 8 for you by default), eg
> 
> ```
> diff --git a/lib/plat/freertos/freertos-init.c b/lib/plat/freertos/freertos-init.c
> index 49f5b5d9..15f0916d 100644
> --- a/lib/plat/freertos/freertos-init.c
> +++ b/lib/plat/freertos/freertos-init.c
> @@ -60,7 +60,7 @@ const struct http2_settings lws_h2_defaults_esp32 = { {
>         1,
>         /* H2SET_HEADER_TABLE_SIZE */                    512,
>         /* H2SET_ENABLE_PUSH */                            0,
> -       /* H2SET_MAX_CONCURRENT_STREAMS */                 8,
> +       /* H2SET_MAX_CONCURRENT_STREAMS */                 16,
>         /* H2SET_INITIAL_WINDOW_SIZE */                    0,
>         /* H2SET_MAX_FRAME_SIZE */                     16384,
>         /* H2SET_MAX_HEADER_LIST_SIZE */                 512,
> ```

Thank you, Andy, for your response.

Please share your inputs on the following.
1. What behaviour could be if H2_ERR_ENHANCE_YOUR_CALM or H2_ERR_REFUSED_STREAM is sent to the client in a GOAWAY packet as shown in the following snippet?
```c
			/* no more children allowed by parent */
			if (wsi->mux.child_count + 1 >
			    wsi->h2.h2n->our_set.s[H2SET_MAX_CONCURRENT_STREAMS]) {
				lws_h2_goaway(wsi, H2_ERR_ENHANCE_YOUR_CALM ,
				"Another stream not allowed");
				return 1;
			}
``` 

2. MAX_CONCURRENT_STREAMS limit is per client connection. similarly we have info.ip_limit_ah, to track peer IPs and monitor how many connections and ah resources they are trying to use at one time. So, assuming I have set the H2SET_MAX_CONCURRENT_STREAMS as 16, is it possible to set ip_limit_ah as 8 and have the remaining requests upto 16 buffered?

**Comment by lws-team** [comment]
If the client doesn't take MAX_CONCURRENT_STREAMS we sent seriously, and exceeds it, lws will close the connection to the client.  You're welcome to try changing it to failing just the new stream and keep the rest of the connection up.

This idea of buffering transactions at the server is just something you have imagined, it is not a thing.  As I said the issue is the amount of resources on the server, that one client can lay claim to.  So the server is hardcore about restricting what the client can get away with on the server.  In order to "buffer" streams, we have to store the headers for the stream on the server, and lws supports very restricted platforms like ESP32 where there may not be enough memory lying around for that.

**Comment by BhanuPrakash-P** [comment]
> If the client doesn't take MAX_CONCURRENT_STREAMS we sent seriously, and exceeds it, lws will close the connection to the client. You're welcome to try changing it to failing just the new stream and keep the rest of the connection up.
> 
> This idea of buffering transactions at the server is just something you have imagined, it is not a thing. As I said the issue is the amount of resources on the server, that one client can lay claim to. So the server is hardcore about restricting what the client can get away with on the server. In order to "buffer" streams, we have to store the headers for the stream on the server, and lws supports very restricted platforms like ESP32 where there may not be enough memory lying around for that.

Thank you for the clarification.
