### ISSUE TITLE
Query on MQTT

### ISSUE THREAD

**Issue by Venkyv555** [warmcat/libwebsockets#3272]
@lws-team ,
Does libwebsockets currently support MQTT over WebSockets?
Are there any future plans/Roadmap to add support for MQTT version 5.0?

**Comment by lws-team** [comment]
Unless someone wants to pay for it. it's unlikely there'll be any more MQTT work.

**Comment by Dhruv1107** [comment]
@lws-team Is there any minimal-example which we can modify to implement MQTT over Websockets?

**Comment by lws-team** [comment]
No, there's no example because it's not directly supported.

You can presumably use lws ws support to pass the right messages and translate to and from mqtt things, for server and client.  But that's unrelated to anything around the direct MQTT apis in lws.
