### ISSUE TITLE
Lifetime of http client connection? 

### ISSUE THREAD

**Issue by samsnori** [warmcat/libwebsockets#3277]
When I create a http-server and connect to it via a client, what callback reasons are used to manage its lifetime?

What I'm trying to figure out is how to detect when a `lws*` has been allocated/created and when it's going to be destroyed. I've seen `LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED` and `LWS_CALLBACK_WSI_DESTROY`, however the `LWS_CALLBACK_WSI_DESTROY` is also triggered when I destroy my context itself. 

Thanks!

**Comment by lws-team** [comment]
Naturally at context destroy time, any extant wsi in the context are destroyed first.  Wsi may exist for a variety of purposes.  So there is no reason to be surprised you see WSI_DESTROY coming at context destroy time.

**Comment by samsnori** [comment]
Thanks, so using `LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED` and `LWS_CALLBACK_WSI_DESTROY` are not the reasons I need to check when I want to now the creation and destruction of http-client connections. My question still holds and it would be great if you could share some info on this? 

And curious, the `LWS_CALLBACK_WSI_DESTROY` that I receive, even when no client connects, is that the server socket? Is there a way to determine what this `lws*` is?

**Comment by samsnori** [comment]
Thanks, this was exactly what I needed to know, you even have a nice readme for this: https://github.com/warmcat/libwebsockets/blob/v4.3-stable/READMEs/README.lifecycle.md
