### ISSUE TITLE
 High CPU Usage with Continuous Streaming in libwebsockets on Embedded Linux Device

### ISSUE THREAD

**Issue by pppaulpeter** [warmcat/libwebsockets#3280]
Hi Andy,

I am using libwebsockets to create a WebSocket server on an embedded Linux device. The server streams real-time audio and video data to clients upon request. Since the libwebsockets APIs are non-blocking, I handle data transmission as follows:

I use lws_write() within the LWS_CALLBACK_SERVER_WRITEABLE callback to send data to the client.
I repeatedly call lws_callback_on_writable() to ensure that LWS_CALLBACK_SERVER_WRITEABLE is triggered continuously for ongoing data transmission.
I've noticed that this approach leads to increased CPU usage (for example, CPU occupancy exceeding 1%), which is significant for an embedded device.

My questions are:

Is it normal for continuous data streaming using libwebsockets in this manner to result in higher CPU usage?
Is there a more efficient way to implement real-time streaming with libwebsockets to minimize CPU occupancy?
Are there best practices for handling continuous data transmission in libwebsockets that could help reduce CPU load?
Any guidance or suggestions would be greatly appreciated. @lws-team

**Comment by lws-team** [comment]
What exactly are you expecting?  Yes if you spam data cpu will go above 1%...

Normal humans use UDP for video, not tcp /ws.

**Comment by pppaulpeter** [comment]
> What exactly are you expecting? Yes if you spam data cpu will go above 1%...
> 
> Normal humans use UDP for video, not tcp /ws.

thanks for the quick reply. The cpu is high is not just because the video data but the non-block api. if i sleep 5ms when there is no video data(since the real-time video data still has 40ms interval if the frame rate is 25 fps) then call lws_callback_on_writable(), it will help to decrease the cpu usage.  i could sleep more but since i also need send other data at the same time, sleep more will block other data sending. @lws-team

**Comment by lws-team** [comment]
Please don't blame async waits for your code, which seems to just spin.  sleep-ing for any amount of time is a sure sign you don't know what you're doing.

If there is something to do, do it or schedule it.  If nothing to do, sleep in the event loop wait.

Just a gentle reminder I don't have to spend any time at all on your problems.

**Comment by pppaulpeter** [comment]
> Please don't blame async waits for your code, which seems to just spin. sleep-ing for any amount of time is a sure sign you don't know what you're doing.
> 
> If there is something to do, do it or schedule it. If nothing to do, sleep in the event loop wait.
> 
> Just a gentle reminder I don't have to spend any time at all on your problems.

Hi Andy,

yes, it just spin. but i have to spin and can not schedule it since the data could be ready in any next second :(. wish you have a nice weekend!

**Comment by pppaulpeter** [comment]
> Please don't blame async waits for your code, which seems to just spin. sleep-ing for any amount of time is a sure sign you don't know what you're doing.
> 
> If there is something to do, do it or schedule it. If nothing to do, sleep in the event loop wait.
> 
> Just a gentle reminder I don't have to spend any time at all on your problems.
Hi Andy,


it seems this function occupy most of the cpu time, this is the callgrind_annotate --show-percs=yes callgrind.out.23260 output
_Profile data file 'callgrind.out.23260' (creator: callgrind-3.15.0)
'''150,994,442 (73.61%)  ???:sanity_assert_no_sockfd_traces [/usr/local/lib/libwebsockets.so.19]'''_
this api is called in lws_service(context, 0);  correct? should i increase the timeout_ms value to decrease the cpu usage?

**Comment by lws-team** [comment]
Build with -DCMAKE_BUILD_TYPE=RELEASE to cause this kind of debug helper to not be built.

**Comment by pppaulpeter** [comment]
> DCMAKE_BUILD_TYPE

Hi Andy,

is it the same as stip the so library?

> Build with -DCMAKE_BUILD_TYPE=RELEASE to cause this kind of debug helper to not be built.

Hi Andy,

thanks a lot！
