### ISSUE TITLE
how to set SO_REUSEADDR Socket Option in libwebsockets?

### ISSUE THREAD

**Issue by pppaulpeter** [warmcat/libwebsockets#3284]
Hi Andy,

i got this error when i recreated the vhost by lws_create_vhost with the same port different tls certification in lws version 4.3
_E: [null wsi]: lws_socket_bind: ERROR on binding fd 266 to port 7683 (-1 98)
E: [vh|4|websockets||7683]: lws_create_vhost: init server failed
E: Failed to recreate WebSocket vhost_

should i wait some time to call lws_create_vhost or could i set SO_REUSEADDR Socket Option somehow? thanks! @lws-team

**Comment by lws-team** [comment]
How is that going to help?  If you open two different listening sockets on the same port, what is the OS supposed to do so that stuff for socket a gets seen by socket a and not b?

Lws can handle multiple vhosts listening on the same socket at the same port.  You must ensure the .name of each vhost is different, and matches what would be seen at the host: header.  Eg, `warmcat.com` and `libwebsockets.org` are vhosts that both exist at :443.  routing to which vhost is handled after seeing which host the connecting client actually wanted.  Then the right certs are passed back and it is hooked up to the correct logical vhost.

**Comment by pppaulpeter** [comment]
> How is that going to help? If you open two different listening sockets on the same port, what is the OS supposed to do so that stuff for socket a gets seen by socket a and not b?
> 
> Lws can handle multiple vhosts listening on the same socket at the same port. You must ensure the .name of each vhost is different, and matches what would be seen at the host: header. Eg, `warmcat.com` and `libwebsockets.org` are vhosts that both exist at :443. routing to which vhost is handled after seeing which host the connecting client actually wanted. Then the right certs are passed back and it is hooked up to the correct logical vhost.

Hi Andy,

sorry for misunderstanding, i have destroy the last vhost before  recreated the vhost by lws_create_vhost with the same port. Sometime i got this error even i have slept 5 seconds before recreated the vhost(destroy the vhost--------sleep 5 seconds---------create vhost with the same port).

**Comment by pppaulpeter** [comment]
> > How is that going to help? If you open two different listening sockets on the same port, what is the OS supposed to do so that stuff for socket a gets seen by socket a and not b?
> > Lws can handle multiple vhosts listening on the same socket at the same port. You must ensure the .name of each vhost is different, and matches what would be seen at the host: header. Eg, `warmcat.com` and `libwebsockets.org` are vhosts that both exist at :443. routing to which vhost is handled after seeing which host the connecting client actually wanted. Then the right certs are passed back and it is hooked up to the correct logical vhost.
> 
> Hi Andy,
> 
> sorry for misunderstanding, i have destroy the last vhost before recreated the vhost by lws_create_vhost with the same port. Sometime i got this error even i have slept 5 seconds before recreated the vhost(destroy the vhost--------sleep 5 seconds---------create vhost with the same port). @lws-team

Hi Andy,

may i know how long do i need sleep to avoid this error?(destroy the vhost--------sleep 8 seconds---------create vhost with the same port). now i sleep 8s, but sometime i still got this error. the waiting time is too long for starting the new service. @lws-team 
_[2024/12/06 14:16:04:9037] E: [null wsi]: lws_socket_bind: ERROR on binding fd 9 to port 8012 (EADDRINUSE)
[2024/12/06 14:16:04:9038] E: [vh|9|default||8012]: lws_create_vhost: init server failed
[2024/12/06 14:16:04:9039] E: Failed to recreate WebSocket over TLS vhost_
https://github.com/warmcat/libwebsockets/issues/963

**Comment by lws-team** [comment]
> how long do I need to sleep

Why are you asking me, this is a 'feature' of your crappy OS.

**Comment by pppaulpeter** [comment]
> > how long do I need to sleep
> 
> Why are you asking me, this is a 'feature' of your crappy OS.
Hi Andy,

are you sure? i test it in my ubuntu system not '''crappy OS'''.

**Comment by lws-team** [comment]
Yes, I am sure it is not my problem.

**Comment by pppaulpeter** [comment]
> Yes, I am sure it is not my problem.

Hi Andy,

could you give me a hint? you guys have discussed this issue before, right? 
'''If I destroy a vhost, and it is the last vhost on the port, the listening port will be closed, otherwise only vhost is removed.''' this is the old issue:
https://github.com/warmcat/libwebsockets/issues/963
thanks!
