### ISSUE TITLE
LWS_WITH_EXTERNAL_POLL Redefinition Warning When Building libwebsockets with CMake

### ISSUE THREAD

**Issue by suyash191** [warmcat/libwebsockets#3285]
When building libwebsockets version 4.3.3 from source with LWS_WITH_EXTERNAL_POLL enabled via CMake on a Debian 11.7 slim container, the build fails due to a redefinition warning for the macro LWS_WITH_EXTERNAL_POLL. The warning is treated as an error, causing the build to terminate.

Steps to Reproduce:
1. Set up the environment:
  a. Debian 11.7 slim container
  b. OpenSSL v3.1.6 installed from source (/usr/local/ssl).
  c. Clone libwebsockets source code (v4.3.3):

2. Configure the build with LWS_WITH_EXTERNAL_POLL:
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DLWS_WITH_SSL=ON \
    -DLWS_WITH_EXTERNAL_POLL=ON \
    -DOPENSSL_ROOT_DIR="/usr/local/ssl" \
    -DOPENSSL_LIBRARIES="/usr/local/ssl/lib" ..

Observed Behavior: The following error occurs:
- In file included from /libwebsockets-4.3.3/include/libwebsockets.h:42,
                 from /libwebsockets-4.3.3/test-apps/test-server.c:21:
/libwebsockets-4.3.3/build/lws_config.h:158: error: "LWS_WITH_EXTERNAL_POLL" redefined [-Werror]
  158 | #define LWS_WITH_EXTERNAL_POLL
      | 
<command-line>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
make[2]: *** [test-apps/CMakeFiles/test-server-extpoll.dir/build.make:82: test-apps/CMakeFiles/test-server-extpoll.dir/test-server.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1473: test-apps/CMakeFiles/test-server-extpoll.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Expected Behavior: The build should complete successfully with LWS_WITH_EXTERNAL_POLL enabled.

**Comment by lws-team** [comment]
If you build a tag, you are always and forever going to get whatever bugs exist on that tag.  It's never going to get fixed on the tag, because that tag is the unfixed version.

The fix on main for it is this

```
diff --git a/test-apps/CMakeLists.txt b/test-apps/CMakeLists.txt
index e0c097f1..d1c58ab0 100644
--- a/test-apps/CMakeLists.txt
+++ b/test-apps/CMakeLists.txt
@@ -163,7 +163,6 @@ if ((LWS_ROLE_H1 OR LWS_ROLE_H2))
                        set_property(
                                TARGET test-server-extpoll
                                PROPERTY COMPILE_DEFINITIONS 
-                                       LWS_WITH_EXTERNAL_POLL
                                        INSTALL_DATADIR="${CMAKE_INSTALL_PREFIX}/share"
                                )
 
```

You should be able to solve it by applying it on top of v4.3.3
