### ISSUE TITLE
lws-minimal-ss-server-hello_world doesn't work as expected

### ISSUE THREAD

**Issue by Oozlum** [warmcat/libwebsockets#3298]
According to the README, hello_world should respond to a browser with HTML + JS which opens a web socket and reports a changing value.  When I connect to https://localhost:7861 all I receive is this minimal content:
```html
<html>
  <head></head>
  <body>Hello World: 7794961046</body>
</html>
```

**Comment by lws-team** [comment]
Yes the README is wrong (belongs to a different example), this pure SS example sets up an h2 server that just uses http to GET the result you see.  I pushed a patch on main to correct the README.
