### ISSUE TITLE
client application crashes in libwebsocket_context_destroy on flaky network tests

### ISSUE THREAD

**Issue by vgahlan-cpi** [warmcat/libwebsockets#331]
On flaky network testing, client application crash is observed in libwebsocket_context_destroy(). On further debugging, it seems crash is happening because of wsi double free. 

When lws_change_pollfd() fails in libwebsocket_client_connect_2(), oom: hanlding free up wsi but does't perform wsi_sock cleanup. On connection failure detection application tries to destroy libwebsocket context and invokes  libwebsocket_context_destroy(). libwebsocket_context_destroy() find wsi valid and its socket entry in fdpolltable and tries to wsi again.

Here is logs flow when crash happens:
Here is exact trace flow of the crash:

libwebsocket_client_connect_2
libwebsocket_client_connect_2: address mywebsocket.com
closed  >> This logs comes when lws_change_pollfd() fails
libwebsocket_context_destroy
close: just_kill_connection
remove_wsi_socket_from_fds: wsi=0x7a0d8, sock=9, fds pos=1

Here is the fix that works for me. Please review:

```
From 300e50b2fe6a033a109d5f1f15208cb8490363e4 Mon Sep 17 00:00:00 2001
From: vgahlan-cpi <vikas.gahlan@chargepoint.com>
Date: Sat, 17 Oct 2015 22:40:23 -0700
Subject: [PATCH] fdpolllist cleanup requires if wsi socket exists in fdtable
 to avoid double free in libwebsocket_context_destroy

---
 lib/client-handshake.c | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/lib/client-handshake.c b/lib/client-handshake.c
index 7293a41..d7d72e6 100644
--- a/lib/client-handshake.c
+++ b/lib/client-handshake.c
@@ -291,9 +291,12 @@ struct libwebsocket *libwebsocket_client_connect_2(
        return wsi;

 oom4:
-       lws_free(wsi->u.hdr.ah);
-       lws_free(wsi);
-       return NULL;
+        /*In case wsi added successfully in fd polllist, clean-up requires for fdtable and session data properly using libwebsocket_close_and_free_session().*/
+        if(wsi->position_in_fds_table < 0  || wsi->sock < 0 ){
+                lws_free(wsi->u.hdr.ah);
+                lws_free(wsi);
+                return NULL;
+        }

 failed:
        libwebsocket_close_and_free_session(context, wsi,
--
1.8.3.1

```

**Comment by JoakimSoderberg** [comment]
Please create a pull request instead, this is not the way to submit patches.

**Comment by lws-team** [comment]
A different version of this got pushed so closing (I just realized after recent changes I wasn't getting notification mails...)
