### ISSUE TITLE
Windows binaries as part of release

### ISSUE THREAD

**Issue by ralight** [warmcat/libwebsockets#333]
Hello,

It would be very convenient if Windows binaries were provided alongside the source at release time. It should be possible to automate this for tagged commits using appveyor.

**Comment by lws-team** [comment]
Joakim is in a better position to decide that than me, since he has a windows box.  I think licensewise it's okay even if the binary library has its dependent libs in there since zlib and openssl don't require source distribution, and the build manifest will show where they came from.

And if we're going to do it around now is good since we will make a tag soon.

**Comment by lws-team** [comment]
Well, it's almost true for openssl... if it's composed into the library we will also have to abide by this

 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.

https://www.openssl.org/source/license.html

But it sounds doable.

**Comment by JoakimSoderberg** [comment]
Yea I think this is a good idea. And make appveyor build the release when there's a new tag in the repo.

However, I dislike how the current windows installer has been created. CMake through CPack itself has support for creating NSIS packages. This support actually cares about what features are turned on when you decide what goes into the package (it uses the `install(..)` commands in `CMakeLists.txt` to determine that).

So if we're going to do this I think the solution should scrap the broken (and disabled on appveyor) build of the installer using CMake/CPack. This then allows you to generate debian packages, rpm and so on with the same configuration. Some relevant URLs:

* https://cmake.org/Wiki/CMake:Packaging_With_CPack
* https://cmake.org/Wiki/CMake:CPackPackageGenerators#NSIS
* https://cmake.org/cmake/help/v3.0/module/CPackNSIS.html

Some other points:

* I guess simply adding the license file for openssl in the package should be ok.
* Any file going into the installer should be placed there using a `install(...)`  call using CMake. Windows specific stuff inside of `if (WIN32)` of course.

@ralight  Is this something you're up for creating a patch for? :)

**Comment by lws-team** [comment]
* I guess simply adding the license file for openssl in the package should be ok.

Probably some smallprint on libwebsockets.org site too, it's also no problem.

Leveraging cmake sounds like a very good way if we have the wherewithal to do it.

**Comment by ralight** [comment]
We could get away without distributing openssl as long as we link to where it can be downloaded I suppose, if that helps.

You can read into who I'd prefer to make the patch by the fact that I submitted an issue not a pull request :) I'll try and have a look at some point, but I don't feel it would be before the next release.

**Comment by lws-team** [comment]
I think maybe this should be closed and reopened if something happening towards it.

I can't solve it because windows.  If it gets solved, someone else will do it on their own timescale unrelated to this project I think.
