### ISSUE TITLE
!!! libwebsocket_client_connect failed when using libwebsockets together with gstreamer

### ISSUE THREAD

**Issue by cppbitman** [warmcat/libwebsockets#334]
Hi, recently I have been assigned a work, in which libwebsockets will be used with gstreamer   together on Windows7 platform. Here is a link of gstreamer: http://gstreamer.freedesktop.org/

I encounter a problem that libwebsocket_client_connect fails in demo project "test-client"  when I insert one line code before the line creating context, i.e. 
gst_init(NULL,NULL);
context = libwebsocket_create_context(&info);
and do noting else. gst_init is a gstreamer API which initializes the gstreamer library and should be called always firstly when delevoping gstreamer application.

I find that libwebsocket_client_connect calls libwebsocket_client_connect2 to initiate a tcp connection and could not establish a connection successfully until libwebsocket_service loops for 2-3 times in the original project. 
When I insert gst_init before libwebsocket_create_context, I find that tcp connection could not be established and LWS_ERRNO equals to 10022L in the following snippet  excerpted from the funciton libwebsocket_client_connect2.  ( WSAEINVAL==10022L, windows sockets error code ) 

if (connect(wsi->sock, v, n) == -1 || LWS_ERRNO == LWS_EISCONN) {

		if (LWS_ERRNO == LWS_EALREADY || LWS_ERRNO == LWS_EINPROGRESS
		                              || LWS_ERRNO == LWS_EWOULDBLOCK
									  /*|| LWS_ERRNO == 10022L*/) {
			lwsl_client("nonblocking connect retry\n");

			/*
			 * must do specifically a POLLOUT poll to hear
			 * about the connect completion
			 */
			if (lws_change_pollfd(wsi, 0, LWS_POLLOUT))
				goto oom4;

			return wsi;
		}

		if (LWS_ERRNO != LWS_EISCONN) {
			lwsl_debug("Connect failed errno=%d\n", LWS_ERRNO);
			fprintf(stderr, "Connect failed errno=%d\n", LWS_ERRNO);
			goto failed;
		}
	}

But when I add " LWS_ERRNO == 10022L" into upper code snippet, tcp connectin can be established successfully, and also test_client can work well.
I don't know if this is the corret way, or there is any other way like doing some configure when creating context to solve my problem?

Can anyone help me???

**Comment by lws-team** [comment]
Update to current lws.

It already has

#ifdef _WIN32
			|| LWS_ERRNO == WSAEINVAL
#endif

there.
