### ISSUE TITLE
SSL websockets fail when allowing non-SSL on same port

### ISSUE THREAD

**Issue by github-user-7** [warmcat/libwebsockets#338]
lib/ssl.c
lws_server_socket_service_ssl()
case LWS_CONNMODE_SSL_ACK_PENDING:
if (context->allow_non_ssl_on_ssl_port) {

Looks like the code is checking LWS_ERRNO when it should not be.  This is causing it to loop on SSL_ERROR_WANT_READ when there is actually plenty of data to be read (n returned by recv is >0).  This is a problem if LWS_ERRNO is already set to LWS_EAGAIN or LWS_EWOULDBLOCK before calling recv().  It should only check LWS_ERRNO if recv returned n < 0.

Additionally, if n=0 it is also looping on SSL_ERROR_WANT_READ.  When recv() returns 0, that means the connection is lost (per its manpage) so it should actually fail out in that case.

**Comment by lws-team** [comment]
Thanks... yes it's wrong as you say in both cases.  And it's pretty glaringly wrong :-/

I pushed cc64fb5 which should fix those.

**Comment by github-user-7** [comment]
Looks great, thanks Andy.
