### ISSUE TITLE
libwebsockets doesn't respond with close message after getting close message from client

### ISSUE THREAD

**Issue by github-user-7** [warmcat/libwebsockets#340]
With 1.4 libwebsockets release, as soon as the web browser sends a WebSocket Connection Close message to the libwebsockets server, libwebsockets would send back a WebSocket Connection Close and the socket would get closed right away.

With 1.5 libwebsockets (everything else the same) it doesn't do that anymore.  After 20 seconds, the browser apparently times it out and closes the socket anyway.

Is there something new in 1.5 I'm supposed to be doing to get the connection closed in a timely fashion?

![close-ok-1 4](https://cloud.githubusercontent.com/assets/15474343/11013633/3a98115e-84ca-11e5-8deb-3eb845063539.png)
![close-issue-1 5](https://cloud.githubusercontent.com/assets/15474343/11013634/4020f60e-84ca-11e5-8721-67a65f3539f3.png)

**Comment by lws-team** [comment]
I just pushed a patch which should solve it.

**Comment by lws-team** [comment]
Well it's solved here, if it's still broken for anyone else please reopen.
