### ISSUE TITLE
Build without SSL 

### ISSUE THREAD

**Issue by hannorein** [warmcat/libwebsockets#342]
It would be nice to be able to build libwebsockets without SSL. Am I correct that this is currently not possible?

**Comment by lws-team** [comment]
You can disable it with an CMake option, but recently you needed to disable a second option

cmake .. -DLWS_WITH_SSL=OFF -DLWS_WITHOUT_BUILTIN_SHA1=OFF

I just pushed a patch that should remove the need for giving the second option.

**Comment by vishweshgm** [comment]
![image](https://user-images.githubusercontent.com/5349458/127444483-cb58a4a7-f19a-4963-8928-462c5851fcc8.png)

Hello, 
Is this option changed in latest release?

**Comment by Lassebq** [comment]
```
[cmake] CMake Error at libwebsockets/minimal-examples-lowlevel/secure-streams/minimal-secure-streams-blob/CMakeLists.txt:46 (add_test):
[cmake]   Error evaluating generator expression:
[cmake] 
[cmake]     $<TARGET_FILE:lws-minimal-secure-streams>
[cmake] 
[cmake]   No target "lws-minimal-secure-streams"
```
Doesn't seem to work

**Comment by lws-team** [comment]
This is fixed on main.
