### ISSUE TITLE
Outdated documentation links on main page

### ISSUE THREAD

**Issue by mulander** [warmcat/libwebsockets#344]
Hi,

The [main page](http://libwebsockets.org) links to documentation pages that have been reworked into markdown format. Links such as:

 http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tree/README.test-apps

should be turned into:

 http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tree/README.test-apps.md

**Comment by lws-team** [comment]
Thanks it's updated.
