### ISSUE TITLE
No documentation for LWS_CALLBACK_LOCK_POLL/LWS_CALLBACK_UNLOCK_POLL

### ISSUE THREAD

**Issue by hotcookie** [warmcat/libwebsockets#346]
I try use libwebsockets in multithreaded app.
As i understand i can call libwebsocket_service function in a different threads.
In this callbacks I should lock/unlock mutex.
All right?

**Comment by lws-team** [comment]
Libwebsockets is not threadsafe, it's designed to run with service in a single thread.

However under some circumstances it's 'threadsafe enough'.

Those callbacks are designed to allow user code to support locking the fd list, when the fd list is shared with some other thread in a single poll() wait.  This is for when, eg, lws is being grafted on some other multithreaded app that has his own event loop already, and lws needs to observe his existing locking.

For lws running in his own thread, the main thing to take care is that only lws can do writes when the writeable callback comes.  If the other thread generates data to write, he should put it in a fifo or holding buffer and the WRITEABLE callback will read it later.  The only interface from other thread contexts should be libwebsocket_callback_on_writable() to signal the wsi there's something for him to do.

**Comment by hotcookie** [comment]
i.e I can create thread for a long time operations and call libwebsocket_callback_on_writable from this thread?
What will happen if client disconnected while this thread execute? I need lock mutex from LWS_CALLBACK_LOCK_POLL in this thread?

**Comment by lws-team** [comment]
Yes.

Monitoring which wsi are born and die is done in your user code monitoring CLOSE and ESTABLISHED callbacks.  When you record a change of wsi state there, and when you will use the wsi from your other thread,you must do your own locking.

**Comment by hotcookie** [comment]
I also can't change data into user(per_session_data__echo) structure in other thread, because it can be changed by main thread?
Locking only fd list, user structure avaible to write with locked mutex?

**Comment by hotcookie** [comment]
I also can't change data into user(per_session_data__echo) structure in other thread, because it can be changed by main thread, right? Waiting on mutex in main thread in this case get not profit, because it equivalent synchronized(singlethreaded) execution?

**Comment by lws-team** [comment]
It's 'user data'.  Which user code can touch what, under which locking condition is wholly defined and controlled by your code alone

What works well is a ringbuffer type thing with a head and tail that only one thread may write, but both may read.  It's simple and robust without locking.  But you can do what you like with 'user data'.

All you need is protect references to wsi (including wsi->user_data) with the same lock that protects CLOSE handling where you remove the wsi from your list of live wsis.

**Comment by hotcookie** [comment]
Okay, thanks.
I think would be nice add multithreaded example.

**Comment by lws-team** [comment]
This patch

https://github.com/warmcat/libwebsockets/commit/b7fed3532ae27f8c1afa58720ec04b8474fdd71a

adds a test server version that uses pthread to do the dumb increment, and shows how to do the locking so the wsi list is always safe.

**Comment by hotcookie** [comment]
LWS_CALLBACK_LOCK_POLL/LWS_CALLBACK_UNLOCK_POLL calls on every iteration of main cycle from lws_change_pollfd function.

**Comment by hotcookie** [comment]
I get not LWS_CALLBACK_LOCK_POLL/LWS_CALLBACK_UNLOCK_POLL when client connected to my server. Only get it for socket actions (FD_READ, FD_WRITE, FD_CLOSE).

**Comment by hotcookie** [comment]
Also i get two pair LWS_CALLBACK_LOCK_POLL/LWS_CALLBACK_UNLOCK_POLL callbacks on client disconnect.

**Comment by lws-team** [comment]
If you look at

https://github.com/warmcat/libwebsockets/commit/5a3b1d307b0446beb58e2664d8b9ad549bbf7b46

which I added with the pthreads example patch, you can use len in the callback to determine if the locking callback is covering insert / remove from the live wsi / fd list or not... len == 1 if it is.  If len ==0 it's covering pollfd change (POLLIN/POLLOUT) and you can ignore it for multithreaded locking purposes, as the pthreads example does.

**Comment by lws-team** [comment]
Oh you deleted some comments I guess you found the answer yourself.

Two sets of calls to these locking callbacks doesn't necessarily represent a problem.  You should only be using them for locking (if len==1), there is a oneshot CLOSE callback you can use for onetime destroy processing.
