### ISSUE TITLE
Service callback handler not executed on bad connectivity

### ISSUE THREAD

**Issue by datmorrison** [warmcat/libwebsockets#347]
I'm having trouble getting connections to close when the client-side connection is interrupted (e.g. disabling network card / wireless). In these situations websockets' doesn't seem to see the connection as being shutdown, and never produces a LWS_CALLBACK_CLOSED event. I'm guessing this is because it acts as a silent disconnect and TCP never considers it closed. I tried using the libwebsocket keep alive timeouts, but it appears my system doesn't support it (CLOSED is never produced for the socket after the timeout period).

The perplexing part is that it also appears that calls to libwebsocket_service never result in my callback handler being executed for the bad socket, even though service() is called at 10Hz. As such, I can never return a -1 to close the connection on the server side. This is a problem because the LWS_CALLBACK_CLOSED event is responsible for doing a lot of the required cleanup of my program. 

I can live without the TCP keepalive working, but I absolutely need the ability to close a client connection from the server. Why would the socket not get serviced if the client connectivity is interrupted? Is anyone else experiencing this? Any suggestions?

Thanks in advance!

**Comment by lws-team** [comment]
What platform is this, and are you using latest lws from git?

**Comment by datmorrison** [comment]
Sorry, that would have been useful information:
CentOS 6.5
lws-1.3-chrome37-firefox30

**Comment by lws-team** [comment]
The CentOS bit is good news since I'm a Fedora guy, but the lws is old... please try current HEAD

**Comment by datmorrison** [comment]
Thanks, I'll give that a try, but it may be a while before I can integrate due to our release schedule. I'll let you know more information when I get it going.

**Comment by lws-team** [comment]
You're welcome... since there's nothing I can do I'll close this, please reopen it if still problems on latest stuff.
