### ISSUE TITLE
Add "#ifdef CMAKE_BUILD" back to  lib/libwebsockets.h?

### ISSUE THREAD

**Issue by stevenylai** [warmcat/libwebsockets#351]
I sent this to trac before but it didn't seem to get through. 

#ifdef CMAKE_BUILD was removed a while ago from this commit (Always include lws_config.h since now we have only CMake build):
https://github.com/warmcat/libwebsockets/commit/41802c7a98a1ff559fba9e7b1165fd9a8e35e99d#diff-1a03ea41c91111289d2f50246637983f

My use case is as follows: my own project is built with autotools and autotools generates config.h which defines a lot of macros that are the same as in lws_config.h. As a result, whenever I include both libwebsockets.h and config.h inside my project, gcc will pop up a lot of warnings about already defined macros.

It's not a big deal - the build will still pass but would you consider my use case for using libwebsockets in a project which is not using CMake?

**Comment by lws-team** [comment]
What does that practically mean, revert the commit?  AFICS if the old code the commit replaced is still enough it won't have any bad side effects to revert it.

**Comment by stevenylai** [comment]
OK. My bad. My project was still pointing an older version. This issue has already been addressed in commit:
https://github.com/warmcat/libwebsockets/commit/7a474b4e2d9279f28161c76c6ee3a426ffe78ac0#diff-af3b638bc2a3e6c650974192a53c7291

Closing the issue
