### ISSUE TITLE
Namespace collision of "assert" macro

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#356]
[libwebsockets.h](https://github.com/warmcat/libwebsockets/blob/bb085dab0403c185a0a18266c056ce0afebfbf7f/lib/libwebsockets.h) includes in [line 164](https://github.com/warmcat/libwebsockets/blob/bb085dab0403c185a0a18266c056ce0afebfbf7f/lib/libwebsockets.h#L164) the `assert.h` header.

I don't see any usage of the assert() macro in the file itself. More badly, it collides with my own definition of assert() :-1: 

If assert() is used internally by the lib, it should be only included in a private header or the source code itself.

**Comment by JoakimSoderberg** [comment]
Uhm `assert.h` is a C standard header, if you're using such generic names that are used by the C standard, I rather think that is the problem in a more general sense. The common way of doing your own assert macros is to give them some kind of prefix.

But sure if no `assert.h` related things are never used in the public header it makes more sense to move it to the private include instead.

**Comment by stv0g** [comment]
I agree.

I scanned the libwebsockets source code for uses of `assert()`.
It used a few times in the implementation (`*.c`) files. But never in the headers.
So, it should be save to move this include to the implementation itself.

**Comment by lws-team** [comment]
Joakim is right, if your code ever needs to move to other platforms like windows, their compilers take a very maximilist view of reserved names and it'll bite you using them locally.

But your point is also right, it's not needed in the public header.  We might break some user code that uses assert inheriting its definition from our header, but that's very small and obvious what to do from the error.  So I pushed a patch simply moving the include as suggested.
