### ISSUE TITLE
Confusing naming of library functions: libwebsockets_*, lws_*, lwsl_*

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#357]
Is there a reasoning behind those different naming conventions?
I searched the documentation but didn't found an explanation.

It would be nice to add a sentence to the documentation which explains it :-)
Personally, I get easily upset when spotting inconsistencies like those which I don't understand xD

**Comment by lws-team** [comment]
lwsl_ = libwebsockets_log, that has meaning and is consistent.

Generally the earliest apis spelled out the full name libwebsockets_.  Newer apis use lws_.  And this is only an issue with api function names.

We could provide preprocessor defines to normalize the naming in a compatible way I guess, let me have a think about it.

**Comment by stv0g** [comment]
Thanks for the explanation :-)

Maybe alias symbols could solve this as well: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html (see the alias function attribute).

Breaking the API is always something I would avoid.
But new versions of the library could provided aliases for the old (libwebsockets_) naming scheme.

**Comment by lws-team** [comment]
Yeah... but lws is used on many platforms.  Although I personally only use it on gcc, we cannot solve a generic, platform-agnostic thing like this by throwing gcc-isms on it.  That won't even pass the CI build autotests.

**Comment by lws-team** [comment]
These two patches should rationalize the naming considerably.

Code using the previous naming should be unaffected since there are compatibility defines in the public header.

But the public api names in the header, test apps and internal code are all changed to lws_ prefix.

I'll close this since it works here and passes the autobuilders but if they make trouble feel free to reopen.

**Comment by stv0g** [comment]
Thanks Andy :-) I really appreciate that!

I don't want to be to pedantic but the structures have inconsistent type names too:
```
struct ls_context_creation_info
```
vs
```
struct libwebsocket_context
````

If I'm correct, your patch will break API compatibility? So the next lws release should use a different SONAME?

**Comment by lws-team** [comment]
One thing at a time...

I'm still going with the patches related to this, the binary abi thing will also become transparent.

**Comment by lws-team** [comment]
OK current HEAD should be everything lws_, but neither break build nor abi compatibility (the latter if you use the new cmake define described in changelog)

**Comment by stv0g** [comment]
Thanks again :-) I have a much better feeling using lws now :D
I wil test it later.
