### ISSUE TITLE
Support IPv6 only network

### ISSUE THREAD

**Issue by asuuma** [warmcat/libwebsockets#364]
Hi, I'm now testing libwebsockets with IPv6 only network and I found that there is an issue with opening socket with IPv4-mapped address. 
Since IPv6 only host can not use IPv4-mapped address to connect, it should use only real IPv6 address to connect. `getaddrinfo` will return addresses with undefined order, so the first address may not be IPv6 address and [current implementation](https://github.com/warmcat/libwebsockets/blob/master/lib/client-handshake.c#L77-L97) is only using first address to connect, so it may fail to connect on IPv6 only host because of IPv4-mapped address.
I think client should test all addresses until socket is opened successfully, but I don't know much about IPv6 socket programming. What do you think with this issue?

I'm sorry for my poor English.

**Comment by asuuma** [comment]
I found more better way to support both IPv6-only and dual stack network.
I will give a PR later.

**Comment by asuuma** [comment]
I created #365

**Comment by lws-team** [comment]
Thanks
