### ISSUE TITLE
win libwebsockets_serve_http_file

### ISSUE THREAD

**Issue by Libco** [warmcat/libwebsockets#367]
in lws-plat-win.c in function _lws_plat_file_open is this line 

if (flags & _O_RDONLY)

but _O_RDONLY is 0x0000, so bitwise AND is going to return false when called with the read flag and then jump to error - shouldnt it just be == ?

**Comment by lws-team** [comment]
You're right... I just assumed they were flags all this time but actually, the low 3 bits are a mutually exclusive mode even in posix.  I pushed a fix thanks.
