### ISSUE TITLE
Parsing of escaped URL does not work as expected

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#369]
Escaped '?' characters in the query values cause libwebsockets to loose the leading part of a query string.

For example the following URL:
```
/cgi-bin/settings.js?UPDATE_SETTINGS=1&Root_Channels_1_Channel_name_http_post=%3F&Root_Channels_1_Channel_location_http_post=%3F
```
got parsed to:
```
/
```
as reported by ```lws_hdr_copy( wsi, ..., ..., WSI_TOKEN_HTTP_URI_ARGS )```

**Comment by lws-team** [comment]
Yeah... I can reproduce it.

**Comment by lws-team** [comment]
I pushed a fix and added the problem to attack.sh
