### ISSUE TITLE
Build fails on Windows using CMake and Visual Studio 2013

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#373]
```libwebsockets.h``` uses C99 keyword 'inline' in declaration of a few new functions, which is not supported by VS2013 for C-sources.

**Comment by lws-team** [comment]
Can you advise how the build tools you are using can let us identify they are in use so we can dumb down the sources?

**Comment by lws-team** [comment]
... or better yet send a patch?

**Comment by emptyVoid** [comment]
Well, actually the issue affects the public header only, since CMake script detects support of 'inline' keyword and adds the following to ```lws_config_private.h```:
```
/* Define if the inline keyword doesn't exist. */
#define inline __inline
```
You could possibly introduce a macro to the public header and use it instead of 'inline', something like this:
```
#if defined(_MSC_VER)
#define LWS_INLINE __inline
#else
#define LWS_INLINE inline
#endif
```

PS: Sorry, I'm not familiar with this patch/pull-request thing.

**Comment by lws-team** [comment]
I moved the CMake handling for inline from the private to the public lws_config.h... that's also included by the private lws header so this should cover everything now.

**Comment by emptyVoid** [comment]
I think the resolution is a bit problematic: since it's a public header defining an unsupported keyword could lead to unexpected side effects for the user's code, especially for C++ code that includes ```libwebsockets.h```.

**Comment by lws-team** [comment]
I see your point.  I nuked that patch and pushed one introducing  LWS_INLINE.

I considered just making these APIs exported from the library and avoid inline.  But they really want to be inline and I don't see microsoft not supporting even a 17 year old standard for C should make everybody's code worse.

**Comment by JoakimSoderberg** [comment]
https://github.com/akheron/jansson/blob/master/CMakeLists.txt#L291

This is how you can do actual system introspection exactly which `inline` keyword works and not using CMake

Then in the `config.h`: https://github.com/akheron/jansson/blob/master/cmake/jansson_config.h.cmake#L44

**Comment by lws-team** [comment]
We seem to have that stuff in the CMakeLists already Joakim.

We weren't doing the second bit in a way it had its own namespace was the problem.

I think the current fix is OK I will close this because new ones keep coming ^^
