### ISSUE TITLE
ABI incompatibility on Windows platform

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#374]
```lws_pollfd``` structure's layout and size is dependent on project settings and Windows SDK version.

When compiling ```libwebsockets``` the compiler uses definition specified in the following preprocessor block:
```
#if defined(_WIN32) && (_WIN32_WINNT < 0x0600)
typedef SOCKET lws_sockfd_type;
...
```
whereas while compiling my code it sees this one:
```
#else
typedef int lws_sockfd_type;
...
```

And all hell breaks loose: the library sends 8+4+4 byte structure to ```LWS_CALLBACK_ADD_POLL_FD```, where it is interpreted as 4+4+4.

**Comment by lws-team** [comment]
Can you give us a clue what magic preprocessor string your build environment would like to see there?

**Comment by emptyVoid** [comment]
AFAIU ```_WIN32_WINNT``` and other version macros are used to check what WinAPI subset is available at compile time, and if explicitly set (before including WinAPI headers) to constrain Windows SDK so that resulting binary would work on the specified or newer versions of Windows.

I'm not sure what is the purpose of the version check in this particular case, though I would remove ```(_WIN32_WINNT < 0x0600)```, since on Windows it's perfectly legal to link binaries built against different versions of Windows SDK.

**Comment by emptyVoid** [comment]
I think the version check is due to ```WSAPoll``` which was introduced with Windows Vista (0x0600). Moreover removing the check results in compilation error, since ```WSAPoll``` is already declared in WinSock headers, and the second declaration in ```libwebsockets.h``` has to be removed for compilation to succeed.

And I wouldn't recommend using ```WSAPoll``` (see http://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/).

**Comment by lws-team** [comment]
Could you possibly, if not send a patch, then cut and paste what your working code looks like for that check now?

**Comment by emptyVoid** [comment]
I removed version check and function declaration in the following block (```libwebsockets.h```):
```
#if defined(_WIN32) && (_WIN32_WINNT < 0x0600)
typedef SOCKET lws_sockfd_type;
typedef HANDLE lws_filefd_type;
#define lws_sockfd_valid(sfd) (!!sfd)
struct lws_pollfd {
	lws_sockfd_type fd;
	SHORT events;
	SHORT revents;
};
WINSOCK_API_LINKAGE int WSAAPI WSAPoll(struct lws_pollfd fdArray[], ULONG fds, INT timeout);
#else
```

Here's how it looks on my side:
```
#if defined(_WIN32)
typedef SOCKET lws_sockfd_type;
typedef HANDLE lws_filefd_type;
#define lws_sockfd_valid(sfd) (!!sfd)
struct lws_pollfd {
	lws_sockfd_type fd;
	SHORT events;
	SHORT revents;
};
#else
```

Compiles and works.

**Comment by netrounds-joakim** [comment]
Uhm it works by simply removing the `WSAPoll` line? Doesnt' it make more sense to only add `#if _WIN32_WINNT < 0x0600)` around `WSAPoll`?

**Comment by emptyVoid** [comment]
Does it really makes sense to even declare ```WSAPoll``` with ```_WIN32_WINNT``` set to ```0x0501``` (Windows XP)?
The application linked against ```WSAPoll``` wouldn't start on Windows XP.

**Comment by lws-team** [comment]
At least one thing unrelated to WSAPoll has crept into that stanza anyway, lws_filefd_type.  He's needed for any windows version.

Easiest to follow the cut and paste that's known to work I think, since the only way I can test it is Appveyor and that never minded the original test.

I pushed it, reopen if still problems coming.

**Comment by lws-team** [comment]
Hum... Appveyor don't like it now lol

"C:\projects\libwebsockets\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\libwebsockets\build\test-server-extpoll.vcxproj" (default target) (10) ->
(Link target) -> 
  test-server.obj : error LNK2019: unresolved external symbol _WSAPoll referenced in function _main [C:\projects\libwebsockets\build\test-server-extpoll.vcxproj]
  C:\projects\libwebsockets\build\bin\Release\libwebsockets-test-server-extpoll.exe : fatal error LNK1120: 1 unresolved externals [C:\projects\libwebsockets\build\test-server-extpoll.vcxproj]
 
    35 Warning(s)
    2 Error(s)
 
Time Elapsed 00:00:22.13

any ideas?

**Comment by emptyVoid** [comment]
It should define ```_WIN32_WINNT``` to ```0x0600``` before including ```libwebsockets.h``` and WinAPI headers for ```WSAPoll``` to become available.

Since ```WinSock2.h``` checks requested API version when declaring ```WSAPoll```:
```
#if(_WIN32_WINNT >= 0x0600)
#if INCL_WINSOCK_API_PROTOTYPES
WINSOCK_API_LINKAGE
int
WSAAPI
WSAPoll(
    _Inout_ LPWSAPOLLFD fdArray,
    _In_ ULONG fds,
    _In_ INT timeout
    );
#endif /* INCL_WINSOCK_API_PROTOTYPES */
#endif // (_WIN32_WINNT >= 0x0600)
```

**Comment by JoakimSoderberg** [comment]
Well yes, this `#ifdef` makes no sense. `WSAPoll` is only available in Vista and onwards.

So the only reason for the added line:

```c
#if (_WIN32_WINNT < 0x0600) // This means if older than Vista.
WINSOCK_API_LINKAGE int WSAAPI WSAPoll(struct lws_pollfd fdArray[], ULONG fds, INT timeout);
```

Which is declaring something that should be declared in a windows header.

Total hack.

**Comment by JoakimSoderberg** [comment]
> It should define _WIN32_WINNT to 0x0600 before including libwebsockets.h

Uh you mean changing the current windows version define??? In `libwebsockets.h`? Even more of a hack

**Comment by emptyVoid** [comment]
Nah, I mean ```Appveyor``` should do it in its own version defining headers.

**Comment by lws-team** [comment]
Guys I tried a few things with Appveyor and backed this out for now.

Is doing this going to do more harm that good?

#if defined(WIN32) || defined(_WIN32)
#if (WINVER < 0x0600)
#undef WINVER
#undef _WIN32_WINNT
#define WINVER 0x0600
#define _WIN32_WINNT WINVER
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

I'm like a blind guy an Appveyor is my white stick..  If someone thinks they have a good solution send me a patch....

**Comment by netrounds-joakim** [comment]
> Nah, I mean Appveyor should do it in its own version defining headers.
??? They are just a CI service, that runs windows. They should not be touching the windows version defines either. So I don't get what you mean.

> I'm like a blind guy an Appveyor is my white stick.. If someone thinks they have a good solution send me a patch....

Sorry I don't have any off hand fix for this right now, but redefining the windows version I'm sure is not a good idea, and might give all sorts of weird results. Especially for end users that includes `libwebsockets.h` and then try to do their own stuff based on windows version defines.

I think we should revert to the original code until someone can produce a proper fix for this. Either getting rid of the use of `WSAPoll` entirely like libcurl did (before there was some other poll fakery going on, right?)...

**Comment by emptyVoid** [comment]
Yeah... sorry, I didn't now what Appveyor is (thought it is some project using libwebsockets).

I'll try to come up with a fix for ```test-server-extpoll``` (on my system CMake builds it without errors, though there's a warning concerning undefined ```WSAPoll```).

**Comment by lws-team** [comment]
Appveyor seems to have updated something and gone apeshit anyway

C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(94): error C2061: syntax error: identifier 'ADDRINFOEX' [C:\projects\libwebsockets\build\websockets.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(94): error C2059: syntax error: ';' [C:\projects\libwebsockets\build\websockets.vcxproj]

I don't have (or want) those proprietary tools so I can't look into why that's started happening.

**Comment by emptyVoid** [comment]
Here's changes that should fix ```test-server.obj : error LNK2019: unresolved external symbol _WSAPoll referenced in function _main ```.

Add the following to the top of ```test-server.h```:
```
#if defined(_WIN32) && defined(EXTERNAL_POLL)
#define WINVER 0x0600
#define _WIN32_WINNT 0x0600
#define poll(fdArray, fds, timeout)  WSAPoll((LPWSAPOLLFD)(fdArray), (ULONG)(fds), (INT)(timeout))
#endif
```
Remove the other ```poll``` definition from the same header:
```
#ifdef EXTERNAL_POLL
#define poll WSAPoll
#endif
```

**Comment by emptyVoid** [comment]
lws-team, what script does this Appveyor use to build libwebsockets?
I could try to reproduce the issues it has on my system.

**Comment by lws-team** [comment]
There's an "appveyor.yml" in the toplevel dir of lws.

But it doesn't assert the toolchain bits to use, unless I accidentally trod on something thismorning I think Appveyor have randomly updated their toolchain.

**Comment by emptyVoid** [comment]
Ok, I reproduced the issue.

To fix it add an include to ```private-libwebsockets.h``` line 69:
```
#include <winsock2.h>
#include <ws2tcpip.h>  // <-- this one, right between WinSock2.h and Windows.h
#include <windows.h>
```

Actually it's a side effect of having ```WINVER``` set to ```0x0600```.

I would remove the whole version alteration block from the public header:
```
#if (WINVER < 0x0600)
#undef WINVER
#undef _WIN32_WINNT
#define WINVER 0x0600
#define _WIN32_WINNT WINVER
#endif
```
Cause in reality it is totally unexpected for the user code. For example, user wants to target Windows XP as the lowest supported platform and sets ```_WIN32_WINNT``` (Microsoft recommends setting this one instead of ```WINVER```) to ```0x0501``` in their root header (which gonna be included before ```libwebsockets.h```) expecting Windows SDK to constrain to Windows XP APIs. Later in the chain of includes ```libwebsockets.h``` changes ```_WIN32_WINNT``` to ```0x0600```. This could either just silently enable unwanted Windows Vista APIs , or even break user's build if some WinAPI headers got included before ```libwebsockets.h``` and others after that.

**Comment by lws-team** [comment]
Great job, Appveyor is happy again.

Thanks a lot.

**Comment by JoakimSoderberg** [comment]
Yea as I mentioned, you cannot just change the window version without expecting weird results. The headers and defines in Windows are especially stupid.
