### ISSUE TITLE
Serving large files with external polling doesn't work on Windows

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#375]
There is a Windows-exclusive flag ```sock_send_blocking``` in ```struct lws``` which is being set with ```lws_set_blocking_send``` macro in ```lws_ssl_capable_write_no_ssl``` and ```lws_ssl_capable_write```. The field gets reset in ```lws_plat_service``` only (which is not used with external polling).

Effectively on Windows external polling code path is able to serve only small files which fit into socket's internal buffer (otherwise ```send``` sets ```LWS_ERRNO``` to ```LWS_EWOULDBLOCK``` and causes the flag to be set, that in turn prevents subsequent ```send``` for the file).

I'm not sure if it is the right place or the right way for the fix (and it definitely should be wrapped in a macro, like ```lws_clear_blocking_send```), though adding the following block to ```service.c``` right on top of ```/* okay, what we came here to do... */``` fixes the issue:
```
#ifdef _WIN32
	if (pollfd->revents & LWS_POLLOUT)
		wsi->sock_send_blocking = FALSE;
#endif
```

**Comment by lws-team** [comment]
I added it thanks.  We can refactor it just inside the library later, and frankly I daren't move it without being able to test it.
