### ISSUE TITLE
Parsing of escaped URL does not work as expected (take 3)

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#376]
1. ```lws_hdr_copy_fragment``` doesn't work for queries with a single key-value pair (e.g. for ```/cgi-bin/settings.js?key1=value1``` it returns ```-1``` for ```frag_idx``` set to ```0```).

2. [Not sure if it is an issue or a feature] Symbol ```;``` is not treated as a key-value delimiter.

3. There's a case where key-value pair could become ambiguous for the user code (e.g. for ```/cgi-bin/settings.js?key_%3D_key=value1&key2=value2``` the first pair gets reported as ```key_=_key=value1```).

PS: as of 54806b15417ff626ec8504c0666e4bf634846752

**Comment by lws-team** [comment]
Hoooo... I will look at 1), 2) I didn't know is legal, what do you think it should do? 3) hm urlencoding the name part of the pair with a version of = is unreasonable in terms of not being an attack isn't it?  Should we maybe drop the connection?

**Comment by emptyVoid** [comment]
2. According to [Wiki](https://en.wikipedia.org/wiki/Query_string#Web_forms) support of semicolon is recommended by W3C [here](http://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2).

3. According to [StackOverflow](http://stackoverflow.com/a/5433216) query string format is defined in [RFC 1866](https://www.rfc-editor.org/rfc/rfc1866.txt); clause [8.2.1]: 
```
        1. The form field names and values are escaped: space
        characters are replaced by `+', and then reserved characters
        are escaped as per [URL]; that is, non-alphanumeric
        characters are replaced by `%HH', a percent sign and two
        hexadecimal digits representing the ASCII code of the
        character. Line breaks, as in multi-line text field values,
        are represented as CR LF pairs, i.e. `%0D%0A'.
```
I guess it is used in some scenarios.

**Comment by lws-team** [comment]
1) works fine here... I'm using the v1.6.0 release but I don't think it's changed since your version.

Run the libwebsockets-test-server with -d15 (so we can see info logging, relies on build with _DEBUG)

$  wget "http://localhost:7681/cgi-bin/settings.js?key1=value1"

He says "forbidden" but in the test server window

lwsts[17802]: Method: GET request for '/cgi-bin/settings.js'
    get  = /cgi-bin/settings.js
    host: = localhost:7681
    connection: = Keep-Alive
    http/1.1  = HTTP/1.1
    accept: = */*
    accept-encoding: = identity
    user-agent: = Wget/1.16.3 (linux-gnu)
    delete = key1=value1  <--- this is the composite URI args to be ignored now
lwsts[17802]: URI Arg 1: key1=value1  <--- this is in fragment 0

**Comment by lws-team** [comment]
I pushed a patch making an unescaped semicolon be treated like an unescaped ampersand.

03d7e9d33123c3079b7e12d5ea77dc5169772fc2

I pushed another patch which converts + to spaces.

8b9fe99deeffa16adc0dab19441a284c67ad5935

And a third one which translates %3d in the name part of name=value to be _, so the real = is always the first = that can be found.

3ba035dc2ca467d138b822e74b79fe689b2e182d

**Comment by emptyVoid** [comment]
1) Yeah, I identified the cause: since there's no way to get the size of a fragment I get the total size using ```len = lws_hdr_total_length( wsi, WSI_TOKEN_HTTP_URI_ARGS );``` and then request a copy ```lws_hdr_copy_fragment( wsi, buffer, len + 1, WSI_TOKEN_HTTP_URI_ARGS, index );```.

Here's what causes the issue:
```
	if (wsi->u.hdr.ah->frags[f].len >= (len - 1))
		return -1;
```
I think it should be ```>= len``` as in ```lws_hdr_copy```.

**Comment by emptyVoid** [comment]
>And a third one which translates %3d in the name part of name=value to be _, so the real = is always the first = that can be found.

Won't that be an issue if the name part contains other ```_``` symbols? How to translate it back to ```=``` in this case?

**Comment by lws-team** [comment]
The goal of it is to retain the original = and have the user code fail to recognize that name cleanly.  Actually nobody choosing the namespace for x=y is going to choose x is able to contain '='.

**Comment by lws-team** [comment]
About the length, no it's -1 because we add a '\0' on the copy, in the simple case you just look for canned name=value or just existence of name=, you can use strcmp then, you can use strchr safely to find the = etc.

**Comment by emptyVoid** [comment]
>The goal of it is to retain the original = and have the user code fail to recognize that name cleanly. Actually nobody choosing the namespace for x=y is going to choose x is able to contain '='.

And what if the user code expects ```some_key``` named key, while URL request has ```some%3dkey=hack``` in its query?

>About the length, no it's -1 because we add a '\0' on the copy, in the simple case you just look for canned name=value or just existence of name=, you can use strcmp then, you can use strchr safely to find the = etc.

But ```(wsi->u.hdr.ah->frags[f].len >= (len - 1))``` check fails only when ```dst``` is 2-bytes bigger than the fragment. For the case ```key1=value1``` I set ```len``` to ```12```, and this check looks like ```if (11 >= (12-1))```.

**Comment by lws-team** [comment]
Yeah... what if exactly... the "attacker" can just as well save his fingertips and use the "some_key=not-much-of-a-hack".  The code is going to see "some_key" either way, what's the hack there?  It didn't buy him anything.

Alright I will look closer and the length thing.

**Comment by lws-team** [comment]
You're right about the length, he basically requires length +2 as it is when all he needs is length +1 (for the '\0').  I pushed a one-liner allowing the length to be smaller by one char.

**Comment by lws-team** [comment]
I added a lws_hdr_fragment_length().

I'll close this now, we can open a take 4 or reopen this if there is more.
