### ISSUE TITLE
The websocket connection stopped working after upgrading to 1.6

### ISSUE THREAD

**Issue by 012345678987654321** [warmcat/libwebsockets#382]
Hi!

I have upgraded my software to libwebsockets 1.6.0 like in the changelog described, but now the websocket connection stopped to work. My callback is called only once, with "LWS_CALLBACK_PROTOCOL_INIT" as reason and that's all. I don't get any error, neither on the server side nor  on the client side. My protocols are defined as follow:

	struct lws_protocols protocols[3] =
	{
	    /* first protocol must always be HTTP handler */
	    {
	        "http-only",
	        callback_http,
	        sizeof(per_session_data),
	        0
	    },
	    {
	        "websocket",
	        callback_ws,
	        sizeof(per_session_data),
	        0
	    },
	    {
	        NULL, NULL, 0, 0  /* End of list */
	    }
	};

And later the thread:

	// Context creation info
	struct lws_context_creation_info info;

	// Context creation info setup
	memset(&info, 0, sizeof info);
	info.port = __CONFIG_SERVER_PORT__;
	info.iface = NULL;
	info.protocols = protocols;
	info.extensions = NULL;
	info.ssl_cert_filepath = NULL;
	info.ssl_private_key_filepath = NULL;
	info.gid = -1;
	info.uid = -1;
	info.options = 0;
	info.ka_time = 0;

	// Create context
	struct lws_context *context = lws_create_context(&info);
	if(!context) return NULL;

        while(server_is_running) {
                lws_service(context, 10);
        }

        // Destroy
	lws_context_destroy(context);

Do you have any idea what can cause the problem!? Thank you :)

**Comment by lws-team** [comment]
Make sure you set up the logging like in the test server, and set the logging level to, eg, 31

**Comment by 012345678987654321** [comment]
Yeah, did it. But nothing happens. No  error or anything else. I only get my first info messages and that's it, nothing else happens. On the client side (WebBrowser) onopen is called properly, but than nothing.

**Comment by lws-team** [comment]
Does the test server itself work OK on your platform?

**Comment by 012345678987654321** [comment]
Hm yes, it does.

**Comment by 012345678987654321** [comment]
Ok, solved it. It was a mistake in my js code. I haven't used a protocol name before, and for some reason the lieb didn't like that after the upgrade. Now i have fixed that and it works. :)

**Comment by lws-team** [comment]
Glad you're working again.

FWIW I checked the echo test app by giving it a protocol name of "" and even NULL and it could still work in both server and client modes.
