### ISSUE TITLE
Select the IP for making WebSocket requests

### ISSUE THREAD

**Issue by SzAmmi** [warmcat/libwebsockets#385]
My computer has a few IPs. Can I select one for making WebSocket connections? I want to set the local address for the connection. Is this possible?

**Comment by JoakimSoderberg** [comment]
I assume you're talking about a websocket client? The echo client example shows you how to bind to a specific interface:
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-echo.c#L397

So if you list the available interfaces, and then get their respective IPs you can then enable binding to the appropriate interface.

**Comment by SzAmmi** [comment]
Oh thanks, I was looking for it! :)

2015-12-29 20:01 GMT+01:00 Joakim Söderberg <notifications@github.com>:

> I assume you're talking about a websocket client? The echo client example
> shows you how to bind to a specific interface:
>
> https://github.com/warmcat/libwebsockets/blob/master/test-server/test-echo.c#L397
>
> So if you list the available interfaces, and then get their respective IPs
> you can then enable binding to the appropriate interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/warmcat/libwebsockets/issues/385#issuecomment-167853709>
> .
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by SzAmmi** [comment]
Do You by `_interface` mean interface name?

2015-12-30 14:37 GMT+01:00 Szymon Marczak <sz.marczak@gmail.com>:

> Oh thanks, I was looking for it! :)
>
> 2015-12-29 20:01 GMT+01:00 Joakim Söderberg <notifications@github.com>:
>
>> I assume you're talking about a websocket client? The echo client example
>> shows you how to bind to a specific interface:
>>
>> https://github.com/warmcat/libwebsockets/blob/master/test-server/test-echo.c#L397
>>
>> So if you list the available interfaces, and then get their respective
>> IPs you can then enable binding to the appropriate interface.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/warmcat/libwebsockets/issues/385#issuecomment-167853709>
>> .
>>
>
>
>
> --
> Pozdrawiam,
> Szymon Marczak
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by JoakimSoderberg** [comment]
Well yes, in this example it would be `eth0` or whatever. But of course as I said, you could first translate IP to what interface that IP belongs to (unless your interfaces have multiple IPs of course).

**Comment by SzAmmi** [comment]
Thanks! This issue can be closed.

**Comment by lws-team** [comment]
Thanks Joakim.  I'm not certain but on some platforms I think you can stick the network interface IP itself in there as well and it will bind the socket appropriately from that.
