### ISSUE TITLE
janus gateway checking

### ISSUE THREAD

**Issue by interfaith** [warmcat/libwebsockets#389]
git clone git://git.libwebsockets.org/libwebsockets
	cd libwebsockets
	mkdir build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
	make && sudo make install

then configure for janus gives 

checking for TRANSPORTS... yes
checking for MHD... yes
checking for libwebsocket_get_internal_extensions in -lwebsockets_shared... no
checking for libwebsocket_get_internal_extensions in -lwebsockets... no
configure: error: libwebsockets not found. See README.md for installation instructions or use --disable-websockets

**Comment by interfaith** [comment]
the github.com awm086 libwebsocket did work ok !

**Comment by JoakimSoderberg** [comment]
The name of `libwebsocket_get_internal_extensions` has been changed to `lws_get_internal_extensions` in the latest `master` branch. So janus would have to be changed to use the new updated API.

So you should checkout the latest libwebsockets release instead, that has the old API and build that instead.

**Comment by lws-team** [comment]
```
git checkout v1.5-chrome47-firefox41
```
Is probably what it wants, 1.6 release has the name changes.

**Comment by lws-team** [comment]
I assume this is resolved, if not, please reopen.
