### ISSUE TITLE
Can I pass the same buffer to many libwebsocket_write() calls?

### ISSUE THREAD

**Issue by MacGritsch** [warmcat/libwebsockets#390]
Hi there,

a server has many connected clients.
At one point he needs to push/send a message to all connected clients (same message for all).
Can I pass the same memory-buffer to all libwebsocket_write calls?

thank you

**Comment by lws-team** [comment]
In the case it's a server particularly, yes.  In ws protocol the **client** must send stuff xor'd with a random 32-bit mask... lws does that masking in-place at write time destroying the input buffer.  But the server never sends anything masked, and the ws protocol prepends that are also written behind the input buffer do not get referenced after the write operation that put them there.  So it's safe.

**Comment by MacGritsch** [comment]
Thank you for the information!
