### ISSUE TITLE
Valgrind: lws_accept_cb leaves eventfd.events uninitialized

### ISSUE THREAD

**Issue by alexhultman** [warmcat/libwebsockets#393]
I'm trying to swap my use of the default poll() to epoll() by using libev. It kind of works (sometimes) but it is very buggy.

In libev.c:
In lws_accept_cb:
struct lws_pollfd eventfd; <- created and passed to lws_service_fd with events member unset. Causes "conditional jump or move depends on uninitialised value(s)" in lws_server_socket_service @ line 696:
```c++
if (!(pollfd->revents & pollfd->events && LWS_POLLIN))
	goto try_pollout;
```

This can, however be my fault since I'm kind of left in the dark for the most part as the documentation is very scarce. I'm using lws_initloop, setting the LWS_SERVER_OPTION_LIBEV, compiling with -DLWS_WITH_LIBEV=1 and running ev_run.

**Comment by lws-team** [comment]
There's a variant of the test-server that builds now that uses libev.

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-libev.c

That should help with the how-to-do, but the other thing you found seems a bug.

**Comment by lws-team** [comment]
I pushed a patch setting events to match revents in that code.  The code that makes the error is new, the test on events was only added recently.

**Comment by alexhultman** [comment]
Now my server works perfectly. And it outperforms Node.js running in debug mode. Thanks for quick support!
