### ISSUE TITLE
Using lws in C++ causes warning with -Wshadow

### ISSUE THREAD

**Issue by rikvdh** [warmcat/libwebsockets#396]
Hi,

I'm intending to use libwebsocket within our application. We use C++11 and have very strict compiler options enabled.

We faced the error below. The problem is that the function `lws_client_connect_info` has the name name as the struct.

```
libwebsockets/lib/libwebsockets.h:1620:64: error: ‘lws* lws_client_connect_info(lws_client_connect_info*)’ hides constructor for ‘struct lws_client_connect_info’ [-Werror=shadow]
 lws_client_connect_info(struct lws_client_connect_info * ccinfo);
```

Can this be fixed?

Thanks,

Rik

**Comment by lws-team** [comment]
I changed the new api name to lws_client_connect_via_info() and left everything else the same.
