### ISSUE TITLE
Limit number of connections per context

### ISSUE THREAD

**Issue by alexhultman** [warmcat/libwebsockets#397]
I'm running multiple single-threaded instances of lws on separate threads. Every instance of lws allocates memory for handling up to \<max file descriptors allowed, system wide\>. However, since every instance is supposed to handle only a fraction of this system wide limit, it is unnecessary for every instance to allocate memory for this system limit.

What I'm saying is, a system limit of 1 million file descriptors, and 10 instances of lws means a better allocation would be 100k per instance. It would be nice to be able to specify some kind of per instance limit.

Or maybe lws allocates 1 million descriptors at init and then shares these with every context created? It doesn't seem like this? Maybe I'm missing something?

Edit: "system wide limit" is wrong, I mean per process.

**Comment by alexhultman** [comment]
context.c @ 189: context->max_fds = getdtablesize();

This could be easily limited by passing some kind of value in the lws_context_creation_info struct

**Comment by lws-team** [comment]
You are right.

But *nix has a way to do this already

http://ss64.com/bash/ulimit.html

Try using ulimit -n 1024 or whatever before starting lws.

If you're on Windows, well, that sucks you have other problems.

**Comment by alexhultman** [comment]
Haha, no I'm not on Windows.

But won't ulimit limit the whole process? I want the process to be able to handle many connections, while every instance of lws should only allocate a fraction of this process limit.

**Comment by lws-team** [comment]
Yes you are right, it limits the process.  Let me study it in a little while.

**Comment by alexhultman** [comment]
Well yes it seems to work that way:
```c++
    struct rlimit rlim;
    getrlimit(RLIMIT_NOFILE, &rlim);
    rlim.rlim_cur /= 10;
    setrlimit(RLIMIT_NOFILE, &rlim);

    cout << getdtablesize() << endl;

    rlim.rlim_cur *= 10;
    setrlimit(RLIMIT_NOFILE, &rlim);

    cout << getdtablesize() << endl;
```

Displays 100k and then 1million. I guess I could do this to get what I need.

**Comment by lws-team** [comment]
If it's workable then it seems to be enough.

**Comment by alexhultman** [comment]
Yes, it lowered RAM usage from 400mb to 40mb. Sorry for this report.

**Comment by alexhultman** [comment]
I'm not sure it works correctly. Looking at the memory usage, it clearly uses less memory but I'm not able to get more connections than what I specified in the first setrlimit called before context creation. If I remove this ulimit limitation, it starts to work again and I can get many connections but then I have the initial problem of a very large memory allocation.

**Comment by lws-team** [comment]
Hmmm I think ulimit may only let you revise things downwards unless you have root powers.

How about start as root, do this, and drop permissions (you can set the perms to drop to in the info struct).

**Comment by lws-team** [comment]
Did this get sufficiently solved or we should add something on info?

**Comment by alexhultman** [comment]
Hi. Sorry for the delay. I tried running the server as root but I got the same results. I cannot get more connections than what I set prior to initializing the contexts, even if I re-set the limits before starting the eventloops.

**Comment by lws-team** [comment]
What's the way forward then... leave the ulimit very high and restrict it in each context create?

If so, please send a patch.

**Comment by alexhultman** [comment]
I can take a look. Maybe not the highest priority right now for us but certainly something to look at later on.

**Comment by lws-team** [comment]
I see... well, let's reopen this when the planets align.

**Comment by alexhultman** [comment]
I've taken a look and I'm starting to figure things out. I've reduced the memory usage from 400mb down to 200mb by fixing context->fds allocation, but I should be able to reduce it down to 14mb by fixing the same for context->lws_lookup (however that is currently crashing).

I could start by cleaning up the fix for context->fds.

**Comment by alexhultman** [comment]
There we go! Now it consumes 16mb ram from start, even though I have 30 contexts :)

I can get 100k connections so it seems to work. Will clean this up.

**Comment by alexhultman** [comment]
This is what I'm working with (unfinished):

```
diff --git a/lib/context.c b/lib/context.c
index 436216a..662707d 100644
--- a/lib/context.c
+++ b/lib/context.c
@@ -131,6 +131,7 @@ lws_create_context(struct lws_context_creation_info *info)
 	context->ka_time = info->ka_time;
 	context->ka_interval = info->ka_interval;
 	context->ka_probes = info->ka_probes;
+	context->max_connections = info->max_connections;
 
 	memset(&wsi, 0, sizeof(wsi));
 	wsi.context = context;
@@ -186,16 +187,22 @@ lws_create_context(struct lws_context_creation_info *info)
 		    context->max_http_header_data, sizeof(struct allocated_headers),
 		    context->max_http_header_pool);
 
+	/* max_fds is only used for checking file descriptor boundaries */
 	context->max_fds = getdtablesize();
 
-	context->fds = lws_zalloc(sizeof(struct lws_pollfd) * context->max_fds);
+	/* limit number of connections per context */
+	if ((context->max_connections && context->max_connections >
+	     context->max_fds) || !context->max_connections)
+		context->max_connections = context->max_fds;
+
+	context->fds = lws_zalloc(sizeof(struct lws_pollfd) * context->max_connections);
 	if (context->fds == NULL) {
-		lwsl_err("OOM allocating %d fds\n", context->max_fds);
+		lwsl_err("OOM allocating %d fds\n", context->max_connections);
 		goto bail;
 	}
 
 	lwsl_info(" mem: pollfd map:      %5u\n",
-		    sizeof(struct lws_pollfd) * context->max_fds);
+		    sizeof(struct lws_pollfd) * context->max_connections);
 
 	if (lws_plat_init(context, info))
 		goto bail;
diff --git a/lib/libwebsockets.h b/lib/libwebsockets.h
index 7b771ea..7f5a728 100644
--- a/lib/libwebsockets.h
+++ b/lib/libwebsockets.h
@@ -1286,6 +1286,8 @@ struct lws_context_creation_info {
 	short max_http_header_data;
 	short max_http_header_pool;
 
+	unsigned short max_connections;
+
 	/* Add new things just above here ---^
 	 * This is part of the ABI, don't needlessly break compatibility
 	 *
diff --git a/lib/lws-plat-unix.c b/lib/lws-plat-unix.c
index 9d3a66c..a0b5e56 100644
--- a/lib/lws-plat-unix.c
+++ b/lib/lws-plat-unix.c
@@ -496,7 +496,10 @@ LWS_VISIBLE int
 lws_plat_init(struct lws_context *context,
 	      struct lws_context_creation_info *info)
 {
-	context->lws_lookup = lws_zalloc(sizeof(struct lws *) * context->max_fds);
+	static void *global_table;
+	if (!global_table)
+		global_table = lws_zalloc(sizeof(struct lws *) * context->max_fds);
+	context->lws_lookup = global_table;
 	if (context->lws_lookup == NULL) {
 		lwsl_err(
 		  "Unable to allocate lws_lookup array for %d connections\n",
@@ -505,7 +508,7 @@ lws_plat_init(struct lws_context *context,
 	}
 
 	lwsl_notice(" mem: platform fd map: %5u bytes\n",
-		    sizeof(struct lws *) * context->max_fds);
+		    sizeof(struct lws *) * context->max_connections);
 
 	context->fd_random = open(SYSTEM_RANDOM_FILEPATH, O_RDONLY);
 	if (context->fd_random < 0) {
diff --git a/lib/lws-plat-win.c b/lib/lws-plat-win.c
index 988460a..1dbb5e0 100644
--- a/lib/lws-plat-win.c
+++ b/lib/lws-plat-win.c
@@ -501,16 +501,16 @@ lws_plat_init(struct lws_context *context,
 
 	for (i = 0; i < FD_HASHTABLE_MODULUS; i++) {
 		context->fd_hashtable[i].wsi =
-			lws_zalloc(sizeof(struct lws*) * context->max_fds);
+			lws_zalloc(sizeof(struct lws*) * context->max_connections);
 
 		if (!context->fd_hashtable[i].wsi)
 			return -1;
 	}
 
-	context->events = lws_malloc(sizeof(WSAEVENT) * (context->max_fds + 1));
+	context->events = lws_malloc(sizeof(WSAEVENT) * (context->max_connections + 1));
 	if (context->events == NULL) {
 		lwsl_err("Unable to allocate events array for %d connections\n",
-			context->max_fds);
+			context->max_connections);
 		return 1;
 	}
 
diff --git a/lib/pollfd.c b/lib/pollfd.c
index 319abbd..39ed26a 100644
--- a/lib/pollfd.c
+++ b/lib/pollfd.c
@@ -26,8 +26,8 @@ insert_wsi_socket_into_fds(struct lws_context *context, struct lws *wsi)
 {
 	struct lws_pollargs pa = { wsi->sock, LWS_POLLIN, 0 };
 
-	if (context->fds_count >= context->max_fds) {
-		lwsl_err("Too many fds (%d)\n", context->max_fds);
+	if (context->fds_count >= context->max_connections) {
+		lwsl_err("Too many fds (%d)\n", context->max_connections);
 		return 1;
 	}
 
diff --git a/lib/private-libwebsockets.h b/lib/private-libwebsockets.h
index 36ae98f..274ef8d 100644
--- a/lib/private-libwebsockets.h
+++ b/lib/private-libwebsockets.h
@@ -594,6 +594,7 @@ struct lws_context {
 
 	short max_http_header_data;
 	short max_http_header_pool;
+	unsigned short max_connections;
 	short ah_count_in_use;
 };
```

The need for max_connections is minimal, I would rather use max_fds but since that is used in lws_init_plat to allocate the (global, shared) lws_lookup-table I cannot use it but need to add max_connections. Any thoughts on this?

**Comment by lws-team** [comment]
I don't understand why you are calling the lws_lookup array "global"... he also exists within one context... am I missing a point somewhere?

You're spawning n contexts and servicing them in n threads?  Or something else?

**Comment by alexhultman** [comment]
It is global in the sense that it contains file descriptors (which are in "global domain") while fds as an example is local in the sense thay is holds file descriptors in " local domain". Wsi_insert inserts file descriptors in the context->lws_lookup buffer and since a file descriptor is global, the memory can be shared between all contexts.

At least thats how I currently see it.

**Comment by lws-team** [comment]
I am not sure that's accurate... in unix fds are a per-process ordinal starting from 0.

If you use fork() to generate your n instances, each fork gets copes of parent open files but after that, each forked process may open his own set of files / sockets up to the limit.  So each forked process may have a fd "5" and that can be a different file or socket in each forked process context.  And with fork a fd limit of 10000 with 10x forked contexts would get your job done.

If you spawn threads - that is why I asked about it - there is only one process and the fds are a common resource in the process, there is only one fd "5" and any thread that looked at it would see the same file or socket.  You need an fd limit of 100000, create 10 contexts each with his own thread and service loop.

Either way you are listening on 10 different ports limited to 10000 fds using this new scheme, and you must load-balance them somehow.

Unless I miss a point somewhere... ?

**Comment by alexhultman** [comment]
I use threads so there is only one process yes. It can be solved mpre gracefully by changing wsi_insert to not use sock but some local offset instead.

**Comment by alexhultman** [comment]
It can also be solved by checking the PID to see if it differs from the static pointer. If it differs - allocate a new buffer.

**Comment by alexhultman** [comment]
Maybe it is considered too specific as I could use multiple processes to solve it without any fix. However, I don't want to. Maybe I should keep this as a private patch for our purpose only?

**Comment by lws-team** [comment]
No I am not against it at all.  But lws is fundamentally not threadsafe, by design.  So only one thread may service one context.  Then smp scaling for n cores must be done with n contexts.

I think we probably need to add the load balancing in the library to some extent so you can have one listen socket, but he figures out which context should take the accept to best balance the load.

I just want to make sure we're fighting the same problem, and that afterwards it can still work with fork or threads.

What seems good to me is just each thread has a new 10000 context with only his local fds.  And we add load-balancing and communication between the contexts if needed.

**Comment by alexhultman** [comment]
I'm not trying to change thread-safety, I'm running 1 context per thread. It's just about reducing memory usage for this specific case.

Load balancing is IMO another problem and could be solved by third party layers, or by the Linux 3.9 SO_REUSEPORT feature which allows multiple threads to listen to the same port and have the kernel load balance it.

This patch is not compatible with fork() like you pointed out. In order to make this applicable for others I need to solve this for use with fork() as well as with threads.

*What seems good to me is just each thread has a new 10000 context with only his local fds.*

You like the context->fds limitation?

**Comment by lws-team** [comment]
Oh... I will read about SO_REUSEPORT.

But if there will be n contexts we still need to do things in the library to make that transparent to apis like "callback when writeable all protocol".

The fds "limitation" might be helpful since there's a lot of overhead scanning the fds to find the ones that need service.  If one guy needs something at the end of a 100K array it's expensive to find him.  Whereas with the smp-friendly smaller contexts, we can service n things simultaneously only by scanning 10K array.

**Comment by lws-team** [comment]
I read this

https://lwn.net/Articles/542629/

It seems it might not be a good way despite the simplicity.

a) it's linux-only afaik

b) he only distributes fairly according to threads blocked waiting to accept.  Actually it doesn't know how many live connections are active in each thread.  If over time one thread / context has less active connections, this won't act to balance that, leading to cpu-bound cores and idle cores.

I'm willing to work on this end, I know we already have at least one user in the 100K+ connection service range it would be good to simplify it.  Because performance / memory usage should be very good compared to other solutions.

**Comment by alexhultman** [comment]
Yeah it's a very basic load balancer, we might use something else (Amazon and other distributors have built in load balancing) - it's not decided. We are still pretty much in planning phase and I don't even know if we need WebSockets (lol!). I'm just kind of evaluating libwebsockets at this moment. I looked at many different WebSocket server implementations and libwebsockets scale far (up to 16x) better than the best library for Node.js and maybe 3x better than WebSocket++.

I use libev which is using epoll instead of poll so we don't face the increasing linear search (I hope?).

The library is pretty rough in terms of usage and documentation but I don't see any need to improve it - any user is going to wrap it up themselves anyways, it's more like a foundation than something you use directly IMO (well, I for sure don't use it directly).

**Comment by lws-team** [comment]
Yes put another way lws should require a fraction of the server capacity to do the same job as the traditional web services methods, and he's very modest on memory.

Yes libev / epoll should get you out from the linear searches.

**Comment by alexhultman** [comment]
As a completely unrelated side note. For fun I'm doing a Node.js addon for lws, called lws (meant as a reference to ws but also to lws). Now I realize this might be way too closely named and cause confusion / "credit-stealing". It could be renamed to node-lws or anything other. However, I like lws because it is like (lightweight) ws.

https://github.com/alexhultman/lws
https://github.com/websockets/ws

Do you have any thoughts on the naming. Also, I don't have any way of contacting you other than through github issues.

**Comment by JoakimSoderberg** [comment]
I'd go with `node-lws`, but not really for the reason you mentioned:

https://github.com/search?utf8=%E2%9C%93&q=lws

;)

Or mayb `node-libwebsockets` to be explicit...

**Comment by alexhultman** [comment]
That's a ton of lws for sure. But any user would use npm to install and the package name lws is not taken. The goal is (probably) for any user to simply swap ws with lws.

**Comment by lws-team** [comment]
I think it's cool, but as Joakim says we pretty universally use 'lws' to refer to libwebsockets.  Even though it's in a different namespace for install, it isn't in, eg github.

It probably sounds pedantic to bloat your name if the existing one is 'ws', but I don't think you'll regret disambiguating it SEO-wise in the long run.  Even 'nlws' would be enough.

**Comment by lws-team** [comment]
I just pushed a patch which implements multithreaded service support in lws.

https://github.com/warmcat/libwebsockets/commit/d3a550554241735dfa7a06b608a3908e845845fa

You can control both the number of service threads and if you choose the number of fds each thread can handle explicitly, setting a couple of ints in info struct: by default it divides the process fd limit between the threads.

The actual threading is entirely done in the user code, I implemented support in libwebsockets-test-server-pthreads as an example but there is nothing about pthreads or other locking / threading in lws itself.

Structurally there is one context, with one listening socket, that holds the process fd->wsi map, and it load-balances accepts to the service thread with the lowest number of active connections.  The individual service threads do their own poll() on the subset of wsis that they were allocated and service simultaneously, each only dealing with their own subset.

You can test it easily with

$ libwebsockets-test-server-pthreads -j 8

(-j is number of service threads).and use the code in there as a template

```
void *thread_service(void *threadid)
{
	while (lws_service_tsi(context, 50, (int)(long)threadid) >= 0 && !force_exit)
		;

	pthread_exit(NULL);
}
```
```
	for (n = 0; n < lws_get_count_threads(context); n++)
		if (pthread_create(&pthread_service[n], NULL, thread_service,
				   (void *)(long)n))
			lwsl_err("Failed to start service thread\n");

	/* wait for all the service threads to exit */

	for (n = 0; n < lws_get_count_threads(context); n++)
		pthread_join(pthread_service[n], &retval);
```

**Comment by lws-team** [comment]
Well the original topic is now solved I think.  If you find any problems please reopen.

**Comment by alexhultman** [comment]
Well yes sure but I'm not using any locking. Might try this later but in any case I have a custom patch.
