### ISSUE TITLE
recent change broke Windows build

### ISSUE THREAD

**Issue by bprodoehl** [warmcat/libwebsockets#400]
Thanks again for the great library.  I think this commit introduced a raw close():

https://github.com/warmcat/libwebsockets/commit/809d69aa859255f21ac137644e855cc88f58c101#diff-e76d1429d8485adf3df5b570b26637d1R355

That fails to build on Windows.  Replacing the close(wsi->sock) with compatible_close(wsi->sock) fixed the problem for me.

**Comment by lws-team** [comment]
Yes my mistake... thanks for letting me know.
