### ISSUE TITLE
improper use of tolower() in parsers.c

### ISSUE THREAD

**Issue by bprodoehl** [warmcat/libwebsockets#403]
Building with gcc 4.9.3 on Windows, I'm getting this error:

```
/src/libwebsockets/lib/parsers.c: In function ‘lextable_decode’:
/src/libwebsockets/lib/parsers.c:32:2: error: array subscript has type ‘char’ [-Werror=char-subscripts]
  c = tolower(c);
  ^
cc1: all warnings being treated as errors
```

The manpage for tolower() says ```If c is not an unsigned char value, or EOF, the behavior of these functions is undefined.```  I think the best fix is just to change the definition of lextable_decode from ```int lextable_decode(int pos, char c)``` to ```int lextable_decode(int pos, unsigned char c)``` seeing as how its only called from lws_parse() with an unsigned char anyways.  Guess this also affects minihuf.c and minilex.c but cmake didn't try to build those for me.

**Comment by lws-team** [comment]
I pushed a patch removing tolower and doing it by hand.
