### ISSUE TITLE
lws_write could be improved by passing a structure with dataptr + size

### ISSUE THREAD

**Issue by xor-gate** [warmcat/libwebsockets#406]
Currently I have integrated libwebsockets in a C++ application which emits JSON into a buffer. The downside with `lws_write` currently is there needs to be always have leading and trailing buffer space. So I need to wrap a alloc (json size + head + tail), then memcpy the json at correct offset and then pass it to `lws_write`. Would it not be more nice to pass a structure with a pointer to the actual data + size. And have the structure allocated on the stack of the caller so libwebsockets can write the header and tail into the struct and send the correct fields as appropriate. This saves a alot of memcpy and offset calculation which slows down the application performance. It can also a bit dangerous to use because libwebsocket will write before and after the data pointer currently. The structure can look something like this (correct me if i'm wrong):

```c
struct lws_writer {
   unsigned char *data;
   size_t len;
   unsigned char header[LWS_SEND_BUFFER_PRE_PADDING];
   unsigned char end[LWS_SEND_BUFFER_POST_PADDING];
};
```

Then the write function can become:

```c
int lws_write (struct lws * wsi, struct lws_writer *w, enum lws_write_protocol protocol)
```

**Comment by lws-team** [comment]
Why don't you tell the thing writing the JSON to do it at &buf[LWS_PRE] instead of buf?  Then no memcpy, which is the point of doing it this way.

The trailing space requirement has gone in current master branch.

**Comment by xor-gate** [comment]
You are right it is well stated in the current header of the `lws_write` function: https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L1518-L1532. Sorry for the noise.
