### ISSUE TITLE
Add "#include <sys/socket.h>" to test-server/fuzxy.c

### ISSUE THREAD

**Issue by stevenylai** [warmcat/libwebsockets#407]
As titled, without the include, and using gcc3, I got:

/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c: In function `fuzxy_listen':
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:465: warning: implicit declaration of function `socket'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:472: warning: implicit declaration of function `setsockopt'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:492: warning: implicit declaration of function `bind'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:500: warning: implicit declaration of function `getsockname'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:505: warning: implicit declaration of function `listen'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c: In function `handle_accept':
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:708: warning: implicit declaration of function `connect'
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c: In function `main':
/home/stevenylai/work/src/linux_firmware/build/RT5350/build/ws/libwebsockets/test-server/fuzxy.c:846: warning: implicit declaration of function `accept'
CMakeFiles/test-fuzxy.dir/build.make:62: recipe for target 'CMakeFiles/test-fuzxy.dir/test-server/fuzxy.c.o' failed

**Comment by lws-team** [comment]
It's pushed thanks.
