### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by select-this** [warmcat/libwebsockets#409]
Hi

In the latest master of libwebsockets, I get the following warning when building:

``/home/dferrie/Eclipse/libs/libwebsockets/lib/ssl-http2.c:` In function ‘lws_http2_configure_if_upgraded’:
/home/dferrie/Eclipse/libs/libwebsockets/lib/ssl-http2.c:112:14: error: variable ‘method’ set but not used [-Werror=unused-but-set-variable]
  const char *method = "alpn";``

Since all warnings appear to be treated as errors, this aborts the compilation.

**Comment by lws-team** [comment]
What version is that?  Because line 112 is in a completely different function.

**Comment by select-this** [comment]
Sorry, please ignore this; I upgraded libssl this morning from someone's Ubuntu PPA and it appears to be a broken version, as a downgrade then allowed the build to continue.

I don't know why this manifested as a compilation error.
