### ISSUE TITLE
Questionable use of libev

### ISSUE THREAD

**Issue by alexhultman** [warmcat/libwebsockets#410]
Hi.

I'm still playing around with wrapping libwebsockets for Node.js. I have recently realized I need to port it over to libuv from libev to play nicely with Node.js (which uses libuv). I decided I wanted to simply implement a wrapper of libev, making use of libuv. This works and is a very simple way of not polluting libwebsockets with stuff about libuv (and I do not want to write a custom poller).

This wrapper is very minimal, only a couple of lines and makes corresponding calls to libuv.

Now, I'm debugging some strange behavior:

ev_io_init, fd: 4, ptr: 0x1a000f0
ev_io_start, fd: 4, ptr: 0x1a000f0
\<server runs\>
ev_io_init, fd: 11, ptr: 0x1a28d58
ev_io_init, fd: 11, ptr: 0x1a28d90
ev_io_start, fd: 11, ptr: 0x1a28d58
\<connection happens\>
ev_io_start, fd: 11, ptr: 0x1a28d90
lws: src/unix/core.c:833: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

(ptr is the pointer to the passed ev_io). In other words, you are initializing the same fd twice, but with different pointers. The documentation is unclear about this but it seems invalid. You should only need to initialize it once and then pass this pointer around. Making sure you pass the same pointer when representing the same fd would greatly help my wrapper work.

What's your thoughts on this?

**Comment by andrew-canaday** [comment]
I can't tell without looking into it, but my guess would be that you are
seeing two separate ev_io watchers used for a single fd - one for read
events and one for write events. This is the pattern recommended by the
ev.pod, though I don't recall whether or not libwebsockets adopted it. To
the best of my recollection, it has.

Hope this helps!

Ciao!
-Andrew

**Comment by lws-team** [comment]
The libev stuff was contributed... I only wrote the libev test server.  So I'm not the right guy to discuss how it works.

But looking around a bit, we're not talking about this are we?

```
LWS_VISIBLE void
lws_libev_accept(struct lws *new_wsi, int accept_fd)
{
	struct lws_context *context = lws_get_context(new_wsi);
	struct ev_io *r = &new_wsi->w_read.watcher;
	struct ev_io *w = &new_wsi->w_write.watcher;

	if (!LWS_LIBEV_ENABLED(context))
		return;

	new_wsi->w_read.context = context;
	new_wsi->w_write.context = context;
	ev_io_init(r, lws_accept_cb, accept_fd, EV_READ);
	ev_io_init(w, lws_accept_cb, accept_fd, EV_WRITE);
}
```

**Comment by alexhultman** [comment]
Yes you have found it. But looking at the libev doc it seems you could do this using only 1 ev_io. I see you want to get what event got triggered so you use two separate ev_io with its own different events registered. Then you read there events from the ev_io in the callback. But the callback has an argument passed which is what events got triggered.

So instead you could have 1 ev_io and use EV_READ | EV_WRITE. If I'm not making too quick assumptions.

**Comment by alexhultman** [comment]
Whoops you already read the event from the callback. Well I've been up for \<too many\> hours.

**Comment by lws-team** [comment]
I think generally if Andrew recognizes it, it's not 'questionable' for libev.  It might not be convenient for libuv.

If there's something we can understand is good to do that keeps libev in good shape and makes libuv more convenient, we should certainly consider it.

Otherwise if libuv significantly diverges from libev it might be simpler to think about cut and paste libev.c and abstract any libev-isms so you can choose either in lws.  At least the plumbing / cmake / options I can help a bit with then, and you don't have to deal with a shim library.

**Comment by alexhultman** [comment]
Yes the larger goal would probably be to add native libuv support. But I'm really close to getting this up and looking at the code it seems you could in fact change it to use 1 ev_io with EV_READ | EV_WRITE.

**Comment by lws-team** [comment]
For your purpose of making it work today you can just hack that into the library.  And if it's necessary for libev function, it'll at least be useful to see a working diff.

**Comment by alexhultman** [comment]
Yes I'll do that. It worked much better and I was able to send messages. But yeah I'll check if this is correct.

**Comment by alexhultman** [comment]
Okay, thanks for the clarifications. I will take a look at this.

**Comment by alexhultman** [comment]
@andrew-canaday Okay I see the difference now. You are doing the only possible solution.

In libev you set what events you are waiting for at *init*, while you set these events at *start* in uv.
