### ISSUE TITLE
lws_parse_uri stripping / from path parameter

### ISSUE THREAD

**Issue by dericpr** [warmcat/libwebsockets#414]
The lws_parse_uri function is stripping the / from the path parameter which prevents my websocket from connecting as the path is incorrect resulting in a 400 Bad Request error

**Comment by lws-team** [comment]
lws_parse_uri is designed to work that way, but yoy're right the example code using it does not take care about it.  I pushed a patch that corrects the usage.

**Comment by dericpr** [comment]
Thanks!
