### ISSUE TITLE
Failure with a long text file

### ISSUE THREAD

**Issue by mkschreder** [warmcat/libwebsockets#417]
I have a 3.3Mb js file that I'm trying to serve using the built in web server. But sometimes (not always) the connection is randomly closed when file is only 53% transfered. I have reproduced this with wget and it happens actually quite often, but not always. 

Are you familiar with this problem? Could it be that libwebsockets somehow prematurely closes the connection before file transfer has completed?

**Comment by lws-team** [comment]
Is it maybe timeout?  If your serving will take a long time, you need to reset the timeout as you send something (this is very inexpensive, basically sets an int)

```
LWS_VISIBLE LWS_EXTERN void
lws_set_timeout(struct lws *wsi, enum pending_timeout reason, int secs);
```

**Comment by mkschreder** [comment]
Andy, my poblem seems to have been "pipe choked" so I had to check that in
my code and not return 1 from the callack. I think it is too much detail to
handle in the user code though. I think such case would be better handled
internally by the library.

**Comment by lws-team** [comment]
The user code has to figure out what it wants to send, and how much, there's not really any choice about that.

The library provides the callback when you can send more.

As an optimization you can keep the pipe stuffed when you service it, not merely send 'something' but send as much as you can until the pipe would block; the library provides an api for knowing that too.

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-http.c#L324-L370
