### ISSUE TITLE
Crash if browsing if SSL is on

### ISSUE THREAD

**Issue by 00P** [warmcat/libwebsockets#418]
I to all,
a crash occours if:
1 ) setting on SSL;
2) open IE on https://127.0.0.1:7681/
3) continue to browse on certificate alert;
4) probably test-server will crash at parsers.c line 68.

**Comment by lws-team** [comment]
This is a dupe of #416 and the temporary workaround there will hide it for now.

I left #416 open to track the larger fix needed so will close this.
