### ISSUE TITLE
make libwebsockets_rpm is broken 

### ISSUE THREAD

**Issue by ezerbib** [warmcat/libwebsockets#419]
make libwebsockets_rpm is broken 
....

> Requires: /usr/bin/pkg-config
> Processing files: libwebsockets-debuginfo-1.6.0-1.fc21.x86_64
> Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/ezerbib/work/libwebsockets/libwebsockets/build/RPM/tmp
> error: Installed (but unpackaged) file(s) found:
>    /usr/bin/libwebsockets-test-fuzxy
> 
> 
> RPM build errors:
>     Installed (but unpackaged) file(s) found:
>    /usr/bin/libwebsockets-test-fuzxy
> CMakeFiles/libwebsockets_rpm.dir/build.make:49: recipe for target 'CMakeFiles/libwebsockets_rpm' failed
> make[3]: *** [CMakeFiles/libwebsockets_rpm] Error 1
> CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/libwebsockets_rpm.dir/all' failed
> make[2]: *** [CMakeFiles/libwebsockets_rpm.dir/all] Error 2
> CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/libwebsockets_rpm.dir/rule' failed
> make[1]: *** [CMakeFiles/libwebsockets_rpm.dir/rule] Error 2
> Makefile:184: recipe for target 'libwebsockets_rpm' failed
> make: *** [libwebsockets_rpm] Error 2
> 

need to add this line
`/usr/bin/libwebsockets-test-fuzxy`
 in %files section of the RPM/SPECS/libwebsockets.spec

**Comment by lws-team** [comment]
Thanks it's pushed.

**Comment by ezerbib** [comment]
thanks to you !!!
 for supporting the bugs
