### ISSUE TITLE
application crash when calling lws_client_connect_via_info(&i) after a keep alive disconnect

### ISSUE THREAD

**Issue by dericpr** [warmcat/libwebsockets#426]
I'm working on an application that can switch network connections on a somewhat frequent basis, to detect this I have setup my connection using keep-alives and while it seems to work most of the time, the reconnection following the keep-alive firing often results in the application encountering a sigsegv.  The reconnection occurs in my main while loop and is identical to the initial connection
`
 while (!force_exit) {
        // open the connection
        if (!wsi) {
                wsi = lws_client_connect_via_info(&i);
                if ( !wsi ) {
                    // be a nice process and wait a bit before retrying
                    sleep(5);
                }
        }   
         lws_service(context,500);
}
`
I've instrumented this loop and the crash happens at the lws_client_connect_via_info call.  Short of instrumenting the lws_client_connect_via_info loop can you think of any reason for this?  I'm using a 

`struct lws_client_connect_info i;` 

global to keep track of the connect info and I use the following code to fill in the info struct.

`
if ( lws_parse_uri(argv[optind], &prot, &i.address, &i.port, &i.path)) {
        fprintf(stderr, "Can't parse %s\n", argv[optind]);
}
    i.context = context;
    i.ssl_connection = use_ssl;
    i.host = i.address;
    i.origin = i.address;
    i.ietf_version_or_minus_one = -1;
    i.client_exts = exts;
    i.protocol = protocols[0].name;
`

path here is a value I'm passing in on the command-line due to slash from the parse_uri function you resolved earlier with an improved client example and use_ssl is set to 2 for a self-signed cert.

**Comment by lws-team** [comment]
Nothing in the info struct itself needs to stick around after trying to connect with it.

The code in your loop is a bit wrong because after the connect call, unless something really basic is wrong he will always assign the wsi and leave the rest of the connect steps to when he gets serviced.

So if he's NULL **after** service you might wait 5s.

In the test app the CLOSE callback sets the global wsi NULL is that what we're doing here?

**Comment by lws-team** [comment]
... and if the test client can also fail the same way, can you letme know how to reproduce?

**Comment by lws-team** [comment]
With the segfault, gdb backtrace might also give us a clue...

**Comment by lws-team** [comment]
Welp, please reopen if you can give us more info or way to reproduce on test client.

**Comment by dericpr** [comment]
Hi Andy I'll do some more testing today and let you know if I find anything.  I'm going to test against the latest 1.7 release.

Thanks.
