### ISSUE TITLE
Websocket connection issue

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#427]
Hi,
 I am using libwebsockets 1.6.3 Library,When ever my client connecting to webserver Am getting a callback of LWS_CALLBACK_WSI_DESTROY. For libwebsockets 1.6.0 It works fine.

**Comment by lws-team** [comment]
Can you show us as much logs as possible?  Equivalent of -d65535 on the test client.

You need to build in DEBUG mode

cmake .. -DCMAKE_BUILD_TYPE=DEBUG

to get more detailed logs than lwsl_notice() to appear..

**Comment by Arun19921991** [comment]
[1454905697:7199] NOTICE: lws_context_destroy is getting after the callback of LWS_CALLBACK_WSI_DESTROY

**Comment by Arun19921991** [comment]
And i have one more doubt, If i want to close the connection, is it necessary to request for a callback?.if that callback is not available i cant close the connection.

**Comment by lws-team** [comment]
1) There's not enough info coming to understand your problem... that's why I am asking for full logs.

2) destroy the wsi (an individual connection) is unrelated to destroy the context (the whole lws environment in your app)

3) Yes you should only close the connection from inside the callback, by returning nonzero.

However if you're shutting down, you don't need to take care about it, you can just exit the event loop and destroy the context, everything will get closed properly.

4) If in doubt, follow exactly the code in the test client

**Comment by Arun19921991** [comment]
Sir,
1)  From wireshark i observed that The client only closing the connection by sending FIN_ACK
2)  I am using SSL support
3)  Is there any webserver library version dependency in Websocket client connection?
4) And another difference is am not using the mirror protocol,only dump_increment.

static struct lws_protocols protocols[] =
{

	{
		"dumb-increment-protocol,fake-nonexistant-protocol",
		callback_dumb_increment,
		0,
		TUNNEL_CHANNEL_MAX_SUPPORTED_SIZE,
	},
	{ NULL, NULL, 0, 0 } /* end */
};

**Comment by lws-team** [comment]
If you use the lws test client as it is, does it make the same problem?

**Comment by Arun19921991** [comment]
Yes..When i connect through test-client code using my ssl certificates it shows the same error

**Comment by Arun19921991** [comment]
The code test-client is not using the LWS_CALLBACK_WSI_DESTROY callback,But in wireshark i found the same log.

**Comment by lws-team** [comment]
I just built the v1.6.3 test server and test client, and ran them

$ libwebsockets-test-server --ssl

$ libwebsockets-test-client localhost --ssl

they work fine.

Is that the same for you?

**Comment by Arun19921991** [comment]
Ya but the server is different

**Comment by lws-team** [comment]
I understand you're trying to do something else.

I just want to confirm it works "out of the box" the same with just lws test apps.

If that does work for you, please send the logs I asked for in comment 2.

If not, well, we need to find a way I can reproduce the problem (assuming it's Linux).

**Comment by Arun19921991** [comment]
Yes it is linux.I will get you more logs

**Comment by Arun19921991** [comment]
If server using different websocket library will it work?

**Comment by lws-team** [comment]
Yes if the server speaks standard websockets, everything should work with everything else without being from the same vendor.

You have to have something server-side that is willing to speak the same ws protocol, like "dumb increment" or whatever, how you do that depends on your ws server.  If the server does not know how to use the protocol you want, it'll reject the connection.

I wanted to know if our stuff worked with its own test apps as a sanity test for your build and platform.  If that works, it means the problem is somewhere else.

**Comment by Arun19921991** [comment]
Yes..The problem is only with my webserver,But when i use 1.6.0 version everything works fine.Is there any version change happened in the 1.6.3 library?.

Did u try with SSL connection?

**Comment by lws-team** [comment]
Yes as I wrote above, I used --ssl to test it using the test apps.

Reviewing the diff between v1.6 and v1.6.3 one of the fixes was changing the flow to interpret what the server sends back

```
                /* is this websocket protocol or normal http 1.0? */

-               if (!lws_hdr_total_length(wsi, WSI_TOKEN_UPGRADE) ||
-                   !lws_hdr_total_length(wsi, WSI_TOKEN_CONNECTION)) {
+               if (lws_hdr_total_length(wsi, WSI_TOKEN_UPGRADE)) {
+                       if (!strcasecmp(lws_hdr_simple_ptr(wsi, WSI_TOKEN_UPGRADE),
+                                       "websocket")) {
+                               lwsl_info("Upgrade to ws\n");
+                               goto upgrade_ws;
+                       }
```

You might want to capture with wireshark or whatever exactly what your server is sending at the http stage (before it upgrades to ws)

**Comment by Arun19921991** [comment]
Ya Now it is working..I have changed the AWAITING_TIMEOUT as 60.Previously it was 5.
Anyway thank you for your help.

**Comment by lws-team** [comment]
lol OK glad it got solved.

**Comment by Arun19921991** [comment]
I suggest we can configure the AWAITING_TIMEOUT from user level

**Comment by lws-team** [comment]
Yeah.... it's 20s in master.  But maybe the default timeout should be settable.

**Comment by lws-team** [comment]
master branch has the user code-settable timeouts now

https://github.com/warmcat/libwebsockets/commit/1c41a158491497cb32428bbb38e9ee830fd2c4d3

**Comment by Arun19921991** [comment]
Okay.So that is not Released r8?

**Comment by Arun19921991** [comment]
Now i will go with 1.6.3 version and Will update when 1.7 release happens
