### ISSUE TITLE
assert() failure in lws_poll_listen_fd (lws-plat-win.c)

### ISSUE THREAD

**Issue by rdeg** [warmcat/libwebsockets#430]
Hi,

I wrote the prototype of my own server starting from test-server.c and a static version of libwebsockets, build with minimal support for the Websocket server role (no client, no ssl, no extension, etc.). This server manages a single protocol used to communicate with its dedicated client running on a browser.
The whole stuff runs under Windows.

Actually, once websockets handshaking has been done, the server **sends** requests to the client at its own rythme and expects responses in return.

My problem is that the assert() in line:

       assert(fd->events == LWS_POLLIN);

in lws_poll_listen_fd() systematically fires after the handshaking.
As in my case fd->events is (LWS_POLLIN | LWS_POLLOUT), I changed it to:

	assert((fd->events & LWS_POLLIN) == LWS_POLLIN);

and it did the job.
However, I wonder whether it is a flaw in lws-plat-win.c or if I did something wrong or illegal.

Any help will be appreciated.

Remi

**Comment by lws-team** [comment]
Thanks... it's just a bug I think... I pushed it on master + v1.7-stable.
