### ISSUE TITLE
libwebsockets-1.7.1 fails to build with libressl

### ISSUE THREAD

**Issue by Gottox** [warmcat/libwebsockets#435]
build output:

https://travis-ci.org/Gottox/void-packages/jobs/110659359#L759

System:

* VoidLinux
* linux-4.4.2_1 
* libressl-2.2.6

**Comment by lws-team** [comment]
build_cert_chain() looked like it would be good, but only later openssl supports it hence the protection by SSL lib version.  LibreSSL has moved to bigger version numbers and still doesn't have it.

Since everything is working without it, I just removed the code on master + v1.7-stable.
