### ISSUE TITLE
question: use of mTCP to (further) improve performance?

### ISSUE THREAD

**Issue by reuzel** [warmcat/libwebsockets#450]
Hi,

Just out of curiosity, would there be any value in using user-space TCP libraries to further increase the scalability and performance of the libwebsockets library? If you look at the links below, such libraries may increase scalability quite a lot...

Kind regards and keep up the good work!
Joost

  * http://highscalability.com/blog/2013/5/13/the-secret-to-10-million-concurrent-connections-the-kernel-i.html
  * http://shader.kaist.edu/mtcp/
  * https://github.com/eunyoung14/mtcp
  * http://dpdk.org/

**Comment by lws-team** [comment]
I don't mind cooperating with someone who is motivated to do this port this to make it happen neatly inside lws, as recently happened with libuv support (and windows, mac support and many other things before).  I don't personally have a use for it.

**Comment by lws-team** [comment]
If a hero rises who's interested in doing this, please reopen.
