### ISSUE TITLE
Simultaneous WS:// and WSS:// connections

### ISSUE THREAD

**Issue by bdkjones** [warmcat/libwebsockets#451]
I'd like to know if it's possible to configure a single instance of libwebsockets (acting as a server) to accept BOTH secure and non-secure connections from clients.

I understand that, in general, this isn't something most folks would want to do—a server should either be secure or not secure. But I use libwebsockets as part of an app that hosts a local development server for folks building websites. The websocket lets me refresh browsers. I'd like my users to be able to connect via TLS and non-TLS without having to run two different instances of libwebsockets. 

I don't think this option currently exists, so I'm requesting that it be added. Thank you.

**Comment by bdkjones** [comment]
Whelp, never mind; I found `LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT` in the implementation. I'm going to have to stop opening issues on Libwebsockets.

**Comment by lws-team** [comment]
It does exist already, OR the flag

```
LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT
```

... on to info.options before creating the context../

...ah beat me to it
