### ISSUE TITLE
Callback on writable is not coming

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#454]
Hi,

Not getting **LWS_CALLBACK_CLIENT_WRITEABLE** when i request for it,I had this issue for the older version of library,But am currently using 1.7 version.When i checked using netstat there is no connection existing.

**Comment by lws-team** [comment]
If there is no connection, that connection will never be writeable.

First turn on the logging.

Check the structure of your code against the test client.  In particular notice when ypu ask to make the connection he may return ok, but the network connection will be made later, during service.

**Comment by Arun19921991** [comment]
I can connect to websocket server And data is also transmitted and received,I am getting this problem after some time.And full LOG is enabled.There is no print is coming up during this problem

**Comment by Arun19921991** [comment]
Are we using Select or poll in the backhand?

**Comment by Arun19921991** [comment]
And will the lws_service return any value ?
In previous library there is one checking for that,But in test client ( 1.7 version) I didnt find any checking.

**Comment by lws-team** [comment]
You should be getting a CLOSE callback if the connection goes down.

The default event loop for unix is poll().

The logic of the test client changed, he continuously tries to reacquire the connection, with rate-limiting, and he only ends the service loop on ^C.  You might want to think about something similar, becsuse the server or an intermediary may close your connection at any time.

**Comment by Arun19921991** [comment]
Ya,
1)When server clses the connection The client will reconnect.But i didnt get the CLOSE Callback.
2) Is there any way to change the event loop for SELECT

**Comment by lws-team** [comment]
Test client gets it here.  Tested by using libwebsockets-test-client -l localhost then kill test test server and look at client logs.

What's the point of using select()?

**Comment by Arun19921991** [comment]
Some times it is working,When the server close the connection, client will automatically starts to connect,After the data transfer i will close the connection,For that i need to call 'callbackonwritable' that time i am not getting the callback,If i get the callback i will close it by returning -1.

**Comment by lws-team** [comment]
I can't debug your code... if the test apps act badly, that's always interesting.

**Comment by Arun19921991** [comment]
I dont know may be mine is week connection to the server

**Comment by lws-team** [comment]
If you can patch the test client to show the problem, or find another way I can see it, please reopen I will try to reproduce and fix.
