### ISSUE TITLE
ev_loop_foreign not set to 1

### ISSUE THREAD

**Issue by gaby64** [warmcat/libwebsockets#455]
`LWS_VISIBLE int`
`lws_ev_initloop(struct lws_context *context, struct ev_loop *loop, int tsi)`
`{`
`...`
`if (!loop)`
`		loop = ev_loop_new(0);`
`	else`
`		context->pt[tsi].ev_loop_foreign = 1;`

**Comment by lws-team** [comment]
Thanks, it's pushed on both master and v1.7-stable.  I took care of the destroy part of that change on libev and libuv but only converted libuv to set the flag.... thanks for the clear fix.
