### ISSUE TITLE
lws_get_peer_name returns wrong name

### ISSUE THREAD

**Issue by angelfromhell** [warmcat/libwebsockets#456]
in the function lws_get_peer_name the wrong ip address is returned in some cases

Situation:
in /etc/Hosts one defines two Hosts
127.0.0.1   main
127.0.0.2   other

when one opens a client Connection with name "other" the lws_get_peer Name Returns 127.0.0.1 on the host side although the socket was opened with 127.0.0.2

i think when using socket_addr_in instead of get_peer_address within the function should solve the issue

**Comment by lws-team** [comment]
Sorry it's a bit confusing.... so you run like

$ myclient other

which is same as

$ myclient 127.0.0.2

At the server who accepts the connection, who listens on 127.0.0.2, he says that his peer ip is 127.0.0.1.

That could be correct from that description.  The guy running myclient may be going out on 127.0.0.1 to connect to 127.0.0.2.

**Comment by angelfromhell** [comment]
you are right, you arent doing a bind to the specified hostname for clients... then it is correct.. i was busy with another socket client which i binded to a second hostname , which is not done in the libwebsockets

**Comment by lws-team** [comment]
No, we bind client sockets to the interface given at context creation time in info.iface, if it's non-NULL.

If there's some problem with that, please reopen.
