### ISSUE TITLE
LWS_SSL_CAPABLE_ERROR: got some not quite descriptive errors

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#459]
Here's what I see in our logs:
```
lws_issue_raw: wsi 000001CA9ACC1260: LWS_SSL_CAPABLE_ERROR
lws_issue_raw: wsi 000001CA9AF775E0: LWS_SSL_CAPABLE_ERROR
lws_issue_raw: wsi 000001DECB997250: LWS_SSL_CAPABLE_ERROR
```
The message is very rare.
What does it mean? Is it possible to fix its cause?

Using version 1.6 (cc5dff9bb1147c85ecd7cc7850aa40fec29ecf59).

**Comment by lws-team** [comment]
You really should update from 1.4.... even v1.5-stable which is before the api normalization changes.

**Comment by emptyVoid** [comment]
Oh, actually the version is 1.6 (sorry for the confusion).
And it looks like ```lwsl_err``` invocation got removed from ```lws_issue_raw``` at some point after commit cc5dff9bb1147c85ecd7cc7850aa40fec29ecf59.
I suppose it is caused by some send failure and now is treated as a noncritical error.

**Comment by lws-team** [comment]
Yes... tbh if I am working in an area I pepper it with lwsl_err() to see what's going on sequence-wise.  Sometimes if they don't normally fire, they get left in accidentally...
