### ISSUE TITLE
Clang scan-build warnings

### ISSUE THREAD

**Issue by rikvdh** [warmcat/libwebsockets#461]
Hi,

We use Clang's scan-build (version 3.7) in our application for static analysis. It found a few problems in your library:

* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/context.c#L383

  `Value stored to 'n' is never read`
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/context.c#L386

  `Value stored to 'n' is never read`
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/service.c#L145

  `Value stored to 'm' is never read`
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/test-server/fuzxy.c#L508

  `Value stored to 'port' is never read`
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/handshake.c#L158

  `Value stored to 'len' is never read`
  (I think this one is invalid)
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/lib/base64-decode.c#L133

  `The left operand of '>>' is a garbage value`
* https://github.com/warmcat/libwebsockets/blob/v1.7-stable/test-server/test-server-pthreads.c#L364

  `Function call argument is an uninitialized value`

I can provide more information when necessary.

Perhaps it is a good idea to include Clang's scan-build into Travis.

Kind regards,

Rik

**Comment by lws-team** [comment]
Thanks.  Well the more 'compiler warnings' the merrier, if they have meaning.  We already use coverity before releases.

The first two are no problem, we are doing destroy callbacks and the retval has no use (the whole thing is anyway going down).

Third one is not used by any existing extension, but yes he should have an error path.  I patched it.

Fourth one is in a fuzzing tool, it's not a part of the library or example apps, and it's harmless... nothing uses the set port yet.

Fifth one is read in the while() condition, it's not a valid complaint.

Sixth one it seems it doesn't apprehend the code's restriction it will get valid base64 string of len >=4, which makes the conditional setting of quad[] on one path moot.

Seventh one is telling us if pthread_create() fails, we still run the thread cleanup processing anyway... I patched that too.

So unless I missed the point only 2/7 have any real problem behind them...   I pushed a patch on master and v1.7-stable.
