### ISSUE TITLE
Incorrect comparison of unsigned int to 0

### ISSUE THREAD

**Issue by kimtopley** [warmcat/libwebsockets#466]
Line 289/290 of server.c look like this:

		if (n < 0)
			goto bail_nuke_ah;

The problem is that n is declared as unsigned int, resulting in the following error with clang on OS X:

server.c:289:9: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
                if (n < 0)
                    ~ ^ ~
1 error generated.

Simply dropping the "unsigned" in the declaration of "n" makes the compiler happy. Not sure if it's the correct fix.

**Comment by lws-team** [comment]
Thanks.  I cleared out all the appveyor warnings and fixed an ssl reference not being ptotected by ssl being enabled at cmake, this should be solved now.

**Comment by kimtopley** [comment]
Thanks!

Kim
