### ISSUE TITLE
lws_b64_decode_string does not correctly decode some strings

### ISSUE THREAD

**Issue by steven6677** [warmcat/libwebsockets#467]
I believe there is a problem with the implementation of lws_b64_decode_string.  Specifically, when there are no padding bytes, that last byte is not properly decoded.

For example,  the following:
`        const char *input = "123456";`
`        const size_t ENCODE_BUF_SIZE = 20;`
`        char encode_buf[ENCODE_BUF_SIZE];`
`        printf("input = %s\n", input);`
`        int ret = lws_b64_encode_string(input, strlen(input), encode_buf, ENCODE_BUF_SIZE);`
`        printf("ret = %d - encode = %s\n", ret, encode_buf);`
`        const size_t DECODE_BUF_SIZE = 20;`
`        char decode_buf[DECODE_BUF_SIZE];`
`        ret = lws_b64_decode_string(encode_buf, decode_buf, DECODE_BUF_SIZE);`
`        printf("ret = %d - decode = %s\n", ret, decode_buf);`

Results in:
`input = 123456`
`ret = 8 - encode = MTIzNDU2`
`ret = 5 - decode = 12345`

Based on comments at the top of the file, it appears that the code is based on [http://base64.sourceforge.net/b64.c](url).  I believe that when the code was ported to lws, some errors were inadvertently introduced.

I think the change from supporting files to buffers did not take into account the semantics correctly.  Specifically, in the original, `feof` will be set when trying to read the byte after the last byte of the file.  In the lws code, the `in` will be NULL while still processing the last byte (because the pointer is incremented when reading it).  As a result, the code takes the incorrect path at `if (*in)` when processing the last byte.  Note that if the last byte is padding, this is not a problem (so for any strings with padding, the code will decode to the correct string).

Also, it the code:
`				if (*in) {`
`					len++;`
`					if (v)`
`						quad[i] = v - 1;`
`				} else`
`					quad[i] = 0;`

in lws is inside the `while` loop, but in the reference code, it is outside.  As a result, lws will handle decodes of invalid base64 strings in a manner different than the reference.

Thanks.

**Comment by lws-team** [comment]
Yes, you're right it was broken for strings like your example.

For its only usage in lws, because of the ws key plaintext mandatory fixed size, and restricted character set, it never meets that problem and so always works as it is.

Since we export the api though for general use it's a real breakage.  I pushed what should be a fix on master and v1.7-stable.

**Comment by steven6677** [comment]
Thanks.  I was using the function to decode data received over the ws which is why I noticed the issue.

Thank you for you quick response.
