### ISSUE TITLE
SSL callback and ecdh init when SSL not requested

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#468]
Hi,

I've noticed in my applications that since libwebsockets version 1.7, when not using SSL (by setting cert and key paths in `info` to `NULL`, and not setting any SSL flags in `options`) two things happen differently than before:

1. the callback `OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS` is now fired. It's useful when using SSL and client certs. But I can't see a case when this callback in particular might be useful if SSL disabled (cert path NULL). It's safe to ignore though.

2. the ECDH init functions are called, resulting in valgrind's uninitialised memory warnings, and in some cases "the impossible happened" crashes (default-config OpenSSL builds are not valgrind-clean).

Regarding ECDH init, I found a related commit which moves some init code outside an if-clause and so It may be relevant https://github.com/warmcat/libwebsockets/commit/78773b6da09841896694a9b599199b60c0764119#diff-0127057f7ace26a81f87374e43782fecR271

Looking more closely at lib/ssl.c I saw that many more SSL inits are done regardless of whether SSL was requested or not. I'm not sure, but I presume some OpenSSL code may be used even with SSL turned off, e.g. for random sec-websocket-key or similar.

I know all of these are avoided by disabling SSL at build tme, but it may be worth checking ssl.c OpenSSL init to initialise only the parts which are configured to be used at runtime.

**Comment by lws-team** [comment]
Yes it's as you say.

But client connections are supported in the same context as the listening server.  On master, that's a thing now both with individual client connections started in user code and with "semi-automatic" proxy passthru.  In those cases, the ssl status for the client connections is not required to be related to the listening socket ssl status.  Ie, he may have an http server which has https client connections also running in the same context.

I also plan to expand the listening socket for the context to support vhosts shortly, and they can be a mixture of ssl or not; I haven't completely thought that implementation through yet but I guess it means multiple listening sockets in one context becomes possible too, some with and some without an SSL_CTX associated.

What it boils down to I think is we may need another _OPTION_ flag that says whether to do global SSL init or not (all existing _OPTION_ flags that imply it can have that flag OR'd on at their definition) and some other init like ecdh would become per-vhost.   But with this new context-creation flag, it'd be enforced that all SSL init was dependent on it.

I plan to start on the vhosts changes in the next day or two, so for these reasons it will need to get done as part of that (I'll see what's involved to also support on v1.7-stable during that).  So I will leave this open until that's done.

**Comment by lws-team** [comment]
This is pushed on master (only) as described, it means for client-only apps where there is no sign of SSL use in the context creation struct, you now need to tell it to do the ssl init in the context because you will use it afterwards

```
	if (use_ssl)
		info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
```

without it, it prints a notice during context creation that the SSL init is not being called

```
lwsts[14463]:  Compiled with OpenSSL support
lwsts[14463]:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
lwsts[14463]:  Listening on port 7681
```

**Comment by interfaith** [comment]
how do avoid this error ?
[2016/07/14 19:28:33:4455] NOTICE: Initial logging level 7
[2016/07/14 19:28:33:4455] NOTICE: Libwebsockets version: 2.0.0  ubuntu-v2.0.0-113-gee7819b
[2016/07/14 19:28:33:4455] NOTICE: IPV6 not compiled in
[2016/07/14 19:28:33:4455] NOTICE: libev support not compiled in
[2016/07/14 19:28:33:4455] NOTICE: libuv support not compiled in
[2016/07/14 19:28:33:4455] NOTICE:  Threads: 1 each 1024 fds
[2016/07/14 19:28:33:4455] NOTICE:  mem: platform fd map:  8192 bytes
[2016/07/14 19:28:33:4455] NOTICE:  Compiled with OpenSSL support
[2016/07/14 19:28:33:4455] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2016/07/14 19:28:33:4456] NOTICE: Creating Vhost 'default' port 8989, 2 protocols, IPv6 off

**Comment by lws-team** [comment]
When you are creating the lws context, if you want ssl make sure `info.options` has LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT or-ed on to it, eg

```
info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
```

**Comment by minggo** [comment]
> info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

Will crash when create lws context, am i miss something? I used v2.10 version and compile with ssl enabled.

**Comment by lws-team** [comment]
What does it mean, 'crash'?  How about a backtrace?

Did you provide it with certs?

Does the lws test server crash when you run `libwebsockets-test-server --ssl`?

**Comment by minggo** [comment]
I haven't run test tests, i just built libwebsockets and use it in [cocos2d-x](https://github.com/cocos2d/cocos2d-x). 

I found if i create more than one lws instance with `info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`, then it will crash. But i need more than on lws instance.

**Comment by minggo** [comment]
I haven't provide with certs. The backtrace is
```
NOTICE: Libwebsockets version: 2.1.0 minggo@A03101308207.local-v3.4-131-gb8e116d

NOTICE: IPV6 compiled in and enabled

NOTICE: Initial logging level 967

NOTICE: Initial logging level 967

NOTICE: libev support not compiled in

NOTICE: Libwebsockets version: 2.1.0 minggo@A03101308207.local-v3.4-131-gb8e116d

NOTICE: Libwebsockets version: 2.1.0 minggo@A03101308207.local-v3.4-131-gb8e116d

NOTICE: libuv support not compiled in

NOTICE: IPV6 compiled in and enabled

NOTICE: IPV6 compiled in and enabled

NOTICE: libev support not compiled in

NOTICE: libev support not compiled in

NOTICE: libuv support not compiled in

NOTICE: libuv support not compiled in

NOTICE:  Threads: 1 each 256 fds

NOTICE:  Threads: 1 each 256 fds

NOTICE:  Threads: 1 each 256 fds

NOTICE:  mem: platform fd map:  2048 bytes

NOTICE:  mem: platform fd map:  2048 bytes

NOTICE:  mem: platform fd map:  2048 bytes

NOTICE:  Compiled with OpenSSL support

NOTICE:  Compiled with OpenSSL support

NOTICE:  Compiled with OpenSSL support

cpp-tests iOS(57512,0x700008664000) malloc: *** error for object 0x6080001f7d00: Freeing unallocated pointer
*** set a breakpoint in malloc_error_break to debug
```

I invoke `lws_create_context` three times with `info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`.

**Comment by lws-team** [comment]
It seems you're using it in client mode.

 - you should only use one context.

 - that's not a backtrace.

 - lws is not threadsafe.

 - openssl < 1.2 (? or so... I forget when they fixed it) cannot be initialized safely more than once in a process.  using one context will help with that.

**Comment by minggo** [comment]
Yep, it is in client mode and there is not problem if no invoking `info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT` that create more than one context. So did you mean it is caused by openssl? The openssl version is 1.0.2g.

`Websocket` of cocos2d-x need to crate more than one lws context because `Websocket` can have more than one instances.

**Comment by lws-team** [comment]
You can have as many client connections (client plus server mixed as well) inside one context as you want.

Openssl will blow up on destroy if you init it more than once in the process.

If you get a proper backtrace you can get an idea of the cause.

What you mean is 'current implementation thinks it wants multiple contexts'.  But you can do everything in one, also solving your ssl problem.

If you are desperate you can try hack in a context init flag that stops lws calling the openssl global init.  Or use 1.2 openssl, which added alternate init / destroy apis to fix their problem.

**Comment by minggo** [comment]
thanks, i will try and give feedback here

**Comment by lws-team** [comment]
okay, but just noting without a backtrace, nothing actually links your symptom to this cause.  LWS is simply not threadsafe, although isolating one thread to one context may hide most or all of the problems.

**Comment by minggo** [comment]
cocos2d-x uses lws as prebuilt lib, so there is not backtrace. 

Are you sure openssl has 1.2.0? I found [here](https://github.com/openssl/openssl/releases), there is 1.1.0 and 2.0.

**Comment by lws-team** [comment]
There shouldn't be anything inherent about a prebuilt lib not having debug info sections.  It's simply built without them by the sound of it.  Anyway it just means neither you nor I can know what's wrong.

You're right openssl 1.2 is just my happy dream.  It tells here

https://wiki.openssl.org/index.php/Library_Initialization

1.1.x was when the thread support / init was rewritten in Openssl.

**Comment by minggo** [comment]
Ok, i will try to use source code to have the backtrace, but i think you can create a test case easily in lws to create more than on instance with `info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT`.

**Comment by lws-team** [comment]
LWS just supports one context in the process.

We already know openssl <1.1 (which is what almost everyone uses) blows up with multiple contexts, whether lws or something else inits it multiple times.  That's not an lws issue.

The actual answer here is use one lws context and one openssl init.

But my point is, something totally unrelated to openssl could cause the memory problem.  We have no backtrace and no evidence.  So we should keep alive the idea it may not go away with newer openssl.

**Comment by minggo** [comment]
Ok, i am not familiar with lws, and i am not sure if it is possible to use one context to connect more than one website at the same time, and every website has its own call back(such as onOpen, onClose and so on).

**Comment by lws-team** [comment]
Yes... the context is like a container for all your other lws activities.

If you look at test-client.c, he already demonstrates multiple idependent client wsi usage including ratelimited autoreconnect.

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c

each client connection has his own wsi.  The connection calls his protocol's callback with the wsi as an argument.

**Comment by minggo** [comment]
Thanks, i will take a look.
