### ISSUE TITLE
libuv initloop signal handling

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#469]
Hi,

in the libwebsockets-libuv code, there is a function `lws_uv_sigint_cfg` which should allow disabling signal handler registration (via `use_uv_sigint` parameter) as well as custom signal handler parameter. I tried those and they didn't work.

Digging through lib/libuv.c i spotted a couple related problems with libuv signal handling code:

1. the `lws_uv_initloop` doesn't check the `use_ev_sigint` (= `use_uv_sigint`) flag as the libev counterpart does, before setting signal handlers. This impacts the use of libwebsockets in existing/foreign loop.

2. the `lws_uv_initloop` function takes a callback parameter itself, and does not use the one set by `lws_uv_sigint_cfg`, making the latter function currently useless as far as I could tell. The callback parameter is of different type, is not needed and sigint_cfg should be used for that.

3. there is a typedef `lws_uv_signal_cb_t` which is used in above functions, but I don't see its purpose. First, it has a `int revents` parameter for which I don't see how it can be related to a signal like SIGINT. Second, it has parameters uv_loop_t and uv_signal_t. These can be collapsed into just uv_signal_t, since it is a handle, and has a public member pointing to its loop: http://docs.libuv.org/en/v1.x/handle.html#c.uv_handle_t.loop. The typedef then becomes identical to libuv's `uv_signal_cb` and is thus not of any use.

4. there is a function lws_uv_sigint_cb which is set as the default sigint action (probably meant to be used unless overridden by `lws_uv_sigint_cfg` function). It conforms to the typedef in the previous item, and just runs uv_stop on the loop. Most likely it should run lws_libuv_stop instead., but I'm not certain about this. If lws_libuv_stop is the right one, the lws_context should be passed as a user pointer (member named `data` in signal `uv_handle_t`) to it.

Aside from changing (in my opinion) broken behavior, the proposed fixes would break API:
- `lws_uv_initloop` loses the callback parameter (should be set via _cfg function)
- the typedef is changed to be plain `uv_signal_cb`, or removed in favor of it

On the other hand, the API can be maintained (keeping the function signatures and typedef):
- for the initloop function. ignore the parameter
- for the redundant loop argument in typedef: a libuv-compatible callback wrapper has to be made, and a context structure would have to be allocated for each signal handler (per-thread) which would just store two pointers: lws_context, and the wrapped callback. The wrapper would call the wrapped callback with redunntant parameters...
I think that this is too much to worry about just for keeping libuv API with errors.

I'll make a pull request soon.

**Comment by lws-team** [comment]
Thanks the PR is pushed.
