### ISSUE TITLE
Incorrect https://github.com/warmcat/libwebsockets/archive/v1.7.4.zip

### ISSUE THREAD

**Issue by joepschroen** [warmcat/libwebsockets#471]
It seems this archive does not contain 1.7.4.
More specific this version does not know about LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT which is a 1.7.4 feature.

**Comment by lws-team** [comment]
I think you got a wrong idea and worked back from that.

The URL you gave is indeed v1.7.4, if you look in CMakeLists.txt it says so.

However that new feature you mention is only on master...

**Comment by joepschroen** [comment]
You're right, sorry for the confusion!
