### ISSUE TITLE
SIGPIPE

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#474]
Whenever my websserver stops, am getting connection closed callback and a signal of SIGPIPE.
This thing happening only when my Server is forcefully stops.

**Comment by Arun19921991** [comment]
******Continuation**************This thing happening only when

**Comment by lws-team** [comment]
Does this happen on the test server?  IIRC SIGPIPE is set for ignore there.

You're using libev or libuv?

What does it mean 'forcefully stopped', ^C or so?

**Comment by Arun19921991** [comment]
1) I am using libwebsocket 1.7 version
2) It is a client code.
3) I didnt set libev or libuv in the cmake section.
4) Forcefully stopped means ( kill -9 pid)

**Comment by lws-team** [comment]
If I understood... you're the client, you get a SIGPIPE when your server dies.

I think it's OK, your connection has closed.

Assuming the signal is the problem why don't you just turn the signal off in your app

```
#include <signal.h>
signal(SIGHUP, SIG_IGN);
```

**Comment by Arun19921991** [comment]
It is a multi threaded application ,And i have put signal(SIGPIPE , SIG_IGN) in all threads.

**Comment by lws-team** [comment]
I think processes receive signals, not threads.

So how does the SIGPIPE make itself known to you?  (ie, why do we think a SIGPIPE is coming?)

**Comment by Arun19921991** [comment]
I have run the executable with gdb,So it shows the SIGPIPE

**Comment by lws-team** [comment]
Yeah but gdb is hooking the signal, I don't think that reflects reality.

For example you can ignore SIGINT (^C) successfully in you app, but under gdb, gdb will by default catch the ^C and halt.  You can tell gdb how to handle each signal, separately from what the process being debugged has for handlers, in this case

```
ha SIGPIPE nostop
```

And what happens if you run your app without gdb but with SIGPIPE set to SIG_IGN... he acts normally and does not terminate?

**Comment by Arun19921991** [comment]
Yes it is terminating,Let me try some other methods to ignore SIGPIPE.

**Comment by Arun19921991** [comment]
what is  IIRC SIGPIPEin test-server?
is it possible to use the same in my client code?

**Comment by Arun19921991** [comment]
I have seen the handling of SIGPIPE in lws_plat_unix.c.The older versions of library contains the SIGPIPE handling under create_context function,but now it is not there.

**Comment by lws-team** [comment]
IIRC = "If I Recall Correctly"

Take a look at man 3 sigaction, for another way to disable signals.

But you should try the test client + test server as I originally suggested first.

$ libwebsockets-test-server

In another window

$ libwebsockets-test-client localhost

And then in a third window

$ killall -9 libwebsockets-test-server

Here, the test client remains running (trying to reconnect to the server) with no fatal signal.

So we can tell if it's something about your app, or something about your system, by trying the same test your side.

**Comment by Arun19921991** [comment]
so my question is how this SIGPIPE got handled in test-client ?
are u using any kind of methods in test-client?

**Comment by lws-team** [comment]
It's exactly current master test-client.  But you also need to test it, not make assumptions there are differences in the code...

**Comment by Arun19921991** [comment]
I am using libwebsockets 1.7 version
When i commented the websocket-client it works fine.

**Comment by lws-team** [comment]
If I understood you also don't get the problem using the test client.

You have the source code for the test client... so I would try to align your code to just do what the test client does... somewhere between what it does now, and when it only does what the test client does, you should change something that makes it act the same.

**Comment by Arun19921991** [comment]
Let me compare my client with Master test-client code

**Comment by Arun19921991** [comment]
I didnt find any kind of SIGPIPE Handling in Master test client code,Only SIGINT.

**Comment by Arun19921991** [comment]
I didnd find any difference in Context filling,Connect structure filling,So the only difference is the library version.

**Comment by lws-team** [comment]
Library version is unrelated, I get the same result (no sigpipe) on the 1.7.4 test client, kill -9'ing the 1.7.4 test server.

**Comment by Arun19921991** [comment]
Try kill -13 pid

it will show sigpipe

**Comment by Arun19921991** [comment]
I tried in websocket client.

**Comment by lws-team** [comment]
Actually it doesn't here, firing a SIGPIPE at the server nor the client has any effect and both keep running.

**Comment by Arun19921991** [comment]
Sorry,One another library was running with my code,It is not handling the SIGPIPE.
Now run fine.
Thank you for your Sudden updates and help sir.

**Comment by lws-team** [comment]
Well... glad it's working.
