### ISSUE TITLE
Question: How to properly notify client of a WebSocket connection reject?

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#478]
I'm not sure how exactly connection upgrade works.
Currently I return ```-1``` on ```LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION``` if the URL path is wrong or the query arguments are invalid.
How do I notify client of a reject reason? Should I use the same technique as for common HTTP requests, e.g. via ```lws_return_http_status```?

**Comment by lws-team** [comment]
Yes at that time, the connection between the client and server is not upgraded and is still using HTTP semantics.

The client has asked to upgrade, but the callback occurs when the server identifies that's what is being asked for, but before he replies.

So if you want to reply anything more than hanging up, it would be in the form of an normal HTTP response like lws_return_http_status().

**Comment by emptyVoid** [comment]
Thank you!
