### ISSUE TITLE
libwebsockets behind reverse proxy - lws_callback_on_writable: failed to find socket

### ISSUE THREAD

**Issue by select-this** [warmcat/libwebsockets#479]
I'm attempting to use libwebsockets as an HTTP server with nginx as a reverse proxy in front of it, but for some reason it appears that the socket is closing prematurely and I can't seem to figure out why.

Interestingly, I also observed this behavior when using libwebsockets on its own when a certain iOS user agent attempted to get content (namely, Apple's CaptiveNetworkSupport WISPr agent - any other user agents seemed to be fine, which I find to be very bizarre), so I'm not sure if this is entirely related to being behind a reverse proxy or not, although with the reverse proxy in place it happens for all clients and all user agents.

In the nginx logs, I'm getting the following:

```
2016/03/31 09:53:08 [error] 6690#0: *1 upstream prematurely
closed connection while reading response header from upstream,
client: 127.0.0.1, server: , request: "GET /admin/ HTTP/1.1",
upstream: "https://127.0.0.1:8010/admin/", host: "localhost"
```

So it appears nginx is claiming that libwebsockets is closing the connection earlier than expected.

When libwebsockets logging is on, any attempts to call lws_callback_on_writable to start serving the content outputs the following error:

```
lws_callback_on_writable: failed to find socket 12
```

Here's a few more details about the libwebsockets environment:

```
OS: Ubuntu 14.04 LTS
Libwebsockets version: 1.7.0 d32bb05
IPV6 compiled in and enabled
libev support not compiled in
Compiled with OpenSSL support
Using SSL mode
HTTP2 / ALPN configured but not supported by OpenSSL 0x1000106f
Listening on port 8010
```

...and a sample of the nginx config, if it makes any difference:

```
upstream admin {
    server 127.0.0.1:8010;
    keepalive 64;
}

server {
    listen 443 ssl;
    ssl_certificate *********;
    ssl_certificate_key *********;
    ssl_protocols *********;
    ssl_ciphers *********;
    ssl_prefer_server_ciphers On;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate *********;
    server_name *********;
    location / {
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_bind $server_addr;
        proxy_pass https://admin;
    }
}

```

(Please ignore the *********, that's just me removing the sensitive information from the config)

I don't really know how to start debugging this or figuring out whether this is a user code issue or not, so any advice and / or guidance would be appreciated. I have used this configuration in conjunction with node.js before so I'm pretty sure the nginx config is okay.

Once again, any help would be appreciated!

**Comment by lws-team** [comment]
The best initial sanity check is swap in the test server.  Because that eliminates every other aspect about the user code.

If it still has the problem, I stand a chance of reproducing it.  If not, it's something specific to the user application code.

**Comment by select-this** [comment]
That's a good point, I hadn't thought of that. Using the test server, it indeed works as expected, so it seems I'm doing something wrong; though at this time I've no idea what since bar the CaptiveNetworkSupport and the reverse proxy, everything seems to work correctly.

I shall continue to examine the differences between the user code and the test server, since the user code is based on an older release of libwebsockets so my first port of call will be to make sure I'm not missing something that's now mandatory.

**Comment by select-this** [comment]
Right, I have a bit more info now: here's the breakdown of the connection's callbacks:

```
FILTER_HTTP_CONNECTION 
HTTP 
LOCK_POLL 
CHANGE_MODE_POLL_FD 
UNLOCK_POLL 
LOCK_POLL 
DEL_POLL_FD 
UNLOCK_POLL 
CLOSED_HTTP
```

Looks like something in the HTTP callback is causing the connection to close, so that's where I'll look. It seems 100% like a user code error now so I'll close this.
