### ISSUE TITLE
context->max_fds = getdtablesize() is not worked fine on Android OS.

### ISSUE THREAD

**Issue by GalenMa** [warmcat/libwebsockets#488]
In lws_create_context function, context->max_fds = getdtablesize().
When use libwebsockets on android os, max_fds is the sysconf (_SC_OPEN_MAX), 
but  _SC_OPEN_MAX is described as below:
OPEN_MAX - _SC_OPEN_MAX
              The maximum number of files that a process can have open at
              any time.  Must not be less than _POSIX_OPEN_MAX (20).

I think, the max fds is the maximum file descriptor number rather than the number of files. 
so, does it should use  getrlimit function with RLIMIT_NOFILE ?

**Comment by lws-team** [comment]
Please send a patch for how you should think it should be on Android, with something like #ifdef ANDROID or so around it, since it works as it is on Linux / Windows atm.

**Comment by GalenMa** [comment]
OK, Below is my code for android.

LWS_VISIBLE struct lws_context *
lws_create_context(struct lws_context_creation_info *info)
{
...
#ifndef LWS_NO_DAEMONIZE
	if (pid_daemon) {
		context->started_with_parent = pid_daemon;
		lwsl_notice(" Started with daemon pid %d\n", pid_daemon);
	}
#endif
`#if defined(__ANDROID__)
	struct rlimit rt;	
	int res = getrlimit ( RLIMIT_NOFILE,&rt);
	if (-1 == res){
		lwsl_err("Get RLIMIT_NOFILE failed!\n");
		return NULL;	
	}
	context->max_fds = rt.rlim_cur;
#else
	context->max_fds = getdtablesize();
#endif
...`

**Comment by lws-team** [comment]
Thanks, it's pushed on master + v1.7-stable.
