### ISSUE TITLE
SIGUSR2

### ISSUE THREAD

**Issue by aatukora** [warmcat/libwebsockets#499]
Hi Andy,

Quick question about your use of SIGUSR2 in the library.  I notice that lws_plat_context_early_init() registers a (empty) signal handler for this, but I can't see where or why this is actually used.  Is this behaviour that we no longer need?  I need to use SIGUSR2 in my application, and its signal handler is being overridden by lws.  If it's not needed any more, could it be removed or at least put inside an #ifdef or something?

Thanks!

**Comment by lws-team** [comment]
It's cruft from when we used to use it to break into poll() waits, I removed it on master + v1.7-stable.

**Comment by aatukora** [comment]
Thanks
