### ISSUE TITLE
create an instance server that accept request on 2 port

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#500]
I try to open a server with 2 listen port like this:

    struct libwebsocket_context* context = libwebsocket_create_context(&info);
    struct libwebsocket_context* context2 = libwebsocket_create_context(&info2);
    for (;;) {
        libwebsocket_service(context, 50);
        libwebsocket_service(context2, 50);
    }

    but dont work.

I use version 1.23 .

it is possible with the last version?

Thank you

Mario

**Comment by lws-team** [comment]
Wow that's very old.

Yes, on master branch there is new support for 'vhosts'.

I answered a similar question on the ml recently, the guy was able to get it working.

https://libwebsockets.org/pipermail/libwebsockets/2016-April/002284.html

Actually libwebsockets.org itself uses it, with 11 vhosts, it works fine.

**Comment by lws-team** [comment]
I added some docs about doing this here

https://github.com/warmcat/libwebsockets/blob/master/README.coding.md#using-lws-v2-vhosts

**Comment by lws-team** [comment]
Please reopen if you have more related questions.
