### ISSUE TITLE
libuv foreign loop and teardown

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#503]
Hi,

In the libuv part of libwebsockets, when attaching to an existing (foreign) uv_loop, I think libwebsockets doesn't handle cleanup / teardown on a foreign loop properly:

1. lws doesn't teardown what it should -- In the function lws_libuv_destroyloop, the foreign-loop case doesn't do anything, while the owned-loop case uses uv_walk to uv_close all handles on the loop. Obviously, foreign-loop case can't do uv_walk because there will be other non-lws related handles on the loop, but it should somehow close only lws uv handles. So, I think this currently leaves handles hanging on the loop.

2. lws tears down what it shouldn't: Function lws_libuv_stop in the end calls lws_libuv_kill which calls uv_stop on the loop, which might be foreign. I don't think we want to stop the foreign loop. In fact, I'm not exactly sure what the use case of lws_libuv_stop is in a foreign loop case, or whether lws_libuv_kill (which is called from elsewhere) should pay attention to foreign flag.

In the process of resolving this, I'm sure it would be most useful if libwebsockets had an example of foreign-loop test app, one which would run an independent libuv loop, after a while attach lws to it, run some lws code through the loop, then teardown lws while keeping the libuv loop alive for some additiponal time. Ideally it would combine this with signal-handling to verify it handles init and teardown on libuv, as well as signal handler behavior before lws is on the loop, during use, and after it is detached, and that the loop is cleaned up.

I saw on the mailing list that the next release would be soon, so I'm reporting this without clearer idea of solution suggestions/requirements, while API and behavior change in these cases is still on the table before release.

Regards,

Denis

**Comment by lws-team** [comment]
Yes, I agree it'd be useful to have an example for libuv with a foreign loop.... libuv stuff for internal loop(s) has tests in libwebsockets-test-server-libuv and lwsws, so I believe that is in good shape.

How about you hacking the existing libwebsockets-test-server-libuv to take a commandline flag where he uses a 'foreign' loop he sets up himself?

I can help debug what's broken in the lib but it'd be a help for me (and ultimately, you, since that then represents what you want to end up with working) if I can get a nice test case to start with.

**Comment by dosvald** [comment]
I could do that with the libuv test server but certainly not before next week.

**Comment by lws-team** [comment]
AFAIK master is generally in good shape to release, but there is no reason to rush.  So let's leave this open until next week.

**Comment by lws-team** [comment]
Any news?

**Comment by dosvald** [comment]
I've hacked up test-server-libuv a bit in these two branches:

https://github.com/sartura/libwebsockets/tree/test-foreign-stable
https://github.com/sartura/libwebsockets/tree/test-foreign-master

It segfaults at times, and valgrind yells at it.

Can you see what I was getting at in this example?

**Comment by lws-team** [comment]
Thanks... I could reproduce it using your stuff easily.

I pushed two patches on master, yours adapted to work with -f / --foreign switch on the existing libuv test server, and a fix patch that lets it work with or without --foreign valgrind-clean and with clean reactions to ^C.

It didn't require any new apis just making it act more closely to what's needed if it was a foreign loop, and making the foreign loop shut itself down as it needed to do.

**Comment by lws-team** [comment]
Well, if it's still got problems, please reopen.  But thanks to your patch I can say it's working well here.

**Comment by dosvald** [comment]
Thanks!

**Comment by meiry** [comment]
Can you please explain what is this foreign_libuv_loop and how the mechanizem works ?,
As i now checking it and can see it in :test-server-libuv.c

**Comment by lws-team** [comment]
One way to use lws is integrate it to an existing event loop in some other code.

For example you may have a server or app already happily using libuv himself, and you want lws to work with that.

Instead of lws creating his own personal libuv event loop, actually you can pass him an existing event loop at context creation time.  Lws understands he doesn't own that event loop, that it is 'foreign', so, eg, when the lws context is destroyed, he doesn't try to kill the event loop, just removes all his events and closes their handles.

The code dosvald added to the test-server-libuv.c simulates this situation (if you give --foreign), he makes a libuv loop himself outside of lws, adds his own timers and checks they work, then lets lws also use it.  Afterwards, he destroys the lws context and checks his loop still works ok.  Finally he closes his loop.

**Comment by meiry** [comment]
Thanks! 
but as i understand for it Lws needs event loop all the time , i can't just use its API inside the libuv event loop?

**Comment by lws-team** [comment]
Sorry, I don't understand the question.  Lws will process events, so he needs some kind of event loop.  For libuv he can use an existing loop or create + destroy his own along with the context.

There's some other way it could work?

**Comment by meiry** [comment]
Want i meant is that i don't understand why it needs event loop , but i guess it is for processing the chunks of data it process ( correct me if i wrong ) .

**Comment by lws-team** [comment]
No... it's to be informed when something happened, and to be properly idle (0% cpu) while nothing happened, without using multiple threads or blocking IO.

Even the lws service loop uses poll() in a loop for this purpose.

If you use libuv, he also can use poll(), but he normally uses epoll(), which is more efficient if things get busy.

Libuv has another advantage, he hides platform differences between, eg, windows and Linux.  It means your code can be compiled for different platforms same as lws can.  That's still true if you are using normally platform-dependent things like hires timers.

**Comment by meiry** [comment]
Thank , 
the most important question what is better to use , the foreign or the lws inner event loop ?
when building websocket game server for example in terms of Performance

**Comment by lws-team** [comment]
If it's a standalone server that just does stuff on ws, then no point using a foreign loop.

The foreign loop concept is only useful if you integrate lws with something else that has its own sockets or fds with events.  If it's not the case, just let lws manage the loop.

If you're on windows, there is no native poll() and the wsa emulation of it is so crap you should definitely use libuv.  Even on Linux which has a decent poll(), libuv supports epoll() which scales a lot better.

Generally unless there's a real memory or other restriction I recommend using libuv.

**Comment by meiry** [comment]
Thanks for the quick replay i really Appreciate it.
Now regarding my project i plan to use this stack :
libuv as the networking layer. 
libwebsockets as the websockets layer. 
Linux CentOS as the production server. 
Windows as the main development OS 

So if i understand right . i do need to use foreign loop as im using libuv  as libuv manage the sockets with events , right ? 
I fully aware that windows dosn't have poll just some kind of enulation of it , also i see you handle it in : test-server.h
```
#if defined(_WIN32) && defined(EXTERNAL_POLL)
#define WINVER 0x0600
#define _WIN32_WINNT 0x0600
#define poll(fdArray, fds, timeout)  WSAPoll((LPWSAPOLLFD)(fdArray), (ULONG)(fds), (INT)(timeout))
#endif
```
now if i think about it does it even necessary when integrating with libuv as it is already handle the windows emulation of poll  ....

**Comment by lws-team** [comment]
Whether you need foreign loop support or not is only about whether your app as a whole has things outside lws that also need libuv event management.  For example, if you add lws to an IRC server, and the IRC server already uses libuv for his own sockets, you would need to integrate with the IRC server's 'foreign' loop that has the other things using it as well, so everything was all working in the same event loop.  But if the only sockets and files floating around are coming from lws or lws user code already, no need for integrating with any foreign loop; there is no foreign loop to integrate with.

Yes if you use libuv, it takes over the job of the crappy default poll().  If you use libuv you can forget about windows' limitations and use the generic libuv apis (which will also work on Linux the same).

**Comment by meiry** [comment]
Thanks i see.
 i will use the foreign loop support as the IRC example is very similar to my situation.
