### ISSUE TITLE
libwebsocket in binary mode (as server) with browser as a client

### ISSUE THREAD

**Issue by oferch** [warmcat/libwebsockets#504]
I have a very simple js function that sends bytearray on a websocket:
   websocket.binaryType = "arraybuffer";

		var s = new Float32Array(256);
		for (i=0; i < 256; i++)
		{
			s.set([255], i);
		}
		websocket.send(s);

But what I see on the libwebsocket side is strange. 
I see for each Float32 4 bytes (which is probably true):
0 0 127 64

When I send the buffer right back to the client I indeed get the 0 0 127 64 in the browser.
My code is based on the test-server. (and normal strings are working fine). Am I missing something? Is this a bug?

**Comment by lws-team** [comment]
I didn't understand the problem, sorry.

What were you expecting that didn't happen?

**Comment by oferch** [comment]
I was expecting to get an array of 255's
so the buffer itself will look something like : (first byte)0 (second byte)0 (third byte)0 (4th byte)255

**Comment by lws-team** [comment]
These things are floats though.  Js knows that when you set it, when you dump it you see 255.0 in internal format.  Try newing up an Int32Array.

When you 'send it back' it's just a byte stream, if there are no extra bytes to explain the type it's up to your receiving Js how it interprets them.

If lws gets the bytes correctly and sends them back correctly (you are sending with LWS_WRITE_BINARY on lws side, right?) there's no Js on lws side to do anything else.  So the Js code deciding how those bytes are interpreted is the receiving Js you don't show.

**Comment by oferch** [comment]
Got you.
Helped me alot. 
thank you very much
