### ISSUE TITLE
client stuck in infinite loop on TLSv1.2 handshake failure

### ISSUE THREAD

**Issue by smipi1** [warmcat/libwebsockets#508]
If the a server responds with a `TLSv1.2 Handshake Failure` a libwebsockets client gets stuck in an aggressive error loop with the following symptoms:
- `ERR: SSL connect error 336085247: error:140840FF:SSL routines:SSL3_CONNECT:unknown state` is agressively logged non-stop.
- A call to `lws_service()` returns without delay.
- The `LWS_CALLBACK_GET_THREAD_ID` event fires non-stop.
- Returning a `-1` for the `LWS_CALLBACK_GET_THREAD_ID` event has no effect.

The above is an easy sticky denial-of-service attack on the client. Any connection attempt that results in a TLSv1.2 Handshake Failure will reproduce the issue.

To reproduce:
- Apply the attached/zipped patch to v1.7.3, v1.7.4, v1.7.5, v1.7.6 or master.
- Compile with Ubuntu 14.04LTS using the instructions in the `README.build.md`
- Start `libwebsockets-test-server` with the following options `--ssl --resource_path <path to share/libwebsockets-test-server>`
- Run `libwebsockets-test-client` with the following options: `localhost --port 7681 --ssl`

As soon as the client receives a `TLSv1.2 Handshake Failure`, the described problem manifests.

[0001-reproduce-TLSv1.2-handshake-failure-error-loop.zip](https://github.com/warmcat/libwebsockets/files/245755/0001-reproduce-TLSv1.2-handshake-failure-error-loop.zip)

**Comment by lws-team** [comment]
Thanks for the detailed report and way to reproduce on the test server / client... I can reproduce it on Fedora 22... I'll look at it thismorning.

**Comment by lws-team** [comment]
I pushed fixes on master and v1.7-stable, please give it a go.

**Comment by smipi1** [comment]
Hi Andy,

On Tue, 3 May 2016, 02:30 Andy Green, <notifications@github.com> wrote:

> I pushed fixes on master and v1.7-stable, please give it a go.
>
Thanks. I'll give it a go this morning.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/warmcat/libwebsockets/issues/508#issuecomment-216403824>
>
Regards,
Pieter

>

**Comment by smipi1** [comment]
Thanks Andy, 

I'll give it a go this morning.

**Comment by smipi1** [comment]
It works nicely on master and v1.7-stable. Can you make a v1.7 release of this?

Thanks,
Pieter

**Comment by lws-team** [comment]
Great... yes I just tagged it out as v1.7.7, as you saw it's already in master (which will very shortly become v2.0)... thanks for the bug report.

**Comment by smipi1** [comment]
Hi Andy,

I think you forgot to push the tag. Will you check please?

**Comment by lws-team** [comment]
Yes sorry, it's pushed now.

**Comment by smipi1** [comment]
Thanks!
