### ISSUE TITLE
Is there a real option to disable zlib?

### ISSUE THREAD

**Issue by mapx** [warmcat/libwebsockets#515]
In https://github.com/gentoo/gentoo/pull/1402 @gktrk found an unsuccessful attempt to disbale zlib support. 

It doesn't matter as we could enable zilb anyway.

**Comment by lws-team** [comment]
Zlib is needed for permessage-deflate extension support, you'd need to disable extensions at cmake to avoid zlib, ie LWS_WITHOUT_EXTENSIONS=1

**Comment by mapx** [comment]
Thanks :)
