### ISSUE TITLE
[Question] Is there a way to tell if the connection is upgraded?

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#516]
Is there a function to check if ```wsi``` is in upgraded (WS) mode?
Or at least the list of callback reasons used in WS mode?

PS: I know I could store this info in the connection's user data on ```LWS_CALLBACK_ESTABLISHED```, though I would prefer to get it directly from ```wsi``` for the sake of exception/failure safety.

**Comment by lws-team** [comment]
Obviously lws knows well what each connection state is, but the user code just needs to react to the things happening on the connection.  However if your ws protocol is not 0 (shared with http), you could tell by lws_protocol_get(wsi).

But actually there should be no need to tell, if it upgrades to ws then it starts doing ws type things like ESTABLISHED.  If he is in http-related states, he will never do ws-related things.  Similarly client-mode wsi will call client-related callbacks, not server-related ones.

If it feels confusing then maybe use the 'default protocol' stuff I pushed earlier to keep the protocols separate callbacks, see test-server/test-server-v2.0.c for example code.

**Comment by emptyVoid** [comment]
Yeah, I realize ```lws``` should not invoke the callback with HTTP-related reason after the upgrade is done. Though from the API reference it's hard for me to tell which reasons correspond to what connection mode.

I need to know the working mode for "default" protocol only to be able to notify user by sending an appropriate HTTP status code or a WebSocket close status while terminating connection in case of an internal failure (e.g. in case of a C++ exception).

I'm not sure if I can use the 'default protocol' stuff: as I understand it has something to do with protocols implemented as plugins (in form of some shared libraries or external scripts I guess), whereas I need all the implementation in a single executable.

**Comment by lws-team** [comment]
No you should be able to use the per-vhost options stuff fine.

In struct lws_context_creation_info now there is a member pvo, if you leave him NULL he's just ignored.  He's used to a) select which protocols are enabled in a particular vhost, and b) attach name:value options to a protocol, per-vhost.

For backwards-compatibility if you don't have multiple vhosts, every protocol is enabled on your default vhost.  So everything works with NULL info.pvo.

To set a given protocol as the default, get current master or v2.0-stable, and this should do

```
/*
 * this sets a per-vhost, per-protocol option name:value pair
 * the effect is to set this protocol to be the default one for the vhost,
 * ie, selected if no Protocol: header is sent with the ws upgrade.
 */

static const struct lws_protocol_vhost_options pvo_opt = {
	NULL,
	NULL,
	"default",
	"1"
};

static const struct lws_protocol_vhost_options pvo = {
	NULL,
	&pvo_opt,
	"dumb-increment-protocol",  /* which protocol is to be default, by name */
	""
};

....

info.pvo = &pvo;
```

You should get a NOTICE log like

 `Setting default protocol for vh default to dumb-increment-protocol`

**Comment by emptyVoid** [comment]
Great, I'll try it out!
Thanks!
