### ISSUE TITLE
%3D is not getting converted to =

### ISSUE THREAD

**Issue by mjmessina** [warmcat/libwebsockets#518]
If %3D is in the URL, it looks like it is getting coverted to an "_" and not an "=".         
              http://www.w3schools.com/tags/ref_urlencode.asp

Don't know if this is an issue or I don't have some proper setting.

Did a sampling of other hex characters and they seem to work.  Not sure what is magical about 3D.

**Comment by lws-team** [comment]
Yes.... it's only supposed to do it in the argument name, like `?name%3dy=x` should end up as `name_y=x`, not `name=y=x`, so it's immune to being tricked where the `=` separating the name and the value is.

But it does it in the raw url path part too, which is wrong.  I'll fix it later thismorning.

**Comment by lws-team** [comment]
It's fixed on master / v2.0-stable / v1.7-stable, and the test case added to attack.sh.

**Comment by mjmessina** [comment]
Great, thanks for fixing!

**Comment by mjmessina** [comment]
Just pulled and tested. Not sure this is an issue. 

if you have something like "the url path"/command?param%3dvalue.

It doesn't work the ? make the %3d to an "_".   You need to have

Not sure this is an issue but if you have something like "the url path"/command%3fparam%3dvalue.

**Comment by lws-team** [comment]
Where is your test 'url' with the % characters actually being generated?

**Comment by mjmessina** [comment]
I was manually pinging my server.   It's a rest server.
So entering something like:
        127.0.0.1/RestV1/command/dataFor?Date%3d03312016
results in an under score.

something like:
     127.0.0.1/RestV1/command/dataFor%3fDate%3d03312016

works.

Not sure if this is an issue.  It's kind-of mixing the escaping of the url.

**Comment by lws-team** [comment]
What about

`/RestV1/command/dataFor?Date=03312016`

Typically ?, = and & are not %-encoded in urls if they're supposed to be part of the 'escape infrastructure'.

**Comment by mjmessina** [comment]
Yes, that always worked.
One of the people hitting our server must have been escaping the the '?' and '=' too.
We where seeing `_' in our get commands.
