### ISSUE TITLE
Example test-client does not work with libwebsockets 2.0.0

### ISSUE THREAD

**Issue by cppbitman** [warmcat/libwebsockets#521]
Hi,
I'm building libwebsockets 2.0.0 using VS2013 Community on Win7. Solution file libwebsockets.sln  is generated with CMake. The build process of solution is successful, but test-client seems not-working.

When I run the test-client, console display repeatedly following content

[2016/04/10 20:09:32:2796] NOTICE: dumb: connecting
[2016/04/10 20:09:32:2906] NOTICE: mirror: connecting
[2016/04/10 20:09:32:3016] NOTICE: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[2016/04/10 20:09:33:4917] NOTICE: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0
[2016/04/10 20:09:34:4917] NOTICE: mirror: connecting
...

dumb-increment-protocol connecting seems happened once, and lws-mirror-protocol connecting continues again and again.

Can anybody fix this problem please?

**Comment by lws-team** [comment]
Actually that is what the test client should continuously say.

If you look with a browser while the test client is running at the test server, on the mirror test page, you should see that the test client is spamming circles there for a second or two, then dropping the connection and reconnecting automatically and spamming another load of circles.

**Comment by cppbitman** [comment]
Thanks a lot. I have seen the result on the the mirror canvas.
