### ISSUE TITLE
build error with vs2013 on win7 

### ISSUE THREAD

**Issue by cppbitman** [warmcat/libwebsockets#524]
error LNK2019: unresolved external symbol _chown referenced in function _lws_create_vhost

chown is not defined in function lws_create_vhost when set LWS_WITH_LWSWS=1

**Comment by lws-team** [comment]
Thanks... I just made the chown() conditional on no WIN32.

I don't know how to get appveyor to add libuv to his environment, so this option not build tested for windows atm.
