### ISSUE TITLE
[Win10][VS2010/2015][v2.0] Compilation issues

### ISSUE THREAD

**Issue by alexgille** [warmcat/libwebsockets#526]
I tried to compile **libwebsockets-2.0-stable** with both _Visual Studio 2010 Express_ and _Visual Studio 2015 Express_ but I had some issues with the compilation that fails for few projects in the generated solution.
I'm compiling on Windows 10.

First of all, my cmake command to generate the solution :

> cmake	-G "Visual Studio 10"
>     -DOPENSSL_ROOT_DIR=C:\tools\build_openssl-1.0.2h
>     -DOPENSSL_INCLUDE_DIR=C:\tools\build_openssl-1.0.2h\include
> 				-DOPENSSL_LIBRARIES=C:\tools\build_openssl-1.0.2h\lib\libeay32.lib;C:\tools\build_openssl-1.0.2h\lib\ssleay32.lib
> 				-DLWS_WITH_LWSWS=ON
> 				-DLIBUV_INCLUDE_DIRS=C:\tools\build_libuv-v1.8.0\include
> 				-DLIBUV_LIBRARIES=C:\tools\build_libuv-v1.8.0\libuv.lib
> 				-DCMAKE_INSTALL_PREFIX=C:\tools\build_libwebsockets-2.0-stable
> 				..

I made a list of issues I encountered with a set of quick solutions that resolved these issues.
**I don't know if these solutions are good, best, nor accurate** :

```
*	Error	:	"error C2133: 'protocols' unknown size" in 'protocol_lws_server_status.c' (line 42)
	Solution:	Specify 'protocols' array size in "static const struct lws_protocols protocols[];"
	
	
*	Error	:	"warning C4013: 'gettimeofday' undefined; assuming extern returning int" in 'protocol_lws_status.c' (line 134)
	Solution:	Add 'gettimeofday.c' as external dependency to 'protocol_lws_status' project
				Add "#include <gettimeofday.h>" at start of 'protocol_lws_status.c' file	
	
	
*	Error	:	[VS2010 ONLY] "unresolved symbol '__func__'" in 'protocol_lws_mirror.c' (line 58 & 72) and in 'protocol_lws_server_status.c' (line 72)
	Solution:	Replace '__func__' by '__FUNCTION__' manually
				        OR
				Add '#include "../lib/private-libwebsockets.h"' at start of :
					- protocol_lws_status.c
					- protocol_lws_server_status.c
					- protocol_lws_mirror.c


*	Error	:	"fatal error C1083: unable to find 'syslog.h'" in 'test-server-v2.0.c' (line 23)
	Solution:	Comment or delete '#include <syslog.h>' preprocessor line


*	Error	:	"unresolved external symbol _XXX [...]" where XXX is a function from this list (in libwebsockets.h) :
					- lws_protocol_vh_priv_zalloc
					- lws_protocol_vh_priv_get
					- lws_vhost_get
					- lws_protocol_get
					- lws_callback_on_writable_all_protocol_vhost
					- lws_extension_callback_pm_deflate
					- lws_create_vhost
					- lws_libuv_stop
	Solution:	Add LWS_EXTERN keyword to each function declaration
				Replace 'extern' keyword by 'LWS_EXTERN' for function "lws_extension_callback_pm_deflate"


*	Error	:	"error C2059: syntax error : '}'" in 'lwsws\main.c' (line 65).
	Solution:	Specify NULL initialization. Replace '{ }' by '{ NULL, NULL, 0, 0 }'


*	Error	:	"error C2036: 'void *': size unknown" in 'lwsws\http.c' (line 152)
	Solution:	Add explicit cast '(TCHAR *)' before variable 'in' in 'strcmp()' call
```

After that, everything is fine with compilation and linking. I have all the libs I needed, but some testing executables are still crashing when trying to use them.

I hope it could help.

Regards

**Comment by lws-team** [comment]
Thanks for the big list, I'll go through them tomorrow.

Lws is build-tested for windows by Appveyor, but because I have no idea how to feed it libuv, it cannot test any build options depending on libuv.  (For Linux on Travis, I added libuv and it's all build-tested there)..

If you have some idea how to add that (in ./appveyor.yml... for openssl, it downloads a windows install package from a guy who maintains builds) then I will be able to fix these problems myself before you meet them.

**Comment by lws-team** [comment]
Those should be solved by the patches on v2.0-stable and master.

I moved the define for __func__ into libwebsockets.h itself for win32.  The rest of the win32-isms are fixed as you suggested, although on master other refactor means the last two issues no longer exist (the related code no longer exists).

Libuv provide windows installer blobs via NSIS, 

http://dist.libuv.org/dist/v1.9.0/

but testing it in wine these do not support the necessary autoinstall switches used by openssl.  Googling around these seem to be an option at the time the install package is created.  I'll ask the libuv people.

**Comment by lws-team** [comment]
https://github.com/libuv/libuv/issues/871

**Comment by alexgille** [comment]
Thanks for your quick answer. I hope I contributed in a productive way :-)
For libuv, I tried to compile v1.9.0 but I had compilation errors so I compiled with v1.8.0 and it worked perfectly. I did not try the installer version of that lib though...

I don't know anything about AppVeyor but maybe a Jenkins with different flavours of Windows and Unix slave machines (with VirtualBox) could give more flexibility for testing. This would imply more work for you as you'll have to tell Jenkins how to build/test libs but, in the other hand, you'll gain full control on the building/testing process.

Thanks for your great work !

**Comment by alexgille** [comment]
Hey,

I tried to compile what's from the master branch and I still have Linker errors:

* The gettimeofday issue in **protocol_lws_status** project, **gettimeofday.c** is not included in the project as source. _Right-click -> Add existing source -> gettimeofday.c_ fixed the problem.

* unresolved external symbol errors for :
    - lws_extension_callback_pm_deflate
    - lejp_destruct
    - lejp_parse
    - lejp_construct
    - lejp_get_wildcard

For the first, replacing 'extern' keyword by 'LWS_EXTERN', and for the others simply adding 'LWS_EXTERN' fixed the problem.

Now compilation is fine :)

Regards

**Comment by alexgille** [comment]
Hi again,

I fixed the following warnings in **context.c** in **websockets_shared** project :
* _warning C4013: 'open' undefined; assuming extern returning int_ (line 449)
* _warning C4013: 'close' undefined; assuming extern returning int_ (line 944)
* _warning C4013: 'write' undefined; assuming extern returning int_ (line 2347)

by including **io.h** in the Win32-only preprocessor section of **private-libwebsockets.h**.
Don't know if it's the right spot... Don't know if it's relevant...

Regards

**Comment by lws-team** [comment]
Thanks a lot... I added the LWS_EXTERNs and found an accidental paste killing the arrangements in CMakeLists.txt already to add gettimeofday.c for WIN32... those further fixes are pushed on master + v2.0-stable

**Comment by lws-team** [comment]
After a lot of attempts (and advice from libuv guys, and cribbing your Cmake setup) I was able to get all the pieces installed in the appveyor instance, plus self-hosted the pieces to avoid waiting ten minutes for sourceforge each time.

So we can now build-test LWSWS with the other deps like libuv related code, plugins etc included on windows.

I saw the newly built code had some msft-ism warnings coming still, so I have cleared those out.  So to the extent appveyor building it is the same as msvc, this makes it easy for me to keep the build clean of errors going on.

**Comment by alexgille** [comment]
Great news! I'll check this out asap. Thanks

**Comment by alexgille** [comment]
Compilation is as smooth as silk, no warning :) Thanks!

**Comment by lws-team** [comment]
Super.

**Comment by lws-team** [comment]
@alexgille ... sorry to bother you.... I am adding a new feature in lws that depends on sqlite3.  I found official windows binaries here

https://www.sqlite.org/2016/sqlite-dll-win32-x86-3130000.zip

But inside are only a .dll and .def file.  I found you can run a utility from the SDK

`lib /def:sqlite3.def /out:sqlite3.lib`

However there's no PATH set up to get to this lib utility and I'm not even sure which version of VS stuff is in Appveyor.

Is theer any chance you could dowload the zip and run the command "Using the VS Command Prompt" that sets up the PATH appropriately, and give me the .lib?

**Comment by alexgille** [comment]
Yep, I'll give it a try !

**Comment by alexgille** [comment]
Everything went well.

The `/MACHINE:X86` was set automatically.

Please rename file attached with a **.zip** extension, it seems like GitHub is not felling good with my archive.


[sqlite.txt](https://github.com/warmcat/libwebsockets/files/279839/sqlite.txt)

**Comment by lws-team** [comment]
Thanks a lot, that got me over the hump ^^
