### ISSUE TITLE
lws_close_free_wsi() gets called twice

### ISSUE THREAD

**Issue by eludar** [warmcat/libwebsockets#532]
Hi,

there seems to be a mistake in calling chain of the lws_ssl_client_connect2() function. Look at the following code snippet from lws_ssl_client_connect2():

`	if (n != X509_V_OK) {
		if ((n == X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT ||
		     n == X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN) && wsi->use_ssl == 2) {
			lwsl_notice("accepting self-signed certificate\n");
		} else {
			lwsl_err("server's cert didn't look good, X509_V_ERR = %d: %s\n",
				 n, ERR_error_string(n, sb));
			lws_ssl_elaborate_error();
			lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS);
			return -1;
		}`

If the certificate was not OK, the wsi gets closed and freed and the function exits with return value -1.
Now look at the code in lws_client_socket_service(), where lws_ssl_client_connect2() is called:

`	case LWSCM_WSCL_WAITING_SSL:

		if (wsi->use_ssl) {
			n = lws_ssl_client_connect2(wsi);
			if (!n)
				return 0;
			if (n < 0)
				goto bail3;
		} else
			wsi->ssl = NULL;
`

Since lws_ssl_client_connect2() returned -1, the flow continues at the bail3 label:

`bail3:
		lwsl_info("closing conn at LWS_CONNMODE...SERVER_REPLY\n");
		wsi->vhost->protocols[0].callback(wsi,
			LWS_CALLBACK_CLIENT_CONNECTION_ERROR,
					wsi->user_space, NULL, 0);
		lws_close_free_wsi(wsi, LWS_CLOSE_STATUS_NOSTATUS);
		return -1;`

If I understand correctly, bail3 is the place where some uniform handling of all connection errors in lws_client_socket_service() takes place. At this point the wsi is closed and freed. The problem is, that the wsi has already been closed and freed inside the lws_ssl_client_connect2() function.

As the result of closing and freeing wsi twice, I get a segmentation fault.

I suppose, the call to lws_close_free_wsi() inside lws_ssl_client_connect2() should be removed.

**Comment by lws-team** [comment]
Thanks... yes you're right the close is not needed because the parent will do it.

I pushed a patch on master and v2.0-stable removing the duplicated close.

**Comment by ajsetter** [comment]
So I've noticed commit 29bb33b is no longer in branch v2.0-stable. Only commit 7c2d596 has it in the master branch. 

Is there a plan to have this change put into one of the release branches?

**Comment by lws-team** [comment]
Not sure what happened there, I added it to v2.0-stable (as it seems I already thought I had done).
