### ISSUE TITLE
Minilex and websocket headers parsing

### ISSUE THREAD

**Issue by usergoodvery** [warmcat/libwebsockets#535]
Hi,
This is not exactly related to the lib, but I did clean extraction of the code that parses the websocket handshake headers (parsers.c) and I noticed when testing that some headers don't get picked up:
I used the following string:
char buf[]="GET / HTTP/1.1\r\nCookie: session=614141414110\r\nX-Cm-Token: 1\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: cVA4L6lLENWjV6BtzTPKug==\r\nSec-WebSocket-Version: 13\r\nHost: xxx.com:1973\r\nAccept-Encoding: gzip\r\nUser-Agent: okhttp/2.2.0\r\nX-Forwarded-For: 130.20.17.119\r\n\r\n";

User-Agent is not recognised, even though it is in the minilex-strings.h. I did a fresh minilex > lextable.h. It seems to be recognising the first two letters only. See output below.

Also, when I tried to add my own headers (where you clearly indicate in the header file) and sync that with enum lws_token_indexes as well as a fresh 'minilex > lextable.h' those headers don't get recognised.
 

This is the output from the lexer:
WSI_TOKEN_NAME_PART 'U' (mode=0)
WSI_TOKEN_NAME_PART 's' (mode=0)
WSI_TOKEN_SKIPPING 'e'
WSI_TOKEN_SKIPPING 'r'
WSI_TOKEN_SKIPPING '-'
WSI_TOKEN_SKIPPING 'A'
WSI_TOKEN_SKIPPING 'g'
WSI_TOKEN_SKIPPING 'e'
WSI_TOKEN_SKIPPING 'n'
WSI_TOKEN_SKIPPING 't'
WSI_TOKEN_SKIPPING ':'
WSI_TOKEN_SKIPPING ' '
WSI_TOKEN_SKIPPING 'o'
WSI_TOKEN_SKIPPING 'k'
WSI_TOKEN_SKIPPING 'h'
WSI_TOKEN_SKIPPING 't'
WSI_TOKEN_SKIPPING 't'
WSI_TOKEN_SKIPPING 'p'
WSI_TOKEN_SKIPPING '/'
WSI_TOKEN_SKIPPING '2'
WSI_TOKEN_SKIPPING '.'
WSI_TOKEN_SKIPPING '2'
WSI_TOKEN_SKIPPING '.'
WSI_TOKEN_SKIPPING '0'
'SI_TOKEN_SKIPPING '
WSI_TOKEN_SKIPPING_SAW_CR '
'
' (mode=0)NAME_PART '
WSI_TOKEN_NAME_PART '
' (mode=0)
known hdr 8
v00 hdrs completed

**Comment by lws-team** [comment]
All I can say is "User-Agent" is recognized fine in stock lws.  Did something change?

```
lwsws[589]: WSI_TOKEN_NAME_PART 'U' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 's' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'e' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'r' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART '-' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'A' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'g' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'e' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 'n' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART 't' (mode=0)
lwsws[589]: WSI_TOKEN_NAME_PART ':' (mode=0)
lwsws[589]: known hdr 69
lwsws[589]: WSI_TOK_(69) ' '
lwsws[589]: WSI_TOK_(69) 'M'
lwsws[589]: WSI_TOK_(69) 'o'
lwsws[589]: WSI_TOK_(69) 'z'
lwsws[589]: WSI_TOK_(69) 'i'
lwsws[589]: WSI_TOK_(69) 'l'
...
etc
```

Also I am not sure your paste of the parse matches the stuff you pasted for buf[]... where is X-Forwarded-For?

It sounds like something got confused or broken.  Maybe try backing up to stock lws and confirm it acts well or not there.

**Comment by usergoodvery** [comment]
The output I included is not the full one, in fact X-Forwarded-For was not recognised either... as you say I must have inadvertently messed up something... I only really needed to do minor changes, your code is well structured to begin with...

This the test driver:

struct lws *wsi=calloc(1, sizeof(struct lws));
	wsi->u.hdr.ah=calloc(1, sizeof(struct allocated_headers));
	wsi->u.hdr.parser_state=WSI_TOKEN_NAME_PART;
	wsi->state=2;//WSI_STATE_HTTP_HEADERS;

	while (len--)
	{

		if (libwebsocket_parse(context, wsi, *buf2++))
		{
			printf("libwebsocket_parse failed\n");
			break;
		}
		if (wsi->u.hdr.parser_state != WSI_PARSING_COMPLETE)
				continue;
	}

	//int data_offset=wsi->u.hdr.ah->frag_index[3];

	int idx=1;
	for ( ; idx<=wsi->u.hdr.ah->nfrag; idx++)
	{
		int j=wsi->u.hdr.ah->frags[idx].offset;
		printf("frag_offset:'%d'  len:'%d'  data: '%s' \n",
				wsi->u.hdr.ah->frags[idx].offset,
				wsi->u.hdr.ah->frags[idx].len,
				wsi->u.hdr.ah->data+wsi->u.hdr.ah->frags[idx].offset);

	}

	idx=wsi->u.hdr.ah->frag_index[WSI_TOKEN_HTTP_COOKIE];//WSI_TOKEN_HTTP_COOKIE];
	printf("WSI_TOKEN_HTTP_COOKIE(%d) idx='%d' frag_offset:'%d'  len:'%d' data: '%s' \n",
			WSI_TOKEN_HTTP_COOKIE, idx,
					wsi->u.hdr.ah->frags[idx].offset,
					wsi->u.hdr.ah->frags[idx].len,
					wsi->u.hdr.ah->data+wsi->u.hdr.ah->frags[idx].offset);



which produces
frag_offset:'0'  len:'1'  data: '/'
frag_offset:'2'  len:'8'  data: 'HTTP/1.1'
frag_offset:'11'  len:'20'  data: 'session=614141414110'
frag_offset:'32'  len:'9'  data: 'websocket'
frag_offset:'42'  len:'7'  data: 'Upgrade'
frag_offset:'50'  len:'24'  data: 'cVA4L6lLENWjV6BtzTPKug=='
frag_offset:'75'  len:'2'  data: '13'
frag_offset:'78'  len:'22'  data: 'ufsrv.unfacd.com:19702'
frag_offset:'101'  len:'4'  data: 'gzip'
WSI_TOKEN_HTTP_COOKIE(24) idx='3' frag_offset:'11'  len:'20' data: 'session=614141414110'
WSI_TOKEN_HOST(3) idx='8' frag_offset:'78'  len:'22' data: 'ufsrv.unfacd.com:19702'

**Comment by lws-team** [comment]
I can't debug this with just the info and snippets you're giving, it's only broken in your port of it I think.

If you want to strip it down to something I can build easily and push it somewhere I could look at where it blows up.  But no guarantees...

**Comment by usergoodvery** [comment]
thanks for your suggestion. I uploaded to https://github.com/usergoodvery/ws_parser
I marked my changes with '//AA-' or '//AA+' which you'll see dotted around...

All you need to do is gcc ws_parser2.c

**Comment by lws-team** [comment]
I tried it, but isn't this as expected?

```
WSI_TOKEN_NAME_PART 'U' (mode=0)
WSI_TOKEN_NAME_PART 's' (mode=0)
WSI_TOKEN_NAME_PART 'e' (mode=0)
WSI_TOKEN_NAME_PART 'r' (mode=0)
WSI_TOKEN_NAME_PART '-' (mode=0)
WSI_TOKEN_NAME_PART 'A' (mode=0)
WSI_TOKEN_NAME_PART 'g' (mode=0)
WSI_TOKEN_NAME_PART 'e' (mode=0)
WSI_TOKEN_NAME_PART 'n' (mode=0)
WSI_TOKEN_NAME_PART 't' (mode=0)
WSI_TOKEN_NAME_PART ':' (mode=0)
known hdr 30
WSI_TOK_(30) ' '
WSI_TOK_(30) 'o'
WSI_TOK_(30) 'k'
WSI_TOK_(30) 'h'
WSI_TOK_(30) 't'
WSI_TOK_(30) 't'
WSI_TOK_(30) 'p'
WSI_TOK_(30) '/'
WSI_TOK_(30) '2'
WSI_TOK_(30) '.'
WSI_TOK_(30) '2'
WSI_TOK_(30) '.'
WSI_TOK_(30) '0'
'SI_TOK_(30) '
*
WSI_TOKEN_SKIPPING_SAW_CR '
'
' (mode=0)NAME_PART '
WSI_TOKEN_NAME_PART '
' (mode=0)
known hdr 8
v13 hdrs completed
frag_offset:'0'  len:'1'  data: '/' 
frag_offset:'2'  len:'8'  data: 'HTTP/1.1' 
frag_offset:'11'  len:'20'  data: 'session=614141414110' 
frag_offset:'32'  len:'1'  data: '1' 
frag_offset:'34'  len:'9'  data: 'websocket' 
frag_offset:'44'  len:'7'  data: 'Upgrade' 
frag_offset:'52'  len:'24'  data: 'cVA4L6lLENWjV6BtzTPKug==' 
frag_offset:'77'  len:'2'  data: '13' 
frag_offset:'80'  len:'11'  data: 'xx.com:1970' 
frag_offset:'92'  len:'4'  data: 'gzip' 
frag_offset:'97'  len:'12'  data: 'okhttp/2.2.0' 
WSI_TOKEN_HTTP_COOKIE(24) idx='3' frag_offset:'11'  len:'20' data: 'session=614141414110' 
WSI_TOKEN_HOST(3) idx='9' frag_offset:'80'  len:'11' data: 'xx.com:1970' 
```

Valgrind complains you don't free your allocations, but otherwise no funny business.

What platform + compiler are you using?

**Comment by usergoodvery** [comment]
hmmm.... strange I think my issues may have been data related ie i may have had some inconsistencies with my tokens. I shuffled few things around before I pushed the code to github and that may have fixed it without me noticing... because you are right I now get the right output, included my added fields. 
This was a crude port to test the stuff to see if it could replace my own parser, so I am not surprised valgrind is complaining...
looks like we are in business again... I extracted it in an hour but took a good portion of a day to debug it before I thought i reach out to you... thanks for your input

**Comment by lws-team** [comment]
It's often the way having to explain or refactor it helps solve it...
