### ISSUE TITLE
Include libwebsockets in Xcode project

### ISSUE THREAD

**Issue by stefanobider** [warmcat/libwebsockets#536]
Hey everyone,
I am trying to use libwebsockets in my Xcode project but I'm having issues with linking. Here is the detailed list of steps I'm following:
- clone lws repo in a subfolder of my project directory tree: `third_party/libwebsockets_2_0/libwebsockets` (I need it to be with this tree)
- configure and generate (xcode) files with Cmake 3.1.0rc2:
	- suggested build path (`third_party/libwebsockets_2_0/libwebsockets/build`)
	- `LWS_WITH_STATIC`
	- `CMAKE_OSX_ARCHITECTURES : i386 x86_64`	(necessary)
	- `CMAKE_OSX_DEPLOYMENT_TARGET : 10.7` (necessay, all my project need to be fully backwards compatible with 10.7 and properly links against 10.7 SDK)
- once created, add libwebsockets.xcodeproj as a subproject to my own xcode proj
- in my project build phases, add "websockets" to target dependencies  and "websockets" (static) in linked binary items 
- in my project build settings, add third_party/libwebsockets_2_0/libwebsockets/lib to header search paths
- in my project build settings, add third_party/libwebsockets_2_0/libwebsockets/build to library search paths

The outcome:
Building from Xcode the websockets target of the libwebsockets xcode project works fine, the static library is generated. When trying to include "libwebsockets.h" the file itself is properly found, but the linker returns this error:

`third_party/libwebsockets_2_0/libwebsockets/lib/libwebsockets.h:105:10: fatal error: 'lws_config.h' file not found`

Note that I also tried to NOT include the project as subproject and simply to link to a precompiled version of websockets.a.
All other subprojects (including other third party libraries) link properly, so I'm not sure what's happening here. Does anyone have a clue? Any help would be much appreciated. 

Some environment details: 
- LWS 2.0 (note that the same happened with 1.7)
- Mac OS 10.10.5
- Xcode 7.0 linking against 10.7 SDK

Thank you, have a great day.

Stefano Bider

**Comment by troyc** [comment]
I am not familiar with Xcode, but I believe that your compiler can't find lws_config.h when trying to include it, which is not a linker error. The solution would be to find where lws_config.h is and make sure the compiler knows to check that directory when looking for include files.

Since Mac is Unix-based, I assume you can find where lws_config.h is by doing `find / -iname lws_config.h`. Then, you should be able to add its directory to Xcode's [search paths](https://stackoverflow.com/questions/14134064/how-to-set-include-path-in-xcode-project).

**Comment by lws-team** [comment]
As Troy says, it's a compiler error about include dirs.

lws_config.h is generated in your lws build dir, and if you make install lws it goes into /usr/include along with libwebsockets.h.

If you don't install lws, just like you had to configure your other app to look for libwebsockets.h in "third_party/libwebsockets_2_0/libwebsockets/lib", you'll need to also have it look for includes (-I) in your lws build path "third_party/libwebsockets_2_0/libwebsockets/build".

**Comment by stefanobider** [comment]
Thank you, the /build include path was indeed the problem.
However something just doesn't feel right...I guess the issue is closed anyway.
Have a nice day everyone, thank you again
