### ISSUE TITLE
Question: about lws_get_peer_addresses

### ISSUE THREAD

**Issue by mjmessina** [warmcat/libwebsockets#537]
I have been seeing lws_get_peer_addresses take upto 7 seconds to complete.
Is there any calls that are **fast**  (in the microSeconds) to get the clients IP for incoming requests?

**Comment by lws-team** [comment]
Basically it's doing a reverse dns.

In v2.0+ for logging if you enable LWS_WITH_ACCESS_LOG at cmake, you can pass a filepath at vhost creation time (== context creation time if using the default vhost) in info.log_filepath.  This uses an internal api lws_get_peer_simple() that avoids the rdns, and automatically writes Apache-compatible logs to the file.  You can read here

https://github.com/warmcat/libwebsockets/blob/master/README.lwsws.md#integration-with-logrotate

how to make it work with logrotate.

If that's not actually what you need I can expose lws_get_peer_simple() as a public api, but either way you will need v2.0+ or master.

**Comment by mjmessina** [comment]
If you don't mind exposing lws_get_peer_simple would be great.  I would like to log some of our information along with the client IP.

**Comment by lws-team** [comment]
It's made available on master.

```
/**
 * lws_get_peer_simple() - Get client address information without RDNS
 * @wsi:	Local struct lws associated with
 * @name:	Buffer to take client address name
 * @name_len:	Length of client address name buffer
 *
 * 	This provides a 123.123.123.123 type IP address in @name from the
 * 	peer that has connected to @wsi
 */
```

**Comment by mjmessina** [comment]
Thank you!
