### ISSUE TITLE
blocking http/https urls by using ndpi netfilter

### ISSUE THREAD

**Issue by hemanth4ap** [warmcat/libwebsockets#547]
hi ,
i am using ndpi net filter for blocking websites but its not blocking https websites. i want block https websites.
i am using command like **

> iptables -A INPUT -m ndpi --facebook -j DROP

** its working . but if use https website its not working, please help me.

**Comment by lws-team** [comment]
Dunno why you're asking at lws project.

What I'd do (aside from ask at ndpi filter project) is block the dns.

https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all
