### ISSUE TITLE
IPv6 support should be per-vhost, not per-context

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#552]
Let's say I want to make this scenario with 1 context and couple of vhosts:

- vhost A wants to listen on 0.0.0.0:4444, doesn't want to touch IPv6
- vhost B wants to listen on *:6464, using both IPv6 and IPv4 (via mapping), or using IPv6 only

Of course, if  LWS_IPV6=OFF compile-time, vhost A is only possible option, and works as expected by default (no options need to be set), and vhost B can't be supported.
But when having IPV6 on compile-time, how to achieve the vhost cases like above?

I've tried and failed. and I now think that IPv6 handling is wrong at least in vhost / server part, or at least It isn't obvious what to do. I've tried the logical stuff, disabling IPv6 on some vhost but that didn't work.

Then I saw in server.c `lws_context_init_server` ( called from create vhost function ):

```c
#ifdef LWS_USE_IPV6
	  if (LWS_IPV6_ENABLED(vhost->context))
 		sockfd = socket(AF_INET6, SOCK_STREAM, 0);
 	else
#endif
		sockfd = socket(AF_INET, SOCK_STREAM, 0);
```

That looks like it checks if **context** enables IPv6 when doing vhost init, but since socket belongs to vhost, it should check that instead. That means that currently one lws context can make all vhosts either type A above (4 only, if ctx info disables IPv6) or type B (if ctx info doesn't enable IPV6), and I believe that's a defect.

So, the vhost creating part should check the vhost ipv6 support when making socket.

Then user code would do something like this:

```c
// don't disable IPv6, since some vhosts need it (analog to SSL, need to enable if some vhosts need it)
ctxinfo->options &= ~LWS_SERVER_OPTION_DISABLE_IPV6;
...
// For vhost A disable IPv6
vhinfoA->options = LWS_SERVER_OPTION_DISABLE_IPV6
....
// For vhost B don't disable IPv6
vhinfoB->options &= ~LWS_SERVER_OPTION_DISABLE_IPV6;
....
```

The global context option for IPv6 might not be needed though, it might be okay if that flag is only looked at for vhosts.

**Comment by dosvald** [comment]
> I can migrate the ipv6-fulness flag to vhost by myself easily but is that really going to solve your problem? 

If IPv6 is checked per-vhost that'll solve this one. I have no idea how client context works, but I think for server + vhosts part, checking IPv6 per vhost is enough

**Comment by lws-team** [comment]
Clients will create a default vhost at context creation time.... that vhost will reflect the vhost-related info settings from the context creation action by default.  So if it's set in the options, it should be enough.

**Comment by dosvald** [comment]
Alright. To solve the other merged issue 551, in addition to making IPv6 per-vhost, need to add some way of making a three-state option.

I don't know how best to do that cleanly with bitfields other than this:

- `LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE`
- `LWS_SERVER_OPTION_IPV6_CHANGE_V6ONLY` - if this bit is set, then should look at OPTION_V6ONLY_VALUE, and do: `setsockopt(sockfd, SOL_IPV6, IPV6_V6ONLY, &value, sizeof value)`.

But then It's not `|`able as easily as other ones.
Other approach would be to add a new two-bit bitfield member somewhere.

**Comment by lws-team** [comment]
Fixed in current master
