### ISSUE TITLE
libwebsockets.h shouldn't define ARRAY_SIZE in public header

### ISSUE THREAD

**Issue by karlp** [warmcat/libwebsockets#558]
Given that ARRAY_SIZE isn't used by anything in the public header, it shouldn't be defined in the public header.  While it's a common define, it's not even protected by an ifndef, so it clashes badly with other code that also defines this, depending on inclusion order.

**Comment by lws-team** [comment]
Hm it's used in the test apps and plugins; given what it does it would never be 'used in the public header'.

You're right though it should be protected by a #ifndef like the one in ./lib/lejp.h.

I pushed a patch adding that on v2.0-stable and master.
