### ISSUE TITLE
LWS_HAVE_OPENSSL_ECDH_H is set for non-openssl builds

### ISSUE THREAD

**Issue by karlp** [warmcat/libwebsockets#559]
If I have both openssl and wolfssl available on my host, but have set LWS_USE_WOLFSSL = ON, then I get a build failure, because LWS_HAVE_OPENSSL_ECDH_H is also set, but I'm not linking against openssl.

I can move the if/endif checks to only do the check in the "if (NOT chose_ssl)" block, which _works_ and I can compile libwebsockets 2.x, but wolfssl does provide wolfssl/openssl/ecdh.h, so I'm not sure if that's the _complete_ or correct patch.

**Comment by lws-team** [comment]
I don't fully understand the problem... from your description it's not wrong to say that there is an openssl/ecdh.h either way.

Is it that your wolfssl has installed the ecdh.h, but the wolfssl library was not built configured with ecdh?  If that's not it, can you elaborate on the "build failure"?

**Comment by karlp** [comment]
At least part of it relates to /usr/include/openssl/ecdh.h including <openssl/ec.h> directly,
but /usr/include/wolfssl/openssl/ecdh.h doesn't.

There's also problems with "OBJ_sn2nid" being only available if wolfssl was compiled with "LIGHTY" support.  WolfSSL just seems to have complicated and awkward compat structures, but LWS isn't handling it well.  "SSL_CTX_set_tmp_ecdh" isn't available in WolfSSL at all as best I can tell.

I've attached a full compile log if you want to look at it further.
[compile.txt](https://github.com/warmcat/libwebsockets/files/302338/compile.txt)

**Comment by lws-team** [comment]
> At least part of it relates to /usr/include/openssl/ecdh.h including <openssl/ec.h> directly,
but /usr/include/wolfssl/openssl/ecdh.h doesn't.

Well I think that's another way of saying it should open .../wolfssl/... path only.

> There's also problems with "OBJ_sn2nid" being only available if wolfssl was compiled with "LIGHTY" support. WolfSSL just seems to have complicated and awkward compat structures, but LWS isn't handling it well.

TBH it's not lws' problem to 'handle' wolfssl funky internal deps from wolfssl's own build.

How about using openssl?

**Comment by karlp** [comment]
openssl works just fine :) I'm not even using wolf, just trying to maintain the wolf build of LWS for openwrt.  However, if LWS is going to claim to support wolf, then it should support wolf.  Or not support wolf.  I don't mind either way.  But claiming to support wolf, with a bunch of code in place to support wolf, but actually failing to compile, I do consider an issue in LWS, not an issue in wolf.

**Comment by karlp** [comment]
(and dropping ECDH support from wolf builds, even if wolf _may_ have some ECDH support is one way of fixing it, moving the if checks in cmake to only apply to openssl)

**Comment by lws-team** [comment]
Hm... but you do consider it to be at least partly an issue in wolfssl

> There's also problems with "OBJ_sn2nid" being only available if wolfssl was compiled with "LIGHTY" support. WolfSSL just seems to have complicated and awkward compat structures [...]

At any rate wolfssl support was contributed, this is the first time since then someone using it says there's a problem.

If you want to send a patch removing ECDH support from wolfssl support as a workaround I'll be happy to take it.  Otherwise if wolfssl is broken I will disable it in cmake until someone who cares enough to fix it appears.

**Comment by karlp** [comment]
Well, a patch that works is attached here, but I believe that mbed/polar have the same problem.  The check for ecdh support in LWS is explicitly based around the existance of whether `<openssl/echd>` exists, regardless of whether openssl is being linked or not.
[0002-non-openssl-only-check-for-openssl-ecdh-in-openssl-b.txt](https://github.com/warmcat/libwebsockets/files/302459/0002-non-openssl-only-check-for-openssl-ecdh-in-openssl-b.txt)

**Comment by lws-team** [comment]
Thanks... I understand it's a workaround.  If I understood the issue, looking for openssl/ecdh.h is fine, because wolfssl does provide such a thing if you can direct its attention to -I/usr/include/wolfssl ... it's that last bit that isn't right.

Anyway it's pushed on master + v2.0-stable and I appreciate your time sending the tested workaround.

**Comment by karlp** [comment]
Well yes, looking for openssl/ecdh.h is _meant_ to be fine, and the regular wolf setups direct -I/usr/include/wolfssl so that you can "compatibly" just do `#include <openssl/ecdh.h>` but unfortunately, the _actual_ openssl/ecdh.h includes openssl/ec.h itself, but wolfssl's openssl/ecdh.h doesn't, the user is meant to include it themselves.  It's _possible_ therefore, that leaving the check as it was, and expanding LWS to include openssl/ec.h directly would get ecdh working with wolf.  But, as you can tell, it's tedious, difficult to test, and extremely uninteresting to work on :bomb:

**Comment by lws-team** [comment]
Yes it seems we agree about everything in that post ^^
