### ISSUE TITLE
Asterisk 13.9.0 and libwebsocket 1.4 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by costca** [warmcat/libwebsockets#561]
I am able to compile app_xxxxx.c in Asterisk (using make, make install), but when I tried to load it I get errors on libwebsockets. It looks like the library is not recognized/loaded properly. When I checked with pkg-config --modversion libwebsockets I see 1.4. I already tried this code on different VM with the same result. This seems to be the only library not found. 
The error is:
_loader.c:599 load_dynamic_module: Error loading module 'app_xxxxx.so': /usr/lib/asterisk/modules/app_xxxxx.so: undefined symbol: libwebsocket_service_
If I remove the call for libwebsocket_service, the app fails on the next libwebsocket call when loaded (module load app_xxxxx.so under Asterisk). Isn't this the way to create the .so file in Asterisk? Do I need to specifically include the library in the compile call?
Thanks.
CoS

**Comment by lws-team** [comment]
From the sound of it, either 1) your asterisk plugin .so wants to bind to lws and can't find the lws so.

Use `ldd /usr/lib/asterisk/modules/app_xxxxx.so` to confirm it.  If that's ok then 2) it's not v1.4 of lws like you think.

Where did the lws you're using come from?  If a package, there shouldn't be any problem, but if you built yourself, you may need to do `ldconfig` one time as root to have your system realize a new .so has appeared.

The version of cmake pieces installed is a very oblique way to mention the version of lws.  After v1.5 of lws, there was an api rationalization, and the api names changed to all begin lws_...  That can also explain your symptom, so check the actual lws version either by dpkg or look in CMakeLists.txt of lws for the checked-out version in the lws sources.

**Comment by costca** [comment]
When i run ldd /usr/... I get this:

_linux-vdso.so.1 =>  (0x00007ffc45d3a000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f160f0e2000)
libc.so.6 => /lib64/libc.so.6 (0x00007f160ed4e000)
/lib64/ld-linux-x86-64.so.2 (0x0000003d60c00000)_

I did ldconfig as root, but I still see the error on module loading. The lws was installed as a package and I can check it with dpkg - rev. 1.4.
Thanks. for your help.
CoS

**Comment by lws-team** [comment]
If that's all ldd says, it means the plugin doesn't seem to expect to bind to lws as a dynamic lib.

You'll have to look closer at how the plugin builds to understand the problem... it wants to static link to lws?  Or something wrong with the plugin build config?
