### ISSUE TITLE
why do I get ENAMETOOLONG(errno=36)?

### ISSUE THREAD

**Issue by springrider** [warmcat/libwebsockets#562]
I am using libwebsockets along with a game engine cocos2dx.    it was okay while I was using the older version v1.3,   but after I switched to the version v1.6, things are getting really wired, looks that error occured in client-handshake.c:

`  if (connect(wsi->sock, v, n) == -1 || LWS_ERRNO == LWS_EISCONN) {
`
after this line,  LWS_ERRNO has a value,  LWS_ERRNO==36,  and I checked it is  ENAMETOOLONG, what does that mean? I googled the whole internet and no clue about it. 
I sniffed the packet with the working version(v1.3) and the problem version(v1.6), and the only difference between them is the extension header:
   Sec-WebSocket-Extensions: x-webkit-deflate-frame,deflate-frame\r\n (v1.3)
    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits,deflate_frame\r\n (v1.6)
and it seems this is not the problem.

I tried the test program lib libwebsockets-test-client to connect to  libwebsockets-test-server, sometimes it works fine(after a reboot maybe), some times it also return error code 36 and the 56(which is Invalid request code, maybe caused by errno 36?).   if I compile libwebsockets to ".a" static library and use it in the game engine, it always has this wired error code.   I asked the game engines guys and they have no idea what it is, I pasted the log below:

```
[WebSocket::init] _host: xxx.com, _port: 80, _path: /

WebSocket thread start, helper instance: 0x14e4ec10

NOTICE: Initial logging level 1023

NOTICE: Libwebsockets version: 1.6.0 6803e50

NOTICE: IPV6 not compiled in

NOTICE: libev support not compiled in

NOTICE:  mem: platform fd map: 19456 bytes

function id:245
NOTICE:  mem: per-conn:          268 bytes + protocol rx buf
// then things just went wrong.
```

**Comment by lws-team** [comment]
I never saw this problem... the fact you can get it with the test client though narrows it down a bit and suggests it's not related to the game engine part.

If it's coming at connect() that's also significant, if it's not consistently giving the symptom it sounds lke something uninitialized in the sockaddr arg to that.

- what platform is this, Linux?

- can you try current lws, say master branch, rather than v1.6?  Just try its test client.

**Comment by springrider** [comment]
thanks for the help, I am sure it's coming from the connect function, I print the errno before "connect()" and it's zero. 
I am cross-compiling libwebsockets on macbook,  target platform is armv7,arm64, i386, and x86_64.  
but I am testing it on iPhone Simulator so "i386" is used. 

I run  libwebsockets-test-client and  libwebsockets-test-server on mac. 

I tried to use the client to connect to a normal websocket server, but seems there is protocol issue, maybe it would be easier if I could use libwebsockets-test-client to connect to a normal websocket server. so we could know if it's the wrapper or libwebsocket caused the problem.

bin/libwebsockets-test-client xx.com --port=80 -d 1023   // xx.com is a normal nodejs+ws server.
```
[1465441797:9453] NOTICE:  mem: per-conn:          336 bytes + protocol rx buf
[1465441797:9453] NOTICE: dumb: connecting
[1465441798:0051] NOTICE: mirror: connecting
[1465441798:0578] ERR: lws_client_int_s_hs: fail protocol dumb-increment-protocol
[1465441798:0578] ERR: dumb: LWS_CALLBACK_CLIENT_CONNECTION_ERROR

```

**Comment by springrider** [comment]
another question is that what does ENAMETOOLONG(path name too long) means... why there is a "path name" while I am connect to a IP addrss.
how could I get more useful error information?    errno==36 makes no sense to me...

**Comment by lws-team** [comment]
No offense but connect() is not an lws function, it's provided by your OS[1].  Actually the libc or more likely the OS kernel is the guy setting errno to 36.

Now you mention this wrapper - isn't that most likely the problem?

Either way unless there's some evidence we feed connect() bad things - nobody has ever reported this issue until now - the solution is somewhere other than lws.

[1] Your OS is closed source so...

**Comment by springrider** [comment]
okay, since you never saw this problem,  I guess I need close this issue and try debug the wrapper throughly.     I didn't doubt the wrapper is because anyone else using this engine didn't report this problem... and the test client did show this error.  

anyway, thanks for your time :)
