### ISSUE TITLE
Is any version of libwebsocket thread-safe?

### ISSUE THREAD

**Issue by slend0225** [warmcat/libwebsockets#566]
I have a multi-thread program,  and two of those threads will do constructing a websocket instance by using `libwebsocket_client_connect`. 

I found several articles said libwebsocket is not thread-safe, but in issue #145 , it said it depends on what we have done to our program.

Problem is that when the two thread called `libwebsocket_client_connect` at almost the same time (difference less than 0.1 sec), and the servers are temporary not available (logs like below), it may cause program crash. 
```
[1466058845:8384] ERR: Unable to get host name from xxxxxx-xx-xxxxx-wsa-1.xxxxxx.com
[1466058845:8390] ERR: Unable to get host name from xxxxxx-xx-xxxxx-ws-1.xxxxxx.com
```

This two wsis are constructed with different struct protocol in the info struct when creating two contexts.

I am now use libwebsocket v1.5 3b3fa9e

I want to know that any further version of libwebsocket is thread-safe?
If not, is there any suggestions when we use libwebsocket in multi-thread program?

**Comment by lws-team** [comment]
Hm... you have three basic choices

 - use two unrelated contexts, one for each thread.  Then nothing cares.  If your two threads operate completely independently, that can work.

 - consolidate both clients into the same service thread (using the same context).

 - use something else other than lws that blocks

Actually client_connect is anyway asynchronous, he does not perform the connection before he returns.  He relies on later service actions to complete the connection.  So you probably do not need two different threads to call client_connect either.

It's more like you need to indicate that you want connections up... that can be done by signalling a single thread who is responsible for that and the service activity.  If you look at the test client he is working along those lines.

Lws is the opposite of threadsafe, he's designed to serialize everything into a single nonblocking service thread - that's it's "thing".  It's not an oversight or deficit that it's not threadsafe.  If you want to use it, you'll need to do your object synchronization outside of lws.
