### ISSUE TITLE
When message size increases in callback_dumb_increment, server stops working as expected

### ISSUE THREAD

**Issue by ogheorghies** [warmcat/libwebsockets#567]
When this patch is applied to test-server-dumb-increment, the frequency with which libwebsockets-test-server-extpoll sends increment messages increases from 20Hz to "as fast as possible":
https://github.com/ogheorghies/libwebsockets/commit/eca7c11579eb1b14188a9118f19e92bf2cd8d283

The "poll" call in test-server.c no longer appears to temporarily block, and quickly returns with the revents field is set to POLLOUT.

If the added prefix is smaller, this effect does not happen. Is this related to a protocol setting in the test server that I'm missing?

**Comment by lws-team** [comment]
For dumb increment, the protocol rx_buffer_size is set to 10.

This is also used to set the amount that can be sent at once in some lws versions.

If you increase it in the protocols[] definition to be more than what you want to send at once, you can avoid what you're seeing.

Also notice in dumb increment, he regulates his tx by checking more than 20ms actually passed, not simply that he came out of poll().

**Comment by ogheorghies** [comment]
Increasing rx_buffer_size did solve the issue - thanks!

Would it be correct/useful to add to @rx_buffer_size docs that the setting applies to both sending and receiving?

 * @rx_buffer_size: if you want atomic frames delivered to the callback, you
 *		should set this to the size of the biggest legal frame (for both sending
 *              and receiving) that you support.

**Comment by lws-team** [comment]
It's on my list to revisit how this works, it's awkward that the same number is used for rx buffering and tx chunking.
