### ISSUE TITLE
assert on server close + truncated send corner case

### ISSUE THREAD

**Issue by nyx** [warmcat/libwebsockets#573]
We have a modified version of libwebsockets with some specific platform compatibility changes based on: f1cf5bec53bd6cfd8011554340346b74e5157495 (release 1.6.0)

It seems that if you encounter a situation where you have a client connect and send that gets truncated  and pause processing of the client (either via a thread sleep or breakpoint) and close the connection on the server side that upon resuming processing on the client you hit this assertion in `output.c`:

https://github.com/warmcat/libwebsockets/blob/master/lib/output.c#L112

The scenario I believe plays out like this:
1. you establish a truncated send state on the client (we have configured a small `rx_buffer_size`)
2. immediately pause client processing via thread sleep or breakpoint
3. close the connection on the server side sending a close control code
4. resume client processing it reads the close control code, sees it did not initiate the close
5. client attempts to send close control code back to the server as per websocket protocol: https://github.com/warmcat/libwebsockets/blob/master/lib/client-parser.c#L389
6. client asserts b/c a new send is attempted with a truncated send in progress.

I realize our version is now getting pretty old, and we aim to upgrade it soon, however I wanted to share this scenario and get feedback regarding a potential solution which is to before step 5 check `wsi->trunc_len` and skip sending the close control code if non-zero. A nicer solution I'm sure exists that would allow the client to finish that truncated send before the close control code is sent.

I took at look around the latest libwebsockets code and found in `client-parser.c`: `user_callback_handle_rxflow` that allows that callback to decide to close the connection skipping the close. This callback doesn't exist in our version, but that is what I modeled my solution on.

Thanks for your time!

**Comment by lws-team** [comment]
I see the problem... I also think he should just kill the connection.  It's legal to do that any time in ws, since the reality is it could happen at any time.  Otherwise we might uselessly sit there completing a big truncated send nobody cares about.

**Comment by lws-team** [comment]
I guess your plan solved the problem, if not, please reopen.

**Comment by nyx** [comment]
I had prepared a little patch, but wasn't sure if you were interested in addressing the issue. If you are, I'll open a pull request.

**Comment by lws-team** [comment]
If there's something we should do, we should do it... from reading your initial post it sounded like this was already solved in master.  If it's not we should definitely fix it.

**Comment by nyx** [comment]
It seems that in master there's a new callback `user_callback_handle_rxflow` that allows programmers to opt to close the connection w/o the automatic `close` response, however it wasn't clear if the truncated send case I outlined was covered in master. I don't think it is.

**Comment by lws-team** [comment]
I pushed a tiny patch on master that looks like it should handle it, can you take a look and see if it meets your situation?

https://github.com/warmcat/libwebsockets/commit/226f89250036c47a29905d63a010fa7c94770086

**Comment by nyx** [comment]
that implements exactly what I ended up with except I wasn't aware of lws_partial_buffered :+1: thanks.
