### ISSUE TITLE
Compile error 3.5 gcc and 3.8 clang: __x86_64__ is not defined

### ISSUE THREAD

**Issue by robinrowe** [warmcat/libwebsockets#574]
With stricter compiler switch settings, you will get this error...

libwebsockets.h:1839:5: error: 
      '__x86_64__' is not defined, evaluates to 0 [-Werror,-Wundef]
#if __x86_64__
    ^

Bug fix is to use #ifdef instead of #if.

**Comment by lws-team** [comment]
Thanks, your fix is pushed on master + v2.0-stable.
