### ISSUE TITLE
about libwebsocket client with libev

### ISSUE THREAD

**Issue by xykcode** [warmcat/libwebsockets#579]
hi,I'm  using libwebsocket as server with libev. however, i want to connect to other server as client at the same time.  how to using libwebsocket as client with libev supported?

**Comment by lws-team** [comment]
On master mixed server + client in the same context is supported, but I have only tested it with libuv.

However making it work didn't really involve the event loop stuff, so it's definitely worth trying with libev.

Notice if using ssl on client, when mixing with server you must call this

https://libwebsockets.org/lws-api-doc-master/html/group__client.html#ga4f44b8230e6732816ca5cd8d1aaaf340

after vhost creation to init the client ssl context as well as the default server one on the vhost.

**Comment by xykcode** [comment]
ohhh. I mixed server + client without ssl, however,it does not work. should i using lws_service after lws_client_connect_via_info?could you give me some sample code?

**Comment by xykcode** [comment]
I have mixed server + client with libev now, but it just  connected to one server before libev loop or in a libev loop

**Comment by lws-team** [comment]
Sorry does that last comment mean there is a problem?

**Comment by xykcode** [comment]
yes,It will be blocked when you try to connecting more then one server in a libev loop,do you have some idea about it? or  am I using  incorrect?

**Comment by lws-team** [comment]
Since I can't see your code, it's hard to answer if you're "using it incorrect".

The way to use client connections is shown in test-server/test-client.c  He makes two simultaneous connections to the lws test server and that works fine.

If you're sure you're following that code correctly, please hack down your code to the minimum needed to show the problem and push it somewhere.

**Comment by xykcode** [comment]
I know that test-client works fine, because there has ratelimit_connects between lws_client_connect_via_info. But I don't know why ratelimit at there ,if made connection to other server per 0.01s, it will waiting by pthread_mutex_lock.


The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /global/zebra/code/c++/proj/test/bin/test/./test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[2016/07/13 11:58:49:4064] NOTICE: Initial logging level 7
[2016/07/13 11:58:49:4065] NOTICE: Libwebsockets version: 2.0.0 zebra@dev001-
[2016/07/13 11:58:49:4066] NOTICE: IPV6 not compiled in
[2016/07/13 11:58:49:4068] NOTICE: libev support compiled in and enabled
[2016/07/13 11:58:49:4068] NOTICE: libuv support not compiled in
[2016/07/13 11:58:49:4068] NOTICE:  Threads: 1 each 1048576 fds
[2016/07/13 11:58:49:4204] NOTICE:  mem: platform fd map: 8388608 bytes
[2016/07/13 11:58:49:4205] NOTICE:  Compiled with OpenSSL support
[2016/07/13 11:58:49:4205] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2016/07/13 11:58:49:4206] NOTICE: Creating Vhost 'default' port 3077, 1 protocols, IPv6 off
[2016/07/13 11:58:49:4207] NOTICE:  Listening on port 3077
[2016/07/13 11:58:49:4207] NOTICE:  mem: per-conn:          608 bytes + protocol rx buf
[2016/07/13 11:58:49:4209] NOTICE:  canonical_hostname = dev003
[2016/07/13 11:58:49:4220] NOTICE:  libev backend: epoll
[2016/07/13 11:58:50:4075] NOTICE: lws_protocol_init
connectionCount=1
connectionCount=2
connectionCount=3
connectionCount=4
connectionCount=5

^C
Program received signal SIGINT, Interrupt.
0x00007ffff7bccf7d in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff7bccf7d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007ffff7bc8d32 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00007ffff7bc8c38 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007ffff7799e61 in insert_wsi_socket_into_fds () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#4  0x00007ffff77a09c8 in lws_client_connect_2 () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#5  0x00007ffff779bc88 in lws_header_table_detach () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#6  0x00007ffff779f8d7 in lws_client_interpret_server_handshake () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#7  0x00007ffff77a055c in lws_client_socket_service () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#8  0x00007ffff7799928 in lws_service_fd_tsi () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#9  0x00007ffff77a91ab in lws_accept_cb () from /home/zebra/global/code/c++/proj/proj_userproxy/lib/libwebsockets.so.8
#10 0x00007ffff79b5587 in ev_invoke_pending () from /lib64/libev.so.4
#11 0x00007ffff79b878d in ev_run () from /lib64/libev.so.4
#12 0x0000000000447c49 in CWebsocketServer::loop (this=0x7fffffffddd0) at src/./websocketServer.cpp:533
#13 0x00000000004382c0 in CManager::loop (this=0x7fffffffdd00) at src/./manager.cpp:23
#14 0x000000000046dae4 in main (argc=1, argv=0x7fffffffe1c8) at src/./proj.cpp:23

**Comment by lws-team** [comment]
The ratelimit is there because your users might become upset if they went to bed not noticing they had disconnected (because, eg, your server was down) and used up all of their data allocation for the month for no useful result endlessly trying to connect to it.

Can you try it with cmake .. -DLWS_MAX_SMP=1 (the default), if that is what is going on?

Otherwise lws itself never uses pthreads...

**Comment by lws-team** [comment]
... I saw you're using v2.0, also try v2.0-stable branch or master.

**Comment by lws-team** [comment]
Can't help you debug it without more info...
