### ISSUE TITLE
Simple HTTP ping times out

### ISSUE THREAD

**Issue by stefanobider** [warmcat/libwebsockets#581]
In my application, the lws HTTP server that runs locally on the user's machine is pinged from javascript every 10 seconds. Javascript simply pings `http://localhost:5074/ping` and the HTTP server, on `LWS_CALLBACK_HTTP` simply returns a JSON containing some status parameters. However, in some cases this ping times out (takes more than 10s) for no apparent reason. The log states:
```
[2016/06/06 16:14:17:7566] NOTICE: lws_header_table_detach: wsi 0x102416de0: ah held 9s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:16:28:4099] NOTICE: lws_header_table_detach: wsi 0x102416de0: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:16:48:8089] NOTICE: lws_header_table_detach: wsi 0x1021134d0: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:16:59:0087] NOTICE: lws_header_table_detach: wsi 0x1021136a0: ah held 21s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:17:19:4078] NOTICE: lws_header_table_detach: wsi 0x1021134d0: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:17:39:8069] NOTICE: lws_header_table_detach: wsi 0x1021136a0: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:18:00:2058] NOTICE: lws_header_table_detach: wsi 0x107000670: ah held 21s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:18:20:6049] NOTICE: lws_header_table_detach: wsi 0x102228420: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:18:41:0039] NOTICE: lws_header_table_detach: wsi 0x1021134d0: ah held 21s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:19:01:4030] NOTICE: lws_header_table_detach: wsi 0x1021136a0: ah held 20s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:19:19:5037] NOTICE: lws_header_table_detach: wsi 0x1021134d0: ah held 18s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:19:19:7040] NOTICE: lws_header_table_detach: wsi 0x1021136a0: ah held 8s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:19:42:9346] NOTICE: lws_header_table_detach: wsi 0x1021134d0: ah held 12s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:19:57:9342] NOTICE: lws_header_table_detach: wsi 0x107e00300: ah held 15s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:20:18:3334] NOTICE: lws_header_table_detach: wsi 0x107e004d0: ah held 21s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
[2016/06/06 16:20:26:0494] NOTICE: lws_header_table_detach: wsi 0x107000670: ah held 8s, ah.rxpos 344, ah.rxlen 344, mode/state 2 4,wsi->more_rx_waiting 0
```

Here is a screenshot of Chrome's dev panel that graphically shows the successful pings (dots, about 200ms response time) and timeouts (longer lines, from 2 to ~20 seconds):
![screen shot 2016-07-06 at 16 20 21](https://cloud.githubusercontent.com/assets/18703460/16621162/920bf6d2-4395-11e6-95b7-42fda6a93df6.png)
What could it be?

**Comment by lws-team** [comment]
What lws version / platform is this?

Is it possible you're doing something on the server side that simply blocks?

It's something that happens after some time only, or can happen immediately?

**Comment by stefanobider** [comment]
lws 2.0, mac OS 10.10.
It happens only after some time, and the screenshot I attached is a very
typical outcome. It starts ok and then becomes slower.
On the server I'm really doing nothing fancy, in `LWS_CALLBACK_HTTP` I'm
simply writing a string status to the response and returning 0. I used to
do the same in an older version of the app using lws 1.3 and this never
happened.
I use the multi-threaded approach with `lws_service()` called periodically
(200ms period) from a separate thread. But how should I interpret the log?
As an example `ah held 20s` means that it took the lws server 20 seconds to
process the request?

2016-07-06 16:56 GMT+02:00 Andy Green <notifications@github.com>:

**Comment by lws-team** [comment]
It sounds like some kind of resource exhaustion.

"ah held" is a debugging number that tells how long the connection had hold of an ah "allocated headers" from the ah pool.

It's possible that's the resource being exhausted, there's a finite number of ah in a pool initialized at context creation time by info.max_http_header_pool ... maybe try setting that to 32 or 64 and see if the time taken to get the symptom increases accordingly (default is 16).

**Comment by stefanobider** [comment]
Here a comparison between 16 and 64 (I tried several times, the outcome is always almost the same):
  
![screen shot 2016-07-06 at 16 32 28](https://cloud.githubusercontent.com/assets/18703460/16646021/3b316d72-4428-11e6-8353-9ad7d796785d.png)
![screen shot 2016-07-07 at 09 46 51](https://cloud.githubusercontent.com/assets/18703460/16646029/43b17280-4428-11e6-96be-c989f34aade8.png)

It is indeed a bit better, but nothing substantial...

**Comment by lws-team** [comment]
Unfortunately as a library, most problems people see involve a mixture of the lib + the user code.  If the user code isn't forthcoming, that makes debugging kinda hard, because one guy has the symptom, the platform, the software to reproduce it and them problem, and the other guy has squat.

I made some JS that fetches test.html from the test apps every 10s

```
<html>
Fetching from server every 10s
 <script>
function req()
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.onreadystatechange = function() { 
        if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
            var lwsgs_user_check = xmlHttp.responseText;

		window.setTimeout(req, 10000);
        }
    }
    xmlHttp.open("GET", "/test.html", true);
    xmlHttp.send(null);
}

req();

 </script>
</html>
```

I fetched it via lwsws, it looks perfect.  Netstat shows two established connections only, and looking at /proc/[pid]/fd shows that stable.  One "loop" serving the file looks like this in the logs, using -d31

```
lwsws[27206]: fd=11, revents=1
lwsws[27206]: lws_header_table_attach: wsi 0x11b7530: ah (nil) (tsi 0)
lwsws[27206]: lws_header_table_attach: wsi 0x11b7530: ah 0x119df60: count 1 (on exit)
lwsws[27206]: lws_server_socket_service: 0x11b7530: rxpos:0 rxlen:0
lwsws[27206]: lws_server_socket_service: wsi 0x11b7530, ah->rxlen = 409
lwsws[27206]: lws_read: incoming len 409  state 0
lwsws[27206]: lws_handshake_server: wsi->more_rx_waiting=0
lwsws[27206]: lws_set_timeout: 0x11b7530: 0 secs
lwsws[27206]: No upgrade
lwsws[27206]: lws_union_transition: 0x11b7530: mode 2
lwsws[27206]: lws_handshake_server: wsi 0x11b7530: ah 0x119df60
lwsws[27206]: lws_ensure_user_space: 0x11b7530 protocol 0x11b2f60
lwsws[27206]: lws_ensure_user_space: 0x11b7530 protocol pss 0, user_space=0
lwsws[27206]: Method: GET request for '/test.html'
lwsws[27206]: lws_set_timeout: 0x11b7530: 20 secs
lwsws[27206]:  /usr/share/libwebsockets-test-server/test.html mode 32768
lwsws[27206]: lws_http_serve: ETAG match test.html /usr/share/libwebsockets-test-server
lwsws[27206]: lws_http_transaction_completed: wsi 0x11b7530
lwsws[27206]: lws_ensure_user_space: 0x11b7530 protocol 0x11b2f60
lwsws[27206]: lws_ensure_user_space: 0x11b7530 protocol pss 0, user_space=0
lwsws[27206]: lws_set_timeout: 0x11b7530: 60 secs
lwsws[27206]: lws_http_transaction_completed: wsi->more_rx_waiting=0
lwsws[27206]: lws_header_table_detach: wsi 0x11b7530: ah 0x119df60 (tsi=0, count = 1)
lwsws[27206]: lws_http_transaction_completed: 0x11b7530: keep-alive await new transaction
lwsws[27206]: lws_read: thinks we have used 0
lwsws[27206]: lws_read: read_ok, used 409
```

He serves it, preserves the connection by calling transaction completed (which sees it's http/1.1 keepalive), sees there is no next http header already buffered for the next transaction and so drops the ah immediately and leaves the connection alive, with a timeout of 60s, for the browser to use again.  I left it running for 400s with no problems, it looks like it will go on forever.

Can you try serving that test html fetching some static html the same way?  libwebsockets-test-server will do.

**Comment by stefanobider** [comment]
I will try to serve the file as suggest. But in the meantime, I would like to post here some snippets of my code, in case you see anything wrong (this is a simplified version that I'm using now to test):

Protocols definition and context creation:
```
static struct lws_protocols serverProtocols[] = {
  {
    "http-only",
    CallbackHttp,
    sizeof(sose::remote::WebSocket*),
    2048,
  },
  { NULL, NULL, 0, 0 } /* end */
};

/* ... */

struct lws_context_creation_info info;
memset(&info, 0, sizeof(info));
info.port = localServerPort_;
info.protocols = serverProtocols;
info.iface = NULL;
info.gid = -1;
info.uid = -1;
info.user = this;
info.options = 0;
//info.max_http_header_pool = 64;
serverContext_ = lws_create_context(&info);

/* ... */

// start service loop on separate thread
```

Service loop:
```
/* ... */
lws_service(serverContext_, 0);
/* ... */
// schedule next service 200ms in the future
```

Callback:
```
/* ... */
case LWS_CALLBACK_HTTP:
{
  if (len < 1) {
    lws_return_http_status(wsi, HTTP_STATUS_BAD_REQUEST, NULL);
    return -1;
  }
  
  if (lws_hdr_total_length(wsi, WSI_TOKEN_POST_URI)){
    return 0;
  }
  
  std::string path = std::string((char*) in);
  std::string responseType = "text/plain";
  std::string response = "hi.";
  int         responseCode = 200;
  
  n = sprintf((char *)ubuf,
              "HTTP/1.0 200 OK\x0d\x0a"
              "Content-Type: %s\x0d\x0a"
              "Access-Control-Allow-Origin: *\x0d\x0a"
              "Cache-Control: no-cache\x0d\x0a"
              "Connection: keep-alive\x0d\x0a"
              "Content-Length: %lu\x0d\x0a\x0d\x0a"
              "%s",
              responseType.c_str(),
              response.length(),
              response.c_str());
  
  lws_write(wsi, ubuf, n, LWS_WRITE_HTTP);
  return 0;
}
/*...*/
```

I realized that there was an error and the code was returning -1 everytime. Now it returns 0 and every request produces the log:
```
[2016/06/08 09:43:55:3085] WARN: Duplicated method
[2016/06/08 09:43:55:3085] NOTICE: lws_header_table_detach: wsi 0x102433e90: ah held 5s, ah.rxpos 344, ah.rxlen 344, mode/state 2 2,wsi->more_rx_waiting 1
```
In case of timeout, as before, the `ah held` part reports larger numbers

**Comment by lws-team** [comment]
If you look at how the test-server-http.c handles it, after completing an http transaction he does this

```
	/* if we're on HTTP1.1 or 2.0, will keep the idle connection alive */
try_to_reuse:
	if (lws_http_transaction_completed(wsi))
		return -1;

        return 0;
```

If you are on http/1.0 or http/1.1 with connection:close, after serving you must hang up the connection.  On http/1.1 with the default connection:keepalive from the client, you can recycle the connection.  On http/2 it's different again.  Using the code above lets you do the right thing whatever the client sent.

**Comment by lws-team** [comment]
Well... if that didn't solve it, please reopen.
