### ISSUE TITLE
ERR: Ran out of header data space

### ISSUE THREAD

**Issue by nixomose** [warmcat/libwebsockets#582]
This is weird, not sure where to start.

I have a little test webpage with this:

var connection = new WebSocket('ws://test-dev.example.com:25901', ['test']);

test-dev.example.com has two A records that do round robin dns to two machines called
test1.example.lan and test2.example.lan

When I run the above from firefox 47.0 I get "Ran out of header data space" from the console and firefox gives me an error "aborted" and it doesn't show me anything in the network console.

If I do the same thing from chrome 51.0.2704.106 it works fine.

The weird part is that if I go directly against the actual hostname on firefox it works fine.
like so...
var connection = new WebSocket('ws://test1.example.lan:25901', ['test']);

So something about the hostname used in the request differing from the canonical hostname, and only on firefox?

Do you have suggestions of how I can watch the wire and see what the difference in the request is on firefox?
I'm using firebug and it craps out before it shows me anything.

I'm using a build from v2.0-stable.

**Comment by mjmessina** [comment]
Sorry to respond on this one.
But we just hit this issue in production yesterday too.

If you run a debug build of your libwebsocket, you can see what each token is and what is blowing the header data space (the default was 1024).

The context has a setting max_http_header_data.  You can up the size if it is not a real issue and just something firefox is adding to the headers that blows the 1024 size.

**Comment by nixomose** [comment]
thanks a lot. it would have taken forever for me to work that out. I'll try it out.

**Comment by nixomose** [comment]
Well by gum that fixed it. thank you very much.
