### ISSUE TITLE
payload 128k, callback Is invoked more than once

### ISSUE THREAD

**Issue by blueonew** [warmcat/libwebsockets#585]
I would like to receive 128K message one time, 
but in fact, the protocol callback is fired many times while the reason is LWS_CALLBACK_RECEIVE,  
no ssl,  
I set LWS_MAX_SOCKET_IO_BUF  is 131072(128k) and the rx_buffer_size is 131072
 #define LWS_MAX_SOCKET_IO_BUF 131072

I want to know, Can  received 128k one time
thank you

**Comment by lws-team** [comment]
The RX buffer doesn't accumulate RX and then notify the user callback.... instead as the data comes in, it is passed to the user code.  From socket perspective, it will usually come in chunks related to the size of packets on the network.

If you want it all together at once, you need to copy it into your own buffer (and no need for huge lws RX  buffer then).

**Comment by blueonew** [comment]
Thanks,
The question is, how do I know that those data are spliced together? Each piece of data you have terminator.
 how to deal with What if I need to receive 10 messages with 128K data

**Comment by lws-team** [comment]
https://libwebsockets.org/lws-api-doc-master/html/group__wsstatus.html#ga08e9ee165fca503fd9427d55cfecac37

**Comment by blueonew** [comment]
lws_is_final_fragment?

**Comment by lws-team** [comment]
Yeah.... so you know when a fragment completes a message.

**Comment by blueonew** [comment]
OK,thanks
