### ISSUE TITLE
lws_write buff 131072,  crash

### ISSUE THREAD

**Issue by blueonew** [warmcat/libwebsockets#586]
lws_write  buff is set to 131072, websocket crash ,whether support this large length  
when i enlarge rx_buffer_size and LWS_MAX_SOCKET_IO_BUF to 131072, always crash

the crash log:
lwsts[558]: ****** 39f80 Sending new, pending truncated ...

**Comment by lws-team** [comment]
No that should be unrelated.

You may only do lws_write from the WRITEABLE callback.

If it cannot send what you have in one lump, lws caches it and sends it automatically as the socket becomes writeable.

You cannot start sending something new while it's doing that.  And, you won't get a WRITEABLE callback until it has finished doing it.  So just send things from the WRITEABLE callback.

**Comment by blueonew** [comment]
sorry , I make  a mistake,  have solved this problem now 
thanks
