### ISSUE TITLE
About LWS_CALLBACK_HTTP_DROP_PROTOCOL

### ISSUE THREAD

**Issue by ABruines** [warmcat/libwebsockets#588]
Hi Andy,

Ever since commit 7f92ee802c4ffd3802a5180469082d27f49fb462 the per session data in my application gets dropped in between LWS_CALLBACK_FILTER_HTTP_CONNECTION and LWS_CALLBACK_HTTP.
I've concluded that this is caused by LWS_CALLBACK_HTTP_DROP_PROTOCOL.

Are things going to stay like this? If so, doesn't this break backwards compatability (it does for me).
My application depends on per session data stored during LWS_CALLBACK_FILTER_HTTP_CONNECTION to be available on the next LWS_CALLBACK_HTTP.

**Comment by ABruines** [comment]
I was able to fix my user code - still, there may be others who depend on the old way. It took me a while to figure it out...

**Comment by lws-team** [comment]
The problem these changes are aimed at is that your connection may be http/1.1 or http/2, and now lws decides what protocol handler to use for http based on the URL it's servicing.

Without a stricter lifecycle about the pss, they can leak when the connection moves to a new URL and potentially a new protocol handler.  So now when it changes protocol. it calls to LWS_CALLBACK_HTTP_DROP_PROTOCOL on the old protocol if any so you can handle destroy functionality for the old pss.

HTTP is ultimately stateless you can't assume the next http activity is happening on the same / connection + pss, basically the pss lifetime is one http transaction.

An example of that is the messageboard lwsgs demo at https://libwebsockets.org/lwsgs/ , bits of the page around the session login etc are handled by URLs that map to the generic-sessions protocol and bits of the page that are related to doing the messageboard part are handled by URLs that map to the messageboard protocol.  In the browser, one http/1.1 keeplive connection may do both jobs... then there is no way to map one (protocol-specific) pss to the connection persistently.  So it has to create and destroy pss per http transaction.  (If what you're looking for is actually session semantics then have a look at lwsgs, which does session cookies even without a login).

If that seems buggy in this case, I'd be happy to hear more about it.

**Comment by ABruines** [comment]
> "basically the pss lifetime is one http transaction"

I was under the assumption that the transition from LWS_CALLBACK_FILTER_HTTP_CONNECTION to LWS_CALLBACK_HTTP was part of that (initial) single http transaction.

I understand the statelessness of HTTP and I've been working my way around that 'problem' in my application too.

In my specific case I am using libwebsockets to remotely arm/disarm/monitor a home security system.
So I am particularly interested that communications are as secure as possible.
This also means I cannot use session cookies because I do not want to depend on (or trust) anything happening on the client side.

My implementation handles http sessions is by generating a server side object for each client that contains a unique session id. That session id is then stored inside the per session data and passed back to each client by means of server redirects (HTTP 302 status code).

My LWS_CALLBACK_HTTP implementation expects to find the session id in either the DELETE or REFERER http header for any subsequent http request.

On top of that my application requires each client to connect using a client SSL certificate (that is only allowed to be associated with one session object at a time). The combination of session object and its associated peer certificate allows my application to make http stateful enough for my purpose :)

The connection with LWS_CALLBACK_HTTP_DROP_PROTOCOL is that I was using LWS_CALLBACK_FILTER_HTTP_CONNECTION to create my session object and store the session id in the pss. Then later during LWS_CALLBACK_HTTP it used the id stored in the pss to obtain the session object.

My current solution if to forego LWS_CALLBACK_FILTER_HTTP_CONNECTION and create my session object in LWS_CALLBACK_HTTP.

**Comment by ABruines** [comment]
The final solution for my user code is to use LWS_CALLBACK_HTTP_BIND_PROTOCOL and LWS_CALLBACK_HTTP_DROP_PROTOCOL to create and delete the reference to my session object in the per session data, instead of using  LWS_CALLBACK_FILTER_HTTP_CONNECTION and LWS_CALLBACK_CLOSED_HTTP...

Just like you intent for them to be used ;)

**Comment by lws-team** [comment]
Great... you're also able to extend the server to other http protocols without problems that way.

About generic-sessions session cookies though, they are 160-bit random numbers issued by the server.  When a client says it has a cookie, the generic-sessions stuff checks that cookie against its server-side sqlite db of live cookies it has issued before accepting it.  The cookies have a lifetime and the server side prunes his db regularly to remove expired cookies.  So an attacker must guess or acquire a live 160-bit number (and acquiring it is not that easy assuming the clients must use SSL and your site doesn't allow XSS).

**Comment by ABruines** [comment]
Yes, you are correct about the safety of session cookies. But what if the client does not allow us to set a cookie at all...

Perhaps I should have been more specific when I said I did not want to trust/rely on anything happening on the client while talking about safety the line before.
