### ISSUE TITLE
Ping Pong Implemetation

### ISSUE THREAD

**Issue by Arun19921991** [warmcat/libwebsockets#589]
Hi,

I am using libwebsockets 1.7 version, And it works fine too.I have a small doubt on Ping-Pong implementation.I need my Websocket client to respond for the Websocket Server Ping.Is that possible ?

**Comment by lws-team** [comment]
It should automatically reply back with a PONG and the same payload the PING came in with, if any.

The RFC defines that's what it should do, so the library takes care of it.
