### ISSUE TITLE
about http client

### ISSUE THREAD

**Issue by xykcode** [warmcat/libwebsockets#591]
how can i make a http client request?  lws_client_connect_via_info can do this, but in case LWS_CALLBACK_RECEIVE_CLIENT_HTTP, I do not know the request path, so I don't know how to parse it.
Can you help me? or is there any sample about http client?

**Comment by xykcode** [comment]
I try to use lws_hdr_copy get the request path in case LWS_CALLBACK_RECEIVE_CLIENT_HTTP, it crash in function  lws_hdr_total_length.

**Comment by lws-team** [comment]
If you set info.method to "GET" and info.path to the request path, you can get the http client connection how you like.  test-client.c shows how to do this.

The URI path of the request is kept around for a while in an accessible way (fake header _WSI_TOKEN_CLIENT_URI) but only for the period while it's creating the GET request.

By the time the response payload is coming, the original URI used for the GET is lost (the headers stuff was used to process the incoming headers of the response).

One way around it is set the .userdata in the lws_client_connect_info to point to your own struct, and point to a copy of the URl path or some other identification information there.  That will uniquely turn up as user_data in the callbacks on that wsi then.

**Comment by lws-team** [comment]
If you're still stuck, please reopen.
