### ISSUE TITLE
lws_spa_create() -> (NOTICE: Name too long)

### ISSUE THREAD

**Issue by mradul17** [warmcat/libwebsockets#594]
---test-server-http.c----
 
when i used this curl cmd for post .wav file
curl  -XPOST -F  "file=@/home/mradul/Desktop/adi.wav" 'http://localhost:7681'
adi.wav successfully posted and  store in /tmp

But I when used this 
curl --request POST --data-binary  "@/home/mradul/Desktop/adi.wav" 'http://localhost:7681'.
[2016/08/03 13:14:30:2600]NOTICE: lws_spa_create: Created SPA 0xfb4b10.
[2016/08/03 13:14:30:2600] NOTICE: Name too long.
[2016/08/03 13:14:30:2601] NOTICE: closing connection at lws_read bail.

**Comment by lws-team** [comment]
Hm... what does curl actually tell lws it is sending?

When I look with tcpdump at what comes from curl with `echo -e '\x03\xF1' | curl -X POST --data-binary @- http://foo.com`, he claims he's sending `x-www-form-encoded`, ie, name=vale&name1=value content.  If you send a binary wav file, lws correctly chokes on an excessive "name=" part.

```	0x0000:  4500 00c3 307d 4000 4006 4e8c c0a8 02d8  E...0}@.@.N.....
	0x0010:  1715 e096 ab90 0050 ecb6 c0cf fa7d 71cd  .......P.....}q.
	0x0020:  8018 00e5 4939 0000 0101 080a 06d1 f1c6  ....I9..........
	0x0030:  0c5c 5b07 504f 5354 202f 2048 5454 502f  .\[.POST./.HTTP/
	0x0040:  312e 310d 0a48 6f73 743a 2066 6f6f 2e63  1.1..Host:.foo.c
	0x0050:  6f6d 0d0a 5573 6572 2d41 6765 6e74 3a20  om..User-Agent:.
	0x0060:  6375 726c 2f37 2e34 372e 310d 0a41 6363  curl/7.47.1..Acc
	0x0070:  6570 743a 202a 2f2a 0d0a 436f 6e74 656e  ept:.*/*..Conten
	0x0080:  742d 4c65 6e67 7468 3a20 330d 0a43 6f6e  t-Length:.3..Con
	0x0090:  7465 6e74 2d54 7970 653a 2061 7070 6c69  tent-Type:.appli
	0x00a0:  6361 7469 6f6e 2f78 2d77 7777 2d66 6f72  cation/x-www-for
	0x00b0:  6d2d 7572 6c65 6e63 6f64 6564 0d0a 0d0a  m-urlencoded....
	0x00c0:  03f1 0a                                  ...
```

So what is it you think lws should do about that?

**Comment by lws-team** [comment]
AFAICS lws acts reasonably for what curl gives it, so nothing to do here.
