### ISSUE TITLE
lws_callback_on_writable_all_protocol() not triggering callback

### ISSUE THREAD

**Issue by sbehnsen** [warmcat/libwebsockets#595]
I have been playing with libwebsockets for a little while now.

I am using lwsws with the lws-mirror plugin as a Server and am trying to implement a simple client in C (acutally running on the same machine). I have used `test-client.c` as a basis for my tests.

My issue is how to tell the lib to start sending data. I understand that `lws_callback_on_writable_all_protocol()` should do the trick, but no callback is called if I use it... 

`lws_callback_on_writable()` causese the `CLIENT_WRITEAB`LE callback to be called, but since this function needs the wsi data, I can not call it from outside the callback function. 

I tried to find a simple example how to send one message (from C), but I did not find anything (from  HTML this is simpel, but from C I am having trouble...
The only way I got this working is to call `lws_callback_on_writable() `in the connection callback and then continously at the end of the `CLIENT_WRITABLE `callback, but this creates a lot of uneccessary CPU use... (IMHO not a good/viable solution).  Again according on how I understand the docs `lws_callback_on_writable_all_protocol()` should trigger the `CLIENT_WRITEABLE `or `SERVER_WRITEABLE `callbacks to be called. But this does not seem to happen...

Any ideas? A simple example would be great.

**Comment by lws-team** [comment]
> lws_callback_on_writable_all_protocol() should do the trick, but no callback is called if I use it...

What does your code look like that does that?

Because, eg, the mirror test code you mentioned that uses lws_callback_on_writable_all_protocol() works fine, right?

**Comment by sbehnsen** [comment]
In my main loop I call: 

```
		sprintf (teststr, "Test =%d", t++);
			send_len = strlen (teststr);
			strncpy (&sendbuf[LWS_PRE +1], teststr, send_len);
			log (LOGSTATUS, "Data to send = %s", &sendbuf[LWS_PRE +1]);
			ret = lws_callback_on_writable_all_protocol(context, &protocols[0]);
```
before calling `lws_service(context, 500);
`
where protocols is:
```

static struct lws_protocols protocols[] = {
	{
		"fake-nonexistant-protocol,lws-mirror-protocol",
		callback_lws_mirror,
		0,
		128,
	},
	{ NULL, NULL, 0, 0 } /* end */
};
```

The callbacks in `callback_lws_mirror()` :

```
static int callback_lws_mirror(struct lws *wsi, enum lws_callback_reasons reason,
		    void *user, void *in, size_t len)
{
	unsigned char buf[LWS_PRE + 4096];
	char*	data[512];
	int l = 0;
	int n;

	switch (reason) {
	case LWS_CALLBACK_CLIENT_ESTABLISHED:
		lwsl_notice("mirror: LWS_CALLBACK_CLIENT_ESTABLISHED\n");
  		// including the line below will make it work in a busy loop
		// lws_callback_on_writable(wsi);
		break;

	case LWS_CALLBACK_CLOSED:
		lwsl_notice("mirror: LWS_CALLBACK_CLOSED\n");
		wsi_mirror = NULL;
		break;

	case LWS_CALLBACK_CLIENT_RECEIVE:
		memset((char*)data, 0x00, 512);
		strncpy ((char*)data, (char*)in, len);
		log (LOGSTATUS, "Receive...%d =(%s)", len, data);
		break;

	case LWS_CALLBACK_SERVER_WRITEABLE:
		lwsl_notice("server_writable callback\n");
		break;

	case LWS_CALLBACK_CLIENT_WRITEABLE:
		lwsl_notice("client_writable callback\n");


		if (send_len > 0)
		{
			n = lws_write(wsi, &sendbuf[LWS_PRE+1], send_len, LWS_WRITE_TEXT);
			log (LOGSTATUS, "send %d bytes from %d", n, send_len);
			send_len -= n;
			if (n < 0)
				return -1;
			if (n < l) {
				lwsl_err("Partial write LWS_CALLBACK_CLIENT_WRITEABLE\n");
				return -1;
			}
			//lws_callback_on_writable(wsi);
		}
  		// including the line below will make it work in a busy loop, if called once from the connect callback
  		//lws_callback_on_writable(wsi);
		break;

	default:
		break;
	}

	return 0;
}
```

**Comment by lws-team** [comment]
The code is helpful to understand what you're doing thanks.

I added something similar to the test client, on master.  Use the -m switch to make it create 3 x "dumb" protocol client connections to the test server, and periodically call lws_callback_on_writable_all_protocol() on that protocol.  Three client writable callbacks are coming, so I think this works fine, at least on master.

Can you try it?

**Comment by sbehnsen** [comment]
OK, your example works. I have stripped it down a lot and it stil works (if build on the target)
I have found something strange, which is probably the reason for my Problem with `lws_callback_on_writable_all_protocol(), `even though it quite strange.

If I build the test-client on the target (it a raspberry pi) it works as expected. However if build on my cross development System (Windows with Eclipse CDT) it behaved differently (and it does not work correctly...). The strange thing is that I still get a working excutable which works in other Scenarios, but simply not the ome using `lws_callback_on_writable_all_protocol()`
libwebsockets and libuv were build on the target and then copied to my cross development System, so they are the same... Must be some other lib or Compiler Option...
I will investigate, but this may take some time...

**Comment by lws-team** [comment]
Are plugins enabled?  Maybe rather than the cross build itself, the difference is related to local install action vs copying things over from the build host.  Eg previously installed native-built plugin of same protocol name is being picked up at runtime even after you copied over cross-built rest of it.  Just a guess.

To debug it need to have lws_callback_on_writable_all_protocol() dump his point of view in detail and compare dumps run on native and cross.

**Comment by sbehnsen** [comment]
I found it :-)))))

On the cross environment `LWS_USE_UNIX_SOCK` is not defined. That causes things to break.

A simple `#define LWS_USE_UNIX_SOCK` solved my problems.
I can not tell if this is an issue in libwebsocket to be solved or if this is only an issue because I am cross-developing... (which I guess other are a well...). I guess thats you to look at. 

Anyway, thank you for help. I have a solution that works for me...

**Comment by lws-team** [comment]
Great... but I don't use unix sockets in the test app, and it's not defined here, without problems.  So I am not sure what to do about that.  But I am glad you're working --> close the issue.
