### ISSUE TITLE
Server can't accept any connections on windows

### ISSUE THREAD

**Issue by Assert1** [warmcat/libwebsockets#596]
using test-server

server.c:1873
if (!(pollfd->revents & LWS_POLLIN) || !(pollfd->events & LWS_POLLIN))
	break;

at connection from test-client
pollfd->revents==8
pollfd->events==0
and this always breaks

**Comment by lws-team** [comment]
What lws version is this?  If master how recent is it?

**Comment by Assert1** [comment]
master

**Comment by Assert1** [comment]
configured using CMake 3.5 for MSVC10

**Comment by Assert1** [comment]
same thing for 2.0 stable
both configured without SSL

**Comment by Assert1** [comment]
checked with current master, same thing

**Comment by lws-team** [comment]
Hm... v2.0-stable should be fine at least.

What happens if you go back to master and try

`git reset --hard 41c250e`

**Comment by Assert1** [comment]
41c250e works

**Comment by Assert1** [comment]
now works with this path, thank you

**Comment by lws-team** [comment]
Thanks a lot for the debugging, I added the change to the ESP8266 patch and updated master.
