### ISSUE TITLE
LWS_CALLBACK_CLOSED_HTTP called when connecting via reverse ssh tunnel

### ISSUE THREAD

**Issue by p0fi** [warmcat/libwebsockets#599]
Hello,

recently I noticed a strange behavior. When connecting from the local network to libwebsockets everything is fine, the webserver serves the necessary files via HTTP and opens the websocket connection just fine.
But once I try to connect via a reverse ssh tunnel from outside the local network there are 3 callbacks called which are not called from the local network. The callbacks are:  
LWS_CALLBACK_DEL_POLL_FD
LWS_CALLBACK_CLOSED_HTTP
LWS_CALLBACK_WSI_DESTROY

After this happens, the bigger files are not delivered (500kb and 1,5mb) and the connections seems to hang at some point. After this events there are no more HTTP connections or WS connections possible. The question is why these callbacks are called and how to handle them to avoid this blocking state of the server?

If I add gzip compression to the files wich makes them all under 200 kb each, everything works just fine too. Im wondering why that is the case and how I could work around it.

edit: Im working with v2.0.1

thanks!

**Comment by lws-team** [comment]
You don't mention the lws logs anywhere... the callbacks are related to the connection closing, the logs might help understand why.  You can increase the log verbosity.

Lws itself doesn't have any issue about serving large files on slow links (https://libwebsockets.org itself runs on lws).  It sounds like maybe file size == time, and you hit a timeout, the logs will say if so.

**Comment by p0fi** [comment]
Thanks for the response!

Interestingly I found out that using v2.0.2 solves the issue which was in the 2.0.1.
It would be interesting to understand what was the problem so I enabled the logs. The output is absolutely massive so I hope I get the right parts:  

When the actual close callback gets called it looks like this:
```
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 1556)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=19, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103008be0 partial adv 20 (vs 1576)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=20, revents=17
Aug  9 10:57:36  lwsts[12643] <Debug>: lws_server_socket_service: wsi 0x101e17520 read 0
	
Aug  9 10:57:36  lwsts[12643] <Info>: lws_server_socket_service: read 0 len
Aug  9 10:57:36  lwsts[12643] <Info>: lws_close_free_wsi: real just_kill_connection: 0x101e17520 (sockfd 20)
Aug  9 10:57:36  lwsts[12643] <Info>: remove_wsi_socket_from_fds: removing same prot wsi 0x101e17520
Aug  9 10:57:36  lwsts[12643] <Info>: remove_wsi_socket_from_fds: wsi=0x101e17520, sock=20, fds pos=5, end guy pos=6, endfd=0
[2016-08-09 10:57:36.253] [WEBSOCKET] [debug] LWS_CALLBACK_CLOSED_HTTP
Aug  9 10:57:36  lwsts[12643] <Debug>: calling back CLOSED_HTTP
[2016-08-09 10:57:36.254] [WEBSOCKET] [debug] LWS_CALLBACK_CLOSED_HTTP
Aug  9 10:57:36  lwsts[12643] <Info>: lws_header_table_detach: wsi 0x101e17520: ah 0x10406abf8 (tsi=0, count = 4)
Aug  9 10:57:36  lwsts[12643] <Notice>: lws_header_table_detach: wsi 0x101e17520: ah held 8s, ah.rxpos 464, ah.rxlen 464, mode/state 2 4,wsi->more_rx_waiting 0
Aug  9 10:57:36  lwsts[12643] <Debug>: lws_free_wsi: 0x101e17520, remaining wsi 4
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=16, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103304dd0 partial adv 20 (vs 996)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=18, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 1536)
```

on other occasions one can find something like that:
```
...
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=18, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 576)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=19, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103008be0 partial adv 20 (vs 596)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=16, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103304dd0 partial adv 16 (vs 16)
Aug  9 10:57:36  lwsts[12643] <Info>: ***** 3304dd0 partial send completed
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=18, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 556)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=19, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103008be0 partial adv 20 (vs 576)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=16, revents=4
Aug  9 10:57:36  lwsts[12643] <Debug>: lws_set_timeout: 0x103304dd0: 20 secs
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103304dd0 new partial sent 20 from 4096 total
Aug  9 10:57:36  lwsts[12643] <Info>: choked before able to send whole file (post)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=18, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 536)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=19, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103008be0 partial adv 20 (vs 556)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=16, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103304dd0 partial adv 20 (vs 4076)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=18, revents=4
Aug  9 10:57:36  lwsts[12643] <Info>: 0x103007d30 partial adv 20 (vs 516)
Aug  9 10:57:36  lwsts[12643] <Debug>: fd=19, revents=4
...
```

can you see something in this logs?

**Comment by lws-team** [comment]
> Aug  9 10:57:36  lwsts[12643] <Info>: 0x103304dd0 new partial sent 20 from 4096 total

The amount you can send at once is the smaller of the protocol .rx_buffer_size and (on master anyway) the context creation info's .pt_serv_buf_size.

It looks like the protocol .rx_buffer_size you're using doesn't relate to the big things you want to send, you're basically restricting what can be sent at one time to 20 bytes atm.

> Aug  9 10:57:36  lwsts[12643] <Info>: lws_server_socket_service: read 0 len

it looks like maybe the peer timed you out.

**Comment by p0fi** [comment]
Well thanks a lot! the rx buffer size of the http handler seemed weird if to take a closer look.
```
 /* first protocol must always be HTTP handler */
    {
        "http-only",		/* name */
        callback_http,		/* callback */
        sizeof (struct per_session_data__http),	/* per_session_data_size */
        0,			/* max frame size / rx buffer */
        0,
        NULL
    }
```

If I increase that from 0 to basically anything it works also with v2.0.1 over the reverse ssh tunnel!
Thanks for your help!

**Comment by lws-team** [comment]
Yes it was a bug fixed some months ago... glad you're working.
