### ISSUE TITLE
LWS_CALLBACK_CLOSED_CLIENT_HTTP is not called during lws_close_free_wsi

### ISSUE THREAD

**Issue by Assert1** [warmcat/libwebsockets#600]
Because lws_client_interpret_server_handshake sets mode from LWSCM_HTTP_CLIENT to LWSCM_HTTP_CLIENT_ACCEPTED, but LWS_CALLBACK_CLOSED_CLIENT_HTTP called only for LWSCM_HTTP_CLIENT.

I am expected LWS_CALLBACK_CLOSED_CLIENT_HTTP in the end of connection, like LWS_CALLBACK_CLOSED_HTTP at the server to free session resources...

**Comment by lws-team** [comment]
I updated yesterday's patch to ensure LWS_CALLBACK_CLOSED_CLIENT_HTTP is called for any of the connection states related to client where we are still in http mode when we close.
