### ISSUE TITLE
Char array too small

### ISSUE THREAD

**Issue by lcta0717** [warmcat/libwebsockets#601]
In server.c, function lws_handshake_server, char protocol_name, I am getting a handshake failure because the array is too small (32 bytes). The name I'm using (I can't change it) is more than 32 chars, so when the copy happens my protocol name gets split into 2 protocol names, and thus fails.
Can someone update the array to a bigger size (64 worked for me), or put a check for the name size?

**Comment by lws-team** [comment]
I increased it to 64 on master.... there is already a bounds check for this array, it stops composing the protocol name into it if it reaches the length of the array and proceeds with the truncated name, so I think that's already okay.

**Comment by lcta0717** [comment]
Will that ever make it to the 2.0 branch?

**Comment by lws-team** [comment]
Also on v2.0-stable now
