### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by jsella** [warmcat/libwebsockets#608]
I'm attempting to access a custom header passed by a client, in a websocket server based on libwebsockets 1.7.5, but have been unsuccessful in accessing them. In  LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION, I'm able to iterate through the headers that the library tracks, but the custom header is missing by this stage (as described in the documentation).

Any direction on how to access a custom header would be appreciated.

**Comment by lws-team** [comment]
1) Add it to ./lib/lextable-strings.h after "http/1.0"

2) Add a corresponding WSI_TOKEN_MYHEADER in ./lib/libwebsockets.h after WSI_TOKEN_HTTP1_0

3) Read the instructions at the top of ./lib/minilex.c.  Following them will generate a new ./lib/lextable.h which contains an updated parser state machine including your new header.

4) Recook lws

**Comment by lws-team** [comment]
BTW Is your icon an Ichigo chibi?  If so 22nd is going to be a big day...

**Comment by jsella** [comment]
Thanks for the instructions. That should do it.

Ha, yes it is. :) All things must come to and end.
