### ISSUE TITLE
Website Issue

### ISSUE THREAD

**Issue by urkle** [warmcat/libwebsockets#615]
the integrity hashes on your JS script tags are incorrect.  Specifically the galleria-1.4.2.min.js has an extra "[" at the end of the integrity hash.  This causes Firefox to (correctly) reject the script, which end up causing severe layout issues on the site.

**Comment by lws-team** [comment]
Thanks for letting me know... I removed the stray [, but there's no symptom here on firefox.  I guess it has it cached locally in my case.  And it passed the Mozilla observatory tests, but I guess it just looked for existence of the hash.
