### ISSUE TITLE
struct lws_context_creation_info after calling lws_create_context(info)

### ISSUE THREAD

**Issue by eladn** [warmcat/libwebsockets#616]
1. Can I free `info` after calling lws_create_context(info) ?
2. Can I free buffers pointed by fields of `info` (ex: iface, ssl_cert_filepath, ssl_private_key_filepath)?

**Comment by lws-team** [comment]
1) Yes you can free the context creation info struct itself afterwards

2) No most of the things you point to in info are expected to exist at least as long as the context, to avoid needless mass duplication of what are basically static objects.

lwsws JSON config deals with this by appending all strings and structs generated by parsing in the config to a small heap that's freed on exit; all the pointers in the info point in there.

If you don't have much dynamic content in the info (usually eg, the protocol structs and the mounts are written in structs in the code and never go out of scope) you just need to take care about whatever strings you gave in the info.
