### ISSUE TITLE
RECEIVE_CLIENT_HTTP after CLOSED_CLIENT_HTTP

### ISSUE THREAD

**Issue by Assert1** [warmcat/libwebsockets#620]
I am experienced an unexpected RECEIVE_CLIENT_HTTP callback after CLOSED_CLIENT_HTTP. Whole callback sequence looks like:
LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER < as expected
LWS_CALLBACK_CLIENT_HTTP_WRITEABLE < as expected
LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP < as expected
LWS_CALLBACK_RECEIVE_CLIENT_HTTP < as expected
  -> lws_http_client_read < as expected
    -> LWS_CALLBACK_COMPLETED_CLIENT_HTTP < expected no more data from this point
LWS_CALLBACK_CLOSED_CLIENT_HTTP < expected no more callbacks to this session
LWS_CALLBACK_RECEIVE_CLIENT_HTTP < unexpected callback with zero data length

MacOS X 11.4, XCode 7.3.1, On branch master
Trace of callbacks lws_callback_reasons is in attachment:
[log.txt](https://github.com/warmcat/libwebsockets/files/455535/log.txt)

This is not a critical bug, and i am used a workaround, but may be you are interested in...

**Comment by lws-team** [comment]
Thanks for letting me know... does the above push solve it?
