### ISSUE TITLE
Server wsi teardown in lws_adopt_socket_vhost may not be complete

### ISSUE THREAD

**Issue by github-user-7** [warmcat/libwebsockets#621]
Found this with Valgrind using v2.0 stable source, looked at latest git source and I think the issue is still there.

I could be mistaken, but it looks like in server.c, lws_adopt_socket_vhost() there is a path where the wsi can get freed even though it is still left on the timeout list.  Then when processing timeouts it would access freed memory.

It calls lws_set_timeout(), then if LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED does not return 0 it closes the socket, frees the wsi directly but doesn't seem to take it off the timeout list.  Is this the case?  Not sure why static analysis wouldn't have caught this.  Maybe it just needs a call to lws_remove_from_timeout_list()?

**Comment by lws-team** [comment]
Well spotted... I pushed a fix to back the timeout off the list correctly on that path, on master and v2.0-stable.  Static analysis (coverity) could have spotted it but I guess it's not that trivial to see that a pointer was left on a linked list after the object is destroyed.

The path is a bit unusual in that we didn't assemble the wsi fully enough to use the generic close function, which normally takes care of the timeout list.  So it must be done by hand there.

**Comment by github-user-7** [comment]
Thanks
