### ISSUE TITLE
Make with jsmn

### ISSUE THREAD

**Issue by vova01987** [warmcat/libwebsockets#623]
Hello. I want to make libwebsocket-test-server with jsmn JSON parser. I include jsmn.h in test-server.c. But then I try to make all, I have an errors: undefined reference to `jsmn_init', `jsmn_parse' (defined in jsmn.h). How can I add jsmn.h and jsmn.c in libwebsockets project? I try to edit CMakeLists.txt, but didn't understand where to add.

**Comment by lws-team** [comment]
You should build and install lws without changes... that will install a dynamic library libwebsockets.so.  Run `sudo ldconfig` one time so your linux system notices the new library.

Then copy test-server.c to a new project, and build with make or whatever you choose, linking with -lwebsockets

**Comment by vova01987** [comment]
Thank you!
But as I understand, libwebsocket-test-server links statically with libwebsocket library, so I can use only one test-server.bin without library.so. And test-server uses also test-server-dumb-increment.c, test-server-http.c, etc. I made changes to test-server.c and test-server-dumb-increment.c and then use "cmake .." and "make" to all the project. Is's OK.
Then I add #include jsmn.h into test-server.c, and add "test-server/jsmn.c" into CMakeLists.txt, section "test-server" (strings after 975). If I add "test-server/jsmn.c" at string 981 after "test-server/test-server-echogen.c" - error is the same (undefined reference to jsmn_init', jsmn_parse'). But if I add "test-server/jsmn.c" before "test-server/test-server-echogen.c", error changes to "undefined reference to `callback_lws_echogen'".

**Comment by lws-team** [comment]
> But as I understand, libwebsocket-test-server links statically with libwebsocket library

It can either link statically or dynamically, there's no special requirement for either.

You should definitely get away from following the build mechanism of the built-in test apps, which is about what is convenient for the library, and make your own separate project that either binds dynamically to libwebsockets.so, or feed it libwebsockets.a at link-time if you have some reason you want to build a static link version of your project.

> add "test-server/jsmn.c" into CMakeLists.txt,

Wrong way!  Turn back ^^

Don't do that.  Build and install lws as one, one-time action.  Then copy the test server pieces to your own project and build them standalone with either -lwebsockets or libwebsockets.a at link-time.

You do not need any CMake at all, unless you want it: you can make a script or simple Makefile for your project how you like independent of lws except the link bringing it in.

**Comment by vova01987** [comment]
Thank you very much! I understand.
