### ISSUE TITLE
Make test-server separately

### ISSUE THREAD

**Issue by vova01987** [warmcat/libwebsockets#625]
Hello!
I try to make test-server with static libwebsockets.a as you described in https://github.com/warmcat/libwebsockets/issues/623. I copy dir https://github.com/warmcat/libwebsockets/tree/master/test-server
and add libwebsockets.a there. Then add Makefile to build test-server:
libwebsockets-test-server: test-server.c test-server-http.c test-server-dumb-increment.c test-server-mirror.c test-server-status.c test-server-echogen.c jsmn.c 
			gcc -static test-server.c test-server-http.c test-server-dumb-increment.c test-server-mirror.c test-server-status.c test-server-echogen.c jsmn.c -L. -lwebsockets -o lws_test_server

But I take a lot of errors like this:
libwebsockets.c:(.text+0x4c9): undefined reference to `pthread_mutex_lock'
pollfd.c:(.text+0x42b): undefined reference to `pthread_mutex_lock'
ssl.c:(.text+0x31d): undefined reference to `SSL_read'
extension-permessage-deflate.c:(.text+0x450): undefined reference to `deflate'
test-server-http.c:(.text+0x15eb): undefined reference to `X509_verify_cert_error_string'

And etc.
Can I get a HowTo build libwebsockets-test-server in this way?

**Comment by lws-team** [comment]
`gcc test-server.c test-server-http.c test-server-dumb-increment.c test-server-mirror.c test-server-status.c test-server-echogen.c  -lwebsockets -o lws_test_server -lssl -lcrypto`

**Comment by vova01987** [comment]
Some errors still remain:
./libwebsockets.a(extension-permessage-deflate.c.o): In function `lws_extension_callback_pm_deflate':
extension-permessage-deflate.c:(.text+0x5f): undefined reference to `deflateEnd'
extension-permessage-deflate.c:(.text+0x36c): undefined reference to `deflateEnd'
extension-permessage-deflate.c:(.text+0x3e0): undefined reference to `deflateInit2_'
extension-permessage-deflate.c:(.text+0x450): undefined reference to `deflate'
extension-permessage-deflate.c:(.text+0x696): undefined reference to `inflate'
extension-permessage-deflate.c:(.text+0x726): undefined reference to `inflate'
extension-permessage-deflate.c:(.text+0x783): undefined reference to `inflateEnd'
extension-permessage-deflate.c:(.text+0x819): undefined reference to `inflateInit2_'
extension-permessage-deflate.c:(.text+0x86c): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status

**Comment by JoakimSoderberg** [comment]
You need zlib as well for the deflate extension, so to link `-lz`

bash
```
gcc test-server.c test-server-http.c test-server-dumb-increment.c test-server-mirror.c test-server-status.c test-server-echogen.c -lwebsockets -o lws_test_server -lssl -lcrypto -lz
```

Is this the first time you ever compile a C program? If so, I suggest you read some tutorial or something on that first.

**Comment by vova01987** [comment]
Thank you, it's works!
Not the first time, but I have a little experience with such complex projects and with Cmake. I'm sorry for asking this newbie questions, but I have a little time to make my project and some questions are difficult and not obviuos for me.

OK, another questions:
1. When I make empty "hello world" project with  libwebsockets.a and using gcc -static, the output bin file have size about 900 Kb. And without -static key, it's size about 9 Kb. Why? Size of libwebsockets.a about 230 Kb.

About test-server.
2. I make libwebsockets.a with cmake.. and make. Then I copy directory https://github.com/warmcat/libwebsockets/tree/v2.0-stable/test-server .
Copy there  libwebsockets.a and Makefile described above. Then use "make". There is errors because it's need "lws_config.h" and "libwebsockets.h". I use "libwebsockets.h" from lib source directory and "lws_config.h" from **build** directory (it's generated from "lws_config.h.in" by Cmake when I build libwebsockets.a). Is it right? After that there is a error:
test-server.c:37:29: error: ‘INSTALL_DATADIR’ undeclared here (not in a function)
If I use #define LOCAL_RESOURCE_PATH "usr/local/share/libwebsockets-test-server" instead of default
#define LOCAL_RESOURCE_PATH INSTALL_DATADIR"/libwebsockets-test-server"
everyfing works and test-server builds.
Where I should declare INSTALL_DATADIR?
3. How can I use cross-compilation for ARM architecture in this Makefile for test-server? I have a toolchain for ARM and already use it for all project by editing "cross-arm-linux-gnueabihf.cmake" and using "cmake .. -DCMAKE_TOOLCHAIN_FILE=../cross-arm-linux-gnueabihf.cmake". It works OK and builds a library itself and all test-server and client binaries for ARM architecture.

**Comment by lws-team** [comment]
1) Just google it.  It's not related to lws.

2) As was mentioned in your other question - make and install lws.  It means `make && sudo make install`.  Then you can find the necessary .h files in /usr/include.  You should modify the use of INSTALL_DATADIR to the directory where you plan to store the assets of your program, your program needs to store its own stuff not use the directory of lws test programs.

3) Just google it.  It's not related to lws.

I'm sorry to hear you have little time to solve your problems.  But why do you think we have a lot of time to solve your problems?  You have any time to solve my problems?

**Comment by vova01987** [comment]
Thank you again!
