### ISSUE TITLE
Use libuv internal loop for external needs

### ISSUE THREAD

**Issue by eladn** [warmcat/libwebsockets#626]
I've noticed that lws interface allows accesssing the internal lws auto-generated libuv loop. I also noticed the library support foreign loop. 
1. Can i use the internal loop for my own needs as a regular libuv loop, for example to add my custom events or add timers to this loop? Are there any limitations?
2. I'm planning a ws server that would also access db async, connect to http APIs async, has it's own timers for scheduling tasks, access filesystem, etc.. so I need to use libuv for my project not only for lws. This said, the project is still open to design modifications so it would not be a problem using the lws internal loop as it's main loop. But it might just be a bad design. What do you think? Would you suggest using a foreign loop in that case?
3. What other considerations should i have in mind when deciding whether to use foreign loop?
4. Does lws do something special with it's internal loop that I'll have to implement myself if i decide to use foreign loop? Like the way it makes the loop run or make sure it won't just stop (because it does not have events to handle for awhile?) Would it be sufficient to init an empty loop, pass it to lws while init and just run it via libuv interface?

**Comment by lws-team** [comment]
1 + 2) Yes just use a foreign loop.  BTW lws also supports HTTP and WS client activities alongside server.

3) There are no special considerations about it, timers and socket service from lws on the foreign loop are treated the same as ones used by the outer application that owns the loop.  So there is still a single libuv event happening at a time in one thread, and lws events take their turn with events from the outer application.  lws should deal with closing libuv handles for everything he allocated by himself.

4) No, all that's going on is during the context init, lws will either instantiate a uv loop and use it for everything, or skip doing that and use the one you passed in.  So there should be no big ramifications from it.


Also though, take a look at lwsws.  This is a canned, standalone webserver using lws, configured by JSON config files.  In his protocol plugins, he uses libuv, eg

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_dumb_increment.c

That'd be another way of coming at it, the app would be lwsws and the other features like database access and your other libuv actions are in a protocol plugin, using lws internal libuv loop then.  Generic sessions and the messageboard example work like that

https://github.com/warmcat/libwebsockets/blob/master/plugins/generic-sessions/protocol_lws_messageboard.c

as does the generic-table live directory listing example

https://github.com/warmcat/libwebsockets/blob/master/plugins/generic-table/protocol_table_dirlisting.c

lwsws gives you a nice standalone, configurable web server in one step, you can add whatever libuv stuff you want in the protocol plugin.

**Comment by eladn** [comment]
Thanks a lot for the detailed asnwers as usual and for the library itself! Wonderful work!
