### ISSUE TITLE
limit the number of connection

### ISSUE THREAD

**Issue by mradul17** [warmcat/libwebsockets#627]
there is any way to limit the number of client?.i  mean  sever can serve service only to 20 clients. Where can i mention this number?.

**Comment by lws-team** [comment]
This should do it in the context creation struct

```
	unsigned int fd_limit_per_thread;
	/**< CONTEXT: nonzero means restrict each service thread to this
	 * many fds, 0 means the default which is divide the process fd
	 * limit by the number of threads. */
```

By default there is one service thread, so this reflects a limits on the total humber of fds.

**Comment by mradul17** [comment]
thanks for saving my time.
but i noticed 
for  fd_limit_per_thread = 1
[2016/09/13 19:22:08:0694] ERR: libwebsocket init failed

fd_limit_per_thread = 2
[2016/09/13 19:22:27:2031] ERR: Too many fds (1024 vs 2)
[2016/09/13 19:22:27:2031] ERR: lws_adopt_socket_vhost: fail inserting socket

fd_limit_per_thread = 3
no message. nothing happed

fd_limit_per_thread = 4
now only one client can connect

fd_limit_per_thread = 23
now 20 clients can connect

**Comment by lws-team** [comment]
Posix apps are started with stdin, stdout and stderr pipes set up, which is three fds literally 'before you get started'.  Socket and file descriptors are treated interchangeably by the OS.  So this number is literally how many fds the service thread can deal with; runtime memory allocations occur at context creation time scaled by this limit.

If you care about the number of connections super precisely, you can track how many connections are live and fail excess ones using connection-time callbacks.
