### ISSUE TITLE
TLS Documentation

### ISSUE THREAD

**Issue by ronniebrash** [warmcat/libwebsockets#632]
Hello crew,

Do you have complete start to finish documentation on how to get the library to use TLS and certificates with a running example?  I see the options in the example server, but no comments on verifying the enforcement of TLS 1.2 or generation of certificates for example.  SSL seems to be used interchangeably and they are not necessarily interchangeable paradigms.

This would be of great help for not only myself.

Thanks!

**Comment by lws-team** [comment]
Lws is a webserver before it's a ws server... every ws connection starts out as HTTP and the security wrapping negotiation if any occurs before that.  So for these purposes, you can test it at HTTP(S) level.  If that is OK then the ws upgrade occurs inside that without further changes to the security wrapping.

There are several sites who will objectively do that for you: here are the test results for libwebsockets.org itself from SSL Labs (not TLS labs...)  You can see we get an A+ and part of that testing is confirm we only accept TLS1.2.

https://www.ssllabs.com/ssltest/analyze.html?d=libwebsockets.org

That's running lwsws.

Lws gets its "TLS" related services from Open**SSL** or another similar "SSL" library, not OpenTLS.  So we refer to the whole thing as SSL, even though as a protocol that itself is deprecated in favour of TLS.  We support all the TLS that OpenSSL does so it doesn't indicate a problem.

Likewise we allow control of excluding and including negotiation protocols and ciphers in OpenSSL by passing opaque strings to their apis.

From README.coding.md

```
There's a member ssl_cipher_list in the lws_context_creation_info struct which allows the user code to restrict the possible cipher selection at context-creation time.

You might want to look into that to stop the ssl peers selecting a cipher which is too computationally expensive. To use it, point it to a string like

`"RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL"`

if left NULL, then the "DEFAULT" set of ciphers are all possible to select.

You can also set it to "ALL" to allow everything (including insecure ciphers).
```

From README.lwsws.md (documentation on related options settable in lws conf)

```
    If the three options host-ssl-cert, host-ssl-ca and host-ssl-key are given, then the vhost supports SSL.

    Each vhost may have its own certs, SNI is used during the initial connection negotiation to figure out which certs to use by the server name it's asking for from the request DNS name.

    "sts": "1" causes lwsws to send a Strict Transport Security header with responses that informs the client he should never accept to connect to this address using http. This is needed to get the A+ security rating from SSL Labs for your server.

    "enable-client-ssl": "1" enables the vhost's client SSL context, you will need this if you plan to create client conections on the vhost that will use SSL. You don't need it if you only want http / ws client connections.

    "ciphers": "" sets the allowed list of ciphers and key exchange protocols for the vhost. The default list is restricted to only those providing PFS (Perfect Forward Secrecy) on the author's Fedora system.

    If you need to allow weaker ciphers,you can provide an alternative list here per-vhost.

    "ecdh-curve": "" The default ecdh curve is "prime256v1", but you can override it here, per-vhost

    "ssl-option-set": "" Sets the SSL option flag value for the vhost. It may be used multiple times and OR's the flags together.

    The values are derived from /usr/include/openssl/ssl.h

     # define SSL_OP_NO_TLSv1_1                               0x10000000L

would equate to

     "`ssl-option-set`": "268435456"

    "`ssl-option-clear'": "" Clears the SSL option flag value for the vhost. It may be used multiple times and OR's the flags together.
```

Same information if you will do it programmatically at vhost creation time, from libwebsockets.h

```
	const char *ssl_private_key_password;
	/**< VHOST: NULL or the passphrase needed for the private key */
	const char *ssl_cert_filepath;
	/**< VHOST: If libwebsockets was compiled to use ssl, and you want
	 * to listen using SSL, set to the filepath to fetch the
 	 * server cert from, otherwise NULL for unencrypted */
	const char *ssl_private_key_filepath;
	/**<  VHOST: filepath to private key if wanting SSL mode;
	 * if this is set to NULL but sll_cert_filepath is set, the
	 * OPENSSL_CONTEXT_REQUIRES_PRIVATE_KEY callback is called
	 * to allow setting of the private key directly via openSSL
	 * library calls */
	const char *ssl_ca_filepath;
	/**< VHOST: CA certificate filepath or NULL */
	const char *ssl_cipher_list;
	/**< VHOST: List of valid ciphers to use (eg,
	 * "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL"
	 * or you can leave it as NULL to get "DEFAULT" */
	const char *ecdh_curve;
/**< VHOST: if NULL, defaults to initializing server with "prime256v1" */
	long ssl_options_set;
	/**< VHOST: Any bits set here will be set as SSL options */
	long ssl_options_clear;
/**< VHOST: Any bits set here will be cleared as SSL options */
```

As you see these are passed through to OpenSSL.

If you feel there should be more docs, it's be great if you contributed something.

**Comment by lws-team** [comment]
Well, please reopen if you have any specific question or something else related.
