### ISSUE TITLE
about secure connection(SSL/TLS)

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#640]
Hi,

I found that SSL doesn't works well in v2.0.3(we are using libwebsockets for 'Server')
Unfortunately, we can't check why it doesn't works well because any significant log are not shown except next log.
This is only the one log of 'libwebsockets' of Server, when client side(browser) try to connect via secure connection(wss://...).
================================
forbidding on uri sanitation
================================

We are using next code as user code of libwebsockets.
Using this user code, Secure Server(for wss and https) is works well with libwebsockets v1.7.9.
But, with v2.0.3, It's failed when client side try to connect as secure.
Could you check this issue(about SSL/TLS) already reported?
Or, Is there some wrong part in next user code we are setting?
==============================================================================================
void* SercureServer::ServerThread(void* data)
{
  static struct lws_protocols protocols[] = {
  {
    "http-only",
    callback_http,
    sizeof(struct per_session_data_http),
    0,
  }
	:
	:
  }

  int n = 0;
  struct lws_context* context;
  struct lws_context_creation_info info;
  memset(&info, 0, sizeof info);
  info.port = 8002;
  info.protocol = protocols;
  info.extensions = NULL;
  info.ssl_cert_filepath = /usr/share/test/cert.pem;
  info.ssl_private_key_filepath = /usr/share/test/private_key.pem;
  info.ssl_ca_filepath = /usr/share/test/ca.pem;
  info.gid = -1;
  info.uid = -1;
  info.options = 0;
  info.user = 0;

  context = lws_create_context(&info);
  if (context == NULL) {
    return NULL;
  }

  n = 0;
  while (n>=0) {
    n = lws_service(context, 0x0FFFFFFF);
  }

  if (context)
    lws_context_destroy(context);

  return NULL;
}
==============================================================================================

Thanks.

**Comment by lws-team** [comment]
In the v2.0 changelog it says this

https://github.com/warmcat/libwebsockets/blob/v2.0-stable/changelog#L110

**Comment by kjnoh77** [comment]
After submit this issue, I awared that you already handled issue similar with this and already closed.
I will close this issue and try that.
Thank you very much for your so fast reply~
