### ISSUE TITLE
How to deal with a short lws_write()

### ISSUE THREAD

**Issue by smipi1** [warmcat/libwebsockets#644]
Hi @warmcat,

The API documentation warns that lws_write() can return with a short write (not all bytes written). What is not clear in the API documentation, is that every lws_write() call appears to result in a websocket frame being received by the other side.

How can we then complete the frame if we get a short write? Should we treat this as a critical failure?

Regards,
@smipi1

**Comment by lws-team** [comment]
Historically lws left the user code to sort it out, the docs are likely from that era.

In even mildly recent releases, lws deals with it for you by malloc-ing up a buffer if it sees not everything got sent, and completing the send in the background.  Notifications the the connection is writable are suppressed until it completes the send.

Ws is designed to treat messages as atomic and not sweat about frames; it's legal for ws intermediaries to refragment frames the same way tcp intermediaries may coalesce or refragment tcp packets.

**Comment by smipi1** [comment]
Maybe I should rephrase:

How should I programmatically deal with lws_write() if it returns a non -1 value that is less than the requested length?

**Comment by lws-team** [comment]
The answer is the same... Lws either errors out because the socket is dead or sends everything, concealing that needs multiple waits on POLLOUT.  So you just need to check for the -1 case.  There's no middle ground any more.

**Comment by smipi1** [comment]
That true for v1.7.x as well?

**Comment by lws-team** [comment]
Yes, this predates v1.7.

**Comment by smipi1** [comment]
Good to know. Thanks!

Will you mention this in the next API doc update?

**Comment by lws-team** [comment]
Like this (from v2.1 / master)?

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L3290

==

https://libwebsockets.org/lws-api-doc-master/html/group__callback-when-writeable.html

**Comment by smipi1** [comment]
I was more referring to the following API description on lws_write():

https://libwebsockets.org/lws-api-doc-master/html/group__sending-data.html:

>  Return may be -1 for a fatal error needing connection close, or a
 positive number reflecting the amount of bytes actually sent.  This
 can be less than the requested number of bytes due to OS memory
 pressure at any given time.

The last sentence still clearly states that you will have to programmatically deal with short writes, but does not tell you how you should go about it.

**Comment by lws-team** [comment]
Mmm well I agree, it doesn't provide the context I explained here.

I pushed patches on v1.7-stable, v2.0-stable, v2.1-stable and master adding the explanation to lws_write in libwebsockets.h.
