### ISSUE TITLE
Question: Auto-reconnect logic

### ISSUE THREAD

**Issue by Dev0Null** [warmcat/libwebsockets#646]
Good day,

I currently have a simple libwebsockets client based off of an example I found here:
https://stackoverflow.com/questions/30904560/libwebsocket-client-example

I made a simple server based off of the provided code as well, and the client sends the server a "heartbeat" message every second if they aren't already communicating rapidly, which is the typical case. On occasion, the two disconnect due to network issues, or errors detected by the server, resulting in an intentional disconnect.

Is there a trivial way to add some code to either my monitor thread that calls the LWS message pump, or the callback logic itself to attempt to auto-reconnect to the remote server when I encounter an issue connecting (`LWS_CALLBACK_CLIENT_CONNECTION_ERROR`) or an existing connection dies (`LWS_CALLBACK_CLOSED`)?

I've been reading through the API documentation, and am familiar with the API calls required to create a connection, but found some other forum posts (which I can no longer find) that show memory leaks when attempting to reconnect in such a manner.

Pardon for using an issue/ticket request for filing this, but my personal and gmail accounts never seem to successfully post to the mailing list, and get bounce notifications a day or two later on each attempt.

Thank you.

**Comment by lws-team** [comment]
Well, the example in the stack exchange question is broken.  It shouldn't just send out tx from the rx callback.  It has to ask for a callback when the connection is writeable and send whatever it has then. 
I provide an example test client and test server in the sources, you should base your stuff off these.

In particular, if you had looked at the test client, you would have seen it tests close and reconnect as part of its normal activity.

The test apps are licensed CC0, they show the recommended way to drive lws, I support them, so there is no reason not to use them...

**Comment by Dev0Null** [comment]
@lws-team  Thank you for the prompt reply. Which part of the test client (https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c) handles auto-reconnect logic? 

Thank you.

**Comment by lws-team** [comment]
1) the client connect wsi pointer being NULL means we are not connected

2) handle connection attempt failures
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c#L112

3) Ratelimit the reconnection attempts (to once per 2s)
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c#L384

4) Inbetween service calls, check if it's time to retry anyone's connections
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c#L634

**Comment by Dev0Null** [comment]
Thank you again. Cheers!
