### ISSUE TITLE
Issue connecting to remote host on CentOS v6 client (x86, x64)

### ISSUE THREAD

**Issue by Dev0Null** [warmcat/libwebsockets#648]
I've tried the (warmcat/LWS-supplied) client/server examples on CentOS6.  I'm currently using vagrant to setup my virtual machines (https://atlas.hashicorp.com/boxcutter) for testing my LWS code. I've already gone through the usual test steps, ie:

- Disabling seLinux.
- Disabling the firewall and opening all ports.
- Disabling IPv6.

Despite all this, I can't get LWS client examples working with remote servers on CentOS6. I can initialize the context variable, but cannot get it to connect to the remote host, while pings and a few other network tools of mine don't seem to have issues doing simple POST/GET requests, etc.

```
 NOTICE: Initial logging level 7
 NOTICE: Libwebsockets version: 2.0.2 vagrant@localhost.localdomain-v2.0.2
 NOTICE: IPV6 not compiled in
 NOTICE: libev support not compiled in
 NOTICE: libuv support not compiled in
 NOTICE:  Threads: 1 each 1024 fds
 NOTICE:  mem: platform fd map:  8192 bytes
 NOTICE:  Compiled with OpenSSL support
 NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
 NOTICE: Creating Vhost 'default' port -1, 1 protocols
 NOTICE:  mem: per-conn:          488 bytes + protocol rx buf
 NOTICE:  canonical_hostname = localhost.localdomain
 NOTICE: lws_protocol_init
```

Is there a general set of suggestions for working with LWS on CentOS, or a set of steps I should carry out to help diagnose this issue?

Thank you.

**Comment by lws-team** [comment]
Lws is built and tested on Fedora.  So there should be nothing strange to it about Centos at all.

 - you can connect the test client to the test server on localhost?

 - it's the lws test server you are trying to connect to or something else?  The lws test client as it is, is designed to use ws protocols only the test server provides.

 - Crank up the logging with -d65535 to see everything.  If no extra logging appears, make sure you are building in DEBUG mode (cmake .. -DCMAKE_BUILD_TYPE=DEBUG)

 - and / or look with tcpdump what happens on the wire

**Comment by Dev0Null** [comment]
I was able to connect the "mirror" test client and server on local host. Connecting to a remote server failed. Turns out my firewall changes in CentOS weren't set to persist across boots. Continued with my test setup, now working. Thanks!
