### ISSUE TITLE
Fast close of websocket

### ISSUE THREAD

**Issue by Dincorporated** [warmcat/libwebsockets#649]
Hello,

We are using libwebsocket and the echo protocol, but we have noticed that many upstream (server) implementations are not adhering 100% to the specification when performing a disconnect.  The RFC asks a server to echo back a close response, but this is optional (https://tools.ietf.org/html/rfc6455#section-1.4).  

While we can only hope that upstream libraries on the server do in fact do this, but fast-close is desired because we need the code to reliably handle this edge case.  What is the best way within the client to disconnect? e.g.

` 
```
...
void close(... context) {
libwebsockets_set_timeout(wsi, NO_PENDING_TIMEOUT, 0);
...// anything else? is there a disconnect call?
}
```
`

Unfortunately, we are seeing a timeout of roughly 15 seconds using ws contexts and detecting a timeout.  This interrupts our program's flow for obvious reasons.  Is there a way to do something like a force close on a connection/context instead of hinting? like a close();

**Comment by lws-team** [comment]
Not sure I understand completely...

 - Why is it 'obvious' this 'interrupts the flow of your program'?  What's actually happening there in your program?  Since lws does things asynchronously although it may hang around for a bit waiting to do the close handshake, it's not like it's actually blocked or 'stalled'.

 - You can set the pending timeout to -1 to mark a wsi as to be closed.

 - What version of lws are you using?  The apis all changed to start lws_ back with 1.6.

 - You can set the general timeout number in secs in the context creation info struct.  But it doesn't default to 15.

**Comment by Dincorporated** [comment]
I have these events being dumped to the console:

`[2016/10/19 16:52:23:0139] NOTICE: wsi 0x7f04c00008c0: TIMEDOUT WAITING on 13 (did hdr 1, ah (nil), wl 0, pfd events 0)
`
My program was waiting for a timeout (blocking) after a disconnect and is not able to reconnect fast enough to a server after disconnecting (ongoing/persistent connections is not desirable).  

As you suggested, I changed the general timeout in the context creation info struct and the blocking time was clearly minimised. Is there another way that is more appropriate to fast-disconnect to allow the program to carry on execution?

We are using 2.0 and a relatively recent checkout of the main tree.

What is the call to set a pending timeout to -1?

**Comment by lws-team** [comment]
OK.... timeout 13 is PENDING_TIMEOUT_SHUTDOWN_FLUSH, it is related to the close sequencing, but not the ws handshake part.

When lws decides to close, there may be unread RX "in the pipe".  So it first uses shutdown() to disable any more TX on the pipe.  Having done that, poll() is supposed to return POLLHUP error when no more rx is pending and we complete the close on that error; the close code understands the wsi is in a state specific to doing the shutdown wait and picks up where it left off.

 - What OS is this on?  I see this code is disabled for WinCE for example.  On Linux it works well.

 - What lws event loop (libuv, libev, or just the default poll() service loop) is this?

 - I still don't understand why your code is blocking, maybe it's another thread or something and you're making it block on your own.  Nothing in lws should actually block.

- lws_set_timeout(wsi, PENDING_TIMEOUT_CLOSE_ACK, -1); will mark the wsi as to be closed next time there is service.  It doesn't get you out of the wait on shutdown flush once you are closing.

**Comment by lws-team** [comment]
I can't do anything to help about this without some answers ---^
