### ISSUE TITLE
WebSocket opening handshake was canceled

### ISSUE THREAD

**Issue by mradul17** [warmcat/libwebsockets#650]
Sir,
i am try to enable ssl. this is code

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <libwebsockets.h>

#define KGRN "\033[0;32;32m"
#define KCYN "\033[0;36m"
#define KRED "\033[0;32;31m"
#define KYEL "\033[1;33m"
#define KMAG "\033[0;35m"
#define KBLU "\033[0;32;34m"
#define KCYN_L "\033[1;36m"
#define RESET "\033[0m"

static int destroy_flag = 0;

static void INT_HANDLER(int signo) {
    destroy_flag = 1;
}

/* *
 * websocket_write_back: write the string data to the destination wsi.
 */
int websocket_write_back(struct lws *wsi_in, char *str, int str_size_in) 
{
    if (str == NULL || wsi_in == NULL)
        return -1;

    int n;
    int len;
    char *out = NULL;

    if (str_size_in < 1) 
        len = strlen(str);
    else
        len = str_size_in;

    out = (char *)malloc(sizeof(char)*(LWS_SEND_BUFFER_PRE_PADDING + len + LWS_SEND_BUFFER_POST_PADDING));
    //* setup the buffer*/
    memcpy (out + LWS_SEND_BUFFER_PRE_PADDING, str, len );
    //* write out*/
    n = lws_write(wsi_in, out + LWS_SEND_BUFFER_PRE_PADDING, len, LWS_WRITE_TEXT);

    printf(KBLU"[websocket_write_back] %s\n"RESET, str);
    //* free the buffer*/
    free(out);

    return n;
}

static int ws_service_callback(
                         struct lws *wsi,
                         enum lws_callback_reasons reason, void *user,
                         void *in, size_t len)
{

    switch (reason) {

        case LWS_CALLBACK_ESTABLISHED:
            printf(KYEL"[Main Service] Connection established\n"RESET);
            break;

        //* If receive a data from client*/
        case LWS_CALLBACK_RECEIVE:
            printf(KCYN_L"[Main Service] Server recvived:%s\n"RESET,(char *)in);

            //* echo back to client*/
            websocket_write_back(wsi ,(char *)in, -1);

            break;
    case LWS_CALLBACK_CLOSED:
            printf(KYEL"[Main Service] Client close.\n"RESET);
        break;

    default:
            break;
    }

    return 0;
}

struct per_session_data {
    int fd;
};

int main(void) {
    // server url will usd port 5000
    int port = 1973;
    const char *interface = NULL;
    struct lws_context_creation_info info;
    struct lws_protocols protocol;
    struct lws_context *context;

    //* register the signal SIGINT handler */
    struct sigaction act;
    act.sa_handler = INT_HANDLER;
    act.sa_flags = 0;
    sigemptyset(&act.sa_mask);
    sigaction( SIGINT, &act, 0);

    //* setup websocket protocol */
    protocol.name = "my-echo-protocol";
    protocol.callback = ws_service_callback;
    protocol.per_session_data_size=sizeof(struct per_session_data);
    protocol.rx_buffer_size = 0;

    //* setup websocket context info*/
    memset(&info, 0, sizeof info);
    info.port = port;
    info.iface = interface;
    info.protocols = &protocol;
    info.ssl_cert_filepath = "apache.crt";
    info.ssl_private_key_filepath = "apache.key";
    info.gid = -1;
    info.uid = -1;
    info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

    //* create libwebsocket context. */
    context = lws_create_context(&info);
    if (context == NULL) {
        printf(KRED"[Main] Websocket context create error.\n"RESET);
        return -1;
    }

    printf(KGRN"[Main] Websocket context create success.\n"RESET);

    //* websocket service */
    while ( !destroy_flag ) {
        lws_service(context, 50);
    }
    usleep(10);
    lws_context_destroy(context);

    return 0;
}

**console print** 

[2016/10/20 17:56:22:5636] NOTICE:  Using SSL mode
[2016/10/20 17:56:22:5645] NOTICE:  SSL ECDH curve 'prime256v1'
[2016/10/20 17:56:22:5650] NOTICE:  Listening on port 1973
[2016/10/20 17:56:22:5650] NOTICE:  mem: per-conn:          512 bytes + protocol rx buf
[2016/10/20 17:56:22:5650] NOTICE:  canonical_hostname = DELL
[Main] Websocket context create success.
[2016/10/20 17:56:22:6152] NOTICE: lws_protocol_init
[2016/10/20 17:56:35:1968] NOTICE: lws_server_socket_service: wsi 0x25901f0 read -1
[2016/10/20 17:56:35:1969] NOTICE: lws_header_table_detach: wsi 0x25901f0: ah 0x2567880 (tsi=0, count = 0)

**on browser console error:** 
WebSocket connection to 'wss://localhost:1973/' failed: WebSocket opening handshake was canceled

**Comment by lws-team** [comment]
First, this plan doesn't work with lws.

```
    case LWS_CALLBACK_RECEIVE:
        printf(KCYN_L"[Main Service] Server recvived:%s\n"RESET,(char *)in);

        //* echo back to client*/
        websocket_write_back(wsi ,(char *)in, -1);
```

With lws, you can only safely write from the WRITEABLE callback.

Nor do you need to do the malloc / free dance, if you followed the rule about only sending when WRITEABLE, you can safely send from a stack buffer.

There's some bad example code like this out in the web, you are best to follow the sample code that comes with lws, eg, test-client.  The sample code is licensed CC0 so there is no problem just copying it wholesale as your starting point, and chopping out the stuff you don't need.  That has the advantage that it works well and properly, and you can keep checking you didn't break anything while chopping it down.

So... where is this error message "WebSocket opening handshake was canceled" coming from?  It is not a message from lws and I don't see it in your code.  Who says it and what exactly causes it to appear?

**Comment by mradul17** [comment]
thanks for reply. Okay. i will try with test-client.c. 
"WebSocket opening handshake was canceled" it is on browser's console when i do inspect on chrome browser. But on Firefox -  **can't establish a connection to the server at wss://192.168.3.2:1973/.**
i am try to create chat service. Error is on browser. and on ubuntu terminal **lws_server_socket_service: wsi 0x25901f0 read -1**

**Comment by lws-team** [comment]
If you want to make a chat **server**, you should look closely at the mirror protocol in the test server

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_lws_mirror.c

Although it's short, this has the basics for everything you need... a FIFO to hold messages, update each client as fast as they can take a new message, and receive new messages shared to all the other clients.

This is the protocol that does the drawing "mirror" tab in the test server

https://libwebsockets.org/testserver/

but it can be adapted to send text easy enough.

**Comment by mradul17** [comment]
Thanks again. one more question.
info.ssl_cert_filepath , info.ssl_private_key_filepath and
 info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

these three three field for creating wss? or more thing, will be added ?

**Comment by lws-team** [comment]
If your cert is selfsigned, you also need ssl_ca_filepath IIRC.

But isn't it going to be easier to first confirm the test apps work with ssl, and then cut them down so you can build them back up as your app?  You can see for yourself what is needed for what then because you know it works as it is, and you can try removing things.

**Comment by mradul17** [comment]
Sir,i am trying on my local system. WS server works fine client is connecting  but after adding these 4 field 
info.ssl_cert_filepath,
info.ssl_private_key_filepath,
info.ssl_ca_filepath,
info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
I create my self certificate with the help oh this link "https://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority". 
client is not connecting. 

i will catch up you again. after doing more work on this

**Comment by lws-team** [comment]
If you want me to help you, you need to tell me about the lws test server and / or client function on your system, using ssl.

I don't have your code, the code you pasted is broken and I am not going to waste my time making wild guesses about how else your code I can't see (don't particularly want to see, either) is broken.

The lws test apps should work right out of the box, or I will try to do something to understand why not and fix if possible / necessary.

And you can base your code directly off the test apps sources.  So you are not wasting time using the test apps.  You are getting a known-working solution for your own code.
