### ISSUE TITLE
ws- allow cross site scripting

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#651]
Sir, please tell  me how  to enable cross site scripting.where will i add Acess-Control-Allow-Origin:\* in header

**Comment by lws-team** [comment]
If you are using lwsws, you can just add this kind of thing in the vhost definition

```
                   "headers": [{
                        "Content-Security-Policy": "script-src 'self'",
                        "X-Content-Type-Options": "nosniff",
                        "X-XSS-Protection": "1; mode=block",
                        "X-Frame-Options": "SAMEORIGIN"
                 }]
```

If you are doing it programmatically, well, that's painful now isn't it ^^

You need to create your vhost explicitly, and set this in the info struct when creating your vhost

```
	const struct lws_protocol_vhost_options *headers;
		/**< VHOST: pointer to optional linked list of per-vhost
		 * canned headers that are added to server responses */
```

You need to prepare a linked-list of structs to carry the options you want (or just the one if only one in your "list").  The last entry says .next is NULL.  An example of the style is here

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L140

**Comment by tejendrasingh** [comment]
thanks for reply, 
Sir, I used lws. There is any easy way to convert into lwsws.

**Comment by lws-team** [comment]
I dunno what your code looks like.

lwsws is almost entirely implemented in lws library.  So they are basically the same thing already.

If you have a standalone server type job, lwsws can solve it.  If you have something more complex or integrate with another program, you probably need to stick with making your own implementation with lws.

Just add cmake .. -DLWS_WITH_LWSWS=1 and it will build it, there's docs on it here:

https://libwebsockets.org/lws-api-doc-master/html/md_README.lwsws.html

It requires libuv (for ubuntu, the package is libuv1 / libuv1-dev)

Copy the example config files

 - ./lwsws/etc-lwsws-conf-EXAMPLE to /etc/lwsws/conf
 - ./lwsws/etc-lwsws-conf.d-localhost-EXAMPLE to /etc/lwsws/conf.d/localhost

He can run the test server on port 7681 if you run lwsws

Once that's working, to add your own ws protocol, look at copying this

https://github.com/warmcat/libwebsockets/tree/master/plugin-standalone

change all the names "dumb_increment" in that to your protocol name.

The code is a lot cleaner and simpler using the plugins.  The whole dumb-increment protocol looks like this

https://github.com/warmcat/libwebsockets/blob/master/plugin-standalone/protocol_example_standalone.c

**Comment by mradul17** [comment]
sir, Please Review code,

[test-websocket.zip](https://github.com/warmcat/libwebsockets/files/569144/test-websocket.zip)

 i used test-server.c test-server-http.c. i add some extra code to read  lwsws/conf.d/localhost 
i added Acess-Control-Allow-Origin:* in lwsws/conf.d/localhost.
but i get error on chrome browser console-
"XMLHttpRequest cannot load http://localhost:5001/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."
zip contain test.hmtl to post image

[test-websocket.zip](https://github.com/warmcat/libwebsockets/files/569144/test-websocket.zip)

**Comment by lws-team** [comment]
I think you misunderstand something... if you are contributing something useful to this project I will certainly look at the code in your contribution.  If it's just your own code that doesn't work, well, you need to put it in terms of something I need to fix *in this project* for me to care.  If there's no problem to fix in lws and no question to answer, well, that's *your* problem.  Ask your partner / Dad / Manager to 'review your code'.

Since I use headers { } on libwebsockets.org, and it works... it's up to you to show a problem on my side.  If so, I'll certainly look at it.
