### ISSUE TITLE
'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by mradul17** [warmcat/libwebsockets#656]
Sir please review the code
[test-websocket.zip](https://github.com/warmcat/libwebsockets/files/569163/test-websocket.zip)

I use test-server.c test-server-http.c file. i make some change in test-server.c to read lwsws/conf.d/localhost.
I added Access-Control-Allow-Origin:* in header section of lwsws/conf.d/localhost conf file. 
but i get same error on chrome browser "XMLHttpRequest cannot load http://localhost:5001/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."
zip contain test.html to post image

**Comment by mradul17** [comment]
in test.html two method(using <form> tag or xmlhttprequest) are present.
when i post using <from> image is successfully posted but with xmlhttprequest cross origin error is occuring

**Comment by lws-team** [comment]
I can't answer questions about chrome.  Or your code.

Is lws putting the headers on as expected or not?  It applies them to every file served from a mount, at least.

Use tcpdump or wireshark to see the headers and see what gets sent or not on your post.

**Comment by mradul17** [comment]
sir, I think there is something problem with lwsws server.
 i run lwsws and it staring listening on localhost:7681 
after that i post image on http://localhost:7681/formtest. 
using html form tag is successfully posted and save to /tmp. but this is not happening with xmlhttprequest. it gave error on browser
**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:7681/formtest. (Reason: CORS header 'Access-Control-Allow-Origin' missing)**
my web page is 

`<!DOCTYPE html>
<html>
<body>
  <script>
		function uploadAudio (){
      var filesSelected = document.getElementById("fileToUpload").files
      var fileToLoad = filesSelected[0]
      var fileReader = new FileReader()
      var rawData = new ArrayBuffer();
      fileReader.onload = function(fileLoadedEvent) { 
      rawData = fileLoadedEvent.target.result
		  var fd = new FormData();
		  fd.append("filename", rawData);
		  var xhr = new XMLHttpRequest();
		  xhr.open('POST', 'http://localhost:7681/formtest', true);
		  xhr.onload = function() {
		    alert(this.status);
      };
      xhr.send(fd);
      } 
      fileReader.readAsDataURL(fileToLoad)
    }
  </script>
  <h2>Upload image by XMLHttpRequest</h2>
  <input type="file" name="fileToUpload" id="fileToUpload">
  <input type="submit" value="Upload Image" name="submit" onclick="uploadAudio()">
  <br>
  <h2>Upload image by form</h2>
  <form action="http://localhost:7681/formtest" method="post" enctype="multipart/form-data"> 
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
  </form> 
</body>
</html>` 

Request Header is
POST /formtest HTTP/1.1
Host: localhost:7681
Connection: keep-alive
Content-Length: 9782
Origin: http://localhost
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryC9oCVW4VPDsyJZCi
Accept: */*
Referer: http://localhost/test.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

Response header is
HTTP/1.1 200 OK
Acess-Control-Allow-Origin: *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self'
server: lwsws
content-type: text/html
content-length: 389

**Comment by lws-team** [comment]
> CORS header 'Access-Control-Allow-Origin' missing

> Acess-Control-Allow-Origin: *

Let's play "spot the difference"...

**Comment by mradul17** [comment]
ohhh sorry my mistake... Sorry i am disturbing you again and again.
