### ISSUE TITLE
update to libwebsockets 2.0

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#657]
I have update my code from library 1.23 to 2.0 because I want use vhost.
But my first step is make it run. 
In few minutes the update is made.
In ws it work, in wss i receive the error "forbidding on uri sanitation"

2016/11/04 10:39:42.423 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_FILTER_NETWORK_CONNECTION lws* wsi=0x7f9c980a5940;lws_callback_reasons reason=17;void* user=0;void* in=0x23;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_WSI_CREATE lws* wsi=0x7f9c98001170;lws_callback_reasons reason=29;void* user=0;void* in=0;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED lws* wsi=0x7f9c98001170;lws_callback_reasons reason=19;void* user=0;void* in=0;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_LOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=35;void* user=0;void* in=0x7f9c7dbf4750;unsigned long len=1;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_ADD_POLL_FD lws* wsi=0x7f9c98001170;lws_callback_reasons reason=32;void* user=0;void* in=0x7f9c7dbf4750;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_UNLOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=36;void* user=0;void* in=0x7f9c7dbf4750;unsigned long len=1;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_CHANGE_MODE_POLL_FD lws* wsi=0x7f9c98001170;lws_callback_reasons reason=34;void* user=0;void* in=0x7f9c7dbf4750;unsigned long len=0;
[2016/11/04 10:39:42:4240] NOTICE:  forbidding on uri sanitation
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_CLOSED_HTTP lws* wsi=0x7f9c98001170;lws_callback_reasons reason=5;void* user=0;void* in=0;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_LOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=35;void* user=0;void* in=0x7f9c7dbf46f0;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_CHANGE_MODE_POLL_FD lws* wsi=0x7f9c98001170;lws_callback_reasons reason=34;void* user=0;void* in=0x7f9c7dbf46f0;unsigned long len=0;
2016/11/04 10:39:42.424 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_UNLOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=36;void* user=0;void* in=0x7f9c7dbf46f0;unsigned long len=0;
2016/11/04 10:39:42.432 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_LOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=35;void* user=0;void* in=0x7f9c7dbf4730;unsigned long len=1;
2016/11/04 10:39:42.432 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_DEL_POLL_FD lws* wsi=0x7f9c98001170;lws_callback_reasons reason=33;void* user=0;void* in=0x7f9c7dbf4730;unsigned long len=0;
2016/11/04 10:39:42.432 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_CHANGE_MODE_POLL_FD lws* wsi=0x7f9c980a5940;lws_callback_reasons reason=34;void* user=0;void* in=0x7f9c7dbf4720;unsigned long len=0;
2016/11/04 10:39:42.432 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_UNLOCK_POLL lws* wsi=0x7f9c98001170;lws_callback_reasons reason=36;void* user=0;void* in=0x7f9c7dbf4730;unsigned long len=1;
2016/11/04 10:39:42.432 | DEBUG | 2109691648l | [/home/mariorollino/WS/MSP3/src/frontend/feserver.cc 1439] LWS_CALLBACK_WSI_DESTROY lws* wsi=0x7f9c98001170;lws_callback_reasons reason=30;void* user=0;void* in=0;unsigned long len=0;

What is my error ?

Thank you.

Mario

**Comment by lws-team** [comment]
Did you read this?

https://github.com/warmcat/libwebsockets/blob/v2.0.3/changelog#L110

Also make sure you use v2.0-stable or release tags like v2.0.3, v2.0 original release already has several bugfixes.

**Comment by rollen1960** [comment]
I probe with the last stable 2.1 but the error remain

The functions lws_json_dump_* dont exist .

Thank you
mario

**Comment by lws-team** [comment]
Did you actually read the link, ie, about LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT?

lws_json_dump_* do exist in v2.1, look:

https://github.com/warmcat/libwebsockets/blob/v2.1.0/lib/libwebsockets.c#L2481

You need to give cmake -DLWS_WITH_SERVER_STATUS=1 to build them.

**Comment by rollen1960** [comment]
Thank you very much for your patient with my vary bad english.

All works.

Mario

**Comment by lws-team** [comment]
Great.
