### ISSUE TITLE
WSS UTF-8

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#658]
I send message in LWS_WRITE_TEXT mode that contains extended ascii (ascii code > 127 like àù ... iso8859-1). With ws I have no problem, with wss the frontend close the socket.
I have found that this is normal because I must send UTF-8 with wss.
Question: what make the flag  LWS_SERVER_OPTION_VALIDATE_UTF8 ? translate iso8859-1 to utf-8 ?
Question: if I translate iso8859-1 to utf-8 the length  in function lws_write is expressed in byte or in char ?
Question: with lws_write in LWS_WRITE_TEXT mode the message length must calculate the '\0' null terminate string or not ?

Thank you

Mario

**Comment by lws-team** [comment]
> I send message in LWS_WRITE_TEXT mode that contains extended ascii
> (ascii code > 127 like àù ... iso8859-1). With ws I have no problem,
> with wss the frontend close the socket.

Hm... it should not care if ssl is involved or not.  Have you looked at the logs to check why it closed?

> I have found that this is normal because I must send UTF-8 with wss.

No, you must send UTF-8 **with TEXT ws messages**.  ssl wrapping it or not is something completely unrelated.

> Question: what make the flag LWS_SERVER_OPTION_VALIDATE_UTF8 ?

You either give the flag in info.options when you create the context, in which case it will check for valid UTF-8 in incoming TEXT payloads, or you don't give the flag in which case it doesn't check.

> translate iso8859-1 to utf-8 ?

No that's your problem.

> Question: if I translate iso8859-1 to utf-8 the length in function
> lws_write is expressed in byte or in char ?

lws_write operates at the dumb payload level, so bytes.

> Question: with lws_write in LWS_WRITE_TEXT mode the message length
> must calculate the '\0' null terminate string or not ?

Dunno, do you want to send a NUL?  Then yes.  Don't want to send a NUL?  Then no.  That's entirely up to you.
