### ISSUE TITLE
On the incomplete Qt5 websocket library sub-protocol implementation

### ISSUE THREAD

**Issue by fapfap69** [warmcat/libwebsockets#662]
Hi,
I wrote a C++ Websocket server based on libwebsocket library, it works fine with clients written in Jscript or Phyton, but when I try to write a Qt5 client I discover that the server breaks the work.

The reason: Qt5 websocket plugin don't implements the sub-protocol handshake (they apply slavishly to the RFC !)
I found a mode to bypass this limitation : Defining in the list of accepted protocols one entry with the protocol name = "", and putting this entry as the first (default) protocol.

From first tests that i did, seems that the websocket server is able to correctly manage the Qt5 client requests.

Do you think this approach could be valid ?

**Comment by lws-team** [comment]
It's legit, if limiting, to not send any protocol negotiation header at all

https://tools.ietf.org/html/rfc6455#section-1.9

But as a server, we support it if given and also in the case it's not given.

By default as you found it maps to the vhost's protocols[0].  However if you want you can control which protocol, by name, per-vhost, gets matched to a missing incoming protocol header, using the info.pvo field at vhost creation time.  In lwsws it's easy as shown in the README

https://github.com/warmcat/libwebsockets/blob/master/README.lwsws.md

```
"ws-protocols": [{ "warmcat-timezoom": { "status": "ok", "default": "1" } }]
```

If you need to implement that in code instead, I provided that code in test-server-v2.0.c

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L122

```
/*
 * this sets a per-vhost, per-protocol option name:value pair
 * the effect is to set this protocol to be the default one for the vhost,
 * ie, selected if no Protocol: header is sent with the ws upgrade.
 */

static const struct lws_protocol_vhost_options pvo_opt = {
	NULL,
	NULL,
	"default",
	"1"
};

/*
 * We must enable the plugin protocols we want into our vhost with a
 * linked-list.  We can also give the plugin per-vhost options here.
 */

static const struct lws_protocol_vhost_options pvo_3 = {
	NULL,
	NULL,
	"protocol-post-demo",
	"" /* ignored, just matches the protocol name above */
};

static const struct lws_protocol_vhost_options pvo_2 = {
	&pvo_3,
	NULL,
	"lws-status",
	"" /* ignored, just matches the protocol name above */
};

static const struct lws_protocol_vhost_options pvo_1 = {
	&pvo_2,
	NULL,
	"lws-mirror-protocol",
	""
};

static const struct lws_protocol_vhost_options pvo = {
	&pvo_1,
	&pvo_opt,
	"dumb-increment-protocol",
	""
};

...
	info.pvo = &pvo;
...
```
In the example code `dumb-increment-protocol` is tagged as being the default protocol handler if the client didn't attempt any protocol negotiation.
