### ISSUE TITLE
receive ping callback?

### ISSUE THREAD

**Issue by nyx** [warmcat/libwebsockets#663]
It appears that there's a callback (`LWS_CALLBACK_RECEIVE_PONG`) invoked when `PONG` frames are received by the client however there is not, as far as I can tell, a corresponding callback invoked when `PING` frames are received. Is this understanding correct, and is this intentional or an oversight?

My reading of the websocket protocol indicates either the client or server may send `PING` frames and I've verified that libwebsockets clients send `PONG` responses as expected just no callback for user code to be notified through.

Thanks for your time and effort!

**Comment by lws-team** [comment]
It's intentional... lws itself always handles a PING by returning a PONG, without any user code.  What's in a PONG is defined by the standard as only being able to be the contents of the PING.

You can send PINGs in user code, and detect PONG came in user code.

In addition, lws itself can manage issuing PING and confirming PONG within a time limit on every ws connection automatically by setting this at context creation time

```
unsigned short ws_ping_pong_interval;
	/**< CONTEXT: 0 for none, else interval in seconds between sending
	 * PINGs on idle websocket connections.  When the PING is sent,
	 * the PONG must come within the normal timeout_secs timeout period
	 * or the connection will be dropped.
	 * Any RX or TX traffic on the connection restarts the interval timer,
	 * so a connection which always sends or receives something at intervals
	 * less than the interval given here will never send PINGs / expect
	 * PONGs.  Conversely as soon as the ws connection is established, an
	 * idle connection will do the PING / PONG roundtrip as soon as
	 * ws_ping_pong_interval seconds has passed without traffic
	 */
```

**Comment by nyx** [comment]
I saw that `ws_ping_pong_interval` commit today actually :) however I'm stuck for the time being with an older version of the library embedded in a pre-existing codebase. In my case I have been handling `PONG` frames via the callback I mentioned (for the purpose of custom connection liveliness checks), however due to some complicated reasons I won't go into am switching to a model where I had hoped to handle `PING` frames sent from the server in the same way instead.

I happen to not be concerned with the payload just the time since the last `PING` was received so unless that information is already available (I didn't see any such tracking in my quick look) I'll probably be adding that to our `libwebsockets` version.

**Comment by lws-team** [comment]
If the automatic keepalive stuff is too distruptive to add to the old code and you're rolling your own keepalive code, yes your best bet is stick your own callback to user code at the PING reception.

But for people able to use v2.1+ the built-in keepalive stuff means no need for it otherwise.
