### ISSUE TITLE
Segmentation fault on SSL use

### ISSUE THREAD

**Issue by annaseufert** [warmcat/libwebsockets#664]
Hi lws team,

I am trying to establish an encrypted websocket client. If I don't use SSL, establishing a connection is no problem. If I use SSL, the application throws a segmentation fault.

I use version 2.0.0 (because I can't build later versions) in a C++ application in an embedded linux environment (ARM9 CPU).

I wonder whether I forgot to set some value? Here is the relevant part of the code:

    // Create the websocket handler

    struct lws_context_creation_info info;
    int disallow_selfsigned = 0;

    memset(&info, 0, sizeof info);

    if(use_ssl && !disallow_selfsigned)
    {
        lwsl_info("allowing selfsigned\n");
        use_ssl = 2;
    } else
    {
        lwsl_info("requiring server cert validation against %s\n", ssl_cert);
        char ssl_cert_str[256];
        strcpy(ssl_cert_str, ssl_cert);
        info.ssl_ca_filepath = ssl_cert_str;
    }

    info.port = CONTEXT_PORT_NO_LISTEN;
    info.iface = NULL;
    info.protocols = protocols;
    if(use_ssl)
    {
        info.ssl_cert_filepath = NULL;
        info.ssl_private_key_filepath = NULL;
        info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
    }
    info.gid = -1;
    info.uid = -1;
    info.options = 0 | LWS_SERVER_OPTION_VALIDATE_UTF8;
    info.user = &session_data;

    context = lws_create_context(&info);
    if(context == NULL)
    {
        std::cout << ("libwebsocket init failed\n");
        return -1;
    }

    int timeout_ms = 10;

    // Connect to server

    address[sizeof(address) - 1] = '\0';
    sprintf(ads_port, "%s:%u", address, port & 65535);
    memset(&i, 0, sizeof(i));

    i.context = context;
    i.address = address;
    i.port = port;
    i.ssl_connection = use_ssl;
    i.path = uri;
    i.host = ads_port;
    i.origin = ads_port;
    i.protocol = protocols[0].name;
    i.userdata = &session_data;

    // Connect to websocket server
    std::cout << "trying to connect ..." << std::endl;
    wsi = lws_client_connect_via_info(&i);
    std::cout << "trying to connect done" << std::endl;
    if(!wsi)
    {
        lwsl_err("Client failed to connect to %s:%u\n", address, port);
        close();
    }

    // Service the pending activities, until there the confirmation or an error
    while(CONNECTED != status && FAULTED != status)
    {
        std::cout << "doing connection service ..." << std::endl;
        lws_service(context, timeout_ms); // Service any pending websocket activity
        std::cout << "doing connection service done" << std::endl;
    }

and here is what i get (the callback messages are printed in the callback method of course) :

    Client connecting to 192.168.3.88:8000....
    trying to connect ...
    callback called 35
    callback called 32
    callback called 36
    callback called 29
    callback called 35
    callback called 34
    callback called 36
    trying to connect done
    doing connection service ...
    callback called 31
    callback called 27
    callback called 35
    callback called 34
    callback called 36
    Segmentation fault (core dumped)

I would really appreciate your help! Thanks a lot in advance!

**Comment by lws-team** [comment]
> I use version 2.0.0 (because I can't build later versions)

Don't use v2.0 release.  It's superceded by some important bugfixes in v2.0-stable branch.  This is still v2.0.  But it has some security and other fixes you really need.

> info.options = 0 | LWS_SERVER_OPTION_VALIDATE_UTF8;

There shouldn't be any segfault from lws.  But if you think you're using SSL, you should see in the logs

```
SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
```

If you will use SSL, you must OR LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT on to info.options.

If that's not it

 - check the unchanges test server for this problem

 - send the logs

**Comment by lws-team** [comment]
Mmm also run it under gdb, and get a backtrace of exactly where the segfault is coming from.

That's like

$ gdb --args myapp myargs

When it blows chunks, type

 bt

to get the backtrace.

q to quit.

**Comment by annaseufert** [comment]
Thanks a lot! The info.options did it. I was to blind to see that I set this twice :laughing: 

As 2.0.0 has security problems, i will now try to get 2.0-stable or even 2.1 running.

**Comment by lws-team** [comment]
Well... you got the right answer, but not because I looked closer than you did at your code ^^  Anyway all's well that ends well.
