### ISSUE TITLE
libwebsockets (as client) do not check CN in the server's certificate against the URL it is connecting to

### ISSUE THREAD

**Issue by PoltoS** [warmcat/libwebsockets#669]
Looks like libwebsockets client do not check CN field in the server's SSL certificate against the URL it is connecting to.

This leads to an easy man-in-middle attack - any certificate signed by trusted CA will be accepted despite the URL. Common practice is to check for CN flied in the server certificates.

I use version 1.5-chrome47-firefox41 (pretty old, but works well in my OpenWRT based project).

Any suggestions?

**Comment by lws-team** [comment]
It was added before v2.1 (current stable release)... you can either update to v2.1-stable, or backport the patch.

 - the patch is small https://github.com/warmcat/libwebsockets/commit/e7bf0aa1dcaa73171ef300d36ae0b6c3cc5140da although the code will have changed a lot, backport isn't a crazy idea if you match it up by anchors like SSL_new()

 - if you upgrade, at v1.6 there was an api name rationalization.  You can solve it for your code with some search-replaces and three manual steps, here it is explained in the v1.6 changelog https://github.com/warmcat/libwebsockets/blob/v1.6-stable/changelog

**Comment by lws-team** [comment]
I don't think it particularly helps you, but for the record I also backported this to v2.0-stable at the time (June).

**Comment by PoltoS** [comment]
Thanks, this is great to know!

Few questions:
1. curious, what is this for (https://github.com/warmcat/libwebsockets/commit/e7bf0aa1dcaa73171ef300d36ae0b6c3cc5140da?diff=unified#diff-ba2096cb942baa11c032cd716968d55fR44):
                        (void)hostname;
                        (void)param;
2. I've applied the following patch, but now no certs are accepted anymore. Am I doing something wrong?

diff -u libwebsockets-1.5-chrome47-firefox41_/CMakeCache.txt libwebsockets-1.5-chrome47-firefox41/CMakeCache.txt
--- libwebsockets-1.5-chrome47-firefox41_/CMakeCache.txt	2016-11-12 01:13:46.947168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/CMakeCache.txt	2016-11-13 06:20:43.675168000 +0300
@@ -225,6 +225,9 @@
 //Libwebsocket static library
 LIBWEBSOCKETS_LIBRARIES_STATIC:STRING=websocket
 
+//No help, variable specified on the command line.
+LWS_HAVE_X509_VERIFY_PARAM_set1_host:UNINITIALIZED=ON
+
 //Installation directory for executables
 LWS_INSTALL_BIN_DIR:PATH=bin
 
diff -u libwebsockets-1.5-chrome47-firefox41_/CMakeLists.txt libwebsockets-1.5-chrome47-firefox41/CMakeLists.txt
--- libwebsockets-1.5-chrome47-firefox41_/CMakeLists.txt	2016-11-12 01:13:46.935168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/CMakeLists.txt	2016-11-13 06:20:42.079168000 +0300
@@ -266,6 +266,7 @@
 CHECK_FUNCTION_EXISTS(strerror LWS_HAVE_STRERROR)
 CHECK_FUNCTION_EXISTS(vfork LWS_HAVE_VFORK)
 CHECK_FUNCTION_EXISTS(getifaddrs LWS_HAVE_GETIFADDRS)
+CHECK_FUNCTION_EXISTS(X509_VERIFY_PARAM_set1_host LWS_HAVE_X509_VERIFY_PARAM_set1_host)
 
 if (NOT LWS_HAVE_GETIFADDRS)
 	if (LWS_WITHOUT_BUILTIN_GETIFADDRS)
diff -u libwebsockets-1.5-chrome47-firefox41_/lws_config.h libwebsockets-1.5-chrome47-firefox41/lws_config.h
--- libwebsockets-1.5-chrome47-firefox41_/lws_config.h	2016-11-12 01:13:46.935168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/lws_config.h	2016-11-13 06:20:43.491168000 +0300
@@ -62,4 +62,7 @@
 /* use SHA1() not internal libwebsockets_SHA1 */
 /* #undef LWS_SHA1_USE_OPENSSL_NAME */
 
+/* Check URL against Common Name in the server's certificate */
+#define LWS_HAVE_X509_VERIFY_PARAM_set1_host
+
 #define LWS_SIZEOFPTR 4
diff -u libwebsockets-1.5-chrome47-firefox41_/lws_config.h.in libwebsockets-1.5-chrome47-firefox41/lws_config.h.in
--- libwebsockets-1.5-chrome47-firefox41_/lws_config.h.in	2016-11-12 01:13:46.947168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/lws_config.h.in	2016-11-13 06:20:42.079168000 +0300
@@ -62,4 +62,7 @@
 /* use SHA1() not internal libwebsockets_SHA1 */
 #cmakedefine LWS_SHA1_USE_OPENSSL_NAME
 
+/* Check URL against Common Name in the server's certificate */
+#cmakedefine LWS_HAVE_X509_VERIFY_PARAM_set1_host
+
 ${LWS_SIZEOFPTR_CODE}
diff -u libwebsockets-1.5-chrome47-firefox41_/lib/client.c libwebsockets-1.5-chrome47-firefox41/lib/client.c
--- libwebsockets-1.5-chrome47-firefox41_/lib/client.c	2016-11-12 01:13:46.931168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/lib/client.c	2016-11-13 06:20:42.079168000 +0300
@@ -134,12 +134,21 @@
 		/* we can retry this... just cook the SSL BIO the first time */
 
 		if (wsi->use_ssl && !wsi->ssl) {
-#if defined(CYASSL_SNI_HOST_NAME) || defined(WOLFSSL_SNI_HOST_NAME) || defined(SSL_CTRL_SET_TLSEXT_HOSTNAME)
 			const char *hostname = lws_hdr_simple_ptr(wsi,
 						_WSI_TOKEN_CLIENT_HOST);
-#endif
+			X509_VERIFY_PARAM *param;
 
 			wsi->ssl = SSL_new(context->ssl_client_ctx);
+
+#if defined LWS_HAVE_X509_VERIFY_PARAM_set1_host
+			param = SSL_get0_param(wsi->ssl);
+			/* Enable automatic hostname checks */
+			X509_VERIFY_PARAM_set_hostflags(param,
+							X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
+			X509_VERIFY_PARAM_set1_host(param, hostname, 0);
+			/* Configure a non-zero callback if desired */
+			SSL_set_verify(wsi->ssl, SSL_VERIFY_PEER, 0);
+#endif
 #ifndef USE_WOLFSSL
 			SSL_set_mode(wsi->ssl,
 					SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);
diff -u libwebsockets-1.5-chrome47-firefox41_/lib/private-libwebsockets.h libwebsockets-1.5-chrome47-firefox41/lib/private-libwebsockets.h
--- libwebsockets-1.5-chrome47-firefox41_/lib/private-libwebsockets.h	2016-11-12 01:13:46.931168000 +0300
+++ libwebsockets-1.5-chrome47-firefox41/lib/private-libwebsockets.h	2016-11-13 06:20:42.079168000 +0300
@@ -164,6 +164,7 @@
 #include <openssl/err.h>
 #include <openssl/md5.h>
 #include <openssl/sha.h>
+#include <openssl/x509v3.h>
 #endif /* not USE_WOLFSSL */
 #endif

**Comment by PoltoS** [comment]
Is it worth/hard to should switch to the latest LWS? I'm a bit under pressure with our project and have no time to make full tests after upgrading LWS - this is why backport looks more reasonable. But now after wasting a full day on debugging this backport on OpenWRT I fear it might be worth ;(

**Comment by lws-team** [comment]
1. Some cross toolchains warn on unused function params.  This 'uses' them.  Depending on the preprocessor defines, unused function params can be expected and unremarkable.

2.  Dunno... you need to dump what openssl actually found to object to.

3.  Yes all else being equal of course it's better to use modern stuff if you need support.  Nobody would choose to use 1.5 today.

**Comment by PoltoS** [comment]
Interesting, if I backport it as is, I get:
ERR: SSL connect error 336134278: error:14090086:lib(20):func(144):reason(134)
ERR: SSL connect error 336142450: error:14092072:lib(20):func(146):reason(114)
ERR: server's cert didn't look good, X509_V_ERR = 62: error:0000003E:lib(0):func(0):reason(62)

If I comment SSL_set_verify (becuase before the patch it was never called explicitelly in LWS code), I get only:
ERR: server's cert didn't look good, X509_V_ERR = 62: error:0000003E:lib(0):func(0):reason(62)

This means "hostname mismatch", which is not true in my case - CN == server name. No idea where to dig deeper...

In future will allocate time to move to 2.1. Looks you have some quite cool features now.

**Comment by lws-team** [comment]
Not sure what "it" is any more in your first sentence.

SSL reason 134 seems related to the ability of OpenSSL to validate the CA that signed the cert.

Does your client box have such a thing?

**Comment by PoltoS** [comment]
It does. It has a list of CA it validates against. Even without verify it complains about self-signed if no trusted CA found in the chain.

Ok, lets clise the issue. Thabks for your help with the backport. Will need to learn more about OpenSSL to understand the matter.
