### ISSUE TITLE
Returning JSON response.

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#670]
Hi, 

I have a route for `/get-version`, and I'm having trouble returning response from the server.

```
if (!strcmp((char *)pss->onward, "/get-version")) {
    printf("================= GET VERSION =================\n");
}
```

For now, all it does is print something on the terminal after I make a `POST` request to `localhost:port/get-version`

```
<form action="get-version" method="post">
    <input type="hidden" name="get_version">
    <button type="submit">Get Version</button>
</form>
```

What I'm trying to accomplish is to have the backend to return data in `JSON` format.

Example:

```
{
    version: "v1.0.0"
}
```

Is there a built in function to achieve this or do I have to use external lib? I have tried with `lws_return_http_status` but the third argument is returning an *html*.

Thanks

**Comment by lws-team** [comment]
JSON is trivial to compose (it's a bit harder to parse properly).  For that reason there's a JSON parser in lws, but no tools for composing it.

Ignoring the JSON for a minute take a look at the POST sample code

https://github.com/warmcat/libwebsockets/blob/master/plugins/protocol_post_demo.c#L138

It shows how to respond to a POST, the demo has argument parsing but you can chop it out if you don't care.

If you replace the HTML response at LWS_CALLBACK_HTTP_BODY_COMPLETION with JSON, that sounds like it will do what you want.

**Comment by d30jeff** [comment]
Thanks a lot, after 6 hours, I managed to get it to work lol.

For anyone else reading this having issues with making an AJAX `POST` request, you might want to add a hidden field of `admin` with the value of `needadmin/admin-login.html`

*Example:*
```
$.ajax({
  method: "POST",
  data: {
    admin: "needadmin/admin-login.html"
  },
  url: '/lwsgs/get-version'
  // rest of the code
});
```

Cheers.

Closing ticket.
Thanks again.
