### ISSUE TITLE
upload file with POST: callback with LWS_UFS_FINAL_CONTENT missing

### ISSUE THREAD

**Issue by neo9903** [warmcat/libwebsockets#671]
Hello,

When uploading a file with http post sometimes the fileupload-callback with LWS_UFS_FINAL_CONTENT doesn't get called.

It only happens with some files. And it doesn't fail every time.
I think the only difference is the length of the random number in the boundary.

I discovered that the LWS_UFS_FINAL_CONTENT  doesn't get called because, s->pos = 0 (server.c Line 8 of lws_urldecode_s_process) gets executed right before final would get called. 

File to Upload that randomly fails. (hasChangedWorker.lua)
[hasChangedWorker.txt](https://github.com/warmcat/libwebsockets/files/588725/hasChangedWorker.txt)

Exported Requests from Fiddler
[WorkingRequest.txt](https://github.com/warmcat/libwebsockets/files/588722/WorkingRequest.txt)
[BrokenRequest.txt](https://github.com/warmcat/libwebsockets/files/588723/BrokenRequest.txt)

If i send the broken Request it fails every time.
If i send the working request if works every time.

I hope i is possible to reproduce the problem.

Thanks

**Comment by lws-team** [comment]
Before I look at it... what version of lws is this?  Because there was a bug related to tracking CRLFs that got fixed in October

https://github.com/warmcat/libwebsockets/commit/8187c76943af03d7d3ae9fa11cb85cc7c5860520

**Comment by neo9903** [comment]
Version 2.1 
The CRLF Bug was also found by me. I tested it and it is not the same bug. 
Thanks

**Comment by lws-team** [comment]
Well, you're doing a good job finding problems ^^

Comparing broken and working as you say it seems to be the boundary again somehow.  I'll try feed your files into the parser somehow and see what happens.

**Comment by lws-team** [comment]
I was able to reproduce it with netcat and the demo POST plugin.

Please give this a try

https://github.com/warmcat/libwebsockets/commit/56826dbfd75c304f5466045646aaba1010539086

It's pushed on master + v2.1-stable

**Comment by neo9903** [comment]
I have tested it with the scenarios that failed before.
It looks like it is fixed now.

Thanks for the quick fix.
