### ISSUE TITLE
user==NULL in callback with reason LWS_CALLBACK_CLOSED_HTTP

### ISSUE THREAD

**Issue by locobert** [warmcat/libwebsockets#676]
In a pure HTTP application and under high load, the HTTP callback for the reason LWS_CALLBACK_CLOSED_HTTP is sometimes called with user==NULL

I'm wondering if this is intended and must be expected and handled by the application, or if this indicates a bug (in which case I can provide more information)

The stack trace is as follows:
- callback_http
- lws_close_free_wsi
- lws_server_socket_service
  - in the `if (ah->rxpos == ah->rxlen)` branch at `case LWS_SSL_CAPABLE_ERROR`
- lws_service_fd_tsi
- lws_service_fd
- lws_accept_cb
- ev_invoke_pending
- ev_run
- main

Environment: LWS 2.0.3 with libev, macOS and Linux, load generated with curl

**Comment by lws-team** [comment]
I would guess it is failing immediately after it was created, before it got any headers.

If so, NULL user on http close callback is probably a reasonable thing.

**Comment by locobert** [comment]
Sounds reasonable. Thanks!
