### ISSUE TITLE
struct lws_protocol user

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#680]
I probe to use

static struct lws_protocols protocols[] = {  
    {
        "my_protocol",
        my_callback,
        sizeof(Client**), 0xFFFFFF
    },
    {
        NULL, NULL, 0
    }

I expect, when i receive LWS_CALLBACK_WSI_CREATE, that the field "user" points to a location with 4 bytes and that I can set, for example with

my_callback ...
...
*static_cast<Client**>(user) = new Client();

But this don't work because the user is always NULL. Where is my error ? How can I utilize the user area ?

Thank you

Mario

**Comment by lws-team** [comment]
The user field gets allocated later than LWS_CALLBACK_WSI_CREATE, which is the earliest indication a new wsi has been created.

Notice

 - the user allocation is defined in the protocol struct

 - for ws connections, it is not decided what protocol was negotiated until after the http - ws upgrade completes much later... the ESTABLISHED callback is coming then, with a valid user pointer.  Once it's negotiated it cannot change for the rest of the lifetime of the wsi.

 - for http connections, the url path can bind the connection to a different 'mount'.  With keepalive, which is the default, one wsi may visit multiple URLs and thus bind to different protocols sequentially.  LWS_CALLBACK_HTTP_BIND_PROTOCOL is called when the wsi binds to a protocol, creating the user allocation, and ..._DROP_PROTOCOL is called before the wsi destroys the user allocation.

**Comment by rollen1960** [comment]
Thank you, all right !
