### ISSUE TITLE
Link error on Mac OS X ( _ERR_remove_thread_state )

### ISSUE THREAD

**Issue by joshcameron** [warmcat/libwebsockets#683]
I have a Homebrew installed OpenSSL library on Mac OS X. In my case, it's installed in `/usr/local/Cellar/openssl/1.0.2j`. The libwebsockets build could not find it at link time, even after I set `$OPENSSL_ROOT_DIR`. It seems setting `$OPENSSL_ROOT_DIR` allowed the build to find the headers, but not the libs.

I was finally able to build libwebsockets using `cmake .. -DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/Cellar/openssl/1.0.2j/include -DLWS_OPENSSL_LIBRARIES="/usr/local/Cellar/openssl/1.0.2j/lib/libssl.dylib;/usr/local/Cellar/openssl/1.0.2j/lib/libcrypto.dylib"` to configure the make.

**Comment by joshcameron** [comment]
The link error was:
`Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _lws_ssl_destroy in libwebsockets.a(ssl.c.o)
      _lws_ssl_context_destroy in libwebsockets.a(ssl.c.o)`

**Comment by lws-team** [comment]
If I understood, this is a story with a happy ending already, you just propose to add a note summarizing this to REAADME.build.md?

**Comment by lws-team** [comment]
Well... if it is a happy, educational story for future sufferers, could you possibly send me a patch on README.build.md explaining it?

Or, if there is still some problem to look at, can you clarify what the remaining problem is?

**Comment by joshcameron** [comment]
Yes, this is a story with a happy ending, for my build at least. Ideally, setting `$OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2j` and running `cmake ..; make` should have been enough, though. That was enough to solve my include problems but not my link problems. If the build can't be fixed to find the libraries based on `$OPENSSL_ROOT_DIR`, then please document the fix I describe above in README.build.md for other Homebrew users.

**Comment by lws-team** [comment]
I haven't forgotten about this.

But there seems to be something else going on with cmake and non-OS openssl as well.

For example I built and installed a newer OpenSSL the other day in /usr/local.  This was able to build well... one time.

After a lot of head scratching I found out two things

 - I could make it build well again against the new OpenSSL by cutting and pasting the ccache line used to iinvoke the linker (via make VERBOSE=1) and adding -L/usr/local/lib64 on the line.  For reference it's like this here (I added the -L... )

```
/usr/lib64/ccache/cc -L/usr/local/lib64 -fPIC  -Wall -Werror -fvisibility=hidden  -pthread -g   CMakeFiles/test-client.dir/test-server/test-client.c.o  -o bin/libwebsockets-test-client -rdynamic lib/libwebsockets.a -lz -lssl -lcrypto -luv -lm -ldl
```

 - I could also make it link well again against the OS OpenSSL by mv-ing /usr/local/include out of existence temporarily.

So it seems at least the ccache link auto-prefers /usr/local/include if it exists, even if it is not told to use it, creating trouble by compiling with new OpenSSL includes and then linking aginst the OS old OpenSSL libs.  Unfortunately I don't have any good ideas left atm to get to the bottom of this.  It was still true starting a new build dir and not giving any special cmake flags about OpenSSL.

Also I think what's already in README.build.md covers what you did, unless I miss the point

```
NOTE4: If you are building against a non-distro OpenSSL (eg, in order to get access to ALPN support only in newer OpenSSL versions) the nice way to express that in one cmake command is eg,

    $ cmake .. -DOPENSSL_ROOT_DIR=/usr/local/ssl \
         -DCMAKE_INCLUDE_DIRECTORIES_PROJECT_BEFORE=/usr/local/ssl \
         -DLWS_WITH_HTTP2=1

When you run the test apps using non-distro SSL, you have to force them to use your libs, not the distro ones

    $ LD_LIBRARY_PATH=/usr/local/ssl/lib libwebsockets-test-server --ssl

To get it to build on latest openssl (2016-04-10) it needed this approach

    cmake .. -DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/include/openssl -DLWS_OPENSSL_LIBRARIES="/usr/local/lib64/libssl.so;/usr/local/lib64/libcrypto.so"
```

**Comment by lws-team** [comment]
I think this is documented enough... and I can't solve the related problem I mentioned about ccache.

**Comment by whisper-bye** [comment]
+1

➜  build git:(master) make
[ 33%] Built target websockets
[ 34%] Linking C executable bin/libwebsockets-test-server-extpoll
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _lws_ssl_destroy in libwebsockets.a(ssl.c.o)
      _lws_ssl_context_destroy in libwebsockets.a(ssl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libwebsockets-test-server-extpoll] Error 1
make[1]: *** [CMakeFiles/test-server-extpoll.dir/all] Error 2
make: *** [all] Error 2

**Comment by lws-team** [comment]
Did you follow Josh's recommendations?

In travis, it builds OK for Mac.  Eg,

https://travis-ci.org/warmcat/libwebsockets/jobs/203645569

**Comment by whisper-bye** [comment]
@lws-team 
great! It works for me with "export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k"; cmake ..; make -j4

**Comment by dirkharbinson** [comment]
Cheers, just had the same problem and the above line (which references homebrew's openssl path) works a treat

**Comment by lws-team** [comment]
I added a small doc patch with whisperbye's line.
