### ISSUE TITLE
Provide explicit callback for X.509 client errors

### ISSUE THREAD

**Issue by smipi1** [warmcat/libwebsockets#684]
The only way to tie behavior to the X.509 client errors in libwebsockets, is to parse the libwebsockets log messages. Can you add a LWS_CALLBACK_CLIENT_X509_ERROR callback that provides the X509_V_ERR value to a client application?

**Comment by lws-team** [comment]
Maybe... why don't you send a patch and we will see?

**Comment by smipi1** [comment]
What? No pony for Christmas? ;-)

I'll free up some time for this...

**Comment by lws-team** [comment]
I'll be very happy to look at your patch... please update when it's ready.
