### ISSUE TITLE
lws_hdr_copy

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#686]
Hallo,

i probe to read the arguments in a HTTP request.

I use lws_hdr_copy(wsi, dest, sizeof(dest), WSI_TOKEN_HTTP_URI_ARGS) with the request
http://dev-msp:9003/?&n1=v1&n2=v2

dest is n1=v1n2=v2

How can I distinguish the parameters name n1 and n2 if is not the & ?

Thank you

Mario

**Comment by lws-team** [comment]
https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L2679

**Comment by lws-team** [comment]
This is handy too

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L2700
