### ISSUE TITLE
close silent client connection

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#695]
hello sir,
There is any way to close connection from WebSocket server side, if client does not send message to server for a long time.. like in lws-mirror-protocol.. if i were not draw image for a long time.. connection is still open.. it can't be free for other client when server is limited to fix number of clients
thanks

**Comment by lws-team** [comment]
Use the timeout api

/**
 * lws_set_timeout() - marks the wsi as subject to a timeout
 *
 * You will not need this unless you are doing something special
 *
 * \param wsi:	Websocket connection instance
 * \param reason:	timeout reason
 * \param secs:	how many seconds
 */
LWS_VISIBLE LWS_EXTERN void
lws_set_timeout(struct lws *wsi, enum pending_timeout reason, int secs);
///@}

Every time something happens on a wsi, reset the wsi's timeout, to 500 secs or whatever.  If nothing resets the timeout for `secs` seconds, the connection will be closed cleanly and automatically.

You can choose an arbitrary timeout reason like 1000.  If it times out for your reason, you will see your reason number mentioned.
