### ISSUE TITLE
When opcode setted to 0xB?

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#697]
Dear Andy,

We are using libwebsocket 1.7.9 for server function.
Our client said to us that they disconnected socket because they received opcode=0x0B.
We(server) didn't intend to disconnect that socket.
Can you check why server send 0x0B even though we didn't intend to disconnect?

Thanks,
oshare.

**Comment by kjnoh77** [comment]
*    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
	 *   +-+-+-+-+-------+-+-------------+-------------------------------+
	 *   |F|R|R|R| opcode|R| Payload len |    Extended payload length    |

our client received next frame.

receivedOpcode:nil baseAddress[0]:123 -> 0111 1011 
Opcode:  4 bits               
     *  %xB-F are reserved for further control frames

**Comment by kjnoh77** [comment]
It's reproduced when using "wss:".
It looks like that it's not reproduced when using "ws:".

**Comment by lws-team** [comment]
I got a better idea... if you think this is an lws issue you are having, YOU show ME the code in lws that is responsible.

I don't have your problem and I don't have your faith this is an issue in lws either.

ssl / wss is a transparent pipe when it's working, it sounds like something about that is not working, and you have lost sync with the byte stream alignment to the ws fragment headers.

Feel free to reopen if you get some clue and evidence about where your issue comes from, and it is related to lws itself.

**Comment by kjnoh77** [comment]
Thank you for  your  answer!

Let me ask a question  just  one  more.
Yes, we are using two thread for non secure port  and  secure  port.
And they  invoke  same  callback_http() because  they  handle  same  user  protocol.
In our user senario, http and wss event can be invoke simultanously, but ws and wss event can't be invoked simultanously.
Anyway, simultanously event of http and wss can derive critical section error? If so, it can be prevented using mutex inside of callback_http()?

Thank you!

**Comment by lws-team** [comment]
> Yes, we are using two thread for non secure port and secure port.

Ehhhh don't do that.  I have no idea what that would even look like that even half working.  Read README.coding,md

```
@section evtloop Libwebsockets is singlethreaded

Libwebsockets works in a serialized event loop, in a single thread.

Directly performing websocket actions from other threads is not allowed. Aside from the internal data being inconsistent in forked() processes, the scope of a wsi (struct websocket) can end at any time during service with the socket closing and the wsi freed.

Websocket write activities should only take place in the LWS_CALLBACK_SERVER_WRITEABLE callback as described below.
```

lws is a singlethreaded, serialized event loop type of deal.  It is deliberately not threadsafe.

Do not spawn two "threads".  One thread, one lws context.

There are two ways to come at supporting both SSL or not SSL

1) Support SSL and not SSL on the same listen port.  Yes you can do it, use LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT in info.options when creating the context.  That's all.

2) Support SSL on one port, and non-SSL on another port.  Use LWS_SERVER_OPTION_EXPLICIT_VHOSTS and create 2 x vhost with lws_create_vhost() after you create the context: one listens on one port (eg, 443) and has SSL + certs enabled.  The other listens on another port (eg, 80) and either redirects to the 443 / https port or serves his own, possibly different stuff.

One thread.  One context.

-Andy
