### ISSUE TITLE
unknow opcode 0xB

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#699]
Here is our user code using libwebsockets.
I generate two port by using lws_create_vhost().(one is secure and the other is non-secure port)
I believe two service will working at same thread.
But, still it looks like that client sometimes receive unexpected opcode=0xB.
Could you review this user code?

============================================

#include <dlog.h>
#include <pthread.h>
#include <json/json.h>
#include <sdp/sdp_api.h>
#include <ss/ss_api.h>

//#define DUMP_HANDSHAKE_INFO

std::string Server::serverPort;
char* Server::private_key_pw = NULL;

std::map<struct lws*, Websocket*> Server::InstanceMap;
std::map<Websocket*, void*> Server::WebsocketAliveMap;

std::map<struct lws*, HttpMessage*> Server::HttpInstanceMap;
std::map<HttpMessage*, void*> Server::HttpAliveMap;

void Server::dump_handshake_info(struct lws *wsi)
{
	int n = 0, len;
	char buf[256];
	const unsigned char *c;

	do {
		c = lws_token_to_string((lws_token_indexes)n);
		if (!c) {
			n++;
			continue;
		}

		len = lws_hdr_total_length(wsi, (lws_token_indexes)n);
		if (!len || (unsigned int)len > sizeof(buf) - 1) {
			n++;
			continue;
		}

		lws_hdr_copy(wsi, buf, sizeof buf, (lws_token_indexes)n);
		buf[sizeof(buf) - 1] = '\0';

		PGM_DLOG_INFO("%s = %s", (char *)c, buf);
		n++;
	} while (c);
}

int Server::callback_http(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
	switch (reason) {
		case LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION");
				char Buf[128] = {0,};
				memset(Buf, 0, sizeof(Buf));
				lws_hdr_copy(wsi, Buf, sizeof(Buf), WSI_TOKEN_PROTOCOL);
				PGM_DLOG_INFO("protocol is '%s'", Buf);
			}
			break;

		case LWS_CALLBACK_ESTABLISHED:
			{
				PGM_DLOG_INFO("SERVER : ESTABLISHED (wsi:0x%x)", wsi);

#ifdef DUMP_HANDSHAKE_INFO
				dump_handshake_info(wsi);
#endif

				Websocket* pWebsocket = new Websocket(wsi);
				if (pWebsocket == NULL) {
					PGM_DLOG_FATAL("error : cannot create new instance for this wsi(0x%x)", wsi);
					return -1;
				}
				InstanceMap.insert({wsi, pWebsocket});

				WebsocketAliveMap.insert({pWebsocket, NULL});

				if (connection == "Upgrade") {
          Channel::onSocketConnection(pWebsocket, path.c_str());
				}
			}
			break;

		case LWS_CALLBACK_RECEIVE:
			{
				//PGM_DLOG_INFO("SERVER : LWS_CALLBACK_RECEIVE");

				if (InstanceMap.find(wsi) == InstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				Websocket* pWebsocket = (InstanceMap.find(wsi))->second;

				if (lws_remaining_packet_payload(wsi) == 0) { // recieved all data
					{
						Channel::onSocketMessage(pWebsocket, (const char*)(pWebsocket->ReceiveBuf), pWebsocket->ReceivedLength, lws_frame_is_binary(wsi));
					}

					// cleanup receive buffer
					if (pWebsocket->ReceiveBuf) {
						free(pWebsocket->ReceiveBuf);
					}
					pWebsocket->ReceiveBuf = (unsigned char*)calloc(1, sizeof(char));
					pWebsocket->ReceivedLength = 0;
				}
			}
			break;

		case LWS_CALLBACK_RECEIVE_PONG:
			{
				//PGM_DLOG_INFO("SERVER : LWS_CALLBACK_RECEIVE_PONG");

				if (InstanceMap.find(wsi) == InstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				Websocket* pWebsocket = (InstanceMap.find(wsi))->second;

				pWebsocket->numberNotAck = 0;
			}
			break;

		case LWS_CALLBACK_SERVER_WRITEABLE:
			{
				//PGM_DLOG_INFO("SERVER : LWS_CALLBACK_SERVER_WRITEABLE");

				if (InstanceMap.find(wsi) == InstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				Websocket* pWebsocket = (InstanceMap.find(wsi))->second;

				if (pWebsocket->CloseRequest) {
					PGM_DLOG_INFO("'%s' will be closed(wsi:0x%x)", pWebsocket->GetID().c_str(), wsi);
					RemoveWebsocket(wsi);
					return -1; // to close this wsi
				}

				pthread_mutex_lock(&pWebsocket->SendBufMutex);
				while (pWebsocket->SendBuf_Q.begin() != pWebsocket->SendBuf_Q.end()) {
					SendBufList::iterator itr = pWebsocket->SendBuf_Q.begin();
					_SendBufInfo SendBufInfo = *itr;
					pWebsocket->SendBuf_Q.erase(itr);

					bool BinaryFlag = SendBufInfo.BinaryFlag;
					bool IsPingpongSend = SendBufInfo.IsPingpongSend;
					unsigned char* SendBuf = SendBufInfo.SendBuf;
					int SendLength = SendBufInfo.SendLength;
					int MsgId = SendBufInfo.MsgId;

					if (SendBuf == NULL) {
						PGM_DLOG_INFO("Send Buf is NULL");
						continue;
					}

					if (SendLength == 0) {
						PGM_DLOG_INFO("Send Length is 0");
						continue;
					}

					int n = 0;

					if (BinaryFlag) {
						n = lws_write(wsi, &(SendBuf[LWS_SEND_BUFFER_PRE_PADDING]), SendLength, LWS_WRITE_BINARY);
					}
					else {
						n = lws_write(wsi, &(SendBuf[LWS_SEND_BUFFER_PRE_PADDING]), SendLength, LWS_WRITE_TEXT);
					}

					if (n < 0) {
						PGM_DLOG_FATAL("socket write failed. Msg ID:%d, To:'%s'", MsgId, pWebsocket->GetID().c_str());
					}
					else {
						if ((pWebsocket->ForDevLogging == false) && (IsPingpongSend == false)) {
							PGM_DLOG_INFO("Msg ID:%d, Length:%d, To:'%s'", MsgId, n, pWebsocket->GetID().c_str());
						}
					}

					// cleanup write buffer
					if ((SendBuf != NULL)) {
						free(SendBuf);
						SendBuf = NULL;
					}
				}
				pthread_mutex_unlock(&pWebsocket->SendBufMutex);
			}
			break;

		case LWS_CALLBACK_CLOSED:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_CLOSED (wsi:0x%x)", wsi);
				RemoveWebsocket(wsi);
			}
			break;

		case LWS_CALLBACK_CLIENT_RECEIVE_PONG:
			PGM_DLOG_INFO("SERVER : LWS_CALLBACK_CLIENT_RECEIVE_PONG");
			break;

		case LWS_CALLBACK_HTTP:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_HTTP (wsi:0x%x)", wsi);

#ifdef DUMP_HANDSHAKE_INFO
				dump_handshake_info(wsi);
#endif

				HttpMessage* pHttpMessage;
				if (HttpInstanceMap.find(wsi) == HttpInstanceMap.end()) {
					pHttpMessage = new HttpMessage(wsi);
					if (pHttpMessage == NULL) {
						PGM_DLOG_FATAL("error : cannot create new instance for this wsi(0x%x)", wsi);
						return -1;
					}
					HttpInstanceMap.insert({wsi, pHttpMessage});
				}
				else {
					pHttpMessage = (HttpInstanceMap.find(wsi))->second;
				}

				HttpAliveMap.insert({pHttpMessage, NULL});

				pHttpMessage->AnalyzeRequest();

				if (pHttpMessage->ReqBodyExist == false) {
					pHttpMessage->onHTTPRequest();
				}
			}
			break;

		case LWS_CALLBACK_HTTP_BODY:
			{
				//PGM_DLOG_INFO("SERVER : LWS_CALLBACK_HTTP_BODY (wsi:0x%x)", wsi);

				if (HttpInstanceMap.find(wsi) == HttpInstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				HttpMessage* pHttpMessage = (HttpInstanceMap.find(wsi))->second;

				pHttpMessage->ReqBodyTmp = (unsigned char*)realloc(pHttpMessage->ReqBodyTmp, pHttpMessage->ReqBodyLengthTmp + len);
				memcpy(&(pHttpMessage->ReqBodyTmp[pHttpMessage->ReqBodyLengthTmp]), (char*)in, len);
				pHttpMessage->ReqBodyLengthTmp = pHttpMessage->ReqBodyLengthTmp + len;
			}
			break;

		case LWS_CALLBACK_HTTP_BODY_COMPLETION:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_HTTP_BODY_COMPLETION (wsi:0x%x)", wsi);

				if (HttpInstanceMap.find(wsi) == HttpInstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				HttpMessage* pHttpMessage = (HttpInstanceMap.find(wsi))->second;

				pHttpMessage->ReqBody = (unsigned char*)calloc(pHttpMessage->ReqBodyLengthTmp, sizeof(char));
				memcpy(pHttpMessage->ReqBody, pHttpMessage->ReqBodyTmp, pHttpMessage->ReqBodyLengthTmp);
				pHttpMessage->ReqBodyLength = pHttpMessage->ReqBodyLengthTmp;

				PGM_DLOG_DEBUG("HTTP REQ BODY length = %d", pHttpMessage->ReqBodyLength);

				pHttpMessage->onHTTPRequest();

				// cleanup tmp receive buffer
				if (pHttpMessage->ReqBodyTmp) {
					free(pHttpMessage->ReqBodyTmp);
					pHttpMessage->ReqBodyTmp = NULL;
				}
				pHttpMessage->ReqBodyTmp = (unsigned char*)calloc(1, sizeof(char));
				pHttpMessage->ReqBodyLengthTmp = 0;
			}
			break;

		case LWS_CALLBACK_HTTP_WRITEABLE:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_HTTP_WRITEABLE (wsi:0x%x)", wsi);

				if (HttpInstanceMap.find(wsi) == HttpInstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return -1;
				}
				HttpMessage* pHttpMessage = (HttpInstanceMap.find(wsi))->second;

				int n = lws_write(wsi, pHttpMessage->ResponseBody, pHttpMessage->ResponseBodyLength, LWS_WRITE_HTTP);
				if (n == pHttpMessage->ResponseBodyLength) {
					PGM_DLOG_DEBUG("success for 'Requested Id : %d' (written length=%d)", 
									pHttpMessage->RequestedId, n);
				}
				else {
					PGM_DLOG_FATAL("error for 'Requested Id : %d' (req length=%d, written length=%d)",
									pHttpMessage->RequestedId, pHttpMessage->ResponseBodyLength, n);
				}
				return -1;
			}
			break;

		case LWS_CALLBACK_CLOSED_HTTP:
			{
				PGM_DLOG_INFO("SERVER : LWS_CALLBACK_CLOSED_HTTP (wsi:0x%x)", wsi);

				if (HttpInstanceMap.find(wsi) == HttpInstanceMap.end()) {
					PGM_DLOG_FATAL("error : cannot find instance for this wsi(0x%x)", wsi);
					return 0;
				}
				HttpMessage* pHttpMessage = (HttpInstanceMap.find(wsi))->second;
				HttpInstanceMap.erase(HttpInstanceMap.find(wsi));

				if (HttpAliveMap.find(pHttpMessage) != HttpAliveMap.end()) {
					HttpAliveMap.erase(HttpAliveMap.find(pHttpMessage));
				}

				delete pHttpMessage;
			}
			break;

		default:
			if ((reason != LWS_CALLBACK_GET_THREAD_ID) && (reason != LWS_CALLBACK_CHANGE_MODE_POLL_FD) &&
				(reason != LWS_CALLBACK_LOCK_POLL) && (reason != LWS_CALLBACK_UNLOCK_POLL)) {
				PGM_DLOG_INFO("SERVER : %d", reason);
			}
			break;
	}

	return 0;
}
      :
void* Server::ServerThread(void* data)
{
	static struct lws_protocols protocols[] = {
		/* first protocol must always be HTTP handler */
		{
			"http-only",		/* name */
			callback_http,		/* callback */
			sizeof (struct per_session_data__http),	/* per_session_data_size */
			0,			/* max frame size / rx buffer */
		},
		{
			NULL,		/* name */
			callback_null,		/* callback */
			0,	/* per_session_data_size */
			0,			/* max frame size / rx buffer */
		},
		{
			"msf-2",
			callback_msf2,
			0,
			0,
		},
		{ // for c# client
			"basic",
			callback_basic,
			0,
			0,
		},
		{
			"dumb-increment-protocol",
			callback_dumb_increment,
			sizeof(struct per_session_data__dumb_increment),
			10,
		},
		{
			"lws-mirror-protocol",
			callback_lws_mirror,
			sizeof(struct per_session_data__lws_mirror),
			128,
		},
		{
			"lws-echogen",
			callback_lws_echogen,
			sizeof(struct per_session_data__echogen),
			128,
		},
		{
			"lws-status",
			callback_lws_status,
			sizeof(struct per_session_data__lws_status),
			128,
		},
		{ NULL, NULL, 0, 0 } /* terminator */
	};

	int use_ssl = 0;
	int n = 0;
	// int ret = 0;

	struct lws_context *context;

	struct lws_context_creation_info info;

	memset(&info, 0, sizeof info);
	info.port = WEBSOCKET_SERVER_SECURE_PORT;
	info.protocols = protocols;
	info.extensions = NULL;
	info.ssl_cert_filepath = CERT_PATH;
	info.ssl_private_key_filepath = PRIVATE_KEY_PATH;
	info.ssl_private_key_password = private_key_pw;
	info.ssl_ca_filepath = CA_PATH;
	info.ssl_cipher_list = "ECDHE-RSA-AES256-SHA384:"
						"DHE-RSA-AES256-SHA384:"
						"ECDHE-RSA-AES256-SHA256:"
						"DHE-RSA-AES256-SHA256:"
						"ECDHE-RSA-AES128-SHA256:"
						"DHE-RSA-AES128-SHA256:"
						"HIGH:"
						"!aNULL:"
						"!eNULL:"
						"!EXPORT:"
						"!DES:"
						"!RC4:"
						"!MD5:"
						"!PSK:"
						"!SRP:"
						"!CAMELLIA:"
						"!DES-CBC3-SHA:"
						"!ECDHE-RSA-DES-CBC3-SHA";
	info.gid = -1;
	info.uid = -1;
	info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	info.user = 0;

#ifndef LWS_NO_EXTENSIONS
	// info.extensions = lws_get_internal_extensions();
#endif
	context = lws_create_context(&info);

	if (context == NULL) {
		PGM_DLOG_INFO("create_websocket context failed");
		return NULL;
	}

	memset(&info, 0, sizeof info);
	info.port = WEBSOCKET_SERVER_PORT;
	info.protocols = protocols;
	info.extensions = NULL;
	info.ssl_cert_filepath = NULL;
	info.ssl_private_key_filepath = NULL;
	info.gid = -1;
	info.uid = -1;
	info.options = LWS_SERVER_OPTION_EXPLICIT_VHOSTS;
	info.user = 0;

	lws_create_vhost(context, &info);

	n = 0;
	// loop until socket closed
	while (n >= 0) {
		n = lws_service(context, 0x0FFFFFFF);
	}

	PGM_DLOG_INFO("create_websocket destroy context");

	if (context)
		lws_context_destroy(context);

	return NULL;
}

std::string Server::Port()
{
	return serverPort;
}

void Server::Start()
{
	char port[10] = {0,};
	snprintf((char *)port, sizeof(port), "%d", WEBSOCKET_SERVER_PORT);
	serverPort = port;

	pthread_t ServerThreadID;
	int status = pthread_create(&ServerThreadID, NULL, ServerThread, NULL);
	pthread_detach(ServerThreadID);

	PGM_DLOG_INFO("'%s' server thread created", port);
}

**Comment by kjnoh77** [comment]
We start server service by calling "Server::Start()"

**Comment by lws-team** [comment]
No, I won't spend my morning reviewing your code.

**Comment by kjnoh77** [comment]
Dear Andy.

I think "libsockets" is very good solution for our server service, so always thanks for you.
I feel some difficulty how can I check reason for unexpected opcode which client received.
Could you teach me where can I log opcode which out to client in libwebsockets.
It's OK if you tell us at afternoon.

Best Regards,
oshare.

**Comment by lws-team** [comment]
Lol... the problem is not morning or afternoon.

This is all your code, right?  Why is it my problem to fix your code or even read it?  Do you regard it as your problem to fix things for me?

I already answered this in your other "issue" where you mention you are using multiple threads.

https://github.com/warmcat/libwebsockets/issues/697

You just seemed to ignore the solution I wrote there and opened another issue just asking about an illegal opcode, when your problem seems to be two threads reading from the same fd and turning the stream to junk.

Get rid of your threads and use the solution I wrote on the other "issue" for SSL and on-SSL sharing.  Or don't... it's entirely up to you.

**Comment by kjnoh77** [comment]
Originally, we used multiple thread as I said in other issue. But, I already fixed it after hearing your mention of that "issue".
Now, I made just single thread, and used "lws_create_vhost()" to insert another info(anther port) to same context of same thread.

**Comment by lws-team** [comment]
Does the original test server have the same problem, when running in ssl mode?

**Comment by kjnoh77** [comment]
It looks like that problem also happend in "ws"(non ssl mode).
the clue is that when problem occurred, there was transport of some big data by client's "http" request  in the front and the rear of websocket(ws) transport.
There is some possibillity that data interfare between http and ws?

**Comment by lws-team** [comment]
Does the original test server have the same problem, when running in ssl mode?

**Comment by kjnoh77** [comment]
Yes, it does.
both(orginal(two thread) and fixed(single thread)) have same problem.

**Comment by lws-team** [comment]
I mean libwebsockets-test-server.  Or libwebsockets-test-server-2.0.  Or lwsws.  Ie, if we subtract your code.

Do any of those have the same problem?

If so, let me know how to reproduce.  If not...

**Comment by kjnoh77** [comment]
As above, we made our code referncing libwebsockets-test-server.
And I can't make same senario, without user code over it.
Because this issue looks like be reproduced under specified user condition.
The specified user senario is....
"While client communicate with us(server) over websocket protocol, simultanously same client request us http request"
For example, server side is sending to client next data with Websocket protocol.(We checked it inside of lws_issue_raw() and used monitoring program as like wireshark)
7b,22,72,65....
In Websocket protocol 0x7b(0111 1011 ) is meaning opcode is 'b'.
But, in real, it looks like that it's server's http response body because we(server) really respond {"result":true} as http response body for specified http request.
{"result":true} is 7b,22,72,65.... if it converted to hex.
And, our client said us it's not reproduced using another server(ex:node.js) with same user senario.
(I don't mean node.js is right)
Could you give us some clue?
And I will find clues continuously.

Thanks.

**Comment by lws-team** [comment]
LWS_SERVER_OPTION_EXPLICIT_VHOSTS doesn't work how you are using it... you give it at context creation time to suppress generation of the default vhost.

The rest can't be remotely debugged otherwise with all your unknown c++ etc.

> "While client communicate with us(server) over websocket protocol, simultanously same client request us http request"

What does it really mean?  The problem is still coming if we open an idle ws connection on one wsi and later the same client, on a different wsi / tcp connection, tries to do a GET?

Or we must be spamming the ws connection?  How much do we have to send, if anything?  Or do we have to receive?

We must reply to the GET to see the problem?  What happens if we send, eg, a 1-byte reply then?

**Comment by kjnoh77** [comment]
I'm so sorry but please forget report until now, and I hope your understanding.
The one thing ovious is that there is phenomenon when client receicve "continuous" frame over websocket protocol.
They(client) receive some frame as next when it's OK.(they recognize it as "continuous" frame)
0,123,34,100,97,116,97,34...
But, they receive some frame as next when it's "not" OK.
123,34,100,97,116...
It's whole same data except the first byte, but they recognize it as "unknow" frame.
Problem is mainly occurring under user environment they receive big websocket data repeatedly in short term from our server.
Should user code of libwebsockets control "continuous" frame?
If not, can you guess when this phenomenon can be occurred?
Thank you for your help.

**Comment by lws-team** [comment]
I dunno what you found in your code but the loss of sync on ws frame boundary is not something you can legitimately provoke from user code in lws.

The reason is lws_write() can only produce whole ws fragments, ie, whole ws frames.  And it manipulates visibility of WRITABLE callback so you will never get one while it is in the middle of a frame.  So there is no legal way to inject something in the middle of a frame.

Therefore it sounds more likely your code explicitly does something crazy like send http response on wrong wsi.  That's nothing to do with me and it's why you should reference the problem against the test apps directly, even if they need a little patch.  If the patch does nothing crazy and reproduces the problem on the test server, then it becomes my problem.

To debug it you must narrow down the conditions necessary to create the problemas I discussed in my previous reply.  What does it really mean about 'same client'?  Lws doesn't track that it's the same client making connections.
