### ISSUE TITLE
build error.  cmake .. -DLWS_USE_LIBEV=NO

### ISSUE THREAD

**Issue by zhangjinming** [warmcat/libwebsockets#700]
log:
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)
---------------------------------------------------------------------
 LWS_WITH_STATIC = ON
 LWS_WITH_SHARED = ON
 LWS_WITH_SSL = ON (SSL Support)
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)
 LWS_WITHOUT_BUILTIN_SHA1 = OFF
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF
 LWS_WITHOUT_CLIENT = OFF
 LWS_WITHOUT_SERVER = OFF
 LWS_LINK_TESTAPPS_DYNAMIC = OFF
 LWS_WITHOUT_TESTAPPS = OFF
 LWS_WITHOUT_TEST_SERVER = OFF
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF
 LWS_WITHOUT_TEST_PING = OFF
 LWS_WITHOUT_TEST_ECHO = OFF
 LWS_WITHOUT_TEST_CLIENT = OFF
 LWS_WITHOUT_TEST_FRAGGLE = OFF
 LWS_WITHOUT_EXTENSIONS = OFF
 LWS_WITH_LATENCY = OFF
 LWS_WITHOUT_DAEMONIZE = ON
 LWS_USE_LIBEV = NO
 LWS_USE_LIBUV = 
 LWS_IPV6 = OFF
 LWS_UNIX_SOCK = OFF
 LWS_WITH_HTTP2 = OFF
 LWS_MBED3 = OFF
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF
 LWS_MAX_SMP = 32
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_HAVE_SSL_CTX_set1_param = 1
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES = 
 PLUGINS = 
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
 LWS_WITH_LEJP = OFF
 LWS_WITH_LEJP_CONF = OFF
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ming/Desktop/libwebsockets-master/build
ming@ubuntu:~/Desktop/libwebsockets-master/build$ make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  2%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  3%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  5%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[  6%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[  7%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[  9%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[ 10%] Building C object CMakeFiles/websockets.dir/lib/context.c.o
[ 11%] Building C object CMakeFiles/websockets.dir/lib/alloc.c.o
[ 12%] Building C object CMakeFiles/websockets.dir/lib/header.c.o
[ 14%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 15%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 16%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 18%] Building C object CMakeFiles/websockets.dir/lib/ssl.c.o
[ 19%] Building C object CMakeFiles/websockets.dir/lib/ssl-server.c.o
[ 20%] Building C object CMakeFiles/websockets.dir/lib/ssl-client.c.o
[ 22%] Building C object CMakeFiles/websockets.dir/lib/sha-1.c.o
[ 23%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-unix.c.o
[ 24%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
[ 28%] Building C object CMakeFiles/websockets.dir/lib/extension-permessage-deflate.c.o
[ 29%] Linking C static library lib/libwebsockets.a
[ 29%] Built target websockets
Scanning dependencies of target test-fuzxy
[ 31%] Building C object CMakeFiles/test-fuzxy.dir/test-server/fuzxy.c.o
[ 32%] Linking C executable bin/libwebsockets-test-fuzxy
[ 32%] Built target test-fuzxy
Scanning dependencies of target test-server
[ 33%] Building C object CMakeFiles/test-server.dir/test-server/test-server.c.o
[ 35%] Building C object CMakeFiles/test-server.dir/test-server/test-server-http.c.o
[ 36%] Building C object CMakeFiles/test-server.dir/test-server/test-server-dumb-increment.c.o
[ 37%] Building C object CMakeFiles/test-server.dir/test-server/test-server-mirror.c.o
[ 38%] Building C object CMakeFiles/test-server.dir/test-server/test-server-status.c.o
[ 40%] Building C object CMakeFiles/test-server.dir/test-server/test-server-echogen.c.o
[ 41%] Linking C executable bin/libwebsockets-test-server
[ 41%] Built target test-server
Scanning dependencies of target websockets_shared
[ 42%] Building C object CMakeFiles/websockets_shared.dir/lib/base64-decode.c.o
[ 44%] Building C object CMakeFiles/websockets_shared.dir/lib/handshake.c.o
[ 45%] Building C object CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.o
[ 46%] Building C object CMakeFiles/websockets_shared.dir/lib/service.c.o
[ 48%] Building C object CMakeFiles/websockets_shared.dir/lib/pollfd.c.o
[ 49%] Building C object CMakeFiles/websockets_shared.dir/lib/output.c.o
[ 50%] Building C object CMakeFiles/websockets_shared.dir/lib/parsers.c.o
[ 51%] Building C object CMakeFiles/websockets_shared.dir/lib/context.c.o
[ 53%] Building C object CMakeFiles/websockets_shared.dir/lib/alloc.c.o
[ 54%] Building C object CMakeFiles/websockets_shared.dir/lib/header.c.o
[ 55%] Building C object CMakeFiles/websockets_shared.dir/lib/client.c.o
[ 57%] Building C object CMakeFiles/websockets_shared.dir/lib/client-handshake.c.o
[ 58%] Building C object CMakeFiles/websockets_shared.dir/lib/client-parser.c.o
[ 59%] Building C object CMakeFiles/websockets_shared.dir/lib/ssl.c.o
[ 61%] Building C object CMakeFiles/websockets_shared.dir/lib/ssl-server.c.o
[ 62%] Building C object CMakeFiles/websockets_shared.dir/lib/ssl-client.c.o
[ 63%] Building C object CMakeFiles/websockets_shared.dir/lib/sha-1.c.o
[ 64%] Building C object CMakeFiles/websockets_shared.dir/lib/lws-plat-unix.c.o
[ 66%] Building C object CMakeFiles/websockets_shared.dir/lib/server.c.o
[ 67%] Building C object CMakeFiles/websockets_shared.dir/lib/server-handshake.c.o
[ 68%] Building C object CMakeFiles/websockets_shared.dir/lib/extension.c.o
[ 70%] Building C object CMakeFiles/websockets_shared.dir/lib/extension-permessage-deflate.c.o
[ 71%] Linking C shared library lib/libwebsockets.so
[ 71%] Built target websockets_shared
Scanning dependencies of target test-fraggle

********** 
libev.o no include.
thanks fix this error.

**Comment by lws-team** [comment]
You should specify

-DLWS_WITH_LIBEV=1

not  "USE"
