### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#701]
How many types of callbacks does this library support in client implementation?
There are following necessary callbacks required to use in production.

onconnect
onreceive
onconnecterror
send
ondisconnect

Can you please provide me with example where I can refer to implement those APIs?

**Comment by lws-team** [comment]
The callbacks are listed in an enum

https://github.com/warmcat/libwebsockets/blob/master/lib/libwebsockets.h#L662

There are docs inline in the enum explaining most of them.

Assuming you're talking about a ws[s] client connection, all but send map well

your api|event
-|-
onconnect|`LWS_CALLBACK_CLIENT_ESTABLISHED`
onreceive|`LWS_CALLBACK_CLIENT_RECEIVE`
onconnecterror|Either `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` (note a disagnostic string with more info is passed with the callback) or if the connection attempt failed before any wsi created, then error from `lws_client_connect_via_info()`
ondisconnect|`LWS_CALLBACK_CLOSED`

Sending data doesn't work like your API wants, you will have to buffer it if that's how you must present it.  The ability of the peer (in this case, the server) to receive more data regulates the sending of it in lws.

You can call an api like `lws_callback_on_writable(wsi)` to request a callback when more can be sent.  When more can be sent, you will receive a `LWS_CALLBACK_CLIENT_WRITEABLE` on the wsi in question.  There - and only from there - you may send one ws fragment using lws_write().  If there is still more to send, you should call `lws_callback_on_writable(wsi)` again and send it when the next callback comes.

Each individual connection receives his WRITEABLE callback as soon as his specific pipe can accept more.  The rest of the time, aside from receive, he's idle.

**Comment by lws-team** [comment]
Oh... example code... ./test-server contains a bunch of examples.  The client example is here

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-client.c

It supports multiple client connections, rate-limited auto reconnect, and http client connections, as well as ssl.

**Comment by sacOO7** [comment]
Thanks for the reply , I will checkout examples. If there are any more queries I will let you know.
