### ISSUE TITLE
Enabling HTTP2 and using Firefox will result in a crash

### ISSUE THREAD

**Issue by avdbg** [warmcat/libwebsockets#704]
It will crash in [there](https://github.com/warmcat/libwebsockets/blob/v2.1-stable/lib/http2.c#L237)

The `wsi->u.http2.stream_wsi` is NULL.Test command is 
```
libwebsockets-test-server.exe --ssl --resource_path D:\Project\libwebsockets_build2\bin\share\libwebsockets-test-server
```
Firefox version is 50.0.2.

Microsoft Edge and IE works fine.Chrome and safari can not access, but will not cause the server to crash.

**Comment by lws-team** [comment]
Ok.  I'll study it later today.

Http/2 is kind of 'experimental' in lws.  I got it to the point it was able to serve pages and announced it a couple of years ago.  There were literally zero people interested in it at that time, and indeed up until now.  Considering the considerable amount of work the lack of interest was a big disappointment.

**Comment by INRIX-joel-winarske** [comment]
I would prefer built in http2, opposed to bolting on support via libnghttp2.

**Comment by lws-team** [comment]
@INRIX-joel-winarske  I can understand that... I would 'prefer' people sending me patches.  Otherwise it looks like this will be stuck at 85% complete for a while.

**Comment by lws-team** [comment]
I'm sorry this is incomplete atm.

Basically there is no http/2 support for websockets.  So spending time solving this seems pointless at the moment for "libwebsockets".
