### ISSUE TITLE
socket disconnect

### ISSUE THREAD

**Issue by kjnoh77** [warmcat/libwebsockets#705]
Dear lws-team

We faced some new problem during test.
We are using libwebsockets for server service.(2.1-stable)
The problem is that socket is diconnect as soon as we sent socket message to client.
next is libwebsockets's log except just 1 line. 1 line is our user code's log.
our user code receviced success write length(Len:371) return after call "lws_write".
But then, that socket looks like disconnected.
Could you give us some clue teaching us what happend in libwebsockets ?

01-01 14:06:53.694+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.694+0900 I/libwebsockets(P18151, T18156): service.c: lws_calllback_as_writeable(43) >
 lws_calllback_as_writeable: 0xb3f0dcf0 (user=0xb3f14760)
01-01 14:06:53.694+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156): extension.c: lws_issue_raw_ext_access(265) > written 375 bytes to client
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 I/OUR_USER_CODE(P18151, T18156): Server.cpp: callback_http(353) > Msg ID:3, Length:371, To:'163ab7dc-d17d-42bb-84e5-3c2d2b9c268'
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156): libwebsockets.c: _lws_rx_flow_control(1317) > _lws_rx_flow_control: no pending change
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 D/libwebsockets(P18151, T18156): service.c: lws_service_fd_tsi(948) > lws_se
rvice_fd_tsi: zero length read
01-01 14:06:53.695+0900 D/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156): service.c: lws_service_fd_tsi(1116) > Close
 and handled
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 D/libwebsockets(P18151, T18156): libwebsockets.c: lws_close_free_wsi(400) >
lws_close_free_wsi: shutting down connection: 0xb3f0dcf0 (sock 24, state 5)
01-01 14:06:53.695+0900 D/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156): libwebsockets.c: lws_close_free_wsi(403) >
closing: shutdown (state 5) ret 107
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156):
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156): libwebsockets.c: lws_set_timeout(119) > lws
_set_timeout: 0xb3f0dcf0: 20 secs
01-01 14:06:53.695+0900 I/libwebsockets(P18151, T18156):

**Comment by lws-team** [comment]
There's no evidence anything 'happened in libwebsockets'.

For example, the other end may have hung up on it.

You're the guy with the problem and the code, debug it... if there's some evidence of issue in lws, I'll study it.  Otherwise... your problem.

**Comment by kjnoh77** [comment]
Doing backtrace, I found that our issue is dependent on next commit of v2.0-stable.

Author: Andy Green <andy@warmcat.com>  2016-11-29 21:42:57
Committer: Andy Green <andy@warmcat.com>  2016-11-29 21:42:57
Parent: 65cefdf8792c83ca51b6aa2f998d7ad5a949f09e (client stash: update path variable to larger size)
Child:  a7487e95d8700c0821274670b035f19335d34a33 (Update CMakeLists.txt for BSD + libdl)
Branches: remotes/origin/v2.0-stable, v2.0-stable
Follows: v2.0.3
Precedes: 

    ws-server: restrict returned Sec-Websocket-Protocol to the chosen name only
    
    https://libwebsockets.org/pipermail/libwebsockets/2016-November/002948.html

Our user protocol is empty, so previous code(related with "WSI_TOKEN_PROTOCOL" check) do nothing in real, but now it affect something because "wsi->protocol->name" is showing "http-only".
I'm not saying libwebsocket is some wrong at all. Now, I'm strudying why it affect to our connection.

Thank you.

**Comment by kjnoh77** [comment]
If I fix as like next issue disappear even though I don't know well it's right solution.

if (wsi->protocol->name && wsi->protocol->name[0]) {
		if (strcmp(wsi->protocol->name, "http-only")) { // adding this condition
			LWS_CPYAPP(p, "\x0d\x0aSec-WebSocket-Protocol: ");
			p += lws_snprintf(p, 128, "%s", wsi->protocol->name);
		}
	}

**Comment by lws-team** [comment]
I am OK if it's something wrong with lws.... there have been plenty of things wrong with lws before and there will be after.

But there needs to be evidence like you found in your last-but-one post, then there is something for me to look at.  "What is wrong with my code" I can't do anything with.

That patch was a good fix, as far as it went... the stuff was definitely wrong before.

I'll check how it acts with empty protocol later, it was only checked with explicit protocol name.

**Comment by lws-team** [comment]
I updated the original patch to deal with this, on v2.0-stable, v2.1-stable and master.

It is only allowed to send the protocol header in the response if it received one in the upgrade request.

https://github.com/warmcat/libwebsockets/commit/4acf7a67b2470e3f28e59c46ced871ce2a5f29db

**Comment by kjnoh77** [comment]
I checked with it and it works well.
Thank you!
