### ISSUE TITLE
Generic session allows password change even with wrong current password

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#706]
Hi, I've been playing with [this demo](https://libwebsockets.org/lwsgs/index.html) and I managed to change the password even giving it the wrong current password.

**Steps**
1. Register, email confirmation, and log in.
2. Login with correct credentials.
3. Change password while giving it an incorrect current password.
4. Everything goes through, log out, and log in with the newly changed password.

Thanks

**Comment by lws-team** [comment]
Yeah... good find.  The check to see if it was doing the forgot password flow was broken, so it skipped checking it.

Now it will check it, and unceremoniously log you out if it fails.

Little fix pushed on v2.1-stable and master.
