### ISSUE TITLE
how to set cookie in the http response header when the websocket do handahake

### ISSUE THREAD

**Issue by hellochenchen** [warmcat/libwebsockets#707]
i've add dlws_with_generic_sessions=1 as a option to cmake command ,but i can't receive LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER the resson and have no way to add set-cookie to the response header.

**Comment by lws-team** [comment]
This is a bit confusing...

 - if you are using Generic Sessions, you should make sure you can reproduce the messageboard example first (same as runs at https://libwebsockets.org/lwsgs/ )

 - `LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER` only appears on connections that are in **client** mode.  You are presumably running a server, so you wouldn't expect it.

 - If you are using lwsgs, it handles adding login cookies to headers automatically.  Are you wanting to add some other cookie?

**Comment by hellochenchen** [comment]
- i am sorry to make u confused. in your example.i saw the request cookie.but, in my example i could not saw th cookie  which was build in "cmake .. -DLWS_WITH_GENERIC_SESSIONS=1 -fPIC -DLIB_SUFFIX=64 (also contains ssl and zlib library floders)". and than "make && make install ". it reminder me that build sucess. 
- as what u said, can i understand as "when i add -DLWS_WITH_GENERIC_SESSIONS=1 this option, the libwebsockets.so can automatically add the cookie headers.". in my example, i use libwebsockets.so as server mode. but it did not add. 

- how can i use libwebsockets.sp to add cookie automatically. add some options in cmake, or write some configure code?thanks for response!

**Comment by lws-team** [comment]
No Generic Sessions is a bigger thing than just adding cookies.

https://libwebsockets.org/lws-api-doc-master/html/md_README_8generic-sessions.html

It's a whole user credentials / authentication / sessions management thing that just happens to also use cookies.

If all you want to do is set a cookie, actually the test server shows you how to simply send cookies

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-http.c#L387

**Comment by hellochenchen** [comment]
Thank you for your response.Actually,we only want to set a cookie.But we can not trigger the callback reason lws_callback_http when the websocket handshake.Is it because we need a simple http request except handshake？Thanks.

**Comment by lws-team** [comment]
Please use the test server and see (eg, by tcpdump) if the cookie is coming.

If it is, study the differences between what the test server is doing and what your code is doing.
