### ISSUE TITLE
Problem changing password

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#710]
Hi,

I have trouble changing the password with **lwsgs-change**

I have included these fields in my **POST** request.

```
curpw
username:
change:Change
good:
bad:
admin:
reg-good:
reg-bad:
forgot-good:
forgot-bad:
forgot-post-good:
forgot-post-bad:
password:
password2:
```

After submitting the form, I got redirected to the URL of whatever I gave **bad** field.

I'm getting these in the terminal.

```
lwsws[30615]: 0x6f8ab0 new partial sent 1044 from 2243 total
lwsws[30615]: Accepted wsi 0x6f8510 to context 0x6795f0, tsi 0
lwsws[30615]: lws_server_socket_service: wsi 0x6f8510 read 353
lwsws[30615]: lws_spa_create: Created SPA 0x6ff770
lwsws[30615]: user/password no good admin
lwsws[30615]: lws_spa_destroy: destroy spa 0x6ff770
```

I was able to log in with the same user-password that I had given during **lwsgs-change**

**Comment by lws-team** [comment]
It says "...no good admin"... you cannot change the admin password from the net.  It is stored in the config files (to stop the possibility of getting locked out).

Assuming the messageboard sample works, that's likely a clue.

**Comment by d30jeff** [comment]
Ahh that makes sense.

Now that **admin** account is out of the picture, is possible to create a default **non-admin** user in the configuration file?

**Comment by lws-team** [comment]
No... but you can use sqlite commandline utility to poke arbitrary sql into the database / query the schema.  You should take that approach to, eg, mass register normal users.

**Comment by d30jeff** [comment]
I played with the DB and I got this schema, now I'm trying to INSERT into it.

```
CREATE TABLE users ( username varchar(32), creation_time integer, ip varchar(46), email varchar(100), pwhash varchar(42), pwsalt varchar(42), pwchange_time integer, token varchar(42), verified integer, token_time integer, last_forgot_validated integer, primary key (username));
```
Correct me if I'm wrong, but to generate `pwhash` all I have to do is get the output of 
`echo -n "<my-password-here>" | sha1sum`, correct?

But how do you generate the `pwsalt`? So far my clue is the `confounder` in the config file, I mean, how do you `squeeze` them together?

Thanks :smiley:

**Comment by lws-team** [comment]
There's no secret about how it is done... the secret is in the password and the confounder (the salt is stored in the db in plaintext).

https://github.com/warmcat/libwebsockets/blob/master/plugins/generic-sessions/utils.c#L386

Look at the sprintf.

The job of the salt is to make attacks on one hashed pw worthless on another hashed pw.  It forces the attacker to attack each password individually.

You might know that the SHA-1 of "mypassword" is 1234etc.  But it does you know good if everybody who has the password "mypassword" has a completely different hash because of the unique salt on each one.  And the confounder (while it remains secret) is not stored in the db and makes that even harder.

**Comment by lws-team** [comment]
Mmm you were actually asking how to generate the salt... it's a random number with no meaning.  rand() or so will do it.

It becomes part of the hashed plaintext, and must be stored in the db.  It has no other meaning than it's a random number (and you must use the same random number to create a hash to check against the stored hash) that should have a high chance of being different for each user.

**Comment by d30jeff** [comment]
I'm trying to insert **default** data to the sqlite3 db so that I could log in with the username and password that I previously inserted to the database.

So far it's not working :sob: 

I skipped some of the fields. 
Here's the value that I inserted to the `users` table.

**username** = deojeff
**creation_time** = *blank*
**ip** = *blank*
**email** = *blank*
**pw_hash** = a75acff76313682f83991f571778aadbec2828de
**pw_salt** = ni12i3mi912moqwmi9eqwemqwie9wqeok12 (copied from 'confounder' in conf.d/)
**pw_change_time** = *blank*
**token** = *blank*
**verified** = 1
**last_forgot_validated** = *blank*

Is there anything that's missing?

**Comment by lws-team** [comment]
> Is there anything that's missing?

Who knows, I don't know how you generated these fields.  However

1) The salt is a whole other thing, it is not related to the confounder.

2) The confounder must never directly be stored in the db!

3) You prepare the hash like

`echo -n $PASSWORD-$CONFOUNDER-$SALT | sha1sum | cut -d' ' -f1`

$PASSWORD is the plaintext password
$CONFOUNDER is the confounder string from the config file
$SALT is a unique-ish string you should also hash, like

SALT=\`dd if=/dev/urandom bs=8 count=1 >/dev/null 2>&1 | sha1sum | cut -d' ' -f1\`

**Comment by d30jeff** [comment]
> Who knows, I don't know how you generated these fields. 

Sorry. It's the database schema in `/var/www/sessions/lws.sessions.sqlite3` which I assumed, where the username and password hash are being stored in.

What I'm trying to accomplish is to register users by inserting their default credentials somewhere.

I tried querying most of the `*.sqlite3` stuff in `/var/www/sessions` but most of them are empty!

Where are the username and password hash being stored?

I'm so confused right now :confused: sorry.

**Comment by lws-team** [comment]
Look at the code

https://github.com/warmcat/libwebsockets/blob/master/plugins/generic-sessions/protocol_generic_sessions.c#L370

There is a table 'users' in the sqlite3 db.  The path to that db file is set in the per-vhost settings for lwsgs, "session-db".

You're on the right path.

**Comment by d30jeff** [comment]
Phew! Managed to get it to work.

Basically what I did is to create a form that mimics the registration fields, and fake an account confirmation.

```
<form action="lwsgs-login" method="post">
  <input type="text" name="admin" value="needadmin/admin-login.html">
  <input type="text" name="good" value="google.com">
  <input type="text" name="reg-good" value="post-register-ok.html">
  <input type="text" name="reg-bad" value="youtube.com">
  <input type="text" name="username" value="deojeff">
  <input type="text" name="password" value="mypassword">
  <input type="text" name="password2" value="mypassword">
  <input type="email" name="email" value="test@gmail.com">
  <input type="text" name="register" value="Register">
  <button type="submit">Register</button>
</form>
```

And in my login form, I change the value from ~~name="admin"~~ to **name="good"**

```
<input type="text" name="username" id="username" placeholder="Username" autofocus>
<input type="password" name="password" id="password" placeholder="Password">
<input type="hidden" name="good" value="/home">
<input type="hidden" name="bad" value="/login">
```

Thanks for your guidance. Cheers
