### ISSUE TITLE
lws_context_destroy does not free memory allocated by lws_create_vhost (OpenSSL 1.0.1m+)

### ISSUE THREAD

**Issue by daren-qterics** [warmcat/libwebsockets#711]
Valgrind reports the following memory leak when lws is linked with OpenSSL v1.0.1m or later:

> ==1522== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 21 of 34
> ==1522==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==1522==    by 0x5FAFC86: default_malloc_ex (mem.c:79)
> ==1522==    by 0x5FB035D: CRYPTO_malloc (mem.c:342)
> ==1522==    by 0x605247A: sk_new (stack.c:128)
> ==1522==    by 0x6052456: sk_new_null (stack.c:120)
> ==1522==    by 0x5FB28D2: CRYPTO_set_ex_data (ex_data.c:614)
> ==1522==    by 0x5D2A4CF: SSL_CTX_set_ex_data (ssl_lib.c:3046)
> ==1522==    by 0x4E5173C: lws_context_init_server_ssl (ssl-server.c:331)
> ==1522==    by 0x4E4973E: lws_create_vhost (context.c:506)
> ==1522==    by 0x4E4A1BB: lws_create_context (context.c:765)

If one examines the call stack, they will see the following sequence of function calls:
```
lws_context_destroy(context);
    lws_ssl_context_destroy(context);
        CRYPTO_cleanup_all_ex_data();
```
The `CRYPTO_cleanup_all_ex_data()` code calls a function that clears the OpenSSL `ex_data` pointer.
```
static void int_cleanup(void)
{
    EX_DATA_CHECK(return;)
        lh_EX_CLASS_ITEM_doall(ex_data, def_cleanup_cb);
    lh_EX_CLASS_ITEM_free(ex_data);
    ex_data = NULL;
    impl = NULL;
}
```
Later the `lws_context_destroy()` code attempts to free vhost->ssl_ctx and vhost->ssl_client_ctx with the following call stack:
```
    lws_ssl_SSL_CTX_destroy(vh);
        SSL_CTX_free(vhost->ssl_ctx); / SSL_CTX_free(vhost->ssl_client_ctx);
            static void int_free_ex_data(int class_index, void *obj, CRYPTO_EX_DATA *ad)
```
The `int_free_ex_data()` function does not free the memory because a change was made to exit the function upon entry if `ex_data` is NULL.
```
static void int_free_ex_data(int class_index, void *obj, CRYPTO_EX_DATA *ad)
{
    int mx, i;
    EX_CLASS_ITEM *item;
    void *ptr;
    CRYPTO_EX_DATA_FUNCS **storage = NULL;
    if (ex_data == NULL)
        return;
    ...
```
This change was made between v1.0.1l and v1.0.1m of OpenSSL.  Details about the change can be found [here](https://gitlab.beget.ru/LTD-Beget/openssl/commit/ba25221226f0c9b033d8ff8a2a2bde8b359c6426).

I fixed the memory leak on my system by changing the order of operations in `lws_context_destroy` so that memory associated with the vhost is freed before memory associated with the context is free:

```
--- libwebsockets-2.1-stable.orig/lib/context.c 2016-12-08 09:40:50.344294204 -0600
+++ libwebsockets-2.1-stable/lib/context.c  2016-12-08 09:39:44.132294486 -0600
@@ -895,7 +895,6 @@
            lws_free(pt->http_header_data);
    }
    lws_plat_context_early_destroy(context);
-   lws_ssl_context_destroy(context);

    if (context->pt[0].fds)
        lws_free_set_NULL(context->pt[0].fds);
@@ -939,6 +938,8 @@
        vh = vh1;
    }

+   lws_ssl_context_destroy(context);
+
    lws_plat_context_late_destroy(context);

    lws_free(context);
```

The patch is in the attached file for your consideration.  [libwebsockets-context.txt](https://github.com/warmcat/libwebsockets/files/642435/libwebsockets-context.txt)

**Comment by lws-team** [comment]
Thanks, it's pushed on v2.0-stable, v2.1-stable and master.
