### ISSUE TITLE
How to deal with the warning "Targets may link only to libraries.  CMake is dropping the item."

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#713]
My steps:
1. I run：`cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_LIBRARIES=/usr/bin/openssl  .. `
     it told me to specify the zlib path
2. Then I run :`cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_LIBRARIES=/usr/bin/openssl -DZLIB_LIBRARY=/data/progam/zlib/lib -DZLIB_INCLUDE_DIR=/data/progam/zlib/include ..`
  Then the warning appears:
```
WARNING: Target "websockets_shared" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server-pthreads" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fraggle" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server-extpoll" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-echo" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-ping" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-client" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-server" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test-fuzxy" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "websockets_shared" requests linking to directory "/data/progam/zlib/lib".  Targets may link only to libraries.  CMake is dropping the item.
```
```

And I find once the warning appears，make will fail:
```
[ 61%] Linking C executable bin/libwebsockets-test-server-pthreads
lib/libwebsockets.a(extension-permessage-deflate.c.o): In function `lws_extension_callback_pm_deflate':
extension-permessage-deflate.c:(.text+0x354): undefined reference to `deflateEnd'
extension-permessage-deflate.c:(.text+0x411): undefined reference to `deflateInit2_'
extension-permessage-deflate.c:(.text+0x48a): undefined reference to `deflate'
extension-permessage-deflate.c:(.text+0x696): undefined reference to `inflate'
extension-permessage-deflate.c:(.text+0x768): undefined reference to `inflateInit2_'
extension-permessage-deflate.c:(.text+0x793): undefined reference to `deflateEnd'
extension-permessage-deflate.c:(.text+0x7dc): undefined reference to `inflateEnd'
extension-permessage-deflate.c:(.text+0x804): undefined reference to `inflate'
extension-permessage-deflate.c:(.text+0x8ab): undefined reference to `inflateEnd'
collect2: ld returned 1 exit status
make[2]: *** [bin/libwebsockets-test-server-pthreads] Error 1
make[1]: *** [CMakeFiles/test-server-pthreads.dir/all] Error 2
make: *** [all] Error 2
```

Is there something wrong with the zlib path I set?

**Comment by lws-team** [comment]
What platform is this?

It sounds like it wants you to tell it where libz.so or whatever is, not a directory.

**Comment by HiAlisaYang** [comment]
Yes,it is. I add `libz.so` in the path ,and it works.
`cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_LIBRARIES=/usr/bin/openssl -DZLIB_LIBRARY=/data/progam/zlib/lib/libz.so -DZLIB_INCLUDE_DIR=/data/progam/zlib/include ..`

Thank you so much.
