### ISSUE TITLE
How to specify ip for a websocket context?

### ISSUE THREAD

**Issue by HiAlisaYang** [warmcat/libwebsockets#717]
We can specify iface and port for a websocket context. But if a network adapter bundled with more then one IP address.And I only want one IP to bind the websocket port. How can I specify an IP? Many thanks.

**Comment by lws-team** [comment]
You can just give the IP in .iface.

Eg

test|netstat -pltn
-|-
libwebsockets-test-server -i 127.0.0.1|tcp        0      0 127.0.0.1:7681          0.0.0.0:*               LISTEN      21495/libwebsockets
libwebsockets-test-server -i 192.168.2.229|tcp        0      0 192.168.2.229:7681      0.0.0.0:*               LISTEN      21720/libwebsockets

**Comment by HiAlisaYang** [comment]
Thanks so much. And if I want to set an IPv6 address,I just need to set LWS_IPV6=1?Is it?

**Comment by lws-team** [comment]
ipv6 also able to do that needed an extra patch, it's pushed on v2.0-stable, v2.1-stable and master.

**Comment by HiAlisaYang** [comment]
OK,Thanks so much.
