### ISSUE TITLE
Tip: Upgrading libwebsocket client from v1.7 to v2.0

### ISSUE THREAD

**Issue by dulguunbatmunkh** [warmcat/libwebsockets#718]
Hello,

We have recently upgraded our libwebsocket client from v1.7 to v2.0 and our code stopped working correctly when we have tried to use SSL. We added `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT` as it was mentioned in the [changelog](https://github.com/warmcat/libwebsockets/blob/153f5da531e285b05a53c1523f558cabca03ddd4/changelog#L56-L58). 

Error log:
``` cpp
ssl-client.c: lws_ssl_client_connect2(269) > SSL connect error 336134278: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

So finally we have found the solution for our problem. It was a silly mistake and think will be helpful for others who may make the same mistake.
``` git
-    i.host = foobar.com:443;  // this works on v1.7 but not since v2.0
+    i.host = foobar.com;  // this works on v2.0
```

It is fixed and wrote this in case someone make sames mistake. 

Thanks,
Dulguun

**Comment by lws-team** [comment]
I appreciate the thought to leave it in google.

Actually the library should probably snip the port part.  The HTTP 1.1 definition for Host: is this

```
Host = "Host" ":" host [ ":" port ] ; Section 3.2.2
```

ie, it's OK to put the port in it.  The `info->host` field is intended to supply what to put in the `Host:` header.

So if you had a server on a nonstandard port, you would want to give it there.  And then you would meet this cert host verification issue.

I pushed a patch on v2.0-stable, v2.1-stable and master  that has it snip any ':' in the hostname, and anything past that, for the purposes of comparing with the certificate.  So it should work either way from now on.

**Comment by lminiero** [comment]
Sorry for adding my question here, but I thought it made sense to re-use this issue rather than opening a new one. Is there any programmatic way to check whether or not the flag is available, e.g, library version checking? My application still allows older versions of libwebsockets to be used via ifdefs (a define I trigger via configure), so being able to do the same for `LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT` without breaking support for older versions of libwebsockets would be cool.

**Comment by lws-team** [comment]
Hm... it's an enum.

What you could do is just set options |= (1 << 12) with a comment... earlier versions aren't going to care it's set and I doubt this will change quickly.

I take the general point about versioning detection though.... CMakeLists.txt knows it but not exported to the C stuff atm.

**Comment by lws-team** [comment]
Oh... spoke too soon... these should turn up in lws_config.h included by libwebsockets.h

```
#define LWS_LIBRARY_VERSION_MAJOR ${LWS_LIBRARY_VERSION_MAJOR}
#define LWS_LIBRARY_VERSION_MINOR ${LWS_LIBRARY_VERSION_MINOR}
#define LWS_LIBRARY_VERSION_PATCH ${LWS_LIBRARY_VERSION_PATCH}
```

**Comment by lminiero** [comment]
Thanks for the quick answer! It looks like those defs have been around for a while so they'll definitely do the trick :+1:
