### ISSUE TITLE
[generic-session] directory permission breaks on openwrt, works on laptop

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#721]
Hi, 

I'm using libwebsocket's generic session plugin in openwrt.

It breaks (directories that are not supposed to be accessible without logging in are accessible) on openwrt, but works fine on my laptop.

Could it be that it's missing some program (apache, etc)?

Thanks

**Comment by lws-team** [comment]
No there's nothing needed external to lws + the related plugins.

Is your lwsws or other configuration identical?  Particularly the per-mount config?

Plugin is loaded?

Check logs looking for trouble?

**Comment by d30jeff** [comment]
Oops! My apologies.

I totally forgot to update the old libwebsockets code in openwrt to the new one with the fix (#691).

Thanks
