### ISSUE TITLE
Unable to get libwebsockets to work with TLS using libwebsockets-test-server

### ISSUE THREAD

**Issue by dschere** [warmcat/libwebsockets#723]
Hello,

   I was originally having problems getting MQTT mosquitto to work using websocketts, after troubleshooting I narrowed it down to 

 line 889, server.c , libwebsockets 1-7.1,  ah->rxlen = -1 that triggered a  LWS_SSL_CAPABLE_ERROR

So I decided to test to make sure that the libwebsockets-test-server works. I ran

libwebsockets-test-server with no arguments and it works flawlessly

I rerun using the --ssl flag and I get a slew of error:

lwsts[20713]: lws_protocol_init
lwsts[20713]: Accepted wsi 0x218ca60 to context 0x2145010, tsi 0
lwsts[20713]: Accepted wsi 0x218adc0 to context 0x2145010, tsi 0
lwsts[20713]: SSL_accept failed skt 8: error:00000001:lib(0):func(0):reason(1)
lwsts[20713]: *** error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
lwsts[20713]: SSL_accept failed skt 8: error:00000001:lib(0):func(0):reason(1)
lwsts[20713]: *** error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
^Clwsts[20713]: lws_context_destroy: ctx 0x2145010
lwsts[20713]: lws_header_table_detach: wsi 0x218adc0: ah held 5s, ah.rxpos 0, ah.rxlen 0, mode/state 6 4,wsi->more_rx_waiting 0

I tried using my certs with no effect.

What is needed to get libwebsockets-test-server to work? Hopefully this will allow me the solve my issues with the mosquitto MQTT message broker.

**Comment by lws-team** [comment]
Here is what I just did here, using master

1) build and install lws

2) libwebsockets-test-server --ssl

3) Navigate firefox to `https://localhost:7681`

4) Add the exception for the "selfsigned certificate"

Everything is fine.

Same procedure is fine if I do it in v1.7-stable.

Are you sure you are not running the test server in --ssl, but still using `http://` URL in the browser?

**Comment by dschere** [comment]
yes that was it https, I wish all the bugs they were all that simple.

thanks
