### ISSUE TITLE
Chunked Upload

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#724]
@lws-team 
actually when i run this  curl cmd
curl -v -F file=@/home/tej/file.wav  "http://localhost:7681/formtest" . file is succesfully uploaded. and gave the response.

but with curl -v -F audio=@/home/tej/file.wav --header "Transfer-Encoding: chunked"  --limit-rate 6000 "http://localhost:7681/formtest" ..
 Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7681 (#0)
> POST /formtest HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:7681
> Accept: */*
> Transfer-Encoding: chunked
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------3a034cb821920a27

 seems lwsws server receiving file, but not giving response....I want to send my file as chunked.. 
There is any test-server for handle PUT method as like post_demo.c?

**Comment by lws-team** [comment]
No... literally chunked transfer-encoding for file upload is not supported as it stands.

Nobody has asked for it and I don't need it personally; generic browser file upload is never chunked.

I can see it's useful if you don't know the length of a generated file when you start the upload.  But it's a kind of unusual situation.

Patches welcome tho.
