### ISSUE TITLE
abnormal close when using a proxy

### ISSUE THREAD

**Issue by jonowoodward1986** [warmcat/libwebsockets#728]
Hello,

I have been using a libwebsocket v2.0.0 server running on a Linux machine and connected to it using javascript websockets via a nginx proxy very successfully from 4 pc's however it fails on another another pc.

The error I get is the following:

`LWS_CLOSE_STATUS_ABNORMAL_CLOSE				= 1006,
	/**< 1006 is a reserved value and MUST NOT be set as a status code in a
      Close control frame by an endpoint.  It is designated for use in
      applications expecting a status code to indicate that the
      connection was closed abnormally, e.g., without sending or
      receiving a Close control frame. */`

The server side will write fail and call:

`			/**< when the websocket session ends */
			case LWS_CALLBACK_CLOSED:	`

If I go directly to the url:port and not the proxy it works fine....

Any ideas? Could this cause fd's to be left open because it eventually runs out?

**Comment by lws-team** [comment]
If I understood it, it's not your code or client, but the proxy that seems to be enforcing a policy it wants to see a close frame before the connection closes?  If it doesn't get one it adds its own, when 1006 shouldn't go out on the wire?

If so I'm not sure we can say the server 'fails', it just follows the connection close action from the proxy.

Doesn't that mean the client simply hung up and the proxy is just passing that on, after adding his own 1006 close code?

**Comment by jonowoodward1986** [comment]
Am not entirely sure myself.

What will happen is the client will connect to the server and successfully establish a connection.
My client subscribes to events from my server and upon the server writing an event lws_write returns -1 and the client side is closed.

The strange thing is this only happens on a couple of PC's and not all of them which is very inconstant.

Another problem I have not sure if it is related is this:
`[2016/12/22 17:18:22:1571] ERR: ERROR on accept: Too many open files
[2016/12/22 17:18:22:1571] ERR: ERROR on accept: Too many open files
[2016/12/22 17:18:22:1571] ERR: ERROR on accept: Too many open files
[2016/12/22 17:18:22:1571] ERR: ERROR on accept: Too many open files`

I think if it is abnormally closed the file descriptor may still be in use?

**Comment by lws-team** [comment]
File / socket descriptors are a processwide resource, anything can leak them.  With Linux you can do `sudo ls -l /proc/\<pid\>/fds` and see what path each fd is open on.

I wouldn't read too much into 'abnormal', it just means the proxy saw a tcp close before a ws close frame.  That's actually legitimate with ws, it depends on the application if it wants to feelthat reflects something abnormal.

I think to understand it you have to turn off https and tcpdump / wireshark both sides of the proxy as it does this behaviour on a connection.

**Comment by jonowoodward1986** [comment]
The file descriptor problem was me using epol timers every time a client subscribed to a timed event and not closing them if the client was terminated.

I will try tcpdump next week either side of the proxy.

Thanks for your help! Merry Christmas and thank you for libwebsockets :)

**Comment by lws-team** [comment]
There's nothing for me to do here, so closing.  If you see some problem with lws feel free to continue posting here or open a new issue.
