### ISSUE TITLE
Link error on Windows

### ISSUE THREAD

**Issue by twoask** [warmcat/libwebsockets#731]
I've been using lws version v1.5-chrome47-firefox 41 until now (for both Linux and Windows). Recently I've hit a serious bug in Windows (for which I suspected it has been fixed in https://github.com/warmcat/libwebsockets/commit/6ff571f854a0181f041db687cd87c546cd4752f1) and decided to upgrade lws to version v2.1.0, in the hope to get the serious bug above fixed.

After making code changes to use the new API in the version 2.1.0, I've got an error as follows:

```
windows\third_party\libwebsockets\lib\libwebsockets.h(3641): warning C4273: '_snprintf' : inconsistent dll linkage [windows\foo\foo.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(346) : see previous definition of '_snprintf'
...
...
(Link target) -> 
  MSVCRT.lib(MSVCR120.dll) : error LNK2005: _snprintf already defined in websockets_static.lib(libwebsockets.obj)
```

I am a bit surprised to see this error, because I found no places in lws that defines _snprintf except for a "potential" macro:

https://github.com/warmcat/libwebsockets/blob/f3ad9540fa1e53d703a6839cc80ceff511648fc0/lib/libwebsockets.h#L152

I am using VS 12.0 (2013), C++ compiler version 18.00.x to compile the code and the code above says "#if !defined(__MINGW32__) && (!defined(_MSC_VER) || _MSC_VER < 1900) /* Visual Studio 2015 already defines this in <stdio.h> */" but I am not sure why it has to be < 1900.

Note that the previous lws v1.5 compiled perfectly fine. Could you please advice where the issue could possibly be?

**Comment by lws-team** [comment]
The sanity check for Windows build is appveyor... this is able to build and link without problems.

Looking at the error, it seems it basically complains "_snprintf already defined" in lws static lib.... I can guess the problem is this

```
#ifdef LWS_HAVE__SNPRINTF
#define lws_snprintf _snprintf
#endif
```

in private-libwebsockets.h

Please try remove this and recook lws and see if it changes anything.

**Comment by twoask** [comment]
Turns out that I needed to remove (or comment out) both places:

```
#if !defined(__MINGW32__) && (!defined(_MSC_VER) || _MSC_VER < 1900) /* Visual Studio 2015 already defines this in <stdio.h> */
#define lws_snprintf _snprintf
#endif
```

in libwebsockets.h, and

```
#ifdef LWS_HAVE__SNPRINTF
#define lws_snprintf _snprintf
#endif
```

in private-libwebsockets.h to make it work. Do you know which MSVC version is being used for sanity check in appveyor?

**Comment by lws-team** [comment]
OK, I'll try it and see if apveyor remains happy.

I don't know the msvc version, but the build of current head is here

https://ci.appveyor.com/project/lws-team/libwebsockets/build/1.0.1275/job/fbhxge652as9wqo6

**Comment by twoask** [comment]
It's using a newer version than mine:

```
cmake -DCMAKE_BUILD_TYPE=Release %CMAKE_ARGS% ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
```

And since the version is 1900, the check `_MSC_VER < 1900` will fail therefore it's as good as removing it.

**Comment by lws-team** [comment]
Well appveyor is just as happy.  I guess it's due to build static or not.

Thanks for reporting and helping fix it.
