### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH  The client and server don't support a common SSL protocol version or cipher suite.

### ISSUE THREAD

**Issue by hellochenwang** [warmcat/libwebsockets#732]
On the chrome side:
![image](https://cloud.githubusercontent.com/assets/16633061/21561176/ea257f88-ce1d-11e6-8bbb-29c9e05d106f.png)

On the server side:

stovetop-2:bin nw$ ./libwebsockets-test-server --ssl
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: libwebsockets test server - license LGPL2.1+SLE
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: (C) Copyright 2010-2016 Andy Green <andy@warmcat.com>
Using resource path "/usr/local/share/libwebsockets-test-server"
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: Initial logging level 7
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: Libwebsockets version: 2.1.0 nw@stovetop-2.local-v2.0.0-216-g714f66f
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: IPV6 not compiled in
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: libev support not compiled in
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: libuv support not compiled in
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  Threads: 1 each 256 fds
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  mem: platform fd map:  2048 bytes
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  Compiled with OpenSSL support
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: Creating Vhost 'default' port 7681, 5 protocols, IPv6 off
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  SSL ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:!SHA1:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!AES128-GCM-SHA25
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  Using SSL mode
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  SSL ECDH curve 'prime256v1'
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  Listening on port 7681
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  mem: per-conn:          568 bytes + protocol rx buf
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>:  canonical_hostname = stovetop-2.local
Dec 29 23:22:46 stovetop-2.local lwsts[1336] <Notice>: lws_protocol_init
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Notice>: Accepted wsi 0x7fe393e00390 to context 0x7fe394800400, tsi 0
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SNI: Unknown ServerName: localhost
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SSL_accept failed socket 7: SSL_ERROR_SSL
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: *** error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: lws_adopt_socket_vhost: fail ssl negotiation
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SNI: Unknown ServerName: localhost
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SSL_accept failed socket 7: SSL_ERROR_SSL
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: *** error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Notice>: Accepted wsi 0x7fe393e00f30 to context 0x7fe394800400, tsi 0
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SNI: Unknown ServerName: localhost
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SSL_accept failed socket 7: SSL_ERROR_SSL
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: *** error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: lws_adopt_socket_vhost: fail ssl negotiation
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SNI: Unknown ServerName: localhost
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: SSL_accept failed socket 7: SSL_ERROR_SSL
Dec 29 23:23:00 stovetop-2.local lwsts[1336] <Error>: *** error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher

It's strange that on an ubuntu server, it worked fine, but on OSX, it gives this error.

**Comment by lws-team** [comment]
There are a few things in the context creation info struct that affect what openssl will accept to do.

Eg

```
const char *ssl_cipher_list;
	/**< VHOST: List of valid ciphers to use (eg,
	 * "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL"
	 * or you can leave it as NULL to get "DEFAULT" */
```

But also `ssl_options_set` and `ssl_options_clear`.

test-server-v2.0.c sets it like this

```
	info.ssl_cipher_list = "ECDHE-ECDSA-AES256-GCM-SHA384:"
			       "ECDHE-RSA-AES256-GCM-SHA384:"
			       "DHE-RSA-AES256-GCM-SHA384:"
			       "ECDHE-RSA-AES256-SHA384:"
			       "HIGH:!aNULL:!eNULL:!EXPORT:"
			       "!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:"
			       "!SHA1:!DHE-RSA-AES128-GCM-SHA256:"
			       "!DHE-RSA-AES128-SHA256:"
			       "!AES128-GCM-SHA256:"
			       "!AES128-SHA256:"
			       "!DHE-RSA-AES256-SHA256:"
			       "!AES256-GCM-SHA384:"
"!A'ES256-SHA256";
```

This is demanding a good cipher and key exvhange that provides pfs.

If osx openssl is too crappy to come up with that, there'll be no usable cipher when this list is combined with an openssl that doesn't even have the goodies in it.

**Comment by hellochenwang** [comment]
Problem fixed by updating OpenSSL:

brew install openssl

/usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2j  26 Sep 2016

cmake .. -DOPENSSL_EXECUTABLE=/usr/local/opt/openssl/bin/openssl -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include/ -DLWS_OPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib 

libwebsockets-test-server --ssl
