### ISSUE TITLE
Run-time check failure #3 with LWS_WITHOUT_EXTENSIONS on?

### ISSUE THREAD

**Issue by vroad** [warmcat/libwebsockets#733]
I tried some piece of code from test-client example and ran into this error:

`"Run-Time Check Failure #3 - The variable 'eff_buf' is being used without being initialized."`

Then I downloaded zlib and tried disabling `LWS_WITHOUT_EXTENSIONS` and the error seems to have gone. (I've just enabled this to try libwebsockets without installing zlib.)
Is this a bug, or am I using this library in a wrong way?
Looks like this line is assuming that `lws_ext_cb_active` always writes something to `eff_buff` but it actually does nothing with `LWS_WITHOUT_EXTENSIONS`.

https://github.com/warmcat/libwebsockets/blob/dd0dfaecb7f772c66352daa2216933b326a28e26/lib/service.c#L1016

**Comment by lws-team** [comment]
Nobody knows, or cares, what happemed with that 'piece of code' after you meddled with it.

Does the unchanged  test-client example itself give that error with permessage-deflate?

**Comment by lws-team** [comment]
Well if the test client itself blows chunks, let me know.  Valgrind says not, on Linux anyway.
