### ISSUE TITLE
issue with client connection with lws server

### ISSUE THREAD

**Issue by tejendrasingh** [warmcat/libwebsockets#734]
Sir,
lws_protocols protocol[]{
http-protocol,
ws-protocol
}
when i declare ws protocol on second position then my c++ client is connecting to lws server but client of different language is not connecting like python. 
lws_protocols protocol[]{
ws-protocol,
http-protocol
}
now when i declare ws first then my both python and c++ client connecting but now http client is not connecting..
please suggest some solution for that

**Comment by lws-team** [comment]
...

This isn't anything to do with python or C++ if I understand it.  But your question is kind of abstract.

Lws requires the first way as shown in all the example code.

My guess is the python client does not send the ws subprotocol name.  Then it defaults also to mapping to protocols[0].

You can mark another protocol as being the default one... it's done using per-vhost options as shown here

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L128

Or you can make the python code send your subprotocol name.

But this is a guess.  You should turn up logging in lws and confirm how the connection attempts actually differ.

**Comment by tejendrasingh** [comment]
Thanks, after check log.. yes it match to default protocol[0]..
One more question is when i run test-server.c with tag -D for daemonize..  nothing is happeing.. i am not sure.. i think my server will be run in backgroud with -D???

**Comment by lws-team** [comment]
You also need `-DLWS_WITHOUT_DAEMONIZE=0` on cmake.

But actually this is kind of deprecated.  Systemd knows how to start daemons and put them in the background without forks.  And lwsws in master does his own explicit fork now.

**Comment by lws-team** [comment]
Just about the memory corruption, afaik you have no reason to think you can safely use 5  bytes behind *in.  That's not safe to do.

About your question no idea I'll read it in the morning again and see if it makes more sense.

**Comment by tejendrasingh** [comment]
i am not adding 5 byte "0\r\n\r\n"....it is a terminating chunk
https://en.wikipedia.org/wiki/Chunked_transfer_encoding
Format[edit]
If a Transfer-Encoding field with a value of "chunked" is specified in an HTTP message (either a request sent by a client or the response from the server), the body of the message consists of an unspecified number of chunks, a terminating chunk, trailer, and a final CRLF sequence (i.e. carriage return followed by line feed).
The terminating chunk is a regular chunk, with the exception that its length is zero

**Comment by lws-team** [comment]
Yeah... lws does implement chunked transfer-encoding for other cases like client http and cgi; I know how it works.

But your code does not check len >=5, before doing effectively `in[len - 5]`.  If len was zero, this is `in[-5]`.

Also there is no guarantee at all the last 5 bytes arrive in ome packet / callback.  That is why lws uses bytewise state machines for everything like this.

**Comment by tejendrasingh** [comment]
I am not confirm.. but i think
because of info.pt_serve_buf_siz=4096 the last 5 byte are added in buffer and then that buffer is send to callback function.
some times callback_http function receive 5 byte independently or sometimes it is added to previous chunk  because of 
info.pt_serve_buf_size > receiving chunk

that's why i am checking like this 
if(str[len-5] == '0' && str[len-4] == '\r' && str[len-3] == '\n' && str[len-2] == '\r' && str[len-1] == '\n') {
    callback_http(wsi, LWS_CALLBACK_HTTP_BODY_COMPLETION , user, NULL, 0);
}

log on lwsws server...
But I think lws server it unable to identify the last chunk
log when --header "Transfer-Encoding: chunked"
lwsws[13859]: lws_server_socket_service: wsi 0x1b2f5a0 read 2945
lwsws[13859]: file_upload_cb: write 1023 says 1023
lwsws[13859]: file_upload_cb: write 1023 says 1023
lwsws[13859]: file_upload_cb: write 858 says 858
lwsws[13859]: wsi 0x1b2f5a0: TIMEDOUT WAITING on 10 (did hdr 1, ah 0x1b0da60, wl 0, pfd events 1)
lwsws[13859]: 127.0.0.1 - - [04/Jan/2017:20:19:38 +0530] "POST /formtest http/1.1" 0 0 curl/7.35.0
lwsws[13859]: lws_header_table_detach: wsi 0x1b2f5a0: ah held 22s, ah.rxpos 223, ah.rxlen 223, mode/state 1 4,wsi->more_rx_waiting 0

log without chunk
lwsws[13867]: lws_server_socket_service: wsi 0xceb5a0 read 2926
lwsws[13867]: file_upload_cb: write 1023 says 1023
lwsws[13867]: file_upload_cb: write 1023 says 1023
lwsws[13867]: file_upload_cb: write 844 says 844
lwsws[13867]: 127.0.0.1 - - [04/Jan/2017:20:29:57 +0530] "POST /formtest http/1.1" 200 626 curl/7.35.0
lwsws[13867]: lws_spa_destroy: destroy spa 0xcebb30

**Comment by lws-team** [comment]
You're not attending to what I wrote.  Your code is broken.

 - last block is 858 above.  Nothing stops it being 1 byte.

 - your code acts like it's guaranteed to see the chunk terminator sequence in one block contiguously.  It isn't.

 - your code doesn't check len >= 5 before subtracting 5 from it and using that to index an array.  But that's the least of your problems since the whole approach is broken.

Here is what a properly-written bytewise state machine for parsing chunked transfer-encoding looks like

https://github.com/warmcat/libwebsockets/blob/b3c2427cfd7f86a20856c0a07f3a7f85172fbddf/lib/service.c#L558

He doesn't care how the chunked stream is received or where the blocks begin and end, he will give the same result.
