### ISSUE TITLE
unable to launch websocket server on Google Compute Engine

### ISSUE THREAD

**Issue by chetanbnaik** [warmcat/libwebsockets#740]
I am using libwebsockets as a part of janus-gateway. The installation works properly on my laptop, however when I run janus-gateway on Compute Engine, I get the following error:

```
[2017/00/05 20:52:09:0090] NOTICE: Initial logging level 7
[2017/00/05 20:52:09:0091] NOTICE: Libwebsockets version: 2.0.0 chetan@instance-1-v2.0.0
[2017/00/05 20:52:09:0091] NOTICE: IPV6 not compiled in
[2017/00/05 20:52:09:0091] NOTICE: libev support not compiled in
[2017/00/05 20:52:09:0091] NOTICE: libuv support not compiled in
[2017/00/05 20:52:09:0092] NOTICE:  Threads: 1 each 65536 fds
[Thu Jan  5 20:52:09 2017] Sessions watchdog started
[Thu Jan  5 20:52:09 2017] Filesource (live) thread starting...
[Thu Jan  5 20:52:09 2017] [file-live-sample] Opening file source /usr/local/share/janus/streams/radio.alaw...
[Thu Jan  5 20:52:09 2017] [file-live-sample] Streaming audio file: /usr/local/share/janus/streams/radio.alaw
[Thu Jan  5 20:52:09 2017] Streaming watchdog started
[Thu Jan  5 20:52:09 2017] Joining Streaming handler thread
[Thu Jan  5 20:52:09 2017] Starting streaming relay thread
[Thu Jan  5 20:52:09 2017] VideoCall watchdog started
[Thu Jan  5 20:52:09 2017] Joining VideoCall handler thread
[2017/00/05 20:52:09:0105] NOTICE:  mem: platform fd map: 524288 bytes
[2017/00/05 20:52:09:0105] NOTICE:  Compiled with OpenSSL support
**_[2017/00/05 20:52:09:0105] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/00/05 20:52:09:0106] NOTICE: Creating Vhost 'default' port 8188, 2 protocols
[2017/00/05 20:52:09:0107] ERR: ERROR on binding fd 16 to port 8188 (-1 99)
[2017/00/05 20:52:09:0107] ERR: Failed to create default vhost_**
[Thu Jan  5 20:52:09 2017] [FATAL] [transports/janus_websockets.c:janus_websockets_init:473] Error initializing libwebsockets...
```

Please help. I am stuck badly just before I am trying to make my website live :(

**Comment by lws-team** [comment]
Have you told it to bind to a specific interface or IP (equivalent to -ieth0 or -i192.168.0.1 in test server)?

Or maybe the Janus default config sets it and that interface doesn't exist on that box?

Cos that's what the error suggests.

**Comment by chetanbnaik** [comment]
I am setting it to bind to the external (public) IP of the compute engine instance. 

Should I not specify this and let it be the default one??

**Comment by lws-team** [comment]
Why are you asking me ^^

Your kernel refuses to do what you asked, so presumably there is something wrong with what you asked.

As a sanity check you can try `libwebsockets-test-server` that should have been built with lws... try the -i parameter and see how it acts.  -ieth0 or -i192.168.0.1 or whatever should bind correctly if the names are appropriate.  You can check with netstat -ltn what it actually bound to.

This doesn't look like an lws issue tho, the error is from your kernel.

**Comment by chetanbnaik** [comment]
yes, i figured out the problem. it wasn't issue with LWS. thanks!

**Comment by takaaptech** [comment]
@chetanbnaik How to resolve that problem? I have this error too!
It would be great if you can share how to pass this error

**Comment by Gnomey123** [comment]
> @chetanbnaik How to resolve that problem? I have this error too!
> It would be great if you can share how to pass this error

Yes, I am also having this problem

**Comment by lws-team** [comment]
It's literally the same problem, like this?

> ERROR on binding fd 16 to port 8188 (-1 99)

Errno 99 is EADDRNOTAVAIL... is something else already bound to that port (check with `sudo netstat -tln`)?  Selinux?  Instead of listening on 0.0.0.0 (all interfaces) restrict the network interface you listen on?

Like the OP cryptically says, I think we find it's not caused by lws but by the environment it's running in.
