### ISSUE TITLE
Libssl versions are hardcoded

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#743]
Actually this is not a issue, I just want you to change the hardcoded versions of libssl. I was trying to compile server.c code using command gcc server.c -lpthread -lwebsockets , and it gave me following error.

``
/usr/bin/ld: warning: libssl.so.0.9.8, needed by //usr/local/lib/libwebsockets.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.0.9.8, needed by //usr/local/lib/libwebsockets.so, not found (try using -rpath or -rpath-link)
``
My latest version of libssl-dev contained versions to be libssl.so.1.0.0 and libcrypto.so.1.0.0, so I needed to create symlinks of those versions in order to make library available. I think it is possible to remove hardcoded versions.

**Comment by lws-team** [comment]
You need to rebuild stuff that was previously linked against changed dependent libraries with different sonames.

This is true for the whole of Linux, not just for lws.
