### ISSUE TITLE
libwebsockets.org

### ISSUE THREAD

**Issue by anporumb** [warmcat/libwebsockets#746]
https://libwebsockets.org/ looks all funny. 

SCREENSHOT OR IT DID NOT HAPPEN:

![image](https://cloud.githubusercontent.com/assets/9283365/21821726/75c1977a-d729-11e6-8d3d-dd2270024cc6.png)

Thank you.

Best Regards,
Andrei Porumb

**Comment by lws-team** [comment]
I can't reproduce your problem.
