### ISSUE TITLE
Warnings while compilation and cpp support

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#747]
Hey, I was trying to compile following code and it gave me warnings about deprecated functions.
``

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <unistd.h>
    #include <signal.h>
    #include <libwebsockets.h>
    #define KGRN "\033[0;32;32m"
    #define KCYN "\033[0;36m"
    #define KRED "\033[0;32;31m"
    #define KYEL "\033[1;33m"
    #define KBLU "\033[0;32;34m"
    #define KCYN_L "\033[1;36m"
    #define KBRN "\033[0;33m"
    #define RESET "\033[0m"

    static int destroy_flag = 0;
    static int connection_flag = 0;
    static int writeable_flag = 0;

    static void INT_HANDLER(int signo) {
        destroy_flag = 1;
    }

    struct session_data {
        int fd;
    };

    struct pthread_routine_tool {
        struct lws_context *context;
        struct lws *wsi;
    };

    static int websocket_write_back(struct lws *wsi_in, char *str, int str_size_in) 
    {
        if (str == NULL || wsi_in == NULL)
            return -1;

        int n;
        int len;
        char *out = NULL;

        if (str_size_in < 1) 
            len = strlen(str);
        else
            len = str_size_in;

        out = (char *)malloc(sizeof(char)*(LWS_SEND_BUFFER_PRE_PADDING + len + LWS_SEND_BUFFER_POST_PADDING));
        //* setup the buffer*/
        memcpy (out + LWS_SEND_BUFFER_PRE_PADDING, str, len );
        //* write out*/
        n = lws_write(wsi_in, out + LWS_SEND_BUFFER_PRE_PADDING, len, LWS_WRITE_TEXT);

        printf(KBLU"[websocket_write_back] %s\n"RESET, str);
        //* free the buffer*/
        free(out);

        return n;
    }

    static int ws_service_callback(
                             struct lws *wsi,
                             enum lws_callback_reasons reason, void *user,
                             void *in, size_t len)
    {

        switch (reason) {

            case LWS_CALLBACK_CLIENT_ESTABLISHED:
                printf(KYEL"[Main Service] Connect with server success.\n"RESET);
                char * data = "{\"event\": \"#handshake\",\"data\": {\"authToken\":null},\"cid\":1}";
                websocket_write_back(wsi, data, -1);
                connection_flag = 1;
                break;

            case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
                printf(KRED"[Main Service] Connect with server error.\n"RESET);
                destroy_flag = 1;
                connection_flag = 0;
                break;

            case LWS_CALLBACK_CLOSED:
                printf(KYEL"[Main Service] LWS_CALLBACK_CLOSED\n"RESET);
                destroy_flag = 1;
                connection_flag = 0;
                break;

            case LWS_CALLBACK_CLIENT_RECEIVE:
                if (strcmp((char *)in,"#1")==0){
                    websocket_write_back(wsi, "#2", -1);    
                }else{
                    printf(KCYN_L"[Main Service] Client recvived:%s\n"RESET, (char *)in);
                }
                if (writeable_flag)
                    destroy_flag = 1;

                break;
            case LWS_CALLBACK_CLIENT_WRITEABLE :
                printf(KYEL"[Main Service] On writeable is called. send byebye message\n"RESET);
                websocket_write_back(wsi, "Byebye! See you later", -1);
                writeable_flag = 1;
                break;

            default:
                break;
        }

        return 0;
    }

    static void *pthread_routine(void *tool_in)
    {
        struct pthread_routine_tool *tool = tool_in;

        printf(KBRN"[pthread_routine] Good day. This is pthread_routine.\n"RESET);

        //* waiting for connection with server done.*/
        while(!connection_flag)
            usleep(1000*20);

        //*Send greeting to server*/
        printf(KBRN"[pthread_routine] Server is ready. send a greeting message to server.\n"RESET); 
        websocket_write_back(tool->wsi, "Good day", -1);

        printf(KBRN"[pthread_routine] sleep 2 seconds then call onWritable\n"RESET);
        sleep(1);
        printf(KBRN"------------------------------------------------------\n"RESET);
        sleep(1);
        //printf(KBRN"[pthread_routine] sleep 2 seconds then call onWritable\n"RESET);

        //*involked wriable*/
        printf(KBRN"[pthread_routine] call on writable.\n"RESET);   
        lws_callback_on_writable(tool->wsi);

    }

    int main(void)
    {
        //* register the signal SIGINT handler */
        struct sigaction act;
        act.sa_handler = INT_HANDLER;
        act.sa_flags = 0;
        sigemptyset(&act.sa_mask);
        sigaction( SIGINT, &act, 0);

        struct lws_context *context = NULL;
        struct lws_context_creation_info info;
        struct lws *wsi = NULL;
        struct lws_protocols protocol;

        memset(&info, 0, sizeof info);
        info.port = CONTEXT_PORT_NO_LISTEN;
        info.iface = NULL;
        info.protocols = &protocol;
        info.ssl_cert_filepath = NULL;
        info.ssl_private_key_filepath = NULL;
        info.extensions = lws_get_internal_extensions();
        info.gid = -1;
        info.uid = -1;
        info.options = 0;

        protocol.name  = "websocket";
        protocol.callback = &ws_service_callback;
        protocol.per_session_data_size = sizeof(struct session_data);
        protocol.rx_buffer_size = 0;
        protocol.id = 0;
        protocol.user = NULL;

        context = lws_create_context(&info);
        printf(KRED"[Main] context created.\n"RESET);

        if (context == NULL) {
            printf(KRED"[Main] context is NULL.\n"RESET);
            return -1;
        }

        wsi = lws_client_connect(context, "localhost", 8000, 0,
                "/socketcluster/", "localhost:8000", NULL,
                 protocol.name, -1);
        
        if (wsi == NULL) {
            printf(KRED"[Main] wsi create error.\n"RESET);
            return -1;
        }

        printf(KGRN"[Main] wsi create success.\n"RESET);

        struct pthread_routine_tool tool;
        tool.wsi = wsi;
        tool.context = context;

        // pthread_t pid;
        // pthread_create(&pid, NULL, pthread_routine, &tool);
        // pthread_detach(pid);

        while(!destroy_flag)
        {
            lws_service(context, 50);
        }

        lws_context_destroy(context);

        return 0;
    }

``
client.c: In function ‘main’:
client.c:159:5: warning: ‘lws_get_internal_extensions’ is deprecated (declared at /usr/local/include/libwebsockets.h:1221) [-Wdeprecated-declarations]
     info.extensions = lws_get_internal_extensions();
     ^
client.c:180:5: warning: ‘lws_client_connect’ is deprecated (declared at /usr/local/include/libwebsockets.h:2142) [-Wdeprecated-declarations]
     wsi = lws_client_connect(context, "localhost", 8000, 0,
     ^

Can you suggest me replacement to those API and can I compile library code using CPP, I mean if I want to use libwebsockets in cpp ?

**Comment by lws-team** [comment]
It's what it looks like... the code written by someone else is not up to date with lws.

The test-client.c that comes with lws is always up to date and it's the best place to start, although it needs chopping down before it is useful for anything else.

"Deprecated" means it is still supported, but it will be removed soon and there will be a better way, for client connect it is `lws_client_connect_via_info()`.  For `lws_get_internal_extensions` the extensions array should be given explicitly now if you want extensions... that basically means if you want permessage-deflate, which is the only standardized extension.  If you don't care, just set info.extensions to NULL.

cpp can call C OK, so you can mix them.  Libwebsockets already has the extern "C" stuff in the headers.
