### ISSUE TITLE
[Win7][vs2015][chrome][wss]libwebsocket was  blocking when wss connecting.

### ISSUE THREAD

**Issue by AmelieFan** [warmcat/libwebsockets#751]
I have used the libwebsockets in my webserver. and cmake in vs2015 environment.Run the server with openssl  . I have not used libev/libuv. When I used MSE as  client, ws connection is  fast well, but wss connection always happened blocking, and wss will fail or take long time to connection about 10 seconds.ssl certificate is self-signed

![wss_failed](https://cloud.githubusercontent.com/assets/25164168/22006222/3ff147f0-dca4-11e6-856b-14c4f074c9fb.png)

. Chrome version is 55.0.2883.87(64bit) and server openssl version 1.0.1t. As the wireshark capture said chrome always say tcp FIN after ssl handshake done, and reconnect to server, then  it will block on server. Anyone has the same problem? Thanks for your direction.

**Comment by lws-team** [comment]
What happens if you use the `libwebsockets-test-server` test app directly in the same way?

**Comment by AmelieFan** [comment]
My test case is similar with libwebsockets-test-server, different that client send multi-connections to webserver in wss at the same time. When chrome happen reject TCP connection and connect again, server will blocking. I think maybe is　ｎｅｔｗｏｒｋ IO　ｂｌｏｃｋ．

**Comment by lws-team** [comment]
Yeah... I understand it is different.  But I know what is in the test server.  If that acts the same, or if that doesn't show the problem, it helps us a little bit to guess about the problem.

Sockets are set to nonblocking, at least they are supposed to be.

When you call the service loop (since you are not using libuv / ev) how long did you set the timeout for in the service call?

**Comment by AmelieFan** [comment]
I test the libwebsockets-test-server, and I find it will take about 6 seconds when server and client not in the same machine. And http or https both will delay 6 seconds. I confuse. wireshark said also has TCP FIN,but send by server. My test case use:
while (lws_service_tsi(context, 20, (int)(long)thread_id) >= 0 && !force_exit),is that you said timeout?

**Comment by AmelieFan** [comment]
Thank you for your tip. This morning I just find my test case without "ssl_cipher_list", It's different with test-server, so I try to add "ssl_cipher_list", and it works well. Thank you!!! I think ssl handshake fail for openssl default cipher list is less cipher for chrome.

**Comment by lws-team** [comment]
Ah that is good news.
