### ISSUE TITLE
Mingw linker issue

### ISSUE THREAD

**Issue by thomasarnbjerg** [warmcat/libwebsockets#754]
I'm trying to build 2.1 stable but have linker issues against openssl. I've built 1.1.0b and pass the location of libcrypto.dll and libssl.dll (and NOT libeay32.dll/ssleay32.dll) like this:

cmake -G"MinGW Makefiles" -DLWS_USE_LIBEV=0 -DLWS_USEUV=0 -DOPENSSL_ROOT_DIR=C:/development/openssl-1.1.0b -DLWS_OPENSSL_LIBRARIES="C:/development/openssl-1.1.0b/libssl.dll.a;C:/development/openssl-1.1.0b/libcrypto.dll.a"

The configuration report still states:
OpenSSL libraries: C:/OpenSSL-Win32/ssleay32.dll;C:/OpenSSL-Win32/libeay32.dll

What am I doing wrong?

Also it's not clear to me if i need to build libuv and libev?

I'm building on Windows 7, 64 bit with Mingw-64 (x86_64-6.2.0-posix-seh-rt_v5-rev1)

**Comment by lws-team** [comment]
You don't have to build ev or uv if you don't want either.

These don't sound like 'linker issues', they sound like 'cmake issues'.

Where did these weird fixed paths about ssleay come from?  They don't seem to be coming out of CMakeLists.txt...

**Comment by thomasarnbjerg** [comment]
Just did a vanilla build with the same command + make and everything worked. I think this is a leftover from previous build-attemts using cmake-gui/different versions of openssl. 
At some point in time the dlls C:/OpenSSL-Win32/ssleay32.dll;C:/OpenSSL-Win32/libeay32.dll were present.
Case closed and thanks for your time!
