### ISSUE TITLE
Unable to get disconnect callback from server

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#756]
Hi, I have developed C- client for socketcluster framework in node.js using libwebsocket client. I was trying to implement reconnection facility in client. Reconnection to server can only be called if we know that client has accidently disconnected from server. Still , when I shut down server client is unable to get disconnect callback from server.My code for connecting to server is 
``

    void *pthread_lws_service(void *tool)
    {
    while(!destroy_flag)
    {
        lws_service(context, 50);
    }
    printf("lws service got called");
    wsi=NULL;
    // lws_context_destroy(context);
    pthread_t pid;
    pthread_create(&pid, NULL, pthread_reconnect,(void *) &tool);
    
    }

    void *pthread_reconnect(void *tool)
    {
    sleep(3); 
    printf("\nTrying to reconnect");
    i.protocol="websocket"; 
    i.pwsi = &wsi;
    destroy_flag=0;
    wsi=lws_client_connect_via_info(&i);

    if (wsi == NULL) {
        printf(KRED"[Main] wsi create error.\n"RESET);
    }else{

    printf(KGRN"[Main] wsi create success.\n"RESET);

    pthread_t pid;
    pthread_create(&pid, NULL, pthread_lws_service,(void *) &tool);
    }
    }

    void socket_connect()
    {
    context = NULL;
    wsi = NULL;

    act.sa_handler = INT_HANDLER;
    act.sa_flags = 0;
    sigemptyset(&act.sa_mask);
    sigaction( SIGINT, &act, 0);

    memset(&info, 0, sizeof info);
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.iface = NULL;
    info.protocols = &protocol;
    info.ssl_cert_filepath = NULL;
    info.ssl_private_key_filepath = NULL;
    info.http_proxy_address=s->proxy_address;
    info.http_proxy_port=(unsigned int )s->proxy_port;
    // info.extensions = lws_get_internal_extensions();
    info.extensions=NULL;
    info.gid = -1;
    info.uid = -1;
    info.options = 0;

    protocol.name  = "websocket";
    protocol.callback = &ws_service_callback;
    protocol.per_session_data_size = sizeof(struct session_data);
    protocol.rx_buffer_size = 0;
    protocol.id = 0;
    protocol.user = NULL;

    context = lws_create_context(&info);

    memset(&i, 0, sizeof(i));

    i.port = s->port;
    i.path = s->path;
    i.address=s->address;
    i.context = context;
    i.ssl_connection = use_ssl;
    i.host = s->address;
    i.origin = s->address;
    i.protocol="websocket";
    i.ietf_version_or_minus_one = ietf_version;
    i.client_exts = exts;

    printf(KRED"[Main] context created.\n"RESET);

    if (context == NULL) {
        printf(KRED"[Main] context is NULL.\n"RESET);
        return;
    }

    // wsi = lws_client_connect(context, "localhost", 8000, 0,
            // "/socketcluster/", "localhost:8000", NULL,
             // protocol.name, -1);

    wsi=lws_client_connect_via_info(&i);
    
    if (wsi == NULL) {
        printf(KRED"[Main] wsi create error.\n"RESET);
        return;
    }

    printf(KGRN"[Main] wsi create success.\n"RESET);

    
    tool.wsi = wsi;
    tool.context = context;

    pthread_t pid;
    pthread_create(&pid, NULL, pthread_lws_service,(void *) &tool);
    pthread_detach(pid);
    

    return;
    }

``
and callbacks are received in following method

``

    static int ws_service_callback(
                         struct lws *wsi,
                         enum lws_callback_reasons reason, void *user,
                         void *in, size_t len)
    {

    switch (reason) {

        case LWS_CALLBACK_CLIENT_ESTABLISHED:
            printf(KYEL"[Main Service] Connect with server success.\n"RESET);
            connection_flag = 1;
            break;

        case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
            printf(KRED"[Main Service] Connect with server error.\n"RESET);
            destroy_flag = 1;
            connection_flag = 0;
            break;

        case LWS_CALLBACK_CLOSED:
            printf(KYEL"[Main Service] LWS_CALLBACK_CLOSED\n"RESET);
            destroy_flag = 1;
            connection_flag = 0;
            break;

        case LWS_CALLBACK_CLIENT_RECEIVE:
            printf(KCYN_L"[Main Service] Client recvived:%s\n"RESET, (char *)in);

            if (writeable_flag)
                destroy_flag = 1;

            break;
        case LWS_CALLBACK_CLIENT_WRITEABLE :
            printf(KYEL"[Main Service] On writeable is called. send byebye message\n"RESET);
            websocket_write_back(wsi, "Byebye! See you later", -1);
            writeable_flag = 1;
            break;

        default:
            break;
    }

    return 0;
    }

LWS_CALLBACK_CLOSED: is not called when server is disconnected from client. It is called only if lws context is destroyed.

**Comment by lws-team** [comment]
In the case your connection was in client mode, and closed while doing http (as opposed to ws), your closed callback will come with reason `LWS_CALLBACK_CLOSED_CLIENT_HTTP`.

**Comment by sacOO7** [comment]
Hey I tried adding above case to switch statement but it didn't worked. Can you provide me with possible reason? Actually ws_service_callback functions doesn't get called after disconnect event from server.

**Comment by lws-team** [comment]
What does "disconnect from server" mean exactly?

**Comment by sacOO7** [comment]
It means I have closed the server process accidentally or network error occured due to which connection is lost.

**Comment by sacOO7** [comment]
Actually I tried other clients which shows disconnect event after server process is closed or network error occured. In this case disconnect event is called only if lw_context is destroyed.

**Comment by lws-team** [comment]
Those two are very different... if you close the server but all else is OK, then clients are actively notified at tcp layer and you should get a close callback.

If the network connection silently fails, you won't get notified.  You have to detect it by probing the connection with ping / pong at intervals... lws can do it for you.

What platform is this?

**Comment by sacOO7** [comment]
I'm currently using Ubuntu 14.04

**Comment by lws-team** [comment]
Hm... your code for protocols[] is wrong.  It must be an array with NULL-filled entry to mark the end of it.

What happens if you try this with the test server and client?  Ie `libwebsockets-test-server` in one terminal and `libwebsockets-test-client localhost` in another, then ^C the server?  Test client should know about it and attempt reconnects at 2s intervals.

**Comment by sacOO7** [comment]
Just a minute, I will try

**Comment by sacOO7** [comment]
Well it shows me this message after I close the server process,

2017/01/20 23:55:59:1116] NOTICE: dumb: LWS_CALLBACK_CLOSED
[2017/01/20 23:55:59:1116] NOTICE: dumb: connecting
[2017/01/20 23:55:59:1118] ERR: CLIENT_CONNECTION_ERROR: dumb: (null) (nil)
[2017/01/20 23:56:01:1137] NOTICE: dumb: connecting
[2017/01/20 23:56:01:1140] NOTICE: mirror: connecting
[2017/01/20 23:56:01:1143] ERR: CLIENT_CONNECTION_ERROR: dumb: (null) (nil)
[2017/01/20 23:56:01:1145] ERR: CLIENT_CONNECTION_ERROR: mirror: (null) (nil)
[2017/01/20 23:56:03:1163] NOTICE: dumb: connecting
[2017/01/20 23:56:03:1167] NOTICE: mirror: connecting
[2017/01/20 23:56:03:1169] ERR: CLIENT_CONNECTION_ERROR: dumb: (null) (nil)
[2017/01/20 23:56:03:1170] ERR: CLIENT_CONNECTION_ERROR: mirror: (null) (nil)
[2017/01/20 23:56:05:1194] NOTICE: dumb: connecting
[2017/01/20 23:56:05:1196] NOTICE: mirror: connecting
[2017/01/20 23:56:05:1197] ERR: CLIENT_CONNECTION_ERROR: dumb: (null) (nil)
[2017/01/20 23:56:05:1198] ERR: CLIENT_CONNECTION_ERROR: mirror: (null) (nil)
[2017/01/20 23:56:07:1221] NOTICE: dumb: connecting
[2017/01/20 23:56:07:1223] NOTICE: mirror: connecting
[2017/01/20 23:56:07:1226] ERR: CLIENT_CONNECTION_ERROR: dumb: (null) (nil)
[2017/01/20 23:56:07:1227] ERR: CLIENT_CONNECTION_ERROR: mirror: (null) (nil)

**Comment by sacOO7** [comment]
Where should I change the code in order to fix this ?

**Comment by lws-team** [comment]
How should I know, it's your code.

I provide the test apps with CC0 license to make it easy to use that code as your starting point.  If they work but whatever you have doesn't, then it's up to you to align your code to the working example you have sources for.

**Comment by sacOO7** [comment]
I will try for sure :) .

**Comment by flybysky** [comment]
Hi, I'm using cocos2d-x 3.17 which includes lws 2.1.0. My app connects with wss to the server. it is working well on android/ios/win32. but only on ios, when the app becomes inactive (phone goes idle or sleep/idle button pressed), wss disconnects silently immediately when screen goes black (5-7 seconds sometimes sooner). No event is fired even when the app is active again. I verified it very well, the server clearly shows it was disconnected but the app still thinks it is connected and last event was "open". I checked cocos WebSocket.cpp wrapper, it does not get any event, the only thing that happens is the callbacks related to polling stop. Is there any workaround?
