### ISSUE TITLE
When connecting as client, lws always prepends http:// to origin header

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#757]
in commit 44e260e004a414cd7d1ec3f36cc6bd4f25cdfdae (from pull request https://github.com/warmcat/libwebsockets/pull/19) lws was changed to prepend `"http://"` string to whatever was provided in client connect info as `origin` member.

I think this makes little sense, especially if using SSL.
However, I'm not sure what to propose as the fix. Perhaps depend on `ssl_connection` in info and put `"https://"` in that case? But that's just guesswork again, since as a non-web-browser lws doesn't know the wider context of what "origin" the connection we're making is associated with, if any.

I'd even say it's best if the library didn't put http:// prefix, and let the application decide if it's going to do that or anything similar.

Any thoughts?

**Comment by lws-team** [comment]
It looks like the patch wasn't a great idea.  However it's well entrenched there now and changing the default behaviour will probably make trouble.

How about stay as it is by default but add a context option flag that just disables all meddling on what was given in the client connect info?  If you don't care about origin security you'll still be happy but if you are aware of it, this lets you manage it entirely yourself.

**Comment by dosvald** [comment]
If I understood right, it'd mean adding a new `LWS_SERVER_OPTION_RAW_ORIGIN` to a context/vhost creation info, and when that vhost is used in client_connect_info, no change on origin would be done. That makes sense if you ignore the misnomer or name the enum better.

**Comment by lws-team** [comment]
This should do it?

**Comment by dosvald** [comment]
Thanks
