### ISSUE TITLE
Support for Binary  web socket protocol?

### ISSUE THREAD

**Issue by thomasarnbjerg** [warmcat/libwebsockets#758]
I'm trying to write an Emscripten powered client against a libwebsocket based server. 

The communication works with a java script web-socket - e.g.:

var ws = new WebSocket("ws://127.0.0.1:9338");

With emscripten communication with the same URL fails.  I get the call backs equivalent to the following sequence (the sequence represents one connection attempt):

2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance.
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established.
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established.
2017-1-20 12:46:53     INFO: Creating web socket instance.
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated.
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established.
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated..
2017-1-20 12:46:53     INFO: Destroying web socket instance..
2017-1-20 12:46:53     INFO: New network Connection established..
2017-1-20 12:46:53     INFO: Creating web socket instance..
2017-1-20 12:46:53     INFO: New client instantiated.. 
2017-1-20 12:46:53     INFO: Destroying web socket instance.. 

I suspect that the problem lies in the protocol requested when Emscripten is involved. One additional request header is present: 

Sec-WebSocket-Protocol:"binary"

- which is not present in the pure javascript version.

Is there a way to have libwebsockets accept the binary protocol?

**Comment by lws-team** [comment]
Yeah... just name the name in the protocols[] struct as "binary".  It will match it.

However it is an implicit promise that the server knows how to deal with ws messages in this 'binary' format, which might just be chunks of data, or might have structure and need parsing etc.  At least, passing the ws upgrade negotiation will get you further along.

Btw it's best to turn up the logging to -d31 or so to see why this kind of thing happened.  Note you have to tell cmake to do a "ebug" build to get logging beow Notice level compiled in (see README.build.md)

**Comment by thomasarnbjerg** [comment]
GREAT! You are the hero of the day.
Thanks.
