### ISSUE TITLE
Having problem building in Docker

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#763]
For some of the errors, I could easily fix by install the lib-stuff.

Until I encountered the error below:

`[ 22%] Building C object CMakeFiles/websockets.dir/lib/smtp.c.o`

    CMakeFiles/websockets.dir/build.make:662: recipe for target 'CMakeFiles/websockets.dir/lib/smtp.c.o'     failed
    make[2]: *** [CMakeFiles/websockets.dir/lib/smtp.c.o] Error 1
    make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
    make: *** [all] Error 2

Full error gist: https://gist.github.com/d30jeff/081c214b45c43d8633aea7b12c0c5a96

My Dockerfile:

    FROM ubuntu:16.04

    RUN apt update

    RUN apt install git cmake zlibc zlib1g zlib1g-dev openssl libssl-dev libuv-dev sqlite3 libsqlite3-dev -y

    RUN mkdir -p /usr/src/app

    WORKDIR /usr/src/app

    RUN git clone https://github.com/warmcat/libwebsockets.git libwebsockets

    WORKDIR /usr/src/app/libwebsockets

    RUN mkdir build

    WORKDIR /usr/src/app/libwebsockets/build

    RUN cmake .. -DLWS_WITH_LWSWS=1 -DLWS_WITH_GENERIC_SESSIONS=1

    RUN make && make install

Should run fine in ubuntu as I have one running fine locally.

Decided to run it on Docker because I have like 10s of libwebsockets directory, and can't remember which folder contains the current built lwsws.

**Comment by lws-team** [comment]
I am not sure Docker is the answer to your problem (git probably is...) but this looks like another case of Ubuntu's ancient libuv making trouble.  If you apt-get `libuv1` package, replacing the stone-age libuv package they have by default, it is less ancient and hopefully that's the cause of the api mismatches.

**Comment by d30jeff** [comment]
I have forgotten about that #637 , installed **libuv1** and **libuv1-dev** and it works fine now, sorry.
