### ISSUE TITLE
http_proxy format

### ISSUE THREAD

**Issue by vpopescu** [warmcat/libwebsockets#764]
The library expects http_proxy set to "hostname:port".
On linux, the format of this variable is http://proxy:port".  

Please consider:

a) fixing this bug to support the proper format  (preferred) or...
b) use a different environment variable name that won't conflict with http_proxy on linux

from: libwebsocket_set_proxy:

p = strchr(context->http_proxy_address, ':');
	if (!p) {
		lwsl_err("http_proxy needs to be ads:port\n");
		return -1;
	}

That code is incorrect anyway, since it will pass http://proxy:port too, so it will just silently not work on linux systems.

**Comment by lws-team** [comment]
Please try https://github.com/warmcat/libwebsockets/commit/71bb40080510bd1d2ddf90e0b81bd69f0bbb4dd9

**Comment by vpopescu** [comment]
Thanks for the quick turnaround. The code looks good to me, althought I can't test it until the guys in Azure IOT SDK update their dependency on your library.

A note though; It fixes my issue BUT some people may still have issues, specifically those with authenticated proxies. I *believe* they need to use a format like http://username:password@hostname:port. You may want to consider using a URL parser instead of blindly removing the scheme component.

I'll let you decide what you want to do with this request -- in case you want to keep it open for a more comprehensive fix.

Thanks again!

**Comment by vpopescu** [comment]
Ignore my previous comment, I think you are handling the authenticated proxy right after that code.
