### ISSUE TITLE
Problem compiling with libev.

### ISSUE THREAD

**Issue by matrixhacker** [warmcat/libwebsockets#766]
I get the following output when I try to compile with libev support:

/home/foo/git/libwebsockets/test-server/test-server-libev.c: In function ‘main’:
/home/foo/git/libwebsockets/test-server/test-server-libev.c:305:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   _ev_init(&signals[n], signal_cb);
   ^
/home/michaelt/git/libwebsockets/test-server/test-server-libev.c:373:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  _ev_timer_init(&timeout_watcher, ev_timeout_cb, 0.05, 0.05);
  ^
cc1: all warnings being treated as errors
CMakeFiles/test-server-libev.dir/build.make:62: recipe for target 'CMakeFiles/test-server-libev.dir/test-server/test-server-libev.c.o' failed

I'm using libwebsockets master and libev 4.22. on Debian 8. Any thoughts would be appreciated.

**Comment by lws-team** [comment]
Mmmmm read this from libev maintainer 2008

http://lists.schmorp.de/pipermail/libev/2008q4/000442.html

that pretty much singlehandedly put me off libev and on to libuv.

I tried to work around it in the libev example, but ev uses macros for many things with the dodgy casts, so what appears in the test app depends on your libev headers version.  You can try put `-fno-strict-aliasing` at the end here

https://github.com/warmcat/libwebsockets/blob/master/CMakeLists.txt#L706

**Comment by matrixhacker** [comment]
Thank you for your time. I'm writing a websocket plugin for a framework that already works with libev, so I'm stuck with it. I was using an ev_timer to call lws_service every 50ms, but I seem to be running into a timing issue that causes subsequent file requests (js/css) to not be filled immediately following the index request. I was hoping that a tighter coupling would resolve the issue.
