### ISSUE TITLE
http/https/ws/wss on same port

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#767]
Hallo,

is possible to configure the server on the same port (for example 10080) to receive HTTP / HTTPS / WS /  WSS connections ?
 How ?

Thank you for your help

Mario

**Comment by lws-team** [comment]
Since every ws[s] starts off as http[s], that part is no big trick.

To convince it to accept http on a port set up for https - **notice this makes the security aspect of https worthless and is dangerous from that POV** - you can give an option at context creation time

```
	LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT		= (1 << 3) |
								  (1 << 12),
	/**< (VH) Allow non-SSL (plaintext) connections on the same
	 * port as SSL is listening... undermines the security of SSL;
	 * provides  LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT */
```
