### ISSUE TITLE
configure multiple vhost

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#768]
I have a vhost on port 10080 for accept WS and HTTP
Another vhost on port 10443 for WSS and HTTPS
Another vhost on port 10523 for accept WSS HTTPS and HTTP

Is possible create a vhost for accept WS / WSS / HTTP / HTTPS ? How ?

Thank you.

Mario

**Comment by lws-team** [comment]
Accepting ssl or unencrypted on the same port is a nasty hack.  It's only supported as a flag at context creation time that affects all ssl.  And I don't recommend using it because it's not sane to have ssl requiring crypto, but at the same time accept connections without crypto for the same purpose.

Otherwise though, you control ssl or not by giving the vhost a cert + key or not when you create it.

And you also control which protocols your vhost will accept when you create it because you give it an array of protocols then.

**Comment by rollen1960** [comment]
I don't understand. I use different vhost

	struct lws_context *context;
	// create connection struct
	struct lws_context_creation_info info;
	memset(&info, 0, sizeof(info));
	info.port = 16384;
	//info.iface = NULL;
	struct lws_protocols protocols[] = {  
	    {
		"http-only", callback
		, sizeof(void*), 0xFFFFFF
		, 0, NULL
	    },
	    {
		NULL, NULL, 0
	    }
	};
	//protocols[0].user = this;
	info.protocols = protocols;
	//info.extensions = NULL;
	info.ssl_cert_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.pem";
	info.ssl_private_key_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.key";
	info.ssl_ca_filepath = "/home/mariorollino/WS/MSP3/config/FinecoCASubordinate.pem";
	//info.ssl_cipher_list = "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL";
	info.gid = -1;
	info.uid = -1;
	//info.options = 0;
	info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;
	info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	//info.options |= LWS_SERVER_OPTION_EXPLICIT_VHOSTS;
	//info.options |= LWS_SERVER_OPTION_VALIDATE_UTF8;
	info.user = this;
	//info.ka_time = 0;
	//info.ka_probes = 0;
	//info.ka_interval = 0;   
	// create libwebsocket context representing this server
	LOGGER_ALWAYS("lws_create_context");
	context = lws_create_context(&info);
	if (context == NULL) {
	    LOGGER_HALT("error lws_create_context");
	}
	//char buf[0xFFFF];
	//lws_json_dump_context(context, buf, sizeof(buf));
	//LOGGER_DEBUG(VALUE(buf));

	{
	    memset(&info, 0, sizeof(info));
	    info.port = 30080;
	    info.protocols = protocols;
	    info.gid = -1;
	    info.uid = -1;
	    info.user = this;
	    // create lws context representing this server
	    struct lws_vhost* vhost = lws_create_vhost(context, &info);
	    if (vhost == NULL)
		LOGGER_HALT("error lws_create_vhost")
	    //char buf[0xFFFF];
	    //lws_json_dump_vhost(vhost, buf, sizeof(buf));
	    //LOGGER_DEBUG(VALUE(buf));
	}
    
	{
	    memset(&info, 0, sizeof(info));
	    info.port = 30443;
	    info.protocols = protocols;
	    info.gid = -1;
	    info.uid = -1;
	    info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	    info.user = this;
	    info.ssl_cert_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.pem";
	    info.ssl_private_key_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.key";
	    info.ssl_ca_filepath = "/home/mariorollino/WS/MSP3/config/FinecoCASubordinate.pem";
	    //info.ssl_cipher_list = "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL";
	    // create lws context representing this server
	    struct lws_vhost* vhost = lws_create_vhost(context, &info);
	    if (vhost == NULL)
		LOGGER_HALT("error lws_create_vhost")
	    //char buf[0xFFFF];
	    //lws_json_dump_vhost(vhost, buf, sizeof(buf));
	    //LOGGER_DEBUG(VALUE(buf));
	}
    
	// infinite loop, to end this server send SIGTERM. (CTRL+C)
	LOGGER_ALWAYS("lws_service");
	for (;;) {
	    lws_service(context, 50);
	}
	LOGGER_ALWAYS("lws_context_destroy");
	lws_context_destroy(context);
	return NULL;

but on port 16384 I can not connect in WS, I must connect in WSS. How must I set the procols array for obtain that i connect with WS and with WSS ?

Thank you.

Mario

**Comment by lws-team** [comment]
Your code is comment city... if you will create you own vhosts the context creation must have this enabled

```
info.options |= LWS_SERVER_OPTION_EXPLICIT_VHOSTS;
```

**Comment by rollen1960** [comment]
struct lws_context *context;
	// create connection struct
	struct lws_context_creation_info info;
	memset(&info, 0, sizeof(info));
	struct lws_protocols protocols[] = {  
	    {
		"http-only", callback
		, sizeof(void*), 0xFFFFFF
		, 0, NULL
	    },
	    {
		NULL, NULL, 0
	    }
	};
	info.ssl_cert_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.pem";
	info.ssl_private_key_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.key";
	info.ssl_ca_filepath = "/home/mariorollino/WS/MSP3/config/FinecoCASubordinate.pem";
	//info.ssl_cipher_list = "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL";
	info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;
	info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	info.options |= LWS_SERVER_OPTION_EXPLICIT_VHOSTS;
	info.user = this;
	// create libwebsocket context representing this server
	LOGGER_ALWAYS("lws_create_context");
	context = lws_create_context(&info);
	if (context == NULL) {
	    LOGGER_HALT("error lws_create_context");
	}
	{
	    memset(&info, 0, sizeof(info));
	    info.port = 30080;
	    info.protocols = protocols;
	    info.gid = -1;
	    info.uid = -1;
	    info.user = this;
	    // create lws context representing this server
	    struct lws_vhost* vhost = lws_create_vhost(context, &info);
	    if (vhost == NULL)
		LOGGER_HALT("error lws_create_vhost")
	}
    
	{
	    memset(&info, 0, sizeof(info));
	    info.port = 30443;
	    info.protocols = protocols;
	    info.gid = -1;
	    info.uid = -1;
	    info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;
	    info.options |= LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
	    info.user = this;
	    info.ssl_cert_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.pem";
	    info.ssl_private_key_filepath = "/home/mariorollino/WS/MSP3/config/dev-msp.fineco.it.key";
	    info.ssl_ca_filepath = "/home/mariorollino/WS/MSP3/config/FinecoCASubordinate.pem";
	    //info.ssl_cipher_list = "RC4-MD5:RC4-SHA:AES128-SHA:AES256-SHA:HIGH:!DSS:!aNULL";
	    // create lws context representing this server
	    struct lws_vhost* vhost = lws_create_vhost(context, &info);
	    if (vhost == NULL)
		LOGGER_HALT("error lws_create_vhost")
	}
    
	// infinite loop, to end this server send SIGTERM. (CTRL+C)
	LOGGER_ALWAYS("lws_service");
	for (;;) {
	    lws_service(context, 50);
	}
	LOGGER_ALWAYS("lws_context_destroy");
	lws_context_destroy(context);
	return NULL;

I can open a WSS on port 30443 but i cannot open a WS on 30443 . Is it impossible or I write a bad code ? Thank for your patient.

Mario

**Comment by lws-team** [comment]
You are using the wrong option, it is

LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT
