### ISSUE TITLE
lws_client_connect_info member client_exts not used

### ISSUE THREAD

**Issue by mmilata** [warmcat/libwebsockets#770]
Maybe I'm overlooking something but the `client_exts` member of `struct lws_client_connect_info` doesn't seem to be used anywhere?

```
$ grep --exclude-dir=doc -R client_exts
lib/libwebsockets.h:    const struct lws_extension *client_exts;
test-server/android/app/src/main/jni/LwsService.cpp:  info_ws.client_exts = exts;
test-server/test-fraggle.c:             i.client_exts = exts;
test-server/test-client.c:      i.client_exts = exts;
test-server/test-ping.c:        i.client_exts = exts;
test-server/test-echo.c:                        i.client_exts = exts;

```

**Comment by lws-team** [comment]
Thanks for pointing it out... it's just leftover cruft.

For client give the array of extensions in the context creation struct same as server.

The patch above cleans out the cruft and corrects the examples.
