### ISSUE TITLE
lws_client_connect_via_info always return NULL

### ISSUE THREAD

**Issue by FuyuriSeiji** [warmcat/libwebsockets#773]
Hi, libwebsocket developers,

Thank you, first. It's really great library for me, probably until 1.6

I'm switching to v2.02 where lws_client_connect is deprecated.
I try to adopt lws_client_connect_via_info() instead. But it always return NULL for me.

The parameter initialized like this:
        `lws_client_connect_info lws_client_info;`
        `lws_client_info.context = context;`
        `lws_client_info.address = "stream.pushbullet.com";`
        `lws_client_info.port = 443;`
        `lws_client_info.ssl_connection = 2;  // WSS                `                                                                                           
        `lws_client_info.path = path;`
        `lws_client_info.host = "stream.pushbullet.com:443";`
        `lws_client_info.origin = NULL;`
        `lws_client_info.protocol = protocol.name;`
        `lws_client_info.ietf_version_or_minus_one = -1;`
        `lws_client_connect_info *ptr = &lws_client_info;`

        wsi = lws_client_connect_via_info( ptr );

Although I read the documents many times very carefully,
Is there anything mistaken in this initialization?

Thank you.

**Comment by lws-team** [comment]
1) Make sure you memset() the client info struct down to 0 first, if it is declared on the stack.  Otherwise it will be full of trash in the uninitialized members.  The example code all does this.

2) Turn up your logging to see what is happening.

3) Use master branch, and handle the LWS_CALLBACK_CLIENT_CONNECTION_ERROR in protocols[0].

You may get a descriptive error string in *in
```
	LWS_CALLBACK_CLIENT_CONNECTION_ERROR			=  1,
	/**< the request client connection has been unable to complete a
	 * handshake with the remote server.  If in is non-NULL, you can
	 * find an error string of length len where it points to
	 *
	 * Diagnostic strings that may be returned include
	 *
	 *     	"getaddrinfo (ipv6) failed"
	 *     	"unknown address family"
	 *     	"getaddrinfo (ipv4) failed"
	 *     	"set socket opts failed"
	 *     	"insert wsi failed"
	 *     	"lws_ssl_client_connect1 failed"
	 *     	"lws_ssl_client_connect2 failed"
	 *     	"Peer hung up"
	 *     	"read failed"
	 *     	"HS: URI missing"
	 *     	"HS: Redirect code but no Location"
	 *     	"HS: URI did not parse"
	 *     	"HS: Redirect failed"
	 *     	"HS: Server did not return 200"
	 *     	"HS: OOM"
	 *     	"HS: disallowed by client filter"
	 *     	"HS: disallowed at ESTABLISHED"
	 *     	"HS: ACCEPT missing"
	 *     	"HS: ws upgrade response not 101"
	 *     	"HS: UPGRADE missing"
	 *     	"HS: Upgrade to something other than websocket"
	 *     	"HS: CONNECTION missing"
	 *     	"HS: UPGRADE malformed"
	 *     	"HS: PROTOCOL malformed"
	 *     	"HS: Cannot match protocol"
	 *     	"HS: EXT: list too big"
	 *     	"HS: EXT: failed setting defaults"
	 *     	"HS: EXT: failed parsing defaults"
	 *     	"HS: EXT: failed parsing options"
	 *     	"HS: EXT: Rejects server options"
	 *     	"HS: EXT: unknown ext"
	 *     	"HS: Accept hash wrong"
	 *     	"HS: Rejected by filter cb"
	 *     	"HS: OOM"
	 *     	"HS: SO_SNDBUF failed"
	 *     	"HS: Rejected at CLIENT_ESTABLISHED"
	 */
```

**Comment by FuyuriSeiji** [comment]
Hi, thank you for the reminds. 
After memseting the client info struct, 
the initialization went fine but somehow segmentation fault happens in lws_service() and ssl_ctrl.
I will try to collect the details and to see if I need some other help.
Thank for the help anyway and consider this issue closed.

**Comment by FuyuriSeiichi** [comment]
Hi, I'm leaving a note here, just in case some one else bump into similar issue.

The problem I encountered is actually rooted in my kernel does not include IPv6 support, while I compiled libwebsockets with IPv6 support. It take me really long time before I notice this.

Now everything is fine for me. 
Thank you, libwebsockets devs.
