### ISSUE TITLE
length mismatch with http server from remote client

### ISSUE THREAD

**Issue by jonowoodward1986** [warmcat/libwebsockets#779]
Hello,

I have added http support to my application and on the local machine it works with folders / mimetypes however if I access from another machine I get the following:

net::ERR_CONTENT_LENGTH_MISMATCH

**Comment by jonowoodward1986** [comment]
`int callback_http(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
	int last_fd;
	struct lws_pollargs *pa = (struct lws_pollargs *)in;

	switch (reason) {
		case LWS_CALLBACK_ADD_POLL_FD:

			if (count_pollfds >= max_poll_elements) {
				applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_WARN, "%s: too many sockets to track", __func__);
				return 1;
			}

			fd_lookup[pa->fd] = count_pollfds;
			pollfds[count_pollfds].fd = pa->fd;
			pollfds[count_pollfds].events = pa->events;
			pollfds[count_pollfds++].revents = 0;
			break;

		case LWS_CALLBACK_DEL_POLL_FD:
			if (!--count_pollfds)
				break;
			last_fd = fd_lookup[pa->fd];

			/* have the last guy take up the vacant slot */
			pollfds[last_fd] = pollfds[count_pollfds];
			fd_lookup[pollfds[count_pollfds].fd] = last_fd;
			break;

		case LWS_CALLBACK_CHANGE_MODE_POLL_FD:
		    pollfds[fd_lookup[pa->fd]].events = pa->events;
			break;

		case LWS_CALLBACK_CLIENT_WRITEABLE :
			applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_WARN, "%s: LWS_CALLBACK_CLIENT_WRITEABLE", __func__);
			break;

		case LWS_CALLBACK_HTTP :
		{
			char buf[256];
			const char *mimetype;
			char *other_headers;
			char leaf_path[1024];
			unsigned char *p;
			struct timeval tv;
			int n;

			lws_get_peer_simple(wsi, buf, sizeof(buf));

	        applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_WARN, "%s: LWS_CALLBACK_HTTP HTTP connect from %s", 
	        	__func__,
	        	buf
	        );

			if (len < 1) {
				lws_return_http_status(wsi,	HTTP_STATUS_BAD_REQUEST, NULL);
		        applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_ERROR, "%s: LWS_CALLBACK_HTTP HTTP_STATUS_BAD_REQUEST", 
		        	__func__
		        );				
				return 0;
			}

			/* if a legal POST URL, let it continue and accept data */
			if (lws_hdr_total_length(wsi, WSI_TOKEN_POST_URI)) {
				applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_ERROR, "%s: if a legal POST URL, let it continue and accept data", 
					__func__
				);				
				return 0;
			}

			strcpy(buf, resource_path);

			if (strcmp(in, "/")) {
				if (*((const char *)in) != '/') {
					strcat(buf, "/");
				}
				strncat(buf, in, sizeof(buf) - strlen(buf) - 1);			
			} else {
				/* default file to serve */
				strcat(buf, "/index.html");
			}

			buf[sizeof(buf) - 1] = '\0';

			/* refuse to serve files we don't understand */
			mimetype = get_mimetype(buf);
			if (!mimetype) {
				lwsl_err("Unknown mimetype for %s\n", buf);
				lws_return_http_status(wsi, HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE, NULL);
				return -1;
			}

			other_headers = leaf_path;
			p = (unsigned char *)leaf_path;
			n = (char *)p - leaf_path;

			n = lws_serve_http_file(wsi, buf, mimetype, other_headers, n);
			if (n < 0 || ((n > 0) && lws_http_transaction_completed(wsi))) {
				applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_ERROR, "%s: lws_serve_http_file failed to complete", 
					__func__
				);				
				return -1; /* error or can't reuse connection: close the socket */
			}

			/*
			 * notice that the sending of the file completes asynchronously,
			 * we'll get a LWS_CALLBACK_HTTP_FILE_COMPLETION callback when
			 * it's done
			*/

			/* if we're on HTTP1.1 or 2.0, will keep the idle connection alive */
			if (lws_http_transaction_completed(wsi)) {
				applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_ERROR, "%s: lws_http_transaction failed to complete", 
					__func__
				);					
				return -1;
			}

	        break;
		}

		default:
			break;
	}

	return 0;
}`

**Comment by lws-team** [comment]
Hm....  dunno if it's your problem but at the end of CALLBACK_HTTP you are calling transaction_completed twice.

**Comment by jonowoodward1986** [comment]
That fixed the problem thank you again :+1:
