### ISSUE TITLE
is wss SSL certificate support .cer　ｒｅｐｌａｃｅ　．ｐｅｍ?

### ISSUE THREAD

**Issue by AmelieFan** [warmcat/libwebsockets#780]
I build a websocket server with libwebsockets. And used wss is OK ,when I config the server SSL　ｗｉｔｈ　libwebsockets-test-server.key.pem　ａｎｄ　libwebsockets-test-server.pem．　Ｎｏｗ　Ｉ　ｗａｎｔ　ｒｅｐｌａｃｅ　ｔｈｅ　ｃｅｒｔｉｆｉｃａｔｅ　ｗｉｔｈ　CA.crt．Ａｎｄ　ｔｈｅ　ｋｅｙ　ｗｉｔｈｉｎ　ｉｔ  ．Ｒｕｎ　ｔｈｅ　ｓｅｒｖｅｒ，　ｉｔ　ｃｒａｓｈ．ｌｏｇ　ｓａｙｓ：[2017/02/08 08:44:18:4086] ERR: problem getting cert 'C:\MSE\Release_2017_02_08\Resource/dahuatech_mymaxprocloud_com.cer' 151441516: error:0906D06C:PEM routines:PEM_read_bio:no start line
[2017/02/08 08:44:18:4086] ERR: Failed to create default vhost
[2017/02/08 08:44:18:4086] ERR: libwebsocket init failed
Ｈｏｗ　ｔｏ　ｓｕｐｐｏｒｔ　．ｃｅｒ　ｆｏｒｍａｔ　ｃｅｒｔｉｆｉｃａｔｅ？
Ｔｈａｎｋｓ！

**Comment by lws-team** [comment]
Well... it doesn't crash.  Openssl api doesn't like what you have given it and gives you an error.

If you have a funny format certificate you need to convert it outside lws to PEM/DER format that OpenSSL wants.

For example libwebsockets.org cert is a .cer file I was given by the official SSL cert provider.  It begins with

```
-----BEGIN CERTIFICATE-----
```

it looks like your .cer file has something else... "no start line".

**Comment by AmelieFan** [comment]
Yes, you are right. Thank you!
