### ISSUE TITLE
Compiling libwebsockets in Visual Studio 2005 

### ISSUE THREAD

**Issue by cesareof** [warmcat/libwebsockets#781]
Trying to build libwebsockets in Windows 7 with Visual Studio 2005. I have used libwebsockets before using an older build, but I needed to rebuild to add SSL support. It seems there have been quite a few changes to libwebsockets since 2015 but I can't seem to get this application to build. What am I doing wrong? 

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Deleting intermediate and output files for project 'ZERO_CHECK', configuration 'Debug|Win32'
1>Checking Build System
1>CMake does not need to re-run because C:/Users/CesareoF/libwebsockets/build/CMakeFiles/generate.stamp is up-to-date.
1>Build log was saved at "file://c:\Users\CesareoF\libwebsockets\build\ZERO_CHECK.dir\Debug\BuildLog.htm"
1>ZERO_CHECK - 0 error(s), 0 warning(s)
2>------ Rebuild All started: Project: zlib_internal, Configuration: Debug Win32 ------
2>Deleting intermediate and output files for project 'zlib_internal', configuration 'Debug|Win32'
2>Building Custom Rule C:/Users/CesareoF/libwebsockets/CMakeLists.txt
2>CMake does not need to re-run because C:\Users\CesareoF\libwebsockets\build\CMakeFiles\generate.stamp is up-to-date.
2>Compiling...
2>zutil.c
2>uncompr.c
2>trees.c
2>inftrees.c
2>inflate.c
2>inffast.c
2>infback.c
2>gzwrite.c
2>gzread.c
2>gzlib.c
2>gzio.c
2>gzclose.c
2>deflate.c
2>crc32.c
2>compress.c
2>adler32.c
2>Generating Code...
2>Creating library...
2>gzio.obj : warning LNK4006: _gzsetparams already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzungetc already defined in gzread.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzwrite already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzprintf already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzputc already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzputs already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzflush already defined in gzwrite.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzrewind already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzeof already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzerror already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzclearerr already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzopen already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzdopen already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzread already defined in gzread.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzgetc already defined in gzread.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzgets already defined in gzread.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gzseek already defined in gzlib.obj; second definition ignored
2>gzio.obj : warning LNK4006: _gztell already defined in gzlib.obj; second definition ignored
2>gzclose.obj : warning LNK4006: _gzclose already defined in gzio.obj; second definition ignored
2>gzclose.obj : warning LNK4221: no public symbols found; archive member will be inaccessible
2>Build log was saved at "file://c:\Users\CesareoF\libwebsockets\build\zlib_internal.dir\Debug\BuildLog.htm"
2>zlib_internal - 0 error(s), 20 warning(s)
3>------ Rebuild All started: Project: websockets, Configuration: Debug Win32 ------
3>Deleting intermediate and output files for project 'websockets', configuration 'Debug|Win32'
3>Building Custom Rule C:/Users/CesareoF/libwebsockets/CMakeLists.txt
3>CMake does not need to re-run because C:\Users\CesareoF\libwebsockets\build\CMakeFiles\generate.stamp is up-to-date.
3>Compiling...
3>gettimeofday.c
3>extension-permessage-deflate.c
3>extension.c
3>server-handshake.c
3>server.c
3>lws-plat-win.c
3>..\lib\lws-plat-win.c(9) : warning C4005: 'DELTA_EPOCH_IN_MICROSECS' : macro redefinition
3>        C:\Users\CesareoF\libwebsockets\win32port\win32helpers\gettimeofday.h(7) : see previous definition of 'DELTA_EPOCH_IN_MICROSECS'
3>..\lib\lws-plat-win.c(234) : error C2143: syntax error : missing ';' before 'type'
3>..\lib\lws-plat-win.c(234) : error C2143: syntax error : missing ';' before 'type'
3>..\lib\lws-plat-win.c(234) : error C2143: syntax error : missing ')' before 'type'
3>..\lib\lws-plat-win.c(234) : error C2143: syntax error : missing ';' before 'type'
3>..\lib\lws-plat-win.c(234) : error C2065: 'eIdx' : undeclared identifier
3>..\lib\lws-plat-win.c(234) : warning C4552: '<' : operator has no effect; expected operator with side-effect
3>..\lib\lws-plat-win.c(234) : error C2059: syntax error : ')'
3>..\lib\lws-plat-win.c(234) : error C2143: syntax error : missing ';' before '{'
3>sha-1.c
3>ssl-client.c
3>..\lib\ssl-client.c(72) : error C2275: 'X509_VERIFY_PARAM' : illegal use of this type as an expression
3>        C:\OpenSSL-Win32\include\openssl/x509_vfy.h(177) : see declaration of 'X509_VERIFY_PARAM'
3>..\lib\ssl-client.c(72) : error C2065: 'param' : undeclared identifier
3>..\lib\ssl-client.c(76) : warning C4047: '=' : 'int' differs in levels of indirection from 'X509_VERIFY_PARAM *'
3>..\lib\ssl-client.c(78) : warning C4047: 'function' : 'X509_VERIFY_PARAM *' differs in levels of indirection from 'int'
3>..\lib\ssl-client.c(78) : warning C4024: 'X509_VERIFY_PARAM_set_hostflags' : different types for formal and actual parameter 1
3>..\lib\ssl-client.c(80) : warning C4047: 'function' : 'X509_VERIFY_PARAM *' differs in levels of indirection from 'int'
3>..\lib\ssl-client.c(80) : warning C4024: 'X509_VERIFY_PARAM_set1_host' : different types for formal and actual parameter 1
3>ssl-server.c
3>ssl.c
3>client-parser.c
3>client-handshake.c
3>client.c
3>header.c
3>alloc.c
3>context.c
3>parsers.c
3>output.c
3>pollfd.c
3>service.c
3>..\lib\service.c(742) : error C2143: syntax error : missing ';' before 'type'
3>..\lib\service.c(743) : error C2065: 'vh' : undeclared identifier
3>..\lib\service.c(744) : error C2223: left of '->count_protocols' must point to struct/union
3>..\lib\service.c(745) : error C2223: left of '->same_vh_protocol_list' must point to struct/union
3>..\lib\service.c(765) : error C2223: left of '->vhost_next' must point to struct/union
3>Generating Code...
3>Compiling...
3>libwebsockets.c
3>handshake.c
3>base64-decode.c
3>Generating Code...
3>Build log was saved at "file://c:\Users\CesareoF\libwebsockets\build\websockets.dir\Debug\BuildLog.htm"
3>websockets - 14 error(s), 7 warning(s)
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

**Comment by INRIX-joel-winarske** [comment]
It builds fine for me with VS2015 Community edition, as does libuv.  I have the latest MSFT updates installed.


Only one change was required for lwsws -> comment out the exit() after "Sorry Windows doesn't support fork()."

________________________________

**Comment by cesareof** [comment]
Yeah I was curious if there was an issue with Visual Studio 2005, I know it is an older IDE but it is the one that I use. So I was hoping there was a simple fix for this. 

Or any chance there are pre-built libraries available that I can use? So I don't have to try and build libwebsockets from source.

**Comment by jwinarske** [comment]
I'm not entirely certain the lib/dll versions are compatible between VS2005/VS2015.  Have you done this for other things?

If there was no compatibility issue, you still have the issue of building the versions of libuv and openssl I'm using.  So I think you'd be better off installing VS2015 Community edition (Free) and build everything yourself.

I used VS2005 for lots and lots of WinCE/Windows Mobile work.  It gives me the shivers just thinking about it ;)

**Comment by lws-team** [comment]
I'm glad it worked out OK.  I attempted to provide binaries from Appveyor, I was able to build, collate and zip them as part of the build process OK , but unable to get them recognized as a "build product" so you can reach them from outside.  If anyone else would like them and more knowledgeable about appveyor than me, the problem is like this

```
...
7z a lws.zip %APPVEYOR_BUILD_FOLDER%\build\lib\Release\websockets.lib %APPVEYOR_BUILD_FOLDER%\build\lib\Release\websockets.exp %APPVEYOR_BUILD_FOLDER%\build\bin\Release\websockets.dll %APPVEYOR_BUILD_FOLDER%\lib\libwebsockets.h  %APPVEYOR_BUILD_FOLDER%\build\lws_config.h  %APPVEYOR_BUILD_FOLDER%\build\bin\Release\*.exe
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
Scanning the drive:
14 files, 1681711 bytes (1643 KiB)
Creating archive: lws.zip
Items to compress: 14
Files read from disk: 14
Archive size: 839808 bytes (821 KiB)
Everything is Ok
Discovering tests...OK
Collecting artifacts...
**No artifacts found matching 'lws.zip' path**
Updating build cache...
Cache 'C:\OpenSSL-Win32' - Updated
Build success
```

Our appveyor.yml is here

https://github.com/warmcat/libwebsockets/blob/master/appveyor.yml
