### ISSUE TITLE
Unable to login with copied sqlite file

### ISSUE THREAD

**Issue by d30jeff** [warmcat/libwebsockets#782]
I'm having problems logging in with the correct credentials stored in lws.sessions.sqlite3 file that was generated and copied over from a different machine.

Is there any workaround for this?

Thanks

**Comment by lws-team** [comment]
I can imagine either permissions, so the user: group or rwx are wrong, or selinux state of the file.

Or, maybe different sqlite3 versions cannot read each other's internal file format.  In which case dump the file to ascii and use sqlite3 tools to execute the ascii dump back into a new sqlite3 file using the same version of sqlite3 that will read it.

**Comment by d30jeff** [comment]
Is it possible to keep the session alive?
I suspect that the reason that this happens has to do with the session expiring,
as I am able to login for about a day with the freshly copied over sqlite3 file.

Sorry for forgetting to mention that earlier.

**Comment by lws-team** [comment]
The credentials themselves don't expire.... a session might expire.

What exactly is happening, credentials are no longer accepted for login?  Something else?

**Comment by d30jeff** [comment]
Yes, credentials are no longer accepted for login.

ie:
We are able to login for a day or so, and then we are not able to login anymore.

**Comment by d30jeff** [comment]
Hi,
today it happened again.

I was able to login on my laptop just fine yesterday, today when I tried to login again, it doesn't seem to work.

    lwsws[4037]: lws_spa_create: Created SPA 0xbc0b40
    lwsws[4037]: user/password no good swaguser
    lwsws[4037]: lws_spa_destroy: destroy spa 0xbc0b40

The size of the `lws.sessions.sqlite3` has not changed but for some reason, when I try to open it with sqlite3 and do `select * from users` command; it's empty.

**Comment by accounts01** [comment]
Hi :) I also have this issue. I can login for a day or two and then all of sudden I can't login anymore and get wrong password errors. I figured it was some sort of salt error but I haven't had time to look more into it. For the moment my fix has been to set auth-mask to 0 on all mounts but this is obviously a bad and temporary solution haha. Any help if either of you guys figures this out would be much appreciated. Thanks! :)

**Comment by lws-team** [comment]
The only ways I can see for users to get deleted is 

 - he asked for it via the form
 
 - that users that did not complete the email verification link (setting verified to 100 in the entry in the users table) get cleaned out after 24h.

I'm not seeing any empty users table here, either on libwebsockets.org/lwsgs or on my local machine... the old accounts are still there.

If you can remember your credentials, can you try login on https://libwebsockets.org/lwsgs ?

**Comment by lws-team** [comment]
It doesn't seem to be related to cookie timeout either.

I set the cookie lifetime to 30s, I confirmed it expired by reloading the page, and I could log back in again as the same user in the same browser window after expiry.

So I need more information how to reproduce... if users are actually disappearing it really sounds like the email verification never happened.

**Comment by accounts01** [comment]
It was the email verification for me. I never realized it was mandatory. Solved! Thanks!

**Comment by lws-team** [comment]
Thanks for letting me know.

I'll close this but please continue here if more related things to discuss.
