### ISSUE TITLE
undefined reference to `ERR_error_string_n'

### ISSUE THREAD

**Issue by Fallsleep** [warmcat/libwebsockets#783]
I built the dll with MinGW,then I got the "undefined reference to" error  when linking.
The error is like following:
[ 61%] Linking C shared library bin/libwebsockets.dll
"/C/Program Files/CMake/bin/cmake.exe" -E remove -f CMakeFiles/websockets_shared.dir/objects.a
/C/MinGW/bin/ar.exe cr CMakeFiles/websockets_shared.dir/objects.a @CMakeFiles/websockets_shared.dir/objects1.rsp
/C/MinGW/bin/gcc.exe -Wall -fvisibility=hidden -D__USE_MINGW_ANSI_STDIO -O3 -DNDEBUG -shared -o bin/libwebsockets.dll -Wl,--out-implib,lib/libwebsockets.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/websockets_shared.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/websockets_shared.dir/linklibs.rsp
CMakeFiles/websockets_shared.dir/objects.a(ssl.c.obj):ssl.c:(.text+0x210): undefined reference to `ERR_error_string_n'
...
CMakeFiles/websockets_shared.dir/objects.a(ssl-client.c.obj):ssl-client.c:(.text+0x98b): undefined reference to `ERR_error_string'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [bin/libwebsockets.dll] Error 1
make[2]: Leaving directory `/d/libwebsockets-master/build'
make[1]: *** [CMakeFiles/websockets_shared.dir/all] Error 2
make[1]: Leaving directory `/d/libwebsockets-master/build'
make: *** [all] Error 2

What should I do with it?I'm newly with MinGW,cmake,make.

MinGW was installed in C:\MinGW.
Openssl was installed in C:\OpenSSL-Win32\,and was download from http://slproweb.com/products/Win32OpenSSL.html,1.0.2d .

**Comment by lws-team** [comment]
https://wiki.openssl.org/index.php/Manual:ERR_error_string(3) says it is in all versions of openssl.

Are you linking against the equivalent of libssl.a and libcrypto.a, or .so, or .dll/.lib or however it works.... the actual openssl libs?  I don't see them mentioned.

**Comment by Fallsleep** [comment]
Openssl 1.0.2.d I installed from http://slproweb.com/products/Win32OpenSSL.html only supplied libeay32.a and ssleay32.a,there's no libssl.a or libcrypto.a given.Should I make the openssl with the offical source code by myself?

┭┮﹏┭┮

OK!
I just got the newliest package 1.1.0d from http://slproweb.com/products/Win32OpenSSL.html ,it given libssl-1_1.a and libcrypto-1_1.a files.

But I still failed.I'm newly with MinGW,cmake,make.How to link against  libssl.a and libcrypto.a?

**Comment by lws-team** [comment]
I am sorry, I don't use mingw or windows, I have little idea.

There is some contributed info here

**Comment by Fallsleep** [comment]
After a few times trying, I got success when I change -DLWS_OPENSSL_LIBRARIES="C:/OpenSSL-Win32/libssl32.dll;C:/OpenSSL-Win32/ssleay32.dll;" to  -DLWS_OPENSSL_LIBRARIES="C:/OpenSSL-Win32/libeay32.dll;C:/OpenSSL-Win32/libssl32.dll;C:/OpenSSL-Win32/ssleay32.dll;C:/OpenSSL-Win32/libcrypto-1_1.dll;C:/OpenSSL-Win32/libssl-1_1.dll;".

I think it need to use the .a but .dll in the MinGW.

**Comment by lws-team** [comment]
Yes... I was just guessing about .a because I saw a .a in your existing link line.

It's solved then?

**Comment by Fallsleep** [comment]
I built the libwebsockets.dll successly,and now I'm writing the service pragram.Hope it work well.

**Comment by lws-team** [comment]
OK good luck.
