### ISSUE TITLE
Need better documentation of SSL certificate file formar

### ISSUE THREAD

**Issue by ngoel17** [warmcat/libwebsockets#784]
Documentation examples show the host configuration file (snippet posted below) as follows.
            "port": "443",
            "interface": "eth0",  # optional
            "host-ssl-key": "/etc/pki/tls/private/warmcat.com.key",  # if given enable ssl
            "host-ssl-cert": "/etc/pki/tls/certs/warmcat.com.crt",
            "host-ssl-ca": "/etc/pki/tls/certs/warmcat.com.cer",

  however there is no example I could find for the warmcat.com.crt file itself. It appears that this file needs to be in JSON format. I have a file that has 
-----BEGIN CERTIFICATE-----
in the top and 
-----END CERTIFICATE-----
in the bottom
   and with this kind of file, I am getting a syntax error:
lwsts[28480]: lwsws_pron/conf.d/cert3.pem(1): parsing error -2: No opening '{'

  Your help is appreciated in clarifying what this certificate file should look like.

**Comment by lws-team** [comment]
Eh?... no... the certs are just normal PEM.

However lws will iterate through every file in the .../conf.d/ dir parsing it as JSON.  Apache and other daemons do the same expecting only their config files in their .d dirs.  You can't just stick ancillary files in there as well.

Put your certs + keys somewhere else, even the parent dir like /etc/lwsws, or better /etc/pki/tls.. etc that uses directory permissions to hide your key.
