### ISSUE TITLE
How can i get&use the receive message?

### ISSUE THREAD

**Issue by MonkeyMajik** [warmcat/libwebsockets#787]
Hi
I have a problem on using the get message 

Like i define a struct session_data ,it contain a pointer which i define pEventInf ,this point use to operate the receive message,but how can i init this session_data? how to init the pointer CWebScoketEvent*?

Or how to receive a message and put it to the other class's fuction? 

Best regards 

struct session_data 
{
	int connection_flag	;
	int	destroy_flag;
	CWebScoketEvent* pEventInf;
};

int CEasyWebsocket::ws_service_callback(struct lws *wsi,enum lws_callback_reasons reason, void *user,void *in, size_t len)
{
	struct session_data *pss = (struct session_data *)user;
	switch (reason) {

	case LWS_CALLBACK_CLIENT_ESTABLISHED:

		break;

	case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
		break;

	case LWS_CALLBACK_CLOSED:
		break;

	case LWS_CALLBACK_CLIENT_RECEIVE:
		{
			pss->pEventInf->OnReceiveMsg(NULL,(char*)in);
		}
		break;
	default:
		break;
	}

	return 0;
}

**Comment by lws-team** [comment]
I am not really certain what you are asking, but from the general shape of it, you should look at the `user` member of the context create info struct

```
	void *user;
	/**< CONTEXT: optional user pointer that can be recovered via the context
 *		pointer using lws_context_user */
```

lws ignores this, so you can point it to some master object of your class.

In the callbacks, you can recover that pointer from any wsi with

```
 void *my_user = lws_context_user(lws_get_context(wsi));
```

This lets you connect the callback code to an object from outside.

For how to track instantiations, connections are coming randomly to lws.  You need to hook things like CLIENT_ESTABLISHED and _CLOSE and create and destroy instances of your per-connection class in there.  You can store a pointer to your per-connection object in the pss.

**Comment by MonkeyMajik** [comment]
got it 
thanks!
