### ISSUE TITLE
WSI loses handle?

### ISSUE THREAD

**Issue by iUltimateLP** [warmcat/libwebsockets#791]
Hey there, 
I have a problem with libwebsockets, which is pretty strange and I couldn't track it down myself..
I have a function called **WriteToServer** which takes the wsi and a FString (the string type of Unreal). I do some conversion and then simple send the message using lws_write. Somehow this works for some time, but then suddenly (while looking at the debugger), the wsi variable doesn't have its real address anymore, but **0xdddddddddddddddd**, and Visual Studio shows an access violation. The WriteToServer function is called when I click an UI button, while the lws_service runs in another thread. The wsi is a global variable in my class.

The function:
```cpp
int UWebSocketClient::WriteToServer(struct lws* wsi, FString ToWrite)
{
	unsigned char* buffer = new unsigned char[LWS_PRE + ToWrite.Len()];

	// The TCHAR_TO_UTF8 is just for the correct conversion of Unreal's string
	memset(&buffer[LWS_PRE], 0, ToWrite.Len());
	strncpy((char*)buffer + LWS_PRE, TCHAR_TO_UTF8(*ToWrite), ToWrite.Len());

	// The access violation points to here! wsi is 0xdddddddddddddddd then
	int result = lws_write(wsi, &buffer[LWS_PRE], ToWrite.Len(), LWS_WRITE_TEXT);

	delete[] buffer;

	return result;
}
```

How I call it:
```cpp
int UWebSocketClient::Send(FString Content)
{
	if (wsi && !ConnectionWorker->IsThreadFinished())
	{
		return WriteToServer(wsi, Content);
	}

	return -1;
}
```
What could be the problem? The length of the message clearly isn't, I tested that.
Thanks for help!

**Comment by lws-team** [comment]
Well there are three problems.

1) You don't seem to take any care about lws logs
2) The connection can close any time.  Just like on a phone call, your conversation partner can hang up any time. It'll call one or another close callback when it does and after that the wsi is deleted.
3) The tcp internet is not some endless sink for whatever you want to pour into it.  When the tcp window is full, you cannot send anything more until some acks come from the remote peer.  At that time, the connection becomes writeable again.

So you need to look at the example apps and follow the scheme

 - ask for a callback when the connection becomes writable if you have something to write

 - ONLY call lws_write from the writable callback ONE TIME pr callback.

**Comment by iUltimateLP** [comment]
I'm sorry, I shorted down the code a lot:
  1. The lws logs don't tell anything, I have a custom hook up for them
  2. I have a breakpoint on the CONNECTION_CLOSED_CALLBACK, but that doesn't trigger, so the connection isn't closed, as I think

So, instead of just writing, I call lws_callback_on_writable(), and then send my message from the protocol callback?

**Comment by lws-team** [comment]
Yeah.  The most likely thing is you are writing something , lws is told the kernel won't accept all of it, lws starts to buffer it and send as the connection becomes writable, you decide to send something new and lws closes the connection since it's already working through what it couldn't send from last time.

That will get you a particular log, so you should check the logging carefully.

Look at the mirror protocol in the test server and follow that logic.

**Comment by iUltimateLP** [comment]
Allright, done it this way, but I think the problem was more related to Unreal, which garbage-collected my object somehow, but thanks!

**Comment by lws-team** [comment]
If something else didn't garbage collect it, if you weren't following the above method it's anyway broken.

**Comment by iUltimateLP** [comment]
Yup, but now I fixed both problems, and I now only write the message when the WRITEABLE reason in the callback is fired.
