### ISSUE TITLE
Set cache-control http header

### ISSUE THREAD

**Issue by louisbraun** [warmcat/libwebsockets#795]
Hi,

maybe a stupid question, but nevertheless: i use the callback_http just to serve the necessary files needed for my javascript app. Some of the files don't have to be cached by the webbrowser, but others like images should be cached. 

Adding headers via "other_headers" works fine, but i noticed that the header "cache-control: no-store" is set automatically when using lws_serve_http_file. When i add another "cache-control" header with different settings, the response has both headers. 

Is there a way to prevent that the first cache-control header is set? Or is the correct way to ask lws to set this header using my values?

Thx in advance...cheers Louis

**Comment by lws-team** [comment]
You can manage lws built-in cache control using mounts.  From README.lwsws.md

```
Cache policy of the files in the mount can also be set. If no options are given, the content is marked uncacheable.

           {
            "mountpoint": "/",
            "origin": "file:///var/www/mysite.com",
            "cache-max-age": "60",      # seconds
            "cache-reuse": "1",         # allow reuse at client at all
            "cache-revalidate": "1",    # check it with server each time
            "cache-intermediaries": "1" # allow intermediary caches to hold
           }
```

The corresponding entries here exist in the mount struct.

So the idea would be place your assets to be cached in a particular place in the url namespace and have the mount for that enable caching.

**Comment by louisbraun** [comment]
Hi,

thx for the quick answer...i'll give that a try asap.

Btw: thx for this great piece of software :-)

Cheers Louis

**Comment by louisbraun** [comment]
Hi,

just to be sure: you suggest to provide a list of mounts to lws_context_creation_info by passing the "const struct lws_http_mount *mounts" to this struct? In your documentation you write "VHOST: optional linked list of mounts for this vhost". I do not use vhosts, just a single server. Is this possible then too? And what exactly is meant by "linked list of mounts"? Is it just an array of mount structs with a NULL termination entry? Do you may be have some kind of a code example? :-)

Cheers Louis

**Comment by lws-team** [comment]
There's a nice example in the tree...

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L106

When you don't explicitly make your own vhosts, lws creates a default vhost from the same info after creating the context.  Under those condition then, the same info first creates the context and then the vhost... both classes of members are active.

**Comment by louisbraun** [comment]
Ok, found some time to test it...works fine :-)

Issue solved...thx a lot!

Cheers Louis

**Comment by horchi** [comment]
I have a similar problem, I'm looking for a way to set 'no-cache' by using the mount. I tried all combinations of the four cache options without luck.

**Comment by horchi** [comment]
i hope the pull request arrived, never created one on github before
