### ISSUE TITLE
Receive issue

### ISSUE THREAD

**Issue by MonkeyMajik** [warmcat/libwebsockets#798]
Hi
I receive lots of message from server in a short time . Then i found some of them were connected together.So which founction can i use to split these messages?
like:
server send first :"123"
                   seccond:"2234"
                   third:"3356"
                    ......................(these message send to client in a very short time)
client receive  first :"123223"
                       second"43356"
So how can i use to split these messages  like:
client receive first:"123"
                      second"2234"
                      third:"3356"

**Comment by lws-team** [comment]
... when you say, "message", do you mean "ws message"?  Or "ws fragment"?

If you want a message boundary, send ws messages.

You can use

```
/**
 * lws_is_final_fragment() - tests if last part of ws message
 * \param wsi: lws connection
 */
LWS_VISIBLE LWS_EXTERN int
lws_is_final_fragment(struct lws *wsi);
```

To find put if the fragment you received is the last part of a message or not.

**Comment by MonkeyMajik** [comment]
Got it thanks very much
