### ISSUE TITLE
libwebsocket_write(): Unable to spill ext

### ISSUE THREAD

**Issue by chrismeyersfsu** [warmcat/libwebsockets#8]
I am getting the following printout error when I call libwebwsocket_write() for the first time.

[1374954782:4840] ERR: Unable to spill ext 7669 vs 5792

From tracing the code a little the error feels like I am trying to write too much in a message. However, i didn't think there was a limit on the message size.

Can you clue me into the meaning of the "unable to spill ext" error?

**Comment by warmcat** [comment]
It meant that the extension didn't accept to send the amount you asked.  Why that is, is something the extension decided or had forced on it.
