### ISSUE TITLE
lws_ssl_context_destroy free EVP table in OpenSSL and prevents further usage of OpenSSL

### ISSUE THREAD

**Issue by PoltoS** [warmcat/libwebsockets#801]
Why to do EVP_cleanup on contex destroy (lws_ssl_context_destroy)?
https://github.com/warmcat/libwebsockets/blob/master/lib/ssl.c#L780

When I destroy context on SSL connection error, EVP_cleanup is called and other threads in my s/w can not use OpenSSL anymore due to digests/ciphers table cleaned up.

I have OPENSSL_VERSION_NUMBER  0x1000207fL.

**Comment by lws-team** [comment]
Older OpenSSL is just not very good at more than one thing in the process wanting to use it.

Recently they added extra APIs to allow it.

If you want to suggest a patch making it conditional on the OpenSSL version that won't break older guys that need this, I can give it a try.

**Comment by PoltoS** [comment]
Ok, will have a look. We are using LWS on many platforms and usually use libs from distro, so fixing it in git will not solve my problem. So either I compile own LWS distro or upgrade OpenSSL. I think I'll just live with that.

**Comment by lws-team** [comment]
Well... it will solve your problem eventually, if it's capable of solving it.  Since distro packages are ultimately coming from our git.

**Comment by PoltoS** [comment]
It takes pretty long time and some of our platforms are too old, so anyway we will need to either use own build of lws or own build of openssl. will check what is easier and will make a patch in LWS if needed.

**Comment by lws-team** [comment]
If that happens I will be happy to try your patch.
