### ISSUE TITLE
master: context.c memory leaks removed

### ISSUE THREAD

**Issue by namowen** [warmcat/libwebsockets#804]
If LWS_SERVER_OPTION_EXPLICIT_VHOSTS is set, specific memory is malloc'd for protocols, but never free'd anymore.
This patch solve this. Memory leaks were found w/ valgrind (and removal tests verified w/ valgrind).
Tested with:
1. w/o explicit lws_create_vhost (so internal default vhost is created)
2. w/ explicit lws_create_vhost
Note: not tested with plugins
###########################################
```
diff --git a/lib/context.c b/lib/context.c
index c72f473..d35b469 100644
--- a/lib/context.c
+++ b/lib/context.c
@@ -405,8 +405,10 @@
 
 	if (info->options & LWS_SERVER_OPTION_EXPLICIT_VHOSTS)
 		vh->protocols = lwsp;
-	else
+	else {
 		vh->protocols = info->protocols;
+		free(lwsp);
+	}
 
 	vh->same_vh_protocol_list = (struct lws **)
 			lws_zalloc(sizeof(struct lws *) * vh->count_protocols);
@@ -1033,6 +1035,11 @@
 #ifdef LWS_WITH_PLUGINS
 		if (context->plugin_list)
 			lws_free((void *)vh->protocols);
+#else
+		if (vh->options & LWS_SERVER_OPTION_EXPLICIT_VHOSTS)
+			lws_free((void *)vh->protocols);
+#endif
+#ifdef LWS_WITH_PLUGINS
 #ifndef LWS_NO_EXTENSIONS
 		if (context->plugin_extension_count)
 			lws_free((void *)vh->extensions);
```

**Comment by lws-team** [comment]
Wow... this is code I wrote for ESP32 support less than 24h before your issue ^^  thanks for the patch, it's pushed.
