### ISSUE TITLE
how can I get more info when lws_create_context returns NULL?

### ISSUE THREAD

**Issue by Fallsleep** [warmcat/libwebsockets#808]
I wrote my Win32 Service with ALT, and I start a thread to run the libwebsocet server.

But when I called `context = lws_create_context(&info);`, I got NULL.

How can I get more info about it?

**Comment by Fallsleep** [comment]
OK.I found out the problem, I removed the http-only protocol from the protocols .

After prepend it into protocols, I got lws_create_context start.

**Comment by lws-team** [comment]
OK... it's good to look at lws logging.  You can make it very verbose if you build in DEBUG mode (see README.build.md) and select 65535 as the mask, eg, -d 65535 on the test server.
