### ISSUE TITLE
Change to use SSL_shutdown appears to have stopped generation of the LWS_CALLBACK_WSI_DESTROY callback

### ISSUE THREAD

**Issue by skyhisi** [warmcat/libwebsockets#809]
The commit 052a685 which changed to use `SSL_shutdown` appears to have changed the callback sequence such that `LWS_CALLBACK_WSI_DESTROY` isn't called when closing an HTTP client down.

I'm still investigating, so I'm not sure why it breaks yet.

Previously I would get the sequence (with b8034bb):
```
LWS_CALLBACK_WSI_CREATE
...
LWS_CALLBACK_COMPLETED_CLIENT_HTTP
LWS_CALLBACK_RECEIVE_CLIENT_HTTP
LWS_CALLBACK_CLOSED_CLIENT_HTTP
LWS_CALLBACK_WSI_DESTROY
```

Now I'm getting (with 052a685):
```
LWS_CALLBACK_WSI_CREATE
...
LWS_CALLBACK_COMPLETED_CLIENT_HTTP
LWS_CALLBACK_RECEIVE_CLIENT_HTTP
LWS_CALLBACK_CLOSED_CLIENT_HTTP
```

**Comment by skyhisi** [comment]
I think the socket needs closing once SSL_shutdown has completed. Also, SSL_shutdown may indicate it needs to be called again.

Possible fix:

```diff
diff --git a/lib/libwebsockets.c b/lib/libwebsockets.c                                                                                      
index 225efa9..dcb6967 100755
--- a/lib/libwebsockets.c
+++ b/lib/libwebsockets.c
@@ -437,7 +437,13 @@ just_kill_connection:
            !wsi->socket_is_permanently_unusable) {
 #ifdef LWS_OPENSSL_SUPPORT
                if (lws_is_ssl(wsi) && wsi->ssl)
+               {
+                       lwsl_info("%s: shutting down SSL connection: %p (ssl %p, sock %d, state %d)\n", __func__, wsi, wsi->ssl, (int)(long)wsi->sock, wsi->state);
                        n = SSL_shutdown(wsi->ssl);
+                       if (n == 0) /* Complete bidirectional SSL shutdown */
+                               n = SSL_shutdown(wsi->ssl);
+                       n = shutdown(wsi->sock, SHUT_WR);
+               }
                else
 #endif
                {
```

**Comment by lws-team** [comment]
Sound good, although can it repeatedly ask to go again?  I pushed it on master.

**Comment by skyhisi** [comment]
I don't think the `if` needs to be a `while`/`for`. I think the SSL_shutdown is just a two step process, on the first call if it has received a shutdown from the remote end, it'll return 1, otherwise it'll send a shutdown and return 0. If you get 0 then calling it again will wait for the remote end to send the shutdown reply. At least that's how I've interpreted the [man page for SSL_shutdown](https://www.openssl.org/docs/man1.0.1/ssl/SSL_shutdown.html).

Thanks,
Silas
