### ISSUE TITLE
SIGSEGV on lws_header_table_attach loop

### ISSUE THREAD

**Issue by jjiego** [warmcat/libwebsockets#815]
Hi, libwebsockets team.
I am using libwebsockets 1.7-stable version.
I got SIGSEGV from lws_header_table_attach() of parser.c 

backtraces are below.

(gdb)bt full
#0  lws_header_table_attach (wsi=wsi@entry=0xa9bd0598) at /usr/src/debug/libwebsockets-1.7.9/lib/parsers.c:120
        context = 0xa9d004a0
        pt = <optimized out>
        pa = {fd = -1440754156, events = 0, prev_events = -1440754208}
        pwsi = 0x12d
        n = <optimized out>
#1  0xb58d54c2 in lws_client_connect_via_info (i=0xaa1fd614) at /usr/src/debug/libwebsockets-1.7.9/lib/client-handshake.c:423
        wsi = 0xa9bd0598
        v = <optimized out>

`
int LWS_WARN_UNUSED_RESULT
lws_header_table_attach(struct lws *wsi)
{
	struct lws_context *context = wsi->context;
	struct lws_context_per_thread *pt = &context->pt[(int)wsi->tsi];
	struct lws_pollargs pa;
	struct lws **pwsi;
	int n;

	lwsl_info("%s: wsi %p: ah %p (tsi %d)\n", __func__, (void *)wsi,
		 (void *)wsi->u.hdr.ah, wsi->tsi);

	/* if we are already bound to one, just clear it down */
	if (wsi->u.hdr.ah) {
		lwsl_info("cleardown\n");
		goto reset;
	}

	lws_pt_lock(pt);
	pwsi = &pt->ah_wait_list;
	while (*pwsi) {
		if (*pwsi == wsi) {
			/* if already waiting on list, if no new ah just ret */
			if (pt->ah_count_in_use ==
			    context->max_http_header_pool) {
				lwsl_err("ah wl denied\n");
				goto bail;
			}
			/* new ah.... remove ourselves from waiting list */
			*pwsi = wsi->u.hdr.ah_wait_list; /* set our prev to our next */
			wsi->u.hdr.ah_wait_list = NULL; /* no next any more */
			pt->ah_wait_list_length--;
			break;
		}
		pwsi = &(*pwsi)->u.hdr.ah_wait_list; // 120 lines of parser.c
	}
`

I am curious the last phrase is safe.
Could you please check the phrase of 120 line is stable ?

**Comment by lws-team** [comment]
It looks OK... it's part of a linked-list of guys waiting for an ah.

Can you give me a clue how to reproduce the problem?  I would suggest trying master but I think no big changes in this area that I can remember.

**Comment by jjiego** [comment]
Unfortunately, there are no other clues...
I am just wondering 

		pwsi = &(*pwsi)->u.hdr.ah_wait_list; <- 

that RIGHT value is always set with valid data or pointer.

**Comment by lws-team** [comment]
If it crashes, you are right to wonder ^^

Unless I miss the point, if the linked-list is valid this is OK.  Instead of walking the list with a pointer, it's walking the list with a pointer to the last forward pointer.  That has the advantage we can change the guy pointing at us as well as know who "we" are.

That's why I am asking for a way to reproduce it, for example spam connections at test server using ab etc.

**Comment by lws-team** [comment]
Well, if you have more info how to reproduce let me know.
