### ISSUE TITLE
2 wsi creating on single connection on firefox

### ISSUE THREAD

**Issue by mradul17** [warmcat/libwebsockets#817]
I am using window and server is running on ubuntu
my javascript is
```
<html> <head>
<script>
         function WebSocketTest()
         {
               var ws = new WebSocket("ws://localhost:7681");
               ws.onopen = function()
               {
                  ws.send("EOS");
                  console.log("Message is sent...");
               };
				
               ws.onmessage = function (evt) 
               { 
                  var received_msg = evt.data;
                  console.log("Message is received...");
                  console.log(received_msg);
                 
               };
               ws.onclose = function()
               { 
                  console.log("Connection is closed..."); 
               };
            }
            window.onload = WebSocketTest;
      </script>	
   </head><body></body></html>
```

now when i run my html page in Firefox, on server side two wsi is creating but not on chrome
lwsts[25981]: Accepted wsi 0x7f23e0001ec0 to context 0x6103d210, tsi 0
lwsts[25981]: Accepted wsi 0x7f23e00135e0 to context 0x6103d210, tsi 0
lwsts[25981]: lws_server_socket_service: wsi 0x7f23e00135e0 read 0
lwsts[25981]: lws_header_table_detach: wsi 0x7f23e00135e0: ah held 6s, ah.rxpos 0, ah.rxlen 0, mode/state 0 4,wsi->more_rx_waiting 0

When i used firefox in ubuntu.. only single wsi is creating.. 
is this my server code problem or firefox problem

**Comment by lws-team** [comment]
I dunno, but it doesn't sound like my problem.

Use the 'developer tools' on each browser to see what it thinks is happening.

How many wsi is coming is too much of a blunt instrument to understand anything.

**Comment by lws-team** [comment]
There's nothing related to lws about this afaics.  If it becomes an lws issue feel free to continue with more info.
