### ISSUE TITLE
Change user-specific data after connection creation

### ISSUE THREAD

**Issue by lukasgeyer** [warmcat/libwebsockets#819]
Currently it seems not to be possible to change the user-specific data after a context or connection has been created. 

The use case for having such support is a C++ wrapper, where the lifetime of the object wrapping the `wsi` differs from the lifetime of the `wsi` itself. The user callback which acts as dispatching function to the wrapping object therefore needs a predicate whether the object wrapping the `wsi` still exists. Currently the user-specific data (which contains a pointer to the wrapping object) cannot be used as that predicate, as it cannot be modified once it has been created (in this case in the destructor of the wrapping object).

Possible implementation:

```
diff --git a/lib/libwebsockets.c b/lib/libwebsockets.c
index 16a9f5a..1a1110f 100755
--- a/lib/libwebsockets.c
+++ b/lib/libwebsockets.c
@@ -1284,6 +1284,12 @@ lws_wsi_user(struct lws *wsi)
        return wsi->user_space;
 }

+LWS_VISIBLE LWS_EXTERN void 
+lws_wsi_set_user(struct lws *wsi, void *data)
+{
+       wsi->user_space = data;
+}
+
 LWS_VISIBLE LWS_EXTERN struct lws *
 lws_get_parent(const struct lws *wsi)
 {
diff --git a/lib/libwebsockets.h b/lib/libwebsockets.h
index 2aed309..45f0f3e 100644
--- a/lib/libwebsockets.h
+++ b/lib/libwebsockets.h
@@ -3683,6 +3683,14 @@ LWS_VISIBLE LWS_EXTERN void *
 lws_wsi_user(struct lws *wsi);

 /**
+ * lws_wsi_set_user() - set the user data associated with the connection
+ * \param wsi: lws connection
+ * \param user: user data
+ */
+LWS_VISIBLE LWS_EXTERN void 
+lws_wsi_set_user(struct lws *wsi, void *user);
+
+/**
  * lws_parse_uri:      cut up prot:/ads:port/path into pieces
  *                     Notice it does so by dropping '\0' into input string
  *                     and the leading / on the path is consequently lost
```

I can also provide a PR if requested.

**Comment by lws-team** [comment]
I pushed it with some changes

 - the original patch didn't build (void * return)
 - api name changed to `lws_set_wsi_user`
 - added runtime check that user_space was originally set externally
 - added docs explaining this can only be used on client wsi who had user_space set externally originally.

**Comment by lukasgeyer** [comment]
> added runtime check that user_space was originally set externally

If the user-specific data is set internally (and thus cannot be modified externally), how do I set connection-specific user-data for an incoming connection then?

**Comment by lukasgeyer** [comment]
`lws_protocols.per_session_data_size`
