### ISSUE TITLE
Unable to clone repository from libwebsockets.org

### ISSUE THREAD

**Issue by sudeepb02** [warmcat/libwebsockets#821]
The clone url https://libwebsockets.org/git for libwebsockets is not working. 
Error is 
`fatal: unable to connect to git.libwebsockets.org:
git.libwebsockets.org[0: 163.172.24.82]: errno=Connection timed out
`
However cloning and building the source from github works perfectly fine.

**Comment by lws-team** [comment]
Thanks for letting me know, it's fixed.

**Comment by sudeepb02** [comment]
Great! 👍

**Comment by tesar27** [comment]
No, it is still no fixed

**Comment by lws-team** [comment]
Can you access https://libwebsockets.org itself in your browser?  Or, eg, wget if it's a remote server?

**Comment by deviantfero** [comment]
same here, can't connect to git.libwebsockets.org, any fix for this

**Comment by lws-team** [comment]
Just use libwebsockets.org

```
$ git clone https://libwebsockets.org/repo/libwebsockets
Cloning into 'libwebsockets'...
remote: Enumerating objects: 26681, done.
remote: Counting objects: 100% (26681/26681), done.
remote: Compressing objects: 100% (6029/6029), done.
remote: Total 26681 (delta 20883), reused 26134 (delta 20484)
Receiving objects: 100% (26681/26681), 14.23 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (20883/20883), done.
$
```

**Comment by deviantfero** [comment]
Thank you for your quick response, I'll fix up my scripts!

**Comment by lws-team** [comment]
I just noticed you're using git://... the issue is originally about https:// ... I moved server a few months ago and forgot to open the port for that :-)  that's also fixed now... but https:// is better since it's secure and on :443

**Comment by deviantfero** [comment]
oh, thanks! good to hear it works already, I'll keep on using https:// from now on.

**Comment by Hajto** [comment]
```
 ~/Projects  git clone https://libwebsockets.org/repo/libwebsockets
Cloning into 'libwebsockets'...
fatal: unable to access 'https://libwebsockets.org/repo/libwebsockets/': Could not resolve host: libwebsockets.org
```

**Comment by lws-team** [comment]
@Hajto Thanks for letting me know, it was just the DNSSEC signatures needed rotating, I have done it

https://dnssec-analyzer.verisignlabs.com/libwebsockets.org

it should work or start working for you soon depending on your DNS cache arrangements.  Luckily the caching means most people didn't see that problem yet.

**Comment by Qizot** [comment]
Experiencing the same thing as @Hajto once again...

**Comment by lws-team** [comment]
Thanks for pointing it out, I renewed the dnssec signature and it should work now (+/- any negative TTL on your local resolver)

**Comment by stevechen2015** [comment]
Failed to connect to libwebsockets.org port 443

**Comment by lws-team** [comment]
Thanks for letting me know, it should be solved now.

**Comment by miroslavavramov** [comment]
sudo git clone https://libwebsockets.org/repo/libwebsockets
[sudo] password for osboxes: 
Cloning into 'libwebsockets'...
fatal: The remote end hung up unexpectedly
