### ISSUE TITLE
Can not correctly choose to use ipv4 address

### ISSUE THREAD

**Issue by moonwalkerjay** [warmcat/libwebsockets#822]
A domain has both ipv4 address also ipv6 address.   when i'm  in ipv4 network, the websocket will choose Ipv6 address to connect.  the result is it can never be success

**Comment by lws-team** [comment]
What platform is this running on?

What version of lws?

It can never be a success because something is broken with lws or broken with ipv6 routing on your side somewhere... or some other reason?

**Comment by lws-team** [comment]
Can you help me understand what it should do that it isn't doing?
