### ISSUE TITLE
error occur when Load Balance proxy SSL connection

### ISSUE THREAD

**Issue by Fallsleep** [warmcat/libwebsockets#823]
When running local test, it run well sometime. But when I deploy the program into the server and proxy SSL connection with Load Balance, I Got following error :
```
[2017/03/02 18:15:25:5599] ERR: SSL_accept failed socket 424: SSL_ERROR_SYSCALL: No error
[2017/03/02 18:15:25:5599] ERR: lws_adopt_socket_vhost: fail ssl negotiation
```

I now check the connection with http protocol on 4444, and I change the defautl protocol to the second of lws_protocols array.
```c++
struct lws_protocols protocols[] =
{
	{
		"http-only",
		http_protocol,
		0,
		1024,
	},
	{
		"default_protocol",
		nullptr,
		0,
		1024,
	},
	{ nullptr, nullptr, 0, 0 }
};


static const struct lws_protocol_vhost_options pvo_opt = {
	nullptr,
	nullptr,
	"default",
	"1"
};

static const struct lws_protocol_vhost_options pvo = {
	nullptr,
	&pvo_opt,
	"default_protocol",
	""
};
...
info->protocols = protocols;
info->pvo = &pvo;
struct lws_vhost *vhost = lws_create_vhost(context, info);
```

Is there some more to do with the vhost when proxy with Load Balance?

**Comment by lws-team** [comment]
Dunno... you're going to have to find out more about why the ssl negotiation error is coming.

If the load balancing action works well, I think lws and the client should not be able to know if it is there or not, if each server has a valid ssl cert.

**Comment by Fallsleep** [comment]
When remote debugging on server, VS2015  throw interception message like follwoing：
`0x703BC0CE (libssl-1_1.dll) (in ConsoleTest.exe): 0xC0000005: An access violation occurred while reading location 0x00000068.`

I think maybe I linked ssl library in wrong way. I will try some other way tomorrow.

**Comment by lws-team** [comment]
Looks like some pointer was NULL and we tried to dereference it.

You really need a backtrace to get an idea.

**Comment by Fallsleep** [comment]
I replaced 708 line in `lib\ssl.c`(now is https://github.com/warmcat/libwebsockets/blob/master/lib/ssl.c#L553) from 
```c++
lwsl_err("SSL_accept failed socket %u: %s\n", wsi->sock,
         lws_ssl_get_error_string(m, n, buf, sizeof(buf)));
```
to
```c++
lwsl_err("SSL_accept failed socket %u: %s\n", wsi->sock,
	SSL_state_string_long(wsi->ssl));
```

I saw log as following:
```
[2017/03/03 14:19:13:5342] ERR: SSL_accept failed socket 348: before SSL initialization
[2017/03/03 14:19:13:5342] ERR: lws_adopt_socket_vhost: fail ssl negotiation
```

I get the source code on Jan 23, and I saw there were a few commit this days. 

Is there any important change with ssl? Shall I get the lastest code and complie the dll again?

**Comment by lws-team** [comment]
"Before SSL initialization"... does this problem only happen one time?  Otherwise the errors are not much help.  lws_ssl_elaborate_error() should print the whole error stack.

If lws works well without a load balancer, the point seems to be something the load balancer does differently...

**Comment by Fallsleep** [comment]
`lws_ssl_elaborate_error()` print nothing as `lws_ssl_get_error_string(m, n, buf, sizeof(buf))` print 'SSL_ERROR_SYSCALL: No error'.

This happened everytime the load balancer doing the health check with tcp port.

**Comment by lws-team** [comment]
And what exactly does the load balancer do with a "health check on tcp port"?

**Comment by Fallsleep** [comment]
I'm not sure about that. 

The aliyun told me it just like telnet ip port.

And shall I return -1 in the callback when `LWS_CALLBACK_CLOSED`?

**Comment by lws-team** [comment]
Doesn't matter, it's closing anyway.

I don't see anything here for lws to do.  Your load balancer does "something" and the SSL negotiation failed.  Maybe it does something without any SSL on its side.

If you find out it does something reasonable, please continue to update and maybe we can reopen.
