### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by WalterCreazyBear** [warmcat/libwebsockets#824]
Hi, I have got some problem with this project. After build it for ios app, I have got the out put files(include and .a). Then I add libwebsocket( include and .a ) and openssl (include and .a )into my xcode project. Every thing seen to be all right. But when I call lws_create_context(&creationInfo) or lws_client_connect_via_info(&connectInfo) I will got this error.
```
Undefined symbols for architecture i386:
  "_lws_ssl_client_connect2", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_ssl_client_bio_create", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_ssl_client_connect1", referenced from:
      _lws_client_socket_service in libwebsockets.a(client.o)
  "_lws_context_init_server_ssl", referenced from:
      _lws_create_vhost in libwebsockets.a(context.o)
  "_lws_context_init_client_ssl", referenced from:
      _lws_create_vhost in libwebsockets.a(context.o)
      _lws_init_vhost_client_ssl in libwebsockets.a(context.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have no idea where is gong wrong. Would please help me 😄

**Comment by lws-team** [comment]
Ehhh... the errors suggest your libwebsockets.a is broken.

The same libwebsockets.a that contains lws_create_vhost() that calls lws_context_init_server_ssl(), also contains that function.

It looks like you built the .a by hand and only included half the sources... go back and look at how you built the .a.
