### ISSUE TITLE
SSL shutdown may cause poll to constantly trigger

### ISSUE THREAD

**Issue by skyhisi** [warmcat/libwebsockets#831]
I'm seeing an issue with the SSL shutdown, where the client enters a situation where the poll is always triggering with POLLIN (1).

```
[ CLIENT ]DEBUG : 0 : LWS : LWS_CALLBACK_RECEIVE_CLIENT_HTTP closed it
[ CLIENT ]DEBUG : 0 : LWS : Close and handled
[ CLIENT ]LwsCallback: wsi=0x8985e68, reason=LWS_CALLBACK_CLOSED_CLIENT_HTTP, user=0x81eec00, in=(nil), len=0
[ CLIENT ]INFO : 0 : LWS : lws_close_free_wsi: shutting down SSL connection: 0x8985e68 (ssl 0x8986190, sock 6, state 6)
[ CLIENT ]DEBUG : 0 : LWS : lws_set_timeout: 0x8985e68: 20 secs
[2017/03/09 10:52:54:8812] INFO: lws_http_transaction_completed: wsi 0x88ac0b8
[2017/03/09 10:52:54:8816] INFO: lws_http_transaction_completed: 0x88ac0b8: close connection
[2017/03/09 10:52:54:8816] INFO: writeable_fail
[2017/03/09 10:52:54:8816] INFO: lws_close_free_wsi: shutting down SSL connection: 0x88ac0b8 (ssl 0x88ac268, sock 8, state 3)
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
[ CLIENT ]DEBUG : 0 : LWS : fd=6, revents=1
```

This can be "fixed" by not using the `SSL_shutdown`, and just calling `shutdown` in `lws_close_free_wsi`; I'm not yet sure what the proper fix is.

I'm only seeing sporadically when running this on a slower PC.

I suspect that it is due to the non-blocking sockets, as `SSL_shutdown` may fail if the read or write would block and return an error code, expecting to be called again.

**Comment by lws-team** [comment]
I guess this is from the change sin https://github.com/warmcat/libwebsockets/issues/802

@namowen is this something you're also seeing?

`SSL_shutdown` is a logical "I am done with this SSL tunnel" type deal that may involve network roundtrips and RX and / or TX  at SSL layer.  `shutdown` is a "I am done writing on this connection" type of deal to give our side a chance to eat any pending RX, while stating there wil be no more TX.

Does he spin forever like that or only briefly?

**Comment by skyhisi** [comment]
It will spin very quickly (thousands of times per second) like a busy loop until the timeout fires.

**Comment by skyhisi** [comment]
The following patch appears to fix the issue, it will keep trying the `SSL_shutdown` until the connection is finished.

```diff
diff --git a/lib/libwebsockets.c b/lib/libwebsockets.c                                                                                      
index c98e60b..668158c 100755
--- a/lib/libwebsockets.c
+++ b/lib/libwebsockets.c
@@ -480,13 +480,14 @@ just_kill_connection:
            !wsi->socket_is_permanently_unusable) {
 #ifdef LWS_OPENSSL_SUPPORT
                if (lws_is_ssl(wsi) && wsi->ssl)
-               {
-                       lwsl_info("%s: shutting down SSL connection: %p (ssl %p, sock %d, state %d)\n", __func__, wsi, wsi->ssl, (int)(long)wsi->desc.sockfd, wsi->state);
+               {
+                       lwsl_info("%s: shutting down SSL connection: %p (ssl %p, sock %d, state %d)\n", __func__, wsi, wsi->ssl, (int)(long)wsi->desc.sockfd, wsi->state);
                        n = SSL_shutdown(wsi->ssl);
-                       if (n == 0) /* Complete bidirectional SSL shutdown */
-                               SSL_shutdown(wsi->ssl);
-                       n = shutdown(wsi->desc.sockfd, SHUT_WR);
-               }
+                       if (n == 1) /* If finished the SSL shutdown, then do socket shutdown, else need to retry SSL shutdown */
+                               n = shutdown(wsi->desc.sockfd, SHUT_WR);
+                       else
+                               lws_change_pollfd(wsi, LWS_POLLOUT, LWS_POLLIN);
+               }
                else
 #endif
                {
diff --git a/lib/service.c b/lib/service.c
index 4b15319..604d4b2 100644
--- a/lib/service.c
+++ b/lib/service.c
@@ -839,10 +839,30 @@ lws_service_fd_tsi(struct lws_context *context, struct lws_pollfd *pollfd, int t
 
 #endif
 
-       lwsl_debug("fd=%d, revents=%d\n", pollfd->fd, pollfd->revents);
+       lwsl_debug("fd=%d, revents=%d, mode=%d, state=%d\n", pollfd->fd, pollfd->revents, (int)wsi->mode, (int)wsi->state);
        if (pollfd->revents & LWS_POLLHUP)
                goto close_and_handled;
 
+
+#ifdef LWS_OPENSSL_SUPPORT
+       if ((wsi->state == LWSS_SHUTDOWN) && lws_is_ssl(wsi) && wsi->ssl)
+       {
+               n = SSL_shutdown(wsi->ssl);
+               lwsl_debug("SSH_shutdown=%d for fd %d\n", n, wsi->desc.sockfd);
+               if (n == 1)
+               {
+                       n = shutdown(wsi->desc.sockfd, SHUT_WR);
+                       goto close_and_handled;
+               }
+               else
+               {
+                       lws_change_pollfd(wsi, LWS_POLLOUT, LWS_POLLIN);
+                       n = 0;
+                       goto handled;
+               }
+       }
+#endif
+
        /* okay, what we came here to do... */
 
        switch (wsi->mode) {
```

**Comment by namowen** [comment]
Hi, I don't think it comes from #802 (commit 96b91cc ssl: avoid EVP errors), because this does only concern error logging in lws_ssl_capable_read and lws_ssl_capable_write, but the logic was not changed, there is a LWS_SSL_CAPABLE_ERROR returned as before.

But there was a commit dc4934d ssl close improvement which concerns SSL_shutdown. But this patch works fine on my platforms (Ubuntu 64bit websocket client & server + Android & iOS as websocket clients). I have no spinning.

If the initiating peer calls SSL_shutdown the first time, it will return 0 in success case; the peer receiving the ssl close alert will call then SSL_shutdown and will get a 1 in success case; the initiating peer will receive the ssl close alert back, and should get a 1 on its 2nd SSL_shutdown. If SSL_shutdown returns -1 instead of 0 or 1 as expected, usually SSL_get_error returned SSL_ERROR_WANT_WRITE in my investigations. Without handling this case in lws_close_free_wsi, it went to the 20 seconds timeout (which may be the same as skyhisi is reporting here).
But this was before commit dc4934d ssl close improvement was applied. After this commit, there was no 20 seconds timeout delay anymore, and I assume this is thanks to the shutdown(wsi->desc.sockfd, SHUT_WR), which is done in any outcome of the SSL_shutdown.

**Comment by lws-team** [comment]
@namowen thanks for the reasoning.... I don't completely understand the symptom, but it seems it is going to be due to WANT coming or not... the patch Silas sent looks like it manages that so hopefully it will solve it.
@skyhisi Thanks for the patch, it's applied on master + v2.2-stable.

**Comment by mmilata** [comment]
@skyhisi @namowen I ran into related issue in #865 - any feedback appreciated.
