### ISSUE TITLE
Error when importing libwebsockets.h on multiple sources

### ISSUE THREAD

**Issue by marcobizzarr1** [warmcat/libwebsockets#833]
Hello, 
I found an issue trying to build a project using the latest version of libwebsocket (2.2.0)

When I try to import the "libwebsockets.h" header on multiple source files in the same project I have the following build errors.

```
1>source1.obj : error LNK2005: _fops_zip already defined in myProj.obj
1>source2.obj : error LNK2005: _fops_zip already defined in myProj.obj
```

The problem disappears if I include the header into a single source file.
The older version of the library worked without any issue.

**Comment by lws-team** [comment]
Is this on windows?

We have

```
LWS_VISIBLE LWS_EXTERN struct lws_plat_file_ops fops_zip;
```

In there which is OK for gcc but as I recall `LWS_EXTERN` is an empty string on windows.

I pushed a patch on both v2.2-stable and master that should fix it.
