### ISSUE TITLE
How to communicate between a libwebsockets client and a websocket server like Nginx?

### ISSUE THREAD

**Issue by GuzzettaLoic** [warmcat/libwebsockets#834]
Hello everyone !
I try to implement a websocket client (with *libwebsockets* in C and it's not an option). As example, i used the _[test-client.c][1]_ given with the library. 
My websocket-client actualy works fine with the _test-server.c_ . But i experienced some complications to communicate with an _nginx_ server. 

As i understand, the handshack doesn't end up well because *nginx* doesn't know my **websocket client's sub-protocol**. 
Well, it appears, like in _test-client.c_ i'm implementing my own sub-protocol (with its own name, its own callback function). 

My questions are : 

- **Is there a way to not use a specific websocket sub-protocol with *libwebsockets* ?**
 
- **If not, am i supposed to implement an existing one (client side) like *WAMP* or something in this [list][2]?** (I do not want to reinvent the wheel...)

- **If not, does it exist a "default" websocket subprotocol that i can specify to nginx and in which it could be compatible with my websocket-client ?** (I'm only doing some simple send/receive action with my client. Implementing a libwebsockets client seems completly useless if it can only communicate with a libwebsockets server)

- **Are my questions relevant? If not why ? What am i missing ?**

Any help is appreciated.
Thanks!

  [1]: https://libwebsockets.org/
  [2]: https://github.com/warmcat/libwebsockets/blob/v2.2-stable/test-server/test-client.c
  [3]: https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name

**Comment by lws-team** [comment]
You can just leave the client creation `info.protocol` as NULL... lws will understand it should not send the ws subprotocol header at all then.

By default, callbacks for no-protocol connections go to the vhost's protocols[0] callback... if you only have one kind of protocol (or no-explicit-protocol-name protocol) in your app that's usually OK and you can just do that.

If you want to separate out that stuff in its own callback / protocol, you can add a protocol for it with a name as if you were going to negotiate it, and direct the vhost to use that named protocol as the 'default' for 'no protocol' ws links at the vhost creation time, using a pvo (per-vhost option)

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L145

In the case you don't create your own vhost explicitly, lws generates one as part of the context creation, so set up the pvo then (both ways use the same context creation info struct).

**Comment by GuzzettaLoic** [comment]
Thank you ! Yes, i've done some digging, as i understood, if i set `info.protocol=NULL` the first sub protocol used (which is not evaluated as one in the header) is `protocols_dummy` (http only). 
My app needs a full bidirectionnal connection (websocket) so, i've to use my own callback function. I don't create my own vhost explicitly. Like in your example in the _test-server.c_ , if i want to use my own callback function, i've to code a plugin (like you did with all your protocols) and linked it in with `lws_context_creation_info.plugin_dirs `.  Indeed, using a pvo didn't set the callback function, just the name of the protocol i want to use, the plugin seems the only way to assign my callback function to `lws_context_creation_info`, am i right ?

**Comment by lws-team** [comment]
Yeah it's right until the end... 

1) plugins are just another way to deliver the protocols[] array entry and the callback, they are otherwise equivalent to putting those things into your code directly.  They're preferred because it's cleaner and reusable to put code for a protocol in a plugin, for example lwsws can use plugins just with a bit of JSON config and no new code, otherwise they have no feature that can't be done directly.

2) You can give an explicit array of protocols in the context creation info struct .protocols.  The original test-server.c / test-server-http.c etc does this, but you can see it's much more messy than test-server-v2.0.c that does exactly the same with plugins.  If you don't give any ptotocols array at context creation time, leaving the info member pointer for it NULL, yes a built-in dummy http one is used plus whatever protocols it finds from plugins at runtime.

3) Yes the protocols[] array binds a callback to a protocol.  Pvo are name:value strings that are passed to the init of the protocol they named, to enable it in the case you used explicit vhosts (otherwise enabling them is optional, since by default they are all enabled).  A pvo can take another pvo as a child expressing "options" to form a tree-like structure, that's how marking a protocol as the default one is done.  A pvo names the protocol, and the .option pointer of that points to a child pvo setting "default" to "1".

That may seem strange but it is aimed at lwsws, which lets you configure all this stuff in JSON rather than in code, see README.lwsws.md for examples.  But that's for serving.

**Comment by GuzzettaLoic** [comment]
Hmm, ok.. I use the protocols[] array entry atm with a pvo. That one set my sub-protocol as 'default'.  But, now i'm going back to my issue, my client header try to negociate with `sec-websocket-protocol: = my-sub-protocol` it seems, such sub-protocol the server has to support.

Client side logs :
```
[2017/03/16 17:25:40:4632] NOTICE: Initial logging level 7
[2017/03/16 17:25:40:4802] NOTICE: Libwebsockets version: 2.1.1
[2017/03/16 17:25:40:4802] NOTICE: IPV6 not compiled in
[2017/03/16 17:25:40:4803] NOTICE: libev support not compiled in
[2017/03/16 17:25:40:4803] NOTICE: libuv support not compiled in
[2017/03/16 17:25:40:4803] NOTICE:  Threads: 1 each 4096 fds
[2017/03/16 17:25:40:4804] NOTICE:  mem: platform fd map: 32768 bytes
[2017/03/16 17:25:40:4808] NOTICE:  Compiled with OpenSSL support
[2017/03/16 17:25:40:4808] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/03/16 17:25:40:4808] NOTICE: Creating Vhost 'default' port -1, 2 protocols, IPv6 off
[2017/03/16 17:25:40:4808] NOTICE:  mem: per-conn:          512 bytes + protocol rx buf
[2017/03/16 17:25:40:4808] NOTICE:  canonical_hostname = ArchDev
[2017/03/16 17:25:40:4808] NOTICE: mirror: connecting
[2017/03/16 17:25:40:4808] NOTICE: lws_protocol_init
[2017/03/16 17:25:40:4809] NOTICE:     vh default prot my-sub-protocol opt default
[2017/03/16 17:25:40:4809] NOTICE: Setting default protocol for vh default to my-sub-protocol
[2017/03/16 17:25:40:4832] ERR: Exiting
[2017/03/16 17:25:40:4837] NOTICE: lws_context_destroy
```

> By default, callbacks for no-protocol connections go to the vhost's protocols[0] callback... if you only have one kind of protocol (or no-explicit-protocol-name protocol) in your app that's usually OK and you can just do that.

I think i missunderstand something right there. 

>  you can just do that.

Are you talking about `info.protocol=NULL` and implicitly use the dummy http default protocol ? Because i don't want to. I've to go through the websocket protocol and so without using a specific sub-websocket protocol (i don't know how to implement it on nginx for instance). 

Or maybe, it's actually working but the _test-server.c_ is not able to work with the client without a sub-protocol (i didn't check that). I'll do more check tomorow (central european summer time zone...) with _wireshark_ .

You are very helpfull. Thanks you !

**Comment by lws-team** [comment]
Yes I am talking about **client connection** `info.protocol=NULL;`.  It will negotiate 'no sub-protocol' then.

I am not talking about **context / vhost creation** `info.protocol**s**` needing to be NULL.

**Comment by GuzzettaLoic** [comment]
Tks for your quick answer. Well i'm not sur that was what you wanted but I think i did it! I just... set the name sub-protocol to `NULL`, i'm not using the pvo, my callback function seems automaticly set as default : 
```
/* list of supported protocols and callbacks */
static struct lws_protocols ws_protocols[] = {
        { NULL, ws_callback, 0, 128, },
        { NULL, NULL, 0, 0 } /* end */
};
```
And it's working. No sub-protocol is specified in the header : 

> Hypertext Transfer Protocol
>     GET // HTTP/1.1
>     Pragma: no-cache
>     Cache-Control: no-cache
>     Host: xxx.xxx.xxx.xxx
>     Origin: http://xxx.xxx.xxx.xxx
>     Upgrade: websocket
>     Connection: Upgrade
>     Sec-WebSocket-Key: cs39DsHagRBsc1SOPFbk/A==
>     Sec-WebSocket-Version: 13

Thank you for your patience, you clarified a lot of things. Have a good St Patrick's day !

**Comment by yagrass** [comment]
With the same protocol setting: 
static struct lws_protocols ws_protocols[] = {
        { NULL, ws_callback, 0, 128, },
        { NULL, NULL, 0, 0 } /* end */
};
I got a runtime error: E: lws_client_connect_via_info: unknown protocol and followed by Segmentation fault (core dumped)!
