### ISSUE TITLE
illegal opcode & interpret_incoming_packet has bailed

### ISSUE THREAD

**Issue by IvanKuchin** [warmcat/libwebsockets#841]
Hi, team, 

Thank you for great product ! 
My WebSocket-server suffered DDoS-attack. Hope you'll help me. For now I applied workaround: turned-off permessage-deflating.
    My setup: 
    	1) ext enabled 
    	2) permessage-deflate negotiated
    	3) rx_buf_size <= struct lws_protocols.rx_buffer_size = any size (I tested on 1024 and 32k)
        4) tested on 2.1.0 and 2.0.2
    Failure scenario:
    	WebSocket server receiving deflated message bigger than rx_buffer_size.

---------- JFYI begin
Success scenario 1) 
    	1) ext enabled 
    	2) permessage-deflate negotiated
    	3) rx_buf_size <= struct lws_protocols.rx_buffer_size = any size 
4) !!! Message <= struct lws_protocols.rx_buffer_size
Success scenario 2) 
    	1) ext enabled 
    	2) permessage-deflate DISABLED
    	3) struct lws_protocols.rx_buffer_size = any size 
		4) !!! Any size received message
---------- JFYI end

---------- How to reproduce: start
1) test-fraggile: fix the struct lws_protocols.rx_buffer_size to 1024.
2) send from client any base64-encoded jpeg-file (pictures will not compressing), for example following line (purpose of that line is to get message deflated to size > than 1024):
`{ \"RequestType\":\"DDoS\", \"blob\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAJbElEQVR4Xu2af4xUVxXHv+e9O0OhIEibgrRlF8rOG6CWKiumrUlTo6byj6mmNFta2DdQsRJJrP5j+0cnjSVp1BoSU1yzO28LEeL6h7GJNhpJNa2CBQ1gd9k3QPlRBU2LLV0W2p173zFvZvbtzOybmbd7J9DEd/+befece97nfe+95/4gxEWLAGlZx8aIAWqKIAYYA9QkoGkeKzAGqElA0zxWYAxQk4CmeazAGKAmAU3zWIExQE0CmuaxAmOAmgQ0zWMFxgA1CWiaxwqMAWoS0DRvrQJ3ujeb17Hrx6SuzLwV32x7VzO+1pj3HJprJue8BcBQCSONRzr+2RrHaO2OtHDc1wDcUwqOj0s7nWpVoDp+hOMeA5Au+zggbesuHX+Vti1VoOh3j4BxRxEf8xmVSbe3KlAdP2bOPUmEpaXviiGZsVbq+IsBxgCnpp9YgVPjNan2RwagmXMfUpnUAEAc9k6Rx8AHB0zzy3euU5nUXk02RXMzl+9Ssw8PYN06FeYvOkAmM5dfpzLWL6LGFXkSMR13jIAEmKXMpBM6AIXjeih+BVLqTEcSWfJ/T71ks4bZ9vAYgU1/epC2ZegAFLnhAogEM0tV5x1r/UcGKBw3UJ1sTyVwH8laZ5EU2DO4WCTFmXFbOTbnemxZdHnq9AAMvDVTjF4ObKVS7di8IvA97jOSArNsiLZ8oGBpW5HYRKrkB1IFcGwkiS2dhWkB7B1qE6Z5uiUAew7NEsk5o4EveEtgLw98TwngwIApRlcFoogBVnzdSArUAWg6+T4QS3U69Xi98eiqK7A4vnX1+YsldWbPJmSzk8fJa6FAP67FXTv9sVLZqU1k9rvHibGsmKQzBlTGeih0gqgcA69CFxaO+zKA+4uxEF6W3dbaSXFdA4Bmzt1DhK5SLHycTMd9n4A5pT9oSNqp0GXO1VagcFx/cphZhnZF2tasjwJAkRs+CqJPFvEBIzHA8a8ScQyMAdbbTGgJwAY7FS3LA3edXCyUbJoHitzwKIhK3Zb5ssykr5/Uha9BHigc9whQ3nHyu7DIDe8A0TY/OI/xtJexngnP5ocLRCRAkLLbas1KhOGps6lE2MxvOO6TBvBsMS7Pe8rbtHz7pLhavRLpdwtgCDCkzIS/o9Gff8pg/n55EtlRSqT7h+8B0xhs62AYvHJlf524QZ3duzs0pfCT7aj7gQNsmqPHH1V2qr9+ewBePHYXIICNHfsb1TNzw7Y6e343svdNWh35dpHyQL9iKUV5VGVSu+qt94tx7DrZCa8wA93pP0deiTR80fLDyACjOGthncgAp9FmqwG+CsbnynHkpW1Z04ip5Sai3x0CY3kpU+P9sjt9d6saaSlA9JybJWaMXARDyRFjLrZ1fNiqQLX8DAwmxai4CCAhzblzsWFhsH7W8lvM8eOiRSAGqIUvVqAmvhhgDFCbgKaDqY+B2ayBBV2fQJJnwzQlSL6HjcsvhMaRHUwG/2dXjjWMtXdwPjBjPryCARKXIcQ7sJd8EOn9fFuTbkCBCDOMUZw69596SXWVv4HB2bicXAClBARdwqm95+stEurFER1gz6GESM45DGBFmLNJW+C5E7cKUmfH68pkoh3rl046r8CL7s3CQ+hdFQY2KNvaXS94o8/\" }`
3) test-fraggile will get crash
---------- How to reproduce: end

---------- Debug start
**Pay attention to comments on lines 18,31,32,41,42**

	1: lwsts[16631]: fd=10, revents=1
	2: lwsts[16631]: lws_read: incoming len 2609  state 5
	3: lwsts[16631]: lws_interpret_incoming_packet: received 2609 byte packet
	4: lwsts[16631]: spill on ddos-protocol
	5: lwsts[16631]: lws_rx_sm: passing 1024 to ext
	6: lwsts[16631]:  lws_extension_callback_pm_deflate: LWS_EXT_CB_PAYLOAD_RX: in 1024, existing in 0
	7: lwsts[16631]: inflate ret 0, avi 258, avo 0, wsifinal 1
	8: lwsts[16631]: -- rx grabbing held --
	9: lwsts[16631]:   lws_extension_callback_pm_deflate: RX leaving with new effbuff len 1023, ret 1, 9: rx.avail_in=258, TOTAL RX since FIN 1023
	10: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 1577, draining 1
	11: lwsts[16631]: _lws_rx_flow_control: no pending change
	12: lwsts[16631]: spill on ddos-protocol
	13: lwsts[16631]: lws_rx_sm: passing 1024 to ext
	14: lwsts[16631]:  lws_extension_callback_pm_deflate: LWS_EXT_CB_PAYLOAD_RX: in 1024, existing in 258
	15: lwsts[16631]: -- RX piling on held byte --
	16: lwsts[16631]: inflate ret 0, avi 280, avo 0, wsifinal 1
	17: lwsts[16631]: -- rx grabbing held --
	18: lwsts[16631]:   lws_extension_callback_pm_deflate: RX leaving with new effbuff len 1023, ret 1, rx.avail_in=280, TOTAL RX since FIN 2046 <-------------- (here you'll get a garbage instead of correct  data)
	19: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 553, draining 1
	20: lwsts[16631]: _lws_rx_flow_control: no pending change
	21: lwsts[16631]: spill on ddos-protocol
	22: lwsts[16631]: lws_rx_sm: passing 553 to ext
	23: lwsts[16631]:  lws_extension_callback_pm_deflate: LWS_EXT_CB_PAYLOAD_RX: in 553, existing in 280
	24: lwsts[16631]: -- RX piling on held byte --
	25: lwsts[16631]: inflate ret 0, avi 0, avo 262, wsifinal 1
	26: lwsts[16631]: RX APPEND_TRAILER-DO
	27: lwsts[16631]: RX trailer inf returned 0, avi 0, avo 258
	28: lwsts[16631]:   lws_extension_callback_pm_deflate: RX leaving with new effbuff len 766, ret 0, rx.avail_in=0, TOTAL RX since FIN 2812
	29: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 0, draining 1
	30: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 0, draining 1
	31: lwsts[16631]: _lws_rx_flow_control: no pending change <--- (must return from  lws_interpret_incoming_packet)
	32: lwsts[16631]: lws_rx_sm: doing draining flow <-------- (must not drain inside lws_interpret_incoming_packet)
	33: lwsts[16631]: lws_rx_sm: passing 0 to ext
	34: lwsts[16631]:  lws_extension_callback_pm_deflate: LWS_EXT_CB_PAYLOAD_RX: in 0, existing in 0
	35: lwsts[16631]: RX APPEND_TRAILER-DO
	36: lwsts[16631]: inflate ret 0, avi 0, avo 992, wsifinal 1
	lwsts[16631]:   lws_extension_callback_pm_deflate: RX leaving with new effbuff len 32, ret 0, 37: rx.avail_in=0, TOTAL RX since FIN 32
	38: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 0, draining 0
	39: lwsts[16631]: lws_is_final_fragment: final 1, rx pk length 0, draining 0
	40: lwsts[16631]: _lws_rx_flow_control: no pending change
	41: lwsts[16631]: illegal opcode <--------- ERROR
	42: lwsts[16631]: interpret_incoming_packet has bailed <------------ leaving lws_interpret_incoming_packet
	43: lwsts[16631]: lws_close_free_wsi: shutting down connection: 0x7f7bb00008c0 (sock 10, state 5)
	44: lwsts[16631]: lws_set_timeout: 0x7f7bb00008c0: 20 secs
---------- Debug end

**Comment by lws-team** [comment]
Well, thanks a lot for finding and reporting this.

I reproduced it on master by adding a button allowing your string-of-death to be sent back from the test server "server list" tab.

The basic problem seemed to be that if we have stuff buffered in the ext that needs draining, we don't take enough care about ignoring the stuff we're flushing with and just getting on with draining the output.  However I am not sure why there was no problem triggered by autobahn pmd tests then.... it has been checked against that several times since 2.0.0 with zero trouble.... and the Autobahn tests spam several MB of text at it.

I pushed what seems to be a fix on v2.0-stable, v2.1-stable, v2.2-stable and master, and confirmed it still passes Autobahn.  Please give it a try.

**Comment by IvanKuchin** [comment]
Appreciate for quick fix. 
Checked on 2.1 and 2.2 - works like charm !
