### ISSUE TITLE
on Android 7.0, code hangs at line "signal(SIGPIPE, SIG_IGN);"

### ISSUE THREAD

**Issue by springrider** [warmcat/libwebsockets#842]
I am using libwebsockets on Android, everything's okay except on Android 7.0, it's wired that the log stops at "SYSTEM_RANDOM_FILEPATH".

```

03-19 21:44:52.899 16025 16261 D libwebsockets: NOTICE: Initial logging level 1023
03-19 21:44:52.900 16025 16261 D libwebsockets: NOTICE: Libwebsockets version: 2.1.0 myname.local-v3.4-162-gd3e50f9
03-19 21:44:52.900 16025 16261 D libwebsockets: NOTICE: IPV6 compiled in and enabled
03-19 21:44:52.900 16025 16261 D libwebsockets:  NOTICE: libev support not compiled in
03-19 21:44:52.900 16025 16261 D libwebsockets: NOTICE: libuv support not compiled in
03-19 21:44:52.900 16025 16261 D libwebsockets: INFO:  LWS_DEF_HEADER_LEN    : 4096
03-19 21:44:52.900 16025 16261 D libwebsockets: INFO:  LWS_MAX_PROTOCOLS     : 5
03-19 21:44:52.900 16025 16261 D libwebsockets: INFO:  LWS_MAX_SMP           : 32
03-19 21:44:52.900 16025 16261 D libwebsockets: INFO:  SPEC_LATEST_SUPPORTED : 13
03-19 21:44:52.900 16025 16261 D libwebsockets:  INFO:  sizeof (*info)        : 184
03-19 21:44:52.900 16025 16261 D libwebsockets: INFO:  SYSTEM_RANDOM_FILEPATH: '/dev/urandom'
// it's all the log.   the following "INFO:  default timeout xxx" never shows up.
```

after some digging I found it's got stuck at the file "lib/lws-plat-unix.c", and the function lws_plat_context_early_init which eventually called signal(SIGPIPE, SIG_IGN). 
after commented this line,  the code just continue and worked normally.

does anyone met this before?  I am newbie to *nix signal and have no idea why it only stuck on Android version 7.0.  lower version works fine.

**Comment by lws-team** [comment]
I have no idea either, but, it seems we should protect this by something like `#if defined(ANDROID_VERSION) && ANDROID_VERSION >= 7 .... #else`

Can you let me know a working way to add that for you?  I am just using ANDROID_VERSION as an example I don't know the official defines for that.

**Comment by springrider** [comment]
thanks for the quick reply.  I could make some test and find the right way to get android version.
but, how about just remove this line for android? would that be a problem?

**Comment by lws-team** [comment]
It's a problem for everyone using it except you, and then a problem for you later when you update lws and it's not fixed.

So you'll be helping yourself and others if you can tell be the one `#if` line to use here for Android 7.

**Comment by lws-team** [comment]
Never mind... Google seem to have not provided any way to detect NDK level from C.

I pushed a patch on master where you can disable this line from CMake using -DLWS_AVOID_SIGPIPE_IGN=1

**Comment by springrider** [comment]
wow that was quick, thanks.

I was trying to do like this:
 ```
 char sdk_ver_str[10] = "0";
  int sdk_ver = 0;
#if defined(__ANDROID__)
  property_get("ro.build.version.sdk", sdk_ver_str, "0");
  sdk_ver = atoi(sdk_ver_str);
#endif
  if(sdk_ver<24){ // not execute for Android version 7.0 and above
    signal(SIGPIPE, SIG_IGN);
  }
```
this could detect build version but need additional dependency setting(libcutils).   so if SIGPIPE ignore is not that important, your solution should be good enough.

**Comment by springrider** [comment]
I still have question about this issue:
a friend told me that if it's a ssl connection, while user exit the app, there would be a SIGPIPE message that cause the app do die immediately.  so user could see a FC message when they exit the app.

is that true or it's a bug and been fixed?    if it's still the case, then this patch could cause potential force close..

thanks!

**Comment by lws-team** [comment]
It's not a "bug" that SIGPIPE is coming when it should.  The OS sends it to us, we don't ask for it.

In fact the code you are turning off defeats the SIGPIPE having any effect at the signal level.  That code just asks to ignore SIGPIPE... you say it makes the process hang... I dunno what you are asking me in each case you have been telling me

 - On Android 7+ signal with IGN on SIGPIPE hangs

 - The code "just continue and work normally"

**Comment by lws-team** [comment]
...

Because lws works on a large number of platforms, not just yours.

I put it there originally because on posix platforms you will get a signal, which unhandled, terminates your application when a remote peer closes the socket on you.

Years later, you open this issue and say one particular version of one platform hangs when we turn off SIGPIPE... there's no reason to think every other platform has retrospectively aligned itself with the behaviour of your version of android that did not even exist until recently, right?

**Comment by springrider** [comment]
yeah that make sense.  just to make sure I didn't broke anything.   thanks for your time 👍
