### ISSUE TITLE
Libwebsockets and PHP

### ISSUE THREAD

**Issue by georges619** [warmcat/libwebsockets#844]
Hello,

I recently discovered Libwebsocket, and wanted to use my web pages programmed in PHP. I searched the web and found nothing about PHP support on Libwebsockets. The only thing I found was that it supports HTML, CSS and Javascript. So I wanted to know if there is a possibility to enable PHP on Libwebsockets. If there is a possibility, please explain how you proceed to setup PHP on the webserver.

Thanks

**Comment by lws-team** [comment]
If you really want to use PHP you can use it with lws as a CGI.

I tested this on current master branch.

### Step 1: make your PHP cgi script somewhere

The script will be a CGI, it needs to produce inline headers and to use chunked transfer-encoding.  This is not hard to do...

Eg, save this as `/var/www/cgi-bin/hello.php`

```
#!/usr/bin/php
<?php

        function chunk($s)
        {
                echo dechex(strlen($s))."\r\n".$s."\r\n";
        }

        echo("Transfer-encoding: chunked\r\n");
        echo("Content-Type: text/html\r\n");
        echo("\r\n");

        chunk("<html>hello</html>");

        echo "0\r\n\r\n";
        flush();
?>
```

### Step 2: Configure LWS for CGI

```
 $ cmake .. -DLWS_WITH_CGI=1
```

### Step 3: Create a mount for the cgi somewhere

You can do this in JSON with lwsws, the mount part looks like

```
     {
        "mountpoint": "/phptest",
        "origin": "cgi:///var/www/cgi-bin/hello.php"
      }
```

Or you can add the mount as code to `test-server-v2.0.c`

```
diff --git a/test-server/test-server-v2.0.c b/test-server/test-server-v2.0.c
index 6041e70..95c970a 100644
--- a/test-server/test-server-v2.0.c
+++ b/test-server/test-server-v2.0.c
@@ -71,8 +71,30 @@ static const struct lws_extension exts[] = {
  * mount handlers for sections of the URL space
  */
 
-static const struct lws_http_mount mount_ziptest = {
+static const struct lws_http_mount mount_phptest = {
        NULL,                   /* linked-list pointer to next*/
+       "/phptest",             /* mountpoint in URL namespace on this vhost */
+       "/var/www/cgi-bin/hello.php",   /* handler */
+       NULL,   /* default filename if none given */
+       NULL,
+       NULL,
+       NULL,
+       NULL,
+       0,
+       0,
+       0,
+       0,
+       0,
+       0,
+       LWSMPRO_CGI,    /* origin points to a callback */
+       8,              /* strlen("/phptest"), ie length of the mountpoint */
+       NULL,
+
+       { NULL, NULL } // sentinel
+};
+
+static const struct lws_http_mount mount_ziptest = {
+       &mount_phptest,                 /* linked-list pointer to next*/
        "/ziptest",             /* mountpoint in URL namespace on this vhost */
        LOCAL_RESOURCE_PATH"/candide.zip",      /* handler */
        NULL,   /* default filename if none given */
```

### Step 4: Build and test

```
 $ make && sudo make install
```

Then run `sudo lwsws` if you set that up, or

```
 $ libwebsockets-test-server-v2.0
```

and visit `http://localhost:7681/phptest`

**Comment by georges619** [comment]
Thanks for your reply. I tested what you wrote, and everything worked fine until step 4. When I execute `$ make && sudo make install` everything works fine. But how should I execute ` $ libwebsockets-test-server-v2.0` ? I work with an embedded Linux card, and I copy the server file on it. I tried to copy the file `$ libwebsockets-test-server-v2.0` on it, but it didn't worked.

From the beginning, I start the server with this command : 
`libwebsockets-test-server -r /usr/share/libwebsockets-test-server/`

**Comment by lws-team** [comment]
Your embedded target is a whole other question that's kind of unrelated to lws.

You should confirm it works on your PC, so you can know "lws can work with php".

Reproducing it on another target is then a different problem specific to your setup.
