### ISSUE TITLE
Question about ipv6 implemention

### ISSUE THREAD

**Issue by MyunghoLee88** [warmcat/libwebsockets#845]
I wonder if there is any doc or sample code for implementing ipv6 version of lws server.
I already implemented server of ipv4 but I can't find any infomations about ipv6.
thank you inadvance.

**Comment by lws-team** [comment]
If you enable it in CMake (-DLWS_IPV6=1) it should just use it if available.

**Comment by MyunghoLee88** [comment]
Thanks, and yes, I saw that.
But is there anything I should do more?
I mean, if I enable -DLW_IPV6=1, is it going to work as a ipv6 server?
I don't know how to change or configure my ipv4 code to ipv6 server.

**Comment by lws-team** [comment]
Unless you went out of your way to add your own ipv4-only socket code, your code uses lws for everything already.  So if lws starts using ipv6, nothing to do.

By default the cmake config is enough to use ipv6 + ipv4, you can control it per-vhost using vhost creation-time `info.options` flags

Flag|function
---|---
(nothing special)|IPV6 + IPV4
LWS_SERVER_OPTION_DISABLE_IPV6|do not use ipv6 on this vhost
LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY|IPV6 + IPV4
LWS_SERVER_OPTION_IPV6_V6ONLY_MODIFY \| LWS_SERVER_OPTION_IPV6_V6ONLY_VALUE| IPV6 only

**Comment by MyunghoLee88** [comment]
thank you very much!!
