### ISSUE TITLE
libwebsockets-test-server doesn't handshake correctly on Solaris 10 (Sparc)

### ISSUE THREAD

**Issue by luk65** [warmcat/libwebsockets#846]
Hello,
I built LWS on a Solaris 10 Sparc system and ran an interoperability test:
- libwebsockets-test-server on Solaris
- libwebsockets-test-ping on a RHEL machine

The handshake fails: libwebsockets-test-ping logs on screen the following message:

[2017/03/23 16:22:04:0786] NOTICE: lws_client_connect_2: address 10.96.4.141
[2017/03/23 16:22:04:0806] NOTICE: checking client ext permessage-deflate
[2017/03/23 16:22:04:0807] NOTICE: instantiating client ext permessage-deflate
[2017/03/23 16:22:04:0808] WARN: lws_client_int_s_hs: accept '2Km1lV6nOnBhznNIPAOdKt4/Jl8=' wrong vs 'sN7TXWQqGqt2L/ez3FRs/ENPxyY='

I found out that there's a problem in the lws_SHA1 function, due to a wrong detection of the BIG_ENDIAN architecture.

I fixed the private-libwebsockets.h header file to make it work correctly:

diff -c private-libwebsockets.h private-libwebsockets-new.h

`*** private-libwebsockets.h     2017-03-21 22:36:33.000000000 +0100`
`--- private-libwebsockets-new.h 2017-03-23 16:29:03.000000000 +0100`
`***************`
`*** 370,379 ****`
`--- 370,388 ----`
`  #endif`

`  #if defined(__sun) && defined(__GNUC__)`
`+ #include <arpa/nameser_compat.h>`
`+ #if !defined (BYTE_ORDER)`
`  #define BYTE_ORDER __BYTE_ORDER__`
`+ #endif`
`+`
`+ #if !defined (LITTLE_ENDIAN)`
`  #define LITTLE_ENDIAN __ORDER_LITTLE_ENDIAN__`
`+ #endif`
`+`
`+ #if !defined (BIG_ENDIAN)`
`  #define BIG_ENDIAN __ORDER_BIG_ENDIAN__`
`  #endif`
`+ #endif`

`  #if !defined(BYTE_ORDER)`
`  #define BYTE_ORDER __BYTE_ORDER`

Regards

**Comment by lws-team** [comment]
Thanks a lot, it's pushed on v2.2-stable and master.
