### ISSUE TITLE
Findlibwebsockets.cmake doesn't log any information

### ISSUE THREAD

**Issue by JonnyPtn** [warmcat/libwebsockets#851]
Originally mentioned in #850 which was closed for some inexplicable reason.

Is there a reason find_package_handle_standard_args isn't used in Findlibwebsockets.cmake? It effectively does the same as the block you have on lines 22-27 currently, but will actually output whether it has been found or not (currently there is no cmake output when finding lws), e.g.:

`-- Could NOT find LibWebSockets (missing: LIBWEBSOCKETS_INCLUDE_DIR LIBWEBSOCKETS_LIBRARIES)`

I've made the change here, so if you are interested I can put together a PR straight away

**Comment by lws-team** [comment]
No thanks.

I invite people who wonder why this is a very rare case of lws turning down a patch to read #850.

**Comment by JonnyPtn** [comment]
Haha, really? Well thanks for justifying everything I said I guess
