### ISSUE TITLE
lwsl_err() instead of lwsl_warn(): failed to acquire ah

### ISSUE THREAD

**Issue by stv0g** [warmcat/libwebsockets#858]
My code uses a HTTP mount point to serve some HTTP content and a custom log emit function which was registered with `lws_set_log_level()`.

The following code throws an error with `lwsl_err()` where in my mind a warning is more appropriate:

https://github.com/warmcat/libwebsockets/blob/master/lib/server.c#L2084

I stumbled upon this because my log emitter function will kill the process as soon as an error is emitted. But it turns out that the error in the title is not really severe and more like a warning?

**Comment by lws-team** [comment]
Right... it's a bad habit to make things lwsl_err() while I work on them and forget to fix them up.  I reduced this to info on v2.1-stable, v2.2-stable and master.

**Comment by stv0g** [comment]
Thank you :-)
