### ISSUE TITLE
Linking snprintf on Windows VS 10

### ISSUE THREAD

**Issue by renyaow** [warmcat/libwebsockets#859]
Building on Windows VS 10 x64 for v2.2-stable. 

It has the issue from #731 when I am building my application using libwebsocket as a library
```
MSVCRT.lib(MSVCR100.dll) : error LNK2005: _snprintf already defined in websockets_static.lib(libwebsockets.obj)
```
Commenting out the following chunk as #731 mentioned solved the double definition problem
```
#if !defined(__MINGW32__) && (!defined(_MSC_VER) || _MSC_VER < 1900) /* Visual Studio 2015 already defines this in <stdio.h> */
#define lws_snprintf _snprintf
#endif
```

But both my application and test_client still failed to build with this error
```
websockets_static.lib(ssl.obj) : error LNK2019: unresolved external symbol snprintf referenced in function lws_ssl_get_error_string
```

I believe the problem is that snprintf is not implemented on VS10 (http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010)
Adding the following line to libwebsockets.h solve the problem
```
#ifndef snprintf
#define snprintf(buf,len, format,...) _snprintf_s(buf, len,len, format, __VA_ARGS__)
#endif
```

**Comment by lws-team** [comment]
OK I added it on master + v2.2-stable.

**Comment by lws-team** [comment]
Ugh... belay that... it kills appveyor with

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error: Macro definition of snprintf conflicts with Standard Library function declaration [C:\projects\libwebsockets\build\websockets_shared.vcxproj]
```

Appveyor also seems to use vs10?  At any rate I will remove this patch until something that doesn't break appveyor appears.

**Comment by renyaow** [comment]
It is using VS14 2015 actually. 

https://ci.appveyor.com/project/lws-team/libwebsockets/build/1.0.1551/job/p0lm70vhgjs1q53s
```
Building for: Visual Studio 14 2015
```

Since snprintf is introduced in VS 2015, this should work for versions before 2015 and keep AppVeyor happy.

```
#if (!defined(_MSC_VER) || _MSC_VER < 1900) && !defined(snprintf)
#define snprintf(buf,len, format,...) _snprintf_s(buf, len,len, format, __VA_ARGS__)
#endif
```

**Comment by lws-team** [comment]
Thanks... that seems to keep it happy, it's pushed on both branches.

**Comment by renyaow** [comment]
One last thing, do you know why is this code in libwebsockets.h? It looks like lws_snprintf is declared later in the header file and defined in libwebsockets.c. This code still gives me problem in VS10

```
#if !defined(__MINGW32__) && (!defined(_MSC_VER) || _MSC_VER < 1900) /* Visual Studio 2015 already defines this in <stdio.h> */
#define lws_snprintf _snprintf
#endif
```

**Comment by kaidoe** [comment]
@renyaow did you ever find a solution to this? I'm having the problem also now in VC12. It seems project specific as I've only began seeing it since moving the lib include to another project file. Any suggestions would be appreciated. I'll post up if I find a solution.

**Comment by lws-team** [comment]
A while back all the non-esp32 snprintf() in lws got changed to lws_snprintf()... since then a couple crept back in, but I pushed a patch on master correcting those and removing the preprocessor hacks for windows around snprintf.  Please give it a try.

**Comment by kaidoe** [comment]
Updated to master and all working fine now, thank you.
