### ISSUE TITLE
GPL-2.0 or LGPL-2.1 ?

### ISSUE THREAD

**Issue by Silviu-Caprar** [warmcat/libwebsockets#863]
Hi there,
I do see some files under GPL-2.1. Were u referring to GPL-2.0 or LGPL-2.1 ?
Here are the files: 
\plugins\generic-table\protocol_table_dirlisting.c
\plugins\generic-sessions\utils.c
\plugins\generic-sessions\handlers.c
\plugins\generic-sessions\protocol_generic_sessions.c
\plugins\generic-sessions\private-lwsgs.h
\plugins\generic-sessions\protocol_lws_messageboard.c
\lib\smtp.

I am talking about version 2.1.0.
Thanks you in advance.

**Comment by lws-team** [comment]
Thanks for pointing it out... it's LGPL... at one time I was thinking lwsws as a standalone app should be GPL... gradually almost all of it migrated into the library though so a while back that also reverted to LGPL... inbetweentimes I just cut and pasted the related headers around when making new source files without looking close enough.

I pushed a patch on v2.1-stable, v2.2-stable and master adding back the missing "Lesser" on those files.
