### ISSUE TITLE
HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by udenaka** [warmcat/libwebsockets#870]
Hi,

I am using the v2.2 stable release test-server in --ssl mode.

when I type the browser just the address and the port (http://127.0.0.1:7681/) by default it tries to go through in http mode I gives me following errors

lwsts[9827]: SSL_accept failed socket 8: SSL_ERROR_SSL
lwsts[9827]: *** error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
lwsts[9827]: lws_adopt_descriptor_vhost: fail ssl negotiation
lwsts[9827]: wsi 0xaf0ed0: TIMEDOUT WAITING on 13 (did hdr 0, ah (nil), wl 0, pfd events 1) 1491968159 vs 1491968158

but when I implicitly type https://127.0.0.1:7681/, It work properly.

I previously use v2.0 stable and it work properly in http to https re-directions. I tested v2.1 stable as well it also give me the same error as v2.2 stable.

For all the scenarios i user the default test server and I see the following options has enable as well.

info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;

any comments regarding this ?

Thanks!!

**Comment by udenaka** [comment]
Hi, 

I added the following option and it seems to fix the issue.  If it is the case please close the issue.

info.options |= LWS_SERVER_OPTION_ALLOW_NON_SSL_ON_SSL_PORT;


Thanks!!

**Comment by lws-team** [comment]
This is working as intended... naturally by default people using https do not want it to be able to be circumvented.  You have to explicitly give that open to enable unencrypted access to the same port.
