### ISSUE TITLE
Several problems with building lws on win10 using mingw

### ISSUE THREAD

**Issue by dspname** [warmcat/libwebsockets#871]
Hi there

I'm currently trying to build lws-master and 2.2 on Win10 using MinGW like the build readme advises. I successfully built lws 2.1.0 some time ago. I encountered some problems during building with both the current master and the 2.2 version.

cmake run output:
https://pastebin.com/fPGYAprQ

First build run:
https://pastebin.com/W3cpLiG1

"Fixed" by commenting out
`typedef SSIZE_T ssize_t;`
in libwebsockets.h line 4429.

Second build run:
https://pastebin.com/HB9THSTu

Fastest workaround was to add
`#define ECONNABORTED 103`
to lib/ssl.c

Third build run:
https://pastebin.com/6DzDCWGM

lws-plat-win.c, line 525:
`_lws_plat_file_open(struct lws_plat_file_ops *fops, const char *filename,
		    const char *vpath, lws_fop_flags_t *flags)`
			
libwebsockets.h, line 4635:
`_lws_plat_file_open(const struct lws_plat_file_ops *fops, const char *filename,
		    const char *vpath, lws_fop_flags_t *flags)`

I replaced the declaration in lws-plat-win.c with the one from libwebsockets.h, so both files have the same declaration for _lws_plat_file_open.

Fourth build run:
https://pastebin.com/aAFbEy8C

Here I got stuck. The linker obviously fails, but I have no idea where to start looking for the missing reference. Perhaps somebody can help me.

Thanks.

**Comment by lws-team** [comment]
Are you you using v2.2-stable branch?  If not please do so.

The last problem seems you are not linking the openssl libraries, libcrypto and libssl produced by building openssl.

**Comment by dspname** [comment]
Hello,
it's the same with both the current master and the 2.2 stable branch.

I'm not that experienced with CMake which makes it pretty hard for me to unterstand its chain. CMakeCache.txt lists
`//Path to a library.
LIB_EAY:FILEPATH=C:/OpenSSL-Win64/lib/libcrypto.lib`
and
`//Path to a library.
SSL_EAY:FILEPATH=C:/OpenSSL-Win64/lib/libssl.lib`

Both libraries exist. I'm using a binary version of openssl.

**Comment by lws-team** [comment]
The mingw stuff was contributed, however it builds OK with openssl in windows on Appveyor.

On windows the '.lib' isn't the actual library, I don't know how it's supposed to work with mingw and linking.

**Comment by dspname** [comment]
Thanks for your answers. I removed OpenSSL-Win64 and installed OpenSSL-Win32 (both v1.1.0e from https://slproweb.com/products/Win32OpenSSL.html). Besides one warning [0], I can now successfully build lws, using the three fixes/workarounds mentioned in the OP.

[0] [ 76%] Building C object CMakeFiles/websockets.dir/lib/context.c.obj
c:/lib_workspace/libwebsockets-2.2-stable/lib/context.c: In function 'lws_create_context':
c:/lib_workspace/libwebsockets-2.2-stable/lib/context.c:637:38: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  context->fops_platform.LWS_FOP_OPEN = _lws_plat_file_open;

**Comment by theuser1** [comment]
I had success building lws v2.2-stable under Windows 7 x64 with MinGW 2013072200 and OpenSSL-Win64 when applying the above mentioned workarounds from @dspname. To build lws useing the x64 OpenSSL libraries use the `-DLIB_SUFFIX=64` switch as stated in the [build instructions](https://github.com/warmcat/libwebsockets/blob/master/README.build.md) . The complete cmake command is:
`cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=C:/MinGW -DLIB_SUFFIX=64 ..`
to build in the current directory. 
I also had the OpenSSL-Win32 libraries installed on my machine as well and for me no intercompatibility problems  occured.

**Comment by lws-team** [comment]
Well it's good to hear some good news and I'm glad you're both working.

I couldn't see any problem at context.c:637... however as you say in lws-plat-win.c where _lws_plat_file_open was defined for windows there was a missing const.  But there is no warning in Linux and it seems I miss the point about what it is trying to tell me there.

I pushed the other fixes from dspname on master and v2.2-stable.
