### ISSUE TITLE
lws_send_pipe_choked implementations differ in functionality

### ISSUE THREAD

**Issue by blockbomb** [warmcat/libwebsockets#873]
I've been working with mosquitto (mqtt broker) which uses libwebsockets and have run into a problem which I believe both pieces of software are at fault with, but I am unsure of the proper fix.  from the libwebsocket perspective this is what I have observed.

the function lws_send_pipe_choked implementation differes slightly from the lws-plat-unix and lws-plat-win in that the unix implementation checks the wsi->trunc_len it returns as if the sending pipe is choked. 

it seems that the windows implementation should also check this?  however I have not worked with the websockets codebase long enough to make a judgment call as to whether this is the appropriate fix or not. I do believe it should be consistant among the platforms. The mosquitto software does not perform the same between a unix system and windows, because of this slight inconsistancy.

should the send pipe be choked if internally there are items buffered?

Thank You
-Brian

**Comment by lws-team** [comment]
Thaks... it sounds right.

I pushed a patch on master / v2.2-stable and v2.1-stable.
