### ISSUE TITLE
finding openssl files

### ISSUE THREAD

**Issue by vigilancetech-com** [warmcat/libwebsockets#874]
I've been trying to compile it under msys2.

The README.build.md under mingw doesn't seem to apply

For one, it says to point your openssl config env var to \bin\openssl.cfg

I set these variables which is the best I can figure out (after trying everything else I could think of too) to:

OPENSSL_CONF=/mingw64/ssl/openssl.cnf
OPENSSL_ROOT_DIR=/mingw64/ssl

It still complains about not being able to find this stuff even though ls -l $<varname> works

Can someone install msys2 and give me a clue how to compile this?

Supposedly there are 3 environments:  msys, mingw32, and mingw64.   The first is mostly for installing packages and developing POSIX only software, and the latter two are for developing windows software.   I'm only interested in the latter two right now.

I followed the build instructions for MingW in the build md as closely as possible.    Also, it doesn't seem to matter if I'm using stable or master.

Here's my command and its output:

$  cmake -DOPENSSL_ROOT_DIR=c:/mingw64/ssl -G "MSYS Makefiles" ..
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE=''
-- Found Git: C:/msys64/usr/bin/git.exe
Git commit hash: desktop-54v20ij\\kevin@DESKTOP-54V20IJ-v2.0.0-364-g6018c05
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Success
-- Performing Test LWS_HAVE___inline__
-- Performing Test LWS_HAVE___inline__ - Success
-- Performing Test LWS_HAVE___inline
-- Performing Test LWS_HAVE___inline - Success
-- Looking for bzero
-- Looking for bzero - found
-- Looking for fork
-- Looking for fork - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for execvpe
-- Looking for execvpe - found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for getloadavg
-- Looking for getloadavg - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for in6addr.h
-- Looking for in6addr.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Performing Test LWS_HAVE_VISIBILITY
-- Performing Test LWS_HAVE_VISIBILITY - Success
CMake Warning (dev) at CMakeLists.txt:868 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "zlib_internal".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

zlib include dirs: win32port/zlib
zlib libraries: C:/msys64/home/kevin/0work/libwebsockets.stable/build/lib/libzlib_internal.a
Compiling with SSL support
CMake Error at C:/msys64/mingw64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
  version "1.0.2k")
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw64/share/cmake-3.7/Modules/FindOpenSSL.cmake:375 (find_package_handle_standard_args)
  CMakeLists.txt:920 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/kevin/0work/libwebsockets.stable/build/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/kevin/0work/libwebsockets.stable/build/CMakeFiles/CMakeError.log".

kevin@DESKTOP-54V20IJ MINGW64 ~/0work/libwebsockets.stable/build
[CMakeError.txt](https://github.com/warmcat/libwebsockets/files/927595/CMakeError.txt)
[CMakeOutput.txt](https://github.com/warmcat/libwebsockets/files/927596/CMakeOutput.txt)

**Comment by lws-team** [comment]
> Can someone install msys2 and give me a clue how to compile this?

Not me... nothing in lws says anything about "msys2".  I had to google it to find out what it was.

All of the lws support for windows is contributed, including the mingw stuff.  It has worked for a lot of people over the years but if you are basically using a new toolchain / os wrapper it's going to be down to you to solve problems around that.  One thing in your favour is that CMake is able to do it on windows and on mingw, so I would guess it is not a million miles away.  It does say

>  (found version "1.0.2k")

which sounds reasonable...

**Comment by vigilancetech-com** [comment]
I would have two questions here:

Can we agree that the README.build.md is wrong where it says?:

NOTE2: Be sure that OPENSSL_CONF environment variable is defined and points at \bin\openssl.cfg

For example:

$ locate openssl.cfg

kevin@DESKTOP-54V20IJ MINGW64 ~/0work/libwebsockets-master/build
$ locate openssl.cnf
/mingw64/ssl/openssl.cnf
/usr/ssl/openssl.cnf

Also, as far as MSYS is concerned, it says:

    Generate the build files (default is Make files) using MSYS shell:

	$ cd /drive/path/to/src
	$ mkdir build
	$ cd build
	$ cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=C:/MinGW ..

Isn't this MSYS?

Is this more of an MSYS related issue, like I should be asking that community how they deal with their paths?

Further, how would I go about finding out how to contact those who have gotten this running over the years?

**Comment by lws-team** [comment]
Well... okay... it seems someone mentioned MSYS in a contributed patch :-)

If you want to use it on MSYS, and it's not working, you either need to debug it or find another solution.  MSYS guys have maybe seen the same thing before but you'll have to ask them if so, not me.

The tools you need to look for who contributed related patches are in front of you...

1) `$ git log -S mingw`

Gets me, eg

```
commit b820e2c2cc16620f6a664edf27377b3a7d9516a7
Author: Stephan Eberle <stephaneberle9@gmail.com>
```
He has been the main contributor about mingw.

2) Search the closed issues here.

**Comment by vigilancetech-com** [comment]
okay, thanks!

**Comment by stephaneberle9** [comment]
After having set up a fresh MSYS2 & MinGW-w64 installation under C:\msys2 following this guide https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2, I was able to bring it a bit further. More precisely, I'm still facing some link errors in a later stage but the OpenSSL stuff works out well. 

This is a list of things that I installed in addition to MSYS2 & MinGW-w64 using pacman within the MSYS2 MINGW64 Shell:

- CMake: MSYS2 MINGW64 Shell > pacman -S mingw-w64-x86_64-cmake
- OpenSSL: MSYS2 MINGW64 Shell > pacman -S mingw-w64-x86_64-openssl
- zlib: MSYS2 MINGW64 Shell > pacman -S zlib

I used this command 

cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=C:/msys2 -DCMAKE_BUILD_TYPE=DEBUG ..

to run the build and got the following OpenSSL-related ouput:

Compiling with SSL support
-- Found OpenSSL: C:/msys2/mingw64/lib/libssl.dll.a;C:/msys2/mingw64/lib/libcrypto.dll.a (found version "1.0.2k")
OpenSSL include dir: C:/msys2/mingw64/include
OpenSSL libraries: C:/msys2/mingw64/lib/libssl.dll.a;C:/msys2/mingw64/lib/libcrypto.dll.a
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for SSL_CTX_set1_param
-- Looking for SSL_CTX_set1_param - not found
Searching for OpenSSL executable and dlls
OpenSSL executable: C:/msys2/usr/bin/openssl.exe
Generating SSL Certificates for the test-server...
cmd = "C:/msys2/usr/bin/openssl.exe" req -new -newkey rsa:1024 -days 10000 -nodes -x509 -subj "/C=GB/ST=Erewhon/L=All around/O=libwebsockets-test/CN=localhost"
 -keyout "W:/github/libwebsockets/build/libwebsockets-test-server.key.pem" -out "W:/github/libwebsockets/build/libwebsockets-test-server.pem"
Generating a 1024 bit RSA private key
.....++++++
......................................++++++
writing new private key to 'W:/github/libwebsockets/build/libwebsockets-test-server.key.pem'
-----
SUCCSESFULLY generated SSL certificate
OpenSSL dlls found:
  Libeay: C:/msys2/mingw64/bin/libeay32.dll
  SSLeay: C:/msys2/mingw64/bin/ssleay32.dll
-- RPM tools not available on Win32 systems

**Comment by lws-team** [comment]
Thank Stephan for the help.  Is there something in lws to do about the link errors?

@vigilancetech-com this helps?

**Comment by lws-team** [comment]
Well... there seems nothing for me to do here.  Thanks again for the help.
