### ISSUE TITLE
can't connect to Socket.IO server

### ISSUE THREAD

**Issue by mindori** [warmcat/libwebsockets#877]
HI, there. I wrote the client code with reference to "test-client.c" But, my test client can't connect to Socket.IO server. Do U have any idea what might be the problem? 

Source is as follows.
```
static enum protocols
{
	PROTOCOL_EXAMPLE = 0,
	PROTOCOL_COUNT
};

static int ProtocolCallback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len);

struct lws *web_socket = NULL;

static struct lws_protocols protocols[] =
{
	{ "protocol_example", ProtocolCallback, 0, 100, },
	{ NULL, NULL, 0, 0 }
};

void ConnectWebSocket() // role of main function
{
	struct lws_context_creation_info info;
	memset(&info, 0, sizeof(info));

	info.port = CONTEXT_PORT_NO_LISTEN;
	info.protocols = protocols;
	info.gid = -1;
	info.uid = -1;
	info.ws_ping_pong_interval = 10;
	//info.extensions = exts;

	struct lws_context *context = lws_create_context(&info);

	web_socket = lws_client_connect(
		/* context = */ context,
		/* address = */ "192.168.1.7", // my local server's IP
		/* port = */ 3000, // my local server's port number
		/* ssl_connection = */ 0,
		/* path = */ "/socket.io/?transport=websocket",
		/* host = */ lws_canonical_hostname(context),
		/* origin = */ "origin",
		/* protocol = */ protocols[PROTOCOL_EXAMPLE].name,
		/* ietf_version_or_minus_one = */ -1);
	//
	lws_service(context, 500);
	lws_callback_on_writable_all_protocol(context, &protocols[PROTOCOL_EXAMPLE]);
}

int ProtocolCallback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
{
	switch (reason)
	{
	case LWS_CALLBACK_CLIENT_ESTABLISHED:
		break;

	case LWS_CALLBACK_CLOSED:
		web_socket = NULL;
		break;

	case LWS_CALLBACK_CLIENT_RECEIVE:
		break;

	case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
		web_socket = NULL;
		break;

	case LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED:
		if ((strcmp((const char *)in, "deflate-stream") == 0)) {
			UE_LOG(LogTemp, Warning, TEXT("denied deflate-stream extension\n"));
			return 1;
		}
		if ((strcmp((const char *)in, "x-webkit-deflate-frame") == 0))
			return 1;
		if ((strcmp((const char *)in, "deflate-frame") == 0))
			return 1;
		break;

	case LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP:
		break;

	case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
		// write something. but it never called.
		break;

	case LWS_CALLBACK_COMPLETED_CLIENT_HTTP:
		web_socket = NULL;
		break;

	default:
		break;
	}
	return 0;
}
```
![null](https://cloud.githubusercontent.com/assets/3761191/25234778/163963e8-261e-11e7-8d53-8293b4aed555.PNG)
[Figure. reason == LWS_CALLBACK_CLIENT_CONNECTION_ERROR]

**Comment by lws-team** [comment]
If 'in' is not NULL when you get LWS_CALLBACK_CLIENT_CONNECTION_ERROR, you can print it as a string to get a clue about why.

Also use tcpdump -s0 -X to look at what is actually getting sent around.

**Comment by mindori** [comment]
Unfortunately, 'in' was 0x00 when LWS_CALLBACK_CLIENT_CONNECTION_ERROR event occured. Instead, I tried capturing packets.

### CASE 1. use test client
![1](https://cloud.githubusercontent.com/assets/3761191/25259959/3568b866-2684-11e7-8001-134866e7c72d.PNG)
[Figure 1. try to connect remote Socket.IO server via my test client]
![3](https://cloud.githubusercontent.com/assets/3761191/25260022/801ca552-2684-11e7-9579-962c07464ce6.PNG)
[Figure 2. try to connect remote Socket.IO server via my test client(change 'path' parameter in lws_client_connect)]
![2](https://cloud.githubusercontent.com/assets/3761191/25259960/356a302e-2684-11e7-9257-d38bdbd2caf1.PNG)
[Figure 3. follow TCP Stream]
### CASE 2. use web browser(chrome)
![image](https://cloud.githubusercontent.com/assets/3761191/25260059/a008e3b2-2684-11e7-80ca-d2ff2391ccff.png)
[Figure 4. try to connect remote Socket.IO server via chrome browser]
![image](https://cloud.githubusercontent.com/assets/3761191/25260108/efa08718-2684-11e7-8554-f1355891c6b6.png)
[Figure 5. follow TCP Stream]

I guess the settings for my test client are incorrect. FIN-ACK packet to be weird too.
What do U think about it? Thank you very much for your prompt reply :)

**Comment by lws-team** [comment]
Well he accepts the connection, takes our request and then hangs up on us.

Generally you will need to look at logging on the server side to see what he felt was bad.

Your host and origin look wrong, they should match the hostname you are using to reach the server.

**Comment by lws-team** [comment]
NEEDINFO
