### ISSUE TITLE
Delay before LWS_CALLBACK_ESTABLISHED on new connection

### ISSUE THREAD

**Issue by thelasthope4U** [warmcat/libwebsockets#878]
Hello,
I am having an issue between lws and it's host application (in this case Janus SFU).  Basically what I am seeing is a 6 second delay between the LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION  callback and the LWS_CALLBACK_ESTABLISHED callback.  Looking at wireshark there is no delay in TCP layer.  In fact the client side of connection sees the connection established and sends first application layer message but it is not received until 6 seconds later.
I have uploaded a zip file of the wireshark capture (pcapng) 
Using lws 1.6 and Ubuntu 16.04.1

I am not sure where to go from here, Janus team feels it is an lws issue.  Any direction is appreciated.

If it helps, here is some Janus log around problem.  This is not the same sample as the pcap attached but failure is very repeatable so it agrees with captured sample.

Apr 20 11:08:24 2017] [WSS-0x7f14580037b0] 20 (LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION)
[Thu Apr 20 11:08:29 2017] [WSS-0x7f14580037b0] WebSocket connection opened from 192.168.0.244 by 192.168.0.244
[Thu Apr 20 11:08:29 2017] Checking if 192.168.0.244 is allowed to contact janus interface
[Thu Apr 20 11:08:29 2017] Yep
[Thu Apr 20 11:08:29 2017] [WSS-0x7f14580037b0] WebSocket connection accepted
[Thu Apr 20 11:08:29 2017] [WSS-0x7f14580037b0]   -- Ready to be used!

[WebSocketDelay.zip](https://github.com/warmcat/libwebsockets/files/947335/WebSocketDelay.zip)

**Comment by lws-team** [comment]
Using such an old lws isn't helping... lws itself doesn't have any plan about waiting 5s before proceeding.  Something else in your setup regulates the passing of the 5s.  It's either in your user code or, eg, as I recall older lws does rdns on connections... it there something strange about rdns on that box for 192.168.x.x addresses?

**Comment by thelasthope4U** [comment]
Thanks for quick response!  First I agree about old build, I will check with Janus team to make sure updating is okay.  I will investigate rdns, it may likely be the cause.  First choice however is to update lws.  Any suggestion on how to update to latest?  I am new to linus world so I am not sure how to remove current package or does latest just overwrite?  I can goole more on this.

**Comment by lws-team** [comment]
If it's built against 1.6 in the distro you need a more recent version of ubuntu itself to update it.

Why don't you add an entry in `/etc/hosts` for 192.168.0.244... that will normally get used instead of doing the rdns, if that's where the delay comes from.  Something like

```
192.168.0.244 mybox
```

**Comment by thelasthope4U** [comment]
You were right on rdns, logged in and executed host ipaddr and there was the delay.  It would not be practicle to add into hosts file as I wont always know client IP, but I am going to do some testing with the hosts file and see if that clears other problems we are seeing while trying to connect. 

Regarding the distro and 1.6, when we install janus we use 
git clone https://github.com/warmcat/libwebsockets.git  I thought this would provide latest version but it looks like I have a misplaced expectation.  Would you mind enlightening me on this?  (Full disclosure, new to linus world)

Thanks

**Comment by lws-team** [comment]
Good... I meant add to hosts as a test to confirm the source of the delay, not as a solution.

I thought you were installing from packages, not git.  By default cloning from lws master gets you the latest version, but you are telling me it's v1.6...

You should look into your DNS setup on that box, check /etc/resolv.conf but also /etc/nsswitch.conf ... mine has a line

```
hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname
```

Also confirm you have an entry for localhost in /etc/hosts.

At any rate this is unrelated to lws, so closing.

**Comment by thelasthope4U** [comment]
Thank you
