### ISSUE TITLE
Error in test-server/test-server-libev.c: dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by mapx** [warmcat/libwebsockets#882]
It was reported at https://bugs.gentoo.org/show_bug.cgi?id=615532

`test-server/test-server-libev.c` in the master branch seems to be affected by the same issue.

**Comment by lws-team** [comment]
I answered this at your bugzilla at 26th April.  libev know they cause this warning and don't care.  So things using libev have to remove -Werror.  It's May 2 if you want to continue discussion, please do it on your bugzilla; I should see it.

**Comment by mapx** [comment]
Thanks for posting to the bugzilla and closing this issue. I hate keeping an issue open too 😸
