### ISSUE TITLE
TIMEDOUT received 

### ISSUE THREAD

**Issue by rollen1960** [warmcat/libwebsockets#885]
I open 4 websocket with HTTP protocol. and all work very well. Thisi is the sequence for the 4th creation:

2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_WSI_CREATE lws* wsi=0x7fb740005430;lws_callb
ack_reasons reason=29;void* user=0;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED lws* wsi=0x7f
b740005430;lws_callback_reasons reason=19;void* user=0;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_FILTER_HTTP_CONNECTION lws* wsi=0x7fb7400054
30;lws_callback_reasons reason=18;void* user=0x7fb740005d10;void* in=0xb77e40;unsigned long len=1;CstringFormat cstringformat(string((char*) in, len))="/";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP_DROP_PROTOCOL lws* wsi=0x7fb740005430;l
ws_callback_reasons reason=50;void* user=0x7fb740005d10;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP_BIND_PROTOCOL lws* wsi=0x7fb740005430;l
ws_callback_reasons reason=49;void* user=0x7fb740005d10;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP lws* wsi=0x7fb740005430;lws_callback_re
asons reason=12;void* user=0x7fb740005d10;void* in=0xb77e40;unsigned long len=1;CstringFormat cstringformat(string((char*) in, len))="/";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP_BODY lws* wsi=0x7fb740005430;lws_callba
ck_reasons reason=13;void* user=0x7fb740005d10;void* in=0xb7bf07;unsigned long len=47;CstringFormat cstringformat(string((char*) in, len))="request=CONNECT&cookie=%0E%0
6%1B%0CSBZA%19VS%3D";
2017/05/02 11:23:18.089 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP_BODY_COMPLETION lws* wsi=0x7fb740005430
;lws_callback_reasons reason=14;void* user=0x7fb740005d10;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:18.140 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_HTTP_WRITEABLE lws* wsi=0x7fb740005430;lws_c
allback_reasons reason=16;void* user=0x7fb740005d10;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:26.930 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_FILTER_NETWORK_CONNECTION lws* wsi=0xba2790;
lws_callback_reasons reason=17;void* user=0;void* in=0x24;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";

After I open another websocket and don't work. The sequence that appear is:

2017/05/02 11:23:26.930 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_WSI_CREATE lws* wsi=0x7fb7400063a0;lws_callback_reasons reason=29;void* user=0;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:26.930 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED lws* wsi=0x7fb7400063a0;lws_callback_reasons reason=19;void* user=0;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";
2017/05/02 11:23:26.930 | INFO | 463439616l | [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1313] WpsServer_log_emit_function : lws_header_table_attach: adding 0x7fb7400063a0 to ah waiting list
2017/05/02 11:23:47.021 | INFO | 463439616l | [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1313] WpsServer_log_emit_function : wsi 0x7fb7400063a0: TIMEDOUT WAITING on 9 (did hdr 0, ah (nil), wl 1, pfd events 0)
2017/05/02 11:23:47.021 | DEBUG | 463439616l | ### [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1287] LWS_CALLBACK_WSI_DESTROY lws* wsi=0x7fb7400063a0;lws_callback_reasons reason=30;void* user=0;void* in=0;unsigned long len=0;CstringFormat cstringformat(string((char*) in, len))="";

The question is ... why I receive the TIMEOUT and WSI_DESTROY ?

Thank you.

Mario

**Comment by lws-team** [comment]
I am not sure what your are doing (being the client?) but timeout reason 9 is PENDING_TIMEOUT_SSL_ACCEPT.  So look for some restriction on simultaneous SSL connections from same client on your server?

**Comment by rollen1960** [comment]
I write the server. My server accept connections and the first 4 connection work very well. When my server receive the 5th connection http (you see LWS_CALLBACK_WSI_CREATE) come the problem. The problem come with ws or with wss or with https. Always the 5th connection will be destroyed. The problem is the same if I make the 5th connection from another client.

**Comment by lws-team** [comment]
Well, I just ran `libwebsockets-test-server --ssl` and opened five firefox windows on `https://localhost:7681`... no problem.

Why don't you try the same test?

**Comment by rollen1960** [comment]
I am sure that the problem is my server because the problem is the same with firefox or with chrome, all connections from the same pc or from 5 pc ... .
The problem is the same if I disable the SSL : I receive

2017/05/02 13:57:21.020 | INFO | 3875501824l | [/home/mariorollino/SVN/PUSH/MSP3/src/msp/feserver.cc 1313] WpsServer_log_emit_function : wsi 0x7ff90c081410: TIMEDOUT WAITING on 3 (did hdr 0, ah (nil), wl 1, pfd events 0)

and the DESTROY

**Comment by lws-team** [comment]
OK... but until you debug your way to some clue implicating lws or way to reproduce, what are you asking me to do about it?  The problem only exists in your code.

If you get more information and something I should do, feel free to continue.

**Comment by rollen1960** [comment]
i probe with libwebsockets-test-server and came no problem. With my server at the 5th connection I receive this notice "lws_header_table_attach: adding 0x7f4a10084bf0 to ah waiting list" and than the connection is DESTROYED. If I close one of the 4 open connections then all works. 

Help please

**Comment by lws-team** [comment]
Does your code by any remote chance have

```
   info.max_http_header_pool = 4;
```

When it creates the context?  This sets the max number of 'ah' (header processing buffers) that can be in use at one time.  If all in use, connections must wait until one is freed.

Just crank up the number from 4, at the cost of a few kB for each one.

If the client holds open http connections, eg after pipelining, it will use up the ah pool until the server times it out.  But for ws, as soon as the connection is upgraded the ah is freed.

**Comment by rollen1960** [comment]
Thank you for help. The problem was inside my sequence of initialization (create context ...)

So my question:

I create the context:
    struct lws_context* context = lws_create_context(&info);

and after I create the the vhost
    struct lws_vhost* vhost = lws_create_vhost(WpsServer_context, &info);

which info option must I set in context and which in vhost ?

And second question:
I will open HTTP connection in push, so I must open taken. How many open http / ws connection can I have ? Where is the option for this ?

Thank Mario

**Comment by lws-team** [comment]
The main thing is make sure you zero down the info struct if it is declared on the stack.  If optional members are zero, it generally means "do whatever the default is".

Read the documentation for the info struct in libwebsockets.h... the members are marked up at the start of the comment as being relevant to the context or the vhost.

> I will open HTTP connection in push, so I must open taken.

I am not sure what this means.  But from the rest of it, it's limited by the  number of fds your process can open.  It's usually 1024 by default in Linux but you can set it to, eg, 100,000 or more if you have enough memory.
