### ISSUE TITLE
Most recv() calls are of size 1 when compiled without SSL

### ISSUE THREAD

**Issue by cgpe-a** [warmcat/libwebsockets#887]
If you compile without SSL support (-DLWS_WITH_SSL=0), then lws_ssl_pending_no_ssl() returns 1, which causes most socket reads to be size 1 after pending = lws_ssl_pending(wsi) is called from service.c.

The performance is therefore terrible.

Commit b3c2427c changed lws_ssl_pending_no_ssl() to return 1 instead of 0, but it's not obvious why.

Returning 0 from lws_ssl_pending_no_ssl() would be consistent with the behaviour of lws_ssl_pending() when SSL is compiled in, but not in use.

**Comment by lws-team** [comment]
... sorry why are "most socket reads... size 1" in that case?  I eyeballed the code but I don't immediately see the link.

**Comment by cgpe-a** [comment]
In service.c this code is followed:

		pending = lws_ssl_pending(wsi);
		if (pending) {
			if (lws_is_ws_with_ext(wsi))
				pending = pending > wsi->u.ws.rx_ubuf_alloc ?
					wsi->u.ws.rx_ubuf_alloc : pending;
			else
				pending = pending > context->pt_serv_buf_size ?
					context->pt_serv_buf_size : pending;
			goto read;
		}

pending is first set to 1 because the call to lws_ssl_pending( wsi ) is ifdef'd to lws_ssl_pending_no_ssl(), which always returns 1.

The if statement returns false in my case, because there are no extensions.

1 is < context->pt_serv_buf_size, so pending remains at 1 before the goto read.

The read uses pending as the size argument to lws_ssl_capable_read(), because it is set. Again, that is ifdef'd to lws_ssl_capable_read_no_ssl(), which uses 1 in the recv() call.

I found all this with strace and the debugger.

**Comment by lws-team** [comment]
Thanks... you're right non-SSL RX looks affected as you say... I pushed a patch on v2.2-stable and master having the non-SSL version return 0.

**Comment by cgpe-a** [comment]
Thanks. Hopefully it was changed from 0 to 1 in commit b3c2427 by accident, rather than to "fix" some other problem.

**Comment by lws-team** [comment]
Yeah there are very few uses of it... even if it 'fixed' something else it would not the right fix since as you found it returns a count, not a flag.
