### ISSUE TITLE
libwebsocket not able to send additional header from client

### ISSUE THREAD

**Issue by selvamKrish** [warmcat/libwebsockets#888]
I'm trying to send additional header (user defined header) from client using below lws API lws_add_http_header_by_name(wsi,
				(const unsigned char *)"my-device-name",
				(const unsigned char *)"mac-address",11 , p, end);
But this "my-device-name" header is not received at the server end. I'm using  test-server and test-client code which downloaded from master. 
To verify this additional header I have just used header name which is already initialized in STORE_IN_ROM static const char * const set[] from lextable-strings.h file.
For example : 
lws_add_http_header_by_name(wsi,
				(const unsigned char *)"user-agent:",
				(const unsigned char *)"mac-address",11 , p, end);
This changes are working fine. I figured out that we can add only header name which is already initialized in char * const set[]  array, other than this custom header which is defined by user is not able to send from client.
Please give any recommendations or possible solution to send user defined custom header from client.
Thanks in advance.

**Comment by lws-team** [comment]
Hm... adding the header for **send** doesn't need anything special, it will be sent just fine with no fiddling with the lexical parser.

However lws only parses incoming headers it knows from the lexical parser and discards the rest.  To add headers to the parser, look here: https://github.com/warmcat/libwebsockets/issues/608
