### ISSUE TITLE
Libsockets crash

### ISSUE THREAD

**Issue by trankkilou** [warmcat/libwebsockets#890]
Hi,

I'm using secure websocket through Janus webrtc gw and so libwebsocket.

I did compile libwebsocket using latest stable branch.

The crash happen when a new connection from a user happen and send some data

the strace: 

https://pastebin.com/SyDjPgC9

what gdb is telling us
https://pastebin.com/AZ47bSqE

ATM I have to fallback to HTTP(s)

**Comment by lws-team** [comment]
It says it crashes in lws_ssl_server_name_cb(), but that doesn't mean the problem is there or in lws... strlen(NULL) will get you a crash in libc but the problem is not in strlen or libc.  I have no problem with it.

Since you built lws you should have the test server... you should be able to run `libwebsockets-test-server --ssl` and connect via https://localhost:7681 ... if that has the same problem I can try to help.  If not, your problem seems related to (Janus + lws) not lws.

**Comment by trankkilou** [comment]
Hello Andy,

What kind of test do you want me to do ?

I try a GET / and POST using telnet and nothing bad happen. However it does not mean anything to me

root@OMS-WEBRTC0:~# libwebsockets-test-server --ssl
lwsts[4209]: libwebsockets test server - license LGPL2.1+SLE
lwsts[4209]: (C) Copyright 2010-2016 Andy Green <andy@warmcat.com>
Using resource path "/usr/share/libwebsockets-test-server"
lwsts[4209]: Initial logging level 7
lwsts[4209]: Libwebsockets version: 2.2.0 root@OMS-WEBRTC0-v2.0.0-374-ga1210f7
lwsts[4209]: IPV6 not compiled in
lwsts[4209]: libev support not compiled in
lwsts[4209]: libuv support not compiled in
lwsts[4209]:  Threads: 1 each 65536 fds
lwsts[4209]:  mem: platform fd map: 524288 bytes
lwsts[4209]:  Compiled with OpenSSL support
lwsts[4209]: Doing SSL library init
lwsts[4209]: Creating Vhost 'default' port 7681, 5 protocols, IPv6 off
lwsts[4209]:  SSL ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!HMAC_SHA1:!SHA1:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!AES128-GCM-SHA25
lwsts[4209]:  Using SSL mode
lwsts[4209]:  SSL ECDH curve 'prime256v1'
lwsts[4209]:  Listening on port 7681
lwsts[4209]:  mem: per-conn:          568 bytes + protocol rx buf
lwsts[4209]:  canonical_hostname = OMS-WEBRTC0
lwsts[4209]: SSL_accept failed socket 8: SSL_ERROR_SSL
lwsts[4209]: *** error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
lwsts[4209]: lws_header_table_detach: wsi 0xe78c40: ah held 4s, ah.rxpos 0, ah.rxlen 0, mode/state 6 4,wsi->more_rx_waiting 0
lwsts[4209]: wsi 0xe78c40: TIMEDOUT WAITING on 9 (did hdr 0, ah 0xe4cc90, wl 0, pfd events 1) 1493987100 vs 1493987099
lwsts[4209]: lws_header_table_detach: wsi 0xe78c40: ah held 6s, ah.rxpos 0, ah.rxlen 0, mode/state 6 4,wsi->more_rx_waiting 0
lwsts[4209]: SSL_accept failed socket 8: SSL_ERROR_SSL
lwsts[4209]: *** error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
lwsts[4209]: lws_header_table_detach: wsi 0xe78c40: ah held 4s, ah.rxpos 0, ah.rxlen 0, mode/state 6 4,wsi->more_rx_waiting 0

**Comment by lws-team** [comment]
If it's an lws problem, you are basically saying in the original report you can't connect to lws without a crash.

But in the lws test apps, you can connect to lws using ssl without a crash.

If it was, eg, lws braindamaged, or openssl libs braindamaged, you would not be able to succeed with the test server.

Therefore the problem needs something specific from Janus and needs debugging on that side (until or unless something points back at lws issue at least).

**Comment by lws-team** [comment]
Rereading what you wrote

> I try a GET / and POST using telnet and nothing bad happen

why?  Did you actually connect with a browser at https://localhost:7681 or not?

**Comment by trankkilou** [comment]
Hello Andy,

Not the firs time (just using telnet) but now I did
 I made all the test provided by your « minimal web socket test app »

I didn’t see anything obvious and nothing crash

J-

**Comment by lws-team** [comment]
Well, it seems it needs debugging from Janus side.  If more info appears making it look like lws issue, please let me know.
