### ISSUE TITLE
Mailing list doesn't seem to work

### ISSUE THREAD

**Issue by andy-ning** [warmcat/libwebsockets#893]
I know this is not the right place to report a mailing list issue ... But I couldn't find another way to contact the author or the team. The mailing list seems to be down. My subscription and confirmation were bounced back a few days.

I have patched libwebsockets to support SOCKS5 and would like to push it up to mainstream. I need to know roughly the submission procedure.

The following is the bounced back emails.

Thanks for your attention.

Andy Ning (@ Wind River)

This is my confirmation to the subscription:
===================================================================
This is the mail system at host build.warmcat.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<libwebsockets-request@warmcat.com>: Command died with status 1:
    "/usr/lib/mailman/mail/mailman request libwebsockets". Command output:
    mailcmd script, list not found: libwebsockets

Reporting-MTA: dns; build.warmcat.com
X-Postfix-Queue-ID: B13DE2E1373
X-Postfix-Sender: rfc822; Andy.Ning@windriver.com
Arrival-Date: Thu,  4 May 2017 23:02:49 +0800 (CST)

Final-Recipient: rfc822; libwebsockets-request@warmcat.com
Original-Recipient: rfc822;libwebsockets-request@warmcat.com
Action: failed
Status: 4.3.0
Diagnostic-Code: x-unix; mailcmd script, list not found: libwebsockets

Re: confirm 32192125355fb3241c58279fc13ca2d6d4b054ca.eml
Subject: 
Re: confirm 32192125355fb3241c58279fc13ca2d6d4b054ca
From: 
Andy Ning <andy.ning@windriver.com>
Date: 
2017-05-04 11:02 AM
To: 
<libwebsockets-request@warmcat.com>

On 2017-05-04 10:52 AM, libwebsockets-request@warmcat.com wrote:
>      confirm 32192125355fb3241c58279fc13ca2d6d4b054ca 

This is my first email to the list:
====================================================================
This is the mail system at host build.warmcat.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<libwebsockets@warmcat.com>: Command died with status 1:
    "/usr/lib/mailman/mail/mailman post libwebsockets". Command output: post
    script, list not found: libwebsockets

Reporting-MTA: dns; build.warmcat.com
X-Postfix-Queue-ID: 5B8012E1378
X-Postfix-Sender: rfc822; Andy.Ning@windriver.com
Arrival-Date: Thu,  4 May 2017 23:11:03 +0800 (CST)

Final-Recipient: rfc822; libwebsockets@warmcat.com
Original-Recipient: rfc822;libwebsockets@warmcat.com
Action: failed
Status: 4.3.0
Diagnostic-Code: x-unix; post script, list not found: libwebsockets

Patch submission.eml
Subject: 
Patch submission
From: 
Andy Ning <andy.ning@windriver.com>
Date: 
2017-05-04 11:10 AM
To: 
<libwebsockets@warmcat.com>

Hi,

I have a patch that I'm going to push up to the upstream.  What's the submission procedure roughly?

I read from the "Quality" section on the home page that libwebsockets has been:

- Valgrind-cleaned

- Tested against Autobahn WS Test Suite (never used it before)

- Tested by Coverity

- auto build  tested

Doest this mean the patch needs to pass all the above tests?

Thanks,

Andy Ning

**Comment by lws-team** [comment]
Yeah... I received your email about it... an update seems to have broken the mailman service... I'll fix it shortly.

Push your patch here as a pull request against master... I confirm releases against the criteria you mention, for patches if the code looks good, doesn't blow anything up for me, appveyor or travis, it'll probably go in.

**Comment by andy-ning** [comment]
Cool. Thanks for your rapid reply. Do I have to re-subscribe to the mailing list?

**Comment by lws-team** [comment]
I dunno yet I have to figure out what broke.  I'll post about it later.

**Comment by lws-team** [comment]
I can't see any problem with the ml stuff.

You seem to have ended up at the wrong email address for the list, there is no 'libwebsockets@warmcat.com'.

Please try signing up here again (you are not signed up atm)

https://libwebsockets.org/mailman

If it's still broken I think your corporate email server is rewriting the email address to this wrong '@warmcat.com' address... afaik that's not a problem on my side.
