### ISSUE TITLE
lws_callback_on_writable apparently causing a deadlock

### ISSUE THREAD

**Issue by lminiero** [warmcat/libwebsockets#894]
Hi,

I'm debugging an issue with my server deadlocking in its websockets functionality, and by some probes and several tests it seems to be happening when calling `lws_callback_on_writable`. My server is multithreaded, which is why I use `lws_callback_on_writable` to notify the thread responsible for the lws event loop that it's time to send something, as per the guidelines. It only rarely happens, but when it deadlocks, that's where it does: basically, the call to `lws_callback_on_writable` seems never to return, which causes a mutex we locked never to be released, thus causing the deadlock in some aspects of the platform (the ones affected by that mutex).

I was under the assumption that `lws_callback_on_writable` simply only set a flag that the event loop could use to subsequently trigger a `LWS_CALLBACK_SERVER_WRITEABLE` event (for a server), but a quick glance at the code revealed it seems to do much more than that. Is there any condition that may actually cause `lws_callback_on_writable` never to return or wait on something forever for some reason?

Thanks in advance for any insight you can give me on this!

**Comment by lws-team** [comment]
LWS_MAX_SMP (at cmake) is the default of 1 or something else?  Still have problems with it at 1?  At 1, meaning one lws service thread, which is all that works atm, there is no locking done inside lws and logically then no way to deadlock.

If problems still coming, attach a debugger next sign of trouble and collect backtraces from the threads in case it's a simple race.

**Comment by lminiero** [comment]
Thanks for the quick answer! I'm using the repo version Fedora ships, but looking at the contents of the source RPM, `libwebsockets-2.1.0-2.fc25.src.rpm`, it doesn't look like they're overriding the default value. I'll try attaching with gdb when it happens: it might take a bit as I'll have to find the right thread to attach to, but that's my fault for using so many threads! :wink:

**Comment by lws-team** [comment]
Gdb attaches to your whole process.  You can use `info threads` to see what threads are around and `t 1`, `t 2` etc to change the context to each in turn for `bt`.

**Comment by lminiero** [comment]
I can't seem to be able to replicate the issue anymore: my guess is that I was using a manually compiled version of the library when I last collected my data, and that I hadn't tried again when switching to the repo version recently, so it seems you were spot on about the `LWS_MAX_SMP=1` fixing it, thanks! Another user confirmed that he got several hours without a deadlock with that change, which again seems to confirm your observation.

At this point I think we can close this, so sorry for the noise and thanks again for the quick help! Should I manage to replicate this again with the new environment as well, I'll be sure to provide the gdb information here.
