### ISSUE TITLE
LWS_CALLBACK_CONFIRM_EXTENSION_OKAY is passed to a wrong callback

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#897]
`LWS_CALLBACK_CONFIRM_EXTENSION_OKAY` is always passed to `protocol[0]` which is wrong in my opinion, since preceding and following "reasons" (at least those I handle) are passed to the default WS protocol.

To illustrate the issue, here's the server configuration:
```
lws_extension Extensions[] =
{
    {
        "permessage-deflate",
        lws_extension_callback_pm_deflate,
        "permessage-deflate"
    },
    {
        "deflate-frame",
        lws_extension_callback_pm_deflate,
        "deflate_frame"
    },
    { nullptr, nullptr, nullptr }
};

lws_protocols Protocols[] =
{
    {
        "http-only",
        &HttpCallback,
        sizeof( HttpSession ),
        15 * 1024
    },
    {
        "v1",
        &WsCallback,
        sizeof( WsSession ),
        10 * 1024
    },
    { nullptr, nullptr, 0, 0 }
};

lws_protocol_vhost_options Options[] =
{
    {
        nullptr,
        &Options[1],
        "v1",
        ""
    },
    {
        nullptr,
        nullptr,
        "default",
        "1"
    }
};
```
And the observed call sequence:
1. `WsCallback : LWS_CALLBACK_FILTER_PROTOCOL_CONNECTION`
2. `HttpCallback : LWS_CALLBACK_CONFIRM_EXTENSION_OKAY`
3. `WsCallback : LWS_CALLBACK_ESTABLISHED`
4. `WsCallback : LWS_CALLBACK_SERVER_WRITEABLE`
5. `WsCallback : LWS_CALLBACK_CLOSED`

**Comment by lws-team** [comment]
I see.

Why don't you propose a patch?
