### ISSUE TITLE
[Windows build] [Target XP] Compilation Issue.

### ISSUE THREAD

**Issue by Joffrey** [warmcat/libwebsockets#898]
1) First, I call cmake with XP target as parameter.

```
cmake -G"Visual Studio 14 2015"
  -DCMAKE_GENERATOR_TOOLSET=v140_xp
  C:\dev\libraries\libwebsockets
```
2) When I start the build, with **cmake --build . --config Debug**, there is a compiler error :

```
  C:\dev\libraries\libwebsockets\win32port\win32helpers\gettimeofday.c(22):
error C2037: left of 'tv_sec' specifies undefined struct/union
'timeval' [C:\dev\vc2015\libwebsocket_x86_MDd_build\websockets_shared.vcxproj]
  C:\dev\libraries\libwebsockets\win32port\win32helpers\gettimeofday.c(23):
error C2037: left of 'tv_usec' specifies undefined struct/union
'timeval' [C:\dev\vc2015\libwebsocket_x86_MDd_build\websockets_shared.vcxproj]
```
3) A possible workaround is to define the timeval struct at the beginning of win32helpers/gettimeofday.c

```
struct timeval {
    long tv_sec;                /* seconds */
    long tv_usec;               /* microseconds */
};
```

But there is probably a better way to do that..

**Comment by JoakimSoderberg** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740560(v=vs.85).aspx

This struct is defined in `time.h` on windows:

Minimum supported client
Windows 2000 Professional [desktop apps only]
Minimum supported server
Windows 2000 Server [desktop apps only]

So I suspect some other funny business is going on here.

I mean the best solution would be to do system introspection for this in CMake.
```cmake
check_function_exists (gettimeofday LWS_HAVE_GETTIMEOFDAY)
```

And use it in https://github.com/warmcat/libwebsockets/blob/master/lws_config_private.h.in
```c
#cmakedefine LWS_HAVE_GETTIMEOFDAY
```

Curl does this.
https://github.com/curl/curl/blob/master/CMakeLists.txt#L808

And maybe using `check_symbol_exists` is better like they do
https://cmake.org/cmake/help/v3.0/module/CheckSymbolExists.html

Then they use it in places like this:
https://github.com/curl/curl/blob/66de563482c0fd4324e1eae19809d2499e3c4fa8/lib/timeval.c#L71

But yea all this is some lose recommendations and thoughts. So don't take this is a ready solution to use rather just some pointers.

**Comment by lws-team** [comment]
Thanks Joakim.

We seem to do this in gettimeofday.c:

```
#include <time.h>
#include <windows.h> //I've omitted context line

#include "gettimeofday.h"

int gettimeofday(struct timeval *tv, struct timezone *tz)
```

Something funny sounds like a good diagnosis, the error seems to be saying we have `struct timezone`, but not `struct timeval`.  I guess it's picking up a different time.h.  This has been unchanged for a long time, back to the days when XP was much more commonly targeted, with no problems.  How about checking for wrong time.h by temporarily putting an absolute path to the right time.h instead of `#include <time.h>`, using quotes?

**Comment by lws-team** [comment]
@Joffrey if you want to give it a try at some point, please let us know.
