### ISSUE TITLE
LWS_NO_EXTENSIONS=ON compilation failure

### ISSUE THREAD

**Issue by chrismeyersfsu** [warmcat/libwebsockets#9]
Compilation fails because the ifdef factors out an enum which as the return value of a function that is not factored out.
<pre>
mkdir build
cd build
cmake ../ -DLWS_NO_EXTENSIONS=ON
make
</pre>

<pre>
pi@raspberrypi ~/pestermypet/libs/libwebsockets/build $ make
Scanning dependencies of target websockets
[  2%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  5%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  8%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[ 11%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[ 13%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[ 16%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 19%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 22%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 30%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
In file included from /home/pi/pestermypet/libs/libwebsockets/lib/extension.c:4:0:
/home/pi/pestermypet/libs/libwebsockets/lib/extension-deflate-frame.h:25:3: error: ‘enum libwebsocket_extension_callback_reasons’ declared inside parameter list [-Werror]
In file included from /home/pi/pestermypet/libs/libwebsockets/lib/extension.c:5:0:
/home/pi/pestermypet/libs/libwebsockets/lib/extension-deflate-stream.h:20:12: error: ‘enum libwebsocket_extension_callback_reasons’ declared inside parameter list [-Werror]
/home/pi/pestermypet/libs/libwebsockets/lib/extension.c:7:31: error: array type has incomplete element type
/home/pi/pestermypet/libs/libwebsockets/lib/extension.c: In function ‘libwebsocket_get_internal_extensions’:
/home/pi/pestermypet/libs/libwebsockets/lib/extension.c:34:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/websockets.dir/lib/extension.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by warmcat** [comment]
Nowdays we have automated testing to find when we didn't take care about the common build options.
