### ISSUE TITLE
Multiple LWS_CALLBACK_SERVER_WRITEABLE for a single lws_callback_on_writable

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#900]
Sometimes (most often in the first minutes after the server starts) my callback receives multiple (at least two) calls with `LWS_CALLBACK_SERVER_WRITEABLE` reason for a single `lws_callback_on_writable` request; it sends data using `lws_write` on the first invocation and bails out with `return 0` on subsequent calls since it has no data to send.
Most prominently I'm facing this issue on Linux (Ubuntu 16.04 x64), seen it but once on Windows (x64).

I'm using `LWS 2.2.1` and I've never faced it with `LWS 1.6` (neither on Linux nor Windows, nor Android); the server code stays the same.

Maybe I'm missing something that needs to be changed to adapt my code for `LWS 2.2.1`?

**Comment by lws-team** [comment]
There's no guarantee about how many writeable calls you will receive.

In the opposite case if you ask for a callback multiple times between the connection becoming writable, you will only get one.

Why is that a problem?

**Comment by emptyVoid** [comment]
It's just the server's callback initially treated absence of data during `LWS_CALLBACK_SERVER_WRITEABLE` as a signal to tear down connection (and it worked with `LWS v1 series`).

It's not really a problem if it's the expected behavior (just a breaking change for me), though since all the work is done in a single thread I can really understand what is the purpose of issuing multiple writable calls (after all they may not be cheap).

**Comment by lws-team** [comment]
After handling a partial send, lws must eat the writable callbacks to send the remainder until it's cleared.  Since it doesn't know if the user side requested a writeable callback in the meanwhile, it gratuitously calls one after it has cleared the backlog.

Again if you want to send a patch to store that there has been a user writable callback and only do it if then, I'll be happy to look at it.
