### ISSUE TITLE
Default WebSocket Protocol

### ISSUE THREAD

**Issue by tmarrinan** [warmcat/libwebsockets#904]
I am attempting to use libwebsockets to create a WebSocket server using the default / no protocol name. In JavaScript, the protocols are optional when creating a WebSocket client ([https://developer.mozilla.org/en-US/docs/Web/API/WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)).
How can I create a WebSocket server that will communicate with a client instantiated without any protocol specified? So far I have tried passing `NULL` and `""` as the name of the protocol, but no luck.

**Comment by lws-team** [comment]
By default, protocols[0] gets selected if there is no protocol header sent by the client.

You can select another protocols[n] guy for the job by adding a per-vhost option (pvo) on the protocol marking it as the default instead.  Eg,

https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L146
https://github.com/warmcat/libwebsockets/blob/master/test-server/test-server-v2.0.c#L443

**Comment by tmarrinan** [comment]
Thanks!
I am still having trouble following how to integrate that though. Here is what I tried:

```
struct lws_protocols protocols[] = { // first protocol must always be HTTP handler
    { "http-only", callback_http, 0 },
    { "default", callback_default_ws, 0},
    { NULL, NULL, 0 }
};
const struct lws_protocol_vhost_options pvo = {
    NULL, NULL, "default", ""
};

// ...

info.pvo = &pvo;
```

This still is not receiving anything from clients with no protocol header.

**Comment by tmarrinan** [comment]
Nevermind... I got it.
Saw that that last commit was disabling default protocol, so understood when checking out that commit ([https://github.com/warmcat/libwebsockets/commit/629e356bb2e25f16f6714cdd96e7b26aafe4e68f](https://github.com/warmcat/libwebsockets/commit/629e356bb2e25f16f6714cdd96e7b26aafe4e68f))

In case others are curious, here was my final solution:

```
struct lws_protocols protocols[] = { // first protocol must always be HTTP handler
    { "http-only", callback_http, 0 },
    { "default-protocol", callback_default_ws, 0},
    { NULL, NULL, 0 }
};
const struct lws_protocol_vhost_options pvo_opt = {
    NULL, NULL, "default", "1"
};
const struct lws_protocol_vhost_options pvo = {
    NULL, &pvo_opt, "default-protocol", ""
};

// ...

info.pvo = &pvo;
```

**Comment by lws-team** [comment]
Glad you are working.

**Comment by tmarrinan** [comment]
So, this solution ended up causing another issue. As can be seen from the code I previously posted, the WebSocket protocol is `protocols[1]`. However, when I call `lws_callback_on_writable_all_protocol(context, &protocols[1])` from my main loop, I never get a callback to `LWS_CALLBACK_SERVER_WRITEABLE`. If I instead call `lws_callback_on_writable_all_protocol(context, &protocols[0])`, then I do get the callback.

However, I do not want to always call `lws_callback_on_writable_all_protocol` from my main loop, only when I want to write something (triggered by receiving data from the client). Therefore I try `lws_callback_on_writable_all_protocol(lws_get_context(wsi), lws_get_protocol(wsi))` from inside `LWS_CALLBACK_RECEIVE`, but this never triggers `LWS_CALLBACK_SERVER_WRITEABLE` either.

**Comment by lws-team** [comment]
I am not sure marking protocols[1] as the default can have caused whatever your problem is.

The wsi gets bound to a specific vhosts's protocol at the time of the upgrade, one-time (a pointer in the wsi is set to the selected lws_protocols).  So assuming your wsi gets created and callbacks like ESTABLISHED are coming in callback_default_ws(), WRITABLE will come there too.

`lws_callback_on_writable_all_protocol()` is certainly doing what it is supposed to generally, because it is used in the test server, eg, for mirror.

BTW you are setting the `per_session_data_size` member of struct lws_protocols to 0 everywhere here.  That is why you don't get anything usable in `user` param of the callback.  You should define your own struct that holds things for each connection using the protocol and set this to sizeof(struct yourstruct).  `user` will then be enough space for a struct yourstruct with its creating and freeing automatically managed by lws.

**Comment by tmarrinan** [comment]
Inside my callback for the second protocol (i.e. `protocols[1]`), this is what I have to do in order to trigger `LWS_CALLBACK_SERVER_WRITEABLE`:

```
lws_callback_on_writable_all_protocol(lws_get_context(wsi), lws_get_protocol(wsi) - 1);
```

Which points to `protocols[0]`. I don't believe this was the case before setting `protocols[1]` as the default.

**Comment by lws-team** [comment]
Hum looks like a bug... please try a4f88d543ea95d83396f2afc42c677b8ffeb73ac

**Comment by tmarrinan** [comment]
That seems to have fixed it - thanks!
