### ISSUE TITLE
Setting user data

### ISSUE THREAD

**Issue by tmarrinan** [warmcat/libwebsockets#906]
I cannot seem to set the user data in order to later retrieve it during callbacks. According to the documentation I see that:

```
For each connection / session there is user data allocated that is
pointed to by "user".  You set the size of this user data area when
the library is initialized with lws_create_server.
```

However, I never call `lws_create_server`, but rather `lws_create_context`, and I don't see any examples that set or retrieve the user field for use during a callback.

I have tried setting the `user` field in the `lws_protocols` struct, but the `user` pointer in my correlating callbacks are still NULL.

**Comment by lws-team** [comment]
The `user` pointer in the callbacks is auto-allocated when a ws wsi binds to a protocol.

The `per_session_data_size` member of the struct lws_protocols controls how much memory is allocated there.

```
struct lws_protocols {
...
        size_t per_session_data_size;
        /**< Each new connection using this protocol gets
         * this much memory allocated on connection establishment and
         * freed on connection takedown.  A pointer to this per-connection
         * allocation is passed into the callback in the 'user' parameter */
```

`user` in struct lws_protocols itself is just a dumb pointer you can associate with the protocol, and retrieve with eg `lws_get_protocol(wsi)->user`.  It's useful is you have, eg, a C++ object wrapping the protocol. lws ignores it.

**Comment by tmarrinan** [comment]
Got it! `lws_get_protocol(wsi)->user` works for my situation.

**Comment by sackett** [comment]
Hello! I wonder how to assgn user pointer.

struct test_struct {
	char buf[100];
};

	test_struct ts;
	sprintf_s(ts.buf, "test str");

	lws_get_protocol(wsi)->user = &ts;
error C3892: 'lws_get_protocol': you cannot assign to a variable that is const

This way it works:
ctxCreationInfo.user = &ts;

but inside callback function the *user pointer not changed (still NULL).

How it works? Thanks in adavance.
