### ISSUE TITLE
Get Client Port

### ISSUE THREAD

**Issue by tmarrinan** [warmcat/libwebsockets#908]
I can successfully get the ip address of a client using `lws_get_peer_addresses`:

```
char name[64];
char ip[16];
int fd = lws_get_socket_fd(wsi);
lws_get_peer_addresses(wsi, fd, name, 64, ip, 16);
```

However, I don't see a way to get that clients port. Is this possible?

**Comment by lws-team** [comment]
It has never seemed a very useful bit of information.

lws does get it during accept() in lib/server.c, it's written to cli_addr.

```
			clilen = sizeof(cli_addr);
			lws_latency_pre(context, wsi);
			accept_fd  = accept(pollfd->fd, (struct sockaddr *)&cli_addr,
					    &clilen);
			lws_latency(context, wsi, "listener accept", accept_fd,
```

If you want to pass stuff from cli_addr in the LWS_CALLBACK_FILTER_NETWORK_CONNECTION callback just after (user is unused) that sounds pretty cheap.  Please send a patch if so.

**Comment by tmarrinan** [comment]
I notice that in the comments it says: "There's no protocol selected yet so we issue this to protocols[0]". This means that the http callback is the only one to receive `LWS_CALLBACK_FILTER_NETWORK_CONNECTION` and I get two with two different port numbers (one from the webpage connecting to the http server and one from the WebSocket client connecting to the WebSocket server), but no real way to distinguish between them.

Is there a way to have a simple function to retrieve this (such as `lws_get_peer_addresses` or `lws_get_peer_simple`?

As a side note, I don't quite understand `lws_get_peer_simple`. When I do the following:

```
char ip[16];
const char *r = lws_get_peer_simple(wsi, ip, 16);
```

Both `r` and `ip` contain the client's IP address. I can't figure out from the documentation which to use use, or if they will ever be different.

As a suggestion, an extension similar to `lws_get_peer_simple` would be great:

```
void lws_get_peer_addr_port(struct lws *wsi, char *addr, int addrlen, unsigned int *port);
```

**Comment by lws-team** [comment]
Oh... I thought it was only available at accept().  But it seems you can get it from `getpeername()`.

In that case since you found how to get the socket fd from the wsi, why do you need any help from lws?

**Comment by tmarrinan** [comment]
Aha! That works:

```
socklen_t len;
struct sockaddr_storage addr;
char ipstr[INET6_ADDRSTRLEN];
int fd, port;

len = sizeof(addr);
fd = lws_get_socket_fd(wsi);

getpeername(fd, (struct sockaddr*)&addr, &len);

// deal with both IPv4 and IPv6:
if (addr.ss_family == AF_INET) {
    struct sockaddr_in *s = (struct sockaddr_in*)&addr;
    port = ntohs(s->sin_port);
    inet_ntop(AF_INET, &s->sin_addr, ipstr, INET6_ADDRSTRLEN);
} else { // AF_INET6
    struct sockaddr_in6 *s = (struct sockaddr_in6*)&addr;
    port = ntohs(s->sin6_port);
    inet_ntop(AF_INET6, &s->sin6_addr, ipstr, INET6_ADDRSTRLEN);
}

printf("Peer IP address: %s\n", ipstr);
printf("Peer port      : %d\n", port);
```

**Comment by tmarrinan** [comment]
Sorry - one more issue. It seems as though this info is not accessible on disconnect:

```
int fd;
struct sockaddr_storage addr;
socklen_t len = sizeof(addr);

switch (reason) {
    case LWS_CALLBACK_ESTABLISHED:
        fd = lws_get_socket_fd(wsi);
        getpeername(fd, (struct sockaddr*)&addr, &len);
        // ... rest of code to retrieve client ip and port
        // proper ip and port retrieved :)
        break;
    case LWS_CALLBACK_CLOSED:
        fd = lws_get_socket_fd(wsi);
        getpeername(fd, (struct sockaddr*)&addr, &len);
        // ... rest of code to retrieve client ip and port
        // junk ip and port retrieved :(
        break;
```

**Comment by lws-team** [comment]
... "junk" is coming because the fd is closed, and you don't check getpeername() return value either.  So it fails on invalid fd, addr etc are never written and trash from the stack is there instead.

As the name suggests LWS_CALLBACK_CLOSED is a notification the connection has been closed, there's nothing wrong about this outcome.

Since the connection client port is invariant, if you still care about what is used to be after the fd is closed, you can capture it in ESTABLISHED and store it in the pss as shown in the examples, store it in your own per-connection object or whatever.
