### ISSUE TITLE
Websocket and MQTT

### ISSUE THREAD

**Issue by beadon-SAT** [warmcat/libwebsockets#912]
Hi !  I am trying to get the MQTT broker working with SSL.  I am having a terrible time with what I think are libwebsocket error messages -- specifically I'm trying to figure out why 3 different clients cannot connect : (mosquitto_pub, mosquitto_sub and a python client using paho.mqtt.client ) , but a successful connection can be made by this client : http://www.hivemq.com/demos/websocket-client/ .

Can you help me understand what's going wrong in the attached logs ?  (I've set  websockets_log_level 255)

Failure:
client
mosquitto_pub -h mqtt.domain.com -p 8883 -t test --cafile /home/root/local_cert/COMODO_DV_SHA-256_bundle.crt -u "user" -P "pass" -m "hello world"

server
[mosquitto_broker_connection_error.log.txt](https://github.com/warmcat/libwebsockets/files/1049367/mosquitto_broker_connection_error.log.txt)

Compared to success:
[success_mosquitto.log.txt](https://github.com/warmcat/libwebsockets/files/1049375/success_mosquitto.log.txt)

**Comment by lws-team** [comment]
This is 'libwebsockets' not 'libmqtt'.

According to this you are sending non-http trash

```
1496461631: WSI_TOKEN_NAME_PART '' (mode=0) 1496461631: Unknown method - dropping
```

to lws.  That's not an lws problem...
