### ISSUE TITLE
More authentication steps before send http file

### ISSUE THREAD

**Issue by WebsocketUser** [warmcat/libwebsockets#913]
How to send mutual authentication before send http file?

The situation is like
client send POST data to server, server get post data in WS_CALLBACK_HTTP_BODY.
How to do the below steps in callback??
server check the POST data then send json data {status: 1} to client
client received data and send data authdata=123 back to server
server received data and response {authdata: 123} back to client
after client check authdata value from server, then start to download file.

how to do this??

**Comment by lws-team** [comment]
http is more or less stateless.  So your idea you will coordinate this multi-transaction sequence 'in the callback' alone - with http - isn't enough.  The browser side sequencing is the main thing that must be coordinated.

Basically there has to be a simple download url as usual, but with a requirement that extra validation data attached.  How it's attached, in the url itself, or as ?url=args, or POST data, or from a cookie, isn't critical.  But the callback will not send the download unless it likes the extra data.  The client either followed the sequencing and gave the right data along with the url access or it didn't.

Lws also supports basic auth if you just need something simple.

**Comment by WebsocketUser** [comment]
Could you help to provide me the basic auth  combined with download file in server and client side sample?

Now I have client and server side test program.
In client side, I use POST method to send parameters with 
lws_client_http_body_pending(wsi, 1);
lws_callback_on_writable(wsi);
then server received post data in LWS_CALLBACK_HTTP_BODY and then callback LWS_CALLBACK_HTTP_BODY_COMPLETION.

I have no idea when and where to do multi-transaction after receive post data in server side??

**Comment by lws-team** [comment]
It's not my job to do your job.

I would re-read what I said before because you don't seem to have absorbed the key point about http being stateless.  If it's just http you can sequence the client by moving what URL it will ask for next (and what additional data it sends according to client state), that's it.

**Comment by WebsocketUser** [comment]
I update my question, I know http being stateless. I will handle it.

The problem is after server side receiving the post data. I add one request send back to client in LWS_CALLBACK_HTTP_BODY_COMPLETION.

// lws_spa_finalize(pss->spa);
lws_add_http_header_status(wsi, HTTP_STATUS_OK, &p, end);
lws_add_http_header_by_token(wsi, WSI_TOKEN_HTTP_CONTENT_TYPE,
				                   (unsigned char *)"application/json", strlen("application/json"), &p, end);
lws_add_http_header_content_length(wsi, strlen("{"status":1}"), &p, end);
lws_finalize_http_header(wsi, &p, end);
lws_write(wsi, start, p - start, LWS_WRITE_HTTP_HEADERS);
lws_write(wsi, (unsigned char *)"{"status":1}" + LWS_PRE, strlen("{"status":1}"), LWS_WRITE_HTTP);

client side receive in callback sequences:
LWS_CALLBACK_EATABLISHED_CLIENT_HTTP
LWS_CALLBACK_RECEIVE_CLIENT_HTTP => call lws_http_client_read
LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ=>I add lws_callback_on_writable but not to call LWS_CALLBACK_CLIENT_HTTP_WRITABLE and then callback to LWS_CALLBACK_COMPLETED_CLIENT_HTTP and LWS_CALLBACK_CLOSED_CLIENT_HTTP close the transaction directly.

In client side, after receiving first transaction response from server, I add lws_callback_on_writable but not to callback LWS_CALLBACK_CLIENT_HTTP_WRITABLE and then close the transaction directly. Any steps goes wrong??
