### ISSUE TITLE
Problem with multiple vhosts

### ISSUE THREAD

**Issue by leonardorufino** [warmcat/libwebsockets#914]
I'm facing a problem where I create a lws_context and several lws_vhost (using LWS_SERVER_OPTION_EXPLICIT_VHOSTS).
When I receive a connection on any vhost, in accept function (lws_server_socket_service:2282) wsi->vhost points to the correct vhost.
But when my app's callback is called with LWS_CALLBACK_ESTABLISHED, the wsi->vhost points to another vhost (always the first created through lws_create_vhost).
Is this the correct behavior? Am I missing something?

**Comment by lws-team** [comment]
Have you named the vhosts according to their external hostname?

Disambiguating the vhosts either by Host: header or by SNI using TLS attempts to match using the vhost name.  If no joy it falls back to the first vhost (as does, eg, apache).

**Comment by leonardorufino** [comment]
Great!
I wasn't setting the vhost_name.
Thanks
