### ISSUE TITLE
More than one CA filepath

### ISSUE THREAD

**Issue by leonardorufino** [warmcat/libwebsockets#918]
I know I can have a large CA file, but I'd like to configure more than one, like two: one local and another copied from my browser, for instance.
I've seen that ssl_ca_filepath and client_ssl_ca_filepath only support one path each.
How can I do it?

**Comment by lws-team** [comment]
If you want to do something special, this is a good place

```
	LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS	= 22,
	/**< if configured for
	 * including OpenSSL support, this callback allows your user code
	 * to load extra certifcates into the server which allow it to
	 * verify the validity of certificates returned by clients.  user
	 * is the server's OpenSSL SSL_CTX* */
```

**Comment by leonardorufino** [comment]
That's what I needed!
I set ssl_ca_filepath and client_ssl_ca_filepath to NULL and called SSL_CTX_load_verify_locations more than once with my CA files from LWS_CALLBACK_OPENSSL_LOAD_EXTRA_SERVER_VERIFY_CERTS and LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS callbacks.
Thanks!
