### ISSUE TITLE
Question about LWS_PRE

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#925]
Hi, I'm new with Web Socket.

In this link(https://libwebsockets.org/lws-api-doc-master/html/group__sending-data.html)

it says

> This allows us to add protocol info before and after the data, and send as one packet on the network without payload copying, for maximum efficiency.

so I dug your code, found that it injects protocol header information(**not sure about extension info**), also found below comment in the code.

> give a chance to the extensions to modify payload the extension may decide to produce unlimited payload erratically

but still don't understand about meaning of "without payload copying". who decide copying payload? it is concerned with extension features which is specified in RFC?(I'm guessing that compression features can do something with it) or just kind of hack?

Thanks.

**Comment by lws-team** [comment]
If lws didn't require LWS_PRE valid buffer space before the pointer to lws_write(), it'd have to assemble the packet including the ws header preamble before sending it on the network.  That requires making the preamble and then copying the user payload after it.

With LWS_PRE requirement lws just creates the necessary ws header in the LWS_PRE region and sends that plus the original payload in place to the network stack.  It doesn't need a second buffer to assemble the header + data into.  And it doesn't copy the bulk payload.

**Comment by sorrowhill** [comment]
Thanks! it helps me alot :+1:
