### ISSUE TITLE
callback_http

### ISSUE THREAD

**Issue by arunkvnss** [warmcat/libwebsockets#927]
I have to implement a lws server on dump increment protocol, But in sample test server assosiated with libwesocket 2.2.0 says that, i have to keep "callback_http" as the first element. Actually websocket initially connect with "http Get" then switch to websocket, is that the reason y we keep so?

**Comment by lws-team** [comment]
The exact reason is we don't know which protocol the client and server will negotiate before the negotiation completes.  So for http traffic, before the ws upgrade negotiation, we use protocols[0].

For normal purposes, like http GET, actually you don't normally need to provide code any more, you can use lws mounts.  Take a look at test-server-v2.0.c.

**Comment by arunkvnss** [comment]
okay, And for ssl handshake if we need any extra certs we must have to add reason macro in callback_http, i guess. Actually in my case i need only dump_increment protocol.And i need to use the callback_http for loading extra chain certs. 

Is it possible to use websocket client (SSL) and server (SSL)  from multiple thread accessing the Libwebsockets version: 2.2.0 library ?,

**Comment by lws-team** [comment]
No.  The internal architecture is a single-threaded event loop.  That is poll() by default, but you can also use libuv/libevent/libev to get, eg, epoll() backend.

It's possible to ask for a 'callback on writable' on a wsi from another thread.  But to do it, you must hook ESTABLISHED / CLOSE to maintain your own wsi list, and do your own locking to manage access to that list.

**Comment by arunkvnss** [comment]
So it is not possible to use client, server from multiple thread.But actually i want to use the same.Is there any way to achieve this ?. or else i have to enable libev support to achieve this multi threaded functionality?

**Comment by lws-team** [comment]
Nope... libuv / libev / libevent are all architecturally single-threaded serialized event loops compatible with lws.

If you really must have multithreaded ws you are best to use something else.

**Comment by arunkvnss** [comment]
I dont want to use the client 'wsi' and server 'wsi' to be used from multiple thread,My client and server are independent,I want to know whether the library support for the multiple threaded action.

**Comment by arunkvnss** [comment]
so u mean to say libwebsocket does not support multithreaded action becz of libev/uv/event not supporting it ?

**Comment by arunkvnss** [comment]
I dont want to use the client 'wsi' and server 'wsi' to be used from multiple thread,My client and server are independent,I want to know whether the library support for the multiple threaded action.

**Comment by arunkvnss** [comment]
so you mean to say that i can not call "libwebsocket api" from multiple thread.

**Comment by lws-team** [comment]
I answered it clearly I think (even though I can't see what you want from the description).  Stuff happens in a single-threaded serialized event loop in lws.  That's not the fault of other event libraries that follow the same design, it's a design choice of lws which those other event libraries happen to share.

By doing so, using nonblocking sockets, there is no memory or other overhead of thread-per-connection and no need for locking and its overhead.  On small systems that may have many connections these are significant savings.

Ideally, client and server connections are on the same event loop.  So they occupy one thread total that services whatever is happening in a serialized way.

In particular, lws won't let you just randomly 'send' stuff on a connection.  You must ask for an event when you may next send something on the connection, and send it then.  This eliminates 'unbounded local buffering' for send data, again especially with multiple connections the resource savings are significant.

If that doesn't make any sense don't worry ^^  you should look for a different ws library that uses threaded / blocking semantics.
