### ISSUE TITLE
Question about difference between libuv and default io

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#930]
Hi again, 

Is there any benchmark, or performance data with libuv? how does libuv compare to default io? i think that big difference is in looping code, but i don't know how big it is...

Thanks

**Comment by lws-team** [comment]
libuv is just an OS-independent wrapper around whatever your OS provides.

In lws itself, we use poll() which is in Posix.  It's highly likely whatever you are building on provides some kind of poll().  But eg Linux provides epoll(), which has much better performance under load.  libuv (including libuv in lws) will use epoll() by default on Linux.

There is a similar situation in windows, they provide select() to be grudgingly posix-compatible (they don't even provide poll(), but we wrap select) but they provide some windows-only more efficient solution and again libuv on windows platform uses that.

So you are asking the wrong question, you should look for poll() vs epoll() information if your platform is Linux.

**Comment by sorrowhill** [comment]
Thanks. I was also looking for performance data between Windows and Linux.
