### ISSUE TITLE
Can libwebsockets generate pkg-config file automatically 

### ISSUE THREAD

**Issue by swordyang** [warmcat/libwebsockets#933]
make install not generate `websockets_static.pc` file, when I build libwebsockets 2.2.1 on msys2
so, i create a pkg-config file manually like following code
```
# Package Information for pkg-config

prefix=/home/Neo/prefix
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: websockets_static
Description: libwebsockets
Version: 2.2.1
Libs: -L${libdir} -lwebsockets_static
Libs.private: 
Cflags: -I${includedir}
```

Can libwebsockets generate pkg-config file automatically

**Comment by lws-team** [comment]
The patch referenced  (on master) should do it.
