### ISSUE TITLE
Catch and manage TLS Alert messages

### ISSUE THREAD

**Issue by daviddelage** [warmcat/libwebsockets#936]
Hi,
this is not really an issue. For a project, I need to implement a (WebSocket) server be aware about TLS Alert message as support in TLS protocol ( https://tools.ietf.org/html/rfc5246#section-7.2 ). Current, I did see any CALLBACK reason that allows developers to catch a such event. Is supported by libwebsocket API ?

Regards
David

**Comment by lws-team** [comment]
Please try the patch linked above on master.

There's information on how to use added to README.coding.md by the patch.

**Comment by lws-team** [comment]
... if you get any problem, feel free to post about it here.

**Comment by daviddelage** [comment]
Thanks a lot for this reactivity !!  I saw that code have been merged !
Question: I am not expert but I still working with the "old style" server ( with user call back ..... I have seen that it is not supported anymore ). Does need to migrate with the new style ( with plugins ). ?

**Comment by lws-team** [comment]
The old style still works and it's not "not supported".  It's just recommended to use the "v2.0" or lwsws style, because it's usually cleanly providing everything you need to do by hand the old way.

In particular this patch provides a callback for the alerts.

Also you do not have to use plugins at runtime if you don't want to.  The protocol plugin sources can be included statically as ESP32 does it, then you get the benefit of cleaner sources and protocol separation.

**Comment by JayRom33** [comment]
Hi, 
I'm working with daviddelage.
We also need to detect when the ClientHello message is received. We didn't find anything that could allow us to get this information, in the current implementation.
Do you know if it's currently possible ? If not, is it something that could easily be added ?
Thanks a lot.

**Comment by lws-team** [comment]
Dunno... that's really a question for openssl about if it notifies anyone.

SSL_CB_HANDSHAKE_START and SSL_CB_HANDSHAKE_DONE look like they would bracket it.

**Comment by JayRom33** [comment]
Thanks for your answer.
Finally I was able to detect the ClientHello message reception by using SSL_state_string() API in lws_ssl_info_callback() and adding a "state" field in lws_ssl_info structure.
The remaining issue is that it seems impossible to know from which Client (IP address) the message was received. But as you said, it's surely a question for openssl.

**Comment by lws-team** [comment]
Well, send a patch (or paste a diff) for your change.

The callback includes a wsi, this is the individual connection object in lws the ssl info event relates to.  You can get the connection IP from it using:

```
/**
 * lws_get_peer_simple() - Get client address information without RDNS
 *
 * \param wsi:	Local struct lws associated with
 * \param name:	Buffer to take client address name
 * \param namelen:	Length of client address name buffer
 *
 * This provides a 123.123.123.123 type IP address in name from the
 * peer that has connected to wsi
 */
LWS_VISIBLE LWS_EXTERN const char *
lws_get_peer_simple(struct lws *wsi, char *name, int namelen);
```

**Comment by JayRom33** [comment]
Yes I will send a patch asap (surely tomorrow).

I've already tried to use the lws_get_peer_simple() function but it always returns the IP address of the server.
Maybe I'm missing something.

**Comment by lws-team** [comment]
Hard to see how that can happen, unless the client is on the same machine.  It boils down to calling `getpeername()`.

http://man7.org/linux/man-pages/man2/getpeername.2.html

**Comment by JayRom33** [comment]
Here are the diff.

In libwebsockets.h, added a new field "ssl_state" in the "lws_ssl_info" structure :
`struct lws_ssl_info {
	int where;
	int ret;
	const char *ssl_state;
};
`
In ssl.c, added the following line in lws_ssl_info_callback() function :
`si.ssl_state = SSL_state_string(ssl);
`

I've noticed that during all the TLS handshake operation, the lws_get_peer_simple() API doesn't give the client's address but the server's one (although they are not on the same machine).
I've also tried to use directly getpeername() in lws_ssl_info_callback() and the result is the same.

**Comment by lws-team** [comment]
Thanks.

1) When people ask for a diff, and you are using giit, they just mean the relevant parts of the output of `git diff`.  It's structured in such a way they can feed it into `patch -p1 --merge < yourdiff` and apply it directly to the same code, capturing it as a patch without any errors through describing it or redoing it etc.

2) You don't need to hack this in.  In the callback, you have the wsi.  You can get the related SSL object from the wsi using

```
LWS_VISIBLE LWS_EXTERN SSL*
lws_get_ssl(struct lws *wsi);
```

then you can get the state string directly from that.

**Comment by JayRom33** [comment]
Hi.

Please forget all I said about the fact that I was not able to retrieve the client's address. My test was wrong and I'm actually able to retrieve it thanks to lws_get_peer_simple().

Thanks for the tip about getting the SSL object from the wsi. It works as expected.

Just another question if possible : it seems like p_user is NULL when the callback is LWS_CALLBACK_SSL_INFO or LWS_CALLBACK_USER but correct when the callback is ESTABLISHED, SERVER_WRITEABLE or RECEIVE ? Is this normal ?

**Comment by lws-team** [comment]
For a ws connection, user data isn't allocated until the protocol has been negotiated.  Because the different protocols may have different sized allocations.
