### ISSUE TITLE
Comments below declaration

### ISSUE THREAD

**Issue by rickynelson1939** [warmcat/libwebsockets#938]
I was looking into libwebsockets source code and I stumble across these comments:
```
	LWS_CALLBACK_RAW_RX					= 59,
	/**< RAW mode connection RX */
	LWS_CALLBACK_RAW_CLOSE					= 60,
	/**< RAW mode connection is closing */
```
At first I tried to remind myself every time - "read below declaration", but I'm frighteningly often did find myself in position where I was thinking "Hmm, those comments doesn't make any sense. Oh, wait...". So... my question is: Is there any way I can turn this comments into "comments above declaration", I'm not criticising your code style, It's just my issue, but I never met this type of comments before and I thought, maybe I should ask this at libwebsockets github. Or maybe you can give me at least some psychological advice on how to deal with this?

**Comment by lws-team** [comment]
What can I say when life is that cruel to put comments directly after the declaration.

Actually this cruelty is very common, eg

```
  int myvar; /* myvar does this and that */
```

The comments are structured for doxygen https://en.m.wikipedia.org/wiki/Doxygen

You can read them html-formatted at the link in the README.md, eg

https://libwebsockets.org/lws-api-doc-master/html/group__usercb.html

The description is to the right of the enum member name there.  I dunno if that is just a new dimension of suffering but we all have our crosses to bear.
