### ISSUE TITLE
Question about attaching a ssl socket on ssl server

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#939]
Hi again,

As i said before, i'm writing the code that creates web socket client dynamically and attach to running server that configured SSL. 

The problem is that web socket with ssl is unable to attach with the server with ssl, because of below code in lib/ssl-client.c

	if (info->port != CONTEXT_PORT_NO_LISTEN)
		return 0;

I also tested and it works well when a socket is created with no-ssl options. so i'm looking for a way to use vhost(probably the best?),  but i wish to know about above code, why it is there, for what...

**Comment by lws-team** [comment]
It seems you are already aware of the need to call `lws_init_vhost_client_ssl()` to allow a vhost to perform ssl client operations.

You can work around that code by just setting `info.port = CONTEXT_PORT_NO_LISTEN;` before that call... .port has no meaning for the call... I think that check is pointless now and if so I will remove it.
