### ISSUE TITLE
Older docs (1.7.3)

### ISSUE THREAD

**Issue by Cl1608Ho** [warmcat/libwebsockets#941]
Hey there, any chance to find older docs, specifically for version 1.7(.3)?

Thanks in advance

**Comment by lws-team** [comment]
Docs were in the tree at that time

https://github.com/warmcat/libwebsockets/blob/v1.7.3/libwebsockets-api-doc.html

Load the file in a browser.

1.7.3 is a bad idea since the fixes are up to 1.7.9 and master will be 2.3...

**Comment by Cl1608Ho** [comment]
Well I've seen that but it's not much, I'm especially interested in stuff for the callback, etc etc etc. 

I'm using the Version shipped with the unreal engine 4, which is 1.7.3 unfortunately, but I may open a ticket and request they update the Version. Shouldn't be too much work for them.

**Comment by lws-team** [comment]
The docs were overhauled for v2.1, after that there is doxygen-compatible comments inline for everything.  So upgrading to something more modern (and thinking about a plan to keep it updated with security and other fixes on the stable branch...) would be a good idea all around.
