### ISSUE TITLE
How to know if a websocket server listens on a used port?

### ISSUE THREAD

**Issue by yjjnls** [warmcat/libwebsockets#942]
I ran two processes of the same websocket server code, hence the two servers listened on the same port. But the latter will not alarm and can not receive connections or messages. When the former server closed, the latter one can operate normally. 
How could I know if a websocket server listens on a used port?

**Comment by lws-team** [comment]
Are you on Linux?

It should be enough to make sure LWS_MAX_SMP is set to 1 in cmake.

**Comment by yjjnls** [comment]
I will use it on both Linux and Windows, but I tested it on Windows.
After set LWS_MAX_SMP to in cmake and compile again. The test result has't changed, the second server could still listen on the same port without any alarm.

**Comment by lws-team** [comment]
Uhhhh windows being windows

On Linux SO_REUSEADDR does this

```
       SO_REUSEADDR
              Indicates that the rules used in validating addresses supplied
              in a bind(2) call should allow reuse of local addresses.  For
              AF_INET sockets this means that a socket may bind, except when
              there is an active listening socket bound to the address.
              When the listening socket is bound to INADDR_ANY with a
              specific port then it is not possible to bind to this port for
              any local address.  Argument is an integer boolean flag.
```

http://man7.org/linux/man-pages/man7/socket.7.html

So it will refuse to bind and error out during vhost creation if the interface + port already has a listener.  You can override it and get the sockets to round-robin share accepts on the same port (that happens with LWS_MAX_SMP > 1 and multiple service threads in use).

On Windows, it's some long story version by version

https://msdn.microsoft.com/zh-tw/library/windows/desktop/ms740621(v=vs.85).aspx

Basically

```
Using SO_REUSEADDR

The SO_REUSEADDR socket option allows a socket to forcibly bind to a port in use by another socket. The second socket calls setsockopt with the optname parameter set to SO_REUSEADDR and the optval parameter set to a boolean value of TRUE before calling bind on the same port as the original socket. Once the second socket has successfully bound, the behavior for all sockets bound to that port is indeterminate. For example, if all of the sockets on the same port provide TCP service, any incoming TCP connection requests over the port cannot be guaranteed to be handled by the correct socket — the behavior is non-deterministic. A malicious program can use SO_REUSEADDR to forcibly bind sockets already in use for standard network protocol services in order to deny access to those service. No special privileges are required to use this option.

If a client application binds to a port before a server application is able to bind to the same port, then problems may result. If the server application forcibly binds using the SO_REUSEADDR socket option to the same port, then the behavior for all sockets bound to that port is indeterminate.

The exception to this non-deterministic behavior is multicast sockets. If two sockets are bound to the same interface and port and are members of the same multicast group, data will be delivered to both sockets, rather than an arbitrarily chosen one.
```

So that is broken.

They added a platform-specific hack `SO_EXCLUSIVEADDRUSE` (explained on same webpage) after NT4 SP4 and call that "enhanced security"... obviously that is just "normal security" that was totally lacking until then.

I added a patch above on master, which uses `SO_EXCLUSIVEADDRUSE` alone on windows... I am not sure if it should additionally use SO_REUSEADDR, but please give that a go.

**Comment by yjjnls** [comment]
It's a good idea to use SO_EXCLUSIVEADDRUSE. But SO_EXCLUSIVEADDRUSE is already defined, hence the service will use it certainly on Windows. I think it's better to use a newly defined macro to let users choose weather to use SO_EXCLUSIVEADDRUSE or SO_REUSEADDR.

**Comment by lws-team** [comment]
The patch as it is fixes your problem?

**Comment by yjjnls** [comment]
Yes, the second server listens on the used port will raise error.

**Comment by lws-team** [comment]
Thanks.

Why is anyone going to choose to not have `SO_EXCLUSIVEADDRUSE` though?  If you have a minute checking if setting both in windows case works sanely would be good... if so we should just do that I think.

Note you will have to set `opt = 1` again before executing the second `setsockopt()`.

**Comment by yjjnls** [comment]
I have tested and they can't be set both. An error `reuseaddr failed` will be raised even just run one server.
I think some need to restart the server immediately when the process crashed, `SO_REUSEADDR` is suitable for them. While in my use case, I provide the server component for others, they may listen on a used port and it's important to alarm their mistakes.

**Comment by lws-team** [comment]
OK the updated patch changes windows platform stuff to default to exclusive listen by default, that is to match the Linux situation.

You can then use an `options` flag on the vhost creation info `LWS_SERVER_OPTION_ALLOW_LISTEN_SHARE` to force it to be less strict, on either platform it should do the same then.

**Comment by lws-team** [comment]
I assumed that solved it then...
