### ISSUE TITLE
libev support

### ISSUE THREAD

**Issue by jonowoodward1986** [warmcat/libwebsockets#947]
Hello,

I have been using a poll implementation of libwebsockets for several months now with a lot of success. 
I have just decided to port libev to my event manager so I can get rid of the second thread that libwebsockets is running enabling to have a single threaded application.

I was wondering how libev is configured into the library? I removed my poll setup and added the ev example from the test server but it can no find the lws_ev functions?

error: implicit declaration of function 'lws_ev_initloop'

Forgive me if I am missing the obvious.

**Comment by lws-team** [comment]
If you want to build for libev, the main thing is add to cmake -DLWS_WITH_LIBEV=1 and rebuild lws.  That causes it to build the libev bits into the lws library as you need.

You also need to apply the context creation options flag LWS_SERVER_OPTION_LIBEV, you probably saw that already as part of bringing over the libev test server pieces.

lws running with poll() doesn't have to mean a second thread.  But if you like the idea of libev for other reasons no worries.

**Comment by jonowoodward1986** [comment]
Okay I have tried adding -DLWS_WITH_LIBEV=1 to cmake and got the following error:

libwebsockets/test-server/test-server-libev.c:305:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   _ev_init(&signals[n], signal_cb);

libwebsockets/test-server/test-server-libev.c:373:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  _ev_timer_init(&timeout_watcher, ev_timeout_cb, 0.05, 0.05);

Not an error I have come across before.

**Comment by jonowoodward1986** [comment]
Using the second thread was more libwebsockets working with my existing epoll event manager.

**Comment by lws-team** [comment]
Yeah the author of libev claims that is a gcc problem.  For the last 9 years...

http://lists.schmorp.de/pipermail/libev/2008q4/000442.html

**Comment by lws-team** [comment]
For what it's worth, when I read the above originally, I decided to use libuv (which has no such problems) instead of libev for the features in lws that needs to pick an event loop.

**Comment by jonowoodward1986** [comment]
How can I get round this? Problem I have is that I am supporting a 3 year old rootfs with a very old libuv libuv-0.11.29. The library has change a lot since this point.

**Comment by jonowoodward1986** [comment]
`[ 29%] Building C object CMakeFiles/websockets.dir/lib/libuv.c.o
cc1: warnings being treated as errors
/home/jwoodward/projects/heatingsave/libwebsockets/lib/libuv.c: In function ‘lws_io_cb’:
/home/jwoodward/projects/heatingsave/libwebsockets/lib/libuv.c:103:2: error: passing argument 2 of ‘uv_idle_start’ from incompatible pointer type
/usr/include/uv.h:1406:15: note: expected ‘uv_idle_cb’ but argument is of type ‘void (*)(struct uv_idle_t *, int)’
/home/jwoodward/projects/heatingsave/libwebsockets/lib/libuv.c: In function ‘lws_uv_initloop’:
/home/jwoodward/projects/heatingsave/libwebsockets/lib/libuv.c:248:11: error: passing argument 2 of ‘uv_timer_start’ from incompatible pointer type
/usr/include/uv.h:1465:15: note: expected ‘uv_timer_cb’ but argument is of type ‘void (*)(struct uv_timer_t *, int)’
make[2]: *** [CMakeFiles/websockets.dir/lib/libuv.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2`

**Comment by lws-team** [comment]
Well... for your old libev you can just hack out `-Werror` from CMakeLists.txt.

Your ancient libuv is just too old for lws, the libuv api has changed from the modern one we target.

But of course if you have a 3 year old rootfs, you will have all kinds of dire security problems.  So it might be worth thinking about a way to update that ongoing.

**Comment by jonowoodward1986** [comment]
Okay thanks. I will see if I can upgrade the rootfs without damaging to much.
I just tried building the latest libuv and bumped into a few issues.
