### ISSUE TITLE
libwebsockets_get_peer_addresses() returning an empty name and ip

### ISSUE THREAD

**Issue by orenzvuluni** [warmcat/libwebsockets#949]
Hi,
I have libwebsockets server and i want to get each client name and ip.
i read here that libwebsockets_get_peer_addresses() function will do the work but its returning empty data.

i using this function in my callback inside LWS_CALLBACK_ESTABLISHED case.
here my code:

`static int callback_websockets(struct libwebsocket_context *context, struct libwebsocket *wsi,
			enum libwebsocket_callback_reasons reason,  void *user, void *in, size_t len)
{
	......
	int clientIpLen = 20;
	int clientNameLen = 40;
	char clientIp[20];
	char clientName[40];
	switch(reason)
	{

		case LWS_CALLBACK_ESTABLISHED:
			......
			printf("LWS_CALLBACK_ESTABLISHED\n");

			libwebsockets_get_peer_addresses(context, wsi, libwebsocket_get_socket_fd(wsi),
									clientName, sizeof(clientName),
								  clientIp, sizeof(clientIp));

			printf("Received network connect from %s (%s)\n",
                                    clientName, clientIp);
                    .......
                     break;
                    .......

`

thanks,
Oren

**Comment by lws-team** [comment]
What platform is this running on?

**Comment by orenzvuluni** [comment]
it's running on linux.

**Comment by lws-team** [comment]
Glibc or a different libc?

What's your situation for local DNS resolution?

For example if you try to ping that IP from the same machine, what does it say?

**Comment by orenzvuluni** [comment]
i think its a libc, i found only libc.so.*  on my machine and when i type ./libc.so.6 i got:

**root@varsomam33:/lib# ./libc.so.6 
GNU C Library (Ubuntu EGLIBC 2.15-0ubuntu10) stable release version 2.15, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.6.3.
Compiled on a Linux 3.2.14 system on 2012-04-19.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        Support for some architectures added on, not maintained in glibc core.
        BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, plea<http://www.debian.org/Bugs/>.**


when i ping from my machine to the client ip:

**root@varsomam33:/lib# ping 192.168.147.123
PING 192.168.147.123 (192.168.147.123): 56 data bytes
64 bytes from 192.168.147.123: seq=0 ttl=128 time=1.136 ms
64 bytes from 192.168.147.123: seq=1 ttl=128 time=0.614 ms
64 bytes from 192.168.147.123: seq=2 ttl=128 time=0.736 ms
64 bytes from 192.168.147.123: seq=3 ttl=128 time=0.646 ms
64 bytes from 192.168.147.123: seq=4 ttl=128 time=0.563 ms
^C
--- 192.168.147.123 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.563/0.739/1.136 ms**

**Comment by lws-team** [comment]
You are using some unimaginably ancient version of lws?

```
libwebsockets_get_peer_addresses
```

**Comment by orenzvuluni** [comment]
I am using version 1.3(it's unimaginably ancient....?)

**Comment by lws-team** [comment]
Yeah.... last release is v2.2, master is well along to becoming v2.3.

Most projects only care about their last release and stable... I will update things back to v2.0-stable and occasionally still v1.7-stable.  But even if you find a bug in v1.3, if it isn't in a current or even recent version nobody is going to take care about it.

**Comment by orenzvuluni** [comment]
O.K, i will upgrade! 
Thanks a lot for the quick responses.
Oren

**Comment by orenzvuluni** [comment]
I upgraded to 2.2 stable  version and the problem didn't solved.
I still get empty answer for the command.
what it's can be....?

**Comment by lws-team** [comment]
Dunno, but I would guess something about your DNS arrangements on that machine.

If you run `libwebsockets-test-server -d15` and connect to `http://localhost:7681` in your browser, if you built with DEBUG cmake option (see README.build.md) you will get a log like

````
lwsts[5255]: HTTP connect from ::1
```

this is coming out of `ws_get_peer_addresses()`.

Forget your old target machine for a minute, do you get the same result on your build machine?

**Comment by orenzvuluni** [comment]
it's working on my build machine(my laptop) and i get the ip of other PC that connecting to the server.

**Comment by lws-team** [comment]
Then there's something up with your target machine name resolution.  That's nothing really to do with lws but /etc/resolv.conf, /etc/nsswitch.conf and /etc/hosts are good places to look.  If the target gets its ip from dhcp usually it will set /etc/resolv.conf to the dhcp server's preferred dns server.  Nsswitch.conf tells the libc where to go for name resolution.  And your libc itself would need to be non-broken.

**Comment by orenzvuluni** [comment]
So the problem exist only when my device is in  NFS state(The file system is on remote PC. it's very comfortable for developing like this).
When i am the fs is on the device flash, it's work,
just a little thing...instead of name i get the ip again:
`Received network connect from 192.168.147.110 (192.168.147.110)`
Is this O.K or i'ts dhcp server definitions?
