### ISSUE TITLE
Truncated large messages when compression is enabled

### ISSUE THREAD

**Issue by Boutoukoat** [warmcat/libwebsockets#951]
As the title mentions, I get easily frequent truncated messages in my client code. Their pattern is invariably the same : rx_buffer_size bytes are ok, plenty byte missing, rx_buffer_size bytes ok, plenty bytes missing .....

This strongly seems to be related to #486 and #593 

Invariably, I found that failing frames where processed within client.c and successful frames where processed within service.c code.

After investigating, the problem comes from lws_remove_wsi_from_draining_ext_list() being called from lws_rx_sm(), without passing the corresponding buffer to the callback. 

Here is a suggested fix (there is already similar code in service.c)

```
$ diff -Naur libwebsockets-master/lib libwebsockets-dev/lib
--- libwebsockets-master/lib/client.c	2017-03-29 01:22:19.000000000 +0100
+++ libwebsockets-dev/lib/client.c	2017-06-28 14:22:30.435180263 +0100
@@ -42,6 +42,9 @@
 				return 0;
 			}
 			if (wsi->u.ws.rx_draining_ext) {
+                            if (wsi->mode == LWSCM_WS_CLIENT)
+                                m = lws_client_rx_sm(wsi, 0);
+                            else
 				m = lws_rx_sm(wsi, 0);
 				if (m < 0)
 					return -1;
$ 

```
Please confirm that this makes sense. 
The whole fix would probably include #ifndef LWS_NO_CLIENT

**Comment by lws-team** [comment]
Thanks, it's pushed on master.
