### ISSUE TITLE
[esp32] Does not find libwebsockets.h when the path gets too long

### ISSUE THREAD

**Issue by johsely1234** [warmcat/libwebsockets#956]
I can compile my esp32 project without problems. 
But if I change the path to a longer path (I just copied it there) and rebuild it, it won't compile anymore => fatal error: libwebsockets.h: No such file or directory

I copied it one folder up, and it worked again.

What could be the problem here?

**Comment by lws-team** [comment]
So what was it trying to compile?

How long is 'longer path' exactly?

Did you copy ./build, or regenerate a clean empty dir there in the new destination?

Afaik nothing in the build system should be especially fragile to path length.

**Comment by johsely1234** [comment]
I have a modified version of the esp32-factory app. (but only modified the sources not the build system)

/home/esp32dev/esp/orcaSVN/ABC/ABCGenius/esp32/trunc/lws_server => not working
/home/esp32dev/esp/orcaSVN/ABC/ABCGenius/esp32/lws_server => not working
/home/esp32dev/esp/orcaSVN/ABC/ABCGenius/lws_server => working

I made a make clean and rm -rf build/ every time after copying.

Probably its also on espressif side, but I don't know... the examples also have a very long path

Sorry for responding so late, a lot of other things to do...

**Comment by lws-team** [comment]
I could reproduce it... it should be fixed (at least for 6 or so more directory levels deep)

**Comment by johsely1234** [comment]
Yes it works now, thanks!
