### ISSUE TITLE
Websocket server is receiving "LWS_CALLBACK_WSI_DESTROY" event when client(Android) tries to send any data

### ISSUE THREAD

**Issue by yashwanth999** [warmcat/libwebsockets#958]
Scenerio:

- I'm running a libwebsocket server in an  Embedded platform in port (7070) which is listening to  a client.
- I'm connecting an Android app client to the particular port in the server.
- "LWS_CALLBACK_WSI_CREATE" event is received in the server; and able to  connect to  client.
- But when I tried sending some data to Sever . (No any data is received ) "LWS_CALLBACK_RECEIVE" event  is no where getting triggered.

**after "LWS_CALLBACK_WSI_CREATE" is  called; without any intervention "LWS_CALLBACK_WSI_DESTROY"  is getting triggered in the server side.**

**Issue**: "LWS_CALLBACK_WSI_DESTROY" is getting called automatically without any input from the client.

**Server side logs:**
LWSServer::__callback (this=0xc563fd0, context=0xc5682e8, wsi=0xc585368, reason=LWS_CALLBACK_WSI_CREATE, user=0x0, in=0x0, len=0)

new connection created  : debug print to ensure connection is created

 LWSServer::__callback (this=0xc563fd0, context=0xc5682e8, wsi=0xc585368, reason=LWS_CALLBACK_WSI_DESTROY, user=0x0, in=0x0, len=0) 
 
**"LWS_CALLBACK_WSI_DESTROY" is  getting triggered automatically after 4 seconds.**

Pls help  me in resolving  the Issue.

Any comment/help is much appreciated.

Thanks in Advance.
Thanks and Regards,
Yashwanth

**Comment by lws-team** [comment]
Well this is a very incomplete story.  You don't show any lws logging.

Many other callbacks are occurring if you get to the point of getting a WRITABLE callback, so you can send something.

ESTABLISHED callback must be coming for example.

Create / Destroy callbacks just indicate a wsi was created and destroyed.

Why don't you set cmake for DEBUG build (see README.build.md) and increase the logging verbosity, 65535 debugging level will show you everything.

**Comment by yashwanth999** [comment]
Thanks for the Comments.

Actually Issue is the Android Client itself. (improper usage of methods in Android to send messages to  the Server)

thanks for the response.!!
