### ISSUE TITLE
Failed to connect to git.libwebsockets.org

### ISSUE THREAD

**Issue by kiokumicu** [warmcat/libwebsockets#965]
Hi!
Got error

> curl: (7) Failed to connect to git.libwebsockets.org port 80: Connection refused
> Error: Failed to download resource "libwebsockets"
> Download failed: http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/snapshot/libwebsockets-1.6.2.tar.gz

**Comment by lws-team** [comment]
Our cgit moved a couple of years ago to

https://warmcat.com/git/libwebsockets/

**Comment by kiokumicu** [comment]
Hm, I'm use 
`brew install mosquitto`

**Comment by kiokumicu** [comment]
Problem solved with brew ugrade

**Comment by lws-team** [comment]
Super.
