### ISSUE TITLE
How to stop a particular websocket server running with at a port.

### ISSUE THREAD

**Issue by yashwanth999** [warmcat/libwebsockets#968]
Hi Team,

Actually my application runs with multiple WS servers on different ports using multi-threading.

I'm staring 3 different WS  servers at independent ports  say 7070,8080 & 9090.

**Issue:**
What is the way to Stop a particular Ws server...?

I can see **"libwebsocket_context_destroy"**  which contains only "context" argument to it.

Thanks in Advance..!!

**Comment by lws-team** [comment]
There is a brand new lws_destroy_vhost() on master.

**Comment by yashwanth999** [comment]
Thanks ..!!

**Is there any way in the older version ...?** Since my Stack is tightly coupled with the old version.
Its very difficult for me to  migrate to  new version in my existing Eco-system.

pls suggest a way for older versions ...


Thank you...:)

**Comment by lws-team** [comment]
nope.

**Comment by yashwanth999** [comment]
So you mean to say  Older version of LWS library has no capability to Stop a particular running server.

Migrating to the new LWS-master is it the only way??

But in my case I'm able to manage  to open and communicate multiple servers at different ports.

**Question is using older version of LWS I can work on multiple servers right ?**
**in that case definitely there should be provision to close a particular server at a port .  isn't it ???**

**Comment by lws-team** [comment]
Correct me if I am wrong, but you have never contributed anything to this project.

You never asked for this feature until today.

You don't pay me.

Lws is mainly my work but also made up from the contributions of 140 others who either fixed stuff or provided implementations of missing features they wanted.

Why don't you step down from your entitlement bus and send a patch for the feature you want (on some random old version, yet).  Or update and leech the feature off master.

You are welcome.

**Comment by yashwanth999** [comment]
Sorry, pls don't mistake me.

As I said before, I have cloned and integrated the LWS library onto my Stack.
I'm very Thankfull to LWS. no second thought on it.

I just want  to confirm whether I can stop the running server w/o migrating the library.

Kindly don't mistake my words..
