### ISSUE TITLE
Locking up using http

### ISSUE THREAD

**Issue by jonowoodward1986** [warmcat/libwebsockets#969]
I am running a service which has a HTTP POST sent to it every few seconds, after a while of running the service just stops and outputs nothing at all.

This is on version 2.1.0 as shown below:

```
[2017/07/18 12:51:55:1650] NOTICE: Initial logging level 7
[2017/07/18 12:51:55:1652] NOTICE: Libwebsockets version: 2.1.0 root@localhost-v2.0.0-213-gdd0dfae
[2017/07/18 12:51:55:1652] NOTICE: IPV6 not compiled in
[2017/07/18 12:51:55:1653] NOTICE: libev support not compiled in
[2017/07/18 12:51:55:1654] NOTICE: libuv support compiled in and enabled
[2017/07/18 12:51:55:1656] NOTICE:  Threads: 1 each 1024 fds
[2017/07/18 12:51:55:1657] NOTICE:  mem: platform fd map:  8192 bytes
[2017/07/18 12:51:55:1658] NOTICE:  Compiled with OpenSSL support
[2017/07/18 12:51:55:1658] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/07/18 12:51:55:1659] NOTICE: Creating Vhost 'default' port 7682, 3 protocols, IPv6 off
[2017/07/18 12:51:55:1660] NOTICE:  Listening on port 7682
[2017/07/18 12:51:55:1661] NOTICE:  mem: per-conn:          736 bytes + protocol rx buf
[2017/07/18 12:51:55:1661] NOTICE:  canonical_hostname = xxxxxxx
[2017/07/18 12:51:55:1662] NOTICE:  Using foreign event loop...
```

Because of this I thought I would try the latest stable version but I am unable to build the library.

```
Searching for OpenSSL executable and dlls                        
OpenSSL executable: /usr/bin/openssl                             
 GENCERTS = 1                                                              
Generating SSL Certificates for the test-server...                      
SUCCESSFULLY generated SSL certificate                        
-- Looking for RPMTools... - rpmbuild NOT FOUND                      
---------------------------------------------------------------------
  Settings:  (For more help do cmake -LH <srcpath>)             
---------------------------------------------------------------------   
 LWS_WITH_STATIC = ON                                            
 LWS_WITH_SHARED = ON                                                      
 LWS_WITH_SSL = ON (SSL Support)                                    
 LWS_SSL_CLIENT_USE_OS_CA_CERTS = 1                                                    
 LWS_USE_WOLFSSL = OFF (wolfSSL/CyaSSL replacement for OpenSSL)  
 LWS_WITHOUT_BUILTIN_SHA1 = OFF                                    
 LWS_WITHOUT_BUILTIN_GETIFADDRS = OFF              
 LWS_WITHOUT_CLIENT = OFF     
 LWS_WITHOUT_SERVER = OFF                 
 LWS_LINK_TESTAPPS_DYNAMIC = OFF                                        
 LWS_WITHOUT_TESTAPPS = OFF                             
 LWS_WITHOUT_TEST_SERVER = OFF                                           
 LWS_WITHOUT_TEST_SERVER_EXTPOLL = OFF                                        
 LWS_WITHOUT_TEST_PING = OFF                                            
 LWS_WITHOUT_TEST_ECHO = OFF                                 
 LWS_WITHOUT_TEST_CLIENT = OFF                               
 LWS_WITHOUT_TEST_FRAGGLE = OFF                              
 LWS_WITHOUT_EXTENSIONS = OFF                                
 LWS_WITH_LATENCY = OFF                                           
 LWS_WITHOUT_DAEMONIZE = ON                                  
 LWS_USE_LIBEV =                                                                                          
 LWS_USE_LIBUV = 1                                                            
 LWS_IPV6 = OFF                                                            
 LWS_UNIX_SOCK = OFF                                                        
 LWS_WITH_HTTP2 = OFF                                                
 LWS_SSL_SERVER_WITH_ECDH_CERT = OFF                                                  
 LWS_MAX_SMP = 32                                                   
 LWS_WITH_CGI = OFF                                                                   
 LWS_HAVE_OPENSSL_ECDH_H = 1                                        
 LWS_HAVE_SSL_CTX_set1_param = 1                                    
 LWS_WITH_HTTP_PROXY = OFF                                                     
 LIBHUBBUB_LIBRARIES =                                                     
 PLUGINS =                                                             
 LWS_WITH_ACCESS_LOG = OFF                                         
 LWS_WITH_SERVER_STATUS = OFF                                             
 LWS_WITH_LEJP = OFF                                               
 LWS_WITH_LEJP_CONF = OFF                                              
 LWS_WITH_SMTP = OFF                                             
 LWS_WITH_GENERIC_SESSIONS = OFF                                          
 LWS_STATIC_PIC = OFF                                            
 LWS_WITH_RANGES = ON                                            
 LWS_PLAT_OPTEE = OFF                                            
 LWS_WITH_ESP32 = OFF                                             
 LWS_WITH_ZIP_FOPS = ON                                               
---------------------------------------------------------------------
-- Configuring done                                                                                            
-- Generating done                        
-- Build files have been written to: /home/jwoodward/projects/libwebsockets/build           
0 jwoodward@Arch ~/projects/libwebsockets/build $ make   
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  2%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  3%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  4%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[  6%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[  7%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[  8%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[  9%] Building C object CMakeFiles/websockets.dir/lib/context.c.o
[ 11%] Building C object CMakeFiles/websockets.dir/lib/alloc.c.o
[ 12%] Building C object CMakeFiles/websockets.dir/lib/header.c.o
[ 13%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 14%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 16%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 17%] Building C object CMakeFiles/websockets.dir/lib/ssl.c.o
[ 18%] Building C object CMakeFiles/websockets.dir/lib/ssl-server.c.o
[ 19%] Building C object CMakeFiles/websockets.dir/lib/ssl-client.c.o
[ 20%] Building C object CMakeFiles/websockets.dir/lib/sha-1.c.o
[ 22%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-unix.c.o
[ 23%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 24%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/extension-permessage-deflate.c.o
[ 28%] Building C object CMakeFiles/websockets.dir/lib/ranges.c.o
[ 29%] Building C object CMakeFiles/websockets.dir/lib/fops-zip.c.o
[ 30%] Linking C static library lib/libwebsockets.a
[ 30%] Built target websockets
Scanning dependencies of target test-fuzxy
[ 32%] Building C object CMakeFiles/test-fuzxy.dir/test-server/fuzxy.c.o
[ 33%] Linking C executable bin/libwebsockets-test-fuzxy
lib/libwebsockets.a(libwebsockets.c.o): In function `lws_close_free_wsi':
libwebsockets.c:(.text+0x1825): undefined reference to `lws_libuv_closehandle'
lib/libwebsockets.a(pollfd.c.o): In function `lws_change_pollfd.part.1':
pollfd.c:(.text+0x310): undefined reference to `lws_libuv_io'
pollfd.c:(.text+0x348): undefined reference to `lws_libuv_io'
pollfd.c:(.text+0x380): undefined reference to `lws_libuv_io'
pollfd.c:(.text+0x3b8): undefined reference to `lws_libuv_io'
lib/libwebsockets.a(pollfd.c.o): In function `_lws_change_pollfd':
pollfd.c:(.text+0x579): undefined reference to `lws_libuv_io'
lib/libwebsockets.a(pollfd.c.o):pollfd.c:(.text+0x591): more undefined references to `lws_libuv_io' follow
lib/libwebsockets.a(client-handshake.c.o): In function `lws_client_connect_2':
client-handshake.c:(.text+0x439): undefined reference to `lws_libuv_accept'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `_lws_plat_service_tsi':
lws-plat-unix.c:(.text+0x20d): undefined reference to `lws_libuv_run'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_insert_socket_into_fds':
lws-plat-unix.c:(.text+0x899): undefined reference to `lws_libuv_io'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_delete_socket_from_fds':
lws-plat-unix.c:(.text+0x8e9): undefined reference to `lws_libuv_io'
lib/libwebsockets.a(lws-plat-unix.c.o): In function `lws_plat_init':
lws-plat-unix.c:(.text+0xbab): undefined reference to `lws_libuv_init_fd_table'
lib/libwebsockets.a(context.c.o): In function `lws_context_destroy.part.2':
context.c:(.text+0xdaf): undefined reference to `lws_libuv_destroyloop'
lib/libwebsockets.a(context.c.o): In function `lws_create_context':
context.c:(.text+0xf03): undefined reference to `lws_feature_status_libuv'
context.c:(.text+0x13c4): undefined reference to `lws_uv_sigint_cb'
lib/libwebsockets.a(server.c.o): In function `lws_context_init_server':
server.c:(.text+0x531): undefined reference to `lws_uv_initvhost'
lib/libwebsockets.a(server.c.o): In function `lws_adopt_descriptor_vhost':
server.c:(.text+0xe21): undefined reference to `lws_libuv_accept'
server.c:(.text+0xef7): undefined reference to `lws_libuv_accept'
server.c:(.text+0xfad): undefined reference to `lws_libuv_accept'
server.c:(.text+0x107d): undefined reference to `lws_libuv_accept'
lib/libwebsockets.a(server.c.o): In function `lws_adopt_socket_vhost':
server.c:(.text+0x117a): undefined reference to `lws_libuv_accept'
lib/libwebsockets.a(server.c.o):server.c:(.text+0x11b2): more undefined references to `lws_libuv_accept' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test-fuzxy.dir/build.make:99: bin/libwebsockets-test-fuzxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/test-fuzxy.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by lws-team** [comment]
Well that's two questions.

1) "why does my server stall".  I dunno, it's your server.  Does the test server we provide stall?

2) "I updated the lws tree and can't compile."  Did you remove the build dir and make a new one?  It looks like your Makefile did not get the memo you are using libuv, it did not build libuv.c.... that's typcially shenanigans around the build dir and CMakeCache.txt / Makefile from old builds.

**Comment by jonowoodward1986** [comment]
1. I will write a test program to spam the test server.
2. Yes I deleted the build folder and done a fresh cmake -DLWS_USE_LIBUV=1 ..

**Comment by lws-team** [comment]
1) You can spam it with `libwebsockets-test-client` (testing ws) or `ab` (testing http).

If it does act badly, make sure LWS_MAX_SMP is set to 1.

2) cmake wants you to tell LWS_WITH_LIBUV=1

**Comment by jonowoodward1986** [comment]
1. I will try this later if 2.2.0 fails.

2. Thanks, did it change at some point? I found LWS_USE_LIBUV when using google.

**Comment by lws-team** [comment]
No it has always been `LWS_WITH_LIBUV` at cmake.

This is going to go into google too... not everything in google is there because it is right.

It's better to have a look near the top of `CMakeLists.txt`... all the options are listed there with a short description.

**Comment by jonowoodward1986** [comment]
It happened on 2.2.0, the service is running at 100% CPU so I will set LWS_MAX_SMP to 1 and test again.

**Comment by jonowoodward1986** [comment]
This still occurs. I will try break it with the test server later after finishing my development.

**Comment by jonowoodward1986** [comment]
> You can spam it with libwebsockets-test-client (testing ws) or ab (testing http).

What do you mean ab?

**Comment by jonowoodward1986** [comment]
I am running the test-server and it is being sent the messages that break my test so will see if  it breaks.

Currentlty it is outputting:

**Comment by lws-team** [comment]
https://httpd.apache.org/docs/2.4/programs/ab.html

What exactly are you sending it?

**Comment by jonowoodward1986** [comment]
some json encoded data.

**Comment by lws-team** [comment]
The message looks like it's rejecting POST data parsing... is what you're sending intended to be valid or just checking it can survive being given it?

**Comment by jonowoodward1986** [comment]
I am posting valid json which I can decode inside the body of my http callback. Before libwebsockets I had a php script handling the post data then inserting the data into a database.

I suspect it will not fail with the test-server, the test is still running.

Is it okay for me to allocate memory and point to the memory from the pss data? I am not using the spa impl. 

[WebServiceLWS_HTTP.txt](https://github.com/warmcat/libwebsockets/files/1156702/WebServiceLWS_HTTP.txt)

**Comment by jonowoodward1986** [comment]
Another difference I have notice between my service and the test server is info.max_http_header_pool = 8 opposed to info.max_http_header_pool = 1

**Comment by lws-team** [comment]
You can (and should) use pss to hold allocations for ws longterm, but for http it's stateless.  If you consider http/1 pipelining, the same wsi may bind to completely different protocol handlers between sets of headers, based on the url each time.  Handling LWS_CALLBACK_HTTP_DROP_PROTOCOL as you do correctly releases the pss stuff, but that's coming inbetween say a GET and POST on the same connection.  It will persist while you send it one big transaction body though for eg, one POST though.

You'll have to debug it, either by aligning the test server with the breaking code until it breaks or vice versa.  The fact spa stuff feels one arg name is unreasonably long might be a clue.

**Comment by jonowoodward1986** [comment]
Should LWS_CALLBACK_HTTP_DROP_PROTOCOL always follow LWS_CALLBACK_HTTP_BODY_COMPLETION?

When handling this POST I would get:

T1 - LWS_CALLBACK_HTTP
T1 - LWS_CALLBACK_HTTP_BODY
T1 - LWS_CALLBACK_HTTP_BODY_COMPLETION

T2 - LWS_CALLBACK_HTTP_DROP_PROTOCOL
T2 - LWS_CALLBACK_HTTP
T2 - LWS_CALLBACK_HTTP_BODY
T2 - LWS_CALLBACK_HTTP_BODY_COMPLETION

T3 - LWS_CALLBACK_HTTP_DROP_PROTOCOL
T3 - LWS_CALLBACK_HTTP
T3 - LWS_CALLBACK_HTTP_BODY
T3 - LWS_CALLBACK_HTTP_BODY_COMPLETION

T representing each time interval a HTTP POST is sent.

Maybe the connection never closes until a new one starts?

**Comment by lws-team** [comment]
DROP_PROTOCOL comes when the connection closes or the protocol binding changes.

If BODY_COMPLETION changes your pss state you should reflect that in your code.

**Comment by jonowoodward1986** [comment]
I just started the service and it had the problem haha.

19:13:09.021|default     |main: Starting WebServiceWS
19:13:09.021|default     |WebService_init
[2017/07/18 19:13:09:0219] NOTICE: Initial logging level 7
[2017/07/18 19:13:09:0220] NOTICE: Libwebsockets version: 2.2.0 jwoodward@Arch-v2.0.0-354-g31b1029
[2017/07/18 19:13:09:0221] NOTICE: IPV6 not compiled in
[2017/07/18 19:13:09:0222] NOTICE: libev support not compiled in
[2017/07/18 19:13:09:0223] NOTICE: libuv support compiled in and enabled
[2017/07/18 19:13:09:0224] NOTICE:  Threads: 1 each 1024 fds
[2017/07/18 19:13:09:0225] NOTICE:  mem: platform fd map:  8192 bytes
[2017/07/18 19:13:09:0226] NOTICE:  Compiled with OpenSSL support
[2017/07/18 19:13:09:0227] NOTICE:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
[2017/07/18 19:13:09:0227] NOTICE: Creating Vhost 'default' port 7682, 3 protocols, IPv6 off
[2017/07/18 19:13:09:0229] NOTICE:  Listening on port 7682
[2017/07/18 19:13:09:0229] NOTICE:  mem: per-conn:          736 bytes + protocol rx buf
[2017/07/18 19:13:09:0230] NOTICE:  canonical_hostname = flora
[2017/07/18 19:13:09:0231] NOTICE:  Using foreign event loop...
19:13:09.023|default     |WebService_run
19:13:09.215|default     |WebServiceLWS_HTTP_callback: LWS_CALLBACK_HTTP_DROP_PROTOCOL in[(null)]

At this point the service is stalled 100% cpu.

I will keep digging tomorrow and share the result.

**Comment by lws-team** [comment]
I'd attach gdb and look where the 100% cpu is going.

**Comment by jonowoodward1986** [comment]
Thanks, I only ever think of gdb when I have a segfault. There was a bad jump in memory.

**Comment by jonowoodward1986** [comment]
I am handling a POST on the BODY and in the BODY completion I am writing all the data associated. I was under the impression I would need to write what I can then set a writable callback to send the rest.

1) It is sending 13477541 bytes, should this work like this?
2) Should I be sending my API data on the BODY COMPLETION?

This is what  I am doing in the BODY COMPLETION:

				if((int)ClibString_size(pss->data_string) > n) {
					applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_WARN, 
						"%s: LWS_CALLBACK_HTTP_BODY_COMPLETION sent[%d] left[%d]", 
						__func__,
						n,
						(int)ClibString_size(pss->data_string)
					);					
					pss->data_string = ClibString_erase_range(pss->data_string, 0, n);	
					goto later;
				} else {
					applog(CLIB_APPLOG_FACILITY_DEFAULT, CLIB_APPLOG_WARN, 
						"%s: LWS_CALLBACK_HTTP_BODY_COMPLETION sent[%d] destroying", 
						__func__,
						n
					);	

					ClibString_destroy(pss->data_string);
					pss->data_string = NULL;
				}


When later is the following :


later:
	lws_callback_on_writable(wsi);
	return 0;

**Comment by lws-team** [comment]
Depending on what else happened it's possible you get the POST and and the body, but right now you can't send anything back on the connection.

The best "network programming" approach to it is have a per-connection state machine of some kind (if your situation is simple, one bit is enough), and if incoming RX affects the state so we want to return something, always ask for a writeable callback.  In the writeable callback, decide what to do based on the per-connection state.

Lws supports rx flow control

```
/**
 * lws_rx_flow_control() - Enable and disable socket servicing for
 *				received packets.
 *
 * If the output side of a server process becomes choked, this allows flow
 * control for the input side.
 *
 * \param wsi:	Websocket connection instance to get callback for
 * \param enable:	0 = disable read servicing for this connection, 1 = enable
 */
LWS_VISIBLE LWS_EXTERN int
lws_rx_flow_control(struct lws *wsi, int enable);
```

This buffers existing rx and disables servicing it until you re-enable rx flow.  So you can use this with the writeable callback and **in** the writeable callback to cleanly make the tx backpressure felt in the rx processing, without unbounded memory allocations from processing rx causing you to have to hold tx that can't be sent right now.
