### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by yjjnls** [warmcat/libwebsockets#972]
I ran the test `test-server-libuv` on windows and used crt debug to detect memory leaks.
Some of the output is:

> Dumping objects ->
> {117} normal block at 0x00000288454F52E0, 32 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {115} normal block at 0x00000288455B6050, 432 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {113} normal block at 0x000002884775AA70, 240000 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {112} normal block at 0x00000288477200B0, 240000 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {111} normal block at 0x00000288476C9CB0, 240000 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {110} normal block at 0x000002884768F2F0, 240000 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

I didn't modify the test and ran it in a foreign loop. Is there real memory leaks, or I made a mistake?
If I ran the same test not using a foreign loop, there's no memory leaks reported.

**Comment by lws-team** [comment]
Thanks... it's simply that the foreign loop close path doesn't call lws_context_destroy2() at the end.  The patch (on master) doing that fixes it.
