### ISSUE TITLE
protocol_lws_meta.c complile error

### ISSUE THREAD

**Issue by mgaiser** [warmcat/libwebsockets#973]
Hi, I'm trying to compile test-server-v2.0 from latest version on Github as described in your documents:

cd /space/libwebsockets; mkdir build; cd build
cmake .. -DLWS_WITH_PLUGINS=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr .
make

Make process ist interrupted due to a compile error:

Building C object CMakeFiles/protocol_lws_meta.dir/plugins/protocol_lws_meta.c.o
/space/libwebsockets/plugins/protocol_lws_meta.c: In function ‘lws_get_channel_id’:
/space/libwebsockets/plugins/protocol_lws_meta.c:115:9: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  return (lws_intptr_t)lws_get_opaque_parent_data(wsi);
         ^
/space/libwebsockets/plugins/protocol_lws_meta.c: In function ‘lws_set_channel_id’:
/space/libwebsockets/plugins/protocol_lws_meta.c:121:34: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  lws_set_opaque_parent_data(wsi, (void *)(lws_intptr_t)id);
                                                     ^

Did I miss something?
System is Ubuntu 16.04 on armhf.

Thanks in advance!

**Comment by lws-team** [comment]
Hmm you should really have `intptr_t` from `stdint.h`.  Lws will use it if it found it.  That should always be the right size integer to hold a whole pointer.

```
-- Performing Test LWS_HAS_INTPTR_T
-- Performing Test LWS_HAS_INTPTR_T - Success
```

Unfortunately there is no way to use C sizeof with the preprocessor to automate it otherwise; trying to build test apps and running them breaks when people build cross.

Do you have `intptr_t` in your toolchain `stdint.h`?

**Comment by mgaiser** [comment]
Running cmake returns among others:
-- Performing Test LWS_HAS_INTPTR_T
-- Performing Test LWS_HAS_INTPTR_T - Success

stdint.h contains:
//...
/* Types for `void *' pointers.  */
#if __WORDSIZE == 64
# ifndef __intptr_t_defined
typedef long int                intptr_t;
#  define __intptr_t_defined
# endif
typedef unsigned long int       uintptr_t;
#else
# ifndef __intptr_t_defined
typedef int                     intptr_t;
#  define __intptr_t_defined
# endif
typedef unsigned int            uintptr_t;
#endif
//...

I'm compiling on my target system.

I also checked sizeof(intptr_t):

#include <libwebsockets.h>
//...
printf("%u\n", sizeof(intptr_t));

and 

#include <stdint.h>
//...
printf("%u\n", sizeof(intptr_t));

returns the same result (4).

**Comment by lws-team** [comment]
Ah damn... it's my fault.

The referenced patch above should sort it.

**Comment by mgaiser** [comment]
Shouldn't the block
```
#if defined(LWS_WITH_ESP8266)
struct sockaddr_in;
#define LWS_POSIX 0
#else
#define LWS_POSIX 1
#endif
```

also go below 

```
#include "lws_config.h"
```
?

**Comment by lws-team** [comment]
;-)

**Comment by lws-team** [comment]
I updated the patch and added a reminder not to put things there.

**Comment by mgaiser** [comment]
OK, build completed without errors now. Thanks!
