### ISSUE TITLE
lwsws startup error

### ISSUE THREAD

**Issue by mgaiser** [warmcat/libwebsockets#974]
Hi,
I successfully built lwsws and set up lwsws configuration as described in README.lwsws.md by copying the config examples to /etc/lwsws/conf and /etc/lwsws/conf.d/localhost.

On startup, lwsws reports
```
lwsws[8734]: Using config dir: "/etc/lwsws"
lwsws: symbol lookup error: lwsws: undefined symbol: lwsws_get_config_globals
```
lwsws is not terminated, but client connection to http://localhost:7681 and https://localhost:7681 is refused.

lwsws_get_config_globals() is declared inside libwebsocket.h. The comment above the declaration says, it depends on cmake setting LWS_WITH_LEJP_CONF enabled. I tried that with no effect.

Inside lws_config.h I find:
```
#define LWS_WITH_LEJP
```

Did I miss something?

**Comment by lws-team** [comment]
It looks like you built `lwsws` at one point, but now the last build you made of `libwebsockets.so` was not configured with the lwsws bits enabled.

Check with `ldd` where your `lwsws` gets `libwebsockets.so` from.

And confirm you did -DLWS_WITH_LWSWS=1 in your build dir with

```
$ cmake .. 2>&1 | grep LWSWS
-- LWS_WITH_LWSWS --> Enabling LWS_WITH_PLUGINS and LWS_WITH_LIBUV
```

**Comment by mgaiser** [comment]
OK, lwsws searches for libwebsockets.so in /usr/lib/arm-linux-gnueabihf, while "make install" copies the lib to /usr/lib. After copying the lib to /usr/lib/arm-linux-gnueabihf, the error message has gone.

**Comment by lws-team** [comment]
> OK, lwsws searches for libwebsockets.so in /usr/lib/arm-linux-gnueabihf

Well, your system prefers that path, it's nothing to do with "lwsws looking".  At the time those libraries are bound by your system, lwsws is not running yet.
