### ISSUE TITLE
lws_service_fd_tsi() : wrong length passed to lws_ssl_capable_read

### ISSUE THREAD

**Issue by pierre-emutex** [warmcat/libwebsockets#977]
When receiving large websocket frames, the variable pending is set from lws_ssl_pending(wsi) and can be much larger than context->pt_serv_buf_size. This creates a crash in libwebsocket when calling SSL_read().

The following patch bounds the length passed to lws_ssl_capable_read().

```

diff -Naur libwebsockets-master/lib/service.c libwebsockets-dev/lib/service.c 
--- libwebsockets-master/lib/service.c	2017-03-29 01:22:19.000000000 +0100
+++ libwebsockets-dev/lib/service.c	2017-07-24 13:47:15.267814320 +0100
@@ -1067,6 +1067,9 @@
 				if (eff_buf.token_len > context->pt_serv_buf_size)
 					eff_buf.token_len = context->pt_serv_buf_size;
 
+                                if (pending > context->pt_serv_buf_size)
+                                        pending = context->pt_serv_buf_size;
+
 				eff_buf.token_len = lws_ssl_capable_read(wsi,
 					(unsigned char *)eff_buf.token, pending ? pending :
 					eff_buf.token_len);

```

**Comment by lws-team** [comment]
This isn't on master?

https://github.com/warmcat/libwebsockets/blob/master/lib/service.c#L1067

...is something quite different.  Does the problem exist on master?

eff_buf is usually used where the original buffer + len may be replaced by an extension, eg, permessage-deflate may take some amount of compressed data and deflate it into some other amount of uncompressed data, usually a larger amount.  Without looking at the code (it's 23:00 where I am) because of that pt_serv_buf_size may not be the right way to solve it.  I seem to remember solving this a while ago.

**Comment by pierre-emutex** [comment]
Maybe the correct fix is on line 1183 (master branch) 

` eff_buf.token = (char *)pt->serv_buf;`

which sets eff_buf to the original buffer even if lws_is_ws_with_ext() evaluates to true in the next line, in which case the length and buffer address in eff_buf seem to be mixed.

**Comment by pierre-emutex** [comment]
To provide more information, here are the buffer addresses and buffer lengths just before the crash.

--- libwebsockets-master/lib/service.c	2017-03-29 01:22:19.000000000 +0100
+++ libwebsockets-dev/lib/service.c	2017-07-24 16:48:33.802362901 +0100
@@ -1064,9 +1064,14 @@
 					eff_buf.token_len = context->pt_serv_buf_size;
 				}
 
+				printf("doing lws_ssl_capable_read %d bytes from pt->serv_buf %p %d / eff_buf %p %d\n", pending, pt->serv_buf, (int)context->pt_serv_buf_size, eff_buf.token, (int)eff_buf.token_len);
+
 				if (eff_buf.token_len > context->pt_serv_buf_size)
 					eff_buf.token_len = context->pt_serv_buf_size;
 
 				eff_buf.token_len = lws_ssl_capable_read(wsi,
 					(unsigned char *)eff_buf.token, pending ? pending :
 					eff_buf.token_len);

doing lws_ssl_capable_read 0 bytes from pt->serv_buf 0x10c3ed0 4096 / eff_buf 0x10c3ed0 8208
doing lws_ssl_capable_read 0 bytes from pt->serv_buf 0x10c3ed0 4096 / eff_buf 0x10c3ed0 8208
doing lws_ssl_capable_read 0 bytes from pt->serv_buf 0x10c3ed0 4096 / eff_buf 0x10c3ed0 8208
doing lws_ssl_capable_read 0 bytes from pt->serv_buf 0x10c3ed0 4096 / eff_buf 0x10c3ed0 8208
doing lws_ssl_capable_read 8208 bytes from pt->serv_buf 0x10c3ed0 4096 / eff_buf 0x10c3ed0 8208
crash

**Comment by lws-team** [comment]
So I didn't get any answer about what version of lws this relates to.

A quick look through the -stable HEADs and top tags from there does not line up with your service.c:1067.  From

```
--- libwebsockets-master/lib/service.c 2017-03-29 01:22:19.000000000 +0100
```

It seems to be a commit from master around the end of March.... but 73e12e7b9360c5ab1a7106b20358ee4ce403adc9 from that date doesn't quite line up either.

There's no way to reproduce given using the test apps + / - a patch.

Why don't you try today's master and see if the problem still exists.

**Comment by pierre-emutex** [comment]
The exact source code version I use is taken from github as follows
    $ git clone https://github.com/warmcat/libwebsockets.git libwebsockets
    $ cd libwebsockets
    $ git checkout -b my_temp_branch v2.2.0

I can reproduce this problem on 2.2.0 quite "easily"
I can reproduce this problem on master only intermittently. It takes me a while to hit it. It is timing dependent. 

I am using libwebsocket client only. the server side is built from nodejs and  'ws' , with compression and ssl enabled.

**Comment by lws-team** [comment]
Well v2.2.0 (why that?  There is a v2.2.2... with fixes) doesn't line up with your patch either.

https://github.com/warmcat/libwebsockets/blob/v2.2.0/lib/service.c#L1064

I'm willing to look at this on master if you can suggest a reasonably convenient way I can try to reproduce it; I understand if it's less probable on master but it's highly preferable to try to fix things there first. If it's client that fails that usually means as small a patch as possible on libwebsockets-test-client, and either something remote that will trigger it or as small a patch as possible on libwebsockets-test-server as well.

**Comment by lws-team** [comment]
I would be very happy to look at this if there's a way to reproduce it with a cogent patch on the test apps.
