### ISSUE TITLE
Bug: client-handshake.c: return value of lws_getaddrinfo46 not checked if ipv6 enabled

### ISSUE THREAD

**Issue by namowen** [warmcat/libwebsockets#978]
concerns master:
if ipv6 is enabled, it accesses directly the result, which is invalid if return value of lws_getaddrinfo46 is != 0. ipv4 does handle this situation.

Proposal:
```
       n = lws_getaddrinfo46(wsi, ads, &result);

#ifdef LWS_USE_IPV6
	if (wsi->ipv6) {
if (n == EAI_SYSTEM) {
	lwsl_err("%s: lws_getaddrinfo46 failed for hostName=%s: EAI_SYSTEM, strerror(%d)=%s\n", __func__,
			ads, errno, strerror(errno));
	cce = "lws_getaddrinfo46 failed";
	goto oom4;
} else {
	lwsl_err("%s: lws_getaddrinfo46 failed for hostName=%s: gai_strerror(%d)=%s\n", __func__, ads,
	       n, gai_strerror(n));
	cce = "lws_getaddrinfo46 failed";
	goto oom4;
}

```

**Comment by lws-team** [comment]
Good catch.... I pushed something slightly different, please check it.

**Comment by namowen** [comment]
Upps, I just realized my mistake. I just copied from somewhere else the else part of if(!n)...and because getaddrinfo always failed...
I prefer the slightly different but far better (=correct) version ;-)
