### ISSUE TITLE
Using only the websocket part without http or tls functionality

### ISSUE THREAD

**Issue by wilhelmmatilainen** [warmcat/libwebsockets#981]
How could I use only the websocket packet handling without any http(s)?
My project is already itself using http(s) and I would like to send and receive through only a single http(s) library. Also, there is the tls library, but I would like to use only a single library my project already has.
Thus, I am trying to get libwebsocket to only handle the websocket layer.
app -> recv data via own interface -> websocket parse packet(s) -> app received a packet
app -> write data -> websocket create packet(s) -> app sends all the created packets via its own interface

**Comment by lws-team** [comment]
lws can 'adopt' a socket or file desc that was accepted by an external listener.

```
typedef enum {
	LWS_ADOPT_RAW_FILE_DESC = 0,	/* convenience constant */
	LWS_ADOPT_HTTP = 1,		/* flag: absent implies RAW */
	LWS_ADOPT_SOCKET = 2,		/* flag: absent implies file descr */
	LWS_ADOPT_ALLOW_SSL = 4,	/* flag: if set requires LWS_ADOPT_SOCKET */
	LWS_ADOPT_WS_PARENTIO = 8,	/* flag: ws mode parent handles IO
					 *   if given must be only flag
					 *   wsi put directly into ws mode
					 */
} lws_adoption_type;

typedef union {
	lws_sockfd_type sockfd;
	lws_filefd_type filefd;
} lws_sock_file_fd_type;

/*
* lws_adopt_descriptor_vhost() - adopt foreign socket or file descriptor
* if socket descriptor, should already have been accepted from listen socket
*
* \param vhost: lws vhost
* \param type: OR-ed combinations of lws_adoption_type flags
* \param fd: union with either .sockfd or .filefd set
* \param vh_prot_name: NULL or vh protocol name to bind raw connection to
* \param parent: NULL or struct lws to attach new_wsi to as a child
*
* Either returns new wsi bound to accept_fd, or closes accept_fd and
* returns NULL, having cleaned up any new wsi pieces.
*
* If LWS_ADOPT_SOCKET is set, LWS adopts the socket in http serving mode, it's
* ready to accept an upgrade to ws or just serve http.
*
* parent may be NULL, if given it should be an existing wsi that will become the
* parent of the new wsi created by this call.
*/
LWS_VISIBLE LWS_EXTERN struct lws *
lws_adopt_descriptor_vhost(struct lws_vhost *vh, lws_adoption_type type,
			   lws_sock_file_fd_type fd, const char *vh_prot_name,
struct lws *parent);
```

It doesn't support 'logical only' ws transport on something external.

lws is primarily designed to be the library doing all the http and ssl as well in one step.

**Comment by Globik** [comment]
Does it mean that I can attach node.js listening port to libwebsockets?

**Comment by lws-team** [comment]
It means you can use lws_adopt_...() to integrate with someone else's listen socket,by having lws take over responsibility for socket fds it accepted.
