### ISSUE TITLE
Any plans to port library to another platform

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#988]
I think library is really one of the best implementation of websockets. Are there any plans to port to another language platform. Lets say Java,
Java supports JNI (Java Native Interfaces) by which you can actually call functions inside C library. As library is true low level of implementation, we can actually use it to maintain optimized connection with server (If used in android as a background connection, will reduce power consumption compared to another libs). I think you can give a little thought on this.

**Comment by lws-team** [comment]
If you want to use it on Android, people have already used it there as part of an NDK project.  There's a contributed script to make it here (untested by me)

https://github.com/warmcat/libwebsockets/blob/master/contrib/android-make-script.sh

**Comment by sacOO7** [comment]
Thank you very much sir. One last question. Can I use it in iOS also? And connection is optimized right?

>

**Comment by lws-team** [comment]
I don't have Android or iOS, so I don't test them.

However we have had people use lws on both Android and iOS.

"connection is optimized" means what?
