### ISSUE TITLE
possible documentation mistake

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#989]
Hey, on page https://libwebsockets.org/lws-api-doc-master/html/group__callback-when-writeable.html#ga9f893903d9de29c3de5631efad7dd9e6
there is:

> lws_callback_on_writable_all_protocol()
> Request a callback for all connections **on same vhost** using the given protocol when it becomes possible to write to each socket without blocking in turn.

while

> lws_callback_on_writable_all_protocol_vhost()
> Request a callback for **all connections** using the given protocol 

Shouldn't it be the opposite?

**Comment by lws-team** [comment]
Thanks.  Yes... I swapped the "on same vhost" over to the other description on v2.2-stable, v2.3-stable and master.
