### ISSUE TITLE
unclear ownership of pointers in structs

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#991]
Hi,
Ownership of pointers and structs seems quite unclear to me, example:

calling `lws_create_vhost` accepts `struct lws_context_creation_info *info`
this structure contains pointers like:
`const struct lws_protocols *protocols;`
`const char *ssl_private_key_password;`
`const char *vhost_name;`
and more.

Who is responsible for those values? I mean does the `lws_create_vhost` copy of all items in creation info struct? Is it safe to pass some std::string::c_str from local variable to the creation info, or does the string have to live longer then the vhost (which is typically the whole process lifetime). And the same with protocols struct and many other members

**Comment by lws-team** [comment]
Generally you are responsible that the things pointed to exist for the lifetime of the thing created.

The logic is user code may already statically / permanently define things.  Then there is no point wasting memory allocating and creating another copy of them.

There are cases where we anyway make copies for some members, for some under some conditions.  But it seems too much of a mess to document exactly what that is, and it's subject to change with the code.

So "generally you are responsible that the things pointed to exist for the lifetime of the thing created."
